### ISSUE TITLE
Linux rc1 binaries do not contain listed option in release notes

### ISSUE THREAD

**Issue by padrino121** [ethereum-mining/ethminer#100]
Downloaded the binary, the code with cuda-parallel-hash not in the Linux release, did not try the others but assume its in at least Windows given the release comment on 0.11rc1 on trying cuda-parallel-hash

**Comment by AstarothPoD** [comment]
You may have copy pasted from the --help, which contains a typographic error, like I did. Are you sure you tried cuda-parallel-hash, not cude-parallel-hash?

**Comment by padrino121** [comment]
Thanks for the note, I guess I didn't look too close, that was in fact the issue..
