### ISSUE TITLE
ethminer can not find the RX 570 with the PCI Express 1x to 16x riser card plugged in 1X slot

### ISSUE THREAD

**Issue by bitflying** [ethereum-mining/ethminer#1005]
ethminer can not find the RX 570 with the PCI Express 1x to 16x riser card plugged in 1X slot
--------------------------------------------------------------------------------------------

Any guy can advise me why?

My computer has installed 3 * RX 570 with Z270-A mainboard (only 2*16X slots), 3 * 1x to 16x risers and running on ubuntu server 16.04.3, 

For first       RX 570, 1x to 16x riser is plugged in the PCIe 16X slot.
For second RX 570, 1x to 16x riser is plugged in the PCIe 16X slot.
For third      RX 570, 1x to 16x riser is plugged in the PCIe 1X slot.

As result, the first and second RX 570s worked good, but the ethminer can not find the third RX 570.

try with command: 
  ethminer --list-devices
Result:
 
Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[0] [0] gfx803
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 8589934592
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[0] [1] gfx803
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 8589934592
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

only find two RX 570s

try with command: 
  rocm-smi
Result:

  ---- ROCm System Management Interface  
 GPU  Temp    AvgPwr   SCLK     MCLK     Fan      Perf    SCLK OD
  0   73.0c   105.134W 1270Mhz  2000Mhz  47.84%   auto      0%
  1   70.0c   104.155W 1270Mhz  2000Mhz  44.71%   auto      0%
  2   33.0c   35.189W  300Mhz   2000Mhz  34.9%    auto      0%
  ---- End of ROCm SMI Log    

That means Ubunut can find three RX 570s and the ethminer can only find two instead of three.

Something wrong?

My computer configuration:

ASUS's PRIME Z270-A   
3  *  Dataland(PowerColor) RX570 8G X-Serial 
3  *  PCI Express 1x to 16x Card
Ubuntu 16.04.3 LTS Server AMD64 
ethminer for linux - 0.14.0.dev3

**Comment by cdarken** [comment]
Did you try `clinfo` ? How many cards does it find?

**Comment by tribalpixel** [comment]
hello i never tried this mobo... 
 
but have you double check your bios settings?
PCIEX16_1 Link Speed (for both Z270-A & Z270-P) to **Gen2.** 
and the PCIEX16_2 Link Speed for the Z270-A boards.

[maybe this link can help you](https://blockoperations.com/motherboard-bios-settings-for-asus-z270-a-and-z270-p/)

**Comment by ddobreff** [comment]
This is because you are using rocm ocl stack. It requires pci atomics which only PCIe gen.3 x8/x16 support. Try removing rocm stack and install amdgpu-pro using —opencl=legacy

**Comment by bitflying** [comment]
Thanks ddobreff, your advice is great!

I uninstalled  amdgpu-pro and re-install with "./amdgpu-pro-install -y --opencl=legacy --headless ".
Now, it worked fine.

Thanks guys!
