### ISSUE TITLE
0.15.0.dev1 and HiveOS issue

### ISSUE THREAD

**Issue by Urik26** [ethereum-mining/ethminer#1006]
![2018-04-14 14 54 03](https://user-images.githubusercontent.com/17965727/38767953-258bdac4-3ff4-11e8-9a27-bbf554f906e2.png)

**Comment by Hakkk2002** [comment]
-P 1 ?

**Comment by Urik26** [comment]
13 version worked only with that key.

**Comment by smurfy** [comment]
``-P`` is a new param, drop it and you do not get that error.
