### ISSUE TITLE
Current vs Reported hashrate

### ISSUE THREAD

**Issue by Kecedar** [ethereum-mining/ethminer#1008]
Hi,

please give me just short clarification.
In ethermineI have reported hashrate lower then current hashrate, which one is more important and whih is related with real mining in the pool?

Thanks a lot

**Comment by AndreaLanfranchi** [comment]
Reported Hashrate is the speed your miner tells the pool
Effective Hashrate is the speed the pool calculates using valid submitted shares and current jobs difficulty

Generally speaking Effective Hashrate and Reported Hashrate should overlay on a long mining run (say 18/24 hours)

**Comment by Kecedar** [comment]
Thanks a lot

2018-04-15 13:30 GMT+02:00 Andrea Lanfranchi <notifications@github.com>:
