### ISSUE TITLE
# char not allowed in worker name

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ethereum-mining/ethminer#1009]
0.15.0.dev1 (latest)
Launch with '#' in workername

` -P stratum+tcp://<myetheraddress>.BG01R01#01@eu1.ethermine.org:4444`

Causes this never ending loop.
Hash char (#) is probably parsed as separator ?

```
 ℹ  18:24:45|stratum |  Retrying in 1 ...
  ✘  18:24:46|stratum |  Could not resolve host <ethaddress>.BG01R01:0, Host not found (authoritative)
  ℹ  18:24:46|stratum |  Disconnected from <ethaddress>.BG01R01

```

**Comment by jean-m-cyr** [comment]
err... I don't anticipate making any further contributions.

**Comment by AndreaLanfranchi** [comment]
> err... I don't anticipate making any further contributions.

Quite sorry to hear that. It's a pity.

**Comment by megapearl** [comment]
Maybe you can try %23 as # in your url...
source: https://en.wikipedia.org/wiki/Percent-encoding

**Comment by AndreaLanfranchi** [comment]
Superseded.
