### ISSUE TITLE
Build on Windows failed with CMake Error at cmake/HunterGate.cmake:82

### ISSUE THREAD

**Issue by fbehrens** [ethereum-mining/ethminer#101]
Hi
I want to build on Windows 10, 

What i did?
* clone `ethminer`
* download `cmake-3.8.2-win64-x64`, extract and add to path
* follow instructions in `readme`

I am getting the following error:
```
> cmake ..
-- Building for: NMake Makefiles
-- [hunter] Initializing Hunter workspace (435b09a4eec7fd58486bfb61efb1044ddb85c0f0)
-- [hunter]   https://github.com/ruslo/hunter/archive/v0.18.57.tar.gz
-- [hunter]   -> C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a
The system cannot find the file specified
CMake Error: Generator: execution of make failed. Make command was: "nmake" "/NOLOGO"

[hunter ** INTERNAL **] Build project failed
[hunter ** INTERNAL **] [Directory:C:/tools/cpp-ethereum]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at cmake/HunterGate.cmake:82 (message):
Call Stack (most recent call first):
  cmake/HunterGate.cmake:92 (hunter_gate_wiki)
  cmake/HunterGate.cmake:345 (hunter_gate_internal_error)
  cmake/HunterGate.cmake:498 (hunter_gate_download)
  CMakeLists.txt:10 (HunterGate)


-- Configuring incomplete, errors occurred!
```

It is not clear for me if i need to install `hunter`, guess not i have some files dowloades at `C:\.hunter\_Base\Download\Hunter\0.18.57\435b09a`.

Please advise

**Comment by chfast** [comment]
Do you have Visual Studio installed?

**Comment by fbehrens** [comment]
Hell no, 
will install `VS2017 Community` and try again.
Guess it is a prerequisite, right ?

**Comment by chfast** [comment]
If you are not interested in developing ethminer, just download the binaries from https://github.com/ethereum-mining/ethminer/releases.

**Comment by fbehrens** [comment]
Thanks for support.  i didn't find the binaries as I first landed in https://github.com/Genoil/cpp-ethereum/ , which seems to be a mirror. You may want to delete it and link to here?

**Comment by chfast** [comment]
I cannot delete someone's else fork.
But I plan to update the README to include information where to find the binaries. Any feedback welcome.

**Comment by coderpradp** [comment]
@chfast I'm having same error. Is visual studio mandatory? Aren't there any alternative to Visual Studio?

**Comment by coderpradp** [comment]
@chfast @fbehrens Hey guys I'm having same error. I have MS Build Tools installed but keep getting same error. Do I need to install full Visual Studio package for the build to work?
