### ISSUE TITLE
Newline needed at the end of JSON-RPC server before command is processed (Incompatible with Claymore's JSON-RPC API)

### ISSUE THREAD

**Issue by jkcdarunday** [ethereum-mining/ethminer#1010]
As shown in the following examples. The JSON-RPC API server of ethminer seems to be requiring a newline at the end before sending a response. This causes JSON-RPC client libraries such as jayson for node.js to not receive any response because ethminer waits for a newline character. 

##### With newline at the end (echo without -n)
```
skeithc@freedom ~ % echo '{"method":"miner_getstat1","jsonrpc":"2.0","id":"test"}' | nc 127.0.0.1 3333
{"id":"test","jsonrpc":"2.0","result":["0.15.0.dev1","4","5815;0;0","5815","0;0;0","off","66;47","censored.pool:1234","0;0;0;0"]}
```

##### Without newline at the end (echo with -n)
```
skeithc@freedom ~ % echo -n '{"method":"miner_getstat1","jsonrpc":"2.0","id":"test"}' | nc 127.0.0.1 3333
// no response here
```

##### With newline at the end (echo without -n)
```
skeithc@freedom ~ % echo '{"method":"miner_getstat1","jsonrpc":"2.0","id":"test"}' | nc 127.0.0.1 3333
{"id": -1, "result": ["11.6 - ETH", "1", "4785;0;0", "4785", "0;0;0", "off", "60;39", "censored.pool:1234", "0;0;0;0"], "error": null}
```
##### Without newline at the end (echo with -n)
```
skeithc@freedom ~ % echo -n '{"method":"miner_getstat1","jsonrpc":"2.0","id":"test"}' | nc 127.0.0.1 3333
{"id": -1, "result": ["11.6 - ETH", "1", "4785;0;0", "4785", "0;0;0", "off", "60;39", "censored.pool:1234", "0;0;0;0"], "error": null}
```

**Comment by AndreaLanfranchi** [comment]
Hard to say which is "more" compliant to standard.
From my personal point of view :
- all stratum implementation are a ndjson over jsonrpc (thus with line termination)
- ethminer's API implementation follows the same rules
- if claymore makes no difference about termination line (with or without you always get the response) why not simply assume you always need to append \n ? Your compatibility is already found.

Closed for now but feel free to reopen if it does not make sense to you.
