### ISSUE TITLE
ethminer 0.15 dev3 - 10% to 15% less accepts

### ISSUE THREAD

**Issue by satori-q3a** [ethereum-mining/ethminer#1017]
Compared to 14.0 rc4 and 15.0 dev2, looks like 15.0 dev3 is producing 10 to 15% less accepts.  It might be the nanopool difficulty, but once I switch back from 15.0 dev3 to dev2, the accepts rate return to what was expected.

Rigs were using a mix of nvidia 1070, 1060 and 1050 ti.
Nvidia 391.32 on windows 10, update april 2018.

**Comment by igy137** [comment]
+1

**Comment by chfast** [comment]
The .dev3 only changes OpenCL code.

**Comment by AndreaLanfranchi** [comment]
Can you perform a test with two rigs loaded with different versions of 0.15.x but in the **same** period of time say of 4 hours ?

**Comment by satori-q3a** [comment]
I'll let the miner rig run 15.0 dev7 for a day, as I'm now seeing expected accept rates.

I only have the single 225 MHash miner rig, but it's an i3 with 8 gigs so it should handle two instances of different ethminers with the gpus split between them.  If dev7 acts strange, I'll do this test.
