### ISSUE TITLE
ethminer -Z: Manager has no connections defined!

### ISSUE THREAD

**Issue by karmus89** [ethereum-mining/ethminer#1018]
Hello!

I'm trying to run ethminer in a computing cluster running on UNIX. The GPU I'm currently testing on is NVIDIA Tesla P100-PCIE-12GB. While I have problems with finding solutions when connected to a pool, I suspect that the problem has to do with some kind incompatibility between the ethminer and the hardware setup. 

Thus, I'm trying to get this command to work:

``ethminer -Z``

The output of the command is:

![img](https://user-images.githubusercontent.com/17722707/39083599-1d8ff636-456f-11e8-8990-ae13b1b442f5.png)

The version of the ethminer is visible on the image. I have copied and extracted the *.tar.gz to the host system and am able to run it there. I am able to run `ethminer -M` and gain proper-looking information on the H/S. I cannot use sudo.

Any help is appreciated!

**Comment by AndreaLanfranchi** [comment]
Please post full command line arguments.
It seems like you're not indicating any pool.

**Comment by karmus89** [comment]
That is my full command line argument. I did not know a pool was required. The help for the simulation states:¨

```
Simulation mode:
    -Z [<n>],--simulation [<n>] Mining test mode. Used to validate kernel optimizations. Optionally specify block number.
```

It wasn't thus apparent to me, that a connection to a live pool was required. I sincerely thought this was just for offline use.

**Comment by AndreaLanfranchi** [comment]
Seems like that Poolmanager has a missing check agains -Z switch and has NOT to check for active pools.

/CC @chfast

**Comment by karmus89** [comment]
When running

``ethminer -U -Z -P -P stratum+tcp://<wallet>D@eu1.ethermine.org:4444``

I get an error:

``Mixed stratum and getwork endpoints not supported.``

**Comment by AndreaLanfranchi** [comment]
Suggest not to use -Z and do run test against live mining pool.
This should give you more accurate results.

**Comment by karmus89** [comment]
Well that’s thr actual problem I’m trying to troubleshoot, as running against a live pool results in no solutions and thus no shares found. With the benchmark handle I’m able verify that there are hashes calculated, but the only way to tap into finding solutions would through the simulation handle. So this is a dead end atm.

**Comment by chfast** [comment]
I noticed the issue too. This is useful feature for me when testing new improvements... Maybe I'll find time to fix it someday...
