### ISSUE TITLE
Why hashrate went from 32 mh/card on 4x1070 down to 26mh/s on 6x1070. What to do?

### ISSUE THREAD

**Issue by MichaelA2014** [ethereum-mining/ethminer#102]
Hello Pawel and all others. I started using ethminer when I had 4 gpu setup (4x 1070) and average was 32 mh per card give or take..... Now I have 6 1070's and i hardly get 26 mh with the same settings. Same overclock and everything.
I was wondering if I need to adjust some parameters?

Thank you

**Comment by tex6246** [comment]
@MichaelA2014  have you tried changing the --cuda-parallel-hash # to either 2, 4,or 8?  they say this can help with hashrates for various cards

**Comment by MichaelA2014** [comment]
Should I just add that parameter to the command line ? I remember reading that by default it's setting of 4. I will try to put that variable and see how it goes. Thank you for pointing it out.

**Comment by MichaelA2014** [comment]
tried with all the available modes. The only boost I get is with either default (4) or 8. When trying 7,6,5,3,2 or 1 the hashrate drops by ~20-25% so I decided to leave it alone and let it churn out.

**Comment by jimmykl** [comment]
@MichaelA2014 Are you still experiencing the reduced performance with 6 cards?

When I added more cards to my rigs I found I had to up the power limit on my overclocks a bit to keep the same performance.

Is your power supply up to the job of 6 1070s? I'd recommend 1200W as a good capacity. 

Also have you assigned more virtual memory for Windows? Not sure if that can drop hashrate or not but it can't hurt trying.

**Comment by MichaelA2014** [comment]
@jimmykl I have two 650W supplies ewach feeding three cards. The total draw at the wall is 870W which is within my margins. If I will add two or three more cards I will add another PSU. 

I haven't changed OC settings per card. I set "copy settings to similar hardware" tick in the settings.

My settings are memory +550  core -150 and I set the custom fan settings to keep the cards cool around 60-62celsius.
I assigned 16gb minimum and 32gb maximum page file so it's 32gb max

**Comment by jimmykl** [comment]
@MichaelA2014 Sounds like you have plenty of power overhead and virtual memory overhead.

Is your performance still down at 100% power limit?

What happens if you remove the core underclock and leave it at zero?

**Comment by derubm** [comment]
check each card with the same settings for GPU / ram Frequency, might be that one (or two ) of your cards needs dfferent setting the the other ones. they did work as a setup of 4, so i would look into the 2 new cards, are they the same brand ? do they have the same GDDR5 on board ? Run it with dev version 12 to see if all cards run at slower speed or only one or two.

**Comment by mreid2005** [comment]
Check the difficulty charts on CoinWarz see if by chance it coincided with a difficulty jump.

**Comment by dafyk** [comment]
And dont forget to check if your cards are running in P0 state. I assume you are on windows, after adding new cards driver installation resets your nvidia profile.

**Comment by nickotoss** [comment]
** check your power management advanced settings maybe you have it set to the defaul where your hard drive goes to sleep this was my problem I just put it too 100000000 min and everything works smoothly now **

**Comment by DeadManWalkingTO** [comment]
GTX1060 +150/+500/65%TDP @ 23-24MHs

1. Try Update Drivers.
Download and install the latests.

2. Try Update Ethminer.
Download (or beter build) the latest.

3. Try use -U for CUDA devices.
CUDA Hardware Test Launch Command:
`ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.issue102`

4. Try to change P2 State and Power managment mode.
You can use [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW).
For the best mining hashrate choose from sector "5 - Common":
    - CUDA - Force P2 State (Set to "Off")
    - Power managment mode (Set to "Prefer maximum performance")

5. Try Tweak Win10.
You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) (#695).

6. Try Optimize/Overclock GPUs. 
You can use [MSI Afterburner](https://www.msi.com/page/afterburner) for GPU OverClock/Optimize. 

7. Try use a WatchDog
You can use [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) (#735).

Please feedback.
Thank you!

**Comment by AndreaLanfranchi** [comment]
No feed back.
