### ISSUE TITLE
ver 0.15 - not working without --stratum protocol

### ISSUE THREAD

**Issue by Teressss** [ethereum-mining/ethminer#1020]
As --stratum protocol is deprecated in 0.15, I am not able to connect to my pools (Nanopool, 2miners). On 14rc4 when I set --stratum protocol 1 my connection to pools is without problem, but this option is in 0.15 not available. So how to achieve ver0.15 to connect? Thanks

**Comment by AndreaLanfranchi** [comment]
--stratum-protocol is still there but in a sligthly different form.

Take a look at the help

```
    -P URL Specify a pool URL. Can be used multiple times. The 1st for for the primary pool, and the 2nd for the failover pool.
        URL takes the form: scheme://user[:password]@hostname:port.
        for getwork use one of the following schemes:
          http
        for stratum use one of the following schemes:
          stratum+ssl stratum+tcp stratum+tls stratum+tls12 stratum1+ssl stratum1+tcp stratum1+tls stratum1+tls12 stratum2+ssl stratum2+tcp stratum2+tls stratum2+tls12
        Example: stratum+ssl://0x012345678901234567890234567890123.miner1@ethermine.org:5555

```

This means that old --stratum-protocol 0 (default) is equivalent to new "-P stratum+tcp://"; --stratum-protocol 1 is equivalent to new "-P stratum1+tcp://" and finally --stratum-protocol 2 is equivalent to new "-P stratum2+tcp://"

**Comment by Teressss** [comment]
With your comment it is more clear, but be honest - from the internal help - who can understand what devs meant by stratum1 or stratum2? Ethminer is great, but is lacking a proper documentation etc...

**Comment by AndreaLanfranchi** [comment]
Please remember ethminer is great and is open-source. Not a single dime is requested by developers for their work and they're gifting us with their free time. If you want to a full-stack easy to play-with miner with proper documentation ask to someone who has a paid version: in this case you can claim a fully exhaustive documentation and support.

We're all here to help for free !!!

**Comment by AndreaLanfranchi** [comment]
Ethminer is a great open-source project. It's not meant to be for developers only (as they made it publicly available) but also is not meant for people who claim full commercial support.

>I have no problem to pay for "great" ethminer if also things around would be great.

This is the tradeoff among FOSS vs commercial software.
**There is always something to pay**: with ethminer you have to pay some time reading and understanding (also the code). With commercial software you pay (money) for direct support provided by the developer.

**Comment by AndreaLanfranchi** [comment]
As we're going off-topic ... I invite you to close the issue.

**Comment by Teressss** [comment]
again: "I don't understand why it is so big problem to document changes made"... :( I am really sad of this behaviour.

**Comment by Teressss** [comment]
Yes, closed it, the same way I have to sadly give up using ethminer.

**Comment by AndreaLanfranchi** [comment]
It's up to you to read them.
Every commit on github project is documented and keeps track of every change made.
Github is the largest changelog you can have,

**Comment by AndreaLanfranchi** [comment]
> Yes, closed it, the same way I have to sadly give up using ethminer.

Sorry to hear that.
You will loose an opportunity to use a miner which plays fair.

**Comment by Teressss** [comment]
But I can't use it, because version 15 is simply not working for me. 

You say to read every commit?? Read whole 13 thousands? Quite ach even open source project on releases page have written changes between latest vesrion and previous. What has there ethminer? "Bump version: 0.15.0.dev3 → 0.15.0.dev4" Yes that says all. No I know exactly what has changed...

**Comment by AndreaLanfranchi** [comment]
> But I can't use it, because version 15 is simply not working for me.

Why you say that ?
Didn't you get proper help for your "understanding" problems ?
What else is "_not working for you_ ?"

**Comment by AndreaLanfranchi** [comment]
You're not praying for help. Your interacting with a community.

Believe it or not the FOSS world is entirely made up of people asking for clarifications and other people providing answers on a voluntary basis.
This is the world of open-source software.

If you can handle it you will be happy and, as a plus, you will enlarge your knowledge.

If not ... you're in the wrong place and better deal with some "Windows Style Next->Next->Next" install and usage solution.

Please close the issue with the "Close" button.
Thank you.

**Comment by Teressss** [comment]
I am only Mac user, BSD, Linux admin, builded and configured dozens of servers, but from what you say, I am just an idiot who only can operate only with stupid Windows. Well. You must be right. Thanks for an expierence and life lesson...
