### ISSUE TITLE
-RH not send hashrate to pool and work stratum on dwarfpool

### ISSUE THREAD

**Issue by BoriZka67** [ethereum-mining/ethminer#1023]
win 10, rx 580 8Gb

ethminer.exe -HWMON 1 -RH --farm-recheck 200  --cl-local-work 256 --cl-global-work 65536 --cl-parallel-hash 2 --cl-kernel 1 --opencl-platform 1 -G -P stratum1+tcp://0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxx@eth-ru.dwarfpool.com:8008

0.15 dev 3 (and dev 4) on pool not send hashrate, and please, all right in my bat file for best result?

**Comment by tribalpixel** [comment]
hello,
not sure about this, as i see in 0.15 it's deprecated
but have you tried with `-SP 1` ?

`./ethminer.exe --help` is your friend ;)

```
 -SP, --stratum-protocol <n> (deprecated) Choose which stratum protocol to use:
        0: official stratum spec: ethpool, ethermine, coinotron, mph, nanopool (default)
        1: eth-proxy compatible: dwarfpool, f2pool, nanopool (required for hashrate reporting to work with nanopool)
        2: EthereumStratum/1.0.0: nicehash
```

**Comment by AndreaLanfranchi** [comment]
Confirmed.

**Comment by AndreaLanfranchi** [comment]
Found problem.
Method requires "worker" element for all flavours.

**Comment by AndreaLanfranchi** [comment]
Solved in 
* 0.14.rc7
* 0.15.dev6
