### ISSUE TITLE
ethminer.exe  Positive Hits in Virusscan.org

### ISSUE THREAD

**Issue by sirplus51** [ethereum-mining/ethminer#1032]
ethminer-dbg-0.14.0rc5-Windows.zip 
http://r.virscan.org/language/en/report/c9cc44a49f6b15781378de3dccbec668
File Name :	 ethminer.exe
File Size :7260672 byte
2 Positives reported

ethminer-0.14.0rc5-Windows.zip 
http://r.virscan.org/language/en/report/df9e8cce965a034a57be04b72330037a
File Name :	ethminer.exe
File Size :7303680 byte <--Larger Package (shouldn't it be the same size?)
3 Positives reported <--Different result (shouldn't it be the same for both?)

Both files reported to contain Trojan Gen:Variant.Application.Razy.283372 by the same scanner
Razy is a pretty nasty Trojan providing remote access...
Also
Only the smaller one contained  PUF.CoinMiner<--Shouldn't it be in both

Not claiming any significance to these results.
Perhaps someone with more knowledge can assess further as it raised some questions for me.
I also tweeted Paweł Bylica direct.

**Comment by MariusVanDerWijden** [comment]
This is propably a false positive. Try recompiling from source and checking the hashes
