### ISSUE TITLE
Warning: -S is deprecated. Use the -P parameter instead.

### ISSUE THREAD

**Issue by erkange** [ethereum-mining/ethminer#1033]
Why i get this warning?
I use newest version ethminer 0.14.0rc5

my bat file is like this;

```
ethminer.exe -HWMON -RH -U --exit -S eu1.ethermine.org:4444 -O 0xbc1d0170aa1edd53a7370ebe1c8526b1b056e03a.Rig001
```

**Comment by AndreaLanfranchi** [comment]
ethminer.exe --help is your friend

`ethminer.exe -HWMON -RH -U --exit -P stratum+tcp://0xbc1d0170aa1edd53a7370ebe1c8526b1b056e03a.Rig001@eu1.ethermine.org:4444 `

**Comment by ut9ea** [comment]
what is the bat
t file for nanopool
with the use of mail ?
ethminer.exe --farm-recheck 200 -G -S eth-eu1.nanopool.org:9999 -O 0xxxxxxxxxxxxxxxxxxxxxx.rig1/ut9ea76@gmail.com -RH --work-timeout 500 --cl-local-work 256 --cl-global-work 65536 --cl-kernel 1 --cl-parallel-hash 2 --report-hashrate -SP 1

**Comment by erkange** [comment]
Hi AndreaLanfranchi,

our codes gives below error.

`Invalid argument: -P`

**Comment by chfast** [comment]
URL encode your rig name: 0xxxxxxxxxxxxxxxxxxxxxx.rig1/Fut9ea76@gmail.com` -> 
`0xxxxxxxxxxxxxxxxxxxxxx.rig1%2Fut9ea76%40gmail.com`

**Comment by ut9ea** [comment]
to connect to the nanopool
required vorker and email
ethminer.exe --farm-recheck 200 -G -S eth-eu1.nanopool.org:9999 -O YOUR_ADDRESS.YOUR_WORKER/YOUR_EMAIL

**Comment by ut9ea** [comment]
t does not work .rig1%2ut9ea76%40gmail.com
on the server statistics will recognize
rig1ut9ea760gmail.com

**Comment by chfast** [comment]
In the bat script you have to double the `%` sign: `rig1%%2Fut9ea76%%40gmail.com` because `%` is a special character.
