### ISSUE TITLE
error in URL user causes `No work` loop endlessly

### ISSUE THREAD

**Issue by SnowLeopard71** [ethereum-mining/ethminer#1036]
version 0.14.0rc6 (build from source release)
I made simple mistake in my sh wrapper script building my SERVER variable for the new -P format and added extra dots.  To take the example from the help output:
`stratum+ssl://.0x012345678901234567890234567890123.miner1.@ethermine.org:5555`  
Below is the log output from failed run followed by the run with proper username. 
My first guess is ethminer is not handling the server response from an invalid user -- the output from successful run has `Authorized worker` right after the `Subscribed to stratum server` line whereas failed run goes into the `No work. Pause for 3 s.` without having been _Authorized_

```
ℹ  19:20:31|stratum |  Connected to us1.ethermine.org  [18.219.59.155:5555]
  ℹ  19:20:31|stratum |  Spinning up miners...
  ℹ  19:20:31|cuda-0  |  No work. Pause for 3 s.
  ℹ  19:20:31|cuda-1  |  No work. Pause for 3 s.
  ℹ  19:20:31|cuda-2  |  No work. Pause for 3 s.
  ℹ  19:20:31|stratum |  Subscribed to stratum server
  ℹ  19:20:34|cuda-0  |  No work. Pause for 3 s.
  ℹ  19:20:34|cuda-1  |  No work. Pause for 3 s.
  ℹ  19:20:34|cuda-2  |  No work. Pause for 3 s.
  m  19:20:36|ethminer|  Speed   0.00 Mh/s    gpu/0  0.00 0C 0%   gpu/1  0.00 0C 0%   gpu/2  0.00 0C 0%   [A0+0:R0+0:F0] Time: 00:00
  ℹ  19:20:37|cuda-0  |  No work. Pause for 3 s.
  ℹ  19:20:37|cuda-1  |  No work. Pause for 3 s.


  ℹ  19:22:43|stratum |  Connected to us1.ethermine.org  [18.219.59.155:5555]
  ℹ  19:22:43|stratum |  Spinning up miners...
  ℹ  19:22:43|cuda-0  |  No work. Pause for 3 s.
  ℹ  19:22:43|cuda-1  |  No work. Pause for 3 s.
  ℹ  19:22:43|cuda-2  |  No work. Pause for 3 s.
  ℹ  19:22:43|stratum |  Subscribed to stratum server
  ℹ  19:22:43|stratum |  Authorized worker  <hidden>
  ℹ  19:22:43|stratum |  New pool difficulty:  4.0000 gigahashes
  ℹ  19:22:43|stratum |  New job #cc7062b8…   us1.ethermine.org [18.219.59.155:5555]
  ℹ  19:22:46|cuda-0  |  Initialising miner 0
```

**Comment by SnowLeopard71** [comment]
If I'm not mistaken, the requests and responses are supposed to match up by `id` -- the request to authorize the miner is sent with `id` 3, however the error response from the server has `id` 999:
    Sent: `{"id": 3, "method": "mining.authorize", "params": [".0x0123456789abce.miner1.",""]}`
    Recd: `{"id":999,"jsonrpc": "2.0","result": false,"error": "Invalid user provided"}`
Adding `case 999:` to EthStratumClient.cpp at line 472 (to go with `case 3:`) makes it see the response properly, but the ethminer still goes into the `No work` loop without exiting.  Putting `exit(1)` after the `disconnect()` does not seem to make it terminate -- it loops anyway.

**Comment by AndreaLanfranchi** [comment]
Unfortunately this should not happen as the pool should reply to the same message id being sent by the client. I will try to manage this unfortunate situation but, I reiterate, this is a bad implementation on pool's side.

**Comment by AndreaLanfranchi** [comment]
Nevertheless I must say that a better parsing of command line arguments might be needed
