### ISSUE TITLE
ethminer help file, if needed

### ISSUE THREAD

**Issue by erkange** [ethereum-mining/ethminer#1037]
If you want to get updated help output, create a bat file with these codes.
and put it in same folder with ethminer.exe

```
ethminer.exe --help
pause
```

**Comment by trtw89** [comment]
offtop: in version 14.rc5 i have max 10 stale shares, today i test 14.rc6 and stale shared now up to 21

**Comment by AndreaLanfranchi** [comment]
Not an issue. 
Simple very basic usage.
