### ISSUE TITLE
Warning: -S is deprecated. Use the -P parameter instead. for nanopool with the use of mail

### ISSUE THREAD

**Issue by ut9ea** [ethereum-mining/ethminer#1039]
what is the bat
file for nanopool
with the use of mail ?
ethminer.exe --farm-recheck 200 -G -S eth-eu1.nanopool.org:9999 -O 0xxxxxxxxxxxxxxxxxxxxxx.rig1/ut9ea76@gmail.com -RH --work-timeout 500 --cl-local-work 256 --cl-global-work 65536 --cl-kernel 1 --cl-parallel-hash 2 --report-hashrate -SP 1

**Comment by AndreaLanfranchi** [comment]
Stop spamming the same question over and over again
If none responded yet there is no need to insist.
Same as #1033
