### ISSUE TITLE
stratum Read response failed

### ISSUE THREAD

**Issue by papampi** [ethereum-mining/ethminer#104]
I cant connect to any servers and gives me this error on 2 windows 10 pc,
any way to solve it ? 

```
21:57:31|main Connecting to stratum server asia1.ethermine.org:4444
21:57:31|stratum Connected to stratum server asia1.ethermine.org : 4444
21:57:31|stratum Starting farm
21:57:50|stratum Read response failed: The semaphore timeout period has expired
21:57:50|stratum Reconnecting in 3 seconds...
21:57:53|stratum Connecting to stratum server asia1.ethermine.org:4444
21:57:53|stratum Connected to stratum server asia1.ethermine.org : 4444
21:58:12|stratum Read response failed: The semaphore timeout period has expired
21:58:12|stratum Reconnecting in 3 seconds...
```

**Comment by JHGitty** [comment]
I think you have an issue with your internet connection or pool.

a) Do you use a proxy which is blocking or filtering your data?
b) Do you use any internet connection which does not allow communication on port 4444?
c) Did you try to use another pool (= another pool address)?

**Comment by papampi** [comment]
Thanks for reply
I found out that it was my asus router "vulnerability protection" that was blocking it
I can now connect to all pools but nicehash.

**Comment by jimmykl** [comment]
Glad you got it figured out. Can you please close this issue?
