### ISSUE TITLE
Suggestion: use Coverity Scan / Clang-Tidy / other tools to find code problems

### ISSUE THREAD

**Issue by unquietwiki** [ethereum-mining/ethminer#1045]
Given the list of issues here; and the sensitivity of the work being done (financial & computer security); it might make sense to have some code linting and static analysis as part of the build and fix process.

- https://scan.coverity.com/projects
- http://clang.llvm.org/extra/clang-tidy/
- https://github.com/danmar/cppcheck
- https://github.com/JossWhittle/FlintPlusPlus

**Comment by XhmikosR** [comment]
https://github.com/ethereum-mining/ethminer/tree/coverity

**Comment by chfast** [comment]
I'd like to have clang-tidy, but never had it integrated in CI...

**Comment by unquietwiki** [comment]
@chfast I found this. Might help? https://www.reddit.com/r/cpp/comments/7obg9p/how_do_you_use_clangtidy/

**Comment by chfast** [comment]
Yes, thanks.
However I prefer it to be a part of CMake directly. I will try to add it.

**Comment by AndreaLanfranchi** [comment]
@chfast ... still relevant ?

**Comment by chfast** [comment]
Basics done in #1715 and #1721.
@XhmikosR was working on coverity.

**Comment by chfast** [comment]
Basics done in #1715 and #1721.
@XhmikosR was working on coverity.

**Comment by XhmikosR** [comment]
The thing is...

1. the current coverity version does not seem to work with the latest MSVC
2. I couldn't make Travis work
3. There's like zero support from coverity

So, I'd say we should just leave the branch there in case someone else wants to take a stab at it later.
