### ISSUE TITLE
Cli loop locks PoolManager's thread

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ethereum-mining/ethminer#1053]
This code 

```
		// Start PoolManager
		mgr.start();

		// Run CLI in loop
		while (g_running && mgr.isRunning()) {
			if (mgr.isConnected()) {
				auto mp = f.miningProgress(m_show_hwmonitors, m_show_power);
				minelog << mp << f.getSolutionStats() << f.farmLaunchedFormatted();

#if ETH_DBUS
				dbusint.send(toString(mp).data());
#endif
			}
			else {
				minelog << "not-connected";
			}
			this_thread::sleep_for(chrono::seconds(m_displayInterval));
		}

		mgr.stop();

		exit(0);
```

Causes this behavior

![locking](https://user-images.githubusercontent.com/15280851/39520337-8a5701c6-4e0a-11e8-883a-f3e040e92d9b.png)

**Comment by AndreaLanfranchi** [comment]
5 seconds is hardcoded in m_displayInterval

What blows my mind is that after the "No response in 2 seconds" you should get an *immediate* Disconnected from ... . Here, instead, it lags a good 20 seconds.

**Comment by smurfy** [comment]
> Here, instead, it lags a good 20 seconds

yea,

other stuff is fast again, like the reconnecting 3, 2, 1 .. the messages are 1 second apart.
But other stuff lags behind quite severe.

I really don't know what can cause this.

**Comment by AndreaLanfranchi** [comment]
It's not a personal observation. Has been reported.

#936

**Comment by AndreaLanfranchi** [comment]
Keen to think it's NIC related.
