### ISSUE TITLE
Cons of separate instance for 8 ethminer.exe on 1 PC?

### ISSUE THREAD

**Issue by mensa84** [ethereum-mining/ethminer#1054]
Hello,

I have 8 Nvidia 1060 GPUs connected to 1 Windows 10 PC (Celeron G3900, 4GB RAM, 40 GB swap on SSD).
To find out max. overclocking settings for each card, I currently prefer to run a separate instance of ethminer.exe for every GPU itself. So I can see exactly which GPU failed and not the whole system stops after a failure:

```
ethminer.exe --cuda-devices 0 ...
ethminer.exe --cuda-devices 1 ...
ethminer.exe --cuda-devices 2 ...
ethminer.exe --cuda-devices 3 ...
ethminer.exe --cuda-devices 4 ...
ethminer.exe --cuda-devices 5 ...
ethminer.exe --cuda-devices 6 ...
ethminer.exe --cuda-devices 7 ...
```

So this starts 8 windows on my PC.
Do you think, that I should use that way of running ethminer only for testing? Are there any disadvantages if I start like this? Is the system or even mining slowing down cause of this?
Or can I leave it like that?

**Comment by AndreaLanfranchi** [comment]
From my very personal POV there are more CONS than PRO.

CONS
* 8 open sockets to pool (clogging)
* 8 processes racing for network device
* 8 + cpu threads
* 8 x ram consumption
* you do not cluster computing capacity as each process gets it's own works.

PRO
* single instance/GPU failure likely won't affect other gpu's (in case it's not a driver issue in which case all other instances will fail too)
