### ISSUE TITLE
Ethminer 0.14 using -p now wont launch

### ISSUE THREAD

**Issue by beardedbob** [ethereum-mining/ethminer#1056]
Since changing to the new ethminer -p i'm not able to get past the following 

ethminer.exe -HWMON -RH -U --exit -P stratum+tcp://_wallet_.Miner:x@us1.ethermine.org:4444
  m  15:50:33|main    |  ethminer version 0.14.0rc8
  m  15:50:33|main    |  Build: windows / release +git. 8aaa768
 cu  15:50:33|main    |  Using grid size 8192 , block size 128

after this i get a windows 10 popup " ethminer.exe  has stopped responding"

**Comment by AndreaLanfranchi** [comment]
Try remove launch simple with 

`ethminer.exe -P stratum+tcp://wallet.Miner@us1.ethermine.org:4444`

No password
No RH
No HWMON

Please report.

**Comment by beardedbob** [comment]
thanks, it does the following

ethminer.exe -P stratum+tcp://_wallet_.Miner@us1.ethermine.org:4444
  m  16:01:13|main    |  ethminer version 0.14.0rc8
  m  16:01:13|main    |  Build: windows / release +git. 8aaa768

same error message / popup

**Comment by AndreaLanfranchi** [comment]
Which cards ? NVIDIA ? AMD ?

**Comment by SnowLeopard71** [comment]
How long does it take to crash?
Does using the alternate port `14444` make any difference?  `4444` has always timed out for me (as if a firewall is dropping those packets somewhere)

**Comment by beardedbob** [comment]
@AndreaLanfranchi Nvidia

@SnowLeopard71 Straight away it doesn't get any further than that error message. 14444 hasn't changed it as this still causes the same issue.

Motherboard is Asus B250 with 8x Nvidia GPU's.

**Comment by AndreaLanfranchi** [comment]
On bios settings have you enabled "Above 4G decoding" ?
How much ram do you have on board ?

**Comment by beardedbob** [comment]
Yes 4G is enabled 

4gb

**Comment by AndreaLanfranchi** [comment]
Sorry just te be sure ... du you start with

`ethminer.exe -U -P stratum+tcp://wallet.Miner@us1.ethermine.org:4444 `

**Comment by beardedbob** [comment]
I'm using 

ethminer.exe -U -P stratum+tcp://wallet.Miner:x@us1.ethermine.org:4444

**Comment by AndreaLanfranchi** [comment]
Could you please run this and report result ?

`ethminer.exe --list-devices `

**Comment by beardedbob** [comment]
I'm just in the process of rebuilding it to see if this resolves the issue as i've two other rigs which are working fine on this version. once this is complete i'll test again and if this fails i'll provide the device lists. Thanks for your help so far.

**Comment by AndreaLanfranchi** [comment]
@peterwillcn 
eth-proxy stratum mode is set with "stratum1" thus your command line becomes

`./ethminer -RH -X -P stratum1+tcp://xxx@eth.f2pool.com:8008`

**Comment by AndreaLanfranchi** [comment]
No feed back. Closing.
