### ISSUE TITLE
Json::LogicError with minergate pool

### ISSUE THREAD

**Issue by x29a** [ethereum-mining/ethminer#1065]
Since i thought this might be related to issue #1038 i posted my problem there as comment but i think it might be invisible since the item is closed so im posting as a new issue

im running `ethminer 0.15.0.dev7-5+commit.2e5fef6c` on ubuntu 16.04.3 headless via

`./ethminer -G -S eth.pool.minergate.com:45791 -O <emailaddress>`

and i get the following errormessage:
> terminate called after throwing an instance of 'Json::LogicError'
> what():  Type is not convertible to string

This is the recommended startcommand by minergate but its using deprecated parameters so i tried the same with
`./ethminer -G -P stratum+tcp://name%40email.com@eth.pool.minergate.com:45791`

same error message after a couple of accepted nonces. Thanks for any hints!

**Comment by AndreaLanfranchi** [comment]
Please report the log up to the moment of crash

**Comment by x29a** [comment]
I ran the command again with `NO_COLOR` set and once with `strace` running, hope this helps
[minergate_strace.log](https://github.com/ethereum-mining/ethminer/files/1975700/minergate_strace.log)
[minergate.log](https://github.com/ethereum-mining/ethminer/files/1975701/minergate.log)

**Comment by AndreaLanfranchi** [comment]
Could you filter network messages with strace please ?

strace -s 1000 -p <processid> -f -tt -e trace=network

**Comment by x29a** [comment]
Sure, its truncated a bit from the beginning because i wasnt fast enough, hope it helps though

[minergate_network.log](https://github.com/ethereum-mining/ethminer/files/1975756/minergate_network.log)

thanks for your support!

**Comment by AndreaLanfranchi** [comment]
Got it.
Will amend asap.

**Comment by x29a** [comment]
I verified with a build of your "Stratum" branch and indeed, it has been running for multiple minutes without problems whereas before it crashed within the first minute! Thanks for looking into this and fixing it so quickly!

**Comment by AndreaLanfranchi** [comment]
Thank you for appreciation.
Nevertheless you must be warned: minergate has variable difficulty and, at first round, it starts with an extremely **low** 1 Mh/s difficulty. It takes some time for it to adjust at higher levels. Do not know how your mining device is configured (a rig ? how many GPUs ? which kind ?) but when starting it will find shares at an incredible rate. The more GPU's you have the more the CPU and network driver can't keep up with the amount of shares being submitted.
Me personally, with a test rig of 6 GPU Gtx 1050 Ti (each one with a speed of 14.5 Mh/s), was not able to run ethminer with more than 3 GPUs. In all other cases I got segfaults on conflicting threads. 
At 1Mh difficulty a single GPU with 14.5 Mh speed can namely produce ~14 valid solutions per second. 3 Gpu is 45 solutions per second which is roughly 1 every 22 milliseconds. Considering that a good network connection takes 30 to 35 milliseconds roundtrip for the share being accepted by the pool. This means you're producing solutions at a higher rate than the network and cpu can handle 
Here ends the technical official part.

_Personal advice part: I woul discourage you from using Minergate. Look at other pools._

**Comment by AndreaLanfranchi** [comment]
Solved in source releases 0.14 and master.
Binaries yet to be released.
