### ISSUE TITLE
ethminer not switching

### ISSUE THREAD

**Issue by fsalle** [ethereum-mining/ethminer#1067]
Hello,

More a question than a bug for now, but I observe several times a day this kind of behavior:

_May  5 01:57:12 miner001 ethminer[6027]:   ℹ  01:57:12|stratum |  New job #2ec8b39a…   eth-eu1.nanopool.org [213.32.74.230:9999]
May  5 01:57:12 miner001 ethminer[6027]:  cu  01:57:12|cuda-0  |  Switch time 25 ms.
May  5 01:57:12 miner001 ethminer[6027]:   m  01:57:12|ethminer|  Speed  23.80 Mh/s    gpu/0 23.80 82C 50% 115W  [A6+0:R0+0:F0] Time: 00:55
May  5 01:57:17 miner001 ethminer[6027]:   m  01:57:17|ethminer|  Speed  23.64 Mh/s    gpu/0 23.64 82C 50% 115W  [A6+0:R0+0:F0] Time: 00:55
May  5 01:57:22 miner001 ethminer[6027]:   m  01:57:22|ethminer|  Speed  23.77 Mh/s    gpu/0 23.77 82C 50% 115W  [A6+0:R0+0:F0] Time: 00:55
May  5 01:57:26 miner001 ethminer[6027]:   ℹ  01:57:26|stratum |  New job #572a099f…   eth-eu1.nanopool.org [213.32.74.230:9999]
May  5 01:57:27 miner001 ethminer[6027]:   m  01:57:27|ethminer|  Speed  23.80 Mh/s    gpu/0 23.80 77C 50% 38W  [A6+0:R0+0:F0] Time: 00:55
May  5 01:57:32 miner001 ethminer[6027]:   m  01:57:32|ethminer|  Speed  23.80 Mh/s    gpu/0 23.80 75C 50% 38W  [A6+0:R0+0:F0] Time: 00:55
May  5 01:57:32 miner001 ethminer[6027]:   ℹ  01:57:32|stratum |  New job #7cb0eacf…   eth-eu1.nanopool.org [213.32.74.230:9999]
May  5 01:57:37 miner001 ethminer[6027]:   m  01:57:37|ethminer|  Speed  23.80 Mh/s    gpu/0 23.80 74C 50% 37W  [A6+0:R0+0:F0] Time: 00:55
May  5 01:57:39 miner001 ethminer[6027]:   ℹ  01:57:39|stratum |  New job #7ec03de0…   eth-eu1.nanopool.org [213.32.74.230:9999]
May  5 01:57:42 miner001 ethminer[6027]:   m  01:57:42|ethminer|  Speed  23.80 Mh/s    gpu/0 23.80 72C 50% 37W  [A6+0:R0+0:F0] Time: 00:55
May  5 01:57:47 miner001 ethminer[6027]:   m  01:57:47|ethminer|  Speed  23.80 Mh/s    gpu/0 23.80 72C 50% 37W  [A6+0:R0+0:F0] Time: 00:55
May  5 01:57:49 miner001 ethminer[6027]:   ℹ  01:57:49|stratum |  New job #96a2fc53…   eth-eu1.nanopool.org [213.32.74.230:9999]
May  5 01:57:52 miner001 ethminer[6027]:   m  01:57:52|ethminer|  Speed  23.80 Mh/s    gpu/0 23.80 71C 50% 37W  [A6+0:R0+0:F0] Time: 00:55
May  5 01:57:53 miner001 ethminer[6027]:   ℹ  01:57:53|stratum |  New job #ff6e58fe…   eth-eu1.nanopool.org [213.32.74.230:9999]
May  5 01:57:57 miner001 ethminer[6027]:   m  01:57:57|ethminer|  Speed  23.80 Mh/s    gpu/0 23.80 70C 50% 37W  [A6+0:R0+0:F0] Time: 00:55
May  5 01:57:59 miner001 ethminer[6027]:   ℹ  01:57:59|stratum |  New job #ac57bb9a…   eth-eu1.nanopool.org [213.32.74.230:9999]
May  5 01:58:02 miner001 ethminer[6027]:   m  01:58:02|ethminer|  Speed  23.80 Mh/s    gpu/0 23.80 69C 50% 37W  [A6+0:R0+0:F0] Time: 00:56_

As you can see, we receive new jobs but there is no switch.
My own monitoring see no more activity on the PCI bus (with nvidia-smi) so it restart the miner.

Is there something I can do about it ?

This occur only on my 1060 cards, not with the 1080.
I run the latest Ubuntu 16, latest nvidia drivers (390), and latest ethminer from master branch. The command line is:
/usr/local/bin/ethminer --cuda-devices 0 --cuda-noeval -v 7 -U -P stratum1+tcp://xyz@eth-eu1.nanopool.org:9999 -P stratum1+tcp://xyz@eth-us-west1.nanopool.org:9999 -RH -HWMON 1

Thank you,
Fred

**Comment by AndreaLanfranchi** [comment]
@fsalle 
This is because it's likely your GPU is in error due to excessive overclocking. (check with dmesg if there are issues on GPU PCIid)
Re run the test with zero overclocking and report.

**Comment by fsalle** [comment]
There is no dmesg for that time.
I have:
_[Sat May  5 01:01:28 2018] NVRM: Xid (PCI:0000:0a:00): 31, Ch 00000013, engmask 00000101, intr 10000000_
but it's due to:
_May  5 01:01:30 miner001 ethminer[3651]:   ✘  01:01:30|cuda-0  |  Fatal GPU error: CUDA error in func search at line 461 an illegal memory access was encountered_

I will test with zero overclocking.

**Comment by SnowLeopard71** [comment]
FYI:  ver 0.15.0.dev6 works fine and shows `switch time` for all three cards cuda cards on one rig.
In my experience, the `Xid 31` does not require a full system reboot like `Xid 62` but I always restart ethminer after any Xid error to avoid any adverse affects.

Note:  Help output indicates logging level 9 for `switch time` but source code actually says level 6.

**Comment by AndreaLanfranchi** [comment]
> Note: Help output indicates logging level 9 for switch time but source code actually says level 6.

Has been amended in dev7
