### ISSUE TITLE
could not connect to pool on  0.14.rc9

### ISSUE THREAD

**Issue by kolumbus120** [ethereum-mining/ethminer#1070]
Can not connect to some ubiq pool. It try start and then just crash down a close the windown. I used 0.14.rc6 and everything works great. Use the same params on rc9 and have problem.
My command is:
`ethminer.exe --farm-recheck 2000 -U -P stratum1+tcp://<wallet>@eu2.ubiqpool.io:8008 -HWMON 1 --cuda-block-size 256 --cuda-grid-size 8192 --cuda-streams 2 --cuda-parallel-hash 4 --work-timeout 250`

**Comment by kolumbus120** [comment]
Here is my command with log:
`ethminer.exe --farm-recheck 2000 -U -P stratum1+tcp://wallet@eu2.ubiqpool.io:8008 -HWMON 1 --cuda-block-size 256 --cuda-grid-size 8192 --cuda-streams 2 --cuda-parallel-hash 4 -v 8`
 m  20:49:33|main    |  ethminer version 0.14.0rc9
  m  20:49:33|main    |  Build: windows / release +git. d190f23
 cu  20:49:34|main    |  Using grid size 8192 , block size 256
  i  20:49:34|main    |  Selected pool eu2.ubiqpool.io:8008
  m  20:49:34|main    |  not-connected
  i  20:49:34|stratum |  Trying 104.238.171.4:8008 ...
  i  20:49:34|stratum |  Connected to eu2.ubiqpool.io  [104.238.171.4:8008]
  i  20:49:34|stratum |  Spinning up miners...
  i  20:49:34|cuda-0  |  No work. Pause for 3 s.
  i  20:49:34|cuda-1  |  No work. Pause for 3 s.
  i  20:49:34|cuda-2  |  No work. Pause for 3 s.

Thanks

**Comment by AndreaLanfranchi** [comment]
Please try and report.

`ethminer.exe --farm-recheck 2000 -U -P stratum+tcp://wallet@eu2.ubiqpool.io:8008 -HWMON 1 --cuda-block-size 256 --cuda-grid-size 8192 --cuda-streams 2 --cuda-parallel-hash 4 -v 8`

(note stratum1 has been amended to stratum).

**Comment by kolumbus120** [comment]
Same result.

**Comment by AndreaLanfranchi** [comment]
Got it.
We'have made changes on source code but binary releases are not ready yet.
Are you able to install from source ?

**Comment by kolumbus120** [comment]
Thank you. Maybe I am, but not now. I am too busy for that now. I try it to do it maybe tommorow.

**Comment by izoomrud** [comment]
Same trouble
 m  18:40:25|main    |  ethminer 0.15.0.dev7
  m  18:40:25|main    |  Build: windows / release
 cu  18:40:26|main    |  Using grid size 8192 , block size 128
  i  18:40:26|main    |  Selected pool eth.suprnova.cc:5005
  m  18:40:26|main    |  not-connected
  i  18:40:26|stratum |  Trying 149.202.76.194:5005 ...
  i  18:40:26|stratum |  Connected to eth.suprnova.cc  [149.202.76.194:5005]
  i  18:40:26|stratum |  Spinning up miners...
  i  18:40:26|cuda-0  |  No work. Pause for 3 s.
  i  18:40:26|cuda-1  |  No work. Pause for 3 s.
  i  18:40:26|cuda-2  |  No work. Pause for 3 s.
  i  18:40:29|cuda-0  |  No work. Pause for 3 s.
  i  18:40:29|cuda-1  |  No work. Pause for 3 s.
  i  18:40:29|cuda-2  |  No work. Pause for 3 s.

0.15.0.dev7
ethminer.exe --farm-recheck 2000 -U -P stratum+tcp://izoomrud.izoomrud@eth.suprnova.cc:5005 -RH --work-timeout 500

**Comment by AndreaLanfranchi** [comment]
Solved in 0.15.dev8 and 0.14
