### ISSUE TITLE
0.14 rc9 no reported hashrate on nanopool

### ISSUE THREAD

**Issue by newtoopensuse** [ethereum-mining/ethminer#1073]
I read it was solved in rc7.
win 10, rx 570 4Gb

ethminer.exe -HWMON 1 -RH --v 5 --display-interval 30 --farm-recheck 200 --cl-local-work 256 --cl-global-work 65536 --cl-parallel-hash 2 --cl-kernel 1 -G -P stratum+tcp://0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxx.rig1@eth-asia1.na..org@mymail

Everything works, but reported hashrate. Thanks

**Comment by smurfy** [comment]
use ``stratum1+tcp://0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxx.rig1@eth-asia1.na..org@mymail``

**Comment by newtoopensuse** [comment]
Tx. It works.
