### ISSUE TITLE
Ether mining system slowdown on Linux when GPU on x1 riser

### ISSUE THREAD

**Issue by azx07** [ethereum-mining/ethminer#1078]
I have a weird problem when trying to mine ethereum. I'm running manjaro linux and have the latest nvidia drivers installed. There are 3 GTX 1070 GPUs in my computer - two of them are connected natively to the motherboard and the 3rd card is connected via x1 to X16 pci riser. If I mine using only the 2 natively connected cards everything works fine and there is no system slowdown.

But when I try to mine on all of the 3 cards or even only on the card connected to the x1 riser there is a significant system slowdown - for instance scrolling in Firefox is very laggy (unusable) and, in general, the whole system becomes laggy.

I have no clue what could be the cause of this - since the 3rd card should not be used for any graphics (my monitor is connected to the 1st card).

The problem is present when using ethminer or Claymore’s dual miner.

On the other hand, on the same computer but in Win10 I do not have these problems and everything works fine.

My system config:
AMD Ryzen 1600
X370 Prime pro
16 GB RAM
500 GB Samsung Evo SSD
Corsair HX1000 PSU

**Comment by MariusVanDerWijden** [comment]
Maybe a bad riser? Have you tried switching out the riser?

**Comment by azx07** [comment]
I have not tried to switch the riser since it works fine under Win10 on the same machine. This seems to be a Linux specific problem. I will try to swap the riser when I find the time to do it.

**Comment by SnowLeopard71** [comment]
Try the riser on it's own (only 1 card) to be absolutely certain it is not the problem.
What is your `xorg.conf`?
You might want to try using the onboard video as the primary display adapter to see if that makes a difference.

**Comment by azx07** [comment]
I tried only to mine only on the riser and the problem is also present (with the other two cards being idle). Could be a faulty riser but it does not explain why its working on Win10. I'll try to swap as soon as I find time.

Anyway, here's my xorg.conf:

[20-nvidia.conf.txt](https://github.com/ethereum-mining/ethminer/files/1980881/20-nvidia.conf.txt)

**Comment by SnowLeopard71** [comment]
Nothing wrong with xorg.conf.   Does X log have any warings (WW) or errors (EE) that might indicate problem?  Maybe something with OpenGL?
Also, could it be Firefox related?  It has a history of poor performance in certain setups (search for "firefox laggy" finds many examples).

**Comment by azx07** [comment]
The relevant warnings/errors that I see could be:
(WW) NVIDIA(0): Option "PrimaryGPU" is not used - maybe I need to specify that GPU0 is primary?
Anyway, here is my Xorg.log

[Xorg.0.log.txt](https://github.com/ethereum-mining/ethminer/files/1981105/Xorg.0.log.txt)

The lag is not firefox related - it seems that it is GUI related - anything graphical is laggy.
There seems to be no nongraphical slowdown. It seems that the system is trying to use the x1 GPU for some graphical stuff whereas it should leave it just for computing.

P.S. The X370 does not have an onboard GPU so I cannot test what you suggested above.

**Comment by SnowLeopard71** [comment]
Saw image of the X370 with HDMI output, but realize now it depends on CPU used.
Quick test on my rig didn't have problems with Firefox, but primary gfx is built-in Intel.  Also, it's Ubuntu 16.04.
Maybe worth trying a pre-built USB mining distro to determine if it's something with your particular install?

**Comment by azx07** [comment]
could be worth a try - do you have a suggestion for a pre-built USB mining distro?

**Comment by rawdez** [comment]
try set pci-e ports to gen1 in bios

**Comment by rawdez** [comment]
> using gen 1 for pci-e lanes might be too slow

nope, there is no data to send through, all calculations perform on card

**Comment by azx07** [comment]
Hmm, I don't seem to se the option to change pci-e ports gen. in my bios. Is that possible for the asus X370 pr prime?

**Comment by rawdez** [comment]
from manual it seems like its not, you can try set pciex16_3 slot to x2 though. 
and try updating bios there is new version at asus website
Version 4011
2018/05/02
