### ISSUE TITLE
Using CUDA with win10 and gtx970 lets the miner crash. Opencl works fine. 

### ISSUE THREAD

**Issue by chross** [ethereum-mining/ethminer#108]
Hi,
I'm using the ethminer genoil version 1.1.7 on Win10 Pro Insider 16226 with the following options:
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --farm-recheck 200 -X --allow-opencl-cpu --verbosity 4 -S eth-eu1.nanopool.org:9999 -FS etc-eu2.nanopool.org:19999 -O address.worker

I have a GTX970 with 4 GB VRAM using the NVIDIA driver 382.53 with "Optimize for compute performance" activated. Using opencl, the GPU yields around 20 Mh/s. Whenever I'm trying to use CUDA, the miner will crash.

Debugging using a Visual Studio trial says:
"Unhandled exception at 0x00007FF6BE9E6A2A in ethminer.exe: 0xC0000005: Access violation writing location 0x0000000000000000."

The log itself says:
"CUDA error in func 'ethash_cuda_miner::init' at line 243 : out of memory."

My system has got 32GB of RAM with plenty available when running the miner.

Any help is greatly appreciated as I want to combine CPU and GPU mining for more performance.

This question was asked previously here: [https://github.com/ethereum/cpp-ethereum/issues/4207](https://github.com/ethereum/cpp-ethereum/issues/4207)

**Comment by z1ck** [comment]
I have the same problem.

Use loop for batch file. It helped me

```
@echo off
cls
:start
ethminer -U -S blablabla....
goto start
```

It takes 1-2 minutes of attempts, then it starts.

**Comment by chross** [comment]
Wow, at least you found a solution, albeit a very unsatisfying one.
Seems as if some buffers? need to be full to let the miner run successfully.

**Comment by chfast** [comment]
Looks like the driver fails to allocate big chunk of memory. We may try implementing this try loop in the code, but I'm not sure this will help.

**Comment by chross** [comment]
Mmh, what about a routine that will allocate small chunks then release them
and immediately allocate the large chunk.

Am 04.07.2017 19:41 schrieb "Paweł Bylica" <notifications@github.com>:

**Comment by chfast** [comment]
Reverting the order might help.

**Comment by chross** [comment]
Ok, so I tried looping until it mines, and I just works. I mean, I guess it is not great practice to do it like this but it will definitely work. It takes like 15 to 30 sec for my machine to establish a connection and start hashing.

**Comment by chfast** [comment]
@chross Do you mean looping in the code and using an external script?

**Comment by z1ck** [comment]
GTX970 contains 3.5 Gb of fast memory (192 Gb/s) and 512 Mb slow memory (28 Gb/s). We need to use only fast memory I think.

**Comment by chross** [comment]
Oh I meant in the code.

Am 05.07.2017 12:59 schrieb "Paweł Bylica" <notifications@github.com>:

**Comment by gotnt** [comment]
@chfast I also have this problem with my gtx970, win10 x64, latest nvidia driver and latest release ethminer, the external script is really helpful, but it would be better if it could be fixed...I have multiple cards, 970 will cause the ethminer to crash, so I have to use a separate script for it.

**Comment by rundekugel** [comment]
I have GTX965M and the batch script does not help. I just want to try mining.

**Comment by DeadManWalkingTO** [comment]
GTX1060 +150/+500/65%TDP @ 23-24MHs

1. Try Update Drivers.
Download and install the latests.

2. Try Update Ethminer.
Download (or beter build) the latest.

3. Try use -U for CUDA devices.
CUDA Hardware Test Launch Command:
`ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.issue108`

4. Try to change P2 State and Power managment mode.
You can use [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW).
For the best mining hashrate choose from sector "5 - Common":
    - CUDA - Force P2 State (Set to "Off")
    - Power managment mode (Set to "Prefer maximum performance")

5. Try Tweak Win10.
You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) (#695).

6. Try Optimize/Overclock GPUs. 
You can use [MSI Afterburner](https://www.msi.com/page/afterburner) for GPU OverClock/Optimize. 

7. Try use a WatchDog
You can use [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) (#735).

Please feedback.
Thank you!
