### ISSUE TITLE
api connection reset

### ISSUE THREAD

**Issue by logicminds** [ethereum-mining/ethminer#1081]
The following ruby code hangs when reading from the socket because the server does not properly close the socket or send a EOF signal after receiving data which signals to the receiver to stop reading.

Just copy and paste this to replicate.

```
cat > testcode.rb <<'EOF'
#!/usr/bin/env ruby

require 'json'
require 'socket'
sock = TCPSocket.new('localhost', '3333')
sock.write({"method": "miner_getstat1", "jsonrpc": "2.0", "id": 5 }.to_json + "\n")
puts sock.read
sock.close

EOF

ruby testcode.rb
```

The expected behavior is to return something like.

```
{"id":5,"jsonrpc":"2.0","result":["0.14.0.dev2","39","31175;17;0","31175","0;0;0","off","46;75","us2.ethermine.org:4444","0;0;0;0"]}
```

Also running `lsof -i :3333` is showing a bunch of ports open from the socket.

```
ethminer 21406 ethos   17u  IPv4 66693749      0t0  TCP *:3333 (LISTEN)
ethminer 21406 ethos   35u  IPv4 66828618      0t0  TCP localhost:3333->localhost:37622 (CLOSE_WAIT)
ethminer 21406 ethos   36u  IPv4 66835055      0t0  TCP localhost:3333->localhost:37624 (CLOSE_WAIT)
ethminer 21406 ethos   37u  IPv4 66845330      0t0  TCP localhost:3333->localhost:37626 (CLOSE_WAIT)
ethminer 21406 ethos   38u  IPv4 66893555      0t0  TCP localhost:3333->localhost:37628 (CLOSE_WAIT)
ethminer 21406 ethos   39u  IPv4 67320215      0t0  TCP localhost:3333->localhost:37640 (CLOSE_WAIT)
ethminer 21406 ethos   40u  IPv4 67397571      0t0  TCP localhost:3333->localhost:37642 (CLOSE_WAIT)
ethminer 21406 ethos   41u  IPv4 67412349      0t0  TCP localhost:3333->localhost:37644 (CLOSE_WAIT)
````

**Comment by AndreaLanfranchi** [comment]
Same as #847

**Comment by AndreaLanfranchi** [comment]
Before you close socket you should "shutdown" it.

```
cat > testcode.rb <<'EOF'
#!/usr/bin/env ruby

require 'json'
require 'socket'
sock = TCPSocket.new('localhost', '3333')
sock.write({"method": "miner_getstat1", "jsonrpc": "2.0", "id": 5 }.to_json + "\n")
puts sock.read
sock.shutdown(:RDWR)
sock.close

EOF

```
Please report.

**Comment by AndreaLanfranchi** [comment]
Do not know much about ruby's sockets.
I've written an api query tool in C# and does not suffer from the depicted behavior and does not leave connections in CLOSE_WAIT state.

Also this one can be issued many times: never hangs and no CLOSE_WAIT states recorded

`echo '{"id":0,"jsonrpc":"2.0","method":"miner_getstathr"}' | netcat localhost 3333 `

**Comment by smurfy** [comment]
> This reads and hangs forever because the server doesn't close or end the session.

well i'm no ruby user but a quick stackoverflow and replacing your ``puts sock.read``  with ``puts sock.gets``  should do the trick.
