### ISSUE TITLE
dag load single exit with error.

### ISSUE THREAD

**Issue by cnilsecure** [ethereum-mining/ethminer#1083]
./original --cl-kernel 1  --cl-local-work 128 --dag-load-mode single  --farm-recheck 5000 --farm-retries 8 -RH -SP 1 -HWMON -G -S etc1.91pool.com:8008 -O 0xeXXXXXXXXXXXXXXXXXXXXXXXXXXX
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stol
Aborted (core dumped)

Which leads me to another problem when trying to run 9 cards i get out of resource error.
important to mention is in experimental kernel no such problem only in "stable"

**Comment by AndreaLanfranchi** [comment]
As per help text

`--dag-load-mode single <n>`

where n is the GPU device you want to generate DAG on and then copy from.
