### ISSUE TITLE
 how to run on hiveos

### ISSUE THREAD

**Issue by ut9ea** [ethereum-mining/ethminer#1087]
ethminer 0.14.0rc4->rc9, 0.15.0dev4->dev7
which commands to connect
to display the name of the mail 
cache ride
 on the bullet  nanapool
Extra arguments for miner: 
You can put here something like:
--farm-recheck 500
--stratum-protocol 2 for nicehash
--opencl-devices 3 4 5 which OpenCL devices to mine on
--cuda-devices 3 4 5 which CUDA devices to mine on
just this !
and overclocking for cards amd  ?

for windows  --cl-parallel-hash 2 --cl-local-work 256 --cl-global-work 16384 --cl-kernel 1

**Comment by AndreaLanfranchi** [comment]
Do you want to mine on nicehash ?
If you have NVIDIA cards

`
ethminer -U -P stratum2+tcp://YOUR-BITCOIN-ADDRESS.WORKERNAME@daggerhashimoto.LOCATION.nicehash.com:3353
`

If you have AMD cards

`
ethminer -G -P stratum2+tcp://YOUR-BITCOIN-ADDRESS.WORKERNAME@daggerhashimoto.LOCATION.nicehash.com:3353
`

For the rest ... i do not understand what you mean by

>to display the name of the mail
cache ride
on the bullet nanapool

**Comment by AndreaLanfranchi** [comment]
Do not know anything about hiveos.
What I can tell you is you can execute ethminer with:

For Nvidia
`ethminer -U -P stratum+tcp://<yourethereumaddress>.<yourworkername>@eth-eu1.nanopool.org:9999
`
For AMD simply replace -U with -G

Ethminer does not perform overclocking. It runs at the best speed possible as set with external tools like nvidia-smi.

**Comment by ut9ea** [comment]
https://hiveos.farm/changelog/
0.5-50 2018-05-05
ethminer 0.14.0rc4->rc9, 0.15.0dev4->dev7

**Comment by AndreaLanfranchi** [comment]
I reiterate.
Do not know anything about hiveos. If you need support about hiveos ask them.

For ethminer relase 
- 0.14.x is latest **stable**
- 0.15.x is development and may be unstable
