### ISSUE TITLE
OpenCL init failed: clEnqueueNDRangeKernel: CL_MEM_OBJECT_ALLOCATION_FAILURE

### ISSUE THREAD

**Issue by Danielhodali** [ethereum-mining/ethminer#1089]
I always get this message:
 OpenCL init failed: clEnqueueNDRangeKernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
How can I solve this problem?

![screenshot](https://user-images.githubusercontent.com/23587533/39789763-377c7670-5332-11e8-9a29-ae27527a76c5.jpg)

I run ethminer on Windows 7 64 bit

**Comment by AndreaLanfranchi** [comment]
Why use OpenCL when you have NVIDIA cards ?
I know this does not answer your question but use CUDA and get more hashrate.
Also I see you're on an outdated release.
Please update to latest 0.14 or to developer's 0.15

**Comment by AndreaLanfranchi** [comment]
Other related
#1062

**Comment by Danielhodali** [comment]
It is version 0.14. How can I use Cuda? I need an example

**Comment by invidtiv** [comment]
use this to get CUDA working
_ethminer -RH -U -P stratum+tcp://"$MY_ADDRESS.$MY_RIG"@eu1.ethermine.org:4444_

you are using -G and - opencl that calls for AMD.

**Comment by AndreaLanfranchi** [comment]
>You are wrong. It is version 0.14.

It's version 0.14.dev4. There are 11 newer builds for 0.14

**Comment by Danielhodali** [comment]
I solved this issue. The graphic cards are not  properly recognised by the new mainboard. Avoid this mainboard: ASRock Q1900M J1900

**Comment by AndreaLanfranchi** [comment]
> The -F option is deprecated in version 0.15. How can I use ethminer 0.15 in combination with eth-proxy now?

Is it so difficult to read ethminer --help ?

```
    -P URL Specify a pool URL. Can be used multiple times. The 1st for for the primary pool, and the 2nd for the failover pool.
        URL takes the form: scheme://user[:password]@hostname:port[/emailaddress].
        for getwork use one of the following schemes:
          http
        for stratum use one of the following schemes:
          stratum+ssl stratum+tcp stratum+tls stratum+tls12 stratum1+ssl stratum1+tcp stratum1+tls stratum1+tls12 stratum2+ssl stratum2+tcp stratum2+tls stratum2+tls12
        Example 1 : stratum+ssl://0x012345678901234567890234567890123.miner1@ethermine.org:5555
        Example 2 : stratum1+tcp://0x012345678901234567890234567890123.miner1@nanopool.org:9999/john.doe@gmail.com
        Example 3 : stratum1+tcp://0x012345678901234567890234567890123@nanopool.org:9999/miner1/john.doe@gmail.com

```

Thus your -P parameter will be

`-P http://eth-proxy.address:port/Workername`
