### ISSUE TITLE
Disabling cuda device(s)

### ISSUE THREAD

**Issue by Scorpion2185** [ethereum-mining/ethminer#1094]
I need to disable a GPU because make the miner stop (it has only 2 gb ram) while i' m mining with cuda option.
Now i' m using the opencl because it has already this feature.
Any help?

**Comment by smurfy** [comment]
``--help`` is your friend, in the meantime: ``--cuda-devices`` lets you select, like with opencl, the devices you want to use with the miner.

**Comment by Scorpion2185** [comment]
thanks, in the help menu there isn' t any --cuda-devices i think that it should be added.

**Comment by AndreaLanfranchi** [comment]
There is 

```
 CUDA configuration:
    --cuda-block-size Set the CUDA block work size. Default is 128
    --cuda-grid-size Set the CUDA grid size. Default is 8192
    --cuda-streams Set the number of CUDA streams. Default is 2
    --cuda-schedule <mode> Set the schedule mode for CUDA threads waiting for CUDA devices to finish work. Default is 'sync'. Possible values are:
        auto  - Uses a heuristic based on the number of active CUDA contexts in the process C and the number of logical processors in the system P. If C > P, then yield else spin.
        spin  - Instruct CUDA to actively spin when waiting for results from the device.
        yield - Instruct CUDA to yield its thread when waiting for results from the device.
        sync  - Instruct CUDA to block the CPU thread on a synchronization primitive when waiting for the results from the device.
    --cuda-devices <0 1 ..n> Select which CUDA GPUs to mine on. Default is to use all

```

**Comment by Scorpion2185** [comment]
If i type ethminer --help in the terminal (ubuntu 16.04) there isn' t, how you get it?

**Comment by smurfy** [comment]
Please use the latest stable version of ethminer: https://github.com/ethereum-mining/ethminer/releases/latest
You also can try pre-releases

**Comment by Scorpion2185** [comment]
this https://github.com/ethereum-mining/ethminer/releases/tag/v0.15.0.dev9 is a pre-releases?

**Comment by AndreaLanfranchi** [comment]
@Scorpion2185 is only --cuda-devices missing or the entire "CUDA configuration" section missing ?

If the latter you're using a build without CUDA support.

**Comment by AndreaLanfranchi** [comment]
> this https://github.com/ethereum-mining/ethminer/releases/tag/v0.15.0.dev9 is a pre-releases?

Latest "official" release is 0.13
0.14 is release "candidate"
0.15 is development/experimental

**Comment by Scorpion2185** [comment]
Is missing the entire "CUDA configuration" section. Without support what is missing?

Candidate what means exactly? That is .orc version.

**Comment by AndreaLanfranchi** [comment]
> Is missing the entire "CUDA configuration" section. Without support what is missing?

This conflicts with your statement

> while i' m mining with cuda option.

If you do not have CUDA enabled it's impossible you can mine with cuda option.

If you're building yourself from source code you should follow this instructions.

https://github.com/ethereum-mining/ethminer#cmake-configuration-options

**Comment by Scorpion2185** [comment]
so i have cuda support indeed it seemed strange. So the "CUDA configuration" section should be added also for this version.

**Comment by AndreaLanfranchi** [comment]
No you have not.
If you download source code and compile yourself CUDA is not enabled unless you issue 

`cmake -DETHASHCUDA=ON ..`

**Comment by Scorpion2185** [comment]
i get this while i compiling using https://github.com/ethereum-mining/ethminer#building-from-source
nvcc fatal   : Unsupported gpu architecture 'compute_60'
