### ISSUE TITLE
RejectedStales and Failures 

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ethereum-mining/ethminer#1097]
Examining the log output

`[A34+0:R0+0:F0] Time: 00:28`

- A holds total accepted and detailed of stales accepted
- R holds total rejected and detailed of stales rejected
- F holds failures (incorrect results from GPU)

My questions :

1. What's the point of having rejected divided into stales ? If it's rejected it's rejected. Full stop.
2. Failures can be detected only if --noeval is **NOT** set. Maybe output shoudl be conditional ?

**Comment by efrasyad** [comment]
>Me? I'd rather have an option for a detailed report on a per gpu basis.. It would help in determining whether a particular card is not performing expectantly due to overclocking issues.

I agree I would like to have option for detailed shared per GPU followed by summary report.

**Comment by Sail86** [comment]
I agree with @AndreaLanfranchi, rejects can be simplified and failures optional. This will shorten log output which is nice for rigs with plenty GPUs.
As per GPU statistics, please do not blow up logs. Running a single instance per GPU is the better attempt to test & verify new clockrates.

**Comment by satori-q3a** [comment]
@Sali86...

It's not about testing new clockrates, it's about what happens to gpus over time and changing conditions.  GPUs become weaker, or more sensitive to heat, or memory chips begin to glitch.

If gpus were a constant, then I wouldn't need to keep etheminer in a batch loop to restart upon an unexpected failure exit.

**Comment by Sail86** [comment]
Ok I get your point, i considered GPUs quite constant (except for ambient temp) but in the conditions they're treated on mining abrasion might be an issue too. Then I'd suggest to make per GPU stats optional via cli argument.
