### ISSUE TITLE
Error using benchmarking Radeon 6850 HD

### ISSUE THREAD

**Issue by red0bear** [ethereum-mining/ethminer#1102]
./ethminer -G -M -v 9
  m  00:45:18|ethminer|  ethminer 0.15.0.dev7-5+commit.2e5fef6c.dirty
  m  00:45:18|ethminer|  Build: linux / release
  ℹ  00:45:18|ethminer|  Found suitable OpenCL device [ AMD BARTS (DRM 2.50.0 / 4.12.14-lp150.10-default, LLVM 5.0.1) ] with 1073741824  bytes of GPU memory
Benchmarking on platform: CL
Preparing DAG for block #0
 cl  00:45:18|cl-0    |  No work. Pause for 3 s.
Warming up...
 cl  00:45:21|cl-0    |  New epoch: 0
 cl  00:45:21|cl-0    |  Platform: Clover
 cl  00:45:21|cl-0    |  Device:   AMD BARTS (DRM 2.50.0 / 4.12.14-lp150.10-default, LLVM 5.0.1)  / OpenCL 1.1 Mesa 18.0.2
 cl  00:45:21|cl-0    |  OpenCL 1.1  not supported, but platform Clover might work nevertheless. USE AT OWN RISK!
 cl  00:45:22|cl-0    |  OpenCL kernel: Stable kernel
LLVM ERROR: Cannot select: 0x7fd8d87bfcb8: i32,ch = AtomicLoadAdd<Volatile LDST4[%count433(addrspace=1)]> 0x7fd8d87bb468, 0x7fd8d865e228, Constant:i32<1>
  0x7fd8d865e228: i32,ch = CopyFromReg 0x7fd8d87bb468, Register:i32 %vreg178
    0x7fd8d85b67a0: i32 = Register %vreg178
  0x7fd8d8552f28: i32 = Constant<1>
In function: ethash_search

**Comment by SnowLeopard71** [comment]
HD6850 only has 1GB memory, way too little for mining ethereum.
