### ISSUE TITLE
[0.15-dev10] No reconnection after network loss. (Windows)

### ISSUE THREAD

**Issue by Splitframe** [ethereum-mining/ethminer#1108]
Problem: Workers do not reconnect after network loss.
Reproduce: Have worker working, cut network (wifi in my case), reconnect network.
What happens: Endless prompt of "No connection".
What should happen: Reconnecting.

**Comment by AndreaLanfranchi** [comment]
Being addressed in #1107

**Comment by AndreaLanfranchi** [comment]
Please specify : are you on Windows or Linux ?

**Comment by Splitframe** [comment]
Ah, sorry. Windows. 
I used the search function, but didn't look through the whole Issue. Thank you!

**Comment by paddymahoney** [comment]
I've encountered this problem on both platforms

**Comment by AndreaLanfranchi** [comment]
Being addressed in #1135
