### ISSUE TITLE
DAG generates after reconnection

### ISSUE THREAD

**Issue by supaminer** [ethereum-mining/ethminer#1113]
Since 0.14 after reconnection DAG starting to regenerate. It take a lot of time.  With poor internet connection it's a big problem. Why need to generate it again after reconnect?
"Claymore" and "Ethminer <= 0.13" never regenerate DAG after reconnect

**Comment by AndreaLanfranchi** [comment]
Dag regeneration has nothing to do with internet connection performance as it does not download anything. 

Since 0.14 ethminer, on disconnection, shutsdown miner thus freeing generated Dag. It's been requested from many sources to stop mining (and stop wasting power) if no connection.

**Comment by supaminer** [comment]
@AndreaLanfranchi , I mean,  with poor internet connection(3g/4g cellular network) there are too many dissconnects, and we are wasting time for generation DAG.  
I think that a good idea to make a special parameter for Disable/Enable regeretation DAG after disconnect.

**Comment by supaminer** [comment]
@AndreaLanfranchi can you plz help with disable regeneration in source code. I can build from source, but can't understand how to disable "shutdown miner" when reconnect comes.

**Comment by supaminer** [comment]
@AndreaLanfranchi , I deleted m_farm.stop() from PoolManager.cpp. Looks like it helps. Is it all I need to do?

**Comment by AndreaLanfranchi** [comment]
You've done wrong.
It was enough to set the cli argument --response-timeout to a higher value instead of tamper with the code.

**Comment by supaminer** [comment]
Thanks
