### ISSUE TITLE
Having a problem with AppVeyor -  build 0.14 release 

### ISSUE THREAD

**Issue by supaminer** [ethereum-mining/ethminer#1115]
Hi. I'm trying to build 0.14 release with AppVeyor and got error:
 raise Exception('Expected GITHUB_USER_PASSWORD environment variable')
  Exception: Expected GITHUB_USER_PASSWORD environment variable
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\projects\ethminer\build\hunter_upload_cache.vcxproj]
Done Building Project "C:\projects\ethminer\build\hunter_upload_cache.vcxproj" (default targets) -- FAILED.

0.15dev10 building is OK, but 0.14 got error.

**Comment by chfast** [comment]
Yes. It was using an old mechanism for uploading Hunter cache.

You can try to set `GITHUB_USER_PASSWORD` environment variable for anything. It might workaround the problem.
