### ISSUE TITLE
Windows 10 AMD +Nvidia not working. AMD not working at all.

### ISSUE THREAD

**Issue by fenlasonb** [ethereum-mining/ethminer#1116]
Windows 10
EVGA 1070ti (2) RX570 8gb (2)
build 0.14 AND build 0.15dev10

Maybe im missing something. Maybe my batch script is wrong?

Trying to run both of these on the same batchfile. No luck. always reverted to the Nvidia card. So to isolate issue tried running this with just the AMD cards. Cannot get this to run with AMD cards.
##############################################################################

Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[0] [0] GeForce GTX 1070 Ti
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2147483648
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
[0] [1] GeForce GTX 1070 Ti
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2147483648
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
[1] [0] Intel(R) HD Graphics 630
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 3380195328
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1690097664
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[2] [0] Ellesmere
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[2] [1] Ellesmere
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1070 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 8589934592
        Pci: 0000:01:00
[1] GeForce GTX 1070 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 8589934592
        Pci: 0000:05:00

C:\Users\CrypteyMiney\Downloads\bin>
##############################################################################

ethminer.exe -X --opencl-platform 2 --farm-recheck 200 -U -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -u 0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney
pause

C:\Users\CrypteyMiney\Downloads\bin>ethminer.exe -X --opencl-platform 2 --farm-recheck 200 -U -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -u 0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney
Warning: -S is deprecated. Use the -P parameter instead.
Warning: -FS is deprecated. Use the -P parameter instead.
Warning: -u is deprecated. Use the -P parameter instead.
  m  22:33:52|main    |  ethminer version 0.14.0
  m  22:33:52|main    |  Build: windows / release +git. 24c65cf
 cu  22:33:52|main    |  Using grid size 8192 , block size 128
  i  22:33:53|main    |  Selected pool us1.ethermine.org:4444
  m  22:33:53|main    |  not-connected
  i  22:33:53|stratum |  Trying 18.219.59.155:4444 ...
  i  22:33:53|stratum |  Connected to us1.ethermine.org  [18.219.59.155:4444]
  i  22:33:53|stratum |  Spinning up miners...
  i  22:33:53|cuda-0  |  No work. Pause for 3 s.
  i  22:33:53|cuda-1  |  No work. Pause for 3 s.
  i  22:33:53|stratum |  Subscribed to stratum server
  i  22:33:53|stratum |  Authorized worker 0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney
  i  22:33:53|stratum |  New pool difficulty:  4.00 gigahashes
  i  22:33:53|stratum |  New job #fdc55582...   us1.ethermine.org [18.219.59.155:4444]
  i  22:33:56|cuda-0  |  Initialising miner 0
  i  22:33:56|cuda-1  |  Initialising miner 1
 cu  22:33:58|cuda-0  |  Using device: GeForce GTX 1070 Ti  (Compute 6.1)
 cu  22:33:58|cuda-0  |  Set Device to current
 cu  22:33:58|cuda-0  |  Resetting device
 cu  22:33:58|cuda-1  |  Using device: GeForce GTX 1070 Ti  (Compute 6.1)
 cu  22:33:58|cuda-1  |  Set Device to current
 cu  22:33:58|cuda-1  |  Resetting device

ethminer.exe -G --opencl-platform 2 --farm-recheck 200 -U -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -u 0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney
pause

C:\Users\CrypteyMiney\Downloads\bin>ethminer.exe -G --opencl-platform 2 --farm-recheck 200 -U -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -u 0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney
Warning: -S is deprecated. Use the -P parameter instead.
Warning: -FS is deprecated. Use the -P parameter instead.
Warning: -u is deprecated. Use the -P parameter instead.
  m  22:35:33|main    |  ethminer version 0.14.0
  m  22:35:33|main    |  Build: windows / release +git. 24c65cf
 cu  22:35:34|main    |  Using grid size 8192 , block size 128
  i  22:35:35|main    |  Selected pool us1.ethermine.org:4444
  m  22:35:35|main    |  not-connected
  i  22:35:35|stratum |  Trying 18.219.59.155:4444 ...
  i  22:35:35|stratum |  Connected to us1.ethermine.org  [18.219.59.155:4444]
  i  22:35:35|stratum |  Spinning up miners...
  i  22:35:35|cuda-0  |  No work. Pause for 3 s.
  i  22:35:35|cuda-1  |  No work. Pause for 3 s.
  i  22:35:35|stratum |  Subscribed to stratum server
  i  22:35:35|stratum |  Authorized worker 0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney
  i  22:35:35|stratum |  New pool difficulty:  4.00 gigahashes
  i  22:35:35|stratum |  New job #0e9a9289...   us1.ethermine.org [18.219.59.155:4444]
  i  22:35:38|cuda-0  |  Initialising miner 0
  i  22:35:38|cuda-1  |  Initialising miner 1
 cu  22:35:40|cuda-1  |  Using device: GeForce GTX 1070 Ti  (Compute 6.1)
 cu  22:35:40|cuda-0  |  Using device: GeForce GTX 1070 Ti  (Compute 6.1)
 cu  22:35:40|cuda-1  |  Set Device to current
 cu  22:35:40|cuda-0  |  Set Device to current
 cu  22:35:40|cuda-1  |  Resetting device
 cu  22:35:40|cuda-0  |  Resetting device

##############################################################################
Card name: Radeon RX 570 Series
        Manufacturer: Advanced Micro Devices, Inc.
           Chip type: AMD Radeon Graphics Processor (0x67DF)
            DAC type: Internal DAC(400MHz)
         Device Type: Full Device
          Device Key: Enum\PCI\VEN_1002&DEV_67DF&SUBSYS_341B1462&REV_EF
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
 Driver Problem Code: Unknown
      Display Memory: 12168 MB
    Dedicated Memory: 8139 MB
       Shared Memory: 4029 MB
        Current Mode: Unknown
         HDR Support: Unknown
    Display Topology: Unknown
 Display Color Space: Unknown
     Color Primaries: Unknown
   Display Luminance: Unknown
         Driver Name: C:\WINDOWS\System32\DriverStore\FileRepository\c0317304.inf_amd64_3f14567ea75b9e52\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\c0317304.inf_amd64_3f14567ea75b9e52\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\c0317304.inf_amd64_3f14567ea75b9e52\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\c0317304.inf_amd64_3f14567ea75b9e52\amdxc64.dll
 Driver File Version: 22.19.0659.0000 (English)
      Driver Version: 22.19.659.0
         DDI Version: 12
      Feature Levels: 12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
        Driver Model: WDDM 2.2
 Graphics Preemption: Primitive
  Compute Preemption: DMA
            Miracast: Not Supported
 Hybrid Graphics GPU: Not Supported
      Power P-states: Not Supported
      Virtualization: Not Supported
          Block List: No Blocks
  Catalog Attributes: N/A
   Driver Attributes: Final Retail
    Driver Date/Size: 8/7/2017 8:00:00 PM, 1938144 bytes
         WHQL Logo'd: Yes
     WHQL Date Stamp: Unknown
   Device Identifier: Unknown
           Vendor ID: 0x1002
           Device ID: 0x67DF
           SubSys ID: 0x341B1462
         Revision ID: 0x00EF
  Driver Strong Name: oem23.inf:cb0ae414b0256a4a:ati2mtag_Polaris10DS:22.19.659.0:pci\ven_1002&dev_67df&rev_ef
      Rank Of Driver: 00D12000
         Video Accel: Unknown
         DXVA2 Modes: DXVA2_ModeMPEG2_VLD  DXVA2_ModeMPEG2_IDCT  DXVA2_ModeH264_VLD_NoFGT  DXVA2_ModeHEVC_VLD_Main  DXVA2_ModeH264_VLD_Stereo_Progressive_NoFGT  DXVA2_ModeH264_VLD_Stereo_NoFGT  DXVA2_ModeVC1_VLD  DXVA2_ModeMPEG4pt2_VLD_AdvSimple_NoGMC  DXVA2_ModeHEVC_VLD_Main10  
      Deinterlace Caps: n/a
        D3D9 Overlay: Unknown
             DXVA-HD: Unknown
        DDraw Status: Enabled
          D3D Status: Enabled
          AGP Status: Enabled
       MPO MaxPlanes: 0
            MPO Caps: Not Supported
         MPO Stretch: Not Supported
     MPO Media Hints: Not Supported
         MPO Formats: Not Supported
    PanelFitter Caps: Not Supported
 PanelFitter Stretch: Not Supported

           Card name: Radeon RX 570 Series
        Manufacturer: Advanced Micro Devices, Inc.
           Chip type: AMD Radeon Graphics Processor (0x67DF)
            DAC type: Internal DAC(400MHz)
         Device Type: Full Device
          Device Key: Enum\PCI\VEN_1002&DEV_67DF&SUBSYS_341B1462&REV_EF
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
 Driver Problem Code: Unknown
      Display Memory: 12168 MB
    Dedicated Memory: 8139 MB
       Shared Memory: 4029 MB
        Current Mode: Unknown
         HDR Support: Unknown
    Display Topology: Unknown
 Display Color Space: Unknown
     Color Primaries: Unknown
   Display Luminance: Unknown
         Driver Name: C:\WINDOWS\System32\DriverStore\FileRepository\c0317304.inf_amd64_3f14567ea75b9e52\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\c0317304.inf_amd64_3f14567ea75b9e52\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\c0317304.inf_amd64_3f14567ea75b9e52\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\c0317304.inf_amd64_3f14567ea75b9e52\amdxc64.dll
 Driver File Version: 22.19.0659.0000 (English)
      Driver Version: 22.19.659.0
         DDI Version: 12
      Feature Levels: 12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
        Driver Model: WDDM 2.2
 Graphics Preemption: Primitive
  Compute Preemption: DMA
            Miracast: Not Supported
 Hybrid Graphics GPU: Not Supported
      Power P-states: Not Supported
      Virtualization: Not Supported
          Block List: No Blocks
  Catalog Attributes: N/A
   Driver Attributes: Final Retail
    Driver Date/Size: 8/7/2017 8:00:00 PM, 1938144 bytes
         WHQL Logo'd: Yes
     WHQL Date Stamp: Unknown
   Device Identifier: Unknown
           Vendor ID: 0x1002
           Device ID: 0x67DF
           SubSys ID: 0x341B1462
         Revision ID: 0x00EF
  Driver Strong Name: oem23.inf:cb0ae414b0256a4a:ati2mtag_Polaris10DS:22.19.659.0:pci\ven_1002&dev_67df&rev_ef
      Rank Of Driver: 00D12000
         Video Accel: Unknown
         DXVA2 Modes: DXVA2_ModeMPEG2_VLD  DXVA2_ModeMPEG2_IDCT  DXVA2_ModeH264_VLD_NoFGT  DXVA2_ModeHEVC_VLD_Main  DXVA2_ModeH264_VLD_Stereo_Progressive_NoFGT  DXVA2_ModeH264_VLD_Stereo_NoFGT  DXVA2_ModeVC1_VLD  DXVA2_ModeMPEG4pt2_VLD_AdvSimple_NoGMC  DXVA2_ModeHEVC_VLD_Main10  
      Deinterlace Caps: n/a
        D3D9 Overlay: Unknown
             DXVA-HD: Unknown
        DDraw Status: Enabled
          D3D Status: Enabled
          AGP Status: Enabled
       MPO MaxPlanes: 0
            MPO Caps: Not Supported
         MPO Stretch: Not Supported
     MPO Media Hints: Not Supported
         MPO Formats: Not Supported
    PanelFitter Caps: Not Supported
 PanelFitter Stretch: Not Supported

           Card name: NVIDIA GeForce GTX 1070 Ti
        Manufacturer: NVIDIA
           Chip type: GeForce GTX 1070 Ti
            DAC type: Integrated RAMDAC
         Device Type: Full Device
          Device Key: Enum\PCI\VEN_10DE&DEV_1B82&SUBSYS_86231043&REV_A1
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
 Driver Problem Code: Unknown
      Display Memory: 12109 MB
    Dedicated Memory: 8080 MB
       Shared Memory: 4029 MB
        Current Mode: Unknown
         HDR Support: Unknown
    Display Topology: Unknown
 Display Color Space: Unknown
     Color Primaries: Unknown
   Display Luminance: Unknown
         Driver Name: C:\WINDOWS\System32\DriverStore\FileRepository\nv_ref_pubwu.inf_amd64_708ec8f9a4d134c6\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_ref_pubwu.inf_amd64_708ec8f9a4d134c6\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_ref_pubwu.inf_amd64_708ec8f9a4d134c6\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_ref_pubwu.inf_amd64_708ec8f9a4d134c6\nvldumdx.dll
 Driver File Version: 23.21.0013.9135 (English)
      Driver Version: 23.21.13.9135
         DDI Version: 12
      Feature Levels: 12_1,12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
        Driver Model: WDDM 2.3
 Graphics Preemption: Pixel
  Compute Preemption: Dispatch
            Miracast: Not Supported
 Hybrid Graphics GPU: Not Supported
      Power P-states: Not Supported
      Virtualization: Paravirtualization 
          Block List: No Blocks
  Catalog Attributes: Universal:N/A Declarative:N/A 
   Driver Attributes: Final Retail
    Driver Date/Size: 3/22/2018 8:00:00 PM, 949016 bytes
         WHQL Logo'd: Yes
     WHQL Date Stamp: Unknown
   Device Identifier: Unknown
           Vendor ID: 0x10DE
           Device ID: 0x1B82
           SubSys ID: 0x86231043
         Revision ID: 0x00A1
  Driver Strong Name: oem3.inf:0f066de361876b02:Section118:23.21.13.9135:pci\ven_10de&dev_1b82
      Rank Of Driver: 00D12001
         Video Accel: Unknown
         DXVA2 Modes: DXVA2_ModeMPEG2_VLD  DXVA2_ModeVC1_D2010  DXVA2_ModeVC1_VLD  DXVA2_ModeH264_VLD_Stereo_Progressive_NoFGT  DXVA2_ModeH264_VLD_Stereo_NoFGT  DXVA2_ModeH264_VLD_NoFGT  DXVA2_ModeHEVC_VLD_Main  DXVA2_ModeHEVC_VLD_Main10  DXVA2_ModeMPEG4pt2_VLD_Simple  DXVA2_ModeMPEG4pt2_VLD_AdvSimple_NoGMC  DXVA2_ModeVP9_VLD_Profile0  
      Deinterlace Caps: n/a
        D3D9 Overlay: Unknown
             DXVA-HD: Unknown
        DDraw Status: Enabled
          D3D Status: Enabled
          AGP Status: Enabled
       MPO MaxPlanes: 0
            MPO Caps: Not Supported
         MPO Stretch: Not Supported
     MPO Media Hints: Not Supported
         MPO Formats: Not Supported
    PanelFitter Caps: Not Supported
 PanelFitter Stretch: Not Supported

           Card name: NVIDIA GeForce GTX 1070 Ti
        Manufacturer: NVIDIA
           Chip type: GeForce GTX 1070 Ti
            DAC type: Integrated RAMDAC
         Device Type: Full Device
          Device Key: Enum\PCI\VEN_10DE&DEV_1B82&SUBSYS_56783842&REV_A1
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
 Driver Problem Code: Unknown
      Display Memory: 12109 MB
    Dedicated Memory: 8080 MB
       Shared Memory: 4029 MB
        Current Mode: Unknown
         HDR Support: Unknown
    Display Topology: Unknown
 Display Color Space: Unknown
     Color Primaries: Unknown
   Display Luminance: Unknown
         Driver Name: C:\WINDOWS\System32\DriverStore\FileRepository\nv_ref_pubwu.inf_amd64_708ec8f9a4d134c6\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_ref_pubwu.inf_amd64_708ec8f9a4d134c6\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_ref_pubwu.inf_amd64_708ec8f9a4d134c6\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_ref_pubwu.inf_amd64_708ec8f9a4d134c6\nvldumdx.dll
 Driver File Version: 23.21.0013.9135 (English)
      Driver Version: 23.21.13.9135
         DDI Version: 12
      Feature Levels: 12_1,12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
        Driver Model: WDDM 2.3
 Graphics Preemption: Pixel
  Compute Preemption: Dispatch
            Miracast: Not Supported
 Hybrid Graphics GPU: Not Supported
      Power P-states: Not Supported
      Virtualization: Paravirtualization 
          Block List: No Blocks
  Catalog Attributes: Universal:N/A Declarative:N/A 
   Driver Attributes: Final Retail
    Driver Date/Size: 3/22/2018 8:00:00 PM, 949016 bytes
         WHQL Logo'd: Yes
     WHQL Date Stamp: Unknown
   Device Identifier: Unknown
           Vendor ID: 0x10DE
           Device ID: 0x1B82
           SubSys ID: 0x56783842
         Revision ID: 0x00A1
  Driver Strong Name: oem3.inf:0f066de361876b02:Section118:23.21.13.9135:pci\ven_10de&dev_1b82
      Rank Of Driver: 00D12001
         Video Accel: Unknown
         DXVA2 Modes: DXVA2_ModeMPEG2_VLD  DXVA2_ModeVC1_D2010  DXVA2_ModeVC1_VLD  DXVA2_ModeH264_VLD_Stereo_Progressive_NoFGT  DXVA2_ModeH264_VLD_Stereo_NoFGT  DXVA2_ModeH264_VLD_NoFGT  DXVA2_ModeHEVC_VLD_Main  DXVA2_ModeHEVC_VLD_Main10  DXVA2_ModeMPEG4pt2_VLD_Simple  DXVA2_ModeMPEG4pt2_VLD_AdvSimple_NoGMC  DXVA2_ModeVP9_VLD_Profile0  
      Deinterlace Caps: n/a
        D3D9 Overlay: Unknown
             DXVA-HD: Unknown
        DDraw Status: Enabled
          D3D Status: Enabled
          AGP Status: Enabled
       MPO MaxPlanes: 0
            MPO Caps: Not Supported
         MPO Stretch: Not Supported
     MPO Media Hints: Not Supported
         MPO Formats: Not Supported
    PanelFitter Caps: Not Supported
 PanelFitter Stretch: Not Supported

**Comment by SnowLeopard71** [comment]
Each of your command lines shown includes `-U` (uppercase) which seems to be overriding `-X` or `-G`.

**Comment by fenlasonb** [comment]
@SnowLeopard71 

WOW. I am in need of some coffee tonight. Ive been hammering at this now forever. I cant believe that silly mistake. 

As clearly you can see i am pretty new to this. Is there any thing else i can do to maximize performance. was reading about the --cuda-parallel-hash 

Again ty so much

**Comment by SnowLeopard71** [comment]
For OpenCL, I use `--cl-local-work 256 --cl-kernel 1 --cl-global-work 65536 --cl-parallel-hash 2`.   If you get many stales, try a lower cl-global-work.
For cuda, I haven't found better than defaults.

**Comment by fenlasonb** [comment]
@SnowLeopard71 Good to know. So if i can get my nvidia cards to now work at the same time we would be golden.

Would be curious if -x runs cuda with cuda and opencl with amd or is it opencl for all 4

**Comment by fenlasonb** [comment]
strange because -G works. all i should have to change is the -G to -X

C:\Users\CrypteyMiney\Downloads\bin>ethminer.exe -G --opencl-platform 2 -S us1.ethermine.org:4444 -u 0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney --cl-local-work 256 --cl-kernel 1 --cl-global-work 65536 --cl-parallel-hash 2
Warning: -S is deprecated. Use the -P parameter instead.
Warning: -u is deprecated. Use the -P parameter instead.
  m  23:31:57|main    |  ethminer version 0.14.0
  m  23:31:57|main    |  Build: windows / release +git. 24c65cf
  i  23:32:00|main    |  Found suitable OpenCL device [ Ellesmere ] with 8589934592  bytes of GPU memory
  i  23:32:00|main    |  Selected pool us1.ethermine.org:4444
  m  23:32:00|main    |  not-connected
  i  23:32:00|stratum |  Trying 18.219.59.155:4444 ...
  i  23:32:00|stratum |  Connected to us1.ethermine.org  [18.219.59.155:4444]
  i  23:32:00|stratum |  Spinning up miners...
 cl  23:32:00|cl-0    |  No work. Pause for 3 s.
 cl  23:32:00|cl-1    |  No work. Pause for 3 s.
  i  23:32:00|stratum |  Subscribed to stratum server
  i  23:32:00|stratum |  Authorized worker 0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney
  i  23:32:00|stratum |  New pool difficulty:  4.00 gigahashes
  i  23:32:00|stratum |  New job #6fbef31b...   us1.ethermine.org [18.219.59.155:4444]
 cl  23:32:03|cl-0    |  New seed #e6073b55...
 cl  23:32:03|cl-1    |  New seed #e6073b55...
  m  23:32:05|main    |  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  23:32:05|cl-0    |  Platform: AMD Accelerated Parallel Processing
 cl  23:32:05|cl-1    |  Platform: AMD Accelerated Parallel Processing
 cl  23:32:05|cl-0    |  Device:   Ellesmere  / OpenCL 2.0 AMD-APP (2442.12)
 cl  23:32:05|cl-1    |  Device:   Ellesmere  / OpenCL 2.0 AMD-APP (2442.12)
 cl  23:32:06|cl-0    |  OpenCL kernel: Experimental kernel
 cl  23:32:07|cl-0    |  Build info:
 cl  23:32:07|cl-0    |  Creating light cache buffer, size 41286208
 cl  23:32:07|cl-0    |  Creating DAG buffer, size 2642407552
 cl  23:32:07|cl-0    |  Loading kernels
 cl  23:32:07|cl-0    |  Writing light cache buffer
 cl  23:32:07|cl-1    |  OpenCL kernel: Experimental kernel
 cl  23:32:07|cl-0    |  Creating buffer for header.
 cl  23:32:07|cl-0    |  Creating mining buffer
 cl  23:32:08|cl-1    |  Build info:
 cl  23:32:08|cl-1    |  Creating light cache buffer, size 41286208
 cl  23:32:08|cl-1    |  Creating DAG buffer, size 2642407552
 cl  23:32:08|cl-1    |  Loading kernels
 cl  23:32:08|cl-1    |  Writing light cache buffer
 cl  23:32:08|cl-1    |  Creating buffer for header.
 cl  23:32:08|cl-1    |  Creating mining buffer
  m  23:32:10|main    |  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  i  23:32:13|cl-0    |  2.46093  GB of DAG data generated in 5490 ms.
  i  23:32:13|cl-1    |  2.46093  GB of DAG data generated in 4964 ms.

**Comment by SnowLeopard71** [comment]
Running two copies, with `-U` and `-G` might be best (it's what most do afaik).
Is the output log heavily edited in the first reply (the `-X` output)?  It shows both types waiting for work:
> i 23:28:04|cuda-0 | No work. Pause for 3 s.
i 23:28:04|cuda-1 | No work. Pause for 3 s.
cl 23:28:04|cl-2 | No work. Pause for 3 s.
cl 23:28:04|cl-3 | No work. Pause for 3 s.
But strangely it does not have the `Subscribed` and `Authorized` that normally appear next.

**Comment by fenlasonb** [comment]
I will run it again to show you. I have not edited log one bit.

C:\Users\CrypteyMiney\Downloads\bin>ethminer.exe -X --opencl-platform 2 -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -u 0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney
Warning: -S is deprecated. Use the -P parameter instead.
Warning: -FS is deprecated. Use the -P parameter instead.
Warning: -u is deprecated. Use the -P parameter instead.
  m  23:43:25|main    |  ethminer version 0.14.0
  m  23:43:25|main    |  Build: windows / release +git. 24c65cf
  i  23:43:27|main    |  Found suitable OpenCL device [ Ellesmere ] with 8589934592  bytes of GPU memory
 cu  23:43:28|main    |  Using grid size 8192 , block size 128
  i  23:43:28|main    |  Selected pool us1.ethermine.org:4444
  m  23:43:28|main    |  not-connected
  i  23:43:28|stratum |  Trying 18.219.59.155:4444 ...
  i  23:43:28|stratum |  Connected to us1.ethermine.org  [18.219.59.155:4444]
  i  23:43:28|stratum |  Spinning up miners...
  i  23:43:28|cuda-0  |  No work. Pause for 3 s.
  i  23:43:28|cuda-1  |  No work. Pause for 3 s.
 cl  23:43:28|cl-2    |  No work. Pause for 3 s.
 cl  23:43:28|cl-3    |  No work. Pause for 3 s.
  i  23:43:31|cuda-0  |  No work. Pause for 3 s.
  i  23:43:31|cuda-1  |  No work. Pause for 3 s.
 cl  23:43:31|cl-2    |  No work. Pause for 3 s.
 cl  23:43:31|cl-3    |  No work. Pause for 3 s.
  i  23:43:34|cuda-0  |  No work. Pause for 3 s.
  i  23:43:34|cuda-1  |  No work. Pause for 3 s.
 cl  23:43:34|cl-2    |  No work. Pause for 3 s.
 cl  23:43:34|cl-3    |  No work. Pause for 3 s.
  i  23:43:37|cuda-0  |  No work. Pause for 3 s.
  i  23:43:37|cuda-1  |  No work. Pause for 3 s.
 cl  23:43:37|cl-2    |  No work. Pause for 3 s.
 cl  23:43:37|cl-3    |  No work. Pause for 3 s.
  i  23:43:56|cuda-0  |  No work. Pause for 3 s.
  i  23:43:56|cuda-1  |  No work. Pause for 3 s.
 cl  23:43:56|cl-2    |  No work. Pause for 3 s.
 cl  23:43:56|cl-3    |  No work. Pause for 3 s.

**Comment by fenlasonb** [comment]
Well I will leave this one open for a few here. See if anyone has any ideas before closing. Maybe a bug? not sure.

**Comment by SnowLeopard71** [comment]
Unless someone else has a suggestion, I'd recommend running two copies, one for each of AMD and Nvidia.
It does appear to be a bug with `-X`.

**Comment by MariusVanDerWijden** [comment]
Can you open a new Issue for the -X parameter? And link this thread?
