### ISSUE TITLE
pool eth.2miners.com

### ISSUE THREAD

**Issue by ut9ea** [ethereum-mining/ethminer#1117]
10:21:46|cl-2    |  No work. Pause for 3 s.
  ℹ  10:21:46|stratum |  Could not login to ethproxy server: code:-1 message:Invalid login 
  ℹ  10:21:46|stratum |  Disconnected from eth.2miners.com  [54.36.109.160:2020]
  ℹ  10:21:46|stratum |  Shutting down miners...
  ✘  10:21:49|cl-0    |  OpenCL Error: clFinish: CL_INVALID_COMMAND_QUEUE (-36)
 cl  10:21:49|cl-1    |  No work. Pause for 3 s.
 cl  10:21:49|cl-2    |  No work. Pause for 3 s.
  m  10:21:49|ethminer|  not-connected
  ✘  10:21:52|cl-1    |  OpenCL Error: clFinish: CL_INVALID_COMMAND_QUEUE (-36)
 cl  10:21:52|cl-2    |  No work. Pause for 3 s.
  m  10:21:54|ethminer|  not-connected
  ✘  10:21:55|cl-2    |  OpenCL Error: clFinish: CL_INVALID_COMMAND_QUEUE (-36)
  ℹ  10:21:55|stratum |  Retrying in 3 ... 
  ℹ  10:21:56|stratum |  Retrying in 2 ... 
  ℹ  10:21:57|stratum |  Retrying in 1 ... 
  ℹ  10:21:58|stratum |  Selected pool eth.2miners.com:2020
  ℹ  10:21:58|stratum |  Trying 54.36.109.160:2020 ...
  ℹ  10:21:58|stratum |  Connected to eth.2miners.com  [54.36.109.160:2020]
  ℹ  10:21:58|stratum |  Spinning up miners...
 cl  10:21:58|cl-0    |  No work. Pause for 3 s.
 cl  10:21:58|cl-1    |  No work. Pause for 3 s.
 cl  10:21:58|cl-2    |  No work. Pause for 3 s.
  ℹ  10:21:58|stratum |  Could not login to ethproxy server: code:-1 message:Invalid login 
  ℹ  10:21:58|stratum |  Disconnected from eth.2miners.com  [54.36.109.160:2020]
  ℹ  10:21:58|stratum |  Shutting down miners...
  m  10:21:59|ethminer|  not-connected
  ✘  10:22:01|cl-0    |  OpenCL Error: clFinish: CL_INVALID_COMMAND_QUEUE (-36)
 cl  10:22:01|cl-1    |  No work. Pause for 3 s.

**Comment by AndreaLanfranchi** [comment]
What are we supposed to understand from this ?

What command line arguments do you use to launch ethminer ?

**Comment by ut9ea** [comment]
14.0
ethminer.exe --farm-recheck 5000 -RH -P stratum1+tcp://0xхххххххх@/eth.2miners.com:2020ig1/ut9@gmail.com -G --work-timeout 500 --cl-parallel-hash 2 --cl-local-work 256 --cl-global-work 16384 --cl-kernel 1 --display-interval 30

**Comment by AndreaLanfranchi** [comment]
There is an extra "/" after first @ and before hostname.

**Comment by AndreaLanfranchi** [comment]
Also read #1021 

According to https://eth.2miners.com/en/faq they do not accept email addresses.
Thus your command should be

`ethminer -RH -P stratum1+tcp://<etheraddress>.rig1@eth.2miners.com:2020  -G --work-timeout 500 --cl-parallel-hash 2 --cl-local-work 256 --cl-global-work 16384 --cl-kernel 1 --display-interval 30`

--farm-recheck is totally unneeded
