### ISSUE TITLE
undefined reference to `Curl_ipv4_resolve_r'

### ISSUE THREAD

**Issue by RyanF109** [ethereum-mining/ethminer#1122]
When compiling I get this error:

> [ 17%] Built target devcore
[ 32%] Built target hwmon
[ 44%] Built target ethash-cl
[ 55%] Built target ethcore
[ 55%] Built target ethminer-buildinfo-git
[ 64%] Built target ethminer-buildinfo
[ 82%] Built target poolprotocols
[ 94%] Built target apicore
[ 97%] Linking CXX executable ethminer
/home/miner/.hunter/_Base/5cd594b/b4bd535/51e893d/Install/lib/libcurl.a(asyn-thread.c.o): In function `gethostbyname_thread':
asyn-thread.c:(.text+0x105): undefined reference to `Curl_ipv4_resolve_r'
/home/miner/.hunter/_Base/5cd594b/b4bd535/51e893d/Install/lib/libcurl.a(asyn-thread.c.o): In function `Curl_resolver_getaddrinfo':
asyn-thread.c:(.text+0x8cf): undefined reference to `Curl_ipv4_resolve_r'
collect2: error: ld returned 1 exit status
ethminer/CMakeFiles/ethminer.dir/build.make:121: recipe for target 'ethminer/ethminer' failed
make[2]: *** [ethminer/ethminer] Error 1
CMakeFiles/Makefile2:555: recipe for target 'ethminer/CMakeFiles/ethminer.dir/all' failed
make[1]: *** [ethminer/CMakeFiles/ethminer.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by peterwillcn** [comment]
yum install libcurl-devel.x86_64 .  Can fix this issus.

**Comment by RyanF109** [comment]
fixed with:

> rm -Rf ~/.hunter

**Comment by abelardojarab** [comment]
i did same, remove ~/.hunter still same error.

**Comment by yosnoop** [comment]
Same here even after removing the directory. In my case, I had to revert the commit c0c67a8f376602cd0f3e2a91c28f0348a6cc5675 then everything went well.

https://github.com/ethereum-mining/ethminer/commit/c0c67a8f376602cd0f3e2a91c28f0348a6cc5675
