### ISSUE TITLE
Run here to close the program

### ISSUE THREAD

**Issue by zijieli111** [ethereum-mining/ethminer#1124]
m  09:47:24|main    |  ethminer version 0.14.0
  m  09:47:24|main    |  Build: windows / release +git. 24c65cf
 cu  09:47:25|main    |  Using grid size 8192 , block size 128
  i  09:47:25|main    |  Selected pool asia1.ethermine.org:14444
  m  09:47:25|main    |  not-connected
  i  09:47:25|stratum |  Trying 13.250.135.167:14444 ...
  i  09:47:25|stratum |  Connected to asia1.ethermine.org  [13.250.135.167:14444]
  i  09:47:25|stratum |  Spinning up miners...
  i  09:47:25|cuda-0  |  No work. Pause for 3 s.
  i  09:47:25|cuda-1  |  No work. Pause for 3 s.
  i  09:47:25|cuda-2  |  No work. Pause for 3 s.
  i  09:47:25|cuda-3  |  No work. Pause for 3 s.
  i  09:47:25|cuda-4  |  No work. Pause for 3 s.
  i  09:47:25|cuda-5  |  No work. Pause for 3 s.
  i  09:47:25|stratum |  Subscribed to stratum server
  i  09:47:26|stratum |  Authorized worker 0xf7bb4e50640181e37b50ae559456a00740301c7a
  i  09:47:26|stratum |  New pool difficulty:  4.00 gigahashes
  i  09:47:26|stratum |  New job #62880baf...   asia1.ethermine.org [13.250.135.167:14444]
  i  09:47:28|cuda-0  |  Initialising miner 0
  i  09:47:28|cuda-1  |  Initialising miner 1
  i  09:47:28|cuda-2  |  Initialising miner 2
  i  09:47:28|cuda-3  |  Initialising miner 3
  i  09:47:28|cuda-4  |  Initialising miner 4
  i  09:47:28|cuda-5  |  Initialising miner 5
  m  09:47:30|main    |  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  gpu/2  0.00  gpu/3  0.00  gpu/4  0.00  gpu/5  0.00  [A0+0:R0+0:F0] Time: 00:00
 cu  09:47:31|cuda-5  |  Using device: GeForce GTX 1080  (Compute 6.1)
 cu  09:47:31|cuda-2  |  Using device: GeForce GTX 1060 3GB  (Compute 6.1)
 cu  09:47:31|cuda-0  |  Using device: GeForce GTX 1080  (Compute 6.1)
 cu  09:47:31|cuda-3  |  Using device: GeForce GTX 1060 3GB  (Compute 6.1)
 cu  09:47:31|cuda-4  |  Using device: GeForce GTX 1060 3GB  (Compute 6.1)
 cu  09:47:31|cuda-1  |  Using device: GeForce GTX 1060 3GB  (Compute 6.1)
 cu  09:47:31|cuda-5  |  Set Device to current
 cu  09:47:31|cuda-2  |  Set Device to current
 cu  09:47:31|cuda-0  |  Set Device to current
 cu  09:47:31|cuda-3  |  Set Device to current
 cu  09:47:31|cuda-4  |  Set Device to current
 cu  09:47:31|cuda-1  |  Set Device to current
 cu  09:47:31|cuda-5  |  Resetting device
 cu  09:47:31|cuda-2  |  Resetting device
 cu  09:47:31|cuda-0  |  Resetting device
 cu  09:47:31|cuda-3  |  Resetting device
 cu  09:47:31|cuda-4  |  Resetting device
 cu  09:47:31|cuda-1  |  Resetting device
 cu  09:47:31|cuda-5  |  Allocating light with size: 41286208

**Comment by trtw89** [comment]
increase the buffer size in "my computer - properties"
sorry for my bad english

**Comment by danangfebrian** [comment]
@zijieli111 same error but after increase the buffer size, is work, thx @trtw89

**Comment by chfast** [comment]
Fixed?

**Comment by danangfebrian** [comment]
yeah fixed that issue
