### ISSUE TITLE
undefined reference to `Curl_ipv4_resolve_r' #1122

### ISSUE THREAD

**Issue by abelardojarab** [ethereum-mining/ethminer#1129]
Scanning dependencies of target ethash-cuda
[ 59%] Building CXX object libethash-cuda/CMakeFiles/ethash-cuda.dir/CUDAMiner.cpp.o
[ 62%] Linking CXX static library libethash-cuda.a
[ 62%] Built target ethash-cuda
Scanning dependencies of target ethash-cl
[ 64%] Building CXX object libethash-cl/CMakeFiles/ethash-cl.dir/CLMiner.cpp.o
[ 67%] Linking CXX static library libethash-cl.a
[ 72%] Built target ethash-cl
Scanning dependencies of target ethcore
[ 75%] Building CXX object libethcore/CMakeFiles/ethcore.dir/EthashAux.cpp.o
[ 78%] Building CXX object libethcore/CMakeFiles/ethcore.dir/BlockHeader.cpp.o
[ 81%] Building CXX object libethcore/CMakeFiles/ethcore.dir/Miner.cpp.o
[ 83%] Linking CXX static library libethcore.a
[ 83%] Built target ethcore
Scanning dependencies of target apicore
[ 86%] Building CXX object libapicore/CMakeFiles/apicore.dir/Api.cpp.o
[ 89%] Building CXX object libapicore/CMakeFiles/apicore.dir/httpServer.cpp.o
[ 91%] Building CXX object libapicore/CMakeFiles/apicore.dir/ApiServer.cpp.o
[ 94%] Linking CXX static library libapicore.a
[ 94%] Built target apicore
Scanning dependencies of target ethminer
[ 97%] Building CXX object ethminer/CMakeFiles/ethminer.dir/main.cpp.o
[100%] Linking CXX executable ethminer
/home/abelardojara/.hunter/_Base/5cd594b/a013b3f/51e893d/Install/lib/libcurl.a(asyn-thread.c.o): In function `gethostbyname_thread':
asyn-thread.c:(.text+0x15): undefined reference to `Curl_ipv4_resolve_r'
/home/*******/.hunter/_Base/5cd594b/a013b3f/51e893d/Install/lib/libcurl.a(asyn-thread.c.o): In function `Curl_resolver_getaddrinfo':
asyn-thread.c:(.text+0x85a): undefined reference to `Curl_ipv4_resolve_r'
collect2: error: ld returned 1 exit status
ethminer/CMakeFiles/ethminer.dir/build.make:125: recipe for target 'ethminer/ethminer' failed
make[2]: *** [ethminer/ethminer] Error 1
CMakeFiles/Makefile2:610: recipe for target 'ethminer/CMakeFiles/ethminer.dir/all' failed
make[1]: *** [ethminer/CMakeFiles/ethminer.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

I tried removing ~/.hunter as mentioned in other post [https://github.com/ethereum-mining/ethminer/issues/1122](https://github.com/ethereum-mining/ethminer/issues/1122) and it did not solve this issue.

**Comment by AndreaLanfranchi** [comment]
Go ahead on issue #1122
