### ISSUE TITLE
Fatal GPU error: CUDA error in func dev::eth::CUDAMiner::search at line 461 unspecified launch failure Terminating

### ISSUE THREAD

**Issue by vendim1966** [ethereum-mining/ethminer#1130]
Build:
0.15.0 dev 10.

Error:
"Fatal GPU error: CUDA error in func dev::eth::CUDAMiner::search at line 461 unspecified launch failure Terminating."

Description of a problem:
On two farms of a mistake appear with a different frequency. On one thicket (10-15 times a day), on another is more rare (4-5 times a day).
On farms on 4 video cards, and the message at the same time appears on each video card.
After that the mayner finishes the work.

At the Windows 10 updating to the version 1803 the problem began to be shown after 8-10 share (1-2 minutes after start).
Forcedly downgrade windows 10 back to version 1709 was necessary.

Configuration:
CPU: AMD Phenom II X3 - X4.
RAM: 8Gb.
OS: Windows 10 (1709), build 16299.431.
Driver NVIDIA: 391.35

Question:
In what can be a problem? What is occurs in this release in line 461?

**Comment by AndreaLanfranchi** [comment]
Same as 
#902 
#793 
#239
