### ISSUE TITLE
Genereting DAG issue with à sixth card

### ISSUE THREAD

**Issue by Secullus** [ethereum-mining/ethminer#1134]
Hello.
I have a issue with Ethminer release 0.14 since adding a sixth GTX 1050ti to my RIG, it crash when it displays "Generating DAG for GPU # 5".
I am on Windows 10, nvidia drivers are up to date and my motherboard is an Asus B250 Mining Expert.
The card and the riser worked previously without worries in another computer
When I add the option --cuda-devices 0 1 2 3 4 I have no problem, with --cuda-devices 5 only, no problem.
Thanks for your help.

**Comment by AndreaLanfranchi** [comment]
You might be running out of virtual memory.
Either expand windows' page file or try loading DAG in sequential mode

`ethminer.exe [yourusualarguments] --dag-load-mode sequential`

**Comment by Secullus** [comment]
Thank you Andrea for your quick response.
Indeed, I needed to change the amount of virtual memory.
It was automatically set and I put it at 48Gb.
Thanks again.
Best regards.
François.
