### ISSUE TITLE
[0.15.0.dev11] Error: Insufficient CUDA driver: 9010. Not bug. You must upgrade CUDA to 9.2

### ISSUE THREAD

**Issue by Mycopka** [ethereum-mining/ethminer#1138]
Ethminer from archive  **ethminer-0.15.0.dev11-Linux.tar.gz**

On start have following:
```
  m  21:17:41|ethminer|  ethminer 0.15.0.dev11
  m  21:17:41|ethminer|  Build: linux / release
  Error: Insufficient CUDA driver: 9010
```

**nvidia-smi** 
```
Tue May 22 21:15:33 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.48                 Driver Version: 390.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    On   | 00000000:01:00.0  On |                  N/A |
| 34%   56C    P0    61W / 150W |    356MiB /  8118MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
```

**nvcc --version**
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
```

With ethminer version 0.14.0 and 0.15.0.dev10 have no problems.

**Comment by jefferson-1** [comment]
try 390.59 from Nvidia? dev11 is compiled with cuda 9.2 and on Win10 works fine with latest nvidia drivers.

**Comment by Mycopka** [comment]
Oh, yes. Now I see "Travis CI: Build with g++-7, upgrade CUDA to 9.2" comments in commits.
Issue can be closed.

**Comment by celavek** [comment]
The explanation here seems inconsistent. I have just built v0.14.0 with CUDA 9.2 and I get the same error ...

**Comment by jefferson-1** [comment]
Not sure about v0.14 ... I know 0.15 has the CUDA 9.2 code. You also must have the Linux 390.59 drivers from Nvidia for Linux or the latest drivers for Windows that also includes CUDA 9.2.

The drivers must match the code that ethermine uses.

**Comment by celavek** [comment]
Well something does not match. I just checked out  the 0.15.0dev11, built and get the same error.
I'm on Debian 9, I have the proper CUDA, the proper driver and all that jazz

```
Starting ethminer on 2 device(s) ...
  m  23:17:51|ethminer|  ethminer 0.15.0.dev11
  m  23:17:51|ethminer|  Build: linux / release
Error: Insufficient CUDA driver: 9010


Wed May 23 23:08:30 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.59                 Driver Version: 390.59                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0  On |                  N/A |
| 29%   59C    P0    34W / 120W |     53MiB /  6077MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 106...  Off  | 00000000:02:00.0 Off |                  N/A |
| 26%   58C    P0    32W / 120W |      8MiB /  6078MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       469      G   /usr/lib/xorg/Xorg                            51MiB |
|    1       469      G   /usr/lib/xorg/Xorg                             6MiB |
+-----------------------------------------------------------------------------+


nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Wed_Apr_11_23:16:29_CDT_2018
Cuda compilation tools, release 9.2, V9.2.88

```
I tried the debug version but I cannot get more from the log ... any suggestions?

**Comment by chfast** [comment]
The problem is in nvidia driver, not the CUDA SDK,

**Comment by Scorpion2185** [comment]
@celavek How do you installed cuda 9,2? I downloaded the cuda toolkit deb network (https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1604&target_type=debnetwork) but after the installation i was unable to login. I had to run `sudo apt-get purge nvidia-*` for fix this problem, reinstall nvida-390 driver (`sudo apt-get install nvidia-390`) and also the cuda toolkit  (`sudo apt install nvidia-cuda-toolkit`).
Now if i run `nvcc --version` i have the 7.5.17 version 
```
nvcc` --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
```
But if i run this command i have the 9.2.88 version
```
cat` /usr/local/cuda/version.txt
CUDA Version 9.2.88
```

**Comment by invidtiv** [comment]
Same issue here, 

  m  03:45:06|ethminer|  ethminer 0.15.0.dev11-79+commit.83b75508
  m  03:45:06|ethminer|  Build: linux/release
Error: Insufficient CUDA driver: 9010

terminate called without an active exception
./miner.sh: line 40:  3437 Aborted                 

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Wed_Apr_11_23:16:29_CDT_2018
Cuda compilation tools, release 9.2, V9.2.88


Driver Version: 390.59    

Any help welcomed

**Comment by Scorpion2185** [comment]
How do you precisely set manually the path?

**Comment by AndreaLanfranchi** [comment]
@invidtiv you may have to reinstall nvidia drivers.

```
sudo apt-get purge nvidia-*
sudo apt-get install nvidia-390
```

**Comment by invidtiv** [comment]
@AndreaLanfranchi Thanks , actually the issue was no purge from apt-get with the * , had to manually purge every nvidia , don t know why...
Got it working, actually installing with sudo apt-get install nvidia-390 it simply did not work for me .
I downloaded the cuda from nvidia cuda_9.2.88.1_linux.run , plus the NVIDIA-Linux-x86_64-396.24.run.
And installed the driver from the cuda install setup.
Again don t know why, I had these issues , they are not etherminer issues, sudo apt-get purge nvidia* always worked for me previously...

@Scorpion2185 
just write
PATH=$PATH:/usr/local/cuda-9.2/bin
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-9.2/bin/../lib:/usr/local/cuda-9.2/bin/../lib64
It will add the path... you are setting PATH=$PATH:(new path to include)

**Comment by Scorpion2185** [comment]
@invidtiv  i wrote in the terminal:
```
PATH=$PATH:/usr/local/cuda-9.2/bin
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-9.2/bin/../lib:/usr/local/cuda-9.2/bin/../lib
```
And always get:
```
nvcc` --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
```
I used `sudo apt-get install cuda` and again i wasn' t be able to login, and i had to do all the things that i said before to fix it.

**Comment by invidtiv** [comment]
@Scorpion2185 
sudo apt-get install cuda installs cuda7.5 not cuda 9.2
use this 
sudo apt-get purge nvidia-*
then this to check that you removed everything
dpkg --list 'nvidia*'
Download from nvidia site nvidia cuda_9.2.88.1_linux.run
run it... it will be fixed..

**Comment by Decryptic** [comment]
I am having the same issue.

` m 14:07:54 ethminer ethminer 0.16.0.dev0+commit.eff28d2e
 m 14:07:54 ethminer Build: linux/release
Error: Insufficient CUDA driver: 9010

terminate called without an active exception
./start.sh: line 1:  4122 Aborted                 (core dumped) /home/enigma/Git/ethminer/build/ethminer/ethminer -U --cuda-devices 1 -P stratum+ssl://snip.x@us1.ethermine.org:5555`

I installed the nvidia-390 driver with apt, and it works fine. I installed cuda 9.2 with the runfile provided by nvidia and it seems to have installed successfully. Any help would be appreciated.

**Comment by chfast** [comment]
I have the same issue when nouveau driver is used
```
lsmod | grep nouveau
```

**Comment by samr28** [comment]
Was a solution ever confirmed for this issue? I just installed the latest drivers from Nvidia's website and ran into this issue. I don't have a `/usr/local/cuda` folder which makes me think something went wrong but I didn't run into any issues when installing. Do I need to install cuda separately?

**Comment by AndreaLanfranchi** [comment]
Yes you need to install CUDA separately.
