### ISSUE TITLE
15.0 dev11 : -S is no longer supported and -P does not support email address as used by nanopool

### ISSUE THREAD

**Issue by satori-q3a** [ethereum-mining/ethminer#1139]
nanopool uses the eth-address and worker-id in the form of:

  {eth-address}.{workername}/{name@email.com}

where the email address was also used as an optional password to the user's nanopool page to set the payout limit, which the old "-S" switch was able to pass onto nanopool when ethminer connected.

Now that "-S' usage is rejected by 15.0-dev11, using the "-P" fails when adding the email-address as part of the parameter:

fails:: -P stratum+tcp://{eth-address}.{worker-id}/{name@email.com}@eth-us-east1.nanopool.org:9999

fails:: -P stratum+tcp://{eth-address}.{worker-id}/{name%40email.com}@eth-us-east1.nanopool.org:9999

the error it gives is:
Could not resolve host 0x{eth-address}.workername, no such host is known

note that without the email address, ethminer connects and sets up the worker correctly:

valid:: -P stratum+tcp://{eth-address}.{worker-id}@eth-us-east1.nanopool.org:9999

**Comment by satori-q3a** [comment]
The above format does connect but the worker id and email address are not passed to nanopool

**Comment by AndreaLanfranchi** [comment]
Related to #1075

**Comment by AndreaLanfranchi** [comment]
At the moment there is no quick solution.
You have to roll back to previous version.

**Comment by AndreaLanfranchi** [comment]
Wait a minute. Try this.

`-P stratum+tcp://<ethaddress>.<workername>@eth-us-east1.nanopool.org:9999/email@mail.com`

**Comment by satori-q3a** [comment]
hehe... already did, it passes the worker id but not the email address, tho it does connect correctly.

**Comment by AndreaLanfranchi** [comment]
Well actually the latest sample should send mining.authorize with 

`<ethaddress>.<workername>/<email>`

Just read in the code.

**Comment by satori-q3a** [comment]
should, but {ethaddress}.{workername} is mistaken for the host name

**Comment by AndreaLanfranchi** [comment]
What do you mean mistaken ?
You just said it's the syntax nanopool wants.

**Comment by satori-q3a** [comment]
When ethminer run, it parses {ethaddress}.{workername} as the pool to connect to, hense the error:

"Could not resolve host {eth-address}.workername, no such host is known"

**Comment by AndreaLanfranchi** [comment]
Do you have any "@" in worker name ?

**Comment by satori-q3a** [comment]
nope... just a plain 6 character worker id of "satori"

**Comment by AndreaLanfranchi** [comment]
> When ethminer run, it parses {ethaddress}.{workername} as the pool to connect to, hense the error:
No it does not.

**Comment by satori-q3a** [comment]
running ethminer with nanopool parms  : 
note: ethaddress has been edited out...

C:\Users\satori\Miner>c:\apps\ethminer-0.15\ethminer --farm-recheck 1000 -U --cuda-grid-size 16384 --cuda-block-size 128 --cuda-parallel-hash 2 -P stratum+tcp://0xethaddress.satori/ename%40gmail.com@eth-us-east1.nanopool.org:9999
  m  14:45:21|main    |  ethminer 0.15.0.dev11
  m  14:45:21|main    |  Build: windows / release
 cu  14:45:21|main    |  Using grid size 16384 , block size 128
  i  14:45:21|main    |  Selected pool 0xethaddress.satori:0
  m  14:45:21|main    |  not-connected
  X  14:45:21|stratum |  Could not resolve host 0xethaddress.satori , No such host is known
  i  14:45:21|stratum |  Disconnected from 0xethaddress.satori  [0.0.0.0:0]
  i  14:45:21|stratum |  Retrying in 3 ...
  i  14:45:22|stratum |  Retrying in 2 ...
  i  14:45:23|stratum |  Retrying in 1 ...

**Comment by AndreaLanfranchi** [comment]
What did I told you to try few posts before ? 

`C:\Users\satori\Miner>c:\apps\ethminer-0.15\ethminer -U --cuda-grid-size 16384 --cuda-block-size 128 --cuda-parallel-hash 2 -P stratum+tcp://0xethaddress.satori@eth-us-east1.nanopool.org:9999/ename@gmail.com
`

**Comment by satori-q3a** [comment]
for nanopool, the format for the authorized worker name is:

0xethaddress.workerid/ename@email.com

when using "-P stratum+tcp://0xethaddress.workeridi@eth-us-east1.nanopool.org:9999/ename@gmail.com"
15.0 dev11 ignores "/ename@email.com" and does not pass it as part of the worker name

**Comment by Dafrankster** [comment]
I am also experiencing this issue where the email is not recognized. It creates a bug in my pool (nanopool) since the email is not reported correctly.

**Comment by Dafrankster** [comment]
I had my .bat file set up like your example 2, and I can not lower my withdraw fee. I dont know if this is because the emails are not reporting correctly. I updated my .bat file to your example 3, but I have no way to check if the email is syncing now. Are the commands -G & -P still required? Thanks!
ex] ethminer.exe --farm-recheck 200 -G  -P <from your example3>

**Comment by AndreaLanfranchi** [comment]
> and I can not lower my withdraw fee

Which is the reason of the error (if any) ?
Do you realize you have to reach a score of 10 (minimum) on Nanopool before you can ask for any changes in your payout threshold ?
Do you realize there is a **minimum** payout you can not go below ?

**Comment by AndreaLanfranchi** [comment]
> Are the commands -G & -P still required? Thanks!

-G means use OpenCL (needed for AMD cards)
- P is the command argument where you define the stratum connection (-P stratum2+tcp:// ...)

So yes ... they are both needed.

**Comment by Dafrankster** [comment]
>-G means use OpenCL (needed for AMD cards)
-P is the command argument where you define the stratum connection (-P stratum2+tcp:// ...)
So yes ... they are both needed.

Great, thanks!

>Which is the reason of the error (if any) ?
Do you realize you have to reach a score of 10 (minimum) on Nanopool before you can ask for any changes in your payout threshold ?
Do you realize there is a minimum payout you can not go below ?

Ever since i switched to example 3 from example 2, nano has shown my primary worker as offline, but the hash speed is still recorded for my overall eth account. The worker has a score over 10, and I am only trying to meet the minimum payout. It just says incorrect password when I try to change the settings for the payout.

**Comment by AndreaLanfranchi** [comment]
>Ever since i switched to example 3 from example 2, nano has shown my primary worker as offline, but the hash speed is still recorded for my overall eth account. The worker has a score over 10, and I am only trying to meet the minimum payout. It just says incorrect password when I try to change the settings for the payout.

How many workers do you have ?
Do they **all** share the same email address as password ?

**Comment by Dafrankster** [comment]
I only have one worker. I switched the .bat file to the example 3 above, and it showed the worker as offline but the address was still reporting hash rates. I just switched back to the example 2 .bat file with the same email. Now it shows the worker as online, but wont recognize the email address- it still says 'incorrect password.' I just switched emails in the script and still no luck.

**Comment by AndreaLanfranchi** [comment]
> Now it shows the worker as online, but wont recognize the email address- it still says 'incorrect password.' I just switched emails in the script and still no luck.

How much time do you wait ?
In my tests it took over 30 minutes to allow me change settings using my email address as password.

**Comment by PrieureDeSion** [comment]
> Two things :
> 
> > for nanopool, the format for the authorized worker name is:
> > 0xethaddress.workerid/ename@email.com
> 
> That's not completely true. Nanopool supports both the "dot" separation of workername
> 
> `ethminer.exe --farm-recheck 200 -G -S eth-eu1.nanopool.org:9999 -O YOUR_ADDRESS.YOUR_WORKER/YOUR_EMAIL`
> 
> and the "slash" separation.
> 
> `EthDcrMiner64.exe -epool eth-eu1.nanopool.org:9999 -ewal YOUR_ETH_ADDRESS/YOUR_WORKER_NAME/YOUR_EMAIL -mode 1`
> 
> This said you have also to bind with ethminer help which reports
> 
> ```
>         Example 1 : stratum+ssl://0x012345678901234567890234567890123.miner1@ethermine.org:5555
>         Example 2 : stratum1+tcp://0x012345678901234567890234567890123.miner1@nanopool.org:9999/john.doe@gmail.com
>         Example 3 : stratum1+tcp://0x012345678901234567890234567890123@nanopool.org:9999/miner1/john.doe@gmail.com
> ```
> 
> So proper connection to nanopool is clearly stated in Example 3 which, actually, works perfectly (personally tested)

@AndreaLanfranchi I tried following this, but it gives me the following output:
<img width="652" alt="image" src="https://user-images.githubusercontent.com/14254187/80079470-2dec1a00-8505-11ea-8220-207fe4fd21a3.png">

Looks like the text following `@` is parsed differently and is being treated as the pool address?

**Comment by vburenin** [comment]
Can you guys encode @ as %40?
