### ISSUE TITLE
inaccurate hashrates on ethermine.org 

### ISSUE THREAD

**Issue by tex6246** [ethereum-mining/ethminer#114]
i am noticing that possibly the hashrate that the software is reporting to what ethermine reports is inaccurate by as much as 10h/s 
both 0.11.0rc1 and rc2 are both affected with it also not reporting Reported hashrate on ethermine.
![hashrate](https://user-images.githubusercontent.com/29905340/27845439-bc391992-60ec-11e7-9207-7de1b0d6ddb0.PNG)
as per the green line in pic.
i'll do more testing and try on other pools for more info

**Comment by jimmykl** [comment]
This has been raised here https://github.com/ethereum-mining/ethminer/issues/49 if you could add your feedback to that issue it will help to have it all in one place – cheers!

**Comment by tex6246** [comment]
will do, i'll close this and post there
