### ISSUE TITLE
0.15.0.dev11 Error: `GLIBCXX_3.4.22' not found

### ISSUE THREAD

**Issue by Starkot** [ethereum-mining/ethminer#1140]
ethminer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/user/ethminer/ethminer)

Linux user 4.13.0-41-generic #46~16.04.1-Ubuntu SMP Thu May 3 10:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chfast** [comment]
That's because I upgraded the compiler to GCC 8.

**Comment by Scorpion2185** [comment]
try installing this: 
sudo apt-get install libstdc++6
It solved the problem to me.

**Comment by chfast** [comment]
Fixed in #1214
