### ISSUE TITLE
ssl or tcp for ethermine.org

### ISSUE THREAD

**Issue by BoriZka67** [ethereum-mining/ethminer#1143]
stratum+ssl or +tcp. what is better for ethermine.org?
Thanks.

**Comment by AndreaLanfranchi** [comment]
Depends on your needs.

stratum+ssl encodes all messages to pool server thus mitigating the "man-in-the-middle" attack.
stratum+tcp sends all messages in plain text to pool

Neither the former not the latter have any impact on your mining "efficiency" but is to be noted that "encoding" (in SSL mode) of all messages might cause tiny amounts of time in messages delivery.

It's a trade-off ... you choose.

**Comment by BoriZka67** [comment]
Thanks for the detailed answer
