### ISSUE TITLE
Ethminer v 0.14.0 (but not other versions) flagged as Virus or Malware by the major web browsers

### ISSUE THREAD

**Issue by gabefair** [ethereum-mining/ethminer#1145]
I noticed today (not previously) that the major browsers are flagging v0.14 as containing malware. The beta releases and previous releases are not being flagged.

**Comment by AndreaLanfranchi** [comment]
Nothing we can do.
The code is open and here to read. No hidden malware.

For reference look at all those threads.
https://github.com/ethereum-mining/ethminer/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed++virus
