### ISSUE TITLE
-S -FS -O is deprecated

### ISSUE THREAD

**Issue by L0e1i** [ethereum-mining/ethminer#1148]
Hello together,

I have 2 AMD cards (RX570 4GB and 8 GB) and wanted to try ethminer.

My batch file looks like that: 

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

ethminer.exe --farm-recheck 200 -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x20aaCAd8d876D8703f1D9394f2c659eb0462bb90.PC

I get the warnings that -S, -FS and -O is deprecated and that no CUDA driver is found. When I put a -G instead of -U the warning about the driver goes away but the others stay and it won't start. My driver is the AMD BETA Blockchain driver. Does anyone know what the problem is? Can use the latest driver to get the best performance or do I have to stick to the Blockchain driver?

**Comment by AndreaLanfranchi** [comment]
ethminer --help is your friend (aside the fact you're making confusion among cuda and openCL)

-S argument has been dropped.
What was

`-S eu1.ethermine.org:4444 -O 0x20aaCAd8d876D8703f1D9394f2c659eb0462bb90.PC
`

becomes now

`-P stratum+tcp://0x20aaCAd8d876D8703f1D9394f2c659eb0462bb90.PC@eu1.ethermine.org:4444`

Second matter ... CUDA.
You have AMD Rx570 cards so CUDA (-U) could never work on them as CUDA is only for NVIDIA cards.
