### ISSUE TITLE
stratum[10133]: segfault occurs on reconnect

### ISSUE THREAD

**Issue by gordan-bobic** [ethereum-mining/ethminer#1149]
0.14 release on Linux.
Observed on multiple machines with different hardware.

**Comment by AndreaLanfranchi** [comment]
Post logs before error happens.
Without we can not understand where it happened.

**Comment by gordan-bobic** [comment]
It coincides with a message that it is aborting because it couldn't connect to the stratum for 2 seconds. I'll add logs next time I catch it.

**Comment by AndreaLanfranchi** [comment]
Ok ... got it ... 
We're addressing it in #1135

**Comment by chfast** [comment]
@gordan-bobic can you test this build from Reconnect PR? https://1347-89067146-gh.circle-artifacts.com/0/ethminer

**Comment by gordan-bobic** [comment]
That binary doesn't work at all for me:
```
ethminer: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ethminer)
ethminer: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ethminer)
ethminer: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ethminer)
ethminer: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ethminer)
```

**Comment by AndreaLanfranchi** [comment]
@gordan-bobic your issue is not related to this.
Feel free to open another one if your problem persists
