### ISSUE TITLE
How to stop ethminer properly

### ISSUE THREAD

**Issue by xushijie** [ethereum-mining/ethminer#1155]
I run ethminer in Ubuntu system with 4G-memory AMD GPU card. Sometimes, I stop the miner by kill command.  But later, I found i was no longer able to start it again. Then I  tried using `--list-devices` option, and it shows that the GPU memory was only about 1G AMD. This memory size is not sufficient for mining. 

In this case, the only way I can do is to restart the Ubuntu system, and then everything works again. 

So is there any GPU memory leak in the system?  or is there a proper way to stop the ethminer mining process?  Thanks

**Comment by xushijie** [comment]
kill -9

**Comment by AndreaLanfranchi** [comment]
Use kill -2 (it's like CTRL-C)
