### ISSUE TITLE
Creating DAG buffer failed, OpenCL Error

### ISSUE THREAD

**Issue by 3decimal14159** [ethereum-mining/ethminer#1157]
C:\Users\USER\Desktop\ethminer-0.14.0-Windows\bin>ethminer -F http://eth1.nanopool.org:8888/0xa7B6F27a26b8DD2bDa69A42011277AE45Bd2855a -G -M
Warning: -F is deprecated. Use the -P parameter instead.
  m  10:50:06|main    |  ethminer version 0.14.0
  m  10:50:06|main    |  Build: windows / release +git. 24c65cf
  i  10:50:09|main    |  Found suitable OpenCL device [ BeaverCreek ] with 2146697216  bytes of GPU memory
Benchmarking on platform: CL
Preparing DAG for block #0
 cl  Warming up...10
:50:09|cl-0    |  No work. Pause for 3 s.
 cl  10:50:12|cl-0    |  New seed #00000000...
 cl  10:50:15|cl-0    |  Platform: AMD Accelerated Parallel Processing
 cl  10:50:15|cl-0    |  Device:   BeaverCreek  / OpenCL 1.2 AMD-APP (1800.11)
 cl  10:50:16|cl-0    |  OpenCL kernel: Stable kernel
 cl  10:50:23|cl-0    |  Build info:
 cl  10:50:23|cl-0    |  Creating light cache buffer, size 16776896
 cl  10:50:23|cl-0    |  Creating DAG buffer, size 1073739904
  X  10:50:23|cl-0    |  Creating DAG buffer failed: clCreateBuffer: CL_INVALID_BUFFER_SIZE (-61)
  X  10:50:23|cl-0    |  OpenCL Error: clEnqueueWriteBuffer: CL_INVALID_MEM_OBJECT (-38)
Trial 1...
0
Trial 2...
0
Trial 3...
0
Trial 4...
0
Trial 5...
0

Please help, thanks!

**Comment by stefangordon** [comment]
Looks like a 2GB memory GPU.  Not possible to mine Ethereum.

**Comment by AndreaLanfranchi** [comment]
> i 10:50:09|main | Found suitable OpenCL device [ BeaverCreek ] with 2146697216 bytes of GPU memory

This is the key ... 2 Gb of GPU ram is not enough to mine Ethereum.
You might be able to mine one of these:

- Musicoin
- Expanse
- Ubiq
- Soilcoin

Bottomline ... you can mine any coin based on Ethash PoW which has a DAG size smaller than your GPU ram.
