### ISSUE TITLE
GPU not boosting?

### ISSUE THREAD

**Issue by richh1833** [ethereum-mining/ethminer#116]
Hi! I'm new to github so I'm not sure if I'm doing this right. I've been monitoring one of my miners Gigabyte Windforce 6GB x 8 and I've noticed that one card in particular isn't boosting at all. It's sitting around 1100Mhz and sometimes a bit lower. On the other hand my other cards are hitting 1400-1500Mhz. They're all on the same settings and temps are well below 60. I've used DDU to uninstall drivers and reinstall new ones but it seems to persist.

Is this an issue for others or is this working as intended?

**Comment by jimmykl** [comment]
Github is all about the software – in this case ethminer. Raising an issue should really relate to a problem/bug with ethminer.

That said my advice is every card is different even if they are exactly the same make and model. Your overclocking app should let you select a particular card to overclock. Drop the card in question back to stock and start increasing the clock, I usually add 50MHz a time, mine a while and if it's stable notch it up again until you find it's limit.

It takes a bit of work but once you have the settings note them down and/or save a preset.

If this doesn't work and your card still stays very low you should try posting on a mining hardware or overclocking forum or site.

It would be good if you could close this issue to let the devs concentrate on ethminer work.

**Comment by richh1833** [comment]
Ah yes I understand. This specifically applies to Etherminer which is why I asked here. I tried replicating the problem on Claymore but the issue never appeared. All GPUs remain boosted. All my GPUs are overclocked exactly to the same core clock and memory clocks which is why I'm curious as to why Ethminer isn't utilising that specific GPU and whether it's something that is working as intended or a bug.

Given that power delivery is the same across the board I don't see why that specific GPU isn't boosting under Ethminer but boosting in Claymore?

**Comment by jimmykl** [comment]
Oh I see. Have you reduced your power limit? I found some cards don't like low PL and overclocks. I'm not sure why this would occur with Ethminer and not Claymore but maybe different CUDA programming is stressing the card in different ways?

**Comment by richh1833** [comment]
I would assume that CUDA programming is probably different between Claymore and Ethminer but that wouldn't explain why some cards are getting stressed more than others. I have all my cards on 65% PL but some can still boost higher. Is it possible that they can react differently to my PL settings? 

An observation I've made is that the core does get boosted within the first maybe 3-4 minutes of mining and then it drops while others continue.

**Comment by jimmykl** [comment]
Yeah I suspect a lot of things aren't well optimised in Ethminer, witness the slow text issue on startup a few versions ago. Sometimes it seems part voodoo to get things working optimally.

I'd also double-check the hardware for good measure. I have had cards come right after swapping out a riser or USB cable or even just switching the PCIE slot on the mobo.

**Comment by DLS-bau** [comment]
Increase the power limit 1-3% on the GPU that downclocks more. Not all cards are perfectly equal, not even ones of the same model.

**Comment by jimmykl** [comment]
Hi @richh1833 did you manage to sort out your card? If so and you have nothing more to add to this issue could you please close it?

**Comment by richh1833** [comment]
While I haven't 100% sorted it out, I'll still close it. I appreciate the help. Thanks all!
