### ISSUE TITLE
Combining httpServer and ApiServer so they use the same TCPIP port (like Claymore)

### ISSUE THREAD

**Issue by StefanOberhumer** [ethereum-mining/ethminer#1163]
Claymore uses for http and jsonrpc the same TCPIP port.
Is it possible to determine how to handle the request based on the protocol?
I've checked mongoose and ApiServer classes but I'm not sure if it can be done easily (without writing the whole socket parsing by myself).
Hints and suggestions are welcome.

**Comment by AndreaLanfranchi** [comment]
Generally speaking yes you can identify the type of protocol when a new request comes in.
This said we need to handle with the differences among a persistent socket (which transports json rpc calls) and an http socket (which has an accept->process->send->close lifecycle).
The whole matter leads, imho, to a redesign of the whole API interface:

- An acceptor listening for incoming connection requests on a single port for both services
- A connection handler which handles HTTP methods (primarily GET) separated from Json methods

**Comment by StefanOberhumer** [comment]
Basically - its technically clear what to do....
But I thought someone knows how to deal with high-end classes where I can set up a TCPIP listener and 
* get an event where the analyze of request is already done
* or I can register different handlers based on protocol

**Comment by divinity76** [comment]
could easily make a http header separating the 2, for example, we could have an `X-API: 1` header, stating you're trying to use the API (could even take it further, meaning "api version 1"), or you could have a different endpoint for the api, eg `GET /api/` (this is a rather common solution)

**Comment by AndreaLanfranchi** [comment]
> could easily make a http header separating the 2

Http headers are for http only. This technique would assume **all** calls to be http like.
Actually we need to preserve normal json rpc calls (which transport no headers).

**Comment by AndreaLanfranchi** [comment]
@StefanOberhumer 

> But I thought someone knows how to deal with high-end classes where I can set up a TCPIP listener and

Creating an tcp server is not an issue. If we would want to keep leveraging boost we can have any sort samples to start from (eg. https://www.boost.org/doc/libs/1_50_0/doc/html/boost_asio/tutorial/tutdaytime3/src.html)

But in my opinion we should aim our efforts towards this points :

- define better API functionalities
- combine socket rpc calls and http methods so we get substantially the same behaviour 

At present http interface is readonly while json rpc calls implement an actually functional method (miner_restart) and a still pending method miner_reboot.
"Write" actions should be implemented in HTTP too (POST method ?)
Also I would highly encourage the adoption of some sort of password protection to allow users who may want to control their rigs remotely to not expose unsafe control ports to the web.

**Comment by StefanOberhumer** [comment]
To clearyify what should work - http request and jsonrpc api use same port - without changing the current content of request - eg:
* `wget <RIG_IP>:<PORT>` ==> should result in an saved index.html file
* `Browser: http://<RIG_IP>:<PORT>` ==> should result in a site displayed in the browser
* `(echo "{\"id\":0,\"jsonrpc\":\"2.0\",\"method\":\"miner_getstat1\"}" | netcat <RIG_IP> <PORT>` ==> should result in the jsonrpc result of "miner_getstat1"

**Comment by AndreaLanfranchi** [comment]
Exactly ... but I reiterate you need a single TCP listener which separate HTTP methods (GET/POST) from normal text delimited strings over TCP socket.

**Comment by AndreaLanfranchi** [comment]
At the moment we have a jsonrpc server separated from an http server.
We need to create an, say, API manager (like PoolManager) which acts as a director of the two underlying services.

**Comment by divinity76** [comment]
oh sorry, i thought they were both http-based.  does all JSON RPC requests start with `{` ? (or perhaps spaces are legal, eg `\s*\{` in regex) - because all HTTP requests start with an ASCII A-Z letter (`GET /`, `POST /`, `PUT `/, `HEAD /`, and so on)

**Comment by divinity76** [comment]
oh sorry, i thought they were both http-based. does all JSON RPC requests start with { ? (or perhaps spaces are legal, eg \s*\{ in regex) - because all HTTP requests start with an ascii A-Z letter (GET /, POST /, PUT /, HEAD /, and so on), if a JSON RPC request never starts with A-Z, we can just check if the first byte received, when cast to an uint8_t, is between 65 and 90, to determine if its HTTP or JSON-RPC

**Comment by StefanOberhumer** [comment]
Thanks for your infos and first feedbacks ! 
I'll wait for some possible more feedbacks till I start my tries ....

**Comment by chfast** [comment]
I believe there is some misunderstanding here.
JSON-RPC and HTTP is not the same level. For transporting JSON-RPC requests both HTTP and TCP can be used. So for HTTP request you can separate JSON-RPC from web page requests by inspecting the method (GET vs POST) and/or Content-Type header.

If not sure what error the HTTP server should generate in case of receiving JSON instead of proper HTTP request, but we can plug in a fallback there that also transfers the request to JSON-RPC server.

**Comment by AndreaLanfranchi** [comment]
I believe we might end up reinventing the wheel over and over again.
My very humble opinion is that http is primarily an interface, more a data consumer that a data producer.
Why not simply generate an html page with an embedded javascript which polls methods from jsonrpc source ?

**Comment by divinity76** [comment]
@AndreaLanfranchi `Why not simply generate an html page with an embedded javascript which polls methods from jsonrpc source ?` - unless that source use the HTTP or WebSocket protocols, the javascript engine of most (or all?) web browsers won't allow you to communicate with it (at least not a 2-way communication), you can't use javascript to have a web browser fetch json-rpc data from a server serving it over a raw tcp socket.. it will need to support http or WebSocket.

**Comment by jean-m-cyr** [comment]
Why bother? What would be the advantage of using a single port???

**Comment by divinity76** [comment]
@jean-m-cyr i can't think of any good reasons, but 2 weak ones: 
1: it makes firewall/port-forwarding/whatever management slightly easier

2: the Claymore miner already does it, and we don't wanna be worse than Claymore 😛

**Comment by jean-m-cyr** [comment]
@divinity76 The fact that Claymore does it doesn't mean it makes any sense. I really don't think we should undertake such a non-standard networking approach in Ethminer.

**Comment by StefanOberhumer** [comment]
My basic intention using same port is that the same configs in monitoring software can be used.
Eg: 
* Monitoring is done via rpc API.
* In the monitoring tool the list of rigs have a http link to the website of the rig to easily access it.

In this case I have to determine (on version number) which mining software is running and have to switch the TCPIP port based on mining software to get the miners html site.

**Comment by jean-m-cyr** [comment]
Then get Claymore to adjust.

**Comment by StefanOberhumer** [comment]
It's not a problem for me to adjust my environment appropriate. 
**I sympathize with your views :+1:**

> I really don't think we should undertake such a non-standard networking approach in Ethminer` 

**But:**
I just wanted to add more "standard behaviour" to Ethminer to make monitoring more comfortable
 (even if the "standard" is driven from a closed source application - btw: It seems the whole JSON RPC API implementation into Ethminer was driven by Claymore (see #253))

**Comment by AndreaLanfranchi** [comment]
It's my opinion that the so called "Claymore" standard is probably the worst jsonrpc API implementation ever seen. getstat1 method returns nothing more than an array (instead of a fully flavoured json object). A partial effort has been taken into getstathr ... but still we could do better ... waaayyy better than this.

Who cares claymore ... let's do it our way.

**Comment by StefanOberhumer** [comment]
OK. Feel free to close this issue.
