### ISSUE TITLE
Unrealistic hashrate and no actual work on Mac (AMD)

### ISSUE THREAD

**Issue by WilliamBlais** [ethereum-mining/ethminer#1164]
Hello,

I'm trying to mine with an RX580 on Mac. However, I'm always seeing impossible hashrates and no actual work at the pool. I've tried multiple pools (Nanopool and Ethermine) and checked if it was working correctly on Windows (it does). I also tried multiple releases and compiling from source... still the same error.

The GPU is definitely working as it's hot.

Log sample:
`  m  00:18:23|          Speed 24358.49 Mh/s    gpu/0 24358.49  [A0+0:R0+0:F0]
  m  00:18:24|          Speed 24358.49 Mh/s    gpu/0 24358.49  [A0+0:R0+0:F0]
  m  00:18:24|          Speed 24358.49 Mh/s    gpu/0 24358.49  [A0+0:R0+0:F0]
  ℹ  00:18:24|stratum   Received new job #0x16a667  seed: #7bb6f14a940828054edc1aa9ec9f31e2  target: #000000006df37f675ef6eadf
 cl  00:18:24|cl-0      New work: header #16a66738… target 000000006df37f675ef6eadf5ab9a2072d44268d97df837e6748956e5c6c2116
 cl  00:18:24|cl-0      Switch time 0 ms / 66 us
  m  00:18:24|          Speed 24299.30 Mh/s    gpu/0 24299.30  [A0+0:R0+0:F0]
  m  00:18:24|          Speed 24299.30 Mh/s    gpu/0 24299.30  [A0+0:R0+0:F0]
  m  00:18:24|          Speed 24299.30 Mh/s    gpu/0 24299.30  [A0+0:R0+0:F0]
  m  00:18:24|          Speed 24299.30 Mh/s    gpu/0 24299.30  [A0+0:R0+0:F0]
  m  00:18:24|          Speed 24299.30 Mh/s    gpu/0 24299.30  [A0+0:R0+0:F0]
  m  00:18:24|          Speed 24211.15 Mh/s    gpu/0 24211.15  [A0+0:R0+0:F0]
  m  00:18:24|          Speed 24211.15 Mh/s    gpu/0 24211.15  [A0+0:R0+0:F0]
  m  00:18:24|          Speed 24211.15 Mh/s    gpu/0 24211.15  [A0+0:R0+0:F0]
` 

My start script:
`#!/bin/bash

export GPU_FORCE_64BIT_PTR=0
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_SINGLE_ALLOC_PERCENT=100

./ethminer --farm-recheck 100 --work-timeout 40 --opencl-platform 0 --opencl-device 0 --cl-local-work 128 --cl-global-work 16384 --cl-parallel-hash 2 -G -S eth-eu2.nanopool.org:9999 -FS eth-eu1.nanopool.org:9999 -O address.name/email -SC 2 -SP 1 -RH`

Can anyone help me?

Thank you! 
William

**Comment by AndreaLanfranchi** [comment]
Which release are you compiling from ?
It seems like you're still using old command line arguments which have been dropped in latest releases.
I do not mean this can be the origin of the issue but would help if you could test in on latest source.

**Comment by AndreaLanfranchi** [comment]
Related to #841

**Comment by WilliamBlais** [comment]
@AndreaLanfranchi I've tried with the latest release as well as older ones (so I had to use the old command line arguments). Unfortunately, there is always the same bug; unrealistic hash rate and no work at pool.
