### ISSUE TITLE
ethminer.exe not working on fresh windows install (AMD)

### ISSUE THREAD

**Issue by epolat** [ethereum-mining/ethminer#1165]
i was mining but os get virus and i formatted the device, and i can't start ethminer.exe even --liste-devices, black screen coming up and closed.  i have a 3 rx580, when i look in windows i can see devices(also i see msi afterburner). what is problem for that issue?

**Comment by AndreaLanfranchi** [comment]
Please post the full command line argument you use to start ethminer.

**Comment by epolat** [comment]
ethminer.exe --farm-recheck 200 -S eu1.ethermine.org:4444 -FS eu1.ethermine.org:4444 -O wallet.worker
also 
ethminer -G --list-devices
i get same result.

**Comment by AndreaLanfranchi** [comment]
Please run the following (in a bat file) and report

```
ethminer -G --list-devices
echo %ERRORLEVEL%
pause
```
thank you

**Comment by epolat** [comment]
![4](https://user-images.githubusercontent.com/18308559/40588901-2a6a429a-61d4-11e8-8ef0-a880d41f3861.PNG)

**Comment by AndreaLanfranchi** [comment]
Hmmm ... that's not an ethminer exit code.
There is something wrong with your AMD driver.

A quick search on Google reports that (re)installing updated AMD drivers should help solve the problem.

**Comment by AndreaLanfranchi** [comment]
Also ... I know this may sound crazy but a lot of people complain about this error code and solve resetting Windows' sound scheme to default.
A try is worth it.

**Comment by epolat** [comment]
I did your suggest event formatted the computer but something is wrong, i install driver(blockchain version) and tried to see list of devices, list was empty. You have an any idea of that problem ?

**Comment by AndreaLanfranchi** [comment]
Please see this comment
https://github.com/ethereum-mining/ethminer/issues/1182#issuecomment-393898692

Apparently it's an issue with latest Windows Update(s)

**Comment by epolat** [comment]
i remove all update of windows but nothing changed , i get same error, it seems complex problem.

**Comment by aconite33** [comment]
I changed my windows sounds from "Windows Default" to "No sounds" then back to "Windows Default". Magically fixed this problem. Using AMD and ethminer 14.0. Windows 10.

**Comment by divinity76** [comment]
@AndreaLanfranchi that code, -1073741819, means ethminer tried to access unallocated memory. you can get the same result by compiling & running the following C code: 
`int main() {*((int*)5)=1;}`

it might be an ethminer bug brought to light by a recent windows update, idk, anyway, someone should run it through a debug build with a debugger to see which line it occurs on

**Comment by AndreaLanfranchi** [comment]
@divinity76 you _may_ be right but I underline those facts:

- Issue is noticed on Windows only 
- Error code -1073741819 is widely reported to be some sort of file system error (google search)
- Until recent Windows updates (as you confirm) this did not happen

Following the above workaround posted by @aconite33 I believe problem is not in the code but in something related to "path" search of Windows (maybe a directory left in path env is no more accessible ?).
As window searches for components in current directory first and then through any directory listed in the path environment the workaround above makes sense.

Due to this I would make a very simple test.

1. Add ethminer's directory as first in path environment
2. Launch ethminer from outside it's own directory 
3. See what happens

If ethminer runs properly then it's positively a Windows problem while enumerating/checking path's directories.

**Comment by AndreaLanfranchi** [comment]
Let me add another thing. It may be also an incompatibility with Travis builds which are published as release. 

It would be interesting to know if someone suffering from this issue may try to build locally directly from source.

**Comment by divinity76** [comment]
-1073741819 as hex is [c0000005](https://ideone.com/cjLNLc), and the error c0000005 is widely reported to be a memory access violation.

**Comment by AndreaLanfranchi** [comment]
So how do you explain the above workaround ?

**Comment by epolat** [comment]
thank you for your answer, i'm so unhappy for this issue, that problem since 25th May. I will change operating system toninght. In addition, i checked graphics cards one by one, all of them working properly. After change os, i will write status.

**Comment by divinity76** [comment]
@epolat AMD officially support for Ubuntu 16.04 with their drivers, and you can run Ubuntu 16.04 and Windows 10 in multiboot, you don't have to get rid of win10 just to test which OS works better

**Comment by divinity76** [comment]
@epolat oh btw, got some time? can you contact me on discord takeoded#1532 or facebook https://www.facebook.com/hanshenrik.bergan or email divinity76+spam@gmail.com ? i'd like to poke around on your win10 system a bit, see if i can get to the bottom of the out-of-folder crash

**Comment by efrasyad** [comment]
Any update on this?

**Comment by epolat** [comment]
yep, @divinity76 helps me and solved. if @divinity76 will avaliable, he will explain.

**Comment by efrasyad** [comment]
sounds good, it seems other are facing a similar problem and this could help them.

**Comment by AndreaLanfranchi** [comment]
Please share the solution and help us identify whether it's an Ethminer's problem or it' OS related.
Thank you.

**Comment by divinity76** [comment]
unfortunately, i don't know how we `fixed it`, we did a lot of different things to attempt to fix it, and managed in the end, 

(from here on, "same problem" = "the same, or a similar problem")
here's the significant events (there was lots in between) that i remember: 

* windows 10 - same problem
* trying to compile a custom windows version with debugging symbols (compiling with -g), after several hours, failed (can someone please write a guide on that? after hours of trying, i couldn't get it to build with debugging enabled on Windows/MSVC - but managed in minutes to do the same in linux )
* reformat it with Xubuntu 16.04, letting Xubuntu install the GPU drivers - same problem
* reformatted it with Ubuntu 16.04 Server Edition, installing the amdgpu-pro drivers from https://support.amd.com/en-us/download/linux with the command `./amdgpu-pro-install -y`  - same problem
* reformatted with Ubuntu 16.04 Server Edition again, and installed the GPU drivers from amd.com , this time with the parameters `./amdgpu-pro-install --opencl=legacy,pal --headless`  , and *the problem magically vanished.*   (but iirc, initially i got some errors installing with the `--headless` parameter, had to run an `apt install <something, i forgot exactly what>` command before it accepted the `--headless` parameter)

**Comment by AndreaLanfranchi** [comment]
I believe `--headless` replaces the deprecated `--compute` argument: maybe this is the key.

**Comment by AndreaLanfranchi** [comment]
Seems a solution has been found. Closing.

**Comment by fenlasonb** [comment]
the listed workaround appears not to work for me?

C:\Users\CrypteyMiney\Desktop\bin>ethminer.exe -U -P stratum1+ssl://0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney@us1.ethermine.org:5555 -v 9
 m 17:33:09 main     ethminer 0.16.0.dev1
 m 17:33:09 main     Build: windows/release
cu 17:33:09 main     Using grid size: 8,192, block size: 128

C:\Users\CrypteyMiney\Desktop\bin>echo %ERRORLEVEL%
-1073741819


also tested with bat file

C:\Users\CrypteyMiney\Desktop\bin>ETHminerNvidia_only.bat

C:\Users\CrypteyMiney\Desktop\bin>ethminer.exe -U -P stratum1+ssl://0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney@us1.ethermine.org:5555 -v 9
 m 17:31:21 main     ethminer 0.16.0.dev1
 m 17:31:21 main     Build: windows/release
cu 17:31:21 main     Using grid size: 8,192, block size: 128

C:\Users\CrypteyMiney\Desktop\bin>echo -1073741819
-1073741819

**Comment by divinity76** [comment]
does anybody know how to compile a debug build of ethminer with MSVC on windows?

**Comment by fenlasonb** [comment]
also want to note that this is on a fresh installed computer. no windows updates. disabled updates via dpo and services.msc.

it was running fine. rebooted and this error occured.
