### ISSUE TITLE
nicehash unknown method exception 

### ISSUE THREAD

**Issue by salihcirgan** [ethereum-mining/ethminer#1168]
hi,
ethminer no longer runs with nicehash. Also 0.13 and 0.15 gives the same error. Any idea what is wrong?

m 09:14:08|ethminer| ethminer version 0.14.0
m 09:14:08|ethminer| Build: linux / release +git. 24c65cf
cu 09:14:08|ethminer| Using grid size 8192 , block size 128
ℹ 09:14:08|ethminer| Selected pool daggerhashimoto.eu.nicehash.com:3353
m 09:14:08|ethminer| not-connected
ℹ 09:14:08|stratum | Trying 169.51.33.8:3353 ...
ℹ 09:14:08|stratum | Connected to daggerhashimoto.eu.nicehash.com [169.51.33.8:3353]
ℹ 09:14:08|stratum | Spinning up miners...
ℹ 09:14:08|cuda-0 | No work. Pause for 3 s.
ℹ 09:14:08|cuda-1 | No work. Pause for 3 s.
ℹ 09:14:08|stratum | Subscribed to stratum server
ℹ 09:14:08|stratum | Authorized worker xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.testme
✘ 09:14:08|stratum | Got unknown method [ mining.set_difficulty ] from pool. Discarding ...
terminate called after throwing an instance of 'boost::exception_detail::clone_impl&lt;dev::BadHexCharacter&gt;'
what(): BadHexCharacter
Aborted

**Comment by AndreaLanfranchi** [comment]
For nicehash you have to use stratum2

-P stratum2+tcp://....

Sent from mobile. Apologies for brevity and typos.

In data 27 maggio 2018 20:55:09 Salih CIRGAN <notifications@github.com> ha 
scritto:

**Comment by salihcirgan** [comment]
Thank you Andrea. Works!
