### ISSUE TITLE
Question: how to force an error in the miner?

### ISSUE THREAD

**Issue by jimmykl** [ethereum-mining/ethminer#117]
Does anyone know a foolproof way to force the miner to error out?

I am testing a watchdog script which monitors the output of the miner but can't make the miner generate an error!

I've tried extreme under/overclocking but that just makes the whole rig hang rather than the actual miner.

**Comment by JHGitty** [comment]
You could try to remove the internet connection from the miner - is this a type of error you want to have? Or what type of error do you want to handle?

What could happen on the miner?
a) a GPU is failing (e.g. too much Overclocking)
b) the internet connection is lost (no connection to pool address)
c) the whole system is hanging
d) no (or too less) GPU are found on start of miner

What else could happen?

**Comment by jimmykl** [comment]
Good ideas thanks @JHGitty 👍 At this stage I just want to be able to reliably generate a known error so I can begin figuring out how to parse the output and the internet connection one is good for this.
