### ISSUE TITLE
cant build DBUS on linux

### ISSUE THREAD

**Issue by reqshark** [ethereum-mining/ethminer#1175]
```cmake
libpoolprotocols/PoolManager.h:11:21: fatal error: DBusInt.h: No such file or directory
```
point to the correct location from PoolManager.h I got another no such file
```cmake
ethminer/DBusInt.h:3:23: fatal error: dbus/dbus.h: No such file or directory
```
where is that header supposed to be?

**Comment by divinity76** [comment]
it's part of [D-Bus](https://www.freedesktop.org/wiki/Software/dbus/) (specifically the libdbus C api), to quote freedesktop.org:  released versions can be downloaded from the releases directory on dbus.freedesktop.org and are available in all major Linux distributions. <big><big><big><big><big>**If in doubt, use your distribution's packages**</big></big></big></big></big>

**Comment by reqshark** [comment]
correct, my `4.10.0-28-generic 16.04.2-Ubuntu` needed to run:
```bash
apt install libdbus-1-dev
```

thank you

(btw im just trying to manage a certain few GPUs that get too hot during the summer)

**Comment by AndreaLanfranchi** [comment]
>(btw im just trying to manage a certain few GPUs that get too hot during the summer)

You can leverage, without the need of DBUS, new CLI arguments --tstart / --tstop

**Comment by reqshark** [comment]
sounds very useful, 

ya forget listening to DBUS, `tstart` and `tstop` is exactly what i need this summer!

thank you @AndreaLanfranchi
