### ISSUE TITLE
Ethminer stops working after receiving job

### ISSUE THREAD

**Issue by Algomorph** [ethereum-mining/ethminer#1177]
Hi! I'm trying out the latest git version with the new "P" syntax, here's what happens:

ethminer -P stratum+ssl://MYWALLET.myworker@us1.ethermine.org:5555 -U --report-hashrate  --farm-recheck 200

  m  09:21:39|ethminer|  ethminer 0.15.0.dev11-50+commit.7f621626.dirty
  m  09:21:39|ethminer|  Build: linux / release
 cu  09:21:39|ethminer|  Using grid size 8192 , block size 128
  m  09:21:39|ethminer|  not-connected
  ℹ  09:21:39|main    |  Selected pool us1.ethermine.org:5555
  ℹ  09:21:39|stratum |  Trying 18.219.59.155:5555 ...
  ℹ  09:21:39|stratum |  Connected to us1.ethermine.org  [18.219.59.155:5555]
  ℹ  09:21:39|stratum |  Spinning up miners...
  ℹ  09:21:39|cuda-0  |  No work. Pause for 3 s.
  ℹ  09:21:39|stratum |  Subscribed to stratum server
  ℹ  09:21:39|stratum |  Authorized worker MYWALLET.myworker
  ℹ  09:21:39|stratum |  New job #abb8f09d…   us1.ethermine.org [18.219.59.155:5555]
  ℹ  09:21:39|stratum |  New pool difficulty:  4.00 gigahashes 
  ℹ  09:21:39|ethminer|  Shutting down...
  ℹ  09:21:39|ethminer|  Shutting down miners...
  ℹ  09:21:39|main    |  Disconnected from us1.ethermine.org  [18.219.59.155:5555]
  ℹ  09:21:42|ethminer|  Terminated !

I had no trouble with 0.12 using the old F / FS / O syntax. I have no idea what protocol I should be using or if I'm doing this right. I have tried the 0.14.0 release, I didn't get even this far with it.
Is there anything I'm doing wrong?

**Comment by Algomorph** [comment]
P.S. already tried all suggestions in this [proposed pull request](https://github.com/ethereum-mining/ethminer/pull/1172/commits/eff761e2879a2019a7440ff7f6d7e6ff245772eb), same result or no jobs. All my other workers are mining happily. Please, halp!

**Comment by AndreaLanfranchi** [comment]
The key is here.

`ethminer 0.15.0.dev11-50+commit.7f621626.dirty`

That "dirty" tells you have made some change into your local copy which is not coming from this repository.

Please clone a "clean" copy of this repo.

**Comment by AndreaLanfranchi** [comment]
BTW

--farm-recheck 200 is totally unnecessary. In stratum mode it does nothing.

**Comment by Algomorph** [comment]
Thanks, I'm thinking the "change" was probably just the build folder I made inside the repo folder for the CMake config. Still, same deal:
ethminer -P stratum+ssl://MYWALLET.MYWORKER@us1.ethermine.org:5555 -U -R

  m  10:31:25|ethminer|  ethminer 0.15.0.dev11-50+commit.7f621626
  m  10:31:25|ethminer|  Build: linux / release
 cu  10:31:25|ethminer|  Using grid size 8192 , block size 128
  m  10:31:25|ethminer|  not-connected
  ℹ  10:31:25|main    |  Selected pool us1.ethermine.org:5555
  ℹ  10:31:25|stratum |  Trying 18.219.59.155:5555 ...
  ℹ  10:31:25|stratum |  Connected to us1.ethermine.org  [18.219.59.155:5555]
  ℹ  10:31:25|stratum |  Spinning up miners...
  ℹ  10:31:25|cuda-0  |  No work. Pause for 3 s.
  ℹ  10:31:25|stratum |  Subscribed to stratum server
  ℹ  10:31:25|stratum |  Authorized worker MYWALLET.MYWORKER
  ℹ  10:31:25|stratum |  New job #e92b2fe8…   us1.ethermine.org [18.219.59.155:5555]
  ℹ  10:31:25|stratum |  New pool difficulty:  4.00 gigahashes 
  ℹ  10:31:26|ethminer|  Shutting down...
  ℹ  10:31:26|ethminer|  Shutting down miners...
  ℹ  10:31:26|main    |  Disconnected from us1.ethermine.org  [18.219.59.155:5555]
  ℹ  10:31:28|ethminer|  Terminated !

If I try 'stratum1+ssl' instead of 'stratum+ssl', it does exactly the same thing, except without the "subscribed to ..." or "Authorized worker" messages.

**Comment by AndreaLanfranchi** [comment]
Hmmm ... strange ... it's like someone hits CTRL+C or something sends kill signal to ethminer.
Can you check this ?

Also ... please try plain tcp on port 4444

`ethminer -P stratum+tcp://MYWALLET.MYWORKER@us1.ethermine.org:4444 -U -R`

**Comment by Algomorph** [comment]
Yes, you were right. I had an idler script still running in the background, trying to use the old syntax, and it was shutting down the process on user input. Sorry about bothering you with this, thank you for your help.
