### ISSUE TITLE
what are those % numbers that only comes when using --tstart / --tstop ? 

### ISSUE THREAD

**Issue by divinity76** [ethereum-mining/ethminer#1178]
when not using the `--tstop 80 --tstart 40` parameters, my logs look like:

`m  16:47:01|ethminer|  Speed 257.66 Mh/s    gpu/0 28.41  gpu/1 29.36  gpu/2 29.07  gpu/3 28.50  gpu/4 28.41  gpu/5 28.50  gpu/6 28.50  gpu/7 28.50  gpu/8 28.41  [A2+0:R0+0:F0] Time: 00:00`

but when using `--tstop 80 --tstart 40`, it looks like: 

`m  16:40:32|ethminer|  Speed 252.63 Mh/s    gpu/0 28.73 49C 93%   gpu/1 29.57 49C 57%   gpu/2 28.73 53C 55%   gpu/3 28.63 49C 93%   gpu/4 26.53 49C 93%   gpu/5 27.37 49C 93%   gpu/6 25.06 49C 93%   gpu/7 28.63 49C 93%   gpu/8 29.36 49C 93%   [A0+0:R0+0:F0] Time: 00:00`

what are those extra % numbers? at first, i though it was `how far it is from the temp limit in %`, but then the numbers doesn't make any sense, like 49C is 93% ?  and 53C is 55%?  so.. then i have no clue what they mean. anyone know?

**Comment by AndreaLanfranchi** [comment]
It's the fan %.
When activating tstart and tstop this implies hwmon to be set to 0 which shows temperature **and** fan percent.
