### ISSUE TITLE
ETHminer will not start after Windows update Nvidia miner

### ISSUE THREAD

**Issue by StephanSm** [ethereum-mining/ethminer#1182]
Hi,

I use ethminer 0.14 dev3 what was perfect for me so no update needed.
Since 4 hours ago the RIG got the April update and now i cannot start the minersoftware anymore.

When i click on miner.bat the software starts and a few seconds later the cmd window closes. I put Pause at the bat file but there was no more additional information. 

I tried the latest update 0.15 dev11 and changed -S into -P

But for now i have in version 0.14 this rule:
ethminer.exe -U -RH -HWMON --farm-recheck 200 -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0xwalletnumber.default1

I disabled windows defender and also the windows firewall.

Any idea how i can solve this problem? The next rig is already ready for the Windows update :)

Best regards,
Stephan

**Comment by StephanSm** [comment]
Hi Andrea,

Thanks for your message. The gpu is NVIDIA.

**Comment by AndreaLanfranchi** [comment]
Can you please modify your .bat file like this ?

```
@echo off
ethminer.exe -U -RH -HWMON --farm-recheck 200 -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0xwalletnumber.default1
echo %errorlevel%
pause
```

and report which is the output ?

**Comment by efrasyad** [comment]
I think you will have something like this:
>ethminer.exe -U -R --HWMON -P stratum+tcp://<wallet_address>.<worker_name>@us1.ethermine.org:4444

**Comment by StephanSm** [comment]
![error1](https://user-images.githubusercontent.com/39748803/40717361-5630f2c2-640c-11e8-8b07-89c02b832027.jpg)

Hi, this is the output i get, above there is the miner.bat file i use.

**Comment by AndreaLanfranchi** [comment]
It seems like error 1073741819 is recurring after recent Windows 10 updates.
See also #1165 

It may be worth trying this fix
http://www.fixerrs.com/2015/08/file-system-error-1073741819.html

**Comment by AndreaLanfranchi** [comment]
Any news here ?

**Comment by StephanSm** [comment]
Sorry for the late response. I tried to fix it with the soundsetting like described in the link above but this didn't work. Now, 5 minutes ago i deleted the Windows update and all is up and running again.

Thanks for your help!

**Comment by AndreaLanfranchi** [comment]
@all please read this

https://github.com/ethereum-mining/ethminer/issues/1165#issuecomment-394129880

**Comment by AndreaLanfranchi** [comment]
Any update here ?

**Comment by AndreaLanfranchi** [comment]
No feed back.
Closing.
