### ISSUE TITLE
Ethminer download the DAG in two places? 

### ISSUE THREAD

**Issue by MerlinBenj** [ethereum-mining/ethminer#1187]
On ubuntu (16), the same dag's are created in two places. 
1> in /home/user/.ether
2> in /root/.ether 

Is this needed, would symlink be better? The ethminer is setup to run a startup via crontab.  Flags :  -G -F.  Yes, the size on disk for base is 2x.   

Log in as root, and check for dag. 

Can -C flag be used to setup dag, then use -G  to run?  Is there a flag to remove old dags.

**Comment by AndreaLanfranchi** [comment]
Ethminer (this project) does not create any file for DAGs ... they're generated on GPU directly.
We also do not implement any -C flag.
Which version are you using ?
