### ISSUE TITLE
No work. Pause for 3 s. on 3Gb Nvidia Card

### ISSUE THREAD

**Issue by Wafflezzzzz** [ethereum-mining/ethminer#1206]
Specs:
Windows 10
Nvidia gtx 1060 3gb
16gb ram
Core i5
500gb Hard Disk

Every time I open ethminer.exe with this command:
"ethminer.exe -P stratum1+ssl://0x94458c56cC88128564F4fE4d67aab6d7AFF3b5df.rig0@eu1.ethermine.org:5555"

It shows:
https://gyazo.com/d6e119e914f84262bc6a4f939832ab11

The "No work. Pause for 3 s" continues forever until I force close the application. Please help someone !

**Comment by AndreaLanfranchi** [comment]
You do not have enough memory on GPU to mine ethereum : 3Gb are not enough anymore due to DAG size. In addition windows holds some GPU ram for itself.

You might have a chance on linux or try another coin with lower dag size.
