### ISSUE TITLE
GPU numbering mismatch question (nvidiaInspector vs. ethminer)

### ISSUE THREAD

**Issue by igy137** [ethereum-mining/ethminer#1210]
Hi, 

I just updated to Windows 10 latest April release and at the same time to nvidia driver 397.93, on a rig with 8 cards: 7x1070 1x1060.

All runs fine with 0.15.0-dev11, but I noticed that the GPU numbering does not match as it did previously between ids in nvidiaInspector and the ids shown by ethminer. It still runs though, but first I was quite confused.

In nvidiaInspector, the gtx1060 is shown with card id 1, this is how is configured in my starter batch files.
However, this card is shown as the last card with id 7 in ethminer, I can surely identify this from the fan speed set and the mh rate reported. Note that card is on an M.2 to PCI-E adapter and sometimes it already happened than it changed location when changing cards/bios settings, but so far it has always been consistent between different apps.

Any idea what could cause this?

Thank,
igy

**Comment by igy137** [comment]
For completeness, here's my command line for running ethminer (probably needs some clean-up :))

set NO_COLOR=1
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

%ETHMINER%  --farm-recheck 1000 -RH -HWMON -G --cuda --opencl-platform 1 -P stratum+tcp://0xFFFF...FFFF.a%1@eu1.ethermine.org:4444 -P stratum+tcp://0xFFFF...FFFF.a%1@us1.ethermine.org:4444 2>&1 | wtee -a output.log

**Comment by AndreaLanfranchi** [comment]
set the CUDA_​DEVICE_​ORDER environment variable to PCI_BUS_ID in your shell.

setx CUDA_DEVICE_ORDER=PCI_BUS_ID

**Comment by igy137** [comment]
I tried it but seems not to make any difference.
If I understand correctly, this is an nvidia driver feature, so could that be that the newest driver dropped support for that?

**Comment by AndreaLanfranchi** [comment]
Sorry ... I gave you incorrect info.

What you need is also to change all "setx" to "set"

**set** takes effect in local cmd context.  Meaning once you exit or close the cmd window, you lose the environment variable.

**setx** takes effect in future cmd context.  So you won't see the environment variable and its value in the current cmd.  You need to open a new cmd window to see it.

**Comment by igy137** [comment]
Thank you very much, with set it worked, back to normal now.
