### ISSUE TITLE
Invalid argument: --cuda-parallel-hash

### ISSUE THREAD

**Issue by mvrhov** [ethereum-mining/ethminer#122]
Anybody knows what's going on?

```
C:\ethminer>ethminer -V
ethminer version 0.11.0
Build: Windows/msvc/Release

C:\ethminer>ethminer --cuda-parallel-hash
Invalid argument: --cuda-parallel-hash

C:\\ethminer>ethminer -U -M --cuda-parallel-hash
Invalid argument: --cuda-parallel-hash
```

**Comment by mvrhov** [comment]
Ok, That's stupid... The help says `Define how many hashes to calculate in a kernel, can be scaled to achive better performance. Default=4`
It seems that's not true on windows? As it barfs with the above error. I have to run with `ethminer -U -M --cuda-parallel-hash 4`

**Comment by jimmykl** [comment]
The --cuda-parallel-hash switch is there to change the value from the default of 4. If you want to change it use a value between 1–8 after the switch. It will not work if you have no argument for the switch.

**Comment by jimmykl** [comment]
@mvrhov Could you please close this issue if there's nothing more to add?

**Comment by mvrhov** [comment]
As I don't know when I'll have the time to check this up. I'm going to close it. And reopen if necessary.

**Comment by JohnSmall** [comment]
Is there anywhere this is documented other than this thread? It's a pain to have to search through issues to find out how command line options should work.

**Comment by jimmykl** [comment]
@JohnSmall See FAQ #6 which was added recently https://github.com/ethereum-mining/ethminer#faq

**Comment by JohnSmall** [comment]
Ok thanks
