### ISSUE TITLE
ethminer 0.15.0rc0 not working

### ISSUE THREAD

**Issue by megapearl** [ethereum-mining/ethminer#1223]
System is: `Ubuntu 4.13.0-45-generic #50-Ubuntu SMP Wed May 30 08:23:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

0.15.0dev11 precompiled linux version is running fine with:

`/usr/bin/ethminer --cuda -HWMON 1 --report-hashrate --stratum-email my@mailaddress.com -P stratum1+tcp://0x1xxxxxxxxxxxxxxxxxxxxxxxxx@eth-eu1.nanopool.org:9999/myworker-name/my@mailaddress.com -P stratum1+tcp://0x8xxxxxxxxxxxxxxxxxx@eth-eu2.nanopool.org:9999/my-worker/my@mailaddress.com --api-port 8888`

0.15.0rc0 precompiled linux version is not running and giving error:

 m 18:35:44 ethminer ethminer 0.15.0rc0
 m 18:35:44 ethminer Build: linux/release
cu 18:35:44 ethminer Using grid size: 8192, block size: 128
Error: bind: Bad file descriptor

terminate called without an active exception

running with cmdline:
`/usr/bin/ethminer --cuda --HWMON 1 --report-hashrate --stratum-email my@mailaddress.com -P stratum1+tcp://0x1xxxxxxxxxxxxxxxxxxxxxxxxx@eth-eu1.nanopool.org:9999/myworker-name/my@mailaddress.com -P stratum1+tcp://0x8xxxxxxxxxxxxxxxxxx@eth-eu2.nanopool.org:9999/my-worker/my@mailaddress.com --api-port 8888
`
How to debug?

Regards,
Donald.

**Comment by invidtiv** [comment]
Same here

 m 21:07:29 ethminer ethminer 0.15.0rc0
 m 21:07:29 ethminer Build: linux/release
cu 21:07:29 ethminer Using grid size: 8192, block size: 128
Error: bind: Bad file descriptor

also with 0.16dev0

**Comment by StevenV009** [comment]
Hi
 To devs, awesome work so far and appreciated!!
On my windows machine I have this error on V15rc0

![image](https://user-images.githubusercontent.com/27699919/41000776-58418a9c-690f-11e8-86c6-ce79bffb47d2.png)

When I remove '-RH -HWMON 1' it works perfectly. 

On my Ubuntu server 16.04 machine, I also have this error, there are other errors which Im not skilled enough to catch when removing '-RH -HWMON' have reverted to V15dev11 on ubuntu.

Hope this helps.

**Comment by megapearl** [comment]
You need to use —HWMON 1 not -HWMON 1 with the start of release 0.15.0rc0

**Comment by bbroge** [comment]
oh nice @megapearl, that was easy, fixed my issue. thanks!

**Comment by AndreaLanfranchi** [comment]
Amended with #1227
