### ISSUE TITLE
ethminer 0.15.0rc0 not working | NVIDIA GPUs

### ISSUE THREAD

**Issue by Daspharion** [ethereum-mining/ethminer#1224]
```
C:\Users\Miner\Desktop>ethminer -U --list-devices

Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1050 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 4294967296
        Pci: 0000:07:00
[1] GeForce GTX 1050 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 4294967296
        Pci: 0000:09:00
[2] GeForce GTX 1050 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 4294967296
        Pci: 0000:0b:00
[3] GeForce GTX 1050 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 4294967296
        Pci: 0000:0c:00
[4] GeForce GTX 1050 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 4294967296
        Pci: 0000:0d:00
[5] GeForce GTX 1050 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 4294967296
        Pci: 0000:0e:00

C:\Users\Miner\Desktop>ethminer -U -P stratum1+tcp://<wallet>.<worker>@eu1.ethermine.org:4444
 m 01:04:01 main     ethminer 0.15.0rc0
 m 01:04:01 main     Build: windows/release
cu 01:04:01 main     Using grid size: 8192, block size: 128

C:\Users\Miner\Desktop>pause
```
Please help 🆘

**Comment by chfast** [comment]
I think we at least need the error code returned from ethminer process.

**Comment by Daspharion** [comment]
How can i get that?

**Comment by chfast** [comment]
Put this in your script after `ethminer -U -P...` or execute in command line after ethminer terminates.
```sh
echo %errorlevel%
```

**Comment by Daspharion** [comment]
Thank you
```
C:\Users\Miner\Desktop>echo -1073741819
-1073741819
```

**Comment by AndreaLanfranchi** [comment]
please read this

https://github.com/ethereum-mining/ethminer/issues/1165#issuecomment-394129880

and see if it helps.

Have you recently updated Windows ?

**Comment by Daspharion** [comment]
Yes, i installed the brand-new windows 10 image

**Comment by Daspharion** [comment]
Ugh... that doesn't really help, do i wait for it to be fixed or is there more workarounds?

**Comment by satori-q3a** [comment]
Have you installed the latest NVidia drivers from their web site?  398.11 works without problems.

**Comment by Daspharion** [comment]
Yes, I installed it

**Comment by chfast** [comment]
Do previous versions of ethminer work?

**Comment by Daspharion** [comment]
Using ethminer 0.13.0
```
C:\Users\Miner\Desktop>miner.exe -U -S eu1.ethermine.org:4444 -O <wallet>.miner
 cu  13:44:58|main      Using grid size 8192 , block size 128
  i  13:44:58|main      Connecting to stratum server eu1.ethermine.org:4444
  i  13:44:58|stratum   Connected to stratum server eu1.ethermine.org : 4444
  i  13:44:58|stratum   Starting farm
  i  13:44:58|cuda-0    No work. Pause for 3 s.
  i  13:44:58|cuda-1    No work. Pause for 3 s.
  i  13:44:58|cuda-2    No work. Pause for 3 s.
  i  13:44:58|cuda-3    No work. Pause for 3 s.
  i  13:44:58|cuda-4    No work. Pause for 3 s.
  i  13:44:58|cuda-5    No work. Pause for 3 s.
  i  13:44:58|stratum   Subscribed to stratum server
  i  13:44:58|stratum   Authorized worker <wallet>.miner
  i  13:44:58|stratum   Received new job #365ae15d  seed: #c906fa38eca6c8a38bb932db61ca31b4  target: #0000000112e0be826d694b2e
  m  13:45:00|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  gpu/2  0.00  gpu/3  0.00  gpu/4  0.00  gpu/5  0.00  [A0+0:R0+0:F0] Time: 00:00
  i  13:45:01|cuda-0    Initialising miner...
  i  13:45:01|cuda-1    Initialising miner...
  i  13:45:01|cuda-3    Initialising miner...
  i  13:45:01|cuda-5    Initialising miner...
  i  13:45:01|cuda-4    Initialising miner...
  i  13:45:01|cuda-2    Initialising miner...
  m  13:45:02|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  gpu/2  0.00  gpu/3  0.00  gpu/4  0.00  gpu/5  0.00  [A0+0:R0+0:F0] Time: 00:00
 cu  13:45:04|cuda-2    Using device: GeForce GTX 1050 Ti  (Compute 6.1)
 cu  13:45:04|cuda-3    Using device: GeForce GTX 1050 Ti  (Compute 6.1)
 cu  13:45:04|cuda-5    Using device: GeForce GTX 1050 Ti  (Compute 6.1)
 cu  13:45:04|cuda-1    Using device: GeForce GTX 1050 Ti  (Compute 6.1)
 cu  13:45:04|cuda-0    Using device: GeForce GTX 1050 Ti  (Compute 6.1)
 cu  13:45:04|cuda-4    Using device: GeForce GTX 1050 Ti  (Compute 6.1)
 cu  13:45:04|cuda-2    Set Device to current
 cu  13:45:04|cuda-3    Set Device to current
 cu  13:45:04|cuda-5    Set Device to current
 cu  13:45:04|cuda-1    Set Device to current
 cu  13:45:04|cuda-0    Set Device to current
 cu  13:45:04|cuda-4    Set Device to current
 cu  13:45:04|cuda-2    Resetting device
 cu  13:45:04|cuda-3    Resetting device
 cu  13:45:04|cuda-5    Resetting device
 cu  13:45:04|cuda-1    Resetting device
 cu  13:45:04|cuda-0    Resetting device
 cu  13:45:04|cuda-4    Resetting device
  m  13:45:04|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  gpu/2  0.00  gpu/3  0.00  gpu/4  0.00  gpu/5  0.00  [A0+0:R0+0:F0] Time: 00:00
 cu  13:45:04|cuda-2    Allocating light with size: 41811904
 cu  13:45:05|cuda-0    Allocating light with size: 41811904
 cu  13:45:05|cuda-1    Allocating light with size: 41811904
 cu  13:45:05|cuda-2    Generating mining buffers
CUDA error in func 'dev::eth::CUDAMiner::cuda_init' at line 366 : out of memory.
 cu  13:45:06|cuda-4    Allocating light with size: 41811904
 cu  13:45:06|cuda-5    Allocating light with size: 41811904
 cu  13:45:06|cuda-0    Generating mining buffers
  m  13:45:09|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1
C:\Users\Miner\Desktop>echo -1073741819
-1073741819
```

**Comment by Daspharion** [comment]
It works only if i'm using max of 2 video cards

**Comment by chfast** [comment]
Try different dag allocation options

**Comment by Daspharion** [comment]
Oh my... sorry, i forgot to increase my virtual memory. Now it perfectly using ethminer 0.13.0

**Comment by chfast** [comment]
So it works with 0.13, but not with 0.15?

**Comment by Daspharion** [comment]
yes

**Comment by webprophet** [comment]
I had -1073741819 when I dropped my 8th NV card in.  Bumped up page file to 30 gig (remembered seeing it in the asrock mb manual), works fine w 14.  Ill try 15 this weekend when I figure the new bat arguments out.  :)

**Comment by turbozapekanka** [comment]
same error for me. what command line do you use for 13.0? it does not accept -P parameter

**Comment by chfast** [comment]
Please try `-L 1` and `-L 2` options.

**Comment by chfast** [comment]
Did you increase "page size from 16 to 20gb"?

**Comment by chfast** [comment]
@Daspharion What is the last working release?

**Comment by Daspharion** [comment]
i've increased it to 32gb; v0.13.0

**Comment by webprophet** [comment]
15rc2 works fine in 2 of my rigs.  Win 10 build 17134, NV driver 397.64, 8 NV 1070 TI cards, 8GB ram, 30GB page file...

The nugget I mentioned earlier from ASUS when I caught the -107374181 error upon creating the 8th dag.  Increasing the page file fixed it for me.

Section 1, Page 7: ASUS B250 Mining Expert Manual
“To make your build more stable, when using 8 or more cards for mining, we recommend that you install 4GB memory modules and change the size of the virtual memory paging file to 30GB.”

@Daspharion how much ram are you running?

**Comment by St3x** [comment]
I encounter the same issue and tried everything suggested above without luck.

__Test rig__
- i7-7700K
- 2 x Aorus GeForce GTX 1080 Ti Waterforce
- 2 x 8 GB RAM (I have read somewhere on Internet "8 GB per card is perfect")
- Fresh install (`diskpart clean all` first) of Windows 10 Pro x64 10.0.17134
- Fresh install of nVidia drivers 398.36
- Fresh install of nVidia CUDA Toolkit 9.2
- Fresh install of Aorus Engine 1.3.5 to overclock the cards a bit : GPU 1746 MHz, Memory 12096 MHz
- Windows virtual memory set to 32768-32768

__Results__
- :x: ethminer 0.15.0rc2 (`ethminer.exe -P stratum2+tcp://username.ethminer:x@url:port -U`)
```
m 18:02:32 main     ethminer 0.15.0rc2
m 18:02:32 main     Build: windows/release
cu 18:02:32 main     Using grid size: 8192, block size: 128
```
and it simply exits.
```
echo %errorlevel%
-1073741819
```

- :x: ethminer 0.14.0 (`ethminer.exe -P stratum2+tcp://username.ethminer:x@url:port -U`)
```
m  18:19:16|main    |  ethminer version 0.14.0
m  18:19:16|main    |  Build: windows / release +git. 24c65cf
cu  18:19:16|main    |  Using grid size 8192 , block size 128
```
and it simply exits.
```
echo %errorlevel%
-1073741819
```

- ✔️ ethminer 0.13.0 (`ethminer.exe -O username.ethminer:x -U -S url:port`)
```
i  18:41:00|stratum   Received new job #7bac  seed: #9d3fef9bc522aee668ac0c6f6b22cf92  target: #00000000ffb34c02420e9948
m  18:41:01|main      Speed  68.98 Mh/s    gpu/0 34.39  gpu/1 34.60  [A3+0:R0+0:F0] Time: 00:00
m  18:41:03|main      Speed  69.20 Mh/s    gpu/0 34.50  gpu/1 34.70  [A3+0:R0+0:F0] Time: 00:00
m  18:41:05|main      Speed  69.17 Mh/s    gpu/0 34.49  gpu/1 34.68  [A3+0:R0+0:F0] Time: 00:00
m  18:41:07|main      Speed  69.17 Mh/s    gpu/0 34.49  gpu/1 34.68  [A3+0:R0+0:F0] Time: 00:00
m  18:41:09|main      Speed  69.08 Mh/s    gpu/0 34.54  gpu/1 34.54  [A3+0:R0+0:F0] Time: 00:00
m  18:41:11|main      Speed  69.14 Mh/s    gpu/0 34.48  gpu/1 34.67  [A3+0:R0+0:F0] Time: 00:01
m  18:41:13|main      Speed  69.28 Mh/s    gpu/0 34.64  gpu/1 34.64  [A3+0:R0+0:F0] Time: 00:01
m  18:41:15|main      Speed  69.28 Mh/s    gpu/0 34.64  gpu/1 34.64  [A3+0:R0+0:F0] Time: 00:01
m  18:41:17|main      Speed  69.27 Mh/s    gpu/0 34.63  gpu/1 34.63  [A3+0:R0+0:F0] Time: 00:01
```

__Tests__
- Defining Windows' virtual memory range to 8192-8192, 16384-16384 and 32768-32768 did not help
- Trying options `-L 1` and `-L 2` did not help
- Running ethminer.exe from another directory or from the same directory did not help, ethminer starts anyway
- Trying options `-G` , `-U` or `-X` did not help either
- `ethminer.exe --list-devices -U` returns as expected
```
Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1080 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 11811160064
        Pci: 0000:01:00
[1] GeForce GTX 1080 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 11811160064
        Pci: 0000:03:00
```

I have no clue so mining with ethminer 0.13.0 seems to be a workaround for now.

**Comment by jfcg** [comment]
i am trying ethminer 0.15.0 on 64-bit manjaro (kernel 4.14.57) with latest nvidia drivers (396.45) with

`ethminer -U --cuda-devices 1 2 --farm-recheck 200 -v 1 -P stratum1+tcp://ADDRESS@eth-eu1.nanopool.org:9999/WORKER/EMAIL`

and it crashes with
```
Error: clGetPlatformIDs

terminate called without an active exception
./run.txt: line 1:  2119 Aborted                 (core dumped)
```
why is it calling an OpenCL function when I used -U ?

**Comment by jfcg** [comment]
after installing opencl-nvidia package, it looks OK :)

**Comment by MoRoBG** [comment]
webprophet,
Тhanks, I did this and my rig started working with all cards “To make your build more stable, when using 8 or more cards for mining, we recommend that you install 4GB memory modules and change the size of the virtual memory paging file to 30GB.” 👍

**Comment by St3x** [comment]
Hi ! Big news !

I wrote https://github.com/ethereum-mining/ethminer/issues/1224#issuecomment-402230548 above, regarding the "auto-exiting with error -1073741819" issue, 2.5 months ago.

My rig is still the exact same hardware and [ethminer 0.16.0rc1+commit.68ca5dcf](https://github.com/ethereum-mining/ethminer/releases/tag/v0.16.0) works like a charm, both on Ethereum and Ethereum Classic, without any issue, and without exiting.

Ethereum
![image](https://user-images.githubusercontent.com/43316415/45596943-75730180-b9c4-11e8-9eb4-c69742616eda.png)

Ethereum Classic
![image](https://user-images.githubusercontent.com/43316415/45596958-a8b59080-b9c4-11e8-93f4-a626a5532e6b.png)

__What I did__
- Installed the latest cumulative updates for Windows 10 (recently [KB4457128](https://support.microsoft.com/en-us/help/4457128/windows-10-update-kb4457128) and [KB4100347](https://support.microsoft.com/en-us/help/4100347/intel-microcode-updates-for-windows-10-version-1803-and-windows-server))
- Reinstalled the nVidia drivers 399.24 from sratch
- Reinstalled the nVidia CUDA Toolkit 9.2 + Patch 1 from scratch
- Use [ethminer 0.16.0rc1+commit.68ca5dcf](https://github.com/ethereum-mining/ethminer/releases/tag/v0.16.0)

I don't know which one of these solved the issue, and I will probably never know, but everything works great right now.

**Comment by lesjokolat** [comment]
@AndreaLanfranchi  I think this can be closed now.
