### ISSUE TITLE
EthMiner Crash in Win10 x64 v1709 (patched drivers)

### ISSUE THREAD

**Issue by Picxha** [ethereum-mining/ethminer#1229]
![image](https://user-images.githubusercontent.com/39989478/41032014-81ff7e5c-6982-11e8-8589-661b0aac48ce.png)

I have 2 Amd rx580 mining without problems with claymore. But when I run ethminer I get the error shown in the capture. I have put the ethmiiner folder in the path. I have disabled windows update and windows defender services, but ethminer.exe does not work. With Claymore there is no problem, but I think that ethminer has better hashrate in the medium term. There are many issues with similar problems and I think that is the windows configuration. Has someone solved it? Thank you

**Comment by Picxha** [comment]
i Update with another capture just in case it helps 

![image](https://user-images.githubusercontent.com/39989478/41032885-f65391a6-6984-11e8-9649-97460d9bab9c.png)

**Comment by chfast** [comment]
`ethminer --version`.
And have you tried previous versions?

**Comment by Picxha** [comment]
update
i have tried with versions 0.12 0.13 0.14
but the message "ethminer stop working" still appears ...

**Comment by BoriZka67** [comment]
.exe

**Comment by chfast** [comment]
So all the version do not work?

**Comment by efrasyad** [comment]
Can you try this release [v0.14.0](https://github.com/ethereum-mining/ethminer/releases/tag/v0.14.0) and then run `ethminer.exe --list-devices`

**Comment by Picxha** [comment]
I do not think it's a problem with the ethermine version
maybe  it's a problem with the amd drivers
the rx580 cards have been bios mod with polaris
and the amd drivers were patched with pixel clock patcher ..
So the question is, is there someone who works ethermine with the patched drivers (signature changed)?
![image](https://user-images.githubusercontent.com/39989478/41090590-ea03e26e-6a44-11e8-9896-2261eb0e8201.png)


![image](https://user-images.githubusercontent.com/39989478/41090632-00246136-6a45-11e8-9374-fe438033603b.png)

**Comment by AndreaLanfranchi** [comment]
Not an ethminer problem.
