### ISSUE TITLE
Mix Rig select all cards to mine -X

### ISSUE THREAD

**Issue by JayChickenK** [ethereum-mining/ethminer#123]
i try to explain the problem as detailed as possible even if English isn't my first language:
I have a mix Rig with Nvidia + Amd Cards:
4x GTX 1070
2x HD 7950
1x R9 270x
i tried to run the miner with all cards my launch parameter:

`ethminer.exe -F http://******:7777/*******/GTX*** -G --opencl-platform 0`
with this command the program only selects the 4 1070s and if i do

`ethminer.exe -F http://******:7777/*******/GTX*** -G --opencl-platform 2`
i get all my Amd Cards. 

`ethminer.exe -F http://******:7777/*******/GTX*** -X --opencl-platform 1`
gets the Intel Graphic HD

`ethminer.exe -F http://******:7777/*******/GTX*** -X --opencl-platform 2`
gets one amd card but 0 mh/s all the time.

`ethminer.exe -F http://******:7777/*******/GTX*** -X --opencl-platform 0`
gets one 1070 with 0 mh/s.

`ethminer.exe -F http://******:7777/*******/GTX*** -X --cuda-opencl`
https://gyazo.com/fc8992a62e0d0e736ec068423a3163ad

`ethminer.exe -G --list-devices`
> Listing OpenCL devices.
> FORMAT: [deviceID] deviceName
> [0] GeForce GTX 1070
>         CL_DEVICE_TYPE: GPU
>         CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
>         CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2147483648
>         CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
> [1] GeForce GTX 1070
>         CL_DEVICE_TYPE: GPU
>         CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
>         CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2147483648
>         CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
> [2] GeForce GTX 1070
>         CL_DEVICE_TYPE: GPU
>         CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
>         CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2147483648
>         CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
> [3] GeForce GTX 1070
>         CL_DEVICE_TYPE: GPU
>         CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
>         CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2147483648
>         CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
> [4] Intel(R) HD Graphics 610
>         CL_DEVICE_TYPE: GPU
>         CL_DEVICE_GLOBAL_MEM_SIZE: 1655360717
>         CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1655360717
>         CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
> [5] Tahiti
>         CL_DEVICE_TYPE: GPU
>         CL_DEVICE_GLOBAL_MEM_SIZE: 3221225472
>         CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2952790016
>         CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
> [6] Pitcairn
>         CL_DEVICE_TYPE: GPU
>         CL_DEVICE_GLOBAL_MEM_SIZE: 2147483648
>         CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1879048192
>         CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
> [7] Tahiti
>         CL_DEVICE_TYPE: GPU
>         CL_DEVICE_GLOBAL_MEM_SIZE: 3221225472
>         CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2952790016
>         CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

JCK

PS: all launch parameter were tested with --farm-recheck 2000 and without. And ALL cards are stock and work fine with claymore 9.6.

**Comment by JHGitty** [comment]
The most awesome thing would be to use CUDA on nvidia and OpenCL on AMD on the same miner window. But I think this is not supported yet.

**Comment by JayChickenK** [comment]
my though was that it is support because the --help say so, but i cant get it to work so i don't know if it is implemented or not.

**Comment by JHGitty** [comment]
@chfast Is this implemented / supported? Can we use NVIDIA for CUDA + AMD for OpenCL on the same time somehow?

**Comment by darkfires** [comment]
I can confirm it's not working, even specifying --opencl-device with what's listed in list-devices it will always remain the same card regardless of device-id unless you specify opencl-platform.  That's even with using the NVIDIA card in OpenCL mode, it just flat out refuses to use both AMD and NVIDIA in the same process.

**Comment by chfast** [comment]
I don't know. I have no way of testing this.

**Comment by marksims** [comment]
i can confirm it is not working

**Comment by smurfy** [comment]
i will check, i'm quite sure it only works in stratum mode.

**Comment by smurfy** [comment]
Please test if #302 fixes the problem

**Comment by ikonspirasi** [comment]
Hi, i have tried the ethminer-0.14.0.dev3-Windows and use this params ethminer.exe --farm-recheck 2000 -F http://127.0.0.1:8080/xxx -X --opencl-platform 2 --cl-local-work 256 --cl-global-work 16384 -L parallel and it can mine using all my 4 cards: gtx 1070, 2x rx 580 and rx 570
altough still getting lower hashrate than claymore (around 6 mh/s less), but i will try this until payout.
