### ISSUE TITLE
ethminer 0.15.0rc1 doesn't work as well

### ISSUE THREAD

**Issue by Danielhodali** [ethereum-mining/ethminer#1236]
ethminer 0.15.0rc1 does not do any work (nvidia 1070.) I am using ethminer015_dev11 now and it works well. What is wrong with the new version?

**Comment by ThetaProtocol** [comment]
Also for the devs. Was the --cuda-noeval syntax removed? I had that enabled for my nvidia cards mining ethash  and with the new bump, ethminer doesn't recognize it anymore

**Comment by chfast** [comment]
We need logs and command line arguments.
