### ISSUE TITLE
donation addresses please

### ISSUE THREAD

**Issue by aleqx** [ethereum-mining/ethminer#1240]
I've been using ethminer on and off but it served me well. Given I still haven't found time to contribute with code, I'd like to donate to the active devs.

Can you guys please drop your Eth (or other) crypto donation addresses, either here or in README.md? (the latter is probably better so others can see it by default as well).

**Comment by nguylb73** [comment]
https://github.com/chfast seems like the main contributor. He has a tip jar listed in the link I gave

**Comment by nguylb73** [comment]
You might want to contact @chfast first before you donate anything big... to make sure he still owns the address

**Comment by aleqx** [comment]
Thanks. chfast seems to post the releases, but if you look at code commits I only see others committing actual code.

**Comment by jean-m-cyr** [comment]
I've done some work lately. Any tip you'd send my way should be directed to your favorite charity.

**Comment by aleqx** [comment]
I already donate to lots of charities ...

**Comment by chfast** [comment]
How about we add such table: https://github.com/ethereum-mining/ethminer/blob/ebd1c2be4ab5c107d7088bbc11b1c342b9bd8428/README.md#maintainers--authors

https://github.com/ethereum-mining/ethminer/pull/1255

**Comment by chfast** [comment]
https://github.com/ethereum-mining/ethminer#maintainers--authors
