### ISSUE TITLE
Miner exits with error (nvidia, linux)

### ISSUE THREAD

**Issue by l4Dream** [ethereum-mining/ethminer#1244]
4xGTX1050ti and 1xGTX1070, Debian 9.4 x64, kernel 4.9.0-6-amd64, 396.26 driver.

`ethminer -U -P stratum+ssl://WALLET.miner@eu1.ethermine.org:5555 -R --display-interval 30 --tstop 75 --exit 2>&1 | tee -a /miner/miner.log`

Compiled from source 2 days ago, i get this errors randomly during 24/7 mining (12-1 hours between miner exits).

From log:

`X 12:24:58 stratum  Socket read failed:Connection reset by peer
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  shutdown: Transport endpoint is not connected`

**Comment by AndreaLanfranchi** [comment]
Do you have an internet connection with a static IP address ? It seems like your internet connection has a changing IP address.

**Comment by l4Dream** [comment]
No i got dynamic IP but it changes very rarely (ones in 3-5 month), but i will check it later.

**Comment by l4Dream** [comment]
I checked router logs and seems like this miner errors appears under same IP..

**Comment by AndreaLanfranchi** [comment]
Related to PR #1251
