### ISSUE TITLE
V0.14.0 crash on reconnect Win10 x64 1607 LTSB

### ISSUE THREAD

**Issue by wcpannell** [ethereum-mining/ethminer#1245]
![screenshot](http://i.imgur.com/OoSG8E4.jpg)
Does not occur on v0.13.0. Does not appear to happen on v0.15.0.rc1 (only used for 16hrs so far). I saw crashes roughly every 4-8 hours, unsure if connection actually dropped.

Nvidia GPUs, stratum+ssl pool, API enabled (rw), report hashrate enabled, hwmon enabled, colors disabled due to weak CPU.

**Comment by AndreaLanfranchi** [comment]
Two problems here. 
First one is you have high latency on your internet connection so when waiting for a response from pool it gets after 2 seconds or more. See that "_No response received in 2 seconds_" It is also possible your internet connection gets congested during downloads or smthing else.
Try adjusting parameter` --response-timeout `and set it to a higher value than 2.

Second problem is the reconnection : in 0.14 we had some issue which has been amended in 0.15. Please stay on 0.15
