### ISSUE TITLE
Problem with the ethminer-0.15.0rc1-Windows.zip **14. Jun 2018**

### ISSUE THREAD

**Issue by DagobertDug** [ethereum-mining/ethminer#1247]
Hello everybody,
sorry first for my English, I have everything with Google Translated ^^
I have a problem with the Ethminer-0.15.0rc1.
The miner does not start.
I have tried many times and entered the data differently, but something is wrong.

maybe I'm just too stupid ^^

You see I have tried a lot but nothing works ...
see screenshot

**I hope you can help me**

Guss DagobertDug

what I have already tried:

ethminer.exe --farm-recheck 200 -S eu1.ethermine.org:4444 -FS eu1.ethermine.org:4444 -O 0x#-#-#-#-#-#-#-#-#-#-#WalletAdress#-#-#-#-#-#-#-#-#-#-#.DagobertDug
![grafik](https://user-images.githubusercontent.com/40257993/41394322-ca295c70-6fa9-11e8-855f-9834879117f2.png)

################################################################################
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe -U --farm-recheck 200 -S eu1.ethermine.org:4444 -FS eu1.ethermine.org:44440 -O 0x#-#-#-#-#-#-#-#-#-#-#WalletAdress#-#-#-#-#-#-#-#-#-#-#.DagobertDug

![grafik](https://user-images.githubusercontent.com/40257993/41394451-42064fbe-6faa-11e8-83d0-c8a47b1d0dc0.png)

################################################################################
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
@echo off
ethminer.exe -U -RH -HWMON --farm-recheck 200 -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x#-#-#-#-#-#-#-#-#-#-#WalletAdress#-#-#-#-#-#-#-#-#-#-#.DagobertDug
echo %errorlevel%
pause

![grafik](https://user-images.githubusercontent.com/40257993/41394165-45d36f38-6fa9-11e8-8685-222e387a1096.png)

################################################################################
ethminer.exe -G --farm-recheck 200 http://eu1.ethermine.org/?miner=18@0x#-#-#-#-#-#-#-#-#-#-#WalletAdress#-#-#-#-#-#-#-#-#-#-#@DagobertDug
pause

![grafik](https://user-images.githubusercontent.com/40257993/41394779-8df69162-6fab-11e8-8a6e-c3591002d120.png)

**Comment by AndreaLanfranchi** [comment]
The only thing you have not tried is to read what the help says.

`ethminer.exe --help`

Parameters like -S and -FS are not supported anymore.

So you have to change to : 

`ethminer.exe -U -P stratum+tcp://<wallet>.<worker>@eu1.ethermine.org:4444 -P stratum+tcp://<wallet>.<worker>@eu1.ethermine.org:14444 `

**Comment by DagobertDug** [comment]
unfortunately still does not work 🤔





2018-06-14 10:42 GMT+02:00 Andrea Lanfranchi <notifications@github.com>:

**Comment by AndreaLanfranchi** [comment]
What do you mean does not work ?
Post the log

**Comment by DagobertDug** [comment]
I got it.🤗
it works now!

Thank you very very very much for your help.
with the best regards from Switzerland





2018-06-14 11:33 GMT+02:00 Andrea Lanfranchi <notifications@github.com>:
