### ISSUE TITLE
ethminer 0.15.0rc1 -RH & -HWMON don't work

### ISSUE THREAD

**Issue by sirplus51** [ethereum-mining/ethminer#1252]
-RH
-HWMON 
-HWMON  1

don't work with the current release as per subject

Getting 
Unexpected argument -H <-this is not a typo (W is missing)
Unexpected argument -HWMON <-this is not a typo (1 is missing)

--report-hashrate does work

Windows 10 x64.
Just had lots of updated=s only that's not it

Just overwriting the exe with the previous dev version of the exe makes everything work with same argument

PS
Where can I donate..?

**Comment by AndreaLanfranchi** [comment]
ethminer.exe --help is your friend

```
  -R,--report-hashrate        Report current hashrate to pool
  --HWMON UINT                0 - Displays gpu temp, fan percent. 1 - and power usage. Note for Linux: The program uses sysfs for power, which requires running with root privileges.
```

Look at dashes count

**Comment by sirplus51** [comment]
PS
Where can I donate..?

**Comment by AndreaLanfranchi** [comment]
We, defined as contributing developers of this project, are not a well identified group. Devs come, some go.  A contribution to anyone would not be fully deserved. If you'd tip me, for example, I'd feel the duty tho share with all the long stack of people who wrote the code before me. But many of them I don't even know who they are.

If you really want to contribute all I need is your thank you and your support if you want to endorse our free and open source solution against other, maybe more popular, closed source projects.

**Comment by sirplus51** [comment]
I’m amazed and gratified.
Thanks so much for your patience, and especially all your work and help.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
