### ISSUE TITLE
ethminer keeps reporting not-connected on version 0.16 (3Gb Card)

### ISSUE THREAD

**Issue by Starkot** [ethereum-mining/ethminer#1254]
Three days ago, something happened:
 m 19:29:18 ethminer ethminer 0.15.0rc1
 m 19:29:18 ethminer Build: linux/release
 i 19:29:18 ethminer Found suitable OpenCL device [Ellesmere] with 3652853760 bytes of GPU memory
 i 19:29:18 main     Selected pool eu1.ethermine.org:5555
 m 19:29:23 ethminer not-connected
 m 19:29:28 ethminer not-connected
 i 19:29:29 stratum  Trying 94.23.36.128:5555 ...
 X 19:29:31 stratum  Error  94.23.36.128:5555 [Timeout]
 i 19:29:31 stratum  Trying 51.255.64.43:5555 ...
 i 19:29:31 main     Selected pool eu1.ethermine.org:5555
 m 19:29:33 ethminer not-connected
 m 19:29:38 ethminer not-connected
 m 19:29:43 ethminer not-connected
 m 19:29:48 ethminer not-connected
... many many times

Sometimes it ends with an error, something there about "Segment fault"
Most of the day it works normally, but it ceases to work more and more often.
This happens with 0.16.0.dev0, 0.15.0.rc1 and rc0
With 0.15.0.dev10 it's ok

Linux fa01 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
ethminer --cl-local-work 128 --cl-global-work 32768 -R -G --farm-recheck 2000 -P stratum+ssl://0xmywallet.fa01@eu1.ethermine.org:5555 -P stratum+ssl://0xmywallet.fa01@eu2.ethermine.org:5555

**Comment by AndreaLanfranchi** [comment]
Could you please try to run with default parameters ? (and remove the farm-recheck which does nothing in stratum-mode). 

Does it happen after a cold reboot of your linux machine ?
Have you tried to increase your virtual memory ?

Take also into account that recently we switched to epoch 193 and the DAG size is quickly reaching your card limit of 3Gb ... we expect to see such troubles more and more often as the 3Gb limit approaches.

**Comment by Starkot** [comment]
After the reboot is the same. (Or should I turn off the power?)
I ran it with default parameters. 
The first time it gave the error "Segmentation fault".
The second time it started and works 25 minutes and "not-connected" and
"i 20:34:44 cl-0     Solution 0x377f3289db1f2b47 wasted. Waiting for connection ..."
I did not try to increase the virtual memory. Yet.
And the most unpleasant thing: my card has 4 GB.

**Comment by AndreaLanfranchi** [comment]
>And the most unpleasant thing: my card has 4 GB.

i 19:29:18 ethminer Found suitable OpenCL device [Ellesmere] with 3652853760 bytes of GPU memory

Ethminer detects only 3.4 available.

**Comment by AndreaLanfranchi** [comment]
Do you use this machine for normal also for desktop operations, maybe gaming ?

**Comment by Starkot** [comment]
No, I don't use it for anything else.

**Comment by joolius** [comment]
I have a similar issue:

 m 22:27:32 main     ethminer 0.15.0rc2
 m 22:27:32 main     Build: windows/release
cu 22:27:32 main     Using grid size: 8192, block size: 128
 i 22:27:32 main     Selected pool eu1.ethermine.org:8888
 i 22:27:33 main     Selected pool eu1.ethermine.org:8888
 i 22:27:34 main     Selected pool eu1.ethermine.org:8888
 i 22:27:35 main     Selected pool eu1.ethermine.org:8888
 i 22:27:36 main     Selected pool eu1.ethermine.org:8888
 m 22:27:37 main     not-connected
 i 22:27:37 main     Selected pool eu1.ethermine.org:8888
 i 22:27:38 main     Selected pool eu1.ethermine.org:8888
 i 22:27:39 main     Selected pool eu1.ethermine.org:8888
 i 22:27:40 main     Selected pool eu1.ethermine.org:8888
 i 22:27:41 main     Selected pool eu1.ethermine.org:8888
 m 22:27:42 main     not-connected
 i 22:27:42 main     Selected pool eu1.ethermine.org:8888
 i 22:27:43 main     Selected pool eu1.ethermine.org:8888
 i 22:27:44 main     Selected pool eu1.ethermine.org:8888
 i 22:27:45 main     Selected pool eu1.ethermine.org:8888
 i 22:27:46 main     Selected pool eu1.ethermine.org:8888
 m 22:27:47 main     not-connected
 i 22:27:47 main     Selected pool eu1.ethermine.org:8888
 i 22:27:48 main     Selected pool eu1.ethermine.org:8888
 i 22:27:49 main     Selected pool eu1.ethermine.org:8888
 i 22:27:50 main     Selected pool eu1.ethermine.org:8888
 i 22:27:51 main     Selected pool eu1.ethermine.org:8888

**Comment by AndreaLanfranchi** [comment]
Have you tried latest 0.16 ?
Please report,

**Comment by AndreaLanfranchi** [comment]
No feed back.
Closing
