### ISSUE TITLE
Help message for -L option is wrong.

### ISSUE THREAD

**Issue by chfast** [ethereum-mining/ethminer#1257]
```
-L,--dag-load-mode UINT=0   Set the DAG load mode. 0=parallel, 1=sequential, 2=sequential
```

I'm no sure the behavior is broken also, but at least the help message is not as helpful as it could be.

**Comment by jean-m-cyr** [comment]
With master I get:

  -L,--dag-load-mode UINT=0   Set the DAG load mode. 0=parallel, 1=sequential, 2=single.  parallel    - load DAG on all GPUs at the same time  sequential  - load DAG on GPUs one after another. Use this when the miner crashes during DAG generation  single      - generate DAG on device, then copy to other devices. Implies --dag-single-dev
