### ISSUE TITLE
Boost build warning

### ISSUE THREAD

**Issue by XhmikosR** [ethereum-mining/ethminer#1266]
So we are getting this warning:

```
C:\projects\ethminer\libpoolprotocols\stratum\EthStratumClient.cpp(177): warning C4996: 'boost::asio::basic_socket<Protocol>::cancel': By default, this function always fails with operation_not_supported when used on Windows XP, Windows Server 2003, or earlier. Consult documentation for details. [C:\projects\ethminer\build\libpoolprotocols\poolprotocols.vcxproj]
```

@AndreaLanfranchi: do we need to define something ourselves/change the code? I mean, < Vista isn't supported by the Windows binaries at all.

**Comment by AndreaLanfranchi** [comment]
I did not notice it as I don't have Vista.
Can you provide the error code ?

**Comment by AndreaLanfranchi** [comment]
It would be interesting to know **why** it should fail on such OSes

**Comment by XhmikosR** [comment]
You could try checking Boost's own documentation.

**Comment by AndreaLanfranchi** [comment]
Checked ... might be related to the missing definition of BOOST_ASIO_ENABLE_CANCELIO. 
Problem is this definition apparently MUST be included in all source files and, anyway, it does not guarantee to cancel properly pending IO until the socket is closed.

My suggestion is to trap error and continue ... few lines after socket is closed.

**Comment by XhmikosR** [comment]
Maybe a combination of the 2 solutions you describe would be the best approach?
