### ISSUE TITLE
Ubuntu 16.04 How to update ethminer from 14 to 15

### ISSUE THREAD

**Issue by beardedbob** [ethereum-mining/ethminer#1270]
Hi,

How do update to the newer ethminer? I've tired apt update mad apt upgrade but its not updated.

Thanks

**Comment by AndreaLanfranchi** [comment]
Ethminer is not a standard package of your linux distro.

Either you download latest binary releases or clone the git repo and compile/build locally

**Comment by beardedbob** [comment]
Thanks
