### ISSUE TITLE
Can u guyz add some functions like Claymore's -ttli and -tstop?

### ISSUE THREAD

**Issue by Keenni** [ethereum-mining/ethminer#1278]
Can u guyz add some functions like Claymore's -ttli and -tstop? That would be very useful~ thank you for your good work 👍

**Comment by AndreaLanfranchi** [comment]
Since release 0.15.0rc0 --tstart and --tstop arguments are functional.
See https://github.com/ethereum-mining/ethminer/blob/master/CHANGELOG.md#added-1

Ethminer, at the moment, does not support low intensity mode.
