### ISSUE TITLE
CUDA error in func 'search' at line 346 : unknown error. 

### ISSUE THREAD

**Issue by philejmath** [ethereum-mining/ethminer#128]
not sure if this is related to the other issues reported around search. seems to be a different line and message. miner hangs and attempts to kill the process crash my whole rig. 

ubuntu 16.04, no OC, version .0.12.0.dev0 4x Asus 1060 Turbo 

error: 

CUDA error in func 'search' at line 346 : unknown error.  
05:07:10|cudaminer2  Error CUDA mining: unknown error
CUDA error in func 'search' at line 346 : unknown error. 
05:07:10|cudaminer3  Error CUDA mining: unknown error

strace: 

prctl(PR_GET_NAME, "ethminer")          = 0
write(2, "\33[32m  m  \33[35m00:15:25\33[0m\33[30m"..., 112) = 112
write(2, "\n", 1)                       = 1
nanosleep({0, 200000000}, NULL)         = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3545, ...}) = 0
prctl(PR_GET_NAME, "ethminer")          = 0
write(2, "\33[32m  m  \33[35m00:15:25\33[0m\33[30m"..., 112) = 112
write(2, "\n", 1)                       = 1
nanosleep({0, 200000000}, NULL)         = 0
futex(0x7ffeece242a8, FUTEX_WAIT_PRIVATE, 2, NULL

**Comment by mauadib** [comment]
I have asus GTX 1070 cards and I have hangs and random computer resets while mining..

**Comment by rizwansarwar** [comment]
@philejmath  @mauadib  check #72

**Comment by mauadib** [comment]
These are happening at stock frequencies NO OC at all, it is intermittent, I'm also using cuda-parallel-hash 1. The latest NVidia drivers 384.

**Comment by rizwansarwar** [comment]
@mauadib what card and what OS?

**Comment by philejmath** [comment]
I'm using drivers 381.22, I'm going to try and upgrade to 384 and see if I get the same error as #72

**Comment by mauadib** [comment]
Asus GTX 1070 gaming, Win 10, 384.54 drivers.

**Comment by ultimakaz** [comment]
palit gtx 1060 3gb, win 10, 382.74 drivers.

CUDA error in func 'ethash_cuda_miner::search' at line 365 : unspecified launch failure.
  X  21:44:37|cudaminer1  Error CUDA mining: unspecified launch failure

**Comment by bartocc** [comment]
Same here with the following setup:

- drivers 381.22
- GPU: Asus gtx 1060 3Gb Dual OC
- OS: Ubuntu 16.04

**Comment by FabianGabor** [comment]
Same here: 

driver: 384.76
GPU: GTX 1060 6GB
OS: Win 10 x64 (latest updates)

**Comment by derubm** [comment]
Windows: (linux should be easier to do) 
https://github.com/derubm/Ethminer_Watchdog

**Comment by Malapha** [comment]
[see here](https://github.com/ethereum-mining/ethminer/issues/72)

**Comment by MariusVanDerWijden** [comment]
Is this still relevant?

**Comment by AndreaLanfranchi** [comment]
Yes it is still relevant.
Especially in junction with the fact that to avoid this you have to lower too much your overclock settings.
To avoid this error you have to stay 12%~15% less overclocked than in Claymore's which is a lot.

**Comment by DeadManWalkingTO** [comment]
GTX1060 +150/+500/65%TDP @ 23-24MHs

1. Try Update Drivers.
Download and install the latests.

2. Try Update Ethminer.
Download (or beter build) the latest.

3. Try use -U for CUDA devices.
CUDA Hardware Test Launch Command:
`ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

4. Try to change P2 State and Power managment mode.
You can use [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW).
For the best mining hashrate choose from sector "5 - Common":
    - CUDA - Force P2 State (Set to "Off")
    - Power managment mode (Set to "Prefer maximum performance")

5. Try Tweak Win10.
You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) (#695).

6. Try Optimize/Overclock GPUs. 
You can use [MSI Afterburner](https://www.msi.com/page/afterburner) for GPU OverClock/Optimize. 

7. Try use a WatchDog
You can use [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) (#735).

Please feedback.
Thank you!
