### ISSUE TITLE
Take care of community tasks

### ISSUE THREAD

**Issue by XhmikosR** [ethereum-mining/ethminer#1280]
https://github.com/ethereum-mining/ethminer/community

Add a couple issue templates, etc

**Comment by nalyd88** [comment]
To create a code of conduct a community email address is needed. Does that exist? If not can we create one?

**Comment by XhmikosR** [comment]
@nalyd88: you can add @chfast's email address if he agrees. Otherwise just skip CoC.

**Comment by chfast** [comment]
I'm against of code of conducts in general.

**Comment by XhmikosR** [comment]
Ok, then we just skip CoC :)

**Comment by AndreaLanfranchi** [comment]
You may start with a clone of the repository, do your changes, and submit them with a pull request.
Eventually the PR will be reviewed and, if correct and meaningful, approved and merged into repo.
