### ISSUE TITLE
FS -exit removal

### ISSUE THREAD

**Issue by R00dNet** [ethereum-mining/ethminer#1290]
Hi

I mine multi algos that switch to most profitable. FS -exit would stop miner and move onto next algo in old ethminer. --exit and --response-timeout 1 does not do this. I cannot see what setting has replaced FS -exit in help either.

Please advise.

**Comment by smurfy** [comment]
You need to use the new ``-P`` syntax.  So ``-P stratum....``  for your pool and then a second ``-P exit``  to have the same behavior ``-FS exit`` provided in the past.
