### ISSUE TITLE
How do I load the code into the MVS 17?

### ISSUE THREAD

**Issue by Nikolaev-Nikolay** [ethereum-mining/ethminer#1297]
How do I load the code into the MVS 17 - what would it be to write the code and compile it? 

not from the command line but in MVS17?
I'm new to the studio did not work.

**Comment by AndreaLanfranchi** [comment]
Read the docs https://github.com/ethereum-mining/ethminer/blob/master/docs/BUILD.md

**Comment by Nikolaev-Nikolay** [comment]
Setup GIT:

User@NNGEO MINGW64 /e/5/ethminer-0.15.0rc2
$ git submodule update --init --recursive
fatal: not a git repository (or any of the parent directories): .git

Where is the repository of GIT?
In the source folder there is no .git?
W10 I do not understand something.

Help me.

**Comment by AndreaLanfranchi** [comment]
You do not need MINGW64 on windows.
If you want to work with Visual Studio 2017 you have to **clone** this repository using git.
This means you have to :

1. Install GitHub Desktop client for windows https://desktop.github.com/
2. **Clone** the repository locally
3. Open a command prompt and go to the directory where project has been cloned
4. Follow what's described in the windows section of this document https://github.com/ethereum-mining/ethminer/blob/master/docs/BUILD.md

**Comment by Nikolaev-Nikolay** [comment]
E:\GitHub\ethminer\build>cmake --build .
Microsoft (R) Build Engine версии 15.6.85.37198 для .NET Framework
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

MSBUILD : error MSB1009: файл проекта не существует.
Ключ: ALL_BUILD.vcxproj

E:\GitHub\ethminer\build>

write '  the project file does not exist.'
What am I doing wrong?
Please Help!
