### ISSUE TITLE
Mining Machine Hang When Run 6 GPU (Claymore)

### ISSUE THREAD

**Issue by soohan92** [ethereum-mining/ethminer#1305]
I am mining using 6 GPU with Gigabyte XP1200M PSU.
3 x Gigabyte 1060 6GB
1 x Gigabyte 1070 6GB
2 x Msi 1060 6GB

I have been running it for 6 months using Claymore until 1 day it stop with page size error. I have increase the page size and it continue to run for few days. But now when i start the batch file, when it reach Setting DAG epoch, the GPU just hang and blow very fast and loud. Next windows will freeze and went to error. There are several windows error, one of it is WATCHDOG VIOLATION. 

I am able to run few GPU without problems, combinations I tried.
1) Running each of them 1 by 1
2) Running 3 x 1060
3) Running 1 x 1070 and 1 x 1060

Issue happens when i run:
1) All 6 GPU
2) 1 x 1070 and 2 x 1060
3) All 1060

**Comment by AndreaLanfranchi** [comment]
I am sorry but this is not Claymore's support area.
