### ISSUE TITLE
(AMD) only dectecting onboard gpus. 

### ISSUE THREAD

**Issue by TNguyen501** [ethereum-mining/ethminer#1307]
Sorry if this is a repeat. Looked but didn't see any related issue like mine. Or I might have missed.

Anyway. It only dectect my onboard gpus. This is what I use:

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 10
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer -P -G stratum1+ssl://xxxxxxxxxxxxxxxxxxxx2.MiningRig1@us1.ethermine.org:5555

I tried Claymore and Phoenix miner they both dectected my other 7 AMD gpus.

**Comment by AndreaLanfranchi** [comment]
What is the output of the following command ?

`ethminer -X --list-devices `

**Comment by AndreaLanfranchi** [comment]
Report the output please.

**Comment by smurfy** [comment]
@TNguyen501 

Use ``--opencl-platform 1``  or ``--opencl-platform 2``  this should work.

**Comment by TNguyen501** [comment]
@smurfy 
--opencl-platform 1 worked thank.
