### ISSUE TITLE
Can't see worker name on ethermine.org

### ISSUE THREAD

**Issue by yoryer** [ethereum-mining/ethminer#131]
hi everyone!

I know this probably isn't an important thing but using the new version of ethminer 0.11 I can't see the name of my rigs on ethermine.org dashboard.

It's showing "default" as worker, but I have 2 machines running ethminer and I want to know how they perform separatedly.

Using the ethminer-0.9.41-genoil-1.1.7  with the option -O "wallet"."rig-name" used to work just fine.

If somebody could help me I would really appreciate.

--

I have running two rigs:

RIG - A

2x ZOTAC GTX 1060 AMP Edition 6Gb: ~25-26Mh/s (each one)
Overclocking with MSI Afterburner:
- Power: 100%
- Temp: 80º
- GPU clock: +160
- Memory clock: +975

RIG - B

1x Gigabyte Xtreme Gaming GTX 1060 6Gb: ~25Mh/s
Overclocking with MSI Afterburner:
- Power: 80%
- Temp: 75º
- GPU clock: +100
- Memory clock: +950

**Comment by jimmykl** [comment]
My rig names show on ethermine.org I use ```-O Oxblahblahblah.rigname```. I assume you're not putting them inside quotes?

**Comment by yoryer** [comment]
No, I'm not using quotes on the wallet or the rigname. I was thinking maybe could be the position of the parameters, so I put it to the end of the config line but doesn't change anything.

**Comment by yoryer** [comment]
After trying different things, I opened my .bat file with Notepad++ and I found before mi rig name some kind of return character that I can't see on Windows.
I really forgot about CL/RF return character differences between Windows and *nix systems, so after editing the file with Notepad++ now I can see the name of my rigs.
Sorry for the misunderstood!
