### ISSUE TITLE
API: miner_addconnection(docu) vs miner_addpool(source)

### ISSUE THREAD

**Issue by StefanOberhumer** [ethereum-mining/ethminer#1317]
In the documentation https://github.com/ethereum-mining/ethminer/blob/master/docs/API_DOCUMENTATION.md#miner_addconnection the function is named **miner_addconnection**

In the source (https://github.com/ethereum-mining/ethminer/blob/668368d2f65dd9cc5c6c0a3e4edc0997c7936499/libapicore/ApiServer.cpp#L267) the function is called **miner_addpool**

Not sure how we should name it ?

**Comment by AndreaLanfranchi** [comment]
Should be addconnection.
Sorry .. my fault.
