### ISSUE TITLE
W10 cod is not compiled  Cmake error! Help...

### ISSUE THREAD

**Issue by Nikolaev-Nikolay** [ethereum-mining/ethminer#1320]
Nothing helps and does not Google. Please help - does not want to compel code under W10 64

[hunter ** FATAL ERROR **] Build step failed (dir: C:/.hunter/_Base/0056188/f0fc498/834ecbe/Build/CLI11
[hunter ** FATAL ERROR **] [Directory:C:/.hunter/_Base/Download/Hunter/0.21.9/0056188/Unpacked/cmake/projects/CLI11]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.21.9/0056188/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.21.9/0056188/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  C:/.hunter/_Base/Download/Hunter/0.21.9/0056188/Unpacked/cmake/modules/hunter_download.cmake:672 (hunter_fatal_error)
  C:/.hunter/_Base/Download/Hunter/0.21.9/0056188/Unpacked/cmake/projects/CLI11/hunter.cmake:32 (hunter_download)
  C:/.hunter/_Base/Download/Hunter/0.21.9/0056188/Unpacked/cmake/modules/hunter_add_package.cmake:53 (include)
  ethminer/CMakeLists.txt:13 (hunter_add_package)

**Comment by Nikolaev-Nikolay** [comment]
Yes, Yes, Yes, it is compil!
Cmake write: 
 -- Configuring done
-- Generating done
-- Build files have been written to: D:/GitHub/ethminer/build


And how to make exe?!

**Comment by Nikolaev-Nikolay** [comment]
It's True W10?!
end CMakeLists.txt:
------------------------------------- 
if(WIN32)
add_executable (${PROJECT_NAME} ${MAIN_SOURCES} ${SOURCES})

target_link_libraries (${PROJECT_NAME} ${ADDITIONAL_LIBRARIES})

set_target_properties(${PROJECT_NAME} PROPERTIES VERSION "${${PROJECT_NAME}_VERSION}" SOVERSION "0")

INSTALL (
    TARGETS
    ${PROJECT_NAME}
    DESTINATION
    lib${LIB_SUFFIX}
)

INSTALL (
    FILES
    ${PUBLIC_HEADERS}
    DESTINATION
    include/${PROJECT_NAME}
)
endif()

--------------------------

**Comment by AndreaLanfranchi** [comment]
> And how to make exe?!

simply execute 

`cmake --build . --config Release`

you will get your exe
