### ISSUE TITLE
does 0.15 require cuda 9.2?

### ISSUE THREAD

**Issue by aleqx** [ethereum-mining/ethminer#1321]
Or is it just the released binaries that were compiled against cuda 9.2? Sorry if this was mentioned somewhere. I have cuda9.1 installed and the released 0.15rc2 binary (Linux) says:

```
Error: Insufficient CUDA driver: 9010
```

**Comment by MariusVanDerWijden** [comment]
Yes, the binaries are compiled with cuda 9.2
https://github.com/ethereum-mining/ethminer/blob/master/circle.yml

**Comment by MariusVanDerWijden** [comment]
@piotr-dobrogost Oh yes, sorry I misread. 
The precompiled binaries are compiled with 9.2.
If you compile your own binaries, you have to use 9.+ 
You can use 9.0 if you want to (as currently in the appveyor build)
https://github.com/ethereum-mining/ethminer/blob/master/appveyor.yml
