### ISSUE TITLE
bat file doesn't work with new ethminer

### ISSUE THREAD

**Issue by erkange** [ethereum-mining/ethminer#1323]
Version : ethminer-0.14.0rc1
OS : Windows 10

I have 2 bat file line but both have issue.
How to make it work?

This one can't connect to pool.
`ethminer.exe -HWMON 1 -U -P stratum+tcp://0x3efe7f61e33e67e29ad181f4ee2266684f470cfa.rig001@etc.arsmine.net:8888`

below one can connect to pool but keep saying S or O is deprecated.
`ethminer.exe -HWMON 1 -S etc.arsmine.net:8008 -SP 1 -O 0x3efe7f61e33e67e29ad181f4ee226a5866670cfa.rig001 --cuda`

meesages;
Warning: -S is deprecated. Use the -P parameter instead.
Warning: -SP is deprecated. Use the -P parameter instead.
Warning: -O is deprecated. Use the -P parameter instead.

**Comment by AndreaLanfranchi** [comment]
There are differences among the two.
In the second one you specify -SP 1 (stratum protocol 1) but in the first one you don't.

For the first one to run you have to set 

-P **stratum1**+tcp://[...] (note the 1 suffix for stratum.)

**Comment by erkange** [comment]
Thanks but didn't worked.
 Could not connect to stratum server etc.arsmine.net:8888, A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by erkange** [comment]
new line was below, but couldn't connect the pool;
`ethminer.exe -HWMON 1 -U -P stratum1+tcp://0x3efe7f61e33e67e29ad181f4ee226fff584f470cfa.rig001@etc.arsmine.net:8888`
