### ISSUE TITLE
REQUEST: GCC7 Support (Archlinux): gcc versions later than 7 are not supported!

### ISSUE THREAD

**Issue by alkavan** [ethereum-mining/ethminer#1327]
So this error comes from my system cudo install on Arch at `/opt/cuda/`
Since the issue is with the CUDA, anyone is aware of some quick workaround, parhaps a patch so I won't have to build with GCC6? can this built with Clang? Any instructions?

I woulld really like to make an AUR package for this miner for ArchLinux...

```
[ 41%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
In file included from /opt/cuda/include/host_config.h:50,
                 from /opt/cuda/include/cuda_runtime.h:78,
                 from <command-line>:
/opt/cuda/include/crt/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 7 are not supported!
 #error -- unsupported GNU version! gcc versions later than 7 are not supported!
  ^~~~~
[ 58%] Built target poolprotocols
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.Release.cmake:219 (message):
  Error generating
  /home/wdna/Develop/ethminer/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o


make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:65: libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:492: libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by XhmikosR** [comment]
You can always try to modify the CUDA header and change the GCC check. But that isn't the proper way.

**Comment by divinity76** [comment]
i imagine this is a very temporary issue, if the cuda library has maintainers. any info on that?

**Comment by gianlucastella1** [comment]
At https://wiki.archlinux.org/index.php/GPGPU#CUDA there's a note:
> CUDA 9.2 is not compatible with GCC 8 (see FS#49272 for the history). Therefore the cuda package depends on gcc7 [CUT]

Did you try updating the cuda package? 
The 9.2 package is available since  May 30, as shown at
https://www.archlinux.org/packages/?sort=&arch=x86_64&q=cuda

**Comment by chfast** [comment]
CUDA does not support GCC 8 yet. Install GCC 7 or beg Nvidia for support.

**Comment by freedom9393** [comment]
This solved my problem:
`sudo rm /usr/local/cuda/bin/gcc`
`sudo apt install gcc-7 g++-7`
`sudo ln -s /usr/bin/gcc-7 /usr/local/cuda/bin/gcc`
`sudo ln -s /usr/bin/g++-7 /usr/local/cuda/bin/g++`
