### ISSUE TITLE
How to add failover servers?

### ISSUE THREAD

**Issue by erkange** [ethereum-mining/ethminer#1328]
I use below code. But how i can add second pool address just in case first one is down?

```
ethminer.exe -HWMON 1 -U --exit -P stratum1+tcp://0x3efe7f61e33e67e29ad181f4ee226fsdsd4f470cfa.rig003@etc.arsmine.net:8008 --cuda
````

**Comment by AndreaLanfranchi** [comment]
Simply add another -P valued argument. You can add as many as you want.

**Comment by erkange** [comment]
Thanks, how? Can you make me an example line? Please :)

**Comment by AndreaLanfranchi** [comment]
Simple as that 

`ethminer.exe -HWMON 1 -U --exit -P stratum1+tcp://0x3efe7f61e33e67e29ad181f4ee226fsdsd4f470cfa.rig003@etc.arsmine.net:8008 -P stratum+tcp://0x3efe7f61e33e67e29ad181f4ee226fsdsd4f470cfa.rig003@eu1.ethermine.org:4444`
