### ISSUE TITLE
Socket connection failed - Pool

### ISSUE THREAD

**Issue by zephyr125** [ethereum-mining/ethminer#1329]
Hi, 

Can anyone help out why the ethminer 14.0 cannot connect to the pool,

Website: https://eth.sparkpool.com/

Error: Socket connection failed 

Pool Address
Mainland China | cn.sparkpool.com | 3333 | 13333
US West | na-west.sparkpool.com | 3333 | 13333
US East | na-east.sparkpool.com | 3333 | 13333
Europe | eu.sparkpool.com | 3333 | 13333
Southeast Asia | asia.sparkpool.com | 3333 | 13333
Taiwan | tw.sparkpool.com | 3333 | 13333
Korea | kr.sparkpool.com | 3333 | 13333
Japan | jp.sparkpool.com | 3333 | 13333

**Comment by AndreaLanfranchi** [comment]
Post the complete launch of ethminer including all parameters you set and the first lines of the output.

**Comment by AndreaLanfranchi** [comment]
Apparently not ethminer's fault.
All connections to sparkpool keep being resetted.
Suggest to contact pool's administrators.
