### ISSUE TITLE
Can I use an older BUILD for my 2GB GPU?

### ISSUE THREAD

**Issue by marcofranssen** [ethereum-mining/ethminer#133]
Hi I was wondering if there is an older version available to do some mining on my 2GB ATI GPU. Or is there something I can change in code to make it possible and compile my own. I know it will probably be slower and less performing, but I accept that.

**Comment by mauadib** [comment]
The ethereum DAG memory file is >2GB now so no not enough memory on the video card to mine.

**Comment by marcofranssen** [comment]
So what defines the size of the DAG file? That probably also clarifies why on my old laptop the miner pretty often hangs and needs a restart.

**Comment by mauadib** [comment]
The block height if memory serves and this is pre-generated by the mining software on board the GPU it is a memory hard algorithm to stop ASICS and other dedicated hardware from completely taking over. The memory file now exceeds 2GB and is held on board the GPU before mining begins. That;s why hardware suppliers have lots of 1GB and 2GB video cards in stock but sold out of the 4GB-8GB models.

**Comment by jimmykl** [comment]
Hi @marcofranssen if your question is answered could you please close this issue? Thanks!

**Comment by EoD** [comment]
There is an enhancement request #87 for cards with RAM<DAG-size, just continue there.
