### ISSUE TITLE
API server should accept requests with string ID

### ISSUE THREAD

**Issue by gianlucastella1** [ethereum-mining/ethminer#1330]
As stated in [JSONRPC 2.0 specs](https://www.jsonrpc.org/specification#request_object)

> An identifier established by the Client that MUST contain a String, Number, or NULL value if included.

ApiServer checks for an unsigned request ID only, returning error -32600 (Invalid Request) in case of a string ID.

**Comment by AndreaLanfranchi** [comment]
Technically speaking you're right.
However all implementations use unsigned integers for id.
Matching for string literals would be an extra checking.

**Comment by gianlucastella1** [comment]
> However all implementations use unsigned integers for id.
I don't know "all implementations", I'm using [Tivoka client library](https://github.com/marcelklehr/tivoka) and it forges a UUID as request ID.

**Comment by AndreaLanfranchi** [comment]
We're working in the world of mining where **all** JSON-RPC messages are marked with id as unsigned integer. Unfortunately JSONRPC specs (both 1 and 2) are NOT 100% honored.

You can propose a PULL REQUEST if you want to change.
