### ISSUE TITLE
What is the best bat command for Nvidia P104 cards?

### ISSUE THREAD

**Issue by erkange** [ethereum-mining/ethminer#1334]
I am using this line for my P104's.

> ethminer.exe -U --HWMON 1 --exit -P 
 stratum1+tcp://0x3efe7f61e33e67e29ad181f4ee226a584f470cfa.rig001@etc1.tr.arsmine.net:8008

power limit %70, core 0, mem +600.

Can you suggest better settings?
Should i add cuda settings?

CUDA Options:
  --cuda-grid-size UINT=8192  Set the grid size
  --cuda-block-size UINT=128  Set the block size
  --cuda-devices UINT ...     Select list of devices to mine on (default: use all available)
  --cuda-parallel-hash UINT in {1,2,4,8}=4
                              Set the number of hashes per kernel
  --cuda-schedule TEXT in {auto,spin,sync,yield}=sync
                              Set the scheduler mode
  --cuda-streams UINT=2       Set the number of streams

**Comment by AndreaLanfranchi** [comment]
Default settings are, generally speaking, best.

You might wish to underclock cores

**Comment by Nikolaev-Nikolay** [comment]
:start

set GPU_FORCE_64BIT_PTR=0
set GPU_MAX_HEAP_SIZE=100
set GPU_USE_SYNC_OBJECTS=1
set GPU_MAX_ALLOC_PERCENT=100
set GPU_SINGLE_ALLOC_PERCENT=100
start ethminer.exe -U  --HWMON=1 --farm-recheck 500 --cl-local-work 128 --cl-global-work 16384 --noeval --cuda-parallel-hash 4 --exit stratum1+tcp://0x48ac286ae23f2cbba7bb5b9c5715ff5a7f903c2d@eth-ru2.dwarfpool.com:8008/nngeo

REM Sleep for 5 seconds
ping 127.0.0.1 -n 3600 > nul

taskkill /f /im ethminer.exe > nul

REM Sleep for 10 seconds
ping 127.0.0.1 -n 10 > nul

set GPU_FORCE_64BIT_PTR=0
set GPU_MAX_HEAP_SIZE=100
set GPU_USE_SYNC_OBJECTS=1
set GPU_MAX_ALLOC_PERCENT=100
set GPU_SINGLE_ALLOC_PERCENT=100
start ethminer.exe -U  --HWMON=1 --farm-recheck 500 --cl-local-work 128 --cl-global-work 16384 --noeval --cuda-parallel-hash 4 --exit stratum1+tcp://0x48ac286ae23f2cbba7bb5b9c5715ff5a7f903c2d@eth-ru.dwarfpool.com:8008/nngeo

REM Sleep for 5 seconds
ping 127.0.0.1 -n 3600 > nul

taskkill /f /im ethminer.exe > nul

REM Sleep for 10 seconds
ping 127.0.0.1 -n 10 > nul

REM Return to start
goto start


pause

**Comment by AndreaLanfranchi** [comment]
Which is the question ?

**Comment by Nikolaev-Nikolay** [comment]
it is possible as that to make that when we allow when 5 rejection  or the pool is not available that the miner switches to the next pool from the list. Can a new key do?

**Comment by AndreaLanfranchi** [comment]
@Nikolaev-Nikolay your question has nothing to do with this issue.

**Comment by Nikolaev-Nikolay** [comment]
I'm sorry...

**Comment by ddobreff** [comment]
For P104 specifically he needs to bump core a bit, not lower it.
+100/+150 depends on GPU itself +800/900(linux so windows /2) for mem is best for P104-100 mining cards. Powerlimit of 120/130W for these is fine ~65/70% on windows.

**Comment by AndreaLanfranchi** [comment]
Closing as it's not a functional issue.
