### ISSUE TITLE
ethminer crash in v0.15.0rc2

### ISSUE THREAD

**Issue by wujun** [ethereum-mining/ethminer#1339]
My environment is Ubuntu 16.04, Cuda 9.0 and Nvidia driver version is 387.34, pool: us1-etc.ethermine.org:4444. The error message is below:

  m  16:04:40|ethminer|  Speed  81.33 Mh/s    gpu/0 22.98  gpu/1 19.74  gpu/2 15.64  gpu/3 22.98  [A420+14:R0+0:F0] Time: 06:08
  m  16:04:45|ethminer|  Speed  81.52 Mh/s    gpu/0 22.98  gpu/1 19.83  gpu/2 15.64  gpu/3 23.07  [A420+14:R0+0:F0] Time: 06:08
  m  16:04:50|ethminer|  Speed  81.80 Mh/s    gpu/0 23.16  gpu/1 19.92  gpu/2 15.64  gpu/3 23.07  [A420+14:R0+0:F0] Time: 06:08
  m  16:04:55|ethminer|  Speed  82.11 Mh/s    gpu/0 23.15  gpu/1 20.00  gpu/2 15.73  gpu/3 23.23  [A420+14:R0+0:F0] Time: 06:08
  ℹ  16:04:57|cuda-2  |  Nonce 0x9a5d60dbb824c5d9                                                                  
  ✘  16:04:59|stratum |  No response received in 2 seconds.                                                                     
  ℹ  16:04:59|stratum |  Disconnected from us1-etc.ethermine.org  [54.177.207.188:4444]                                         
  ℹ  16:04:59|stratum |  Shutting down miners...
  m  16:05:00|ethminer|  not-connected
*** Error in `ethminer': double free or corruption (fasttop): 0x00007fc47c001390 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fc4d0ac27e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7fc4d0acb37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fc4d0acf53c]
ethminer(_ZN3dev3eth4Farm4stopEv+0x12c)[0x52eebc]
ethminer[0x53193a]
ethminer(_ZN16EthStratumClient10disconnectEv+0x170)[0x5451e0]
ethminer(_ZN16EthStratumClient24response_timeout_handlerERKN5boost6system10error_codeE+0x11f)[0x53fb2f]
ethminer(_ZN5boost4asio6detail12wait_handlerINS_3_bi6bind_tIvNS_4_mfi3mf1Iv16EthStratumClientRKNS_6system10error_codeEEENS3_5list2INS3_5valueIPS7_EEPFNS_3argILi1EEEvEEEEEE11do_completeEPvPNS1_19scheduler_operationESB_m+0xa5)[0x538de5]
ethminer(_ZN5boost4asio6detail9scheduler3runERNS_6system10error_codeE+0x414)[0x500cd4]
ethminer(_ZN5boost4asio10io_context3runEv+0x25)[0x5042a5]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80)[0x7fc4d13ecc80]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7fc4d16bd6ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fc4d0b5241d]
======= Memory map: ========
00400000-00d13000 r-xp 00000000 08:01 35913744                           /usr/bin/ethminer
00f13000-00f35000 r--p 00913000 08:01 35913744                           /usr/bin/ethminer
00f35000-00f44000 rw-p 00935000 08:01 35913744                           /usr/bin/ethminer
00f44000-00f4d000 rw-p 00000000 00:00 0
023b1000-0243a000 rw-p 00000000 00:00 0                                  [heap]
200000000-600200000 ---p 00000000 00:00 0
700000000-b00200000 ---p 00000000 00:00 0
10000000000-10800000000 ---p 00000000 00:00 0
7fc454000000-7fc45541d000 rw-p 00000000 00:00 0
7fc45541d000-7fc458000000 ---p 00000000 00:00 0
7fc45c000000-7fc45d242000 rw-p 00000000 00:00 0
7fc45d242000-7fc460000000 ---p 00000000 00:00 0
7fc460000000-7fc461242000 rw-p 00000000 00:00 0
7fc461242000-7fc464000000 ---p 00000000 00:00 0

**Comment by yong0706** [comment]
This is one of reason why I had to switch back to v0.14.0.
Just wild guess, it seems there is thread synchronization issue after lost connection.

**Comment by chfast** [comment]
Is this fixed?

**Comment by AndreaLanfranchi** [comment]
@chfast for what concerns my findings yes it's fixed.
