### ISSUE TITLE
Is there issue with 1063 cards?

### ISSUE THREAD

**Issue by serzhblack** [ethereum-mining/ethminer#1340]
Hi!

I think I hove some problem. Please help me
I have 2 cards: GPU0 1066 and GPU1 1063
I mine ETC on etc.ethermine.org
Here is ethminer output:
`
m 12:44:52 main     Speed  46.73 Mh/s    gpu/0 23.27  gpu/1 23.46  [A8+0:R0+0:F0] Time: 00:15
m 12:44:57 main     Speed  47.02 Mh/s    gpu/0 23.42  gpu/1 23.60  [A8+0:R0+0:F0] Time: 00:15
`
After a lot of time I see that counter of accepted shares increased only for GPU0. but GPU1 never found shares. Averege hashrate on the pool is 24 instead of reported is 48

If i try to run miner with --cuda-devices 1 then 1063 cards works fine

is there solution for this?

**Comment by AndreaLanfranchi** [comment]
Windows ? Linux ?
Version of ethminer you're using ?

**Comment by serzhblack** [comment]
oh. sorry  for that. win7x64. 391.01 and 397.55 just installed

**Comment by AndreaLanfranchi** [comment]
Version of ethminer ?

**Comment by serzhblack** [comment]
ethminer 0.15.0rc2

**Comment by AndreaLanfranchi** [comment]
> After a lot of time I see that counter of accepted shares increased only for GPU0. but GPU1 never found shares. 

How can you tell this ? the counter we provide is not per GPU. Is global.

> Averege hashrate on the pool is 24 instead of reported is 48

Average hashrate is NEVER the same as reported hashrate. It fluctuates (a lot) depending on your luck.

**Comment by serzhblack** [comment]
I look at [A;100+0] is it not right?
the luck can not be constantly half of reported hashrate. pool with another miner show me average HR about of 48 MH\s that is seems more true.

**Comment by AndreaLanfranchi** [comment]
Nope.

 [A;100+0] means Accepted 100 with 0 stale. It does not mean 100 shares from GPU0 and 0 shares from GPU1

**Comment by AndreaLanfranchi** [comment]
> pool with another miner show me average HR about of 48 MH\s that is seems more true.

Same pool ?
Have you run ethminer for at least 6 hours ?

**Comment by serzhblack** [comment]
I began to suspect this ) thank you
can you please answer me what R0+0 is?
PS: yes. same pool. I remember that I switch to another miner due to "small luck" of ethminer. now I returned to my problem again. New ethminer and drivers version. Started ti mine right now. Will keep track and response latter within some of hours

**Comment by AndreaLanfranchi** [comment]
> can you please answer me what R0+0 is?

R=Rejected 
R0+0 means 0 rejects + 0 stale rejects.

This particular info have been removed in latest developer release as stale rejects have no meaning.

**Comment by divinity76** [comment]
i use this php script to check shares (and ram errors) per gpu:

```php
#!/usr/bin/env php
<?php
declare(strict_types = 1);
if(@include_once ('hhb_.inc.php')){
	hhb_init(); // optional, better php error reporting
}
$logs = glob ( "*.log" );
$key = array_search ( "stderr.mining.log", $logs, true );
if ($key !== false) {
	// make sure it's the last on the list.
	unset ( $logs [$key] );
	$logs [] = 'stderr.mining.log';
}
$blacklist = array (
		'errorlog.log',
		'mining.log' 
);
foreach ( $logs as $log ) {
	if (in_array ( $log, $blacklist, true )) {
		continue;
	}
	echo hex2bin ( "1b5b303b33326d" ) . "$log" . hex2bin ( "1b5b306d" ) . ": \n";
	f ( $log );
}
function f(string $filename) {
	$fuckery = function (array $arr): array {
		$total = 0;
		foreach ( $arr as $tmp ) {
			$total += $tmp;
		}
		foreach ( $arr as &$tmp ) {
			$tmp = "$tmp (" . number_format ( (($tmp / $total) * 100), 1, ".", "" ) . "%)";
		}
		// ksort ( $arr );
		natsort ( $arr );
		return $arr;
	};
	$raw = shell_exec ( 'cat ' . escapeshellarg ( $filename ) . ' | grep --text inco' );
	if (! is_string ( $raw )) {
		echo "seems no incorrects was found...", PHP_EOL;
		$raw = "";
	}
	// $parsed1 = array_filter ( array_map ( 'trim', preg_split ( "/\n/", $raw ) ), 'strlen' );
	$parsed2 = preg_match_all ( "/cl\-(\d+)/", $raw, $matches );
	$ramErrors = [ ];
	foreach ( $matches [1] as $foo ) {
		$ramErrors[$foo] = ($ramErrors[$foo] ?? 0) + 1;
	}
	$ramErrors = $fuckery ( $ramErrors );
	echo 'ram errors: ';
	print_r ( $ramErrors );
	unset ( $raw, $matches, $parsed2, $foo );
	// $raw = shell_exec ( 'cat ' . escapeshellarg ( $filename ) . ' | grep --text \'submitted to\'' );
        $raw = shell_exec ( 'cat ' . escapeshellarg ( $filename ) . ' | grep --text Solution' );
	if (! is_string ( $raw )) {
		echo "seems no accepteds was found...", PHP_EOL;
		$raw = "";
	}
	// $parsed1 = array_filter ( array_map ( 'trim', preg_split ( "/\n/", $raw ) ), 'strlen' );
	$parsed2 = preg_match_all ( "/cl\-(\d+)/", $raw, $matches );
	$accepteds = [ ];
	foreach ( $matches [1] as $foo ) {
		$accepteds [$foo] = ($accepteds [$foo] ?? 0) +1;
	}
	$accepteds = $fuckery ( $accepteds );
	echo 'solutions: ';
	print_r ( $accepteds );
}

```

it requires that your ethminer stderr log ends with `.log`, and the output looks like:

![image](https://user-images.githubusercontent.com/1874996/42402286-121d51e4-817a-11e8-92da-81978a6fa074.png)

meaning [gpu num] => number_of_shares  / [gpu num] => number_of_invalid_shares

**Comment by serzhblack** [comment]
thank you for your help
now my problem is gone. mining is pretty enough
![default](https://user-images.githubusercontent.com/21081827/42435250-3cb698c4-8356-11e8-9662-cece934e1a94.png)
