### ISSUE TITLE
ETH-Nanopool not working since -autodetection improvement (nanopool bug)

### ISSUE THREAD

**Issue by MiningGuru** [ethereum-mining/ethminer#1348]
Hello,
I'm big fan of ethminer, often I use the latest appvenior builds. Since improvement -autodetection (for ssl and so on) all share were rejected. After that ethminer want to reconnect but all shares are also rejected.

from log output in console: rejected reason code 32700

The rejects exists since your "autodetection" improvment. I also did check the latest version but none of them works....

Perhaps you can fix that issue. It doesn't matter of hardware I checked several Rigs, everytime the same rejected (100% rejects...)

I did use the command to start ethminer:
(in .bat ethminer watchdog):
ethminer.exe --exit -U -P stratum1+tcp://0xmyWalletID@eth-eu1.nanopool.org:9999/RIGNAME/myemailadress@googlemail.com  --stratum-email myemailadress@googlemail.com --HWMON 1 -R --display-interval 10 --api-port 6000 --http-port 6001 --api-password dt

**Comment by AndreaLanfranchi** [comment]
Just checked and problem seems to be on Nanopool's side.
Apparently in ETHPROXY compatible mode they do not **push** new jobs to client but instead they wait for the client to issue getWork commands. Due to this miner keeps working on the same job and when finds a solution the rejection message is 

```
 i 15:16:06 cuda-0   Solution: 0x845ba3e39e40af93
 X 15:16:06 stratum  Reject reason :code:-32700 message:Work not found
```

**Comment by MiningGuru** [comment]
ok is there any workaround or fix for that issue?

**Comment by AndreaLanfranchi** [comment]
Confirmed ... NANOPOOL stratum implementation is messed up.

Here is the email I just wrote them

Hi, I'm a developer of ethminer https://github.com/ethereum-mining/ethminer

Recently we've added an "stratum autodetection" feature in ethminer which causes our miner to malfunction in bundle with your pool.
In detail we've found

**Wrong response to miner.subscribe nicehash mode (ethereumstratum)**

When issuing this method

```
{
    "id" : 1,
    "method" : "mining.subscribe",
    "params" : 
    [
        "ethminer 0.16.0.dev0+commit.ccf8722e.dirty",
        "EthereumStratum/1.0.0"
    ]
}

```
your server replies

```
{
    "id" : 1,
    "jsonrpc" : "2.0",
    "result" : true
}
```

which is **wrong** for two reasons

* Either you support nicehash mode and in that case your "result" member **MUST** contain an array
* Or you do not support it and in that case your response **MUST** be an error

**Wrong signalling of new jobs when in ETHPROXY compatible mode**

After previous attempt we login with

```
{
    "id" : 1,
    "method" : "eth_submitLogin",
    "params" : 
    [
        "0x4813aEEE0c30C584C559fa8Dc7424481E2e9Fc91"
    ]
}

```
and we get as a reponse

```
{
    "id" : 1,
    "jsonrpc" : "2.0",
    "result" : true
}

```
We also issue a eth_getWork method

```
{
    "id" : 5,
    "method" : "eth_getWork",
    "params" : []
}

```
which causes your reply to be

```
{
    "id" : 0,
    "jsonrpc" : "2.0",
    "result" : 
    [
        "0x6752081d812a286a1e5936b619d777fed2fe60e8f8b640e6228b4e9af14798ff",
        "0x0ba3f65a466961c3edca9c346b0309ece42b254e0d0868b5f5163dfd9c9a3512",
        "0x000000006df37f675ef6eadf5ab9a2072d44268d97df837e6748956e5c6c2116"
    ]
}
```

which is correct. But immediately after we begin to receive notifications of new jobs in another format like this

```
{
    "id" : 6,
    "jsonrpc" : "2.0",
    "method" : "mining.notify",
    "params" : 
    [
        "b9c4a261d998650b7c405d2c581db553f4b3bdaffcab7be0f8a053858ce6afb7",
        "b9c4a261d998650b7c405d2c581db553f4b3bdaffcab7be0f8a053858ce6afb7",
        "0ba3f65a466961c3edca9c346b0309ece42b254e0d0868b5f5163dfd9c9a3512",
        "000000006df37f675ef6eadf5ab9a2072d44268d97df837e6748956e5c6c2116",
        false
    ]
}

```
which is incompatible with ethproxy mode.

Can you please check and feed back ?

**Comment by MiningGuru** [comment]
Perfect!!!! it seemed to work now. Thanks Andrea Lanfranchi lightening workaround coding work!

**Comment by MiningGuru** [comment]
Think you can close #1349
