### ISSUE TITLE
Ver 16 Dev stale shares

### ISSUE THREAD

**Issue by whotheff** [ethereum-mining/ethminer#1350]
I was running ver 14 for a long time, but i got many many disconnects without reconnects to second pool address. That is why I tested the 16Dev and I really liked it.
Pros:
 1. hashrate slightly improved (from 126 to 128Mh/s)
2. hashing is really, really stable! constantly 128Mh/s and only the numbers behind the dot are changing.
Pool average per 20 hours reports 125.38 Mh/s
3. Rig is working for more than 20 hours with no issues (it used to crash 2-3 times a day with v. 14)

Cons:
1. Stale shares. With 14 I had a stale share once a day. Now I have it once every 2 hours.
2. Weird looking and complex syntax. It requires very well explained help file with examples, which is not the case. It took me about 1 hour to find online some examples before i manage to set up the bat file.

Please fix the stale shares and Ethminer will be number one!

**Comment by AndreaLanfranchi** [comment]
Wow ... only 1 stale share once a day ?
I am pretty confident noone here have ever experienced such an incredible result.
A very normal stale share ratio is among 2% to 5% max and frankly there are NO differences in stale shares among 0.14 and 0.15 or 0.16

There is very little (or nothing) ethminer can do to reduce stale shares as they're mostly produced by environment or pool condition. Essentially a stale share is a valid share found for a work which is no more current. If your pool sends new jobs at a very high rate then your stale share ratio is likely to increase. Another matter is network latency: when ethminer finds a solution it immediately pushes it to the pool but the trip to the pool takes time. If in that time another job becomes current then your "traveling share" becomes stale on the journey to pool.

Other factors are pool congestion, on large pools counts which ip you're connected to, blocks frequency and so on. All aspects which are beyond ethminer's scope. They all change constantly.

Anyway I'm glad to hear your first 3 points give you a better experience.

**Comment by AndreaLanfranchi** [comment]
> It took me about 1 hour to find online some examples before i manage to set up the bat file.

Have you checked our documentation section and pool samples files ?
https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md
