### ISSUE TITLE
Hashrate reduction caused by CPU load?

### ISSUE THREAD

**Issue by zypoi** [ethereum-mining/ethminer#1351]
One of my rig has lower hashrate than other rigs (about 140 on 6 RX580 GPUs).
I've checked the GPU status by journalctl and found these errors:

> Jul 11 08:45:34 rig014 kernel: amdgpu 0000:07:00.0: GPU fault detected: 146 0x08600404
Jul 11 08:45:34 rig014 kernel: amdgpu 0000:07:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0014350C
Jul 11 08:45:34 rig014 kernel: amdgpu 0000:07:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x06004004
Jul 11 08:45:34 rig014 kernel: amdgpu 0000:07:00.0: VM fault (0x04, vmid 3) at page 1324300, read fro
Jul 11 08:45:34 rig014 kernel: amdgpu 0000:07:00.0: GPU fault detected: 146 0x08604404
Jul 11 08:45:34 rig014 kernel: amdgpu 0000:07:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0014350C
Jul 11 08:45:34 rig014 kernel: amdgpu 0000:07:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x0C044004
Jul 11 08:45:34 rig014 kernel: amdgpu 0000:07:00.0: VM fault (0x04, vmid 6) at page 1324300, read fro
Jul 11 08:45:35 rig014 kernel: amdgpu 0000:07:00.0: GPU fault detected: 147 0x08988408
Jul 11 08:45:35 rig014 kernel: amdgpu 0000:07:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0014A513
Jul 11 08:45:35 rig014 kernel: amdgpu 0000:07:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x04084008
Jul 11 08:45:35 rig014 kernel: amdgpu 0000:07:00.0: VM fault (0x08, vmid 2) at page 1352979, read fro
Jul 11 08:45:35 rig014 kernel: amdgpu 0000:07:00.0: GPU fault detected: 147 0x0fd84808
Jul 11 08:45:35 rig014 kernel: amdgpu 0000:07:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0014A59C

And the CPU load is about 0.5, higher than other rigs(0-0.1).

I've changed some of the riser and the problem still occurs. Also I've tried to mine using only one GPU, the load is about 0.05 and the hashrate is normal (30 on RX580).

So what exacltly caused the problem.

**Comment by AndreaLanfranchi** [comment]
What you've posted is pretty self explanatory.
Seems like you have a problem on the GPU marked with PCI Bus Id 00:07:00

It's likely you have two miners trying to access the same GPU.
How are you using ethminer ? Are you using any "so called" mining distro ? (EthOS or HiveOS) ?

**Comment by zypoi** [comment]
I did not using any mining distro, and I am sure that there is only one ethminer on each of my rigs.

The GPU 00:07:00 is overclocked and there is something wrong. I have reset the bios. But the hashrate still drops after several hours

**Comment by AndreaLanfranchi** [comment]
You may try to swap pci slot of this card. If problems disappear and emerge on another card then you have problems on the pci slot or on the riser. If the problem persist on same card with different pci id then it's the card which is defective.

**Comment by zypoi** [comment]
I've checked all the risers and cards. Found that the problem is caused by overclocking.

Thank you for your advice.
