### ISSUE TITLE
Claymore Miner sudden hashrate drop - ETH

### ISSUE THREAD

**Issue by orangearmy** [ethereum-mining/ethminer#1353]
I have been part of Ethermine pool for over a year and no issues until a few days ago.  Steady 29+ mh/s on 4 diff rigs.  Hashrate has suddenly dropped to 5mh/s on all 4 rigs.  I reinstalled Win10 on 1 of the rigs and same issue.  Any help will be much appreciated.  Pls see screenshot.

Win10 Pro 64bit
Sapphire Pulse RX 570 4G and 580 8G
Claymore Miner v9.6

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
EthDcrMiner64.exe -epool us1.ethermine.org:4444

[https://imgur.com/a/Fm6e2ee](url)

**Comment by AndreaLanfranchi** [comment]
No Claymore support here.
We're ethminer.
