### ISSUE TITLE
help please: No work, Pause for 3 sec.

### ISSUE THREAD

**Issue by abunezek** [ethereum-mining/ethminer#1354]
this is my command line:
ethminer.exe  -P stratum1+ssl://0xfe815cd084242405c5348ca10da15e1c3607a30a.worker1@us1.ethermine.org:5555
using ethernum wallet app
GTX 1080 card
What am i doing wrong?

thanks

**Comment by AndreaLanfranchi** [comment]
Report the log.
On first connection this message is normal.

**Comment by abunezek** [comment]
but there is no mining

`  i  19:42:57|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:00|cl-1    |  No work. Pause for 3 s.
  i  19:43:00|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:03|cl-1    |  No work. Pause for 3 s.
  i  19:43:03|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:06|cl-1    |  No work. Pause for 3 s.
  i  19:43:06|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:09|cl-1    |  No work. Pause for 3 s.
  i  19:43:09|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:12|cl-1    |  No work. Pause for 3 s.
  i  19:43:12|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:15|cl-1    |  No work. Pause for 3 s.
  i  19:43:15|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:18|cl-1    |  No work. Pause for 3 s.
  i  19:43:18|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:21|cl-1    |  No work. Pause for 3 s.
  i  19:43:21|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:24|cl-1    |  No work. Pause for 3 s.
  i  19:43:24|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:27|cl-1    |  No work. Pause for 3 s.
  i  19:43:27|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:30|cl-1    |  No work. Pause for 3 s.
  i  19:43:30|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:33|cl-1    |  No work. Pause for 3 s.
  i  19:43:33|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:36|cl-1    |  No work. Pause for 3 s.
  i  19:43:36|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:39|cl-1    |  No work. Pause for 3 s.
  i  19:43:39|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:42|cl-1    |  No work. Pause for 3 s.
  i  19:43:42|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:45|cl-1    |  No work. Pause for 3 s.
  i  19:43:45|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:48|cl-1    |  No work. Pause for 3 s.
  i  19:43:48|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:51|cl-1    |  No work. Pause for 3 s.
  i  19:43:51|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:54|cl-1    |  No work. Pause for 3 s.
  i  19:43:54|cuda-0  |  No work. Pause for 3 s.
 cl  19:43:57|cl-1    |  No work. Pause for 3 s.
  i  19:43:57|cuda-0  |  No work. Pause for 3 s.
 cl  19:44:00|cl-1    |  No work. Pause for 3 s.
  i  19:44:00|cuda-0  |  No work. Pause for 3 s.
 cl  19:44:03|cl-1    |  No work. Pause for 3 s.
  i  19:44:03|cuda-0  |  No work. Pause for 3 s.
 cl  19:44:06|cl-1    |  No work. Pause for 3 s.
  i  19:44:06|cuda-0  |  No work. Pause for 3 s.
 cl  19:44:09|cl-1    |  No work. Pause for 3 s.
  i  19:44:09|cuda-0  |  No work. Pause for 3 s.
 cl  19:44:12|cl-1    |  No work. Pause for 3 s.
  i  19:44:12|cuda-0  |  No work. Pause for 3 s.
 cl  19:44:15|cl-1    |  No work. Pause for 3 s.
  i  19:44:15|cuda-0  |  No work. Pause for 3 s.
 cl  19:44:18|cl-1    |  No work. Pause for 3 s.
  i  19:44:18|cuda-0  |  No work. Pause for 3 s.
 cl  19:44:21|cl-1    |  No work. Pause for 3 s.
  i  19:44:21|cuda-0  |  No work. Pause for 3 s.
 cl  19:44:24|cl-1    |  No work. Pause for 3 s.
  i  19:44:24|cuda-0  |  No work. Pause for 3 s.
 cl  19:44:27|cl-1    |  No work. Pause for 3 s.
  i  19:44:27|cuda-0  |  No work. Pause for 3 s.
 cl  19:44:30|cl-1    |  No work. Pause for 3 s.
  i  19:44:30|cuda-0  |  No work. Pause for 3 s.
 cl  19:44:33|cl-1    |  No work. Pause for 3 s.
  i  19:44:33|cuda-0  |  No work. Pause for 3 s.`

**Comment by AndreaLanfranchi** [comment]
How many cards do you have ? 
If only one please use (note I've added a -U)

```
ethminer.exe -U -P stratum1+ssl://0xfe815cd084242405c5348ca10da15e1c3607a30a.worker1@us1.ethermine.org:5555
```

**Comment by colin-i** [comment]
I have similar "No work" but here when trying to mix amd and cuda (-X).
Switching from version 14 to 15rc2 was a fix.

**Comment by abunezek** [comment]
Thanks, th -U solved it.
Can i use cpu as well?

**Comment by AndreaLanfranchi** [comment]
@colin-i Mixed mode is broken even in 15rc2

@abunezek No CPU for ethminer
