### ISSUE TITLE
Feature Request: Shares per hour on the logging output?

### ISSUE THREAD

**Issue by slegge-hl** [ethereum-mining/ethminer#1356]
Is anyone interested in showing the instantaneous 'shares per hour' on the usual ethminer logging output line?

I noticed recent changes have conserved many characters across the ethminer log line so I decided to add 'shares per hour' on my local:

[A12] Time: 00:03 S/h: 240.0

The code I added on my local copy of 
https://github.com/ethereum-mining/ethminer/blob/master/libethcore/Farm.h
in the farmLaunchedFormatted function is very simple or brut force.  I'm usually a Java developer so my C is a bit rusty:

                unsigned accepted_shares = m_solutionStats.getAccepts();

                float time_dec = ((float) hhh.count() + ((float) mm.count() / 60));

                float shares_per_hour = 0;

                if(time_dec > 0 && accepted_shares > 0)
                        shares_per_hour = accepted_shares / time_dec;

                stream << "Time: " << std::setfill('0') << std::setw(hsize) << hhh.count() << ':' << std::setfill('0') << std::setw(2) << mm.count() << " S/h: " << std::fixed << std::setprecision(1) << shares_per_hour;

**Comment by AndreaLanfranchi** [comment]
Mmmm I do not see the point of having such a value (shares per hour) if you do not balance them with difficulties of jobs (which may vary on some pools) and the frequency new jobs come in.

**Comment by yong0706** [comment]
How about having an option to clear etherminer statistics counters after JSON RPC request(e.g. "miner_getstat1_read_and_clear" instead of "miner_getstat1")?
Users may be able to get correct shares calculated by ethminer between requests. If the request is done on every 1 hour,  submitter shall get the same result without resorting to complex code.

**Comment by AndreaLanfranchi** [comment]
It's not viable.
Statistics data are collected globally within the application. So a reset of the counter would also impact the view in console where new lines (after the reset) would begin to count from zero (like a restart) and this would break compatibility with other people who have already written their parsers.

If you plan to query the API on a hourly basis it's up to you to keep track of the previous value and compare it to the most recent.

**Comment by yong0706** [comment]
Ok, I see your point here but sorry I don't fully understand it.  Resetting counters will clear out counters so seeing counters starting from 0 looks normal to me.  If he or she does not want the behavior, "miner_getstat1_read_and_clear" method should not be used here. 

There is another reason why I said a new method like "miner_getstat1_read_and_clear" in order not to break previously working script.

**Comment by AndreaLanfranchi** [comment]
> There is another reason why I said a new method like "miner_getstat1_read_and_clear" in order not to break previously working script.

Yes because it accomplishes a very specific need (yours) while we need to keep as generic as possible. I don't mean your needs are worthless but we need a stronger user base to need this before trying to implement such a feature.  

However I reiterate it's much easier for you to keep track of older and current value than for us to implement a not so requested feature.

**Comment by yong0706** [comment]
I agree on making it general way and as you said it's also doable with a little modification of parser.
Developer resources should be used on high-priority task.
Thanks so much for your detailed explanation and sharing your thoughts.

**Comment by AndreaLanfranchi** [comment]
You're welcome.
