### ISSUE TITLE
Missing accepted shares for long time

### ISSUE THREAD

**Issue by yong0706** [ethereum-mining/ethminer#1358]
I noticed one of my Linux box didn't do any useful work for a long time.
Here is log.

  ℹ  02:22:24|cuda-1  |  Nonce 0x53dd9b1e8729f153
  ℹ  02:22:24|stratum |  New job #99543e94…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  02:22:24|stratum |  **Accepted (stale)   99ms.   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  02:22:28|stratum |  New job #10933626…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  02:22:35|stratum |  New job #c477a604…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  02:22:38|stratum |  New job #b359e417…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  02:22:40|stratum |  New job #30a8cb73…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  02:22:40|stratum |  New job #b701f59b…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  02:22:41|stratum |  New job #2e1eff88…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  02:23:17|stratum |  New job #8477bd03…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  02:23:17|cuda-1  |  Initialising miner 1
  ℹ  02:23:17|cuda-3  |  Initialising miner 3
  ℹ  02:23:17|cuda-2  |  Initialising miner 2
  ℹ  02:23:17|cuda-4  |  Initialising miner 4
  ℹ  02:23:17|cuda-5  |  Initialising miner 5
  ℹ  02:23:23|stratum |  New job #cc3448a8…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  02:23:54|stratum |  New job #06b56d72…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  02:23:57|stratum |  New job #2b83c257…   asia1.ethermine.org [13.250.13.187:5555]

[...]

  ℹ  08:24:36|stratum |  New job #f3308888…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  08:24:41|stratum |  New job #33d462aa…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  08:25:07|stratum |  New job #248fd1f7…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  08:25:10|stratum |  New job #8eccfd1b…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  08:25:24|stratum |  New job #040c846c…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  08:25:55|stratum |  New job #835d69a0…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  08:26:08|stratum |  New job #fd9b96f1…   asia1.ethermine.org [13.250.13.187:5555]
  ℹ  08:26:18|stratum |  New job #7b088005…   asia1.ethermine.org [13.250.13.187:5555]

As you can see there are just bunch of "New job #xxxx" but no "**Accepted" entries.

etherminer status via JSON RPC is useless since it continuously reports old values. Of course, the script that periodically scans miners could be improved to compare the number of previously accepted shares with current ones. Before doing that, I have to implement a script to compute differences of counters between each etherminer status request. (BTW, it would be very useful to have a way to reset etherminer status counters to 0.)

I don't know whether the root cause is in either pool side or ethminer itself.  But I think it would be very useful to have an option like "--share-check time_seconds" to force ethminer checks whether there are any accepted shares within time_seconds seconds interval.  The expected behavior is to terminate itself  (in case of "--exit" option) with exit code or shutdown miners and restart them if ethminer do not see any accepted shares within given "time_seconds" seconds. I guess the default value of "time_seconds" should be big enough not to trigger false alarms(.e.g 600 seconds or 900 seconds).

**Comment by AndreaLanfranchi** [comment]
It seems like your miner has difficulties initializing GPU's.
This behavior is not normal and clearly states there is a problem.

Would strongly suggest to initialize ethminer with only one gpu, then two, then three and so on.

**Comment by yong0706** [comment]
The miner was running without issues for a couple of days so initializing GPU one by one wouldn't be helpful here. And how do you know previous invocation was failed with initialize-related thing in parent process? If I recall correctly I saw just two error exit codes(1 and 139) so far.
I double checked log file but I couldn't find any indication of termination when it encounters unexpected errors. If ethminer encounters an unexpected error, wouldn't it better to terminate with spewing lots of errors?

**Comment by AndreaLanfranchi** [comment]
> The miner was running without issues for a couple of days so initializing GPU one by one wouldn't be helpful here.

Due to this the only possible reason for miner to re-initialize GPUs is due to the fact epoch have changed and consequentially DAG have to be regenerated. As far as I can see thid occurred at 02:23:17

> I double checked log file but I couldn't find any indication of termination when it encounters unexpected errors. If ethminer encounters an unexpected error, wouldn't it better to terminate with spewing lots of errors?

We already do that but I notice you're CUDA mining. It's not rare that in case of excessive overclocking CUDA driver simply hangs and does not report back any error so ethminer stays in an infinite loop waiting for any kind of response from CUDA driver.

**Comment by AndreaLanfranchi** [comment]
> etherminer status via JSON RPC is useless since it continuously reports old values

It does not report "old" values. It always report **current** values. If your miner does not produce new shares (maybe due to CUDA errors) then the counters simply do not increment.

**Comment by AndreaLanfranchi** [comment]
Which version of ethminer are you on ?

**Comment by yong0706** [comment]
It's 0.14.0.

**Comment by yong0706** [comment]
Hmm,  it's not easy decision to deploy latest development version to all production boxes.
I'll see if I can deploy latest version to a couple of boxes.

BTW, what would be best way to detect CUDA errors which make ethminer enter into infinite loop?
Does nvidia-smi(1) also indefinitely wait for response in that case?

**Comment by AndreaLanfranchi** [comment]
>BTW, what would be best way to detect CUDA errors which make ethminer enter into infinite loop?

It all ends up with a single word. Overclocking !
Lower your clock settings and will have your ethminer instance work for months flawlessly.

>Does nvidia-smi(1) also indefinitely wait for response in that case?
In those cases nvidia-smi does not even start as it can't hook the driver.

**Comment by AndreaLanfranchi** [comment]
> I don't think I used excessive memory overclocking(+300 on Linux so +150 in Windows which is much lower values than that of other commercial miners) but yes the overclocking effect may vary on GPUs.

It depends on GPU chipset type and kind of memories on board (Samsung, Micron, Hynix). Generally speaking if you can't have your miner to work stable for at least 72 hours you're overclocking too much.
