### ISSUE TITLE
Improve performance so it's at least the same as Claymore's miner

### ISSUE THREAD

**Issue by danielocdh** [ethereum-mining/ethminer#1359]
The performance of ethminer is around 6% lower than Claymore, Claymore uses around 8% more power which seems ok considering the fee

I'd like ethminer to have at least the same or more performance(because of the fee) than Claymore even if that means using the same power as Claymore, it could even be an option (in case there is people that likes the current performance/power usage).

I've been testing claymore and ethminer for weeks now, I'm pretty sure my numbers are accurate

**Comment by danielocdh** [comment]
@MariusVanDerWijden what circumstances? is that documented somewhere?

**Comment by AndreaLanfranchi** [comment]
With NVIDIA/CUDA mining we're pretty much the same.
Still behind with OpenCL.

**Comment by StefanOberhumer** [comment]
@danielocdh : Comparing miner software is very difficult !
1.) Don't use hashrate displayed in the miner software - **the only thing what counts is hashrate on the pool** (maybe some software cheats or does not calculate the hashrate as the other one)
2.) Compare mining softwares: same time (network latency), same pool (same ip-number), same router, same hardware, same temperature(have found my rigs get unstable/loosing hashpower at about 62°C) - That makes comparing the software really difficulty ;-)
3.) Compare it over one week or more ! (stability, reboots,...)

So for this 3 reasons it is really difficult to compare mining softwares !
I can not speak for the OpenCL part as we're using only NVIDIA / CUDA but we switched to ethminer as we decided its better.
I also enjoy the opportunity to adapt the miner - the contrbuters of the project are really nice and helpful.

**Comment by StefanOberhumer** [comment]
@danielocdh - No - I've no specific parameters - but it made for me a difference when I tried 2 rigs or 20+ (whyever ???)

**Comment by l4Dream** [comment]
I can confirm that ethminer have same/better hashrate with nvidia than claymore on both windows and linux.

**Comment by AndreaLanfranchi** [comment]
> 1.) Don't use hashrate displayed in the miner software - the only thing what counts is hashrate on the pool (maybe some software cheats or does not calculate the hashrate as the other one)

I believe this statement is **gold**. Most users keep following absolute **instant** hashrate as displayed by their miner instead of making long term comparisons on **revenues**. It's proven that lower hashrates with better stability (no crashes to recover from) increase a lot your revenues and help preserve GPUs.

**Comment by ddobreff** [comment]
Here is claymore vs ethminer simple 6 hour comparison:
http://prntscr.com/k8lwfl - single GPU test 6h SMA - claymore 11.9 - AMD RX560 4GB.
http://prntscr.com/k8lwq8 - single GPU test 6 SMA - ethminer latest git - nVidia p106-100 6GB.
My personal tests show that ethminer avg and reported is mostly on par, while claymore has small spikes equalizing it from time to time, rest is way below reported.

**Comment by SukharevPavel** [comment]
I made an improvement for OpenCL mining, which manages to get 3.5% hashrate increase on my RX480 (27.9 vs 27 on default ethminer while claymore has 28.4). But this code changes files CLMiner.cpp and kernel file a lot. Also, it breaks default hash counting. 
I am making a scientific research and want to commit these changes to ethminer to prove my results, but it is rather complicated according to aforementioned causes. Does anyone can to discuss this problem with me?

**Comment by ddobreff** [comment]
Check latest PR. Proposed faster kernel which exceeds claymore performance by a bit.

**Comment by newtoopensuse** [comment]
@ddobreff. You mean the pr made by goobur to libethash-cl?

**Comment by ddobreff** [comment]
Yes. Its already merged. Further optimisations and adjustments are expected to follow.

**Comment by newtoopensuse** [comment]
Thanks for the info ddo. But which version of ethminer will it end up in? And I see Zawawa’s kernel is going to be used. This must be super exciting.

**Comment by SukharevPavel** [comment]
I made an improvement proposition, let's discuss it:
https://github.com/ethereum-mining/ethminer/issues/1366

**Comment by smurfy** [comment]
I'm closing this, with the new binary kernels in 0.16 ethminer is as fast or even faster than claymore on OpenCL

**Comment by zawawawa** [comment]
It actually makes me feel quite good to learn that my kernel is outperforming Claymore's. Good work. guys!

**Comment by AndreaLanfranchi** [comment]
@zawawawa Thank YOU !!!
