### ISSUE TITLE
Error: No CUDA driver found

### ISSUE THREAD

**Issue by dekonunes** [ethereum-mining/ethminer#1365]
**Describe the bug**
When try list devices or start miner show error of CUDA driver
I configured my paths and drives, try version of ethminer 14,15 and 16 and same error.

when start:
`m 20:29:04 ethminer ethminer 0.16.0.dev0
 m 20:29:04 ethminer Build: linux/release
Error: No CUDA driver found`

List devices:
`Listing CUDA devices.
FORMAT: [deviceID] deviceName
 X 20:38:59 ethminer CUDA error: No CUDA driver found`

**To Reproduce**
Just click to miner or list device this error shows
`./ethminer -U -P stratum+tcp://EMAIL@etc.pool.minergate.com:45791`
`./ethminer -U --list-devices`

**Device**
1050-m (Notebook-Avell)
Ubuntu 16.04
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148
`

**Comment by AndreaLanfranchi** [comment]
If you're on Windows it's possible you have not installed the proper driver but a generic Microsoft's one.

Download NVIDIA driver 3.96 for your GPU

**Comment by AndreaLanfranchi** [comment]
Are you using a release binary or building from source ?

**Comment by AndreaLanfranchi** [comment]
Any feed-back here ?

**Comment by AndreaLanfranchi** [comment]
No feed back.
Closing.
