### ISSUE TITLE
Making an asynchronous OpenCL host-part

### ISSUE THREAD

**Issue by SukharevPavel** [ethereum-mining/ethminer#1366]
I want to discuss the problem that right now OpenCL is working according to the next algorithm:
1) Running enqueueNDRangeKernel
2) Blocking waiting for results

The problem is that if the new work is coming, we can't break OpenCL kernel execution and continue to calculate obsolete work. Also, we check new work only once, in the time after sending work to device and before reading for results. Generally, it leads to one cycle work loss every time when new work is coming. It is not a big problem, if the worksize is small enough to make fast cycle (for example, default OpenCL parameters 128 x 8192 on AMD RX 480 lead to about 40 ms cycle time, so we lost 40 ms / 14.2 s = 0.28% work loss (14.2 is a actual Ethereum mean new block time).
But this behavior forbids us to set a bigger work-sizes, cause in that case we would have bigger cycle time -> bigger percent of work loss.

My proposition is to create code, which is:
1) can detect the new work right after it is came, and can stop and relaunch kernel with new parameters immediately
2) can stop the kernel calculations right after the correct share is found (so, we could submit a share as soon as possible, otherwise the new work can make this share obsolete)

I made a code which is executed this way. With this code, I have managed to launch the work with very big worksizes (for example 128 x 3000000, in this case work cycle time is about 12 seconds) and got a significant work increase (3.5% in comparison with default miner on AMD RX 480). The main drawback is that this asynchronous host-part breaks the hash counting logic (which is simply counting the number of worksizes now), so I was forced to make hash counting on the kernel part. 
The main concept:
1) replace blocking enqueueReadBuffer with non-blocking call
2) awaiting for results read in the cycle
```
while (results[0] == c_unread) {
//check for new block
}
```
3) wrap the kernel execution with call:
```
if (g_output[0]==0) {
//ethash calculation
}
```
this helps to almost instantly finish the kernel if the solution is found. My research shown that if this condition is satisfied, the OpenCl work-item stop its work 1400 times faster than it's making computations (on AMD RX 480).
4) Inside the result awaiting cycle (item 1) if the new block is found, use the auxiliary OpenCL queue to rewrite the g_output buffer
```
if (current.header != w.header) {
...
m_invalidatingQueue.enqueueWriteBuffer(m_searchBuffer, CL_TRUE, 0, sizeof(c_invalid), &c_invalid);
...
}
```
In the end we will solve the problem of losing calculation cycle when new work is received, and will manage to run a big cycles on the kernel. We can put these changes to new binary-based ethminer and overtake the Claymore speed.

I'd like to make pull request by myself, but:
1) My code is a very dirty and only for research purposes
2) The hash counting is broken, although I made kernel-part hash counting, but I didn't make any system for real-time hash displaying. Also, when work-size is big enough (and work-cycle take longer than 1 second), ethminer hash counting is broken anyway.
3) I simply don't know GCN assembler and can't apply the kernel-part changes (which are described in the item 3) to the binary kernel by myself.

Here is my code for an old version of ethminer. https://github.com/SukharevPavel/ethminer/tree/asynchronous_kernel-testing (version with log display after 10 minutes)
Feel free to discuss.

**Comment by jean-m-cyr** [comment]
Imagine your approach running on a 16 GPU rig. It would rail the host at 100% CPU!

**Comment by SukharevPavel** [comment]
To be honest, I don't understand why this approach would overload the CPU for a rig with a large number of GPUs. Can you explain me where is a fallacy? 

> This idea, or some variant of it, keeps popping up.
I've never seen this before. i would be grateful if you had any links to discussion which will explain why this wouldn't work.

**Comment by jean-m-cyr** [comment]
@AndreaLanfranchi proposed something similar a short time ago on one of the ethminer gitter threads.

**Comment by SukharevPavel** [comment]
@jean-m-cyr yep, found it, you've talked about CUDA miner there. Too bad I know nothing about CUDA, so it'll take time for me to investigate the CUDA miner code to understand what have you talked about specifically. Right now I don't see any flaws, so I'll leave this issue open for a couple days until I've understand CUDA code. Maybe, someone else will express an opinion in that time.

**Comment by ddobreff** [comment]
Can you rebase your code over current ethash.cl?

**Comment by SukharevPavel** [comment]
@ddobreff just updated my repo and tested, works fine

**Comment by AndreaLanfranchi** [comment]
Yes I reasoned some time ago about making CUDA kernel async.
Unfortunately, after digging into the problem with the help of @jean-m-cyr, it turns out we have to deal with a trade. Either we keep polling the running kernels with non blocking queries which will increase load on CPU and possibly break correct count of processed shares, or we stick waiting on a blocking call (synchronize) 'till the kernel completes and calls back to CPU code.
I'm not an expert neither for CUDA nor for OpenCL but I think the two behave in a quite comparable way.
Honestly I read tons of documents about CUDA and parallel processing but I am still struggling to find a solution : I begin to accept the idea might be non existent.

Only quick and dirty solution I found to gain something very limited was to create non-syncing streams. But aside that my knowledge limits my investigations.

**Comment by SukharevPavel** [comment]
@AndreaLanfranchi 
>Either we keep polling the running kernels with non blocking queries which will increase load on CPU and possibly break correct count of processed shares

>and possibly break correct count of processed shares

If by 'processed shares' you mean 'total processed hash count', then yes, it will be broken.  I proposed counting hashes on the kernel itself through global OpenCL buffer and atomic_inc calls. It don't reduce performance, as my tests showed. At least, I didn't see any difference.

But, what I want to point out, is that non-blocking query allows us to use a large work size, which eliminates time overhead which happens, when miner changes kernel task. This is quite significant work loss. Also, non-blocking query helps to deal with stale shares, which is about 0.3% of the whole mining work by default and I could be worse when we increase worksize.

>which will increase load on CPU 

I'm still investigating CUDA code. But, I guess, if the problem is exists, it can be solved with some blocking C++ mechanisms, which will unblock the working CPU thread only when results are read on new working task came. Maybe later I'll be able to test my solution on a something more proper, then solo RX 480 :)

**Comment by AndreaLanfranchi** [comment]
> But, what I want to point out, is that non-blocking query allows us to use a large work size, which eliminates time overhead which happens, when miner changes kernel task.

For what is my understanding and CUDA (limited) experience larger work sizes can help reduce those micro-time waits to resume jobs after a batch has been completely processed. The drawback is that in a blocking context the kernel stays more time on a batch while new jobs may come in thus producing stale increase. Problem is (in CUDA) we do not have results to examine 'til the streams completes and eventually gets in sync with CPU memory.

Also I found that "cancelling" a running kernel (maybe we want to replace the active job) is a time consuming operation which makes overall performance worst.

**Comment by SukharevPavel** [comment]
@AndreaLanfranchi 
The drawback is that in a blocking context the kernel stays more time on a batch while new jobs may come in thus producing stale increase. 

Exactly! The main word here is "blocking context". I showed in the first post, that percent of lost work = tc/Tb, where tc - one cycle time (which is increased while work size is increasing), Tb - average new block time in the Ethereum cryptocurrency. Making a non-blocking result awaiting fully eliminates this work loss. 

>Problem is (in CUDA) we do not have results to examine 'til the streams completes and eventually gets in sync with CPU memory.

I don't understand this part. I guess, there is some difference between CUDA and OpenCL regarding to computational kernel scheduling, which I need to understand.

>Also I found that "cancelling" a running kernel (maybe we want to replace the active job) is a time consuming operation which makes overall performance worst.

I pointed it out in the first post
>My research shown that if this condition is satisfied, the OpenCl work-item stop its work 1400 times faster than it's making computations (on AMD RX 480).

So, it is fast enough, in case of OpenCL. I'm used a simple if-case to cancel OpenCL work-items. Maybe, a difference between OpenCL and CUDA behavior takes place here. 
In fact. I am using an approach like this : https://stackoverflow.com/a/19730932

On OpenCL, we have a lot of work-items, which are bundled into work-groups. If we send more work-items, than GPU can process, it schedules excessive work-items to execute right after the computational resources for them will appear. So, we can easily make a fast finish code for work-items which is not executed yet, simply by adding an if-case in the beginning of work-item computation.

**Comment by AndreaLanfranchi** [comment]
> I don't understand this part. I guess, there is some difference between CUDA and OpenCL regarding to computational kernel scheduling, which I need to understand.

IDK about OpenCL but for CUDA (unless I am missing something) I have faced two issues:

1. If you cancel a running kernel you issue something like "stop doing that work as I am not interested anymore". This, unfortunately, implies that possible found results til cancellation are lost too.
2. There is no way to aknowledge how many shares have been tested til cancellation (as kernel counters would be voided too) thus making impossible to compute hashrate.

This all said I greatly encourage the target to improve ethminer's OpenCL part as this still is our Achille's heel.

**Comment by SukharevPavel** [comment]
>If you cancel a running kernel you issue something like "stop doing that work as I am not interested anymore". This, unfortunately, implies that possible found results til cancellation are lost too.

My approach implies that the kernel would stop right after the solution was found, so this situation is almost not possible. The chance of that situation is equals to (number of work-items, which can be processed on kernel simultaneously)/(difficulty).
Maybe I am wrong in my calculations, but the standard example here: AMD GPU with 36 compute units, each compute unit has 4 vector processor, each vector processor can process 16 items at one time, and each vector processor can have a wavefront of 64 items. That mean 36 * 4 * 64 = 9216 work-items at a time. While the common difficulty is about some GHashes. In fact, the percentage is a little bigger, cause I use buffer writing to stop work, and this process is not instant, it takes about 1 ms.

But, you should understand that we want to interrupt kernel only if
1) Solution found, we want to submit it
2) New work came

In the first case we can easily process such situation. We simply stop the kernel and read the result from OpenCL buffer, which is not invalidated after such kernel stop and contains a valid result, so we can add the second solution to the result buffer too.
And in the second case we simply don't care about found result, as the new work came, and this result is already stale.

>There is no way to aknowledge how many shares have been tested til cancellation (as kernel counters would be voided too) thus making impossible to compute hashrate.

As I told earlier, I am counting hashes on a kernel side through atomic_inc and write the results to OpenCL buffer. I always can read this buffer from host-part, and it will not be invalidated unless I send a command to do that. This approach don't show any performance loss and is quite precise (I tested it with the common hash counting, and it show difference < 0.01% which could be easily explained).

**Comment by AndreaLanfranchi** [comment]
I totally understand. Only few notes from CUDA perspective

> Solution found, we want to submit it

Stopping a kernel on solution found may prevent you from finding other valid nonces nearby. It's a tiny possibility but it's there.

>As I told earlier, I am counting hashes on a kernel side through atomic_inc and write the results to OpenCL buffer

In CUDA this is slightly different. To have your results (valid nonces and or processed loops count) you have to sync the stream which holds the running kernel. If you cancel the running kernel you cancel the stream thus voiding any result.

**Comment by SukharevPavel** [comment]
>Stopping a kernel on solution found may prevent you from finding other valid nonces nearby. It's a tiny possibility but it's there.

>The chance of that situation is equals to (number of work-items, which can be processed on kernel simultaneously)/(difficulty).

I told earlier on the real example. 9216 work-items which are executed simultaneously on one device. If the solution is found we want to stop exactly this device. For example, the difficulty is 1 GHash. So, the probability is : 9216/10^9=10^-6 . Ok, not really, it is slightly bigger:
>cause I use buffer writing to stop work, and this process is not instant, it takes about 1 ms.

So, in the end, the probability is about 10^-5 = 0.001% in the worst case
And, moreover, as I mentioned, even in this case 
>we can add the second solution to the result buffer too.

So this problem is not exists in the OpenCL. We won't read the result buffer before the kernel stops, so we always get all the results we've found.

>In CUDA this is slightly different. To have your results (valid nonces and or processed loops count) you have to sync the stream which holds the running kernel. 

In the OpenCL, we can increment the OpenCL buffer value and it will store its result despite the kernel workflow.

**Comment by SukharevPavel** [comment]
Ok, I understood. According to `top`, the CPU usage for default miner is about 0.3% while for my solution is 100%. Will try to fix that.

**Comment by SukharevPavel** [comment]
@jean-m-cyr @AndreaLanfranchi Ok, I solved the CPU problem.
The idea that we will leave blocking enqueueReadBuffer, but we also leave the kernel logic, which allows us to end kernel fast after the valid share is found. After that we remove checking for new work logic from workLoop cycle and move it to the method kick_miner(), which is already described in the code. This method is called each time the work is received, so we can launch invalidating logic asynchronously from mining host thread.
I've just made an experiment, all works fine. The CPU load by ethminer process is about 1 percent. Check the code https://github.com/SukharevPavel/ethminer/tree/asynchronous_kernel-testing-230718-lowcpu
Here's the screen: https://ibb.co/kVXmWy 
I made a logging for the exact mining time after each blocking enqueueReadBuffer completion. As you can see, normally cycle takes about 7 seconds, but it breaks when new work is coming or share is found. Also, that speed is wrong, ethminer logging is broken when work cycle time is larger than 1 second. 
CPU loading: https://ibb.co/kNGPJd

**Comment by jean-m-cyr** [comment]
I warned you about the 100% CPU thing initially. Push a PR with a clean implementation of your idea and we'll certainly look at it.
