### ISSUE TITLE
Cuda error in func 'set_header' at line 161 : unknown error.

### ISSUE THREAD

**Issue by Tomcc** [ethereum-mining/ethminer#137]
I started playing with mining ethereum on my home desktop, I've been going at it for 2 days now.
Today I tried `--cuda-parallel-hash 8` and twice, after 4-5 hours, ethminer died with the error in the title, locking up the entire PC (I had to hard reboot).

I was using Ethminer 0.11, latest release.
I don't really care whether you fix the issue or not as `--cuda-parallel-hash 8` is also slower on my GPU (~28 vs 30 MHs average), but I thought you might want to know :)

This start+end of the log:
```
Using grid size 8192, block size 128

  i  09:27:33|main  Connecting to stratum server us2.ethermine.org:4444
  i  09:27:33|stratum  Connected to stratum server us2.ethermine.org : 4444
  i  09:27:33|stratum  Starting farm
  i  09:27:33|stratum  Subscribed to stratum server
  i  09:27:33|stratum  Authorized worker 0x00309909D9C85ff9cC6f117Ba855311C14960771.PC1
  i  09:27:33|stratum  Received new job #384c4b4b
  i  09:27:33|cudaminer0  set work; seed: #39c5f107, target: #0000000112e0
  i  09:27:33|cudaminer0  Initialising miner...
  i  09:27:34|stratum  Received new job #1caf566a
Using device: GeForce GTX 1070 (Compute 6.1)
Generating DAG for GPU #0
CUDA#0: 0%
CUDA#0: 3%
CUDA#0: 6%

... hours of this ...

  m  12:54:56|main  Mining on PoWhash #1fd15023 : 32.51MH/s [A103+0:R0+0:F0]
  m  12:54:58|main  Mining on PoWhash #1fd15023 : 32.51MH/s [A103+0:R0+0:F0]
  m  12:55:00|main  Mining on PoWhash #1fd15023 : 32.51MH/s [A103+0:R0+0:F0]
  i  12:55:01|stratum  Received new job #43b539ae
  i  12:55:03|cudaminer0  set work; seed: #39c5f107, target: #0000000112e0
  m  12:55:03|main  Mining on PoWhash #43b539ae : 0.00MH/s [A103+0:R0+0:F0]
  m  12:55:05|main  Mining on PoWhash #43b539ae : 0.00MH/s [A103+0:R0+0:F0]
  m  12:55:07|main  Mining on PoWhash #43b539ae : 0.00MH/s [A103+0:R0+0:F0]
  m  12:55:09|main  Mining on PoWhash #43b539ae : 0.00MH/s [A103+0:R0+0:F0]
  m  12:55:11|main  Mining on PoWhash #43b539ae : 0.00MH/s [A103+0:R0+0:F0]
  m  12:55:13|main  Mining on PoWhash #43b539ae : 0.00MH/s [A103+0:R0+0:F0]
  m  12:55:15|main  Mining on PoWhash #43b539ae : 0.00MH/s [A103+0:R0+0:F0]
  m  12:55:17|main  Mining on PoWhash #43b539ae : 0.00MH/s [A103+0:R0+0:F0]
  m  12:55:19|main  Mining on PoWhash #43b539ae : 0.00MH/s [A103+0:R0+0:F0]
  m  12:55:21|main  Mining on PoWhash #43b539ae : 0.00MH/s [A103+0:R0+0:F0]
  i  12:55:21|stratum  Received new job #3fe3c8c8
  i  12:55:46|cudaminer0  set work; seed: #39c5f107, target: #0000000112e0
  m  12:55:46|main  Mining on PoWhash #3fe3c8c8 : 0.00MH/s [A103+0:R0+0:F0]
  i  12:55:46|stratum  Received new job #c27c2f46
Cuda error in func 'set_header' at line 161 : unknown error.```

**Comment by derdjme** [comment]
Same issue here with my two 1060s

**Comment by mauadib** [comment]
Have you tried the linux driver 384 beta from nvidia this appears to fix alot of problems for some people.

**Comment by derdjme** [comment]
No, I didn't.  Maybe that's an option.

**Comment by Tomcc** [comment]
Updating this because after ~2 weeks of mining, I can confirm this happens with any `--cuda-parallel-hash` parameter.  
Also, today I got a slightly more informative error:

```  m  23:04:32|main  Mining on PoWhash #17cf0774 : 32.49MH/s [A53+0:R0+0:F0]
  m  23:04:34|main  Mining on PoWhash #17cf0774 : 32.51MH/s [A53+0:R0+0:F0]
  m  23:04:36|main  Mining on PoWhash #17cf0774 : 32.51MH/s [A53+0:R0+0:F0]
  m  23:04:38|main  Mining on PoWhash #17cf0774 : 33.55MH/s [A53+0:R0+0:F0]
  m  23:04:40|main  Mining on PoWhash #17cf0774 : 32.51MH/s [A53+0:R0+0:F0]
  m  23:04:42|main  Mining on PoWhash #17cf0774 : 32.49MH/s [A53+0:R0+0:F0]
CUDA error in func 'ethash_cuda_miner::search' at line 365 : an illegal instruction was encountered.
  X  23:04:43|cudaminer0  Error CUDA mining: an illegal instruction was encountered
  i  23:04:43|stratum  Received new job #f2d7867d

hang here```

It doesn't look like it is caused by overclocking, although with overclocking it's a bit more common.
I'm using ethminer 0.11 and the latest Nvidia driver.

**Comment by mauadib** [comment]
I've been running this code (v0.11) for weeks and sometimes see this error but more often that not I get random resets on my rig. Running latest windows driver 384 and win10. This is not run overclocked but on stock frequencies.

**Comment by derubm** [comment]
@Tomcc the error you have encontered is allready knownand marked as bug here : #94

**Comment by Tomcc** [comment]
@derubm thanks, I made my own watchdog :P

The watchdog isn't helping either though. There's something going on that is making these errors increase...
Tonight my rig couldn't get almost any work done at all!
There's been 63 errors in 9 hours!

Log is attached.
[ethminer_log.txt](https://github.com/ethereum-mining/ethminer/files/1170519/ethminer_log.txt)

**Comment by mdealer** [comment]
Same thing here...

` cl  14:02:32|cl-1      New seed #9e972470ΓÇª
  m  14:02:32|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  14:02:33|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  14:02:33|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  14:02:33|cl-1      Platform: AMD Accelerated Parallel Processing
 cl  14:02:33|cl-1      Device:   Baffin  / OpenCL 2.0 AMD-APP (2348.3)
Cuda error in func 'set_header' at line 161 : CUDA driver version is insufficient for CUDA runtime version.`

**Comment by derubm** [comment]
@tomcc are you running on P2 or P0 ? It might help to set your card to P0 state, i had a lot of crashes back when i used P2 state. (note: P0 state needs you to set memory clock 200 mhz lower then P2 state, as P0 state adds those 200 mhz allready). when i run ethminer with P0 sate i get really not a single crash.

(as mentioned in many other posts allready, nvidia drivers tend to make the memory speed a bit jumpy on P2 state ( sometimes your card will switch to P0 state and add 200 extra mhz to memory speeds - which often if not every time, leads to a crash) setting your card to P0 state from start one will prevent this behavior. (works on windows, don´t know about linux, i heared it´s not possible there to switch power state)

**Comment by MariusVanDerWijden** [comment]
Is this still relevant?
