### ISSUE TITLE
ethminer 0.16.0.dev1 symbol " a " and low speed

### ISSUE THREAD

**Issue by BoriZka67** [ethereum-mining/ethminer#1370]
In ethminer 0.16.0.dev1 in the report download Dag file time writes 5a674 ms. As well as the speed of production (compared to ethminer 0.16.0.dev0) below.
![2018-07-23_13-49-02](https://user-images.githubusercontent.com/37310919/43072805-057ada7a-8e80-11e8-80e4-a3e7e71d32b1.jpg)
 
win7_64, 5 rx580 8Gb, system language Russian.
ethminer.exe -R --HWMON 0 --farm-recheck 2000  --cl-local-work 256 --cl-global-work 65536 --cl-parallel-hash 2 --cl-kernel 1 --opencl-platform 1 -G -P stratum1+tcp://0xХХХХХХХХХХХХХХХХХХХХХХХХХ.Ferma1@eth-eu.dwarfpool.com:8008

**Comment by jean-m-cyr** [comment]
How numbers are displayed is based on system language settings... No idea why the 'a' is being used as the thousands separator.

**Comment by AndreaLanfranchi** [comment]
@jean-m-cyr 

IDK what happened ... but I am pretty sure I have not changed my locale settings.
Nevertheless I suffer from the same behavior since ethminer 0.16.0.dev1

@ ethminer 0.16.0.dev0+commit.531e2d2c it was (actually is as I am still using it) numbers are properly displayed with a comma as thousands separator.

**Comment by jean-m-cyr** [comment]
Hmm... I don't see this here with head code. Looks like memory is being clobbered somewhere!
Can you try running dev1 with the --cl-only option. I want to see if it is related to binary kernel loading?

**Comment by AndreaLanfranchi** [comment]
I'm on CUDA. Does it apply to CUDA too ?

**Comment by jean-m-cyr** [comment]
Right! Forgot about that...

**Comment by jean-m-cyr** [comment]
I don't know... nothing much has changed wrt. cuda since ethminer 0.16.0.dev0+commit.531e2d2c!
I can't reproduce in either cuda or cl.

**Comment by jean-m-cyr** [comment]
@ddobreff Have you seen this issue?

**Comment by BoriZka67** [comment]
"Can you try running dev1 with the --cl-only option."
Should I just insert this command at the end of the line?

**Comment by AndreaLanfranchi** [comment]
Problem has misteriously disappeared.
Closing for now.
