### ISSUE TITLE
rev 16.0 - dev1 : worker name is ignored

### ISSUE THREAD

**Issue by satori-q3a** [ethereum-mining/ethminer#1373]
windows ethminer rev 16.0 - dev1, worker name is being ignored and does not show up in the log when it starts.

shares are accepted on nanopool under the correct account id (eth address) but nanopool shows it as "incorrect worker name".

fails in both -P formats of "-P ethaddress.worker@pool-address" and "-P ethaddress@pool-address/worker"

update: did some retesting ...

format of "-P ethaddress.worker@pool-address" fails but
format of "-P ethaddress@pool-address/worker" seems to work...

however, the log does not show the worker name being gen'ed in both cases.

updated update:

I'm thinking that the format of
"-P ethaddress.worker@pool-address/email-address" is what fails, while the format of
"-P ethaddress@pool-address/worker/email-address" now works since the only way to immediately tell
is that nanopool's 'rating' for each worker is now being reset by the change in email address.

**Comment by AndreaLanfranchi** [comment]
> windows ethminer rev 16.0 - dev1, worker name is being ignored and does not show up in the log when it starts.

No changes have been introduced in 0.16 about worker names handling.

>format of "-P ethaddress.worker@pool-address" fails but
format of "-P ethaddress@pool-address/worker" seems to work...

The format is -P **stratum+tcp://**ethaddress@pool-address/worker ... are you missing something ?

**Comment by satori-q3a** [comment]
windows ethminer 15.0 (final) works, but substituting the 16.0 dev1 exe when it runs results in "invalid worker name" on nanopool.  And since the log no longer shows the worker name being used, it's hard to say what's going on.

Changing the worker name from an embedded ".worker" in the ethaddress of the pool, to a trailing "/worker" followed by the "/email-name" does seem to appease nanopool.

**Comment by lesjokolat** [comment]
can this be closed with new fixes made?

issue 1470

**Comment by AndreaLanfranchi** [comment]
It's not a matter of documentation.
It's a matter of logic. There is NO standard rule for pools: each implements its own separator, sometimes it's a dot, sometimes its a slash. In addition you have to read pool's documentation.

**Comment by DDDanny** [comment]
Sorry to stress this topic again. I agree in read pool doc and help. Therefore I suggest to change the example in the --help to work with nanopool correctly:

https://github.com/ethereum-mining/ethminer/blob/9512a52615ff580609da4764eafdf3e0ef8781be/ethminer/main.cpp#L491-L492

=>

`"stratum://0x012345678901234567890234567890123@nanopool.org:9999/miner1/"`
`"john.doe@gmail.com"`
