### ISSUE TITLE
OpenCL issue CL_INVALID_COMMAND_QUEUE (-36)

### ISSUE THREAD

**Issue by levongh** [ethereum-mining/ethminer#1375]
OpenCL issue 

run the command 
./ethminer.exe -M 1 -G

I am getting the following issue 
Warming up...
cl 13:09:04 cl-0     Platform: NVIDIA CUDA
cl 13:09:04 cl-0     Device:   GeForce GTX 1050 Ti / OpenCL 1.2 CUDA
cl 13:09:04 cl-0     OpenCL kernel
cl 13:09:04 cl-0     Loading binary kernel E:\ethminer\build\ethminer\Release/kernels/ethash_geforce gtx 1050 ti_lws192.bin
 X 13:09:04 cl-0     Failed to load binary kernel: E:\ethminer\build\ethminer\Release/kernels/ethash_geforce gtx 1050 ti_lws192.bin
 X 13:09:04 cl-0     Falling back to OpenCL kernel...
cl 13:09:04 cl-0     Creating light cache buffer, size: 16,776,896
cl 13:09:04 cl-0     Creating DAG buffer, size: 1,073,739,904
cl 13:09:04 cl-0     Loading kernels
cl 13:09:04 cl-0     Writing light cache buffer
cl 13:09:04 cl-0     Creating buffer for header.
cl 13:09:04 cl-0     Creating mining buffer
 X 13:09:15 cl-0     OpenCL init failed: clFinish: CL_INVALID_COMMAND_QUEUE (-36)
 X 13:09:15 cl-0     OpenCL Error: clEnqueueReadBuffer: CL_OUT_OF_RESOURCES (-5)

It should show benchmark results

- Operating System: [ Windows 10]
- Hardware [ GTX 1050 Ti]
- Ethminer Version [ 0.16.0.dev0]

**Comment by AndreaLanfranchi** [comment]
>cl 13:09:04 cl-0 Loading binary kernel E:\ethminer\build\ethminer\Release/kernels/ethash_geforce gtx 1050 ti_lws192.bin
X 13:09:04 cl-0 Failed to load binary kernel: E:\ethminer\build\ethminer\Release/kernels/ethash_geforce gtx 1050 ti_lws192.bin

I honestly do not recognize the kernels you're going to load.

Anyhow ... as you're on NVIDIA cards you should use -U instead of -G to enforce CUDA mining.

**Comment by levongh** [comment]
Thank you for your quick response. 
But  as I can see the issue is 

for (start = 0; start <= workItems - m_globalWorkSize; start += m_globalWorkSize)
{
            m_dagKernel.setArg(0, start);
            m_queue.enqueueNDRangeKernel(m_dagKernel, cl::NullRange, m_globalWorkSize, m_workgroupSize);
            **error is there**
            m_queue.finish();
}

For Nvidia it is loading default "ethash.cl" kenrel

**Comment by levongh** [comment]
Now I am running the miner via flag "-U" 
But I think opencl miner should work even with CUDA GPU's 

./ethminer/Release/ethminer.exe -M 1 -G --cl-nobinary
 m 15:08:07 main     ethminer 0.16.0.dev0+commit.2ce3f1a1.dirty
 m 15:08:07 main     Build: windows/release
 i 15:08:07 main    

 Found suitable OpenCL device [GeForce GTX 1050 Ti] with 4,294,967,296 bytes of GPU memory
Benchmarking on platform: CL
Preparing DAG for block #1
cl 15:08:07 cl-0     No work. Pause for 3Warming up...
 s.
cl 15:08:10 cl-0     Platform: NVIDIA CUDA
cl 15:08:10 cl-0     Device:   GeForce GTX 1050 Ti / OpenCL 1.2 CUDA
cl 15:08:10 cl-0     OpenCL kernel
cl 15:08:10 cl-0     Creating light cache buffer, size: 16,776,896
cl 15:08:10 cl-0     Creating DAG buffer, size: 1,073,739,904
cl 15:08:10 cl-0     Loading kernels
cl 15:08:10 cl-0     Writing light cache buffer
cl 15:08:10 cl-0     Creating buffer for header.
cl 15:08:10 cl-0     Creating mining buffer
 X 15:08:12 cl-0     OpenCL init failed: clFinish: CL_INVALID_COMMAND_QUEUE (-36)
 X 15:08:12 cl-0     OpenCL Error: clEnqueueWriteBuffer: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)

**Comment by levongh** [comment]
To mine etherium on Ubuntu 18.04. I have noticed on my hardware opencl miner is much faster than native CUDA miner

**Comment by levongh** [comment]
Thanks @AndreaLanfranchi

**Comment by AndreaLanfranchi** [comment]
> To mine etherium on Ubuntu 18.04. I have noticed on my hardware opencl miner is much faster than native CUDA miner

Just for the sake of science: could you provide hashrate recorded for CUDA and for OpenCL in your environment ?
And which version of ethminer are you using ?

**Comment by levongh** [comment]
Opencl miner
Nvidia GTX 1050 Ti (4 GB vram) —- 11.5 Mh/s
Nvidia GTX 1070 Ti (6 GB vram) — 25 mh/s

CUDA miner 
Nvidia GTX 1050 Ti (4 GB vram) —- 1.1 Mh/s
Nvidia GTX 1070 Ti (6 GB vram) — 2.1  mh/s

Even dag generation is slow

This issue arose after upgradeing from Ubuntu 17.10 to ubuntu 18.04

**Comment by AndreaLanfranchi** [comment]
Ouch ... there must be something wrong with CUDA drivers.
That difference is not reasonable.

I can confirm those values for OpenCL
But on CUDA and Ubuntu 16.04 I get

CUDA miner
Nvidia GTX 1050 Ti (4 GB vram) —- 14.50 Mh/s
Nvidia GTX 1070 Ti (6 GB vram) —- 32.70 mh/s

I definitely suggest to investigate on your CUDA problems as for NV CUDA is way more efficient.
