### ISSUE TITLE
Higher Power draw 0.16dev1

### ISSUE THREAD

**Issue by shadow-wizzard** [ethereum-mining/ethminer#1376]
Kill a watt with version 0.16dev1(330w) show power draw 30-40 watt more than the previous version 0.15(295w).here's my system hardware.
Operating system : win10 64bit
Cpu intel celeron
Ram : 4gb
Ssd 60gb
Gpu : 2x rx 470 4gb.

**Comment by shadow-wizzard** [comment]
Ops.. sorry.. here's my system hardware
Operating system : win10 64bit
Ram : 4gb
Ssd 60gb
Gpu : 2x rx 470 4gb.

**Comment by ddobreff** [comment]
Can u provide us with command line and miner output?

**Comment by shadow-wizzard** [comment]
sure... 
ethminer.exe --HWMON 1 --report-hashrate -G -P stratum1+ssl://0x7912166cd4e179979d9ac4a7d6f2190edda61271.test001@asia1.ethermine.org:5555 --cl-local-work 256 --cl-kernel 1 --cl-global-work 65536 --farm-recheck 2000 --cl-parallel-hash 2

![ss](https://user-images.githubusercontent.com/21278737/43148151-e6fa9e18-8f8e-11e8-812c-4ffe1728b53c.jpg)

**Comment by jean-m-cyr** [comment]
Evidently the new AMD kernels consume more power.

More power = more hashes... Profitability will depend on power cost.

**Comment by shadow-wizzard** [comment]
here is the output..

![ss2](https://user-images.githubusercontent.com/21278737/43194017-9fac304c-902b-11e8-9d3e-0d3c608ec586.jpg)

**Comment by adserba** [comment]
6x rx580 with version 0.14 at the wall 780-800w and with version 0.16dev1 845-850w, but nice performance
Win 10 x64
Intel g4400
4gb ddr4
120 ssd
Msi 270 a pro

**Comment by ddobreff** [comment]
Options: --cl-global-work, --cl-kernel and --cl-parallel-hash are deprecated, you can simply omit those and use only --cl-local-work(for me 192 is power/hash acceptable).

**Comment by jean-m-cyr** [comment]
--cl-local-work defaults to 192

**Comment by adserba** [comment]
The config above, 6 x rx580
cl-local-work 256  result 183-185 mh/s 845w
cl-local-work 192  result 183-185 mh/s 835-840w
No flags launch.   Results are the same

**Comment by 53nsk** [comment]
0.16.0.dev3 draws 1385w vs 1235w with phoenix, still too much((

**Comment by th0ma7** [comment]
Out of curiosity, any hashrate increase associated with total Watt increase?

**Comment by chfast** [comment]
Please test with 0.16.0
