### ISSUE TITLE
Cannot start mining, New miner using AMD

### ISSUE THREAD

**Issue by coolbelieveit** [ethereum-mining/ethminer#1387]
**Start.bat file listed below**

if not defined in_subprocess (cmd /k set in_subprocess=y ^& %0 %*) & exit )

setx GPU_FORCE_64BIT_PTR 0

setx GPU_MAX_HEAP_SIZE 100

setx GPU_USE_SYNC_OBJECTS 1

setx GPU_MAX_ALLOC_PERCENT 100

setx GPU_SINGLE_ALLOC_PERCENT 100

ethminer.exe --farm-recheck 200 -G -1 eu1.ethermine.org:4444 UNSPECIFIEDETHADDRESS

**Error is Unknown URI Scheme unspecified, please help**

**Also tried using ethminer.exe --farm-recheck 200 -G -S <Mining_Pool_Address> -O <Your_Ethereum_Wallet_Address>.<Friendly_Name_For_Computer>**

**Comment by StefanOberhumer** [comment]
Would helpful to know your ethminer version.

But:
- Please check `ethminer.exe --help` (Pool syntax has been changed)
- Also check https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md

**Comment by coolbelieveit** [comment]
Hi, version being used is


1.79 MB ethminer-0.16.0.dev1-Windows.zip

**Comment by coolbelieveit** [comment]
Additionally, I just tried

-P stratum1+tcp://ETH_WALLET.WORKERNAME@us1.ethermine.org:4444

and the error that pops up is "-P is not recognized as an internal or external command, operable program or bath file"

**Comment by AndreaLanfranchi** [comment]
> -P stratum1+tcp://ETH_WALLET.WORKERNAME@us1.ethermine.org:4444

That is a command line **argument**. It has no meaning if you not preceed that with the executable.
It HAS to be AT LEAST

```
ethminer.exe -P stratum1+tcp://ETH_WALLET.WORKERNAME@us1.ethermine.org:4444
```

In addition. Are you using NVIDIA cards or AMD ?
If NVIDIA 

```
ethminer.exe -U -P stratum1+tcp://ETH_WALLET.WORKERNAME@us1.ethermine.org:4444
```
If AMD
```
ethminer.exe -G -P stratum1+tcp://ETH_WALLET.WORKERNAME@us1.ethermine.org:4444
```

_A little knowledge of computing basics is highly requested._
