### ISSUE TITLE
run_ethash_search signature uses different names in header (looks like opencl)

### ISSUE THREAD

**Issue by YanBellavance** [ethereum-mining/ethminer#139]
in: ethminer-master\libethash-cuda\ethash_cuda_miner_kernel.h

The declaration of run_ethash_search uses the wrong names and doesnt match the names used in the definition.

So replace this:
```c++
void run_ethash_search(
	uint32_t search_batch_size,
	uint32_t workgroup_size,
	uint32_t sharedbytes,
	cudaStream_t stream,
	volatile uint32_t* g_output,
	uint64_t start_nonce,
	uint32_t parallelHash
	);
```
with this:

```c++
void run_ethash_search(
	uint32_t blocks,
	uint32_t threads,
	uint32_t sharedbytes,
	cudaStream_t stream,
	volatile uint32_t* g_output,
	uint64_t start_nonce,
	uint32_t parallelHash
	); 
```

**Comment by jimmykl** [comment]
Could this be related to the errors people are experiencing with ethash_cuda_miner::search crashes? https://github.com/ethereum-mining/ethminer/issues/94

**Comment by DeadManWalkingTO** [comment]
Any news here?
