### ISSUE TITLE
Ethminer 0.15.0 reported hashrate fluctuate too much

### ISSUE THREAD

**Issue by lordrive** [ethereum-mining/ethminer#1391]
**Describe the bug**
since i changed from ethminer 0.13 to 0.15.0 the reported hashrate fluctuate drastically on my gtx 1060 rig, while the other rig with rx 570s are unaffected.

**Expected behavior**
The reported hashrate should follow the old (0.13) behavior. (and yes, i also tried the 0.16 dev version too, same thing happens)

**Screenshots**
![kep](https://user-images.githubusercontent.com/19550433/43261633-b45c88d6-90dd-11e8-8a26-d479733b5a48.png)

**Desktop (please complete the following information):**
- Operating System: Windows 7
- Hardware GTX 1060 3GB
- Ethminer Version 0.15.0

**Comment by AndreaLanfranchi** [comment]
This is a screenshot from one of mine rigs 6x GTX1060 6Gb (24 hours) running on 0.16.dev
Green smooth line.

![ss1](https://user-images.githubusercontent.com/15280851/43320679-8bde343c-91a9-11e8-80bc-25ba247e298c.jpg)

**Comment by lordrive** [comment]
@AndreaLanfranchi the slight increase is because one of the gpus died and after i restarted it the normal hashrate came back. It has nothing to do with the reported hashrate's change on the picture.

The problem is that the reported hashrate should look just like yours on the screenshot, but for some reason it not.

**Comment by lordrive** [comment]
Anyway i decreased the overclock a bit maybe that will help with it.

**Comment by AndreaLanfranchi** [comment]
Ok. Seems a solution is found.
