### ISSUE TITLE
0.16dev1 crash when disconnected from the pool

### ISSUE THREAD

**Issue by shadow-wizzard** [ethereum-mining/ethminer#1393]
![ss3](https://user-images.githubusercontent.com/21278737/43340588-0adf072c-9207-11e8-8a31-fa8d0599917a.jpg)

**Comment by smurfy** [comment]
Which version are you using?

**Comment by shadow-wizzard** [comment]
Im using 0.16dev1

**Comment by AndreaLanfranchi** [comment]
Do you have the opportunity to build from source ?
Please try the latest source.

**Comment by shadow-wizzard** [comment]
@AndreaLanfranchi thank you.i will try to build it from source.It's been a year since last time my keyboard use the miracle word 'sudo make'.wish me luck..
