### ISSUE TITLE
Hashrate lower than claymore on SMOS

### ISSUE THREAD

**Issue by ArtiomkaPL** [ethereum-mining/ethminer#1394]
I know there is a way to increase it on windows but how I do that on Simple Mining Os?

**Comment by smurfy** [comment]
0.16+ with the binary kernels (AMD) is on-par, sometimes even faster than claymore. 
This works on windows AND linux.  Without additional tweaking params.
CUDA is the same. 
IF 0.16+ does not work on  SMOS, please contact their support. It works great on linux so it must be something wrong with SMOS i guess.

Also please provide more information with your issues. Like what GPUS, OS version and such. Basically what the default "bug" issue template asks of you.

**Comment by ArtiomkaPL** [comment]
On 0.15 is available :(  
all rx570 4gb with modded bios

**Comment by smurfy** [comment]
Well, update ethminer and enjoy!
