### ISSUE TITLE
can't benchmark in linux

### ISSUE THREAD

**Issue by patofet** [ethereum-mining/ethminer#1395]
**Describe the bug**
When I try to execute a benchmark in linux I can't, appears "--benchmark: 1 required UINT missing" in console.

**To Reproduce**
1. Download ethminer 0.16.0.dev1 or 0.15.0
2. Extract it
3. Open console and change curret directori to ethminer executable
4. Execute the benchmark "./ethminer -G -M" or "./ethminer -M"
5. In console appears "--benchmark: 1 required UINT missing"

**Expected behavior**
The benchmarkt

**Desktop (please complete the following information):**
- Operating System: Kubuntu 16.04.5 LTS
- Hardware: 2xGTX 980
- Ethminer Version: 0.16.0.dev1 or 0.15.0

**Comment by AndreaLanfranchi** [comment]
Why you do not read the help ?
ethminer --help

```
-M,--benchmark UINT=0       Benchmark mining and exit; Specify block number to benchmark against specific DAG
```

You have to specify a block number to banchmark against.

Thus

```
./ethminer -G -M 6056695
```
