### ISSUE TITLE
Build error: ‘ethash::managed’ has not been declared

### ISSUE THREAD

**Issue by Zenitur** [ethereum-mining/ethminer#1396]
**Describe the bug**
I have been tried to compile ethminer on CentOS 6 with the compiler GCC 5. There is the error:
```

Scanning dependencies of target ethash-cl
[ 42%] Building CXX object libethash-cl/CMakeFiles/ethash-cl.dir/CLMiner.cpp.o
/home/newel/ethminer/libethash-cl/CLMiner.cpp: In member function ‘bool dev::eth::CLMiner::init(int)’:
/home/newel/ethminer/libethash-cl/CLMiner.cpp:624:39: error: ‘ethash::managed’ has not been declared
         const auto& context = ethash::managed::get_epoch_context(epoch);
                                       ^
gmake[2]: *** [libethash-cl/CMakeFiles/ethash-cl.dir/CLMiner.cpp.o] Error 1
gmake[1]: *** [libethash-cl/CMakeFiles/ethash-cl.dir/all] Error 2
```

**Desktop (please complete the following information):**
- Operating System: CentOS 6 Linux
- Hardware: Intel x86_64 PC
- Ethminer Version: 0.15 branch

**Comment by lookfirst** [comment]
I'm seeing similar:

```
ethminer/libethash-cl/CLMiner.cpp:644:39: error: no member named 'managed' in namespace 'ethash'
        const auto& context = ethash::managed::get_epoch_context(epoch);
                              ~~~~~~~~^
1 error generated.
make[2]: *** [libethash-cl/CMakeFiles/ethash-cl.dir/CLMiner.cpp.o] Error 1
make[1]: *** [libethash-cl/CMakeFiles/ethash-cl.dir/all] Error 2
```

**Comment by lookfirst** [comment]
Here is the commit that broke things: https://github.com/chfast/ethash/commit/bdcb5ea65ee8335c78dc82d64d1696fff5b62a48

**Comment by lookfirst** [comment]
Also: https://github.com/chfast/ethash/commit/daff906ad29b589587c72f89e380469b22588e16

**Comment by lookfirst** [comment]
PR #1401 fixes this issue

**Comment by Zenitur** [comment]
Confirm. Now it builts. I have got the perfect binary. 'file' says that the minimal Linux version to run it is 2.6.4. Minimal Glibc version is 2.9 (I maked some changes in devcore to make it lower). It's very very nice
