### ISSUE TITLE
MinerAux.h uses stol() to set unsigned integers instead of stoul()

### ISSUE THREAD

**Issue by YanBellavance** [ethereum-mining/ethminer#140]
not a deal breaker but we should be using stoul instead of stol since the return value of stol is assigned to an unsigned always:

m_numStreams = stol(argv[++i]);

was it done on purpose?

**Comment by EoD** [comment]
@YanBellavance unlikely, it came with commit 56bb6941ace2fd01d3a70a56b4773537337ba3e7 .

Would you create a pull request about your suggested change?

**Comment by chfast** [comment]
Patches welcome.

**Comment by DeadManWalkingTO** [comment]
Any news here?

**Comment by YanBellavance** [comment]
Sorry i been so busy....you would loke me to update all the fixes I made in
a pull request? Im just so busy right now....gotta make ends meet for my
project

Le mar. 27 févr. 2018 5:48 PM, DeadManWalking <notifications@github.com> a
écrit :
