### ISSUE TITLE
auto fan speed for linux hiveos

### ISSUE THREAD

**Issue by erkange** [ethereum-mining/ethminer#1403]
Do we have an option to set target GPU temperature?
Fan should arrange speed accordingly.

for claymore i was using -tt 65

**Comment by smurfy** [comment]
In my opinion you should ask the authors of hiveos to add automatical fan management.

Ethminer has -tstart -tstop which allows you to automatically stop mining at certain temps but the management of speed is based on temp or whatever is in my opinion out of scope of ethminer.
