### ISSUE TITLE
Error ethminer 0.16.0.dev2

### ISSUE THREAD

**Issue by mayner88** [ethereum-mining/ethminer#1408]
ethminer 0.16.0.dev2

cl 10:47:34 cl-3     Loading binary kernel E:\Ethminer/kernels/ethash_hawaii_lws128.bin
 X 10:47:34 cl-3     Failed to load binary kernel: E:\Ethminer/kernels/ethash_hawaii_lws128.bin

**Comment by BoriZka67** [comment]
Are you sure at this address E:\Ethminer/ is there a folder kernels / with kernels?

**Comment by mayner88** [comment]
Yes, all threw with the miner, well, gives such an error

**Comment by AndreaLanfranchi** [comment]
AFAIK they should be in /kernels/**bin**/.

**Comment by mayner88** [comment]
![default](https://user-images.githubusercontent.com/36770898/43653581-25e25566-9751-11e8-9e85-5e3e426cc2a7.jpg)

**Comment by BoriZka67** [comment]
ethash_hawaii_lws128.bin not in the folder with the nuclei

**Comment by mayner88** [comment]
And where to get it if in the archive with the miner he did not go?

**Comment by ddobreff** [comment]
You can use clrxasm to compile .isa files for hawaii or use --cl-only to discard binary loader.

**Comment by mayner88** [comment]
At me near at hand is not present linux only win 10 who can that throws off?

**Comment by ddobreff** [comment]
I don't see this as an issue, if binary kernel is missing it will automatically switch to opencl.

**Comment by mayner88** [comment]
can have someone else to share ?

**Comment by ddobreff** [comment]
The issue you posted is not an error, its a message displaying that there is no binary kernel available for your GPU. If you cannot mine with "HAWAII" using opencl then simply post the whole log.

**Comment by mayner88** [comment]
E:\Ethminer>ethminer.exe --farm-recheck 200 --cl-local-work 128 --cl-global-work 16384 --cl-parallel-hash 2 --cl-kernel 1 -G -P stratum1+tcp://0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.R390X7@s2.solopool.org:8003
--cl-kernel ignored. Kernel is auto-selected
--cl-parallel-hash ignored. No longer applies
 m 22:19:26 main     ethminer 0.16.0.dev2
 m 22:19:26 main     Build: windows/release
 i 22:19:27 main     Found suitable OpenCL device [Hawaii] with 8а589а934а592 bytes of GPU memory
 i 22:19:27 main     Found suitable OpenCL device [Hawaii] with 8а589а934а592 bytes of GPU memory
 i 22:19:27 main     Found suitable OpenCL device [Hawaii] with 8а589а934а592 bytes of GPU memory
 i 22:19:27 main     Found suitable OpenCL device [Hawaii] with 8а589а934а592 bytes of GPU memory
 i 22:19:27 main     Found suitable OpenCL device [Hawaii] with 8а589а934а592 bytes of GPU memory
 i 22:19:27 main     Configured pool s2.solopool.org:8003
 i 22:19:27 main     Selected pool s2.solopool.org:8003
 i 22:19:27 stratum  Trying 92.53.79.125:8003 ...
 i 22:19:27 stratum  Connected to s2.solopool.org [92.53.79.125:8003]
 i 22:19:27 stratum  Spinning up miners...
cl 22:19:27 cl-0     No work. Pause for 3 s.
cl 22:19:27 cl-1     No work. Pause for 3 s.
cl 22:19:27 cl-2     No work. Pause for 3 s.
cl 22:19:27 cl-3     No work. Pause for 3 s.
cl 22:19:27 cl-4     No work. Pause for 3 s.
 i 22:19:27 stratum  Connection remotely closed by s2.solopool.org
 i 22:19:27 stratum  Trying 92.53.79.125:8003 ...
 i 22:19:28 stratum  Connected to s2.solopool.org [92.53.79.125:8003]
 i 22:19:28 stratum  Stratum mode detected : ETHPROXY compatible
 i 22:19:28 stratum  Logged in to eth-proxy server
 i 22:19:28 stratum  Job: #a8854c95... s2.solopool.org [92.53.79.125:8003]
 i 22:19:28 stratum  Pool difficulty: 4.00K megahash
 i 22:19:28 stratum  New epoch 25
 i 22:19:28 stratum  Job: #7f7ab98e... s2.solopool.org [92.53.79.125:8003]
cl 22:19:30 cl-0     Platform: AMD Accelerated Parallel Processing
cl 22:19:30 cl-1     Platform: AMD Accelerated Parallel Processing
cl 22:19:30 cl-2     Platform: AMD Accelerated Parallel Processing
cl 22:19:30 cl-3     Platform: AMD Accelerated Parallel Processing
cl 22:19:30 cl-4     Platform: AMD Accelerated Parallel Processing
cl 22:19:30 cl-0     Device:   Hawaii / OpenCL 2.0 AMD-APP (2580.6)
cl 22:19:30 cl-1     Device:   Hawaii / OpenCL 2.0 AMD-APP (2580.6)
cl 22:19:30 cl-2     Device:   Hawaii / OpenCL 2.0 AMD-APP (2580.6)
cl 22:19:30 cl-3     Device:   Hawaii / OpenCL 2.0 AMD-APP (2580.6)
cl 22:19:30 cl-4     Device:   Hawaii / OpenCL 2.0 AMD-APP (2580.6)
 i 22:19:31 cl-1     Adjusting CL work multiplier for 40 CUs.Adjusted work multiplier: 18а205
 i 22:19:31 cl-4     Adjusting CL work multiplier for 40 CUs.Adjusted work multiplier: 18а205
 i 22:19:32 cl-3     Adjusting CL work multiplier for 40 CUs.Adjusted work multiplier: 18а205
cl 22:19:32 cl-4     OpenCL kernel
cl 22:19:32 cl-3     OpenCL kernel
cl 22:19:32 cl-1     OpenCL kernel
 i 22:19:32 cl-2     Adjusting CL work multiplier for 40 CUs.Adjusted work multiplier: 18а205
cl 22:19:32 cl-2     OpenCL kernel
 i 22:19:32 cl-0     Adjusting CL work multiplier for 40 CUs.Adjusted work multiplier: 18а205
cl 22:19:32 cl-0     OpenCL kernel
 m 22:19:32 main     Speed 0,00 Mh/s gpu0 0,00 gpu1 0,00 gpu2 0,00 gpu3 0,00 gpu4 0,00 [A0] Time: 00:00
cl 22:19:33 cl-2     Loading binary kernel E:\Ethminer/kernels/ethash_hawaii_lws128.bin
 X 22:19:33 cl-2     Failed to load binary kernel: E:\Ethminer/kernels/ethash_hawaii_lws128.bin
 X 22:19:33 cl-2     Falling back to OpenCL kernel...
cl 22:19:33 cl-2     Creating light cache buffer, size: 20а053а952
cl 22:19:33 cl-2     Creating DAG buffer, size: 1а283а453а312
cl 22:19:33 cl-2     Loading kernels
cl 22:19:33 cl-2     Writing light cache buffer
cl 22:19:33 cl-2     Creating buffer for header.
cl 22:19:33 cl-2     Creating mining buffer
cl 22:19:34 cl-0     Loading binary kernel E:\Ethminer/kernels/ethash_hawaii_lws128.bin
 X 22:19:34 cl-0     Failed to load binary kernel: E:\Ethminer/kernels/ethash_hawaii_lws128.bin
 X 22:19:34 cl-0     Falling back to OpenCL kernel...
cl 22:19:34 cl-0     Creating light cache buffer, size: 20а053а952
cl 22:19:34 cl-0     Creating DAG buffer, size: 1а283а453а312
cl 22:19:34 cl-0     Loading kernels
cl 22:19:34 cl-0     Writing light cache buffer
cl 22:19:34 cl-0     Creating buffer for header.
cl 22:19:34 cl-0     Creating mining buffer
cl 22:19:34 cl-1     Loading binary kernel E:\Ethminer/kernels/ethash_hawaii_lws128.bin
 X 22:19:34 cl-1     Failed to load binary kernel: E:\Ethminer/kernels/ethash_hawaii_lws128.bin
 X 22:19:34 cl-1     Falling back to OpenCL kernel...
cl 22:19:34 cl-1     Creating light cache buffer, size: 20а053а952
cl 22:19:34 cl-1     Creating DAG buffer, size: 1а283а453а312
cl 22:19:34 cl-1     Loading kernels
cl 22:19:34 cl-1     Writing light cache buffer
cl 22:19:35 cl-1     Creating buffer for header.
cl 22:19:35 cl-1     Creating mining buffer
cl 22:19:35 cl-3     Loading binary kernel E:\Ethminer/kernels/ethash_hawaii_lws128.bin
 X 22:19:35 cl-3     Failed to load binary kernel: E:\Ethminer/kernels/ethash_hawaii_lws128.bin
 X 22:19:35 cl-3     Falling back to OpenCL kernel...
cl 22:19:35 cl-3     Creating light cache buffer, size: 20а053а952
cl 22:19:35 cl-3     Creating DAG buffer, size: 1а283а453а312
cl 22:19:35 cl-3     Loading kernels
cl 22:19:35 cl-3     Writing light cache buffer
cl 22:19:35 cl-3     Creating buffer for header.
cl 22:19:35 cl-3     Creating mining buffer
 i 22:19:35 cl-2     1,19531 GB of DAG data generated in 2а402 ms.
cl 22:19:36 cl-4     Loading binary kernel E:\Ethminer/kernels/ethash_hawaii_lws128.bin
 X 22:19:36 cl-4     Failed to load binary kernel: E:\Ethminer/kernels/ethash_hawaii_lws128.bin
 X 22:19:36 cl-4     Falling back to OpenCL kernel...
cl 22:19:36 cl-4     Creating light cache buffer, size: 20а053а952
cl 22:19:36 cl-4     Creating DAG buffer, size: 1а283а453а312
cl 22:19:36 cl-4     Loading kernels
cl 22:19:36 cl-4     Writing light cache buffer
cl 22:19:36 cl-4     Creating buffer for header.
cl 22:19:36 cl-4     Creating mining buffer
 i 22:19:36 cl-0     1,19531 GB of DAG data generated in 2а398 ms.
 i 22:19:37 cl-1     1,19531 GB of DAG data generated in 2а389 ms.
 m 22:19:37 main     Speed 3,71 Mh/s gpu0 0,53 gpu1 0,00 gpu2 3,18 gpu3 0,00 gpu4 0,00 [A0] Time: 00:00
 i 22:19:38 cl-3     1,19531 GB of DAG data generated in 2а530 ms.
 i 22:19:38 cl-4     1,19531 GB of DAG data generated in 2а385 ms.
 i 22:19:41 cl-0     Solution: 0x73260dc44d0f0417
 i 22:19:41 stratum  **Accepted  73 ms. s2.solopool.org [92.53.79.125:8003]
 i 22:19:41 stratum  Job: #aaf35721... s2.solopool.org [92.53.79.125:8003]
 m 22:19:42 main     Speed 47,35 Mh/s gpu0 11,18 gpu1 9,64 gpu2 13,02 gpu3 7,26 gpu4 6,25 [A1] Time: 00:00

**Comment by ddobreff** [comment]
Please remove --farm-recheck 200 --cl-global-work 16384 --cl-parallel-hash 2 --cl-kernel 1
They are not used anymore. Set --cl-local-work 192  wait a few minutes for hashrate to adjust. I don't see any issue with this.

**Comment by mayner88** [comment]
TIMEOUT 20
@echo off
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
@echo on
:start
ethminer.exe --cl-local-work 192 -G -P stratum1+tcp://0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.RX7@s2.solopool.org:8003
taskkill /F /IM ethminer.exe
goto start

**Comment by mayner88** [comment]
Hashes have fallen

m 00:04:00 main     ethminer 0.16.0.dev2
 m 00:04:00 main     Build: windows/release
 i 00:04:01 main     Found suitable OpenCL device [Hawaii] with 8а589а934а592 bytes of GPU memory
 i 00:04:01 main     Found suitable OpenCL device [Hawaii] with 8а589а934а592 bytes of GPU memory
 i 00:04:01 main     Found suitable OpenCL device [Hawaii] with 8а589а934а592 bytes of GPU memory
 i 00:04:01 main     Found suitable OpenCL device [Hawaii] with 8а589а934а592 bytes of GPU memory
 i 00:04:01 main     Found suitable OpenCL device [Hawaii] with 8а589а934а592 bytes of GPU memory
 i 00:04:01 main     Configured pool s2.solopool.org:8003
 i 00:04:01 main     Selected pool s2.solopool.org:8003
 i 00:04:01 stratum  Trying 92.53.79.125:8003 ...
 i 00:04:01 stratum  Connected to s2.solopool.org [92.53.79.125:8003]
 i 00:04:01 stratum  Spinning up miners...
cl 00:04:01 cl-0     No work. Pause for 3 s.
cl 00:04:01 cl-1     No work. Pause for 3 s.
cl 00:04:01 cl-2     No work. Pause for 3 s.
cl 00:04:01 cl-3     No work. Pause for 3 s.
cl 00:04:01 cl-4     No work. Pause for 3 s.
 i 00:04:01 stratum  Connection remotely closed by s2.solopool.org
 i 00:04:01 stratum  Trying 92.53.79.125:8003 ...
 i 00:04:01 stratum  Connected to s2.solopool.org [92.53.79.125:8003]
 i 00:04:02 stratum  Stratum mode detected : ETHPROXY compatible
 i 00:04:02 stratum  Logged in to eth-proxy server
 i 00:04:02 stratum  Job: #5b2cea33... s2.solopool.org [92.53.79.125:8003]
 i 00:04:02 stratum  Pool difficulty: 4.00K megahash
 i 00:04:02 stratum  New epoch 25
cl 00:04:04 cl-0     Platform: AMD Accelerated Parallel Processing
cl 00:04:04 cl-1     Platform: AMD Accelerated Parallel Processing
cl 00:04:04 cl-0     Device:   Hawaii / OpenCL 2.0 AMD-APP (2580.6)
cl 00:04:04 cl-2     Platform: AMD Accelerated Parallel Processing
cl 00:04:04 cl-3     Platform: AMD Accelerated Parallel Processing
cl 00:04:04 cl-4     Platform: AMD Accelerated Parallel Processing
cl 00:04:04 cl-1     Device:   Hawaii / OpenCL 2.0 AMD-APP (2580.6)
cl 00:04:04 cl-2     Device:   Hawaii / OpenCL 2.0 AMD-APP (2580.6)
cl 00:04:04 cl-3     Device:   Hawaii / OpenCL 2.0 AMD-APP (2580.6)
cl 00:04:04 cl-4     Device:   Hawaii / OpenCL 2.0 AMD-APP (2580.6)
 i 00:04:05 cl-0     Adjusting CL work multiplier for 40 CUs.Adjusted work multiplier: 72а818
 i 00:04:06 cl-4     Adjusting CL work multiplier for 40 CUs.Adjusted work multiplier: 72а818
 i 00:04:06 cl-3     Adjusting CL work multiplier for 40 CUs.Adjusted work multiplier: 72а818
cl 00:04:06 cl-0     OpenCL kernel
cl 00:04:06 cl-4     OpenCL kernel
 i 00:04:06 cl-1     Adjusting CL work multiplier for 40 CUs.Adjusted work multiplier: 72а818
cl 00:04:06 cl-3     OpenCL kernel
cl 00:04:06 cl-1     OpenCL kernel
 i 00:04:06 cl-2     Adjusting CL work multiplier for 40 CUs.Adjusted work multiplier: 72а818
cl 00:04:06 cl-2     OpenCL kernel
 m 00:04:06 main     Speed 0,00 Mh/s gpu0 0,00 gpu1 0,00 gpu2 0,00 gpu3 0,00 gpu4 0,00 [A0] Time: 00:00
cl 00:04:07 cl-1     Loading binary kernel E:\Ethminer/kernels/ethash_hawaii_lws192.bin
 X 00:04:07 cl-1     Failed to load binary kernel: E:\Ethminer/kernels/ethash_hawaii_lws192.bin
 X 00:04:07 cl-1     Falling back to OpenCL kernel...
cl 00:04:07 cl-1     Creating light cache buffer, size: 20а053а952
cl 00:04:07 cl-1     Creating DAG buffer, size: 1а283а453а312
cl 00:04:07 cl-1     Loading kernels
cl 00:04:07 cl-1     Writing light cache buffer
cl 00:04:07 cl-1     Creating buffer for header.
cl 00:04:07 cl-1     Creating mining buffer
cl 00:04:08 cl-2     Loading binary kernel E:\Ethminer/kernels/ethash_hawaii_lws192.bin
 X 00:04:08 cl-2     Failed to load binary kernel: E:\Ethminer/kernels/ethash_hawaii_lws192.bin
 X 00:04:08 cl-2     Falling back to OpenCL kernel...
cl 00:04:08 cl-2     Creating light cache buffer, size: 20а053а952
cl 00:04:08 cl-2     Creating DAG buffer, size: 1а283а453а312
cl 00:04:08 cl-2     Loading kernels
cl 00:04:08 cl-2     Writing light cache buffer
cl 00:04:08 cl-2     Creating buffer for header.
cl 00:04:08 cl-2     Creating mining buffer
cl 00:04:08 cl-3     Loading binary kernel E:\Ethminer/kernels/ethash_hawaii_lws192.bin
 X 00:04:08 cl-3     Failed to load binary kernel: E:\Ethminer/kernels/ethash_hawaii_lws192.bin
 X 00:04:08 cl-3     Falling back to OpenCL kernel...
cl 00:04:08 cl-3     Creating light cache buffer, size: 20а053а952
cl 00:04:08 cl-3     Creating DAG buffer, size: 1а283а453а312
cl 00:04:08 cl-3     Loading kernels
cl 00:04:08 cl-3     Writing light cache buffer
cl 00:04:08 cl-3     Creating buffer for header.
cl 00:04:08 cl-3     Creating mining buffer
cl 00:04:09 cl-4     Loading binary kernel E:\Ethminer/kernels/ethash_hawaii_lws192.bin
 X 00:04:09 cl-4     Failed to load binary kernel: E:\Ethminer/kernels/ethash_hawaii_lws192.bin
 X 00:04:09 cl-4     Falling back to OpenCL kernel...
cl 00:04:09 cl-4     Creating light cache buffer, size: 20а053а952
cl 00:04:09 cl-4     Creating DAG buffer, size: 1а283а453а312
cl 00:04:09 cl-4     Loading kernels
cl 00:04:09 cl-4     Writing light cache buffer
cl 00:04:09 cl-4     Creating buffer for header.
cl 00:04:09 cl-4     Creating mining buffer
 i 00:04:09 cl-1     1,19531 GB of DAG data generated in 2а390 ms.
cl 00:04:10 cl-0     Loading binary kernel E:\Ethminer/kernels/ethash_hawaii_lws192.bin
 X 00:04:10 cl-0     Failed to load binary kernel: E:\Ethminer/kernels/ethash_hawaii_lws192.bin
 X 00:04:10 cl-0     Falling back to OpenCL kernel...
cl 00:04:10 cl-0     Creating light cache buffer, size: 20а053а952
cl 00:04:10 cl-0     Creating DAG buffer, size: 1а283а453а312
cl 00:04:10 cl-0     Loading kernels
cl 00:04:10 cl-0     Writing light cache buffer
cl 00:04:10 cl-0     Creating buffer for header.
cl 00:04:10 cl-0     Creating mining buffer
 i 00:04:10 cl-2     1,19531 GB of DAG data generated in 2а381 ms.
 i 00:04:11 cl-3     1,19531 GB of DAG data generated in 2а548 ms.
 m 00:04:11 main     Speed 3,19 Mh/s gpu0 0,00 gpu1 3,19 gpu2 0,00 gpu3 0,00 gpu4 0,00 [A0] Time: 00:00
 i 00:04:12 cl-4     1,19531 GB of DAG data generated in 2а381 ms.
 i 00:04:12 cl-0     1,19531 GB of DAG data generated in 2а410 ms.
 m 00:04:16 main     Speed 42,64 Mh/s gpu0 5,08 gpu1 12,18 gpu2 10,15 gpu3 8,12 gpu4 7,11 [A0] Time: 00:00
 i 00:04:17 stratum  Job: #59f57b77... s2.solopool.org [92.53.79.125:8003]
 m 00:04:21 main     Speed 71,28 Mh/s gpu0 12,08 gpu1 16,91 gpu2 15,76 gpu3 13,07 gpu4 13,45 [A0] Time: 00:00
 i 00:04:21 stratum  Job: #ad342ded... s2.solopool.org [92.53.79.125:8003]
 i 00:04:23 cl-1     Solution: 0x5119e2e02240692f
 i 00:04:23 stratum  **Accepted  66 ms. s2.solopool.org [92.53.79.125:8003]
 m 00:04:26 main     Speed 85,28 Mh/s gpu0 15,41 gpu1 19,21 gpu2 18,32 gpu3 15,87 gpu4 16,48 [A1] Time: 00:00
 m 00:04:31 main     Speed 94,76 Mh/s gpu0 17,59 gpu1 20,73 gpu2 19,99 gpu3 17,97 gpu4 18,48 [A1] Time: 00:00
 m 00:04:36 main     Speed 116,03 Mh/s gpu0 21,99 gpu1 25,00 gpu2 24,30 gpu3 21,89 gpu4 22,84 [A1] Time: 00:00
 i 00:04:38 stratum  Job: #e103879b... s2.solopool.org [92.53.79.125:8003]
 i 00:04:41 cl-1     Solution: 0x5119e2e022b60931
 i 00:04:41 stratum  **Accepted  72 ms. s2.solopool.org [92.53.79.125:8003]
 m 00:04:41 main     Speed 139,08 Mh/s gpu0 26,88 gpu1 28,97 gpu2 29,19 gpu3 26,30 gpu4 27,73 [A2] Time: 00:00
 m 00:04:46 main     Speed 143,73 Mh/s gpu0 29,21 gpu1 28,97 gpu2 29,19 gpu3 27,23 gpu4 29,13 [A2] Time: 00:00
 m 00:04:51 main     Speed 143,73 Mh/s gpu0 29,07 gpu1 29,06 gpu2 29,08 gpu3 27,46 gpu4 29,07 [A2] Time: 00:00
 m 00:04:56 main     Speed 143,49 Mh/s gpu0 29,05 gpu1 29,05 gpu2 29,05 gpu3 27,29 gpu4 29,05 [A2] Time: 00:00

**Comment by mayner88** [comment]
DID ethminer.exe --cl-local-work 256 has become
 m 00:15:29 main     Speed 151,82 Mh/s gpu0 30,80 gpu1 30,85 gpu2 30,86 gpu3 28,92 gpu4 30,38 [A16] Time: 00:07

error left Failed to load binary kernel: E:\Ethminer/kernels/ethash_hawaii_lws192.bin

**Comment by goobur** [comment]
This looks like an issue with path delimiters, windows uses "\" but the code was written for linux with "/".

**Comment by jean-m-cyr** [comment]
Path delimiter issue should be corrected by PR #1413, but also there is no binary kernel for hawai.

**Comment by StefanOberhumer** [comment]
>This looks like an issue with path delimiters, windows uses "\" but the code was written for linux with "/".

Just as info: "/" works as path delimiter also under windows (and I used it also under DOS back in 1991).

**Comment by jean-m-cyr** [comment]
There is really no issue left here... closing
