### ISSUE TITLE
Thanks for all your work

### ISSUE THREAD

**Issue by tonyaik** [ethereum-mining/ethminer#1412]
To all developers of ethminer: I'm so grateful for all the time and effort you put in this project. With all the great improvements to the miner lately I thought I'd show my appreciation. I see you get hate sometimes but not much love, so at least now you've gotten some.

Thanks a bunch!
(Sorry for registering an issues for this, but I thought it was worth it.)

**Comment by AndreaLanfranchi** [comment]
Thank you @tonyaik
