### ISSUE TITLE
Possible crash when submitting solutions

### ISSUE THREAD

**Issue by cross** [ethereum-mining/ethminer#1415]
**Describe the bug**
eth miner will run for a few minutes, sometimes successfully submitting one or more solutions.  But eventually, after producing a solution, it will fail when trying to submit the solution.

I am using nanopool, and CUDA drivers on an nVidia device.  Compiled against Cuda 9.1 packages available for my Ubuntu 18.04 system.

**To Reproduce**
Run ethminer -U 

**Expected behavior**

**Screenshots (Optional)**
```
% ethminer -U http://eth-us-east1.nanopool.org:8888/0x4341C1fA5802C0Ba1aA99a22cE0cDF6b72782167.P100
 m 10:47:39 ethminer ethminer 0.16.0.dev2-10+commit.50e91602
 m 10:47:39 ethminer Build: linux/release
cu 10:47:40 ethminer Using grid size: 8,192, block size: 128
 i 10:47:40 ethminer Configured pool eth-us-east1.nanopool.org:8888
 i 10:47:40 main     Selected pool eth-us-east1.nanopool.org:8888
 i 10:47:40 main     Connected to eth-us-east1.nanopool.org
 i 10:47:40 main     Spinning up miners...
[...]
 i 10:54:42 getwork  Job: #d50e4d33… eth-us-east1.nanopool.org
 i 10:54:43 cuda-0   Solution: 0xc16c4d09207c4a6c
 X 10:54:43 cuda-0   Failed to submit solution.
 X 10:54:43 cuda-0   Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 2

ethminer: malloc.c:2868: mremap_chunk: Assertion `((size + offset) & (GLRO (dl_pagesize) - 1)) == 0' failed.
```

I have also seen failures where the ethminer will exit after reporting

```
 i 11:07:43 getwork  Job: #c431b701… eth-us-east1.nanopool.org
 i 11:07:44 cuda-0   Solution: 0xd04af521be3c98ce
 X 11:07:44 getwork  Failed getting work!
 i 11:07:44 main     Disconnected from eth-us-east1.nanopool.org
```

I don't know that that's the same problem, so leave that as another issue.  Focus this bug on the reported crash listed first.

**Desktop (please complete the following information):**
- OS:  Ubuntu 18.04
- Hardware:  Titan P100
- Ethminer version: 0.16.0.dev2-10+commit.50e91602

**Additional context**
Easily reproducible.  Doesn't happen every time, but happens within the first 10 minutes of running, and happens on most executions.  :-)

**Comment by AndreaLanfranchi** [comment]
Do not, I reiterate, do not use getwork (http) for mining to pools. It stresses too much your router and is the least efficient way to mine.

Use this
```
% ethminer -U -P stratum+tcp://0x4341C1fA5802C0Ba1aA99a22cE0cDF6b72782167.P100@eth-us-east1.nanopool.org:9999
```

**Comment by AndreaLanfranchi** [comment]
getwork is not viable anymore even if some pools still offer it as a possible connection method.
We're maintaining this only for backwards compatibility. 

When a pool offers stratum connection **use it**

**Comment by cross** [comment]
Okay, thanks.  I got that http:// URI from their documentation.  I see now digging deeper that they offer stratum, and will switch to that.  Thanks.
