### ISSUE TITLE
Parse response failed: * Line 1, Column 101 Missing ',' or ']' in array declaration

### ISSUE THREAD

**Issue by JHGitty** [ethereum-mining/ethminer#142]
After a few hours I get this error on my miner:
>   i  00:03:27|stratum  Connected to stratum server eth-eu1.nanopool.org : 9999
>   X  00:03:27|stratum  Parse response failed: * Line 1, Column 101
>   Missing ',' or ']' in array declaration

I don't know yet why it happens. I use the release stable version 0.11.0.

System: Windows 10 x64, 7x GTX 1060, ASUS PRIME Z270-A, overclocked to +650 Memory @ 65% Power Target

**Is there any way to find out what the miner tried to parse? Maybe the pool stratum server returns some crap and the miner does not know how to handle it.**

**Comment by JHGitty** [comment]
**Some more information about this error:**

After this error the miner only shows endless in a loop:
>   X  00:03:44|cudaminer2  Can't submit solution: Not connected
>   i  00:03:52|stratum  Received new job #29ff5349
>   i  00:03:53|cudaminer0  set work; seed: #9e972470, target: #00000000dbe6
>   i  00:03:53|cudaminer1  set work; seed: #9e972470, target: #00000000dbe6
>   i  00:03:53|cudaminer2  set work; seed: #9e972470, target: #00000000dbe6
>   i  00:03:53|cudaminer3  set work; seed: #9e972470, target: #00000000dbe6
>   i  00:03:53|cudaminer4  set work; seed: #9e972470, target: #00000000dbe6
>   i  00:03:53|cudaminer5  set work; seed: #9e972470, target: #00000000dbe6
>   i  00:03:53|cudaminer6  set work; seed: #9e972470, target: #00000000dbe6

So the miner is not fixing that issue itself - i need to restart the miner software manually to fix that issue.

**Comment by JHGitty** [comment]
Hi @chfast ,
can you provide me a windows executable which is logging the stratum server response to a text file to debug this? I did not see that error again but I think it's a missing error handling of an unexpected server response. Maybe we will see this error again in the future - so it might be good to be prepared to log this issue once it happens.

**Comment by JHGitty** [comment]
This issue might be related to #153 ?!

**Comment by JHGitty** [comment]
I didn't see this issue again so I close this issue here.

**Comment by georgedpeterson** [comment]
Also seeing "Can't submit solution: Not connected"

**Comment by dnandha** [comment]
@georgedpeterson same is happening for me, but only on one of my rigs.
I'm running ethminer 0.13.0rc7 on Ubuntu 16.04.3., installed on an USB stick. I was suspecting maybe it is  disk issue when json file is not written fast enough. However, I do not know how to get any debug information out of ethminer...
Here is my log:
 ℹ  11:14:16|stratum   Received new job #2d73c83a  seed: #51e74ac038c9e3e66658ef25c1591022  target: #000000006df37f675ef6eadf                                                  [1642/45351]
  ℹ  11:18:02|CUDA0     Solution found; Submitted to eth-eu1.nanopool.org
  ℹ  11:25:18|CUDA1     Solution found; Submitted to eth-eu1.nanopool.org
  ℹ  11:28:52|CUDA0     Nonce: 0xafa40dd6d96ed38f
  ℹ  11:28:52|CUDA1     Nonce: 0x8bf304f3599555d6
  ℹ  11:28:52|stratum   Received new job #064b98bc  seed: #51e74ac038c9e3e66658ef25c1591022  target: #000000006df37f675ef6eadf
  ℹ  11:28:52|stratum   No new work received in 180 seconds.
  ℹ  11:28:52|stratum   Reconnecting in 3 seconds...
  ℹ  11:28:55|stratum   Connecting to stratum server eth-eu1.nanopool.org:9999
  ℹ  11:28:55|stratum   Received new job #b5ddbc7e  seed: #51e74ac038c9e3e66658ef25c1591022  target: #000000006df37f675ef6eadf
  ℹ  11:28:55|stratum   Connected to stratum server eth-eu1.nanopool.org : 9999
  ℹ  11:28:55|stratum   Received new job #f9868742  seed: #51e74ac038c9e3e66658ef25c1591022  target: #000000006df37f675ef6eadf
  ✘  11:28:55|stratum   Parse response failed: * Line 1, Column 22
  Missing ',' or '}' in object declaration

  ℹ  11:28:58|stratum   Received new job #407f08a1  seed: #51e74ac038c9e3e66658ef25c1591022  target: #000000006df37f675ef6eadf
  ℹ  11:29:06|stratum   Received new job #80b980f9  seed: #51e74ac038c9e3e66658ef25c1591022  target: #000000006df37f675ef6eadf
  ℹ  11:29:30|stratum   Received new job #aba61a0d  seed: #51e74ac038c9e3e66658ef25c1591022  target: #000000006df37f675ef6eadf
  ✘  11:29:40|CUDA0     Can't submit solution: Not connected
  ℹ  11:29:46|stratum   Received new job #b73e27a9  seed: #51e74ac038c9e3e66658ef25c1591022  target: #000000006df37f675ef6eadf
  ℹ  11:29:49|stratum   Received new job #ffea08fc  seed: #51e74ac038c9e3e66658ef25c1591022  target: #000000006df37f675ef6eadf
  ✘  11:29:56|CUDA1     Can't submit solution: Not connected
  ℹ  11:30:01|stratum   Received new job #9c71072c  seed: #51e74ac038c9e3e66658ef25c1591022  target: #000000006df37f675ef6eadf
  ℹ  11:30:10|stratum   Received new job #ca1bb2d5  seed: #51e74ac038c9e3e66658ef25c1591022  target: #000000006df37f675ef6eadf
  ℹ  11:30:13|stratum   Received new job #2120b49d  seed: #51e74ac038c9e3e66658ef25c1591022  target: #000000006df37f675ef6eadf
  ✘  11:30:19|CUDA0     Can't submit solution: Not connected
  ℹ  11:30:24|stratum   Received new job #4a483e9e  seed: #51e74ac038c9e3e66658ef25c1591022  target: #000000006df37f675ef6eadf
  ℹ  11:30:41|stratum   Received new job #13963fe9  seed: #51e74ac038c9e3e66658ef25c1591022  target: #000000006df37f675ef6eadf

**Comment by cypheron** [comment]
@georgedpeterson same is happening for me, but only on one of my rigs.
I'm running ethminer 0.13.0rc7 on Ubuntu 16.04.3., installed on an USB stick. I was suspecting maybe it is disk issue when json file is not written fast enough. However, I do not know how to get any debug information out of ethminer...
Here is my log:
ℹ 11:14:16|stratum Received new job #2d73c83a seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf [1642/45351]
ℹ 11:18:02|CUDA0 Solution found; Submitted to eth-eu1.nanopool.org
ℹ 11:25:18|CUDA1 Solution found; Submitted to eth-eu1.nanopool.org
ℹ 11:28:52|CUDA0 Nonce: 0xafa40dd6d96ed38f
ℹ 11:28:52|CUDA1 Nonce: 0x8bf304f3599555d6
ℹ 11:28:52|stratum Received new job #064b98bc seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
ℹ 11:28:52|stratum No new work received in 180 seconds.
ℹ 11:28:52|stratum Reconnecting in 3 seconds...
ℹ 11:28:55|stratum Connecting to stratum server eth-eu1.nanopool.org:9999
ℹ 11:28:55|stratum Received new job #b5ddbc7e seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
ℹ 11:28:55|stratum Connected to stratum server eth-eu1.nanopool.org : 9999
ℹ 11:28:55|stratum Received new job #f9868742 seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
✘ 11:28:55|stratum Parse response failed: * Line 1, Column 22
Missing ',' or '}' in object declaration

ℹ 11:28:58|stratum Received new job #407f08a1 seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
ℹ 11:29:06|stratum Received new job #80b980f9 seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
ℹ 11:29:30|stratum Received new job #aba61a0d seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
✘ 11:29:40|CUDA0 Can't submit solution: Not connected
ℹ 11:29:46|stratum Received new job #b73e27a9 seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
ℹ 11:29:49|stratum Received new job #ffea08fc seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
✘ 11:29:56|CUDA1 Can't submit solution: Not connected
ℹ 11:30:01|stratum Received new job #9c71072c seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
ℹ 11:30:10|stratum Received new job #ca1bb2d5 seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
ℹ 11:30:13|stratum Received new job #2120b49d seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
✘ 11:30:19|CUDA0 Can't submit solution: Not connected
ℹ 11:30:24|stratum Received new job #4a483e9e seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
ℹ 11:30:41|stratum Received new job #13963fe9 seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf

**Comment by georgedpeterson** [comment]
Any updates? Still experiencing this.

**Comment by AndreaLanfranchi** [comment]
Addressed in #1027
