### ISSUE TITLE
Too high hashrate - ethminer 0.15.0

### ISSUE THREAD

**Issue by Rodriguevb** [ethereum-mining/ethminer#1420]
Sometimes my gpus display an unreachable hashrate and the software seems to not work properly. I have no idea how it happens. How to avoid that?

- Ubuntu server 16.0
- GTX 1070 / 1070Ti
- ethminer 0.15.0

> 	 i 16:26:04 cuda-3   Solution: 0xf71fc06c54e0c5f2
> 	 i 16:26:12 cuda-3   Solution: 0xf71fc06c61bd7dd1
	 i 16:26:18 cuda-0   Solution: 0xf71fbd6c6c766fdd
	 i 16:26:19 cuda-11  Solution: 0xf71fc86c76f5758c
	 X 16:26:23 stratum  No response received in2seconds.
	 i 16:26:23 main     Disconnected from eth-eu1.nanopool.org [51.15.39.186:9999]
	 i 16:26:23 stratum  Job: #14d8390e… eth-eu1.nanopool.org [51.15.39.186:9999]
	 m 16:26:23 ethminer Speed 1921.71 Mh/s    gpu/0 133.06  gpu/1 133.60   gpu/2 132.18   gpu/3 136.45   gpu/4 159.67   gpu/5 135.69   gpu/6 160.98   gpu/7 161.31   gpu/8 148.06   gpu/9 161.31    gpu/10 140.61    gpu/11 161.09   gpu/12 157.70   [A88+0:R6+3:F0] Time: 00:46
	 i 16:26:24 main     Selected pool eth-eu1.nanopool.org:9999
	 i 16:26:24 stratum  Trying 51.15.39.186:9999 ...
	 i 16:26:24 stratum  Connected to eth-eu1.nanopool.org [51.15.39.186:9999]
	 i 16:26:24 stratum  **Accepted   0 ms. eth-eu1.nanopool.org [51.15.39.186:9999]
	 i 16:26:24 stratum  **Accepted   0 ms. eth-eu1.nanopool.org [51.15.39.186:9999]
	 i 16:26:24 stratum  **Accepted   0 ms. eth-eu1.nanopool.org [51.15.39.186:9999]
	 i 16:26:24 stratum  **Accepted   0 ms. eth-eu1.nanopool.org [51.15.39.186:9999]
	 i 16:26:24 stratum  **Accepted   0 ms. eth-eu1.nanopool.org [51.15.39.186:9999]
	 i 16:26:24 stratum  **Accepted   0 ms. eth-eu1.nanopool.org [51.15.39.186:9999]
	 i 16:26:24 stratum  **Accepted   0 ms. eth-eu1.nanopool.org [51.15.39.186:9999]
	 i 16:26:24 stratum  **Accepted   0 ms. eth-eu1.nanopool.org [51.15.39.186:9999]
	 i 16:26:24 stratum  **Accepted   0 ms. eth-eu1.nanopool.org [51.15.39.186:9999]
	 X 16:26:24 stratum  Got invalid Json message :* Line 1, Column 6
> 	  Missing ':' after object member name
> 	
> 	 i 16:26:43 cuda-2   Solution: 0xf71fbf6c5e45d10e

**Comment by AndreaLanfranchi** [comment]
Does it happen when you DO NOT overclock ?

**Comment by Rodriguevb** [comment]
> --pool stratum+tcp://$ADDRESS.$MINERNAME@$SERVER1 --stratum-email $EMAIL --cuda --nocolor --report-hashrate --HWMON 0 --cuda-schedule auto

It continues for easily 15 minutes before crash and it doesn't happen if I don't overclock

**Comment by lesjokolat** [comment]
what if you tweaked your startup bat...

ethminer -U -P -L 0 --HWMON 1 --report-hashrate stratum+tcp://$ADDRESS.$MINERNAME@$SERVER1 --cl-local-work YOUR PREF --cl-global-work YOUR PREF -v 8

**Comment by AndreaLanfranchi** [comment]
> It continues for easily 15 minutes before crash and it doesn't happen if I don't overclock

You have your answer. Reduce progressively your overclocking values till you find a stable value.
