### ISSUE TITLE
In vers 16.dev2 cards listing has changed from vers 15

### ISSUE THREAD

**Issue by ZiDanRO** [ethereum-mining/ethminer#1422]
From version 15 i jumpt to version 16.dev2 and i see The order of the cards in cuda mode has changed. It is correct or i'm missing something?

**Comment by ddobreff** [comment]
linux or windows?

**Comment by StefanOberhumer** [comment]
Have you checked the FAQ **CUDA GPU order changes sometimes. What can I do?** ?
https://github.com/ethereum-mining/ethminer#cuda-gpu-order-changes-sometimes-what-can-i-do

**Comment by StefanOberhumer** [comment]
Can you post the output of `ethminer.exe -U --list-devices` of version 15 and 16-dev2 ?

**Comment by StefanOberhumer** [comment]
No feedback got - closing issue.
