### ISSUE TITLE
Ethminer build 0.16.0.dev2-22+commit.211a1aff breaks Stratum Mode

### ISSUE THREAD

**Issue by slinkyvagabond** [ethereum-mining/ethminer#1423]
Ethminer built from source 17:35:10 Aug 5 breaks Stratum detection. Previous build (0.06.0.dev2) works as expected. I build from source once a week on the Master branch to test new optimisations. See below log:

ethminer -R -U -P -v 2 --HWMON=1 --cuda-parallel-hash=8 --cuda-block-size 256 --cuda-streams 68 --farm-recheck=200 stratum2+tcp://0x172717A2e99Adec3c2D9CF967992cd4493CB57d7.desktop@eth-us.maxhash.org:8011
 m 17:35:58 ethminer ethminer 0.16.0.dev2-22+commit.211a1aff
 m 17:35:58 ethminer Build: linux/release
cu 17:35:58 ethminer Using grid size: 8,192, block size: 256
 i 17:35:58 ethminer Configured pool eth-us.maxhash.org:8011
 i 17:35:58 main     Selected pool eth-us.maxhash.org:8011
 i 17:35:58 stratum  Trying 144.217.66.227:8011 ...
 i 17:35:58 stratum  Connected to eth-us.maxhash.org [144.217.66.227:8011]
 i 17:35:58 stratum  Spinning up miners...
 i 17:35:58 cuda-0   No work. Pause for 3 s.
 i 17:35:58 stratum  Connection remotely closed by eth-us.maxhash.org
 i 17:35:58 stratum  Trying 144.217.66.227:8011 ...
 i 17:35:58 stratum  Connected to eth-us.maxhash.org [144.217.66.227:8011]
 X 17:35:58 stratum  Unable to find suitable Stratum Mode
 i 17:35:58 stratum  Connection remotely closed by eth-us.maxhash.org

No errors on build process - Previous build was working perfectly. 

**Desktop (please complete the following information):**
- Ubuntu Linux 18.04 (with latest updates)
- GTX1070Ti
- Ethminer Version 0.16.0.dev2-22+commit.211a1aff

Please let me know if there is anything I can do to help out. :)

**Comment by DuDlikSPB** [comment]
Same

 23:33:32 stratum  Connected to eth.2miners.ru [54.36.109.160:2020]
 i 23:33:33 stratum  Could not subscribe to stratum server
 i 23:33:33 main     Disconnected from eth.2miners.ru [54.36.109.160:2020]
 i 23:33:33 main     Selected pool eth.2miners.ru:2020
 i 23:33:33 stratum  Trying 54.36.109.160:2020 ...
 i 23:33:33 stratum  Connected to eth.2miners.ru [54.36.109.160:2020]
 i 23:33:34 stratum  Could not subscribe to stratum server
 i 23:33:34 main     Disconnected from eth.2miners.ru [54.36.109.160:2020]
 i 23:33:34 main     Selected pool eth.2miners.ru:2020
 i 23:33:34 stratum  Trying 54.36.109.160:2020 ...
 i 23:33:34 stratum  Connected to eth.2miners.ru [54.36.109.160:2020]
 i 23:33:35 stratum  Could not subscribe to stratum server
 i 23:33:35 main     Disconnected from eth.2miners.ru [54.36.109.160:2020]
 i 23:33:35 Api      New api session from 127.0.0.1:50672

**Comment by sneg55** [comment]
@AndreaLanfranchi Same issue reported by a bunch of miners at our pool 2miners.com can you please check it?

**Comment by AndreaLanfranchi** [comment]
Solution applied in #1429 

You can test [Windows binaries](https://ci.appveyor.com/api/buildjobs/bq20p7130ihya8fg/artifacts/build%2Fethminer-0.16.0.dev2-27%2Bcommit.50613eb0-windows-amd64.zip) from appveyor
