### ISSUE TITLE
 Connection remotely closed by cn.sparkpool.com

### ISSUE THREAD

**Issue by FishSeeker** [ethereum-mining/ethminer#1424]
Hi,
when I run the miner using commond below
```
 .\ethminer.exe -U -P stratum+tcp://0x8f24720480e1F682760BcCA743680AF8CCd5EeAe.my580@cn.sparkpool.com:3333
```
I received some errors like this:
![pic](https://s1.ax1x.com/2018/08/06/PrD6W8.png)

These three sentences are repeated many times.
```
 i 19:15:54 stratum  Connected to cn.sparkpool.com [111.47.226.243:3333]
 i 19:15:54 stratum  Connection remotely closed by cn.sparkpool.com
 i 19:15:54 stratum  Trying 111.47.226.243:3333 ...
```

**Comment by ddobreff** [comment]
Hello,
Fix has been applied recently.
https://github.com/ethereum-mining/ethminer/pull/1421

**Comment by FishSeeker** [comment]
@ddobreff thank u so much!
