### ISSUE TITLE
libcurl error: 2 on windows 10

### ISSUE THREAD

**Issue by fwaris** [ethereum-mining/ethminer#1426]
ethminer seems to be working fine up until it finds a solution and tries to submit it.
 It fails on libcurl error: 2. I believe this is related to initialization of libcurl but I am not sure what to do to fix it.
Here is the screen output
 i 08:06:38 cuda-0   Solution: 0x5dd5d86dd1fa054d
 X 08:06:38 cuda-0   Failed to submit solution.
 X 08:06:38 cuda-0   Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 2

I am running on Windows 10 with NVidia 1080.

**Comment by AndreaLanfranchi** [comment]
@fwaris 
Please read this issue and use stratum mode

https://github.com/ethereum-mining/ethminer/issues/1415

**Comment by stone212** [comment]
@lesjokolat Can you tell me how to mine with stratum?  I tried `-SP` and `-S` etc and I always get

```
The following arguments were not expected: -S -SP -H
```
