### ISSUE TITLE
Noob question. No transactions from nanopool to freewallet address

### ISSUE THREAD

**Issue by fwaris** [ethereum-mining/ethminer#1428]
I used the following command to let ethminer run overnight @ 20MHz hash rate.

ethminer -U -P stratum+tcp://0x751c4c17c15a8e76ee9ede32f78c8bf86f4b5eb8.P100@eth-us-east1.nanopool.org:9999

The address is from my mobile freewallet app but I don't see a balance there.

Can someone please explain what I may be doing wrong.

Thanks

**Comment by AndreaLanfranchi** [comment]
You're only too impatient.
With 20 Mh/s at current level it will take roughly 10 days to get 0,01 Eth and as far as I know nanopool has a payout limit of 0.5 Eth.
You will have to wait 50 days or so to have your first payment.

**Comment by AndreaLanfranchi** [comment]
Sorry for asking but ... which device are you using ?
As it appears you will never get break-even on electricity bills.

**Comment by AndreaLanfranchi** [comment]
Anyway you can check your "progress" here

https://eth.nanopool.org/account/0x751c4c17c15a8e76ee9ede32f78c8bf86f4b5eb8

You have earned 0.00066569 ETH
Still a long way to go ...

**Comment by fwaris** [comment]
thanks! @AndreaLanfranchi .

I am using a mobile version of GTX 1080 with 8 GB ram. I see spikes of 20% GPU usage but its about 5% on average.  Wonder if there are better settings to extract more performance.

**Comment by AndreaLanfranchi** [comment]
Are you on windows or linux ?

**Comment by AndreaLanfranchi** [comment]
Anyway a GTX 1080 can't do that much more.

**Comment by FwtSupport** [comment]
fwaris, have you submitted a support request to Freewallet?
You can always send it on our support portal and we'll do our best to facilitate your transaction.

**Comment by AndreaLanfranchi** [comment]
@FwtSupport there is nothing to facilitate as the user have not reached the payout.

(read from top to bottom)

**Comment by fwaris** [comment]
thanks all. I can see my accumulation in nanopool, however it was a bit of a shock to only see $0.30 for 10 hours of work. I believe this is not economically viable for me even if the hardware is sunk cost
