### ISSUE TITLE
Temp and power usage line

### ISSUE THREAD

**Issue by MethanX** [ethereum-mining/ethminer#143]
Is it possible to add some code line for gpu temperature, fan speed , gpu voltage and mhs for each card separately, it will be very helpfull?

**Comment by orkblutt** [comment]
Not sure this part should be inside ethminer for GPU monitoring. I think ethminer should listen for commands like "stop running on this GPU until the reverse order". It could be nice to have that kond of features for scripting .
To have separate hashrate for each GPU is a good idea I guess. But the actual code is not designed at all for this.... 
It's a lot of work for a very little gain.

**Comment by khaman1** [comment]
Right. Claymore does have these features. But if you set up your mining rig on Ubuntu, you will have to set coolbits on NVIDIA driver in order to read out the properties of the cards. I'm pretty sure we have the same thing to do on Windows so that the code still doesn't have that. By the way, I would like to have a watchdog to restart the code when it fails in running.

**Comment by jimmykl** [comment]
@MethanX There's an existing issue for enhancing the console output here https://github.com/ethereum-mining/ethminer/issues/62 and @khaman1 likewise for the restart/watchdog feature: https://github.com/ethereum-mining/ethminer/issues/60 

If you could add your ideas to those issues and close this one that would be cool. Thanks!

I agree they are both important things to have for a fully featured miner.

**Comment by kmanthezu** [comment]
for linux 
watch n -0.5 nvidia-smi

**Comment by hcbraun** [comment]
for all statistics
nvidia-smi dmon -s pucvmet -o T

**Comment by kmanthezu** [comment]
thanks, that is cool. is there a way to have it show by card? I currently have 2 running in my test system

**Comment by hcbraun** [comment]
default shows all cards. you can use -i option to show individual cards. try nvidia-smi dmon --help for details

**Comment by rainbowhat** [comment]
+1

**Comment by Jacxz** [comment]
Hashrate per card was added with #225
Temperature and Fan will come with PR #319
