### ISSUE TITLE
Where is the file “ethash/ethash.hpp”?

### ISSUE THREAD

**Issue by WingsII** [ethereum-mining/ethminer#1432]
In the CLMiner.cpp, there is #include <ethash/ethash.hpp>, but I can't find this file "ethash.hpp"...
If anyone helps me, I will be very grateful.

**Comment by StefanOberhumer** [comment]
ethash.hpp is "installed" via [hunter](https://hunter.sh/) package `ethash` when you build ethminer.
https://github.com/ethereum-mining/ethminer/blob/458bc512b74fe737a587da8eb6beabcbe6e7a8ea/CMakeLists.txt#L64-L65
Under linux hunter files are placed at `$HOME/.hunter/_Base/...` by default.

**Comment by WingsII** [comment]
@StefanOberhumer   Thank you very much！
