### ISSUE TITLE
NiceHash mode check for duplicate jobs does not consider diff ?

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ethereum-mining/ethminer#1434]
**Possible discarding of legit jobs**
When running against NiceHash I receive logs like these

```
 i 15:19:56 stratum  Extranonce set to 17c9fd (nicehash)
 i 15:19:56 stratum  Job: #cc1b0636… daggerhashimoto.eu.nicehash.com [172.65.195.169:3353]
 i 15:19:56 stratum  Difficulty set to 0.5 (nicehash)
 i 15:19:56 stratum  Job: #cc1b0636… daggerhashimoto.eu.nicehash.com [172.65.195.169:3353]
 X 15:19:56 stratum  Duplicate job #cc1b0636… discarded
 i 15:19:56 cuda-5   Solution: 0x170e1d280a8fc7c5
 X 15:19:56 stratum  Reject reason :2 Job not found.  
```

This is more a question than a bug: is it legimate to discard a job if apparently is duplicate but difficulty has changed since previous push ?

**To Reproduce**
Simply use NiceHash

**Desktop (please complete the following information):**
- Operating System: not relevant
- Hardware not relevant
- Ethminer Version 0.16.0-dev2

@jean-m-cyr

**Comment by AndreaLanfranchi** [comment]
I'm using nicehash directly. 
So they're violating their own specs ?

**Comment by AndreaLanfranchi** [comment]
As far I understand from their specs the word "NEXT" should be interpreted as the "next" job coming from a subsequent mining.notify message.
This does not imply the job has to be "different"

My humble opinion.

**Comment by jean-m-cyr** [comment]
If you consider sending the same job twice a violation, then yes.

Remember, we added the duplicate detection because Ethermine occasionally sends the same job twice which could cause us to send the same solution twice and the second being rejected.

Same with nicehash. Supose that we've found a solution for job A, then job A is resubmitted with a different diff, we would possibly find the same solution and be rejected.

The fix for this would be to detect duplicates but not drop them. Instead we flag the as dups, and not reset the startnonce on the duplicate job.

Want me to look at this?

**Comment by AndreaLanfranchi** [comment]
> Want me to look at this?

Would be nice.

Also I cannot understand what do we do with the new difficulty value

```
        else if (_method == "mining.set_difficulty" &&
                 m_conn->StratumMode() == EthStratumClient::ETHEREUMSTRATUM)
        {
            jPrm = responseObject.get("params", Json::Value::null);
            if (jPrm.isArray())
            {
                double nextWorkDifficulty = jPrm.get((Json::Value::ArrayIndex)0, 1).asDouble();
                if (nextWorkDifficulty <= 0.0001)
                    nextWorkDifficulty = 0.0001;
                diffToTarget((uint32_t*)m_nextWorkBoundary.data(), nextWorkDifficulty);
                cnote << "Difficulty set to " EthWhite << nextWorkDifficulty
                      << EthReset " (nicehash)";
                if (m_onWorkReceived && (m_current.epoch != -1))
                {
                    m_onWorkReceived(m_current, false);
                }
            }
        }
```

Apparently we do not use it anywhere nor we store it.
So what's the point of resubmitting the same job with flag for dup detectionset to off ?

**Comment by jean-m-cyr** [comment]
Actually we do store it in m_nextWorkBoundary, which is then passed to the kernels with each job.

**Comment by AndreaLanfranchi** [comment]
> Actually we do store it in m_nextWorkBoundary, which is then passed to the kernels with each job.

Ok but then I believe there is a problem on our side.

Actually we 
1. receive mining.set_difficulty and update m_nextWorkBoundaryData
2. resubmit the very same current work package (without any modification) with dup check to false
3. this causes m_headers to have for sure 2 identical headers and farm will not switch (as it's the same job)
4. then next job arrives with the same header but, due to point 1 will have a different boundary but we discard it as it's alredy presented twice in m_headers.

I'm puzzled.

**Comment by jean-m-cyr** [comment]
You are not confused... you have found a bug! We should not be call WorkReceived on diff or extranonce updates. I was wrong in thinking nicehash was resending the job. It's our own damned fault for creating the apparent duplicate.

**Comment by AndreaLanfranchi** [comment]
Ok then I believe we should also amend this in Farm.h

```
	void setWork(WorkPackage const& _wp)
	{
		// Collect hashrate before miner reset their work
		collectHashRate();

		// Set work to each miner
		Guard l(x_minerWork);
		if (_wp.header == m_work.header && _wp.startNonce == m_work.startNonce)
			return;
		m_work = _wp;
		for (auto const& m: m_miners)
			m->setWork(m_work);
	}

```

including boundary in the comparison test

**Comment by jean-m-cyr** [comment]
That won't be necessary since we'll no longer call setWork incorrectly on nicehash diff changes.

**Comment by AndreaLanfranchi** [comment]
But I believe this will bring us in the very same situation.
On second push of the same job after diff change the boundary changes but setWork won't pass through as we check equality only on header and startNonce

But maybe I am missing something ...

**Comment by jean-m-cyr** [comment]
We won't do the second push. That is the bug! PR #1435
