### ISSUE TITLE
Got invalid Json message :* Line 1, Column 19   Missing ':' after object member name

### ISSUE THREAD

**Issue by RUminingTwo** [ethereum-mining/ethminer#1436]
I had just noticed this error below today, after setting up, and getting the V15 to work.

```
==============================
Got invalid Json message :* Line 1, Column 19
  Missing ':' after object member name
==============================

```

It is mining, properly, but just noticed this error in the console.

I am now mining on Etherminer.Org, successfully, and reporting accurate MH rate too !

**Comment by lesjokolat** [comment]
@jean-m-cyr 

I think this once can be closed as well.

**Comment by jean-m-cyr** [comment]
closing
