### ISSUE TITLE
Spurious Teminating message on startup

### ISSUE THREAD

**Issue by jean-m-cyr** [ethereum-mining/ethminer#1438]
It doesn't happen every time but...

 m 20:00:12 ethminer ethminer 0.16.0.dev2-30+commit.251689f7.dirty
 m 20:00:12 ethminer Build: linux/release
cu 20:00:12 ethminer Using grid size: 8,192, block size: 64
 i 20:00:13 ethminer Configured pool us1-etc.ethermine.org:5555
 i 20:00:13 main     Selected pool us1-etc.ethermine.org:5555
 i 20:00:13 stratum  Stratum mode detected : ETHPROXY Compatible
 i 20:00:13 stratum  Logged in !
 i 20:00:13 stratum  Established connection with us1-etc.ethermine.org:5555 at  [54.177.207.188:5555]
 i 20:00:13 stratum  Spinning up miners...
 i 20:00:13 cuda-0   No work. Pause for 3 s.
 i 20:00:13 cuda-1   No work. Pause for 3 s.
 i 20:00:13 cuda-2   No work. Pause for 3 s.
 i 20:00:13 cuda-3   No work. Pause for 3 s.
 i 20:00:14 stratum  Job: #6dcc7896… us1-etc.ethermine.org [54.177.207.188:5555]
 i 20:00:14 stratum  Pool difficulty: 4.00K megahash
 i 20:00:14 stratum  New epoch 211
 **i 20:00:14 ethminer Terminated !**
 i 20:00:16 cuda-0   Initialising miner 0

Miner runs normally...

**Comment by AndreaLanfranchi** [comment]
Hmmm ... something very bad here.

"Terminated !" is only written by doMiner() in main.cpp after exiting the workloop.

```
		// Start PoolManager
		mgr.start();

		// Run CLI in loop
		while (g_running && mgr.isRunning()) {

			// Wait at the beginning of the loop to give some time
			// services to start properly. Otherwise we get a "not-connected"
			// message immediately
			this_thread::sleep_for(chrono::seconds(m_displayInterval));

			if (mgr.isConnected()) {
				auto mp = f.miningProgress(m_show_hwmonitors, m_show_power);
				minelog << mp << ' ' << f.getSolutionStats() << ' ' << f.farmLaunchedFormatted();

#if ETH_DBUS
				dbusint.send(toString(mp).c_str());
#endif
			}
			else {
				minelog << "not-connected";
			}

		}

#if API_CORE

		// Stop Api server
		api.stop();

#endif

		mgr.stop();
		stop_io_service();

		cnote << "Terminated !";
		exit(0);
```

That message should occur only after mgr has done his job. And should also exit. 
Why it continues to grind ?

**Comment by AndreaLanfranchi** [comment]
Does **not** happen on

```
ethminer 0.16.0.dev2-27+commit.919c8e08
Build: linux/release/gnu

```

**Comment by jean-m-cyr** [comment]
Haven't seen this one lately... hmmm worisome!

We've had a couple of inexplicable incidents lately:
- This one.
- Bizarre localized number formatting where the character 'a' replaced the expected ',' thousands separator.

My guess would be trampled memory of some kind, and I don't trust the cpp-netlib/uri component since I've demonstrated it has a broken assignment operator in the version we are using. Wonder what else it's doing wrong?

**Comment by AndreaLanfranchi** [comment]
Did you find a relationship with cpp-uri ?


Sent from mobile. Apologies for brevity and typos.

In data 18 agosto 2018 12:53:15 Jean Cyr <notifications@github.com> ha scritto:

**Comment by jean-m-cyr** [comment]
No, but I haven't seen this in quite a while and I've been doing a LOT of shutdowns and restarts.
