### ISSUE TITLE
Thank you. Faster speeds and Exit func

### ISSUE THREAD

**Issue by R00dNet** [ethereum-mining/ethminer#1442]
thank you for your work in this latest version of ethminer.

faster speeds. just shy of 1mhs boost here and ethminer is now exiting once lost connection with a pool that deauthorizes users connection. a few more accepted solutions per hour too.

wonderful work, really. 

regards

R

**Comment by ianusy2k2** [comment]
what version are you using and OS

**Comment by ianusy2k2** [comment]
Any chance we can share our working start.bat file on specific versions....

**Comment by R00dNet** [comment]
sure:

ethminer -U -P stratum2+tcp://worker.username:x@europe.ethash-hub.miningpoolhub.com:12020 -P exit --farm-retries 1 --farm-recheck 100

here are my oc/afterburner settings gtx 1060 6gb:
core 0
mem 490
pwr 70%
fan 80%

**Comment by AndreaLanfranchi** [comment]
With -P Stratum... The additional argument farm-recheck is not needed. It 
only works for http mode (getwork) which is highly inefficient.


Sent from mobile. Apologies for brevity and typos.

In data 18 agosto 2018 11:03:01 R00dNet <notifications@github.com> ha scritto:

**Comment by lesjokolat** [comment]
ethminer -U -P stratum+tcp://worker.username:x@europe.ethash-hub.miningpoolhub.com:20535 exit --farm-retries 1 -v

tweaked the start up also may not have had right port.( based on their settings help page) -v helps troubleshoot but eventualy can be removed

**Comment by R00dNet** [comment]
@AndreaLanfranchi cool. thanks for tip.

@lesjokolat ports correct > https://miningpoolhub.com/?page=gettingstarted 
scroll to bottom

**Comment by lesjokolat** [comment]
multi algo ok, once you put port back in can you paste log output that shows errors?

**Comment by ianusy2k2** [comment]
from 0.15.0... i tried the latest release on one of my rigs...
0.16.0 dev3 
GPU 10 x 1070
NVIDIA INSPECTOR for OC 

i tried using the watchdog from github also
commandline is same from 0.15.0
it had some issues
will try running without the watchdog.... but it recorded some data doewn there

rem Skip RunEthMinerCommand section at start
goto PreStart

rem ========== Run EthMiner Command ==========

:RunEthMinerCommand

rem ==================== Your Code Starts Here ====================
rem ==================== Your Code Starts Here ====================
rem ==================== Your Code Starts Here ====================

ethminer.exe --HWMON 1 --report-hashrate --display-interval 5 --exit --api-port -3333 -U -P stratum1+tcp://0x904923a8de488546da8e3c375c07003884c3f28f.BJPJ003@tw.sparkpool.com:3333 -P stratum1+tcp://0x904923a8de488546da8e3c375c07003884c3f28f.BJPJ003@asia.sparkpool.com:3333  
--minername BJPJ --accesstoken 10e5e726ed4f5a7856a8d001b1af1fe2 --version --verbosity 8 --farm-retries 3 --work-timeout 180 --response-timeout 2 --syslog --list-devices --noeval --dag-load-mode 2 --dag-single-dev 0  
--benchmark-warmup 15 --benchmark-trial 3 --benchmark-trials 5 --benchmark  6132223 --simulation 6132226 --tstop 80 --tstart 40
        
rem ==================== Your Code Ends Here ====================
rem ==================== Your Code Ends Here ====================
rem ==================== Your Code Ends Here ====================

exit /b

rem ========== PreStart ==========

:PreStart

rem Don't echo to standard output
@echo off
rem Set EthMiner Variables
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
setx CUDA_DEVICE_ORDER PCI_BUS_ID
rem set NO_COLOR=Yes
rem Make script variables local
setlocal
rem Set version info
set V=1.9.6
rem Switch to the batch file's directory
cd /d %~dp0
rem Set codepage
chcp 437 >nul
rem Set title
title ETHminer WatchDog Version %V% by DeadManWalking

rem ========== Start ==========

cls
echo ###############################################################################
echo.
echo   ETHminerWatchDogDmW Version %V%
echo.
echo   AUTHOR: DeadManWalking  (DeadManWalkingTO-GitHub)
echo.
echo ###############################################################################
echo.
echo ETHminerWatchDogDmW
echo 1. Run ethminer.
echo 2. Restart ethminer up to 10 times.
echo 3. Reboot the system.
echo.
echo Additional:
echo - AutoFix #385 issue of Ethminer
echo - AutoFix #189 issue of Ethminer
echo - Log file RunTimes.log
echo - Auto Turn off the Error Dialog
echo.

rem ========== Initializing ==========

:Initializing
rem set loop to zero
set /A loopnum=0
set FileOut=RunTimes.log
echo ETHminerWatchDogDmW Version %V% >> %FileOut%
reg add "HKCU\SOFTWARE\Microsoft\Windows\Windows Error Reporting" /v "DontShowUI" /t REG_DWORD /d 1 /f > nul 2>&1

rem ========== Run Program ==========

:runProgram

rem ========== Calc ==========

rem Increment loop by one
set /A loopnum=loopnum+1

rem Calculate Date & Time
:DateTime
rem Check if WMIC is available
WMIC.EXE Alias /? >nul 2>&1 || goto wmicError
rem Use WMIC to retrieve date and time
for /F "skip=1 tokens=1-6" %%G in ('WMIC Path Win32_LocalTime Get Day^,Hour^,Minute^,Month^,Second^,Year /Format:table') do (
   if "%%~L"=="" goto wmicDone
      set _yyyy=%%L
      set _mm=00%%J
      set _dd=00%%G
      set _hour=00%%H
      set _minute=00%%I
)
:wmicDone

rem Pad digits with leading zeros
      set _mm=%_mm:~-2%
      set _dd=%_dd:~-2%
      set _hour=%_hour:~-2%
      set _minute=%_minute:~-2%

rem Date/time in ISO 8601 format:
set pISOdate=%_yyyy%-%_mm%-%_dd% %_hour%:%_minute%

goto DateTimeOK

:wmicError
for /f "tokens=2-4 delims=/ " %%a in ('date /t') do (set pdate=%%c-%%a-%%b)
for /f "tokens=1-2 delims=/:" %%a in ('time /t') do (set ptime=%%a:%%b)
set pISOdate=%pdate% %ptime%

:DateTimeOK

rem ========== Output ==========

rem ========== Screen Output ==========

echo.
echo ===============================================================================
echo %pISOdate%
echo ETHminerWatchDogDmW has run %loopnum% times.
echo ===============================================================================
echo.

rem ========== File Output ==========

echo %pISOdate% ETHminerWatchDogDmW has run %loopnum% times.>>%FileOut%

rem ========== Execution Code ==========

call :RunEthMinerCommand

rem Wait 5s
timeout /T 5 /NOBREAK>NUL

rem Check 10 loops
if %loopnum% gtr 9 goto ErrorHandling

rem Loop
goto runProgram

rem ========== Error Handling ==========

:ErrorHandling

rem ========== Error Screen Output ==========

echo.
echo ===============================================================================
echo %pISOdate%
echo ETHminerWatchDogDmW has run %loopnum% times.
echo System restart required.
echo.
echo.
echo.
echo Rebooting now (%pISOdate%).
echo ###############################################################################
echo.

rem ========== Error File Output ==========

echo %pISOdate% ETHminerWatchDogDmW has run %loopnum% times.>>%FileOut%
echo System restart required. Rebooting now (%pISOdate%).>>%FileOut%
echo. >>%FileOut%
echo. >>%FileOut%

rem ========== System Reboot ==========

shutdown -r -f -t 0

rem ========== End ==========

endlocal

rem ========== EoF ==========

**Comment by R00dNet** [comment]
@lesjokolat i have no errors. this is a thank you post. if you have any errors or problems you should post a thread.

@ianusy2k2 i think you should create your own thread for all of that ;)

**Comment by lesjokolat** [comment]
ahh ok no im good glad all is well!
