### ISSUE TITLE
URI copy constructor fails!!!

### ISSUE THREAD

**Issue by jean-m-cyr** [ethereum-mining/ethminer#1445]
@chfast This isn't really an ethminer bug, but I thought you could help?

Presently, we retrieve netlib::uri via https://github.com/hunter-packages/uri.git ... I think.

There's a bug in the uri copy constructor which is causing us trouble

```
network::uri u("http://google.com");
cerr << u.host() << '\n';
u = network::uri("http://microsoft.com");
cerr << u.host() << '\n';
```

yields:

```
google.com
microsoft.

```

Apparently this issue has been fixed in https://github.com/cpp-netlib/uri.git master. Can you merge it back into the hunter packages fork?

**Comment by piotr-dobrogost** [comment]
For completeness, the issue noticed and raised by @jean-m-cyr – https://github.com/cpp-netlib/uri/issues/114

**Comment by chfast** [comment]
I reported the problem to Hunter https://github.com/ruslo/hunter/issues/1519, but this is complicated because Hunter maintains a fork of cpp-netlib that has diverged quite a lot.

**Comment by jean-m-cyr** [comment]
Yeah. I reported to ruslo as well. I've replaced the parser with an in-house version (coded specifically for our needs)

**Comment by jean-m-cyr** [comment]
We no longer use cpp-netlib/uri
