### ISSUE TITLE
illegal instruction in func ethash_cuda_miner::search at line 365

### ISSUE THREAD

**Issue by spyrek10** [ethereum-mining/ethminer#145]
Today I have updated to latest release and encountering  this error: https://scr.hu/GWd9B6

The prerelease 0.11.0rc1 was rock stable.
Windows 7 x64 using only nvidia 1070 and 1060

**Comment by MichaelA2014** [comment]
Welcome to the club :)

**Comment by jimmykl** [comment]
@spyrek10 @MichaelA2014 This has been reported several times. It may be related to overclocking so if you are overclocking please try a more stable overclock and see if that makes a difference.

To make things easier for the devs please close this issue and add your info to the discussion at https://github.com/ethereum-mining/ethminer/issues/72 Thanks!
