### ISSUE TITLE
Proper commands for ethermine.org

### ISSUE THREAD

**Issue by Olegatorius** [ethereum-mining/ethminer#1450]
I`ve tried to move to the new version of ethminer after a long absence
and found that old command "string" will not work anymore - due changes and the ommitings in the new version(s)

The old string was something like:

ethminer.exe --farm-recheck 200  -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0xdwallet.rigname

Could you please tell me the new commands string or point me to the direction where I can read about it.

(rig is win 10 - 8*1066 cards  / Nvidia.)

Thank you in advance.

**Comment by e2dy** [comment]
Hi you can find all command with -help argument or in the exemple template in home page #readme.md

**Comment by jean-m-cyr** [comment]
Question answered. Closing.
