### ISSUE TITLE
Virus Detected on Windows 10 download of DEV.3 zip

### ISSUE THREAD

**Issue by JohnnyOpcode** [ethereum-mining/ethminer#1454]
Why is the zip download triggering a virus removal?

**Comment by StefanOberhumer** [comment]
>Why is the zip download triggering a virus removal?

Please see #1431 for an answer.


Here you can find a complete scan for our binaries (from virus total): (updated Aug 12 2018 11:00 UTC)
1. [Version 0.16.0.dev3](https://www.virustotal.com/#/file/81b722834eb05e9f1b912120d0e54cb393de12568dac5bc3c2a26e75ede6581b/detection) 11 detections
2. [Version 0.16.0.dev2](https://www.virustotal.com/#/file/797c91961a19193c47f0473c7a80080289adbf941d689a2643eb7077652a0660/detection) 17 detections
3. [Version 0.16.0.dev1](https://www.virustotal.com/#/file/cfa901e1fb481d9905f1436d124c76ea5a72068d0c960e9f9c3b858463d90ae9/detection) 13 detections
4. [Version 0.15](https://www.virustotal.com/#/file/b1cb53b3425856ce1a6a7b0efdd065112e852f658b00cc19cb4613836937b08c/detection) 26 detections

**Comment by alptolga** [comment]
because of donkey's dick. You dick head.
