### ISSUE TITLE
Share counter resets at 999

### ISSUE THREAD

**Issue by lesjokolat** [ethereum-mining/ethminer#1455]
**Describe the bug**
running list the Share counter resets at 999, would expect it to continue in thousands etc

**To Reproduce**
 i 12:04:00 stratum  **Accepted 126 ms. etc.ethertrench.com [213.133.98.94:8009]
 m 12:04:02 main     Speed 148.69 Mh/s gpu0 33.92 56C 30% gpu1 34.64 56C 29% gpu2 34.24 56C 48% gpu3 45.89 55C 53% 162W [A3,999+38:F139] Time: 16:05
 m 12:04:07 main     Speed 148.54 Mh/s gpu0 33.94 56C 30% gpu1 34.45 56C 28% gpu2 34.26 56C 49% gpu3 45.90 56C 53% 162W [A3,999+38:F139] Time: 16:05
 m 12:04:12 main     Speed 148.36 Mh/s gpu0 33.94 56C 30% gpu1 34.45 56C 28% gpu2 34.26 56C 50% gpu3 45.71 56C 53% 163W [A3,999+38:F139] Time: 16:05
 m 12:04:17 main     Speed 148.45 Mh/s gpu0 34.01 56C 30% gpu1 34.46 56C 27% gpu2 34.12 56C 50% gpu3 45.86 55C 53% 162W [A3,999+38:F139] Time: 16:05
 i 12:04:17 cl-2     Solution: 0x05f736c4723d40d4
 i 12:04:17 stratum  **Accepted 127 ms. etc.ethertrench.com [213.133.98.94:8009]
 m 12:04:22 main     Speed 148.61 Mh/s gpu0 34.05 56C 29% gpu1 34.50 56C 27% gpu2 34.33 56C 52% gpu3 45.73 56C 53% 162W [A4,000+38:F139] Time: 16:05
 i 12:04:23 cl-1     Solution: 0x05f735c47e898153
 i 12:04:23 stratum  **Accepted 126 ms. etc.ethertrench.com [213.133.98.94:8009]
 i 12:04:23 stratum  Job: #53e42f72... etc.ethertrench.com [213.133.98.94:8009]
cl12:04:23 cl-0     Switch time: 871 us.
cl 12:04:23 cl-1     Switch time: 799 us.
cl 12:04:23 cl-2     Switch time: 1,027 us.
cl 12:04:23 cl-3     Switch time: 911 us.
 i 12:04:25 stratum  Job: #cb235d60... etc.ethertrench.com [213.133.98.94:8009]
cl 12:04:25 cl-0     Switch time: 807 us.
cl 12:04:25 cl-1     Switch time: 936 us.
cl 12:04:25 cl-2     Switch time: 887 us.
cl 12:04:25 cl-3     Switch time: 798 us.
 m 12:04:27 main     Speed 147.68 Mh/s gpu0 33.81 56C 29% gpu1 34.36 56C 27% gpu2 34.09 56C 53% gpu3 45.42 55C 53% 162W [A4,001+38:F139] Time: 16:06
 i 12:04:31 stratum  Job: #e365cb74... etc.ethertrench.com [213.133.98.94:8009]
cl 12:04:31 cl-0     Switch time: 890 us.
cl 12:04:31 cl-1     Switch time: 821 us.
cl 12:04:31 cl-2     Switch time: 872 us.
cl 12:04:31 cl-3     Switch time: 747 us.
 i 12:04:31 stratum  Job: #ad541252... etc.ethertrench.com [213.133.98.94:8009]
cl 12:04:31 cl-0     Switch time: 848 us.
cl 12:04:31 cl-1     Switch time: 999 us.
cl 12:04:31 cl-2     Switch time: 984 us.
cl 12:04:31 cl-3     Switch time: 854 us.
 m 12:04:32 main     Speed 148.43 Mh/s gpu0 33.98 56C 28% gpu1 34.55 56C 27% gpu2 34.31 56C 53% gpu3 45.60 56C 53% 168W [A4,001+38:F139] Time: 16:06
 i 12:04:34 cl-3     Solution: 0x05f737c44af20bd8
 i 12:04:34 stratum  **Accepted 130 ms. etc.ethertrench.com [213.133.98.94:8009]
 m 12:04:37 main     Speed 148.20 Mh/s gpu0 33.99 56C 27% gpu1 34.37 56C 27% gpu2 34.33 56C 53% gpu3 45.50 56C 53% 167W [A4,002+38:F139] Time: 16:06
 i 12:04:40 stratum  Job: #fa00cad8... etc.ethertrench.com [213.133.98.94:8009]
cl 12:04:40 cl-0     Switch time: 787 us.
cl 12:04:40 cl-2     Switch time: 817 us.
cl 12:04:40 cl-3     Switch time: 809 us.

**Desktop (please complete the following information):**
- Operating System: [Windows 10]
- Hardware [vega 64, fury x]
- Ethminer Version [16 dev3]

**Additional context**

**Comment by AndreaLanfranchi** [comment]
It does not reset. Comma is thousands separator. 3,999 => 4,000


Sent from mobile. Apologies for brevity and typos.

In data 12 agosto 2018 18:14:28 lesjokolat <notifications@github.com> ha 
scritto:

**Comment by lesjokolat** [comment]
ahhh apologies ok closing this
