### ISSUE TITLE
ethminer exits dirty on reconnect after a response timeout

### ISSUE THREAD

**Issue by mrAbS777** [ethereum-mining/ethminer#1457]
Couldn't get up after network error. Log on verbosity 3:

 ```
m 08:22:35 ethminer Speed 183.88 Mh/s gpu0 30.46 48C 50% 88W gpu1 29.95 47C 45% 88W gpu2 30.13 47C 45% 90W gpu3 30.61 48C 50% 87W gpu4 30.61 48C 50% 89W gpu5 32.13 50C 60% 99W [A152+4] Time: 01:01
 i 08:22:35 cl-4     Solution: 0xdbaf9892ae9f0951
 X 08:22:37 stratum  No response received in 2 seconds.
 i 08:22:37 main     Disconnected from eu2.ethermine.org [35.234.90.95:4444]
 i 08:22:38 main     Selected pool eu2.ethermine.org:4444
 i 08:22:39 cl-2     Solution 0xdbaf9692b3018380 wasted. Waiting for connection ...
 i 08:22:39 main     Selected pool eu2.ethermine.org:4444
 m 08:22:40 ethminer not-connected
 i 08:22:40 main     Shutting down miners...
 i 08:22:40 cl-4     Solution 0xdbaf9892b783e5ea wasted. Waiting for connection ...
 i 08:22:44 main     Retrying in 3...
 i 08:22:44 stratum  Stratum mode detected : ETHPROXY Compatible
 i 08:22:44 stratum  Logged in !
 i 08:22:44 stratum  Established connection with eu1.ethermine.org:4444 at  [35.198.136.200:4444]
 i 08:22:44 stratum  Spinning up miners...
cl 08:22:44 cl-0     No work. Pause for 3 s.
cl 08:22:44 cl-1     No work. Pause for 3 s.
cl 08:22:44 cl-2     No work. Pause for 3 s.
cl 08:22:44 cl-3     No work. Pause for 3 s.
cl 08:22:44 cl-4     No work. Pause for 3 s.
cl 08:22:44 cl-5     No work. Pause for 3 s.
```

- Ubuntu 18.04, amdgpu from kernel 4.15.0-30-generic
- 6хRX580 
- ethminer 0.16.0.dev3-4+commit.2eaff643.dirty
- cmdline: /usr/local/bin/ethminer --HWMON 1 -R -G --tstop 67 --tstart 40 -v 3 --opencl-devices 0 1 2 3 4 5 -G -P stratum+tcp://0x*******.SERVER1@eu1.ethermine.org:4444 -P stratum+tcp://0x*******.SERVER1@eu2.ethermine.org:4444

**Comment by lesjokolat** [comment]
I tweaked your command line.

cmdline: /usr/local/bin/ethminer --HWMON 1 -R -G --tstop 67 --tstart 40 -v 3 --opencl-devices 0 1 2 3 4 5 -P stratum+tcp://0x*******.SERVER1@eu1.ethermine.org:4444 -P stratum+tcp://0x*******.SERVER1@us2.ethermine.org:4444


You had an extra -G in it as well there is no eu2.ethermine.org so i added us2.ethermine.org.

**Comment by mrAbS777** [comment]
Thank you for pointing me out. I've tried to change cmdline and restart my router for testing network. No changes. The problem persists.

**Comment by StefanOberhumer** [comment]
> Also change the 2 instances of stratum+tcp to stratum1+tcp

If version 0.16-dev3 is used this is not needed anymore as ethminer does autodetection
(Maybe startum1 and startum2 will be removed in future releases)

**Comment by mrAbS777** [comment]
```
m 02:54:47 ethminer Speed 186.95 Mh/s gpu0 29.98 44C 40% 86W gpu1 31.70 47C 45% 97W gpu2 29.86 46C 40% 90W gpu3 31.98 50C 57% 101W gpu4 31.73 47C 41% 96W gpu5 31.70 47C 45% 100W [A860+13:F8] Time: 05:50
 i 02:54:49 cl-0     Solution: 0xc6369cce95b7ad53
 i 02:54:49 cl-0     {
        "id" : 4,
        "method" : "eth_submitWork",
        "params" :
        [
                "0xc6369cce95b7ad53",
                "0x7511eedbdbb3dc09f2b7c554f7012afc413efed3eb15d672d6fa41e938117578",
                "0xdf4588d645fd697d2d1a07e8e23b74746b114765e62d89feca50d8331bbf8e43"
        ],
        "worker" : "NITRO"
}
 X 02:54:51 stratum  No response received in 2 seconds.
 i 02:54:51 stratum  Socket disconnected from  [35.198.179.39:4444]
 i 02:54:51 main     Disconnected from eu1.ethermine.org [35.198.179.39:4444]
 i 02:54:51 main     Shutting down miners...
 m 02:54:52 ethminer not-connected
 i 02:54:55 main     Retrying in 3...
 i 02:54:56 main     Retrying in 2...
 m 02:54:57 ethminer not-connected
 i 02:54:57 main     Retrying in 1...
 i 02:54:58 main     Selected pool eu2.ethermine.org:4444
 i 02:54:58 stratum  Trying 35.234.84.74:4444 ...
 i 02:54:58 stratum  Socket connected to  [35.234.84.74:4444]
 i 02:54:58 stratum  {
        "id" : 1,
        "method" : "mining.subscribe",
        "params" :
        [
                "ethminer-0.16.0.dev3-4+commit.2eaff643.dirty",
                "EthereumStratum/1.0.0"
        ]
}
 i 02:54:58 stratum  {
        "id" : 1,
        "jsonrpc" : "2.0",
        "result" : true
}
 i 02:54:58 stratum  Socket disconnected from  [35.234.84.74:4444]
 i 02:54:58 stratum  Trying 35.234.84.74:4444 ...
 i 02:54:58 stratum  Socket connected to  [35.234.84.74:4444]
 i 02:54:58 stratum  {
        "id" : 1,
        "method" : "eth_submitLogin",
        "params" :
        [
                "0x24Aa5d842B8F653B201aD4CA0E649a0f7c68aC9D"
        ],
        "worker" : "NITRO"
}
 i 02:54:58 stratum  {
        "id" : 1,
        "jsonrpc" : "2.0",
        "result" : true
}
 i 02:54:58 stratum  Stratum mode detected : ETHPROXY Compatible
 i 02:54:58 stratum  Logged in !
 i 02:54:58 stratum  Established connection with eu2.ethermine.org:4444 at  [35.234.84.74:4444]
 i 02:54:58 stratum  Spinning up miners...
cl 02:54:58 cl-0     No work. Pause for 3 s.
cl 02:54:58 cl-1     No work. Pause for 3 s.
cl 02:54:58 cl-2     No work. Pause for 3 s.
cl 02:54:58 cl-3     No work. Pause for 3 s.
cl 02:54:58 cl-4     No work. Pause for 3 s.
cl 02:54:58 cl-5     No work. Pause for 3 s.
 i 02:54:58 stratum  {
        "id" : 5,
        "method" : "eth_getWork",
        "params" : []
}

```

**Comment by StefanOberhumer** [comment]
As there is **no official** server **eu2.ethermine.org** (even if something responds) you have to choose another server ! 
For a **list of valid servers**: See https://ethermine.org/ - "How to Connect"

**Comment by lesjokolat** [comment]
It seems startup is still pointing to the wrong pool. If you have changed the startup from the example I sent you there should be no request for eu2.ethermine.org:4444
Can you verify how do you start miner BAT file or command line?If you are using a bat file check to remove the wrong eu2 address.If you are not using the bat file but are using a command line make sure the eu2 is not in the command line.Is there any other startup script that could be starting the miner with wrong EU2 address?


    On Tuesday, August 14, 2018, 4:26:08 AM EDT, mrAbS777 <notifications@github.com> wrote:  
 
 m 02:54:47 ethminer Speed 186.95 Mh/s gpu0 29.98 44C 40% 86W gpu1 31.70 47C 45% 97W gpu2 29.86 46C 40% 90W gpu3 31.98 50C 57% 101W gpu4 31.73 47C 41% 96W gpu5 31.70 47C 45% 100W [A860+13:F8] Time: 05:50
 i 02:54:49 cl-0     Solution: 0xc6369cce95b7ad53
 i 02:54:49 cl-0     {
        "id" : 4,
        "method" : "eth_submitWork",
        "params" :
        [
                "0xc6369cce95b7ad53",
                "0x7511eedbdbb3dc09f2b7c554f7012afc413efed3eb15d672d6fa41e938117578",
                "0xdf4588d645fd697d2d1a07e8e23b74746b114765e62d89feca50d8331bbf8e43"
        ],
        "worker" : "NITRO"
}
 X 02:54:51 stratum  No response received in 2 seconds.
 i 02:54:51 stratum  Socket disconnected from  [35.198.179.39:4444]
 i 02:54:51 main     Disconnected from eu1.ethermine.org [35.198.179.39:4444]
 i 02:54:51 main     Shutting down miners...
 m 02:54:52 ethminer not-connected
 i 02:54:55 main     Retrying in 3...
 i 02:54:56 main     Retrying in 2...
 m 02:54:57 ethminer not-connected
 i 02:54:57 main     Retrying in 1...
 i 02:54:58 main     Selected pool eu2.ethermine.org:4444
 i 02:54:58 stratum  Trying 35.234.84.74:4444 ...
 i 02:54:58 stratum  Socket connected to  [35.234.84.74:4444]
 i 02:54:58 stratum  {
        "id" : 1,
        "method" : "mining.subscribe",
        "params" :
        [
                "ethminer-0.16.0.dev3-4+commit.2eaff643.dirty",
                "EthereumStratum/1.0.0"
        ]
}
 i 02:54:58 stratum  {
        "id" : 1,
        "jsonrpc" : "2.0",
        "result" : true
}
 i 02:54:58 stratum  Socket disconnected from  [35.234.84.74:4444]
 i 02:54:58 stratum  Trying 35.234.84.74:4444 ...
 i 02:54:58 stratum  Socket connected to  [35.234.84.74:4444]
 i 02:54:58 stratum  {
        "id" : 1,
        "method" : "eth_submitLogin",
        "params" :
        [
                "0x24Aa5d842B8F653B201aD4CA0E649a0f7c68aC9D"
        ],
        "worker" : "NITRO"
}
 i 02:54:58 stratum  {
        "id" : 1,
        "jsonrpc" : "2.0",
        "result" : true
}
 i 02:54:58 stratum  Stratum mode detected : ETHPROXY Compatible
 i 02:54:58 stratum  Logged in !
 i 02:54:58 stratum  Established connection with eu2.ethermine.org:4444 at  [35.234.84.74:4444]
 i 02:54:58 stratum  Spinning up miners...
cl 02:54:58 cl-0     No work. Pause for 3 s.
cl 02:54:58 cl-1     No work. Pause for 3 s.
cl 02:54:58 cl-2     No work. Pause for 3 s.
cl 02:54:58 cl-3     No work. Pause for 3 s.
cl 02:54:58 cl-4     No work. Pause for 3 s.
cl 02:54:58 cl-5     No work. Pause for 3 s.
 i 02:54:58 stratum  {
        "id" : 5,
        "method" : "eth_getWork",
        "params" : []
}

**Comment by mrAbS777** [comment]
Soorry, were away from machines. Here new log.  eu1 + asia 1 + verbosity 9.

```
m 18:56:31 ethminer Speed 192.93 Mh/s gpu0 32.29 51C 61% 98W gpu1 32.27 57C 85% 101W gpu2 32.29 51C 61% 99W gpu3 32.12 53C 70% 102W gpu4 31.68 48C 45% 95W gpu5 32.29 54C 74% 104W [A903+6] Time: 05:21
 m 18:56:36 ethminer Speed 193.69 Mh/s gpu0 32.29 51C 61% 99W gpu1 32.27 57C 85% 102W gpu2 32.29 51C 61% 100W gpu3 32.50 53C 70% 102W gpu4 32.06 47C 45% 95W gpu5 32.29 54C 74% 102W [A903+6] Time: 05:21
 i 18:56:38 cl-4     Solution: 0x23bfa59e4b5984bd
 i 18:56:38 cl-4     {
        "id" : 4,
        "method" : "eth_submitWork",
        "params" :
        [
                "0x23bfa59e4b5984bd",
                "0xc5283a0b4328dc5c5504e9fadffc52c5cd420425ef56163fe90eb0848698fa89",
                "0xd0b25b8196224bc8824b186c3ce2e8e878186399160d5d409408e07c6b7da827"
        ],
        "worker" : "DEVIL"
}
 X 18:56:40 stratum  No response received in 2 seconds.
 i 18:56:40 stratum  Socket disconnected from  [35.198.191.28:4444]
 i 18:56:40 main     Disconnected from eu1.ethermine.org [35.198.191.28:4444]
 i 18:56:40 main     Shutting down miners...
 m 18:56:41 ethminer not-connected
 i 18:56:42 cl-4     Solution 0x23bfa59e53a88294 wasted. Waiting for connection ...
 i 18:56:45 main     Retrying in 3...
 i 18:56:46 main     Retrying in 2...
 m 18:56:46 ethminer not-connected
 i 18:56:47 main     Retrying in 1...
 i 18:56:48 main     Selected pool asia1.ethermine.org:4444
 i 18:56:48 stratum  Trying 35.197.147.14:4444 ...
 i 18:56:48 stratum  Socket connected to  [35.197.147.14:4444]
 i 18:56:48 stratum  {
        "id" : 1,
        "method" : "mining.subscribe",
        "params" :
        [
                "ethminer-0.16.0.dev3-4+commit.2eaff643.dirty",
                "EthereumStratum/1.0.0"
        ]
}
 i 18:56:49 stratum  {
        "id" : 1,
        "jsonrpc" : "2.0",
        "result" : true
}
 i 18:56:49 stratum  Socket disconnected from  [35.197.147.14:4444]
 i 18:56:49 stratum  Trying 35.197.147.14:4444 ...
 i 18:56:49 stratum  Socket connected to  [35.197.147.14:4444]
 i 18:56:49 stratum  {
        "id" : 1,
        "method" : "eth_submitLogin",
        "params" :
        [
                "0x24Aa5d842B8F653B201aD4CA0E649a0f7c68aC9D"
        ],
        "worker" : "DEVIL"
}
 i 18:56:49 stratum  {
        "id" : 1,
        "jsonrpc" : "2.0",
        "result" : true
}
 i 18:56:49 stratum  Stratum mode detected : ETHPROXY Compatible
 i 18:56:49 stratum  Logged in !
 i 18:56:49 stratum  Established connection with asia1.ethermine.org:4444 at  [35.197.147.14:4444]
 i 18:56:49 stratum  Spinning up miners...
cl 18:56:49 cl-0     No work. Pause for 3 s.
cl 18:56:49 cl-1     No work. Pause for 3 s.
cl 18:56:49 cl-2     No work. Pause for 3 s.
cl 18:56:49 cl-3     No work. Pause for 3 s.
cl 18:56:49 cl-4     No work. Pause for 3 s.
cl 18:56:49 cl-5     No work. Pause for 3 s.
 i 18:56:49 stratum  {
        "id" : 5,
        "method" : "eth_getWork",
        "params" : []
}
``
```

**Comment by lesjokolat** [comment]
Can you try and connect to this pool i use it and i know it works. Might just be pool you re connecting to needs a reboot and reset. eth.ethertrench.com

**Comment by AndreaLanfranchi** [comment]
@mrAbS777 

there is apparently nothing wrong with the log you report.
Only issue you do not leave enough time to see what happens next

 ```
i 18:56:49 stratum  Stratum mode detected : ETHPROXY Compatible
 i 18:56:49 stratum  Logged in !
 i 18:56:49 stratum  Established connection with asia1.ethermine.org:4444 at  [35.197.147.14:4444]
 i 18:56:49 stratum  Spinning up miners...
cl 18:56:49 cl-0     No work. Pause for 3 s.
cl 18:56:49 cl-1     No work. Pause for 3 s.
cl 18:56:49 cl-2     No work. Pause for 3 s.
cl 18:56:49 cl-3     No work. Pause for 3 s.
cl 18:56:49 cl-4     No work. Pause for 3 s.
cl 18:56:49 cl-5     No work. Pause for 3 s.
 i 18:56:49 stratum  {
        "id" : 5,
        "method" : "eth_getWork",
        "params" : []
}
```

Up to this point its all perfectly normal.
After method "eth_getWork" you should begin receive mining jobs. Problem is you interrupt too early.

Leave some more time and report.

**Comment by mrAbS777** [comment]
@AndreaLanfranchiAfter, after this log , process is closed,  so no ethminer in 'ps aux' and no more logs, of course. 

@smurfy, thank you for --response-timeout. I'l try to set it to 5 sec, but stiil we have some problem in code, cause it shouldn't exit in this case

**Comment by AndreaLanfranchi** [comment]
@mrAbS777 ... this is unexpected.
We have performed an extensive set of tests to ensure reconnect after a response timeout works properly. And we got a lot of feed-backs confirming is working properly.

If this is the bahavior we have to change the title of the issue to "ethminer exits on reconnect" and investigate further. However, if I had to guess, this might be related to a memory error.

**Comment by AndreaLanfranchi** [comment]
Nevertheless I must underline in your opening post you report

`ethminer 0.16.0.dev3-4+commit.2eaff643.dirty`

That "dirty" tells me your code is not in sync with the master code. Maybe you have added/changed something locally ?

**Comment by AndreaLanfranchi** [comment]
No feed back.
Feel free to reopen if issue persists with any current version (not dirty)

**Comment by geekbeast** [comment]
I'm seeing this myself across at least two different pools on the latest stable release (0.18.0). The only special thing is my case is that I'm running in a docker container. After adding  --response-timeout 30 I haven't seen this again. It went from dying in about 7.5 minutes to running fine for 30 minutes with no issues so far.

` X 21:26:35 ethminer No response received in 2 seconds.
 m 21:26:35 ethminer 0:07 A0 109.66 Mh - cl0 54.83 84C 65%, cl1 54.83 87C 87%
 i 21:26:35 ethminer Job: bee0da10… eth-us.sparkpool.com [52.8.43.205:3333]
cl 21:26:45 cl-1     Job: c766e796… Sol: 0xcc835663ddef18a1
cl 21:27:05 cl-0     Job: bee0da10… Sol: 0xcc83565edde5fbf4
 i 21:28:20 ethminer Disconnected from eth-us.sparkpool.com [52.8.43.205:3333]
 i 21:28:20 ethminer No connection. Suspend mining ...
 i 21:28:20 ethminer Solution 0xcc835663ddef18a1 wasted. Waiting for connection...
 i 21:28:20 ethminer Solution 0xcc83565edde5fbf4 wasted. Waiting for connection...
SIGSEGV encountered ...`
