### ISSUE TITLE
ApiServer request

### ISSUE THREAD

**Issue by oouuppss** [ethereum-mining/ethminer#1459]
First of all, thanks for the great job. 
Ethminer getting better each release.

Can we add ethereum adress and worker name on http json api.

Thanks anyway !
Keep on Going that way

**Comment by StefanOberhumer** [comment]
Possible as workaround you can currently use [miner_getconnections](https://github.com/ethereum-mining/ethminer/blob/master/docs/API_DOCUMENTATION.md#miner_getconnections)

**Comment by oouuppss** [comment]
Nice workaround. thanks

**Comment by ddobreff** [comment]
Does work for me.
echo '{"id":1,"jsonrpc":"2.0","method":"miner_getconnections"}' | nc localhost 3333
{"id":1,"jsonrpc":"2.0","result":[{"active":true,"index":0,"uri":"stratum+tls://0x....devrig1:x@eu1.ethermine.org:5555"}]}

**Comment by oouuppss** [comment]
i'am still using 0.15.0.dev10 ... perhaps that is why

**Comment by oouuppss** [comment]
Just Upgrade to current Git version (ethminer-0.16.0.dev3-12+commit.a6292182.dirty)!
`'{"id":1,"jsonrpc":"2.0","method":"miner_getconnections"}' ` working now ;)
