### ISSUE TITLE
CUDA search error in 0.12.0.dev0

### ISSUE THREAD

**Issue by dhjw** [ethereum-mining/ethminer#146]
This came up after a couple hours of good, fast mining on ubuntu 16.04 with cuda installed via repo .deb per nvidia's site. I'm using 6 gtx 1060's with 6GB overclocked to 200/1200 and undervolted to 85W:
```
CUDA error in func 'search' at line 365 : an illegal memory access was encountered.
  ✘  03:51:30|cudaminer0  Error CUDA mining: an illegal memory access was encountered
```
Then hashrate dropped to 0.

I made a restart script you can see at https://github.com/ethereum-mining/ethminer/issues/115#issuecomment-314080203.

**Comment by jimmykl** [comment]
This has been reported several times. Please close this issue and add your info to the discussion at https://github.com/ethereum-mining/ethminer/issues/72 Thanks!
