### ISSUE TITLE
CL_MEM_OBJECT_ALLOCATION_FAILURE

### ISSUE THREAD

**Issue by Davesmacer** [ethereum-mining/ethminer#1460]
Hello, 

OpenCL Error: clEnqueueNDRangeKernel: CL_MEM_OBJECT_ALLOCATION_FAILURE

I get this error when loading DAG on some of my cards. They are RX 480 and 570 with 4GB of memory each. Does this means that they have fried memory or something? Can it be connection issues? 

I had them all working yesterday, but today something went wrong after an update... I'm using 0.16.0.dev2

Thank you for any help!

**Comment by lesjokolat** [comment]
if you updated from an older version it could just be a the --cl-local-work xxx setting. try ensuring its one of 4 setting
64
128
192
256

I also recommend dev 3 version.

Also to help troubleshoot can you place the startup command line settings and a sample output of the miner setting where the error occurs. also add a -v 9 setting to help output give detailed info on errors.

**Comment by AndreaLanfranchi** [comment]
No feed back.
Closing
