### ISSUE TITLE
RX 550 (gfx804) Binary kernel and low hashrate

### ISSUE THREAD

**Issue by platofff** [ethereum-mining/ethminer#1462]
**Describe the bug**
Hello! I have tested your miner on my RX 550 (Lexa). The program cannot find a binary kernel for gfx804. I have added to a script which compiles binary kernel for GCN3 (GCN_ethash.isa) for my GPU core this text:

.elseifgpu gfx804
    .driver_version 200406
    .include "GCN_ethash_globaldata.isa"
    .include "GCN3_ethash_search.isa"
    .ifdef DAGGEN
        .include "GCN3_ethash_GenerateDAG.isa"
    .endif

And I have compiled binary kernel:
`clrxasm -o 'ethash_gfx804_lws192' --defsym=worksize='192' -A 'gcn1.2' -g 'gfx804' -b 'amdcl2' GCN_ethash.isa`
I have putted this to: ethminer/libethash-cl/kernels/bin and compiled ethminer.
I have 13 Mh/s on my GPU with BIOS mod and OC. But on other miners I have 13.7 Mh/s, what's a problem? I hope you will fix binary kernels for gfx804, thank you.
**Desktop (please complete the following information):**
- Operating System: Ubuntu Server 16.04.5
- Hardware AMD RX 550 2GB
- Ethminer Version 0.16.0dev3

**Comment by ddobreff** [comment]
Try worksize=64, if it doesn't work use "other" miner.

**Comment by platofff** [comment]
@ddobreff  I tested all worksizes and on worksize 64 I got 13,05 Mh/s. It is not good result, but it is larger than this GPU gets with OpenCL kernel.

**Comment by ddobreff** [comment]
Saying that 13.05MH is not good result is basically an insult to developers...You'd rather choose your words carefully when you are addressing non paid voluntary developer's work :)

**Comment by lesjokolat** [comment]
@platofff I think you could have optimized the kernels further to try improve your hashrate.
Things like driver version and 64 bit build are missing from the kernel commands you used to build the binary.

**Comment by invidtiv** [comment]
I have rx580,
everything is fine just use
--cl-local-work 256 --cl-global-work 65536 --cl-kernel 1 --cl-parallel-hash 2

**Comment by platofff** [comment]
@ddobreff You are right. I will wait for the new optimized kernerls for ethminer. Developers, please, add binary kernel for gfx804 because I have 11,5 Mh/s with OpenCL kernel, thank you.
Ethminer is the best miner on my RX 560 and Nvidia GPUs, but RX 550 have problems.
I will wait new optimized kernels, thank you.
