### ISSUE TITLE
0.16.0 DEV3

### ISSUE THREAD

**Issue by ianusy2k2** [ethereum-mining/ethminer#1463]
Miner stalls.... does not exit.... looks like its frozen....

**Comment by lesjokolat** [comment]
please include your startup command line. Add -v to it to show detailed messaging and try and define machine and OS stats.

**Comment by AndreaLanfranchi** [comment]
Without a proper description of issue with all the details depicted in the template we can't accept any help request.

Closing

**Comment by jean-m-cyr** [comment]
Perhaps a pared down version of PR #1439, would help with these?
