### ISSUE TITLE
build error on ubuntu with cuda 9.1

### ISSUE THREAD

**Issue by deh8551** [ethereum-mining/ethminer#1466]
Attempting to build the latest version - Commit 52cb8a7 on Ubuntu 16.04.5 LTS with Cuda 9.1 and 8qty 1070 cards and received the following dump right at 100%.  Tried removing the entire .hunter directory and let it rebuild since it seemed to be complaining about libboost, which it did successfully, but resulted in the same build error.
  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/daniel/Downloads/ethminer/build
Scanning dependencies of target devcore
[  3%] Building CXX object libdevcore/CMakeFiles/devcore.dir/CommonData.cpp.o
[  6%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Worker.cpp.o
[  9%] Building CXX object libdevcore/CMakeFiles/devcore.dir/FixedHash.cpp.o
[ 12%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Log.cpp.o
[ 15%] Building CXX object libdevcore/CMakeFiles/devcore.dir/RLP.cpp.o
[ 18%] Linking CXX static library libdevcore.a
[ 18%] Built target devcore
Scanning dependencies of target hwmon
[ 21%] Building CXX object libhwmon/CMakeFiles/hwmon.dir/wraphelper.cpp.o
[ 25%] Building CXX object libhwmon/CMakeFiles/hwmon.dir/wrapnvml.cpp.o
[ 28%] Building CXX object libhwmon/CMakeFiles/hwmon.dir/wrapadl.cpp.o
[ 31%] Building CXX object libhwmon/CMakeFiles/hwmon.dir/wrapamdsysfs.cpp.o
[ 34%] Linking CXX static library libhwmon.a
[ 34%] Built target hwmon
[ 37%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
txas info    : 0 bytes gmem, 264 bytes cmem[3]
ptxas info    : Compiling entry function '_Z25ethash_calculate_dag_itemj' for 'sm_30'
ptxas info    : Function properties for _Z25ethash_calculate_dag_itemj
    656 bytes stack frame, 1136 bytes spill stores, 848 bytes spill loads
ptxas info    : Used 63 registers, 324 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj8EEvPV14search_resultsm' for 'sm_30'
ptxas info    : Function properties for _Z13ethash_searchILj8EEvPV14search_resultsm
    160 bytes stack frame, 408 bytes spill stores, 420 bytes spill loads
ptxas info    : Used 63 registers, 336 bytes cmem[0], 96 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13ethash_searchILj4EEvPV14search_resultsm' for 'sm_30'
ptxas info    : Function properties for _Z13ethash_searchILj4EEvPV14search_resultsm
    104 bytes stack frame, 288 bytes spill stores, 276 bytes spill loads
ptxas info    : Used 63 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj2EEvPV14search_resultsm' for 'sm_30'
ptxas info    : Function properties for _Z13ethash_searchILj2EEvPV14search_resultsm
    72 bytes stack frame, 236 bytes spill stores, 212 bytes spill loads
ptxas info    : Used 63 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj1EEvPV14search_resultsm' for 'sm_30'
ptxas info    : Function properties for _Z13ethash_searchILj1EEvPV14search_resultsm
    72 bytes stack frame, 224 bytes spill stores, 204 bytes spill loads
ptxas info    : Used 63 registers, 336 bytes cmem[0]
ptxas info    : 0 bytes gmem, 264 bytes cmem[3]
ptxas info    : Compiling entry function '_Z25ethash_calculate_dag_itemj' for 'sm_35'
ptxas info    : Function properties for _Z25ethash_calculate_dag_itemj
    272 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 79 registers, 324 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj8EEvPV14search_resultsm' for 'sm_35'
ptxas info    : Function properties for _Z13ethash_searchILj8EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 101 registers, 336 bytes cmem[0], 96 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13ethash_searchILj4EEvPV14search_resultsm' for 'sm_35'
ptxas info    : Function properties for _Z13ethash_searchILj4EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj2EEvPV14search_resultsm' for 'sm_35'
ptxas info    : Function properties for _Z13ethash_searchILj2EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 79 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj1EEvPV14search_resultsm' for 'sm_35'
ptxas info    : Function properties for _Z13ethash_searchILj1EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 79 registers, 336 bytes cmem[0]
ptxas info    : 0 bytes gmem, 264 bytes cmem[3]
ptxas info    : Compiling entry function '_Z25ethash_calculate_dag_itemj' for 'sm_50'
ptxas info    : Function properties for _Z25ethash_calculate_dag_itemj
    272 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 96 registers, 324 bytes cmem[0], 4 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13ethash_searchILj8EEvPV14search_resultsm' for 'sm_50'
ptxas info    : Function properties for _Z13ethash_searchILj8EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 107 registers, 336 bytes cmem[0], 96 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13ethash_searchILj4EEvPV14search_resultsm' for 'sm_50'
ptxas info    : Function properties for _Z13ethash_searchILj4EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj2EEvPV14search_resultsm' for 'sm_50'
ptxas info    : Function properties for _Z13ethash_searchILj2EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj1EEvPV14search_resultsm' for 'sm_50'
ptxas info    : Function properties for _Z13ethash_searchILj1EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : 0 bytes gmem, 264 bytes cmem[3]
ptxas info    : Compiling entry function '_Z25ethash_calculate_dag_itemj' for 'sm_52'
ptxas info    : Function properties for _Z25ethash_calculate_dag_itemj
    272 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 96 registers, 324 bytes cmem[0], 4 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13ethash_searchILj8EEvPV14search_resultsm' for 'sm_52'
ptxas info    : Function properties for _Z13ethash_searchILj8EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 107 registers, 336 bytes cmem[0], 96 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13ethash_searchILj4EEvPV14search_resultsm' for 'sm_52'
ptxas info    : Function properties for _Z13ethash_searchILj4EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj2EEvPV14search_resultsm' for 'sm_52'
ptxas info    : Function properties for _Z13ethash_searchILj2EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj1EEvPV14search_resultsm' for 'sm_52'
ptxas info    : Function properties for _Z13ethash_searchILj1EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : 0 bytes gmem, 264 bytes cmem[3]
ptxas info    : Compiling entry function '_Z25ethash_calculate_dag_itemj' for 'sm_53'
ptxas info    : Function properties for _Z25ethash_calculate_dag_itemj
    272 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 96 registers, 324 bytes cmem[0], 4 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13ethash_searchILj8EEvPV14search_resultsm' for 'sm_53'
ptxas info    : Function properties for _Z13ethash_searchILj8EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 107 registers, 336 bytes cmem[0], 96 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13ethash_searchILj4EEvPV14search_resultsm' for 'sm_53'
ptxas info    : Function properties for _Z13ethash_searchILj4EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj2EEvPV14search_resultsm' for 'sm_53'
ptxas info    : Function properties for _Z13ethash_searchILj2EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj1EEvPV14search_resultsm' for 'sm_53'
ptxas info    : Function properties for _Z13ethash_searchILj1EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : 0 bytes gmem, 264 bytes cmem[3]
ptxas info    : Compiling entry function '_Z25ethash_calculate_dag_itemj' for 'sm_60'
ptxas info    : Function properties for _Z25ethash_calculate_dag_itemj
    272 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 96 registers, 324 bytes cmem[0], 4 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13ethash_searchILj8EEvPV14search_resultsm' for 'sm_60'
ptxas info    : Function properties for _Z13ethash_searchILj8EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 107 registers, 336 bytes cmem[0], 96 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13ethash_searchILj4EEvPV14search_resultsm' for 'sm_60'
ptxas info    : Function properties for _Z13ethash_searchILj4EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj2EEvPV14search_resultsm' for 'sm_60'
ptxas info    : Function properties for _Z13ethash_searchILj2EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj1EEvPV14search_resultsm' for 'sm_60'
ptxas info    : Function properties for _Z13ethash_searchILj1EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : 0 bytes gmem, 264 bytes cmem[3]
ptxas info    : Compiling entry function '_Z25ethash_calculate_dag_itemj' for 'sm_61'
ptxas info    : Function properties for _Z25ethash_calculate_dag_itemj
    272 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 96 registers, 324 bytes cmem[0], 4 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13ethash_searchILj8EEvPV14search_resultsm' for 'sm_61'
ptxas info    : Function properties for _Z13ethash_searchILj8EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 107 registers, 336 bytes cmem[0], 96 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13ethash_searchILj4EEvPV14search_resultsm' for 'sm_61'
ptxas info    : Function properties for _Z13ethash_searchILj4EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj2EEvPV14search_resultsm' for 'sm_61'
ptxas info    : Function properties for _Z13ethash_searchILj2EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj1EEvPV14search_resultsm' for 'sm_61'
ptxas info    : Function properties for _Z13ethash_searchILj1EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : 0 bytes gmem, 264 bytes cmem[3]
ptxas info    : Compiling entry function '_Z25ethash_calculate_dag_itemj' for 'sm_62'
ptxas info    : Function properties for _Z25ethash_calculate_dag_itemj
    272 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 96 registers, 324 bytes cmem[0], 4 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13ethash_searchILj8EEvPV14search_resultsm' for 'sm_62'
ptxas info    : Function properties for _Z13ethash_searchILj8EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 107 registers, 336 bytes cmem[0], 96 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13ethash_searchILj4EEvPV14search_resultsm' for 'sm_62'
ptxas info    : Function properties for _Z13ethash_searchILj4EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj2EEvPV14search_resultsm' for 'sm_62'
ptxas info    : Function properties for _Z13ethash_searchILj2EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj1EEvPV14search_resultsm' for 'sm_62'
ptxas info    : Function properties for _Z13ethash_searchILj1EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 336 bytes cmem[0]
ptxas info    : 0 bytes gmem, 264 bytes cmem[3]
ptxas info    : Compiling entry function '_Z25ethash_calculate_dag_itemj' for 'sm_70'
ptxas info    : Function properties for _Z25ethash_calculate_dag_itemj
    272 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 82 registers, 356 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj8EEvPV14search_resultsm' for 'sm_70'
ptxas info    : Function properties for _Z13ethash_searchILj8EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 108 registers, 368 bytes cmem[0], 104 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13ethash_searchILj4EEvPV14search_resultsm' for 'sm_70'
ptxas info    : Function properties for _Z13ethash_searchILj4EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 86 registers, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj2EEvPV14search_resultsm' for 'sm_70'
ptxas info    : Function properties for _Z13ethash_searchILj2EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 84 registers, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13ethash_searchILj1EEvPV14search_resultsm' for 'sm_70'
ptxas info    : Function properties for _Z13ethash_searchILj1EEvPV14search_resultsm
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 368 bytes cmem[0]
Scanning dependencies of target ethash-cuda
[ 40%] Building CXX object libethash-cuda/CMakeFiles/ethash-cuda.dir/CUDAMiner.cpp.o
[ 43%] Linking CXX static library libethash-cuda.a
[ 43%] Built target ethash-cuda
Scanning dependencies of target ethcore
[ 46%] Building CXX object libethcore/CMakeFiles/ethcore.dir/BlockHeader.cpp.o
[ 50%] Building CXX object libethcore/CMakeFiles/ethcore.dir/EthashAux.cpp.o
[ 53%] Building CXX object libethcore/CMakeFiles/ethcore.dir/Miner.cpp.o
[ 56%] Built target ethcore
Scanning dependencies of target ethminer-buildinfo-git
[ 56%] Built target ethminer-buildinfo-git
[ 59%] Updating ethminer-buildinfo:
       Project Version:  0.16.0.dev3-16+commit.52cb8a7c (prerelease)
       System Name:      linux
       System Processor: x86
       Compiler ID:      gnu
       Compiler Version: 5.4.0
       Build Type:       release
       Git Info:         0.16.0.dev3 16 52cb8a7cfa9cebc438e885cd58ee33c7f45dd4dd
       Timestamp:        2018-08-16T21:21:34
Scanning dependencies of target ethminer-buildinfo
[ 62%] Building C object CMakeFiles/ethminer-buildinfo.dir/ethminer/buildinfo.c.o
[ 65%] Linking C static library ethminer/libbuildinfo.a
[ 65%] Built target ethminer-buildinfo
Scanning dependencies of target poolprotocols
[ 68%] Building CXX object libpoolprotocols/CMakeFiles/poolprotocols.dir/PoolURI.cpp.o
[ 71%] Building CXX object libpoolprotocols/CMakeFiles/poolprotocols.dir/PoolManager.cpp.o
[ 75%] Building CXX object libpoolprotocols/CMakeFiles/poolprotocols.dir/testing/SimulateClient.cpp.o
[ 78%] Building CXX object libpoolprotocols/CMakeFiles/poolprotocols.dir/stratum/EthStratumClient.cpp.o
[ 81%] Building CXX object libpoolprotocols/CMakeFiles/poolprotocols.dir/getwork/EthGetworkClient.cpp.o
[ 84%] Linking CXX static library libpoolprotocols.a
[ 84%] Built target poolprotocols
Scanning dependencies of target apicore
[ 87%] Building CXX object libapicore/CMakeFiles/apicore.dir/ApiServer.cpp.o
[ 90%] Building CXX object libapicore/CMakeFiles/apicore.dir/httpServer.cpp.o
[ 93%] Linking CXX static library libapicore.a
[ 93%] Built target apicore
Scanning dependencies of target ethminer
[ 96%] Building CXX object ethminer/CMakeFiles/ethminer.dir/main.cpp.o
[100%] Linking CXX executable ethminer
../libapicore/libapicore.a(ApiServer.cpp.o): In function `dev::eth::Farm::spawn_file_in_bin_dir(char const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
ApiServer.cpp:(.text._ZN3dev3eth4Farm21spawn_file_in_bin_dirEPKcRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EE[_ZN3dev3eth4Farm21spawn_file_in_bin_dirEPKcRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EE]+0x68): undefined reference to `boost::filesystem::detail::read_symlink(boost::filesystem::path const&, boost::system::error_code*)'
ApiServer.cpp:(.text._ZN3dev3eth4Farm21spawn_file_in_bin_dirEPKcRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EE[_ZN3dev3eth4Farm21spawn_file_in_bin_dirEPKcRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EE]+0xcb): undefined reference to `boost::filesystem::path::parent_path() const'
ApiServer.cpp:(.text._ZN3dev3eth4Farm21spawn_file_in_bin_dirEPKcRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EE[_ZN3dev3eth4Farm21spawn_file_in_bin_dirEPKcRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EE]+0x1f7): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
ApiServer.cpp:(.text._ZN3dev3eth4Farm21spawn_file_in_bin_dirEPKcRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EE[_ZN3dev3eth4Farm21spawn_file_in_bin_dirEPKcRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EE]+0x27c): undefined reference to `boost::filesystem::detail::file_size(boost::filesystem::path const&, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
ethminer/CMakeFiles/ethminer.dir/build.make:119: recipe for target 'ethminer/ethminer' failed
make[2]: *** [ethminer/ethminer] Error 1
CMakeFiles/Makefile2:489: recipe for target 'ethminer/CMakeFiles/ethminer.dir/all' failed
make[1]: *** [ethminer/CMakeFiles/ethminer.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by StefanOberhumer** [comment]
Have you upgraded the submodules (`git submodule update --recursive`) ?

**Comment by deh8551** [comment]
Yes it was run.

This is the script I use to build from for the cuda rig

$!/bin/bash
git clone https://github.com/ethereum-mining/ethminer
cd ethminer
git submodule update --init --recursive
mkdir build
cd build
cmake .. -DETHASHCUDA=ON -DETHASHCL=OFF -DBINKERN=OFF
cmake --build .

I notice today new files were downloaded via hunter related to cable & disabled-mode, but it still fails.  On my other rig, same OS using openCL for AMD 580 cards, it build successfully.  It only fails on the cuda rig.  For the OpenCL, use the same build script except have -DETHASHCUDA=OFF set.
