### ISSUE TITLE
several 11.0 versions: all produce CUDA search error messages

### ISSUE THREAD

**Issue by MatthiasThoemel** [ethereum-mining/ethminer#147]
Hello to all here - I am a new member and happy to contribute some information to all.

I have tested the several 11.0 versions with my RIG1:

6 x GTX 1060 (ASUS Turbo) 6GB (OC Mem 10 GHz). 
Windows 10: up to date
NVidia Driver: up to date

And I can confirm: 

All versions of 11.0 have similar problems. Sometimes the error message is different but in general they all have the same issue. It looks like that the changes in the area of the CUDA search are buggy.

I am a software developer by myself and worked also with CUDA but unfortunately I do not have MS DevStudio 12 so I cannot contribute a bugfix. I tried to migrate the project to MS DevStudio 2017 but that failed for a lot of reasons.

I am now testing the old version: ethminer-0.9.41-genoil-1.1.7 if it has similar problems with overclocked cards and I will report. 

My best regards, Matthias

**Comment by dextee** [comment]
everyone experiencing this issue... currently using claymore 9.7 till this is fixed... getting same speed improvements on claymore... but i want no fees so i am looking closely at this fix on this software

**Comment by jimmykl** [comment]
This has been reported several times. Please close this issue and add your info to the discussion at https://github.com/ethereum-mining/ethminer/issues/72 Thanks!
