### ISSUE TITLE
Incorrect worker name nanopool since 1987 and reported hashrate did not work 

### ISSUE THREAD

**Issue by MiningGuru** [ethereum-mining/ethminer#1470]
Hello,

there is a big problem with workername on nanopool since around history patch version 1987.

at nanopool graphic hasrate sum report is correct but the worker will not shown anymore and also the reported hashrate is not more reported by ethminer.

I think it is around patchversion 1987 and newer ones.
perhabs it can do to with a fix before 1987 I did not check the older ones.

Worker
Incorrect%20worker%20name
not found

You can easily check the issue by starting with the following comands. If you check at nanopool it will show incorrect workername and also the reported hashrate will not work anymore.

cd c:\eth
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer -U -P stratum1+tcp://0xxxxyyyyyyyyyyyyyyy@eth-eu1.nanopool.org:9999/NVIDIARIG/mygmailadress@googlemail.com  --stratum-email mygmailadress@googlemail.com --HWMON 1 -R --display-interval 10 --api-port 6000 --http-port 6001 --api-password ethtothemoonagain
pause

**Comment by lesjokolat** [comment]
ethminer -U -P --HWMON 1 -R --display-interval 10 --report-hashrate stratum+tcp://0xxxxyyyyyyyyyyyyyyy@eth-eu1.nanopool.org:9999/NVIDIARIG/mygmailadress@googlemail.com --stratum-email mygmailadress@googlemail.com --api-port 6000 --http-port 6001 --api-password ethtothemoonagain -v 8


what is output of this command start up
pause

**Comment by MiningGuru** [comment]
I did start the line with -v 8 when an error occours i will post I have inserted pause so if error occours with your v 8 you get additional infos.

**Comment by MiningGuru** [comment]
here is the log output for v 8:

https://github.com/ethereum-mining/ethminer/issues/1471#issuecomment-414109526

**Comment by lesjokolat** [comment]
hou still did not use command atartup as i had showed you.

ethminer -U -P --HWMON 1 -R --display-interval 10 --report-hashrate stratum+tcp://0xxxxyyyyyyyyyyyyyyy.NVIDIARIG@eth-eu1.nanopool.org:9999/NVIDIARIG/mygmailadress@googlemail.com --stratum-email mygmailadress@googlemail.com --api-port 6000 --http-port 6001 --api-password ethtothemoonagain -v 9

i customized it to your setting. the .worker nsmae and reporthashrate order i hope will fix username and reporting of speed. i tweaked atratum as the 1 is no longer needed. the disconnect i see was mentioned as a bug before but not sure about that.  -v 9 may help others understand why dissconnect. try now and post output.

**Comment by jean-m-cyr** [comment]
Shouldn't this work?

ethminer -U -P --HWMON 1 -R --display-interval 10 -P stratum+tcp://0xxxxyyyyyyyyyyyyyyy.NVIDIARIG@eth-eu1.nanopool.org:9999/mygmailadress@googlemail.com --api-port 6000 --http-port 6001 --api-password ethtothemoonagain -v 9

**Comment by MiningGuru** [comment]
I checked around 2 hours if nanopool accepted workername and reported hashrate ....ethminer -U -P --HWMON 1 -R --display-interval 10 --report-hashrate stratum+tcp://0xxxxyyyyyyyyyyyyyyy.NVIDIARIG@eth-eu1.nanopool.org:9999/NVIDIARIG/mygmailadress@googlemail.com --stratum-email mygmailadress@googlemail.com --api-port 6000 --http-port 6001 --api-password ethtothemoonagain -v 9

DO ALSO Not work! I have updated to the latest appvenior-release.

I will check now the last report from jean-m-cyr.  with:
ethminer -U -P --HWMON 1 -R --display-interval 10 -P stratum+tcp://0xxxxyyyyyyyyyyyyyyy.NVIDIARIG@eth-eu1.nanopool.org:9999/mygmailadress@googlemail.com --api-port 6000 --http-port 6001 --api-password ethtothemoonagain

**Comment by jean-m-cyr** [comment]
It works for me...

 m 12:32:37 ethminer ethminer 0.16.0.dev3-29+commit.09214928
 m 12:32:37 ethminer Build: linux/release
cu 12:32:37 ethminer Using grid size: 8,192, block size: 128
 i 12:32:37 ethminer Configured pool eth-eu1.nanopool.org:9999
 i 12:32:37 ethminer Api server listening on port 6000. Authentication needed.
 i 12:32:37 main     Selected pool eth-eu1.nanopool.org:9999
 i 12:32:37 ethminer Starting web server on port 0.0.0.0:6001
 i 12:32:38 stratum  Stratum mode detected : ETHPROXY Compatible
 i 12:32:38 stratum  Logged in !
 i 12:32:38 stratum  Established connection with eth-eu1.nanopool.org:9999 at  [163.172.162.51:9999]
 i 12:32:38 stratum  Spinning up miners...
 i 12:32:38 cuda-0   No work. Pause for 3 s.
 i 12:32:38 cuda-1   No work. Pause for 3 s.
 i 12:32:38 cuda-2   No work. Pause for 3 s.
 i 12:32:38 cuda-3   No work. Pause for 3 s.
 i 12:32:38 stratum  Job: #67a198dc… eth-eu1.nanopool.org [163.172.162.51:9999]
 i 12:32:38 stratum  Pool difficulty: 10.00K megahash

**Comment by MiningGuru** [comment]
yes the sum of hashrate and the success of jobs is working.
But for this rig if you check the nanopool it shows incorrect worker name and the reported hashrate do not work.

But in sum the hasharte for all rigs are right.

I will check you reported setup line ......

**Comment by AndreaLanfranchi** [comment]
There should be no guessing about this matter.
Only apply logic and read the code.

Nanopool clearly states [here](https://eth.nanopool.org/help)

```
ethminer.exe --farm-recheck 200 -G -S eth-eu1.nanopool.org:9999 -O YOUR_ADDRESS.YOUR_WORKER/YOUR_EMAIL
```

Now ... argument `-O` has been dropped and integrated in the `-P` URI form where _anything_ among the scheme (stratum+tcp://) and the host name (eth-eu1.nanopool.org:9999) is the equivalent of the _old_ -O argument.

Due to this you have two options.
 
Either encode your authentication or use the "path" part.
Let's assume you want to login as `0x1234567890abcdef.MyWorkerName/j.doe@gmail.com`

1st option (encoding)
You might have to set your -P argument as follows.

``` 
-P stratum+tcp://0x1234567890abcdef.MyWorkerName%2Fj.doe%40gmail.com@eth-eu1.nanopool.org:9999
``` 

But this would fail due to this problem #1075 

So you have to fall back to 2nd option. Use path.

``` 
-P stratum+tcp://0x1234567890abcdef.MyWorkerName@eth-eu1.nanopool.org:9999/j.doe@gmail.com
``` 

This is the **only** working syntax to apply when a pool (like nanopool) requires a slash as a separator.

The relevant code part of the login process is from this line on.

https://github.com/ethereum-mining/ethminer/blob/09214928418233e6bf342c0e48d1be19760f2dfc/libpoolprotocols/stratum/EthStratumClient.cpp#L571

Closing notes:

1. Do not value the **`--stratum-email`** argument as the email is already included in your -P argument.
2. Ensure your workername **DOES NOT CONTAIN** any dot.

**Comment by AndreaLanfranchi** [comment]
BTW this has been already answered here

https://github.com/ethereum-mining/ethminer/issues/1139#issuecomment-392352789

**Comment by AndreaLanfranchi** [comment]
**Please also take note that workername should only contain only chars and digits: no underscores, no dashes, no dots, no punctuations in general as nanopool drops them**

**Comment by jean-m-cyr** [comment]
@AndreaLanfranchi There is an issue here... the new Path() URI method does not return the leading '/' the way the old one did. Easy fix, will submit PR

**Comment by AndreaLanfranchi** [comment]
@jean-m-cyr ok.

**Comment by jean-m-cyr** [comment]
Fixed by PR #1477

**Comment by MiningGuru** [comment]
Hi AndreaLanfranchi,

thanks for your support, I did remove the --stratum-email parameter. I have workername Zotac1070-1.

The main reason why I am opened the issue is that after after a code-update the reported hashrate and the workername did not work anymore. so there have an issue with an master-update of your code.

I will check now without parameter --stratum-email.
After that if it do also not work i will remote the "-" from the workername to zotac1070 instead of zotac-1070.

**Comment by MiningGuru** [comment]
I do now the check with
...
ethminer -U -P --HWMON 1 -R --display-interval 10 --report-hashrate stratum+tcp://0xxxxxxxxxx@eth-eu1.nanopool.org:9999/Zotac1070-2/xxxx@yyyy.com --api-port 6000 --http-port 6001 --api-password dt -v 9

After that if it do not work I will change workername to Zotac10702  ......

**Comment by MiningGuru** [comment]
Hi,
thanks to the developer the new compiled revision is working now correct.

- reported hashrate from seperate RIG is OK
- workername on nanopool is now also OK

ticket can be closed.

great work thanks!

**Comment by MiningGuru** [comment]
special character on worker name also work as before.

for example Zotac-1070Rig   ->> "-" is working
