### ISSUE TITLE
ethminer Crahes after BIOS update

### ISSUE THREAD

**Issue by vonRoX** [ethereum-mining/ethminer#1483]
Ethminer was working till yesterday and after I did a BIOS update it just wont start mining... Don't know what else to say... BIOS is the only change I made in between ethminer working and not working...

Mobo:
ASUS B250M-K
GPU:
1060 6gb - Power limit 80, core -400, mem +650 - stable for 6 months
Win 10 (latest updates)
ethminer v14 and 15 as well
![image](https://user-images.githubusercontent.com/42553540/44361932-c116b600-a4bf-11e8-9926-a2bceec592b3.png)

**Comment by lesjokolat** [comment]
Can you add -v 9 to your start up and copy text of output?

**Comment by vonRoX** [comment]
**launch options:**
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

ethminer.exe -v 9 --farm-recheck 2000 --report-hashrate -U --cuda-parallel-hash 4 --cuda-streams 4 -P stratum1+tcp://0x89ad12e0c817dd2ee55d170d488a9564e3d468af.DefineMiniC@eth-eu1.nanopool.org:9999 -P stratum1+tcp://0x89ad12e0c817dd2ee55d170d488a9564e3d468af.DefineMiniC@eth-eu2.nanopool.org:9999

pause

_________________________________________________________________________

**output:**
C:\ethminer>setx GPU_FORCE_64BIT_PTR 0

SUCCESS: Specified value was saved.

C:\ethminer>setx GPU_MAX_HEAP_SIZE 100

SUCCESS: Specified value was saved.

C:\ethminer>setx GPU_USE_SYNC_OBJECTS 1

SUCCESS: Specified value was saved.

C:\ethminer>setx GPU_MAX_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\ethminer>setx GPU_SINGLE_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\ethminer>ethminer.exe -v 9 --farm-recheck 2000 --report-hashrate -U --cuda-parallel-hash 4 --cuda-streams 4 -P stratum1+tcp://0x89ad12e0c817dd2ee55d170d488a9564e3d468af.DefineMiniC@eth-eu1.nanopool.org:9999 -P stratum1+tcp://0x89ad12e0c817dd2ee55d170d488a9564e3d468af.DefineMiniC@eth-eu2.nanopool.org:9999
 m 21:34:26 main     ethminer 0.15.0
 m 21:34:26 main     Build: windows/release
cu 21:34:26 main     Using grid size: 8192, block size: 128

C:\ethminer>pause
Press any key to continue . . .

**Comment by lesjokolat** [comment]
Is this still V 14 or 15? If so try the V16 dev 3 at least

**Comment by vonRoX** [comment]
v15 and 0.16.0.dev3 gives me the same:


C:\ethminer\bin>setx GPU_FORCE_64BIT_PTR 0

SUCCESS: Specified value was saved.

C:\ethminer\bin>setx GPU_MAX_HEAP_SIZE 100

SUCCESS: Specified value was saved.

C:\ethminer\bin>setx GPU_USE_SYNC_OBJECTS 1

SUCCESS: Specified value was saved.

C:\ethminer\bin>setx GPU_MAX_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\ethminer\bin>setx GPU_SINGLE_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\ethminer\bin>ethminer.exe -v 9 --farm-recheck 2000 --report-hashrate -U --cuda-parallel-hash 4 --cuda-streams 4 -P stratum1+tcp://0x89ad12e0c817dd2ee55d170d488a9564e3d468af.DefineMiniC@eth-eu1.nanopool.org:9999 -P stratum1+tcp://0x89ad12e0c817dd2ee55d170d488a9564e3d468af.DefineMiniC@eth-eu2.nanopool.org:9999
 m 21:41:18 main     ethminer 0.16.0.dev3
 m 21:41:18 main     Build: windows/release
cu 21:41:18 main     Using grid size: 8á192, block size: 128

**Comment by vonRoX** [comment]
I even tried to strip the bat launch file to bare minimum and didn't help...

**Comment by lesjokolat** [comment]
wow looks like this is a hardware issue Its not even starting up the miner to get any useful info..

Go into BIOS check you can see if ram (may have been previous ly overclocked) turn it to default 2133 or 2400 whatever is native speed.

I would also re install Nvidia Driver and motherboard drivers. If possible install them as admin. See what happens after that.

**Comment by lesjokolat** [comment]
Can you see all GPUs in hardware manager?

**Comment by vonRoX** [comment]
tried default settings on BIOS and XMP profile of 2400 as well... Drivers was the first thing that i wiped with DDU and reinstalled fresh...
![image](https://user-images.githubusercontent.com/42553540/44362841-90844b80-a4c2-11e8-88a6-8891ab1d4839.png)

**Comment by lesjokolat** [comment]
Does that include motherboard drivers? How much ram you have? What is teh virtual ram setting? shouldnt be huge with just 1 GPU but could be a source.

**Comment by vonRoX** [comment]
will try mb drivers, 16gb RAM and 2432mb of virtual ram (automatically managed)

**Comment by lesjokolat** [comment]
Try bumping virtual memory to 5 gigs... Doubt it is source, but worth a shot.

**Comment by lesjokolat** [comment]
I see this motherboard has a inbuilt Intel you have to run it as a mixed mode cuda /opencl or specify only cuda.

**Comment by vonRoX** [comment]
even if integrated graphics is disabled..?

**Comment by lesjokolat** [comment]
Ah ok if disabled then wont be seen. Make sure new bios still has it as disabled.

**Comment by vonRoX** [comment]
updated chipset drivers, increased virtual mem to 4-5gb checked if igpu is disabled and still same result...

**Comment by lesjokolat** [comment]
Is your hard disk at like 99% capacity? Still lots of room? tweaked startup...

C:\ethminer\bin\ethminer.exe -v 9 -U --report-hashrate --cuda-parallel-hash 4 --cuda-streams 4 -P stratum1+tcp://0x89ad12e0c817dd2ee55d170d488a9564e3d468af.DefineMiniC@eth-eu1.nanopool.org:9999 -P stratum1+tcp://0x89ad12e0c817dd2ee55d170d488a9564e3d468af.DefineMiniC@eth-eu2.nanopool.org:9999

**Comment by vonRoX** [comment]
SSD enough space... no luck with this startup...

**Comment by lesjokolat** [comment]
C:\ethminer\bin\ethminer.exe -U -P -L 0 --HWMON 1 --report-hashrate stratum1+tcp://0x89ad12e0c817dd2ee55d170d488a9564e3d468af.DefineMiniC@eth-eu1.nanopool.org:9999 -v 9

how does this react

**Comment by vonRoX** [comment]
same :/

**Comment by vonRoX** [comment]
So tried Claymore and FinMiner:
Claymore crashes as well - looks basically the same... lodes and crashes just after...
But FinMiner works no problem... hmmmm

**Comment by vonRoX** [comment]
@invidtiv I had VT-d INTEL VIRTUALIZATION already disabled and after Enabling 4G Decode... Still no luck

**Comment by lesjokolat** [comment]
can you change gpu pci slot and see if it makes any difference?

**Comment by vonRoX** [comment]
can't do... only have one... mATX motherboard....

**Comment by lesjokolat** [comment]
ok then reseat it and also reconnect any harddisks. lets see if any wonky hardware connections could be causing havok.

**Comment by lesjokolat** [comment]
I got this from another issue raised here as an option try it.. I am more inclined to see if its a ram issue so try and remove a ram brick to see if one or the other are the issue.

https://windowsreport.com/exception-access-violation-windows-10/ see part on:
Solution 1 – Add Data Execution Prevention Exception



GLTU

**Comment by vonRoX** [comment]
Didn't help...
but what did help was trying to plug my monitor into MB, which automatically enabled the onboard graphics... and viola Miner works again... so I was like... Hmmm...
So i plugged my monitor back to the GPU, went back to BIOS and enabled iGPU... so atm I have the monitor running of the GPU and I have **iGPU enabled** and everything is back to normal...
What pisses me off tho, is the fact that before the BIOS update **I didn't have to have iGPU enabled**, since I have no use for it... When I go away I swich of the monitor and let the system mine and when I game I use the 1060 as well... So I never plug the monitor into the mobo... so why have the iGPU enabled..?

**Comment by lesjokolat** [comment]
@AndreaLanfranchi 

I think this can be closed now.
