### ISSUE TITLE
ethminer dies immediately with exit code 3221225477 (Windows)

### ISSUE THREAD

**Issue by ksloan** [ethereum-mining/ethminer#1488]
**Describe the bug**
ethminer dies immediately with code `3221225477`

**To Reproduce**

```
ethminer.exe --HWMON 0 --farm-recheck 200 --report-hashrate -U -P stratum1+tcp://wallet@eth-us-east1.nanopool.org:9999/workername/email@gmail.com -P stratum1+tcp://wallet@eth-us-west1.nanopool.org:9999/workername/email@gmail.com -P stratum1+tcp://wallet@eth-eu1.nanopool.org:9999/workername/email@gmail.com -P stratum1+tcp://wallet@eth-eu2.nanopool.org:9999/workername/email@gmail.com -P stratum1+tcp://wallet@eth-asia1.nanopool.org:9999/workername/email@gmail.com
```
output:
```
 m 22:10:20 main     ethminer 0.15.0
 m 22:10:20 main     Build: windows/release
cu 22:10:20 main     Using grid size: 8192, block size: 128
```
then it just stops

**Expected behavior**
ethminer to start

**Desktop (please complete the following information):**
- Operating System: Windows 10
- Hardware GTX 1070
- Ethminer Version 0.15.0

**Additional Info**

- adding verbosity doesn't add any additional output

- ethminer does see my devices:
```
ethminer.exe -U --list-devices

Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1070
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 8589934592
        Pci: 0000:01:00
```

- I have 17 other almost identical machines running ethminer just fine, but this is the only one just failing silently.

**Comment by ksloan** [comment]
actually I just notice that this looks similar to #1483

**Comment by lesjokolat** [comment]
If you run this the non email version does it work?

ethminer.exe --HWMON 0 --report-hashrate -P stratum1+tcp://ETH_WALLET.WORKERNAME@eth-eu1.nanopool.org:9999

**Comment by lesjokolat** [comment]
I have 2 more ideas to try... real long shots...

https://windowsreport.com/exception-access-violation-windows-10/ see part on:
Solution 1 – Add Data Execution Prevention Exception

If that fails then try to switch ram from rigs that work into this one and see if its not a ram issue.

GLTU

**Comment by AndreaLanfranchi** [comment]
Mostly related to windows updates as no more feed backs.
Closing
