### ISSUE TITLE
Nvidia K80 sufficient memory. Bug ?

### ISSUE THREAD

**Issue by mmaryo** [ethereum-mining/ethminer#149]
Hello, 

I have this message : 

$ ./ethminer -G -F http://eth.pool.minergate.com:55751/xxxxxxxxxx
[OPENCL]:No OpenCL platforms found
No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument

With : 

ethminer 0.11.0 
Ubuntu 17.04
Nvidia Tesla K80
Nvidia driver 384.47

**Comment by derubm** [comment]
try -U flag instead of -G

**Comment by Singman33** [comment]
And try to read the manual before using that program :)
-U is for CUDA devices (NVidia)
-G is for OpenCL (mainly AMD and CPU)

**Comment by mmaryo** [comment]
thanks :/
