### ISSUE TITLE
Better hashrate calculation

### ISSUE THREAD

**Issue by chfast** [ethereum-mining/ethminer#1495]
Instead of sampling GPUs hash count, try this approach:

1. Calculate hashrate for each GPU as
   ```
   hashrate = batch_size / (batch_end_time - batch_start_time).
   ```
2. Store the hashrate for each GPU in an array of atomics.
3. To get total hashrate just sum all individual hashrates.

This should mitigate the problem of sampling the hashrate of a GPU in the middle of long batch.

To smooth the final results, optionally, a GPU hashrate update can look like:

```
factor = 0.5
hashrate = factor * hashrate + (1 - factor) * current_batch_hashrate
```

**Comment by chfast** [comment]
Oh, I've found a bug. It should be 
```
hashrate = batch_size / (batch_end_time - previous_batch_end_time).
```

**Comment by AndreaLanfranchi** [comment]
This will cause fluctuations too as the interval among batches may not be regular in case of extra activity like job switching and solution submitting

**Comment by DekInc** [comment]
@AndreaLanfranchi  the solution submitting is not async?

**Comment by AndreaLanfranchi** [comment]
@DekInc yes but only the tcp part (send to pool via socket)
The process of extracting it from kernel buffer, store it in a Solution object and, if --noeval not set, reevaluating are all sync.

**Comment by DekInc** [comment]
@AndreaLanfranchi  do you think this could be better?
std::future<void> sub1 = std::async(SubmitSol, this, nonces[i], w);
void SubmitSol(CUDAMiner * CmO, uint64_t N, WorkPackage w1) {
	//CmO->farm.submitProof(SolO);
	//CmO->farm.submitProof(Solution{ N, r.mixHash, w, m_new_work });
	Result r = EthashAux::eval(w1.epoch, w1.header, N);
	if (r.value <= w1.boundary) {
		CmO->NSols++;		
		CmO->farm.submitProof(Solution{ N, r.mixHash, w1, false, CmO->NSols });

**Comment by DekInc** [comment]
seems to work.... ?

i 02:52:40 <unknown> Solution: 0x000003e40700fac2 w f1e9dae1... NSols = 1
 i 02:52:40 stratum  **Accepted 194 ms. eu1.ethermine.org [35.234.112.115:4444]

**Comment by AndreaLanfranchi** [comment]
I'd have to instrument measure it but I believe the overhead introduced by an additional async call is not worth the effort.
Please note the the non-async part of the solution submission weight less than 100 microseconds.
