### ISSUE TITLE
Finally a Stable Ethminer 0.15.0

### ISSUE THREAD

**Issue by ianusy2k2** [ethereum-mining/ethminer#1496]
Just want to share with you guys who work hard to have this for the mining community.... open source no dev fee ethminer....

OS Windows 10 Pro latest update
GPU Nvidia 1070 3 rigs 2 x 10 gpu and 1 x 7 gpu
 = PALIT JETSTREAM 21 pcs;  ZOTAC AMP CORE EDITION
Motherboard: Asrock PRO BTC H110
Ethminer 0.15.0
Ave Hash per GPU is 31.7-31.8 mh/s
*can push it as high as 32mh/s per gpu but reported hash rate would fluctuate
Enhancers:
OC = Nvidia Inspector
https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW#nvidiaprofileinspectordmw
https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW#windows10miningtweaksdmw
https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW#ethminerwatchdogdmw

#Reported hashrate is a straight line... minimal fluctuations, its almost equal with what being displayed on the mining console..... 24 hour shares found increased also = increased income

![smc](https://user-images.githubusercontent.com/42310866/44603585-bccaff80-a815-11e8-974e-5c5f7def0271.png)
![kenyo](https://user-images.githubusercontent.com/42310866/44603602-c48aa400-a815-11e8-97e8-32e8ea77974b.png)
![ethminer](https://user-images.githubusercontent.com/42310866/44603606-c81e2b00-a815-11e8-95dc-12633ba06af8.png)

with the right settings ETHminer is awesome
Nvidia Inspector is better than AB imho for OC of ethminer - 
approximate 87w per GPU Palit Jetstream 115w per Zotac Amp

Credit to all the contributors here in Github for tirelessly working for free, to give us  the tools in crypto mining... 
CHEERS!!! keep  up the good work guys!!! Thank you so much

**Comment by AndreaLanfranchi** [comment]
Thank you for taking time to report.
Believe we're doing even better in 0.16
Stay tuned.

**Comment by chfast** [comment]
Good to hear this!

**Comment by ianusy2k2** [comment]
i have yet to use my settings to 0.16.0 dev3.... i will have to let this run for a week then shift my test rig to the newest release... but 1 thing i notice... the existing start.bat file seems to have a problem with the new release.... will have to check and edit it first....

**Comment by ianusy2k2** [comment]
might be gpu driver failure as reported in events viewer.... uninstalled via safe mode with ddu and reinstalled drivers.... running stable atm....

**Comment by AndreaLanfranchi** [comment]
Closing ... feel free to reopen if something not related to drivers.
