### ISSUE TITLE
CUDA error in Func 'ethash_cuda_miner::init at line 243 : Out of Memory

### ISSUE THREAD

**Issue by nguylb73** [ethereum-mining/ethminer#150]
I get the error above with the 0.11.0 binary release on every run. Using the following setup
6 x 1070s
4 GB RAM
Celeron Proc

Oddly the genoil version worked great until I ran this executable on my computer. Both genoil and 0.11.0 fails trying to gather DAG on the 4th - 6th GPU. Reimaged and tried it again, GenOil version stops working once I execute 0.11.0. My system is running GenOil version stable now after the second reimage without running 0.11.0.

does this binary cache/alters something(s) that may corrupt memory?? p.s. taking out 1 GPU when it's at this bad state fixes the issue..

Also what's the RAM and CPU requirements?

**Comment by JHGitty** [comment]
Please increase the virtual memory (= page file) of your operation system to 20 GB.

http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/uploads/2010/06/increase-virtual-memory-600x430.png

Set to "custom", set 20GB in both fields and press "Set" button.

Afterwards it should work.

**Comment by JHGitty** [comment]
If you don't want to do the above steps, you can try these parameters:
`--dag-load-mode sequential` or `--dag-load-mode single 0`

**Comment by nguylb73** [comment]
@JHGitty 

Thanks for the responds, community support is awesome :)
I'm currently using --dag-load-mode sequential. Same issue

Based on what I read ethereum mining does not require much memory, ethminer does not appear to past 700 MB. Two part question: Can you clarify why you would need so much virtual memory? Would just adding additional physical RAM be more beneficial?

**Comment by deathcamp** [comment]
Because of how the DAG file is created and how virtual graphics memory is managed under WDDM you need sufficient space in RAM or in the page file for all the DAG files.

**Comment by nguylb73** [comment]
@JHGitty @deathcamp 
I added an additional 4gb of ram and changed my virtual ram to 20 GB. It's been running stable. You guys are awesome!
