### ISSUE TITLE
Log output change: gpu0 instead of gpu/0

### ISSUE THREAD

**Issue by th0ma7** [ethereum-mining/ethminer#1504]
**Describe the bug**
Version 0.15 and prior used to show each GPU output as gpu/?:
 m 20:12:20 ethminer Speed  80.14 Mh/s    gpu/0 13.32 60C 40% 31W  gpu/1 13.85 55C 23% 33W  gpu/2 13.43 60C 40% 32W  gpu/3 13.32 60C 38% 31W  gpu/4 12.59 60C 40% 30W  gpu/5 13.64 60C 40% 30W  [A1+0:R0+0:F0] Time: 00:01

Since version 0.16 the output changed to gpu?:
 m 19:46:06 ethminer Speed 83.25 Mh/s gpu0 12.48 77C 53% 33W gpu1 14.00 75C 18% 35W gpu2 13.86 76C 50% 34W gpu3 14.93 75C 48% 33W gpu4 13.55 77C 53% 33W gpu5 14.43 77C 53% 33W [A18] Time: 00:15

**Expected behavior**
Might be expected but I thought it was worth letting know as this might affect external software monitoring ethminer log outputs.

**Comment by StefanOberhumer** [comment]
For monitoring you should prefer the [API](https://github.com/ethereum-mining/ethminer/blob/master/docs/API_DOCUMENTATION.md) methods as output can always change

**Comment by th0ma7** [comment]
Personally I'm in favor of keeping the previous output with `/` but I'm fine with that and just thought it was worth reporting it.
