### ISSUE TITLE
-HWMON option now --HWMON 0|1

### ISSUE THREAD

**Issue by th0ma7** [ethereum-mining/ethminer#1505]
**Describe the bug**
Up to version 0.14 the `-HWMON` switch was available.  Since 0.15 (and current MASTER) we now have to use `--HWMON 0|1` which is fine  although for backward compatibility it may be best to keep previous method also functional?

**Comment by StefanOberhumer** [comment]
We introduced a standard CLI which uses

* `-` and a single character
* `--` and a word (if more words usually joined with `-`)

for options.

As `-HWMON` was a non standard parameter option we fixed it.
Having "wrong/backwards compatible/non standard" code in the sourcecode makes maintenance and development more difficult and error-prone.

You can query ethminers version in your startup using `ethminer --version` and decide based on the version the "correct" parameters.

**Comment by th0ma7** [comment]
Having a log out message for a release or two could have been a "smoother" approch in order to raise awareness to users.  But I'm all good with it as is.
