### ISSUE TITLE
api return errocode:-32700

### ISSUE THREAD

**Issue by franklen** [ethereum-mining/ethminer#1515]
*I'm using version 0.15
 > echo '{"id":0,"jsonrpc":"2.0","method":"miner_ping"}' | netcat localhost 3333

{"error":{"code":-32700,"message":"Parse Error"},"id":null,"jsonrpc":"2.0"}

**Comment by lesjokolat** [comment]
try latest 16 dev lots of fixes around api.

**Comment by franklen** [comment]
i just remove the two  single-quote-mark " ' " which solved the issue.
