### ISSUE TITLE
v0.16.0.rc0 can't load binary kernel, opencl kernel 7MH/s slower

### ISSUE THREAD

**Issue by AntoniosHadji** [ethereum-mining/ethminer#1520]
I compiled v0.16.0.rc0 (without CUDA support) today for testing.  I have been running 0.16.0.dev0+commit.781feb6f with no issues and a hash rate of 116MH/s across  4 RX580s.  The latest version is clocking in no higher than 109MH/s.  

old version is started with:  
`ethminer -G -P pool1 pool2  --cl-local-work 256 --cl-global-work 16384 --cl-kernel 1 --cl-parallel-hash 2 --report-hashrate --syslog --HWMON 1
`
The new version was tested with:  
```sudo ./ethminer/ethminer -G  --cl-local-work 256 --cl-global-work 16384 --report-hashrate --HWMON 1 -P pool1 pool2```

On start, v0.16.0.rc0 reports:  
`l 11:21:23 cl-1     Loading binary kernel /mnt/projects/mining/software/ethminer/build.16.rc0/ethminer/kernels/ethash_ellesmere_lws256.bin`  
`X 11:21:23 cl-1     Failed to load binary kernel: /mnt/projects/mining/software/ethminer/build.16.rc0/ethminer/kernels/ethash_ellesmere_lws256.bin`

There is no `kernels` folder in this location. and no `ethash_ellesmere_lws256.bin` was built.
 
**To Reproduce**
1. Compile per instructions in README.md
2. Start ethminer with above command.
4. See error in log and speed in log 

**Expected behavior**
similar or better performance when compared to older version.

**Desktop**
- Operating System: Ubuntu 18.04
- Hardware: RX580 3x Sapphire 8GB, 1x Asus 4GB
- Ethminer Version: v0.16.0.rc0

I understand that most of the active devs have nvidia rigs.  I have 2 rigs with total 12 AMD rx 580/570.  If there is anything I can do to help the AMD support please let me know.

**Comment by lesjokolat** [comment]
I ve tried but cant use this tool successfully on Windows.

https://github.com/CLRX/CLRX-mirror

Its a kernel compiler and in theory one could build custom kernels like the ones missing. Personally documentation is so advanced most people(myself included) get lost. its lacking more info around examples and syntax to create kernels...

**Comment by AntoniosHadji** [comment]
I found the kernels after following these steps:  

1. `git clone git@github.com:CLRX/CLRX-mirror.git`
2. `cd CLRX-mirror`
3. `mkdir build`
4. `cd build`
5. `cmake .. -DBUILD_TESTS=ON -DBUILD_SAMPLES=ON -DBUILD_DOCUMENTATION=ON`
6. `make`
7. `sudo make install`

Then I recompiled ethminer.
The kernels are in the top level git directory `/libethash-cl/kernels/bin`

I'm now seeing the same speeds and about +5 watts per card (+20 watts over 4 cards)

**Comment by ddobreff** [comment]
I'd suggest stick to --cl-local-work 64-192, a bit less power but hashrate remains the same.

**Comment by AntoniosHadji** [comment]
I tried `--cl-local-work 64` and  `--cl-local-work 192`. neither changed the power consumption significantly.   
the difference looks closer to +4 watts per card.

**Comment by ddobreff** [comment]
We are aware of the increased power and as of now none of devs is looking into power reducing solution, but its already discussed.

**Comment by AntoniosHadji** [comment]
I'm closing this issue since the power consumption is known and not a bug.
