### ISSUE TITLE
Mine one block, force a fork

### ISSUE THREAD

**Issue by dpc** [ethereum-mining/ethminer#1522]
**Is your feature request related to a problem? Please describe.**

I'd like to write a testing framework for stuff that integrates (runs on top of)  ethereum node. To ensure correct handling of of corner cases I'd like to simulate things like eg. reorgs.

I was googling for regtest for ethereum and I've found things like: https://wiki.parity.io/Private-development-chain . It seems it covers what I need from a node itself, but I need to tightly control mining.

I need to be able to:

* mine exactly one block on demand
* force a fork - make the miner mine on top of an arbitrary block instead of a "longest one"

**Describe the solution you'd like**
I would like two command line arguments:

* `stop-after-one-block`
* `force-height=12345`

that would accomplish the above.

**Describe alternatives you've considered**
I haven't considered much and I have no idea about ETH mining. I'm open for suggestions.

**Comment by MariusVanDerWijden** [comment]
If you're developing smart contracts, you can just use a cpu miner, there's no need to run a gpu miner. All major clients (geth, parity) have a cpu miner builtin for test chains. They can probably add a feature to force the cpu miner to generate forks. 

I set up a Clique PoA network with geth today with 30 nodes locally that produces forks almost every second block. Maybe this would be a short term fix for you. But having a feature to produce forks in the clients for testing purposes would be neat.
