### ISSUE TITLE
--api-password option not working

### ISSUE THREAD

**Issue by AlexMalex** [ethereum-mining/ethminer#1530]
--api-password option not working, 
configuration : Windos 10, Windows 7 GTX 1060, 1070 Ethminer Version  0.16rc0 Windows version
client - Claymore Remote manager 3.8

bug in code ApiServer.cpp ?

char input_copy[max_length] = {0};
char password_copy[max_length] = {0};

initialized only first byte, max_length-1 bytes remain uninitialized

**Comment by StefanOberhumer** [comment]
Ethminers Api password handling is not compatible with claymores.
I think you can't use `Claymore Remote manager 3.8` if you've set an Api password in ethminer!

**Comment by AlexMalex** [comment]
Looked at the asm code - I was wrong, sorry.
