### ISSUE TITLE
Using -P instead of -S and -O for Nanopool not working

### ISSUE THREAD

**Issue by SoulCheese** [ethereum-mining/ethminer#1537]
I'm a big novice when it comes to this, but from what I can gather my string *should* work. When using v14 release with the -S and -O flags it works fine. Attempting to use -P with v15 and above doesn't work for me. The string I'm attempting to use is:

ethminer.exe -U -P stratum+tcp://WALLET@etc-us-east1.nanopool.org:19999/WORKER/EMAIL

I have also tried it with a '.' instead of a '/' to delineate the worker and e-mail. Maybe I'm missing something, but I've let the v15 miner run (I have two) with another using version v14 with the -S/-O method, and the -S/-O method is checking in just fine within 30 minutes or so and my -P worker never does.

I've seen a post or two with similar behavior before, but I didn't really see any resolution. I'm curious for anyone using Nanopool what your string looks like if it's working post version 14.

**Comment by AndreaLanfranchi** [comment]
Maybe it's because you're using port `19999` which does not exist.
Nanpool port is `9999` (without the additional 1)

You can find an exhaustive list of pools examples in our [documentation section](https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md)

**Comment by SoulCheese** [comment]
Wtf?

Did they change this? I have used and still use port 19999 with the -S -O flags and it works?

Or is this a protocol change in general?

Strange, thanks for the documentation though I'll try it now.

**Comment by AndreaLanfranchi** [comment]
Sorry my fault. Didn't notice you're on ETC and not ETH.
Yes for ETC port 1999 is valid.

**Comment by SoulCheese** [comment]
Ah okay, that makes sense.
For whatever reason, doesn't seem to check into nanopool with the string I gave you.

**Comment by AndreaLanfranchi** [comment]
What exactly does not work ?
Can you post a log ?
Which version of ethminer are you on ? Please report the output of `ethminer -V`

**Comment by AndreaLanfranchi** [comment]
>  Specifically, my Nanopool wallet URL, where the miners check in, does not show the miner checking in when using -P.

I really don't understand what you mean by that.

For the log I don't need any specific log.
Simply copy and paste here what you see on screen

**Comment by SoulCheese** [comment]
https://etc.nanopool.org/account/0x37b9f47afbeb26De6073F027a5d0cBE042d49AFA

That is my wallet address, where the miners check in to report hashrates, etc. That's what I'm referring to.

**Comment by AndreaLanfranchi** [comment]
I see there are 2 miners there.
What is missing ?

What is the exact value of -P you enter ? (the full value)

**Comment by SoulCheese** [comment]
Had a storm come through so I powered everything off. The link I sent you - you would have noticed one of the miners not checking in recently. Since they've been off, the last share is about 13 hours for both, so it'll be more obvious now.

CheeseRig1 will be running release version 15, the problem version. CheeseRig2 will be running release version 14, which works. I'm starting both now.

The entire script I'm running on the version (15) that does not work is:

@echo off

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

ethminer.exe --farm-recheck 10000 -U -P stratum+tcp://0x37b9f47afbeb26De6073F027a5d0cBE042d49AFA@etc-us-east1.nanopool.org:9999/CheeseRig1/*******@*******.***

Note that the e-mail address is all lower case letters, no numbers or symbols.

The farm-recheck value may be pointless, I found it on a forum a while back. I just started the miners so give it a little time, you seem pretty active on here, which is appreciated.

**Comment by SoulCheese** [comment]
I just noticed the port was wrong from when I changed it previously. The port has been corrected at 19999.

**Comment by AndreaLanfranchi** [comment]
Did you solve your problem ?

**Comment by SoulCheese** [comment]
No sir. If you check the Nanopool link I sent earlier, CheeseRig1 has still not checked in and I have left it running. I'm running the exact code I pasted in my comment with the exception that I corrected the port number and blanked out my e-mail address.

**Comment by lesjokolat** [comment]
Since you are using v 14/15 what if try to add stratum #:

ethminer.exe -U -P stratum1+tcp://0x37b9f47afbeb26De6073F027a5d0cBE042d49AFA@etc-us-east1.nanopool.org:19999/CheeseRig1/@.***

**Comment by SoulCheese** [comment]
Heyyyyyyyyyy! It's checking in!

**Comment by SoulCheese** [comment]
Thanks to @AndreaLanfranchi and @lesjokolat, this is now solved!
