### ISSUE TITLE
Duplicate repositories are confusing users

### ISSUE THREAD

**Issue by JHGitty** [ethereum-mining/ethminer#154]
We have currently two repositories:

1. Genoil's cpp-ethereum "ethminer": https://github.com/Genoil/cpp-ethereum
2. This new repository here: https://github.com/ethereum-mining/ethminer

The code is not the same. One repo contains commits that are 17 days old, the other contains code that is 7 days old.

As you can see there are **new** pull requests in both repositories so the users don't know where to submit them.

Please clarify which repository will contain the newest code and which is obsolete. Please also change the README of the obsolete repository to let the user know what repository should be used.

Please also check all pull requests of all repositories to be sure that all user-improvements are included inside the newest version.

@chfast Can you explain what is happening here? What is the best and newest repo?

**Comment by zackoch** [comment]
For the record, genoli shut down his repo and pointed to chfasts saying it was better...

Then two days later deleted all the open issues and was back in business. I had already moved on to chfasts. I'm guessing since nobody was really helping with issues genoli was frustrated.

**Comment by chfast** [comment]
The other one is not maintained, so it is almost impossible to get new code being merged there. And in this case I cannot afford waiting for my code be reviewed and accepted.

I'm happy to add more maintainers here, but I don't see any candidates so far.

**Comment by chfast** [comment]
We should add this question to FAQ in the end.

**Comment by EoD** [comment]
What about adding @Genoil for example?

**Comment by chfast** [comment]
My impression is (maybe wrong) that @Genoil is not interested in maintaining any ethminer fork any more.

**Comment by JHGitty** [comment]
The README cointains "Then hugely improved in Genoil's fork.".
I think we should change this sentence because it's confusing the users.

Can somebody update the README to explain that this is the new repository?

**Comment by chfast** [comment]
@JHGitty please send a pull request with the updated README (you can just edit the file directly on GitHub).

**Comment by jimmykl** [comment]
Hi @chfast @JHGitty I went ahead and made the changes outlined above with https://github.com/ethereum-mining/ethminer/pull/191 I also added an FAQ re: --cuda-parallel-hash since that seems to come up on gitter regularly.
