### ISSUE TITLE
Infos

### ISSUE THREAD

**Issue by SkyDr4k3** [ethereum-mining/ethminer#1547]
I'm a total nob. I downloaded all the zips but can't start one :(
Nvidia win7
What should i do?

**Comment by lesjokolat** [comment]
Once you have downloaded and extracted archive, 
Find out what pool you are going to mine against. Main page has a bunch examples...
Then run in dos window or create a bat start file.
Use the read me for some examples info.

When ready if still erring post your startup command line and log errors...

Takes some finalgling and work....

Also what model GPU(s) do you plan to use?

**Comment by SkyDr4k3** [comment]
thank you, really appreciate.

Right now i use a 1050ti
