### ISSUE TITLE
How to select version to build

### ISSUE THREAD

**Issue by ykhuat** [ethereum-mining/ethminer#1548]
Hi,

Really sorry for noob question here.
I am using Ubuntu 16.04, Cuda 9.1

I successful Build a latest "Pre-release" (ethminer 0.16.0rc1) by following document on web.

Question is:-

If i want to build latest stable release (ethminer 0.15.0),

how was the step to do it..?

TQ very much for help..

**Comment by Rem559** [comment]
go to https://github.com/ethereum-mining/ethminer/releases  and download there  source code or the desired build you need

**Comment by jean-m-cyr** [comment]
On a 16.04 system it's pretty straightforward. Just follow the instructions at https://github.com/ethereum-mining/ethminer/blob/master/docs/BUILD.md

**Comment by ykhuat** [comment]
@jean-m-cyr 

Thank You very much for help, now I can build stable release follow step below, hope it will help other people as well:-

git clone git@github.com:ethereum-mining/ethminer.git
cd ethminer
git submodule update --init --recursive
git checkout tags/v0.15.0
mkdir build
cd build
cmake -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-9.1 ..
cmake --build . --config release
