### ISSUE TITLE
Include updates from ethereum/cpp-ethereum

### ISSUE THREAD

**Issue by JHGitty** [ethereum-mining/ethminer#155]
I have seen that this project is (of course) using a few libraries from the official ethereum project (ethereum/cpp-ethereum).

Is somebody updating them in our repository here to be sure to use the latest and best code - even for the best performance? Or do we still use very old code here?

Is anybody monitoring the changes from the official ethereum client to improve our miner too?

**Comment by zackoch** [comment]
Scary.

**Comment by piotr-dobrogost** [comment]
@chfast Could you please answer to OP's questions?
