### ISSUE TITLE
A question about DAG

### ISSUE THREAD

**Issue by FishSeeker** [ethereum-mining/ethminer#1555]
Why is the resources generated in the algorithm called dag? I have not found any definitions of edges and vertices. When calling the search cl kernel to hash, is it traversing the dag?

**Comment by FishSeeker** [comment]
First of all, thank you for your answer. I have read the wiki about ethash, but I still have some questions.
This code is a loop that randomly accesses the data set. How to ensure that the entire dag is traversed, and I don't see any relationship with the graph.
@AndreaLanfranchi 
```
# mix in random dataset nodes
    for i in range(ACCESSES):
        p = fnv(i ^ s[0], mix[i % w]) % (n // mixhashes) * mixhashes
        newdata = []
        for j in range(MIX_BYTES / HASH_BYTES):
            newdata.extend(dataset_lookup(p + j))
        mix = map(fnv, mix, newdata)

**Comment by AndreaLanfranchi** [comment]
They keyword is "randomly". Not all the DAG is traversed. Only the points resulting from prev steps.

**Comment by FishSeeker** [comment]
@AndreaLanfranchi thx a lot!!

**Comment by chfast** [comment]
The DAG name is probably not very accurate and it comes from the way this big dataset is created (every item depends on number of item from a smaller cache). But in the end Ethash is not traversing anything, it just access individual indexed items in pseudo-random fashion.

**Comment by AndreaLanfranchi** [comment]
This may be useful too

https://en.wikipedia.org/wiki/Directed_acyclic_graph

**Comment by gennadiv** [comment]
WITH THE INCREASE IN DAG PRODUCTION FOR AMD CARDS BECAME LESS - LESS BALLS
