### ISSUE TITLE
Compiled version low speed

### ISSUE THREAD

**Issue by KL0nLutiy** [ethereum-mining/ethminer#156]
Hello. Compiled ethminer local and the speed is 2 mhash per gtx 1070. Why is it so?

**Comment by haka002** [comment]
Try to add -U ootion, because the default is -G for amd gpus.

**Comment by KL0nLutiy** [comment]
Already with -U and I compile with out opencl support

**Comment by jimmykl** [comment]
Are you running Windows? If so you should install Anniversary or Creator's update and latest nvidia drivers.

**Comment by KL0nLutiy** [comment]
Fixed with build command `cmake -G "Visual Studio 14 2015 Win64" -H. -Bbuild -DETHASHCUDA=ON`

**Comment by jimmykl** [comment]
Hi @KL0nLutiy glad you fixed it, if there's nothing more to add could you please close the issue? Thanks!

**Comment by jimmykl** [comment]
@KL0nLutiy Bump

**Comment by simonkern** [comment]
This bit me as well, it might be a good idea to put that into the readme...
