### ISSUE TITLE
SOLUTIONS

### ISSUE THREAD

**Issue by gennadiv** [ethereum-mining/ethminer#1562]
WHY THE GAME SEARCHES SOLUTIONS DECLINED FOR AMD CARDS - FEWER
WITH THE INCREASE IN DAG PRODUCTION FOR AMD CARDS BECAME LESS - LESS BALLS

**Comment by AndreaLanfranchi** [comment]
So what is the question ?

**Comment by gennadiv** [comment]
WHY FEWER BALLS?

**Comment by AndreaLanfranchi** [comment]
I dont' understand you.
Fewer what ? What are the balls you're referring to ?

**Comment by AndreaLanfranchi** [comment]
Are you complaining about performance decrease as DAG size increases ?
Well there is nothing we can do about: the higher the memory occupation the higher the load on the GPU.
It's written in the algo.

**Comment by gennadiv** [comment]
WHY DECREASED PRODUCTION ETHEREUM --- REDUCING PERFORMANCE HIGH 
 NOTHING HAS CHANGED . BUT DECREASED PRODUCTION OF ETHEREUM .SORRY FOR BROKEN ENGLISH

**Comment by AndreaLanfranchi** [comment]
You're totally uncomprehensible.

**Comment by gennadiv** [comment]
THE QUESTION CAN BE CLOSED
