### ISSUE TITLE
ethminer: /lib64/libc.so.6: version `GLIBC_2.18' not found

### ISSUE THREAD

**Issue by gordan-bobic** [ethereum-mining/ethminer#1567]
It looks like the binary build was linked against an unreasonably new glibc. This makes it not work on many still supported LT distributions.

Please consider linking against at most 2.17 to ensure compatibility with CentOS 7.

**Comment by chfast** [comment]
I will work on this, but does CentOS has any newer compiler than GCC 4?

**Comment by gordan-bobic** [comment]
Not easily.

**Comment by chfast** [comment]
I don't think it is doable, because Ubuntu 16.04 ships with 2.23 and Debian Stretch with 2.24. I think the only way to handle this is to link glibc statically. We link libstdc++ statically already.

**Comment by gordan-bobic** [comment]
I don't see a problem with static linking.

**Comment by chfast** [comment]
I tried some combination of flags, but I don't know how to link libc statically. If you are able to do it, let me know.
