### ISSUE TITLE
What's the difference between this fork and Genoil's?

### ISSUE THREAD

**Issue by Immortalin** [ethereum-mining/ethminer#157]

**Comment by JHGitty** [comment]
Duplicate question, see #154

**Comment by EoD** [comment]
There are a lot of commits by chfast in Genoil's repository: https://github.com/Genoil/cpp-ethereum/commits?author=chfast

And there are a few commits by Genoil in chfast's repository: https://github.com/ethereum-mining/ethminer/commits?author=Genoil

**Comment by chfast** [comment]
Duplicate of #154.
