### ISSUE TITLE
The new miner code is very bad

### ISSUE THREAD

**Issue by DekInc** [ethereum-mining/ethminer#1575]
**Describe the bug**
omg its really bad, all the shares are down by 20%, it is very bad,
i verified the code and now you are changing the nonce in every job,
this really is not working at all... the last version was pretty good and a lot more 
better than glaymore

**To Reproduce**
run with default parameters

**Expected behavior**
-20% shares

**Screenshots (Optional)**
[img]https://i.imgur.com/eZGbfKG.png[/img]

**Desktop (please complete the following information):**
blue screen 10
4x1070 (love nvidia)
- Ethminer last commit in dev3

**Comment by invidtiv** [comment]
How long did you run the miner for ?

**Comment by AndreaLanfranchi** [comment]
Invalid.
