### ISSUE TITLE
ethminer 0.16 Setup Guide

### ISSUE THREAD

**Issue by 851d229** [ethereum-mining/ethminer#1579]
Hi everyone,

I want to mine with ethpool with Ethminer version 0.16.  I only got the binaries, but no installation guide at all .... I'm new to this application and want to get a good installation guide. I know we must create a batch file but no information on that on the net....  thank you for your help !

**Comment by AndreaLanfranchi** [comment]
Interesting question.
The matter of creating a batch file has been deeply discussed nowadays due to it's extremely complex architecture. Nevertheless you can find some useful pages written by MIT experts like this one : 

https://fossbytes.com/what-is-a-batch-file-in-windows-how-to-create-a-batch-file/

To use ethminer in a batch file at some point you have to enter a line like this:

```
ethminer.exe -P <some-uncomprehensible-garbage>
```
Where `<some-uncomprehensible-garbage>` can be replaced by any, **any**, value you can find here according to your needs.

https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md#ethpoolorg

**Comment by 851d229** [comment]
But the program ethminer.exe MUST be used with command line ...  meanwhile, I have continued to test some command line with the help of the program (ethminer.exe -h)  and it seems to work, but not perfect.  I missed the Failover parameter, don't know how to use it, and also how can I pass parameters to modify the GPU clock and memory ...

Alos, right now I use NANOPOOL and it works very well, I want to compare it with ETHPOOL to know what Pool is the most performant...

**Comment by AndreaLanfranchi** [comment]
> But the program ethminer.exe MUST be used with command line

That is exactly what a batch file does.

> I missed the Failover parameter,

Simply add another `-P` argument

> and also how can I pass parameters to modify the GPU clock and memory ...

Ethminer does not apply any overclocking. You have to overclock your cards **before** running ethminer.

> right now I use NANOPOOL and it works very well, I want to compare it with ETHPOOL

Right now you're comparing apples with oranges. ETHPOOL has a payout mechanism completely different from any other pool: it's the only in his class. NANOPOOL **might** compared to ETHERMINE.ORG (even though the latter uses a lower diff).

**Comment by 851d229** [comment]
Ok thank you for the failover parameter!

I was wondering if I could compare the number of Etherum gained with Ethpool vs Nanopool, on a certain period of time (1 week),  I could see what is the most profitable....  I know that pools are very fluctuated...

**Comment by AndreaLanfranchi** [comment]
> I was wondering if I could compare the number of Etherum gained with Ethpool vs Nanopool, on a certain period of time (1 week),

You actually can't : Ethpool uses a predictable payout scheme, Nanopool is PPLNS.

In other words. Unless you have a very high hashrate it is possible you get zero in a week on Ethpool.

**Comment by 851d229** [comment]
Ok thank you for this information, I will not continue anymore with this pool, my hashrate is probably not enough ...
