### ISSUE TITLE
Random sporadic freezing 

### ISSUE THREAD

**Issue by nguylb73** [ethereum-mining/ethminer#158]
My rig seems to be able to mine for hours or almost a full day at a time, then windows randomly freezes and the GPU fans continue to run as if it's locked. Not able to get display or able to do RDP session at this state.  Power cycle is needed...

I have the following setup:
Windows 10
celeron 3900
4 GB of ram
MSI z170a SLI Plus
EVGA 1200 watt SuperNova
6 x 1070 GB windforce OC

While stable CPU is at 10-20% and Memory at 50-60%. CPU only spikes 99% during ethminer initialization. I'm wondering if anyone is running a similar setup mainly proc type and ram amount and is able to run stable for days or weeks.. or is experiencing same issue as I? Was thinking of replacing the CPU for a i3 and bumping up the ram to 8GB.. but would hate go down the costly option when if it's a GPU locking problem..

window eventview log that seems to happen during lockup:
Log Name:      System
Source:        Microsoft-Windows-Kernel-Power
Date:          7/15/2017 3:54:44 AM
Event ID:      41
Task Category: (63)
Level:         Critical
Keywords:      (70368744177664),(2)
User:          SYSTEM
Computer:      DESKTOP-RLNVM4U
Description:
The system has rebooted without cleanly shutting down first. This error could be caused if the system stopped responding, crashed, or lost power unexpectedly.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Kernel-Power" Guid="{331C3B3A-2005-44C2-AC5E-77220C37D6B4}" />
    <EventID>41</EventID>
    <Version>5</Version>
    <Level>1</Level>
    <Task>63</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000400000000002</Keywords>
    <TimeCreated SystemTime="2017-07-15T10:54:44.367310000Z" />
    <EventRecordID>1377</EventRecordID>
    <Correlation />
    <Execution ProcessID="4" ThreadID="8" />
    <Channel>System</Channel>
    <Computer>DESKTOP-xxxx</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="BugcheckCode">0</Data>
    <Data Name="BugcheckParameter1">0x0</Data>
    <Data Name="BugcheckParameter2">0x0</Data>
    <Data Name="BugcheckParameter3">0x0</Data>
    <Data Name="BugcheckParameter4">0x0</Data>
    <Data Name="SleepInProgress">0</Data>
    <Data Name="PowerButtonTimestamp">0</Data>
    <Data Name="BootAppStatus">0</Data>
    <Data Name="Checkpoint">0</Data>
    <Data Name="ConnectedStandbyInProgress">false</Data>
    <Data Name="SystemSleepTransitionsToOn">0</Data>
    <Data Name="CsEntryScenarioInstanceId">0</Data>
    <Data Name="BugcheckInfoFromEFI">true</Data>
  </EventData>
</Event>

**Comment by orkblutt** [comment]
I guess you should tweak your oc settings. Maybe a less anthousiast oc could fix this issue. It did for me at least.
What are your settings?

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by nguylb73** [comment]
@orkblutt

Thanks for helping. Actually I left my GPU stock, no OC at all. What proc and ram size you are using?

**Comment by derubm** [comment]
reduce power cost of your GPU´s to 64 %, should not harm your hashrate in any way, Windows kernelfails often happen when the system gets not enough power from the PSU. on the other hand even with lower power limit of the GPU´s you can raise GPU memory to have a faster hashing rig. 1070 can pull 170 watts each (on non overclocked settings with no power reduction) - reduce to 63 % get higher memory speed and your system should have enough power to not crash.

**Comment by nguylb73** [comment]
@derubm that makes a lot of sense. Let get back with you once I play around and test. Much Appreciated!

**Comment by nguylb73** [comment]
@derubm after adding 4GB + of ram and setting the virtual memory to 20gb. My system is  now running stable. The windows eventvwr is probably just generated after I hard cycle my device when frozen, sorry I gave a non relevant event.  

I will still look into your advice to reduce power limit, to save on energy cost. Seems to messed with my Hash and not run stable, I'll play with it a bit more to get a better understanding. I'm using MSI Afterburner, do you mind sharing what you are using?

**Comment by derubm** [comment]
![image](https://user-images.githubusercontent.com/6720202/28302408-6315e722-6b8d-11e7-9e34-3b82d5d6300d.png)
This is my save setting for a Zotac MSI 1060 Mini with Samsung gddr5. memory settings can greatly vary
