### ISSUE TITLE
Socket read failed: stream truncated terminate

### ISSUE THREAD

**Issue by LyqSpace** [ethereum-mining/ethminer#1581]
I've been using etherminer on ethermine.org for 5 hours. Everything works well. But after 5 hours, it broken up, says 

>  X 00:35:12 stratum  Socket read failed:stream truncated terminate called after throwing an instance of 
 boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  shutdown: Transport endpoint is not connected
Aborted (core dumped)

Run scripts:
 `ethminer -U -P stratum1+ssl://xxxxx@us2.ethermine.org:5555 --cuda-parallel-hash 4`

Screenshots:
![image](https://user-images.githubusercontent.com/8945602/45597317-e4823300-b98f-11e8-8a74-74a62b64fcec.png)

Environment:
Etherminer: 0.15.0
Ubuntu 18.04 64-bit
Cuda: release 9.1, V9.1.85
GeForce GTX 1070
Driver: 396.54

I know it is difficult to reproduce the error. Thank you for your time.

**Comment by AndreaLanfranchi** [comment]
Use 0.16

**Comment by LyqSpace** [comment]
> Use 0.16

I will use it. Thanks for your help.
