### ISSUE TITLE
0.16 final version is causing one of my AMD RX570 to drop Mh/s

### ISSUE THREAD

**Issue by jbramsden** [ethereum-mining/ethminer#1582]
I was previously using 0.16 beta 2 which worked really well and all my cards where stable. 
I've just upgraded to 0.16 final version and after about 5 mins I have one card that will continue to drop in Mh/s until it hits 0.  I used to have this issue prior to 0.15

Output of console. GPU1 starts off on 29.60 GPU0 & GPU2 start off on 29.35
m 12:47:13 ethminer-16-fin Speed 87.71 Mh/s gpu0 29.34 gpu1 29.03 gpu2 29.35 [A3] Time: 00:06
 i 12:47:14 stratum  Job: #57f84859… eth-eu2.nanopool.org [51.15.55.100:9999]
 m 12:47:19 ethminer-16-fin Speed 87.75 Mh/s gpu0 29.36 gpu1 29.02 gpu2 29.36 [A3] Time: 00:06
 m 12:47:25 ethminer-16-fin Speed 87.71 Mh/s gpu0 29.34 gpu1 29.02 gpu2 29.35 [A3] Time: 00:06
 i 12:47:31 cl-2     Solution: 0x808c88471114ecdc
 i 12:47:31 stratum  **Accepted  35 ms. eth-eu2.nanopool.org [51.15.55.100:9999]
 m 12:47:31 ethminer-16-fin Speed 87.65 Mh/s gpu0 29.33 gpu1 29.00 gpu2 29.33 [A4] Time: 00:07
 m 12:47:37 ethminer-16-fin Speed 87.75 Mh/s gpu0 29.39 gpu1 28.96 gpu2 29.40 [A4] Time: 00:07
 m 12:47:43 ethminer-16-fin Speed 87.67 Mh/s gpu0 29.39 gpu1 28.88 gpu2 29.40 [A4] Time: 00:07
 m 12:47:49 ethminer-16-fin Speed 87.78 Mh/s gpu0 29.40 gpu1 28.98 gpu2 29.40 [A4] Time: 00:07
 m 12:47:55 ethminer-16-fin Speed 87.77 Mh/s gpu0 29.40 gpu1 28.98 gpu2 29.40 [A4] Time: 00:07
 i 12:47:55 stratum  Job: #df42bcda… eth-eu2.nanopool.org [51.15.55.100:9999]
 m 12:48:01 ethminer-16-fin Speed 87.59 Mh/s gpu0 29.34 gpu1 28.90 gpu2 29.35 [A4] Time: 00:07
 i 12:48:03 stratum  Job: #9ed0568a… eth-eu2.nanopool.org [51.15.55.100:9999]
 m 12:48:07 ethminer-16-fin Speed 87.60 Mh/s gpu0 29.35 gpu1 28.89 gpu2 29.35 [A4] Time: 00:07
 m 12:48:13 ethminer-16-fin Speed 87.61 Mh/s gpu0 29.36 gpu1 28.88 gpu2 29.37 [A4] Time: 00:07

To run Etherminer I am using: 	
nohup taskset --cpu-list 1,2 ./ethminer-16-final --farm-recheck 200 -G -P stratum1+tcp://0xb6a169a1421a34af008bc8f0061629fc76c06f25@eth-eu2.nanopool.org:9999/mine1/jason@bramsden.com --cl-local-work 256 --cl-global-work 20480   --api-bind 127.0.0.1:3333 & >nohup.out

For the time being, I'm going to go back to using 0.16 beta 2.

Any ideas what can be causing this.

GPU1 is using a slightly different BIOS where I have clocked the memory to run higher.

**Comment by AndreaLanfranchi** [comment]
Your printed log does not depict the issue.

> I have one card that will continue to drop in Mh/s until it hits 0. I used to have this issue prior to 0.15

Which card ? The one with higher OC or the other ?

**Comment by jbramsden** [comment]
Sorry for not depicting the issue correctly. I will rerun the latest version to show the logs with it going down to 0.
The card that this occurs on is GPU1 which is the one with the higher OC. AMD RC570 Strix Gaming OC.  The other 2 are almost identical but have are not the OC version of the card.

**Comment by jbramsden** [comment]
I've been tracking this for running over 300 minutes and GPU1 is showing a gradual downward trend. I'm going to keep this running until GPU1 goes down to 0 Mh/s and I will update you.
![image](https://user-images.githubusercontent.com/14159396/45683418-7b3f2300-bb3b-11e8-8c60-b09ba6f160f7.png)

**Comment by jbramsden** [comment]
After 24 hours the card has not dropped to 0, so I was incorrect to raise this as an issue. As after 1424 minutes card GPU 1 is still around 28 Mh/s, I'm closing this as a none issue.

**Comment by jbramsden** [comment]
Just to add to this issue, after 29 hours of running ethminer 0.16 the Mh/s of card0 has jump up to 29.400 Mh/s.

![image](https://user-images.githubusercontent.com/14159396/45762536-7905c300-bc26-11e8-8582-2c6b9a1fb1fd.png)
