### ISSUE TITLE
How to fix too many jobs?

### ISSUE THREAD

**Issue by DekInc** [ethereum-mining/ethminer#1583]
How to fix this?

[img]https://i.imgur.com/SLXBZjT.png[/img]

too many jobs for the miner, i think it can't handle so many

**Comment by AndreaLanfranchi** [comment]
There is no fix for that.
It's the pool pushing jobs on behalf aof transactions and blocks frequency.
You have to deal with it.

**Comment by AndreaLanfranchi** [comment]
Remember that it's perfectly expected a single miner does not find solutions for the majority of jobs.

**Comment by DekInc** [comment]
> Remember that it's perfectly expected a single miner does not find solutions for the majority of jobs.

@AndreaLanfranchi  how can i change this? i am using stratum, can i change it to other type?

**Comment by AndreaLanfranchi** [comment]
You can't.
It's in the mining logic. You hardware (nobodies hardware) have enough hashing power to find a solution at every job.
