### ISSUE TITLE
Ethminer AMD ROCm driver issue

### ISSUE THREAD

**Issue by SigiSinatra** [ethereum-mining/ethminer#1584]
Does miner support amd linux ROCm dirver (linux ubuntu 16.04) ?
I can't start it

**Comment by AndreaLanfranchi** [comment]
No we never tested against ROCm driver.
Only native AMD and NVIDIA drivers.

**Comment by ernstp** [comment]
Works fine with ROCm btw.

**Comment by tholu** [comment]
@ernstp How many GPUs are you using with ROCm? I can only get 2 of 6 recognized because of the PCIe atomics issue.

**Comment by ernstp** [comment]
> @ernstp How many GPUs are you using with ROCm? I can only get 2 of 6 recognized because of the PCIe atomics issue.

Just a single on my desktop, nothing serious. :-)
