### ISSUE TITLE
falling back to primary pool

### ISSUE THREAD

**Issue by DekInc** [ethereum-mining/ethminer#1585]
feature
the secondary pool sucks, so maybe it can be done that after 10 min of using secondary pool
the miner fall back to use primary pool, by example eu1.ethermine.org:4444 is very bad and not respond after 2 seconds, then the miner try eu1.ethermine.org:14444, but it's maybe a problem with internet, so maybe you can add a parameter like --PoolFallBackTime 10, so the miner can connect again to primary pool after 10 minutes.

**Comment by AndreaLanfranchi** [comment]
So what is this for ?

```
 --failover-timeout INT in [0 - 999]=0
                              Set the amount of time in minutes to stay on a failover pool before trying to reconnect to primary. If = 0 then no switch back.
```

Read guys ... read before asking !
