### ISSUE TITLE
--display-interval 1 sets display interval to 2 seconds

### ISSUE THREAD

**Issue by rawdez** [ethereum-mining/ethminer#1589]
--display-interval 1 sets display interval to 2 seconds

**To Reproduce**
run ethminer 0.16.0 or newer (ethminer 0.17.0.dev0-2+commit.a860cb05) with --display-interval 1
_version without this bug: 0.16.0.dev2_

**Expected behavior**
--display-interval 1 should set display interval to 1 second

**Desktop (please complete the following information):**
- Windows 10
- GTX1060/RX460
- Ethminer Version 0.16.0 or newer

**Comment by StefanOberhumer** [comment]
Fixed.
