### ISSUE TITLE
CUDA_10.0.130 support

### ISSUE THREAD

**Issue by DeadManWalkingTO** [ethereum-mining/ethminer#1594]
Is CUDA 10 supported?

Has better or worse Hashrate (GTX 1060 / 1070)?

Thanks!

**Comment by MariusVanDerWijden** [comment]
https://github.com/ethereum-mining/ethminer/pull/1588

**Comment by MariusVanDerWijden** [comment]
Includes support for RTX 2080

**Comment by chfast** [comment]
CUDA 10 support added in #1614
