### ISSUE TITLE
Ethminer disapperears from pool after 0.16

### ISSUE THREAD

**Issue by evlo** [ethereum-mining/ethminer#1596]
Hi,

unfortunately I don't have any log or anything, as this happens kinda randomly.
I mine on ethermine. I use eu servers as primary, us as secondary.
All of my workers sometimes, ie. after days disappears from pool, by the time I read email notification I don't see anything in log. Only last time i noticed that worker is connected to us and not EU ethermine.
I did not have this issue in 0.15.

Maybe someone else can provide more debugging info. I will try to get some log next time, but it is kinda weird issue. 

Worker keeps hashing, but not for me ...

**Comment by AndreaLanfranchi** [comment]
> Worker keeps hashing, but not for me ...

What do you mean by keep "hashing" ? You see solutions being found and "accepted" messages ?

**Comment by evlo** [comment]
Yes exactly, i see accepted messages, but worker is not listed under worker in pool for hours.

**Comment by AndreaLanfranchi** [comment]
Which port are u using for ethermine.org ?

**Comment by AndreaLanfranchi** [comment]
You _**might**_ be suffering from a man-in-the-middle attack (eg. your internet provider detects connections to us.ethermine.org and simply redirects shares to their account).

Please re-do your tests using port 5555 (TLS)

**Comment by evlo** [comment]
I have checked, and i use port 5555. This issue did not happen until 0.16 so I thing it would be quite a coincidence if no change in 0.16 would be the cause.

**Comment by AndreaLanfranchi** [comment]
If you see `accepted` messages then ethminer is doing his job regularly: sends solution and receives positive response from pool.

If worker disappears from pool stats ... well must be investigated on pool's side.

**Comment by AndreaLanfranchi** [comment]
From 0.15 to 0.16 almost nothing has changed at stratum protocol level.

**Comment by lesjokolat** [comment]
what is your start bat or command line?

**Comment by StefanOberhumer** [comment]
Do you have your router opened to access ethminer's API from the internet ?
There are bots around that changes connections!
If it happens again you can check the active connection using the API [miner_getconnections](https://github.com/ethereum-mining/ethminer/blob/master/docs/API_DOCUMENTATION.md#miner_getconnections) !
