### ISSUE TITLE
Hanging GPU same Hashrate

### ISSUE THREAD

**Issue by Devil-of-Chaos** [ethereum-mining/ethminer#1600]
Hi there 

on current v0.16.0 if GPU (RX580 8GB Powercolor) hangs. The Hashrate stays the same but it‘s not Mining Powerusage is dropping. 

Ubuntu 18.04

**Comment by lesjokolat** [comment]
What is command line startup.

Any log or output to show drop of powerusage?

**Comment by AndreaLanfranchi** [comment]
No feed back.
Closing.

**Comment by be4i** [comment]
Hello, i have the same problem here is my config and log:

```
--report-hashrate --api-port 3334
--HWMON 1
--cuda
-P stratum1+tcp://ethaddress.rig06:x@eu1-eth.hiveon.net:4444
--nocolor
```
`Speed 172.57 Mh/s gpu0 21.57 65C 36% 86W gpu1 21.57 66C 32% 86W gpu2 21.57 65C 36% 85W gpu3 21.57 66C 37% 85W gpu4 21.57 65C 39% 85W gpu5 21.57 65C 35% 85W gpu6 21.57 63C 27% 84W gpu7 21.57 64C 27% 84W [A419+7] Time: 02:49`

`Speed 172.57 Mh/s gpu0 21.57 65C 36% 86W gpu1 21.57 66C 32% 86W gpu2 21.57 0C 0% gpu3 21.57 0C 0% gpu4 21.57 65C 39% 85W gpu5 21.57 0C 0% gpu6 21.57 0C 0% gpu7 21.57 64C 27% 84W [A419+7] Time: 02:49`

**Comment by AndreaLanfranchi** [comment]
It's always, I repeat, always a problem related to overclocking.
Lower your OC values on GPU 6 and you'll see.

**Comment by be4i** [comment]
Okay, but why is it slowing incorrect hashing power ? it should be lower i had 4 gpus missing,

**Comment by AndreaLanfranchi** [comment]
Because the whole thread for the GPU is stuck (waiting for a response from a GPU which is likely fallen off the bus) ! So it never refreshes the hashrate and keeps showing last received value.

**Comment by be4i** [comment]
Would't be a good idea in this scenario after some period of time to just reset the value to zero ? so it the reported hashrate is more accurate ?

**Comment by AndreaLanfranchi** [comment]
If you want to dirty your hands with the code ... you're welcome. Post a PR.
