### ISSUE TITLE
Avast virus detection

### ISSUE THREAD

**Issue by TheNeonBoy** [ethereum-mining/ethminer#1601]
Can't use avast thinks it's a virus "Win64:Malware-gen"
![image](https://user-images.githubusercontent.com/32601437/46098821-83dfcb00-c1c5-11e8-8eda-7bb4147926e2.png)

**Comment by AndreaLanfranchi** [comment]
Read carefully all theese  

- #1431 
- #1454 

there might be other issues. Nothing we can do about.

**Comment by DekInc** [comment]
> Can't use avast thinks it's a virus "Win64:Malware-gen"
> ![image](https://user-images.githubusercontent.com/32601437/46098821-83dfcb00-c1c5-11e8-8eda-7bb4147926e2.png)

Avast suck, try nod32
