### ISSUE TITLE
Feature request: time since last share 

### ISSUE THREAD

**Issue by rawdez** [ethereum-mining/ethminer#1603]
**Is your feature request related to a problem? Please describe.**
 it definitely would be useful for small miners to have time since last share displayed (as an option)

**Describe the solution you'd like**
when verbosity is set to, say, 4, display time since last share counter near accepted shares count like 
(m:ss)
e.g.
m 23:56:54 main     Speed 36.62 Mh/s gpu0 24.14 gpu1 12.48 A15 (3:27) Time: 00:26

and add command line option so if time since last share exceeds some set threshold ethminer will exit or switch to another pool

**Comment by AndreaLanfranchi** [comment]
Could you elaborate the rationale of such a request ?

**Comment by StefanOberhumer** [comment]
You could use [miner_getstatdetail](https://github.com/ethereum-mining/ethminer/blob/master/docs/API_DOCUMENTATION.md#miner_getstatdetail) for that.

**Comment by rawdez** [comment]
thank you for the hint, didn't know that. 
but for me  last update in seconds, for full worker not per GPU and shown constantly with output seems more handy and useful, perfectly aware that you all have more important work to do here, but it's just feature request and this option as I see it might be useful for small miners running just couple weak cards in home PCs. faster rigs fire up shares much more frequently, so don't really need it

thanks for all your great work by the way

**Comment by AndreaLanfranchi** [comment]
The log line is already enough clogged. 
API calls contains exhaustive infos.
Closing.
