### ISSUE TITLE
Not starting, sorry i'm new

### ISSUE THREAD

**Issue by spot88** [ethereum-mining/ethminer#161]
Sorry new to this.. Running windows 10, MSI 1060 6GB

My .bat file is like this:

`setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x36e937e9678334d9e2ef70390df5710b9cf23e6e.ethminer01 --cuda-parallel-hash`

**Comment by jimmykl** [comment]
@spot88 

You need to put a value for the --cuda-parallel-hash flag e.g. ```--cuda-parallel-hash 4``` Or don't add the flag at all – it will still use the default of 4 which provides the best performance for most people.

Also ```--farm-recheck 2000``` will slowdown the display of hashrate and make it easier to tell how the card is performing

**Comment by spot88** [comment]
@jimmykl Thanks a lot! Anything else i should add\remove?

**Comment by jimmykl** [comment]
@spot88 That should be enough to get you up and mining. If your question is sorted please close this issue. Thanks!
