### ISSUE TITLE
 Disconnected from eth.hashcity.org

### ISSUE THREAD

**Issue by gennadiv** [ethereum-mining/ethminer#1615]
i 07:35:14 stratum  Job: #d4df9793... eth.hashcity.org [138.201.198.155:7777]
 X 07:35:15 stratum  No response received in 2 seconds.
 i 07:35:15 main     Disconnected from eth.hashcity.org [138.201.198.155:7777]
cl 07:35:16 cl-0     No work. Pause for 3 s.
 i 07:35:16 main     Suspend mining due connection change...
cl 07:35:16 cl-1     No work. Pause for 3 s.
cl 07:35:16 cl-3     No work. Pause for 3 s.
cl 07:35:16 cl-2     No work. Pause for 3 s.
cl 07:35:16 cl-4     No work. Pause for 3 s.
cl 07:35:16 cl-5     No work. Pause for 3 s.
cl 07:35:16 cl-7     No work. Pause for 3 s.
cl 07:35:16 cl-6     No work. Pause for 3 s.
cl 07:35:16 cl-8     No work. Pause for 3 s.
 i 07:35:16 main     Selected pool eth.hashcity.org:7777
 i 07:35:16 stratum  Stratum mode detected: ETHPROXY Compatible
 i 07:35:16 stratum  Logged in!
 i 07:35:16 stratum  Established connection with eth.hashcity.org:7777 at  [138.201.1

**Comment by AndreaLanfranchi** [comment]
So ? What's the problem ? 

This line
```
X 07:35:15 stratum No response received in 2 seconds.
```
depicts a lag in pool responses.
Due to command line argument `--response-timeout` set by default to 2 seconds, ethminer disconnects and reconnects.

Perfectly normal.

**Comment by snajperro** [comment]
ethminer_run.sh[14951]:  i 04:37:24 ethminer Disconnected from eu1.ethermine.org [172.65.207.106:4444]
лют 18 04:37:24 rig2-TB250-BTC ethminer_run.sh[14951]:  i 04:37:24 ethminer No connection. Suspend mining ...
лют 18 04:37:24 rig2-TB250-BTC ethminer_run.sh[14951]:  i 04:37:24 ethminer No more connections to try. Exiting...
лют 18 04:37:24 rig2-TB250-BTC ethminer_run.sh[14951]:  i 04:37:24 ethminer Shutting down miners...
лют 18 04:37:25 rig2-TB250-BTC ethminer_run.sh[14951]:  i 04:37:25 main     Got interrupt ...
лют 18 04:37:25 rig2-TB250-BTC ethminer_run.sh[14951]:  i 04:37:25 ethminer Terminated!
лют 18 04:37:25 rig2-TB250-BTC kill[2060]: Usage:
лют 18 04:37:25 rig2-TB250-BTC kill[2060]:  kill [options] <pid> [...]
лют 18 04:37:25 rig2-TB250-BTC kill[2060]: Options:
лют 18 04:37:25 rig2-TB250-BTC kill[2060]:  <pid> [...]        
in my case it doesn't want to reconnect
i build on last src version
1)How can i config reconnect?
2)why doesn't  it reconnect again?

**Comment by snajperro** [comment]
> So ? What's the problem ?
> 
> This line
> 
> ```
> X 07:35:15 stratum No response received in 2 seconds.
> ```
> 
> depicts a lag in pool responses.
> Due to command line argument `--response-timeout` set by default to 2 seconds, ethminer disconnects and reconnects.
> 
> Perfectly normal.



> So ? What's the problem ?
> 
> This line
> 
> ```
> X 07:35:15 stratum No response received in 2 seconds.
> ```
> 
> depicts a lag in pool responses.
> Due to command line argument `--response-timeout` set by default to 2 seconds, ethminer disconnects and reconnects.
> 
> Perfectly normal.

what do you think?

**Comment by AndreaLanfranchi** [comment]
See https://github.com/ethereum-mining/ethminer/issues/1962
