### ISSUE TITLE
 id worker miner

### ISSUE THREAD

**Issue by gennadiv** [ethereum-mining/ethminer#1618]
The miner does not respond to the working code, but solutions come to the pool https://hashcity.org

 Solution: 0x66676f60809e04da
 i 17:44:15 stratum  Got response for unknown message id [109а253] Discarding...

**Comment by AndreaLanfranchi** [comment]
Please follow the template when opening issues.
We need to know : 

- ethminer version you're on
- operating system you're on
- full command line used to launch ethminer (including connection)
- full log

At first glance it's hashcity.org replying back with a martian message id 109а253

**Comment by gennadiv** [comment]
ethminer 0.17.0.dev0 - ethminer 0.16.1rc0  windows 10  
thminer.exe --farm-recheck 2000 -G -P stratum1+tcp://gennadiv:x@eth.hashcity.org:7777 --HWMON 1 --cl-local-work 256 --cl-global-work 32384

C:\Users\гена\Desktop\bin17>ethminer.exe --farm-recheck 2000 -G -P stratum1+tcp://gennadiv:x@eth.hashcity.org:7777 --HWMON 1 --cl-local-work 256 --cl-global-work 32384
 m 17:58:56 main     ethminer 0.17.0.dev0
 m 17:58:56 main     Build: windows/release
 i 17:59:13 main     Found suitable OpenCL device [Ellesmere] with 8,000 GB of GPU memory
 i 17:59:13 main     Found suitable OpenCL device [Ellesmere] with 4,000 GB of GPU memory
 i 17:59:13 main     Found suitable OpenCL device [Ellesmere] with 4,000 GB of GPU memory
 i 17:59:13 main     Found suitable OpenCL device [Tonga] with 4,000 GB of GPU memory
 i 17:59:13 main     Found suitable OpenCL device [Tonga] with 4,000 GB of GPU memory
 i 17:59:13 main     Found suitable OpenCL device [Ellesmere] with 4,000 GB of GPU memory
 i 17:59:13 main     Found suitable OpenCL device [Ellesmere] with 4,000 GB of GPU memory
 i 17:59:13 main     Found suitable OpenCL device [Ellesmere] with 8,000 GB of GPU memory
 i 17:59:13 main     Found suitable OpenCL device [Ellesmere] with 8,000 GB of GPU memory
 i 17:59:15 main     Configured pool eth.hashcity.org:7777
 i 17:59:15 main     Selected pool eth.hashcity.org:7777
 i 17:59:16 stratum  Stratum mode detected: ETHPROXY Compatible
 i 17:59:16 stratum  Logged in!
 i 17:59:16 stratum  Established connection with eth.hashcity.org:7777 at  [138.201.198.155:7777]
 i 17:59:16 stratum  Spinning up miners...
cl 17:59:16 cl-0     No work. Pause for 3 s.
cl 17:59:16 cl-1     No work. Pause for 3 s.
cl 17:59:16 cl-2     No work. Pause for 3 s.
cl 17:59:16 cl-3     No work. Pause for 3 s.
cl 17:59:16 cl-4     No work. Pause for 3 s.
cl 17:59:16 cl-5     No work. Pause for 3 s.
cl 17:59:16 cl-6     No work. Pause for 3 s.
cl 17:59:16 cl-7     No work. Pause for 3 s.
cl 17:59:16 cl-8     No work. Pause for 3 s.
 i 17:59:16 stratum  Job: #842495d4... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:16 stratum  Pool difficulty: 10.00K megahash
 i 17:59:16 stratum  New epoch 215
 i 17:59:17 stratum  Job: #842495d4... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:17 stratum  Job: #842495d4... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:17 stratum  Job: #842495d4... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:18 stratum  Job: #842495d4... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:19 stratum  Job: #842495d4... eth.hashcity.org [138.201.198.155:7777]
cl 17:59:19 cl-0     Platform: AMD Accelerated Parallel Processing
cl 17:59:19 cl-1     Platform: AMD Accelerated Parallel Processing
cl 17:59:19 cl-0     Device:   Ellesmere / OpenCL 2.0 AMD-APP (2671.3)
cl 17:59:19 cl-2     Platform: AMD Accelerated Parallel Processing
cl 17:59:19 cl-1     Device:   Ellesmere / OpenCL 2.0 AMD-APP (2671.3)
cl 17:59:19 cl-3     Platform: AMD Accelerated Parallel Processing
cl 17:59:19 cl-4     Platform: AMD Accelerated Parallel Processing
cl 17:59:19 cl-8     Platform: AMD Accelerated Parallel Processing
cl 17:59:19 cl-2     Device:   Ellesmere / OpenCL 2.0 AMD-APP (2671.3)
cl 17:59:19 cl-6     Platform: AMD Accelerated Parallel Processing
cl 17:59:19 cl-7     Platform: AMD Accelerated Parallel Processing
cl 17:59:19 cl-3     Device:   Tonga / OpenCL 2.0 AMD-APP (2671.3)
cl 17:59:19 cl-4     Device:   Tonga / OpenCL 2.0 AMD-APP (2671.3)
cl 17:59:19 cl-5     Platform: AMD Accelerated Parallel Processing
cl 17:59:19 cl-8     Device:   Ellesmere / OpenCL 2.0 AMD-APP (2671.3)
cl 17:59:19 cl-6     Device:   Ellesmere / OpenCL 2.0 AMD-APP (2671.3)
cl 17:59:19 cl-7     Device:   Ellesmere / OpenCL 2.0 AMD-APP (2671.3)
cl 17:59:19 cl-5     Device:   Ellesmere / OpenCL 2.0 AMD-APP (2671.3)
 i 17:59:19 cl-4     Adjusting CL work multiplier for 28 CUs.Adjusted work multiplier: 25а188
 i 17:59:19 cl-2     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 28а786
 i 17:59:19 stratum  Job: #842495d4... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:19 cl-1     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 28а786
 i 17:59:20 cl-6     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 28а786
 i 17:59:20 cl-5     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 28а786
 i 17:59:20 cl-7     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 28а786
 i 17:59:20 stratum  Job: #842495d4... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:20 cl-8     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 28а786
 i 17:59:20 cl-0     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 28а786
 i 17:59:20 cl-3     Adjusting CL work multiplier for 28 CUs.Adjusted work multiplier: 25а188
cl 17:59:20 cl-4     OpenCL kernel
cl 17:59:20 cl-2     OpenCL kernel
cl 17:59:20 cl-1     OpenCL kernel
cl 17:59:20 cl-6     OpenCL kernel
cl 17:59:20 cl-5     OpenCL kernel
cl 17:59:20 cl-7     OpenCL kernel
cl 17:59:20 cl-8     OpenCL kernel
cl 17:59:20 cl-3     OpenCL kernel
cl 17:59:20 cl-0     OpenCL kernel
cl 17:59:21 cl-4     Loading binary kernel C:\Users\ухэр\Desktop\bin17\kernels\ethash_tonga_lws256.bin
 i 17:59:21 stratum  Job: #842495d4... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:21 stratum  Job: #842495d4... eth.hashcity.org [138.201.198.155:7777]
cl 17:59:21 cl-0     Loading binary kernel C:\Users\ухэр\Desktop\bin17\kernels\ethash_ellesmere_lws256.bin
cl 17:59:21 cl-4     Build info success:
cl 17:59:21 cl-4     Creating light cache buffer, size: 42,874 MB
cl 17:59:21 cl-4     Creating DAG buffer, size: 2,680 GB, free: 1,278 GB
cl 17:59:21 cl-4     Loading kernels
cl 17:59:21 cl-4     Writing light cache buffer
cl 17:59:21 cl-4     Creating buffer for header.
cl 17:59:21 cl-4     Creating mining buffer
 i 17:59:21 stratum  Job: #842495d4... eth.hashcity.org [138.201.198.155:7777]
 m 17:59:21 main     Speed 0.00 Mh/s gpu0 0.00 58C 28% 27W gpu1 0.00 45C 84% 25W gpu2 0.00 50C 80% 27W gpu3 0.00 42C 100% gpu4 0.00 57C 41% gpu5 0.00 51C 73% 24W gpu6 0.00 48C 87% 26W gpu7 0.00 59C 34% 31W gpu8 0.00 58C 32% 24W A0 Time: 00:00
cl 17:59:22 cl-3     Loading binary kernel C:\Users\ухэр\Desktop\bin17\kernels\ethash_tonga_lws256.bin
cl 17:59:22 cl-0     Build info success:
cl 17:59:22 cl-0     Creating light cache buffer, size: 42,874 MB
cl 17:59:22 cl-0     Creating DAG buffer, size: 2,680 GB, free: 5,278 GB
cl 17:59:22 cl-0     Loading kernels
cl 17:59:22 cl-0     Writing light cache buffer
cl 17:59:22 cl-0     Creating buffer for header.
cl 17:59:22 cl-0     Creating mining buffer
cl 17:59:22 cl-8     Loading binary kernel C:\Users\ухэр\Desktop\bin17\kernels\ethash_ellesmere_lws256.bin
cl 17:59:22 cl-3     Build info success:
cl 17:59:22 cl-3     Creating light cache buffer, size: 42,874 MB
cl 17:59:22 cl-3     Creating DAG buffer, size: 2,680 GB, free: 1,278 GB
cl 17:59:22 cl-3     Loading kernels
cl 17:59:22 cl-3     Writing light cache buffer
cl 17:59:22 cl-3     Creating buffer for header.
cl 17:59:22 cl-3     Creating mining buffer
 i 17:59:22 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
cl 17:59:23 cl-7     Loading binary kernel C:\Users\ухэр\Desktop\bin17\kernels\ethash_ellesmere_lws256.bin
cl 17:59:23 cl-8     Build info success:
cl 17:59:23 cl-8     Creating light cache buffer, size: 42,874 MB
cl 17:59:23 cl-8     Creating DAG buffer, size: 2,680 GB, free: 5,278 GB
cl 17:59:23 cl-8     Loading kernels
cl 17:59:23 cl-8     Writing light cache buffer
cl 17:59:23 cl-8     Creating buffer for header.
cl 17:59:23 cl-8     Creating mining buffer
cl 17:59:23 cl-5     Loading binary kernel C:\Users\ухэр\Desktop\bin17\kernels\ethash_ellesmere_lws256.bin
cl 17:59:23 cl-7     Build info success:
cl 17:59:23 cl-7     Creating light cache buffer, size: 42,874 MB
cl 17:59:23 cl-7     Creating DAG buffer, size: 2,680 GB, free: 5,278 GB
cl 17:59:23 cl-7     Loading kernels
cl 17:59:23 cl-7     Writing light cache buffer
cl 17:59:23 cl-7     Creating buffer for header.
cl 17:59:23 cl-7     Creating mining buffer
cl 17:59:23 cl-6     Loading binary kernel C:\Users\ухэр\Desktop\bin17\kernels\ethash_ellesmere_lws256.bin
cl 17:59:23 cl-5     Build info success:
cl 17:59:23 cl-5     Creating light cache buffer, size: 42,874 MB
cl 17:59:23 cl-5     Creating DAG buffer, size: 2,680 GB, free: 1,278 GB
cl 17:59:23 cl-5     Loading kernels
cl 17:59:23 cl-5     Writing light cache buffer
 i 17:59:24 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
cl 17:59:24 cl-5     Creating buffer for header.
cl 17:59:24 cl-5     Creating mining buffer
cl 17:59:24 cl-1     Loading binary kernel C:\Users\ухэр\Desktop\bin17\kernels\ethash_ellesmere_lws256.bin
cl 17:59:24 cl-6     Build info success:
cl 17:59:24 cl-6     Creating light cache buffer, size: 42,874 MB
cl 17:59:24 cl-6     Creating DAG buffer, size: 2,680 GB, free: 1,278 GB
cl 17:59:24 cl-6     Loading kernels
cl 17:59:24 cl-6     Writing light cache buffer
cl 17:59:24 cl-6     Creating buffer for header.
cl 17:59:24 cl-6     Creating mining buffer
cl 17:59:24 cl-2     Loading binary kernel C:\Users\ухэр\Desktop\bin17\kernels\ethash_ellesmere_lws256.bin
cl 17:59:24 cl-1     Build info success:
cl 17:59:24 cl-1     Creating light cache buffer, size: 42,874 MB
cl 17:59:24 cl-2     Build info success:
cl 17:59:24 cl-1     Creating DAG buffer, size: 2,680 GB, free: 1,278 GB
cl 17:59:24 cl-2     Creating light cache buffer, size: 42,874 MB
cl 17:59:24 cl-2     Creating DAG buffer, size: 2,680 GB, free: 1,278 GB
cl 17:59:24 cl-1     Loading kernels
cl 17:59:24 cl-1     Writing light cache buffer
cl 17:59:24 cl-2     Loading kernels
cl 17:59:24 cl-2     Writing light cache buffer
cl 17:59:24 cl-1     Creating buffer for header.
cl 17:59:24 cl-1     Creating mining buffer
cl 17:59:24 cl-2     Creating buffer for header.
cl 17:59:24 cl-2     Creating mining buffer
 i 17:59:25 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:25 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:25 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:27 cl-0     2,680 GB of DAG data generated in 5а090 ms.
 i 17:59:27 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:27 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:27 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 m 17:59:27 main     Speed 0.00 Mh/s gpu0 0.00 61C 28% 90W gpu1 0.00 55C 83% 69W gpu2 0.00 58C 81% 71W gpu3 0.00 47C 100% gpu4 0.00 59C 46% gpu5 0.00 61C 74% 87W gpu6 0.00 60C 87% 70W gpu7 0.00 61C 34% 91W gpu8 0.00 61C 31% 90W A0 Time: 00:00
 i 17:59:28 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:28 cl-8     2,680 GB of DAG data generated in 5а089 ms.
 i 17:59:28 cl-5     2,680 GB of DAG data generated in 4а401 ms.
 i 17:59:28 cl-7     2,680 GB of DAG data generated in 5а186 ms.
 i 17:59:29 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:29 cl-4     2,680 GB of DAG data generated in 7а569 ms.
 i 17:59:29 cl-6     2,680 GB of DAG data generated in 5а205 ms.
 i 17:59:29 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:30 cl-2     2,680 GB of DAG data generated in 5а203 ms.
 i 17:59:30 cl-3     2,680 GB of DAG data generated in 7а572 ms.
 i 17:59:30 cl-1     2,680 GB of DAG data generated in 5а442 ms.
 i 17:59:30 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:31 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:31 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:31 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 m 17:59:34 main     Speed 0.00 Mh/s gpu0 0.00 64C 29% 122W gpu1 0.00 58C 84% 82W gpu2 0.00 62C 82% 91W gpu3 0.00 49C 100% gpu4 0.00 61C 48% gpu5 0.00 67C 75% 115W gpu6 0.00 67C 88% 90W gpu7 0.00 63C 35% 125W gpu8 0.00 64C 33% 124W A0 Time: 00:00
 i 17:59:34 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:35 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:35 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:35 stratum  Job: #a7c3f325... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:35 stratum  Job: #1de23c11... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:37 stratum  Job: #1de23c11... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:37 stratum  Job: #1de23c11... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:37 stratum  Job: #1de23c11... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:38 stratum  Job: #1de23c11... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:39 stratum  Job: #1de23c11... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:39 stratum  Job: #1de23c11... eth.hashcity.org [138.201.198.155:7777]
 m 17:59:40 main     Speed 230.89 Mh/s gpu0 30.29 65C 30% 122W gpu1 16.30 64C 83% 91W gpu2 20.43 66C 84% 93W gpu3 23.01 51C 100% gpu4 23.02 62C 52% gpu5 30.83 69C 76% 115W gpu6 26.93 70C 90% 90W gpu7 29.80 64C 36% 124W gpu8 30.27 65C 33% 125W A0 Time: 00:00
 i 17:59:40 stratum  Job: #1de23c11... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:41 stratum  Job: #1de23c11... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:41 stratum  Job: #1de23c11... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:41 stratum  Job: #1de23c11... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:44 stratum  Job: #1de23c11... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:44 stratum  Job: #644b9ec0... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:45 stratum  Job: #644b9ec0... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:45 stratum  Job: #644b9ec0... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:45 stratum  Job: #644b9ec0... eth.hashcity.org [138.201.198.155:7777]
 m 17:59:46 main     Speed 247.77 Mh/s gpu0 30.30 66C 33% 122W gpu1 26.21 66C 85% 91W gpu2 26.98 68C 84% 93W gpu3 23.06 53C 100% gpu4 23.04 64C 53% gpu5 30.86 70C 79% 115W gpu6 26.98 71C 90% 90W gpu7 30.04 65C 38% 125W gpu8 30.28 66C 36% 124W A0 Time: 00:00
 i 17:59:46 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:47 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:47 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:47 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:48 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:49 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:49 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:50 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:51 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:51 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:51 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 m 17:59:52 main     Speed 247.16 Mh/s gpu0 30.30 66C 33% 122W gpu1 26.19 67C 85% 91W gpu2 26.97 68C 84% 94W gpu3 23.06 53C 100% gpu4 23.05 65C 56% gpu5 30.83 71C 80% 115W gpu6 26.95 72C 90% 90W gpu7 29.55 65C 38% 125W gpu8 30.26 66C 36% 124W A0 Time: 00:00
 i 17:59:54 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:55 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:55 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:55 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:57 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:57 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:57 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 m 17:59:58 main     Speed 247.56 Mh/s gpu0 30.30 66C 33% 123W gpu1 26.20 68C 85% 91W gpu2 26.98 69C 84% 94W gpu3 23.05 54C 100% gpu4 23.04 65C 56% gpu5 30.86 71C 80% 116W gpu6 26.98 72C 90% 90W gpu7 29.87 65C 38% 126W gpu8 30.28 66C 36% 124W A0 Time: 00:00
 i 17:59:58 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:59 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 17:59:59 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:00 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:01 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:01 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:01 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 m 18:00:04 main     Speed 247.78 Mh/s gpu0 30.30 66C 33% 123W gpu1 26.20 69C 85% 91W gpu2 26.98 70C 84% 94W gpu3 23.06 54C 100% gpu4 23.05 65C 56% gpu5 30.86 72C 81% 116W gpu6 26.97 73C 90% 90W gpu7 30.07 66C 38% 125W gpu8 30.28 66C 36% 124W A0 Time: 00:00
 i 18:00:04 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:05 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:05 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:05 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:07 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:07 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:07 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:08 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:09 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:09 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 m 18:00:10 main     Speed 247.78 Mh/s gpu0 30.31 67C 33% 122W gpu1 26.21 69C 84% 91W gpu2 26.99 70C 83% 94W gpu3 23.07 55C 100% gpu4 23.06 66C 57% gpu5 30.85 72C 81% 115W gpu6 26.98 73C 90% 90W gpu7 30.02 66C 38% 125W gpu8 30.28 67C 36% 124W A0 Time: 00:00
 i 18:00:10 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:11 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:11 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:11 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:14 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:15 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:15 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:15 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 m 18:00:16 main     Speed 247.77 Mh/s gpu0 30.31 67C 33% 123W gpu1 26.22 70C 84% 92W gpu2 26.99 71C 83% 95W gpu3 23.06 56C 100% gpu4 23.05 66C 57% gpu5 30.86 72C 81% 116W gpu6 26.97 74C 90% 91W gpu7 30.04 67C 38% 125W gpu8 30.28 67C 36% 125W A0 Time: 00:01
 i 18:00:17 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:17 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:17 cl-1     Solution: 0xfc88d3d9393aac66
 i 18:00:17 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:18 stratum  Got response for unknown message id [109а390] Discarding...
 i 18:00:18 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:18 cl-7     Solution: 0xfc88d9d940efc061
 i 18:00:18 stratum  Got response for unknown message id [109а390] Discarding...
 i 18:00:18 cl-2     Solution: 0xfc88d4d93bd94ec6
 i 18:00:18 stratum  Got response for unknown message id [109а390] Discarding...
 i 18:00:19 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:19 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 X 18:00:20 stratum  No response received in 2 seconds.
 i 18:00:20 main     Disconnected from eth.hashcity.org [138.201.198.155:7777]
cl 18:00:20 cl-0     No work. Pause for 3 s.
 i 18:00:20 main     Suspend mining due connection change...
cl 18:00:20 cl-3     No work. Pause for 3 s.
cl 18:00:20 cl-1     No work. Pause for 3 s.
cl 18:00:20 cl-5     No work. Pause for 3 s.
cl 18:00:20 cl-4     No work. Pause for 3 s.
cl 18:00:20 cl-2     No work. Pause for 3 s.
cl 18:00:20 cl-7     No work. Pause for 3 s.
cl 18:00:20 cl-8     No work. Pause for 3 s.
cl 18:00:20 cl-6     No work. Pause for 3 s.
 i 18:00:20 main     Selected pool eth.hashcity.org:7777
 i 18:00:20 stratum  Stratum mode detected: ETHPROXY Compatible
 i 18:00:20 stratum  Logged in!
 i 18:00:20 stratum  Established connection with eth.hashcity.org:7777 at  [138.201.198.155:7777]
 i 18:00:20 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:20 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:21 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:21 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:21 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 m 18:00:22 main     Speed 247.49 Mh/s gpu0 30.30 64C 33% 27W gpu1 26.21 56C 85% 26W gpu2 26.98 59C 83% 28W gpu3 23.06 52C 100% gpu4 23.05 64C 56% gpu5 30.85 60C 81% 24W gpu6 26.97 58C 90% 27W gpu7 29.80 64C 38% 27W gpu8 30.27 63C 36% 24W A0 Time: 00:01
 i 18:00:24 stratum  Job: #579d8d45... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:24 stratum  Job: #ca668fcc... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:25 stratum  Job: #ca668fcc... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:25 stratum  Job: #ca668fcc... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:25 stratum  Job: #ca668fcc... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:27 stratum  Job: #ca668fcc... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:27 stratum  Job: #ca668fcc... eth.hashcity.org [138.201.198.155:7777]
 i 18:00:27 stratum  Job: #ca668fcc... eth.hashcity.org [138.201.198.155:7777]
 m 18:00:28 main     Speed 133.86 Mh/s gpu0 16.93 66C 33% 123W gpu1 13.93 68C 85% 91W gpu2 14.37 71C 83% 94W gpu3 12.27 54C 100% gpu4 12.27 66C 57% gpu5 17.24 71C 81% 115W gpu6 14.36 73C 90% 90W gpu7 15.59 66C 39% 125W gpu8 16.89 66C 37% 124W A0 Time: 00:01
 i 1

**Comment by AndreaLanfranchi** [comment]
Do you have the same problem on other major pools like for example ethermine.org ?

```
i 18:00:24 stratum Job: #ca668fcc... eth.hashcity.org [138.201.198.155:7777]
i 18:00:25 stratum Job: #ca668fcc... eth.hashcity.org [138.201.198.155:7777]
i 18:00:25 stratum Job: #ca668fcc... eth.hashcity.org [138.201.198.155:7777]
i 18:00:25 stratum Job: #ca668fcc... eth.hashcity.org [138.201.198.155:7777]
i 18:00:27 stratum Job: #ca668fcc... eth.hashcity.org [138.201.198.155:7777]
i 18:00:27 stratum Job: #ca668fcc... eth.hashcity.org [138.201.198.155:7777]
i 18:00:27 stratum Job: #ca668fcc... eth.hashcity.org [138.201.198.155:7777]
```

This pool keeps pushing the very same job over and over again.

**Comment by gennadiv** [comment]
no such problem was observed in other pools

**Comment by AndreaLanfranchi** [comment]
>no such problem was observed in other pools 

You have your answer then.
Blame pool maintainers ... not ethminer.
