### ISSUE TITLE
Starting ethminer with an (invalid) ssl connection causes SEGFAULT.

### ISSUE THREAD

**Issue by StefanOberhumer** [ethereum-mining/ethminer#1621]
Starting ethminer with an (invalid) ssl connection causes SEGFAULT.

`./ethminer -P stratum1+ssl://WALLET.WORKER@eth-eu1.nanopool.org:9999 -P stratum1+tcp://WALLET.WORKER@eth-eu1.nanopool.org:9999 --cuda`
(1st pool is an invalid SSL connection as nanopool does not support ssl on port 9999) results in a SEGFAULT.

**Desktop:**
- linux ubuntu-16.04
- Ethminer Version: actual latest master ( 077692c759fe969f24bc77ab79c591b4597e320e )

**Comment by AndreaLanfranchi** [comment]
Can't reproduce.

**Comment by AndreaLanfranchi** [comment]
Correction. The event is spurious.
Will dig into it.

**Comment by AndreaLanfranchi** [comment]
Should be solved by #1704
