### ISSUE TITLE
ethminer exit , when "Failed getting work!"

### ISSUE THREAD

**Issue by trustfarm-dev** [ethereum-mining/ethminer#1627]
**Describe the bug**
When Local solo mining , "Failed getting work!" miner exit.

**To Reproduce**

Running parity node
and run ethminer locally.

`ethminer -U -P getwork://127.0.0.1:8546  --cuda-devices 1`

**Desktop (please complete the following information):**
- Operating System: Windows 10
- Hardware :  GTX 1060
- Ethminer Version : ethminer 0.17.0.dev0-9

**Additional context**

exit with random time.

All is last same log. 

```
 X 12:12:06 getwork  Failed getting work!
 i 12:12:06 main     Disconnected from 127.0.0.1
 i 12:12:08 main     Suspend mining due connection change...
 i 12:12:08 main     Selected pool 127.0.0.1:8546
 i 12:12:08 main     Established connection with 127.0.0.1:
```

another test::

stop parity node ,

and 
```
m 14:15:58 main     Speed 17.41 Mh/s gpu0 17.41 Time: 00:03
 m 14:15:58 main     Solutions A0 gpu0:A0
 X 14:15:58 main     Failed getting work!
 i 14:15:58 main     Disconnected from 127.0.0.1
 i 14:15:59 main     Selected pool 127.0.0.1:8546
 i 14:15:59 main     Established connection with 127.0.0.1:8546 at
 i 14:16:00 cuda-0   No work. Pause for 3 s.
 X 14:16:00 main     Failed getting work!
 i 14:16:00 main     Disconnected from 127.0.0.1
 i 14:16:01 main     Selected pool 127.0.0.1:8546
 i 14:16:01 main     Established connection with 127.0.0.1:8546 at
 X 14:16:02 main     Failed getting work!
 i 14:16:02 main     Disconnected from 127.0.0.1
 i 14:16:03 main     Selected pool 127.0.0.1:8546
 i 14:16:03 main     Established connection with 127.0.0.1:8546 at
 i 14:16:03 cuda-0   No work. Pause for 3 s.
 m 14:16:03 main     Speed 17.41 Mh/s gpu0 17.41 Time: 00:03
 m 14:16:03 main     Solutions A0 gpu0:A0
 X 14:16:04 main     Failed getting work!
 i 14:16:04 main     Disconnected from 127.0.0.1
 i 14:16:05 main     Selected pool 127.0.0.1:8546
 ```
Not Exit and rerun parity node, it resume mining works.

like this way.

what's problem, I don't know.
cuda fail?

**Comment by AndreaLanfranchi** [comment]
This is not a CUDA error but a problem in http communication between ethminer and your parity node.
If, like you say, restarting parity node resumes correct mining I suspect there is a problem on node's side which, for some reason, does not respond (or stops accepting) to http calls.

**Comment by trustfarm-dev** [comment]
@AndreaLanfranchi 

it is another log.

after submit solutioin,
there's no getwork, then exit.

```
 m 15:30:03 main     Speed 17.40 Mh/s gpu0 17.40 Time: 01:17
 m 15:30:03 main     Solutions A49 gpu0:A49
 m 15:30:08 main     Speed 17.40 Mh/s gpu0 17.40 Time: 01:17
 m 15:30:08 main     Solutions A49 gpu0:A49
 m 15:30:13 main     Speed 17.40 Mh/s gpu0 17.40 Time: 01:17
 m 15:30:13 main     Solutions A49 gpu0:A49
 i 15:30:14 cuda-0   Solution: 0x9dc117d51e69055f
 X 15:30:14 main     Failed getting work!
 i 15:30:14 main     Disconnected from 127.0.0.1
 i 15:30:16 main     Suspend mining due connection change...
 i 15:30:16 main     Selected pool 127.0.0.1:8546
```

When testing normal operation , stop parity , 
then no getwork , but ethminer not exit.
and, If I restart node , then resume ethminer works.

**Comment by AndreaLanfranchi** [comment]
Does it work with release 0.16 ?
Unfortunately I do not have a parity node to test. Can you provide a connection to your node ?

**Comment by chfast** [comment]
Does parity support getwork at all?

**Comment by AndreaLanfranchi** [comment]
@chfast yes it does

https://wiki.parity.io/JSONRPC-eth-module.html#eth_getwork

**Comment by trustfarm-dev** [comment]
@chfast  @AndreaLanfranchi  it is parity testnode what I using.
It was working well until now, that version is officially downloaded , 
```
ethminer version 0.14.0.dev1
Build: Windows/msvc/Release
```

that's no problem.

above , testing version is what I built on windows10 , MSVS 2017 .
```
ethminer 0.17.0.dev0-9
```

**Comment by AndreaLanfranchi** [comment]
@trustfarm-dev could you also test releases 0.15 and 0.16 ?
Need to understand where it stopped working.

**Comment by trustfarm-dev** [comment]
@trustfarm-dev  0.16 I'll try now. wait a seconds

**Comment by trustfarm-dev** [comment]
```
d:\works\parity-dev\teochain\ethminer\build>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:08:12_Central_Daylight_Time_2018
Cuda compilation tools, release 9.2, V9.2.148
```

**Comment by trustfarm-dev** [comment]
@AndreaLanfranchi  @chfast  refer above log. 0.16 has same situation.

**Comment by trustfarm-dev** [comment]
Not exited case.

run with parity node,
stop parity node.


```
m 22:57:06 main     Speed 0.00 Mh/s gpu0 0.00 Time: 00:00
 m 22:57:06 main     Solutions A0 gpu0:A0
cu 22:57:10 cuda-0   Generated DAG for GPU1 in: 5,042 ms.
 m 22:57:11 main     Speed 0.22 Mh/s gpu0 0.22 Time: 00:00
 m 22:57:11 main     Solutions A0 gpu0:A0
 X 22:57:12 getwork  Failed getting work!
 i 22:57:12 main     Disconnected from 127.0.0.1
 i 22:57:13 main     Suspend mining due connection change...
 i 22:57:13 main     Selected pool 127.0.0.1:8546
 i 22:57:13 main     Established connection with 127.0.0.1:8546 at
 i 22:57:13 cuda-0   No work. Pause for 3 s.
 X 22:57:14 main     Failed getting work!
 i 22:57:14 main     Disconnected from 127.0.0.1
 i 22:57:15 main     Selected pool 127.0.0.1:8546
 i 22:57:15 main     Established connection with 127.0.0.1:8546 at
 m 22:57:16 main     Speed 17.37 Mh/s gpu0 17.37 Time: 00:00
 m 22:57:16 main     Solutions A0 gpu0:A0
 i 22:57:16 cuda-0   No work. Pause for 3 s.
 X 22:57:16 main     Failed getting work!
 i 22:57:16 main     Disconnected from 127.0.0.1
 i 22:57:17 main     Selected pool 127.0.0.1:8546
 i 22:57:17 main     Established connection with 127.0.0.1:8546 at
```

**Comment by AndreaLanfranchi** [comment]
@trustfarm-dev can you provide the full command line used to start parity node ?

**Comment by trustfarm-dev** [comment]
@AndreaLanfranchi 

parity.exe  -d d:\works\teotestmain3 --chain=teotest --jsonrpc-port=8546 --ws-port=8547 --jsonrpc-interface 127.0.0.1 --jsonrpc-cors "*" --jsonrpc-hosts all --stratum --stratum-port=8888 --jsonrpc-server-threads 10 --jsonrpc-threads 10 --no-ui  --cache-size 16384   --log-file teo.par.main.log

**Comment by AndreaLanfranchi** [comment]
So why not use stratum as you've enabled it ?

**Comment by trustfarm-dev** [comment]
@AndreaLanfranchi  that's not related this issues.
that was also testing. it has over 2months, 0.14.0-dev was no problem. completely no problem.
please interest on getwork protocol option changed commits.

**Comment by eosclassicteam** [comment]
@AndreaLanfranchi "getwork" protocol needs to be supported even if majority is using stratum instead of getwork, and since it worked on previous version I believe there is a coding issue on ethminer

**Comment by AndreaLanfranchi** [comment]
I know ... please also understand this is a voluntary project.
We'll dig into it as soon as we have a parity node to test on.

**Comment by trustfarm-dev** [comment]
@AndreaLanfranchi  as I know , that's not parity problem. that's whole worked on 0.14.0-dev on 

`
ethminer -U -F http://127.0.0.1:8546 --cuda-devices 1
`

**Comment by AndreaLanfranchi** [comment]
@trustfarm-dev 

when you say 

>and start parity node again, get work.
running well

the log immediately after is normal.

**Comment by AndreaLanfranchi** [comment]
> as I know , that's not parity problem. that's whole worked on 0.14.0-dev on

Getwork is getwork. If dwarfpool works ... then there is a problem on your node

**Comment by AndreaLanfranchi** [comment]
The getWork method is always the same ... either it **always** works or it **never** works. 
If sometimes works and sometimes doesnt' well it's the receiver which has issues (either it does not respond or it has some flood control).

For instance you should try one of those :
- reduce on ethminer side the polling interval (eg `--farm-recheck 2000`) maybe the default value of 200 ms is too quick for your test env
- use two separate machines : one for parity node and the other for ethminer (maybe running on the same machine your processor can't catch up with all threads and ethminer falls back to a timed out response)
- try to use ethminer on a pool exposing getwork interface

If the latter works then you definitely have a problem on parity node or you are encountering performance issues.

**Comment by trustfarm-dev** [comment]
official release link : 
it also exited finally, around 35minutes.
download from official release tab.  
https://github.com/ethereum-mining/ethminer/releases/download/v0.17.0-alpha.1/ethminer-0.17.0-alpha.1-cuda9.0-windows-amd64.zip 
 
_


d:\works\parity-dev\teochain\ethm-16.1-R\ethminer-0.17.0-alpha.1-cuda9.0-windows-amd64\bin>ethminer -U -P getwork://127.0.0.1:8546 --cuda-devices 1 -v 3
m 00:25:07 main ethminer 0.17.0-alpha.1
m 00:25:07 main Build: windows/release
cu 00:25:07 main Using grid size: 8,192, block size: 128
cu 00:25:07 main Found suitable CUDA device [GeForce GTX 1060 6GB] with 6,442,450,944 bytes of GPU memory
i 00:25:07 main Configured pool 127.0.0.1:8546
i 00:25:

**Comment by AndreaLanfranchi** [comment]
Please do the tests I told you.

**Comment by trustfarm-dev** [comment]
@gavofyork  @5chdn , can you check parity's getwork logic?
thanks.

**Comment by trustfarm-dev** [comment]
1:16:31 ~ 5:38:41 <around 4h 20m works>
exit pattern ::
```
  m 05:38:22 main     Speed 17.40 Mh/s gpu0 17.40 [A243] Time: 04:21
 i 05:38:23 cuda-0   Solution: 0x76d675130f8d3dea
 i 05:38:23 cuda-0   **Accepted   6 ms. 127.0.0.1
 i 05:38:23 getwork  Job: #9f874bb4... 127.0.0.1
 i 05:38:23 getwork  Pool difficulty: 1.11K megahash
 m 05:38:27 main     Speed 17.40 Mh/s gpu0 17.40 [A244] Time: 04:21
 m 05:38:32 main     Speed 17.40 Mh/s gpu0 17.40 [A244] Time: 04:22
 i 05:38:37 cuda-0   Solution: 0x76d6751313fd638b
 X 05:38:37 getwork  Failed getting work!
 i 05:38:37 main     Disconnected from 127.0.0.1
 i 05:38:37 main     Selected pool 127.0.0.1:8546
 i 05:38:37 main     Established connection with 127.0.0.1:8546 at
 m 05:38:37 main     Speed 17.40 Mh/s gpu0 17.40 [A244] Time: 04:22
 i 05:38:41 main     Job: #2c663851... 127.0.0.1

```
1) solution submit -> accepted.
2) new solution submit and no output of accepted or not. <-- check point
3) failed getwork
4) disconnect and reconnect (pool connection change) 
5) new getwork , and exit

**Assumption** 
when submitting solution, check return success or not. when didn't show logs on result.
check what's influencing the miner to exit.

**Comment by drhashes** [comment]
This works for me on ethminer 0.16.1

./ethminer -G -P http://host:port/wallet/rig_name

**Comment by 5chdn** [comment]
> @5chdn, can you check parity's getwork logic?

what for? how is your parity node configured? I'm not understanding the issue here.

**Comment by sling00** [comment]
This issue also effects http://github.com/atrides/eth-proxy

So the issue can be tested without a local daemon, just connect the proxy to any normal startum pool and connect miner to it.  This worked perfectly in 0.14 but is broken in 0.16 and 0.17

**Comment by AndreaLanfranchi** [comment]
@sling00 
> This issue also effects http://github.com/atrides/eth-proxy

This makes no sense to me.
eth-proxy is used specifically to have ethminer connected to a stratum origin while the proxy communicates with pool via getwork. 
How is it possible to have such error with eth-proxy ?

**Comment by sling00** [comment]
You are thinking backwards, it connects a getwork ethminer to a stratum
pool.

**Comment by AndreaLanfranchi** [comment]
@sling00 yes you're right sorry.

**Comment by AndreaLanfranchi** [comment]
@sling00 can you exactly explain why it's not working ?

**Comment by AndreaLanfranchi** [comment]
No feedback.
Closing

**Comment by sling00** [comment]
Sorry for the delay.  Been a crazy last few weeks.

The main issue is that upon any type of get work disconnect, get work does not try again to connect to the pool. 

Please actually test the issue and it will quickly validate this issue request, as it happens very frequently, especially with multiple GPUs in the system.

This issue did not occur in 0.14.x but is present in 0.15.x and above.

**Comment by lesjokolat** [comment]
just for fun what if you changed your startup

ethminer -U -P getwork://127.0.0.1:8546 --cuda-devices 1
to
ethminer -U -P http://127.0.0.1:8546 --cuda-devices 1

what happens then?

**Comment by lesjokolat** [comment]
add -v 3 to your startup what does log produce then?
