### ISSUE TITLE
Can't Compile  libethash-cuda On VS 2017 

### ISSUE THREAD

**Issue by franklen** [ethereum-mining/ethminer#1633]
4>Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/Release/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.obj
4>CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.obj.Release.cmake:219 (message):
4>  Error generating
4>  D:/workspace/miners/ethminer/ethminer/libethash-cuda/CMakeFiles/ethash-cuda.dir//Release/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.obj
4>

**Environment**
CUDA: 9.0 
VS Community 2017 
Windows10.0.17134.345

**Comment by XhmikosR** [comment]
Unfortunately you will have to provide more info. The above log shows no valuable info.

Since it works on our CI, I suggest that you follow the docs https://github.com/ethereum-mining/ethminer/blob/master/docs/BUILD.md#windows
