### ISSUE TITLE
0.17.0.dev0-4+commit.d2448e04 crash

### ISSUE THREAD

**Issue by rawdez** [ethereum-mining/ethminer#1636]
keeps crashing once in a couple days sometimes couple times a day

**To Reproduce**
run 0.17.0.dev0-4+commit.d2448e04 on windows 10 ltsb 2016

```
 X 05:10:13 cuda-1   GPU error: CUDA error in func dev::eth::CUDAMiner::search at line 455 an illegal instruction was encountered
 X 05:10:13 cuda-2   GPU error: CUDA error in func dev::eth::CUDAMiner::search at line 455 an illegal instruction was encountered
 X 05:10:13 cuda-1   Terminating.
 X 05:10:13 cuda-0   GPU error: CUDA error in func dev::eth::CUDAMiner::search at line 455 an illegal instruction was encountered
 X 05:10:13 cuda-2   Terminating.
```

ethminer 0.17.0.dev0-4+commit.d2448e04
Build: windows/release/msvc

hope it helps

**Comment by XhmikosR** [comment]
Probably an overclocking issue. Try lowering your OC. Also keep in mind that with driver updates the OC might need to be adapted.

**Comment by rawdez** [comment]
I kind of thought I caught some bug @ dev::eth::CUDAMiner::search at line 455
just trying to be helpful.
I never updated any drivers though, only tried some dev builds of ethminer with promising descriptions to check if they run with my config at all and/or if it became a little better

is there any point to update drivers anyway, like will it mine better? as far as I know the only thing it does is optimize some games performance and this not really relevant to mining, or is it?

**Comment by XhmikosR** [comment]
Probably no gain, but still you can't stay to a specific driver version after some time.

Could be a hardware issue then. Unfortunately this will need troubleshooting from your side.

**Comment by AndreaLanfranchi** [comment]
This is 99.9~% due to excessive OC.
Good thing is ethminer exits and does not hang.
Newer ethminer's releases have reduced lag between stream launches thus the OC settings adopted for earlier versions may not work well with more recent releases.
