### ISSUE TITLE
0.16.0 & 0.16.1; Debian stretch; "terminate called without an active exception Aborted"

### ISSUE THREAD

**Issue by sponW12** [ethereum-mining/ethminer#1637]
**Describe the bug**
0.15.0 works great.
both 0.16.0 and 0.16.1 answer for "./ethminer -G -M 220" is "terminate called without an active exception Aborted".
apt update && apt upgrade done.

for -G --list-devices reply is:
Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
"[0] [0] Ellesmere
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8576299008
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256"
**To Reproduce**
1. Lauch ethminer 0.16.0 (1) "./ethminer -G -M 220 (or any)
2. Get the error "terminate called without an active exception Aborted"

**Expected behavior**
Benchmark start

**Desktop (please complete the following information):**
- Operating System: Debian 9 Stretch linux-headers-4.9.0-8-amd64
- GPU Gigabyte Radeon RX580 8GB
- Ethminer Version 0.16.0/0.16.1

**Comment by AndreaLanfranchi** [comment]
Please retry latest and feed back.

**Comment by AndreaLanfranchi** [comment]
No feed back.
Closing.
