### ISSUE TITLE
Ethminer just closes 0.16

### ISSUE THREAD

**Issue by falsepr0phet** [ethereum-mining/ethminer#1638]
Ethminer just closes out without an error

ethminer.exe -G --opencl-platform 1 --opencl-device 0 -P stratum1+ssl://Adress.workername@eu1.ethermine.org:5555

got a 1070ti and rx570, wanna have it just mine on the rx570, its the right platform and device number

m 19:18:36 main     ethminer 0.16.1
 m 19:18:36 main     Build: windows/release
 i 19:18:37 main     Found suitable OpenCL device [Ellesmere] with 8,000 GB of GPU memory
 i 19:18:37 main     Configured pool eu1.ethermine.org:5555
 i 19:18:37 main     Selected pool eu1.ethermine.org:5555
 i 19:18:37 stratum  Stratum mode detected: ETHPROXY Compatible
 i 19:18:37 stratum  Logged in!
 i 19:18:37 stratum  Established connection with eu1.ethermine.org:5555 at  [[2606:4700:90:0:bda0:4092:8f4f:4658]:5555]
 i 19:18:37 stratum  Spinning up miners...
cl 19:18:37 cl-0     No work. Pause for 3 s.
 i 19:18:37 stratum  Job: #3a5dd3e0... eu1.ethermine.org [[2606:4700:90:0:bda0:4092:8f4f:4658]:5555]
 i 19:18:37 stratum  Pool difficulty: 4.00K megahash
 i 19:18:37 stratum  New epoch 216
cl 19:18:40 cl-0     Platform: AMD Accelerated Parallel Processing
cl 19:18:40 cl-0     Device:   Ellesmere / OpenCL 2.0 AMD-APP (2348.3)

then it just closes any suggestions?

**Comment by lesjokolat** [comment]
add -v 3 will give more detailed message and help solve faster

**Comment by falsepr0phet** [comment]
i added once -v 3 before the -G and once after the whole line. In both cases the output is still just

 m 11:10:06 main     ethminer 0.16.1
 m 11:10:06 main     Build: windows/release
 i 11:10:07 main     Found suitable OpenCL device [Ellesmere] with 8,000 GB of GPU memory
 i 11:10:07 main     Configured pool eu1.ethermine.org:5555
 i 11:10:07 main     Selected pool eu1.ethermine.org:5555
 i 11:10:07 stratum  Stratum mode detected: ETHPROXY Compatible
 i 11:10:07 stratum  Logged in!
 i 11:10:07 stratum  Established connection with eu1.ethermine.org:5555 at  [[2606:4700:90:0:bda0:4092:8f4f:4658]:5555]
 i 11:10:07 stratum  Spinning up miners...
cl 11:10:07 cl-0     No work. Pause for 3 s.
 i 11:10:07 stratum  Job: #42c9e0d2... eu1.ethermine.org [[2606:4700:90:0:bda0:4092:8f4f:4658]:5555]
 i 11:10:07 stratum  Pool difficulty: 4.00K megahash
 i 11:10:07 stratum  New epoch 217
cl 11:10:10 cl-0     Platform: AMD Accelerated Parallel Processing
cl 11:10:10 cl-0     Device:   Ellesmere / OpenCL 2.0 AMD-APP (2348.3)

did i add it wrong?:D
