### ISSUE TITLE
All Shares rejected after sometime

### ISSUE THREAD

**Issue by rahimovic100** [ethereum-mining/ethminer#1639]
I'm using ethminer 0.17.0-alpha.1 in Ubuntu 16.04 with GPU Nvidia Tesla Vega V100

my problem is after sometime of good work (maybe 1h or 2h) all of my shares will be rejected with unknown reason !!

I use dwarfpool with cuda parameter
./ethminer -U stratum://mywallet.myworker@eth-us2.dwarfpool.com:8008

the unexpecteble is when I use the same configuration with 4 GPU Vega V100 all works good for much longer

what's the problem ?
please help ... or tell me what i can do to restart the miner automatically when there are rejected shares

thank you

**Comment by lesjokolat** [comment]
add -v 3 get more detail on errors of share rejections

**Comment by lesjokolat** [comment]
also your dwrafminer pool setting needs some tweaking see examples section for pool command lines

**Comment by rahimovic100** [comment]
i 08:24:32 stratum  Job: #12e64a40… eth-us2.dwarfpool.com [209.141.38.185:8008]
 m 08:24:32 ethminer Speed 92.78 Mh/s gpu0 92.78 Time: 03:32
 m 08:24:32 ethminer Solutions A517+1:R69 gpu0:A517+1:R69
 i 08:24:35 cuda-0   Solution: 0x05007d41ce90e6a7
 i 08:24:35 cuda-0   {
        "id" : 40,
        "method" : "eth_submitWork",
        "params" :
        [
                "0x05007d41ce90e6a7",
                "0x12e64a400e91619473c14d7e98b2f4a46abd222dfbb045c31e5c4f72a72a0444",
                "0xbf03c0c1f54be16d1877b5bbe6e9e5148833a6f2ad48c0861480603b0dfddad6"
        ],
        "worker" : "rahim21"
}
 i 08:24:35 stratum  {
        "id" : 40,
        "jsonrpc" : "2.0",
        "result" : false
}
 X 08:24:35 stratum  Reject reason :Unspecified
 X 08:24:35 stratum  **Rejected  71ms.   eth-us2.dwarfpool.com [209.141.38.185:8008]
 i 08:24:37 cuda-0   Solution: 0x05007d41dc471678
 i 08:24:37 cuda-0   {
        "id" : 40,
        "method" : "eth_submitWork",
        "params" :
        [
                "0x05007d41dc471678",
                "0x12e64a400e91619473c14d7e98b2f4a46abd222dfbb045c31e5c4f72a72a0444",
                "0xff1e6d0872dd8bf70f80539b14c4fcefea1966deef7c6d061be1ead3e5c21ed7"
        ],
        "worker" : "rahim21"
}
 i 08:24:37 stratum  {
        "id" : 40,
        "jsonrpc" : "2.0",
        "result" : false
}
 X 08:24:37 stratum  Reject reason :Unspecified
 X 08:24:37 stratum  **Rejected  71ms.   eth-us2.dwarfpool.com [209.141.38.185:8008]
 m 08:24:37 ethminer Speed 92.76 Mh/s gpu0 92.76 Time: 03:32
 m 08:24:37 ethminer Solutions A517+1:R71 gpu0:A517+1:R71

**Comment by rahimovic100** [comment]
I told you but with 4 GPU it works correctly !!
if it's a bug I want a solution just for restarting the miner each time it gets rejected
thank you

**Comment by StefanOberhumer** [comment]
Try lower overclocking (about 20% - mem and core). Test it. If it works raise overclicking in small (3%) steps

**Comment by lesjokolat** [comment]
if you are overclocking the cards try to see if that get better by reducing the over clocks.

are you using risers? if so please check to see the cards are sitting well in place.

how do you run the 4 vs 2 gpus? same motherboard? perhaps switch location of failing gpu to another pci slot to see if problem follows card?

**Comment by rahimovic100** [comment]
I'm using a cloud service so I don't think that's overclocking 
and with the same provider just have more than 1 account 
in the account that I have 4 GPU in one instance there are no problem
but in 1 GPU ..... :'(

**Comment by lesjokolat** [comment]
ok leaves me thinking it is more a hardware issue. As same gpus but diffent machines. If miner was the cause the others would also behave that way eventually. Maybe add a 2nd pool to your startup as a failover pool, see if it can send to that if errors persist.( though i think its network communication loss that triggers failover.) gltu

**Comment by rahimovic100** [comment]
never mind if I don't know what's the problem
but are there a solution to restart miner when the shares will be rejected ?
because when restarting miner all will be ok for a moment 
or just a script to restart miner each 1H !?

**Comment by lesjokolat** [comment]
there is no watch dog but see this thread maybe a so,ution for you.

https://github.com/ethereum-mining/ethminer/issues/97

**Comment by rahimovic100** [comment]
resolve the problem by installing Debian instead of ubuntu 16.04

**Comment by AndreaLanfranchi** [comment]
@rahimovic100 
as far as I understand your only command line is 
```
./ethminer -U stratum://mywallet.myworker@eth-us2.dwarfpool.com:8008
```
and all other optional arguments are left at their default values.
Under these circumstances every solution found by any of your GPUs is double-checked using CPU: if, for any reason, a GPU should find a solution (nonce) which actually does not produce the expected result, this double-check gives an output warning line saying "GPU x gave incorrect result. Lower overclocking values if it happens frequently".

Apparently this does not happen in your environment which leads to the conclusion it's higly unlikely your hardware is producing bad solutions due to excessive overclocking.

Unfortunately the pool you're connecting to does not provide a reason for the rejection thus making impossible to understand what's going on : maybe there is a problem on your side or on pool's side.

Another, remote, possibility, is someone tampering with your data on the trip from your machine to pool (man in the middle attack) which is possible as you're not using an encrypted connection.

**Comment by urpils** [comment]
I had the same issue with stratum on DwarfPool.
Using getwork with or without stratum proxy was the dirty solution.
This is the setup example on their homepage, no example for direct stratum use -.-

**Comment by rahimovic100** [comment]
it appears that the problem was cuda 10
I'll confirm that soon, i'm testing cuda 9 with no problem till now

**Comment by rahimovic100** [comment]
:'( no 
cuda 9 give more hash and just more stability buy always rejected shares after some times
i'll be crasy

**Comment by AndreaLanfranchi** [comment]
> i'll be crasy.... i lose time and money

There is a quick test you can do : change pool for a test batch.
Try using, say, ethermine.org or nanopool and run a batch of 12 hours at least. If the problem disappears then you're facing an issue with the pool.

**Comment by rahimovic100** [comment]
i used an other pool (ethminer) with stratum+ssl:// and all is fine
thank you

**Comment by AndreaLanfranchi** [comment]
So the problem is not ethminer's
