### ISSUE TITLE
CUDA error: Insufficient CUDA driver: 9020

### ISSUE THREAD

**Issue by alienandroid** [ethereum-mining/ethminer#1640]
**Describe the bug**
Cloning and compiling the source code produces the error:
CUDA error: Insufficient CUDA driver: 9020

System Configuration:
Cuda compilation tools, release 10.0, V10.0.130
NVRM version: NVIDIA UNIX x86_64 Kernel Module  396.54
 

**Desktop (please complete the following information):**
- Operating System: Ubuntu 18.04.1
4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Hardware 1080TI
- Ethminer Version cloned from github

**Additional context**
I was initially getting the 9010 error until I upgraded to nvidia-driver-396
No errors on compiling or building the installer
The binary provided on the github site works just fine.

Any help would be appreciated.

Thank you

**Comment by XhmikosR** [comment]
You need to update to newer drivers in order to use CUDA 10. Not sure if they exist for Ubuntu yet.

**Comment by alienandroid** [comment]
Thanks for the suggestion! Installing nvidia-driver-410 from ppa fixed my issue.   With the ppa repo enabled, I ran the following to install the 410 drivers: aptitude install nvidia-driver-410

By using aptitude, it uninstalled the previous drivers (nvidia-driver-396 in my case), and installed the new drivers.
