### ISSUE TITLE
OpenCL Error: clEnqueueReadBuffer: CL_INVALID_VALUE (-30)

### ISSUE THREAD

**Issue by thankst** [ethereum-mining/ethminer#1642]
why?
![img_3490](https://user-images.githubusercontent.com/7693342/46939234-5e453380-d098-11e8-93fb-5d1428f0ec8f.PNG)

**Comment by AndreaLanfranchi** [comment]
Not enough informations.
Please follow the template when opening issues and give all proper infos in particular ethminer version.
Apparently (fro your' log) there are lines not belonging to ethminer.

**Comment by thankst** [comment]
win10  newest version 
ethminer  --farm-recheck 2000 -G -P http://127.0.0.1:8545
using opencl

**Comment by thankst** [comment]
> Not enough informations.
> Please follow the template when opening issues and give all proper infos in particular ethminer version.
> Apparently (fro your' log) there are lines not belonging to ethminer.
win10 newest version
ethminer --farm-recheck 2000 -G -P http://127.0.0.1:8545
using opencl

**Comment by AndreaLanfranchi** [comment]
ethminer version !!!

**Comment by thankst** [comment]
> ethminer version !!!
its actally a fork version
https://github.com/thankst/ethminer

**Comment by thankst** [comment]
> ethminer version !!!

i just chan
