### ISSUE TITLE
in Linux no CPU

### ISSUE THREAD

**Issue by zekritek** [ethereum-mining/ethminer#1649]
ethminer-0.17.0-alpha.1-linux-x86_64.tar.gz
./ethminer -C ...
no work

How to work last ethminer on Linux with CPU ?

**Comment by AndreaLanfranchi** [comment]
You can't.
CPU mining is not available in current releases of ethminer (regardless windows or linux flavour)
Maybe in future releases.

**Comment by smurfy** [comment]
ethminer does no longer support cpu mining.

But if you like you can re-add it:  #1147

**Comment by zekritek** [comment]
Ok, Thanks
