### ISSUE TITLE
Feature: CLI option for search segment randomization

### ISSUE THREAD

**Issue by aleqx** [ethereum-mining/ethminer#1650]
As described first here in this thread: https://github.com/ethereum-mining/ethminer/issues/1646#issuecomment-431687172

In short, have a CLI option to allow the user to specify whether they want 

- per-job randomization
- per-run randomization (current 0.16 implementation)
- per-session randomization (i.e. connection lifetime)
- interval-based randomization (every N seconds)
- custom scrambler and segment width (basically expose [this](https://github.com/ethereum-mining/ethminer/blob/master/docs/API_DOCUMENTATION.md#miner_setscramblerinfo) to CLI)

Different setups and sizes can benefit from different approaches here. I for one would like to use per-job randomization like in 0.12 for reasons expressed in the discussion above (simple solution to ensure ergodicity, avoiding to manage bad luck of many miners' segments clashing for long periods of time leading to increased stale rates). I also think that per-job randomization should be the default to benefit the average person.

Proposal for cli option.

```
--scrambler-rand STR|INT in {job,connection,instance,N}=job
    Scramble nonce search segment offset on every job,
    on every (re)connection, once only at the start of the
    mining instance, or every N seconds.
--set-scrambler INT INT
    Set nonce search segment offset and width to N and M
    respectively, with N in 0..2^24-1 and M in 1..40.
    Overrides --rand-scrambler. Use at your own risk!
```

**Comment by AndreaLanfranchi** [comment]
There are a few issues with this proposal.

- randomization on interval: there is no meaning in randomizing with intervals lower than avg job time 
- I quite do not understand your `--set-scrambler INT INT`

**Comment by aleqx** [comment]
>randomization on interval: there is no meaning in randomizing with intervals lower than avg job time

Sure. I wasn't suggesting there is. The suggestion was precisely to allow randomizations more rarely than the average job notification intervals.

> I quite do not understand your `--set-scrambler INT INT`

As I explained, it's the same as the API and I included a link to said API endpoint (again [here](https://github.com/ethereum-mining/ethminer/blob/master/docs/API_DOCUMENTATION.md#miner_setscramblerinfo)).

**Comment by AndreaLanfranchi** [comment]
In commit #1704 we've added new argument `--ergodicity` which is described in `ethminer -H misc`

```
    --ergodicity        INT[0 .. 2] Default = 0
                        Sets how ethminer chooses the nonces segments to
                        search on.
                        0 A search segment is picked at startup
                        1 A search segment is picked on every pool connection
                        2 A search segment is picked on every new job

```

**Please note that this setting has no effect on connections to pools implementing EthereumStratum/1.0.0 or, the incoming, EthereumStratum/2.0.0` as the start nonce is set by the pool (extranonce)**

**Comment by aleqx** [comment]
The one I really wanted was the periodic option, to set it every `N` seconds, with a configurable `N`. You could even use the same option `--ergodicity` for any value greater than 2 to be interpreted as seconds to periodically shuffle.

**Comment by aleqx** [comment]
Forgot to say thanks for adding the option nonetheless!

**Comment by AndreaLanfranchi** [comment]
Unfortunately @aleqx this would add the overhead of another timer into the poolmanager thread which actually we don't really want to. Nevertheless you can easily implement a task scheduled operation on your OS which simply invokes the execution of the API method

```
echo '{"id":0,"jsonrpc":"2.0","method":"miner_shuffle"}' | netcat <yourethminerinstanceip> 3333
```

**Comment by aleqx** [comment]
That's what I'm doing at the moment but it's a heavier solution for ethminer compared to a timer, since a new tcp connection is always made, etc. An additional _unused_ timer can't be an issue performance wise (right?), while it does reduce overhead of API calls if used. I'd use it if it was available.

**Comment by AndreaLanfranchi** [comment]
It's not only a matter of performance. It's a matter of maintenance of code. Timers must also be activated and shut down upon other bunches of events.

>That's what I'm doing at the moment but it's a heavier solution for ethminer compared to a timer, since a new tcp connection is always made, etc.

The overhead introduced by a new connection is negligible : few microseconds are nothing if we assume you schedule with 30 or more seconds. The shuffling procedure takes the same.
