### ISSUE TITLE
A miner that works for waltonchain (AMD)

### ISSUE THREAD

**Issue by VercauterenK** [ethereum-mining/ethminer#1661]
Hello,

Is there anyone who could build an ethminer that works inside the walton app.
wtcpool.net has one modified version working for his pool.
But the only problem is that the miner adres is always his adres. So when the token swap happens i end up getting nothing beceause the pool mines on his adres. And only the mined adresses get their reward.

So i have to option create a pool where my adres is programmed in or create a ethmine version that works on the node from the waltonchain app.
If someone could deliver me 1 of these so i can mine on my adres i am willing to pay 1 BTC for it.

PS the modified ethminer can be downloaded from wtcpool.net it doesn't matter what adres you give in.

Thanks in advance,
Kevin

**Comment by VercauterenK** [comment]
that previous question was for on simple mining. Also now i am offering 1 BTC for a miner...

**Comment by smurfy** [comment]
Does not matter, **eth**miner is an ETHEREUM Miner not a waltonchain miner.

While wtcpool is probably violating the GPL, your requests do not relate to ethminer, nor is this a forum or support system for general mining stuff.

For question like yours i would suggest: https://bitcointalk.org/
