### ISSUE TITLE
why is CUDA Support disabled in Darwin Builds?

### ISSUE THREAD

**Issue by OEIG** [ethereum-mining/ethminer#1667]
Please enable CUDA Support for darwin builds.

**Comment by chfast** [comment]
Nobody wants to maintain it.

**Comment by chfast** [comment]
Well, if you know how to build it in MacOS, you can send the CI script to build Ethminer with CUDA support.

**Comment by OEIG** [comment]
If i would know how to build it, i would maintain it... If I'll get some support on it, I'll give it a try and document it and provide a darwin build file for it.

**Comment by chfast** [comment]
You have to install CUDA SDK and follow "build from source" instructions: https://github.com/ethereum-mining/ethminer/blob/master/docs/BUILD.md

**Comment by OEIG** [comment]
Well, there is only one entry for MacOS there: „TBF“. That is not a very informative starting point ;-P

**Comment by chfast** [comment]
Thanks to @hackmod this is now done. You can download binaries with CUDA support.
