### ISSUE TITLE
CUDA and high CPU usage on --cuda-schedule != sync

### ISSUE THREAD

**Issue by Spudz76** [ethereum-mining/ethminer#1672]
**Describe the bug**
CPU usage is ridiculous.  All cores pegged 100% while ethminer runs.  Tried `yield` mode and `auto` mode neither solves it, act identical, probably due the number of GPUs - but other miners don't have this side effect / wastage of CPU time.  Seems like a week ago it didn't have quite this problem (same code, same binary), though CPU usage was higher it was not making the CPU completely useless for anything else.

**To Reproduce**
1. Run with options:
```
./ethminer \
        -P "stratum://doesnt.matter:1234" \
        --HWMON 1 \
        -R \
        -U \
        -L 2 \
        --cuda-grid-size 16384 \
        --cuda-block-size 256 \
        --cuda-schedule yield
```
2. Another terminal, run `htop` and observe CPUs pegged and wasted on waiting for GPUs I guess
3. Eventually shares quit flowing, but GPUs still doing work.  Probably CPU got overworked and network / management processes too too long.
4. Do not enjoy CPU mining of other coins at the same time (like with other miners, no problem, same rig)

**Expected behavior**
Process on GPU does nearly nothing to CPU usage, should be maybe 25% of one core, not 100% pegged on all four cores.  Occasional (on result) spike for result revalidation expected, as are PCI transfers at job begin and job end (only).

**Desktop (please complete the following information):**
- Operating System:
    Ubuntu 16.04.5 LTS
    kernel `4.4.0-138-generic`
    driver `410.48-0ubuntu1`
    CUDA SDK `10.0.130-1`
- Hardware
    6 of `GeForce GTX 1060 6GB (Compute 6.1)`
    1 of `Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz` four cores present in OS
- Ethminer Version master freshly compiled (`0.17.0-alpha.1+commit.2bfd45d9.dirty`)
    used cmake opts: `-DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.0 -DCOMPUTE=61 -DETHDBUS=OFF`

The 'dirty' is a patch to ignore pool messages that do not contain JSON.  Dwarfpool pukes empty packets at me, idk, got tired of the bad parse message.  Not sure why it even attempts to parse a packet if it has no `'{'` within, my small hack ignores the packet if it doesn't contain one `{`

**Additional context**
Not to rub you with closed-source-useless-comparisons but claymore dual miner (in single/eth mode) does not chew CPU awaiting CUDA results, at all.  However everything else about it sucks pretty hard, rather use this, but not if it chews CPU (and lost CPU-mining opportunity -  if it doesn't hash it doesn't deserve watts)

ALSO same issue on Windows 7, same types of GPUs, same CUDA 10 level, same compile config.  That CPU has about 50% free while ethminer is running, but since switching from dualminer to ethminer my CPU hashrates on XMR have about halved.  So it is using too much CPU even tho it hasn't yet decided to use 100%.  That rig has 4 GPUs though.  Both rigs ran nearly identical rates on all coins (GPU/ETH and CPU/XMR) for a week, now the Linux one refuses to do anything other than munch CPU. (eth rate same)

Was running CUDA 9.1 (and older driver) with claymore mainly because he hasn't released a CUDA 10 build and that revision seemed happiest.  So the CUDA 10 and associated driver was changed at the same time as switching to ethminer, but is also the main reason I switched to ethminer was to run a CUDA 10 native non-backward-compatible build of something.  Besides a few more H/s which was a nice bonus, but not if its making the CPU useless for side projects.

**Comment by Spudz76** [comment]
I just found that using `--cuda-schedule sync` while counter-intuitive seems to fix the issue completely.

Yield should be the correct setting, and should allow CPU to do other things (while it acts more like spin / waste CPU while waiting) and I use 'yield' with all other CUDA apps to normal success.

Sync should always be worst, but works best on my rigs... somehow

**Comment by AndreaLanfranchi** [comment]
ethminer defaults to `--cuda-schedule sync` as this is the most effective: CUDA thread only polls GPUs on a blocking primitive for STREAMS completion instead of keep synching data (which is not needed).

Also ... AFAIK Claymore does not implement CUDA but uses CL on NVIDIA too.

Interesting your point about dwarfpool sending empty packets.
