### ISSUE TITLE
After change system time wrong display in miner window

### ISSUE THREAD

**Issue by gituser-4** [ethereum-mining/ethminer#1674]
After change system time wrong display in miner window.
It no show speed.

UPD: This bug only if use "time from internet" function.

How to repeat:
1) Change system time to 1 hour + or -
2) Use function "time from internet" from control panel.

- Operating System:  Windows 10
- Hardware  RX 570
- Ethminer Version 0.16.1

**Comment by AndreaLanfranchi** [comment]
Do you do this **while ethminer is running** ?

**Comment by AndreaLanfranchi** [comment]
Well ... this is expected.
Hash rates measurement is function of time which is detected by system clock. If you move the clock backwards or forward we do either have negative intervals or too wide intervals. And measurement is messed up.
