### ISSUE TITLE
Failed to load the binary kernel

### ISSUE THREAD

**Issue by jyouyj** [ethereum-mining/ethminer#1675]
**Describe the bug**
I try to use the ethminer with my Mac's GPU. 
Platform: Apple
Device:   AMD Radeon Pro 560 Compute Engine / OpenCL 1.2 

However, I failed to load the binary kernel. Can you tell me how to fix this problem? Thank you so much!

**Screenshots (Optional)**

i 14:36:06          Configured pool localhost:38391
 i 14:36:06 main     Selected pool localhost:38391
 i 14:36:06 main     Established connection with localhost:38391 at 
 i 14:36:06 main     Spinning up miners...
cl 14:36:06 cl-0     No work. Pause for 3 s.
 i 14:36:06 getwork  Job: #18672671… localhost
 i 14:36:06 getwork  Pool difficulty: 0.00K megahash
cl 14:36:09 cl-0     Platform: Apple
cl 14:36:09 cl-0     Device:   AMD Radeon Pro 560 Compute Engine / OpenCL 1.2 
cl 14:36:10 cl-0     OpenCL kernel
cl 14:36:10 cl-0     Loading binary kernel /Users/jieyou/Desktop/quarkminer/build/ethminer/./kernels/ethash_amd radeon pro 560 compute engine_lws192.bin
 X 14:36:10 cl-0     Failed to load binary kernel: /Users/jieyou/Desktop/quarkminer/build/ethminer/./kernels/ethash_amd radeon pro 560 compute engine_lws192.bin
 X 14:36:10 cl-0     Falling back to OpenCL kernel...
cl 14:36:10 cl-0     Creating light cache buffer, size: 16.000 MB
cl 14:36:10 cl-0     Creating DAG buffer, size: 1,023.998 MB, free: 2.984 GB
cl 14:36:10 cl-0     Loading kernels
cl 14:36:10 cl-0     Writing light cache buffer
cl 14:36:10 cl-0     Creating buffer for header.
cl 14:36:10 cl-0     Creating mining buffer
 m 14:36:11          Speed 0.00 Mh/s gpu0 0.00 A0 Time: 00:00
 i 14:36:14 getwork  Job: #7760fa89… localhost
 m 14:36:16          Speed 0.00 Mh/s gpu0 0.00 A0 Time: 00:00

**Desktop (please complete the following information):**
- Operating System: [e.g. MacOS Mojave]
- Hardware [e.g. AMD Radeon Pro 56]
- Ethminer Version [current version]

**Comment by AndreaLanfranchi** [comment]
Mac platform is **not** supported.
Sorry

**Comment by winterhalter** [comment]
> Mac platform is **not** supported.
Development for macOS appears to be continuing but I'm getting the same load error. 

```
Loading binary kernel ~/Downloads/bin/./kernels/ethash_amd radeon rx vega 56 compute engine_lws192.bin
 X 13:20:15 cl-1     Failed to load binary kernel: ~/Downloads/bin/./kernels/ethash_amd radeon rx vega 56 compute engine_lws192.bin
 X 13:20:15 cl-1     Falling back to OpenCL kernel...
cl 13:20:15 cl-1     Creating light cache buffer, size: 48.874 MB
cl 13:20:15 cl-1     Creating DAG buffer, size: 3.055 GB, free: 4.882 GB
cl 13:20:15 cl-1     Loading kernels
cl 13:20:15 cl-1     Writing light cache buffer
Segmentation fault: 11
```

**Comment by winterhalter** [comment]
OpenCL and OpenGL support were dropped in macOS 10.14 in favor of Metal.
