### ISSUE TITLE
What is this in the log [A148+4]?

### ISSUE THREAD

**Issue by suydovarku** [ethereum-mining/ethminer#1676]
Hi, All

Do anyone Know what this means:
[A148+4]?

ex:
 i 10:00:44 stratum  **Accepted  43 ms. eu1.ethermine.org [172.65.207.106:5555]
 m 10:00:49 main     Speed 398.74 Mh/s gpu0 31.63 gpu1 31.26 gpu2 31.62 gpu3 27.42 gpu4 30.80 gpu5 30.81 gpu6 30.59 gpu7 30.81 gpu8 30.82 gpu9 30.81 gpu10 30.57 gpu11 30.80 gpu12 30.81 [A148+4] Time: 00:28

PS: I'm using 16.1 version

Thanks advanced,
Suy

**Comment by AndreaLanfranchi** [comment]
It's the counter of submitted shares.

A184+4 means 188 submitted solutions of which 4 are accounted as stale.

**Comment by suydovarku** [comment]
Thanks very much for your help
