### ISSUE TITLE
Windows 10 AMD Adrenalin Edition 18.11.1 ltsc causes error opencl

### ISSUE THREAD

**Issue by gennadiv** [ethereum-mining/ethminer#1677]
error no open cl amd Adrenalin Edition 18.11.1 Optional
window 10  ltsс

**Comment by lesjokolat** [comment]
seems like a problem with adrenalin install. Did you do install as administrator?

try using ddu to uninstall then re install amd driver.

**Comment by gennadiv** [comment]
tried does not help the problem that the same writes

**Comment by AndreaLanfranchi** [comment]
Run `clinfo` on your machine.
If same error reported problem is all related to drivers of your GPU.

**Comment by gennadiv** [comment]
I had to install the lts version and everything worked. why did not work in the ntsc version is not clear?

**Comment by AndreaLanfranchi** [comment]
So it was driver error.

**Comment by gennadiv** [comment]
yes
