### ISSUE TITLE
Mac Os graphics hangs while using the computer for other tasks

### ISSUE THREAD

**Issue by VenomLightning** [ethereum-mining/ethminer#1678]
Hello. I have a weird issue, not only with your miner, but also with xmrig and xmr-stack. I got continuous graphics freeze several times a second when trying to mine. The only error in console is:
```void IOAccelFenceMachine::fence_timeout(IOTimerEventSource *): AMDRadeonAccelerator prodding blockFenceInterrupt```
Same issue with benchmark mode also, but reported hashrate is normal.

- Tried latest Ethminer versions 0.16.1 and 0.17 alpha.
- Mac Os 10.14.1 (Hackintosh actually, using latest Clover bootloader and latest WhatEverGreen patches)
- RX560 4Gb

Additional info: Same issue in Mac Os 10.13.X and with RX580

**Comment by AndreaLanfranchi** [comment]
It's pretty normal.
Miner pushes GPU flat-out. Ethminer specifically is meant for dedicated rigs.
