### ISSUE TITLE
heads up: nvidia rtx 2070 + driver 416.81 + ethminer 0.17.0

### ISSUE THREAD

**Issue by satori-q3a** [ethereum-mining/ethminer#1679]
I'm not sure if NVidia RTX 2070 doesn't like using driver 416.81 to run ethminer 0.17.0, but it seems the found solutions are half what the previous drivers would give me, while not affecting GTX boards on the same system.  It might just be my system, but I've tried multiple re-installs of 416.81 and while the hashrate looked good, the found solutions on the RTX were still half what I expected.

Drivers 416.16 thru hot fix 416.64 have no problems with the RTX 2070 and GTX 1070 cards, and trying to roll back from .81 to .64 is truly an exercise in patience and frustration, but fortunately and finally doable.

For your info, the RTX 2070 can get 40 MH at 105 watts, while having a stable desktop running.

**Comment by satori-q3a** [comment]
Update:

The nvidia drivers 417.xx series work well and gives me the expected solution rate for the RTX 2070 card, so.. go fig.

**Comment by AndreaLanfranchi** [comment]
Closing as it's related to NVIDIA drivers. Not much we can do with ethminer
