### ISSUE TITLE
Ethminer does not want -G even though I didn't put it there.

### ISSUE THREAD

**Issue by kylerchin** [ethereum-mining/ethminer#168]
![image](https://user-images.githubusercontent.com/7539174/28347899-b900f486-6bee-11e7-97c8-cdc09e20da4b.png)

**Comment by jimmykl** [comment]
@kylerschin You can't run ethminer with no flags! e.g. you need to specify ```etherminer -G``` for OpenCL or ```ethminer -U``` for CUDA. You will also need to add ```-S```  for your pool and ```-O``` for your wallet.

**Comment by jimmykl** [comment]
@kylerschin If that answers your question please close this issue. Thanks!

**Comment by chfast** [comment]
This is just incorrect error message.

**Comment by peteut** [comment]
@chfast To improve maintainability of the options parsing maybe [Boost.Program_options](http://www.boost.org/doc/libs/1_64_0/doc/html/program_options.html) would be an option?

**Comment by chfast** [comment]
@peteut yes it would.

**Comment by DeadManWalkingTO** [comment]
CUDA Hardware Test Launch Command:

`ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.issue168`

OpenCL Hardware Test Launch Command:

`ethminer -RH -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.issue168`

MIX Hardware Test Launch Command:

`ethminer -RH -X -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.issue168`


Try with latest Ethminer version and feedback please.
Thank you!
