### ISSUE TITLE
GTX Titan X hashrate at 11% of what it should be

### ISSUE THREAD

**Issue by lev-kusanagi** [ethereum-mining/ethminer#1683]
**Describe the bug**
GTX Titan X hashrate is at 11% of what it should be, namely 4.61 when it should be about 35 MH/s

**To Reproduce**
Ubuntu 18, Cuda 10 , latest release of ethminer

have successfully run this rig in the past at the full 35 MH/s.

**Comment by lev-kusanagi** [comment]
On latest version ethminer 0.17.0-alpha.1+commit.16e21442 but also on release 0.16, 0.15, 0.14, and 0.13. All equally low hashrates.

Please help!
Could it be CUDA 10, or Ubuntu 18?

**Comment by lev-kusanagi** [comment]
Hi @AndreaLanfranchi 
The exact model is Nvidia GTX Titan X. To be clear, this means it's the Maxwell version.

Full ethminer command line is ethminer -R -U -P stratum1+ssl://address.rigname@eu1.ethermine.org:5555

Output of ethminer -U --list-devices is
[0] GeForce GTX TITAN X
	Compute version: 5.2
	cudaDeviceProp::totalGlobalMem: 12804685824
	Pci: 0000:01:00

**Comment by AndreaLanfranchi** [comment]
Same issue as https://github.com/ethereum-mining/ethminer/issues/669

Have you tried with CUDA 9x ?

**Comment by lev-kusanagi** [comment]
@AndreaLanfranchi Thanks, I'll do that, and report back!

**Comment by ddobreff** [comment]
I think that this will not help. Please try on ethash coin with <2GB DAG and report.

**Comment by lev-kusanagi** [comment]
@ddobreff Why not? Also, isn't ethereum an ethash coin? Also, my GTX Titan X has 12 GB memory, why would a <2GB DAG be a problem?
Additionally, I remember this thing doing about 35MH/s (when I was mining about this time next year), why shouldn't it be capable of doing that again?

**Comment by ddobreff** [comment]
Too many “why” too less “google”

**Comment by ddobreff** [comment]
DAG <2GB will not be a problem, but >2GB will be if your Titan X is maxwell arch.

**Comment by lev-kusanagi** [comment]
Yeah @ddobreff @AndreaLanfranchi it was Maxwell arch also last year when it got 35 MH/s. It's alright guys, I'm not going to mine anymore, thanks for the help anyhow.
