### ISSUE TITLE
ethminer release 0.17 ETA ?

### ISSUE THREAD

**Issue by gennadiv** [ethereum-mining/ethminer#1686]
I see you have finished working on bugs with the new version and I look forward to the new release. when to expect

**Comment by gennadiv** [comment]
what's stopping you or not yet

**Comment by Olegatorius** [comment]
> и что вас останавливает или ещё не время?

I think you need politely ask in Polish - not in Russian :)

**Comment by gennadiv** [comment]
I understand that a new release is not expected
