### ISSUE TITLE
Impossible to escape the dot in user name 

### ISSUE THREAD

**Issue by pit55** [ethereum-mining/ethminer#1687]
Problem:
When i want to use miningrigrental.com, my all user name contains dot character and after numbers
example: username.246891
-S and -O parameters is removed i need to use normal Pool URL specification settings, but the first dot separator is defined worker name, i cant escape it.

Pool URL Specification:
    URL takes the form: scheme://user[.workername][:password]@hostname:port[/...].

./ethminer -U -P stratum1+tcp://username.246891.rigname:x@eu-01.miningrigrentals.com:3344

Solutions
maybe can i use escape character 
stratum1+tcp://username\.246891.rigname:x@eu-01.miningrigrentals.com:3344
or use ''
stratum1+tcp://'username.246891'.rigname:x@eu-01.miningrigrentals.com:3344

or use force user name parameter 
--forceusername username.246891 and program force sed s/defaultusername/forceusername/

**Comment by AndreaLanfranchi** [comment]
Never used MRR but have you tried this syntax ?
```
./ethminer -U -P stratum1+tcp://eu-01.miningrigrentals.com:3344/username.246891/rigname
```

**Comment by pit55** [comment]
Yes i try but not good

**Comment by AndreaLanfranchi** [comment]
Same as #1075

**Comment by StefanOberhumer** [comment]
With commit e6f23dc020b970b91d8d5754dffbdb6277357871 it should be able to pass a "." within username and workername using "%2e" which means:

 use `./ethminer -U -P stratum1+tcp://username%2e246891.rigname:x@eu-01.miningrigrentals.com:3344` with an actual build to solve the problem

**Comment by pit55** [comment]
not :

./ethminer -U -P stratum1+tcp://
username%2e100011.rigName:x@eu-01.miningrigrentals.com:3344 -v 3

 i 16:17:44 main     Selected pool eu-01.miningrigrentals.com:3344
 i 16:17:44 stratum  {
    "id" : 1,
    "method" : "eth_submitLogin",
    "params" :
    [
        "username"
    ],
    "worker" : "100011."
}
 i 16:17:45 stratum  {
    "error" :
    [
        20,
        "Client Pre-authorization was not accepted (incorrect workername,
check your settings).",
        null
    ],


Stefan Oberhumer <notifications@github.com> ezt írta (időpont: 2018. nov.
23., P, 9:15):

**Comment by pit55** [comment]
official yes

Stefan Oberhumer <notifications@github.com> ezt írta (időpont: 2018. nov.
23., P, 20:22):

**Comment by StefanOberhumer** [comment]
> official yes

Ah - OK - The fix is not included in the latest available official release.
Seems you have to compile it yourself or wait for a new official release (#1686 )

**Comment by pit55** [comment]
yes i wait thank you

Stefan Oberhumer <notifications@github.com> ezt írta (időpont: 2018. nov.
24., Szo, 10:03):

**Comment by StefanOberhumer** [comment]
@pit55 
As info: It seems new official release are available - check the release page https://github.com/ethereum-mining/ethminer/releases
