### ISSUE TITLE
Mail parameter passing is broken in previous commit

### ISSUE THREAD

**Issue by pZFi** [ethereum-mining/ethminer#1688]
Ethminer later  then 0.15.0 stopped working with ubiqpool.io.

It was launched with:
`./ethminer -R -U -P stratum1+tcp://0xAddress.Miner@eu1.ubiqpool.io:8008 ... --stratum-email mail@domain.com`
 After commit 4021a9948e3eefc70b1794e8c96bfbf1ba0b889e for #1477 code was removed:
`        if (!m_email.empty())
            jReq["params"].append(m_email);`
That broke everything.
In versions after that commit parameter is unsupported: `The following argument was not expected: --stratum-email`.

If you try to use it in "new modern way" like:
`    Example 2:    stratum://0x012345678901234567890234567890123.miner1@nanopool.org:9999/john.doe@gmail.com`
`    Example 3:    stratum://0x012345678901234567890234567890123@nanopool.org:9999/miner1/john.doe@gmail.com`
"Very intellectual" autodetection algorithm goes the wrong way in case selector and decides that it's for ETHPROXY (WTF???):
`    switch (m_conn->StratumMode())
    {
    case EthStratumClient::STRATUM:

        jReq["jsonrpc"] = "2.0";

        break;

    case EthStratumClient::ETHPROXY:

        jReq["method"] = "eth_submitLogin";
        if (m_worker.length())
            jReq["worker"] = m_worker;
        jReq["params"].append(m_user + m_conn->Path());

        break;

    case EthStratumClient::ETHEREUMSTRATUM:

        jReq["params"].append(ethminer_get_buildinfo()->project_name_with_version);
        jReq["params"].append("EthereumStratum/1.0.0");

        break;
    }`

That results in wrong login:
`2018-11-18 02-33-51 -  m 02:33:51 ethminer ethminer 0.16.1`
`2018-11-18 02-33-51 -  m 02:33:51 ethminer Build: linux/release`
`2018-11-18 02-33-51 - cu 02:33:51 ethminer Using grid size: 8�192, block size: 128`
`2018-11-18 02-33-52 -  i 02:33:52 ethminer Configured pool eu2.ubiqpool.io:8008`
`2018-11-18 02-33-52 -  i 02:33:52 main     Selected pool eu2.ubiqpool.io:8008`
`2018-11-18 02-33-52 -  i 02:33:52 stratum  Stratum mode detected: ETHPROXY Compatible`
`2018-11-18 02-33-52 -  i 02:33:52 stratum  Could not login:code:-1 message:Invalid login `
`2018-11-18 02-33-52 -  i 02:33:52 main     Disconnected from  [104.238.171.4:8008]`
`2018-11-18 02-33-53 -  i 02:33:53 main     No more connections to try. Exiting...`
`2018-11-18 02-33-54 -  i 02:33:54 ethminer Terminated!`

Please return `--stratum-email` argument and passing E-Mail in parameters part of JSON:
`        if (!m_email.empty())
            jReq["params"].append(m_email);`

P.S. In my way it's pretty shitty to drop legacy feature support for some magic algorithms that always work in unexpected way.

**Comment by AndreaLanfranchi** [comment]
You can easily bypass auto detection.
Rtfm

**Comment by AndreaLanfranchi** [comment]
And btw. Keep your shit away from here as we don't owe you nothing.

**Comment by AndreaLanfranchi** [comment]
> So, according to manual, autodetection should not work at all, because of stratum1+tcp.

Autodetection is nothing more than an iteration through theese three modes (in the exact order)

1. stratum2+tcp://
2. stratum1+tcp://
3. stratum+tcp://

> Why it it asks for password in case of something after "/" and don't if connection string end with port?
Example 2: stratum://0x012345678901234567890234567890123.miner1@nanopool.org:9999 /john.doe@gmail.com

Nothing prevents you from writing
Example 2: stratum://0x012345678901234567890234567890123.miner1:whicheverpasswordyouwant@nanopool.org:9999 /john.doe@gmail.com

A good understanding about what an [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) is would help you better

**Comment by AndreaLanfranchi** [comment]
Not relevant anymore.

In less than 3 days ethminer will not work on UBIQ anymore: they're abandoning ethash in favor of ubqhash (which is not supported by ethminer).

https://ubiqsmart.com/uip1/#/

Regards.
