### ISSUE TITLE
Implement ProgPOW, extension set for Ethash Proof of Work to block asics

### ISSUE THREAD

**Issue by naikmyeong** [ethereum-mining/ethminer#1695]
Reference implementation : https://github.com/ifdefelse/ProgPOW

WIP master branch rebase: https://github.com/ifdefelse/ProgPOW/issues/17 , https://github.com/EthersocialNetwork/ethminer-ProgPOW/commits/progpow-master-rebase , https://github.com/ethereum-mining/ethminer/pull/1692

I would like to request implementing ProgPOW as a part of ethminer, to support features of progpow mining along with wip geth node or parity node, with GPU CUDA & OpenCl support.

I believe ProgPOW's spec is almost finalized for production use and I think it is a good time to start implementing final changes on ethminer repository also.

cc @chfast @ifdefelse @hackmod

**Comment by chfast** [comment]
There are not objections to ProgPoW integration, but there are no volunteers nor funding to have it done.

**Comment by naikmyeong** [comment]
@chfast @hackmod and I am ready to volunteer for ProgPOW integration, all we need is some code reviews and pr merge from ethminer maintainers

**Comment by AndreaLanfranchi** [comment]
We need to support both algos. Ethash and progpow. We can't switch to ProgPow abruptly. Ethminer must continue to live for other ethash coins

**Comment by naikmyeong** [comment]
@AndreaLanfranchi Yes this is the main point of ProgPOW implementation on ethminer

**Comment by naikmyeong** [comment]
Here is the code that is rebased from master branch, we only need switch logic on the code https://github.com/ethereum-mining/ethminer/pull/1692

**Comment by hackmod** [comment]
https://github.com/ethereum/ethash/pull/111 (ethereum/ethash ProgPoW v0.9.1)
and some open-ethereum-pool test result.

**Comment by hackmod** [comment]
the main reason I was trying to rebase manually is that the current ethminer use chfast/ethash and it already support ProgPoW.

**Comment by naikmyeong** [comment]
First version available on https://github.com/gangnamtestnet/progminer
