### ISSUE TITLE
Feature Request : API to report some stats

### ISSUE THREAD

**Issue by Singman33** [ethereum-mining/ethminer#170]
Hi,
I think it's time to add an API to that program, at least to get the hashrate & accepted / dropped numbers. What do you think about a simple API ?
Thanks.

**Comment by chfast** [comment]
Yes, good idea, please do it.

**Comment by zenware** [comment]
I'm willing to work on implementing this, is there a developer/contributions guide or someone with some more experience working in this codebase that could point me to the most appropriate places to bolt on something like that?

**Comment by MariusVanDerWijden** [comment]
https://github.com/ethereum-mining/ethminer/blob/master/libapicore/ApiServer.cpp

**Comment by smurfy** [comment]
This is an old issue, is already implemented.
