### ISSUE TITLE
[master] stratum: invalid epoch, dag memory size

### ISSUE THREAD

**Issue by hackmod** [ethereum-mining/ethminer#1722]
**Describe the bug**
invalid epoch, dag memory size for stratum cases. Please see screenshot.

*getWork works with no problem.*

branch point commit 07ea6f91be5135f0678a0aef775c05fa48a286aa
Merge: 4df6898 1ec2342
~~~
Author: Andrea Lanfranchi <andrea.lanfranchi@isiweb.it>
Date:   Wed Nov 28 13:03:12 2018 +0100

    Merge pull request #1721 from ethereum-mining/clang-tidy

    Tune clang-tidy config and fix some warnings**
~~~
**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/32324335/49151560-a2904880-f353-11e8-9a43-f533c367ce66.png)

**Comment by AndreaLanfranchi** [comment]
Also please post logs (not screenshots) as sime lines are truncated

**Comment by hackmod** [comment]
~~~

cu 21:36:34 cuda-0   Epoch 892,558,107 requires 13055174282.53 GB memory.
cu 21:36:34 cuda-0   This device hasn't available. Mining suspended ...
cu 21:36:35 cuda-2   Epoch 808,465,460 requires 9836798741.55 GB memory.
cu 21:36:35 cuda-2   This device hasn't available. Mining suspended ...
cu 21:36:35 cuda-1   Generating DAG + Light : 260.00 B
cu 21:36:35 cuda-1   Unexpected error CUDA error in func ethash_generate_dag at line 132 an illegal memory access was encountered on CUDA device 04:00.0
cu 21:36:35 cuda-1   Mining suspended ...
~~~

**Comment by AndreaLanfranchi** [comment]
With same verbosity please. There were also stratum messages.

**Comment by AndreaLanfranchi** [comment]
Strange thing is cuda-0 and cuda-2 properly detect abnormal DAG size and stop while cuda-2 tries to generate a 260 B dag file wich has no meaning.

Which is your `--dag-loadmode` parameter ?

**Comment by hackmod** [comment]
no `--dag-loadmode` parameter
