### ISSUE TITLE
--cl-platform and --cl-devices switches not recognized

### ISSUE THREAD

**Issue by deh8551** [ethereum-mining/ethminer#1724]
Compiled release at commit 07ea6f9 for just openCL on machine running Ubuntu 16.04.5 with both nvidia and amd hardware.  When attempting to run ethminer with just the amd hardware in openCL using the switch —cl-platform per the help, receiving the error “Error: The following argument was not expected: —cl-platform”.  I also received the same type error when using the switch —cl-devices.

I am launching with the following command

/usr/local/bin/ethminer --cl-platform 0 --display-interval 15 --cl-local-work 256 -G -P stratum://${ACCOUNT}.${WORKER}:x@us-solo-eth.2miners.com:6060

**Comment by AndreaLanfranchi** [comment]
Sorry for that,

--cl-platform has been removed (but was still present in help though) We're removing it now.

There is no need to specify the platform anymore as ethminer now detects all possible platforms.

Use `ethminer -G --list-devices` to see all your available CL GPUs

**Comment by deh8551** [comment]
Thanks for the update about the —cl-platform.  Unfortunately, I am receiving the same type error using the —cl-devices.  Has it also been removed?

Is there a way on a machine with both NVIDIA and AMD to specify just the AMD cards when using openCL?

Thank you,

**Comment by AndreaLanfranchi** [comment]
> Thanks for the update about the —cl-platform.  Unfortunately, I am receiving the same type error using the —cl-devices.  Has it also been removed?

Hmmm strange ... --cl-devices is in place. 
Can you please post the full command line you use to launch ethminer ?

> Is there a way on a machine with both NVIDIA and AMD to specify just the AMD cards when using openCL?

Yes of course. First of all run `ethminer -G --list-devices`
This will give you the list of all usable openCl devices (wich actually will be both NVIDIA and AMD)
Then take note of the Ids (leftmost column) you want to use (say  0 2 3)
Finally launch 
```
ethminer -G --cl-devices 0 2 3 ...
```

**Comment by deh8551** [comment]
I retyped the command string and it working now so no more issues.  Not sure what what I typed, but thank you for taking the time.
