### ISSUE TITLE
Ubuntu 18.04: can't determine @reboot crontab error

### ISSUE THREAD

**Issue by WinWinHost** [ethereum-mining/ethminer#1746]
**Describe the bug**
I have been using @reboot to auto start the ethminer on Ubuntu 16.04 boxes and older builds without any issues. When I say older, I mean before when we used cmake --build instead of make install.
I would just add a line to the crontab file to execute a simple shell script.

This doesn't work in Ubuntu 18.04, and with the newer build. I am not sure what's to blame, and that's kind of the the bug. The program seems to exit without an error code.

I can't determine what went wrong, logging stdout and stderr yield no clues, and neither does journalctl -u cron.service

**To Reproduce**

```
robert@robert-efm:~$ cat /etc/crontab
# /etc/crontab: system-wide crontab
# Unlike any other crontab you don't have to run the `crontab'
# command to install the new version when you edit this file
# and files in /etc/cron.d. These files also have username fields,
# that none of the other crontabs do.

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m h dom mon dow user	command
17 *	* * *	root    cd / && run-parts --report /etc/cron.hourly
25 6	* * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6	* * 7	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6	1 * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
#
@reboot robert /home/robert/eth.sh
```

I've replaced my wallet and worker id.
eth.sh
```
/home/robert/ethminer/build/ethminer/ethminer -U -P stratum1+tcp://0xADDRESS.WORKER@us1.ethermine.org:4444 2>&1 > /home/robert/eth.log
```

```
robert@robert-efm:~$ cat eth.log


ethminer 0.18.0-alpha.1-18+commit.8294506b
Build: linux/release/gnu



```

journalctl -u cron.service
```
-- Reboot --
Dec 03 09:13:10 robert-efm systemd[1]: Started Regular background program processing daemon.
Dec 03 09:13:10 robert-efm cron[981]: (CRON) INFO (pidfile fd = 3)
Dec 03 09:13:10 robert-efm cron[981]: (CRON) INFO (Running @reboot jobs)
Dec 03 09:13:10 robert-efm CRON[994]: pam_unix(cron:session): session opened for user robert by (uid=0)
Dec 03 09:13:10 robert-efm CRON[1007]: (robert) CMD (/home/robert/eth.sh)
Dec 03 09:13:11 robert-efm CRON[994]: (CRON) info (No MTA installed, discarding output)
Dec 03 09:13:11 robert-efm CRON[994]: pam_unix(cron:session): session closed for user robert
Dec 03 09:17:01 robert-efm CRON[2451]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 03 09:17:01 robert-efm CRON[2452]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Dec 03 09:17:01 robert-efm CRON[2451]: pam_unix(cron:session): session closed for user root
```

**Expected behavior**
I need to understand why the program is failing so I can address the issue. It runs just fine when I log in and execute the script in a screen. 
So I am hoping the fix would be just better error reporting all around, or support for installing the ethminer as a service. Which I also tried with systemd, and had horrible luck with that as well. 

**Desktop (please complete the following information):**
- Operating System: 
Ubuntu 18.04
- Hardware 
GTX 1060
- Ethminer Version 
ethminer 0.18.0-alpha.1-18+commit.8294506b
Build: linux/release/gnu

**Additional context**
Thanks in Advance.

**Comment by AndreaLanfranchi** [comment]
Few questions :
- Are you using downloaded binaries or building from source ?
- Is your motherboard **CPU** and AMD ?

**Comment by WinWinHost** [comment]
Building from source.


This box is an older hexacore xeon chip. LGA2011 socket I believe.
I can provide exact hardware details if you want. 


Works just fine when I login and start it manually.
But I am trying to create a startup script / service so I don't have to when there is another power surge. 
That way I can just start my boxes again and know they are doing their thing.

**Comment by StefanOberhumer** [comment]
* Are your cards initialized at that moment ? (try `/home/robert/ethminer/build/ethminer/ethminer --list-devices 2>&1 > /home/robert/eth.log` and check the output in /home/robert/eth.log )

**Comment by AndreaLanfranchi** [comment]
It's highly possible that `@reboot` is too early for the full stack of services of your machine to be ready.

Try change to 

```
@reboot robert sleep 60 && bash /home/robert/eth.sh
```

Also add 
```
#!/usr/bin/env bash
```
on top of your eth.sh file and ensure is executable by user robert.

**Comment by WinWinHost** [comment]
Added your list devices script before the ethminer start

```
@reboot root /home/robert/checkcards.sh
@reboot robert /home/robert/eth.sh
```

here is the output.
```
robert@robert-efm:~$ cat checkcards.log


ethminer 0.18.0-alpha.1-18+commit.8294506b
Build: linux/release/gnu

 Id Pci Id    Type Name                      CUDA SM  CL    Total Memory  Cl Max Alloc  Cl Max W.Grp
--- --------- ---- ------------------------- ---- --- ----  ------------  ------------  ------------
  0 04:00.0   Gpu  GeForce GTX 1060 6GB      Yes  6.1 Yes        5.93 GB       1.48 GB       1.00 KB
```

**Comment by AndreaLanfranchi** [comment]
@WinWinHost 
you get the device list using `root` but you launch ethminer using `robert`
Maybe `robert` does not have permission to access CUDA devices directly

**Comment by WinWinHost** [comment]
> It's highly possible that `@reboot` is too early for the full stack of services of your machine to be ready.
> 
> Try change to
> 
> ```
> @reboot robert sleep 60 && bash /home/robert/eth.sh
> ```
> Also add
> 
> ```
> #!/usr/bin/env bash
> ```
> on top of your eth.sh file and ensure is executable by user robert.

These changes made it worked.
Can I get an better understanding of why?
Seems like WooWoo to me. 

The script was executing just fine. What timing / startup process could not possibly be re ready to start mining? This is must an Ubuntu 16 vs 18, issue.

**Comment by AndreaLanfranchi** [comment]
> What timing / startup process could not possibly be re ready to start mining?

99.9% the x11 server !
