### ISSUE TITLE
ethminer wont start on newest amd 12.1 driver

### ISSUE THREAD

**Issue by alexmannen** [ethereum-mining/ethminer#1747]

**Comment by AndreaLanfranchi** [comment]
So what ?

ethminer version ?
logs ?
Linux ? Windows ?

Some info please.

**Comment by lesjokolat** [comment]
works for me even latest dev builds..

What is your startup command line? If you add -v 3 to it what is error log showing?

**Comment by alexmannen** [comment]
tried version 17 and new 18a
it just closes instantly as i start it.
windows 10 1803
It worked today before a driver update.

**Comment by AndreaLanfranchi** [comment]
So you have your answer. Don't blame ethminer blame your driver's update
