### ISSUE TITLE
2x power draw

### ISSUE THREAD

**Issue by mtcms** [ethereum-mining/ethminer#1752]
**Describe the bug**
ethminer draws 2x the power draw from the wall after an hour of fresh install

**To Reproduce**
1. Perform an minimal install of Ubuntu 18.04 (with updates)
2. Reboot and drop to recovery mode and select root shell
3. Install cuda 10.0 along with the drivers
4. Append the necessary environment variables as per the last notes from the installer (PATH and LD_LIBRARY_PATH)
5. Reboot
6. Run nvidia x-config to enable all GPUs and turn on coolbits 28 
7. Power limit all the 6x1070 card to 100 watts, Undervolt the core to -200 and memoffset to 800

**Expected behavior**
At first will draw something that's reasonable (about 730-760 watts from the wall). It goes to 1400-1500 watts after 2 hours for no apparent reason.

**Desktop (please complete the following information):**
- Operating System: Ubuntu 18.04
- Hardware: 6xGTX1070
- Ethminer Version: 0.16.0

**Additional context**
The reason for the upgrade to Ubuntu 18.04 and ethminer 0.16.0 was this.
Ubuntu 16.04 (cuda 9.0) was used with ethminer ver 0.13 for a long time with zero issues.

EDIT: It almost as if an update is getting to it (after installing the cuda 10 with the driver) and the issue manifests. Re-installing the OS and doing a complete redo to get more info. Will update this if I get anything else. Suggestions are most welcome.

EDIT2: added the missed step to recreate (just to make sure any one can reproduce it) - happening on 3x identical rigs.

**Comment by ddobreff** [comment]
Dear user, 
Ethminer has nothing to do with powerdraw, its a simple miner that does what its supposed to do, it does not control your powersource, nor your powerlimits. It is up to you to properly configure your GPU devices to reduce powerusage. There are plenty of tutorials on how to do that.
Happy mining.

**Comment by mtcms** [comment]
Thank you Andre. 
Nvidia-smi has been saying what I power limit it on to. I have narrowed the root cause to be on warm boots.
If you cold boot and drain the power on the entire motherboard then power up the PC - it doesn't happen. The issue is can always be reproduced if I shut down, keep the power source plugged and turn on the PC. It's happening on at least 2 different motherboards so far (both with GTX1070s). I have power meters on the power source which is where I am observing all these.

Writing it up here to help someone else doing some search later on. It's not by any means a fix but something that can be easily worked around on.
