### ISSUE TITLE
Half Hash

### ISSUE THREAD

**Issue by stone212** [ethereum-mining/ethminer#1754]
**Describe the bug**
The hashrate I see on my pool is almost exactly half of what I see on the rig, or exactly what I see from 1/2 cards

Rig shows:
```
m 04:08:23 ethminer Speed 53.73 Mh/s gpu0 26.84 gpu1 26.90 [A2+28] Time: 00:40
```

Pool shows: 
```
Hashrate: 22.38 MH
```

**To Reproduce**

I invoke ethminer like this:

`/opt/ethminer/bin/ethminer -U -P stratum1+tls://0x00000000.myworkername@my-working-stratum-pool.com:8008`

**Expected behavior**
I would expect that the pool shows 53Mh/s or the rig shows 26Mh/s and an error for one card maybe.

**Desktop (please complete the following information):**
- Operating System: [e.g. Windows 10] 
Ubuntu 18.04

- Hardware [e.g. GTX 1070] 
```
01:00.0 VGA compatible controller: NVIDIA Corporation GP104 (rev a1)
03:00.0 VGA compatible controller: NVIDIA Corporation GP104 (rev a1)
```

- Ethminer Version [e.g. 0.14]
0.16

**Additional context**
I don't really know what I'm doing.

**Comment by AndreaLanfranchi** [comment]
> Additional context
I don't really know what I'm doing.

This explains all.

I think you better read something more (google is your friend) about reported hashrate vs. calculated hashrate (by the pool)

This threads are only for ethminer issues ... not to learn mining (sorry if I appear rude)

**Comment by stone212** [comment]
> I think you better read something more (google is your friend) about reported hashrate vs. calculated hashrate (by the pool)

Do you have something you recommend I read?  I have lots of miners where ethminer and the pool hash match very very closely.

**Comment by AndreaLanfranchi** [comment]
What about beginning to add a `-R` ??? 

```
/opt/ethminer/bin/ethminer -U -R -P stratum1+tls://0x00000000.myworkername@my-working-stratum-pool.com:8008
```

This said ... don't know what pool you're using (does it provide a graph comparison among the calculated hashrate and the reported hashrate)

> I have lots of miners where ethminer and the pool hash match very very closely

After how much time ? Do you know how pools "compute" your effective hashrate ?

Example
https://forum.ethereum.org/discussion/5999/reported-hashrate-100-mh-s-effective-hashrate-is-about-70-mh-s

**Comment by AndreaLanfranchi** [comment]
And above all ... READ THE DAMNED DOCUMENTATION BEFORE START ASKING QUESTIONS WHICH HAVE BEEN ANSWERED MILLIONS OF TIMES.

**Comment by stone212** [comment]
@AndreaLanfranchi 

Thanks for that link.  I actually already read that.  

To answer the question I guess I wasn't clear that the pool is my pool so I know how it computes hash is honest.

Again I made the mistake of using older documentation.  It still had -SP in it etc and I had so many pages open I was looking at the wrong one.  So I thought I was up on the documentation and I was, as of a year ago.

To your final point my reply is GET USED TO PEOPLE ASKING QUESTIONS YOU HAVE ALREADY ANSWERED BECAUSE UNTIL DOCS ARE UNIFORM AND DATED WELL AND BETTER WRITTEN IT IS NOT REALLY EASY TO TELL WHAT IS A BUG WHAT IS A DOC ERROR AND WHAT IS USER ERROR AND WELCOME TO THE LIFE OF A DEVELOPER MY FRIEND

Also thank you.

**Comment by AndreaLanfranchi** [comment]
> To answer the question I guess I wasn't clear that the pool is my pool so I know how it computes hash is honest.

So ? Why you ask ? You should know that computed hash rate is based on number of valid solutions submitted in the amount of time at a given diff. If your pool does not have enough samples or computes an average, say, over last hour, **is perfectly obvious that if you compare results after 30 minutes you get half of what expected**.

>Again I made the mistake of using older documentation. It still had -SP in it etc and I had so many pages open I was looking at the wrong one. So I thought I was up on the documentation and I was, as of a year ago.

Always, always, always check for newer docs on the git's project pages before making assumptions.

> GET USED TO PEOPLE ASKING QUESTIONS YOU HAVE ALREADY ANSWERED BECAUSE UNTIL DOCS ARE UNIFORM AND DATED WELL AND BETTER WRITTEN IT IS NOT REALLY EASY TO TELL WHAT IS A BUG WHAT IS A DOC ERROR AND WHAT IS USER ERROR AND WELCOME TO THE LIFE OF A DEVELOPER MY FRIEND

And you, as USER, get used to Open Source projetcs. Developers like me already gifted you of their free time providing a free product and the best documentation possibile. **Do your part understanding what you're using - based on everything available - before asking. There is no paid SLA here**

**Comment by stone212** [comment]
@AndreaLanfranchi 

>  is perfectly obvious that if you compare results after 30 minutes you get half of what expected.

Where are you getting 30 minutes from? 

> Always, always, always check for newer docs on the git's project pages before making assumptions.

I already admitted I was looking at an old doc.  It was my mistake.
