### ISSUE TITLE
0.16 doesn't mine with Parity (but 0.12 does)

### ISSUE THREAD

**Issue by stone212** [ethereum-mining/ethminer#1763]
Parity Ethereum version:` 2.1.9`
ethminer:` 0.16`
Operating system: `Ubuntu 18.04`
GPU: 
```
01:00.0 VGA compatible controller: NVIDIA Corporation GP104 (rev a1)
03:00.0 VGA compatible controller: NVIDIA Corporation GP104 (rev a1)
```

I can not mine on a private blockchain using parity in stratum mode and ethminer 0.16.  The same worker is able to mine on an external stratum pool.

The same worker is able to mine with no change in Parity configuration using ethminer 0.12 with this config:

`./ethminer-0.12/bin/ethminer -U -SP 127.0.0.1:8008`

Here is how I run ethminer 0.16:

`/opt/ethminer/bin/ethminer -U -P stratum+tcp://127.0.0.1:8008`

Here is the output from ethminer:

```
m 01:12:05 ethminer ethminer 0.16.1
 m 01:12:05 ethminer Build: linux/release
cu 01:12:05 ethminer Using grid size: 8,192, block size: 128
 i 01:12:05 ethminer Configured pool 127.0.0.1:8008
 i 01:12:05 main     Selected pool 127.0.0.1:8008
 i 01:12:05 stratum  Stratum mode detected: STRATUM
 i 01:12:05 stratum  Subscribed!
 i 01:12:05 stratum  Authorized worker 
 i 01:12:05 stratum  Established connection with 127.0.0.1:8008 at  [127.0.0.1:8008]
 i 01:12:05 stratum  Spinning up miners...
 i 01:12:05 cuda-0   No work. Pause for 3 s.
 i 01:12:05 cuda-1   No work. Pause for 3 s.
 i 01:12:08 cuda-0   No work. Pause for 3 s.
 i 01:12:08 cuda-1   No work. Pause for 3 s.
 m 01:12:10 ethminer Speed 0.00 Mh/s gpu0 0.00 gpu1 0.00 [A0] Time: 00:00
 i 01:12:11 cuda-1   No work. Pause for 3 s.
 i 01:12:11 cuda-0   No work. Pause for 3 s.
 i 01:12:14 cuda-1   No work. Pause for 3 s.
 i 01:12:14 cuda-0   No work. Pause for 3 s.
```

Here is my parity .toml file:

```
[parity]
chain = "/home/parity/my-chain-spec.json"

[network]
reserved_peers = "/home/parity/reserved-peers.txt"
min_peers = 15

[rpc]
hosts = [""]
cors = [""]

[account]
unlock = ["0x00..."]
password = ["/home/parity/keyPass.txt"]

[mining]
author = "0x00..."

[stratum]
```

`netstat -tulpn | grep '8008'` shows:

```
tcp        0      0 127.0.0.1:8008          0.0.0.0:*               LISTEN      6699/parity
```

Do you see something I do not see?

Parity has 15 peers (and that is min_peers in toml file).

Thank you.

**Comment by AndreaLanfranchi** [comment]
Test latest (0.16 is outdated) and replace `stratum+tcp://127.0.0.1:8008` with `stratum1+tcp://127.0.0.1:8008` as ethminer supports the three different flavors of stratum out there.
Parity implements stratum mode `eth-proxy` compatible.

**Comment by AndreaLanfranchi** [comment]
You were already using stratum1 here #1754 (why on earth did you change it ???)

**Comment by stone212** [comment]
@AndreaLanfranchi 

> Test latest (0.16 is outdated)

0.16 is the latest stable version.  I generally don't use alpha or rc versions but if you recommend it strongly for this case I will.  But "outdated" usually implies a stable version not a potential candidate release.  Do I misunderstand?

>  and replace stratum+tcp://127.0.0.1:8008 with stratum1+tcp://127.0.0.1:8008 as ethminer supports the three different flavors of stratum out there.

Actually I tried that before trying without the `1` and I got a different error.  One bug at a time.  But here is what I get with `stratum1+tcp://`:

```
 m 23:53:08 ethminer ethminer 0.16.1
 m 23:53:08 ethminer Build: linux/release
cu 23:53:08 ethminer Using grid size: 8,192, block size: 128
 i 23:53:08 ethminer Configured pool 127.0.0.1:8008
 i 23:53:08 main     Selected pool 127.0.0.1:8008
 i 23:53:08 stratum  Stratum mode detected: ETHPROXY Compatible
 i 23:53:08 stratum  Could not login:code:-32601 message:Method not found 
 i 23:53:08 main     Disconnected from  [127.0.0.1:8008]
 i 23:53:09 main     No more connections to try. Exiting...
 i 23:53:10 ethminer Terminated!
```

**Comment by AndreaLanfranchi** [comment]
You should neither use Parity's stratum feature which is in BETA.

From their [wiki](https://wiki.parity.io/Mining#stratum) 
> Since 1.6, Parity offers Stratum protocol support (beta). 

This said ... **if** connection works with `stratum+tcp` without the `1` and you keep getting no-work the only reason is that parity node is not pushing jobs.

Before trying the **beta** stratum feature of parity I'd highly recommend to test with the proven http getwork ( `-P http://127.0.0.1:xxx`) and check, also with curl calls, if the node passes errors like for example the following
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32001,
        "message": "Still syncing."
    },
    "id": 73
}
```

**Comment by AndreaLanfranchi** [comment]
To see the stratum/http messages of the conversation among ethminer and work provider (either a pool or your private node) simply add `--verbosity 1` to your launch of ethminer.

**Comment by stone212** [comment]
@AndreaLanfranchi 

> if connection works with stratum+tcp without the 1 and you keep getting no-work the only reason is that parity node is not pushing jobs.

That is what it looks like to me also.  I will share this thread with Parity.

**Comment by AndreaLanfranchi** [comment]
I reiterate ... pick latest 0.18 and add `-v 1` to you CLI arguments ... I will trace stratum messages

**Comment by stone212** [comment]
@AndreaLanfranchi Interesting is that 0.18 and `stratum1+tcp` still causes `Could not login: code:-32601 message:Method not found` so maybe Parity stopped supporting `-eth-proxy`

**Comment by AndreaLanfranchi** [comment]
0.16 will not see a release.
Next scheduled release is 0.18

**Comment by stone212** [comment]
Then this issue is solved on this side.
