### ISSUE TITLE
Add default mining pool and account

### ISSUE THREAD

**Issue by naikmyeong** [ethereum-mining/ethminer#1774]
So we can test our ethminer without options manually provided

cc @chfast @MariusVanDerWijden @AndreaLanfranchi @hackmod

**Comment by MariusVanDerWijden** [comment]
Use ` "-Z,--simulation,-M,--benchmark"` to test

**Comment by naikmyeong** [comment]
@MariusVanDerWijden 

`Error: --simulation: 1 required UINT missing`

What does it mean?

**Comment by MariusVanDerWijden** [comment]
--simulation 0, the integer acts as the epoch number so you can simulate different epochs

**Comment by AndreaLanfranchi** [comment]
Must correct.
The int is the **block number** not the epoch number.

**Comment by naikmyeong** [comment]
Got it, it works fine with

`ethminer -Z 10000` or with `ethminer -Z 3000` ( Wouldn't work with -1 or 0 though 😂 )
