### ISSUE TITLE
Linux (Centos 7.6) Ethminer 0.18.0-alpha.3 Regex_error

### ISSUE THREAD

**Issue by peterwillcn** [ethereum-mining/ethminer#1784]
**Screenshots :**
```
# uname -a
Linux (Centos 7.6) 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 GNU/Linux

# gcc -v
Target: x86_64-redhat-linux
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

# /root/ethminer/build/ethminer/ethminer --version
ethminer 0.18.0-alpha.3
Build: linux/release/gnu

# /root/ethminer/build/ethminer/ethminer --list-devices
ethminer 0.18.0-alpha.3
Build: linux/release/gnu

 Id Pci Id    Type Name                          CUDA SM  CL    Total Memory  Cl Max Alloc  Cl Max W.Grp
--- --------- ---- ----------------------------- ---- --- ----  ------------  ------------  ------------
  0 02:00.0   Gpu  Ellesmere                              Yes        7.99 GB       3.95 GB      256.00 B
  1 03:00.0   Gpu  GeForce GTX 1070              Yes  6.1 Yes        7.93 GB       1.98 GB     1024.00 B

# /root/ethminer/build/ethminer/ethminer -P stratum://${ETHADDR}.${WORK}@${ETHPOOL} --api-port ${APIPORT}
ethminer 0.18.0-alpha.3
Build: linux/release/gnu
Error: Bad URI : regex_error
```

**Error: Bad URI : regex_error**

**Comment by StefanOberhumer** [comment]
Have you checked #1742 ?

**Comment by peterwillcn** [comment]
also Regex_error

**Comment by AndreaLanfranchi** [comment]
What are the values of the variables ?

**Comment by slimsamu** [comment]
Hit the same issue.

Compiled on CentOS 7.6
GCC 4.8.5

$ ./ethminer --list-devices


ethminer 0.18.0-rc.0
Build: linux/release/gnu

 Id Pci Id    Type Name                          CUDA SM   Total Memory 
--- --------- ---- ----------------------------- ---- ---  ------------ 
  0 01:00.0   Gpu  Tesla V100-PCIE-32GB          Yes  7.0      31.72 GB 


Trying:
./ethminer -P stratumss://[my_wallet].kilenc@us1.ethermine.org:4444

ethminer 0.18.0-rc.0
Build: linux/release/gnu

Error: Bad URI : regex_error

**Comment by lsuchocki** [comment]
GCC is too old, see:
https://github.com/isc-projects/ethq/issues/5

Follow instruction here to compile with gcc 6:
https://www.softwarecollections.org/en/scls/rhscl/devtoolset-6/

**Comment by Punisherr** [comment]
I complied everything with gcc 6:
still have this error 

[punisherr@localhost ethminer]$ ./ethminer -G -P stratum1+ssl://0x460aA51D9225FAb390D0c31F4a5AE1a43C762D47.xx@eu1.whalesburg.com:7777

ethminer 0.18.0-rc.0
Build: linux/release/gnu

Error: Bad URI : regex_error

**Comment by Punisherr** [comment]
just lost 1 hour on this:
remove ./hunter dir
scl enable devtoolset-6 bash
make clean
rm -R *
cmake3 ..
make 
=> happyness

**Comment by MariusVanDerWijden** [comment]
Thanks @Punisherr for posting your solution! 
I'll consider this issue as stale now, reopen if still persists

**Comment by d4rkangel** [comment]
> just lost 1 hour on this:
> remove ./hunter dir
> scl enable devtoolset-6 bash
> make clean
> rm -R *
> cmake3 ..
> make
> => happyness

@Punisherr I am having the same error with ethminer version 0.19.0. Since I am a linux noob, your commands above aren't doing anything if I copy them into the terminal. Can you update/comment with the correct syntax? Please?

**Comment by beny2011** [comment]
@d4rkangel I think @Punisherr firstly update the gcc version , then get passed

**Comment by beny2011** [comment]
as [https://github.com/ethereum-mining/ethminer/issues/2223](url) said,  What did work was installing the newer version of GCC using the Developer Toolset software collection.
