### ISSUE TITLE
0.18 alpha 3 build 2687 - nvrtc64_100_0.dll not found

### ISSUE THREAD

**Issue by MiningGuru** [ethereum-mining/ethminer#1786]
Hello,

I just test build 2687 @GTX 1070 rig with nvidia driver 416.94 and at beginning of start ethminer.exe I get the windows error message - nvrtc64_100_0.dll not found.

416.94 nvidia driver.
using ethmingerwatch with start line:

ethminer --exit -U  --HWMON 1 -R -P stratum1+tcp://0xmywallet@eth-eu1.nanopool.org:9999/Zotxc1070-x/xxxxxxxxx%googlemail.com

There could be a driver issue perhabs I should install the absolut latest one ???

**Comment by MiningGuru** [comment]
Info build 2685 is working.

**Comment by AndreaLanfranchi** [comment]
Where did you get the build from ?
Which os are you on ? (Linux ? / Windows ?)

**Comment by MiningGuru** [comment]
I donwonload from appvenior. 
Windows 10 1809 (build 2685 is working) 2687 not!

**Comment by AndreaLanfranchi** [comment]
Have you noticed that builds 2686 and 2687 have a very informative msg **( DO NOT MERGE )** ?
Always test only builds from PR which have been merged !
