### ISSUE TITLE
problem with json on https://eth.nanopool.org

### ISSUE THREAD

**Issue by snajperro** [ethereum-mining/ethminer#1787]
Fall after some time!, but this is only for one machine .
i have installed last version 0.17.0-rc.2
[https://pastebin.com/kSkGZjcX](https://pastebin.com/kSkGZjcX)

**Comment by AndreaLanfranchi** [comment]
The message data your rig have received is incomplete
```
{"jsonrpc":"2.0","id":0,"result":["0xa692b6e256576eb23a3498b554390a98a251235a9088dcc21c68057
```
Missing close quotes, close square braces and curly braces.
