### ISSUE TITLE
what():  in Json::Value::find(key, end, found): requires objectValue or nullValue

### ISSUE THREAD

**Issue by snajperro** [ethereum-mining/ethminer#1790]
[https://pastebin.com/y6w97DuM](https://pastebin.com/y6w97DuM)
what about this problem?

**Comment by AndreaLanfranchi** [comment]
Here is the key

```
Dec 25 08:08:22 192 cr.sh[31502]:  i 08:08:22 stratum   << {"id":0,"jsonrpc":"2.0","result":["0x87dcd91abc08df6445836f21653d150b9e09e94dd3995f077493dd4ebfe08c89","0x04a3fa11bc92b0688ffd46fcd172741eed4f3ec77309711b3c0f92600ce8a125","0x0112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0x6a0615"]}
Dec 25 08:08:22 192 cr.sh[31502]:  i 08:08:22 stratum  Job: #87dcd91a… eu1.ethermine.org [172.65.207.106:4444]
Dec 25 08:08:22 192 cr.sh[31502]:  i 08:08:22 stratum   << 3e70e52ba","0x6a0617"]}
```
You see your last line shows an incomplete message received

**Comment by AndreaLanfranchi** [comment]
Also ... which version of ethminer are you on ?

**Comment by snajperro** [comment]
[https://pastebin.com/9ZSjw8SH](https://pastebin.com/9ZSjw8SH)
use this ethminer-0.17.0-rc.2-linux-x86_64.tar.gz

**Comment by AndreaLanfranchi** [comment]
Which pool are you using ?

**Comment by snajperro** [comment]
I use https://ethermine.org 
with two rig :rig1, rig2 ,
when i switch rig1 from ethereum to another one as result i don't have any problem!
