### ISSUE TITLE
Linux (Fedora 29) NVIDIA OpenCL w/ CUDA

### ISSUE THREAD

**Issue by ng0177** [ethereum-mining/ethminer#1792]
This devastating bug appears on Fedora 29 running  4.19.10-300.fc29.x86_64:
> `~/Download/ethminer-0.17.0-rc.2-linux-x86_64/bin/ethminer --opencl --cl-parallel-hash 4 -R -P stratum1+tcp://address@eth-eu1.nanopool.org:9999/miner --farm-recheck 5000

--cl-parallel-hash ignored. No longer applies
 m 21:20:38 ethminer ethminer 0.17.0-rc.2
 m 21:20:38 ethminer Build: linux/release
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
 i 21:20:39 ethminer Found suitable OpenCL device [Intel(R) HD Graphics Skylake ULT GT2] with 3.840 GB of GPU memory
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
 i 21:20:39 ethminer Configured pool eth-eu1.nanopool.org:9999
 i 21:20:39 main     Selected pool eth-eu1.nanopool.org:9999
 i 21:20:39 stratum  Stratum mode detected: ETHPROXY Compatible
 i 21:20:39 stratum  Logged in!
 i 21:20:39 stratum  Established connection with eth-eu1.nanopool.org:9999 at  [51.15.39.52:9999]
 i 21:20:39 stratum  Spinning up miners...
cl 21:20:39 cl-0     No work. Pause for 3 s.
 i 21:20:39 stratum  Job: #d9f176f8… eth-eu1.nanopool.org [51.15.39.52:9999]
 i 21:20:39 stratum  Pool difficulty: 10.00K megahash
 i 21:20:39 stratum  New epoch 231
 i 21:20:39 stratum  Job: #d9f176f8… eth-eu1.nanopool.org [51.15.39.52:9999]
 i 21:20:39 stratum  Job: #be26d567… eth-eu1.nanopool.org [51.15.39.52:9999]
cl 21:20:42 cl-0     Platform: Intel Gen OCL Driver
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
cl 21:20:42 cl-0     Device:   Intel(R) HD Graphics Skylake ULT GT2 / OpenCL 2.0 beignet 1.3
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
 m 21:20:44 ethminer Speed 0.00 Mh/s gpu0 0.00 A0 Time: 00:00
cl 21:20:44 cl-0     OpenCL kernel
 X 21:20:44 cl-0     OpenCL kernel build log:
stringInput.cl:315:9: warning: implicit declaration of function 'amd_bitalign' is invalid in OpenCL
stringInput.cl:175:13: note: expanded from macro 'KECCAK_PROCESS'
stringInput.cl:93:60: note: expanded from macro 'KECCAKF_1600_RND'
stringInput.cl:81:24: note: expanded from macro 'ROTL64_1'
stringInput.cl:315:9: error: no matching function for call to 'as_uint2'
stringInput.cl:175:13: note: expanded from macro 'KECCAK_PROCESS'
stringInput.cl:156:13: note: expanded from macro 'KECCAKF_1600_RND'
/usr/lib64/beignet/include/ocl_as.h:134:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'long' for 1st argument
/usr/lib64/beignet/include/ocl_as.h:147:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'ulong' (aka 'unsigned long') for 1st argument
/usr/lib64/beignet/include/ocl_as.h:160:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'int2' (vector of 2 'int' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:187:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'short3' (vector of 3 'short' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:199:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'short4' (vector of 4 'short' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:211:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'ushort3' (vector of 3 'ushort' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:223:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'ushort4' (vector of 4 'ushort' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:235:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'char8' (vector of 8 'char' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:248:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'uchar8' (vector of 8 'uchar' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:261:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'double' for 1st argument
/usr/lib64/beignet/include/ocl_as.h:274:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'float2' (vector of 2 'float' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:287:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'half3' (vector of 3 'half' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:299:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'half4' (vector of 4 'half' values) for 1st argument
stringInput.cl:425:5: warning: use of out-of-scope declaration of 'amd_bitalign'
stringInput.cl:175:13: note: expanded from macro 'KECCAK_PROCESS'
stringInput.cl:93:60: note: expanded from macro 'KECCAKF_1600_RND'
stringInput.cl:81:24: note: expanded from macro 'ROTL64_1'
stringInput.cl:315:9: note: previous declaration is here
stringInput.cl:175:13: note: expanded from macro 'KECCAK_PROCESS'
stringInput.cl:93:60: note: expanded from macro 'KECCAKF_1600_RND'
stringInput.cl:81:24: note: expanded from macro 'ROTL64_1'
stringInput.cl:425:5: error: no matching function for call to 'as_uint2'
stringInput.cl:175:13: note: expanded from macro 'KECCAK_PROCESS'
stringInput.cl:156:13: note: expanded from macro 'KECCAKF_1600_RND'
/usr/lib64/beignet/include/ocl_as.h:134:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'long' for 1st argument
/usr/lib64/beignet/include/ocl_as.h:147:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'ulong' (aka 'unsigned long') for 1st argument
/usr/lib64/beignet/include/ocl_as.h:160:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'int2' (vector of 2 'int' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:187:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'short3' (vector of 3 'short' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:199:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'short4' (vector of 4 'short' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:211:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'ushort3' (vector of 3 'ushort' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:223:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'ushort4' (vector of 4 'ushort' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:235:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'char8' (vector of 8 'char' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:248:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'uchar8' (vector of 8 'uchar' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:261:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'double' for 1st argument
/usr/lib64/beignet/include/ocl_as.h:274:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'float2' (vector of 2 'float' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:287:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'half3' (vector of 3 'half' values) for 1st argument
/usr/lib64/beignet/include/ocl_as.h:299:20: note: candidate function not viable: no known conversion from 'const __constant uint2' (vector of 2 'uint' values) to 'half4' (vector of 4 'half' values) for 1st argument

 X 21:20:44 cl-0     OpenCL kernel build error (-11):
clBuildProgram
/home/user/bin/script: line 14: 16803 Segmentation fault      (core dumped) ~/Keep/ethminer-0.17.0-rc.2-linux-x86_64/bin`

**Comment by AndreaLanfranchi** [comment]
Intel graphics is not supported. Only Nvidia and or Amd

**Comment by ng0177** [comment]
OK, I switched to another machine w/ NVIDIA driver and w/o CUDA but also Fedora 29:

`$ lspci -k |grep -iA 3 vga
1d:00.0 VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] (rev a1)
	Subsystem: Micro-Star International Co., Ltd. [MSI] Device 3282
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia_drm, nvidia`

interestingly

`$ clinfo | grep -i intel
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short cl_khr_gl_sharing
  Platform Extensions function suffix             Intel
  Platform Name                                   Intel Gen OCL Driver`

and

`$ ./ethminer -G --list-devices
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
cl_get_gt_device(): error, unknown device: 0

Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName`

I do not know where opencl i.e. the installed ocl-icd package on an AM4 AMD Board gets the idea of Intel from. ethminer seems to turn in. Any ideas? Thanks!

**Comment by ng0177** [comment]
OK, then were is the problem:

a) Fedora 29
b) exclusive NVIDIA driver w/o CUDA
c) ocl-icd package
d) ethminer 0.17.0-rc.2 (unlikely)

Appreciate!

**Comment by hackmod** [comment]
`b) exclusive NVIDIA driver w/o CUDA`
what do you mean?
did you install nvidia driver correctly? and `nvidia-smi` works with no problem?

**Comment by ng0177** [comment]
bash: nvidia-smi: command not found...
Packages providing this file are:
'xorg-x11-drv-nvidia-cuda'
'xorg-x11-drv-nvidia-340xx-cuda'
'xorg-x11-drv-nvidia-390xx-cuda'

Yes, the NVIDIA driver from the official Fedora distribution is installed correctly. I cannot install cuda because of its "persistence daemon" locking up the boot process every now and then. However, opencl should work w/o CUDA.

**Comment by smurfy** [comment]
As far as i remember, opencl on nvidia runs via cuda as-well. its basically a transpiler to cuda.

**Comment by hackmod** [comment]
I guess that's your real problem. Nvidia OpenCL depends on Nvidia cuda driver and it needs x11 driver too.

**Comment by ng0177** [comment]
https://ask.fedoraproject.org/en/question/121596/fedora-28-failed-to-boot-after-system-update-with-installed-nvidia-driver-from-rpm-fusion-nonfree-nvidia-driver/ hints at how to work around and install CUDA. Of course, then, opencl is not required any more.

**Comment by AndreaLanfranchi** [comment]
So a solution is found.
Closing
