### ISSUE TITLE
Failed to load ca certificates

### ISSUE THREAD

**Issue by ng0177** [ethereum-mining/ethminer#1794]
certificates file location in Fedora is:
/etc/ssl/certs/ca-bundle.trust.crt

certificates file location in Ubuntu is:
/etc/ssl/certs/ca-certificates.crt

i.e. statums fails in Fedora, see below. Any chance to look at both locations?

However, sudo ln -s /etc/ssl/certs/ca-bundle.trust.crt /etc/ssl/certs/ca-certificates.crt does not fix the problem in Fedora!

ethminer-0.17.0-rc.2-linux-x86_64/bin/ethminer -P stratums://0xaddress.miner@eth-eu1.nanopool.org:9999
 m 15:07:17 ethminer ethminer 0.17.0-rc.2
 m 15:07:17 ethminer Build: linux/release
cu 15:07:17 ethminer Using grid size: 8,192, block size: 128
 i 15:07:17 ethminer Configured pool eth-eu1.nanopool.org:9999
 i 15:07:17 main     Selected pool eth-eu1.nanopool.org:9999
 X 15:07:17 main     Failed to load ca certificates. Either the file '/etc/ssl/certs/ca-certificates.crt' does not exist
 X 15:07:17 main     or the environment variable SSL_CERT_FILE is set to an invalid or inaccessible file.
 X 15:07:17 main     It is possible that certificate verification can fail.
 X 15:07:17 stratum  SSL/TLS Handshake failed: stream truncated
 i 15:07:18 main     No more connections to try. Exiting...
 i 15:07:19 ethminer Terminated!

**Comment by StefanOberhumer** [comment]
Are you sure eth-eu1.nanopool.org:9999 supports SSL?
**I think eth-eu1.nanopool.org:9999 uses just plain tcp.**
So you should use 
`-P stratum1+tcp://ETH_WALLET@eth-eu1.nanopool.org:9999/WORKERNAME/EMAIL`
or
`-P stratum1+tcp://ETH_WALLET.WORKERNAME@eth-eu1.nanopool.org:9999`

**Comment by AndreaLanfranchi** [comment]
@ng0177 

this info should give hint
```
X 15:07:17 main Failed to load ca certificates. Either the file '/etc/ssl/certs/ca-certificates.crt' does not exist
X 15:07:17 main or the environment variable SSL_CERT_FILE is set to an invalid or inaccessible file.
```

simply add this export before you start ethminer

```
export SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.trust.crt
```
(it's also explained in ethminer --help)

Also you may also set SSL_NOVERIFY to whichever value to completely bypass the certificate validation.

beside this I think @StefanOberhumer is right. Nanopool does not support SSL/TLS connections on ethereum port 9999
