### ISSUE TITLE
QUESTION: restarting the miner on any error, debugging CUDA errors in OC?

### ISSUE THREAD

**Issue by evlo** [ethereum-mining/ethminer#1799]
Hi,

First of this is a question, i'm not saying ethminer is doing anything wrong, etc.

I decided to do some improvements to nvidia part of my mini farm.
I'm running 1060s. I don't think I have any extreme OC, as I don't know how to change memory timing on 1060s still :).
So only thing I changed is that i went from 0.15 to 0.17rc2 (I did not try 0.16 as for me it after few days of mining disconnected from pool and never reconnected - I don't know, maybe 0.17rc2 will be same, I will see) and mainly I stopped managing cards using power limit and undervolted them to 650mv. 

On one rig I run into issue - that popups on **ALL cards** at same time after 4 to 6 hours of mining:
**gpu error: cuda error in func dev::eth::cudaminer::search at line 460 unspecified launch failure**
99% too much memory OC on **ONE card**, or maybe some GPU unable to handle 650mV, but from my experience short in ETH mining on undervolted cards it would result t lowering core freq.
I think the rig did not crash with power limit, older drivers (probably even cuda 9 or 8 and not 10 that i'm now using) and ethminer 0.15 - so lot of changes :( - or if it did crash, it crashed ethminer entirely so my watchdog powrshell would restart it. 
The issue now is that ethminer just throws out errors for all the cards and continues outputting that it is mining with 0 hashrate.
Maybe I just missed some new switch?

Is there any way to identify what really crashed or at least which GPU.
I'm on windows. 

BTW I'm also trying 1809 windows and there is no nvidia-smi for nvidia drivers (DCH) compatible with 1809 windows - that is how I found out that undervolting will save me 110W on one 12GPU rig.

I know there is kinda related issue: https://github.com/ethereum-mining/ethminer/issues/199

Update: now it occurred to me that I could run 12 separate eth miner instances on each rig to see which crashes. But still it would be interesting to find a way to debug which card crashed (or resulted in 0MH/s for the whole rig) and WHY.
It still does not make sense to me that I see crashes after switching to undervolting, when undervolting should really only affect gpu and not memory.

Update2: so it seems first GPU to crash is the culprit, needs more verifying thought, but just looks likes that is the case. Still - having memory errors after changing power limit to undervolting, while keeping same memory OC settings is just mind boggling.
Do you have any explanation for this behavior?

**Comment by evlo** [comment]
Here is screenshot so the thing in question and desired behavior for me is more understandable
https://i.imgur.com/KLfQRmk.png

I know possible solution is to check pool api and restart miner - check ethminer api for hashrate and restart miner, i'm only asking if it would be possible to implement more convenient, for me, solution.

**Comment by AndreaLanfranchi** [comment]
Simply add `--exit` to the command line you use to start ethminer.

From `ethminer -H misc`
```
 --exit              FLAG Stop ethminer whenever an error is encountered
```

**Comment by evlo** [comment]
Oh, so that is the switch/parameter I was missing. It is interesting that 0.15 version would exit without it, while it still does have "--exit" paramater.

I noticed, that first GPU in the log to fail seems to be one with too much memory OC. Do you think that using "2>>" to redirect error output will make ethminer log gpu errors to log file? Ie. like this:
`"ethminer.exe" --exit --HWMON 1 --api-port 12000 --report-hashrate --verbosity 2 --farm-recheck 10000 --cuda -P stratum+ssl://*@eu1.ethermine.org:5555 -P stratum+ssl://* 2>> ethMinerError.txt`


_(Display driver fails is logged in windows event log, but no detail about which gpu crashed it :( . I guess I will see if there is anything in cuda 10 toolkit.)_

**Comment by AndreaLanfranchi** [comment]
>using "2>>" to redirect error output will make ethminer log gpu errors to log file?

Unfortunately not.
It is a driver error, not ethminer.

If you were in linux you could detect the error (Xid) using Dmesg.
In Windows i dont' know where are those errors logged.

Anyway ... such errors are always due to excessive overclocking.
