### ISSUE TITLE
Help Please - separating username and workername

### ISSUE THREAD

**Issue by R00dNet** [ethereum-mining/ethminer#1803]
Hi,

I am still having trouble with ethminer separating username and workername. This is the syntax I have for bat file:

stratum2+tcp://testuser.testworker:x@europe.ethash-hub.miningpoolhub.com:17020

If I load that up it states worker is only testuser not testuser.testworker

If I add %2e in place of dot worker is seen as testuseretestworker < small e is where dot should be

The guide states :
stratum2+tcp://USERNAME%2eWORKERNAME:WORKERPWD@europe.ethash-hub.miningpoolhub.com:20535

So I do not understand why %2e is not working, please advise.

**Comment by gennadiv** [comment]
stratum2+tcp://USERNAME%%2eWORKERNAM

**Comment by R00dNet** [comment]
thanks gennadiv

**Comment by AndreaLanfranchi** [comment]
Ouch yes. Forgot to mention that on Windows batch files `%` has a special meaning: `%2` would mean the second argument to the batch file.

You further need to escape with double %%
