### ISSUE TITLE
OpenCL kernel build error (-11): clBuildProgram

### ISSUE THREAD

**Issue by PsySc0rpi0n** [ethereum-mining/ethminer#1804]
**Describe the bug**
Thread 16 "cl-0" received signal SIGSEGV, Segmentation fault.

System info from some terminal commands (command -- output [or link to ouput])

`DRI_PRIME=0 glxinfo | grep "OpenGL renderer"` -- OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile

`DRI_PRIME=1 glxinfo | grep "OpenGL renderer"` -- OpenGL renderer string: Gallium 0.4 on AMD PITCAIRN (DRM 3.26.0 / 4.18.0-0.bpo.3-amd64, LLVM 3.9.1)

`glxinfo` -- https://paste.debian.net/1058940/

`DRI_PRIME=1 glxinfo` -- https://paste.debian.net/1058939/

`./ethminer -G -M 0` -- https://paste.debian.net/1058941/
`./ethminer -G -M 1` -- https://paste.debian.net/1058943/

Backtrace from gdb:
```
gdb ethminer
run -G -M 0
thread 16
bt full
thr apply all bt full
```
https://paste.debian.net/1058945/

```
run -G -M 1
thread 16
bt full
thr apply all bt full
```
https://paste.debian.net/1058946/

**To Reproduce**
1. run ethminer -G -M 0[1]
2. See error

**Expected behavior**
Hoped it worked smootlhy.. :)

**Screenshots (Optional)**

**Desktop (please complete the following information):**
- Operating System: Debian 9.6 (Stretch) 64bit
- Hardware: AMD RADON HD7970M
- Ethminer Version: ethminer 0.18.0-alpha.3-18+commit.54d63f99.dirty

**Additional context**
Kernel Version: 4.18.0-0.bpo.3-amd64
Please contact me if any other info is needed like dmesg or Xorg.log

EDITED:
Forgot to say that I added the following line of code:
`#pragma OPENCL EXTENSION cl_clang_storage_class_specifiers : enable`
to the top of the following file:
PATH_TO_ETHEREUM/build/libethash-cl/kernels/cl/ethash.cl
Then recompiled it again using the following commands:
`cmake -DETHASHCUDA=OFF ..`
`cmake --build .`
`sudo make install`

**Comment by AndreaLanfranchi** [comment]
We cant' handle this issue as there is manual source modification.
I see you have opened another issue to reenable this extension.
Closing this one.
