### ISSUE TITLE
HELP - How to uninstall 

### ISSUE THREAD

**Issue by PsySc0rpi0n** [ethereum-mining/ethminer#1807]
I tried to run:
`make uninstall`
and
`make clear`
inside ./ethminer/build where there is Makefile, but it always returns the following message:
`make: *** No rule to make target 'uninstall'.  Stop.`
and
`make: *** No rule to make target 'clear'.  Stop.`

**Comment by AndreaLanfranchi** [comment]
There is no "uninstall" feature as there is no "install".
If you want to remove simply delete the directory(ies) where you cloned the repo

**Comment by PsySc0rpi0n** [comment]
I followed instructions from [here](https://github.com/ethereum-mining/ethminer/blob/master/docs/BUILD.md)

And last step it says to:
`sudo make install`

so I did. I wanted to uninstall now because I can't make it to work on my OS.

**Comment by PsySc0rpi0n** [comment]
So no solution to undo the last command of instructions to install from sources?

`sudo make install`

**Comment by MariusVanDerWijden** [comment]
you don't have to uninstall it, since it is only a binary file.
You just have to delete the directories
