### ISSUE TITLE
Network socket issue?

### ISSUE THREAD

**Issue by fenlasonb** [ethereum-mining/ethminer#1811]
**Describe the bug**
Miney@us1.ethermine.org:5555
 m 21:23:56 main     ethminer 0.17.0-rc.2
 m 21:23:56 main     Build: windows/release
cu 21:23:56 main     Using grid size: 8,192, block size: 128
 i 21:23:56 main     Configured pool us1.ethermine.org:5555
 i 21:23:56 main     Selected pool us1.ethermine.org:5555
 X 21:23:57 stratum  Error  [2606:4700:90:0:b886:9f1:5c3e:5711]:5555 [ The I/O operation has been aborted because of either a thread exit or an application request ]
 i 21:23:58 main     Selected pool us1.ethermine.org:5555
 X 21:23:59 stratum  Error  [2606:4700:90:0:b886:9f1:5c3e:5711]:5555 [ A connect request was made on an already connected socket ]
 X 21:23:59 stratum  Socket read failed: The network connection was aborted by the local system
 X 21:23:59 stratum  Error  172.65.218.238:5555 [ The I/O operation has been aborted because of either a thread exit or an application request ]
 X 21:23:59 stratum  No more IP addresses to try for host: us1.ethermine.org
 i 21:23:59 main     Disconnected from  [172.65.218.238:5555]
 i 21:24:20 main     Selected pool us1.ethermine.org:5555

C:\Users\CrypteyMiner\Downloads\bin>echo -1073741819
-1073741819

**Desktop (please complete the following information):**
- Windows 10
- Hardware: 2 GTX 1070 ti 2 AMD 570 rx
-ethminer 0.17.0-rc.2

**Comment by lesjokolat** [comment]
add your startup command line. Also add -v3 to get more detailed output.

**Comment by fenlasonb** [comment]
startup:

ethminer.exe -U -P stratum1+ssl://0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney@us1.ethermine.org:5555
echo %ERRORLEVEL%
pause




Adding now

**Comment by fenlasonb** [comment]
C:\Users\CrypteyMiner\Downloads\bin>ethminer.exe -U -P stratum1+ssl://0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney@us1.ethermine.org:5555 -v3
 m 13:33:53 main     ethminer 0.17.0-rc.2
 m 13:33:53 main     Build: windows/release
cu 13:33:53 main     Using grid size: 8,192, block size: 128
 i 13:33:53 main     Configured pool us1.ethermine.org:5555
 i 13:33:53 main     Selected pool us1.ethermine.org:5555
 i 13:33:54 main     Selected pool us1.ethermine.org:5555
 i 13:33:54 stratum   >> {"id":1,"method":"eth_submitLogin","params":["0x8d36ea933dd02aeffb22318125a1d9583aefbd01"],"worker":"CrypteyMiney"}
 X 13:33:54 stratum  Error  [2606:4700:90:0:b886:9f1:5c3e:5711]:5555 [ A connect request was made on an already connected socket ]
 X 13:33:54 stratum  Socket read failed: The network connection was aborted by the local system
 X 13:33:54 stratum  Error  172.65.218.238:5555 [ The I/O operation has been aborted because of either a thread exit or an application request ]
 X 13:33:54 stratum  No more IP addresses to try for host: us1.ethermine.org
 i 13:33:54 main     Disconnected from  [172.65.218.238:5555]
 i 13:33:55 main     Selected pool us1.ethermine.org:5555

C:\Users\CrypteyMiner\Downloads\bin>echo -1073741819
-1073741819

C:\Users\CrypteyMiner\Downloads\bin>pause
Press any key to continue . . .

**Comment by fenlasonb** [comment]
m 23:38:35 main     Solutions A477+4 gpu0:A235+3 gpu1:A242+1
 m 23:38:40 main     Speed 53.47 Mh/s gpu0 26.73 gpu1 26.74 Time: 10:04
 m 23:38:40 main     Solutions A477+4 gpu0:A235+3 gpu1:A242+1
 m 23:38:45 main     Speed 53.47 Mh/s gpu0 26.73 gpu1 26.75 Time: 10:04
 m 23:38:45 main     Solutions A477+4 gpu0:A235+3 gpu1:A242+1
 i 23:38:48 stratum   << {"id":0,"jsonrpc":"2.0","result":["0xa0ccf6a1cd5df2b1e6c333ac8c8bb4f75c55aff2af11fe83697ba0ecd7d699d2","0x3c7815d93a8cb565aefc82a2d95bfc6a5e1c216cc707b143801f68d3a80f493e","0x0112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0x6b5b4b"]}
 i 23:38:48 stratum  Job: #a0ccf6a1... us1.ethermine.org [[2606:4700:90:0:b886:9f1:5c3e:5711]:5555]
 m 23:38:50 main     Speed 53.46 Mh/s gpu0 26.72 gpu1 26.74 Time: 10:04
 m 23:38:50 main     Solutions A477+4 gpu0:A235+3 gpu1:A242+1
 m 23:38:55 main     Speed 53.48 Mh/s gpu0 26.73 gpu1 26.75 Time: 10:04
 m 23:38:55 main     Solutions A477+4 gpu0:A235+3 gpu1:A242+1
 m 23:39:00 main     Speed 53.47 Mh/s gpu0 26.72 gpu1 26.75 Time: 10:04
 m 23:39:00 main     Solutions A477+4 gpu0:A235+3 gpu1:A242+1
 X 23:39:05 stratum  Socket read failed: The network connection was aborted by the local system
 i 23:39:05 main     Disconnected from us1.ethermine.org [[2606:4700:90:0:b886:9f1:5c3e:5711]:5555]
 m 23:39:05 main     not-connected
 i 23:39:05 main     Suspend mining due connection change...
 i 23:39:05 main     Selected pool us1.ethermine.org:5555
 i 23:39:06 cuda-1   No work. Pause for 3 s.
 i 23:39:06 cuda-0   No work. Pause for 3 s.
 X 23:39:06 stratum  Error  172.65.218.238:5555 [ The I/O operation has been aborted because of either a thread exit or an application request ]
 X 23:39:06 stratum  No more IP addresses to try for host: us1.ethermine.org
 i 23:39:07 main     Disconnected from us1.ethermine.org [172.65.218.238:5555]
 i 23:39:08 main     Selected pool us1.ethermine.org:5555
 i 23:39:09 main     Selected pool us1.ethermine.org:5555
 i 23:39:09 cuda-1   No work. Pause for 3 s.
 i 23:39:09 cuda-0   No work. Pause for 3 s.
 i 23:39:09 stratum   >> {"id":1,"method":"eth_submitLogin","params":["0x8d36ea933dd02aeffb22318125a1d9583aefbd01"],"worker":"CrypteyMiney"}
 X 23:39:09 stratum  Error  172.65.218.238:5555 [ A connect request was made on an already connected socket ]
 X 23:39:09 stratum  Socket read failed: The network connection was aborted by the local system
 X 23:39:09 stratum  Error  [2606:4700:90:0:b886:9f1:5c3e:5711]:5555 [ The I/O operation has been aborted because of either a thread exit or an application request ]
 X 23:39:09 stratum  No more IP addresses to try for host: us1.ethermine.org
 i 23:39:09 main     Disconnected from us1.ethermine.org [[2606:4700:90:0:b886:9f1:5c3e:5711]:5555]
 i 23:39:10 main     Selected pool us1.ethermine.org:5555
 i 23:39:12 main     Selected pool us1.ethermine.org:5555
 m 23:39:12 main     not-connected

C:\Users\CrypteyMiner\Downloads\bin>echo -1073741819
-1073741819

**Comment by lesjokolat** [comment]
What happens if you connect to a non ssl port? Same error?

**Comment by fenlasonb** [comment]
No firewalls
No antivirus
no Qos

And haven't seen any issues on the localnetwork.

:/

**Comment by fenlasonb** [comment]
Going to try the regular stratum1+tcp 4444 

Will update

**Comment by AndreaLanfranchi** [comment]
Any news on this ?

**Comment by AndreaLanfranchi** [comment]
Closing. No Feed Back.

**Comment by fenlasonb** [comment]
Hello

Just wanted to update. It appears the issue has resolved going to port 4444 no ssl.

Wonder why
