### ISSUE TITLE
ethminer 0.18.0-alpha.3  and  Adrenalin 2019 Edition 19.1.1 Optional

### ISSUE THREAD

**Issue by gennadiv** [ethereum-mining/ethminer#1816]
not running two cards why is new driver Adrenalin 2019 Edition 19.1.1 Optional version ethminer 0.18.0-alpha.3 but with other versions it works in than zagvostka urgently waiting for an answer ?

C:\Users\гена\Desktop\ethminer-0.17.0-rc.2-cuda10.0-windows-amd64>ethminer.exe -G -P stratum2+tcp://gennadiv%2e1:x@europe.ethash-hub.miningpoolhub.com:20535 -P stratum2+tcp://gennadiv%2e1:x@us-east.ethash-hub.miningpoolhub.com:20535 --farm-recheck 200 --HWMON 0 --cl-local-work 128 --cl-global-work 65536
 m 12:40:03 main     ethminer 0.17.0-rc.2
 m 12:40:03 main     Build: windows/release
 i 12:40:04 main     Found suitable OpenCL device [Ellesmere] with 8,000 GB of GPU memory
 i 12:40:04 main     Found suitable OpenCL device [Ellesmere] with 4,000 GB of GPU memory
 i 12:40:04 main     Found suitable OpenCL device [Tonga] with 4,000 GB of GPU memory
 i 12:40:04 main     Found suitable OpenCL device [Ellesmere] with 4,000 GB of GPU memory
 i 12:40:04 main     Found suitable OpenCL device [Ellesmere] with 8,000 GB of GPU memory
 i 12:40:04 main     Found suitable OpenCL device [Ellesmere] with 4,000 GB of GPU memory
 i 12:40:04 main     Found suitable OpenCL device [Ellesmere] with 8,000 GB of GPU memory
 i 12:40:04 main     Found suitable OpenCL device [Ellesmere] with 4,000 GB of GPU memory
 i 12:40:04 main     Configured pool europe.ethash-hub.miningpoolhub.com:20535
 i 12:40:04 main     Configured pool us-east.ethash-hub.miningpoolhub.com:20535
 i 12:40:04 main     Selected pool europe.ethash-hub.miningpoolhub.com:20535
 i 12:40:04 stratum  Stratum mode detected: ETHEREUMSTRATUM (NiceHash)
 i 12:40:04 stratum  Subscribed to stratum server
 i 12:40:04 stratum  Extranonce set to 027e (nicehash)
 i 12:40:04 stratum  Job: #742d174b...  [18.197.166.72:20535]
 i 12:40:04 stratum  Pool difficulty: 8.60K megahash
 i 12:40:04 stratum  New epoch 234
 i 12:40:05 stratum  Authorized worker gennadiv.1
 i 12:40:05 stratum  Established connection with europe.ethash-hub.miningpoolhub.com:20535 at  [18.197.166.72:20535]
 i 12:40:05 stratum  Spinning up miners...
cl 12:40:05 cl-0     No work. Pause for 3 s.
cl 12:40:05 cl-1     No work. Pause for 3 s.
cl 12:40:05 cl-2     No work. Pause for 3 s.
cl 12:40:05 cl-3     No work. Pause for 3 s.
cl 12:40:05 cl-4     No work. Pause for 3 s.
cl 12:40:05 cl-5     No work. Pause for 3 s.
cl 12:40:05 cl-6     No work. Pause for 3 s.
cl 12:40:05 cl-7     No work. Pause for 3 s.
cl 12:40:08 cl-7     No work. Pause for 3 s.
cl 12:40:08 cl-1     No work. Pause for 3 s.
cl 12:40:08 cl-6     No work. Pause for 3 s.
cl 12:40:08 cl-5     No work. Pause for 3 s.
cl 12:40:08 cl-4     No work. Pause for 3 s.
cl 12:40:08 cl-2     No work. Pause for 3 s.
cl 12:40:08 cl-0     No work. Pause for 3 s.
cl 12:40:08 cl-3     No work. Pause for 3 s.
 i 12:40:08 stratum  Job: #868dab05... europe.ethash-hub.miningpoolhub.com [18.197.166.72:20535]
 m 12:40:09 main     Speed 0.00 Mh/s gpu0 0.00 0C 0% gpu1 0.00 0C 0% gpu2 0.00 0C 0% gpu3 0.00 0C 0% gpu4 0.00 0C 0% gpu5 0.00 0C 0% gpu6 0.00 0C 0% gpu7 0.00 0C 0% A0 Time: 00:00
cl 12:40:11 cl-4     Platform: AMD Accelerated Parallel Processing
cl 12:40:11 cl-7     Platform: AMD Accelerated Parallel Processing
cl 12:40:11 cl-0     Platform: AMD Accelerated Parallel Processing
cl 12:40:11 cl-5     Platform: AMD Accelerated Parallel Processing
cl 12:40:11 cl-0     Device:   Ellesmere / OpenCL 2.0 AMD-APP (2766.5)
cl 12:40:11 cl-6     Platform: AMD Accelerated Parallel Processing
cl 12:40:11 cl-1     Platform: AMD Accelerated Parallel Processing
cl 12:40:11 cl-3     Platform: AMD Accelerated Parallel Processing
cl 12:40:11 cl-4     Device:   Ellesmere / OpenCL 2.0 AMD-APP (2766.5)
cl 12:40:11 cl-7     Device:   Ellesmere / OpenCL 2.0 AMD-APP (2766.5)
cl 12:40:11 cl-5     Device:   Ellesmere / OpenCL 2.0 AMD-APP (2766.5)
cl 12:40:11 cl-2     Platform: AMD Accelerated Parallel Processing
cl 12:40:11 cl-6     Device:   Ellesmere / OpenCL 2.0 AMD-APP (2766.5)
cl 12:40:11 cl-1     Device:   Ellesmere / OpenCL 2.0 AMD-APP (2766.5)
cl 12:40:11 cl-3     Device:   Ellesmere / OpenCL 2.0 AMD-APP (2766.5)
cl 12:40:11 cl-2     Device:   Tonga / OpenCL 2.0 AMD-APP (2766.5)
 i 12:40:11 cl-2     Adjusting CL work multiplier for 28 CUs.Adjusted work multiplier: 50а973
 i 12:40:11 cl-5     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 58а255
 i 12:40:11 cl-7     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 58а255
 i 12:40:12 cl-6     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 58а255
 i 12:40:12 cl-4     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 58а255
 i 12:40:12 cl-1     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 58а255
 i 12:40:12 cl-3     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 58а255
 i 12:40:12 cl-0     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 58а255
cl 12:40:13 cl-2     OpenCL kernel
cl 12:40:13 cl-3     OpenCL kernel
cl 12:40:13 cl-5     OpenCL kernel
cl 12:40:13 cl-6     OpenCL kernel
cl 12:40:13 cl-4     OpenCL kernel
cl 12:40:13 cl-1     OpenCL kernel
cl 12:40:13 cl-0     OpenCL kernel
cl 12:40:13 cl-7     OpenCL kernel
cl 12:40:13 cl-2     Loading binary kernel C:\Users\ухэр\Desktop\ethminer-0.17.0-rc.2-cuda10.0-windows-amd64\kernels\ethash_tonga_lws128.bin
cl 12:40:14 cl-7     Loading binary kernel C:\Users\ухэр\Desktop\ethminer-0.17.0-rc.2-cuda10.0-windows-amd64\kernels\ethash_ellesmere_lws128.bin
cl 12:40:14 cl-2     Build info success:
cl 12:40:14 cl-2     Creating light cache buffer, size: 45,250 MB
cl 12:40:14 cl-2     Creating DAG buffer, size: 2,828 GB, free: 1,128 GB
cl 12:40:14 cl-2     Loading kernels
cl 12:40:14 cl-2     Writing light cache buffer
 m 12:40:14 main     Speed 0.00 Mh/s gpu0 0.00 31C 0% gpu1 0.00 36C 0% gpu2 0.00 34C 0% gpu3 0.00 38C 0% gpu4 0.00 33C 0% gpu5 0.00 36C 0% gpu6 0.00 33C 0% gpu7 0.00 34C 0% A0 Time: 00:00
cl 12:40:14 cl-2     Creating buffer for header.
cl 12:40:14 cl-2     Creating mining buffer
cl 12:40:15 cl-0     Loading binary kernel C:\Users\ухэр\Desktop\ethminer-0.17.0-rc.2-cuda10.0-windows-amd64\kernels\ethash_ellesmere_lws128.bin
cl 12:40:15 cl-7     Build info success:
cl 12:40:15 cl-7     Creating light cache buffer, size: 45,250 MB
cl 12:40:15 cl-7     Creating DAG buffer, size: 2,828 GB, free: 1,128 GB
cl 12:40:15 cl-0     Build info success:
cl 12:40:15 cl-0     Creating light cache buffer, size: 45,250 MB
cl 12:40:15 cl-0     Creating DAG buffer, size: 2,828 GB, free: 5,128 GB
cl 12:40:15 cl-7     Loading kernels
cl 12:40:15 cl-7     Writing light cache buffer
cl 12:40:15 cl-0     Loading kernels
cl 12:40:15 cl-0     Writing light cache buffer
cl 12:40:15 cl-7     Creating buffer for header.
cl 12:40:15 cl-7     Creating mining buffer
cl 12:40:15 cl-0     Creating buffer for header.
cl 12:40:15 cl-0     Creating mining buffer
 i 12:40:16 stratum  Job: #b41e45fa... europe.ethash-hub.miningpoolhub.com [18.197.166.72:20535]
cl 12:40:16 cl-1     Loading binary kernel C:\Users\ухэр\Desktop\ethminer-0.17.0-rc.2-cuda10.0-windows-amd64\kernels\ethash_ellesmere_lws128.bin
cl 12:40:17 cl-4     Loading binary kernel C:\Users\ухэр\Desktop\ethminer-0.17.0-rc.2-cuda10.0-windows-amd64\kernels\ethash_ellesmere_lws128.bin
cl 12:40:17 cl-1     Build info success:
cl 12:40:17 cl-1     Creating light cache buffer, size: 45,250 MB
cl 12:40:17 cl-1     Creating DAG buffer, size: 2,828 GB, free: 1,128 GB
cl 12:40:17 cl-1     Loading kernels
cl 12:40:17 cl-1     Writing light cache buffer
cl 12:40:17 cl-4     Build info success:
cl 12:40:17 cl-4     Creating light cache buffer, size: 45,250 MB
cl 12:40:17 cl-4     Creating DAG buffer, size: 2,828 GB, free: 5,128 GB
cl 12:40:17 cl-4     Loading kernels
cl 12:40:17 cl-4     Writing light cache buffer
cl 12:40:17 cl-1     Creating buffer for header.
cl 12:40:17 cl-1     Creating mining buffer
cl 12:40:17 cl-4     Creating buffer for header.
cl 12:40:17 cl-4     Creating mining buffer
cl 12:40:18 cl-6     Loading binary kernel C:\Users\ухэр\Desktop\ethminer-0.17.0-rc.2-cuda10.0-windows-amd64\kernels\ethash_ellesmere_lws128.bin
cl 12:40:19 cl-5     Loading binary kernel C:\Users\ухэр\Desktop\ethminer-0.17.0-rc.2-cuda10.0-windows-amd64\kernels\ethash_ellesmere_lws128.bin
cl 12:40:19 cl-6     Build info success:
cl 12:40:19 cl-6     Creating light cache buffer, size: 45,250 MB
cl 12:40:19 cl-6     Creating DAG buffer, size: 2,828 GB, free: 5,128 GB
cl 12:40:19 cl-6     Loading kernels
cl 12:40:19 cl-6     Writing light cache buffer
cl 12:40:19 cl-5     Build info success:
cl 12:40:19 cl-5     Creating light cache buffer, size: 45,250 MB
cl 12:40:19 cl-5     Creating DAG buffer, size: 2,828 GB, free: 1,128 GB
cl 12:40:19 cl-5     Loading kernels
cl 12:40:19 cl-5     Writing light cache buffer
cl 12:40:19 cl-6     Creating buffer for header.
cl 12:40:19 cl-6     Creating mining buffer
cl 12:40:19 cl-5     Creating buffer for header.
cl 12:40:19 cl-5     Creating mining buffer
 m 12:40:19 main     Speed 0.00 Mh/s gpu0 0.00 37C 0% gpu1 0.00 42C 0% gpu2 0.00 41C 0% gpu3 0.00 33C 0% gpu4 0.00 36C 0% gpu5 0.00 42C 0% gpu6 0.00 36C 0% gpu7 0.00 46C 0% A0 Time: 00:00
cl 12:40:20 cl-3     Loading binary kernel C:\Users\ухэр\Desktop\ethminer-0.17.0-rc.2-cuda10.0-windows-amd64\kernels\ethash_ellesmere_lws128.bin
cl 12:40:20 cl-3     Build info success:
cl 12:40:20 cl-3     Creating light cache buffer, size: 45,250 MB
cl 12:40:20 cl-3     Creating DAG buffer, size: 2,828 GB, free: 1,128 GB
cl 12:40:20 cl-3     Loading kernels
cl 12:40:20 cl-3     Writing light cache buffer
cl 12:40:20 cl-3     Creating buffer for header.
cl 12:40:20 cl-3     Creating mining buffer
 i 12:40:21 cl-0     2,828 GB of DAG data generated in 5а415 ms.
 i 12:40:21 cl-7     2,828 GB of DAG data generated in 5а700 ms.
 i 12:40:22 cl-4     2,828 GB of DAG data generated in 5а411 ms.
 i 12:40:22 cl-2     2,828 GB of DAG data generated in 8а030 ms.
 i 12:40:22 cl-1     2,828 GB of DAG data generated in 5а579 ms.
 i 12:40:24 cl-6     2,828 GB of DAG data generated in 5а475 ms.
 i 12:40:24 cl-3     2,828 GB of DAG data generated in 4а678 ms.
 i 12:40:24 cl-5     2,828 GB of DAG data generated in 5а580 ms.
 m 12:40:24 main     Speed 0.00 Mh/s gpu0 0.00 40C 0% gpu1 0.00 50C 19% gpu2 0.00 45C 0% gpu3 0.00 51C 0% gpu4 0.00 38C 0% gpu5 0.00 50C 19% gpu6 0.00 38C 0% gpu7 0.00 52C 19% A0 Time: 00:00
 i 12:40:25 stratum  Job: #d767f168... europe.ethash-hub.miningpoolhub.com [18.197.166.72:20535]
 m 12:40:29 main     Speed 134.44 Mh/s gpu0 30.24 43C 0% gpu1 25.79 57C 20% gpu2 22.28 47C 0% gpu3 0.00 59C 34% gpu4 30.23 42C 0% gpu5 0.00 57C 20% gpu6 0.00 42C 0% gpu7 25.89 54C 20% A0 Time: 00:00
 m 12:40:34 main     Speed 223.58 Mh/s gpu0 30.25 44C 0% gpu1 26.78 59C 21% gpu2 23.03 49C 0% gpu3 30.43 61C 34% gpu4 30.25 44C 0% gpu5 26.42 59C 21% gpu6 30.02 44C 0% gpu7 26.39 55C 21% A0 Time: 00:00
 i 12:40:37 stratum  Job: #b03dd673... europe.ethash-hub.miningpoolhub.com [18.197.166.72:20535]
 i 12:40:38 cl-1     Solution: 0x027e080000de0aa9
 i 12:40:38 stratum  **Accepted  87 ms. europe.ethash-hub.miningpoolhub.com [18.197.166.72:20535]
 m 12:40:39 main     Speed 224.47 Mh/s gpu0 30.26 46C 0% gpu1 26.78 61C 22% gpu2 23.03 51C 0% gpu3 30.84 63C 36% gpu4 30.25 45C 0% gpu5 26.79 61C 22% gpu6 30.13 45C 0% gpu7 26.39 58C 21% A1 Time: 00:00

C:\Users\гена\Desktop\ethminer-0.18.0-alpha.3-cuda10.0-windows-amd64>ethminer.exe -G --farm-recheck 100 --report-hashrate --HWMON 1 --cl-local-work 128 -P stratum+tcp://gennadiv%2e1:x@europe.ethash-hub.miningpoolhub.com:20535 -P stratum+tcp://gennadiv%2e1:x@us-east.ethash-hub.miningpoolhub.com:20535

ethminer 0.18.0-alpha.3
Build: windows/release/msvc

 i 12:41:03 main     Configured pool europe.ethash-hub.miningpoolhub.com:20535
 i 12:41:03 main     Configured pool us-east.ethash-hub.miningpoolhub.com:20535
 i 12:41:03 <unknown> Selected pool europe.ethash-hub.miningpoolhub.com:20535
 i 12:41:03 <unknown> Established connection to europe.ethash-hub.miningpoolhub.com  [18.197.166.72:20535]
 i 12:41:03 <unknown> Spinning up miners...
cl 12:41:03 cl-0     Using PciId : 01:00.0 Ellesmere OpenCL 2.0 AMD-APP (2766.5) Memory : 8.00 GB
 i 12:41:03 cl-0     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 58?255
cl 12:41:03 cl-1     Using PciId : 02:00.0 Ellesmere OpenCL 2.0 AMD-APP (2766.5) Memory : 4.00 GB
 i 12:41:03 cl-1     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 58?255
cl 12:41:03 cl-2     Using PciId : 03:00.0 Tonga OpenCL 2.0 AMD-APP (2766.5) Memory : 4.00 GB
 i 12:41:03 cl-2     Adjusting CL work multiplier for 28 CUs.Adjusted work multiplier: 50?973
cl 12:41:03 cl-3     Using PciId : 04:00.0 Ellesmere OpenCL 2.0 AMD-APP (2766.5) Memory : 4.00 GB
 i 12:41:03 cl-3     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 58?255
cl 12:41:03 cl-4     Using PciId : 08:00.0 Ellesmere OpenCL 2.0 AMD-APP (2766.5) Memory : 4.00 GB
 i 12:41:03 cl-4     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 58?255
cl 12:41:03 cl-5     Using PciId : 09:00.0 Ellesmere OpenCL 2.0 AMD-APP (2766.5) Memory : 8.00 GB
 i 12:41:03 <unknown> Stratum mode : STRATUM
 i 12:41:03 cl-5     Adjusting CL work multiplier for 32 CUs.Adjusted work multiplier: 58?255
 i 12:41:03 <unknown> Subscribed!
 i 12:41:03 <unknown> Epoch : 234 Difficulty : 8.60 Gh
 i 12:41:03 <unknown> Job: f53045c0... europe.ethash-hub.miningpoolhub.com  [18.197.166.72:20535]
cl 12:41:05 cl-0     Generating DAG + Light : 2.87 GB
cl 12:41:05 cl-5     Generating DAG + Light : 2.87 GB
cl 12:41:05 cl-3     Generating DAG + Light : 2.87 GB
cl 12:41:05 cl-2     Generating DAG + Light : 2.87 GB
cl 12:41:05 cl-4     Generating DAG + Light : 2.87 GB
 i 12:41:05 <unknown> Authorized worker gennadiv.1
cl 12:41:05 cl-1     Generating DAG + Light : 2.87 GB
cl 12:41:05 cl-2     OpenCL kernel
cl 12:41:05 cl-0     OpenCL kernel
cl 12:41:06 cl-2     Loading binary kernel C:\Users\????\Desktop\ethminer-0.18.0-alpha.3-cuda10.0-windows-amd64\kernels\ethash_tonga_lws128.bin
cl 12:41:07 cl-0     Loading binary kernel C:\Users\????\Desktop\ethminer-0.18.0-alpha.3-cuda10.0-windows-amd64\kernels\ethash_ellesmere_lws128.bin
cl 12:41:07 cl-2     Build info success:
cl 12:41:07 cl-2     Creating light cache buffer, size: 45.25 MB
cl 12:41:07 cl-2     Creating DAG buffer, size: 2.83 GB, free: 1.13 GB
cl 12:41:07 cl-2     Loading kernels
cl 12:41:07 cl-2     Writing light cache buffer
cl 12:41:07 cl-0     Build info success:
cl 12:41:07 cl-0     Creating light cache buffer, size: 45.25 MB
cl 12:41:07 cl-0     Creating DAG buffer, size: 2.83 GB, free: 5.13 GB
cl 12:41:07 cl-0     Loading kernels
cl 12:41:07 cl-0     Writing light cache buffer
cl 12:41:07 cl-2     Creating buffer for header.
cl 12:41:07 cl-2     Creating mining buffer
cl 12:41:07 cl-0     Creating buffer for header.
cl 12:41:07 cl-0     Creating mining buffer
cl 12:41:07 cl-4     OpenCL kernel
cl 12:41:07 cl-3     OpenCL kernel
 m 12:41:08 <unknown> 0:00 A0 0.00 h { cl0 0.00 48C 0% | cl1 0.00 51C 39% | cl2 0.00 52C 0% | cl3 0.00 43C 27% | cl4 0.00 45C 28% | cl5 0.00 45C 0% }
cl 12:41:08 cl-4     Loading binary kernel C:\Users\????\Desktop\ethminer-0.18.0-alpha.3-cuda10.0-windows-amd64\kernels\ethash_ellesmere_lws128.bin
cl 12:41:09 cl-3     Loading binary kernel C:\Users\????\Desktop\ethminer-0.18.0-alpha.3-cuda10.0-windows-amd64\kernels\ethash_ellesmere_lws128.bin
cl 12:41:09 cl-4     Build info success:
cl 12:41:09 cl-4     Creating light cache buffer, size: 45.25 MB
cl 12:41:09 cl-4     Creating DAG buffer, size: 2.83 GB, free: 1.13 GB
cl 12:41:09 cl-3     Build info success:
cl 12:41:09 cl-3     Creating light cache buffer, size: 45.25 MB
cl 12:41:09 cl-3     Creating DAG buffer, size: 2.83 GB, free: 1.13 GB
cl 12:41:09 cl-3     Loading kernels
cl 12:41:09 cl-3     Writing light cache buffer
cl 12:41:09 cl-4     Loading kernels
cl 12:41:09 cl-4     Writing light cache buffer
cl 12:41:09 cl-3     Creating buffer for header.
cl 12:41:09 cl-3     Creating mining buffer
cl 12:41:09 cl-4     Creating buffer for header.
cl 12:41:09 cl-4     Creating mining buffer
cl 12:41:09 cl-5     OpenCL kernel
cl 12:41:09 cl-1     OpenCL kernel
 i 12:41:09 <unknown> Job: 41907f0a... europe.ethash-hub.miningpoolhub.com  [18.197.166.72:20535]
cl 12:41:10 cl-5     Loading binary kernel C:\Users\????\Desktop\ethminer-0.18.0-alpha.3-cuda10.0-windows-amd64\kernels\ethash_ellesmere_lws128.bin
cl 12:41:11 cl-1     Loading binary kernel C:\Users\????\Desktop\ethminer-0.18.0-alpha.3-cuda10.0-windows-amd64\kernels\ethash_ellesmere_lws128.bin
cl 12:41:11 cl-5     Build info success:
cl 12:41:11 cl-5     Creating light cache buffer, size: 45.25 MB
cl 12:41:11 cl-5     Creating DAG buffer, size: 2.83 GB, free: 5.13 GB
cl 12:41:11 cl-5     Loading kernels
cl 12:41:11 cl-5     Writing light cache buffer
cl 12:41:11 cl-1     Build info success:
cl 12:41:11 cl-1     Creating light cache buffer, size: 45.25 MB
cl 12:41:11 cl-1     Creating DAG buffer, size: 2.83 GB, free: 1.13 GB
cl 12:41:11 cl-1     Loading kernels
cl 12:41:11 cl-1     Writing light cache buffer
cl 12:41:11 cl-1     Creating buffer for header.
cl 12:41:11 cl-1     Creating mining buffer
cl 12:41:11 cl-5     Creating buffer for header.
cl 12:41:11 cl-5     Creating mining buffer
cl 12:41:12 cl-0     2.83 GB of DAG data generated in 7?746 ms.
 m 12:41:13 <unknown> 0:00 A0 0.00 h { cl0 0.00 50C 0% | cl1 0.00 61C 40% | cl2 0.00 54C 35% | cl3 0.00 54C 28% | cl4 0.00 56C 29% | cl5 0.00 49C 0% }
cl 12:41:14 cl-4     2.83 GB of DAG data generated in 9?891 ms.
cl 12:41:15 cl-3     2.83 GB of DAG data generated in 10?008 ms.
cl 12:41:15 cl-2     2.83 GB of DAG data generated in 10?262 ms.
cl 12:41:16 cl-1     2.83 GB of DAG data generated in 11?049 ms.
cl 12:41:16 cl-5     2.83 GB of DAG data generated in 11?871 ms.
 m 12:41:18 <unknown> 0:00 A0 29.90 Mh { cl0 29.90 52C 0% | cl1 0.00 68C 41% | cl2 0.00 57C 41% | cl3 0.00 61C 29% | cl4 0.00 62C 30% | cl5 0.00 52C 0% }
 i 12:41:20 <unknown> Job: d1bd8ef1... europe.ethash-hub.miningpoolhub.com  [18.197.166.72:20535]
 m 12:41:23 <unknown> 0:00 A0 159.96 Mh { cl0 30.02 54C 0% | cl1 27.46 70C 41% | cl2 20.15 58C 42% | cl3 25.88 62C 30% | cl4 26.25 63C 32% | cl5 30.21 54C 0% }
 m 12:41:28 <unknown> 0:00 A0 167.33 Mh { cl0 30.10 55C 24% | cl1 30.83 71C 43% | cl2 23.01 59C 44% | cl3 26.38 62C 33% | cl4 26.77 64C 34% | cl5 30.24 55C 24% }
 m 12:41:33 <unknown> 0:00 A0 167.38 Mh { cl0 30.12 56C 24% | cl1 30.84 73C 45% | cl2 23.02 60C 46% | cl3 26.39 63C 35% | cl4 26.78 65C 37% | cl5 30.25 56C 24% }

**Comment by R00dNet** [comment]
hey gennadiv. quick question if you do not mind. Are you able to connect to Miningpoolhubs 17xxx ports with new ethminer?

**Comment by gennadiv** [comment]
yes . but screen is not necessary

**Comment by gennadiv** [comment]
reinstallation of the drivers and complete removal of all AMD saved everything works.closing the question.
