### ISSUE TITLE
cuda-0   Error CUDA mining: CUDA error in func init at line 126 out of memory

### ISSUE THREAD

**Issue by Scorpion2185** [ethereum-mining/ethminer#1817]
It was fine but now:
```
Allocating light with size: 47579072
Segmentation fault
[...]
Fatal GPU error: CUDA error in func run_ethash_search at line 60 invalid device ordinal
Terminating.
```
I' m using a GTX 1060 3gb and ethminer-0.15.0.dev9-Linux.
After I tried with the ethminer-0.17.0-linux-x86_64:
`cuda-0   Error CUDA mining: CUDA error in func init at line 126 out of memory`

**Comment by AndreaLanfranchi** [comment]
You can't mine ethereum with an 3GB card anymore.

**Comment by Scorpion2185** [comment]
For the DAG size?

**Comment by AndreaLanfranchi** [comment]
Yes

**Comment by SnowLeopard71** [comment]
Claymore's miner still works for GTX 1060 3gb cards

**Comment by Scorpion2185** [comment]
@SnowLeopard71  What version?

**Comment by Scorpion2185** [comment]
Never mind, how can it mine if the dag is more than 3 gb now...

**Comment by SnowLeopard71** [comment]
The DAG isn't over 3GB.    There are subtle differences with how different miners generate the DAG, and Claymore has found a way to minimize it so we can squeeze every penny out of lower memory cards.
See the release notes:
https://bitcointalk.org/index.php?topic=1433925.0

**Comment by SnowLeopard71** [comment]
Claymore uses less memory to generate the DAG (which is not over 3GB until a few months yet).
I switched to it two weeks ago when ethminer no longer was able to generate DAG without an out-of-memory error and it works fine -- maybe gives a tiny bit less, but better than not using those cards at all anymore.
See the release notes:   https://bitcointalk.org/index.php?topic=1433925.0

**Comment by slinkyvagabond** [comment]
@SnowLeopard71 Why the hell are you spamming this thread with rather blatant advertising for Claymore. Stick to the Claymore threads if that's what you want to talk about. Thanks for coming out though.

**Comment by Scorpion2185** [comment]
I used it I tried again with the 12.0 and it cannot start since the DAG...

**Comment by source-creator** [comment]
I was getting this error with version 0.17.1
I have 6GB cards.

Turns out, my VM's (Virtual Machines) were using up my graphics memory.
Shutting down the VM's resolved the issue.

**Comment by Gertsch** [comment]
any solution regarding ethminer?
I've got two 1060ti 6GB cards in my system, one works just fine, but the other one throws the same error.

**Comment by tonyaik** [comment]
> any solution regarding ethminer?
> I've got two 1060ti 6GB cards in my system, one works just fine, but the other one throws the same error.

Are you using the one that's throwing the error for display output? I'm guessing something is reserving memory on that card.
