### ISSUE TITLE
cuda line 460 illegal memory access

### ISSUE THREAD

**Issue by R00dNet** [ethereum-mining/ethminer#1818]
Hi

ethminer-0.17.0-cuda10.0-windows-amd64.zip
win 7 pro 64bit

Can someone please inform me what line 460 is? This error has started to happen recently with v17. I have ran ethminer without any OC settings and it still happens. At first I thought it was something to do with Miningpoolhub, time to switch algos, yet ethash was still top for most profitable when checked. I have had a search online without much luck.

Help greatly appreciated.

**Comment by AndreaLanfranchi** [comment]
https://github.com/ethereum-mining/ethminer/blob/release/0.17/libethash-cuda/CUDAMiner.cpp#L460

**Comment by R00dNet** [comment]
thanks

**Comment by R00dNet** [comment]
lowering cuda grid size and increasing power (60% to 70% of 120watt) appears to have solved this issue with and without OC settings.

closing
