### ISSUE TITLE
Failover switch to Eth-proxy pools doesn't work often

### ISSUE THREAD

**Issue by naikmyeong** [ethereum-mining/ethminer#1819]
This may be not a serious issue, but I would like to request allocating Eth-proxy as a prior Stratum position with a bug fix of failover to stratum switch.

**Comment by AndreaLanfranchi** [comment]
Actually there is no bug in ethminer.

Unfortunately there are many stratum flavours out there and the only option for ethminer is to iteratively try to establish a connection with each of them till it gets the proper response. This imply quick disconnections and reconnections which some NIC driver may not honor properly.
If you know in advance which stratum flavor is implemented by the pool you can easily skip the autodetection phase and ask ethminer to stick with a specific.

This schemes apply :
- stratum:// means autodetection
- stratum+tcp:// means Stratum mode bitcoin like
- stratum1+tcp:// means eth-proxy compatible
- stratum2+tcp:// means EthereumStratum/1.0.0 (NiceHash) mode
- stratum3+tcp:// means EthereumStratum/2.0.0 (yet not implemented by many pools).

As always ethminer --help is your friend
