### ISSUE TITLE
Add CUDA 9.2 support and CUDA 10 support for linux.

### ISSUE THREAD

**Issue by naikmyeong** [ethereum-mining/ethminer#1821]
I've been requested by a lot of miners, but will do it later when I have time.

Anyone can do a job before I start to do it.

**Comment by ddobreff** [comment]
Define support? ethminer already supports both versions?!?

**Comment by naikmyeong** [comment]
Yes by adding support on Appveyor/ Travisci compiled version will be delivered.

cc @chfast

**Comment by chfast** [comment]
Linux binaries are built with CUDA 9.1. We are not using 9.2 because it's not compatible with some Nvidia drivers and the performance is the same.

What are benefits of using CUDA 9.2 or 10?

**Comment by naikmyeong** [comment]
@chfast Some need though 

![default](https://user-images.githubusercontent.com/44437404/51103023-94738a00-1824-11e9-9105-9eb41523fa6d.PNG)
![2](https://user-images.githubusercontent.com/44437404/51103024-950c2080-1824-11e9-8230-9e636c05d36b.PNG)
![3](https://user-images.githubusercontent.com/44437404/51103025-950c2080-1824-11e9-9933-e57f3c219bd0.PNG)
![4](https://user-images.githubusercontent.com/44437404/51103026-950c2080-1824-11e9-8a7c-3cba560531fe.PNG)

**Comment by naikmyeong** [comment]
😂 I already have mine but too lazy to submit them here also

**Comment by janrembold** [comment]
Will there be a specific release for Linux and CUDA 10? With release 0.18.0-rc.0 there is only a Linux with CUDA 9 package.

I'm running CUDA 10.1 on my Folding@Home machines and saw some great performance improvements from 10.0. Maybe it is worth investigating?!
