### ISSUE TITLE
Missing kernel binary, ethash_gfx900_lws192.bin

### ISSUE THREAD

**Issue by geofurb** [ethereum-mining/ethminer#1826]
The kernel binary for gfx900_lws192 appears to be missing. In the latest source I see that there are kernels for gfx900, but 192 is still missing. Can we get this included in the next release? Seems easy enough to compile.

**Comment by ddobreff** [comment]
local work size of 192 has been removed.

**Comment by geofurb** [comment]
gfx900 binaries are missing in 0.17.0; will they be in the next release?

**Comment by ddobreff** [comment]
The specific worksize of 192 has been removed. Use 64,128 or 256.

**Comment by geofurb** [comment]
Understood, but no gfx900 binaries are included in 0.17.0; only gfx901.

**Comment by ddobreff** [comment]
just copy from 18.0

**Comment by geofurb** [comment]
Copying [this file](https://github.com/ethereum-mining/ethminer/blob/master/libethash-cl/kernels/bin/ethash_gfx900_lws128.bin) into my kernels directory errors out:
```
ethminer.exe -G -P stratum1+ssl://blahblahblah --cl-local-work 128
    cl 18:53:08 cl-0     OpenCL kernel
    cl 18:53:10 cl-0     Loading binary kernel kernels\ethash_gfx900_lws128.bin
    cl 18:53:10 cl-0     Build info success:
    cl 18:53:10 cl-0     Creating light cache buffer, size: 45.375 MB
    cl 18:53:10 cl-0     Creating DAG buffer, size: 2.836 GB, free: 5.104 GB
    cl 18:53:10 cl-0     Loading kernels
    cl 18:53:10 cl-0     Writing light cache buffer
    cl 18:53:10 cl-0     Creating buffer for header.
     X 18:53:10 cl-0     OpenCL init failed: clSetKernelArg: CL_INVALID_ARG_INDEX (-49)
```

**Comment by ukos-git** [comment]
> just copy from 18.0
They are also missing in [current 18.0 releases](https://github.com/ethereum-mining/ethminer/releases/tag/v0.18.0-alpha.3)
