### ISSUE TITLE
0.17.0 Worker not authorized

### ISSUE THREAD

**Issue by UselessGuru** [ethereum-mining/ethminer#1830]
With version 0.17.0 I get the following error:

```
ethminer.exe --api-port -4004 -P stratum+tcp://**********.multipoolminer:x@europe.ethash-hub.miningpoolhub.com:20585 --opencl --opencl-devices 0
 m 23:20:30 main     ethminer 0.17.0
 m 23:20:30 main     Build: windows/release
 i 23:20:31 main     Found suitable OpenCL device [Baffin] with 2.000 GB of GPU memory
 i 23:20:31 main     Found suitable OpenCL device [Ellesmere] with 4.000 GB of GPU memory
 i 23:20:31 main     Configured pool europe.ethash-hub.miningpoolhub.com:20585
 i 23:20:31 main     Api server listening on port 4004.
 i 23:20:31 main     Selected pool europe.ethash-hub.miningpoolhub.com:20585
 i 23:20:31 stratum  Stratum mode detected: STRATUM
 i 23:20:31 stratum  Subscribed!
 i 23:20:31 stratum  Job: #29017dcf...  [18.197.166.72:20585]
 i 23:20:31 stratum  Pool difficulty: 8.60K megahash
 i 23:20:31 stratum  New epoch 138
 i 23:20:31 stratum  Worker not authorized *************
 i 23:20:31 main     Disconnected from  [18.197.166.72:20585]
 i 23:20:32 main     No more connections to try. Exiting...
 i 23:20:33 main     Terminated!
```

Environment: Windows 10 x64, latest AMD & NVIDIA driver
Error is independent of selected GPU model / maker

The same command works perfectly on version 0.16.2:

```
ethminer.exe --api-port -4004 -P stratum+tcp://**********.multipoolminer:x@europe.ethash-hub.miningpoolhub.com:20585 --opencl --opencl-devices 0
 m 23:22:46 main     ethminer 0.16.2
 m 23:22:46 main     Build: windows/release
 i 23:22:46 main     Found suitable OpenCL device [Baffin] with 2.000 GB of GPU memory
 i 23:22:46 main     Found suitable OpenCL device [Ellesmere] with 4.000 GB of GPU memory
 i 23:22:46 main     Configured pool europe.ethash-hub.miningpoolhub.com:20585
 i 23:22:46 main     Api server listening on port 4004.
 i 23:22:46 main     Selected pool europe.ethash-hub.miningpoolhub.com:20585
 i 23:22:46 stratum  Stratum mode detected: STRATUM
 i 23:22:47 stratum  Subscribed!
 i 23:22:47 stratum  Job: #806d3c95... europe.ethash-hub.miningpoolhub.com [18.197.166.72:20585]
 i 23:22:47 stratum  Pool difficulty: 8.60K megahash
 i 23:22:47 stratum  New epoch 138
 i 23:22:47 stratum  Authorized worker ***********.multipoolminer
 i 23:22:47 stratum  Established connection with europe.ethash-hub.miningpoolhub.com:20585 at  [18.197.166.72:20585]
 i 23:22:47 stratum  Spinning up miners...
```

**Comment by lesjokolat** [comment]
try

ethminer.exe --api-port -4004 -U -P stratum2+tcp://**********.multipoolminer:x@europe.ethash-hub.miningpoolhub.com:20535 --opencl --opencl-devices 0

**Comment by UselessGuru** [comment]
@lesjokolat 

Does not help. Error persists.

**Comment by lesjokolat** [comment]
ok add -v 3 can you then paste output

**Comment by lesjokolat** [comment]
Example connection from help sectio:

-P stratum2+tcp://USERNAME%2eWORKERNAME:WORKERPWD@europe.ethash-hub.miningpoolhub.com:20535

so "." format added between wallet and workername

ethminer.exe --api-port -4004 -U -P stratum2+tcp://**********%2emultipoolminer:x@europe.ethash-hub.miningpoolhub.com:20535 --opencl --opencl-devices 0

**Comment by lesjokolat** [comment]
yes I am on windows thanks for correction.

**Comment by UselessGuru** [comment]
Why would all this '.' (dot) stuff matter???

https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md#a-note-about-this-form-of-notation

**Comment by AndreaLanfranchi** [comment]
> Where ********** is an anonymized login name, and multipoolminer is the worker name.

Yes but if that ********** contains a dot **that dot** must be escaped as %2e (or %%2e in windows). 

> And there is no change in command line syntax documented anywhere.

That's not true.
https://github.com/ethereum-mining/ethminer/blob/master/CHANGELOG.md#removed
https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md

**Comment by St3x** [comment]
Hi !

I got the same issue as @UselessGuru with the same ethminer version on the same environment :

![issue](https://user-images.githubusercontent.com/46976382/51635953-4cf1aa00-1f58-11e9-8023-fc6726039eda.png)

 `Username` is the exact string `Username`, no special character anywhere.

**Comment by lesjokolat** [comment]
what happens if you specify stratum1 vs stratum2?

**Comment by St3x** [comment]
I tried every scheme :

- stratum+ssl : SSL/TLS Handshake failed
- stratum+tcp : Worker not authorized
- stratum+tls : SSL/TLS Handshake failed
- stratum+tls12 : SSL/TLS Handshake failed
- stratum1+ssl : SSL/TLS Handshake failed
- stratum1+tcp : Infinite loop Selected pool / No new work received / Disconnected
- stratum1+tls : SSL/TLS Handshake failed
- stratum1+tls12 : SSL/TLS Handshake failed
- stratum2+ssl : SSL/TLS Handshake failed
- stratum2+tcp : Worker not authorized
- stratum2+tls : SSL/TLS Handshake failed
- stratum2+tls12 : SSL/TLS Handshake failed
- stratum : Worker not authorized
- stratums : SSL/TLS Handshake failed
- stratumss : SSL/TLS Handshake failed

I get these results with any username.

![issue](https://user-images.githubusercontent.com/46988227/51659135-ff059200-1fa9-11e9-9452-b90e02f9ba1e.png)

**Comment by AndreaLanfranchi** [comment]
I see all tests are performed with login `Usernam`. Is this the login name of a **registered** account on MiningPoolHub ?

**Comment by St3x** [comment]
I used my extremely advanced Microsoft Paint skills to replace my real account by "Usernam" so it's a bit more generic screenshot.

__But__ I finally made the ultimate test case :

- I did a fresh install of the nVidia drivers 417.71 (without GeForce Experience)
- I did a fresh install of the nVidia CUDA ToolKit 10.0.130 (without GeForce Experience)
- Reboot (you never know)
- I created this MiningPoolHub real account so anybody can make the exact same test :
    - Username : mph_ethminer_test
	- Password : ethminer
	- Email : mapavajufi@321-email.com (temporary email generated by https://temp-mail.org/fr/)

You can login with this account, mine with it, take the infinitesimal amount of ETH on it, delete it, I don't mind.

Now I use this exact command to test ethminer on MiningPoolHub (so it mine for real on a real account) :
`ethminer -U -P stratum2+tcp://mph_ethminer_test.ethminer:x@europe.ethash-hub.miningpoolhub.com:20535`

And now the results (see the different versions of ethminer) :

![issue](https://user-images.githubusercontent.com/46997340/51677103-d21ca380-1fd8-11e9-9102-74c650d0e1c7.png)

So something happened between 0.16.2 and 0.17.0-rc2.

**Comment by AndreaLanfranchi** [comment]
> I used my extremely advanced Microsoft Paint skills to replace my real account by "Usernam" so it's a bit more generic screenshot.

🤣 

Ok ... now it's a bit more clear. Will dig into it.

**Comment by lesjokolat** [comment]
I would ad -v3 help give more details on errors to help Andrea.

Also check your start grid size text in your bat file it has a weird format(make sure no invisible characters)

**Comment by St3x** [comment]
What bat file ? My bat file is literally
- `[Win]+[R]`
- `cmd`
- `[Enter]`
- `cd C:\Users\-\Downloads\ethminer-0.16.2-windows-amd64`
- `[Enter]`
- `ethminer -U -P stratum2+tcp://mph_ethminer_test.ethminer:x@europe.ethash-hub.miningpoolhub.com:20535`
- `[Enter]`

But I see what you mean, this `8à192` should be something like `8 192` right ?
When I type `chcp` in the command-line it tells me the code page is 850, which is https://en.wikipedia.org/wiki/Code_page_850.
A clue, maybe ?

Regarding `-v3`, new screenshot ! Thx for the tip !

![issue](https://user-images.githubusercontent.com/47008511/51701622-23955480-2012-11e9-9505-5baad7b9e2a9.png)

**Comment by lesjokolat** [comment]
Hi sorry I assumed you were using a BAT file. This is richer info which will may to troubleshoot.

**Comment by lesjokolat** [comment]
Could you try and mine against a different pool entirely? I have a gut feeling there may be an issue with MHP.

**Comment by terre** [comment]
Followong scheme wokrs fine with MPH & ethminer 0.17.0 on Win10.

1. Set environment variable SSL_NOVERIFY to 1 
(`set SSL_NOVERIFY=1`) in bat file.

2. Use connection parameter in following format:
`-P stratumss://mph_login%%2emph_worker_name:worker_password@europe.ethash-hub.miningpoolhub.com:20535`
in command line you will need change %%2e to %2e.

**Comment by St3x** [comment]
### **This is it !** 🎉 

Thanks @terre !

It's not an ethminer issue but a documentation one !

The help says "URL takes the form: scheme://user[.workername][:password]@ hostname:port[/...]."

But it should be "URL takes the form: scheme://user[**%2e**workername][:password]@ hostname:port[/...]."

You have to **literally** write `%2e` instead of `.` to make it work !

See the following test with `.` (failing) followed by another test with `%2e` (working).

No bat file, no environment variables, stratum2+tcp.

@UselessGuru give it a try !

![issue](https://user-images.githubusercontent.com/47032633/51751313-de762e80-20b4-11e9-86f8-3555db8b593a.png)

Thanks all, job done, ethminer 0.17.0 currently at work on MiningPoolHub. ✌️

**Comment by AndreaLanfranchi** [comment]
We have documented it since long time.

https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md#miningpoolhubcom

**Comment by St3x** [comment]
Ah yes it's documented there !

I've only read what was in `ethminer -h`... 🙄 
@UselessGuru too probably.

So in the end there is no bug anywhere.

I see the `docs` directory now.
I'll read everything inside.

Thanks !

**Comment by UselessGuru** [comment]
> We have documented it since long time.

Thank you for the info...

Your miner is the only one requiring special handling with the '.' character. All miners work fine with the 'user.worker' syntax. I suggest you change the inner logic so the miner becomes more compatible.
