### ISSUE TITLE
Tell me how can I limit the work of some cards?

### ISSUE THREAD

**Issue by svytbay** [ethereum-mining/ethminer#1832]
Tell me how can I limit the work of some cards?

There are 2 video cards 1080 and 1030, I want that 1030 would not participate in mining.

**Comment by AndreaLanfranchi** [comment]
Use `--cu-devices` cli argument in startup.

First execute this
`./ethminer -U --list-devices`

This will give you the list of usable devices. By default ethminer uses them all.
If you want only some of then to be used for mining take note of their ids and limit by using `--cu-devices`.

Example :

```
andrea@test-rig:~ $ ethminer -U --list-devices


ethminer 0.18.0-alpha.3+commit.a4f23b65.dirty
Build: linux/release/gnu

 Id Pci Id    Type Name                          CUDA SM   Total Memory
--- --------- ---- ----------------------------- ---- ---  ------------
  0 01:00.0   Gpu  GeForce GTX 1060 3GB          Yes  6.1       2.95 GB
  1 02:00.0   Gpu  GeForce GTX 1060 3GB          Yes  6.1       2.95 GB
  2 03:00.0   Gpu  GeForce GTX 1060 3GB          Yes  6.1       2.95 GB
  3 04:00.0   Gpu  GeForce GTX 1060 3GB          Yes  6.1       2.95 GB
  4 06:00.0   Gpu  GeForce GTX 1060 3GB          Yes  6.1       2.95 GB
  5 08:00.0   Gpu  GeForce GTX 1060 3GB          Yes  6.1       2.95 GB
```

If you want only the last 3 to mine (leaving the first ones free) simply start ethminer with

```
./ethminer -U --cu-devices 3 4 5 <your-other-params-here>`
```

**Comment by svytbay** [comment]
@AndreaLanfranchi Thx its worked in Windows too
