### ISSUE TITLE
Sort AMD GPU by bus index

### ISSUE THREAD

**Issue by Secullus** [ethereum-mining/ethminer#1833]
Hi guys,
Is there a way to sort AMD cards by PCI bus index ?
For information, I am under windows 10 build 10.0.17763.253
Thank you in advance
Regards, François :)

![listdevices](https://user-images.githubusercontent.com/39520558/51480687-e327a380-1d91-11e9-907a-6d6208591b1f.PNG)
![busindex](https://user-images.githubusercontent.com/39520558/51480692-e4f16700-1d91-11e9-9338-b6d0adf533ea.PNG)

**Comment by AndreaLanfranchi** [comment]
Latest releases 0.18 implement binding among device and PCI id.
Please upgrade
