### ISSUE TITLE
Keep ETH-mining with 3GB cards

### ISSUE THREAD

**Issue by Angel996** [ethereum-mining/ethminer#1834]
Is it possible to keep mining the ETH coin using 3GB by loading a partial DAG file into GPU memory? The DAG array would be incomplete, but partial hashing would be possible with proportionally lower hashrate. Then, as the ETH epoch increments, the hashrate would go even lower, but still mine it.

Is this idea feasible? :)

thanks.

**Comment by SnowLeopard71** [comment]
Sidenote:  Claymore's miner still works for my 3GB 1060s -- it regenerated DAG at epoch 237 yesterday no problem.   
Still using ethminer on other machine with AMD cards (all 4gb or more).

**Comment by naikmyeong** [comment]
Mine other ethereum fork coins and exchange them for ethereum. why this will be a problem?

**Comment by AndreaLanfranchi** [comment]
@Angel996 I understand your point nevertheless loading only a part of the DAG would require a lot of modifications to the kernel code which have an impact on performance even on GPUs with 3Gb+.

**Comment by chfast** [comment]
Is the ethminer not usable any more with the current DAG size?

**Comment by AndreaLanfranchi** [comment]
No. Not anymore.

**Comment by Angel996** [comment]
Nanominer from Nanopool can still mine, however.

**Comment by AndreaLanfranchi** [comment]
As DAG is meant to increase well beyond 3Gb (and other mininig software will stop working too) this issue can't be solved.
