### ISSUE TITLE
Ethminer solo mine got a problem

### ISSUE THREAD

**Issue by SIRleee** [ethereum-mining/ethminer#1836]
This my command

ethminer -G --opencl-device 0 --opencl-plaform 1 -F //http:192.168.10.176:8858

Log Info
std::exception::what: Exception -32601 : METHOD NOT FOUND: The method being requested is not available on this server: The method eth_submitHashrate does not exist/is not available

I start with full node,so i do not know how to fix it. Can someone help me?

**Comment by AndreaLanfranchi** [comment]
You appear to run a very old ethminer version. `-F` command line argument has been dropped long time ago.

Please download latest release and run

```
ethminer -G -P http://192.168.10.176:8858 --cl-devices 0
```

**Comment by AndreaLanfranchi** [comment]
Ok ... it's the same.

**Comment by SIRleee** [comment]
But ,log Info like this :  
m 18:16:37 main     ethminer 0.17.0
m 18:16:37 main     Build: windows/release
No GPU device with sufficient memory was found

**Comment by AndreaLanfranchi** [comment]
What is the output of 

```
ethminer -G --list-devices 
```

**Comment by SIRleee** [comment]
![1](https://user-images.githubusercontent.com/30599323/51672484-913b8380-2006-11e9-8a2b-2700b08840f6.png)

**Comment by AndreaLanfranchi** [comment]
Your node is not responding to getWork requests.

- Which coin are you trying to mine ?
- Which node type ? (geth / parity / ...) ?
- Which is the command line to start the node ?

**Comment by SIRleee** [comment]
Q
  1  Which coin are you trying to mine ?
  2  Which node type ? (geth / parity / ...) ?
  3  Which is the command line to start the node ?
A 
 1: It is ETH
 2: geth full node
 3: geth --rpc --rpcaddr 192.168.10.176 --rpcport 8588 console

 The node on my private network.

**Comment by AndreaLanfranchi** [comment]
You're missing to put the node in mining mode.

```
geth --rpc --rpcapi eth --rpcaddr 192.168.10.176 --rpcport 8588 --mine --miner.etherbase <the-eth-address-where-you-want-to-credit-your-rewards> console
```

Also ensure your node is fully in sync (data dir should contain roughly 135+ GB data) otherwise your node won't create any mining job until fully in sync

**Comment by SIRleee** [comment]
Ok,I will try it。 Thank you very very very much!

**Comment by bmatthewshea** [comment]
So you know for ETH, my python script shows:
Speed/Total AVG Seconds till Block/(same in time format)/amount per day/$USD per day

250.0   MH           9316340 seconds          15 weeks, 2 days   0.02698742 - $2.81

If that's your only miner you got a significant wait for a payout/block.
