### ISSUE TITLE
HWMON flag causes exit under Windows

### ISSUE THREAD

**Issue by bmatthewshea** [ethereum-mining/ethminer#1841]
**Adding hardware monitor flag  `--HWMON` causing exception/exit under Windows 10**

I just upgraded my Win10 Nvidia drivers and ethminer (to cuda10/v17) and now I get an error using same start script.

**Expected behavior**
`--HWMON INT` flag should work. If I set it to `0` (off) or `1`, I see same exit/error.
The actual setting doesn't matter. Just the presence of the flag itself.
And yes, I am running under an administrator cmd for everything. Same as before.

**Screenshots (Optional)**
![shea99-2019-02-03_123258](https://user-images.githubusercontent.com/984097/52180941-9e4c3580-27b1-11e9-9af4-d6d59be59c86.png)

**Work-around**
(If I drop the --HWMON flag, it starts mining fine.)

**Environment (please complete the following information):**
Win10 
nVidia 1060/6gb
ethminer v17/Cuda10 (release)

**Comment by vaski666** [comment]
i have had the same, but not clever enough to remove this setting. I thought the issue was due to a faulty driver update or similar.

**Comment by bmatthewshea** [comment]
Yeah, I just start eliminating flags from command line till i find the stinker. lol
Might be easy fix since the presence of flag itself and not necessarily it's setting is breaking it.
(In other words: You would think `--HWMON 0` would be fine since that is 'OFF'. But, nope.

**Comment by AndreaLanfranchi** [comment]
--HWMON if not set in the CLI arguments list is meant to be off
--HWMON 1 means to monitor fans and temperatures
--HWMON 2  same as 1 plus power drain

This said you must have some problems on your Nvidia CUDA driver setup as it's been tested multiple times and works properly.

**Comment by bmatthewshea** [comment]
Understood & TY. Not sure what the issue could be - everything same. Driver upgraded as noted. ethminer updated as noted. Nothing else. Will report back if I find the problem. 

Also, it appears I am not alone in this issue^^ - so your 'multiple tests' may not be complete? Have you tried it on bare-metal box with 1060/slightly older card? thanks

**Comment by vaski666** [comment]
On my end I have the "Nvidia experience" installed and have the same issue.

**Comment by smurfy** [comment]
I am able to reproduce it on my 1080 with latest drivers, clean install. if the problem is still present after reboot i will try to analyse and fix the issue.
Happens on precompiled cuda9 and 10 exes

**Comment by bmatthewshea** [comment]
Thanks for reproducing it @smurfy .. yeah I am busy w/ work at moment. Pretty sure I rebooted mine? (tho now you got me wondering.. lol)

**Comment by bmatthewshea** [comment]
@AndreaLanfranchi If those are the flags then need to update `--help`?

This is v17 release:
```
ethminer.exe --help

Ethminer - GPU Ethereum miner
Usage: ethminer.exe [OPTIONS] [pool...]

(..snip..)

  --HWMON INT in [0 - 1]      0 - Displays gpu temp, fan percent. 1 - and power usage. Note for Linux: The program uses sysfs for power, which requires running with root privileges.
```

Assuming you still meant 0 or 1 (but understand that it is 'on' either way now.. sorry for confusion!)

> --HWMON 1 means to monitor fans and temperatures
> --HWMON 2 same as 1 plus power drain

**Comment by bmatthewshea** [comment]
@smurphy
I'm back. Just rebooted win10 miner box twice.
Same .exe exit popup when using HWMON switch, unfortunately...

**Comment by smurfy** [comment]
@bmatthewshea yea, still happening after reboot, so i can have a look.. it crashes way early for me.. if i enable it. must be somewhat related to hwmon/driver, because it worked before updating driver. (had quite old cuda 9 only installed)

**Comment by bmatthewshea** [comment]
Basically same here. 
Yeah, the only reason I updated the driver is because I wanted to try cuda10 build. Was still using v14 ethminer iirc.
Driver seems to be fine other than the hwmon issue.
- nVidia had to go mess with something apparently. lol

**Comment by smurfy** [comment]
found the problem, but going to sleep now. will create a fix later.

**Comment by chfast** [comment]
Please try this build (when ready): https://github.com/ethereum-mining/ethminer/releases/tag/v0.17.1-rc.0.

**Comment by bmatthewshea** [comment]
@chfast All good now. Just had chance to test.
`--HWMON` works.

     m 21:33:10 main     Speed 23.83 Mh/s gpu0 23.83 53C 50% 78W A0 Time: 00:02

Thanks
