### ISSUE TITLE
Crashes immediately after launch

### ISSUE THREAD

**Issue by Eddie2312** [ethereum-mining/ethminer#1849]
![fbdfgb](https://user-images.githubusercontent.com/25727760/53293334-b6531b80-3797-11e9-9c02-366bf90eb7a9.PNG)

Tried with 0.17.0 and 0.17.1
RX 580 8GB
Windows 10 64 bit
Wrote my batch file as follows:
 ethminer.exe -G -F http://eth-us2.dwarfpool.com:80/0xeb44124113fb11391c9d6527686194e916718d41/Miner1

I tried running the batch and again with the exe and a blank command line windows opens for a second then closes ever time.
I tried running as admin and that didn't help. I also created an exception in win defender

Please help.

**Comment by lesjokolat** [comment]
change to 

ethminer.exe -G -F http://eth-us2.dwarfpool.com:80/0xeb44124113fb11391c9d6527686194e916718d41/Miner1 -v 3

pause

what is output then?

**Comment by Eddie2312** [comment]
What does the "-v 3" do?

**Comment by Eddie2312** [comment]
![sdgdh](https://user-images.githubusercontent.com/25727760/53294407-9a597500-37ab-11e9-87ba-5b7aba68a356.PNG)

**Comment by lesjokolat** [comment]
its for verbose output. try this now

Example format:
-P stratum1+tcp://ETH_WALLET.WORKERNAME@eth-ar.dwarfpool.com:8008

ethminer.exe -G -P stratum1+tcp://0xeb44124113fb11391c9d6527686194e916718d41.Miner1@eth-ar.dwarfpool.com:8008 -v 3

**Comment by Eddie2312** [comment]
I changed the F to a P and it works for a minute. Then this
![xsdbdthdr](https://user-images.githubusercontent.com/25727760/53294839-7d756f80-37b4-11e9-94d4-9fdcc15715f3.PNG)

**Comment by lesjokolat** [comment]
try this now

ethminer.exe -G -P stratum1+tcp://0xeb44124113fb11391c9d6527686194e916718d41.Miner1@eth-ar.dwarfpool.com:8008 --cl-local-work 256 --cl-global-work 18432 -v 3
pause

ethminer.exe -G -P stratum+tcp://0xeb44124113fb11391c9d6527686194e916718d41.Miner1@eth-ar.dwarfpool.com:8008 --cl-local-work 256 --cl-global-work 18432 -v 3
pause

**Comment by Eddie2312** [comment]
Both?

**Comment by lesjokolat** [comment]
sorry one then the other

**Comment by Eddie2312** [comment]
![sgsdg](https://user-images.githubusercontent.com/25727760/53295007-4c4a6e80-37b7-11e9-8898-1ad7de4e7e31.png)
The first one resulted in this

**Comment by lesjokolat** [comment]
ok how about 2nd one?

**Comment by Eddie2312** [comment]
![dnfgnrdg](https://user-images.githubusercontent.com/25727760/53295039-d5fa3c00-37b7-11e9-99fb-013d752a81e7.png)

**Comment by lesjokolat** [comment]
might be a pool setting...
could you try and run on this pool?

https://eth.digipools.org

Just to see if it errors out or allows you to mine V1 of startup

**Comment by Eddie2312** [comment]
When you give me these configs to try, does it matter that you have the Argentina pool set for them?

**Comment by lesjokolat** [comment]
as long as address and port match should be ok.

**Comment by Eddie2312** [comment]
Using this as directed by the site
![dgfbdfvsdfse](https://user-images.githubusercontent.com/25727760/53295084-4c4b6e00-37b9-11e9-8fd5-4ecd66f55a36.PNG)
I got this and it closes after sending those prompts
![drbfyjtyh](https://user-images.githubusercontent.com/25727760/53295087-d5ae7080-37b8-11e9-937a-76be71876443.png)

**Comment by lesjokolat** [comment]
no sorry use teh setting like you had previous(just replace url and port. They have older ethminer settings in example page(as does dwarfpool

**Comment by Eddie2312** [comment]
![rghsdasdaw](https://user-images.githubusercontent.com/25727760/53295117-a3514300-37b9-11e9-88d2-1363dc942159.PNG)
![dfgdgtfsersa](https://user-images.githubusercontent.com/25727760/53295118-c1b73e80-37b9-11e9-8873-4ac02e0e18f6.PNG)

**Comment by lesjokolat** [comment]
ok try stratum1

**Comment by Eddie2312** [comment]
![sdgdghr](https://user-images.githubusercontent.com/25727760/53295148-8406e580-37ba-11e9-8744-83e666cb0c5d.png)
Seems to work

**Comment by lesjokolat** [comment]
awesome!! I think dwarfpool needs to adjust its settings to allow the newer ethminer versions to work. They had really old commands.

**Comment by Eddie2312** [comment]
So it's a problem with dwarfpool? Good to know

**Comment by lesjokolat** [comment]
Yah. The same basic command works on this pool...
If it was not then we would have gotten errors here as well. Might be just since dwarf is used to older ethminer versions it could mean an older version might work...
