### ISSUE TITLE
-v Parameter (1-9) only shows changes when i use "-v 1"

### ISSUE THREAD

**Issue by derubm** [ethereum-mining/ethminer#185]
## Question(s):

- The  Debug option -v [n] shows only a change when i use -v 1. 
As far as i can tell the mining info will not be shown when using this value
(only warning and Info tagged lines). 
![image](https://user-images.githubusercontent.com/6720202/28491239-d12f825a-6eed-11e7-98bf-ff7eb6d3432c.png)

Do the other values have any function (2-9)?

btw : it would be nice to show hashrate on the submit and accept / submit and reject line. 
In case of using -v 1 it would be a possibility to see the actual hashrate when a share gets submitted.

also: what should the miner show as info when it actually finds not only a share, but a block ?

**Comment by marcofranssen** [comment]
+1 wanted to reduce my logging for better performance, but that also prevents me from seeing if the miner still runs. Last statement is related to #340 .

**Comment by zhaodadi** [comment]
+1 want better logging info. maybe colored message like claymore.

**Comment by DeadManWalkingTO** [comment]
The Debug option -v [n]  values are 0 & 1.
Colors have been added to the new version.

Try latest version and feedback please.
Thank you!
