### ISSUE TITLE
Core Dump Boost Exception

### ISSUE THREAD

**Issue by uid89626** [ethereum-mining/ethminer#1851]
**Describe the bug**
ethminer 0.18.0-alpha.3-26+commit.ded21d37
Build: linux/release/gnu

 i 12:00:46 ethminer Configured pool :0
 i 12:00:46 ethminer Configured pool :0
 i 12:00:46 ethminer Selected pool :0
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  Invalid argument
Aborted (core dumped)

**To Reproduce**
1. build per instructions
2. ./ethminer -P  ...

**Expected behavior**
no core dump

**Environment (please complete the following information):**
- Linux zzzz 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by AndreaLanfranchi** [comment]
What is the full launch command line ?

**Comment by uid89626** [comment]
./ethminer -P eth.pool.minergate.com:45791

**Comment by AndreaLanfranchi** [comment]
That's not the correct syntax.
Should be

`./ethminer -P stratum://<youretheraddress>@eth.pool.minergate.com:45791`

For reference please read : https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md
