### ISSUE TITLE
Question about the exact index of the gpu that crashed (nvidia only)

### ISSUE THREAD

**Issue by Rodriguevb** [ethereum-mining/ethminer#1853]
In Ubuntu Server 16, with several GPUs and I use the environnement variable `CUDA_DEVICE_ORDER=PCI_BUS_ID`.

**My problem**
I suspect that a gpu is damaged. After a while, a gpu crashes.

**How can I know which one has crash ?**
This is the first that appears in the logs? Or should I see in the log kernel?
My idea is to observe the first GPU that crash in the logs and look at the correspondent with `nvidia-smi` command.. I am not sure that logs are in order because the program uses parallel processes :(

Someone can help me ? Thanks!

**Comment by AndreaLanfranchi** [comment]
Why don't follow the template to open an issue ?

Are you on Linux or Windows ?

**Comment by Rodriguevb** [comment]
Because my question about the logs don't change between Linux and Windows no?

I'm using Ubuntu Server 16

**Comment by AndreaLanfranchi** [comment]
It changes **a lot** if we have to help investigate which GPU is failing.

**Comment by AndreaLanfranchi** [comment]
On Linux use `dmesg` and you'll get the list of errors on which PCI id.
