### ISSUE TITLE
ethminer halts GUI

### ISSUE THREAD

**Issue by dchmelik** [ethereum-mining/ethminer#1868]
**Describe the bug**
    Ethminer (since about 0.16... tried with about every stable version since then) often works okay for a while, then starts halting my GUI.  Sometimes it's more likely after a reboot, but sometimes happens right away (without rebooting.)  Even for over an hour, all input has stopped (maybe display also won't update; ) can't even \<CTRL\>\<Fn\> out to a pure terminal to kill & restart GUI.

**To Reproduce**
1. Run ethminer until you mine some ether.  Later maybe reboot it and run it again (all I know is it might take more work to resume mining on a pool.)
2. Wait for GUI to become unresponsive and halt.

**Expected behavior**
    It shouldn't make your GUI be completely unresponsive/halted.  Other GPU miners such as for Bitcoin Gold and Feathercoin mine successfully on the same setup but don't make GUI unresponsive/halted.

**Environment (please complete the following information):**
- Operating System: Kubuntu GNU/Linux 18.04
- Hardware: Gigabyte AMD Radeon RX Vega 64
- Ethminer Version: several up to 0.17.1 
- Ethminer options used: ethminer --farm-recheck 200 --opencl -P stratum1+tcp://\<my address.worker\>@us2.ethermine.org:4444

**Comment by OutoSuomiUkko** [comment]
Have you tried different OS?

Im running Ubuntu 16.04 LTS after tried with 18.04 version with H110 PRO BTC+/ Raden RX580, Ethminer 0.17.1.

Options: ethminer -G stratum1+tcp://<my address.worker>@....

Now i only have to figure out what i am seeing on the screen.

**Comment by AndreaLanfranchi** [comment]
ethminer is designed and coded to take full advantage of GPU and the memory usage is far more intensive than in other coins/algos. A freeze of the GUI is expected : ethminer doesn't have "limiting" parameters.
Closing
