### ISSUE TITLE
Mining on INTEL NUC

### ISSUE THREAD

**Issue by Duf1220** [ethereum-mining/ethminer#1872]
Hello I would like to mine on: INTEL NUC8i7HVK, but I can't. 

ethminer 0.18.0-rc.0
Build: windows/release/msvc

Unrecognized platform Intel(R) OpenCL
CUDA Error : No CUDA driver found
Error: No usable mining devices found

C:\Users\fight\Desktop\Miner>pause
Press any key to continue . . .

**Comment by Duf1220** [comment]
[https://www.legitreviews.com/intel-hades-canyon-nuc8i7hvk-nuc-review-radeon-rx-vega-m-gpu_204024/4](url)

**Comment by Duf1220** [comment]
`https://www.legitreviews.com/intel-hades-canyon-nuc8i7hvk-nuc-review-radeon-rx-vega-m-gpu_204024/4`

**Comment by Duf1220** [comment]
https://www.legitreviews.com/intel-hades-canyon-nuc8i7hvk-nuc-review-radeon-rx-vega-m-gpu_204024/4

**Comment by AndreaLanfranchi** [comment]
Closed via #1988

**Comment by Duf1220** [comment]
Thank You!

Odesláno z iPhonu
