### ISSUE TITLE
Mining with NVIDIA 1080 TI

### ISSUE THREAD

**Issue by CorpCoin** [ethereum-mining/ethminer#1874]
Please someone who tells me how to use **Ethminer** with **NVIDIA 1080 TI,** and the new miner, I do not know how to run it, thanks for your help ethereum greetings

**Comment by nn47nn** [comment]
ethminer.exe --farm-recheck 2000 -U --HWMON 0 --display-interval 20 -R --exit -P stratum://YOUR_ADDRESS.RIG_ID@URL

**Comment by invidtiv** [comment]
also go here and check this out it will allow you to reach the maximum with the 1080ti.
https://github.com/LukasBures/OhGodAnETHlargementPill
