### ISSUE TITLE
Ethminer Not Finding Shares

### ISSUE THREAD

**Issue by Aphrodites1995** [ethereum-mining/ethminer#1882]
**Describe the bug**
Ethminer does not find any shares at all after mining for a hour at 20MH/s

**To Reproduce**
1.Go on ethminer.
2.Do this:
./ethminer -G -P stratum+tcp://address@us1.ethermine.org:4444
I actually put local and global work parameters, but without them it still doesn't make any shares.
3.I get no shares at all

**Expected behavior**
I get shares/

**Screenshots (Optional)**

**Environment (please complete the following information):**
- Operating System: MacOS 10.14
- Hardware AMD Radeon Pro 560X
- Ethminer Version 0.14.0 Release
- Ethminer options used -G local work global work

**Additional context**

**Comment by AndreaLanfranchi** [comment]
Post a full log.

**Comment by AndreaLanfranchi** [comment]
No feed back in over a month.
Closing.
