### ISSUE TITLE
My RTX 2080 does not work on your ethminer

### ISSUE THREAD

**Issue by 007fred50** [ethereum-mining/ethminer#1886]
Hello,

I try to get RTX 2080 to work but i can't.
i'm on ubuntu server 16.04

some i do worng? is says:
<img width="701" alt="Screenshot 2019-05-03 at 21 27 54" src="https://user-images.githubusercontent.com/25218874/57160873-5b1e5480-6dea-11e9-86b9-4cdafc2e4407.png">

error:
Cuda error in func 'set_constants' at line 143 : invalid device symbol.

**Comment by AndreaLanfranchi** [comment]
Seems like the output you're reporting is from a quite obsolete ethminer version.
Please report version `ethminer -V`

**Comment by 007fred50** [comment]
Hello,

ethminer -V

> ethminer version 1.2.9
> Build: Linux/g++/Interpreter/RelWithDebInfo

**Comment by AndreaLanfranchi** [comment]
That's not a version release from this repository.
We're still at major release 0.x

**Comment by 007fred50** [comment]
hello,

i'm on ethminer-0.18.0-rc.0-cuda-9-linux-x86_64
but it says: Segmentation fault

**Comment by AndreaLanfranchi** [comment]
Use 0.17.
0.18 rc is "release candidate". Still bugs on it.

**Comment by 007fred50** [comment]
But i'm on RTX 2080

ethminer0.17.0
says: Segmentation fault

**Comment by AndreaLanfranchi** [comment]
Have you set the correct -P parameter ? 
We have changed the syntax.

```
./ethminer -U -P stratum+tcp://007fred5%40gmail%2ecom@eth.pool.minergate.com:45791
```

See here https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md

**Comment by 007fred50** [comment]
Hello,

ethminer0.17.0 -> ./ethminer -U -P stratum+tcp://eth.pool.minergate.com:45791/007fred50@gmail.com

**Comment by AndreaLanfranchi** [comment]
Does it work ?

**Comment by 007fred50** [comment]
i does not work.

it says: Segmentation fault

**Comment by AndreaLanfranchi** [comment]
Post the output

**Comment by 007fred50** [comment]
ethminer0.17.0 -> ./ethminer -U -P stratum+tcp://eth.pool.minergate.com:45791/007fred50@gmail.com

output is: Segmentation fault.

there are no more oytput

**Comment by AndreaLanfranchi** [comment]
Describe the environment.
How many GPUs ?
Linux version ?
CUDA Version ?

What is the output of `./ethminer --list-devices` ?

**Comment by 007fred50** [comment]
1 x RTX 2080
ubuntu server 16.04
cuda 10.0

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+

| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:02:00.0 Off |                  N/A |
| 20%   33C    P8    30W / 215W |   7741MiB /  7951MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     23220      C   python3.5                                   7731MiB |
+-----------------------------------------------------------------------------+
```

But my nvidia-smi says: 10.1. thats worng !

nvcc --version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

**Comment by MariusVanDerWijden** [comment]
Your memory is almost completely used by a python process

**Comment by 007fred50** [comment]
Hello,

./ethminer -U -P stratum+tcp://eth.pool.minergate.com:45791/007fred50@gmail.com
still says: Segmentation fault

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:02:00.0 Off |                  N/A |
| 22%   40C    P0    N/A /  N/A |      0MiB /  7951MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by 007fred50** [comment]
hello,

some news ?

**Comment by Spudz76** [comment]
Turing core requires CUDA 10
You can't run CUDA 9 apps on it.
Compile for CUDA 10.1 if you want to run 418.39 or newer driver
With your current toolkit 10.0 downgrade to previous driver (then nvidia-smi will say 10.0, matching your toolkit)

toolkit is only if you compile and has nothing to do with running a release / precompiled

Driver contains whatever CUDA was current at the time, and is """""compatible"""""" across versions but note the large number of air quotes.  Best results always by matching all versions where CUDA is concerned.

See also [driver version to CUDA version table](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#binary-compatibility__table-toolkit-driver)

**Comment by Spudz76** [comment]
Any luck @007fred50 ?

**Comment by 007fred50** [comment]
Hello,

No, and i ask on: https://stackoverflow.com/questions/56543915/my-graphic-card-does-not-work-then-i-mine

still no luck ;/


maybe i need to wait for cuda 10.2 or 11

**Comment by Spudz76** [comment]
No, you need to make your app's CUDA version match your driver CUDA version match your toolkit version (or if not compiling uninstall the toolkit).  Currently you have I guess the release binary which is 10.0 compiled (at best), the 10.1 drivers, and a 10.0 toolkit (which does nothing for running an app, only compiling).

Downgrade driver so that nvidia-smi says 10.0 which should match the release which was compiled on 10.0.  The driver release notes pdf lists what CUDA runtime is included in each driver release, keep going back until it says 10.0 and then use that version driver.  Your issue is mismatching the CUDA versions and misunderstanding that CUDA-runtime is bundled with the drivers and so you can't just run the newest one unless all your CUDA apps are 10.1 compiled.  Toolkit has nothing to do with runtime, runtime comes with driver and changes to whatever's newest when the driver was released.  You have to run older driver before 10.1 was released to run 10.0 apps without random issues.

Or upgrade the toolkit to 10.1, and recompile from source, and it will work against current driver, containing CUDA 10.1, which is incompatible with 10.0-targeted apps - REGARDLESS what nvidia says it is not cross version compatible, unless you like odd problems (your current ones).

10.2 and 11 will just break even worse if you continue to try and run CUDA10.0 apps on it.  Make everything match or you will have problems.

**Comment by 007fred50** [comment]
hwo can i compile the ethminer ? from souce code. ?

I'm on,
ubuntu 16.4
rtx 2080

**Comment by AndreaLanfranchi** [comment]
Hi @007fred50 ,
here you can find detailed documentation about how you can build the binary on your own.

https://github.com/ethereum-mining/ethminer/blob/master/docs/BUILD.md

**Comment by 007fred50** [comment]
Hello,

i got this error: 

> cmake ..

```
CMake Error at CMakeLists.txt:3 (include):
  include could not find load file:

    cmake/cable/bootstrap.cmake


CMake Error at CMakeLists.txt:5 (include):
  include could not find load file:

    CableBuildInfo


CMake Error at CMakeLists.txt:6 (include):
  include could not find load file:

    CableBuildType


CMake Error at CMakeLists.txt:7 (include):
  include could not find load file:

    CableToolchains


CMake Error at CMakeLists.txt:8 (include):
  include could not find load file:

    HunterGate


CMake Error at CMakeLists.txt:10 (include):
  include could not find load file:

    defaults/HunterCacheServers


CMake Error at CMakeLists.txt:12 (cable_configure_toolchain):
  Unknown CMake command "cable_configure_toolchain".


-- Configuring incomplete, errors occurred!
```

**Comment by AndreaLanfranchi** [comment]
Have you issued

`git submodule update --init --recursive`

**before** starting the build ?

**Comment by 007fred50** [comment]
Hello,

> git submodule update --init --recursive
`
fatal: Not a git repository (or any of the parent directories): .git`

**Comment by AndreaLanfranchi** [comment]
Apparently you have extracted source code from zip archive. That does not work.
You have to **clone** the repository

**Comment by 007fred50** [comment]
with command for clone the repository?

**Comment by AndreaLanfranchi** [comment]
`git clone https://github.com/ethereum-mining/ethminer.git`

**Comment by 007fred50** [comment]
Hello,

it works now. !

**Comment by 007fred50** [comment]
Hello,

So it main, it overwirte the orginal?

```
-- Install configuration: "Release"
-- Installing: /usr/local/bin/kernels/ethash_tonga_lws64_exit.bin
-- Installing: /usr/local/bin/kernels/ethash_gfx900_lws128.bin
-- Installing: /usr/local/bin/kernels/ethash_gfx900_lws64.bin
-- Installing: /usr/local/bin/kernels/ethash_gfx900_lws128_exit.bin
-- Installing: /usr/local/bin/kernels/ethash_ellesmere_lws256.bin
-- Installing: /usr/local/bin/kernels/ethash_ellesmere_lws128.bin
-- Installing: /usr/local/bin/kernels/ethash_ellesmere_lws128_exit.bin
-- Installing: /usr/local/bin/kernels/ethash_gfx901_lws64_exit.bin
-- Installing: /usr/local/bin/kernels/ethash_gfx901_lws64.bin
-- Installing: /usr/local/bin/kernels/ethash_gfx901_lws128_exit.bin
-- Installing: /usr/local/bin/kernels/ethash_gfx900_lws256_exit.bin
-- Installing: /usr/local/bin/kernels/ethash_gfx900_lws256.bin
-- Installing: /usr/local/bin/kernels/ethash_gfx901_lws256.bin
-- Installing: /usr/local/bin/kernels/ethash_tonga_lws128_exit.bin
-- Installing: /usr/local/bin/kernels/ethash_gfx900_lws64_exit.bin
-- Installing: /usr/local/bin/kernels/ethash_tonga_lws256_exit.bin
-- Installing: /usr/local/bin/kernels/ethash_tonga_lws256.bin
-- Installing: /usr/local/bin/kernels/ethash_baffin_lws64.bin
-- Installing: /usr/local/bin/kernels/ethash_tonga_lws64.bin
-- Installing: /usr/local/bin/kernels/ethash_baffin_lws128_exit.bin
-- Installing: /usr/local/bin/kernels/ethash_ellesmere_lws64_exit.bin
-- Installing: /usr/local/bin/kernels/ethash_baffin_lws128.bin
-- Installing: /usr/local/bin/kernels/ethash_baffin_lws64_exit.bin
-- Installing: /usr/local/bin/kernels/ethash_gfx901_lws128.bin
-- Installing: /usr/local/bin/kernels/ethash_ellesmere_lws256_exit.bin
-- Installing: /usr/local/bin/kernels/ethash_tonga_lws128.bin
-- Installing: /usr/local/bin/kernels/ethash_ellesmere_lws64.bin
-- Installing: /usr/local/bin/kernels/ethash_gfx901_lws256_exit.bin
-- Installing: /usr/local/bin/kernels/ethash_baffin_lws256_exit.bin
-- Installing: /usr/local/bin/kernels/ethash_baffin_lws256.bin
-- Installing: /usr/local/bin/ethminer
```

so i just need this here? 

> ethminer -U -P stratum+tcp://eth.pool.minergate.com:45791/007fred50@gmail.com

**Comment by 007fred50** [comment]
hello,

i got this here:

```
./ethminer -U -P stratum+tcp://eth.pool.minergate.com:45791/007fred50@gmail.com


ethminer 0.18.0-rc.0-1+commit.17313073
Build: linux/release/gnu

Error: locale::facet::_S_create_c_locale name not valid
```

**Comment by 007fred50** [comment]
```
./ethminer -U -S eth.pool.minergate.com:45791 -u 007fred50@gmail.com


ethminer 0.18.0-rc.0-1+commit.17313073
Build: linux/release/gnu

Error: The following arguments were not expected: 007fred50@gmail.com -u eth.pool.minergate.com:45791 -S
```

**Comment by 007fred50** [comment]
Hello,

now it works:

> ./ethminer --list-devices

```

[ethminer 0.18.0-rc.0-1+commit.17313073
Build: linux/release/gnu

 Id Pci Id    Type Name                          CUDA SM  CL    Total Memory  Cl Max Alloc  Cl Max W.Grp 
--- --------- ---- ----------------------------- ---- --- ----  ------------  ------------  ------------ 
  0 02:00.0   Gpu  GeForce RTX 2080              Yes  7.5 Yes        7.76 GB       1.94 GB     1024.00 B
```

**Comment by 007fred50** [comment]
sorry i spam !

```
./ethminer -U -P stratum+tcp://eth.pool.minergate.com:45791/007fred50@gmail.com


ethminer 0.18.0-rc.0-1+commit.17313073
Build: linux/release/gnu

 i 13:37:42 ethminer Configured pool gmail.com:0
 i 13:37:42 ethminer Selected pool gmail.com:0
 X 13:37:43 ethminer Error  172.217.17.69:0 [ Operation canceled ]
 X 13:37:43 ethminer Error  [2a00:1450:400e:806::2005]:0 [ Network is unreachable ]
 X 13:37:43 ethminer No more IP addresses to try for host: gmail.com
 i 13:37:43 ethminer Disconnected from gmail.com:0
 i 13:37:43 ethminer No connection. Suspend mining ...
 i 13:37:43 ethminer Selected pool gmail.com:0
 X 13:37:44 ethminer Error  172.217.17.69:0 [ Operation canceled ]
 X 13:37:44 ethminer Error  [2a00:1450:400e:806::2005]:0 [ Network is unreachable ]
 X 13:37:44 ethminer No more IP addresses to try for host: gmail.com
 i 13:37:44 ethminer Disconnected from gmail.com:0
 i 13:37:44 ethminer No connection. Suspend mining ...
 i 13:37:44 ethminer Selected pool gmail.com:0
 X 13:37:45 ethminer Error  172.217.17.69:0 [ Operation canceled ]
 X 13:37:45 ethminer Error  [2a00:1450:400e:806::2005]:0 [ Network is unreachable ]
 X 13:37:45 ethminer No more IP addresses to try for host: gmail.com
 i 13:37:45 ethminer Disconnected from gmail.com:0
 i 13:37:45 ethminer No connection. Suspend mining ...
 i 13:37:45 ethminer No more connections to try. Exiting...
 i 13:37:45 main     Got interrupt ...
 i 13:37:45 ethminer Terminated!
```

**Comment by AndreaLanfranchi** [comment]
`ethminer -U -P stratum+tcp://007fred50%40gmail%2ecom@eth.pool.minergate.com:45791`

Email address need to be escaped as `@` and `.` are reserved delimiters for URI.
Read the docs !! 
https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md

Side note ... I highly discourage you from using minergate as a mining pool. Minergate provides **very low** initial diff **and** you have a very powerful GPU card. 
Before difficulty adjusts your card will try to push an extraordinary number of solutions to the pool causing delays in responses and, maybe, causing segfaults.

**Comment by 007fred50** [comment]
this here give me a error also.
```
./ethminer -U -P stratum+tcp://007fred50%40gmail%2ecom@eth.pool.minergate.com:45791


ethminer 0.18.0-rc.0-1+commit.17313073
Build: linux/release/gnu

Error: Bad URI : bad lexical cast: source type value could not be interpreted as target
```

**Comment by 007fred50** [comment]
so i can't get minergate to work?
not on the list..

**Comment by AndreaLanfranchi** [comment]
That error has been amended by a PR just today.

Go to the directory where you cloned the repository then issue:
`git pull`
and then rebuild the binary.

Report results then

**Comment by 007fred50** [comment]
hello,

thanks it works for me now.

**Comment by 007fred50** [comment]
Hello,

I'm ethminer with 30-32MH/s

**Comment by 007fred50** [comment]
hello,

i got the error here:

```
ethminer 0.18.0
Build: linux/release/gnu

 i 15:52:04 ethminer Configured pool eth.pool.minergate.com:45791
 i 15:52:04 ethminer Selected pool eth.pool.minergate.com:45791
 i 15:52:04 ethminer Stratum mode : Stratum
 i 15:52:04 ethminer Established connection to eth.pool.minergate.com [94.130.143.162:45791]
 i 15:52:04 ethminer Spinning up miners...
cu 15:52:04 cuda-0   Using Pci Id : 02:00.0 GeForce RTX 2080 (Compute 7.5) Memory : 7.79 GB
 X 15:52:07 ethminer No response received in 2 seconds.
 i 15:52:07 ethminer Disconnected from eth.pool.minergate.com [94.130.143.162:45791]
 i 15:52:07 ethminer No connection. Suspend mining ...
 i 15:52:07 ethminer Selected pool eth.pool.minergate.com:45791
 i 15:52:07 ethminer Stratum mode : Stratum
 i 15:52:07 ethminer Established connection to eth.pool.minergate.com [94.130.143.162:45791]
 i 15:52:07 ethminer Resume mining ...
 m 15:52:09 ethminer 0:00 A0 0.00 h - cu0 0.00
 X 15:52:10 ethminer No response received in 2 seconds.
 i 15:52:10 ethminer Disconnected from eth.pool.minergate.com [94.130.143.162:45791]
 i 15:52:10 ethminer No connection. Suspend mining ...
 i 15:52:10 ethminer Selected pool eth.pool.minergate.com:45791
 i 15:52:10 ethminer Stratum mode : Stratum
 i 15:52:10 ethminer Established connection to eth.pool.minergate.com [94.130.143.162:45791]
 i 15:52:10 ethminer Resume mining ...
 X 15:52:13 ethminer No response received in 2 seconds.
 i 15:52:13 ethminer Disconnected from eth.pool.minergate.com [94.130.143.162:45791]
 i 15:52:13 ethminer No connection. Suspend mining ...
 i 15:52:13 ethminer No more connections to try. Exiting...
 i 15:52:13 ethminer Shutting down miners...
 i 15:52:13 main     Got interrupt ...
 i 15:52:13 ethminer Terminated!
```

can you help me with that?

**Comment by Miktarbad** [comment]
i still dont get it..

first: `git clone https://github.com/ethereum-mining/ethminer.git`
second: `cd user/ethminer/cmake`
third: `git submodule update --init --recursive`
fourth: `cmake .. ` (???)
if i follow these steps i only get:
`-- Configuring incomplete, errors occurred!`

on Windows 10

**Comment by 007fred50** [comment]
Hello,

Cmake .. is a Linux command.
But if you want it to windows can be downloaded here https://github.com/ethereum-mining/ethminer/releases

Hope it helps

**Comment by whcjb** [comment]
have you solved the problem, i met the same error.
```
m 15:41:48 ethminer ethminer 0.17.1
 m 15:41:48 ethminer Build: linux/release
cu 15:41:48 ethminer Using grid size: 8,192, block size: 128
 i 15:41:48 ethminer Configured pool eth-cn2.dwarfpool.com:8008
 i 15:41:48 main     Selected pool eth-cn2.dwarfpool.com:8008
 X 15:41:48 stratum  Error  127.0.0.1:8008 [ Connection refused ]
 X 15:41:48 stratum  No more IP addresses to try for host: eth-cn2.dwarfpool.com
 i 15:41:48 main     Disconnected from  [127.0.0.1:8008]
 i 15:41:49 main     Selected pool eth-cn2.dwarfpool.com:8008
 X 15:41:49 stratum  Error  127.0.0.1:8008 [ Connection refused ]
 X 15:41:49 stratum  No more IP addresses to try for host: eth-cn2.dwarfpool.com
 i 15:41:49 main     Disconnected from  [127.0.0.1:8008]
 i 15:41:50 main     Selected pool eth-cn2.dwarfpool.com:8008
 X 15:41:50 stratum  Error  127.0.0.1:8008 [ Connection refused ]
 X 15:41:50 stratum  No more IP addresses to try for host: eth-cn2.dwarfpool.com
 i 15:41:50 main     Disconnected from  [127.0.0.1:8008]
```

**Comment by 007fred50** [comment]
Hello,

What works for me is: ethminer-0.18.0-cuda-9-linux-x86_64 downlaoded from (https://github.com/ethereum-mining/ethminer/releases)

Works wirth:
RTX 2080
ubuntu touch 16.04 server

**Comment by 007fred50** [comment]
with card do you have?

**Comment by whcjb** [comment]
tesla p40, i thought it's ports problem, there are only http connect to net

**Comment by 007fred50** [comment]
i can't help, but make new topic to the owner

**Comment by marcofariasmx** [comment]
> hello,
> 
> i got this here:
> 
> ```
> ./ethminer -U -P stratum+tcp://eth.pool.minergate.com:45791/007fred50@gmail.com
> 
> 
> ethminer 0.18.0-rc.0-1+commit.17313073
> Build: linux/release/gnu
> 
> Error: locale::facet::_S_create_c_locale name not valid
> ```

Can you share how did you fix this issue?

**Comment by Spudz76** [comment]
@marcofariasmx You could try checking `/etc/locale.gen` file and make sure the `en_US.UTF-8 UTF-8` line is not commented, and then run `sudo locale-gen` and it should be able to find the "C locale"

Another possible workaround is `export LC_ALL=C; unset LANGUAGE` before running ethminer.

**Comment by marcofariasmx** [comment]
> @marcofariasmx You could try checking `/etc/locale.gen` file and make sure the `en_US.UTF-8 UTF-8` line is not commented, and then run `sudo locale-gen` and it should be able to find the "C locale"
> 
> Another possible workaround is `export LC_ALL=C; unset LANGUAGE` before running ethminer.

That very last line did the trick as I do not have root privileges, thank you very much!
