### ISSUE TITLE
Output is garbled

### ISSUE THREAD

**Issue by 0xc0re** [ethereum-mining/ethminer#189]
Using ethminer 0.12.0.dev1 on Windows 10, the output of the miner is garbled. Specifically, the header(?) is garbled. Screenshot is attached.

![ethminer_output](https://user-images.githubusercontent.com/7865591/28487966-90063fe6-6e64-11e7-8743-29d407ada9fa.JPG)
.

**Comment by nguylb73** [comment]
What hardware are you running? Did you set your virtual memory? I've mine set to 16-32GB of RAM.

**Comment by Rootax** [comment]
Same thing here, on my 1060 in cuda mode, and fury x with opencl. 16gb of ram and 20gb of virtual memory.

**Comment by derubm** [comment]
why do you guys set that big ammoun of vram ? 16 gb should be more then efficient for a set of 2 cards
4 or 8 more then efficient for a single 1060. apart from that i d also have the strange 2 chars at the end of header, does not seem to affect hashrate / submits tho

**Comment by Rootax** [comment]
It's a recommandation that I see here and there.

**Comment by hcbraun** [comment]
Linux:
Jul 22 12:57:17 em card.sh[4993]:   m  12:57:17|ethminer-792d89  Mining on #c0172315… : 24.97MH/s [A32+0:R0+0:F0]

Looks like the unicode character "…" is not displayed correct

**Comment by gLUK00** [comment]
How do you get a hash rate higher than 59?
I have 3 GTX 1060, I am under ubuntu 14, and I can not exceed 58/59 with the 3 cards ...

**Comment by nguylb73** [comment]
@0xc0re try version 0.11.0, that's the release I'm on without display issues.

@derubm I run windows 10, and with 6 x 1070 cards. Windows already auto updates the vRam to 15 GB automatically after a few hours of running at default settings. So I just initiate at 16 and cap it at 32 based on a few recommendations online.

@gLUK00, what's your overclock/underclock settings set to?

**Comment by derubm** [comment]
@nguylb73 yeah , 6 cards neeed that , but one or two not :)

**Comment by gLUK00** [comment]
**@nguylb73**, I just changed the power to 65w per card because I have an error with my drivers on ubuntu 14 to change the overclock settings of the memory frequency.
Which operating system do you use?

**Comment by chfast** [comment]
Windows console does not accept UTF-8, sorry for that. I'll try to fix it later.

**Comment by nguylb73** [comment]
@gluk00, win10

**Comment by chfast** [comment]
Can you execute command `chcp 65001` before running ethminer?

**Comment by derubm** [comment]
works ;)
![image](https://user-images.githubusercontent.com/6720202/28495147-28b9ce16-6f45-11e7-91f3-09aa2e0ff081.png)

**Comment by DeadManWalkingTO** [comment]
I think the solution has been found.
