### ISSUE TITLE
mining.notify params in stratum+tcp protocol

### ISSUE THREAD

**Issue by topguru** [ethereum-mining/ethminer#1893]
I am trying to implement Stratum proxy now.
But I am getting the following error when call mining.notify in the proxy.
**Error: stratum got invalid Json message : BadHexCharacter**

**Request as following**

> {"jsonrpc": "2.0", "method": "mining.notify", "params": ["5ce36f915f627d2c5f96be9f", "0x0000000000000000000000000000000000000000000000000000000000000000", "0xe9ad2a6a7fead5aea9a68837929553fd0792fd0efc172c64041a3854e7022d1f", true]}

Please give me the valid params for **mining.notify** in stratum+tcp protocol
Thank you

**Comment by AndreaLanfranchi** [comment]
You're missing a value.
Your params array reports :
- Job Id == `5ce36f915f627d2c5f96be9f`
- Job Header == `0x0000000000000000000000000000000000000000000000000000000000000000` (which can't be all zeroes)
- Job Seed == `0xe9ad2a6a7fead5aea9a68837929553fd0792fd0efc172c64041a3854e7022d1f`
- Job Target == true (which is wrong ... should be a hex)

**Comment by topguru** [comment]
So 5th param is cleanjob?

**Comment by AndreaLanfranchi** [comment]
Yes

**Comment by topguru** [comment]
Thank you for your kind support.
