### ISSUE TITLE
Nvidia optimization 

### ISSUE THREAD

**Issue by MethanX** [ethereum-mining/ethminer#190]
Question for developer, is it possible to optimize miner for Nvidia Gpu-s even more than now for ethash especially  ? It will be great

**Comment by jimmykl** [comment]
Naturally this is what everyone is working towards! Not really suitable for raising an issue.

**Comment by MethanX** [comment]
Yes i am not seeing it as a issue, just a question.

**Comment by jimmykl** [comment]
I think it's safe to assume increased performance is part of what the devs are working on. As well as fixing bugs and adding new features.

By creating an issue someone has to read it, realise it's not a bug to be worked on, the number of issues increases and the devs get distracted. 

IMHO general chat and discussion is best kept on [Gitter](https://gitter.im/ethereum-mining/ethminer)

**Comment by MethanX** [comment]
My fault im sorry.

**Comment by chfast** [comment]
Every computed hash of ethash requires accessing 8192 bytes of random memory. You can compare that with your GPU's memory bandwidth. IIRC, we are around 80-90 % of theoretical max performance.

**Comment by MethanX** [comment]
Allright thanks for answer
