### ISSUE TITLE
Impossible to mine inside a docker container

### ISSUE THREAD

**Issue by jgredt** [ethereum-mining/ethminer#1903]
**Describe the bug**

**To Reproduce**
1. Pull the *ubuntu:disco* docker image 
2. Get inside the container, download *ethminer v0.18.0-rc.0*
3. Automatically install drivers with `ubuntu-drivers autoinstall`
4. Try to run a benchmark with `ethminer -U -M 1000`

**Expected behavior**
A simple error message, telling that ethminer isn't able to find a mining device : 

```
root@a0df18001e13:/home/eth/bin# ./ethminer -U -M 1000 
```

ethminer 0.18.0-rc.0
Build: linux/release/gnu

CUDA Error : no CUDA-capable device is detected
Error: No usable mining devices found

**Environment (please complete the following information):**
- Operating System: Ubuntu 19.04 inside a docker container, 5.0.0-15 kernel
- Hardware i5 6600k, GTX 1070, 16 GB RAM
- Ethminer Version v0.18.0-rc.0
- Ethminer options used
Stock options, just trying to run a benchmark with -U -M 1000

**Additional context**

When I'm trying to mine directly on my system, without a container, it works perfectly, whereas same drivers and same packages are installed. Zero error messages when mining in my main OS : 

```
jgredt@discoDingo:~/ethminer/bin$ ./ethminer -U -M 1000


ethminer 0.18.0-rc.0
Build: linux/release/gnu

 i 21:54:49 ethminer Selected pool localhost:0
 i 21:54:49 ethminer Established connection to localhost:0
 i 21:54:49 ethminer Spinning up miners...
cu 21:54:49 cuda-0   Using Pci Id : 01:00.0 GeForce GTX 1070 (Compute 6.1) Memory : 7.93 GB
 i 21:54:49 sim      Epoch : 0 Difficulty : 4.29 Gh
 i 21:54:49 sim      Job: ebcb100e… block 1000 localhost:0
cu 21:54:49 cuda-0   Generating DAG + Light : 1.02 GB
cu 21:54:52 cuda-0   Generated DAG + Light in 3�229 ms. 6.91 GB left.
 m 21:54:54 ethminer 0:00 A0 0.00 h - cu0 0.00
 m 21:54:59 ethminer 0:00 A0 6.67 Mh - cu0 6.67
 m 21:55:04 ethminer 0:00 A0 26.54 Mh - cu0 26.54
 m 21:55:09 ethminer 0:00 A0 26.72 Mh - cu0 26.72
^C i 21:55:11 main     Got interrupt ...
 i 21:55:11 main     Simulation results : Max 26.716248 Mh Mean 26.716244 Mh
 i 21:55:11 main     Disconnected from localhost:0
 i 21:55:11 main     Shutting down miners...
 i 21:55:12 main     Terminated!
```

The GPU is detected inside the Ubuntu container : 

```
root@a0df18001e13:/# lspci | grep VGA
01:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)
```

Installed drivers : 

```
root@a0df18001e13:/# apt list --installed | grep nvidia

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libnvidia-cfg1-418/disco,now 418.56-0ubuntu1 amd64 [installed,automatic]
libnvidia-common-418/disco,now 418.56-0ubuntu1 all [installed,automatic]
libnvidia-common-430/disco,now 430.14-0ubuntu0~gpu19.04.1 all [installed,auto-removable]
libnvidia-compute-418/disco,now 418.56-0ubuntu1 amd64 [installed,automatic]
libnvidia-decode-418/disco,now 418.56-0ubuntu1 amd64 [installed,automatic]
libnvidia-encode-418/disco,now 418.56-0ubuntu1 amd64 [installed,automatic]
libnvidia-fbc1-418/disco,now 418.56-0ubuntu1 amd64 [installed,automatic]
libnvidia-gl-418/disco,now 418.56-0ubuntu1 amd64 [installed,automatic]
libnvidia-ifr1-418/disco,now 418.56-0ubuntu1 amd64 [installed,automatic]
nvidia-compute-utils-418/disco,now 418.56-0ubuntu1 amd64 [installed,automatic]
nvidia-dkms-418/disco,now 418.56-0ubuntu1 amd64 [installed,automatic]
nvidia-driver-418/disco,now 418.56-0ubuntu1 amd64 [installed]
nvidia-kernel-common-418/disco,now 418.56-0ubuntu1 amd64 [installed,automatic]
nvidia-kernel-source-418/disco,now 418.56-0ubuntu1 amd64 [installed,automatic]
nvidia-prime/disco,now 0.8.10 all [installed,automatic]
nvidia-settings/disco,now 418.56-0ubuntu1 amd64 [installed,automatic]
nvidia-utils-418/disco,now 418.56-0ubuntu1 amd64 [installed,automatic]
xserver-xorg-video-nvidia-418/disco,now 418.56-0ubuntu1 amd64 [installed,automatic]
```

I've already tried to mine inside a Debian 9 Stretch container, it was the same result, even with the good drivers. I first thought that I missed something in the drivers installation, so I decided to go on Ubuntu and install everything automatically like on my main Ubuntu machine to make it work, but I was wrong...

**Comment by adhorden** [comment]
You are not passing the GPU into the container:

```--device /dev/nvidia0:/dev/nvidia0 --device /dev/nvidiactl:/dev/nvidiactl --device /dev/nvidia-uvm:/dev/nvidia-uvm```

You need to allow the Docker container to have access to the GPU by passing the device into the Docker container. As an example you need something like this:

```docker run --interactive --privileged --publish 3333:3333 --tty --device /dev/nvidia0:/dev/nvidia0 --device /dev/nvidiactl:/dev/nvidiactl --device /dev/nvidia-uvm:/dev/nvidia-uvm```

I successfully use ethminer inside a Docker container.

Hope this helps,

**Adam D. Horden**

**Comment by jgredt** [comment]
Hello ! 

It works perfectly, thanks a lot for your help !
I should've looked further into the Docker options...
