### ISSUE TITLE
ethminer-0.17.1 - UBIQ actept share but I can not see any pool stat

### ISSUE THREAD

**Issue by kolumbus120** [ethereum-mining/ethminer#1907]
When I use mining ubiq on pools I get 2 options. 
1. Reject reason : Unspecified - on ubiqpool.maxhash.org
2. I get **Accepted  43 ms. eu.ubiqpool.org, but when I want to see some statistics on pool server I get nothing. It looks like the server doesn`t know about my miner

**Environment (please complete the following information):**
- Operating System: [Windows 10]
- Hardware [GTX 1050 Ti]
- Ethminer Version [0.17.1]
- cuda 10
- my command
ethminer.exe --work-timeout 880 -U -P stratum1+tcp://wal.rig2@ubiq-eu.maxhash.org:10008
or
ethminer.exe --work-timeout 880 -U -P stratum1+tcp://wal.rig2@eu.ubiqpool.org:8002

What you suggest?

**Comment by AndreaLanfranchi** [comment]
This ethminer is not meant to mine UBIQ (which has differences from normal ethereum's ethash).
Don't know why pool responds "Accepted"

**Comment by kolumbus120** [comment]
Thank you. Then I ask them why on ubiq miner page when you want to download it it transfer to this page with ethminer.
