### ISSUE TITLE
CUDA 10.1 support on Linux

### ISSUE THREAD

**Issue by Pr0methean** [ethereum-mining/ethminer#1926]
**Is your feature request related to a problem? Please describe.**
I use Ubuntu 19.04 with CUDA 10.1. The latest version of ethminer only supports Ubuntu 18.10 and CUDA 9, and running it on my system gives an error:
```
$ ethminer -U -P getwork://localhost


ethminer 0.18.0
Build: linux/release/gnu

CUDA Error : unknown error
Error: No usable mining devices found
```

**Describe the solution you'd like**
I'd like to be able to use ethminer without having to downgrade Ubuntu or CUDA.

**Describe alternatives you've considered**
Trying other mining software.

**Comment by qisikai** [comment]
+1
I am using cuda 10 too,  and I wish to use ethminer with cuda 10

**Comment by slinkyvagabond** [comment]
Ethminer 19 alpha works perfectly with CUDA 10.2 on Ubuntu 19.10. Currently using it with a MSI GTX 1070Ti

juddly@miner1:~$ ethminer -U -P stratum1+tcp://xxxxxxxxxxxxxxxxxxxx.gtx1070@us.cruxpool.com:5555 -R --cuda-block-size 256 --cuda-streams 8
ethminer 0.19.0-alpha.0-1+commit.7015b1a8
Build: linux/release/gnu

 i 09:16:27 ethminer Configured pool us.cruxpool.com:5555
 i 09:16:27 ethminer Selected pool us.cruxpool.com:5555
 i 09:16:27 ethminer Stratum mode : Eth-Proxy compatible
 i 09:16:27 ethminer Established connection to us.cruxpool.com [144.217.180.180:5555]
 i 09:16:27 ethminer Spinning up miners...
cu 09:16:27 cuda-0   Using Pci Id : 01:00.0 GeForce GTX 1070 Ti (Compute 6.1) Memory : 7.93 GB

**Comment by oliverlj** [comment]
no issue with 0.18 and driver 440/435

**Comment by AndreaLanfranchi** [comment]
Closing as long lived with no further feedback
