### ISSUE TITLE
Which part of  code snippets calculate reported hash rate in ethminer

### ISSUE THREAD

**Issue by IRFANALI-0101** [ethereum-mining/ethminer#1931]
Please guide me reported hash rate calculation part. also in which format ethminer communicate to pool
@Thanks
@LianaHus

**Comment by MariusVanDerWijden** [comment]
https://github.com/ethereum-mining/ethminer/blob/7015b1a8be7f945c020d5bc5b4745f98eb3508f2/libethcore/Miner.cpp#L175

The hashrate calculation is done here.

**Comment by MariusVanDerWijden** [comment]
The pool protocols can be found here: 
https://github.com/ethereum-mining/ethminer/tree/master/libpoolprotocols
Ethminer supports getwork and stratum to communicate with pools.

**Comment by IRFANALI-0101** [comment]
Thanks 💟

**Comment by IRFANALI-0101** [comment]
Please, Can you guide me which Part of code and in which format the
reported hashrate submitted to Pool?!
I'll be very thankful to you because I have spent most of the time on this
module.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/09/19,
04:37:34 PM

**Comment by MariusVanDerWijden** [comment]
https://github.com/ethereum-mining/ethminer/blob/7015b1a8be7f945c020d5bc5b4745f98eb3508f2/libpoolprotocols/stratum/EthStratumClient.cpp#L1545
