### ISSUE TITLE
non responsive API on 0.18.0 and 0.19.0-alpha.0 (cuda10.0)

### ISSUE THREAD

**Issue by danielocdh** [ethereum-mining/ethminer#1938]
**Describe the bug**
The API is not responding to any command, happens around 95% of launches.

**To Reproduce**
1. Start ethminer under windows 10 with a command like this:
`--HWMON 1 -P stratum+tcp://0x*********.******:x@us1.ethermine.org:4444 --api-port 4028`
2. connect with putty(raw connection) to either 127.0.0.1 or lan IP on specified port
3. paste any command and press enter i.e.
`{"id":0,"jsonrpc":"2.0","method":"miner_ping"}`
4. no response received

**Expected behavior**
To receive the appropiate response like I do with older versions like 0.17.1 cuda10.0

**Environment (please complete the following information):**
- Operating System:
3x Windows 10 1703 (fully windows updated except for drivers)
1x Windows 10 1809 (fully windows updated)
- Hardware:
4x GTX 1060, driver 419.17
6x GTX 1070, driver 419.17
6x GTX 1070, driver 419.17
1x GTX 1080ti, driver 436.48
- Ethminer Version: 0.18.0 cuda10.0 and 0.19.0-alpha.0 cuda10.0
- Ethminer options used: `--HWMON 1 -P stratum+tcp://0x*********.******:x@us1.ethermine.org:4444 --api-port 4028`

**Additional context**
Besides using putty I also tried `echo '{"id":0,"jsonrpc":"2.0","method":"miner_ping"}' | netcat <LAN IP> 4028` from a linux machine (I double checked there wasn't any firewall block). The netcat command didn't produce any output but didn't exit, same result as with putty.
As mentioned before, the API seems to be responsive every few launches, I'm guessing in around 1 out of 20 launches.

**Comment by Demion** [comment]
Same behavior.
I think problem at `libapicore/ApiServer.cpp` is `isRunning` check in `ApiServer::begin_accept` happens before `m_running` is set to `true`.
Try change these 2 lines in order. If I am not mistaken, it solved problem for me.
https://github.com/ethereum-mining/ethminer/blob/782292d15c885cc51aea520bf812326937c184fb/libapicore/ApiServer.cpp#L271-L272

**Comment by StefanOberhumer** [comment]
Don't think that solves the problem as "m_running" is just used if ApiServer::stop() gets called.

**Comment by Demion** [comment]
`m_running` in `isRunning()` is checked in `begin_accept()`
https://github.com/ethereum-mining/ethminer/blob/782292d15c885cc51aea520bf812326937c184fb/libapicore/ApiServer.cpp#L292-L293
https://github.com/ethereum-mining/ethminer/blob/782292d15c885cc51aea520bf812326937c184fb/libapicore/ApiServer.h#L78
