### ISSUE TITLE
not using all GPUs at the same time on windows 10

### ISSUE THREAD

**Issue by imirzadeh** [ethereum-mining/ethminer#194]
Hi
I have 4 x AMD RX470(4GB) GPUs, running on winodws 10
ethminer knows all the gpus when I run ethminer.exe --list-devices but when I run and monitor gpus, it only shows 2 gpus are busy at the same time and not 4 !   
first gpu1 and gpu2 are busy and gpu3 and gpu4 are idle then gpu3 and gpu4 are busy and gpu1 and gpu2 are idle and .....   
What can I do to use all my gpus at the same time?  
ethminer version   => tested 0.10 and 0.11
Radeon Settings Version => 2017.0424.2119.36535
Driver Packaging Version => 17.10.1731-170424a2-313745C-CrimsonReLive
OpenCL™ Version => 22.19.162.4

**Comment by nodet07** [comment]
also this is odd for me, 
![ethminer_bug](https://user-images.githubusercontent.com/8312051/28495489-2fd1297a-6f03-11e7-9be9-c063b747dbdd.png)

**Comment by derubm** [comment]
try the latest dev version.

**Comment by roninkaizen** [comment]
@nodet07 i would try to parallelize the process,
as you start device 1 and 3 together, and start afterwards with the device 2 and 4 you should come to a running solution, i am also still testing, but change to the process as mentioned brought a running miner using 4 gpus instead of 2
i am aware, that this is not a solution but a workaround 8-)

**Comment by YanBellavance** [comment]
I had the same issue
This seems to be a OS issue not the miner because in my case:
nvidia-smi reveals the OS does not see all GPUs

**Comment by DeadManWalkingTO** [comment]
Last build believe works fine!

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!

**Comment by DeadManWalkingTO** [comment]
OpenCL Hardware Test Launch Command:

`ethminer -RH -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

Try with latest Ethminer version and feedback please.
Thank you!
