### ISSUE TITLE
ethminer, AMD, macos...

### ISSUE THREAD

**Issue by krrkrr** [ethereum-mining/ethminer#1944]
Hi...

I've managed to compile Ethminer on macos 10.13 ... on a macpro with a RX580 4Go.

Of course, I used the conf arguments for cmake:
`cmake .. -DETHASHCUDA=OFF`
to make it work.
cmake, git, perl, gcc are updated with homebrew.

but ethminer, once compiled without any error, can't find my RX580 when I launch it with -G --list-devices

what am I missing ?

Thanks !

**Comment by krrkrr** [comment]
I've tried on a 2019 iMac 27' with 10.14 (got a 580X, AMD too...) ... Compiling seems to be fine... 

but same result... no device found ?!

**Comment by krrkrr** [comment]
hello ? anybody ?

**Comment by m3scott** [comment]
Use this patch...  simple two line add.

https://github.com/ethereum-mining/ethminer/issues/1839

**Comment by yfaney** [comment]
I posted a PR for this. You can cherry-pick this into your branch as well:
https://github.com/ethereum-mining/ethminer/pull/1951

**Comment by AndreaLanfranchi** [comment]
MacOS support has been dropped long time ago.
We won't patch this.
