### ISSUE TITLE
Ethminer killed

### ISSUE THREAD

**Issue by parumira3** [ethereum-mining/ethminer#1945]
Tit : Ethminer killed

Hi. I'm a begginer of developing of mining

I've run Ethminer on arm+mali g71 board
But 
I have difficulty running Ethminer on ARM board with Mali G7 GPU now
(Ethminer is killed so is not working on this Architecture)

Following is H/W & S/W specification.

01. O/S : Ubuntu16.04 LTS
02. CPU : ARMv8 (2) x64 AES
03. GCC : 7.4.0
04. CPU : ARMv8 (2) x64 AES L2:0.0 MB L3:0.0 MB 8C/8T NUMA:1
05. GPU : Mali G71
06. MEMORY : 6 GB 
07. OPENCL : 2.0
08. LIBS : libuv/1.34.0 OpenSSL/1.1.1d hwloc/2.1.0
09. Ethminer version : 0.15
10. Ethminer options used : $ ./ethminer -G -P stratum+tcp

I don't know what I should do?

**Comment by MariusVanDerWijden** [comment]
Hey @parumira3,
we currently don't have an ARM release. Have you tried compiling ethminer from source for your architecture?

**Comment by jasonwee** [comment]
@parumira3 what is your board name? can you share links to the board?

**Comment by parumira3** [comment]
> Hey @parumira3,
> we currently don't have an ARM release. Have you tried compiling ethminer from source for your architecture?

[Thanks to Ur reply!!!]

Yes, I have
I have built ethminer 0.15 on my machine above.
I didn't get what I want.
I guess the problem is DAG size of Ethereum but it's not sure

**Comment by MariusVanDerWijden** [comment]
Yeah, I don't think we'll be able to support Mali G71 GPUs. 
I'll close this thread if its fine for you

**Comment by parumira3** [comment]
I understand!
I am going to edit source file of ethminer  myself (CLMiner.cpp)
But I have short  idea about that.

Could tell me tips about the ARM + MaliG7 *roughly* ?
what line, what code included

and I have a question about opencl.

Is it possible to run ethminer 0.15 with opencl 1.0 ?

2020년 1월 7일 (화) 오후 8:41, Marius van der Wijden <notifications@github.com>님이
작성:

**Comment by parumira3** [comment]
Sorry to be late to your reply.
It's a Hikey 960 board.

My Github issue was closed a few days ago.

Please  email to me.

My address is k20753014@gmail.com

2020년 1월 6일 (월) 오후 8:39, jasonwee <notifications@github.com>님이 작성:
