### ISSUE TITLE
Startup code...

### ISSUE THREAD

**Issue by GrueseGehenRaus** [ethereum-mining/ethminer#1947]
My Startup code isn't working properly. Can someone spot my mistake?
"setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --farm-recheck 200 -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0xe61E746e2133fBb02449D79349Bcb0209eed5A3b.Miner01
pause"
Thanks

**Comment by AndreaLanfranchi** [comment]
This is your friend: https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md#ethermineorg

Your correct startup command is
```
ethminer.exe -U -P stratum1+tcp://0xe61E746e2133fBb02449D79349Bcb0209eed5A3b.Miner01@eu1.ethermine.org:4444 -P stratum1+tcp://0xe61E746e2133fBb02449D79349Bcb0209eed5A3b.Miner01@us1.ethermine.org:444
```
