### ISSUE TITLE
not showing hashrate on windows 10

### ISSUE THREAD

**Issue by imirzadeh** [ethereum-mining/ethminer#195]
I'm running ethminer on windows 10, and hashrate is not printed in the console as in linux versions!  
I also tested -v 9 but still nothing is printed !  
versions tested => ethminer 0.10.0 and 0.11.0

**Comment by derubm** [comment]
test -v 9 (u need to provide a blank between v and 9)

**Comment by nodet07** [comment]
@derubm sry I made a mistake in my first comment[also edited], but in my bat file I wrote -v 9!

**Comment by derubm** [comment]
in every version i used, -v 1 / -v 0 was the only values that surpressed the hasrate. 
are you running it from a batchfile or are you using a gui to run ethminer ?

**Comment by nodet07** [comment]
@derubm I ran it from batch file, here is my file:
```
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --opencl-platform 1 -G  -F url -v 9

```

**Comment by derubm** [comment]
i asume url is the url to your pool/ethhadress etc... 
looks pretty straight to me

**Comment by nodet07** [comment]
yes its the url of my pool

**Comment by derubm** [comment]
ethminer --farm-recheck 450 -SC 2 -G -F http://eth-eu.dwarfpool.com:80/0x762c924a469f21a446529bd8f6b07db6bde124bf/AMD/testminer@gmail.com
try that, replace ethereum adress/email  with yours.

**Comment by DeadManWalkingTO** [comment]
Everything works now?

**Comment by DeadManWalkingTO** [comment]
OpenCL Hardware Test Launch Command:

`ethminer -RH -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.issue195`

Try with latest Ethminer version and feedback please.
Thank you!
