### ISSUE TITLE
cmake, install ethminer

### ISSUE THREAD

**Issue by 007fred50** [ethereum-mining/ethminer#1958]
Hello,

follow the guide here (https://www.perfacilis.com/blog/crypto-currency/mining-ethereum-on-ubuntu-with-ethminer.html)

i got a problem here then i try to "cmake .. -DETHASHCUDA=ON -DETHASHCL=OFF"

I got this error here:
```
CMake Error at CMakeLists.txt:3 (include):
  include could not find load file:

    cmake/cable/bootstrap.cmake


CMake Error at CMakeLists.txt:5 (include):
  include could not find load file:

    CableBuildInfo


CMake Error at CMakeLists.txt:6 (include):
  include could not find load file:

    CableBuildType


CMake Error at CMakeLists.txt:7 (include):
  include could not find load file:

    CableToolchains


CMake Error at CMakeLists.txt:8 (include):
  include could not find load file:

    HunterGate


CMake Error at CMakeLists.txt:10 (include):
  include could not find load file:

    defaults/HunterCacheServers


CMake Error at CMakeLists.txt:12 (cable_configure_toolchain):
  Unknown CMake command "cable_configure_toolchain".


-- Configuring incomplete, errors occurred!
```

Can you help me with that? i try to compile the source code.

**Comment by 007fred50** [comment]
i found out it was:
"git submodule update --init --recursive"

**Comment by kivechang** [comment]
"git submodule update --init --recursive"
Can't solve the problem

Wǒ kàn dào hěnduō rén shuō tā kěyǐ
10 / 5000
翻譯結果
I see so many people say it can but it can’t

**Comment by 007fred50** [comment]
if you can't solve the problem can you download it from here? (https://github.com/ethereum-mining/ethminer/releases)

**Comment by kivechang** [comment]
> 如果您不能解決問題，可以從這裡下載嗎？（https://github.com/ethereum-mining/ethminer/releases）

yes, i download it from here,and i follow the https://github.com/ethereum-mining/ethminer/blob/master/docs/BUILD.md
windows10 
RTX3080
ethminer 0.19.0-alpha.0

**Comment by hadonga** [comment]
> "git submodule update --init --recursive"
> Can't solve the problem
> 
> I see so many people say it can but it can’t

because you download zip file where cable folder is empty. try download by using git.

**Comment by hadonga** [comment]
> "git submodule update --init --recursive"
> Can't solve the problem
> 
> I see so many people say it can but it can’t

because cable folder is empty. download cable folder from following link and put into cmake folder. https://github.com/ethereum/cable/tree/3e54f9751f50a3b6265c22402dcd5ae85ef701d4

**Comment by kivechang** [comment]
> > "git submodule update --init --recursive"
> > Can't solve the problem
> > I see so many people say it can but it can’t
> 
> because you download zip file where cable folder is empty. try download by using git. (git clone https://github.com/no-fee-ethereum-mining/nsfminer)

thx I tried to download a single cable.
it can work
i also download nsfminer 
I am testing the difference between the two of them
thx again
