### ISSUE TITLE
Every other block is empty

### ISSUE THREAD

**Issue by uluhonolulu** [ethereum-mining/ethminer#1963]
**Describe the bug**
I am testing a private blockchain consisting of 4 Parity nodes. I am sending many identical transactions to a node, and have a miner attached to another node. Even though there are many unmined transactions, every other block is empty.

**Expected behavior**
As long as there are unmined transactions, every block should contain some.

**Screenshots (Optional)**
This is the console output of a node:
![image](https://user-images.githubusercontent.com/872764/75148030-545d2700-5707-11ea-8456-df1d89fda302.png)

**Environment (please complete the following information):**
- Operating System:  **Ubuntu 18.04.3 LTS**
- Hardware -- not sure about this, I can ask if this is important
- Ethminer Version: **0.12**
- Ethminer options used: `./ethminer -G -SP [my-IP]:8855`

**Additional context**
While the odd blocks contain zero transactions, the even blocks contain exactly 81 transactions, while the gas limit allows for much more (they spend only 1.7Mgas of the 8Mgas limit), but I'm not sure it's related.

**Comment by AndreaLanfranchi** [comment]
This can happen when your miner is pushing solutions too fast for the node to keep up.
As far as I know geth behavior (not parity) when a new block is sealed the node sends the miner a new block template with only coinbase transaction. Only after few milliseconds (the time to pick TXs from mempool) sends a second block template to the miner. But if in that interval the miner has found a solution for the empty block ... the empty block is appended to the chain.

**Comment by uluhonolulu** [comment]
@AndreaLanfranchi interesting, but the interval is a few seconds in my case:
```
2020-02-25 15:01:39 UTC Imported #71286 0x7fe5…728d (0 txs, 0.00 Mgas, 1 ms, 1.06 KiB)
2020-02-25 15:01:48 UTC Imported #71287 0x2570…f406 (81 txs, 1.70 Mgas, 5 ms, 9.08 KiB)
2020-02-25 15:01:53 UTC Imported #71288 0xe957…a7ae (0 txs, 0.00 Mgas, 0 ms, 0.53 KiB)
2020-02-25 15:02:02 UTC Imported #71289 0xae3e…a0ea (81 txs, 1.70 Mgas, 3 ms, 9.08 KiB)
2020-02-25 15:02:05 UTC Imported #71290 0xe68f…3f16 (0 txs, 0.00 Mgas, 0 ms, 0.53 KiB)
```

For example, one block containing transactions has a timestamp of `0x5e5536d3`, the next one, empty, `0x5e5536dc`.

**Comment by MariusVanDerWijden** [comment]
Do you have a link to your script that you use to send the transaction so that we can reproduce?
Additionally what parity version are you using?

**Comment by uluhonolulu** [comment]
@MariusVanDerWijden I'm using ` Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0` for submitting transactions, and the miner is attached to another node running `v2.5.13-stable`.

As for the script, the relevant part is here:  https://gist.github.com/uluhonolulu/5728e99536b9393c0e2f540eb451d60e (I just removed the code that saved the data to a DB). The idea is to send 10 000 transactions with a delay of 1ms. All transactions are hashed successfully.

Here is a fresh screenshot:
![image](https://user-images.githubusercontent.com/872764/76143145-72b71100-607d-11ea-90f9-509cefbc9d40.png)
Note that even non-empty blocks contain exactly 81 transactions, consuming 1.7Mgas, although the block limit is ~8Mgas

**Comment by uluhonolulu** [comment]
@MariusVanDerWijden We upgraded to **0.18**, but the issue remains. Here is a piece of the log. There was an empty block at **10:14:23** (the last before the current batch of transactions started being mined), then a full block at **10:14:53** and then another empty block at **10:15:14**:

```
2|miner-cu9 | i 10:14:23 ethminer **Accepted 161 ms. 45.32.149.10:8855
2|miner-cu9 | i 10:14:23 ethminer Epoch : 6 Difficulty : 818.32 Mh
2|miner-cu9 | i 10:14:23 ethminer Job: fdd88ed8… 45.32.149.10:8855
2|miner-cu9 | i 10:14:23 ethminer Job: fdd88ed8… 45.32.149.10:8855
2|miner-cu9 | m 10:14:25 ethminer 6:26 A1538 46.28 Mh - cu0 23.40, cu1 22.87
2|miner-cu9 | m 10:14:30 ethminer 6:26 A1538 46.22 Mh - cu0 23.38, cu1 22.84
2|miner-cu9 | m 10:14:35 ethminer 6:26 A1538 46.25 Mh - cu0 23.40, cu1 22.86
2|miner-cu9 | m 10:14:40 ethminer 6:26 A1538 46.26 Mh - cu0 23.40, cu1 22.86
2|miner-cu9 | m 10:14:45 ethminer 6:26 A1538 46.28 Mh - cu0 23.41, cu1 22.87
2|miner-cu9 | m 10:14:50 ethminer 6:26 A1538 46.24 Mh - cu0 23.39, cu1 22.85
2|miner-cu9 | cu 10:14:53 cuda-1 Job: fdd88ed8… Sol: 0x30ff37764adbc647
2|miner-cu9 | i 10:14:53 ethminer **Accepted 161 ms. 45.32.149.10:8855
2|miner-cu9 | i 10:14:53 ethminer Epoch : 6 Difficulty : 817.53 Mh
2|miner-cu9 | i 10:14:53 ethminer Job: 67471210… 45.32.149.10:8855
2|miner-cu9 | i 10:14:53 ethminer Job: 67471210… 45.32.149.10:8855
2|miner-cu9 | m 10:14:55 ethminer 6:26 A1539 46.27 Mh - cu0 23.41, cu1 22.87
2|miner-cu9 | m 10:15:00 ethminer 6:26 A1539 46.23 Mh - cu0 23.37, cu1 22.85
2|miner-cu9 | m 10:15:05 ethminer 6:27 A1539 46.24 Mh - cu0 23.40, cu1 22.84
2|miner-cu9 | m 10:15:10 ethminer 6:27 A1539 46.25 Mh - cu0 23.39, cu1 22.86
2|miner-cu9 | cu 10:15:14 cuda-1 Job: 67471210… Sol: 0x30ff37763e7a49db
2|miner-cu9 | i 10:15:14 ethminer **Accepted 163 ms. 45.32.149.10:8855
2|miner-cu9 | i 10:15:14 ethminer Epoch : 6 Difficulty : 817.13 Mh
2|miner-cu9 | i 10:15:14 ethminer Job: 500d2908… 45.32.149.10:8855
2|miner-cu9 | i 10:15:14 ethminer Job: 500d2908… 45.32.149.10:8855
```

Note that it took ~20s to mine an empty block while there were transactions waiting to be mined.

**Comment by AndreaLanfranchi** [comment]
You're looking in the wrong direction.
Ethminer has no clue about the composition of the block or whether it is empty or not.
It simply receives an hashing work package from the node and tries to find a solution.
All it gets is header, epoch and difficulty. Nothing else.
If you mine empty blocks you have to look into nodes implementations which are out of the scope of the miner.

**Comment by uluhonolulu** [comment]
@AndreaLanfranchi  Thanks for the clarification!
