### ISSUE TITLE
Set UTF-8 codepage on Windows

### ISSUE THREAD

**Issue by chfast** [ethereum-mining/ethminer#197]
Use https://docs.microsoft.com/en-us/windows/console/setconsoleoutputcp to set UTF-8 encoding for console output on Windows.

**Comment by evilny0** [comment]
This would only work on Win10.

Win7 command line is apparently riddled with bugs for unicode. Even just trying to change the codepage to UTF-8 from command line (chcp 65001 as you mentionned in #189) results in a crash, for both regular terminal & powershell.

Should we implement it only for Win10 ?

**Comment by chfast** [comment]
Yes, why not.

**Comment by DeadManWalkingTO** [comment]
Maybe enhancement.

**Comment by XhmikosR** [comment]
@chfast is this still valid?

**Comment by chfast** [comment]
Yes. But I'm not sure you can set the codepage from within the executable correctly.
If possible, all Unicode logs should be displayed properly on Windows.
