### ISSUE TITLE
Benchmarking and simulation work great, mining does not

### ISSUE THREAD

**Issue by Ecco** [ethereum-mining/ethminer#198]
Using version 0.12.0-dev1 on macOS.

## Benchmarking and simulation: OK

`ethminer -G -M` reports a 7 MH/s rate.

`ethminer -G -Z` also a 7 MH/s rate, and gives many "SUCCESS: GPU gave correct result!"

In both cases:
- Generating the DAG takes some time (~10 seconds)
- Mining puts a load on the GPU (the fan spins and the GPU gets hot)
- CPU is virtually idle

## Actual mining: Not working

`ethminer -G -F insert_pool_here` or just plain `ethminer -G` for solo mining seem to work but actually do not:
 - DAG is built nearly instantly
 - The reported hashrate is insane ("Mining on PoWhash #1f4c9e1e : 8433.07MH/s [A0+0:R0+0:F0]")
 - GPU fans are mostly silent
 - CPU is running at 100%

**Comment by chfast** [comment]
Can you try simulation at the current block height? E.g. `ethminer -G -Z 4100000`?

**Comment by Ecco** [comment]
Wow, spot on! Mining with `ethminer -G -Z 4100000` does indeed exhibit the exact same buggy behavior!

**Comment by derubm** [comment]
@ecco could it be a reason of not enough GDDR5 memory ? (current dag size is about 2.5 gb)

**Comment by Ecco** [comment]
Unfortunately I don't think it's a memory issue. That's a 4GB AMD GPU. Here's the output of `ethminer --list-devices`:
```
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] AMD Radeon HD Hawaii PRO Prototype Compute Engine
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 4294967296
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1073741824
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
```

**Comment by derubm** [comment]
try : ethminer -F http://eth-eu.dwarfpool.com:80/0x762c924a469f21a446529bd8f6b07db6bde124bf -G --opencl-platform 0 --cl-global-work 512
(replace with your eth address)

**Comment by chfast** [comment]
See `CL_DEVICE_MAX_MEM_ALLOC_SIZE` - it is 1GB
You have to increase it by setting env vars `GPU_MAX_ALLOC_PERCENT` and `GPU_SINGLE_ALLOC_PERCENT` to `100`. Or use more recent development build. This is included in the master branch: https://github.com/ethereum-mining/ethminer/pull/186.
