### ISSUE TITLE
What happens to RX 4xx/5xx with 8GB vRAM after DAG file is larger than 4GB?

### ISSUE THREAD

**Issue by bimonsubio1984** [ethereum-mining/ethminer#1982]
Hello,

I was told that all 2-3 years old video cards like RX 470,480,570,580 even having 8GB of vRAM in total still suffer from the problem of 32bit address space for a single DAG file and are therefore limited to 4GB per a single DAG file. 

It applies even to NVidia GTX 1080 Ti too?

Are all these 32 bit DAG cards going to stop mining Ethereum v1  by the end of this 2020 year?

There are some rumors about possibility of some driver fix which could add 64 bit mode, is it true?
Is it going to happen? Does it depend only on AMD? When is it going to be clear and known for sure whether AMD RX 8GB are fixed or not?

Thanks for your help

**Comment by AndreaLanfranchi** [comment]
Hi. Issue is **only** related to **OpenCL** implementation thus mostly AMD (is stupid to have NVIDIA cards run in non-CUDA mode). 
Problem has been addressed and solved by #1977 and #1979.
Source only though so you have to compile the binary yourself.

**Comment by bimonsubio1984** [comment]
Andrea, thank you very much for explanation.

Please clarify if I understood correctly:

1) The problem of DAG file being limited to 4GB does occur only using OpenCL (non AMD  
ROCm), on ROCm the problem would not even happen? And now it is solved even on OpenCL (non ROCm) by splitting DAG file into two parts.

2) If there is a miner using NVidia card directly via CUDA instead of OpenCL it would not suffer from 4GB limit for a DAG file, is it correct?

For example any miner using CUDA to access NVidia 1080 Ti will not ever suffer 4GB limit for a DAG file, such file size is limited only by total vRAM at about 11GB, is it correct?

3) Btw, are there any ROCm based miners for AMD cards?

**Comment by joaogti36** [comment]
there so little cuda miners for eth... only ethminer is the realthing!

**Comment by ddobreff** [comment]
2. Correct.
3. ROCm has no such limitation BUT DAG will be split anyway, this did not show any slowdown so no performance hit is expected. If you are using ROCm and wish to load single DAG - feel free to revert the commits mentioned above.

**Comment by bimonsubio1984** [comment]
Thanks for suggestions.

Does RX 470 8GB work fine with ROCm? Are there any differences compared to RX 580 except 25% percents of performance? Architectures of RX 470 and RX 580 look almost the same IMHO.

Though it seems that only RX 580 is mentioned as supported on ROCm page.

Except mining I would like to learn and experiment with TensorFlow on RX 470 8GB card, is it possible, are there any limitations compared to RX 580?

**Comment by mauser98k** [comment]
using the latest Adrenaline driver from AMD with my Gigabyte 8gb RX580 rig, i can benchmark past 4gb dag using Claymore V15.0... also using clinfo it shows max memory is now at 8gb instead of 4gb...  this may or may not work on other rigs or other cards...  it just works on mine...

still need a miner capable of mining past epoch 384 though, because Claymore V15.0 will not go past that dag number....

**Comment by AndreaLanfranchi** [comment]
Closed via #1977
