### ISSUE TITLE
ethminer stops working

### ISSUE THREAD

**Issue by smalla** [ethereum-mining/ethminer#1984]
For some reason ethminer stops sending in units after some time (days sometimes weeks).

How can I help debug this problem ?

**To Reproduce**
Start ethminer.
Wait (weeks)

**Expected behavior**
either results are sent in properly, or process detects the failure and quits, so it can be restarted automatically.
Im using systemd, and it wont restart the process, as it is working normally from the systemd side of view.

**Screenshots (Optional)**
when it is working in the wrong way, I see only these lines in the logs:
12:07:08 rig01 ethminer[29653]: cl 12:07:08 cl-4     Job: 8ad13842… Sol: 0xdffeb1ba4e6f767b
12:07:09 rig01 ethminer[29653]: cl 12:07:09 cl-1     Job: 8ad13842… Sol: 0xdffeb1b36be716d7
12:07:12 rig01 ethminer[29653]: cl 12:07:12 cl-0     Job: 2a7ab0f2… Sol: 0xdffeb1b671456823
12:07:16 rig01 ethminer[29653]: cl 12:07:16 cl-0     Job: 2a7ab0f2… Sol: 0xdffeb1b679d1449a
12:07:49 rig01 ethminer[29653]: cl 12:07:49 cl-4     Job: 8ad13842… Sol: 0xdffeb1ba9b445f9b
12:08:33 rig01 ethminer[29653]: cl 12:08:33 cl-1     Job: 8ad13842… Sol: 0xdffeb1b40809acbe
12:10:22 rig01 ethminer[29653]: cl 12:10:22 cl-3     Job: 8ad13842… Sol: 0xdffeb1bdc355510a
12:10:39 rig01 ethminer[29653]: cl 12:10:39 cl-4     Job: 8ad13842… Sol: 0xdffeb1bbd56ae5b1
12:11:11 rig01 ethminer[29653]: cl 12:11:11 cl-1     Job: 8ad13842… Sol: 0xdffeb1b52a4fec25
12:11:11 rig01 ethminer[29653]: cl 12:11:11 cl-2     Job: 8ad13842… Sol: 0xdffeb1b8769b928a

instead of this when it is working normally:
Apr 14 12:26:42 rig01 ethminer[29653]: cl 12:26:42 cl-1     Job: f57102ba… Sol: 0xdffeaf5293891eea
Apr 14 12:26:42 rig01 ethminer[29653]:  i 12:26:42 ethminer **Accepted  24 ms. eu1.ethermine.org [172.65.207.106:4444]
Apr 14 12:26:45 rig01 ethminer[29653]:  i 12:26:45 ethminer Job: a5030e8e… block 9869998 eu1.ethermine.org [172.65.207.106:4444]
Apr 14 12:26:45 rig01 ethminer[29653]: cl 12:26:45 cl-2     Job: a5030e8e… Sol: 0xdffeaf5391fced1f
Apr 14 12:26:45 rig01 ethminer[29653]:  i 12:26:45 ethminer **Accepted  18 ms. eu1.ethermine.org [172.65.207.106:4444]
Apr 14 12:26:46 rig01 ethminer[29653]:  m 12:26:46 ethminer 1:22 A156 153.70 Mh - cl0 30.79 83C 76% A36, cl1 30.45 0C 0% A25, cl2 30.72 0C 0% A28, cl3 30.98 0C 0% A33, cl4 30.75 0C 0% A34
Apr 14 12:26:49 rig01 ethminer[29653]:  i 12:26:49 ethminer Job: 3e5bf47d… block 9869998 eu1.ethermine.org [172.65.207.106:4444]
Apr 14 12:26:51 rig01 ethminer[29653]:  i 12:26:51 ethminer Job: 67f4b429… block 9869999 eu1.ethermine.org [172.65.207.106:4444]
Apr 14 12:26:51 rig01 ethminer[29653]:  i 12:26:51 ethminer Job: 56126c4d… block 9869999 eu1.ethermine.org [172.65.207.106:4444]
Apr 14 12:26:51 rig01 ethminer[29653]:  m 12:26:51 ethminer 1:22 A156 153.82 Mh - cl0 30.89 83C 76% A36, cl1 30.48 0C 0% A25, cl2 30.74 0C 0% A28, cl3 30.96 0C 0% A33, cl4 30.75 0C 0% A34
Apr 14 12:26:55 rig01 ethminer[29653]:  i 12:26:55 ethminer Job: 6d964581… block 9869999 eu1.ethermine.org [172.65.207.106:4444]
Apr 14 12:26:56 rig01 ethminer[29653]:  m 12:26:56 ethminer 1:22 A156 153.63 Mh - cl0 30.72 83C 75% A36, cl1 30.51 0C 0% A25, cl2 30.66 0C 0% A28, cl3 30.95 0C 0% A33, cl4 30.81 0C 0% A34

**Environment (please complete the following information):**
- Operating System: Ubuntu 18.04.3 LTS
- Hardware: 5x Radeon RX580
- Ethminer Version [e.g. 0.14] 0.18.0
- Ethminer options used
-G -R -P stratum://0x662changed.rig01@eu1.ethermine.org:4444 --tstop 85 --tstart 65 --HWMON 0 -v 2

**Additional context**

**Comment by AndreaLanfranchi** [comment]
This means GPU threads are stuck (i.e. are waiting indefinitely for a response result from GPU) and possible reason is the GPU(s) has fallen of the bus (in other words GPU(s) has lost contact with the host computer). Mostly this happens due to excessive overclocking or bad PCIe risers.

**Comment by reqshark** [comment]
yeah this happens to me when GPU temps are too high, you might try lowering the `--tstop` threshold

**Comment by AndreaLanfranchi** [comment]
No feed back.
Closing
