### ISSUE TITLE
The following arguments were not expected

### ISSUE THREAD

**Issue by Ragers** [ethereum-mining/ethminer#1987]
**Describe the bug**
I created a start.bat file in windows 10 pointing to the ethminer.exe file with the following setup:

```
TITLE miner
cd /
cd C:\Users\Me\Documents\eth\bin
setx GPU_FORCE64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --farm-recheck 200 -G -U -S eu1.ethermine.org:4444 -FS eu1.ethermine.org:14444 -O 0x77ba81d13ce4330d3ef1cc77bcd9fe43383cbbf2
pause
```
But as soon as the .exe runs I get the following error:
```
ethminer.exe --farm-recheck 200 -G -U -S eu1.ethermine.org:4444 -FS eu1.ethermine.org:14444 -O 0x77ba81d13ce4330d3ef1cc77bcd9fe43383cbbf2

ethminer 0.18.0
Build: windows/release/msvc

Error: The following arguments were not expected: 0x77ba81d13ce4330d3ef1cc77bcd9fe43383cbbf2 -O eu1.ethermine.org:14444 -FS eu1.ethermine.org:4444 -S
```

I cannot really find proper documentation on how to create this .bat file and what is necessary for the script to properly run.

**Comment by StefanOberhumer** [comment]
> I cannot really find proper documentation on how to create this .bat file and what is necessary for the script to properly run.

Refer to https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md
(Syntax for pools has changed a long time ago!)


I think your options should look like:
```ethminer.exe -X -P stratum1+tcp://0x77ba81d13ce4330d3ef1cc77bcd9fe43383cbbf2@eu1.ethermine.org:4444 -P stratum1+tcp://0x77ba81d13ce4330d3ef1cc77bcd9fe43383cbbf2@eu1.ethermine.org:14444```
