### ISSUE TITLE
Featurerequest: Restart Miner on 0 MH/s 

### ISSUE THREAD

**Issue by faithless1108** [ethereum-mining/ethminer#199]
Hey Devteam, 

first of all: Thank you for your great work. Ethminer ist running verry fast an stable on Nvidia-Cards now. We're running a 6x GTX 1070 rig @arround 190mh/s! Way better than Claymore!

But theres one feature wich would be verry nice. Sometimes (didn't find a reason yet) the Miner has "CUDA unspecific launch fail" and puts out 0 MH/s, for hours if you dont stop and restart it. 

It would be verry nice if you could start Monitoring this issue and just restart the Miner if something like this happens... 

KR

**Comment by orkblutt** [comment]
They are some scripts around to deal with that.
Here a tool I'm doing: https://github.com/orkblutt/MinerLamp

**Comment by Gertsch** [comment]
Have got the same issue occurring from time to time on a small 2x1060 rig.
Can't tell why, but it would be nice to have such an option.

**Comment by derubm** [comment]
another watchdog: https://github.com/derubm/Ethminer_Watchdog
reacts on exception, error in output, restarts mining process. 
multible pools configurable-  no GUI, only dos box ;) 

if you guys like a gui, orkbluts tools is nice.

**Comment by Singman33** [comment]
If we get an API on that program, monitoring the hashrate and restarting the miner will be easy.
See issue #170

**Comment by Git1Hub2** [comment]
Ethminer_Watchdog does not work on us2.ethermine.org:14444 ?
I can not make it work

**Comment by derubm** [comment]
if its a straum you need to crrect -F to -S in mining.cmd

**Comment by Git1Hub2** [comment]
erro:
 stratum      Connecting to stratum server http://us2.ethermine.org:14444/ ....../GTX1060/miner@coin.org
 stratum      resolve:  A classe especidicada no foi escontrada
stratum       Reconnecting in 3 seconds....

**Comment by derubm** [comment]
you need to sepcify -o , etc .. anyway easiest way is to use stratum proxy,.
pre configured local stratum mining is allready as a sample in watchdog.bat ( entry 2. )
needs change on miner and password for your configuration.

**Comment by Git1Hub2** [comment]
Changing only (Your_Ethereum_Address.RigName)
GTX 1060 3G = 29MH / S stable
very good
congratulations

**Comment by jimmykl** [comment]
@Git1Hub2 29Mh/s on one 1060 3G?! What type of card, memory and overclock?!

**Comment by Git1Hub2** [comment]
Is it right?
  m  13:29:46|main      Mining on #1a3303bc… : 30.31MH/s [A4+0:R0+0:F0]
  m  13:29:47|main      Mining on #1a3303bc… : 0.00MH/s [A4+0:R0+0:F0]
  m  13:29:48|main      Mining on #1a3303bc… : 30.17MH/s [A4+0:R0+0:F0]
  m  13:29:48|main      Mining on #1a3303bc… : 29.92MH/s [A4+0:R0+0:F0]
  m  13:29:49|main      Mining on #1a3303bc… : 30.09MH/s [A4+0:R0+0:F0]
  m  13:29:50|main      Mining on #1a3303bc… : 30.17MH/s [A4+0:R0+0:F0]

1 GTX 1060 3G MSI MEMORY SANSUNG  
DRIVER : 376.51
MEMORY CLOCK : +1000

--cuda-parallel-hash 4 --cuda-streams 10 --cuda-grid-size 8192 --cuda-block-size 256 -v 9

**Comment by jimmykl** [comment]
Oh yep that's a good result!

**Comment by Git1Hub2** [comment]
Sorry but it's not mining!Nothing appears in the pool

![1111](https://user-images.githubusercontent.com/30468619/28636384-5a34760e-7214-11e7-8529-bbd9be6ca8d5.png)

**Comment by derubm** [comment]
your mining url is false
(address. ???)

**Comment by Git1Hub2** [comment]
Why is the MH / s so high? I already tried a lot and I can not change ... I'm a beginner in this rsrs sorry

**Comment by derubm** [comment]
its because of your memory speed, it is maxed out.

**Comment by prototypeL** [comment]
@Git1Hub2 
May I ask how did you installed tesla driver (ver. 376.51) in your 1060? i tried it but failed miserably...

**Comment by Git1Hub2** [comment]
I downloaded the cuda_8.0.61_win10 from 1.3gb
And he installs this driver (376.51) alone
Https://developer.nvidia.com/cuda-downloads

**Comment by dawjdh** [comment]
I encountered the same issue while playing around with different clock-speeds, power and maximum wattage and wrote a little script to restart on low watts (low MHz sounds even better ...):

```
#!/bin/bash

wallet_id="0x2824194fa61ac4b64ffa485b10d1045c9fbc83d3"
pool_url="http://eth-eu.dwarfpool.com:80/"
etherminer_cmd="ethminer -U -F $pool_url/$wallet_id --farm-recheck 200"
min_watts="55.00"

echo "Starting miner"
eval $etherminer_cmd &
echo "Waiting for 30s for watts to rise"
sleep 30

while sleep 10;do
    current_watts=$(nvidia-smi -i 0 --format=csv --query-gpu=power.draw | sed -n 2p | cut -d ' ' -f 1);
    echo "Current watts: $current_watts";
    if (( $(awk 'BEGIN {print ("'$current_watts'" <= "'$min_watts'")}') )); then
    	echo "Restarting, because low on current watts: $current_watts <= min_watts"
        killall "ethminer"
        sleep 5
        eval $etherminer_cmd &
        echo "Waiting for 30s for watts to rise"
        sleep 30
    fi
done
```

**Comment by DeadManWalkingTO** [comment]
I believe now the issue have been solved #757 (added --exit parameter to exit whenever an error occurred).

**Comment by smurfy** [comment]
Its not solved, but a workaround exists now.

**Comment by sandrodz** [comment]
@smurfy what is the workaround?
