### ISSUE TITLE
 Generating DAG + Light Unexpected error CUDA error in func initEpoch_internal

### ISSUE THREAD

**Issue by okarpov** [ethereum-mining/ethminer#2000]
i 16:40:28 <unknown> Spinning up miners...
cu 16:40:28 cuda-0   Using Pci Id : 01:00.0 GeForce GTX 1650 (Compute 7.5) Memory : 4.00 GB
 i 16:40:28 <unknown> Authorized worker 0xABCDEF...XYZ
 i 16:40:28 <unknown> Epoch : 344 Difficulty : 4.00 Gh
 i 16:40:28 <unknown> Job: 38e37d3b... eu1.ethermine.org [172.65.207.106:5555]
 i 16:40:30 <unknown> Job: f59c96b3... eu1.ethermine.org [172.65.207.106:5555]
cu 16:40:30 cuda-0   Generating DAG + Light : 3.75 GB
cu 16:40:30 cuda-0   Unexpected error CUDA error in func dev::eth::CUDAMiner::initEpoch_internal at line 123 out of memory on CUDA device 01:00.0
cu 16:40:30 cuda-0   Mining suspended ...

**Comment by supermera** [comment]
Did you solve it? I have the same problem after adding 5th GPU to my rig. Rig with 4 cards runs well.

**Comment by maxcom99** [comment]
The only solution was to run one instance per card...

**Comment by SirDickbutt** [comment]
A bit late and not an actual solution, but I also got same error when I tried first time adding second card into system (B85M motherboard with 3pcie (1x16, 2x1) connectors, WIN10x64 home, GPU1=1660 Ti, GPU2=1660 SUPER, ethminer 0.18.0 cuda 10, now at 387 epoch - my info if interested). After adding and removing separately cards found that the culprit behind that error was pcie extension cable. I'm using cheap ribbon type pcie extender. Sometimes after win boot card connected with cable won't show up or report that it don't have VRAM (0MB VRAM). Now I'm waiting for fancier USB3.0 cable-like connector. When I get them, I'll report if that solved anything for me. Until than I have to use two separate rigs.

**Comment by digibill** [comment]
I get the same error on a mining rig with 5 GPUs (4x nvidia 1070 8GB + 1x nvidia 1060 6GB), running Ubuntu Linux 18.04 (nvidia driver 460.32.03, Cuda 11.2)

`ethminer 0.19.0-alpha.0
Build: linux/release/gnu

 i 15:43:08 ethminer Configured pool eu1.ethermine.org:4444
 X 15:43:08 ethminer Could not start API server on port: 0
 X 15:43:08 ethminer Ensure port is not in use by another service
 i 15:43:08 ethminer Selected pool eu1.ethermine.org:4444
 i 15:43:08 ethminer Negotiation of EthereumStratum/2.0.0 failed. Trying another ...
 i 15:43:08 ethminer Stratum mode : EthereumStratum/1.0.0 (NiceHash)
 i 15:43:08 ethminer Established connection to eu1.ethermine.org [172.65.207.106:4444]
 i 15:43:08 ethminer Spinning up miners...
cu 15:43:08 cuda-0   Using Pci Id : 01:00.0 GeForce GTX 1060 6GB (Compute 6.1) Memory : 5.93 GB
cu 15:43:08 cuda-1   Using Pci Id : 02:00.0 GeForce GTX 1070 (Compute 6.1) Memory : 7.93 GB
cu 15:43:08 cuda-2   Using Pci Id : 04:00.0 GeForce GTX 1070 (Compute 6.1) Memory : 7.93 GB
cu 15:43:08 cuda-3   Using Pci Id : 06:00.0 GeForce GTX 1070 (Compute 6.1) Memory : 7.93 GB
cu 15:43:08 cuda-4   Using Pci Id : 07:00.0 GeForce GTX 1070 (Compute 6.1) Memory : 7.93 GB
 i 15:43:08 ethminer Authorized worker ----------------------------- (edited from me)
 i 15:43:08 ethminer Epoch : 389 Difficulty : 4.29 Gh
 i 15:43:08 ethminer Job: 68b4f092… eu1.ethermine.org [172.65.207.106:4444]
 i 15:43:11 ethminer Job: 8916e011… eu1.ethermine.org [172.65.207.106:4444]
 i 15:43:13 ethminer Job: d169ac8a… eu1.ethermine.org [172.65.207.106:4444]
 m 15:43:13 ethminer 0:00 A0 0.00 h - cu0 0.00 65C 50%93.867000, cu1 0.00 63C 45%107.267000, cu2 0.00 68C 47%107.345000, cu3 0.00 61C 42%111.814000, cu4 0.00 66C 44%108.496000
cu 15:43:14 cuda-0   Generating DAG + Light : 4.10 GB
cu 15:43:14 cuda-0   Unexpected error CUDA error in func initEpoch_internal at line 123 out of memory on CUDA device 01:00.0
cu 15:43:14 cuda-0   Mining suspended ...
cu 15:43:14 cuda-1   Generating DAG + Light : 4.10 GB
cu 15:43:14 cuda-1   Unexpected error CUDA error in func initEpoch_internal at line 123 out of memory on CUDA device 02:00.0
cu 15:43:14 cuda-1   Mining suspended ...
cu 15:43:14 cuda-4   Generating DAG + Light : 4.10 GB
cu 15:43:14 cuda-3   Generating DAG + Light : 4.10 GB
cu 15:43:14 cuda-2   Generating DAG + Light : 4.10 GB
cu 15:43:14 cuda-4   Unexpected error CUDA error in func initEpoch_internal at line 123 out of memory on CUDA device 07:00.0
cu 15:43:14 cuda-4   Mining suspended ...
cu 15:43:14 cuda-3   Unexpected error CUDA error in func initEpoch_internal at line 123 out of memory on CUDA device 06:00.0
cu 15:43:14 cuda-3   Mining suspended ...
cu 15:43:14 cuda-2   Unexpected error CUDA error in func initEpoch_internal at line 123 out of memory on CUDA device 04:00.0
cu 15:43:14 cuda-2   Mining suspended ...
`

I get the same error with ethminer 0.18 and with nvidia drivers 450 and 455.

The strange thing is that ethminer runs OK at my desktop PC with just a single nvidia 1070Ti 8GB gpu.

With this issue I've been forced to move to t-rex miner, but I prefer ethminer.

Any ideas please?

**Comment by digibill** [comment]
UPDATE:
I managed to solve this issue on Ubuntu 18.04. It is ram related.

By installing at least 8GB of RAM, ethminer can genetrate the DAG file and proceeds to mining. Bear in mind that just expanding swap file did not work - even with a swap memory of 8GB, ethermine did not generate DAG file.

So, from epoch 389 ethminer needs at least 8GB of physical memory (RAM) to generate the DAG and start mining.

**Comment by okarpov** [comment]
i have 4 GB VGA and 16 GB RAM on Windows 10

**Comment by digibill** [comment]
@okarpov 
The DAG file in now 4.10GB and it should reside within GPU memory for mining. So, at current epoch I don't think you can mine ETH on 4 GB GPUs....

**Comment by okarpov** [comment]
> @okarpov
> The DAG file in now 4.10GB and it should reside within GPU memory for mining. So, at current epoch I don't think you can mine ETH on 4 GB GPUs....

i see, thx

**Comment by Ferryistaken** [comment]
I got the same error on an 8gb gpu (Nvidia rtx 2080 super)

**Comment by Ferryistaken** [comment]
Uninstalled and reinstalled `ethminer-bin`. It now works

**Comment by koletron-coder** [comment]
файл подкачки попробуй увеличить

**Comment by aolave** [comment]
SOLUTION > https://www.youtube.com/watch?v=ZL0m7tVt_DU&ab_channel=Cryptomined
it works for me
