### ISSUE TITLE
ethminer doesn't show AMD devices in ethminer -G --list-devices

### ISSUE THREAD

**Issue by sabotagebeats** [ethereum-mining/ethminer#2001]
**Describe the bug**
ethminer cannot see any amd devices

**To Reproduce**
try to run ethminer and it will only run on integrated graphics. ethminer -G --list-devices only shows integrated graphics

**Expected behavior**
use AMD graphics 

**Environment (please complete the following information):**
- Operating System: Windows 10
- Hardware RX580
- Ethminer Version 0.17
- Ethminer options used .\ethminer.exe -G --list-devices

**Additional context**
windows 10 1903

**Comment by sabotagebeats** [comment]
looks like same issue here: https://github.com/ethereum-mining/ethminer/issues/1936

maybe affecting all windows and amd

**Comment by sabotagebeats** [comment]
running this fine on another pc with windows 1903 so that is definitely not the issue.

**Comment by jgonzis** [comment]
"HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors".

Solution for AMD Radeon GPUs not showing up:

Go to C:\Windows\System32\ and search for amdocl64.dll for OpenCL 2.1, x86_64. (There are also amdocl.dll for OpenCL 2.1, x86; amdocl12cl.dll for OpenCL 1.2, x86; and amdocl12cl64.dll for OpenCL 1.2, x86_64.)

Look for the most recent file, right-click, click "Properties," and then select and copy the file's Location (which is the path to its directory). (Mine was in a subdirectory of C:\Windows\System32\DriverStore\FileRepository\)

Open regedit, aka the Registry Editor, (e.g. via Windows key+r, and entering regedit)

Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors

Create a new DWORD with the Name being the path from step 2 with \amdocl64.dll at the end (or whichever dll version you need or want), and leave the key's data at 0. My key's Name, for example, is C:\Windows\System32\DriverStore\FileRepository\u0336248.inf_amd64_107cc52c701c83d0\B336252\amdocl64.dll

should now see AMD GPUs!

**Comment by Fordstaa** [comment]
> Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors
> 
> Create a new DWORD C:\Windows\System32\DriverStore\FileRepository\u0336248.inf_amd64_107cc52c701c83d0\B336252\amdocl64.dll
> 
> should now see AMD GPUs!

Jgonzis you are a champ! I just created an account just to say thanks. After 3 days of uninstalling and reinstalling my Radeon drivers for my new Sapphire RX 5700XT, in my frustrated attempt to figure out why ethminer and kapow miner could not detect my AMD gpu, giving the Error No OpenCL Device Found... your solution to create the registry entry to the amdocl64.dll worked like a charm!!!

I wished I read your post 3 days earlier!
I have a hunch my issue came about when I used the Display Driver Uninstaller software to completely remove all traces of my previous Nvidia graphics card drivers but probably also removed the AMD registry keys as well which pointed to the opencl dll files.

Seems like also creating the registry entries may have also fixed my screen flickering problem that occurs whenever I try overclock the memory... however will need more test on that later to be sure. This AMD Radeon Adrenalin Edition 20.8.2 Driver seems to be working quite stable as well.

Cheers again!

**Comment by Pdom02** [comment]
> "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors".
> 
> Solution for AMD Radeon GPUs not showing up:
> 
> Go to C:\Windows\System32\ and search for amdocl64.dll for OpenCL 2.1, x86_64. (There are also amdocl.dll for OpenCL 2.1, x86; amdocl12cl.dll for OpenCL 1.2, x86; and amdocl12cl64.dll for OpenCL 1.2, x86_64.)
> 
> Look for the most recent file, right-click, click "Properties," and then select and copy the file's Location (which is the path to its directory). (Mine was in a subdirectory of C:\Windows\System32\DriverStore\FileRepository)
> 
> Open regedit, aka the Registry Editor, (e.g. via Windows key+r, and entering regedit)
> 
> Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors
> 
> Create a new DWORD with the Name being the path from step 2 with \amdocl64.dll at the end (or whichever dll version you need or want), and leave the key's data at 0. My key's Name, for example, is C:\Windows\System32\DriverStore\FileRepository\u0336248.inf_amd64_107cc52c701c83d0\B336252\amdocl64.dll
> 
> should now see AMD GPUs!
I checked in my files but I didn't have an amdocl64.dll file. How should I go about getting it? I just updated drivers today but it still won't show up. Should I just wipe my drivers and reinstall them?

**Comment by domgrigore** [comment]
> 
> 
> "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors".
> 
> Solution for AMD Radeon GPUs not showing up:
> 
> Go to C:\Windows\System32\ and search for amdocl64.dll for OpenCL 2.1, x86_64. (There are also amdocl.dll for OpenCL 2.1, x86; amdocl12cl.dll for OpenCL 1.2, x86; and amdocl12cl64.dll for OpenCL 1.2, x86_64.)
> 
> Look for the most recent file, right-click, click "Properties," and then select and copy the file's Location (which is the path to its directory). (Mine was in a subdirectory of C:\Windows\System32\DriverStore\FileRepository)
> 
> Open regedit, aka the Registry Editor, (e.g. via Windows key+r, and entering regedit)
> 
> Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors
> 
> Create a new DWORD with the Name being the path from step 2 with \amdocl64.dll at the end (or whichever dll version you need or want), and leave the key's data at 0. My key's Name, for example, is C:\Windows\System32\DriverStore\FileRepository\u0336248.inf_amd64_107cc52c701c83d0\B336252\amdocl64.dll
> 
> should now see AMD GPUs!

This fixed my issue after uninstalling with DDU on an RX 580!

**Comment by sweet876** [comment]
"HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors" 
don't have this path, but VULKAN installed. Looks like Ethminer don't see a new registry by AMD 
my rig is AMD rx5700xt  and driver ver. 20.9.1. Search by registry do nothing because in Ethminer code seek in old algorithm OpenCL? I'm right? or not.

**Comment by Fordstaa** [comment]
> "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors"
> don't have this path, but VULKAN installed. Looks like Ethminer don't see a new registry by AMD
> my rig is AMD rx5700xt and driver ver. 20.9.1. Search by registry do nothing because in Ethminer code seek in old algorithm OpenCL? I'm right? or not.

You could try create the pathways in the registry and point them to the correct amdocl64.dll files. You can use notepad and create the entries like my below sample (replacing the : u0359160.inf_amd64_2abe2598d9a3141f\\B358802\\ with your own file pathway) and then save file as "filename.reg" and then merge it to your registry:


Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors]
"C:\\Windows\\System32\\DriverStore\\FileRepository\\u0359160.inf_amd64_2abe2598d9a3141f\\B358802\\amdocl64.dll"=dword:00000000
"C:\\Windows\\System32\\DriverStore\\FileRepository\\u0359160.inf_amd64_2abe2598d9a3141f\\B358802\\amdocl12cl64.dll"=dword:00000000
"C:\\Windows\\System32\\DriverStore\\FileRepository\\u0359160.inf_amd64_2abe2598d9a3141f\\B358802\\amdocl12cl.dll"=dword:00000000
"C:\\Windows\\System32\\DriverStore\\FileRepository\\u0359160.inf_amd64_2abe2598d9a3141f\\B358802\\amdocl.dll"=dword:00000000

**Comment by jasper22** [comment]
> "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors".
> 
> Solution for AMD Radeon GPUs not showing up:
> 
> Go to C:\Windows\System32\ and search for amdocl64.dll for OpenCL 2.1, x86_64. (There are also amdocl.dll for OpenCL 2.1, x86; amdocl12cl.dll for OpenCL 1.2, x86; and amdocl12cl64.dll for OpenCL 1.2, x86_64.)
> 
> Look for the most recent file, right-click, click "Properties," and then select and copy the file's Location (which is the path to its directory). (Mine was in a subdirectory of C:\Windows\System32\DriverStore\FileRepository)
> 
> Open regedit, aka the Registry Editor, (e.g. via Windows key+r, and entering regedit)
> 
> Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors
> 
> Create a new DWORD with the Name being the path from step 2 with \amdocl64.dll at the end (or whichever dll version you need or want), and leave the key's data at 0. My key's Name, for example, is C:\Windows\System32\DriverStore\FileRepository\u0336248.inf_amd64_107cc52c701c83d0\B336252\amdocl64.dll
> 
> should now see AMD GPUs!

How I can upvote your answer multiple times ?!!! You saved me so many times !  

Just a quick note: For some strange reason the location of amdocl64.dll and other DLL could change when you install a new version of the AMD drivers :( so what I did:
```
C:\> ethminer -G --list-devices
..... here is an error message that drivers/device is not found etc.....
C:\> echo %ERRORLEVEL%
```
in my case the error level was **2**.   So I fixed the paths in registry to actual location of DLL files and now ethminer working again !!

Thank you !

**Comment by radioresearch** [comment]
Hoping someone can help out here...  I bought an RX570 8GB card the other day, and have installed it in my miner, running Win10 64bit version 20H2.  I am running ethminer v18, and have never had a problem with it as long as I was using NVidia cards.
Long story short:
I installed the AMD card, installed the latest driver pack from AMD's site, and windows was very happy.  The card showed up as fully functional without any issues.  Ethminer 18 does not see it, however.  I found this thread and have tried it, but still no joy from ethminer.  I have created the new DWORD as described with the file location.  I had to create the Khronos key, as it was not in the HKEY_LOCAL_MACHINE\SOFTWARE\ or \SYSWOW6432 listings.
Does anyone have any other ideas?  I could really use the help.  Thanks!

**Comment by SnorreSelmer** [comment]
> "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors".
> 
> Solution for AMD Radeon GPUs not showing up:
> 
> Go to C:\Windows\System32\ and search for amdocl64.dll for OpenCL 2.1, x86_64. (There are also amdocl.dll for OpenCL 2.1, x86; amdocl12cl.dll for OpenCL 1.2, x86; and amdocl12cl64.dll for OpenCL 1.2, x86_64.)
> 
> Look for the most recent file, right-click, click "Properties," and then select and copy the file's Location (which is the path to its directory). (Mine was in a subdirectory of C:\Windows\System32\DriverStore\FileRepository)
> 
> Open regedit, aka the Registry Editor, (e.g. via Windows key+r, and entering regedit)
> 
> Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors
> 
> Create a new DWORD with the Name being the path from step 2 with \amdocl64.dll at the end (or whichever dll version you need or want), and leave the key's data at 0. My key's Name, for example, is C:\Windows\System32\DriverStore\FileRepository\u0336248.inf_amd64_107cc52c701c83d0\B336252\amdocl64.dll
> 
> should now see AMD GPUs!

This is definitely the fix! But with the 21.1.1 AMD-driver, there is no **OpenCL** key under Khronos. You have to add **OpenCL** and **Vendors**, and then add the DWORD as described above.
The keys available under Khronos are **OpenRX/1** and **Vulkan/[Explicit/Implicit]Layers**.

**Comment by mrplants** [comment]
I am so grateful for this thread.  It worked great.  Thank you.

**Comment by SoloSaber** [comment]
hey I just installed the latest AMD 21.2.2 drivers with adrenaline but it doesnt seem to work for me. I don't even have Khronos as a key in HKEY_LOCAL_MACHINE\SOFTWARE.
Can someone please help?

**Comment by SnorreSelmer** [comment]
> hey I just installed the latest AMD 21.2.2 drivers with adrenaline but it doesnt seem to work for me. I don't even have Khronos as a key in HKEY_LOCAL_MACHINE\SOFTWARE.
> Can someone please help?

My post above (https://github.com/ethereum-mining/ethminer/issues/2001#issuecomment-769278718) should provide all the hints you need to solve the issue... (Hint: You might have to create the folders that are missing!)

**Comment by UselessGuru** [comment]
When copying the path make sure you are NOT including the leadung and trailing ".

So the resulting path sholud only look like:

![image](https://user-images.githubusercontent.com/30080938/108436238-5a6ae280-724b-11eb-9702-5701940f4ecf.png)

This IS working with Non-WHQL-Radeon-Software-Adrenalin-2020-21.2.2-Win10-64Bit-Feb11

**Comment by SoloSaber** [comment]
Thanks a lot! I did exactly as you said in the post above.
I fixed it by downgrading my drivers to the recommended version (20.11.2)

**Comment by kheftel** [comment]
> "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors".
> 
> Solution for AMD Radeon GPUs not showing up:
> 
> Go to C:\Windows\System32\ and search for amdocl64.dll for OpenCL 2.1, x86_64. (There are also amdocl.dll for OpenCL 2.1, x86; amdocl12cl.dll for OpenCL 1.2, x86; and amdocl12cl64.dll for OpenCL 1.2, x86_64.)
> 
> Look for the most recent file, right-click, click "Properties," and then select and copy the file's Location (which is the path to its directory). (Mine was in a subdirectory of C:\Windows\System32\DriverStore\FileRepository)
> 
> Open regedit, aka the Registry Editor, (e.g. via Windows key+r, and entering regedit)
> 
> Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors
> 
> Create a new DWORD with the Name being the path from step 2 with \amdocl64.dll at the end (or whichever dll version you need or want), and leave the key's data at 0. My key's Name, for example, is C:\Windows\System32\DriverStore\FileRepository\u0336248.inf_amd64_107cc52c701c83d0\B336252\amdocl64.dll
> 
> should now see AMD GPUs!

thank you, fixed my issue too!

**Comment by vivedesh** [comment]
> > "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors".
> > Solution for AMD Radeon GPUs not showing up:
> > Go to C:\Windows\System32\ and search for amdocl64.dll for OpenCL 2.1, x86_64. (There are also amdocl.dll for OpenCL 2.1, x86; amdocl12cl.dll for OpenCL 1.2, x86; and amdocl12cl64.dll for OpenCL 1.2, x86_64.)
> > Look for the most recent file, right-click, click "Properties," and then select and copy the file's Location (which is the path to its directory). (Mine was in a subdirectory of C:\Windows\System32\DriverStore\FileRepository)
> > Open regedit, aka the Registry Editor, (e.g. via Windows key+r, and entering regedit)
> > Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors
> > Create a new DWORD with the Name being the path from step 2 with \amdocl64.dll at the end (or whichever dll version you need or want), and leave the key's data at 0. My key's Name, for example, is C:\Windows\System32\DriverStore\FileRepository\u0336248.inf_amd64_107cc52c701c83d0\B336252\amdocl64.dll
> > should now see AMD GPUs!
> 
> This is definitely the fix! But with the 21.1.1 AMD-driver, there is no **OpenCL** key under Khronos. You have to add **OpenCL** and **Vendors**, and then add the DWORD as described above.
> The keys available under Khronos are **OpenRX/1** and **Vulkan/[Explicit/Implicit]Layers**.

Thanks a lot, I was confused when I didn't find it. Problem solved!

**Comment by LockBlock-dev** [comment]
> 
> 
> "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors".
> 
> Solution for AMD Radeon GPUs not showing up:
> 
> Go to C:\Windows\System32\ and search for amdocl64.dll for OpenCL 2.1, x86_64. (There are also amdocl.dll for OpenCL 2.1, x86; amdocl12cl.dll for OpenCL 1.2, x86; and amdocl12cl64.dll for OpenCL 1.2, x86_64.)
> 
> Look for the most recent file, right-click, click "Properties," and then select and copy the file's Location (which is the path to its directory). (Mine was in a subdirectory of C:\Windows\System32\DriverStore\FileRepository)
> 
> Open regedit, aka the Registry Editor, (e.g. via Windows key+r, and entering regedit)
> 
> Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors
> 
> Create a new DWORD with the Name being the path from step 2 with \amdocl64.dll at the end (or whichever dll version you need or want), and leave the key's data at 0. My key's Name, for example, is C:\Windows\System32\DriverStore\FileRepository\u0336248.inf_amd64_107cc52c701c83d0\B336252\amdocl64.dll
> 
> should now see AMD GPUs!

You saved me !

**Comment by XboxBedrock** [comment]
i'm having same issue but with RTX 2070 super

**Comment by DigitalThumb** [comment]
> "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors".
> 
> Solution for AMD Radeon GPUs not showing up:
> 
> Go to C:\Windows\System32\ and search for amdocl64.dll for OpenCL 2.1, x86_64. (There are also amdocl.dll for OpenCL 2.1, x86; amdocl12cl.dll for OpenCL 1.2, x86; and amdocl12cl64.dll for OpenCL 1.2, x86_64.)
> 
> Look for the most recent file, right-click, click "Properties," and then select and copy the file's Location (which is the path to its directory). (Mine was in a subdirectory of C:\Windows\System32\DriverStore\FileRepository)
> 
> Open regedit, aka the Registry Editor, (e.g. via Windows key+r, and entering regedit)
> 
> Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors
> 
> Create a new DWORD with the Name being the path from step 2 with \amdocl64.dll at the end (or whichever dll version you need or want), and leave the key's data at 0. My key's Name, for example, is C:\Windows\System32\DriverStore\FileRepository\u0336248.inf_amd64_107cc52c701c83d0\B336252\amdocl64.dll
> 
> should now see AMD GPUs!

Brilliant, thank you

**Comment by BruneXX** [comment]
Hi, I'm experiencing the same issue but in linux, someone know if there's a topic related to the same issue but in that OS?

**Comment by sabotagebeats** [comment]
> Hi, I'm experiencing the same issue but in linux, someone know if there's a topic related to the same issue but in that OS?

make one and reference this issue?

**Comment by preint1** [comment]
> "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors"
> don't have this path, but VULKAN installed. Looks like Ethminer don't see a new registry by AMD
> my rig is AMD rx5700xt and driver ver. 20.9.1. Search by registry do nothing because in Ethminer code seek in old algorithm OpenCL? I'm right? or not.



> > "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors"
> > don't have this path, but VULKAN installed. Looks like Ethminer don't see a new registry by AMD
> > my rig is AMD rx5700xt and driver ver. 20.9.1. Search by registry do nothing because in Ethminer code seek in old algorithm OpenCL? I'm right? or not.
> 
> You could try create the pathways in the registry and point them to the correct amdocl64.dll files. You can use notepad and create the entries like my below sample (replacing the : u0359160.inf_amd64_2abe2598d9a3141f\B358802\ with your own file pathway) and then save file as "filename.reg" and then merge it to your registry:
> 
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors]
> "C:\Windows\System32\DriverStore\FileRepository\u0359160.inf_amd64_2abe2598d9a3141f\B358802\amdocl64.dll"=dword:00000000
> "C:\Windows\System32\DriverStore\FileRepository\u0359160.inf_amd64_2abe2598d9a3141f\B358802\amdocl12cl64.dll"=dword:00000000
> "C:\Windows\System32\DriverStore\FileRepository\u0359160.inf_amd64_2abe2598d9a3141f\B358802\amdocl12cl.dll"=dword:00000000
> "C:\Windows\System32\DriverStore\FileRepository\u0359160.inf_amd64_2abe2598d9a3141f\B358802\amdocl.dll"=dword:00000000

This worked perfectly creating the paths myself in combination with the suggestion from @jgonzis! 
Just wanted to thank you both so much!

**Comment by sabotagebeats** [comment]
I am no longer using this software but it looks like quite a few people have had the issue resolved. I'm going to close the issue.

**Comment by trustfarm-dev** [comment]
@Fordstaa @jgonzis @sabotagebeats 
It is very late, but, I've adds audo registery batchfile to my miner (forked from ethminer) .
Please share it ,
Thanks for your information

Link [amdcladd.bat](https://github.com/tao-foundation/teominer/releases/download/v0.16.3/amdcladd.bat)

**Comment by micaelamaria** [comment]
Do you have a translation of this solution for Ubuntu 20.04?

**Comment by truedat101** [comment]
@micaelamaria it will be a different approach.  AMD still makes the opencl driver available on linux so it should be possible to google for the exact drivers and installation process.

**Comment by The-Memzer** [comment]
> DWORD with the Name being the path from step 2 with \amdocl64.dll at the end (or whichever dll version you need or want), and leave the key's data at 0. My key's Name, for example, is C:\Windows\System32\DriverStore\FileRepository\u0336248.inf_amd64_107cc52c701c83d0\B336252\amdocl64.dll

Linux user here, help lol

**Comment by deepalarm** [comment]
Hi every one

I tried to run opencl on Intel HD Graphics 620 core i3 8th gen
But nothing
Everytime I see

**unrecognized platform intel(r) opencl**

CUDA working normal (second card nvidia geforce mx250)

Opencl not working at all


1. I ve deleted video driver
Including deleted following key, if it was not removed when uninstalling the driver.
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Intel\GFX


2. I ve installed opencl_runtime_18.1_x64

3. Install video driver

4. Update Registry

In folder C:\Windows\System32\DriverStore\FileRepository\, search IntelOpenCL64.dll. You will find something like C:\Windows\System32\DriverStore\FileRepository\<path>\IntelOpenCL64.dll

In key Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors. Create a DWORD with name C:\Windows\System32\DriverStore\FileRepository\<path>\IntelOpenCL64.dll


5. . Run ethminer 

ethminer.exe --list-devices

And nothing 
​

**unrecognized platform intel(r) opencl**


In list only geforce mx250 

Used ethminer 0.18
