### ISSUE TITLE
Can't detect GPU on Macbook Pro

### ISSUE THREAD

**Issue by PearMiner** [ethereum-mining/ethminer#2005]
When I run the command "./ethminer -G --list-devices" it shows:
ethminer 0.19.0-alpha.0
Build: darwin/release/appleclang

Unrecognized platform Apple
Error: No usable mining devices found

**To Reproduce**
1. cd to ethminer folder
2. ./ethminer -G --list-devices or /ethminer -U --list-devices

**Expected behavior**
Will not detect gpu on macbook pro

**Environment (please complete the following information):**
- Operating System: [macOS 10.15.5 catalina]
- Hardware Processor Quad-Core Intel Core i7, GPU: Intel HD Graphics 630 built-in and AMD Radeon Pro 555 PCle
- Ethminer Version [0.19-alpha 0]

**Comment by AndreaLanfranchi** [comment]
MacOS support dropped long time ago.
