### ISSUE TITLE
Most of my jobs blocked

### ISSUE THREAD

**Issue by GuiguiWhite** [ethereum-mining/ethminer#2006]
Hi,

I'm new to mining so it can be a newbie question but I didn't find my answer here.

I'm using Windows 10 with a GTX1060 6GB card and CUDA
It's seems like all or almost all jobs are blocked. I tried changing the pool but nothing changed. I also noticed the <unknown> that other people don't have (sometimes it's written cuda-0)

![Capture](https://user-images.githubusercontent.com/25375341/87865390-09bd9f00-c975-11ea-819e-6b9d9602dffb.JPG)

Is it a problem ?

Thanks for reading my post

**Comment by GuiguiWhite** [comment]
It was a stupid question ...

**Comment by jewusc** [comment]
White is a dick.   They blocked you to steal your $
