### ISSUE TITLE
FS option doesn't work

### ISSUE THREAD

**Issue by Foredoomed** [ethereum-mining/ethminer#201]
FS option doesnt work when the main pool is not available？
It gets stuck trying to connect to the main pool, is this a bug?

**Comment by derubm** [comment]
Did you allready try in non stratum mode ?
i dont know why but getwork or whatever it is called now, works better in any circumstance for me

**Comment by DeadManWalkingTO** [comment]
I believe it's fixed now!

**Comment by smurfy** [comment]
yes, it has been fixed via my pool-manager implementation. In fact, it would be quite easy in the future to add more than one fallback pool. The new implementation does not care how many connections exist
