### ISSUE TITLE
Creating DAG buffer failed: clCreateBuffer: CL_INVALID_BUFFER_SIZE (-61)

### ISSUE THREAD

**Issue by tristenwallace** [ethereum-mining/ethminer#2012]
**Describe the bug**
Creating DAG buffer failed: clCreateBuffer: CL_INVALID_BUFFER_SIZE (-61)
![Screenshot](https://user-images.githubusercontent.com/40002209/89327518-10793100-d65a-11ea-8fc8-c2373cb38736.JPG)

**To Reproduce**
1. Go to "..."
2. Click on "..."
3. Scroll down to "..."

**Expected behavior**

**Screenshots (Optional)**

**Environment (please complete the following information):**
- Operating System: Windows 10
- Hardware: RX 470
- Ethminer Version 0.18 and 0.19
- Ethminer options used

**Additional context**

**Comment by yahia20** [comment]
did you fix it?

**Comment by zhumingyu** [comment]
> **Describe the bug**
> Creating DAG buffer failed: clCreateBuffer: CL_INVALID_BUFFER_SIZE (-61)
> ![Screenshot](https://user-images.githubusercontent.com/40002209/89327518-10793100-d65a-11ea-8fc8-c2373cb38736.JPG)
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to "..."
> 2. Click on "..."
> 3. Scroll down to "..."
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots (Optional)**
> If applicable, add screenshots to help explain your problem.
> 
> **Environment (please complete the following information):**
> 
> * Operating System: Windows 10
> * Hardware: RX 470
> * Ethminer Version 0.18 and 0.19
> * Ethminer options used
> 
> **Additional context**
> Add any other context about the problem here.

hi,guy!did you fix this error?

**Comment by sobertram** [comment]
Strange I am now having the same problem after running for about 5 days straight without issue.
No changes to the system at all. But now unable to start up miner.

```
ethminer 0.18.0
Build: windows/release/msvc

Unrecognized platform Intel(R) OpenCL
 i 21:09:16 main     Configured pool us1.ethermine.org:4444
 i 21:09:16 main     Configured pool us2.ethermine.org:4444
 i 21:09:17 main     Configured pool eu1.ethermine.org:4444
 i 21:09:17 <unknown> Selected pool us1.ethermine.org:4444
 i 21:09:17 <unknown> Negotiation of EthereumStratum/2.0.0 failed. Trying another ...
 i 21:09:17 <unknown> Stratum mode : EthereumStratum/1.0.0 (NiceHash)
 i 21:09:17 <unknown> Established connection to us1.ethermine.org [172.65.218.238:4444]
 i 21:09:17 <unknown> Spinning up miners...
cl 21:09:17 cl-0     Using PciId : 01:00.0 Ellesmere OpenCL 2.0 AMD-APP (3004.8) Memory : 8.00 GB
cl 21:09:17 cl-1     Using PciId : 02:00.0 Ellesmere OpenCL 2.0 AMD-APP (3004.8) Memory : 8.00 GB
cl 21:09:17 cl-2     Using PciId : 04:00.0 Ellesmere OpenCL 2.0 AMD-APP (3004.8) Memory : 8.00 GB
cl 21:09:17 cl-3     Using PciId : 06:00.0 Ellesmere OpenCL 2.0 AMD-APP (3004.8) Memory : 8.00 GB
cl 21:09:17 cl-4     Using PciId : 09:00.0 Ellesmere OpenCL 2.0 AMD-APP (3004.8) Memory : 8.00 GB
cl 21:09:17 cl-5     Using PciId : 0a:00.0 Ellesmere OpenCL 2.0 AMD-APP (3004.8) Memory : 8.00 GB
 i 21:09:17 <unknown> Authorized worker xxx
 i 21:09:17 <unknown> Epoch : 379 Difficulty : 4.29 Gh
 i 21:09:17 <unknown> Job: 8818baab... us1.ethermine.org [172.65.218.238:4444]
cl 21:09:20 cl-1     Generating DAG + Light : 4.02 GB
cl 21:09:20 cl-0     Generating DAG + Light : 4.02 GB
cl 21:09:20 cl-2     Generating DAG + Light : 4.02 GB
cl 21:09:20 cl-3     Generating DAG + Light : 4.02 GB
cl 21:09:20 cl-4     Generating DAG + Light : 4.02 GB
cl 21:09:20 cl-5     Generating DAG + Light : 4.02 GB
cl 21:09:20 cl-5     OpenCL kernel
 i 21:09:20 <unknown> Job: bd82929c... us1.ethermine.org [172.65.218.238:4444]
cl 21:09:21 cl-1     OpenCL kernel
cl 21:09:22 cl-5     Loading binary kernel C:\ethminer-0.18.0-cuda10.0\bin/kernels/ethash_ellesmere_lws128_exit.bin
 i 21:09:23 <unknown> Job: d338ee49... us1.ethermine.org [172.65.218.238:4444]
cl 21:09:24 cl-1     Loading binary kernel C:\ethminer-0.18.0-cuda10.0\bin/kernels/ethash_ellesmere_lws128_exit.bin
cl 21:09:24 cl-5     Build info success:
cl 21:09:24 cl-5     Creating light cache buffer, size: 63.37 MB
cl 21:09:24 cl-5     Creating DAG buffer, size: 3.96 GB, free: 3.98 GB
 **X 21:09:24 cl-5     Creating DAG buffer failed: clCreateBuffer: CL_INVALID_BUFFER_SIZE (-61)**
cl 21:09:24 cl-1     Build info success:
```

**Comment by zhumingyu** [comment]
@sobertram  maybe this is a bug?

**Comment by donewebb** [comment]
The same thing has happened to me, ha anyone found a way to resollve the issue?

Creating DAG buffer failed: clCreateBuffer: CL_INVALID_BUFFER_SIZE (-61)

Thanks,

**Comment by sobertram** [comment]
@zhumingyu no idea. I am guessing the network difficulty might have uncovered a bug here.

**Comment by seven14** [comment]
I had the same issue with my RX570 and RX580 trying to be used. Crashed tonight randomly.

DAG is 4.02G now
cl 23:35:24 cl-0     Generating DAG + Light : 4.02 GB
cl 23:35:24 cl-1     Generating DAG + Light : 4.02 GB


ethminer 0.18.0
Build: linux/release/gnu

CUDA Error : No CUDA driver found
 Id Pci Id    Type Name                          CUDA SM  CL    Total Memory  Cl Max Alloc  Cl Max W.Grp
--- --------- ---- ----------------------------- ---- --- ----  ------------  ------------  ------------
  0 01:00.0   Gpu  Ellesmere                              Yes        7.80 GB       3.95 GB      256.00 B
  1 02:00.0   Gpu  Ellesmere                              Yes        7.98 GB       3.95 GB      256.00 B
  2 06:00.0   Gpu  gfx1010                                Yes        7.98 GB       7.73 GB      256.00 B
  3 09:00.0   Gpu  gfx1010                                Yes        7.98 GB       7.73 GB      256.00 B

I added "--cl-devices 2 3" and I am back to mining.

**Comment by sobertram** [comment]
I downloaded a new miner, Claymore, and it works with claymore.

@seven14 tried specifying devices and same issue. I will keep an eye on this but for now I guess its claymore.

**Comment by seven14** [comment]
I just realized I have further issues as well, since there is no gfx1010 kernel, I am seeing horrible hashrate.

m 23:47:13 ethminer 0:00 A0 7.13 Mh - cl0 **3.55** 46C 14% A0, cl1 **3.58** 45C 14% A0

**Comment by zhumingyu** [comment]
@sobertram what's the devfee of Claymore?

**Comment by seven14** [comment]
1%, but I thought it was going away soon.
We are at Epoch : 379

This version supports up to and including #384 epoch.
https://2miners.com/blog/claymores-ethereum-miner-stops-working-best-alternatives/

**Comment by SeLu94** [comment]
I have fixed it downloading the latest beta version of the ethminer continuous integration site:
https://ci.appveyor.com/project/ethereum-mining/ethminer/builds/36481676/job/5nu2r6uus5o80igl/artifacts
It removes the 4gb dag limitation.
Maybe it have undetected bugs, so up to date to a new release.

**Comment by zhumingyu** [comment]
> I have fixed it downloading the latest beta version of the ethminer continuous integration site:
> https://ci.appveyor.com/project/ethereum-mining/ethminer/builds/36481676/job/5nu2r6uus5o80igl/artifacts
> It removes the 4gb dag limitation.
> Maybe it have undetected bugs, so up to date to a new release.

thx very much!

**Comment by AndreaLanfranchi** [comment]
OpenCL (not ethminer) imposes a limit on the sizes of memory buffers on GPUs regardless the effective size of available memory
From the snapshot posted above you see :
```
Unrecognized platform Intel(R) OpenCL
CUDA Error : No CUDA driver found
 Id Pci Id    Type Name                          CUDA SM  CL    Total Memory  Cl Max Alloc  Cl Max W.Grp
--- --------- ---- ----------------------------- ---- --- ----  ------------  ------------  ------------
  0 01:00.0   Gpu  Ellesmere                              Yes        8.00 GB       3.95 GB      256.00 B
  1 02:00.0   Gpu  Ellesmere                              Yes        8.00 GB       3.95 GB      256.00 B
```
Those two cards have 8GB ram **but can allocate only 3.95GB per single buffer**.
Actual source code works-around the limitation by allocating DAG in two chunks **but you have to build the binary on you own**

**Comment by emnbdx** [comment]
> I have fixed it downloading the latest beta version of the ethminer continuous integration site:
> https://ci.appveyor.com/project/ethereum-mining/ethminer/builds/36481676/job/5nu2r6uus5o80igl/artifacts
> It removes the 4gb dag limitation.
> Maybe it have undetected bugs, so up to date to a new release.

🙏 This works for me too. But this new release detect Intel GPU.
So you have to identity and ignore them

For example
```
ethminer.exe --list-devices
ethminer 0.19.0-12+commit.beaeb001
Build: windows/release/msvc

CUDA Error : No CUDA driver found
 Id Pci Id    Type Name                          CUDA SM  CL    Total Memory  Cl Max Alloc  Cl Max W.Grp
--- --------- ---- ----------------------------- ---- --- ----  ------------  ------------  ------------
  0 01:00.0   Gpu  Ellesmere                              Yes        8.00 GB       3.95 GB      256.00 B
  1 04:00.0   Gpu  Ellesmere                              Yes        8.00 GB       3.95 GB      256.00 B
  2 05:00.0   Gpu  Ellesmere                              Yes        8.00 GB       3.95 GB      256.00 B
  3 Intel GPU 0.0Gpu  Intel(R) HD Graphics 510               Yes        1.55 GB     793.95 MB      256.00 B
  4 Intel GPU 0.1Gpu  Intel(R) HD Graphics 510               Yes        1.55 GB     793.95 MB      256.00 B
```
So I add **--cl-devices 0 1 2** at end of my ethminer running script

**Comment by zhumingyu** [comment]
> I have fixed it downloading the latest beta version of the ethminer continuous integration site:
> https://ci.appveyor.com/project/ethereum-mining/ethminer/builds/36481676/job/5nu2r6uus5o80igl/artifacts
> It removes the 4gb dag limitation.
> Maybe it have undetected bugs, so up to date to a new release.

thx guy! are  there any solutions for ubuntu?

**Comment by emnbdx** [comment]
As written in the README there are no artifact on unix CI so you have to build it
https://github.com/ethereum-mining/ethminer#build

**Comment by AndreaLanfranchi** [comment]
> If you are on windows @AndreaLanfranchi is also a good solution but more complicated, why build by yourself when there is a CI pipeline !

Cause the pipeline builds only up to CUDA 10.x binaries.
CUDA 11.x not officially supported

**Comment by danizaharie** [comment]
I have solved installing pheonixminer on ethos:

bash <(curl -s https://raw.githubusercontent.com/cynixx3/third-party-miner-installer-for-ethos/master/miner-manager) phoenixminer install

**Comment by artmandon** [comment]
> I have solved installing pheonixminer on ethos:
> 
> bash <(curl -s https://raw.githubusercontent.com/cynixx3/third-party-miner-installer-for-ethos/master/miner-manager) phoenixminer install

I tried your fix, but it didn't work for me. I was use ethminer before, and have never used phoenixminer.

What does your local.conf file look like?

**Comment by ithahn** [comment]
Same issue appeared to me today on Windows:
cl 15:21:13 cl-1     Build info success:
cl 15:21:13 cl-1     Creating light cache buffer, size: 63.37 MB
cl 15:21:13 cl-1     Creating DAG buffer, size: 3.96 GB, free: 3.98 GB
 X 15:21:13 cl-1     Creating DAG buffer failed: clCreateBuffer: CL_INVALID_BUFFER_SIZE (-61)

Can someone guide me to fix this on Windows please?

I  have read that using version 19 beta to fix this issue but not sure where to find the executable.

**Comment by emnbdx** [comment]
@artmandon don't install phoenix there are devs fees...

@ithahn look at my post ;) ⬆️

**Comment by zhumingyu** [comment]
when i build it , getting stuck  :
-- [cable ] Cable 0.2.14 initialized
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [cable ] Build type: Release
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] Calculating Config-SHA1
-- [hunter] HUNTER_ROOT: /home/zjhxmjl/.hunter
-- [hunter] [ Hunter-ID: 4b894e1 | Toolchain-ID: 5e9e5fe | Config-ID: cb395ce ]
-- [hunter] BOOST_ROOT: /home/zjhxmjl/.hunter/_Base/4b894e1/5e9e5fe/cb395ce/Inst                  all (ver.: 1.66.0)
what's wrong?

**Comment by ithahn** [comment]
> @artmandon don't install phoenix there are devs fees...
> 
> @ithahn look at my post ;) ⬆️

Many thanks!

The executable inside this file works for me nicely without any additonal changes.
https://ci.appveyor.com/api/buildjobs/5nu2r6uus5o80igl/artifacts/build%2Fethminer-0.19.0-12%2Bcommit.beaeb001-cuda8.0-windows-amd64.zip

**Comment by danizaharie** [comment]
> > I have solved installing pheonixminer on ethos:
> > bash <(curl -s https://raw.githubusercontent.com/cynixx3/third-party-miner-installer-for-ethos/master/miner-manager) phoenixminer install
> 
> I tried your fix, but it didn't work for me. I was use ethminer before, and have never used phoenixminer.
> 
> What does your local.conf file look like?

**/home/ethos/local.conf**

globalminer phoenixminer
maxgputemp 87
stratumproxy enabled
globalfan 80
safevolt enabled
globalpowertune 2
autoreboot 99999
custompanel xxx
loc 4948df rig_name
lockscreen enabled
cor 4948df 1100 1100 1100 1100 1100 1100 1100 1040 1100 1100 1100 1100 1100
mem 4948df 2220 2220 2220 2220 2220 2140 2220 2100 2220 2220 2220 2220 2220
vlt 4948df 850 850 850 850 850 860 850 820 850 850 850 850 850

proxywallet 0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/rig_name/youremail@gmail.com
proxypool1 eth-eu1.nanopool.org:9999
proxypool2 eth-eu2.nanopool.org:9999
flags

**Comment by artmandon** [comment]
> > @artmandon don't install phoenix there are devs fees...
> > @ithahn look at my post ;) ⬆️
> 
> Many thanks!
> 
> The executable inside this file works for me nicely without any additonal changes.
> https://ci.appveyor.com/api/buildjobs/5nu2r6uus5o80igl/artifacts/build%2Fethminer-0.19.0-12%2Bcommit.beaeb001-cuda8.0-windows-amd64.zip

I got the file, thanks, but I am running ethos from a usb flash drive and am not sure how to use the bash terminal to get the file onto my ethos usb flash drive and then install the file to get things working again. i have tried to simply "update-miner ethminer" but that did nothing to resolve the problem.

**Comment by aolivac** [comment]
> I have solved installing pheonixminer on ethos:
> 
> bash <(curl -s https://raw.githubusercontent.com/cynixx3/third-party-miner-installer-for-ethos/master/miner-manager) phoenixminer install

Thanks!
Worked perfectly.

cheers,
A.

**Comment by artmandon** [comment]
> > > I have solved installing pheonixminer on ethos:
> > > bash <(curl -s https://raw.githubusercontent.com/cynixx3/third-party-miner-installer-for-ethos/master/miner-manager) phoenixminer install
> > 
> > 
> > I tried your fix, but it didn't work for me. I was use ethminer before, and have never used phoenixminer.
> > What does your local.conf file look like?
> 
> **/home/ethos/local.conf**
> 
> globalminer phoenixminer
> maxgputemp 87
> stratumproxy enabled
> globalfan 80
> safevolt enabled
> globalpowertune 2
> autoreboot 99999
> custompanel xxx
> loc 4948df rig_name
> lockscreen enabled
> cor 4948df 1100 1100 1100 1100 1100 1100 1100 1040 1100 1100 1100 1100 1100
> mem 4948df 2220 2220 2220 2220 2220 2140 2220 2100 2220 2220 2220 2220 2220
> vlt 4948df 850 850 850 850 850 860 850 820 850 850 850 850 850
> 
> proxywallet 0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/rig_name/youremail@gmail.com
> proxypool1 eth-eu1.nanopool.org:9999
> proxypool2 eth-eu2.nanopool.org:9999
> flags

I tried it with your same local.conf, but I keep getting the same errors below:

                                                                                                                                                                        
Phoenix Miner 5.3b Linux/gcc - Release build                                                                                                                            
--------------------------------------------                                                                                                                            
                                                                                                                                                                        
Unknown OpenCL driver version! Hashrate and stale shares may suffer                                                                                                     
OpenCL platform: OpenCL 2.0 AMD-APP (1800.11)                                                                                                                           
Available GPUs for mining:                                                                                                                                              
GPU1: AMD Radeon (TM) R9 390 Series  (pcie 1), OpenCL 2.0, 7.9 GB VRAM, 40 CUs                                                                                          
GPU2: AMD Radeon (TM) R9 390 Series  (pcie 4), OpenCL 2.0, 7.9 GB VRAM, 40 CUs                                                                                          
GPU3: AMD Radeon (TM) R9 390 Series  (pcie 5), OpenCL 2.0, 7.9 GB VRAM, 40 CUs                                                                                          
Unable to initialize AMD hardware monitor                                                                                                                               
Eth: the pool list contains 2 pools (2 from command-line)                                                                                                               
Eth: primary pool: eth-eu1.nanopool.org:9999                                                                                                                            
Starting GPU mining                                                                                                                                                     
Eth: Connecting to ethash pool eth-eu1.nanopool.org:9999 (proto: EthProxy)                                                                                              
Listening for CDM remote manager at port 3333 in read-only mode                                                                                                         
Eth: Connected to ethash pool eth-eu1.nanopool.org:9999 (51.15.39.52)                                                                                                   
Eth: New job #a825a992 from eth-eu1.nanopool.org:9999; diff: 10000MH                                                                                                    
GPU1: Starting up... (0)                                                                                                                                                
GPU1: Generating ethash light cache for epoch #379                                                                                                                      
GPU2: Starting up... (0)                                                                                                                                                
GPU3: Starting up... (0)                                                                                                                                                
Eth: New job #ab157eab from eth-eu1.nanopool.org:9999; diff: 10000MH                                                                                                    
Light cache generated in 2.6 s (24.6 MB/s)                                                                                                                              
GPU1: Free VRAM: 7.913 GB; used: 0.006 GB                                                                                                                               
GPU1: Disabling DAG pre-allocation (not enough VRAM)                                                                                                                    
GPU1: Allocating DAG for epoch #379 (3.96) GB                                                                                                                           
GPU1: Allocating buffers failed with: clCreateBuffer (-61).                                                                                                             
Fatal error detected. Restarting.                                                                                                                                       
GPU2: Free VRAM: 7.921 GB; used: 0.007 GB                                                                                                                               
GPU2: Disabling DAG pre-allocation (not enough VRAM)                                                                                                                    
GPU2: Allocating DAG for epoch #379 (3.96) GB                                                                                                                           
GPU2: Allocating buffers failed with: clCreateBuffer (-61).                                                                                                             
GPU3: Free VRAM: 7.921 GB; used: 0.007 GB                                                                                                                               
GPU3: Disabling DAG pre-allocation (not enough VRAM)                                                                                                                    
GPU3: Allocating DAG for epoch #379 (3.96) GB                                                                                                                           
GPU3: Allocating buffers failed with: clCreateBuffer (-61).                                                                                                             
Eth speed: 0.000 MH/s, shares: 0/0/0, time: 0:00                                                                                                                        
GPUs: 1: 0.000 MH/s (0) 2: 0.000 MH/s (0) 3: 0.000 MH/s (0)                                                                                                             
Eth: New job #24368525 from eth-eu1.nanopool.org:9999; diff: 10000MH

**Comment by artmandon** [comment]
The weird thing is, my rigs with NVIDIA cards never stopped a beat, but my rigs with AMD cards all died at the same time, and I haven't been able to get any of them up and running again.  All my rigs were running ethos 1.3.3.  Nothing changed, but then the AMD carded rigs all stopped working with these DAG errors (not enough VRAM) even though every card has 8GB on board.

**Comment by AndreaLanfranchi** [comment]
> The weird thing is, my rigs with NVIDIA cards never stopped a beat, but my rigs with AMD cards all died at the same time, and I haven't been able to get any of them up and running again. All my rigs were running ethos 1.3.3. Nothing changed, but then the AMD carded rigs all stopped working with these DAG errors (not enough VRAM) even though every card has 8GB on board.

@artmandon the issue only affects OpenCL implementation due to a limitation in **OpenCL** itself.
NVIDIA Cards running in CUDA mode are not affected: should you run them in OpenCL mode they had the same problem.
Also the error reports "IMVALID BUFFER SIZE" ... not, as you claimed, not enough VRAM.

**Comment by artmandon** [comment]
> > The weird thing is, my rigs with NVIDIA cards never stopped a beat, but my rigs with AMD cards all died at the same time, and I haven't been able to get any of them up and running again. All my rigs were running ethos 1.3.3. Nothing changed, but then the AMD carded rigs all stopped working with these DAG errors (not enough VRAM) even though every card has 8GB on board.
> 
> @artmandon the issue only affects OpenCL implementation due to a limitation in **OpenCL** itself.
> NVIDIA Cards running in CUDA mode are not affected: should you run them in OpenCL mode they'd have the same problem.
> Also the error reports "IMVALID BUFFER SIZE" ... not, as you claimed, not enough VRAM.

If you had actually looked at the output I provided you would have seen this:
"GPU1: Disabling DAG pre-allocation (not enough VRAM)"
...
"GPU2: Disabling DAG pre-allocation (not enough VRAM)"
...
"GPU3: Disabling DAG pre-allocation (not enough VRAM)"

So perhaps you should take your beef up with the author of the code themselves. Also, if you're going to be "that guy" at least spell "IMVALID BUFFER SIZE" correctly.

I was hoping someone had some insights as to why the phoenixminer install route seems to have worked for some on their ethos rigs, but has not worked for me.

**Comment by AndreaLanfranchi** [comment]
@artmandon 
`GPU1: Disabling DAG pre-allocation (not enough VRAM)` **is not an error** but instead is a lack of "optimization". Basically you can mine at nominal speed but when the epoch changes it takes a little longer to rebuild the DAG as it hasn't been preallocated.
Sorry for the mispell of IMVALID buffer.

This discussion is degenerating to phoenixminer and ethos ... closing. Refer to appropriate support channels for both.
Regards.
