### ISSUE TITLE
The miner doesn't mine on full power

### ISSUE THREAD

**Issue by PvtSec** [ethereum-mining/ethminer#2016]
**Description**
The miner doesn't utilize the full power of GPU for daggerhashimoto nicehash
**Steps to Reproduce**
```wget https://github.com/ethereum-mining/ethminer/releases/download/v0.18.0/ethminer-0.18.0-cuda-9-linux-x86_64.tar.gz -O tar.gz```
```tar -xvf tar.gz```
```sudo ./ethminer -P stratum2+tcp://ADDRESS.digger@daggerhashimoto.br.nicehash.com:3353```
```nvidia-smi | grep W```
***Output***
```| N/A   72C    P0   134W / 250W |   8344MiB / 16280MiB |    100%      Default |```

**Expected behavior**
The miner was expected to go on full throttle
and output expected was
```| N/A   72C    P0   240W / 250W |   8344MiB / 16280MiB |    100%      Default |```

**Environment:**
- Operating System: Linux
- Hardware : Nvidia Tesla P100-PCIE-16GB
- Ethminer Version 0.18.0-cuda-linux

**Comment by Josevora** [comment]
Hello,
Tou mean the Wattage Metter!?
Why should it go full throttle on that? The point is to use the less power as possible, not the oposit...
Performance wise, you have a cap on each card based on frequency, latency, number of cores, etc... As long as you stay close to that limit, you are good... Power wise, the power used is resultant from the VOLTAGE applyed to the core and memory, etc... 
If you are able to apply less voltage and still be close tho that theoretical limit, great... What matters is performance/watt not watt/card... 
Hope this responded to your question...

**Comment by PvtSec** [comment]
If it could use more power, can't the card generate higher hashrate?

**Comment by Josevora** [comment]
No, it will use more power, but it will work on the same amount of data per time... So no gains in performance!
