### ISSUE TITLE
gtx 1070 average utility is about 85

### ISSUE THREAD

**Issue by shyandsy** [ethereum-mining/ethminer#202]
why gtx 1070 average utility is about 85% ?

the command line i used shows below
ethminer --farm-recheck 200 -G -F http://127.0.0.1:8080/rig1 --cuda-parallel-hash 8

**Comment by srxa** [comment]
You should try:
ethminer --farm-recheck 2000 -U -F http://127.0.0.1:8080/rig1

-G option is for AMD, -U is for Nvidia, leave cuda-parallel-hash at default.

**Comment by simonkern** [comment]
GTX 1070 here too, I can not confirm this. My GPU has a utilization between 99% and 100% alle the time.

**Comment by jimmykl** [comment]
My 1070s are ~98-100% too. @shyandsy could you try with the default ```--cuda-parallel-hash 4``` and see if it increases utilisation?

**Comment by derubm** [comment]
also try : 
		setx GPU_FORCE_64BIT_PTR 0
		setx GPU_MAX_HEAP_SIZE 100
		setx GPU_USE_SYNC_OBJECTS 1
		setx GPU_MAX_ALLOC_PERCENT 100
		setx GPU_SINGLE_ALLOC_PERCENT 100

**Comment by shyandsy** [comment]
@jimmykl @simonkern @derubm 
I used the following configuration as start script now, the utilization has increase to 88% average.

But still not 98% average.  are there any other suggestion?  

```php
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

ethminer --farm-recheck 2000 -U -F http://127.0.0.1:8080/rig1 --cuda-parallel-hash 4
```

**Comment by dafyk** [comment]
@shyandsy make sure your cards are running in P0 state (looks like yours are running at P2)

**Comment by shyandsy** [comment]
first time to know there is state px for gpu

How to do that on win10？

发自我的 iPhone

**Comment by derubm** [comment]
To my knowledge Not possible with 10x series, will Check when iam at home

**Comment by derubm** [comment]
To my knowledge Not possible with 10x series, will Check when iam at home

**Comment by shyandsy** [comment]
thank u



发自我的 iPhone

**Comment by dafyk** [comment]
You can use [Nvidia Profile Inspector](https://ci.appveyor.com/project/Orbmu2k/nvidiaprofileinspector/build/artifacts) from @Orbmu2k to turn **OFF** `CUDA - force P2 state` setting in section `5 - Common`. Its turned ON by default as shown in this [image](http://imgur.com/dMAu1T3). **Be ware that other versions than 2.1.3.9 of this utility doesn't have this setting available!**

There is also very handy GUI utility [Nvidia Inspector](http://www.guru3d.com/files-details/nvidia-profile-inspector-download.html) from the same author which also accepts command line arguments. I am using it to overclock and monitor my cards. You can also check the P state of cards. You want to run your cards at P0 state.
To overclock my cards I am using this command:
`nvidiaInspector.exe -setPowerTarget:0,XX -setBaseClockOffset:0,0,"-200" -setMemoryClockOffset:0,0,100 -setTempTarget:0,0,75 -setFanSpeed:0,100`

- setPowerTarget:0,XX - replace XX with your values, lowers total GPU power usage (depends on card and can affect miner performance, you need to experiment to find settings for your cards, i am running my cards at 125W limit)
- setBaseClockOffset:0,0,"-200" - downclock GPU core (affects heat production, lower is better)
- setMemoryClockOffset:0,0,100 - overclock memory by +100MHz (most important for miner performance, gtx1070 can go up to +1000MHz but its rare and depends on manufacturing quality, you will probably be fine around 400-600MHz)
- setTempTarget:0,0,75 - lower temperature target (affects voltages and heat production. on some cards can also affect miner perfomance)
- setFanSpeed:0,100 - set fan speed to 100% (to keep everything cool)

This single line command affects first card only (with index 0) to see all command line arguments run: 
`nvidiaInspector.exe /?`

> Note: nvidiaInspector.exe has arguments to set/force P states of the card, but if you dont 
> turn off "CUDA - force P2 state" it wont work. This is also the main problem when you run on linux, I didnt yet find way how to turn off this setting which by default downlocks memory by 200MHz when running cuda apps
> 

To run monitors only run:
`nvidiaInspector.exe -showMonitoring`

**Comment by shyandsy** [comment]
i switched to ubuntu 16.

all works good now
six gtx 1070 gpu，100%



发自我的 iPhone

**Comment by michaeljohnbennett** [comment]
I know nvidia-inspector is windows only but @shyandsy how did you configure your cards in ubuntu to get 100%?

I have used the coolbits flags on the X11 config to get the extra overclocking and thermal/fan controls and configure them by a bash script. Is there something else we can do there to disable the P2?

I can see on the UI it hits the P2 state immediately when ethminer starts up.

**Comment by DeadManWalkingTO** [comment]
Try
[NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW)

For the best mining hashrate choose from sector "5 - Common":
- CUDA - Force P2 State (Set to "Off")
- Power managment mode (Set to "Prefer maximum performance")
