### ISSUE TITLE
Ethminer on Macos don't runs for a SIGSEGV error - any options?

### ISSUE THREAD

**Issue by macperlita** [ethereum-mining/ethminer#2020]
**Is your feature request related to a problem? Please describe.**
Ethminer on Macos don't runs for a SIGSEGV error - any options?

**Describe the solution you'd like**
I hope you can help me ;)

**Describe alternatives you've considered**

**Additional context**

**Comment by vasilo3001** [comment]
my command: 

`./ethminer -U -P stratum1+tcp://ETHADDRESS@eu1.ethermine.org:14444`

tried port 4444 as well, tried different regions
I also tried v18 and v19

I have the same issue:
<img width="989" alt="Screen Shot 2020-08-28 at 12 35 53" src="https://user-images.githubusercontent.com/26862784/91546398-0aa9ff00-e92b-11ea-941e-362db8f8e9a4.png">

**Comment by AndreaLanfranchi** [comment]
We don't support Mac since long time now.
Sorry
