### ISSUE TITLE
Bad URI : regex_error

### ISSUE THREAD

**Issue by djdejawu** [ethereum-mining/ethminer#2025]
Describe the bug
Build from source 0.18.0 release, now on 0.19.0-alpha same problems

To Reproduce

git pull
git checkout v0.18.0
mkdir build; cd build; cmake3 ..
cmake3 --build .
Run ethminer with -P stratum://0x39383....39393.workername@yourminingpool.net:39393 (your stratum port)
Expected behavior
Normal startup with stratum URI

Environment:

Operating System: CentOS 7.8
Ethminer Version [0.18.0]
Ethminer options used -P stratum://

**Comment by AndreaLanfranchi** [comment]
Without actual log and real stratum connection string is impossible to determine whether is an issue or a badly formatted string.
Feel free to comment again on this. Will eventually reopen
