### ISSUE TITLE
[CUDA error in func] + [No OpenCL platforms found] 1660 Super Win10

### ISSUE THREAD

**Issue by Chewey28** [ethereum-mining/ethminer#2026]
Hey!
I'm a mining newbee, and trying to fix an issues at my early start.
Win10 + GIGABYTE 1660 Super 6GB  with ryzen 7 and 32gb memory. Already tried a Claymore where I get a "Pool sent wrong data, cannot set epoch" and disconnects, while using the latest version of Claymore and already reinstalled the last version of Nvidia drivers. Also I've tried to install dedicated nvidia CUDA drivers, but still nothing.

With ethminer I faced with errors like "No OpenCL platforms found" and "Cuda error in func.."
![image](https://user-images.githubusercontent.com/70637528/92025859-d2f6e900-ed68-11ea-8394-463089985739.png)

Here are the versions of ethminer I've tried:
![image](https://user-images.githubusercontent.com/70637528/92026465-c030e400-ed69-11ea-92de-db715cbf0ab3.png)

Could you please help me with this kind of errors?

**Comment by Josevora** [comment]
Hello,
I'm not part of the team, but I'll try to help... 
Check on the docs if there's Reference to what Nvidia divers are optimal to use... 
Then Uninstaller completely the current Nvidia drivers using DDU! Use it on safe mode!
Then install the recommended drivers... 
Try again then post results here!

PS - next time tell us more about your setup, windows or Linux, I had to check the print to find out...

**Comment by Chewey28** [comment]
> Hello,
> I'm not part of the team, but I'll try to help...
> Check on the docs if there's Reference to what Nvidia divers are optimal to use...
> Then Uninstaller completely the current Nvidia drivers using DDU! Use it on safe mode!
> Then install the recommended drivers...
> Try again then post results here!
> 
> PS - next time tell us more about your setup, windows or Linux, I had to check the print to find out...

Hi,
Thanks for suggesting! I uninstall drivers using DDU, and install the latest version of Nvidia driver 452.06 + ethminer-0.19.0-alpha.0-cuda10.0-windows-amd64. And now it looks like that:
![image](https://user-images.githubusercontent.com/70637528/92046631-ab654800-ed8b-11ea-9213-b20cf26653e2.png)
I guess it's OK right now?)

**Comment by Josevora** [comment]
I don't know if that card can do more... But play around with frequency and power... Try to lower the power and up the frequency on the memory, lower the frequency on the core... You will get better hashrate and lower consumption, but not by any crazy amount
