### ISSUE TITLE
Linux build fails with "Invalid value for the '-j' option, valid values are 1 through 256."

### ISSUE THREAD

**Issue by davilizh** [ethereum-mining/ethminer#203]
@chfast # 
[ 75%] Performing build step for 'Boost-system'
Invalid value for the '-j' option, valid values are 1 through 256.
gmake[2]: [Boost-system-prefix/src/Boost-system-stamp/Boost-system-build] Error 1
gmake[1]: [CMakeFiles/Boost-system.dir/all] Error 2
gmake: * [all] Error 2

This can be avoided by adding "-DHUNTER_JOBS_NUMBER= xxx" to the cmake command
So I would suggest adding this command to the Wiki.

**Comment by DeadManWalkingTO** [comment]
Any news here?

**Comment by chfast** [comment]
This should be a workaround: https://github.com/ethereum-mining/ethminer/pull/989.
