### ISSUE TITLE
Install Ethminer 

### ISSUE THREAD

**Issue by satyamakgec** [ethereum-mining/ethminer#204]
i am very new to mining activity , i want to install the ethminer in ubuntu 16.04 LTS without use of any hardware . so I need a proper guidance to install it and run it with private ethereum network and join it with mining pool build using open-ethereum-pool . please help me to get this done .

System Configuration
Os -Ubuntu 16.04 LTS
RAM - 4 GB

**Comment by chfast** [comment]
Then ethminer is not for you because it only supports GPU mining. Ethereum clients like geth and eth have CPU mininig built in.

Anyway, to install ethminer you just have to download binary from Releases.

**Comment by satyamakgec** [comment]
then i have no need of ethminer or any other to add miner in open-ethereum-pool to test the functionality
. How i create multiple miners from a geth node . It may be a silly question but it may helpful to me to get understand

Thanks

**Comment by chfast** [comment]
As the protocol has not changed, you can try find some old build of ethminer or eth that supports `-F` farm option with CPU.
