### ISSUE TITLE
Nanopool workers not visible (no rating), but hashrate and shares registered properly.

### ISSUE THREAD

**Issue by lss4** [ethereum-mining/ethminer#2044]
**Describe the bug**
Using ethminer with Nanopool, while hashrate and shares are being registered properly, the miners don't show up in the worker list despite I've set the worker name (and later on a passcode) on each of the systems that I use to mine.

However, the hashrate and shares do register properly and I'm indeed getting ETHs there. It's just that workers not visible there would not be rated and thus I would not be able to change my minimum payout as that operation requires a visible worker with sufficient rating under the specified passcode/email.

Not sure if anyone have reported this before, but I saw [this on reddit](https://www.reddit.com/r/EtherMining/comments/7t7kle/nanopool_not_showing_workers/) which seemed to be similar. Do I need to set some additional parameters to get this working? (NOTE: The arguments mentioned there appear to be outdated and not really compatible with the recent ethminer versions anymore)

Even the latest in the release (ethminer 0.19 alpha) doesn't work either.

By the way, how is ethminer's compatibility with pools nowadays? I've tried Ethermine, Sparkpool and f2pool. None of these pools worked, complaining about some protocol-related errors. Eventually I found Nanopool which worked with ethminer, and my shares accepted, just that workers don't show up.

**To Reproduce**
Use the needed parameters to run ethminer to mine on Nanopool and that's it.

**Expected behavior**
The workers should be visible on the Nanopool dashboard, along with the hashrate and shares.

**Screenshots (Optional)**
OS: Windows 10 and Manjaro Linux
Ethminer: 0.18 on Linux, 0.19 alpha on Windows
Hardware: Various
Options used: I just set a 9999 `farm-retries` count instead of the default 3 to prevent the miner from exiting when the pool goes down (which happens intermittently). The rest follows Nanopool's and ethminer's instructions. Need to use stratum+tcp because stratum+ssl currently fails due to expired certificates.

**Additional context**
The current situation with ethminer is uncertain as it's not really an officially supported miner on Nanopool (they use [their](https://github.com/nanopool/genoil-ethereum) [own](https://github.com/nanopool/nanominer) ones), and Claymore is currently recommended on most pools that I currently know, including the ones that I failed to get working with ethminer.

**Comment by toynn** [comment]
Had similar issue with different pool until I read this help doc regarding format for pool connection. You'll need to do escaping or back-ticks to handle periods "." in the connection string. What's needed depends on what OS and how the command is run and the pool. I found that in a Windows batch file I needed to double escape the period,

Check out the examples: 
https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md

**Comment by lss4** [comment]
> Had similar issue with different pool until I read this help doc regarding format for pool connection. You'll need to do escaping or back-ticks to handle periods "." in the connection string. What's needed depends on what OS and how the command is run and the pool. I found that in a Windows batch file I needed to double escape the period,
> 
> Check out the examples:
> https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md

Have you solved the issue? It's just that I wanted to make it pay out every 0.1 ETH instead of 0.2 ETH so as to access what I've mined early. Without a properly rated worker I won't be able to configure this.

Does anyone have a working example? I'm still unable to get everything understood with existing information, and given that ethminer has changed, some old posts and examples are not valid anymore.

**Comment by LeKristapino** [comment]
Thanks @lss4 Your example worked - Was fighting with this for some time, since this kind of example was not mentioned in the POOL_EXAMPLES_ETH.md file
