### ISSUE TITLE
Release Deceptive Site ?

### ISSUE THREAD

**Issue by AlexeySergeyev** [ethereum-mining/ethminer#205]
Hello,

I'm trying to download of ethminer release (Linux,Windows), but my Firefox is warning me:
------------------------------------------------------------------------
This web page at github-production-release-asset-2e65be.s3.amazonaws.com has been reported as a deceptive site and has been blocked based on your security preferences.
-----------------------------------------------------------------
Is this site was hacked ?

**Comment by derubm** [comment]
False warning, you might need to set your antivirus temprary off for download, and give the mining folder a exclusion.

**Comment by chfast** [comment]
Confirmed by already gone.
