### ISSUE TITLE
Bad pool example

### ISSUE THREAD

**Issue by ibmua** [ethereum-mining/ethminer#2052]
Can't get the miner to supply name and email to nanopool. As per https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md
```
-P stratum1+tcp://ETH_WALLET@eth-eu2.nanopool.org:9999/WORKERNAME/EMAIL
```
-- this example is completely wrong. This is what I'm getting:

```
ethminer 0.19.0-7+commit.66186f1b.dirty
Build: linux/release/gnu

 i 16:13:14 ethminer Configured pool gmail.com:0
 i 16:13:14 ethminer Selected pool gmail.com:0
 X 16:13:15 ethminer Error  216.58.215.101:0 [ Operation canceled ]
 X 16:13:15 ethminer Error  [2a00:1450:401b:808::2005]:0 [ Network is unreachable ]
 X 16:13:15 ethminer No more IP addresses to try for host: gmail.com
 i 16:13:15 ethminer Disconnected from gmail.com:0
 i 16:13:15 ethminer No connection. Suspend mining ...
 i 16:13:15 ethminer Selected pool gmail.com:0
 X 16:13:16 ethminer Error  216.58.215.101:0 [ Operation canceled ]
 X 16:13:16 ethminer Error  [2a00:1450:401b:808::2005]:0 [ Network is unreachable ]
 X 16:13:16 ethminer No more IP addresses to try for host: gmail.com
 i 16:13:16 ethminer Disconnected from gmail.com:0
 i 16:13:16 ethminer No connection. Suspend mining ...
 i 16:13:16 ethminer Selected pool gmail.com:0
^C i 16:13:17 main     Got interrupt ...
 i 16:13:17 main     Terminated!
```

So it actually tries to mine on gmail.com because my email address is @gmail.com

**Comment by xgnom666x** [comment]
https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md

> Anything you put in the Path part must be Url Encoded thus, for example, @ must be written as %40

**Comment by ibmua** [comment]
Does launch this way, but seems like nanopool doesn't ignores WORKERNAME and EMAIL.

**Comment by lss4** [comment]
I had the same issue on nanopool (see #2044).

This is the right way to write the URL.
`stratum+tcp://0x<address>%2e<worker>%2f<passcode>@eth-<region>.nanopool.org:9999`

`<address>`: Your wallet address.
`<worker>`: Your worker name.
`<passcode>`: Passcode or e-mail address (in case of using a e-mail address, you need to use `%40` for `@`).
`<region>`: Replace this with the region server you want to use (like `eu2`).

No need to escape anything on Windows, but if you're using Linux (`zsh` in my case), it seems you need to escape the `%` with a backslash (that would be `\%`).

**Comment by ibmua** [comment]
Cool! Can you provide a mininal example you'd personally use on Linux with email address? That would be even more clear.

**Comment by lss4** [comment]
I think it would be like this:

`ethminer --pool stratum+tcp://0x1234567890abcdef1234567890abcdef12345678\%2eworker1\%2ftest\%40example\%2ecom@eth-eu2.nanopool.org:9999`

I personally don't need e-mail notifications so I only used a passcode for the e-mail part.

**Comment by ibmua** [comment]
This worked. Thanks!
