### ISSUE TITLE
Support for A100 Cards?

### ISSUE THREAD

**Issue by jonathanhatch** [ethereum-mining/ethminer#2055]
Are we considering adding support for Nvidia's new A100 cards? I'm not able to get ethminer to start on an A100 card.

**Comment by jean-m-cyr** [comment]
Who is 'we'?

**Comment by jonathanhatch** [comment]
The universal we. Can you do it for me? That would be easiest. :-P

**Comment by jean-m-cyr** [comment]
Nope. Folks don't seem to realize that all active developers have abandoned this project.

**Comment by AndreaLanfranchi** [comment]
Closed by #2082

**Comment by eippbx** [comment]
https://github.com/technopremium/ethminer_RTX30series/releases/tag/v1.2
This project support for Nvidia's A100 cards.
