### ISSUE TITLE
Cuda 11.1 Problem

### ISSUE THREAD

**Issue by jgonzis** [ethereum-mining/ethminer#2058]
**Describe the bug**
i 12:16:14 ethminer Epoch : 380 Difficulty : 60.00 Gh
 i 12:16:14 ethminer Job: b090ad7b… ethash.eu.mine.zergpool.com [51.210.180.98:9999]
 i 12:16:14 ethminer Switching epoch -1 -> 380
cu 12:16:16 cuda-0   Generating DAG + Light for epoch 380 : 4.03 GB
cu 12:16:16 cuda-0   Unexpected error CUDA error in func set_constants at line 124 invalid device symbol on CUDA device 02:00.0
cu 12:16:16 cuda-0   Mining suspended ...
 m 12:16:18 ethminer 0:00 A0 0.00 h - cu0 0.00
 m 12:16:23 ethminer 0:00 A0 0.00 h - cu0 0.00
 m 12:16:28 ethminer 0:00 A0 0.00 h - cu0 0.00
 m 12:16:33 ethminer 0:00 A0 0.00 h - cu0 0.00

**To Reproduce**
Lauch Ethminer in Linux with Cuda 11.1

**Environment (please complete the following information):**
- Operating System: Linux - HiveOS
- Hardware RTX 3080
- Ethminer Version [e.g. 0.19]

**Comment by gorghino** [comment]
Check here #2047 
Since RTX 3080 is an Ampere board, try recompiling with SM_86 and compute_86

**Comment by jgonzis** [comment]
Many thanks… compiled and working perfectly!!

**Comment by technopremium** [comment]
@jgonzis Can you please shared the compiled version, I have an 3080 and cuda 11.1, would like to give it a try.

**Comment by jgonzis** [comment]
Tell me where do you want that I uploaded… I use it with HiveOS … I just replace the ethminer file for my compiled one.

**Comment by technopremium** [comment]
Hi, 

I just finished compiling it and it works great, thanks for getting back to me so fast. Can you just send me the path that I need to replace the files? 

I am using it on plain Ubuntu 20.04 but HiveOS is the best OS for mining. 

Thanks

**Comment by technopremium** [comment]
@jgonzis

**Comment by jgonzis** [comment]
You should copy it to /hive/miners/ethminer/0.19.0/...

**Comment by AndreaLanfranchi** [comment]
Closed by #2082

**Comment by MotorCityCobra** [comment]
> Check here #2047
> Since RTX 3080 is an Ampere board, try recompiling with SM_86 and compute_86

Can I have the a rundown for dummies on how to do this?  I just got a 3080 and I have this error.

**Comment by gorghino** [comment]
You find all building/compiling instructions here: https://github.com/ethereum-mining/ethminer/blob/master/docs/BUILD.md
Before compiling (step 3 "Configure the project with CMake...") edit libethash-cuda/CMakeLists.txt removing lines from 12 to 39 and replace them with just one single:

`list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_86,code=sm_86")`

if you're interested in 3080 only.

Then continue with building procedure (cmake .. and so on)

**Comment by MotorCityCobra** [comment]
> Before compiling (step 3 "Configure the project with CMake...") edit libethash-cuda/CMakeLists.txt removing lines from 12 to 39 and replace them with just one single:
> 
> `list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_86,code=sm_86")`
> 
> if you're interested in 3080 only.
> Then continue with building procedure (cmake .. and so on)

Didn't work out. Though thank you for answering and maybe you feel generous enough to take a look at this error I'm getting.

nvcc fatal   : Unsupported gpu architecture 'compute_86'
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.Release.cmake:220 (message):
  Error generating
  /home/iii/mining/ethminer/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o


make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:65: libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:483: libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by gorghino** [comment]
🤔 That's odd.
Try to recompile ethminer deleting build folder first.
Then:

```
mkdir build && cd build  
cmake .. -DETHASHCUDA=ON -DETHASHCL=OFF -DCOMPUTE=86
make
sudo make install
```

**Comment by MotorCityCobra** [comment]
>  That's odd.
> Try to recompile ethminer deleting build folder first.
> Then:
> 
> ```
> mkdir build && cd build  
> cmake .. -DETHASHCUDA=ON -DETHASHCL=OFF -DCOMPUTE=86
> make
> sudo make install
> ```

Thanks, but I tried again. No dice...
    
    [ 43%] Built target hwmon
    [ 46%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
    nvcc fatal   : Unsupported gpu architecture 'compute_86'
    CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.Release.cmake:220 (message):
      Error generating
      /home/iii/mining/ethminer/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
    
    
    make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:65: libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:386: libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
    make: *** [Makefile:152: all] Error 2

Did I mention I'm using Ubuntu 20.04?
I also tried doing the build without changing those lines you said to change and it wouldn't build that was either because it said my gcc version was later than 8. I spent an hour or so trying to change my gcc version from 9 to 8 but I didn't get that done either. The best I could do was uninstall version 9 and have no gcc and an install of gcc 8 that didn't seem to be recognized by cmake.

**Comment by hwamil** [comment]
> list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_86,code=sm_86")

Would this also work on Windows 10? I have been trying to build for 2 days straight with no luck :(

**Comment by gorghino** [comment]
> Your first answer worked.
> My CUDA version displayed for nvidia-smi was 11.2 but the system was using version 10.1.
> 
> I simply upgraded to 11.2 using the [official Nvidia docs](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#introduction) and your instructions got me mining. Thank you.

Remind to close opened issues if you resolved them

**Comment by gorghino** [comment]
> > list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_86,code=sm_86")
> 
> Would this also work on Windows 10? I have been trying to build for 2 days straight with no luck :(

Yes it would. Edit libethash-cuda/CMakeLists.txt and build your executable following Windows build instructions (https://github.com/ethereum-mining/ethminer/blob/master/docs/BUILD.md#windows)

**Comment by samascience** [comment]
> SM_86 and compute_86

what is the cmake for specifying the make ?

**Comment by gorghino** [comment]
Just edit libethash-cuda/CMakeLists.txt and use the same cmake (`cmake --build .`)

**Comment by encoderlee** [comment]
![image](https://user-images.githubusercontent.com/9878012/146749463-a069f400-4434-461f-8146-49761f70007d.png)
insert
list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_86,code=sm_86")
into file
libethash-cuda/CMakeLists.txt
then rebuild to support RTX30xx gpu
