### ISSUE TITLE
rtx 3090 cuda 11.1 problem not work

### ISSUE THREAD

**Issue by hostkimjang** [ethereum-mining/ethminer#2059]
i 09:40:23 ethminer Configured pool us-east.ethash-hub.miningpoolhub.com:20535
 i 09:40:23 ethminer Selected pool us-east.ethash-hub.miningpoolhub.com:20535
 i 09:40:23 ethminer Stratum mode : EthereumStratum/1.0.0 (NiceHash)
 i 09:40:23 ethminer Established connection to us-east.ethash-hub.miningpoolhub.com [18.204.40.75:20535]
 i 09:40:23 ethminer Spinning up miners...
cu 09:40:23 cuda-0   Using Pci Id : 01:00.0 GeForce RTX 3090 (Compute 8.6) Memory : 23.45 GB
cu 09:40:23 cuda-2   Using Pci Id : 22:00.0 GeForce RTX 3090 (Compute 8.6) Memory : 23.45 GB
cu 09:40:23 cuda-1   Using Pci Id : 21:00.0 GeForce RTX 3090 (Compute 8.6) Memory : 23.45 GB
cu 09:40:23 cuda-3   Using Pci Id : 41:00.0 GeForce RTX 3090 (Compute 8.6) Memory : 23.45 GB
 i 09:40:23 ethminer Extranonce set to 00bb
 i 09:40:23 ethminer Epoch : 369 Difficulty : 8.59 Gh
 i 09:40:23 ethminer Job: 32996b7b… us-east.ethash-hub.miningpoolhub.com [18.204.40.75:20535]
 i 09:40:26 ethminer Authorized worker ko2286.kimjang01
 i 09:40:26 ethminer Job: daaf2831… us-east.ethash-hub.miningpoolhub.com [18.204.40.75:20535]
 i 09:40:26 ethminer Job: cfc397b6… us-east.ethash-hub.miningpoolhub.com [18.204.40.75:20535]
cu 09:40:26 cuda-1   Generating DAG + Light(on GPU) : 3.94 GB
cu 09:40:26 cuda-0   Generating DAG + Light(on GPU) : 3.94 GB
cu 09:40:26 cuda-1   Unexpected error CUDA error in func set_constants at line 110 invalid device symbol on CUDA device 21:00.0
cu 09:40:26 cuda-1   Mining suspended ...
cu 09:40:26 cuda-2   Generating DAG + Light(on GPU) : 3.94 GB
cu 09:40:26 cuda-3   Generating DAG + Light(on GPU) : 3.94 GB
cu 09:40:26 cuda-2   Unexpected error CUDA error in func set_constants at line 110 invalid device symbol on CUDA device 22:00.0
cu 09:40:26 cuda-2   Mining suspended ...
cu 09:40:26 cuda-0   Unexpected error CUDA error in func set_constants at line 110 invalid device symbol on CUDA device 01:00.0
cu 09:40:26 cuda-0   Mining suspended ...
cu 09:40:26 cuda-3   Unexpected error CUDA error in func set_constants at line 110 invalid device symbol on CUDA device 41:00.0
cu 09:40:26 cuda-3   Mining suspended ...

**Comment by gorghino** [comment]
Check here #2047
Since RTX 3090 is an Ampere board, try recompiling with SM_86 and compute_86

**Comment by technopremium** [comment]
Do you have the version ready to support 30 series GPUs?

**Comment by jjziets** [comment]
would be nice if they could release an update

**Comment by TimandXiyu** [comment]
You should modify the CMakeList.txt under ethminer/libethash-cuda:
Add this line:
	list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_86,code=sm_86")
to that bunch of compute and sm stuff.

Then re-compile (delete the build folder, do the cmake .. command and then rebuild ). You are good to go.

**Comment by AndreaLanfranchi** [comment]
@TimandXiyu 
there's no need to modify anything.
Simply use
`cmake -DCOMPUTE=86 ..`
instead of 
`cmake ..`

Anyway #2082 solves it

**Comment by encoderlee** [comment]
![image](https://user-images.githubusercontent.com/9878012/146749463-a069f400-4434-461f-8146-49761f70007d.png)
insert
list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_86,code=sm_86")
into file
libethash-cuda/CMakeLists.txt
then rebuild to support RTX30xx gpu
