### ISSUE TITLE
Stratum Client fails with multiple ethminer instances

### ISSUE THREAD

**Issue by r0l1** [ethereum-mining/ethminer#206]
The stratum client fails when multiple ethminer processes are running. 

Error message:
```
Could not resolve host eu2.ethermine.org:4444, Operation canceled
```

If ethminer is run with the *-SC 2* option, then everything works as expected. What is the current state and future plan for the Stratum Client Version 2?

Thanks!

**Comment by DeadManWalkingTO** [comment]
eu2.ethermine.org:4444 NOT working, NOT exist!!!
Only eu1.ethermine.org:4444

**Comment by DeadManWalkingTO** [comment]
CUDA Hardware Test Launch Command:

`ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

OpenCL Hardware Test Launch Command:

`ethminer -RH -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

MIX Hardware Test Launch Command:

`ethminer -RH -X -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`


Try with latest Ethminer version and feedback please.
Thank you!
