### ISSUE TITLE
There was an error using eGPU under MacOS without computing speed

### ISSUE THREAD

**Issue by ztfot** [ethereum-mining/ethminer#2060]
**Describe the bug**
I would like to try using eGPU RX580 for ETH mining
Choose the latest release binary for 'Darwin'.
But I use AN AMD graphics card and no CUDA
So I chose to download and install the version of EthMiner 0.17.1, URL as follows
`https://github.com/ethereum-mining/ethminer/releases/download/v0.17.1/ethminer-0.17.1-darwin-x86_64.tar.gz
`
I can see my OpenCL device using the command
```
./ethminer -G --list-devices

Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[0] [0] Intel(R) Iris(TM) Plus Graphics 650
CL_DEVICE_TYPE: GPU
CL_DEVICE_GLOBAL_MEM_SIZE: 1610612736
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 402653184
CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[0] [1] AMD Radeon RX 580 Compute Engine
CL_DEVICE_TYPE: GPU
CL_DEVICE_GLOBAL_MEM_SIZE: 4294967296
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1073741824
CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
```
I've tried,
There was an error, but there was still computing power
`X 23:52:35 cl-1     Failed to load binary kernel: /Users/ztfot/Downloads/bin/./kernels/ethash_amd radeon rx 580 compute engine_lws192.bin
`When I use a pit to dig, the computing power is 0
I don't know why. Can someone help ? :(

**Environment (please complete the following information):**
- Operating System: MacOS 10.15.7
- Hardware eGPU AMD rx 580
- Ethminer Version 0.17 darwin
- Ethminer options used stratums://0x012345678901234567890234567890123.miner1@ethermine.org:5555

**Additional context**
The version of Cuda Darwin higher than ethMiner -0.17.1 will become unavailable under MacOS

**Comment by AndreaLanfranchi** [comment]
Besides this project is currently under **no active development** I'm sorry to reiterate we've have dropped any MacOS support long time ago.
