### ISSUE TITLE
Very low hash rate compaered to expected 

### ISSUE THREAD

**Issue by yahia20** [ethereum-mining/ethminer#2069]
I have a radeon 5500xt with hash rate of 1.6!!! it should be around

**Comment by yahia20** [comment]
when I restarted and ran the benchmark it gave me the right hash rate now when I try to join the pool I get this error:
 X 09:09:01 cl-0     Creating DAG buffer failed: clCreateBuffer: CL_INVALID_BUFFER_SIZE (-61)

**Comment by yahia20** [comment]
I have 4GB gpu I asked someone and they said it must have more . can't I use normal ram? or is there a linux os that uses less vram? I should only need 3.91 GB as it says during making the DAG. Is there any fix to this?

**Comment by yahia20** [comment]
I have tried it with stopping gdm usage of around 19 MB of vram still same error is there a fix?

**Comment by AndreaLanfranchi** [comment]
> I have 4GB gpu I asked someone and they said it must have more . can't I use normal ram? or is there a linux os that uses less vram? I should only need 3.91 GB as it says during making the DAG. Is there any fix to this?

4GB does not necessarily mean 4GB. I mean ... I have some Nvidia Ti 1050 claiming 4GB RAM but in reality they have 4Billion bytes ... which is actually 3.75GB. This said you must check actual real capacity.
Besides this you have to take into account that VRAM is used for:
* store the kernel (i.e. the searching program)
* store pointers to mermory allocation(s) for work and results
* store the DAG itself
So you cannot compute the size of the DAG only.

Yes it would be possible to use host ram (the ram of the pc) to mine ... but it would make the miner completely useless as the hashrate would be 100 orders of magnitude lower

**Comment by yahia20** [comment]
I have stoped gnome and only running kernal I use radeontop to measure usage and size of vram it shows up as 4057M which I expect to be mega bytes and the use of 19M so there is 3.943+ free memory

**Comment by caomem** [comment]
linux with navi not work very well. Linux kernel 5.10 fix this problem.. try update your kernel

**Comment by yahia20** [comment]
Thanks to the suggestion but I have lost interest in mining since I found out that it's illegal in my country as soon as it is legal.
