### ISSUE TITLE
 X 19:54:56 cl-0     Creating DAG buffer failed: clCreateBuffer: CL_INVALID_BUFFER_SIZE (-61)

### ISSUE THREAD

**Issue by yahia20** [ethereum-mining/ethminer#2071]
I have a 4GB card radeon 5500xt when I first installed the software it only had a very low hash rate of 1.6 when I rebooted and benchmarked it gave me right hash rate when I try to run the pool I get this error even if I close my DE and only use 17M of VRAM is this a bug?? 
here is my output

ethminer -P stratum1+ssl://0x918CaC3214BD428705D12F9a1e23B267315c196b.YahiaGH@eu1.ethermine.org:5555 -G 

ethminer 0.18.0
Build: linux/release/gnu

 i 19:54:54 ethminer Configured pool eu1.ethermine.org:5555
 i 19:54:54 ethminer Selected pool eu1.ethermine.org:5555
 i 19:54:54 ethminer Stratum mode : Eth-Proxy compatible
 i 19:54:54 ethminer Established connection to eu1.ethermine.org [172.65.207.106:5555]
 i 19:54:54 ethminer Spinning up miners...
cl 19:54:54 cl-0     Using PciId : 08:00.0 gfx1012 OpenCL 2.0 AMD-APP (3180.7) Memory : 3.98 GB
 i 19:54:54 cl-0     Adjusting CL work multiplier for 11 CUs. Adjusted work multiplier: 20,025
 i 19:54:54 ethminer Epoch : 372 Difficulty : 4.00 Gh
 i 19:54:54 ethminer Job: 7ad70065… block 11185621 eu1.ethermine.org [172.65.207.106:5555]
cl 19:54:56 cl-0     Generating DAG + Light : 3.97 GB
 i 19:54:56 ethminer Job: 7ed00553… block 11185622 eu1.ethermine.org [172.65.207.106:5555]
 i 19:54:56 ethminer Job: 4496dcc5… block 11185622 eu1.ethermine.org [172.65.207.106:5555]
cl 19:54:56 cl-0     OpenCL kernel
cl 19:54:56 cl-0     Loading binary kernel /home/yahia/bin/kernels/ethash_gfx1012_lws128_exit.bin
 X 19:54:56 cl-0     Failed to load binary kernel: /home/yahia/bin/kernels/ethash_gfx1012_lws128_exit.bin
 X 19:54:56 cl-0     Falling back to OpenCL kernel...
cl 19:54:56 cl-0     Creating light cache buffer, size: 62.50 MB
cl 19:54:56 cl-0     Creating DAG buffer, size: 3.91 GB, free: 17.50 MB
 X 19:54:56 cl-0     Creating DAG buffer failed: clCreateBuffer: CL_INVALID_BUFFER_SIZE (-61)
SIGSEGV encountered ...
stack trace:
backtrace() returned 7 addresses
ethminer() [0x422af9]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14bb0) [0x7fdd464b7bb0]
ethminer() [0x6e0a61]
ethminer() [0x4baff6]
ethminer() [0x773aaf]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x9590) [0x7fdd464ac590]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7fdd46268223]
SIGSEGV encountered ...
stack trace:
backtrace() returned 7 addresses
ethminer() [0x422af9]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14bb0) [0x7fdd464b7bb0]
ethminer() [0x419e58]
ethminer() [0x429f59]
ethminer() [0x773aaf]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x9590) [0x7fdd464ac590]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7fdd46268223]

**Comment by zhumingyu** [comment]
> I have a 4GB card radeon 5500xt when I first installed the software it only had a very low hash rate of 1.6 when I rebooted and benchmarked it gave me right hash rate when I try to run the pool I get this error even if I close my DE and only use 17M of VRAM is this a bug??
> here is my output
> 
> ethminer -P stratum1+ssl://0x918CaC3214BD428705D12F9a1e23B267315c196b.YahiaGH@eu1.ethermine.org:5555 -G
> 
> ethminer 0.18.0
> Build: linux/release/gnu
> 
> i 19:54:54 ethminer Configured pool eu1.ethermine.org:5555
> i 19:54:54 ethminer Selected pool eu1.ethermine.org:5555
> i 19:54:54 ethminer Stratum mode : Eth-Proxy compatible
> i 19:54:54 ethminer Established connection to eu1.ethermine.org [172.65.207.106:5555]
> i 19:54:54 ethminer Spinning up miners...
> cl 19:54:54 cl-0 Using PciId : 08:00.0 gfx1012 OpenCL 2.0 AMD-APP (3180.7) Memory : 3.98 GB
> i 19:54:54 cl-0 Adjusting CL work multiplier for 11 CUs. Adjusted work multiplier: 20,025
> i 19:54:54 ethminer Epoch : 372 Difficulty : 4.00 Gh
> i 19:54:54 ethminer Job: 7ad70065… block 11185621 eu1.ethermine.org [172.65.207.106:5555]
> cl 19:54:56 cl-0 Generating DAG + Light : 3.97 GB
> i 19:54:56 ethminer Job: 7ed00553… block 11185622 eu1.ethermine.org [172.65.207.106:5555]
> i 19:54:56 ethminer Job: 4496dcc5… block 11185622 eu1.ethermine.org [172.65.207.106:5555]
> cl 19:54:56 cl-0 OpenCL kernel
> cl 19:54:56 cl-0 Loading binary kernel /home/yahia/bin/kernels/ethash_gfx1012_lws128_exit.bin
> X 19:54:56 cl-0 Failed to load binary kernel: /home/yahia/bin/kernels/ethash_gfx1012_lws128_exit.bin
> X 19:54:56 cl-0 Falling back to OpenCL kernel...
> cl 19:54:56 cl-0 Creating light cache buffer, size: 62.50 MB
> cl 19:54:56 cl-0 Creating DAG buffer, size: 3.91 GB, free: 17.50 MB
> X 19:54:56 cl-0 Creating DAG buffer failed: clCreateBuffer: CL_INVALID_BUFFER_SIZE (-61)
> SIGSEGV encountered ...
> stack trace:
> backtrace() returned 7 addresses
> ethminer() [0x422af9]
> /lib/x86_64-linux-gnu/libpthread.so.0(+0x14bb0) [0x7fdd464b7bb0]
> ethminer() [0x6e0a61]
> ethminer() [0x4baff6]
> ethminer() [0x773aaf]
> /lib/x86_64-linux-gnu/libpthread.so.0(+0x9590) [0x7fdd464ac590]
> /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7fdd46268223]
> SIGSEGV encountered ...
> stack trace:
> backtrace() returned 7 addresses
> ethminer() [0x422af9]
> /lib/x86_64-linux-gnu/libpthread.so.0(+0x14bb0) [0x7fdd464b7bb0]
> ethminer() [0x419e58]
> ethminer() [0x429f59]
> ethminer() [0x773aaf]
> /lib/x86_64-linux-gnu/libpthread.so.0(+0x9590) [0x7fdd464ac590]
> /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7fdd46268223]

is there any solutions for this problem?thx

**Comment by yahia20** [comment]
you can use lolminer or wait for them to decrease dag size
