### ISSUE TITLE
Proposal of a small optimization for miner for a particular SHFL operation

### ISSUE THREAD

**Issue by gamebak** [ethereum-mining/ethminer#2073]
**I'm far from an expert, so please take my issue with a grain of salt.**

I'm proposing a small optimization for this line of code:
https://github.com/ethereum-mining/ethminer/blob/d5f3a972220e06bf7b5d964d473d4c757e57e35d/libethash-cuda/ethash_cuda_miner_kernel.cu#L68

While investigating the miner code I kept looking at this and I couldn't figure if it was necessary.
**Assumptions:**
1. `parent_index` will always result in 0 or 1,  we can assume that we will have the following generated SHFL combinations
2. `t` is in the [0:3] range, which means `t modulo 4` will never happen
3. All the shfl variations for each `t`
```
parent_index = 0
SHFL(0,0,4)
SHFL(0,1,4)
SHFL(0,2,4)
SHFL(0,3,4)

parent_index = 1
SHFL(1,0,4)
SHFL(1,1,4)
SHFL(1,2,4)
SHFL(1,3,4)
```

The question is if we really need to have to use SHFL to share data between lanes when the data is actually a constant?

**Code will be:**
```c
uint32_t shuffle_index = parent_index;
```

**Notes**:
I couldn't test this, I have a 3gb nvidia gpu, too small for the current eth dag file.

**Comment by AndreaLanfranchi** [comment]
I believe your assumption 1 is wrong.

**Comment by gamebak** [comment]
Thank you for taking the time to explain, I see the issue with my assumptions, thank you!
