### ISSUE TITLE
Exception thrown in Worker thread - GTX 1070TI

### ISSUE THREAD

**Issue by nonozg** [ethereum-mining/ethminer#2078]
m 00:04:00 ethminer 0:08 A27 252.44 Mh - cu0 31.55, cu1 31.56, cu2 31.56, cu3 31.57, cu4 31.56, cu5 31.57, cu6 31.57, cu7 31.50
i 00:04:01 ethminer Job: 3d79cb45 eu1.ethermine.org [172.65.207.106:4444]
i 00:04:01 ethminer Job: efcf0c18 eu1.ethermine.org [172.65.207.106:4444]
X 00:04:02 cuda-6 Exception thrown in Worker thread: GPU error: CUDA error in func search at line 353 unspecified launch failure
X 00:04:02 cuda-4 Exception thrown in Worker thread: GPU error: CUDA error in func search at line 353 unspecified launch failure
X 00:04:02 cuda-7 Exception thrown in Worker thread: GPU error: CUDA error in func search at line 353 unspecified launch failure
X 00:04:02 cuda-5 Exception thrown in Worker thread: GPU error: CUDA error in func search at line 353 unspecified launch failure
X 00:04:02 cuda-0 Exception thrown in Worker thread: GPU error: CUDA error in func search at line 353 unspecified launch failure
X 00:04:02 cuda-1 Exception thrown in Worker thread: GPU error: CUDA error in func search at line 353 unspecified launch failure
X 00:04:02 cuda-3 Exception thrown in Worker thread: GPU error: CUDA error in func search at line 353 unspecified launch failure
X 00:04:02 cuda-2 Exception thrown in Worker thread: GPU error: CUDA error in func search at line 353 unspecified launch failure
i 00:04:05 ethminer Job: 77bff60a eu1.ethermine.org [172.65.207.106:4444]
m 00:04:05 ethminer 0:08 A27 252.57 Mh - cu0 31.58, cu1 31.56, cu2 31.56, cu3 31.57, cu4 31.55, cu5 31.57, cu6 31.57, cu7 31.60

Hardware: 1070TI Asus Cerberus, clocks: +100, +1100 at 125w (smos)

**Comment by jgonzis** [comment]
Reduce Mem Mhz and clock... to high OC

**Comment by AndreaLanfranchi** [comment]
No feed back.
Closing
