### ISSUE TITLE
Add support for compute_62 / sm_62

### ISSUE THREAD

**Issue by JHGitty** [ethereum-mining/ethminer#208]
I think we should add support for compute_62 / sm_62 to our miner?

Our current implementation: https://github.com/ethereum-mining/ethminer/blob/e4f6cfe94cfeb2c60ebdbff2a3c4ef49c91cf149/libethash-cuda/CMakeLists.txt#L14-L19

I think we should add:
```
-gencode=arch=compute_62,code=sm_62
```

Source: http://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

**Comment by chfast** [comment]
Just make a PR with these.

**Comment by chfast** [comment]
Closed by #245.
