### ISSUE TITLE
All shares are invalid

### ISSUE THREAD

**Issue by x0xa** [ethereum-mining/ethminer#2083]
Hi all!!

Today all shares are invalid with reason:

http://prntscr.com/vscddp

last version 0.19 installed
pool https://etc.ethermine.org/ or any else with same results (2miners.com for example)

have you any solutions?
Thank you!

**Comment by AndreaLanfranchi** [comment]
You probably missed ethereum classic has forked to its own algorithm named etchash which differs from ethash which is the only implemented in ethminer. You have to change miner.

**Comment by x0xa** [comment]
> You probably missed ethereum classic has forked to its own algorithm named etchash which differs from ethash which is the only implemented in ethminer. You have to change miner.

Thank you so much!
Can you recommend any good stuff?

**Comment by AndreaLanfranchi** [comment]
I'd recommend only open source miners.
I'm not aware of any at the moment. 
You can check for ecip-1099 documentation. I believe they report a list of supported miners. Also on etc.ethermine.org you should find suggestion
