### ISSUE TITLE
Problems with 0.18.0 and Win10 with mixed GPU

### ISSUE THREAD

**Issue by radioresearch** [ethereum-mining/ethminer#2085]
**Describe the bug**
2x GTX-1660 and 1x RX570 8GB cards.  I can use either/or via the -C or -U command line switches, but -X switch causes immediate crash. --opencl-platform has no effect

**To Reproduce**
1. Install ethminer in windows 10
2. Install mixed GPUs
3. Kick the tires and light the fire
4. No joy

**Expected behavior**
According to the -X command line switch documentation, this should cause the mixed GPUs to frolic and play together.

**Environment (please complete the following information):**
- Operating System: Windows 10 Enterprise
- Hardware 2x GTX1660; 1x RX570 8G
- Ethminer Version 0.18.0
- Ethminer options used -U or -G, however -X to make use of mixed GPUs does not work.  With the first two variables, it's an either/or scenario.

**Additional context**
Bought the Radeon/AMD to try it out, because it's cheaper than the NVidia cards.  Was hoping to buy more, but not if I can't get the buggardly thing to work!
Please help!

EDIT!  Trying two separate instances of ethminer each with the respective GPU option.  I'm not convinced this is the best thing to do.

**Comment by AndreaLanfranchi** [comment]
The `-X` switch has been dismissed and ethminer runs mixed mode by default.
`-U` and `-G` cli arguments are set when you want to limit mining either on CUDA or OpenCL respectively

**Comment by radioresearch** [comment]
That would have been nice to know.  I wish it had been updated in the command line switch listing.  Thank you! I'll try it out. :-)
