### ISSUE TITLE
No usable mining devices found - ethminer v 18 & 19 - Windows 10 Amd Radeon rx 5600 / 5700 xt - driver Adrenalin 20.11

### ISSUE THREAD

**Issue by i8088** [ethereum-mining/ethminer#2089]
No usable mining devices found - ethminer v 18 & 19 - Windows 10 Amd Radeon rx 5600 / 5700 xt - driver Adrenalin 20.11 

ethminer 0.19.0-alpha.0
Build: windows/release/msvc

Unrecognized platform Intel(R) OpenCL
Error: No usable mining devices found

----------------------------

ethminer 0.18
Build: windows/release/msvc

Unrecognized platform Intel(R) OpenCL
Error: No usable mining devices found

**Comment by i8088** [comment]
https://github.com/ethereum-mining/ethminer/issues/2001

Solved

**Comment by AdhithAdhi** [comment]
> #2001
> 
> Solved

How did you solved this issue
