### ISSUE TITLE
nvcc fatal when building using RTX 3090, Windows 10

### ISSUE THREAD

**Issue by numbfx** [ethereum-mining/ethminer#2091]
I am building ethminer using git latest repo and I can get up to step 4, which is `cmake --build . --config Release`

I then get the following error:

 ``` 
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.obj.Release.cmake:220 (message):
    Error generating
    C:/Users/numbf/Downloads/ethminer/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//Release/ethash-cuda_generated_et
  hash_cuda_miner_kernel.cu.obj

  nvcc fatal   : nvcc cannot find a supported version of Microsoft Visual Studio. Only the versions between 2017 and 20
  19 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check;
   however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at yo
  ur own risk.

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exi
ted with code 1. [C:\Users\numbf\Downloads\ethminer\build\libethash-cuda\ethash-cuda.vcxproj]
  ethminer-buildinfo.vcxproj -> C:\Users\numbf\Downloads\ethminer\build\ethminer\Release\ethminer-buildinfo.lib
  poolprotocols.vcxproj -> C:\Users\numbf\Downloads\ethminer\build\libpoolprotocols\Release\poolprotocols.lib
```

using Windows 10 with a RTX 3090 and Nvidia CUDA 11.2, VS2017 with v140 is installed.

If this helps, I used `cmake .. -G "Visual Studio 15 2017 Win64" -T v140`

**Comment by numbfx** [comment]
using `cmake .. -G "Visual Studio 15 2017 Win64"` worked fine

**Comment by Gimel-ai** [comment]
You can check my compiled repo with RTX 30 series and cuda 11.1 support here - https://github.com/technopremium/ethminer_RTX30series

**Comment by jean-m-cyr** [comment]
NOTE: This above recommended repo violates the terms of GPL V3 licensing and is not recommended. It is a directly derived from Ethminer but publishes no source code as required.

Try this one instead: https://github.com/no-fee-ethereum-mining/nsfminer.git

**Comment by sparky3387** [comment]
Just for anyone else having the same issue above, I had to delete my build directory and use the batch file provided to get past this error
