### ISSUE TITLE
Please also add enode url in addition to stratum.

### ISSUE THREAD

**Issue by ytrezq** [ethereum-mining/ethminer#2092]
The enode url (differrent from the stratum url) is used by other Ethereum nodes to connect the current node.
The problem when racing for transactions is the number of nodes between the submitting node and the miner node.

One can submit a transaction directly to miners but it require connecting his node to the miner s node, which require finding his enode url.

So far, I found it for SparkPool https://www.coindesk.com/sparkpool-taichi-mining-network-front-running-defi and my request for Hiveon wasn t well received because it wasn t read properly.
![Screenshot_20201220-141733_Telegram](https://user-images.githubusercontent.com/3824869/102714358-47c94100-42ce-11eb-89c7-ff76c09592d5.jpg)

**Comment by AndreaLanfranchi** [comment]
This request is completely out of scope. You miss several points:

- ethminer is **not** a mining node. Is a hashing software which finds a nonce for a block header
- ethminer has no knowledge of transactions being inserted in the block candidate.
- ethminer does not even know what a transaction is
- `enode` uri is totally unknown to ethminer and to connect to a specific node would need to implement in ethminer all the p2p protocol stuff typical of nodes

Do not know what you're trying to achieve but "submitting transactions to miners" is totally different from "having ethminer hash them"

**Comment by ytrezq** [comment]
Oh sorry, I was talking about https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md

I didn t paid attention to the type of the project.
