### ISSUE TITLE
CUDA Error : invalid argument Error: No usable mining devices found

### ISSUE THREAD

**Issue by fgblanch** [ethereum-mining/ethminer#2104]
**Describe the bug**
After building from source on Master branch on Windows 10 and Cuda 11.2. When I try to run the client. It says:

CUDA Error : invalid argument
Error: No usable mining devices found

nvidia-smi is showing the correct devices. Why ethminer can not find the Cuda GPU (RTX 3090)

**To Reproduce**
Explained above

**Environment (please complete the following information):**
- Operating System: Windows 10
- Hardware: RTX 3090
- Ethminer Version: ethminer 0.19.0-4
- Ethminer options used 

**Additional context**

**Comment by Gimel-ai** [comment]
You can check my compiled repo with RTX 30 series and cuda 11.1 support here - https://github.com/technopremium/ethminer_RTX30series

**Comment by jean-m-cyr** [comment]
NOTE: This above recommended repo violates the terms of GPL V3 licensing and is not recommended. It is a directly derived from Ethminer but publishes no source code as required.

Try this one instead: https://github.com/no-fee-ethereum-mining/nsfminer.git

**Comment by fgblanch** [comment]
Closing the issue as there is no constructive answers
