### ISSUE TITLE
ethminer GPU 7 gave incorrect result. Lower overclocking values if it happens frequently.

### ISSUE THREAD

**Issue by peterwillcn** [ethereum-mining/ethminer#2114]
ethminer GPU 7 gave incorrect result. Lower overclocking values if it happens frequently.

**Comment by jean-m-cyr** [comment]
Insufficient information provided

**Comment by kivechang** [comment]
I just had this same issue" GPU 0 gave incorrect result. Lower overclocking values if it happens frequently."
it will significantly lower current hashrate and valid shares
I found a few ways
1.dropping my mem clock on my cards a bit
2.Change to a different pool

Some people say  tweaked version of ethminer.
 I didn’t test this
