### ISSUE TITLE
Drop hunter from CMakeLists.txt

### ISSUE THREAD

**Issue by reagentoo** [ethereum-mining/ethminer#212]
Hunter packaging does not allow writing packages for various Linux-distributions properly. Please remove the Hunter (or make optional), this will allow to use native libraries and greatly simplify package support.

**Comment by chfast** [comment]
It is optional, you can disable Hunter. RTFM.

**Comment by reagentoo** [comment]
Please, check build your project with native system libs. It is necessary to edit cmakeLists.

**Comment by reagentoo** [comment]
-- Found PythonInterp: /usr/bin/python (found version "3.4.6") 

[hunter ** INTERNAL **] root is empty
[hunter ** INTERNAL **] [Directory:/var/tmp/portage/net-p2p/ethminer-9999/work/ethminer-9999]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at cmake/HunterGate.cmake:82 (message):
Call Stack (most recent call first):
  cmake/HunterGate.cmake:92 (hunter_gate_wiki)
  cmake/HunterGate.cmake:117 (hunter_gate_internal_error)
  CMakeLists.txt:22 (hunter_gate_self)
