### ISSUE TITLE
Unable to mine with 4Gb card

### ISSUE THREAD

**Issue by Dranaxel** [ethereum-mining/ethminer#2128]
Hello,

I just assembled a mining server with 2xRX480 at 8Gb and one with 4Gb. When I try to launch using the three cards I get an error about not having enough memory (Sorry i don't have access to my computer actually so i cannot give you the exact error) but if i use only the two primary cards it works. I heard 4Gb where not the best to mine so, is it still possible (even with bad perfs) or is this an error from my side ?

Thanks

**Comment by jean-m-cyr** [comment]
See the README. You can't mine Ethereum using 4GB video cards.
