### ISSUE TITLE
temp / fan stats on the api 

### ISSUE THREAD

**Issue by mwalol** [ethereum-mining/ethminer#2130]
the api doesn't show the Temp  / Fan Value, they stay at 0 all time : 

![image](https://user-images.githubusercontent.com/7727649/105439821-d03c5800-5c65-11eb-83df-19e235e8fca7.png)

when i check the nvidia-smi the values are showed! is it something wrong with the support of the api on the latest rtx 3090 card?

**Comment by AndreaLanfranchi** [comment]
Same as #2087
