### ISSUE TITLE
Got unknown method [mining.set_difficulty] from pool

### ISSUE THREAD

**Issue by DATL4G** [ethereum-mining/ethminer#2156]
### Describe the bug
Cannot start mining because of `Got unknown method [mining.set_difficulty] from pool.`

### Error
```shell
ethminer 0.19.0-17+commit.ce52c740
Build: linux/release/gnu

 i 22:22:17 ethminer Configured pool sha256.eu.nicehash.com:3334
 i 22:22:17 ethminer Selected pool sha256.eu.nicehash.com:3334
 i 22:22:17 ethminer Stratum mode : Stratum
 i 22:22:17 ethminer Established connection to sha256.eu.nicehash.com [172.65.200.133:3334]
 i 22:22:17 ethminer Spinning up miners...
cu 22:22:17 cuda-0   Using Pci Id : 41:00.0 GeForce RTX 2080 (Compute 7.5) Memory : 7.54 GB
 i 22:22:17 ethminer Authorized worker BTC_WALLET.PopOS
 X 22:22:17 ethminer Got unknown method [mining.set_difficulty] from pool. Discarding...
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::overflow_error> >'
  what():  Integer Division by zero.
```

### Environment (please complete the following information)
- **Operating System:** Pop!_OS 20.10
- **Hardware:** RTX 2080, AMD Threadripper 1920X
- **Ethminer Version:** Tried with _0.18.0_, _0.19.0-alpha_ and _build by master_
- **Ethminer options used:** `./ethminer -U -P stratum+tcp://BTC_WALLET.PopOS@sha256.eu.nicehash.com:3334`

### Additional Information
BTC_WALLET is provided correctly just don't want to expose here

Tried different methods daggerhashimoto starts at least however it doesn't mine because of:
```shell
Authorized worker BTC_WALLET.PopOS
 X 01:49:41 ethminer Got unknown method [mining.set_difficulty] from pool. Discarding...
 X 01:49:41 ethminer Stratum got invalid Json message : BadHexCharacter
 i 01:49:41 ethminer Connection remotely closed by daggerhashimoto.eu.nicehash.com
 i 01:49:41 ethminer Disconnected from daggerhashimoto.eu.nicehash.com [172.65.200.133:3353]
 i 01:49:41 ethminer No connection. Suspend mining ...
```

**Comment by gardotd426** [comment]
Yeah I'm getting these errors trying to connect to NiceHash as well (on Arch Linux).

**Comment by gardotd426** [comment]
I'll also add that I just checked NiceHash, and the two attempts I just made to start mining actually showed up as rigs (and I'd never used those worker names before). So it's connecting in some way, just not completely.

**Comment by DATL4G** [comment]
@gardotd426 use stratum2+tcp://... instead of stratum+tcp://

**Comment by gardotd426** [comment]
```
 i 10:59:29 ethminer Configured pool daggerhashimoto.usa.nicehash.com:3341
 i 10:59:29 ethminer Selected pool daggerhashimoto.usa.nicehash.com:3341
 i 10:59:30 ethminer Negotiation of EthereumStratum/1.0.0 (NiceHash) failed. Change your connection parameters
 i 10:59:30 ethminer Disconnected from daggerhashimoto.usa.nicehash.com:3341
 i 10:59:30 ethminer No connection. Suspend mining ...
 i 10:59:30 ethminer No more connections to try. Exiting...
 i 10:59:30 main     Got interrupt ...
 i 10:59:30 ethminer Terminated!
```
Doesn't work for me. 


`ethminer -U -P stratum2+tcp://[BTC_WALLET_ADDRESS].archlinux@daggerhashimoto.usa.nicehash.com:3341`

**Comment by jean-m-cyr** [comment]
I believe the correct port is 3353

**Comment by fer-marino** [comment]
same problem with f2pool. Using stratum2+tcp does not work either

**Comment by SFD-411** [comment]
same issue with antpool and prohashing
