### ISSUE TITLE
OpenCL platform detection broken

### ISSUE THREAD

**Issue by EoD** [ethereum-mining/ethminer#216]
In the current version ([97fb700397](https://github.com/ethereum-mining/ethminer/tree/97fb700397c61eff9a447769367b64a7ce6ec5eb)) the OpenCL platform detection is broken.

```
$./ethminer -G -M -v 9
  ℹ  21:08:03|ethminer  Found suitable OpenCL device [ AMD Radeon (TM) R9 380 Series (AMD TONGA / DRM 3.15.0 / 4.12.3, LLVM 3.9.1) ] with 4293136384  bytes of GPU memory
  ◇  21:08:03|ethminer  #00004000…
Benchmarking on platform: CL
Preparing DAG for block #0
 cl  21:08:03|cl-0      No work. Pause.
Warming up...
 cl  21:08:03|cl-0      Set work. Header #50c856ae… target 0000000000000002000000000000000000000000000000000000000000000000
 cl  21:08:03|cl-0      Initialising miner with seed #00000000…
Trial 1...  cl  21:08:19|cl-0      Platform: Clover
 cl  21:08:19|cl-0      Device:   AMD Radeon (TM) R9 380 Series (AMD TONGA / DRM 3.15.0 / 4.12.3, LLVM 3.9.1)  / OpenCL 1.1 Mesa 17.2.0-devel (git-6874b953f6)
 cl  21:08:19|cl-0      OpenCL 1.1  not supported - minimum required version is 1.2
  ✘  21:08:19|cl-0      OpenCL Error: clEnqueueWriteBuffer -36
```

According to [CLMiner.cpp#L375](https://github.com/ethereum-mining/ethminer/blob/f3270b0685eb1208e92d58be47190b1198c8252c/libethash-cl/CLMiner.cpp#L375-L378), it should detect as "Clover" and then go into [CLMiner.cpp#397](https://github.com/ethereum-mining/ethminer/blob/f3270b0685eb1208e92d58be47190b1198c8252c/libethash-cl/CLMiner.cpp#L397-L400). It did work before the rework of this code.

I glanced at the code without seeing anything which could cause the above behaviour.

@chfast Any idea?

**Comment by chfast** [comment]
Sorry for breaking this. No idea so far, need to find some spare time.

Anyway, I'd like to move platform detection to the kernel source code. Do you know this is possible?

**Comment by EoD** [comment]
I bisected the issue and it is caused by cdcb6932d13c4b86ee17dffafc79652a2b9e1f14.

If I read this correctly, you actually downgraded cl.hpp from 
``2.0.10`` (which should be called ``cl2.hpp``) 
to
``1.2.9`` (which is called ``cl.hpp``).

Did this downgrade happen by accident?

I also debugged the issue, and apparently ``if(platformName == "Clover")`` is never true, even though gdb told me that ``platformName`` is ``"Clover"``.

**Comment by EoD** [comment]
I tried to debug this further and both variables ``platformName`` are binary identical if they are converted with ``.c_str()`` according to gdb.

The only difference I could notice is that the ``ptype`` of ``platformName`` changes after switching the header: https://gist.github.com/EoD/cba4e42ba102c54f90f24d8c26629f79

Without further research, I guess that the other header is somehow hitting a difference "==" overload and maybe some compiler bug.

If you have no further idea and if you don't object ofc, I would suggest reverting the change for the moment.

**Comment by chfast** [comment]
The reason for downgrading is that at some point clhpp project decided to split the headers into cl.hpp and cl2.hpp instead of maintaining single one for both CL1 and CL2. So I took cl.hpp that is newer but for CL1 only. 

What does `ETHCL_LOG("Platform: " << platformName);` say?

**Comment by chfast** [comment]
Oh. It looks like the platformName has additional null byte in the and. Try comparing with `"Clover\0"` in the code.

**Comment by EoD** [comment]
We can use ``cl2.hpp`` for OpenCL 1.x if I am not mistaken. We just need to advertise it, don't we?

```c++
#define CL_HPP_TARGET_OPENCL_VERSION 120
#define CL_HPP_MINIMUM_OPENCL_VERSION 110
```
http://github.khronos.org/OpenCL-CLHPP/

**Comment by chfast** [comment]
It was like this before.

Anyway, can you try both? `"Clover\0"` and cl2.hpp? 
I don't mind cl2.hpp if it does not produce a ton of warnings like before.

**Comment by EoD** [comment]
I don't mind trying both.

Just to be sure, by ``"Clover\0"`` you mean remove duplicate null bytes at the end of ``platformName`` and keeping ``if(platformName == "Clover")``? I will test this as soon as I have access to the hardware again.

About your warnings: I never had any warnings with the old ``cl.hpp`` (which was a ``cl2.hpp``), did you use specific compiler flags? Is this related to hunter by any chance?

**Comment by chfast** [comment]
No. They were regular C++ warnings if the include of `cl2.hpp` was not wrapped by warning controlling pragmas.

**Comment by EoD** [comment]
I tried reproducing the error with the following code

```c++
#include <string>
#include <iostream>

using namespace std;

int main()
{
        string str_clean = "My Test";
        string str_spam = "My Test\0\0";

        if(str_clean == "My Test")
            cout << "str_clean equals" << endl;
        else
            cout << "str_clean not-equals" << endl;

        if(str_clean == "My Test\0")
            cout << "str_clean equals \\0" << endl;
        else
            cout << "str_clean not-equals \\0" << endl;

        if(str_spam == "My Test")
            cout << "str_spam equals" << endl;
        else
            cout << "str_spam not-equals" << endl;

        if(str_spam == "My Test\0")
            cout << "str_spam equals \\0" << endl;
        else
            cout << "str_spam not-equals \\0" << endl;
}
```

it returns
```
str_clean equals
str_clean equals \0
str_spam equals
str_spam equals \0
```

Hence I am not convinced that checking by ``"\0"`` will fix our issue.

I am still afraid it's related to the [ptype difference](https://gist.github.com/EoD/cba4e42ba102c54f90f24d8c26629f79) above:
```patch
-    void _M_construct<__gnu_cxx::__normal_iterator<char*, std::vector<char, std::allocator<char> > > >(__gnu_cxx::__normal_iterator<_CharT*, std::vector<char> >, __gnu_cxx::__normal_iterator<_CharT*, std::vector<char> >);
-    void _M_construct<__gnu_cxx::__normal_iterator<char*, std::vector<char, std::allocator<char> > > >(__gnu_cxx::__normal_iterator<_CharT*, std::vector<char> >, __gnu_cxx::__normal_iterator<_CharT*, std::vector<char> >, std::forward_iterator_tag);
-    void _M_construct_aux<__gnu_cxx::__normal_iterator<char*, std::vector<char, std::allocator<char> > > >(__gnu_cxx::__normal_iterator<_CharT*, std::vector<char> >, __gnu_cxx::__normal_iterator<_CharT*, std::vector<char> >, std::__false_type);
-    static void _S_copy_chars<__gnu_cxx::__normal_iterator<char*, std::vector<char, std::allocator<char> > > >(pointer, __gnu_cxx::__normal_iterator<_CharT*, std::vector<char> >, __gnu_cxx::__normal_iterator<_CharT*, std::vector<char> >);
+    void _M_construct<__gnu_cxx::__normal_iterator<char*, std::vector<char> > >(__gnu_cxx::__normal_iterator<_CharT*, std::vector<char> >, __gnu_cxx::__normal_iterator<_CharT*, std::vector<char> >);
+    void _M_construct<__gnu_cxx::__normal_iterator<char*, std::vector<char> > >(__gnu_cxx::__normal_iterator<_CharT*, std::vector<char> >, __gnu_cxx::__normal_iterator<_CharT*, std::vector<char> >, std::forward_iterator_tag);
+    void _M_construct_aux<__gnu_cxx::__normal_iterator<char*, std::vector<char> > >(__gnu_cxx::__normal_iterator<_CharT*, std::vector<char> >, __gnu_cxx::__normal_iterator<_CharT*, std::vector<char> >, std::__false_type);
+    static void _S_copy_chars<__gnu_cxx::__normal_iterator<char*, std::vector<char> > >(pointer, __gnu_cxx::__normal_iterator<_CharT*, std::vector<char> >, __gnu_cxx::__normal_iterator<_CharT*, std::vector<char> >);
```

Unfortunately I didn't have a chance to test either the ``\0`` check or the ``cl2.hpp`` upgrade on AMD hardware as of now.

**Comment by EoD** [comment]
Well, I can confirm what I thought. If I do
```c++
356         string platformName = platforms[platformIdx].getInfo<CL_PLATFORM_NAME>();
[...]
368         else if (platformName == "Clover\0")
369         {
370             platformId = OPENCL_PLATFORM_CLOVER;
371         }   
372 
```
it does still not work. But if I do
```c++
356         string platformName = platforms[platformIdx].getInfo<CL_PLATFORM_NAME>();
357         platformName.erase(std::remove( platformName.begin(), platformName.end(), '\0'), platformName.end());
[...]
369         else if (platformName == "Clover")
370         {   
371             platformId = OPENCL_PLATFORM_CLOVER;
372         }
```
it works again (but eventually fails somewhere else - no idea why, maybe driver related).

I was not able to find something which actually allows checking if we are using ``cl.hpp`` or ``cl2.hpp``, so this new line 357 would be redundant if we ever go back to ``cl2.hpp``. If you still prefer this, I don't mind adding this.

**Comment by EoD** [comment]
About upgrading to ``cl2.hpp``. I remove the above changes and just upgrade ``cl.hpp`` to ``cl2.hpp`` like this:
```patch
--- a/libethash-cl/CLMiner.h
+++ b/libethash-cl/CLMiner.h
@@ -10,8 +10,10 @@
 #include <libethcore/Miner.h>
 
 #define CL_USE_DEPRECATED_OPENCL_1_2_APIS true
-#define __CL_ENABLE_EXCEPTIONS true
-#include "CL/cl.hpp"
+#define CL_HPP_ENABLE_EXCEPTIONS true
+#define CL_HPP_TARGET_OPENCL_VERSION 120
+#define CL_HPP_MINIMUM_OPENCL_VERSION 110
+#include "CL/cl2.hpp"
 
 // macOS OpenCL fix:
 #ifndef CL_DEVICE_COMPUTE_CAPABILITY_MAJOR_NV
```

It did not create a single warning while compiling with GCC 5.4.0. What kind of compiler did you use? Do I need to remove some kind of "disable-warnings" define which I missed?

**Comment by chfast** [comment]
Looks ok. Submit PR.

**Comment by EoD** [comment]
My previous comment was not completely correct. If you use boost-1.64 via hunter (and not my system boost-1.62 as I did), there are indeed new warnings when using ``cl2.hpp``:

```
[ 69%] Building CXX object libethash-cl/CMakeFiles/ethash-cl.dir/CLMiner.cpp.o
In file included from /workspace/ethminer/libethash-cl/CLMiner.h:17:0,
                 from /workspace/ethminer/libethash-cl/CLMiner.cpp:6:
/workspace/ethminer/libethash-cl/CL/cl2.hpp:1829:25: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
     const cl_type get() const { return object_; }
                         ^
[ 73%] Linking CXX static library libethash-cl.a
[ 78%] Built target ethash-cl
[ 91%] Built target ethstratum
Scanning dependencies of target ethminer
[ 95%] Building CXX object ethminer/CMakeFiles/ethminer.dir/main.cpp.o
In file included from /workspace/ethminer/ethminer/../libethash-cl/CLMiner.h:17:0,
                 from /workspace/ethminer/ethminer/MinerAux.h:42,
                 from /workspace/ethminer/ethminer/main.cpp:26:
/workspace/ethminer/ethminer/../libethash-cl/CL/cl2.hpp:1829:25: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
     const cl_type get() const { return object_; }
                         ^
[100%] Linking CXX executable ethminer
```
