### ISSUE TITLE
CMake error generating ethash-cuda_generated_ethash_cuda_miner_kernel.cu.obj

### ISSUE THREAD

**Issue by estebanpw** [ethereum-mining/ethminer#2161]
Hello,
I am trying to compile ethminer from source. I am running Windows 10, Visual Studio 2017, Cmake 3.19.5, strawberry perl  5.32.1.1 and cuda_11.2.r11.2. My GPU is a 1070 gtx.

First, I cloned ethminer from this repo, ran `git submodule update --init --recursive`  and then configured the compiling script as follows:
```
@echo off
setlocal

rem add MSVC in PATH
rem call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"

rem add Perl in PATH; it's needed for OpenSSL build
rem set "PERL_PATH=C:\Perl\perl\bin"
set "PERL_PATH=C:\Strawberry\perl\bin"
set "PATH=%PERL_PATH%;%PATH%"

rem switch to ethminer's source folder
cd "%~dp0\ethminer\"

if not exist "build\" mkdir "build\"

rem For CUDA 9.x pass also `-T v140`
cmake -G "Visual Studio 15 2017 Win64" -H. -Bbuild -DETHASHCL=OFF -DETHASHCUDA=ON -DAPICORE=ON -DBINKERN=OFF ..
cmake --build . --config Release --target package

endlocal
pause

```

After launching the script (takes a while the first time to configure, afterwards compilation takes no longer than few seconds before it fails) I get the following error:

``` 
[...]
-- Configuring done
-- Generating done
-- Build files have been written to: D:/ethminer/ethminer/build
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  devcore.vcxproj -> D:\ethminer\ethminer\libdevcore\Release\devcore.lib
  hwmon.vcxproj -> D:\ethminer\ethminer\libhwmon\Release\hwmon.lib

Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/Release/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.obj
CUSTOMBUILD : nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu
-targets to suppress warning). [D:\ethminer\ethminer\libethash-cuda\ethash-cuda.vcxproj]
  CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.obj.Release.cmake:220 (message):
    Error generating
    D:/ethminer/ethminer/libethash-cuda/CMakeFiles/ethash-cuda.dir//Release/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.obj

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1. [D:\ethmine
r\ethminer\libethash-cuda\ethash-cuda.vcxproj]
```
sidenote: In the compiling tutorial it indicates **Make sure you install MSVC 2015 toolkit (v140).**.  I have tried using v141 (higher) and v140 together but no luck. If I disable v141 then the compilation fails with this error `nvcc fatal   : nvcc cannot find a supported version of Microsoft Visual Studio. Only the versions between 2017 and 20
  19 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check;
   however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at yo
  ur own risk.`

Anybody knows how I can fix this? Is it related to the spaces in the CUDA path installation? 
Thank you very much in advance for your help. If there is any other information I can supply let me know.

Esteban

**Comment by truedat101** [comment]
So the answer on this is as follows:

- you cannot simply follow the batch script to run cmake without modifications if you are going to pass the platform version , for example: if "%CUDA_VER%" NEQ "10.0" set CMAKE_ARGS=%CMAKE_ARGS% -T v140 
- You will need to specify the version of the VS kit that you want to use ... it may not be the one they provide int he example, but it might be.  See the list below for the applicable VS kit to choose.

```
  Visual Studio 17 2022        = Generates Visual Studio 2022 project files.
                                 Use -A option to specify architecture.
* Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                 Use -A option to specify architecture.
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Deprecated.  Generates Visual Studio 2010
                                 project files.  Optional [arch] can be
                                 "Win64" or "IA64".
```

- nvcc will fail if it doesn't support the version of VS that you have installed and have specified in the cmake configuration command.  In my first try, I got the exact same error message because I mistakenly added the v140 argument, which is valid, but not applicable to the VS kit I provided.  
- nvcc may also fail depending on the version of CUDA that you have installed.  I was not able to get the combination of Cuda 11 and VS2017 working properly (it gave a different error in the nvcc step).

I hope this helps.  My recommendation: VS2019, Cuda 11, cmake 3.22 (or anything supporting VS 2019), run this:
- cmake -G "Visual Studio 16 2019" -H. -Bbuild -DETHASHCUDA=ON -DAPICORE=ON -DHUNTER_JOBS_NUMBER=%NUMBER_OF_PROCESSORS%

**Comment by estebanpw** [comment]
Hello @truedat101 

Thanks a lot for taking the time to explain this and document it!

Bests,
Esteban
