### ISSUE TITLE
better instructions

### ISSUE THREAD

**Issue by GlitchNeutrino** [ethereum-mining/ethminer#2169]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I install a program that doesn't have any instructions and can't be operated with only a mouse.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. How to use the program post installation. clear and concise instructions. 

WARN [02-18|20:25:01.158] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [02-18|20:25:10.215] Looking for peers                        peercount=0 tried=4 static=0

-this seems a little confused.

**Describe alternatives you've considered**
I considered uninstalling, and then I realised there was this.

**Additional context**

download, install, that's all that can be done with this program. I wonder how anyone actually does anything else.
download, install, use. that's what I want to do.
windows connected to the pc, pc connected to the gpu, gpu connected to the mining software, and the mining software connected to.. nothing. hahaha very funny, I really laughed.

**Comment by AndreaLanfranchi** [comment]
You're confusing geth (which is an ethereum node) with ethminer which is a mining progam.
This pages are for ethminer. Nothing to do with geth
