### ISSUE TITLE
Does it run on tesla v100 gpus?

### ISSUE THREAD

**Issue by fmaggi** [ethereum-mining/ethminer#2170]
Hi i was wondering if it ran on tesla v100 gpus, thanks

**Comment by jean-m-cyr** [comment]
Because this software is outdated.

**Comment by WhymustIhaveaname** [comment]
I do not have a V100, and of course, using V100 for mining will not make any profit (because V100 is too expensive). However, I believe it can run. This worth a try. Waiting for your answer.

**Comment by fmaggi** [comment]
Yeah, I dont have one either, I was just curious. Thanks anyway
