### ISSUE TITLE
No way to utilize 4Gb card even if I have another one in same rack with 8Gb? 

### ISSUE THREAD

**Issue by MikhailKlemin** [ethereum-mining/ethminer#2173]
I have been googling around, and I can not figure the answer, the ethminer definitely crashes if I use 4Gb card along with 8Gb, unless I use only one. But I read some blog posts form nicehash where they say that if you have one 8Gb card you can use 4Gb if (they are in same rack obviously). 

I guess there is no way to kind of share DAG file between two+ video cards?

**Comment by mask8** [comment]
You could run 4gb card a bit longer by using 8GB to save some VRAM consumed by the system, but I don't think it's possible any longer. I don't think two cards can share VRAM either.
