### ISSUE TITLE
Why does it take such a long time to cmake with cuda11 branch?

### ISSUE THREAD

**Issue by lk1983823** [ethereum-mining/ethminer#2178]
**Environment (please complete the following information):**
- Operating System: [ubuntu 16.04 x86_64]
 Hardware [e.g. RTX 2080ti]
- Ethminer Version [cuda11 branch]
- Ethminer options used
I git clone the cuda11 branch and build it from source. When I run cmake .. . I find it really slowly to finish.
It shows :
```
-- [cable ] Cable 0.2.14 initialized
-- [cable ] Build type: Release
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] Calculating Config-SHA1
-- [hunter] HUNTER_ROOT: /home/lksgcc/.hunter
-- [hunter] [ Hunter-ID: 4b894e1 | Toolchain-ID: b4bd535 | Config-ID: cb395ce ]
-- [hunter] BOOST_ROOT: /home/lksgcc/.hunter/_Base/4b894e1/b4bd535/cb395ce/Install (ver.: 1.66.0)
```
And halted here for almost two hours without any progress. Is there any problem? Thanks.

**Comment by goldenduo** [comment]
I have the same problem.Is it solved?
