### ISSUE TITLE
Failing to load binary kernel

### ISSUE THREAD

**Issue by IKyriazis** [ethereum-mining/ethminer#2190]
**Describe the bug**
The ethash_gfx1030_lws128_exit.bin kernel isn't being loaded because the file path uses a linux file path instead of windows file path.

**To Reproduce**
Run ethminer.exe on a windows device with a RTX 3070 and RX 6800.

**Expected behavior**
The kernel to be loaded.

**Screenshots (Optional)**

**Environment (please complete the following information):**
- Operating System: Windows 10
- Hardware: RTX 3070, RX 6800, Ryzen 7 3100
- Ethminer Version: ethminer 0.19.0-18+commit.53e3c8dc
- Ethminer options used: -P

**Additional context**
ethminer 0.19.0-18+commit.53e3c8dc
Build: windows/release/msvc

 i 21:48:24 main     Configured pool us1.ethermine.org:5555
 i 21:48:24 <unknown> Selected pool us1.ethermine.org:5555
 i 21:48:24 <unknown> Stratum mode : Eth-Proxy compatible
 i 21:48:24 <unknown> Established connection to us1.ethermine.org [172.65.218.238:5555]
 i 21:48:24 <unknown> Spinning up miners...
cu 21:48:24 cuda-0   Using Pci Id : 21:00.0 GeForce RTX 3070 (Compute 8.6) Memory : 6.97 GB
cl 21:48:24 cl-1     Using Device : 25:00.0 gfx1030 OpenCL 2.0 AMD-APP (3188.4) Memory : 15.98 GB (17163091968 B)
 i 21:48:24 cl-1     Adjusting CL work multiplier for 30 CUs. Adjusted work multiplier: 54,614
 i 21:48:24 <unknown> Epoch : 397 Difficulty : 4.00 Gh
 i 21:48:24 <unknown> Job: d1d3b1fc... block 11917235 us1.ethermine.org [172.65.218.238:5555]
cl 21:48:26 cl-1     Generating split DAG + Light (total): 4.10 GB
 i 21:48:26 <unknown> Job: 2f9f2b83... block 11917235 us1.ethermine.org [172.65.218.238:5555]
cu 21:48:27 cuda-0   Generating DAG + Light(on GPU) : 4.17 GB
cu 21:48:27 cuda-0   Unexpected error CUDA error in func set_constants at line 112 invalid device symbol on CUDA device 21:00.0
cu 21:48:27 cuda-0   Mining suspended ...
cl 21:48:27 cl-1     OpenCL kernel
 m 21:48:29 <unknown> 0:00 A0 0.00 h - cu0 0.00, cl1 0.00
cl 21:48:29 cl-1     Loading binary kernel C:\Users\Ioannis\Desktop\ethminer\bin **HERE IS THE PROBLEM** /kernels/ethash_gfx1030_lws128_exit.bin
 X 21:48:29 cl-1     Failed to load binary kernel: C:\Users\Ioannis\Desktop\ethminer\bin/kernels/ethash_gfx1030_lws128_exit.bin
 X 21:48:29 cl-1     Falling back to OpenCL kernel...
cl 21:48:29 cl-1     Creating DAG buffer, size: 4.10 GB, free: 11.88 GB
cl 21:48:29 cl-1     Creating light cache buffer, size: 65.62 MB
cl 21:48:29 cl-1     Loading kernels
cl 21:48:29 cl-1     Creating buffer for header.
cl 21:48:29 cl-1     Creating mining buffer

**Comment by Nimloth** [comment]
Are you sure you have that file and it is because of the path that it cannot be loaded?
I am asking because looking at the repository (https://github.com/ethereum-mining/ethminer/tree/master/libethash-cl/kernels/bin), there does not seem to be a binary kernel for that hardware (yet).

**Comment by IKyriazis** [comment]
Correct. The file is missing. Thanks for pointing that out.
