### ISSUE TITLE
CMake Win10 --Build files have been written, but no ethminer.exe created

### ISSUE THREAD

**Issue by morzsa11** [ethereum-mining/ethminer#2208]
After downloading sources from Github adapting and running the sample Windows10 build script no ethminer.exe created.
 
**To Reproduce**
1. Downloaded Github repsitory
2. Installed CMake, Perl, CUDA Toolkit
3. Copied and tailored Windows specific script (https://github.com/ethereum-mining/ethminer/blob/master/docs/BUILD.md#windows-specific-script)
4. At the end of Cmake script got this, no exe generated

`  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable CLI11_ROOT is set to:

    C:/.hunter/_Base/4b894e1/ff9707f/192fd18/Install

  Environment variable CLI11_ROOT is set to:

    C:/.hunter/_Base/4b894e1/ff9707f/192fd18/Install

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: D:/Kripto/ethminer_github/ethminer/build
Error: could not load cache
Press any key to continue . . .`

5. After readings added to the CMakeLists.txt:
`if (POLICY CMP0074)
  cmake_policy(SET CMP0074 NEW)
endif()`

5. No warning, but still no exe generated
'----------------------------------------------------------------------------
-- CMake 3.20.0-rc2
-- Build  / Windows
----------------------------------------------------------------- components
-- ETHASHCL         Build OpenCL components                      ON
-- ETHASHCUDA       Build CUDA components                        ON
-- ETHASHCPU        Build CPU components (only for development)  OFF
-- ETHDBUS          Build D-Bus components                       OFF
-- APICORE          Build API Server components                  ON
-- BINKERN          Install AMD binary kernels                   ON
-- DEVBUILD         Build with dev logging                       OFF
-- USE_SYS_OPENCL   Build with system OpenCL                     OFF
----------------------------------------------------------------------------

-- Could NOT find Git (missing: GIT_EXECUTABLE)
-- [hunter] OPENSSL_ROOT: C:/.hunter/_Base/4b894e1/ff9707f/192fd18/Install (ver.: 1.1.1a)
-- [hunter] OPENCL_ROOT: C:/.hunter/_Base/4b894e1/ff9707f/192fd18/Install (ver.: 2.1-p3)
-- [hunter] CLI11_ROOT: C:/.hunter/_Base/4b894e1/ff9707f/192fd18/Install (ver.: 1.7.1)
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Kripto/ethminer_github/ethminer/build
Error: could not load cache
Press any key to continue . . .'

**Expected behavior**
I'm sorry, I'm unexperienced with CMake, just followed all instructions. 
Maybe I'm wrong, but as a result of a successful make I'd expect a binary (exe on Windows) created.

**Environment:**
- Operating System: Windows 10 64-bit
- GPU RTX3080

**Comment by ashneverdawn** [comment]
I've also run into the same issue...

**Comment by jikukanashimi** [comment]
I'm no expert whatsoever but since you're using 30xx series, I would recommend installing the latest version of CUDA and then specifying root directory via cmake:

```
cmake -D CUDA_TOOLKIT_ROOT_DIR="C:/CUDA/11.2.1" ..
```

Before building, try removing the contents of the build folder and instead of using the script, run the commands manually. I was able to compile fine using the instructions *via BUILD.md guide* but ran into issues when trying to build using latest CUDA.

I can't recall the error exactly but I ended up removing `-G "Visual Studio 15 2017 Win64" -T v140` from the cmake configuration options and it ended up automatically choosing Visual Studio 2019 as the generator (probably still useful to have **MSVC 2015 toolkit (v140)** files installed, just in case).

Once the build files had been generated successfully, I used the following to build the project: 

```
cmake --build . --config Release
```

It built successfully with some warnings but am getting 98mh/s with 3080 with lenient memory overclock.

---

Installs:
 - CMake
 - Visual Studio 2019 (w/ MSVC 2015 toolkit v140)
 - Perl (for OpenSSL)
 - CUDA Toolkit 11.2.1
 - Git (to update submodules via `git submodule update --init --recursive`)

**Comment by morzsa11** [comment]
Dear jikukanashimi!  

Thank You very much for taking time to help me. 
Based on Your instructions
-  I've installed git (it was missing) ran 'git submodule update --init --recursive'
- cleaned build dir (actually deleted the whole ethminer lib and re-downloaded it from github)
- Specified the CUDA root dir
- Ran command one-by-one
The first CMake ran sucessfully and created build files, but the second one failed with the standard 'Error: could not load cache' message. I attach the output of my command window and I found CMakeError.log and CMakeOutput.log files under /build/build/CMakeFiles. If You had some time to have a look maybe have any idea what's wrong.
It's sad that this project has become such abandoned. The creators could probably fix it in a snap..

[
[ethminer_build_commads_output.txt](https://github.com/ethereum-mining/ethminer/files/6152301/ethminer_build_commads_output.txt)
](url)

[CMakeError.log](https://github.com/ethereum-mining/ethminer/files/6152311/CMakeError.log)
[CMakeOutput.log](https://github.com/ethereum-mining/ethminer/files/6152312/CMakeOutput.log)

**Comment by jikukanashimi** [comment]
Have you tried running `cmake --build . --config Release` within the new build directory, e.g:

```
cd D:/Kripto/ethminer_github/ethminer/build/build
cmake --build . --config Release
```

Not sure why it was creating a new build directory, mine built files into the existing build directory, everything else seems to look fine to me.

Also, I did notice you were using the **Visual Studio 2017 MSBuild Command Prompt** to build, but I think this might cause problems with CUDA so if the above step works but you get issues when opening ethminer.exe, I would try rebuilding using Visual Studio 2019.

If you cmake using cmd prompt, it should automatically locate the correct generator to use.

**Comment by morzsa11** [comment]
You were right! I issued Cmake command under /build/build (instead of /build) and it started to work.
At the end of the output there's neither error not 'OK' message, but if You rollback a little bit there are errors with ethash_cuda... generation. I attach the new command output.
[ethminer_build_commads_output2.txt](https://github.com/ethereum-mining/ethminer/files/6152432/ethminer_build_commads_output2.txt)

**Comment by jikukanashimi** [comment]
Hmmm, maybe try generating build files from scratch (clear build directory) and then do the following only:

```
cmake -D CUDA_TOOLKIT_ROOT_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2"
```

Then, if no errors: `cmake --build . --config Release`

It's possible the error is caused due to building with Visual Studio 2017 (but I have no clue, to be honest lol)

**Comment by morzsa11** [comment]
OK, I'll try it tomorrow. And also with VS 2019 and I'll get back with the results.

**Comment by morzsa11** [comment]
Finally, I managed to build ethminer!!!
Stayed with VS2017. Examining the earlier attached build log, we can see that it wasn't able to build cuda part.
I really can't tell what helped (sorry), I just tried and tried and whoops-wow it succeded.
The final /ultimate build was, which I ran manually line by line in a cmd window:
@jikukanashimi Thank's again for Your help!
`echo off
setlocal
rem add MSVC in PATH
call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
rem add Perl in PATH; it's needed for OpenSSL build
set "PERL_PATH=C:\Perl64\bin"
set "PATH=%PERL_PATH%;%PATH%"
rem switch to ethminer's source folder
cd "%~dp0\ethminer\"
if not exist "build\" mkdir "build\"
rem For CUDA 9.x pass also `-T v140`
cmake -D CUDA_TOOLKIT_ROOT_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2" -G "Visual Studio 15 2017 Win64" -H. -Bbuild -DETHASHCL=OFF -DETHASHCUDA=ON -DAPICORE=ON -DETHDBUS=OFF ..
cmake --build . --config Release
endlocal
pause`

**Comment by morzsa11** [comment]
_Bottom line:
The whole 'project' was because I wanted ethminer, the dev-fee free Ethereum miner. 
Pre-built exe didn't work on RTX3080, gave me 'Unexpected error CUDA error in func set_constants at line 124 invalid device symbol on CUDA device' error. Then I wanted to build myself.
The result: After changing from PhoenixMiner to ethminer, hash rate with fell from ~92MH/s to 98MH/s. By changing GPU settings I was able to get it up to ~96MH/s.
BUT my ernings measured at the pool (ethermine) dropped by 20%(!) measured in a 24h period.
So I went back to dev-fee-d miner because it stiil makes me more money. That's it._

**Comment by jikukanashimi** [comment]
Nice!! I'm glad you were able to get things working and I do agree with the slight performance drop. I believe this has been the case since earlier versions and so switching to a more profitable miner makes sense.

I personally opted to use the ethminer project for my personal gaming/mining rig due to the recent NiceHash / PhoenixMiner drama so I don't mind the drop in hash, as long as I know that the code is clean 😅 

Still using PhoenixMiner on my standalone rigs, but am interested to hear what `dev-fee-d miner` is. Is it open source?

**Comment by morzsa11** [comment]
Hi! The other miner is PhoenixMiner. Tried also T-Rex they arr very similar in performance. I'm making more comparison to see which is better, but the diff won't be high for sure.
