### ISSUE TITLE
Alternative OpenCL kernels

### ISSUE THREAD

**Issue by chfast** [ethereum-mining/ethminer#221]
1. ethash-new from sgminer
   https://github.com/genesismining/sgminer-gm/blob/master/kernel/ethash-new.cl

   Should be superior to 2 others from sgminer.

**Comment by DeadManWalkingTO** [comment]
Is it better? Any results?

**Comment by EoD** [comment]
I think here is an "up for grabs" tag missing.

**Comment by chfast** [comment]
@goobur, is this done?

**Comment by goobur** [comment]
Yes, the "unstable" kernel is based off of the sg miner kernels. They're better if you choose the right worksizes.

**Comment by EoD** [comment]
@goobur I don't think you are talking about the same thing as the original issue here.

I just did a simple diff between sgminer's [ethash.cl](https://github.com/genesismining/sgminer-gm/blob/master/kernel/ethash.cl) and [ethash-new.cl](https://github.com/genesismining/sgminer-gm/blob/master/kernel/ethash-new.cl) and the main difference seems to be the usage of ``MIX()`` and new ``amd_bitalign`` functions. I can find neither of them in ethminer's [CLMiner_kernel_experimental.cl](https://github.com/ethereum-mining/ethminer/blob/18b0c2aa0b8d0a407f58516b0bc897ac18a3c92e/libethash-cl/CLMiner_kernel_experimental.cl). Just search for ``v_alignbit_b32``.

@chfast Imho this has to be reopened with a "up for grabs" tag.

**Comment by goobur** [comment]
I misunderstood your comparison. Yes, there's only a slight difference between ethhash-new and ethhash from sg-miner. There's the asm bitalign which might be useful to port in (although, I have doubts about the compiler in the driver picking up on that, likely it's for use with LLVM).  The MIX function is just exploding the mixhash part out -- it should be the same as fully unrolling the mix loop.

There's also a big difference in how default ethminer kernel and default sgminer kernel share data in the mix-hash. Default ethminer does it in 8 threads per hash, sgminer does it in 4 (experimental in ethminer is the most robust, and does it with 1,2,4,8 -- the only parameters that make sense). What will give you the fastest results depends on multiple things, but worksize and register usage are important keep track of. For example claymore's kernel is 8TPH and uses 64 registers. But this hits the mem controller too hard (maybe not hard, but the access pattern kills performance -- having all those waves running is apparently too much for it), so he has to artificially set it to use more (94 vgpr regs on some architectures like ellesmere, but some can handle having it set 64, like vega). For dual mining, he sets it to 64 and uses the other waves for the other coin. The takeaway of this is that writing a single kernel that works well on all AMD platforms is harder than you might suspect -- this is why I have multiple variations in my private kernels.

But that's a digression -- the important stuff from the sgminer kernel is already in the experimental kernel. You could (and I encourage you to) take the assembly bitalign function out of SG miner and see if that helps, but it'll be a very minor improvement, maybe just power consumption.
