### ISSUE TITLE
Win10 64x - Compilation Fail

### ISSUE THREAD

**Issue by mcluz** [ethereum-mining/ethminer#223]
Hi guys,

I did all the commands and all has been installed with success, but when I use the command: "cmake --builld ." i receive all this errors:

Build FAILED.

"C:\Users\Mauro\Downloads\ethminer-master\ethminer-master\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Mauro\Downloads\ethminer-master\ethminer-master\build\ethminer\ethminer.vcxproj" (default target) (8) ->
(Link target) ->
  LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library [C:\Users\Mauro\Downloads\ethminer-master\ethminer-master\build\ethminer\ethminer.v
cxproj]

"C:\Users\Mauro\Downloads\ethminer-master\ethminer-master\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Mauro\Downloads\ethminer-master\ethminer-master\build\ethminer\ethminer.vcxproj" (default target) (8) ->
(Link target) ->
  jsonrpccpp-client.lib(httpclient.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\Users\Mauro\Downloads\ethminer-mast
er\ethminer-master\build\ethminer\ethminer.vcxproj]
  jsonrpccpp-client.lib(httpclient.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\Users\Mauro
\Downloads\ethminer-master\ethminer-master\build\ethminer\ethminer.vcxproj]
  jsonrpccpp-client.lib(client.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\Users\Mauro\Downloads\ethminer-master\e
thminer-master\build\ethminer\ethminer.vcxproj]
  jsonrpccpp-client.lib(client.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\Users\Mauro\Dow
nloads\ethminer-master\ethminer-master\build\ethminer\ethminer.vcxproj]
  jsonrpccpp-client.lib(batchcall.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\Users\Mauro\Downloads\ethminer-maste
r\ethminer-master\build\ethminer\ethminer.vcxproj]
  jsonrpccpp-client.lib(batchcall.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\Users\Mauro\
Downloads\ethminer-master\ethminer-master\build\ethminer\ethminer.vcxproj]
  jsonrpccpp-client.lib(batchresponse.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\Users\Mauro\Downloads\ethminer-m
aster\ethminer-master\build\ethminer\ethminer.vcxproj]
  jsonrpccpp-client.lib(batchresponse.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\Users\Ma
uro\Downloads\ethminer-master\ethminer-master\build\ethminer\ethminer.vcxproj]
  jsonrpccpp-client.lib(rpcprotocolclient.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\Users\Mauro\Downloads\ethmin
er-master\ethminer-master\build\ethminer\ethminer.vcxproj]
  jsonrpccpp-client.lib(rpcprotocolclient.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\User
s\Mauro\Downloads\ethminer-master\ethminer-master\build\ethminer\ethminer.vcxproj]
  jsonrpccpp-common.lib(exception.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\Users\Mauro\Downloads\ethminer-maste
r\ethminer-master\build\ethminer\ethminer.vcxproj]
  jsonrpccpp-common.lib(exception.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\Users\Mauro\
Downloads\ethminer-master\ethminer-master\build\ethminer\ethminer.vcxproj]
  jsonrpccpp-common.lib(errors.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\Users\Mauro\Downloads\ethminer-master\e
thminer-master\build\ethminer\ethminer.vcxproj]
  jsonrpccpp-common.lib(errors.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\Users\Mauro\Dow
nloads\ethminer-master\ethminer-master\build\ethminer\ethminer.vcxproj]
  jsoncpp.lib(json_value.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\Users\Mauro\Downloads\ethminer-master\ethmine
r-master\build\ethminer\ethminer.vcxproj]
  jsoncpp.lib(json_value.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\Users\Mauro\Downloads
\ethminer-master\ethminer-master\build\ethminer\ethminer.vcxproj]
  jsoncpp.lib(json_reader.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\Users\Mauro\Downloads\ethminer-master\ethmin
er-master\build\ethminer\ethminer.vcxproj]
  jsoncpp.lib(json_reader.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\Users\Mauro\Download
s\ethminer-master\ethminer-master\build\ethminer\ethminer.vcxproj]
  jsoncpp.lib(json_writer.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\Users\Mauro\Downloads\ethminer-master\ethmin
er-master\build\ethminer\ethminer.vcxproj]
  jsoncpp.lib(json_writer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\Users\Mauro\Download
s\ethminer-master\ethminer-master\build\ethminer\ethminer.vcxproj]
  C:\Users\Mauro\Downloads\ethminer-master\ethminer-master\build\ethminer\Debug\ethminer.exe : fatal error LNK1319: 20 mismatches detected [C:\Users\Mauro\Downloads\ethminer-master\ethminer
-master\build\ethminer\ethminer.vcxproj]

    1 Warning(s)
    21 Error(s)

Could anybody help me about it?

PS: I have CMake and Visual Studio 2015 with C++ compiler installed in my computer.

Thanks!!!

**Comment by EoD** [comment]
First of all, I highly recommend to put error messages in `` ``` `` quotes, see https://guides.github.com/features/mastering-markdown/.

I am not sure what is happening at your setup, but as the linker complains, I assume your project setup is somehow wrong.

Apart from that, is there a reason you want to build it yourself? You could also just use the nightly builds from https://ci.appveyor.com/project/ethereum-mining/ethminer
The current build is: https://ci.appveyor.com/project/ethereum-mining/ethminer/build/job/177q9a3se29ko8fx/artifacts

**Comment by mcluz** [comment]
Hi "EoD", thanks for your time. I did all the steps again and all works fine after a windows restart.
