### ISSUE TITLE
Make EthashCUDAMiner.cpp 

### ISSUE THREAD

**Issue by monodrone** [ethereum-mining/ethminer#224]
I am on 

`
Linux 1080Ti 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

and I have these issues with EthashCUDAMiner.cpp  file :
```
Scanning dependencies of target ethminer
[ 97%] Building CXX object ethminer/CMakeFiles/ethminer.dir/main.cpp.o
[100%] Linking CXX executable ethminer
/home/paul/github/cpp-ethereum/libethcore/EthashCUDAMiner.cpp: In member function ‘workLoop’:
/home/paul/github/cpp-ethereum/libethcore/EthashCUDAMiner.cpp:202:96: warning: ‘startN’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   m_miner->search(w.headerHash.data(), upper64OfBoundary, *m_hook, (w.exSizeBits >= 0), startN);
                                                                                                ^
/home/paul/github/cpp-ethereum/libethcore/EthashCUDAMiner.cpp:199:12: note: ‘startN’ was declared here
   uint64_t startN;
            ^
/tmp/ccpcGeqs.ltrans23.ltrans.o:<artificial>:__fatDeviceText: error: undefined reference to 'fatbinData'
collect2: error: ld returned 1 exit status
ethminer/CMakeFiles/ethminer.dir/build.make:118: recipe for target 'ethminer/ethminer' failed
make[2]: *** [ethminer/ethminer] Error 1
CMakeFiles/Makefile2:493: recipe for target 'ethminer/CMakeFiles/ethminer.dir/all' failed
make[1]: *** [ethminer/CMakeFiles/ethminer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by simonkern** [comment]
which command was invoked?

**Comment by monodrone** [comment]
cmake -DBUNDLE=cudaminer ..

But now cmake work works fine, I was doing sudo without exported variables (so "su as root"):

```
export LD_LIBRARY_PATH="/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/lib64/stubs"
export PATH="$PATH:/usr/local/cuda-8.0/"
export PATH="$PATH:/usr/local/cuda-8.0/bin"

```
The new issue is with make

`make -j$(cat /proc/cpuinfo | grep processor | wc -l)
`

`/clone_unique/hash_miner/Ethereum/beta_updates/cpp-ethereum/libethcore/EthashCUDAMiner.cpp: In member function ‘workLoop’:
/clone_unique/hash_miner/Ethereum/beta_updates/cpp-ethereum/libethcore/EthashCUDAMiner.cpp:202:96: warning: ‘startN’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   m_miner->search(w.headerHash.data(), upper64OfBoundary, *m_hook, (w.exSizeBits >= 0), startN);
                                                                                                ^
/clone_unique/hash_miner/Ethereum/beta_updates/cpp-ethereum/libethcore/EthashCUDAMiner.cpp:199:12: note: ‘startN’ was declared here
   uint64_t startN;
            ^
/tmp/ccySxNYV.ltrans23.ltrans.o:<artificial>:__fatDeviceText: error: undefined reference to 'fatbinData'
collect2: error: ld returned 1 exit status
ethminer/CMakeFiles/ethminer.dir/build.make:118: recipe for target 'ethminer/ethminer' failed
make[2]: *** [ethminer/ethminer] Error 1
CMakeFiles/Makefile2:493: recipe for target 'ethminer/CMakeFiles/ethminer.dir/all' failed
make[1]: *** [ethminer/CMakeFiles/ethminer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by hcbraun** [comment]
cmake -DCUDA_NVCC_FLAGS="-ccbin gcc-5" -DBUNDLE=cudaminer -DETHASHCL=0 -DETHASHCUDA=1 -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=c++-5 ..

**Comment by monodrone** [comment]
Same errors with updated cmake flags.

**Comment by nimbosa** [comment]
i have exactly the same issue as @monodrone above, warning on uninitialized `'startN'` and finally failed make over undefined `'fatbinData'`

**Comment by gluckez** [comment]
I can confirm this exact same issue. My compiling skills are only so so, any ideas for a workaround or a fix?

**Comment by smurfy** [comment]
What version of CUDA and system are you using?

I'm on ubuntu xenial with cuda_8.0.61_375.26 and it compiles just fine.

**Comment by gluckez** [comment]
I'm using cuda 8 on Ubuntu Xenial with the latest nvidia drivers. The problem seems to be something with one of the nvidia libraries, i'm not sure. it did compile for AMD, this went fine... until i actually ran it. I can't mine with my GPU, but i could when i compiled for amd and started mining with my cpu. this was however not very good for my computer.

**Comment by gratiot** [comment]
I'm getting the same "fatbinData" loader error as well. I'm running Ubuntu 17.04 and Cuda 9.0. 

You can set the startN variable in the code to zero and that will initialize it and get rid of that message.  

There is also a reference to compute_20 that is not liked either so just remove it from the cmake file ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.cmake 

Any solutions to the "fatbinData" issue are welcome!

**Comment by aaronpirrello** [comment]
Anyone find an answer to this issue? I'm in the same boat as gratiot. I'm going to try installing cuda 8 next.

**Comment by DeadManWalkingTO** [comment]
Any news here?

**Comment by AndreaLanfranchi** [comment]
No feed back.
Closed
