### ISSUE TITLE
RTX3070 laptop success compiled, received job but cant start mining

### ISSUE THREAD

**Issue by ShawnLau11** [ethereum-mining/ethminer#2280]
Hi, I compiled ethminer on windows 10 with cuda 11.3 on visual studio 2017, successfully compiled but when I start mining it starts occupying GPU RAM but there's no GPU usage. Received jobs but can't start mining I guess. 
There's this error:
cu 15:12:15 cuda-0   Unexpected error CUDA error in func set_constants at line 112 invalid device symbol on CUDA device 01:00.0
cu 15:12:15 cuda-0   Mining suspended ...
May I know which step I did wrong?

The full log:
---------------------------------------
C:\Crypto>ethminer.exe -P stratum1+tcp://0xb920481CCe452BF8c6C92ef71194aAA05A784260.ethMiner0@asia1.ethermine.org:4444 -U -R

ethminer 0.19.0-25+commit.4a5b7d6a
Build: windows/release/msvc

 i 15:12:13 main     Configured pool asia1.ethermine.org:4444
 i 15:12:13 <unknown> Selected pool asia1.ethermine.org:4444
 i 15:12:13 <unknown> Stratum mode : Eth-Proxy compatible
 i 15:12:13 <unknown> Established connection to asia1.ethermine.org [172.65.231.156:4444]
 i 15:12:13 <unknown> Spinning up miners...
cu 15:12:13 cuda-0   Using Pci Id : 01:00.0 NVIDIA GeForce RTX 3070 Laptop GPU (Compute 8.6) Memory : 6.98 GB
 i 15:12:13 <unknown> Epoch : 411 Difficulty : 4.00 Gh
 i 15:12:13 <unknown> Job: e012c469... block 12353351 asia1.ethermine.org [172.65.231.156:4444]
cu 15:12:15 cuda-0   Generating DAG + Light(on GPU) : 4.28 GB
cu 15:12:15 cuda-0   Unexpected error CUDA error in func set_constants at line 112 invalid device symbol on CUDA device 01:00.0
cu 15:12:15 cuda-0   Mining suspended ...
 i 15:12:17 <unknown> Job: 8967ae14... block 12353351 asia1.ethermine.org [172.65.231.156:4444]
 i 15:12:17 <unknown> Job: 800edf97... block 12353352 asia1.ethermine.org [172.65.231.156:4444]
 i 15:12:17 <unknown> Job: bb600688... block 12353352 asia1.ethermine.org [172.65.231.156:4444]
 i 15:12:17 <unknown> Job: e735cc3b... block 12353352 asia1.ethermine.org [172.65.231.156:4444]
 m 15:12:18 <unknown> 0:00 A0 0.00 h - cu0 0.00
 i 15:12:19 <unknown> Job: ce3d2da5... block 12353352 asia1.ethermine.org [172.65.231.156:4444]
 m 15:12:23 <unknown> 0:00 A0 0.00 h - cu0 0.00
 i 15:12:23 <unknown> Job: 833d5589... block 12353352 asia1.ethermine.org [172.65.231.156:4444]
 i 15:12:24 <unknown> Job: db335e19... block 12353353 asia1.ethermine.org [172.65.231.156:4444]
 i 15:12:24 <unknown> Job: 9fd58298... block 12353353 asia1.ethermine.org [172.65.231.156:4444]
 i 15:12:24 <unknown> Job: f4bef734... block 12353353 asia1.ethermine.org [172.65.231.156:4444]
 i 15:12:25 <unknown> Job: 47dac86d... block 12353353 asia1.ethermine.org [172.65.231.156:4444]
 i 15:12:25 <unknown> Job: cf4d51eb... block 12353353 asia1.ethermine.org [172.65.231.156:4444]
 i 15:12:28 <unknown> Job: 75388bdc... block 12353353 asia1.ethermine.org [172.65.231.156:4444]
 m 15:12:28 <unknown> 0:00 A0 0.00 h - cu0 0.00
 i 15:12:31 <unknown> Job: 28c15e9b... block 12353353 asia1.ethermine.org [172.65.231.156:4444]
 m 15:12:33 <unknown> 0:00 A0 0.00 h - cu0 0.00
 i 15:12:35 <unknown> Job: 60779c91... block 12353353 asia1.ethermine.org [172.65.231.156:4444]
 i 15:12:36 <unknown> Job: cac55f6c... block 12353354 asia1.ethermine.org [172.65.231.156:4444]
 i 15:12:36 <unknown> Job: 9359034c... block 12353354 asia1.ethermine.org [172.65.231.156:4444]
 i 15:12:37 <unknown> Job: 844af2d3... block 12353354 asia1.ethermine.org [172.65.231.156:4444]
 m 15:12:38 <unknown> 0:00 A0 0.00 h - cu0 0.00
 i 15:12:41 <unknown> Job: a51c29f5... block 12353354 asia1.ethermine.org [172.65.231.156:4444]
 m 15:12:43 <unknown> 0:00 A0 0.00 h - cu0 0.00
 i 15:12:45 <unknown> Job: 375c50dd... block 12353354 asia1.ethermine.org [172.65.231.156:4444]
 m 15:12:48 <unknown> 0:00 A0 0.00 h - cu0 0.00
---------------------------------------
Took GPU RAM but no GPU usage:
![1](https://user-images.githubusercontent.com/45129137/116805430-1f453380-ab59-11eb-9255-d82e5a6dfe5b.PNG)

**Environment (please complete the following information):**
- Operating System: Windows 10
- Hardware: RTX3070 laptop
- Ethminer Version: ethminer 0.19.0-25+commit.4a5b7d6a | Cleaned temp changes for benchmarking / testing {{Troy Neubauer}}  @TroyNeubauer
- Ethminer options used:  ethminer.exe -P stratum1+tcp://0x***@asia1.ethermine.org:4444 -U -R

**Comment by ShawnLau11** [comment]
Able to solve with ethminer 0.19.0-20+commit.4d2ad602 #2133
Thanks @hackmod

**Comment by encoderlee** [comment]
![image](https://user-images.githubusercontent.com/9878012/146749463-a069f400-4434-461f-8146-49761f70007d.png)
insert
list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_86,code=sm_86")
into file
libethash-cuda/CMakeLists.txt
then rebuild to support RTX30xx gpu
