### ISSUE TITLE
MacOS Catalina etherminer crashes

### ISSUE THREAD

**Issue by ganzocrypt** [ethereum-mining/ethminer#2311]
I have build etherminer on Catalina OS but as soon as I execute it I get the following error and a crash:

`ethminer 0.19.0+commit.1a52862e.dirty
Build: darwin/release/appleclang

 i 19:11:39          Configured pool eu1.ethermine.org:4444
 i 19:11:39          Selected pool eu1.ethermine.org:4444
 i 19:11:39          Stratum mode : Stratum
 i 19:11:39          Established connection to eu1.ethermine.org [172.65.207.106:4444]
 i 19:11:39          Spinning up miners...
cl 19:11:39 cl-0     Using Device : GPU:00 AMD Radeon RX 580 Compute Engine OpenCL 1.2  Memory : 8.00 GB (8589934592 B)
 i 19:11:39          Authorized worker address.RX580
 i 19:11:39          Epoch : 416 Difficulty : 4.29 Gh
 i 19:11:39          Job: edc5fd44… eu1.ethermine.org [172.65.207.106:4444]
cl 19:11:47 cl-0     Generating split DAG + Light (total): 4.25 GB
 i 19:11:47          Job: 89c7a795… eu1.ethermine.org [172.65.207.106:4444]
 m 19:11:47          0:00 A0 0.00 h - cl0 0.00
 i 19:11:47          Job: 6ea13461… eu1.ethermine.org [172.65.207.106:4444]
cl 19:11:47 cl-0     OpenCL kernel
 X 19:11:47 cl-0     OpenCL kernel build log:
Error returned by cvms_element_build_from_source
 X 19:11:47 cl-0     OpenCL kernel build error (-11):
clBuildProgram
SIGSEGV encountered ...
stack trace:
backtrace() returned 6 addresses
0   ethminer                            0x00000001020011a5 _ZN8MinerCLI13signalHandlerEi + 277
1   libsystem_platform.dylib            0x00007fff6a3255fd _sigtramp + 29
2   ???                                 0x0000000000000000 0x0 + 0
3   ethminer                            0x000000010207329d _ZNSt3__1L14__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3dev6Worker12startWorkingEvE3$_0EEEEEPvSB_ + 141
4   libsystem_pthread.dylib             0x00007fff6a331109 _pthread_start + 148
5   libsystem_pthread.dylib             0x00007fff6a32cb8b thread_start + 15
SIGSEGV encountered ...
stack trace:
backtrace() returned 9 addresses
`

**Comment by ivanocj** [comment]
I'm having the same exact error with my RX580 on Catalina! Did you get this issue resolved?

**Comment by ganzocrypt** [comment]
no but I recompiled [xmrig](https://github.com/ganzocrypt/xmrig-macos/releases/tag/v6.13.0-dev-macos) for macos from a developer that fixed some issues with OpenCL and Xmrig, it works and can mine with cpu and gpu

**Comment by ivanocj** [comment]
> no but I recompiled [xmrig](https://github.com/ganzocrypt/xmrig-macos/releases/tag/v6.13.0-dev-macos) for macos from a developer that fixed some issues with OpenCL and Xmrig, it works and can mine with cpu and gpu

Ok. I already run xmrig for monero. XMRIG is used for Cpu mining coins... all coins there if you try with GPU it will give you a worse hash than when using CPU's ... Thus it cannot mine Eth... 😔

**Comment by ganzocrypt** [comment]
you can use one of those services that do autoe xchange like unminable, use kawpow to mine ETH, not same hashrate!
Unfortunately OpenCL on macOS is not supported anymore, but better than nothing. Give it a try!
