### ISSUE TITLE
compile success on one windows pc, ethminer.exe run ok on this pc, but not on another

### ISSUE THREAD

**Issue by muziling** [ethereum-mining/ethminer#2312]
compile success on one windows pc, "ethminer.exe -h" run and output help on this pc
copy ethminer.exe to another pc( not install cuda,perl ,git,cmake)  ,"ethminer.exe -h" output nothing, 
open windows task manger, not see ethminer.exe process,  
I have check md5 of ethminer.exe ,  same  on two windows pc.  
Why can not run on another pc?

**Comment by viperguynaz** [comment]
there's a sub-folder "kernels" with a ton of binary files. Did you copy that as well?

**Comment by muziling** [comment]
Found the folder: ethminer\build\_CPack_Packages\win64\ZIP,  thanks
