### ISSUE TITLE
Not all Nvidia GPUs devices detected by Ethminer but successfully listed on nvidia-smi

### ISSUE THREAD

**Issue by marcofariasmx** [ethereum-mining/ethminer#2313]
**Describe the bug**
I currently have 4 x Tesla V100-SXM2-32GB installed in the server that I am working on. The nvidia-smi detects them succesfully but ethminer does not. One interesting thing is that on nvidia-smi all 4 cards seem to have a process running (or at least occupying memory) but one of them not as fully as the other 3.

**To Reproduce**
1) Execute ethminer --M 0 to start tests.
2) In a separate terminal window run "nvidia-smi" to confirm all 4 GPU devices are up and running.
3) Execute ethminer --list-devices to verify that only 3 out of 4 GPUs were successfully detected by ethminer.

**Expected behavior**
To detect all 4 GPUs installed

**Screenshots (Optional)**
nvidia-smi
![Screen Shot 2021-05-28 at 13 23 31](https://user-images.githubusercontent.com/41245794/120029110-473e8000-bfbb-11eb-8985-32355dcc5cb1.png)

ethminer --list-devices
![Screen Shot 2021-05-28 at 13 24 09](https://user-images.githubusercontent.com/41245794/120029140-4f96bb00-bfbb-11eb-8bd4-ca1630fab4e6.png)

**Environment (please complete the following information):**
- Operating System: RHEL 7.6
- Hardware 4 x Tesla V100-SXM2-32GB  running on a Power9 ppc64le architecture server.
- Ethminer Version 0.19.0
- Ethminer options used:
    ethminer --M 0
    ethminer --list-devices

**Additional context**
No additional context for now.

Thank you for your time and interest to help.

**Comment by hibagus** [comment]
I had the same problem before.
Please see my pull req here on how to fix the problem.

https://github.com/ethereum-mining/ethminer/pull/2101

Sadly, the developer has not actively integrated my fix.

**Comment by marcofariasmx** [comment]
> I had the same problem before.
> Please see my pull req here on how to fix the problem.
> 
> #2101
> 
> Sadly, the developer has not actively integrated my fix.

@hibagus That solved my issue, thank you very much for the insight. Will be closing this issue.
