### ISSUE TITLE
hash_types.hpp missing (trying to compile ethminer_V18 from source)

### ISSUE THREAD

**Issue by inprosys** [ethereum-mining/ethminer#2330]
EthashAux.h refrences ethash.hpp which references hash_types.hpp.

I cannot find "hash_types.hpp" anywhere. I have searched all of github. I have googled for any references to it and can only find it mentioned in a doxygen map. 

OK. I imagine that it's in a ethash library somewhere. So where is it please?

(BTW. There are multiple references to <json/json.h> but json.h does not exist in the json folder. I substituted a json.hpp from another library but who knows what corruption that will introduce. Stay tuned.)

**Comment by Spudz76** [comment]
Did Hunter locate and install all the deps (Boost 1.66...)

**Comment by inprosys** [comment]
I have Boost 1.76 (current) and hash_types.hpp it not anywhere in that collection of libraries. I finally found a copy on github in the hyperledger/iroha project code. I'm closing this issue.

**Comment by Spudz76** [comment]
My bad assumption it was from Boost, however it is pulled down by Hunter in general so something is wrong with your dependencies or Hunter is broken.

`/root/.hunter/_Base/4b894e1/51efd6e/cb395ce/Install/include/ethash/hash_types.hpp`

It is in the `.hunter` tree so it's part of one of the deps (not Boost).  I know hunter has problems downloading the Boost-1.66 file and you have to manually grab it and place in the Hunter tree and then rerun it so it can unpack and prepare the deps correctly.  Perhaps it crashed on Boost and then you used a system-installed Boost (1.76) and abandoned Hunter which also needed to get more deps (but won't unless it can process Boost 1.66).

**Comment by Spudz76** [comment]
Should look like this during cmake step

```
-- [cable ] Build type: Release
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] Calculating Config-SHA1
-- [hunter] HUNTER_ROOT: /root/.hunter
-- [hunter] [ Hunter-ID: 4b894e1 | Toolchain-ID: 51efd6e | Config-ID: cb395ce ]
-- [hunter] BOOST_ROOT: /root/.hunter/_Base/4b894e1/51efd6e/cb395ce/Install (ver.: 1.66.0)
-- [hunter] BOOST_ROOT: /root/.hunter/_Base/4b894e1/51efd6e/cb395ce/Install (ver.: 1.66.0)
-- [hunter] BOOST_ROOT: /root/.hunter/_Base/4b894e1/51efd6e/cb395ce/Install (ver.: 1.66.0)
-- [hunter] BOOST_ROOT: /root/.hunter/_Base/4b894e1/51efd6e/cb395ce/Install (ver.: 1.66.0)
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- [hunter] JSONCPP_ROOT: /root/.hunter/_Base/4b894e1/51efd6e/cb395ce/Install (ver.: 1.8.0)
-- [hunter] ETHASH_ROOT: /root/.hunter/_Base/4b894e1/51efd6e/cb395ce/Install (ver.: 0.4.3)
```

And the `ETHASH_ROOT` is where `hash_types.hpp` comes from.  If it doesn't do the hunter stuff right then the path won't be in the includes for it to find the file wherever hunter put it.
