### ISSUE TITLE
Please, builds with CUDA 11. x for RTX3060 Windows 10

### ISSUE THREAD

**Issue by Nikolaev-Nikolay** [ethereum-mining/ethminer#2361]
Guys make a new builds with CUDA 11. x for RTX3060 Windows 10 please!
2 years have passed, there will be a movement forward.

**Comment by guojx1998** [comment]
There was one working perfectly for rtx3060 under windows 10 here,
https://ci.appveyor.com/project/ethereum-mining/ethminer/builds/37485839
according to https://github.com/ethereum-mining/ethminer/issues/2166
But now the binary is get deleted. If you trust me, I have a copy of the binary.
[ethminer-0.19.0-17+commit.23d537a0-cuda11.1.0-windows-amd64.zip](https://github.com/ethereum-mining/ethminer/files/7271425/ethminer-0.19.0-17%2Bcommit.23d537a0-cuda11.1.0-windows-amd64.zip)

**Comment by Nikolaev-Nikolay** [comment]
O, it's ок! I'm build version  ethminer-0.19.0-17+commit.23d537a0-cuda11.1.0 ...cuda 11.3
Boost version: 1.66.0
Thank you!
