### ISSUE TITLE
Do you still use a proxy?

### ISSUE THREAD

**Issue by nguylb73** [ethereum-mining/ethminer#237]
I've been receiving 1-4% stale shares with Ethermine.org on my two rigs. I wonder if using a proxy would help? I see a lot of articles written for stratum proxy back in 2016, nothing really for 2017. I wonder if this is still relevant.

**Comment by Git1Hub2** [comment]
With eth-proxy I noticed a good improvement "average 15%"

**Comment by atyenoria** [comment]
+1

**Comment by ddobreff** [comment]
Due to lowered blocktime(14s vs 30s) its normal stale shares to increase a bit.

**Comment by DeadManWalkingTO** [comment]
I never use proxy. I believe there is no reason for that.
