### ISSUE TITLE
Rewarded miner found block in 10 seconds more than solution found with ethminer

### ISSUE THREAD

**Issue by ptykamikaze** [ethereum-mining/ethminer#2388]
**Describe the bug**
First of all, sorry for my english, second, sorry for my lack of knowledge. I really don't know if this is a bug because I'm starting to understand how mining works. My problem / question is:

I ran ethminer.exe and received this notification from the pool (us-solo-eth.2miners.com:6060) at 13:46:40

```
 i 13:46:40 <unknown>  << {"id":0,"jsonrpc":"2.0","method":"mining.notify","params":["0x9bb5108db60e11d879a5db575ce37149794b52ba067495534b0e67b18be7fa03","0x9bb5108db60e11d879a5db575ce37149794b52ba067495534b0e67b18be7fa03",
"0x0ae1dc880080eca07b1a976949eb91b4f67fa533a59767f24c2e1d332182a024","0x3f00000003f00000003f00000003f00000003f00000003f00000003f",true],"height":13766441}
```

and 1 second later I see this in the log

```
cu 13:46:41 cuda-1   Job: 9bb5108d... Sol: 0x9f55f4790c13dee5
 i 13:46:41 <unknown>  >> {"id":41,"jsonrpc":"2.0","method":"mining.submit","params":["wallet-address","0x9bb5108db60e11d879a5db575ce37149794b52ba067495534b0e67b18be7fa03","0x9f55f4790c13dee5",
"0x9bb5108db60e11d879a5db575ce37149794b52ba067495534b0e67b18be7fa03","0xce7ad846784db7bbc743b699e82f2db4ef3d331325af11c166ff8ef46ed06b62"],"worker":"rig01"}
 i 13:46:41 <unknown>  << {"id":41,"jsonrpc":"2.0","result":true,"error":null}
 i 13:46:41 <unknown> **Accepted  65 ms. us-solo-eth.2miners.com [147.135.11.134:6060]

```

After I checked the block in etherscan.io, I can see that the rewarded miner needed 11 seconds to mine the block and up to this moment I dont understand why a person that found a solution in less time is not rewarded. Can you tell me or explain why this is happening? I see the nonce provided by the miner is 0xab2b772778436fdf which is a bigger number.

12334083015889350623 0xab2b772778436fdf  = rewarded miner 
11481351625781796581 0x9f55f4790c13dee5   = my rig 

![image](https://user-images.githubusercontent.com/5614001/145267339-d863fc7c-b974-462c-be03-433b06b334c0.png)

Thank you

**Comment by AndreaLanfranchi** [comment]
The process of mining is a bit more complex. You must keep in mind nothing is instantaneous and synchronous.
Let's try to make some reasoning on your case

- at 13:46:40 you receive a work package: that means the node at 2miners.com has created a template block (picking transactions from TxPool) and has sent each connected miner the basic data to try to solve the PoW. As in TCP there is no "broadcasting" each connected miner is notified one after the other (in a serialized loop). This may add milliseconds delay to your specific socket
- at 13:46:41 you find a solution and send it back to your pool. Your data packet takes 65ms to travel to your pool server and get verified. Ok at this point you **might** think "I've won" ... sorry but not true yet. When your pool receives your solution it seals the block and sends out the "proposed block" to other node peers connected (which might be other pools or single nodes) but ...
- ... in this 1065ms another node may have found a valid solution to the same block **but with a nonce which produces a higher hash (i.e. it complies to a higher difficulty)**. So when the other nodes also broadcast its own "block proposal" the peer nodes (which have also received the proposal from your pool) agree that the block with the higher diff becomes canonical.

It takes time to build consensus amongst nodes about which block proposal gets into the chain and for the ethereum chain is set to a minimum of 12-13 seconds

**Comment by ptykamikaze** [comment]
Thanks a lot for your quick response. I understood your explanation very well.
