### ISSUE TITLE
CUDA error in func 'search' at line 361 : the launch timed out and was terminated.

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ethereum-mining/ethminer#239]
Hi all,
first of all thank you for this excellent miner.

I am experiencing this issue : most likely due to overclocking problems it happens from time to time to register these events (I'm on several rigs with 6x NVIDIA Gtx 1050 Ti)

CUDA error in func 'search' at line 361 : the launch timed out and was terminated.
[101m[1;30m  ✘  [35m08:23:31[0m[30m|[34mCUDA4   [0m  Error CUDA mining: the launch timed out and was terminated
CUDA error in func 'search' at line 361 : the launch timed out and was terminated.
[101m[1;30m  ✘  [35m08:23:31[0m[30m|[34mCUDA5   [0m  Error CUDA mining: the launch timed out and was terminated
CUDA error in func 'search' at line 361 : the launch timed out and was terminated.
[101m[1;30m  ✘  [35m08:23:31[0m[30m|[34mCUDA2   [0m  Error CUDA mining: the launch timed out and was terminated
CUDA error in func 'search' at line 361 : the launch timed out and was terminated.
[101m[1;30m  ✘  [35m08:23:31[0m[30m|[34mCUDA1   [0m  Error CUDA mining: the launch timed out and was terminated
CUDA error in func 'search' at line 361 : the launch timed out and was terminated.
[101m[1;30m  ✘  [35m08:23:31[0m[30m|[34mCUDA3   [0m  Error CUDA mining: the launch timed out and was terminated
CUDA error in func 'search' at line 361 : the launch timed out and was terminated.
[101m[1;30m  ✘  [35m08:23:31[0m[30m|[34mCUDA0   [0m  Error CUDA mining: the launch timed out and was terminated

All 6 cards get affected by the same error and from there on the program reports hashing at 0MH/s until it gets a new job (I'm on stratum @ nanopool) which is the moment when the process gets zombied and the rig becomes unresponsive 

[32m  m  [35m08:23:32[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:33[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:34[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:35[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:36[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:37[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:38[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:39[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:40[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:41[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:42[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:43[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:44[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:45[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:46[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:47[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:48[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:49[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:50[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:51[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:52[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:53[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:54[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:55[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:56[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:57[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:58[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:23:59[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:00[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:01[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:02[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:03[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:04[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:05[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:06[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:07[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:08[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:09[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:10[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:11[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:12[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:13[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:14[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:15[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:16[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:17[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:18[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:19[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:20[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:21[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:22[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:23[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:24[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:25[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:26[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:27[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:28[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:29[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[32m  m  [35m08:24:30[0m[30m|[34methminer[0m  Mining on [96m#b0affd83…[0m : 0.00MH/s [A206+2:R19+0:F0]
[94m  ℹ  [35m08:24:31[0m[30m|[34mstratum [0m  Received new job #b0affd83[0m
[94m  ℹ  [35m08:24:31[0m[30m|[34mstratum [0m  Received new job #25f2f0e9[0m

For the sake of precision I'm on Ubuntu 16.04.2 LTS with NVIDIA drivers version 381.22 and CUDA 8
To be precise it's this package https://github.com/Cyclenerd/ethereum_nvidia_miner

Any idea about how to get around this ?
(I've tried to reduce overclocking values but it keeps happening).

Thank you.

**Comment by dro162** [comment]
Same problem.  Crashes about 20 minutes after starting.  Sometimes doesn't for a few hours.
4x 8 GB Nvidia GTX 1070
Nvidia driver 375.66 - No overclocking
Ubuntu 17.04

Usually just use ethminer --cuda
Same problem with ethminer --farm-recheck 2000 -cuda -farm http://127.0.0.1:8545/rig1 --cuda-parallel-hash 4

**Comment by Git1Hub2** [comment]
With "--farm-recheck 200"
This does not happen to me
Is to use:  Ethminer_Watchdog

**Comment by smurfy** [comment]
Having the same problem, while ethminer is faster than claymore, i always switch back to claymore after a while because its more stable. 

It crashes randomly.

7x  GTX 1070  .   Driver Version: 381.22     ArchLinux

A quick fix could be just terminate the application if an error occurs.  (maybe with different return codes)  With this its easy to have an endless loop start script for linux and windows.

**Comment by Git1Hub2** [comment]
Already tried using: https://github.com/derubm/Ethminer_Watchdog

**Comment by hcbraun** [comment]
Does the Nvidia driver log anything? You can check with:
journalctl _TRANSPORT=kernel | grep -i nvrm
Table with XID error codes:
http://docs.nvidia.com/deploy/xid-errors/

**Comment by smurfy** [comment]
@hcbraun Nope nothing at the time of the crash

**Comment by dhjw** [comment]
This is a dupe of https://github.com/ethereum-mining/ethminer/issues/72

**Comment by derubm** [comment]
@smurfy it is windows only, but you can easily use the code to build something working on linux.

**Comment by Jacxz** [comment]
I don't think it is only on Linux, I just got this on Windows 10 with 4 x GTX 1060.

```
CUDA error in func 'ethash_cuda_miner::search' at line 348 : the launch timed out and was terminated.
CUDA error in func 'ethash_cuda_miner::search' at line 348 : the launch timed out and was terminated.
CUDA error in func 'ethash_cuda_miner::search' at line 348 : the launch timed out and was terminated.
  X  02:22:34|CUDA2     Error CUDA mining: the launch timed out and was terminated
  X  02:22:34|CUDA3     Error CUDA mining: the launch timed out and was terminated
  X  02:22:34|CUDA0     Error CUDA mining: the launch timed out and was terminated
CUDA error in func 'ethash_cuda_miner::search' at line 348 : the launch timed out and was terminated.
  X  02:22:34|CUDA1     Error CUDA mining: the launch timed out and was terminated
```

**Comment by DeadManWalkingTO** [comment]
After #757 (added --exit parameter to exit whenever an error occurred) you can use a watchdog.

Try [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) Windows7/8/10 [32/64] & Linux (Any Dist/Any Ver/Any Arch) (#735).

Check and feedback please.
Thank you!

**Comment by Goranbol** [comment]
Wtf ??
Anybody has a solution ,maybe ?
Cuda error in func 'quark_blake512_cpu_setBlock_80' at line 547 : the launch timed out and was terminated.

**Comment by AndreaLanfranchi** [comment]
It's always related to excessive overclocking.

**Comment by SolWax** [comment]
Excessive overclocking is not it. Read. You posted this error related to 3 others and one guy said his gpu was "out the box".

**Comment by ddobreff** [comment]
quark_blake512_cpu_setBlock_80
This is not ethminer!
