### ISSUE TITLE
Problem Running CUDA 11.5 on Ubuntu

### ISSUE THREAD

**Issue by xaliander** [ethereum-mining/ethminer#2400]
**The error:**
When using `make` to build ethminer as advised in step 5 of the [instructions](https://github.com/ethereum-mining/ethminer/blob/master/docs/BUILD.md), the following error occurs: 
```
ethash_cuda_miner_kernel.h:8:10: fatal error: cuda_runtime.h: No such file or directory
    8 | #include "cuda_runtime.h"
```

**The reason:**
As described by @aloisklink in [his reply](https://github.com/ethereum-mining/ethminer/commit/8f48e43f9232655340badc626863e88cbc960b73#commitcomment-62989739), the error can occur, if multiple versions of CUDA are installed and CMake is confused about which CUDA version to use. 

**The solution:**
According to [Yamaneko's answer](https://stackoverflow.com/a/58996096) on stackoverflow, setting CPATH and LD_LIBRARY_PATH solves this problem. This can be done by appending the following lines of code to the `~/.bashrc` file.
```
export CPATH=/usr/local/cuda-10.1/targets/x86_64-linux/include:$CPATH
export LD_LIBRARY_PATH=/usr/local/cuda-10.1/targets/x86_64-linux/lib:$LD_LIBRARY_PATH
export PATH=/usr/local/cuda-10.1/bin:$PATH
```

**Pay attention to the user!**
I had already played around with symlinks and adding the PATH to the `~/.bashrc` file. However, the error still prevailed! 
What gives? After running `cmake ..` I used `sudo make` instead of just `make`. Using only `make` solved the problem for me.

**Question:**
It seems to me like the transition from the instructions that state `sudo make install` to `sudo make` is logical, when I don't want to go ahead with the install procedure yet. I suppose the superuser is not influenced by the `~/.bashrc` entry and therefore CMake is confused when using sudo. Could that be? Is there any way to define the PATHs for all users?

**Comment by aloisklink** [comment]
> I suppose the superuser is not influenced by the ~/.bashrc entry and therefore CMake is confused when using sudo. Could that be? Is there any way to define the PATHs for all users?

Yep, that's the reason why :smile:

If you want to add something to the path of all users, most Linux distros support adding it to `/etc/profile` or `/etc/environment` (or the folders `/etc/profile.d` and `/etc/environment.d`. However, I don't know if `sudo` uses that. For security reasons, `sudo` usually removes lots of the environment vars like `PATH`.

I'd recommend always running `make` first **without** `sudo`. E.g. `make` then `sudo make install`. You should only use `sudo` when you need to for security. Plus, running `sudo make` can add admin files all over your user folders, which can break future commands.
