### ISSUE TITLE
Windows detected ehminer.exe as a threat Presenoker

### ISSUE THREAD

**Issue by ZBregov** [ethereum-mining/ethminer#2402]
Online it says that presenoker is a pop up virus that effects the browser, it happend just today even tho i was using it for way longer.
What do i do? My computer that i mine on is just my own pc.

**Comment by mcl1080** [comment]
Same, on windows cuda10,  0.18 and 0.19 alpha

**Comment by ZBregov** [comment]
> In windows security, click on app & browser control, then Reputation-based protection settings, then under Potentially unwanted app blocking, turn it off. this will allow ethminer to run again, but could make your pc vulnerable to actual unwanted programs, so be careful. 

There is an option to specifically only allow that program, but it seems very weird that just now windows is concerned about it. And it's not worried much about the app as its not automatically put in quarantine

**Comment by smurfy** [comment]
It is normal that virus programs detect miners as viruses/unwanted programs. 
Its for the protection of normal users. 

Basically add the folder/exe to your exception list of you virus scanner and be done with it.

Also try to either self-compile  or use a pre build exe from the release page, to make sure you are not getting something nasty if you download ethminer from somewhere else.
