### ISSUE TITLE
New Nvidia driver (384.59) breaks ethminer

### ISSUE THREAD

**Issue by impynutz** [ethereum-mining/ethminer#241]
After upgrade ethminer does no find any opencl device. With cuda flag I get:
terminate called after throwing an instance of 'std::runtime_error'
  what():  unknown error
Aborted (core dumped)

**Comment by Git1Hub2** [comment]
Did you try reinstalling the driver? I'm using (385.28)

**Comment by impynutz** [comment]
Ok, maybe this is a linux related issue. Downgrading the driver helps

**Comment by chfast** [comment]
Usually restart helps.
