### ISSUE TITLE
Code cleanup suggestion for better readability and maintainability

### ISSUE THREAD

**Issue by YanBellavance** [ethereum-mining/ethminer#247]
This version of the code has optimised "state machine" sequence of states (sequential with no wraparound  from one loop iteration to the next):

```cpp
uint64_t batch_size = s_gridSize * s_blockSize;
for (; !exit; m_current_index++, m_current_nonce += batch_size)
{
    auto stream_index = m_current_index % s_numStreams;
    cudaStream_t stream = m_streams[stream_index];
    volatile uint32_t* buffer = m_search_buf[stream_index];
    uint64_t nonces[SEARCH_RESULT_BUFFER_SIZE - 1];
    uint64_t nonce_base = m_current_nonce - s_numStreams * batch_size;

    if (m_current_index >= s_numStreams)
    {
        CUDA_SAFE_CALL(cudaStreamSynchronize(stream));
        if (buffer[0] > 0)
        {
            nonces[0] = nonce_base + buffer[1];
            buffer[0] = 0;
            exit = hook.found(nonces, 1);
        }
        exit |= hook.searched(nonce_base, batch_size);
    }
    run_ethash_search(s_gridSize, s_blockSize, m_sharedBytes, stream, buffer, m_current_nonce, m_parallelHash);
}
```

**Comment by YanBellavance** [comment]
I will try to make a pull request as soon as I can

**Comment by YanBellavance** [comment]
This version of the code has optimised "state machine" sequence of states (sequential with no wraparound  from one loop iteration to the next):

`
		

	uint64_t batch_size = s_gridSize * s_blockSize;
	for (; !exit; m_current_index++, m_current_nonce += batch_size)
	{
		auto stream_index = m_current_index % s_numStreams;
		cudaStream_t stream = m_streams[stream_index];
		volatile uint32_t* buffer = m_search_buf[stream_index];
		uint64_t nonces[SEARCH_RESULT_BUFFER_SIZE - 1];
		uint64_t nonce_base = m_current_nonce - s_numStreams * batch_size;
		
		if (m_current_index >= s_numStreams)
		{
			CUDA_SAFE_CALL(cudaStreamSynchronize(stream));
			if (buffer[0] > 0)
			{
				nonces[0] = nonce_base + buffer[1];
				buffer[0] = 0;
				exit = hook.found(nonces, 1);
			}
			exit |= hook.searched(nonce_base, batch_size);
		}
		run_ethash_search(s_gridSize, s_blockSize, m_sharedBytes, stream, buffer, m_current_nonce, m_parallelHash);
	}

`

**Comment by DeadManWalkingTO** [comment]
Any news here?
