### ISSUE TITLE
CircleCI failing on every pull request

### ISSUE THREAD

**Issue by davidf2281** [ethereum-mining/ethminer#248]
I'm not familiar with the way CircleCI setup works but it appears that the root cause of constant failures is this warning:
```Warning: Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but this is still an experimental feature. We highly recommend using an image that has official git and ssh installed.```
https://circleci.com/gh/ethereum-mining/ethminer/188?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by DeadManWalkingTO** [comment]
Any news here?
