### ISSUE TITLE
Please update monitoring and show speed fan, temp 

### ISSUE THREAD

**Issue by lythongac** [ethereum-mining/ethminer#251]
Please update monitoring and show speed fan, temp

**Comment by AndreaLanfranchi** [comment]
Why not simply use nvidia-smi ?

nvidia-smi --format=csv --query-gpu=timestamp,index,gpu_bus_id,name,pstate,power.limit,power.draw,temperature.gpu,fan.speed,clocks.gr,clocks.mem

**Comment by seymores** [comment]
Use nvidia-smi.

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.

**Comment by smurfy** [comment]
Added via #319
