### ISSUE TITLE
Trying to compile to get full speed on Windows 10

### ISSUE THREAD

**Issue by ngorsuch** [ethereum-mining/ethminer#254]
I compiled on a Windows 7 virtual machine with:

CUDA-v8.0-WindowsServer2012.zip
VS Pro 2015 (MSVC 19.0.24215.1)
python 2.7.13
cmake 3.9.0

using these commands on the command line:

mkdir Release
cd Release
cmake .. -DETHASHCUDA=ON -DCMAKE_BUILD_TYPE=Release
cmake --build . --config Release

on the command line. Compiles fine, works.  But on Windows 10 I get the slowdown as implied in the FAQ. Do I have to compile this statically linked to make sure all the Windows 7 libraries get pulled into the exe file, and how would I do that? Or is there some other thing I'm missing from trying to re-ceate the appveyor build?

Thanks for any help

**Comment by orkblutt** [comment]
What's your GPU and what is the hashrate on Win10 ?

**Comment by ngorsuch** [comment]
Solved, I had to build it using the same older Windows stuff the regular build uses. Now I'm getting 26MH/s on a GTX 1070.

**Comment by AndreaLanfranchi** [comment]
@ngorsuch : you're getting a very low hashrate. Are you overclocking ram ?
Such GPUs should give you at least 29.5 MH/s
