### ISSUE TITLE
Failed to submit hashrate with release 0.11.0

### ISSUE THREAD

**Issue by princerk** [ethereum-mining/ethminer#256]
I am running the ethminer on ubuntu 16.04 with Tesla k80 nvidia gpu on Google compute engine.
with EthereumPool.co pool. I get this kind of output in my console

|ethminer  Mining on PoWhash #8aa0f66f : 13.03MH/s [A0+0:R0+0:F0]
  m  19:49:16|ethminer  Mining on PoWhash #8aa0f66f : 14.28MH/s [A0+0:R0+0:F0]
  m  19:49:16|ethminer  Mining on PoWhash #8aa0f66f : 13.07MH/s [A0+0:R0+0:F0]
  m  19:49:17|ethminer  Mining on PoWhash #8aa0f66f : 13.03MH/s [A0+0:R0+0:F0]

when I click on the get miner stats on the dashboard of EthereumPool.co , It starts showing the following error in my console.

ethminer  Mining on PoWhash #f4439454 : 13.06MH/s [A0+0:R0+0:F0]
ethminer  Failed to submit hashrate.
ethminer  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32700 : JSON_PARSE_ERROR: The JSON-Object is not JSION-Valid:  Database Error

**Comment by carlosnewmusic** [comment]
![imagen](https://user-images.githubusercontent.com/19379457/29771632-2f7172b4-8bf5-11e7-9eab-d3f00f29622a.png)
in windows 10 creators update 64 bits

**Comment by DeadManWalkingTO** [comment]
CUDA Hardware Test Launch Command:

```ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test```

Try with latest Ethminer version and feedback please.
Thank you!

**Comment by carlosnewmusic** [comment]
in w7 no error

**Comment by AndreaLanfranchi** [comment]
Not actual anymore
