### ISSUE TITLE
Create a simple user facing site using gh-pages

### ISSUE THREAD

**Issue by smurfy** [ethereum-mining/ethminer#257]
This one-page site should contain:

* Short introduction 
* Big download link
* Link to "issues", "gitter"  for reporting bugs and questions
* Usage samples for:  getwork (farm mode), stratum.  and cuda, opencl.
* Additional description of possible other options (like report hashrate, different stratum modes..)

**Comment by toymachiner62** [comment]
+1

The usage instructions are absolute garbage. Need some examples.

**Comment by smurfy** [comment]
that was my first try: https://smurfy.github.io/ethminer/

**Comment by toymachiner62** [comment]
Looks like a great start. Now we have something to submit pull requests against if we have questions.

**Comment by DeadManWalkingTO** [comment]
Good job!

**Comment by chfast** [comment]
Are you going to continue this?

**Comment by XhmikosR** [comment]
I can take care of this. Do we still want it?

**Comment by chfast** [comment]
I prefer nice README. But I don't mind if you want to maintain the web page.

**Comment by XhmikosR** [comment]
Well, the idea is to autogenerate the docs. I'll see how it looks and what we can do with the minimal changes.

**Comment by AndreaLanfranchi** [comment]
I believe new documentation section supersedes this request.
Can we close ?

**Comment by smurfy** [comment]
sure, but i still think a simple website would be more user-friendly.
I will look into changing my old start of gh-pages to use the documentation section as source.

**Comment by AndreaLanfranchi** [comment]
Ok.
