### ISSUE TITLE
No improvement in Linux

### ISSUE THREAD

**Issue by JudoFlash** [ethereum-mining/ethminer#258]
Hi all,

Aside from the same results I see when using the Genoil build, when upgrading to this version, I am seeing 0 improvement (getting about 21.5 Mh/s per card in a rig of 13)

I am running in nvOC (Linux build). Has anyone had success getting better results in Linux, and if so, how?

I tried running "ethminer --help" and was told it was not a program (even though I can run it with a bash file). I am not Linux savvy, however, so I am sure I am missing something simple.

**Comment by stoshfabricius** [comment]
Where are you running these commands from?

If ethminer is not in your PATH and you are not in the same folder that contains the ethminer file then bash will be unable to find it

**Comment by derubm** [comment]
./ethminer -h might work if your in the ethminer folder.

**Comment by JudoFlash** [comment]
I had set the path and permissions. ./ ethminer --help worked though.

That said, I've tried changing several settings (and just running default), and I seem to top at at 21.5 Mh/s. This is on 26 1060 6GB GPU's, and these are the same speeds I would see in Claymore. I tried try turning off my power limit and not underclocking my core, but there was no change.

**Comment by Blacksuu** [comment]
@JudoFlash i see you have 1060 model 21.5 is Mh/s is usual default setting card gain, for get more you need to OC vram ... but first of all you need to indentifie vram by who are made Samsung (best case), Micron, Hynix (worst case)
- Samsung they can be push to +900-950 very easy = ~+25 Mh/sec
- Micron & Hynix +600-700 = 21-23 Mh/sec
but a good place to see how x60 it work check this https://bitcointalk.org/index.php?topic=1575547.0

i have x60 to with samsung vram made & with 65% power limit +936 i get a stable 25.2-25.7 Mh/sec in win 7

cheers

**Comment by derubm** [comment]
@JudoFlash i can verify the settings from blacksuu
limit the cards to 63-65 % power ( more does not bring more mh/s)
try to set up memory as high as possible w/o video driver crashing.
samsung memroy will eat 900-940 +mhz, but stable it will run on 910 max.
other memory brands simple won´t eat that high speed.
if gpu runs at ~1600 mhz and memory at ~9000 mhz you ll be topped it out pretty much.
normally one 1060 should not use more then 70 watts on that settings.

**Comment by JudoFlash** [comment]
Thank you both. The 21.5 Mh/s is being received with a core underclock of 200, memory overclock of 850, and a memory limit of 75W (which I have disabled with no different results). These are the same results I was getting in Genoil at these OC settings, which is why I assume something is not working.

As far as I know I have Samsung memory, though I need to find a Linux utility to verify this (if anyone knows of one, please let me know).

**Comment by ddobreff** [comment]
https://github.com/ddobreff/ethminer-manager
On linux you have to double memoffset to 1600-1800 to achieve those speeds.
I am currently at -200 for core and 1300 for mem which is exactly 24.64, that is optimal stable clock for 6/8 pack rig with powerlimit set to 80W.

>   m  20:14:32|ethminer  Mining on #cfc1da14& [A28709+153:R16+19:F0]
  m  20:14:32|ethminer  Total: 196.87MH/s ( 0:24.64 1:24.64 2:24.64 3:24.64 4:24.38 5:24.64 6:24.64 7:24.64 )

**Comment by Blacksuu** [comment]
Print screen done with setting use & ethermine on a stable round sesion 20 hours 17 minutes 30 seconds
Using MSI AFB & Nvidia Inspector is not recomand but i keep have open bouth to show all important data
http://i.imgur.com/UiR4QSx.png
cheers

**Comment by JudoFlash** [comment]
Thank you. I am unsure if I need to double speeds in nVOC - doing so will lock up my machine.

For that screenshot showing the memory type - I assume that is Windows? Hoping for a Linux solution.

**Comment by Blacksuu** [comment]
yes print screan is done under windows 7

**Comment by dafyk** [comment]
@Blacksuu you are running card in P2 state, under Windows you can force it to run in P0 and gain some more MH/s. Check my comment [here](https://github.com/ethereum-mining/ethminer/issues/202#issuecomment-318523568). You will probably have to lower the memclock little bit or your card may be unstable (because of higher clocks gained by forcing card in to P0)

**Comment by Blacksuu** [comment]
@dafyk  Nvidia Inspector it reset setting done by MSI AFB coz it have his own OC management & get in fight with trying to get control, that i say is not recomand to use both, about get more that >25.7 Mh/sec < is best what can doo a x60 with samsung memory :) so i am fine, that P2 state report probabil is because conflict with what i say, anyway thx for sugestion & good post you done there

**Comment by dafyk** [comment]
@Blacksuu there are two utilitie with very similiar name. **Nvidia inspector** can be used to overclock and control fan speeds. And yes it may interfere with other OC tools as nvidia-smi, afterburner etc. its because all this tools use the same API exposed by nvidia driver. So the last tool that you run will reset/overide seetings. 
The second one is **Nvidia profile inspector** and its used to inspect details of system "profile" (or other profiles mostly used for games) and it does not interfere with OC tools (other then setting P0). Nvidia inspector correctly reports your card P state. Give it one more try and you'll see i am correct.

**Comment by Blacksuu** [comment]
yes i double check with nvidia-smi what is own Nvidia application (after you point to that) & that way i seen is on P2 state normal it supose to be on P0, i will check after i will fully restart pc but not now :)
for who not know in c:\Program Files\NVIDIA Corporation\NVSMI\ is nvidia-smi application (for windows)

**Comment by JudoFlash** [comment]
I may be wrong but I do not believe doubling the speeds is the solution in nvOC (an Ubuntu build). Can anyone else confirm? Either way I have not seen any improvement over an older Genoil build, so I fear something is wrong.

**Comment by ddobreff** [comment]
It is, I already told you that. nvOC is based on ubuntu linux.

**Comment by AndreaLanfranchi** [comment]
This is my personal opinion on the matter.
I've been long time manipulating all the settings to achieve better performance and stability on linux and these are my findings.

My rig configuration is
Mobo : Asus B250F Gaming 16Gb Ram 
CPU : Pentium
OS : Ubuntu 16.04.2 LTS (Kernel 4.4.0-83-generic)
GPU : 6x Nvidia Gtx 1070 OC

Actually I am running ethminer 0.12.0.dev2

With these resources I am getting a very stable 33.45 M/Hs (which is well beyond my initial excpectations of roghly 30 M/Hs) from each card using these settings:
GPU Clock : -190
MEM Clock: +1400

After several attempts I decided not to set any power limit to the GPU as it turns out the continuos adjustment to clocks issued by the power limiter may be cause of instability.
At the moment the power drained by each card is floating between 108 and 111 watts.
If you want to lower your power drain just lower your clock values accordingly.
But, I repeat, in my personal case, not setting any power limit has resolved most of the issues.

**Comment by MikiVazquez** [comment]
Congratulations!!

 I have a  Nvidia Gtx 1070 **OC** and I can only: (The same OS) 

GPU Clock: -200
Mem Clock:+900
 
30.41MH/s and the power 146W

If I put your config It hangs :(

**Comment by AndreaLanfranchi** [comment]
@MikiVazquez 
Which mobo ?
Could you please post the result of 

nvidia-smi dmon -o T -d 2 -c 5 -s pucmt

**Comment by MikiVazquez** [comment]
nvidia-smi dmon -o T -d 2 -c 5 -s pucmt
#Time        gpu   pwr  temp    sm   mem   enc   dec  mclk  pclk    fb  bar1 rxpci txpci
#HH:MM:SS    Idx     W     C     %     %     %     %   MHz   MHz    MB    MB  MB/s  MB/s
 11:13:38      0   147    82   100   100     0     0  4252  1645  2328     5    20     5
 11:13:40      0   147    82   100   100     0     0  4252  1645  2328     5    19     5
 11:13:42      0   147    82   100   100     0     0  4252  1645  2328     5    20     5
 11:13:44      0   147    82   100   100     0     0  4252  1645  2328     5    20     5
 11:13:46      0   147    82   100   100     0     0  4252  1645  2328     5    20     5


P.S. Command very interesting, did not know thanks!

**Comment by AndreaLanfranchi** [comment]
AFAIK you have a problem in the data link connection between your mobo and your gpu.
Look at the rightmost column (txpci MB/s) : 5 is a very low level.
Maybe low quality raisers.

In my environment that value is constantly among 15 and 22.

**Comment by MikiVazquez** [comment]
ok... or very old mother board.. I'm going to buy http://www.asrock.com/MB/Intel/H110%20Pro%20BTC+/index.asp

Thank you!!

**Comment by AndreaLanfranchi** [comment]
Good choice for a 12xGPU rig.
If you want to stay on 6 and spend a little less the Asrock H81 PRO BTC R2.0 is a bargain.

**Comment by ddobreff** [comment]
The lower clock ability is caused by memory vendors.
Samsung clocks upto (1900 linux)(950 windows)
Micron clocks /2

**Comment by MikiVazquez** [comment]
Can i know from software, what kind of memory does my GPU have?

**Comment by ddobreff** [comment]
if you are on windows use GPU-Z, on linux I haven't found a way...yet

**Comment by MikiVazquez** [comment]
```
lspci -vnn | grep VGA -A 12
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation Device [10de:1b81] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. Device [1043:85a0]
	Flags: bus master, fast devsel, latency 0, IRQ 27
	Memory at fd000000 (32-bit, non-prefetchable) [size=16M]
	Memory at d0000000 (64-bit, prefetchable) [size=256M]
	Memory at e6000000 (64-bit, prefetchable) [size=32M]
	I/O ports at dc00 [size=128]
	[virtual] Expansion ROM at fe980000 [disabled] [size=512K]
	Capabilities: [60] Power Management version 3
	Capabilities: [68] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Capabilities: [78] Express Legacy Endpoint, MSI 00
	Capabilities: [100] Virtual Channel
	Capabilities: [250] Latency Tolerance Reporting

```

The first line has the name of the vendor, the model name/series and the pci id... i see 1043:85a0 looking in Google:
https://www.techpowerup.com/vgabios/187514/asus-gtx1070-8192-161018

But Memory Support:
  GDDR5, Samsung
  GDDR5, Micron

:(

**Comment by Blacksuu** [comment]
@MikiVazquez from link what you find it not say exactly what manufacture are aka it say it can be Samsung or Micron (with is normal) but from what you was say early aka you have stable run on Mem Clock:+900 & if you try to use Mem Clock: +1400 (setting use by @AndreaLanfranchi ) it crash / hang on it result one think you have Micron
my advice for all who not know exactly what type of mem you have grab win10 kit (microsoft provide free kit on hes site what is fully functionaly for 30 day, with is not matter) install it on a secondary hdd & check it, you will lose max 1 hour (on a sdd probabil it will take 30 min max) but at list you will know exactly how thing goo
that in case anyone not find a alternative for gpu-z or nvidia inspector what to work on linux

**Comment by MikiVazquez** [comment]
@Blacksuu  Thank you! I buy a new mother board and 

 ```
nvidia-smi dmon -o T -d 2 -c 100 -s pucmt
#Time        gpu   pwr  temp    sm   mem   enc   dec  mclk  pclk    fb  bar1 rxpci txpci
#HH:MM:SS    Idx     W     C     %     %     %     %   MHz   MHz    MB    MB  MB/s  MB/s
 11:04:48      0   122    72   100   100     0     0  4252  1480  2336     5    38    13
 11:04:50      0   122    72   100   100     0     0  4252  1480  2336     5    40    15
 11:04:52      0   119    73   100   100     0     0  4252  1442  2336     5    37    13
 11:04:54      0   119    72   100   100     0     0  4252  1442  2336     5    37    13
```

...but Memory no more that 1100 and powerd 120W

**Comment by Blacksuu** [comment]
@MikiVazquez way you keep video on 120 W ? you just waste electricity when is not need 1060 it can work perfectly on 65-80 W with out problem & that's best part :) more power you need only if is need gpu to work faster what in eth case is not need aka only vram is need to push to limit ... if you try mining zcash let say yes you need to push gpu to & that need more power ... soo IF you only mining ETH lower power down with out problem ... less electicity spent more income for you
cheers

**Comment by AndreaLanfranchi** [comment]
@Blacksuu you can lower your power drain by 

`sudo nvidia-smi -pl 100 `

which will set your power drain to a lowe value (GPU adjusts power drain by limiting clocks).
Then set :
```
nvidia-settings -a "[gpu:0]/GPUGraphicsClockOffset[3]=-200"
nvidia-settings -a "[gpu:0]/GPUMemoryTransferRateOffset[3]=1200"
```
**Yes ... its -200 (minus 2 hundred)**

At this point you can try to improve your memory clocks with small adjustments until you find a stable a satisfactory setting.

Try 
`nvidia-settings -a "[gpu:0]/GPUMemoryTransferRateOffset[3]=1205"`
...
`nvidia-settings -a "[gpu:0]/GPUMemoryTransferRateOffset[3]=1210"`
and so on ...

**Comment by Blacksuu** [comment]
@AndreaLanfranchi i think you want all of that to say to @MikiVazquez :) & is good advice
- for windows user with MSI Afterburner all tune is easy power limit set in % (max W) + Memory clock value set, for fine tuning it can adjust core clock to but not necessary special in eth case

**Comment by AndreaLanfranchi** [comment]
Yes @Blacksuu ... sorry. I amended my post.
Confirm for ethereum core clock **over**clocking is detrimental.  Instead it's useful to **under**clock as it helps lowering power drain.

**Comment by dafyk** [comment]
@AndreaLanfranchi lowest power limit is different between manufacturers. My Zotac 1070 minimum is 125W but Asus ROG 1070 can run at 75W. Also note that lower power limt on Zotac has no effect on mining performance, but lowering limit on Asus below 110W also affects miner performance (drops from 33MH/s to 25MH/s)

**Comment by AndreaLanfranchi** [comment]
@dafyk I think we are talking about two separate matters. 
One thing is the limit you can set by invoking nvidia-smi -pl
A complete different thing is how low you can go in power drain.

Talking about nvidia-smi -pl ... in my experience (mainly on linux) this command allows you a specific setting range: for Gtx 1070 (any flavour ... I have used Asus, MSI, EVGA ... no experience on Zotac) this command allows any value between 100 and 216 w. Any value below or above is not accepted.

On the other hand the GPU itself when idle is draining well below those 100w. In my case I register roughly 10w in P8 state. This implies that an accurate (or specific) tuning of core underclock and memory overclock can stabilize the drain to a lower value than 100w.

I am currently running 3 rigs with 6x Gtx 1070 OC from Asus and I have to say that your statement about power limiter at 110 w causing hash rate to drop from 33 to 25 Mh does not correspond to my situation. After several attempts I have a stable configuration at 100W drain per GPU with power limit to 100w, core clock set to -200 and memory clock set to +1490.

**Comment by dafyk** [comment]
@AndreaLanfranchi we are talking about same thing. Again your statement  about 100W is wrong. I have two cards which can run at 75W (confirmed by nvidia-smi and power-meter in wall). You can find limits of your cards by running command (if you have multiple cards add -i X to nvidia-smi)
`nvidia-smi -q | findstr /R /C:"Limit"`

Results for Asus ROG 1070 card:
``` Power Limit                 : 115.00 W
Default Power Limit         : 166.10 W
Enforced Power Limit        : 110.00 W
Min Power Limit             : 75.00 W
Max Power Limit             : 200.00 W
```
And what i was trying to say is that some cards are not affected by lower power-limit but there are some which can be, like Asus ROG where setting power limit to 75W=25MH/s, 95W=29MH/s, 100W=31.8,110W=33MH/s (i hope you get the idea now). If i set any value between 110W-166.1W miner performance doesnt change and keeps at 33MH/s

**Comment by DeadManWalkingTO** [comment]
GTX1060 +150/+500/65%TDP @ 23-24MHs

1. Try Update Drivers.
Download and install the latests.

2. Try Update Ethminer.
Download (or beter build) the latest.

3. Try use -U for CUDA devices.
CUDA Hardware Test Launch Command:
`ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

4. Try to change P2 State and Power managment mode.
You can use nvidia-smi.
For the best mining hashrate:
    - CUDA - Force P0 State
    - Power managment mode (optimize compute)

5. Try Optimize/Overclock GPUs. 
You can use nvidia-smi.

6. Try use a WatchDog
You can use [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) (#735).

Please feedback.
Thank you!
