### ISSUE TITLE
Linux whole GPU not being used?

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [ethereum-mining/ethminer#260]
So in my rig of a GTX 980 I am only getting ~15 MH/s with about nothing on it...

```
echo Pls give Root kthx
cd /home/gido5731/Downloads/ethminer-0.11.0-Linux/bin
export GPU_FORCE_64BIT_PTR=0
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_ALLOC_PERCENT=100
sudo nvidia-smi -i 0 -c 3
nice -19 ./ethminer --farm-recheck 1000 -SC 2 --cuda-block-size 128 --cuda-parallel-hash 8 -t 64 --cuda-schedule spin -U -S us1.ethermine.org:14444 -O 0x11d8f585ac87c8f0dfa2fa35962cab4210db05a4.PC1 
```
^ Startup script

```
  ℹ  20:56:11|stratum  Received new job #c24473df
  ℹ  20:56:11|cudaminer0  set work; seed: #0986c6a2, target:  #0000000112e0
  m  20:56:12|ethminer  Mining on PoWhash #c24473df : 11.42MH/s [A6+0:R0+0:F0]
  m  20:56:13|ethminer  Mining on PoWhash #c24473df : 15.73MH/s [A6+0:R0+0:F0]
  m  20:56:14|ethminer  Mining on PoWhash #c24473df : 16.78MH/s [A6+0:R0+0:F0]
  m  20:56:15|ethminer  Mining on PoWhash #c24473df : 16.78MH/s [A6+0:R0+0:F0]
  m  20:56:16|ethminer  Mining on PoWhash #c24473df : 15.73MH/s [A6+0:R0+0:F0]
  m  20:56:17|ethminer  Mining on PoWhash #c24473df : 16.78MH/s [A6+0:R0+0:F0]
  ℹ  20:56:17|cudaminer0  Solution found; Submitting to us1.ethermine.org ...
  ℹ  20:56:17|cudaminer0    Nonce: 0xcefb5042a2a363b8
  ℹ  20:56:17|stratum  B-) Submitted and accepted.
  m  20:56:18|ethminer  Mining on PoWhash #c24473df : 15.73MH/s [A7+0:R0+0:F0]
  m  20:56:19|ethminer  Mining on PoWhash #c24473df : 16.78MH/s [A7+0:R0+0:F0]
  m  20:56:20|ethminer  Mining on PoWhash #c24473df : 16.78MH/s [A7+0:R0+0:F0]
  m  20:56:21|ethminer  Mining on PoWhash #c24473df : 15.73MH/s [A7+0:R0+0:F0]
  m  20:56:22|ethminer  Mining on PoWhash #c24473df : 16.78MH/s [A7+0:R0+0:F0]
  m  20:56:23|ethminer  Mining on PoWhash #c24473df : 16.78MH/s [A7+0:R0+0:F0]
  m  20:56:24|ethminer  Mining on PoWhash #c24473df : 14.68MH/s [A7+0:R0+0:F0]
  m  20:56:25|ethminer  Mining on PoWhash #c24473df : 16.78MH/s [A7+0:R0+0:F0]
  ℹ  20:56:26|stratum  Received new job #477b57e1
  ℹ  20:56:26|cudaminer0  set work; seed: #0986c6a2, target:  #0000000112e0

```
^ Small snippet of logs

```
gido5731@gido-desk:~/Desktop$ nvidia-smi 
Fri Aug 25 20:57:29 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980     Off  | 0000:01:00.0      On |                  N/A |
| 73%   80C    P2   138W / 196W |   2834MiB /  4035MiB |    100%   E. Process |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1555    G   /usr/lib/xorg/Xorg                             257MiB |
|    0      4923    G   /usr/bin/compiz                                147MiB |
|    0      6958    G   ...el-token=B8AB8BC1E957E99890B1B0D60B83F8C1   130MiB |
|    0      9629    C   ./ethminer                                    2251MiB |
|    0     10149    G   ...s-passed-by-fd --v8-snapshot-passed-by-fd    33MiB |
|    0     10273    G   ...s-passed-by-fd --v8-snapshot-passed-by-fd     9MiB |
+-----------------------------------------------------------------------------+

```
^ Nvidia-smi

As you see above my GPU isnt being used to its fullest, im on Ubuntu 17.04 with just Discord and Opera open in the backround. Are my settings bad?

**Comment by spieiga** [comment]
that hashrate doesn't seem off for a 980.  the GPU-Util is actually 100% so that seems fully utilized.  the 73% is just fan, you could put fan to 100% and then you might get to 196/196W

**Comment by gidoBOSSftw5731** [comment]
Hm, well I was confused by the 2-3 gb of VRAM usage because I had heard that GPU mining was very VRAM intensive.

**Comment by jimmykl** [comment]
Yes it is VRAM *access* intensive, which is why you overclock the memory. But the *amount* of VRAM utilised is related to the ETH DAG file size, which is currently 2.09GB [(you can check here)](https://investoon.com/tools/dag_size). According to your processes ./ethminer is using 2251MiB which seems right.

Anyway as for your hashrate I'd expect a bit better, my 970 was getting more than that (albeit on Windows) I'm not so familiar with linux but here are a few ideas:

Are you overclocking the card? Try overclock the memory and reduce the power limit as much as possible while keeping it stable. I think you'll need to use nvidia-smi, checkout the 'Monitoring and Managing GPU Boost' section [here](https://www.microway.com/hpc-tech-tips/nvidia-smi_control-your-gpus/)

In Windows the nvidia driver control panel has an option to 'optimize for compute performance' ([it looks like this)](https://postimg.org/image/unnnv53vh/), if that is there in the linux control panel enable it. [You might be able to do it from the command line too](https://devtalk.nvidia.com/default/topic/832288/how-to-automatically-set-powermizer-to-prefer-maximum-performace-with-340-and-346-drivers/?offset=3)

If Opera has hardware acceleration as an option in the linux version turn that off.

**Comment by gidoBOSSftw5731** [comment]
Ok, heres what I have, Your cuda options did basically the same as mine did, Opera software acceleration just made my browser look like $h!t and didnt have any noticable affect (Unless I'm blind, then if so then tell be because I went back to hardware.) I do plan to be putting a Windows 10 SSD into my system once I get a SataE > Sata adapter so I will post here then. I do have it in compute mode (hense the sudo nvidia-smi -i 0 -c 3) and I do overclock them with both nvidia-smi and nvidia x setttings (above I wasnt overclocked, overclocking generally does minimal effects until over 1000 where it goes to 6-7 MH/s... IDK why, smi says 100% usage so idk)  


I think I covered all the bases here, If not then please mention.

Also I recall people online saying they get ~20 MH/s on my card, Am I wrong?

**Comment by jimmykl** [comment]
Certainly seems you have covered it all. I guess see if Windows changes anyhing. FWIW I used to have a 970 with micron ram and from memory it was somewhere between 15-20MH/s.
