### ISSUE TITLE
No GPU device with sufficient memory was found. Can't GPU mine.  on all my rigs

### ISSUE THREAD

**Issue by sadgb** [ethereum-mining/ethminer#263]
Hi there. I would like to move to ethminer, but i get strange errors (version from releases section, 0.11.0, windows 10)

No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument

That's super strange because all my cards are AMD RX 470 with at least 4 GB

How could i help you with this issue ?

**Comment by smurfy** [comment]
Do you have the onboard GPU enabled? try playing with the ``--opencl-platform`` setting

**Comment by sadgb** [comment]
--opencl-platform 1 
helped me. But it's really strange,why do i need this setting even if onboard gpu disabled in bios

**Comment by ddobreff** [comment]
If you are using AMD(OpenCL) and onboard GPU is enabled its required to use --opencl-platform 1.

**Comment by sadgb** [comment]
as i said, even hen onboard gpu disabled it requires --opencl-platform 1 to work

**Comment by simjar** [comment]
sorry for my ignorance but how did you enter the  --opencl-platform   as I can't find this command on my ethos terminal window.Thank You for your help!!

**Comment by vampyren** [comment]
Had the same issue, added the command and works fine:
ethminer.exe --farm-recheck 200 **--opencl-platform 1** -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O <Your_Ethereum_Address>.<RigName>

I have 7x1070 nvidia with a buildin Intel GPU on motherboard.

**Comment by simjar** [comment]
Hi! Thanks !! Will try that tomorrow.Cheers J 

    On Saturday, November 25, 2017 6:40 AM, vampyren <notifications@github.com> wrote:
 

 Had the same issue, added the command and works fine:
ethminer.exe --farm-recheck 200 --opencl-platform 1 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O <Your_Ethereum_Address>.I have 7x1070 nvidia with a buildin Intel GPU on motherboard.—

**Comment by rulgrunge** [comment]
I tried all above and still getting same error: No OpenCL platforms found
No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument

i have a sapphire nitro 580 8gb

please someone help

**Comment by rulgrunge** [comment]
plus the MB has no onboard gpu

**Comment by dax0r** [comment]
thank you, this helped me, too!

but it's strange that it worked without the --opencl-platform 1 before I reinstalled the radeon drivers.

**Comment by DeadManWalkingTO** [comment]
I think the solution has been found.
