### ISSUE TITLE
0xc000007b Error in ver 0.11 Windows

### ISSUE THREAD

**Issue by wargun02** [ethereum-mining/ethminer#264]
Hi,

Getting a message when running on Windows 10 x64 Administrator mode: "The application was unable to start correctly (0xc000007b). Click OK to close the application.

Wonder what could be the problem?

**Comment by orkblutt** [comment]
You have a dependency error. You should install visual studio 2015 redistribuable:
https://www.microsoft.com/fr-fr/download/details.aspx?id=53587

hope it will solve your issue
cheers,
orkblutt

**Comment by wargun02** [comment]
That was my initial thought, installed the visual studio 2015 redistribuable (both x86 and x64), problem is still there.

**Comment by wargun02** [comment]
Running the ethminer-dbg-0.11.0-Windows works with the visual studio 2015 redistribuable (both x86 and x64). I'd installed this clean on another machine. I guess I might have screwed up my dlls. Thanks for the pointers.
