### ISSUE TITLE
Apple OSX - <program source>:364:9: warning: comparison of integers of different signs

### ISSUE THREAD

**Issue by hradec** [ethereum-mining/ethminer#266]
I'm seeing this warning when running ethminer 0.12.0.dev2 on OSX with Radeon HD - FirePro D500:

```
cl  01:34:01|cl-0      Platform: Apple
cl  01:34:01|cl-0      Device:   AMD Radeon HD - FirePro D500 Compute Engine  / OpenCL 1.2 
cl  01:34:02|cl-0      Build info: <program source>:329:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~
<program source>:364:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~
```

And it never shows up in ethermine.org. It keeps receiving new jobs, but never finds a solution.

also, It's reporting around 11000MH/s! I'm assuming this is too much for a single board,  so maybe the warning above is causing some weird behaviour... 
```
  m  01:49:55|          Mining on #23dd2a26… : 11518.61MH/s [A0+0:R0+0:F0]
  m  01:49:56|          Mining on #23dd2a26… : 11565.64MH/s [A0+0:R0+0:F0]
  m  01:49:56|          Mining on #23dd2a26… : 11476.95MH/s [A0+0:R0+0:F0]
  m  01:49:56|          Mining on #23dd2a26… : 11513.47MH/s [A0+0:R0+0:F0]
  m  01:49:56|          Mining on #23dd2a26… : 11440.43MH/s [A0+0:R0+0:F0]
  m  01:49:56|          Mining on #23dd2a26… : 11440.43MH/s [A0+0:R0+0:F0]
  m  01:49:57|          Mining on #23dd2a26… : 11461.30MH/s [A0+0:R0+0:F0]
  m  01:49:57|          Mining on #23dd2a26… : 11471.73MH/s [A0+0:R0+0:F0]
  m  01:49:57|          Mining on #23dd2a26… : 11440.43MH/s [A0+0:R0+0:F0]
  m  01:49:57|          Mining on #23dd2a26… : 11544.82MH/s [A0+0:R0+0:F0]
  m  01:49:57|          Mining on #23dd2a26… : 11419.57MH/s [A0+0:R0+0:F0]
  m  01:49:58|          Mining on #23dd2a26… : 11445.65MH/s [A0+0:R0+0:F0]
  m  01:49:58|          Mining on #23dd2a26… : 11440.43MH/s [A0+0:R0+0:F0]
  m  01:49:58|          Mining on #23dd2a26… : 11430.00MH/s [A0+0:R0+0:F0]
  m  01:49:58|          Mining on #23dd2a26… : 11503.04MH/s [A0+0:R0+0:F0]
  m  01:49:58|          Mining on #23dd2a26… : 11482.17MH/s [A0+0:R0+0:F0]

```

any help is much appreciated!! 

all the best...
-Hradec

**Comment by hradec** [comment]
after a while, it started to spit manged text like this from time to time:
![image](https://user-images.githubusercontent.com/806743/29805319-fdf6ece8-8c3d-11e7-89b5-cab104587b87.png)

**Comment by hradec** [comment]
ok... after almost an hour, I got this message: "Read response failed"
![image](https://user-images.githubusercontent.com/806743/29806064-031d85b6-8c42-11e7-8d9e-dc8e147acea2.png)

I also got the same message with ethminer 0.11.0!

**Comment by smurfy** [comment]
Why are you using ``localhost:4443``  instead of ``ethermine.org`` directly.

The read response failed error, is somewhat normal, you always can get disconnected.

**Comment by hradec** [comment]
its because the machines have no direct internet connection, so I do a ssh tunnel to the server that has internet. 
This tunnel works fine with all other machines, so I'm confident that's not the problem. 

> The read response failed error, is somewhat normal, you always can get disconnected.
ok... but I get this message all the time in that machine (the only running OSX) and after 48 hours, theres no "solved" message and still the machine doesn't show up in ethermine.org. So I'm confident something  is really wrong here...

**Comment by rosswlewis** [comment]
Same:  

```
[OPENCL]:Printing program log
[OPENCL]:<program source>:324:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~
<program source>:359:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~

[OPENCL]:Creating cache buffer
[OPENCL]:Creating DAG buffer
[OPENCL]:Allocating/mapping DAG buffer failed with: clCreateBuffer(-61). GPU can't allocate the DAG in a single chunk. Bailing.
[OPENCL]:clEnqueueWriteBuffer(-38)
```

**Comment by tiyang** [comment]
Hi @hradec ,
I have the same issue here. Have you solved this problem?

**Comment by hradec** [comment]
nope!!

**Comment by DeadManWalkingTO** [comment]
Any news here?

**Comment by melvyn2** [comment]
Same problem here, and maybe worse: neither nicehash or minergate (when I mine on them) report any mining from my rx 480.
