### ISSUE TITLE
after latest cuda changes not compilable

### ISSUE THREAD

**Issue by Himan2001** [ethereum-mining/ethminer#268]
I compiled today the latest code and now i have some problems:

``
[ 95%] Building CXX object ethminer/CMakeFiles/ethminer.dir/main.cpp.o
[100%] Linking CXX executable ethminer
../libethash-cuda/libethash-cuda.a(CUDAMiner.cpp.o): In function `dev::eth::CUDAMiner::configureGPU(unsigned int, unsigned int, unsigned int, unsigned int, unsigned long, unsigned int, unsigned int)':
CUDAMiner.cpp:(.text+0x85b): undefined reference to `dev::eth::Miner::s_dagLoadMode'
CUDAMiner.cpp:(.text+0x86f): undefined reference to `dev::eth::Miner::s_dagCreateDevice'
../libethash-cuda/libethash-cuda.a(CUDAMiner.cpp.o): In function `dev::eth::CUDAMiner::workLoop()':
CUDAMiner.cpp:(.text+0x15e2): undefined reference to `dev::eth::Miner::s_dagLoadMode'
CUDAMiner.cpp:(.text+0x1815): undefined reference to `dev::eth::Miner::s_dagLoadMode'
CUDAMiner.cpp:(.text+0x1828): undefined reference to `dev::eth::Miner::s_dagInHostMemory'
CUDAMiner.cpp:(.text+0x1844): undefined reference to `dev::eth::Miner::s_dagLoadIndex'
CUDAMiner.cpp:(.text+0x184d): undefined reference to `dev::eth::Miner::s_dagLoadMode'
CUDAMiner.cpp:(.text+0x1854): undefined reference to `dev::eth::Miner::s_dagLoadIndex'
CUDAMiner.cpp:(.text+0x1b0a): undefined reference to `dev::eth::Miner::s_dagLoadIndex'
CUDAMiner.cpp:(.text+0x1b49): undefined reference to `dev::eth::Miner::s_dagLoadIndex'
CUDAMiner.cpp:(.text+0x1b5a): undefined reference to `dev::eth::Miner::s_dagLoadIndex'
CUDAMiner.cpp:(.text+0x1b6d): undefined reference to `dev::eth::Miner::s_dagInHostMemory'
CUDAMiner.cpp:(.text+0x1b8c): undefined reference to `dev::eth::Miner::s_dagInHostMemory'
CUDAMiner.cpp:(.text+0x1c39): undefined reference to `dev::eth::Miner::s_dagCreateDevice'
CUDAMiner.cpp:(.text+0x1c72): undefined reference to `dev::eth::Miner::s_dagInHostMemory'
CUDAMiner.cpp:(.text+0x1d14): undefined reference to `dev::eth::Miner::s_dagLoadIndex'
collect2: error: ld returned 1 exit status
make[2]: *** [ethminer/ethminer] Error 1
make[1]: *** [ethminer/CMakeFiles/ethminer.dir/all] Error 2
make: *** [all] Error 2
``

and here i got some warnings:

``
[ 56%] Building CXX object libethash-cuda/CMakeFiles/ethash-cuda.dir/CUDAMiner.cpp.o
/usr/src/ethminer-master/libethash-cuda/CUDAMiner.cpp:63:16: warning: unused parameter ‘_count’ [-Wunused-parameter]
   virtual bool found(uint64_t const* _nonces, uint32_t _count) override
                ^
/usr/src/ethminer-master/libethash-cuda/CUDAMiner.cpp: In member function ‘virtual void dev::eth::CUDAMiner::workLoop()’:
/usr/src/ethminer-master/libethash-cuda/CUDAMiner.cpp:173:15: warning: deleting ‘volatile void*’ is undefined [enabled by default]
      delete[] s_dagInHostMemory;
               ^
``

d-bus support is DISABLED and only CUDA+STRATUM is enabled.
Can someone check for the problem ?
used compiler is gcc-4.8.4 on ubuntu 14.04, but yesterday all was ok with same enviroment.

**Comment by smurfy** [comment]
Strange...  CI Server just builds fine: https://travis-ci.org/ethereum-mining/ethminer/builds/269262874

**Comment by Himan2001** [comment]
I think it must be a missing include or something else? Forget to rename sothing? Please note, that i build ONLY with cuda, opencl is not included! And of course: fresh checkout. and gcc-4.8.4 on ubuntu 14.04.
Nothing else is changed on system since your commit.

**Comment by smurfy** [comment]
Ah!.. I can reproduce the error. It somehow fails if it's compiled without opencl

**Comment by Himan2001** [comment]
I rechecked with your dev code: "ethminer-cuda-cleanup"
- got the same result :(

**Comment by smurfy** [comment]
I think i found a fix, patch incoming soon

**Comment by Himan2001** [comment]
1 cosmetic thing i found on the stats right after the startup:

(Compute: 6 . 1)
- with one <space> before and one <space> after the . dot ;-)

**Comment by smurfy** [comment]
Can you try to build my fix branch? Worked for me. Need to fix my windows env, broke it due to cuda 6.5 :)

**Comment by smurfy** [comment]
Ok, compiles on windows too... (verified locally and on CI)

**Comment by Himan2001** [comment]
Compiling include OpenCL was working by me,too.
Compiling WITHOUT OpenCL works now. Thx for the patch ;-)
