### ISSUE TITLE
Please add the hashrate display time option

### ISSUE THREAD

**Issue by aliceaia** [ethereum-mining/ethminer#270]
Please add the hashrate display time option. I think displaying a constant hashrate causes errors on some systems. Thank you.

**Comment by ddobreff** [comment]
Increase --farm-recheck to 2000 or 5000.

**Comment by Himan2001** [comment]
"farm-recheck" is best to let it to 2000, otherwise you can often miss some new work.
This is NOT a cosmectical parameter, but it make sense to add a "display only" parameter so slow
down the info mess ;-)

**Comment by smurfy** [comment]
@Himan2001 it depends. in stratum mode its just for display. in getwork/farm mode it should be quite low.

**Comment by aliceaia** [comment]
Thanks everyone. I have compile another version which shows only error messages and share.

**Comment by ykhuat** [comment]
@aliceaia Hai, can share out how you compile a ethminer only show error message and share?

**Comment by aliceaia** [comment]
@ykhuat Just simple to remove any other messages.

**Comment by derubm** [comment]
in standard compile use -v 1 to show only errors and submissions. - there is no need to build a special version for this.

**Comment by DeadManWalkingTO** [comment]
As described above

1. Ιn stratum mode `--farm-recheck`  its just for display.
2. Ιn getwork/farm mode `--farm-recheck`  hight value can often miss some new work.
so
If you use stratum mode increase --farm-recheck to 5000.
or
If you use getwork/farm mode is best to let it to 2000.

*Of course in standard compile use -v 1 to show only errors and submissions.

Thanks 
@ddobreff  @Himan2001 @smurfy @derubm

**Comment by AndreaLanfranchi** [comment]
No more actual.
Display hashrate is fixed every 5 seconds.
