### ISSUE TITLE
Problem with 3 cards GTX 1060 on latest code (3. card slower as cards 1+2)

### ISSUE THREAD

**Issue by Himan2001** [ethereum-mining/ethminer#271]
I have a strange thing by using 3 cards GTX 1060 under ubuntu 14.04:

With 2 cards it works very nice, by having constant 2x18,87 MH/s - the same i got on the reported hashrate x2.

Today i added one more card, so i running now 3 identical cards.

The strange thing is the balancing by using 3 cards now. Card 0+1 shows 2x18,87 MH/s as before and card 2 never shows more then 17,3 MH/s. After a short while miner is crashing because of hanging of the card 2. (There is no hardware issue with them)

At time of working, the reported hashrate is fluctuating +/- 2 MH/s. (but not with just 2 cards)
What´s more important is, that the hashrate has an enormous drop at the pool. So after hours pool shows an long term average of only 43 MH/s (instead something like 52+).

I rechecked this by using claymore, and here all 3 cards are nice working with the exact maximum hashrate of 3x18,7 MH/s, further more: the reported hashrate is constant as expected.

Can someone check the actual code for problems with 3 cards (instead 2 or 4 or 6 or 8 cards ?)
I played with the paramater --cuda-parallel-hash 2, 4 and 8 - but i got the same results.
Everytime the 3. card is slower and reduced the entire hashrate from the miner.

**Comment by ddobreff** [comment]
Did you overclock them? Perhaps there is some kind of bottleneck concerning PCIe lane. You can try all 3 on a different motherboard and see if the issue persist or try switching between different PCIe generations in bios.

**Comment by Git1Hub2** [comment]
2xGTX1060 sansung memory (Gpu-Z) windows 10 -Ethminer-eth proxy-Watchdog - MSI Afterburner +900 memory clock =------------- 49 MHs -------------------So if the video card's memory is sansung

**Comment by derubm** [comment]
@Himan2001 for 3x 1060 the hashrate should be minimum 66 mh
with samsung memory it should be around 72-74

**Comment by Himan2001** [comment]
@all:
forget to told, that i have 3GB cards, so 18,7 MHz is my maximum. Today i use 4 identical cards and have now 74 MH/s. It looks like, i have some issues with the actual mainboard. The last 2 cards i need to unterclock of -100 Mhz compared to the first 2 cards and slow down cpu from +200 to +150.
Powerlimit was always 65, before i add the cards 3+4. It looks like a PCIe problem. The Bios was set to x1 long time before ;-)

**Comment by ddobreff** [comment]
Try lowering GPU clock to -150/-200. Marked as solved :)
