### ISSUE TITLE
Please add a WATCHDOG function so miner can alert when error occurs.

### ISSUE THREAD

**Issue by fynxer** [ethereum-mining/ethminer#274]
When something happens to ethminer we need a WATCHDOG that can alert and/or restart miner.

Thx to all you guys working on and developing Ethminer, i really appreciate it.

**Comment by ddobreff** [comment]
For AMD there is still no watchdog implemented, I am working on one but its linux only.

**Comment by AndreaLanfranchi** [comment]
See here #97

**Comment by piotr-dobrogost** [comment]
On linux the ideal and fairly easy to add solution would be to implement systemd's `sd_notify` interface – see [systemd for Administrators, Part XV](http://0pointer.de/blog/projects/watchdog.html)

> First of all, to make software watchdog-supervisable it needs to be patched to send out "I am alive" signals in regular intervals in its event loop. Patching this is relatively easy. First, a daemon needs to read the WATCHDOG_USEC= environment variable. If it is set, it will contain the watchdog interval in usec formatted as ASCII text string, as it is configured for the service. The daemon should then issue sd_notify("WATCHDOG=1") calls every half of that interval. A daemon patched this way should transparently support watchdog functionality by checking whether the environment variable is set and honouring the value it is set to.

**Comment by DDDanny** [comment]
On Windows you can easily perl and ps a solution... th escripts are quite small and will restart once you recognize a (CUDA) error via perl log parser or a dead process via ps. and then simply restart...

**Comment by DeadManWalkingTO** [comment]
After #757 (added --exit parameter to exit whenever an error occurred) you can use a watchdog.

Here is my [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) Windows7/8/10 [32/64] & Linux (Any Dist/Any Ver/Any Arch) (#735).

Check and feedback please.
Thank you!
