### ISSUE TITLE
Dual mining! Is it possible to evolve Ethminer into a Dualminer?

### ISSUE THREAD

**Issue by fynxer** [ethereum-mining/ethminer#275]
Find it disturbing Claymore has cornered the market for dual mining. If you could combine the amazing performance of Ethminer with some other coins for dual mining it would be a instant hit with the entire mining community.

Thx to all you guys working on and developing Ethminer, i really appreciate it. If i could program i would be right there alongside you all helping out developing.

**Comment by aliceaia** [comment]
Ethminer was developed for eth. It needs to be improved a lot if you need dual mining. Use claymore and pay him a small fee. I think it deserves the effort he put out.

**Comment by fynxer** [comment]
Just saying Claymore need competition, it only drives development.

At the moment i am running 2.5GH+ on ethereum with 90% nVidia cards and the other day i started a test phase jumping every 24 hours between Ethminer and Claymore on Etereum. Ethminer gave aprox around 100 shares more an hour than Claymore during each test. That my friends is around 4% devfee, not the advertised 1% that Claymore says.

Just saying his closed miner maybe can't be trusted 100% so an alternative open DualMiner could create some healthy competition.

**Comment by jch9678** [comment]
You can run the other miners at the same time.  Just lower the intensity.

100 shares could be something or it may not be.  Depends on the difficulty of the share and you're probably using a vardiff pool.

**Comment by fynxer** [comment]
You just hit the nail on the head, 100 shares/hour could be something or nothing due to other factors, you just don't know with closed software what is happening.

Loosing 100 shares an hour is aprox 250USD a month with Ethereum 385UDS value. I rather use Ethminer over Claymore at the moment. The higher Ethereum gets the higher that difference will be.

Ethereum is money so it could be that he is trying to cash in as much as possible while it lasts OR i could be wrong about the whole thing BUT i started this test because i read about other people doing some testing and those people expressed concerns that something was not right with the devfee.

**Comment by AlekzZz** [comment]
ethminer is awesome :) on ethos+ethminer each GTX1070 runs at 32.5mhs, ethos+claymore = 30mhs

**Comment by nguylb73** [comment]
@AlekzZz  what is your overclock settings?

**Comment by AlekzZz** [comment]
globalcore 1400
globalmem 4600
globalfan 40
globalpowertune 115

on zotac mini's

**Comment by DeadManWalkingTO** [comment]
Maybe enhancement.

**Comment by AndreaLanfranchi** [comment]
Out of scope.
