### ISSUE TITLE
win7 x64 prob with open-cl ellesmere device 

### ISSUE THREAD

**Issue by Rob-2017** [ethereum-mining/ethminer#276]
hello, i have a looong  :) question  about ellesmere prob in ethminer  i  use newest ethminer with win 10 x64  no problems  up to 5 cards in msi pcmate z170a board 1.2kw pwsupply all cards on risers r280 r290 r390 rx470,  rx480 all mixed or only rx all combinations no prob . now i set a miner with win7 x64 on  msi pcmate b150, same ethminer standard settings  in startbat for nanopool.  if miner now comes to use ellesmere device it crash, tahiti and hawaii no prob , if i set to work only with tahiti/hawaii cards (with device 0 1 2 or -t  comand) all ok. if i mix with ellsmere device like rx470, 480 or use ellesmere allone it crash. both rigs have same pwsupply same ram  (8Gb)  almost same bios with above 4G for multigpu-minig enabled. driver is this new crimson miningedition driver.  clean unsistall reinstal allready done. same with bios, reset to default and  set again. in devicemanager and crimson the cards are ok. i did no biosmods. in ethminer i tried to set the cards to sequential settup with  -L but no change.  the R280 has 3Gb, r290  4Gb r390 8Gb , the rx 480 8Gb vram. it crash always if it comes to use ellesmere device and want to load dagfile ? the only difference is win 10 x64 to win7 x64.

**Comment by ddobreff** [comment]
You are mixing Tahiti, Hawaii and Ellesmere in the same rig, which forces driver to switch between legacy and current. I guess by removing Tahiti GPU(280) others can work without issue.

**Comment by Rob-2017** [comment]
hi thx for reply,
hmmm i just removed 280 from rig, reset bios, reinstalled crimson driver, same issue. additional to amd driver removal tool this time  i used registry fix from ccleaner . it found some amd related issues and fixed it. but same problem. i use ethminer 0.11.0 also  i just tried old ethminer 0.9.41 and newer 0.12.0 dev2. i can remove 290,390 from rig but i already tried to mine with only one 480 by switch off the others with device command. i think its a prob with handling opencl with ellesmere gpu. how to check if windows it set correct ? its new clean win 7 x64. i never used opencl application on it. is there a way to check this? im sure in win10 i had mixed all gpus in ethminer 0.11.0 just the 390 i did not use in it but all the rest. it just worked. never had to think about it.

**Comment by ddobreff** [comment]
I am not windows miner but most of my known windows miners use windows 10 with latest blockchain driver with 390/480/580 mix without any issues.

**Comment by Rob-2017** [comment]
Problem is caused by "Radeon Software Crimson ReLive Edition Beta for Blockchain Compute Driver for Windows® 7 64/32 bit​ ". With "Crimson 17.7.2  Minimal Setup" Ethminer is now  working with all cards. I didnt expect this because win 10 work so well with it. I hope they will fix this even if they state to provide no further update for this driver because i cant use more than 4 cards with the normal drivers.
