### ISSUE TITLE
reported hashrate inconsistent

### ISSUE THREAD

**Issue by dhjw** [ethereum-mining/ethminer#277]
I'm relatively new to mining, so this may be a noob question. I see my current effective hashrate fluctuating quite a bit. See: http://i.imgur.com/Zj8NVnY.jpg Is this normal or does my rig have a dirty power, riser or other issue? Thanks

**Comment by smurfy** [comment]
Currently the way we calculate the reported hashrate is quite simplistic. Not really smooth.
You can improve it by setting a higher ``--farm-recheck 5000`` value. (If you are using stratum mode)
