### ISSUE TITLE
How to reduce the GPU-load / clocking / power consumption?

### ISSUE THREAD

**Issue by itinance** [ethereum-mining/ethminer#278]
Is it possible to lower the GPU-Load?

Starting ethminer makes the GPUs running on full power but we want to reduce the clocking. We use a rig with several ATI Readeon 480 with 4 GB.

```
hagen@mine1:~$ amdcovc
Adapter 0: Device 67df
  Core: 1365 MHz, Mem: 1750 MHz, CoreOD: 0, MemOD: 0, Temp: 64 C, Fan: 52.9412%
  Core clocks: 300 600 900 1145 1215 1257 1300 1365
  Memory Clocks: 300 1000 1750
Adapter 1: Device 67df
  Core: 1365 MHz, Mem: 1750 MHz, CoreOD: 0, MemOD: 0, Temp: 58 C, Fan: 47.8431%
  Core clocks: 300 600 900 1145 1215 1257 1300 1365
  Memory Clocks: 300 1000 1750
```

Instead of 1365 Mhz we want to reduce the core clocks to 900 Mhz.

I stumbled upon [this thread](https://www.reddit.com/r/EtherMining/comments/6m7uo3/reduce_gpu_usage_in_ethminer/) on reddit and so I've tried 

`export GPU_MAX_ALLOC_PERCENT=25`

but this does nothing.

Then i've found out that this parameter is set to 100 [in the main.cpp](https://github.com/ethereum-mining/ethminer/blob/master/ethminer/main.cpp#L61). So i changed it to 50 and recompiled ethminer. But the GPU still runs on full heavy load.

Also i've found several postings where people talk about the following switches:
```
-ethi 1
-li 1
```

but this version of ethminer doesnt accept them ("Invalid switch -li")

Can someone help?

**Comment by AndreaLanfranchi** [comment]
Over/Under clocking is beyond the scope of ethminer: this miner does not touch the clocks of your GPU. It sends works to the GPU and wait for the GPU to return results. GPUs work at the speed they're set to work.
If you want to lower power consumption and/or lower cores and memory clocks of your gpu you should use specific tools from AMD.
I am using NVIDIA and have tools like nvidia-smi and nvidia-settings (on Windows you can use MSI's Afterburner or similar).

**Comment by AndreaLanfranchi** [comment]
ethi and li are probably some heritage from different forks and are related to the "intensity" which is something completely different from the GPU speed. Intensity was meant to set some sort of delay between thread starts (very very basic explanation) to prevent the system to use full system resources on the miner.

**Comment by itinance** [comment]
Thank you very much for clarifying @AndreaLanfranchi !
