### ISSUE TITLE
compiling fails on debian unstable

### ISSUE THREAD

**Issue by kroupouk666** [ethereum-mining/ethminer#279]
Compiling ethminer fails on debian unstable with gcc5

`[ 95%] Linking CXX executable ethminer
/usr/bin/ld: ../libethash/libethash.a(internal.c.o): relocation R_X86_64_32S against .rodata' can not be used when making a shared object; recompile with -fPIC /usr/bin/ld: ../libethash/libethash.a(sha3.c.o): relocation R_X86_64_32S against.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../libethash-cuda/libethash-cuda.a(ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o): relocation R_X86_64_32 against symbol `_Z25ethash_calculate_dag_itemj' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status'

Make sure g++ /usr/bin/g++ is symlinked to g++-5.

Then compilation will work perfectly

**Comment by jasonwee** [comment]
how about this? i tried to compile using gcc5 and have g++ package installed, but still complaint cc1plus no such file or dir
```
[ 70%] Built target ethstratum
[ 73%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
gcc-5: error trying to exec 'cc1plus': execvp: No such file or directory
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.Release.cmake:222 (message):
  Error generating
  /home/user/ethminer/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o


libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:63: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o' failed
make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
CMakeFiles/Makefile2:440: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/all' failed
make[1]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by MariusVanDerWijden** [comment]
What version of nvcc are you using?

**Comment by jasonwee** [comment]
version 9.0 is still in experimental, not even in unstable yet... 
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```

so i remove `compute_70` and got the above error

```
diff --git a/libethash-cuda/CMakeLists.txt b/libethash-cuda/CMakeLists.txt
index 58560cd29..966824599 100644
--- a/libethash-cuda/CMakeLists.txt
+++ b/libethash-cuda/CMakeLists.txt
@@ -19,7 +19,6 @@ else()
                "-gencode arch=compute_60,code=sm_60"
                "-gencode arch=compute_61,code=sm_61"
                "-gencode arch=compute_62,code=sm_62"
-               "-gencode arch=compute_70,code=sm_70"
        )
 endif()
```

and using gcc-5

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 989a2738e..a04c796d5 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -43,6 +43,9 @@ endif()
 project(ethminer)
 set(PROJECT_VERSION 0.13.0.dev0)
 
+set(CUDA_HOST_COMPILER /usr/bin/gcc-5)
+find_package(CUDA)
+
 # link_directories interprate relative paths with respect to CMAKE_CURRENT_SOURCE_DIR
 cmake_policy(SET CMP0015 NEW)
```

**Comment by MariusVanDerWijden** [comment]
Maybe you miss a symlink to cc1 
https://stackoverflow.com/questions/11912878/gcc-error-gcc-error-trying-to-exec-cc1-execvp-no-such-file-or-directory

**Comment by jasonwee** [comment]
hmm.. okay, i will try the first thing in the morning.

**Comment by DeadManWalkingTO** [comment]
Try to compile the latest (master) version and feedback please.
Thank you!
