### ISSUE TITLE
question

### ISSUE THREAD

**Issue by publicocean0** [ethereum-mining/ethminer#280]
hi i m trying ethminer in my pc 
```
  ℹ  00:51:13|ethminer  Found suitable OpenCL device [ GeForce 930M ] with 2100232192  bytes of GPU memory
Benchmarking on platform: CUDA
Preparing DAG for block #0
Warming up...
Trial 1... 0
Trial 2... 0
Trial 3... 0
Trial 4... 0
Trial 5... 0
min/mean/max: 0/0/0 H/s
inner mean: 0 H/s
```
` ℹ  00:54:50|ethminer  Found suitable OpenCL device [ GeForce 930M ] with 2100232192  bytes of GPU memory
 cl  00:54:50|cl-0      No work. Pause for 3 s.
  m  00:54:50|ethminer  Waiting for work package...
  m  00:54:51|ethminer  Got work package: #cfbe5a76
  m  00:54:51|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  00:54:52|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  00:54:52|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  00:54:53|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
 cl  00:54:53|cl-0      New work: header #cfbe5a76… target 000000044b82fa09b5a52cb98b405447c4a98187eebb22f008d5d64f9c394ae9
 cl  00:54:53|cl-0      New seed #0986c6a2…
  m  00:54:54|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  00:54:55|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
 cl  00:54:55|cl-0      Platform: NVIDIA CUDA
 cl  00:54:55|cl-0      Device:   GeForce 930M  / OpenCL 1.2 CUDA
 cl  00:54:55|cl-0      Build info: 

 cl  00:54:55|cl-0      Creating light cache buffer, size 35127104
 cl  00:54:55|cl-0      Creating DAG buffer, size 2248145024
 cl  00:54:55|cl-0      Loading kernels
 cl  00:54:55|cl-0      Writing light cache buffer
 cl  00:54:55|cl-0      Creating buffer for header.
 cl  00:54:55|cl-0      Creating mining buffer
 cl  00:54:55|cl-0      Generating DAG
  ✘  00:54:55|cl-0      clEnqueueNDRangeKernel ( -4 )
 cl  00:54:55|cl-0      Switch time 4191 ms / 1527225 us
  ✘  00:54:55|cl-0      OpenCL Error: clEnqueueNDRangeKernel -4
  m  00:54:55|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R`
Why 0H/S?

**Comment by publicocean0** [comment]
ethminer -G -M
  ℹ  01:40:34|ethminer  Found suitable OpenCL device [ GeForce 930M ] with 2100232192  bytes of GPU memory
Benchmarking on platform: CL
Preparing DAG for block #0
 cl  01:40:34|cl-0      No work. Pause for 3 s.
Warming up...
 cl  01:40:37|cl-0      New work: header #50c856ae… target 0000000000000002000000000000000000000000000000000000000000000000
 cl  01:40:37|cl-0      New seed #00000000…
 cl  01:40:38|cl-0      Platform: NVIDIA CUDA
 cl  01:40:38|cl-0      Device:   GeForce 930M  / OpenCL 1.2 CUDA
 cl  01:40:38|cl-0      Build info: 

 cl  01:40:38|cl-0      Creating light cache buffer, size 16776896
 cl  01:40:38|cl-0      Creating DAG buffer, size 1073739904
 cl  01:40:38|cl-0      Loading kernels
 cl  01:40:38|cl-0      Writing light cache buffer
 cl  01:40:38|cl-0      Creating buffer for header.
 cl  01:40:38|cl-0      Creating mining buffer
 cl  01:40:38|cl-0      Generating DAG
 cl  01:40:41|cl-0      DAG 0 %
 cl  01:40:43|cl-0      DAG 6 %
 cl  01:40:46|cl-0      DAG 12 %
 cl  01:40:48|cl-0      DAG 18 %
Trial 1...  cl  01:40:50|cl-0      DAG 25 %
0
Trial 2...  cl  01:40:53|cl-0      DAG 31 %
0
Trial 3...  cl  01:40:55|cl-0      DAG 37 %
 cl  01:40:58|cl-0      DAG 43 %
0
Trial 4...  cl  01:41:00|cl-0      DAG 50 %
0
Trial 5...  cl  01:41:02|cl-0      DAG 56 %
0
 cl  01:41:05|cl-0      DAG 62 %
Errore di segmentazione (core dump creato)

**Comment by AndreaLanfranchi** [comment]
This is mainly related to these possible issues:

1. You're overclocking too much
2. If not overclocking you have a problem in data transferring from pc to gpu (is your GPU on board or is it connected through a raiser ?)
3. Segmentation fault means the program cannot access a specific memory address: either you have faulty ram on your GPU or, may happen, your PC has a faulty ram.

**Comment by derubm** [comment]
2,100,232,192 bytes GPU Memory is not enough.

**Comment by AndreaLanfranchi** [comment]
Whoops ... didn't see you had only 2G of ram on your GPU.
With that GPU RAM you can only mine UBIQ with ethminer.
See https://ubiqpool.io/#/

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
