### ISSUE TITLE
PLease fix DAG same Claymore, ethminer mine with GPU have hash low than claymore

### ISSUE THREAD

**Issue by lythongac** [ethereum-mining/ethminer#281]
PLease fix DAG same Claymore, ethminer mine with GPU have hash low than claymore

**Comment by AndreaLanfranchi** [comment]
Please report:

1. Which OS are you on (Windows ? Linux ?)
2. Which GPU(s) are you using ? (Vendor/Model)
3. Which Driver version are you using
4. Data comparison between ethminer and calymore's

For my experience both miners should have roughly the same hashrate; in my personal case I've been able to get better results with ethminer as I can overclock a little bit more keeping stability.

**Comment by aliceaia** [comment]
fix DAG by driver not miner.

**Comment by sulzbach** [comment]
Our experience is the same as @AndreaLanfranchi. The results are the same or better than Claymore.

**Comment by rs2pt** [comment]
Hi
Using windows 10 with a gtx1070 rig values are identical on both miners, but with a rx580 ethminer is almost 1-2 mhs lower :-/

**Comment by MariusVanDerWijden** [comment]
Are you using Cuda with the gtx 1070s?
There's a big difference between the CUDA and the OpenCL kernel

**Comment by rs2pt** [comment]
on the rig with the gtx 8x 1070s I think so... I am using "EthMiner 12" witch hashes same speed basically as when user Claymore... each card shows 31,xxx usually
but on my other rig I have 6x rx580 4gb and in Claymore each hashes about 29-30,xxx but if use same EthMiner each card only hashes 27-28.xxx
I just wonder if that is normal.

**Comment by MariusVanDerWijden** [comment]
That is normal afaik

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
