### ISSUE TITLE
log ethminer console on a log file

### ISSUE THREAD

**Issue by aliceaia** [ethereum-mining/ethminer#282]
I use ubuntu 16.04. Is there a way to save log files?

**Comment by rdasx** [comment]
You can redirect stdout to a log file:
'ethminer --whatever -Your --options' > /home/minername/ethminer.log

If you want to watch, you can use "tail -f /home/minername/ethminer.log"

Or you can write a systemd unit to run your miner which will automatically
save the output to the journal

**Comment by aliceaia** [comment]
Thank you. i'll try.

**Comment by aliceaia** [comment]
It has created to the log file , but log file  empty.

**Comment by rdasx** [comment]
Looks like ethminer prints to start and stderr. Same command as before but
add 2>&1 after mine.log

**Comment by rdasx** [comment]
*stdout not start. Autocorrected.

**Comment by derubm** [comment]
use tee

**Comment by chronossc** [comment]
Here I use: 

```$ETHMINER -U -S $POOL1 -FS $POOL2 -O "${WALLET}.${WORKER}/${EMAIL}" ${OPTS} 2>&1  | tee -a "/home/felipe/mining/ethminer-$(date +%Y%m%d).log";```

I also zip all logs but not last one.
