### ISSUE TITLE
does the CUDA GPU id always correspond with nvidia-smi?

### ISSUE THREAD

**Issue by dhjw** [ethereum-mining/ethminer#283]
i.e. does CUDA4 in ethminer always equal GPU 4 in nvidia-smi?

It seems to me it does, based on my experience tweaking memory clocks lower on the first reported ID improving stability after crashes, but I thought I'd ask to be certain after reading [this](https://codeyarns.com/2016/07/05/how-to-make-cuda-and-nvidia-smi-use-same-gpu-id/)

**Comment by emminer** [comment]
No, it isn't guaranteed. I have a rig with 1x 1080 and 3x 1080ti
nvidia-smi:
1080
1080ti
1080ti
1080ti

ethminer:
1080ti
1080
1080ti
1080ti

**Comment by hcbraun** [comment]
Thank you for the link. What a stupid default to put the fastest card first.

**Comment by dhjw** [comment]
More at https://github.com/ethereum-mining/ethminer/issues/286
