### ISSUE TITLE
Is there a timeframe for GDDR5X full utilization?

### ISSUE THREAD

**Issue by 4score** [ethereum-mining/ethminer#284]
Was just reading this:

> Why is a GTX 1080 slower than a GTX 1070?
>      Because of the GDDR5X memory, which can't be fully utilized for ETH mining (yet).

.. and was wondering if there's a date in mind for when ethminer could fully take advantage of 1080 cards?

Thanks

**Comment by chfast** [comment]
No plans for this.

**Comment by Contez** [comment]
Would it be possible to have more information on how the miner is not optimized for GDDR5X? Is it a matter of timings?
Thanks
