### ISSUE TITLE
illegal memory access was encountered.

### ISSUE THREAD

**Issue by roachadam** [ethereum-mining/ethminer#285]
![Alt text](https://i.imgur.com/fresc18.png)

Specs:
Windows 10 64-bit home
4gb ram
6x1070 Nvidia FE
ethminer v0.11.0

I know this issue has been posted before, but I did not find a solution to this issue. I've messed with my OC's, lowering them, as well as increasing pagefile size in windows with the same results. After a few hours I get this error.

**Comment by aliceaia** [comment]
Often this error due to wrong overclock.

**Comment by roachadam** [comment]
@aliceaia I figured that was the issue, but it ran stable for 2 months on the same OCs, so I'm not sure what happened. I lowed it and still got the same result.

For now I'm testing Claymore's to see if it encounters a similar error with the same OC.

**Comment by dafyk** [comment]
Different miner is not a good test (theres high chance calymore will work fine), but try to replicate your problem with single GPU. My expectations are that ethminer wont crash with single card and @aliceaia is right (i also believe its problem with OC or power issues)

**Comment by yamid-ny** [comment]
I have the same problem with 1060 3gb, it was run 1 month without problem but now only a card (from 5 1060s) restart complete rig, I only use 4 1060s and the rig works very well but when I put the "rare" GPU the rig shows the problem.
.
Thanks for the help and the best energy for all.

Rig: Asus B250 mining expert, 8gb RAM, Celeron 3930, EVGA 750 GQ, SMOS (simple mining os) Claymore 10.0, 1060 3GB Gibabyte

**Comment by derubm** [comment]
Happens due to P2 state switching into P0 state on Nvidia cards, 
Solution: set your cards to P0 state from start on.
(windows: nvidia inspector, linux: nvidia-smi)
![image](https://user-images.githubusercontent.com/6720202/33154889-e8ece266-cfeb-11e7-83be-09948d8bd479.png)

**Comment by DeadManWalkingTO** [comment]
You can use the [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW) 

* At section "5 - Common"
** Change "CUDA - Force P2 State" to "Off"
** Change "Power management mode" to "Prefer maximum performance"
* Click "Apply Changes"
* Reboot and start mining!

**Comment by DeadManWalkingTO** [comment]
GTX1060 +150/+500/65%TDP @ 23-24MHs

1. Try Update Drivers.
Download and install the latests.

2. Try Update Ethminer.
Download (or beter build) the latest.

3. Try use -U for CUDA devices.
Test launch command:
`ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

4. Try to change P2 State and Power managment mode.
You can use [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW).
For the best mining hashrate choose from sector "5 - Common":
    - CUDA - Force P2 State (Set to "Off")
    - Power managment mode (Set to "Prefer maximum performance")

5. Try Tweak Win10.
You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) (#695).

6. Try Optimize/Overclock GPUs. 
You can use [MSI Afterburner](https://www.msi.com/page/afterburner) for GPU OverClock/Optimize. 

7. Try use a WatchDog
You can use [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) (#735).

Please feedback.
Thank you!

**Comment by lazlomo** [comment]
> GTX1060 +150/+500/65%TDP @ 23-24MHs
> 
> 1. Try Update Drivers.
>    Download and install the latests.
> 2. Try Update Ethminer.
>    Download (or beter build) the latest.
> 3. Try use -U for CUDA devices.
>    Test launch command:
>    `ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`
> 4. Try to change P2 State and Power managment mode.
>    You can use [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW).
>    For the best mining hashrate choose from sector "5 - Common":
>    
>    * CUDA - Force P2 State (Set to "Off")
>    * Power managment mode (Set to "Prefer maximum performance")
> 5. Try Tweak Win10.
>    You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) ([Solution for 100% CPU usage (Win10 - CUDA - OpenCL) #695](https://github.com/ethereum-mining/ethminer/issues/695)).
> 6. Try Optimize/Overclock GPUs.
>    You can use [MSI Afterburner](https://www.msi.com/page/afterburner) for GPU OverClock/Optimize.
> 7. Try use a WatchDog
>    You can use [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) ([Simple Script WatchDog #735](https://github.com/ethereum-mining/ethminer/issues/735)).
> 
> Please feedback. Thank you!

I'm mining on a 3060ti lhr I was getting 43+mhs
then suddenly 2days ago my hashrates wont go up 38
and also when I use photoshop for drawing my hashrates tanks down heavily and lhr kicks in about every 1 min.
and the hashrates plummits to 20-25mhs.

This was not an issue few days ago I use to mine and draw at same time and get 43mhs  my oc set was  cc-500 mc+950 PL70  (hynix mem)
