### ISSUE TITLE
show pci bus id when list the gpus using --list-devices

### ISSUE THREAD

**Issue by emminer** [ethereum-mining/ethminer#286]
Sometimes gpu index doesn't correspond with nvidia-smi, so need the pci bus id to fix it.
just add
outString += "\tpciBusID:" + to_string(props.pciBusID) + "\n";
to 
libethash-cuda/ethash_cuda_miner.cpp

**Comment by zbobyuan** [comment]
I found a better solution to solve the gpu index issue from this [blog](https://codeyarns.com/2016/07/05/how-to-make-cuda-and-nvidia-smi-use-same-gpu-id/)

set the CUDA_​DEVICE_​ORDER environment variable to PCI_BUS_ID in your shell.

please close this issue.

**Comment by dhjw** [comment]
I was curious to see the bus ID order before adding the environment variable, but compile seems to fail when I add the line given. :(

**Comment by sulzbach** [comment]
But if you have AMD gpus mixed with NVIDIA ?

Printing the pci bus address is really interesting when parsing the log and doing things like a GUI or dashboard (like in my case).

Please reopen this issue.

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!

**Comment by chfast** [comment]
This is implemented.

**Comment by chfast** [comment]
Yes, but the first comment was about Nvidia.
