### ISSUE TITLE
most of the output messages are streamed to stderr

### ISSUE THREAD

**Issue by emminer** [ethereum-mining/ethminer#287]
they should be streamed to stdout.

**Comment by DDDanny** [comment]
I suggest that you just join the output, or tee it to the log and parse it - that worked good for me
... let the devs work on the code of mining opt and cool stuff like hashrate reporting ;)

**Comment by emminer** [comment]
Agree, I also found a npm package to get rid of the colors of outputs
[strip-ansi](https://www.npmjs.com/package/strip-ansi)

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!

**Comment by DeadManWalkingTO** [comment]
#282 (log ethminer console on a log file )

**Comment by moozer** [comment]
output to stdout would be appreciated.

I pipe ethminer output to a parser script, and ends up in issues related to line buffering vs. block buffering.

**Comment by stna1981** [comment]
I also noticed this when using PowerShell to write the output to logfiles. stdout is always empty, everything goes to stderr. This is not only not nice, it should not happen. A fix should be easy, stdout should be the standard and only errors should be written to stderr.

Any plans for chanching this in the near future?

**Comment by stna1981** [comment]
Any update on this? Other miners also log properly to stdout and only errors go to stderr, like it should be. Should not be a big issue to fix this. Short comment from the dev(s) about this would be nice.

**Comment by AndreaLanfranchi** [comment]
With this commit https://github.com/ethereum-mining/ethminer/commit/05d3732a985c4b3e5e0e0cb7786ceb1fbbfe7e82 by @jean-m-cyr a new CLI argument `--stdout` has been introduced.

If you need to output to stdout simply

```
ethminer --stdout [other arguments]
```
