### ISSUE TITLE
Ethminer fails to reconnect()

### ISSUE THREAD

**Issue by fobispo-link** [ethereum-mining/ethminer#288]
Hi Guys,

I'm not sure if this is in the works, but my miners from time to time will encounter a network issue, and will force the process to call `reconnect()` the process will fail to reconnect and will never go out of this cycle.

I found this code commented out:

https://github.com/ethereum-mining/ethminer/blob/master/libstratum/EthStratumClientV2.cpp#L199

and

https://github.com/ethereum-mining/ethminer/blob/master/libstratum/EthStratumClient.cpp#L109

Which are probably related.

In any case, my current workaround was simply to `disconnect()` and `return` causing the process to exit, and have a nanny script ensure the process is fired up again.

Any thoughts?

**Comment by markwendy** [comment]
same here

**Comment by marcofranssen** [comment]
+1 might be related to my crashes mentioned in #340

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!

**Comment by fobispo-link** [comment]
I have not seen the issue in the latest release.. Thank you!
