### ISSUE TITLE
Average hashrate (speed)

### ISSUE THREAD

**Issue by mnik247** [ethereum-mining/ethminer#291]
Is it possible add calculated average hashrate (speed) for 1 (last) minute?
And then use it for reported hashrate to pool?

**Comment by aliceaia** [comment]
This looks like CM

**Comment by DeadManWalkingTO** [comment]
Maybe enhancement.

**Comment by AndreaLanfranchi** [comment]
At present releases (0.14 and 0.15) HR is SMA on 10 seconds.
