### ISSUE TITLE
cmake error in Windows

### ISSUE THREAD

**Issue by Stephen-Kp** [ethereum-mining/ethminer#296]
Hi,

Can you help with this CMake error in Windows? I only added from just above where I got the error. I can send more information if you let me know what you need.

Performing download step (download, verify and extract) for 'Boost'
  -- Boost download command succeeded.  See also C:/.hunter/_Base/aafb99b/8743852/68dfa9a/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-download-*.log
  No update step for 'Boost'
  No patch step for 'Boost'
  Performing configure step for 'Boost'
  -- Boost configure command succeeded.  See also C:/.hunter/_Base/aafb99b/8743852/68dfa9a/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-configure-*.log
  No build step for 'Boost'
  Performing install step for 'Boost'
  CMake Error at C:/.hunter/_Base/aafb99b/8743852/68dfa9a/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug.cmake:16 (message):
    Command failed: 1

     'C:/Program Files/CMake/bin/cmake.exe' '-Dmake=' '-Dconfig=Debug' '-P' 'C:/.hunter/_Base/aafb99b/8743852/68dfa9a/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug-impl.cmake'

    See also

      C:/.hunter/_Base/aafb99b/8743852/68dfa9a/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-*.log

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\.hunter\_Base\aafb99b\8743852\68dfa9a\Build\Boost\Build\Boost.vcxproj]
Done Building Project "C:\.hunter\_Base\aafb99b\8743852\68dfa9a\Build\Boost\Build\Boost.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\.hunter\_Base\aafb99b\8743852\68dfa9a\Build\Boost\Build\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\.hunter\_Base\aafb99b\8743852\68dfa9a\Build\Boost\Build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\.hunter\_Base\aafb99b\8743852\68dfa9a\Build\Boost\Build\Boost.vcxproj" (default target) (3) ->
(CustomBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\.hunter\_Base\aafb99b\8743852\68dfa9a\Build\Boost\Build\Boost.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:28:46.54

[hunter ** FATAL ERROR **] Build step failed (dir: C:/.hunter/_Base/aafb99b/8743852/68dfa9a/Build/Boost
[hunter ** FATAL ERROR **] [Directory:C:/.hunter/_Base/Download/Hunter/0.19.86/aafb99b/Unpacked/cmake/projects/Boost]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.19.86/aafb99b/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.19.86/aafb99b/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  C:/.hunter/_Base/Download/Hunter/0.19.86/aafb99b/Unpacked/cmake/modules/hunter_download.cmake:596 (hunter_fatal_error)
  C:/.hunter/_Base/Download/Hunter/0.19.86/aafb99b/Unpacked/cmake/projects/Boost/hunter.cmake:272 (hunter_download)
  C:/.hunter/_Base/Download/Hunter/0.19.86/aafb99b/Unpacked/cmake/modules/hunter_add_package.cmake:53 (include)
  CMakeLists.txt:119 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "C:/Users/Owner/Desktop/Newfolder2/ethminer-master/build/CMakeFiles/CMakeOutput.log".

**Comment by smurfy** [comment]
Please use VS 2015,  neither 2017 nor 2013 work.

**Comment by Stephen-Kp** [comment]
Thank you, smurfy!

Just in case anyone has to go through this, I want to save them a whole lot of frustration. Do the following:

install Visual Studio 14 2015 from the Visual Studio site after logging in.
	choose custom install	
	add c++ language support (not added by default)
copy 
	rc.exe and rcdll.dll 

	from 	"C:\Program Files (x86)\Windows Kits" 		(just search for them in there. I found like 6 copies of each. I copied them from C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x86)
	to	"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin"


rerun cmake

**Comment by hiperz** [comment]
I had exactly same error as @Stephen-Kp. I got the same error even though I tried compiling with VS2015 instead of VS2017. This error is not because of VS version because compiling with VS2017 in my another PC works fine.

**Comment by KunaniGaming** [comment]
I had the same issue but I was using the CMAKE GUI and selecting VS 2015 x64. Once I selected VS 2015 only it worked perfectly.

**Comment by zarochi** [comment]
I was able to get it to build on VS 2017 Community with similar steps to Stephen-Kp

Go to C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\x64
Copy rc.exe and rcdll.dll to:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\Hostx64\x64 and C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\Hostx86\x64

Go to C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\x86
Copy rc.exe and rcdll.dll to:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\Hostx64\x86 and C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\Hostx86\x86

Compile as x64-Release

I think x86-Release would work too, but I have no idea why you would even want to do that.
