### ISSUE TITLE
Show only hashrate/gpu when it's ready

### ISSUE THREAD

**Issue by Chinafreak** [ethereum-mining/ethminer#298]
It's kinda irritating when ethminer show hashrate/GPU even DAG file isn't loaded yet. (So it prints everytime 0.00Mh/s). It should print only once everything is done.

**Comment by AndreaLanfranchi** [comment]
Sorry if I go a little bit off topic but I think too many people complain about what they see on the screen (completely unuseful) while we should encourage developers to concentrate on the effectiveness of mining (algo, stabilty, performance).
Sorry for my rant.

**Comment by Chinafreak** [comment]
I'm just putting on issue and I'm not complaints. Sure they can focus on effectiveness. :)
When I got time, then **maybe** I can work on better logs system.

**Comment by Chinafreak** [comment]
And also it's not unuseful, it's kinda hard to spot error/info when the console prints continue 0.00 Mh/s

**Comment by marcofranssen** [comment]
I would change this issue to mention it should not start mining if there is no DAG yet. The output is most proabbaly a result of the mining already started in a separate thread.

**Comment by DeadManWalkingTO** [comment]
Maybe enhancement.
