### ISSUE TITLE
Hashrate shows wrong sometimes

### ISSUE THREAD

**Issue by Chinafreak** [ethereum-mining/ethminer#300]
When I'm trying to mine with my GPU (nvidia), the hashrate from logs show incorrect. Sometimes it show at double hashrate, sometimes zero hashrate.

I'm not currently at home, but something like that prints:

```
  m  14:28:56|main      Speed   42.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  14:28:58|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  14:29:00|main      Speed   42.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  14:29:02|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  14:29:04|main      Speed   42.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  14:29:06|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  14:29:08|main      Speed   21.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  14:29:10|main      Speed   21.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  14:29:12|main      Speed   42.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  14:29:14|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  14:29:16|main      Speed   42.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  14:29:18|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  14:29:20|main      Speed   42.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  14:29:22|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
```

When I'm at home, I'm going to take screenshot how it really looks like. I'm using MSI Nvidia Geforce 1080 GTX with 8GB Storage

**Comment by smurfy** [comment]
whats your ``--farm-recheck`` value? try increasing it if you are in stratum mode.

**Comment by Chinafreak** [comment]
I'll check it when I'm at home. I think it was --farm-recheck 200?

**Comment by Blacksuu** [comment]
there are few thing what rise question:
1. m  14:28:58|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] = unstable OC my be, if you done any Overclock try to run on default & see if you will get thing like that with is not normal ...
2. Client not see correct value aka Speed 42 or 21 with GPU/0 0.00 it suppose to be same 
- m  14:28:56|main      Speed   **42.00 Mh/s**    gpu/0  **0.00**  [A0+0:R0+0:F0]
- m  14:29:08|main      Speed   **21.00 Mh/s**    gpu/0  **0.00**  [A0+0:R0+0:F0]
question:
 a. you have only 1 GPU ? or you have more ? try add in command --cuda-devices 0 (set correct number according with video card you want to use if you have multiple)
 b. What system do you use linux, windows ? my bet from how it look your data windows 7 ...
 c. double speed or jumpy hrate i think is cause by --cuda-grid-size BUT first you need to fix thing to not have any 0.00 Mh/s & then try to play with that setting
 d. yes --farm-recheck setting it can bring diferite value (double is a litle to much variance like 39-42 is fine but double nop most defently is a other issue there) BUT like i say on point C. before of all resolve problem wiht 0.00 Mh/s

**Comment by Chinafreak** [comment]
Sorry, I forgot to set the gpu/0 hashrate because I don't have the original log (not currently at home). It should be same like the hashrate from speed.

Yes, I've only 1 GPU, I'm using Windows 10 and my GPU can reach 21 Mh/s according to mining pool.
No I don't play game & mine at the same time. I only mine when I'm not using PC at all.

I'll try your methods when I'm at home!

**Comment by Blacksuu** [comment]
well forget about pool first you need to have a steady constant client report value with small variance on value between 41 > 42 is fine let say, double or 0 nop that it show it is a issue with card or oc or something it make drop

**Comment by Chinafreak** [comment]
I don't think so that is a issue with my card, because other ethereum miners works fine without to drop. I guess it's just too fast because of --farm-recheck due 200ms.

**Comment by Blacksuu** [comment]
well your choise i will say one more time small variance on value is fine / OK > BUT receive drop from Max to 0 or double is NOT, anyway play with setting till you will get a stable runing ... when you speak about other miner aka let say claymore i bet he have a constant value but other miner or that miner it working diferite vs how it working etherminer
anyway it will be interesting to see how it will goo after you will play with setting
cheers

**Comment by Chinafreak** [comment]
Increasing --farm-recheck from 200 to 2000 works fine. Now the Mh/s shows correctly.
