### ISSUE TITLE
iMAC with AMD Radeon R9 M295X 4096 MB only 2,3 - 2,8 MH/s

### ISSUE THREAD

**Issue by nerle** [ethereum-mining/ethminer#308]
Hi, reading about 40MH/s possible with AMD Radeon R9 M295X 4096 MB so I gave my iMac an try and installed ethminer. With ethminer 0.10 I get around 2,3-2,8 MH/s (and I could work with iMac).

With etminer 0.12 I get some 1,7 MH/s and every 4 or 5 PoWash a 3,8 MH/s but the iMac slows down and its very hard to use them while mining. 

With around 2 MH/s its only fun to understand the concept it would pay the electricity bills :-)
 
Won't it be possible with OS X to reach around 40MH/s or doing I something wrong?  Any ideas?

**Comment by nerle** [comment]
No ideas out there? 

Does anybody use the AMD R9 M295X under Windows or Linux with ethminer?

**Comment by derubm** [comment]
stands the "M" for mobile ? - also is that a x2 ?

**Comment by nerle** [comment]
I don't think that M stands for mobile. It's a 5K high performance (not cheap) iMac. It's not a x2, that could be the reason.

**Comment by angel12** [comment]
I see the same kind of issue when mining on MacOS High Sierra with an RX 580. I get around 3-4mh/s instead of the expected 15-25mh/s

**Comment by angel12** [comment]
And the iMac's do use a notebook based graphics card, just fyi

**Comment by davidmckenzie** [comment]
Getting the same with iMac with M395x

```
$ bin/ethminer -G -M
  ℹ  15:59:08|          Found suitable OpenCL device [ AMD Radeon R9 M395X Compute Engine ] with 4294967296  bytes of GPU memory
Benchmarking on platform: CL
Preparing DAG for block #0
 cl  15:59:08|cl-0      No work. Pause for 3 s.
Warming up...
 cl  15:59:11|cl-0      New work: header #50c856ae… target 0000000000000002000000000000000000000000000000000000000000000000
 cl  15:59:11|cl-0      New seed #00000000…
 cl  15:59:11|cl-0      Platform: Apple
 cl  15:59:11|cl-0      Device:   AMD Radeon R9 M395X Compute Engine  / OpenCL 1.2
 cl  15:59:12|cl-0      Build info: <program source>:329:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~
<program source>:364:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~

 cl  15:59:12|cl-0      Creating light cache buffer, size 16776896
 cl  15:59:12|cl-0      Creating DAG buffer, size 1073739904
 cl  15:59:12|cl-0      Loading kernels
 cl  15:59:12|cl-0      Writing light cache buffer
 cl  15:59:12|cl-0      Creating buffer for header.
 cl  15:59:12|cl-0      Creating mining buffer
 cl  15:59:12|cl-0      Generating DAG
 cl  15:59:12|cl-0      DAG 0 %
 cl  15:59:12|cl-0      DAG 6 %
 cl  15:59:12|cl-0      DAG 12 %
 cl  15:59:13|cl-0      DAG 18 %
 cl  15:59:13|cl-0      DAG 25 %
 cl  15:59:13|cl-0      DAG 31 %
 cl  15:59:13|cl-0      DAG 37 %
 cl  15:59:14|cl-0      DAG 43 %
 cl  15:59:14|cl-0      DAG 50 %
 cl  15:59:14|cl-0      DAG 56 %
 cl  15:59:14|cl-0      DAG 62 %
 cl  15:59:14|cl-0      DAG 68 %
 cl  15:59:15|cl-0      DAG 75 %
 cl  15:59:15|cl-0      DAG 81 %
 cl  15:59:15|cl-0      DAG 87 %
 cl  15:59:15|cl-0      DAG 93 %
 cl  15:59:15|cl-0      Switch time 7523 ms / 4519393 us
Trial 1... 2623013
Trial 2... 2624064
Trial 3... 2622751
Trial 4... 2622488
Trial 5... 2622488
  ✘  15:59:38|cl-0      OpenCL Error: clSetKernelArg -48
min/mean/max: 2622488/2622960/2624064 H/s
inner mean: 2623276 H/s
```

**Comment by ricktobacco** [comment]
i have the same card 
with flags you get 4.20 ;)
--cl-local-work 256 --cl-global-work 16384

**Comment by gratiot** [comment]
Do an Image backup of your HD so you can recover it later. Install your favourite version of Ubuntu running at init 3 (no graphics). Install the latest AMD drivers. install your miner. I bet that will kick up the hash rate. Just getting OSX out of the mix will be a big improvement.

**Comment by angel12** [comment]
We know that mining in other OS is going to be better. This issue’s purpose is to try to get OS X up to par with the other OS. If you don’t have anything to contribute, please don’t bother replying.

**Comment by nerle** [comment]
Nice, the flags put them really  in 4.2 - 4.6 direction!

**Comment by gratiot** [comment]
Have you tried running in single user mode without the GUI. You might find the following link helpful.

http://www.westwind.com/reference/os-x/commandline/single-user.html

**Comment by kcamcam** [comment]
I'm having the same problem, switching to one of the older releases worked for me.

**Comment by nerle** [comment]
Which release and which hasrate do you get?

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!

**Comment by DeadManWalkingTO** [comment]
OpenCL Low Hashrate Report
#152

**Comment by jamesatfish** [comment]
I reported the low hash rate in #152 linked above.

On a 2017 MacBook Pro with AMD Radeon Pro 560 I was seeing around 2.4Mh/s with the standard OpenCL settings.

With the flags mentioned above by @ricktobacco I'm getting about 4.5Mh/s.
