### ISSUE TITLE
getstuff.bat bad URL 

### ISSUE THREAD

**Issue by bstahlman** [ethereum-mining/ethminer#31]
Hey guys is there an alternative URL for getstuff? It seems 'https://build.ethdev.com/builds/windows-precompiled' no longer works.

**Comment by chfast** [comment]
getstuff.bat is not longer needed. Just run cmake as described in [README.md].

**Comment by chfast** [comment]
Fixed in https://github.com/ethereum-mining/ethminer/commit/8e417c2bdac107e7b27a8cc64b22e153cfa3bab7.

**Comment by bstahlman** [comment]
Thanks alot man! Nice work.
