### ISSUE TITLE
Daemon mode on Linux?

### ISSUE THREAD

**Issue by fhlfibh** [ethereum-mining/ethminer#310]
Hi,

How it is possible to run ethminer on Lin in daemon mode?

Regards,
Alex

**Comment by RyanF109** [comment]
not sure if it has daemon mode but I use screen:

sudo apt update && sudo apt install screen
screen ethminer

Ctrl + A followed by Ctrl + D will disconnect the screen and leave it running in the background.

**Comment by RGPreisschild** [comment]
or you can start it per /etc/rc.local with /path/to/miner > /where/output/should/be     and then you can tail

**Comment by fhlfibh** [comment]
With screen it kinda works.
It would be good if ethminer has its own daemon mode, though...

**Comment by rdasx** [comment]
I have mine running in a simple systemd unit. Assuming your distro runs
systemd for it's pretty simple and automatically logs stderr/stdout.
Viewable with journalctl.

**Comment by AndreaLanfranchi** [comment]
Create a miner bash script like this:

```
#!/usr/bin/env bash
ps cax | grep ethminer > /dev/null
if [ $? -eq 0 ]; then
  echo "Ethminer is already running."
else
  echo "Ethminer being launched"
nohup <path-to-ethminer>/ethminer -U \
	-S "<your-pool>" -FS "your-fall-back-pool" \
	--stratum-protocol 1 --report-hashrate \
	-O "$ETH_ADDRESS.$RIGNAME/$MY_EMAIL" -v 9 --farm-recheck 500  \
	>> /var/log/miner.log 2>&1 </dev/null & echo $! > /var/run/miner.pid & sleep 10
fi
```

Then by crontab -e add 
`@reboot sleep 180 && bash <full-path-to-your-miner-bash-script> `

This will start ethminer at boot or you can issue it manually.
If you want to check log simply tail logfile.

**Comment by fhlfibh** [comment]
@AndreaLanfranchi Will try it, thanks!

**Comment by bmatthewshea** [comment]
Can also add init.d script using 'start-stop-daemon' -
1: Copy this to /etc/init.d/ethminer :
https://gist.github.com/bmatthewshea/9a062c092fd673318f8d208ce44f4f51

2: Update top portion of script ^ as needed.

3: Execute:
```
chown root:root /etc/init.d/ethminer
chmod 755 /etc/init.d/ethminer
sudo update-rc.d  ethminer defaults
sudo update-rc.d  ethminer enable
sudo service start ethminer
```

4: Monitor:
`tail /tmp/ethminer.log`
(To see if it's moving..)

5: Stop with:
`sudo service ethminer stop`

You can also use a tool like 'monit' (or many others) to watch the process and/or log file for 'movement' and have it kill / restart if a problem/freezeup/network goes down/etc.
