### ISSUE TITLE
Interresting discovery on low hashrate GTX 1060

### ISSUE THREAD

**Issue by jgueritte** [ethereum-mining/ethminer#314]
Hello !
I think I have make an interresting discovery about those "low hashrate" GTX1060 cards.
As a lot of people, I have normal hashrate and low hashrate GTX1060 cards.

At a memory speed of 3802MHz, I get :
- 19.9MHs and 100% MCL (memory controler load reported in gpu-z) for normal card
- 15.6MHs and 89% MCL for low hash rate card

Than I underclock the memory by 200Mhz (that gives 3597 MHz) and that's where things become interresting ; I get :
- 17.2MHs and 100% MCL for normal card
- 17.0MHs and 100% MCL for low hashrate card
Both cards now have nearly ther same hashrate. And YES, the lowhashrate card performs better with underclocked memory ! Because of the 100% MCL I guess

So I try to find the frequency where the MCL starts to drop, and I find a "jump" at 1700MHz (on my low hashrate card)
- 3685MHz gives 17.4MHs and 100% MCL load
- 3704MHz gives 15.2MHs and 88% MCL load
Which means that something in the driver or in the card bios "lock" the MCL to 88% when the memory clock gets over 3700MHz. 
Note that :
- this does not happend on the high hashrate cards, there is no gap and the MCL load stays at 100%, no matter the memory frequency
- all of this has been tested on two differents computer, and checked a few times !

Finally, I have tried furmark to check of this lock was always here. And no ! Using furmark, it is possible to get 100% MCL load whatever the memory frequency.
Also when using furmark, the card enters P0 state, but stays P2 when mining. But I don't think this is a power-state issue as I have tried (succesfully) to lock my card in P0 state when mining, and the MCL limit at 1700MHz was still here.

To finish : yes the low hashrate has hynix memory. But the MCL drop (-12%) at exactly 1700MHz makes me beleive that this is a firmware ou driver issue.

I hope some here will read this post, test and confirm this MCL issue (that would be great !!) and maybe we will be able to find a solution

Bye !

**Comment by ddobreff** [comment]
I can bet this GPU has Hynix H5GC8H24MJ, meaning that it has defined more loosened timings when you go up and instead of getting better hashrate happens exactly the opposite.

**Comment by jgueritte** [comment]
Yes, this is hynix memory (don't know the exact reference). It probably has loosened timing

But the fact that there is a specific fréquency (3700Mhz, if other user confirm it, this may be differents on other cards) where you get a 12% performance hit prove that this is something is the driver or in the bios (probably timing change when this frequency is reached). 

More interstingly : when using furmark, there is no "3700MHz 12% hit". The frame rate increase with the memory frequency.

I believe something in the driver/bios looses the memory timing when the frequency is above 3700MHz, but only with... Mining software ? CUDA ? Don't know exactly but does not seems to happend in furmark, so something must detect the software use (or the kink of work it does) and change the timing only under certains contitions.
So maybe changing the miner juste a little (make it a "fake" 3D software maybe ??) could resolve the problem.

**Comment by dafyk** [comment]
Can you verify you are actualy running card in P0 by running nvidia-smi while the miner is running? I am pretty sure its running in P2

**Comment by ddobreff** [comment]
3700 is probably the peak before switching to another timing.

**Comment by michaeljohnbennett** [comment]
@dafyk whats the best way to ensure you get the card in P0. I have seen you comment a few times about this and you seem to know a lot about it. 

I was wondering if you could help me understand:

- what is the benefit of keeping the card in the P0 state regards hash output
- The optimal way to get the card there (power,clock settings etc)

Learning lots here reading all these comments/issue threads!

**Comment by dafyk** [comment]
@michaeljohnbennett to "lock" your cards in P0 state read my comment [here](https://github.com/ethereum-mining/ethminer/issues/202#issuecomment-318523568).
> The GPU performance state APIs are used to get and set various performance levels on a per-GPU basis. P-States are GPU active/executing performance capability and power consumption states.

The P-states acts as power management which cap/limit card capabilities to keep it cool/quiet. NVIDIA by default limits all CUDA workload to use P2 state which limits card maximum memory overclocking ability by -200MHz (minus 200 of whatever maximum is set, including overclocking). Ethereum mining hashrate is most affected by speed of memory and thats why miners are trying to overclock memory to maximum and keep power consumption at minimum possible rate

**Comment by michaeljohnbennett** [comment]
Thanks for that @dafyk! 

I'll need to try this on Windoze then, I was running my cards under linux/ubuntu so won't be able to disable that P2 state flag on the cards unless there is a way to do it in nvidia-smi or similar there?

Does anyone know if the features in nvidia-inspector are available for ubuntu?

So, if we can keep the card in the P0 state when running ethminer then we get an extra 200mhz of Memory overclock on the cards, is that correct?

**Comment by dafyk** [comment]
@michaeljohnbennett its not extra 200MHz, its just your card is not throttled down by 200MHz and can run at full processing power/speed in P0 state.
If you find some way how to lock P0 on Linux please report it back here.

**Comment by derubm** [comment]
@dafyk sudo nvidia-smi ?

**Comment by tsauce** [comment]
I thought it was always this:

nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1

**Comment by DeadManWalkingTO** [comment]
GTX1060 +150/+500/65%TDP @ 23-24MHs

1. Try Update Drivers.
Download and install the latests.

2. Try Update Ethminer.
Download (or beter build) the latest.

3. Try use -U for CUDA devices.
Test launch command:
`ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

4. Try to change P2 State and Power managment mode.
You can use [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW).
For the best mining hashrate choose from sector "5 - Common":
    - CUDA - Force P2 State (Set to "Off")
    - Power managment mode (Set to "Prefer maximum performance")

5. Try Tweak Win10.
You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) (#695).

6. Try Optimize/Overclock GPUs. 
You can use [MSI Afterburner](https://www.msi.com/page/afterburner) for GPU OverClock/Optimize. 

7. Try use a WatchDog
You can use [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) (#735).

Please feedback.
Thank you!

**Comment by tsauce** [comment]
Thanks for this. I will say this though. It's probably due to the memory
chips on the graphics cards.

**Comment by momowchang** [comment]
Thanks a lot @DeadManWalkingTO. I only did the step four and everything was awesome.

**Comment by XhmikosR** [comment]
I have a similar issue with a couple of 1070's but when I force P0 state after a few hours even on 70% power and 0/+150, ethminer's hashrate drops and usage goes to 0.

If I leave the cards on P2 state everything is fine. Memory is Micron. The gain from using P0 isn't negligible, it's around 1.8Mh/s for each card.

Anyone else has a working config with 1070 and P0?

**Comment by ivanlucci1** [comment]
I have x6 GTX 1060 (Hynix) and have tried all methods that i found on the internet for increasing hash, OC or fix crashes, but nothing works! :(

Looks like these GPUs with Hynix memories are really trashes.

I've read that maybe a bios customization can fix this problem, but i haven't tried this yet cuz i didn't want to take the risk.

65% TDP/-200/+335 @ ~19Mh/s each = ~114Mh/s
