### ISSUE TITLE
The drop in speed in the new version (0.12.0rc3)

### ISSUE THREAD

**Issue by progros** [ethereum-mining/ethminer#316]
I use with the paramer -RH.

In the new version of ethminer 0.12.0rc3, the speed is 3-5% (Reported Hashrate) less than in ethminer version 0.12.0rc1.

I observe the comparison for about 4 hours in a row.
What caused such a sharp drawdown on the Reported Hashrate.

p.s. I apologize for the bad translation - I communicate through an interpreter.

**Comment by mnik247** [comment]
I used 0.12.0rc3, and -RH
My comment about new patch here:
https://github.com/ethereum-mining/ethminer/pull/303#issuecomment-329101648
With latest version I have reported hashrate less about 0.5%, but it more accurate - see my screenshot.
What 'farm-check' you use?

**Comment by progros** [comment]
--farm-recheck 2000 --cuda-parallel-hash 4 --cuda-block-size 128

**Comment by SkylionSK** [comment]
I have the same problem, I see the hashrate lower than on previously builds for some time after new job receiving.

**Comment by smurfy** [comment]
Is only the shown hashrate lower or the effective hashrate on the pool too?.

My guess is it's just the displayed hashrate.

Currently smoothing works by collection x amount of datapoints of the hashrates, then adding everything together and calculating the mh/s from it.

As far as i understand it, this is called average.  I could also do the median instead, maybe this is better.

**Comment by SkylionSK** [comment]
I'm not sure about the pool - I should test it.

**Comment by Blacksuu** [comment]
- ethminer was **_not lost_** any hrate it just become **more accurate** & show **correct** value for example with out fix #303 my 1060 was hit a imposible speed 26.3 Mh/s & if i try to use api code for remote i recive 30 Mh/s what was completly wrong noo mater how much i was wish that to be true :)
- before RC3 ethminer it was incorrect & farm-recheck was bring diferite value function by what timing was used, with was completly wrong & inaccurate aka on 200 it was show in my case 25.8-26 Mh/s what was wrong, 500 it was bring 23.5-24.8 then> on 2000 it was bring a strange variation 20-24.5
- with rc3. aka #303 fix implement hrate display & report is how i say on begining more accurate & correct, in all test what i done now display hrate & reported hrate on pool it same noo mater what value i use on farm-recheck what is normal & how it was suppose to be
what probabil it will need now after this fix is a better optimization / tuning on code to be same like other other miner, but for sure it will take some time & patience 
- what all can watch now special if it use --farm-recheck 5000 / 10000 is min > max variance special after a new job is recive & report
something like:
GPU 1060 > --farm-recheck 10000 = min hrate value is 24.3 & max hrate value is 24.9
Claymore = min hrate value & 25.1 max hrate value 25.2
windows 7 / power limit 65 / Core clock 50 / Vram Clock +930

cheers

**Comment by SkylionSK** [comment]
HashRate is going down after new job receiving and going back after some time.
With no this patch was more stable.
FarmRecheck Default

**Comment by progros** [comment]
I tested a few days and the conclusion is this:
Average Effective Hashrate more than Reported Hashrate by about 3-5%.
You can more accurately calculate the Report Hashrate, so that it coincides with the Average Effective.

**Comment by smurfy** [comment]
what ive seen is, that hashrate on opencl is more stable than on cuda. 
Main dips are after "set work" so my guess is adapting #217 for cuda can help, for 1. more stable hashrate, 2. possible small hashrate increase

**Comment by mvnuland** [comment]
I have the same problem with my hashrate. I get back to ethminer 0.12.0rc1 for now.

**Comment by chfast** [comment]
If you want any new feature please describe it properly.
