### ISSUE TITLE
Epoch change callback

### ISSUE THREAD

**Issue by mnik247** [ethereum-mining/ethminer#317]
1) Is it possible add DAG info (DAG number) to console near 'uptime'?
2) Is it possible add support run custom script on "DAG changed"?
Why need this script? 
Because overclocked(maximum) GPU crashed with load DAG or load corrupted DAG., 
But normal worked with this setting (overclock) if I overclocked GPU after DAG loaded

**Comment by jonator** [comment]
On this topic... is it normal for a new DAG file to be generating while I'm mining?

**Comment by AndreaLanfranchi** [comment]
@jonator ... yes it is normal. New dag files are being generated every new epoch of ethereum. New epochs are set in the code of ethereum itself.

**Comment by inprosys** [comment]
I agree mnik247.  It would be very informative to know what the current DAG number is and have some record of when it changes.  I had two computer systems using ethminer V12 die last night at the same time and I suspect that it was when changing from DAG #150 to #151.

**Comment by DeadManWalkingTO** [comment]
Enhancement maybe.

**Comment by AndreaLanfranchi** [comment]
We have inserted the epoch number every time the minier initializes (on startup and on every epoch change). Nevertheless be advised that ethminer can be used with nicehash which switches ethash protocol to coins with different epochs without advice.
