### ISSUE TITLE
CUDA defaults meaning?

### ISSUE THREAD

**Issue by kkkrackpot** [ethereum-mining/ethminer#318]
Hi,

```
    --cuda-block-size Set the CUDA block work size. Default is 128
    --cuda-grid-size Set the CUDA grid size. Default is 8192
```
What exactly these defaults mean?

A block has 128 threads, and the grid has 8192 such blocks (i.e. 128*8129 threads totally)?

I'm not that good at CUDA, sorry...

Regards,
Alex

**Comment by cedricwalter** [comment]
you dont want --cuda-block-size too high, this is the number of registers available to each thread,you want it just big enough to do its work so you can put more streams in parallell

**Comment by fhlfibh** [comment]
@cedricwalter by _more streams in parallel_ you mean `--cuda-streams` option?

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
