### ISSUE TITLE
Build for compute 3.5 and CUDA 7.5

### ISSUE THREAD

**Issue by oppsig** [ethereum-mining/ethminer#32]
Have a 780 TI. Build failed.
`[  0%] Built target BuildInfo.h
[ 26%] Built target devcore
[ 43%] Built target ethash
[ 53%] Built target ethash-cl
[ 56%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_61'
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.cmake:207 (message):
  Error generating
  /home/judas/Code/ethminer/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o

libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:63: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o' failed
make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
CMakeFiles/Makefile2:320: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/all' failed
make[1]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by chfast** [comment]
Have you tried using the executable? https://github.com/ethereum-mining/ethminer/releases/tag/v0.10.0rc2

**Comment by oppsig** [comment]
Ah you can close this now, i updated to cuda 8. And built it fine. But my card was a 2gb so couldnt mine after all cause of dag file. Thanks anyway :)
