### ISSUE TITLE
reported hash with more than one card is not correct

### ISSUE THREAD

**Issue by goodman3654** [ethereum-mining/ethminer#324]
Hi

I use 0.12.0rc3 and enable report hash parameter to around 1060 x 80 with same worker name.
Value of Current Hashrate and Average Hashrate is correct.
But it seems only one card report hash to the pool. 

Is this ethminer's bug? or pool's issue?

![image 72](https://user-images.githubusercontent.com/10626700/30555198-c88dbaa4-9c5b-11e7-955f-c7d07b391fef.jpg)

**Comment by ddobreff** [comment]
you are using same worker for all your miners, its probably pool error.

**Comment by DeadManWalkingTO** [comment]
Yes. That's why you use the same worker name for all miners. @ddobreff  have right.

I think this issue can be closed.
