### ISSUE TITLE
Mining with multiple GPUs (more than 2) issue with "no GPU device" and slow type writer (text output)

### ISSUE THREAD

**Issue by pei3** [ethereum-mining/ethminer#325]
First issue I encounter is that when I had 1 GPU, my .bat file looks something like `ethminer.exe --farm-recheck 1000 -G -S ......` and when I start it, miner would work directly without any problem. Now when I've added more GPUs, when I start the same .bat file, it's saying "No GPU device with sufficient memory was found. Can't GPU mine", so I had to add `--opencl-platform 1`, this workaround somehow fixed this problem, still unsure why but okay. 

Now here comes the follow-up issue, when I start the .bat file, the type writer (text output) is extremely slow during the start up, it would take more than minutes to just finish a few new lines that I had to just close it. CPU usage is also at 100% during start up. I searched around online and found another workaround where I create multiple instances, in my case 3, where I select two devices each time with `--opencl-device 0 1` etc., so basically I need to start 3 different .bat files, start files 3 times. Is it possible to put all codes in just one file? And what is causing the slow typewriter / text output? Please fix it.

**Comment by smurfy** [comment]
What GPUs are you using? AMD, NVIDIA?, How much memory per card?

**Comment by pei3** [comment]
@smurfy Hi, I'm using RX 580 (specifically Asus RX 580 Dual OC), it's 8G. This problem appears if my system has more than 2 cards, it seems; because when I had 2 cards, I didn't need the extra commands, just `ethminer.exe --farm-recheck 1000 -G -S ......` would be sufficient.

**Comment by pei3** [comment]
The latest miner seems to have solved this issue. Closing it.
