### ISSUE TITLE
If no connection for more than 5 minutes - send graphic card(s) to idle

### ISSUE THREAD

**Issue by Simon0Harms** [ethereum-mining/ethminer#328]
Priority: low
It would be great if the miner would shut down if he has no connection for more then 5 minutes.
I am using 2 Vega56 graphic cards and i have to discónnect for several hours every working day..
In this time the load is still at 100%, but no connection...

**Comment by ykhuat** [comment]
Maybe you can have a look here.
Auto restart ethminer if no job for 5 min time.
Auto restart system if "CUDA ERROR" detected.
https://bitcointalk.org/index.php?topic=2195527.0

**Comment by Simon0Harms** [comment]
I am bin at windows for the moment because i didn't found a possibility tweaking my vega56...

**Comment by orkblutt** [comment]
https://github.com/orkblutt/MinerLamp

**Comment by Simon0Harms** [comment]
@orkblutt 
It looks like it is at the moment only working with nvidia cards
https://github.com/orkblutt/MinerLamp/issues/42

**Comment by DeadManWalkingTO** [comment]
After #757 (added --exit parameter to exit whenever an error occurred) you can use a watchdog.

Here is my [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) Windows7/8/10 [32/64] & Linux (Any Dist/Any Ver/Any Arch) (#735).

Check and feedback please.
Thank you!

**Comment by AndreaLanfranchi** [comment]
Latest releases 0.14 and 0.15 shut down miners on connection lost.
Solved
