### ISSUE TITLE
Ethminer on Jetson TX-2 won't remote connect to Geth

### ISSUE THREAD

**Issue by PeterSprague** [ethereum-mining/ethminer#330]
Attempting to get ethminer running on a NVidia Jetson TX-2 with a remote Geth instance.  Both on the same local network.

using most open parameters I can, but still can't get a remote conection between geth and ethminer
geth host: 192.168.xx.50
$ build/bin/geth --rpc --rpcaddr "0.0.0.0" --rpcport "8545" --rpccorsdomain "*" --unlock 0 console

ethminer host: 192.168.xx.60
$ethminer  -U -F "http://192.168.xx.50" --api-port "8545" -v "9" --farm "192.168.xx.50" 
[tried with & w/o farm parameter]

Gives RPC-JSON error:
 Waiting for work package...
  ✘  19:38:10|ethminer  Failed to submit hashrate.
  ✘  19:38:10|ethminer  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to 192.168.xx.50

can ping geth host
can telnet to geth url:port

from ethminer host
$ curl -X POST --data '{"jsonrpc":"2.0","method":"miner_start","params":[],"id":74}' 192.168.16.50:8545
{"jsonrpc":"2.0","id":74,"error":{"code":-32601,"message":"The method miner_start does not exist/is not available"}}

$ ethminer -U -M
hangs at 94%

ethminer built with cuda support, cuda 8.0 installed
Running on a Jetson TX-2 development board with latest kernel flashed

Any ideas or further tests I could run to get this operating correctly?

**Comment by smurfy** [comment]
Try: ``ethminer -U -F http://192.168.xx.50:8545``

``--api-port`` is for ethminers "stats" api, not for specifing the farm port

**Comment by PeterSprague** [comment]
Wish it was that simple.  That's what I had started with.

Any other ideas or tests to help figure this out?

**Comment by iplayfast** [comment]
I've been unable to compile for cuda on the Jetson TX-2, Peter if you are reading this, could you comment on what compile parameters you used? @PeterSprague
