### ISSUE TITLE
How to make release build?

### ISSUE THREAD

**Issue by fx-kirin** [ethereum-mining/ethminer#332]
I'd like to compile release build of ethminer from ubuntu 16.04 with cuda 9.0 in order to use it on ethOS.

I used clean ubuntu 16.04 ,installed cuda 9.0 by following nvidia website and compile it with `cmake` installed by `apt-get`. But ethminer binary showed following error.

    ./ethminer: relocation error: ./ethminer: symbol _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

I know it happens because the environment is not the same, but how do the dev team here provide such release version of ethminer in github?

ethOS doesn't have nvidia-cuda-toolkit so I need to make it.

Could anybody provide any hint to do so?

**Comment by fx-kirin** [comment]
The reason why I'd like to use self-patched ethminer is the command `--cuda-devices` is not as the same order as the `CUDA_DEVICE_ORDER=PCI_BUS_ID`. The device number of `--cuda-devices` changes occasionally. So there is no way to restart mining with the same GPU.

So I'd like to add a text to `--list-devices` like below.

https://github.com/ethereum-mining/ethminer/compare/master...fx-kirin:master

**Comment by amirulali** [comment]
It looks like you are missing the Glibc library. I would recommend the following

1. install build-essentials 

`sudo apt-get update
sudo apt-get install build-essential`

2. Try to compile ethminer without any modification.

**Comment by fx-kirin** [comment]
Thanks for the comment.

The compiled binary works on the Ubuntu 16.04, on which it is built. So it is not because missing some library.

**Comment by DeadManWalkingTO** [comment]
Try 
`cmake --build . --config Release`
and feedback.

**Comment by DeadManWalkingTO** [comment]
Try Update Drivers. (Download and install the latests.)
Linux Auto Download/Build Script
```
#Download ethminer
git clone https://github.com/ethereum-mining/ethminer.git
#Enter Project Directory
cd ethminer/
#Make Build Directory
mkdir build
#Enter Build Directory
cd build/
#CMAKE
echo "Build"
cmake .. -DETHASHCUDA=ON -DETHASHCL=ON -DETHSTRATUM=ON -DAPICORE=ON 
#Build
echo "Release"
cmake --build . 
echo "End Build-Release"
#Enter Home Directory
cd ~/
```
Please feedback.
Thank you!
