### ISSUE TITLE
Problem generating DAG file, writing bus problem, ethminer -g -m

### ISSUE THREAD

**Issue by markusEth** [ethereum-mining/ethminer#334]
Hello, 
after installing drivers, ethminer software etc. i had a problem to run the benchmark ethminer -g -m:

would be very glad if someone may give me an advice..

regards 
Markus

![grafik](https://user-images.githubusercontent.com/32281120/30834200-581096aa-a252-11e7-984d-0240f1d46a9e.png)

**Comment by ddobreff** [comment]
try -U instead of -G

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
