### ISSUE TITLE
Windows Message that rum is full and i need to close Ethminer, happens only with new Version 

### ISSUE THREAD

**Issue by darkkilltec** [ethereum-mining/ethminer#336]
Hey everybody.

I had Version 0.11 and was using it with 4gb ram no problems at all.
Now i am using 0.12.0rc3.
It works like a charm, but after sometime i log into my worker per remote connection and see a System warning fro mWindows that there is not enough ram.
When i check the task manager it says that only 1.9gb is used from 4gb.
So i don´t know if i am the only one getting this. Will get the new release on my computer and run that for a while :)

**Comment by ZiDanRO** [comment]
You need more virtual memory, not RAM.
If you have 6-8 GPU with 8GB memory, then you will need 32GB virtual memory.
I use also 4GB on my rigs and 32GB virtual memory, and no problems.

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
