### ISSUE TITLE
RX470 4G

### ISSUE THREAD

**Issue by 418451** [ethereum-mining/ethminer#337]
![30893668-0fca4528-a372-11e7-98ca-8b676ef1e5cc](https://user-images.githubusercontent.com/30517580/30943191-f4939330-a421-11e7-90d0-119e9d11c6e7.jpg)
RX470 4G, use 0.12.0 to get about 24.6, the use of Claymore is about 27.3. Can you solve the A card problem? Thanks for providing such good miner software.

**Comment by ddobreff** [comment]
not finished yet but you can build latest git source and try --cl-parallel-hash 2 --cl-local-work 256 --cl-global-work 18432

**Comment by 418451** [comment]
Thank you. I try it.

**Comment by voidd** [comment]
These options gave me around 5%. Not much
