### ISSUE TITLE
Mac Pro AMD FirePro D300 DAG Buffer error

### ISSUE THREAD

**Issue by jimhadd** [ethereum-mining/ethminer#341]
any ideas?

 cl  17:03:38|cl-0      Creating light cache buffer, size 35650624
 cl  17:03:38|cl-0      Creating DAG buffer, size 2281701248
  ✘  17:03:38|cl-0      Creating DAG buffer failed: clCreateBuffer -61
  ✘  17:03:38|cl-0      OpenCL Error: clEnqueueWriteBuffer -38
 cl  17:03:38|cl-1      Build info: <program source>:329:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~
<program source>:364:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~

 cl  17:03:38|cl-1      Creating light cache buffer, size 35650624
 cl  17:03:38|cl-1      Creating DAG buffer, size 2281701248
  ✘  17:03:38|cl-1      Creating DAG buffer failed: clCreateBuffer -61
  ✘  17:03:38|cl-1      OpenCL Error: clEnqueueWriteBuffer -38

**Comment by quixoticblink** [comment]
I am having the same issue - if any one can advice will be very helpful

**Comment by axelguilmin** [comment]
Same error on Macbook Pro 2016
```
 cl  20:28:14|cl-1      Platform: Apple
 cl  20:28:14|cl-0      Device:   Intel(R) HD Graphics 630  / OpenCL 1.2 
 cl  20:28:14|cl-1      Device:   AMD Radeon Pro 555 Compute Engine  / OpenCL 1.2 
 cl  20:28:14|cl-1      Build info: <program source>:329:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~
<program source>:364:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~

 cl  20:28:14|cl-1      Creating light cache buffer, size 35650624
 cl  20:28:14|cl-1      Creating DAG buffer, size 2281701248
  ✘  20:28:14|cl-1      Creating DAG buffer failed: clCreateBuffer -61
  ✘  20:28:14|cl-1      OpenCL Error: clEnqueueWriteBuffer -38
```

**Comment by quixoticblink** [comment]
what i understood is that you need the more than 2gb vram for AMD card .. below that will not work

**Comment by axelguilmin** [comment]
Yes, the DAG file is about 2.12GB now, so we need at least a 3GB card to mine. 
https://investoon.com/tools/dag_size

**Comment by DeadManWalkingTO** [comment]
2 GB GPU can't mine ETH anymore.

I think this issue can be closed.
