### ISSUE TITLE
i'm a bit confuse and lost about how to run ethminer

### ISSUE THREAD

**Issue by galios974** [ethereum-mining/ethminer#343]
Hello everyone. 
i want to make my 4 gtx 1070 work and still can't T.T .
i am trying since yesterday to launch ethminer on ethermine.org. I may be a total noob not to be able to do it until now. 
I have the last version  1.2.9 
i read forum to find a solution but nothin until now. 
here the command i tried : 
./ethminer -G -F http://eu1.ethermine.org:14444/@address@ --farm-recheck 200 
whatever i try i still get this error : 
Exception -32603 : INTERNAL_ERROR: : {"id":999,"jsonrpc": "2.0","result": false,"error": "Invalid JSON request"}
if someone can just help me or give me a workign example so i can make this work. 
thx a lot

**Comment by smurfy** [comment]
``ethminer -RH -U -S eu1.ethermine.org:4444 -O 0xXXXXXX.rig``

1.2.9 is a strange version latest is 0.12

https://github.com/ethereum-mining/ethminer/releases

**Comment by AndreaLanfranchi** [comment]
`./ethminer -U -S "eu1.ethermine.org:4444" -O "@youretheraddress@" --farm-recheck 2000 --stratum-protocol 0`

**Comment by galios974** [comment]
just discovered the chat :) you was faster Smurfy :P 
i have download the 0.12 for ubuntu (linux) from the release but when i start ethminer -V it is written : 1.2.9 ...
and i get 
Invalid argument: -RH
when trying this. 
:(

**Comment by AndreaLanfranchi** [comment]
-RH switch works only coupled with switch  --stratum-protocol 1 (which I do not know if supported by ethermine)

**Comment by galios974** [comment]
Thx a lot Andrea.
this works fine with this command. 
i really don't understand why my version is so strange and why i don't get all the argument you all taking about . 
but now it is good . 
thx a lot
Blessings on you all

**Comment by smurfy** [comment]
@AndreaLanfranchi ``-RH`` works with ethermine without or without protocol 1. It works with 0 (default) too.  ``-SP 1`` is only required for nanopool.

@galios974 Strange regarding version. It reports correctly for me. But i'm happy everything works now for you.

**Comment by AndreaLanfranchi** [comment]
Sorry to disagree but if you launch ./ethminer with -RH and without --stratum-protocol 1 you get an error of unknown parameter.
Maybe it's a problem in command line argument parser.

**Comment by smurfy** [comment]
@AndreaLanfranchi i implemented, ``-RH`` :)  But yes there is a problem with the argument parser.
The parameter needs to be one of the first ones to work.
