### ISSUE TITLE
1*GTX1060-6Gb  hashrate=0 and Exception thrown "apparent block number for " XX is too high; max is 61440000

### ISSUE THREAD

**Issue by emanent** [ethereum-mining/ethminer#344]
Hi all

when using ethminer 0.12 with following command 

ethminer --cuda-devices 1 -U -S eth-eu1.nanopool.org:9999 -O MY_WALLET -SP 2 --cuda-parallel-hash 6

my card is GTX 1060 6Gb working fine with EthDcrMiner64.exe getting an average of 21.5Mh/sec

i hoped to get some extra Mh/sec with ethminer

may be there is something wrong with my command ? i've read about the DACH Ram limit but it should be OK with 6Gb ram...

i get the followning results 

cu  07:23:11|main      Using grid size 8192 , block size 128
 cu  07:23:11|main      Found suitable CUDA device [ GeForce GTX 1060 6GB ] with 6442450944  bytes of GPU memory
  i  07:23:11|main      Connecting to stratum server eth-eu1.nanopool.org:9999
  i  07:23:11|stratum   Connected to stratum server eth-eu1.nanopool.org : 9999
  i  07:23:11|stratum   Starting farm
  i  07:23:11|stratum   Subscribed to stratum server
  i  07:23:11|stratum   Authorized worker MY_WALLET
  i  07:23:11|stratum   Received new job #f917bfd6d78e6eb9072a5b318628d6866184ae0235ab8486e43254c301f73df5
  i  07:23:11|CUDA0     set work; seed: #f917bfd6, target: #00000000ffff
  i  07:23:11|CUDA0     Initialising miner...
  X  07:23:11|CUDA0     Exception thrown in Worker thread: apparent block number for f917bfd6d78e6eb9072a5b318628d6866184ae0235ab8486e43254c301f73df5 is too high; max is 61440000
  m  07:23:13|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  07:23:15|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00

**Comment by emanent** [comment]
Hello 

i found out ! 
ethminer -U -S eth-eu1.nanopool.org:9999 -O MY_WALLET --cuda-parallel-hash 2

is working fine !

i tried several hash parameters and get the following hashrate 
2->21Mh/sec.
4->21Mh/sec.
6->14Mh/sec.
8->21Mh/sec.
don't know if it is accurate but it is a bit less than claymore -21.7 Mh/sec)

**Comment by ddobreff** [comment]
Try --cuda-grid-size 4096

**Comment by DeadManWalkingTO** [comment]
For GTX 1060/1070 i believe that the default settings are the better choice.

Test launch command:

`ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

Try with latest Ethminer version and feedback please.
Thank you!
