### ISSUE TITLE
FS + SP

### ISSUE THREAD

**Issue by Tihano** [ethereum-mining/ethminer#345]
mainpool uses SP 1
failoverpool - SP 0

ethminer.exe -U -SP 1 -S ru1.etherchain.ru:8008 -FS eu1.ethermine.org:4444 -O wallet.rig
will it work correct?

**Comment by smurfy** [comment]
``-SP`` aka setting the stratum protocol to use will be used for all stratum connections (main + failover).

So it would use ``-SP 1`` on ethermine too. Which is no problem, as ethermine supports that too.

**Comment by Tihano** [comment]
No way automatic return to mainpool after 30 min ?

**Comment by smurfy** [comment]
not at this point no. happy to see a PR for it :)

**Comment by DeadManWalkingTO** [comment]
Very useful.
Any news here?

**Comment by AndreaLanfranchi** [comment]
-P switch allows setting of protocol on a per connection basis.
