### ISSUE TITLE
Benchmarking RX 570 produces OpenCL Error: clSetKernelArg -49

### ISSUE THREAD

**Issue by AntoniosHadji** [ethereum-mining/ethminer#346]
My machine:  
Ubuntu 16.04.3 LTS 4.10.0-35-generic #39~16.04.1-Ubuntu SMP x86_64
AMDAPPSDK version 3.0 installed
Same results with amdgpu-pro drivers 17.30.465504 installed or not installed.

I have ethminer version 0.12.0rc3 running successfully with command line:
```
ExecStart=/usr/local/bin/ethminer --farm-recheck 200 -G -RH -SP 1 -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -O <ether_address>.<rig_name>:x --cl-local-work 256 --cl-global-work 16384 --api-port 3344 --work-timeout 40 --verbosity 9
```
The `-SP 1` was unexpected since it is not recommended for ethermine.

Output of benchmark test:
```
$ ethminer -G -M -v 9
  ℹ  09:53:29|ethminer  Found suitable OpenCL device [ Ellesmere ] with 6205165568  bytes of GPU memory
Benchmarking on platform: CL
Preparing DAG for block #0
 cl  09:53:29|cl-0      No work. Pause for 3 s.
Warming up...
 cl  09:53:32|cl-0      New work: header #50c856ae… target 0000000000000002000000000000000000000000000000000000000000000000
 cl  09:53:32|cl-0      New seed #00000000…
 cl  09:53:32|cl-0      Platform: AMD Accelerated Parallel Processing
 cl  09:53:32|cl-0      Device:   Ellesmere  / OpenCL 1.2 AMD-APP (2442.7)
 cl  09:53:33|cl-0      Build info: 
 cl  09:53:33|cl-0      Creating light cache buffer, size 16776896
 cl  09:53:33|cl-0      Creating DAG buffer, size 1073739904
 cl  09:53:33|cl-0      Loading kernels
 cl  09:53:33|cl-0      Writing light cache buffer
 cl  09:53:33|cl-0      Creating buffer for header.
 cl  09:53:33|cl-0      Creating mining buffer
 cl  09:53:33|cl-0      Generating DAG
 cl  09:53:34|cl-0      DAG 0 %
...
 cl  09:53:42|cl-0      DAG 93 %
 cl  09:53:42|cl-0      Switch time 13610 ms / 10611438 us
Trial 1... 3987779
Trial 2... 4197452
Trial 3... 4406663
Trial 4... 4407104
Trial 5... 4511583
  ✘  09:53:59|cl-0      OpenCL Error: clSetKernelArg -49
```

**Comment by jenstandstad** [comment]
I have exactly the same issue, running Ubuntu 16.04 LTS and Radeon RX 560.




-

**Comment by ptrk64** [comment]
Same here 2 Win10 systems. One with 2xRx560 and one with 2xRx570. It's happens sporadically, sometimes at startup and sometimes after running for a few hours.

**Comment by worohregger** [comment]
I'm getting the same error in Windows 10 with the stable Crimson driver as well.

**Comment by worohregger** [comment]
Checked again, getting the error "OpenCL Error: clSetKernelArg -49" for "ethminer -M -G" in Windows 10 / driver 17.12.2 (OpenCL 2.0 AMD-APP) for versions 0.12 and various 0.13 release candidates.

**Comment by MariusVanDerWijden** [comment]
fixed in https://github.com/ethereum-mining/ethminer/pull/694

**Comment by RyanF109** [comment]
I am receiving this error with the latest version.

  ✘  02:41:53|getwork   Failed getting work!
  ℹ  02:41:53|getwork   Disconnected from http://127.0.0.1:8545
  ℹ  02:41:53|getwork   Shutting down miners...
  ✘  02:41:53|cl-0      OpenCL Error: clSetKernelArg: CL_INVALID_ARG_INDEX (-49)
  m  02:41:58|ethminer  not-connected
 cl  02:42:00|cl-1      Build info: 
 cl  02:42:00|cl-1      Creating light cache buffer, size 25165376
 cl  02:42:00|cl-1      Creating DAG buffer, size 1610610304
 cl  02:42:00|cl-1      Loading kernels
 cl  02:42:00|cl-1      Writing light cache buffer

**Comment by coinbala** [comment]
so how do i fix>?

**Comment by smurfy** [comment]
Well this is a problem which can occur sporadically. There was a problem in benchmark mode which caused it almost 100% of the time.

For the same error, but in normal operation, there is no fix yet. A workaround could be using the new ``--exit`` param to let ethminer terminate on errors. In conjunction with a loop/monitoring script which restarts ethminer.

**Comment by RyanF109** [comment]
I fixed this by reinstalling AMD pro drivers with --opencl=legacy flag.
