### ISSUE TITLE
Ethminer and hardfork?

### ISSUE THREAD

**Issue by fhlfibh** [ethereum-mining/ethminer#347]
Hi,

Will it be possible to use ethminer after the upcoming ethereum hardfork?

(it may be a stupid question, but I really don't understand much about this fork stuff, sorry)

Regards,
Alex

**Comment by smurfy** [comment]
yes, it does not matter. Only thing you need to do is decide which of the two currencies you want to mine and point to the right pool.

**Comment by chfast** [comment]
Just make sure your mining pool has upgraded the Ethereum node software. In this case "hardfork" means network protocol upgrade, but nobody is going to keep the old software (old fork) running.

**Comment by fhlfibh** [comment]
Thanks!
