### ISSUE TITLE
compilation fails

### ISSUE THREAD

**Issue by SadSock** [ethereum-mining/ethminer#350]
I have a mistake when run
` cmake ..
`

> Building Boost.Build engine with toolset ... tools/build/src/engine/###
> ###No toolset specified. Please use --toolset option.
> ###
> 

Red Hat Enterprise Linux Server release 7.2 (Maipo)

**Comment by DeadManWalkingTO** [comment]
Try Update Drivers. (Download and install the latests.)
Linux Auto Download/Build Script
```
#Download ethminer
git clone https://github.com/ethereum-mining/ethminer.git
#Enter Project Directory
cd ethminer/
#Make Build Directory
mkdir build
#Enter Build Directory
cd build/
#CMAKE
echo "Build"
cmake .. -DETHASHCUDA=ON -DETHASHCL=ON -DETHSTRATUM=ON -DAPICORE=ON 
#Build
echo "Release"
cmake --build . 
echo "End Build-Release"
#Enter Home Directory
cd ~/
```
Please feedback.
Thank you!
