### ISSUE TITLE
my complied cuda code does not work

### ISSUE THREAD

**Issue by TheLegendAli** [ethereum-mining/ethminer#351]
I build ethminer using coda with the following command:

`sudo cmake ..  -DETHASHCL=OFF -DETHASHCUDA=ON`

It builds successfully. However when I run:

`ethminer -U`

I get the following error:

`terminate called after throwing an instance of 'std::runtime_error'
  what():  unknown error
Aborted (core dumped)`

My system:
Ubuntu: 16.04
Nvidia: 375
cuda: 9.0
GPU: Nvidia-980

**Comment by Shaana** [comment]
Same issue with Ubuntu: 16.04.3, GTX 970, Cuda 8.0.61.2 and Nvidia drivers 384.90, 387.12

**Comment by lrehmann** [comment]
7.56 Mh/s on my Google Cloud Tesla K80 with this setup. 

Thanks for the tips @Shaana

**Comment by jasonwee** [comment]
7.56Mh/s is very low man...

**Comment by danyaljj** [comment]
@jasonwee what is a good speed?

**Comment by jasonwee** [comment]
ideally as high as possible. normally a pool will reveal like top 10/20miner with its speed

**Comment by DeadManWalkingTO** [comment]
Try Update Drivers. (Download and install the latests.)
Linux Auto Download/Build Script
```
#Download ethminer
git clone https://github.com/ethereum-mining/ethminer.git
#Enter Project Directory
cd ethminer/
#Make Build Directory
mkdir build
#Enter Build Directory
cd build/
#CMAKE
echo "Build"
cmake .. -DETHASHCUDA=ON -DETHASHCL=ON -DETHSTRATUM=ON -DAPICORE=ON 
#Build
echo "Release"
cmake --build . 
echo "End Build-Release"
#Enter Home Directory
cd ~/
```
Please feedback.
Thank you!

**Comment by AndreaLanfranchi** [comment]
No feed back.
