### ISSUE TITLE
JsonRpcException - Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8545

### ISSUE THREAD

**Issue by Nycticebus** [ethereum-mining/ethminer#352]
PS F:\Ethereum\ethminer\bin> ./ethminer.exe
  i  09:00:23|main      Found suitable OpenCL device [ GeForce GTX 970 ] with 4294967296  bytes of GPU memory
 cl  09:00:23|cl-1      No work. Pause for 3 s.
  m  09:00:23|main      Waiting for work package...
  X  09:00:24|main      Failed to submit hashrate.
  X  09:00:24|main      Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8545

 cl  09:00:26|cl-1      No work. Pause for 3 s.trying in 2...
JSON-RPC problem. Probably couldn't connect. Retrying in 1...
  m  09:00:27|main      Waiting for work package...
PS F:\Ethereum\ethminer\bin> ./ethminer.exe
  i  09:24:14|main      Found suitable OpenCL device [ GeForce GTX 970 ] with 4294967296  bytes of GPU memory
 cl  09:24:14|cl-1      No work. Pause for 3 s.
  m  09:24:14|main      Waiting for work package...
  X  09:24:15|main      Failed to submit hashrate.
  X  09:24:15|main      Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8545

 cl  09:24:17|cl-1      No work. Pause for 3 s.trying in 2...
PS F:\Ethereum\ethminer\bin> ./ethminer.exe
  i  09:26:16|main      Found suitable OpenCL device [ GeForce GTX 970 ] with 4294967296  bytes of GPU memory
 cl  09:26:16|cl-1      No work. Pause for 3 s.
  m  09:26:16|main      Waiting for work package...
  X  09:26:17|main      Failed to submit hashrate.
  X  09:26:17|main      Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8545

 cl  09:26:19|cl-1      No work. Pause for 3 s.trying in 2...
JSON-RPC problem. Probably couldn't connect. Retrying in 1...
  m  09:26:21|main      Waiting for work package...
PS F:\Ethereum\ethminer\bin>

**Comment by smurfy** [comment]
well, what are you trying to do?

**Comment by fenderrex** [comment]
the readme needs some info the --help is junk
