### ISSUE TITLE
Testing: CUDA 9.0 

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ethereum-mining/ethminer#354]
All Tests are currently written with CUDA 8.0, 
to test new features, there should be a test-suite to run all tests with CUDA 9.0

**Comment by gratiot** [comment]
Just put together my first miner a few days ago using ubuntu 17.10 and cuda 9.0 not sure what I have but it is running connected to suprnova on a single miner. Have 2 GTX1060 and 1 RX460 all stock no firmware mods running all defaults. etherminer is showing hash rates between 26 and 36HM/s very consistently. Had to remove the reference to "compute_20" to get it to build, but otherwise no issues.

I'm a bit confused on one thing when ethminer references my AMD rx480 it call it "cudaminer0" and when it references the GTX1060's it calls them "openCLminer1" or "2". I figured it would be the other way around. Am I missing something?

**Comment by MariusVanDerWijden** [comment]
Can you paste the output where it references these cards? (and maybe a bit surrounding output so that i can locate it in the source code)

**Comment by gratiot** [comment]
This is the command being executed in the miner.sh script:

./ethminer --farm-recheck 200 -G -S eth.suprnova.cc:5000 -O maxsilver.genoil:x  -SP 2 -X --opencl-platform 1 --cuda-devices 2

pmorris@miner:~/genoil/nvidia2/cpp-ethereum/build/ethminer$ ./miner.sh
[OPENCL]:Found suitable OpenCL device [GeForce GTX 1060 6GB] with 6366363648 bytes of GPU memory
  ℹ  16:21:44|ethminer  Connecting to stratum server eth.suprnova.cc:5000
  ℹ  16:21:44|stratum  Connected to stratum server eth.suprnova.cc : 5000
  ℹ  16:21:44|stratum  Starting farm
  ℹ  16:21:44|stratum  Extranonce set to 99f0
  ℹ  16:21:44|stratum  Subscribed to stratum server
  ℹ  16:21:44|stratum  Difficulty set to 1
  ℹ  16:21:44|stratum  Received new job #63d
  ℹ  16:21:44|cudaminer0  set work; seed: #d4f2e152, target:  #00000000ffff
  ℹ  16:21:44|cudaminer0  Initialising miner...
  ℹ  16:21:44|openclminer1  set work; seed: #d4f2e152, target:  #00000000ffff
  ℹ  16:21:44|openclminer1  Initialising miner...
  ℹ  16:21:44|openclminer2  set work; seed: #d4f2e152, target:  #00000000ffff
  ℹ  16:21:44|openclminer2  Initialising miner...
  ℹ  16:21:45|stratum  Authorized worker maxsilver.genoil
  m  16:21:45|ethminer  Mining on PoWhash #ae95ec67 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:21:45|ethminer  Mining on PoWhash #ae95ec67 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:21:45|ethminer  Mining on PoWhash #ae95ec67 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:21:45|ethminer  Mining on PoWhash #ae95ec67 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:21:45|ethminer  Mining on PoWhash #ae95ec67 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:21:46|ethminer  Mining on PoWhash #ae95ec67 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:21:46|ethminer  Mining on PoWhash #ae95ec67 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:21:46|ethminer  Mining on PoWhash #ae95ec67 : 0.00MH/s [A0+0:R0+0:F0]
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 1060 6GB(OpenCL 1.2 CUDA)
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 1060 6GB(OpenCL 1.2 CUDA)
Using device: GeForce GTX 1060 6GB (Compute 6.1)
  m  16:21:46|ethminer  Mining on PoWhash #ae95ec67 : 0.00MH/s [A0+0:R0+0:F0]
[OPENCL]:Printing program log
[OPENCL]:

[OPENCL]:Creating cache buffer
[OPENCL]:Creating DAG buffer
[OPENCL]:Loading kernels
[OPENCL]:Writing cache buffer
Generating DAG for GPU #0
  m  16:21:46|ethminer  Mining on PoWhash #ae95ec67 : 0.00MH/s [A0+0:R0+0:F0]
[OPENCL]:Creating buffer for header.
[OPENCL]:Creating mining buffer 0
[OPENCL]:Creating mining buffer 1
[OPENCL]:Generating DAG data
[OPENCL]:Printing program log
[OPENCL]:

[OPENCL]:Creating cache buffer
[OPENCL]:Creating DAG buffer
[OPENCL]:Loading kernels
[OPENCL]:Writing cache buffer
  m  16:21:47|ethminer  Mining on PoWhash #ae95ec67 : 0.00MH/s [A0+0:R0+0:F0]
[OPENCL]:Creating buffer for header.
[OPENCL]:Creating mining buffer 0
[OPENCL]:Creating mining buffer 1
[OPENCL]:Generating DAG data
CUDA#0: 0%

**Comment by gratiot** [comment]
Thought I would add this as well
pmorris@miner:~/genoil/nvidia2/cpp-ethereum/build/ethminer$ ./ethminer -U --list-devices
[CUDA]:
Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1060 6GB
	Compute version: 6.1
	cudaDeviceProp::totalGlobalMem: 6366363648
[1] GeForce GTX 1060 6GB
	Compute version: 6.1
	cudaDeviceProp::totalGlobalMem: 6367739904

pmorris@miner:~/genoil/nvidia2/cpp-ethereum/build/ethminer$ ./ethminer -G --list-devices
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Baffin
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 4270821376
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 3013607424
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] GeForce GTX 1060 6GB
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 6366363648
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1591590912
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
[2] GeForce GTX 1060 6GB
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 6367739904
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1591934976
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

pmorris@miner:~/genoil/nvidia2/cpp-ethereum/build/ethminer$ ./ethminer -X --list-devices
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Baffin
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 4270821376
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 3013607424
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] GeForce GTX 1060 6GB
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 6366363648
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1591590912
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
[2] GeForce GTX 1060 6GB
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 6367739904
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1591934976
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

[CUDA]:
Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1060 6GB
	Compute version: 6.1
	cudaDeviceProp::totalGlobalMem: 6366363648
[1] GeForce GTX 1060 6GB
	Compute version: 6.1
	cudaDeviceProp::totalGlobalMem: 6367739904

**Comment by gratiot** [comment]
Just split up the devices in separate instances of ethminer. Each one picks up the correct card and names them appropriately. Looks like somewhere in the code some one is getting the naming conventions swapped. Plus the hash rate has stabilized quite a bit. I'm getting a solid 10.49MH/s on the single AMD. Every 5 or 6 iterations it drops by half for 1 iteration. On Cuda cards I'm getting a solid 31.46 MH/s with occasional forays up to 36.7MH/s. Each time a new job is received the hash rate drops to 0 or by half which I suspect is normal when switching to a new job.

**Comment by gratiot** [comment]
Was running along quite well for about 10 min when this happened. I've seen others commenting on this but finding no resolutions:
  
 m  15:32:31|ethminer  Mining on PoWhash #7e9c1039 : 10.49MH/s [A0+0:R0+0:F0]
  ✘  15:32:31|stratum  Read response failed: End of file
  ℹ  15:32:31|stratum  Reconnecting in 3 seconds...
  ℹ  15:32:34|stratum  Connecting to stratum server eth.suprnova.cc:5000
Could not resolve hosteth.suprnova.cc:5000, Operation canceled  ℹ  15:32:34|stratum  Reconnecting in 3 seconds...
  ℹ  15:32:37|stratum  Connecting to stratum server eth.suprnova.cc:5000
Could not resolve hosteth.suprnova.cc:5000, Operation canceled  ℹ  15:32:37|stratum  Reconnecting in 3 seconds...
  ℹ  15:32:40|stratum  Connecting to stratum server eth.suprnova.cc:5000
Could not resolve hosteth.suprnova.cc:5000, Operation canceled  ℹ  15:32:40|stratum  Reconnecting in 3 seconds...

**Comment by sfornengo** [comment]
Is there some improvements with cuda 9.0 vs cuda 8.0 ?

**Comment by gratiot** [comment]
Can't really tell you. However, it supports the Nvidia Tesla V100
Accelerator coupled with the Volta GV100 GPU. This configuration is used
in Data Center scale GPU installations. Oracle has teamed up with NVIDIA
and is offering a Bare Metal cloud service which is coupled with this
nvidia configuration. I'm currently trying to get a test cloud platform
stood up to test out the service and see if mining is profitable at that
scale...  

On 2017-11-17 02:51, sfornengo wrote:

> Is there some improvements with cuda 9.0 vs cuda 8.0 ? 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/ethereum-mining/ethminer/issues/354#issuecomment-345182353
[2]

**Comment by MariusVanDerWijden** [comment]
https://developer.nvidia.com/cuda-toolkit/whatsnew

Yes using 9.0 can be faster,
mostly because of changes in supporting libraries
and internal changes to the thread management

**Comment by sfornengo** [comment]
It is safe to use the last cuda 9.1 ?

**Comment by virantha** [comment]
I got an unsupported CUDA version error running ethminer off main with 9.1.  Had to downgrade to 9.0 to get it to work again (was previously on an older commit of ethminer that still supported cuda 8.0)

**Comment by jean-m-cyr** [comment]
You can build with 9.1, by updating you path in /etc/environment:

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/cuda-9.1/bin"

**Comment by sfornengo** [comment]
@jean-m-cyr thanks for this information. Can we expect some improvements with cuda 9.1 ?

**Comment by jean-m-cyr** [comment]
I think it has more to do with supporting the latest Pascal architecture.
