### ISSUE TITLE
Miner couldn't connect

### ISSUE THREAD

**Issue by kuzmich86** [ethereum-mining/ethminer#355]
Dear all, I'm a newbie in mining. Please help me out 'cause I've tried everything I'd found on the Web but still I get the same error:

JSON-RPC problem. Probably couldn't connect. Retrying in 1...
cl miner  04:52:33.939|main  No work
  X  04:52:35.144|main  Failed to submit hashrate.
  X  04:52:35.145|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8545

Here is my bat file:
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

timeout /T 3

ethminer.exe --farm-recheck 400 -U -F http://eth-ru.dwarfpool.com:80/0xf74ebf2ca8daf54bbd21f26faaa195ac7e240422/rig1 --cuda-parallel-hash  --cl-local-work 256 --cl-global-work 16384 
pause
I have Windows 7 64 Professional.

**Comment by bmatthewshea** [comment]
Try:
ethminer.exe --farm-recheck 400 -U **-SP 1** -F http://eth-ru.dwarfpool.com:80/0xf74ebf2ca8daf54bbd21f26faaa195ac7e240422/rig1


> -SP, --stratum-protocol <n> Choose which stratum protocol to use:
>         0: official stratum spec: ethpool, ethermine, coinotron, mph, nanopool (default)
>         **1** eth-proxy compatible: **dwarfpool**, f2pool, nanopool (required for hashrate reporting to work with nanopool)
>         2: EthereumStratum/1.0.0: nicehash

**Comment by smurfy** [comment]
@bmatthewshea  ``-SP 1``  does not really affects ``-F`` at all , since its a stratum, not a getwork option.

**Comment by bmatthewshea** [comment]
Dwarf settings - port 80 does not seem to be stratum per dwarfpool page.
https://dwarfpool.com/eth

> Port: 80 and Stratum-Port (proxy+claymore): 8008

> URL: /your_wallet
> URL: /your_wallet/worker
> URL: /your_wallet/worker/email
> URL: /your_wallet/email
> Stratum-URL(with proxy): /
> Stratum-URL(with proxy): /worker

**Comment by smurfy** [comment]
Well farm/getwork mode works
``ethminer.exe --farm-recheck 400 -U -F http://eth-ru.dwarfpool.com:80/0xf74ebf2ca8daf54bbd21f26faaa195ac7e240422/rig1``  
or stratum mode too:
``ethminer.exe -U -S eth-ru.dwarfpool.com:8008 -O 0xf74ebf2ca8daf54bbd21f26faaa195ac7e240422/rig1 -SP 1``

**Comment by bmatthewshea** [comment]
Yeah, verified dwarfpool working here, too, earlier. Wondering about that geth? port on localhost.
`Could not connect to http://127.0.0.1:8545`

**Comment by cvhong** [comment]
Do anyone trying to run this on macOS? what cmd on macOS ?
it seems setx is not a command in macOS.
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

**Comment by amirulali** [comment]
setx is for windows, for MacOS its export.

`export GPU_FORCE_64BIT_PTR=0`

**Comment by cvhong** [comment]
Thank you. My GPU only have 2GB memory. I supposed it cannot mine Ether any more right ?

**Comment by xushijie** [comment]
For the command:  ethminer.exe -U -S eth-ru.dwarfpool.com:8008 -O 0xf74ebf2ca8daf54bbd21f26faaa195ac7e240422/rig1 -SP 1

Should I also run some proxy server somewhere, because "-Sp 1" means eth-proxy ?
