### ISSUE TITLE
OpenCL mem allocation limits

### ISSUE THREAD

**Issue by elodg** [ethereum-mining/ethminer#356]
Is there a solution for OpenCL platforms that have a CL_DEVICE_MAX_MEM_ALLOC_SIZE < DAG, but CL_DEVICE_GLOBAL_MEM_SIZE enough to fit three?

[0] [0] Intel(R) HD Graphics 520
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 6814448026
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2147483647
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

**Comment by smurfy** [comment]
You could test: #311  i think it tries to solve this

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!

**Comment by AndreaLanfranchi** [comment]
No feed back.
Closing.
