### ISSUE TITLE
JSON RPC API usage

### ISSUE THREAD

**Issue by benpayne** [ethereum-mining/ethminer#357]
Trying to get my python code to access the new API server that was integrated into v12.  I am having a problem getting the request into ethminer.  I'm sending it over tcp and have sent the following:

request = '{"method": "miner_getstat1", "jsonrpc": "2.0", "id": 5}'

Though maybe I was formatting it wrong to tried a library from here:
https://github.com/joshmarshall/jsonrpctcp

Same results.  I've added some printing to ethminer, so I know that the API server is being started and the APIs are binding.  I've added a print to the getstat API and it's not getting called.  Also ran TCP dump to ensure that the packet is being sent and it is.  So not sure what else to try...

Does anyone have working client code that I could try?

**Comment by benpayne** [comment]
Found this issues...  need a '\n' at the end of the line...

**Comment by yannmasoch** [comment]
@benpayne thanks for sharing the '\n' solution!

_I spent a full long day trying different libraries and ways (sockets, requests, telnet, etc.) to connect properly to the API._
