### ISSUE TITLE
New jobs coming too fast

### ISSUE THREAD

**Issue by fhlfibh** [ethereum-mining/ethminer#363]
Hi,

I have the latest git's Linux `ethminer` on GTX 1060 to ethermine.org, with `--farm-recheck=4000 --stratum-client 2`.

I noticed that now new jobs are coming so frequently, that the miner seems even not working over some of them at all:
```
 ℹ  00:11:59|stratum   Received new job #5964d173
  ℹ  00:11:59|CUDA0     set work; seed: #d4f2e152, target:  #0000000112e0
  m  00:11:59|ethminer  Speed  18.92 Mh/s    gpu/0 18.92  [A0+0:R0+0:F0]
  m  00:12:03|ethminer  Speed  18.70 Mh/s    gpu/0 18.70  [A0+0:R0+0:F0]
  m  00:12:07|ethminer  Speed  18.61 Mh/s    gpu/0 18.61  [A0+0:R0+0:F0]
  ℹ  00:12:07|stratum   Received new job #146f9ae0
  ℹ  00:12:07|CUDA0     set work; seed: #d4f2e152, target:  #0000000112e0
  ℹ  00:12:09|stratum   Received new job #5fc24b33
  ℹ  00:12:09|CUDA0     set work; seed: #d4f2e152, target:  #0000000112e0
  ℹ  00:12:11|stratum   Received new job #c5c95b3c
  ℹ  00:12:11|CUDA0     set work; seed: #d4f2e152, target:  #0000000112e0
  m  00:12:11|ethminer  Speed  18.29 Mh/s    gpu/0 18.29  [A0+0:R0+0:F0]
  m  00:12:15|ethminer  Speed  18.29 Mh/s    gpu/0 18.29  [A0+0:R0+0:F0]
  m  00:12:19|ethminer  Speed  18.28 Mh/s    gpu/0 18.28  [A0+0:R0+0:F0]
  ℹ  00:12:22|stratum   Received new job #bb451335
  ℹ  00:12:22|CUDA0     set work; seed: #d4f2e152, target:  #0000000112e0
  m  00:12:23|ethminer  Speed  18.95 Mh/s    gpu/0 18.95  [A0+0:R0+0:F0]
  ℹ  00:12:26|stratum   Received new job #d5495460
```
Is it normal or something needs fixing somehere?

Playing around `--farm-recheck` seems making no difference...

Regards,
Alex

**Comment by DDDanny** [comment]
Hi Alex,
I have seen the same behaviour with previous version 0.11 and ethermine 3 months ago. I finally switched the pool: As a large pool have a (very) fast solution rate and over a long period you get only you get only jobs and sometimes a solution - with nanopool I do not often see this beaviour - of course sometimes lots of jobs within seconds are solved faster than I find a solution...
B.R.
Danny

**Comment by fhlfibh** [comment]
@DDDanny Thanks for the suggestion!
I tried nanopool.org, but situation there is pretty much the same...
Maybe my card is simply too slow...
Yes, 18Mh/s is quite low, because this particular p.o.s. is very bad at mining (only 15Mh/s if not overclocked). I don't know why, I also have another, completely identical card that makes 23Mh/s at 70W easily.

**Comment by chfast** [comment]
1. Pool is sending jobs, so we cannot do anything about it.
2. This is actually very good thing. This means that pools includes more transaction and uncles in a block maximizing profit. In OpenCL the switch cost is < 20 us.

**Comment by fhlfibh** [comment]
@chfast that's good that it's a very good thing, then.
Unfortunately I'm on CUDA with Nvidia's GTX 1060 3Gb (AFAIK, there was already a PR or an issue about jobs switching on CUDA).

**Comment by DDDanny** [comment]
finally. 150mh/s results in ~1000 solves per 12hour period.
so 15mh/s will be 100 per 12h - therefore one solution every ~7 minutes
sure you will have a long time of only receiving work....
