### ISSUE TITLE
  Build info: stringInput.cl:107:60: error: call to 'as_ulong' is ambiguous

### ISSUE THREAD

**Issue by holmanj** [ethereum-mining/ethminer#364]
Build info: stringInput.cl:107:60: error: call to 'as_ulong' is ambiguous
/usr/lib/x86_64-linux-gnu/beignet/include/ocl_as.h:132:20: note: candidate function
...

Linux 4.8.0-1-amd64 #1 SMP Debian 4.8.7-1 (2016-11-13) x86_64 GNU/Linux

**Comment by guanqun** [comment]
I'm having the same issue, and I'm also using Beignet linux driver.

**Comment by DeadManWalkingTO** [comment]
Try Update Drivers. (Download and install the latests.)

Test launch command:

`ethminer.exe -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

Try with latest Ethminer version and feedback please.
Thank you!
