### ISSUE TITLE
ethminer  Failed to submit hashrate.

### ISSUE THREAD

**Issue by Flodu31** [ethereum-mining/ethminer#370]
Hello,
I'm trying to start ethminer but I've the following error:
`florent@Ubuntu1604:~$ ethminer --farm-recheck 200 -G -F us2.ethermine.org:4444/0xB
[OPENCL]:Found suitable OpenCL device [Tesla M60] with 8518238208 bytes of GPU memory
miner  15:05:21.914|ethminer  Getting work package...
  ✘  15:05:21.971|ethminer  Failed to submit hashrate.
  ✘  15:05:21.971|ethminer  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32603 : INTERNAL_ERROR: : {"id":999,"jsonrpc": "2.0","result": false,"error": "Invalid JSON request"}`
Anyone has the same issue on Ubuntu 16.04?
Thanks.
Florent

**Comment by anthonyguertin** [comment]
In another terminal run geth —rpc prior to starting the ethminer

**Comment by AndreaLanfranchi** [comment]
@Flodu31 you have implemented a syntax which allows SOLO mining.
If you want to mine on a pool (as it appears) use this syntax

ethminer -G -S "us2.ethermine.org:4444" --stratum-protocol 1 --report-hashrate \
-O "yourethereumaddresshere" --farm-recheck 200

**Comment by Flodu31** [comment]
Thanks.
@AndreaLanfranchi I've the following error:
Invalid argument: -S
Florent

**Comment by AndreaLanfranchi** [comment]
Please paste the whole command you use for invoking

**Comment by Flodu31** [comment]
ethminer -G -S "us2.ethermine.org:4444" --stratum-protocol 1 --report-hashrate -O "0xBe8" --farm-recheck 200

**Comment by Flodu31** [comment]
@anthonyguertin I'm executing your command. It's in progress.

**Comment by AndreaLanfranchi** [comment]
Did you compile ethminer on your machine ?
How did you compile it ?

**Comment by Flodu31** [comment]
I downloaded it from here: 
https://github.com/ethereum-mining/ethminer/releases

**Comment by AndreaLanfranchi** [comment]
According to ethermine.org help it should work as

ethminer.exe --farm-recheck 200 -G -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -O <Your_Ethereum_Address>

**Comment by barzin24** [comment]
hello :)   ubuntu 16.04   evga 1060 6gb   I compiled ethminer 
I use   ./ethminer --farm-recheck 940 -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O adresse.nomdurig
I do not use  the -RH option  ( the green dots)   to avoid stale shares, actually 0-2%  except if I watch a movie  3-5% .with -RH option 5-6% stale shares .
-U option is for cuda    
j'espere que cela t'aura aidé Flodu31

**Comment by Flodu31** [comment]
Hi,
It works with the command of @AndreaLanfranchi 
Thanks everyone for your help.
Florent

**Comment by jangid** [comment]
@Flodu31 is running on Linux and @AndreaLanfranchi's command is for windows platform. I am also getting the same error. Not sure why.

**Comment by squido75** [comment]
@Flodu31 how did you get the -S argument to work?  I'm on Ubuntu 16.04 and -S is invalid argument.  I installed ethminer using apt-get, and am facing your original problem above.

**Comment by smurfy** [comment]
> I installed ethminer using apt-get, and am facing your original problem above.

use the following link to download ethminer:
https://github.com/ethereum-mining/ethminer/releases/latest

using the ubuntu repo gives you a REALLY OLD version

**Comment by squido75** [comment]
@smurfy Thank you!  Did that and it works like a charm!

**Comment by pari111** [comment]
use the following link to download ethminer:
https://github.com/ethereum-mining/ethminer/releases/latest
Even i used above link to download etherminer but still not working

ethminer.exe --farm-recheck 200 -G -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -O 0xb6...
ethminer.exe: command not found

**Comment by pari111** [comment]
bank@bank-All-Series:~$ ethminer --farm-recheck 200 -G -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -O 0xb6d32398d7f723d6c9124002c2f612ffe183cd6b
Invalid argument: -S
Tried with only ethminer removing .exe
still giving error .......... Invalid argument -S
