### ISSUE TITLE
failover from -SP 2 to -SP 0

### ISSUE THREAD

**Issue by tobutridaz** [ethereum-mining/ethminer#371]
I can't seem to make a functional failover from a -SP 2 to a -SP 0, is that even possible?

my last attempt was this
ethminer --farm-recheck 2000 -U -SP 2 -S eth.poolmining.org:3072 -FS -SP 0 -S eu1.ethermine.org:4444 -O

but it obviously doesn't work. How do I tell the fail over to switch the stratum protocol?

**Comment by smurfy** [comment]
Not at this time, the -SP switch applies to ALL stratum connections

**Comment by DeadManWalkingTO** [comment]
Check #811.
Try compile latest (master) version and feedback please.
Thank you!

**Comment by AndreaLanfranchi** [comment]
-P syntax in latest release makes this obsolete.
