### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by rx560** [ethereum-mining/ethminer#374]
Hello, first of all thanks to everone involved in this projects, second.. is there any detailed guide on how to build this on Windows, Ive always worked on wimdows and visual studio and I've failed to compile this source code on all existant levels of failure known to human life. I dowloaded cmake always got errors.. read some info un hunter site.. seemed to go further but still couldnt compile.

Can someone restore faith in human kind and help me out explaining me the steps as if I were 7yo?

Thanks.

**Comment by cwingy** [comment]
In the releases section there is a Windows .zip file [here](https://github.com/ethereum-mining/ethminer/releases/download/v0.12.0/ethminer-0.12.0-Windows.zip) . Extract this file to where you want to run your exe from (i put mine in the root of C). 

Create a batch file that looks like the following (i named my file start_mining):
 
ethminer.exe --farm-recheck 200 -G -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -O <Your_Ethereum_Address>.<RigName>

Then open a powershell (or command prompt window) and browse to where your batch file and ethminer.exe files are located (I keep them together for ease). You can do this in your powershell window by typing 

cd c:\bin
or for reference c:\path\to\bin

Then execute your batch file
./start_mining.bat

This should work on any windows PC as long as your graphics card drivers are installed.

**Comment by rx560** [comment]
Im talking about building the source code not running the actual binaries, but thanks for that info cwingy!

**Comment by cwingy** [comment]
Ah, I've never had luck building from source on windows (haven't tried more than once or twice). I've only successfully accomplished that on my linux machines where all of them are built from source.

**Comment by bmatthewshea** [comment]
You didn't post error.

I always find the Appveyor build file to be helpful if the README hasn't covered all dependencies/builds/etc:
https://github.com/ethereum-mining/ethminer/blob/master/appveyor.yml

& Appveyor build file output on release:
https://ci.appveyor.com/project/ethereum-mining/ethminer/build/job/j4cbuygdke280uod

If you're just looking for the binary, check releases section.
