### ISSUE TITLE
read response failed: end of file reconnecting in 3 seconds

### ISSUE THREAD

**Issue by daniel3234** [ethereum-mining/ethminer#376]
i fixed it nvm

**Comment by sn0rlax** [comment]
How did you fix it?

**Comment by smurfy** [comment]
#384

**Comment by Chru85** [comment]
no help?

**Comment by smurfy** [comment]
@Chru85 @sn0rlax i closed this issue because its fixed and a dupe of #384.  (probably different error but same message).  Without the actual comandline used its not possible to help.
