### ISSUE TITLE
Two ethminer V12 systems crashed on 11/12 at 01:01 (version V9 ran w/o error)

### ISSUE THREAD

**Issue by inprosys** [ethereum-mining/ethminer#378]
Last night on 11/12 (Sun morning) at 01:01 I had two separate computer systems running ethminer V12 crash -- at the same time -- with the following error:  CUDA error in func 'ethash-cuda-miner::search' at line 346:: unknown error.  Both systems are running Windows 7 with Nvidia cards (GTX 1080 Ti and GTX 1080).  I had one other system (also Win 7) running ethminer V9 with two AMD cards (570, 580) which continued to run without any problems. 

At first I thought that it might be due to a switch to a new DAG block, but I believe that the switch from DAG #150 (block 4529999) to #151 (block 4530000) occurred on 11/10 -- is that correct?

So, what happened at 01:01 on the morning of  11/12 that killed two of my ethminer V12 NVIDIA systems?  Any ideas would be appreciated.

**Comment by derubm** [comment]
windows update ? ( just a wild guess) check your systemlog

**Comment by bmatthewshea** [comment]
Also, not a bad idea to make a script to monitor the output and restart if needed.

I have had it die under Linux occasionally and use a cronjob script.
In Windows you could probably just use task manager+batch script and have it run ever 5 mins or so and simply test for -any- output of ethminer process. (And/or watch for 'error' strings.) Kill/restart it via same or another batch/cmd/ps1 file.

I also redirect all ethminer (or whatever miner) output to a 'log' file. On a restart it copies the last 100 lines to a different text file thus preserving the error and then restarts process with a new log file.

**Comment by inprosys** [comment]
Thanks derubm for the idea to look at the system log.  I don't allow Microsoft automatic updating.  However, there was a "security audit logon" event logged around that time.  A "security audit" event can occur for all sorts of reasons, e.g., just accessing a shared disc from another computer.  Do not know why that would cause a CUDA error on two machines at the same time.

**Comment by inprosys** [comment]
Thanks bmattewshea for the restart idea via task manager.  I already log all output using "2>>logfile.txt" so the ">>" operator will cause output to be added to the log file and not overwrite it.  I clear the log file every few days after collecting statistics if there are no unusual events or errors.

**Comment by dhjw** [comment]
Reduce overclock a little bit on whichever card goes offline.

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
