### ISSUE TITLE
CUDA 8 problem  relocation R_X86_64_32S against

### ISSUE THREAD

**Issue by evadogstar** [ethereum-mining/ethminer#38]
Hello, I have following error with CUDA 8 compilation on Ubuntu 17.04 (while original Genoil's fork compiled file).
How to fix this error? Where ti add `-fPIC`? Will this help? 
I'm already manually edit `PATH` and `LD_LIBRARY_PATH' and `CMakeCache.txt` now contain more correct links to `lib64` folder. And I change my gcc6-3 to 4.9 for cuda. But without results. 

`/usr/bin/ld: ../libethash-cuda/libethash-cuda.a(ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
ethminer/CMakeFiles/ethminer.dir/build.make:110: recipe for target 'ethminer/ethminer' failed
make[2]: *** [ethminer/ethminer] Error 1
CMakeFiles/Makefile2:494: recipe for target 'ethminer/CMakeFiles/ethminer.dir/all' failed
make[1]: *** [ethminer/CMakeFiles/ethminer.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by evadogstar** [comment]
I found where to add `-fPIC` to compile. An unfortunately after compilation it have lower results vs original Genoil version :( But I have so much hope on it :) 

This miner:

Trial 1... 56623104
Trial 2... 56273578
Trial 3... 56623104
Trial 4... 56273578
Trial 5... 56972629
min/mean/max: 56273578/56553198/56972629 H/s
inner mean: 37865244 H/s

Genoin

Trial 1... 56273578
Trial 2... 56623104
Trial 3... 56623104
Trial 4... 55924053
Trial 5... 56273578
min/mean/max: 55924053/56343483/56623104 H/s
inner mean: 37632227 H/s

Test done 3 times with the same results :(

Maybe it's because "-fPIC" and Genoin does not request it ? Or it's because hunter download oldest versions of boost and other libs? 

Anyway thanks for your job!

**Comment by chfast** [comment]
I don't understand this `-fPIC` issue. We are not building shared libs, so I don't know why this is needed.

According to your benchmarks, "this miner" is faster. I don't expect any improvements here, but you can check this PR: https://github.com/ethereum-mining/ethminer/pull/18 (the author need some help there).

**Comment by evadogstar** [comment]
@chfast Maybe shared object is not shared lib? It's the step of `nvcc` compiler(cuda) before linking all objects to one execution file.

As already pointed in my situation it not faster maybe because `-fPIC` used :( Or because it use old libs from Hunter. How to compile it with system libs and not with libs that hunter download? 

Anyway thank for your answer!

**Comment by gabrielkhead** [comment]
@evadogstar Could you share where you added -fPIC to compile successfully? I am having the same issue and trying to track this down.

**Comment by gabrielkhead** [comment]
In case anyone else finds this thread the -fPIC flag can be set in ethminer/build/CMakeCache.txt
You're looking for the CMAKE_CXX_FLAGS:STRING key.

**Comment by chfast** [comment]
Ok, I can fix it easily if the `fPIC` is required, but I still don't understand why it is needed.

Travis CI and many others are building it without `fPIC` without problems. `fPIC` is usually required when you build shared libraries, what is not the case in ethminer (ethminer is single binary not depending on any shared library built by us).

**Comment by chfast** [comment]
Another workaround would be to configure with CMake option: `cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON`.

**Comment by evadogstar** [comment]
@gabrielkhead I check now, and seems I add it to `CMakeCache.txt` to `CUDA_NVCC_FLAGS:STRING`

It's compiled and work, but it's not a solution. With fPIC it work slower then Gnoil :(

**Comment by evadogstar** [comment]
@chfast Something with build configuration. It's requested by compiler "like(to make) a crutch". 
Gnoil does not request it :( Maybe something with patch to CUDA or other libs. Need to use 64 libs, but it link/compile with part of 32bit libs and to link all of this stuff need `fPIC`, but I'm not sure about that.

**Comment by evadogstar** [comment]
@chfast Something with build configuration. It's requested by compiler "like(to make) a crutch".
Gnoil does not request it :( Maybe something with patch to CUDA or other libs. Need to use 64 libs, but it link/compile with part of 32bit libs and to link all of this stuff need fPIC, but I'm not sure about that.

I suggest to NOT add `fPIC` to repository build, because it's crutch and need to fix the issue why it's requested  :(

**Comment by chfast** [comment]
Are you saying that CUDA kernel is built for 32-bit architecture instead of 64-bit one?

**Comment by evadogstar** [comment]
@chfast fPIC requested by cuda compiler. As I remember...

**Comment by evadogstar** [comment]
@chfast I think so. And because it's 32bit, then to link it to program we need a crutch of "fPIC" to compile something like 32bit library that can be used at 64bit or something like this. I'm not sure! It's only my guess-work. 
(sorry for my english and for too many posts, EDIT button does not work :( )

**Comment by evadogstar** [comment]
System:
user@pc:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44
user@pc:~$ gcc --version
gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406

**Comment by Selaron** [comment]
I have a similar issue on Debian Stretch. I get lots of these message from binaries in ~/.hunter/ folder:

> /usr/bin/ld: /home/***/.hunter/_Base/435b09a/cd01ff3/8934f7a/Install/lib/libz.a(inflate.c.o): relocation R_X86_64_32S against symbol `zcalloc' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: /home/***/.hunter/_Base/435b09a/cd01ff3/8934f7a/Install/lib/libz.a(inftrees.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: /home/***/.hunter/_Base/435b09a/cd01ff3/8934f7a/Install/lib/libz.a(inffast.c.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: /home/***/.hunter/_Base/435b09a/cd01ff3/8934f7a/Install/lib/libz.a(zutil.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: /home/***/.hunter/_Base/435b09a/cd01ff3/8934f7a/Install/lib/libz.a(crc32.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: Nonrepresentable section on output
> collect2: error: ld returned 1 exit status
> ethminer/CMakeFiles/ethminer.dir/build.make:108: recipe for target 'ethminer/ethminer' failed
> make[2]: *** [ethminer/ethminer] Error 1
> CMakeFiles/Makefile2:404: recipe for target 'ethminer/CMakeFiles/ethminer.dir/all' failed
> make[1]: *** [ethminer/CMakeFiles/ethminer.dir/all] Error 2
> Makefile:149: recipe for target 'all' failed
> make: *** [all] Error 2
> 

How can I make Hunter build using that `-fPIC` flag?

**Comment by evadogstar** [comment]
Other question: how to build it without hunter? Maybe it's the problem with downloaded libs by hunter.

**Comment by Selaron** [comment]
Just figured out how to build this on my debian rig. Had to do multiple painfule try and error sessions ^^

> mkdir build
> cd build
> 
> cmake -DETHASHCL=OFF -DETHASHCUDA=ON -DBUILD_SHARED_LIBS=ON ..
> 
> -> Adjust CMakeCache.txt
> Boost_SYSTEM_LIBRARY_RELEASE:FILEPATH=/usr/lib/x86_64-linux-gnu/libboost_system.so
> CMAKE_CXX_FLAGS:STRING= -fPIC
> CMAKE_C_FLAGS:STRING= -fPIC
> 
> cp /usr/lib/x86_64-linux-gnu/libjsoncpp.so ~/.hunter/_Base/435b09a/cd01ff3/a107d0c/Install/lib/libjsoncpp.a
> cp /usr/lib/x86_64-linux-gnu/libz.a ~/.hunter/_Base/435b09a/cd01ff3/a107d0c/Install/lib/libz.a
> cp /usr/lib/x86_64-linux-gnu/libcurl.so ~/.hunter/_Base/435b09a/cd01ff3/a107d0c/Install/lib/libcurl.a
> 
> cmake --build .


I get +2,5 % Hashrate on my GTX 1070 cards compared to Gnoil.

When overclocked, I get +3,5% compared to Gnoil with same overclocking.

Default setting --cuda-parallel-hash 4 seemes best for me, any other value slows things down.

I too hope there's an easy way to build without hunter as I have all dependencies on system already. Nevertheless, having a dependency manager is always a real good thing, if it works on every common OS.

**Comment by DeadManWalkingTO** [comment]
I think the solution has been found.
