### ISSUE TITLE
executing cmake get stuck

### ISSUE THREAD

**Issue by helxsz** [ethereum-mining/ethminer#381]
my system is ubuntu 14.04 , when executing the

>  cmake .. 

```
-- [hunter] HUNTER_ROOT: /root/.hunter
-- [hunter] [ Hunter-ID: aafb99b | Toolchain-ID: 66a707b | Config-ID: a63b4ed ]
-- [hunter] BOOST_ROOT: /root/.hunter/_Base/aafb99b/66a707b/a63b4ed/Install (ver.: 1.65.0)
-- [hunter] Cache HIT: Boost
-- [hunter] Cache info: /root/.hunter/_Base/Cache/meta/66a707b/Boost/1.65.0/f926007/da39a3e/d41f56c/0716d97/da39a3e/cache.sha1
```
what is wrong?

**Comment by smurfy** [comment]
try

```
    - cmake -DHUNTER_JOBS_NUMBER=4 -DETHASHCUDA=$CUDA -DETHASHCL=ON -DAPICORE=ON -H. -Bbuild
    - cmake --build build -- -j4
```

also a good reference is: https://github.com/ethereum-mining/ethminer/blob/master/.travis.yml

**Comment by helxsz** [comment]
still getting stuck

**Comment by mask8** [comment]
maybe try to clean the hunter cache? By the way, the sha comparison might take a bit since boost is quite big package. Depending on your machine spec. It took me about 5 mins plus.

**Comment by helxsz** [comment]
@mask8 however it took me two hours in stuck. On the path of the cache, there are files - **CACHE.DONE,  cache.sha1,  cmake.lock , DONE , SHA1**.    

are the file name endewith `DONE` meaning the caching process finished?

**Comment by smurfy** [comment]
you can try deleting the whole ``/root/.hunter/`` directory

**Comment by zhumingyu** [comment]
@helxsz hi,did you solve this problem?

**Comment by bhc8521** [comment]
there's a proxy needed
