### ISSUE TITLE
ethminer 0.12 freezes after Win10 Fall Creators Update

### ISSUE THREAD

**Issue by OlafSt** [ethereum-mining/ethminer#385]
After successfully installing Fall Creators Update my ethminer just freezes. Looks like this:

```
Z:\Geth\ethminer>ethminer.exe -G -v 8 --cl-global-work 16384 --cl-local-work 256 --opencl-platform 1 --farm-recheck 400 -F http://eth-eu.dwarfpool.com:80/adr/GPUMiner
  i  18:38:45|main      Found suitable OpenCL device [ Ellesmere ] with 8589934592  bytes of GPU memory
 cl  18:38:45|cl-0      No work. Pause for 3 s.
  m  18:38:45|main      Waiting for work package...
  m  18:38:45|main      Got work package: #143d72ce
  m  18:38:46|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  18:38:46|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  18:38:47|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  18:38:47|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  18:38:48|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  18:38:48|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  18:38:48|cl-0      New work: header #143d72ce
```
Then ethminer freezes and nothing else happens. When switching to use the built-in GPU inside the CPU, the results are the same, using another pool for mining also didn't help. Process can be cancelled with CTRL-C so it looks like ethminer is waiting for something that doesn't happen.

Had the wild idea that Update KB4048955 (which locks up 24-Pin-Printers from Epson) may be the cause, but deinstalling it didn't help. KB4048954, which also locks up Epson needle Printers, is not installed here.

Any help greatly appreciated.

**Comment by ic0n** [comment]
Same for me, ethminer just hang at `New work: header ...`

**Comment by ic0n** [comment]
OK, it looks like the miner just can't log something to the terminal, but it still runs, it's not stuck there and doing nothing.

**Comment by OlafSt** [comment]
I have found a solution to this phenomenon. While working, ethminer switches to a new block. This looks like this:
`
 cl  23:54:20|cl-0      Switch time 69 ms / 7303 us

 cl  23:54:21|cl-1      New work: header #827b0938ÔÇª target {some cryptic number}`

as you can see we have some garbage there at the end of the header number. This annoyed me and I switched the codepage of the CMD-Window to 65001 using the chcp command. This successfully Shows the real characters intended by Dwarfpool - but under some circumstances the output to CMD gets stuck.

Eliminating the chcp-call also eliminated the freezers.

**Comment by ic0n** [comment]
@OlafSt Wow, adding ` chcp 437 `
at the head of the bat script actually works!!!
No more freeze now!

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
