### ISSUE TITLE
Low hashrate in msi RX 580 8 GB GDDR5 Armor OC directx 12

### ISSUE THREAD

**Issue by blgsyrmhnds** [ethereum-mining/ethminer#388]
Hi
My GPU : MSI RX 580 Armor OC 8GB GDDR5 256Bit AMD Radeon DX12 for mining. They said it is hashrate 30 MH/S - 35 MH/S in mining platforms but my hashrate is 20-25 MH/S altough I did OC.Before OC my hashrate is 15-20 MH/S

 My other hardware 
-core 2 dou processor -
4 gb ddr2 ram 
-160 gb HDD 
-775 slot main board 
-450 w power supply

 Are there any problem with this hardware?
Why my hashrate is to bad?I am using windows 10 and my pool is minergate

I just did OC and start mining with command line with this command 

ethminer -G -S eth.pool.minergate.com:45791 -O blgsyrmhnds@gmail.com

Should I give a any parameter(such as openc cl,paralel...) for increase hashrate?Or Should I change my pool?If you advice changing pool which one do you prefer?I am in Turkey and I think I should choose pool which it is server location nearest me?

I just downloaded ethminer.exe and in folder there is only ethminer.exe and ethminer.pdb
I downloaded here: https://github.com/ethereum-mining/ethminer/releases  

ethminer-dbg-0.12.0-Windows.zip

should I put opencl.DLL or other things?

**Comment by smurfy** [comment]
Well the card is quite CRAP. (i have the same)

You should get around 30MH/s with it. But you need to do read up on memory straps and tweaking of AMD cards.

Closing this issue, because its not a ethminer issue.

**Comment by blgsyrmhnds** [comment]
@smurfy  what is your configuration?How can you get 30 MH/s can you share your .rom file please

**Comment by Hendler** [comment]
https://cryptoyeti.com/msi-rx580-armor-8g-review-and-bios-mod-guide/3/

**Comment by SilkyBlade** [comment]
download the latest AMD drivers  Adrenalin Edition 17.12.2 
http://support.amd.com/en-us/download/desktop?os=Windows%2010%20-%2064#
after installing it open the settings 
gaming
global settings
disable AMD crossfire , the program will restart
then under GPU work load change it from graphics to compute ( do this for each of your cards)
