### ISSUE TITLE
DGX-1 V100 Server Mining

### ISSUE THREAD

**Issue by UKbased** [ethereum-mining/ethminer#39]
I am looking to find out if anyone can provide their expertise on developing a program, in mining on the new DGX-1 V100 server?

**Comment by disconusa** [comment]
@UKbased we support mining on V100. Careful planning is critical, otherwise its a waste of resources. You are also battling against time.

**Comment by UKbased** [comment]
Excellent what is the output of eth coins and do you have access to servers
?

**Comment by UKbased** [comment]
Email on: sphericalmining@gmail.com

**Comment by DeadManWalkingTO** [comment]
Any news?
