### ISSUE TITLE
Worker not authorized?

### ISSUE THREAD

**Issue by blast1987** [ethereum-mining/ethminer#390]
Hello,
i am trying to mine with my gtx 1080 but i dont understand how to launch it, actually i am using:

ethminer -RH -U -S uk-etn-pool.hashparty.io:5555 -O etnBLaBLaBLaBLaBLaAddressetck

and that's what i'm getting:

 cu  14:53:35|main      Using grid size 8192 , block size 128
  i  14:53:35|main      Connecting to stratum server uk-etn-pool.hashparty.io:5555
  i  14:53:35|stratum   Connected to stratum server uk-etn-pool.hashparty.io : 5555
  i  14:53:35|stratum   Starting farm
  i  14:53:35|stratum   Subscribed to stratum server
  i  14:53:35|stratum   Worker not authorized: etnBLaBLaBLaBLaBLaAddressetck
  i  14:53:35|stratum   Disconnecting
  i  14:53:35|stratum   Stopping farm

Can anyone help me?

**Comment by smurfy** [comment]
First of i would use 3333 instead of 5555 with only one card.

other than that you can try:

``ethminer -RH -U -S uk-etn-pool.hashparty.io:3333 -O YOURWALLET:x``

You also can play with the ``-SP`` option, for example ``-SP 1``, which basically is the protocol claymore uses.

**Comment by smurfy** [comment]
Also it seems, ETN is not ETH, so for me it looks even if you get your stratum auth problem working, ethminer is not the choice for you.
