### ISSUE TITLE
ethminer endlessly computing DAGs

### ISSUE THREAD

**Issue by wpoet** [ethereum-mining/ethminer#392]
I have a g2.8xlarge instance on AWS.
geth version is 1.7.2-stable, ethminer version 1.2.9 (Build: Linux/g++/Interpreter/RelWithDebInfo).

After geth has downloaded the necessary files, I run "ethminer -G". All it does is compute a DAG. When it is finished it starts again computing a new DAG. This runs endlessly, and never starts any mining. I have two dozens of  files like full-R23-0823bb39dee602fc, etc., after half a day of running ethminer.

Does anyone have an idea what could be done?

**Comment by chfast** [comment]
Yes. Sync blockchain first, then start mining. Otherwise you will be catching up with DAGs all the time.

And use ethminer from here, not some old 1.2.9.
