### ISSUE TITLE
Travis CI is broken

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ethereum-mining/ethminer#395]
https://travis-ci.org/ethereum-mining/ethminer/builds/305543263?utm_source=github_status&utm_medium=notification

Since three or four builds, Travis Ci always throws an error on "pip install requests"
because "/Users/travis/.travis/job_stages: line 57: pip: command not found"

**Comment by chfast** [comment]
Fixed in https://github.com/ethereum-mining/ethminer/pull/396.
