### ISSUE TITLE
CPU at 100%

### ISSUE THREAD

**Issue by vampyren** [ethereum-mining/ethminer#399]
Hi folkz, 

This my first time i use this miner, before i used claymore but i thought i could try this and see how it works. 
Sadly when i run this my CPU goes to 100%. Another thread says to change farm-recheck to 5-10 but it did not help at all. Sadly i have to continue using claymore for this reason, thought i should mention it. I run this for a very short time but i did not see my total hashpower. Also the color on claymore is helpful.
Maybe use that for improvement work in the future ;)

**Comment by chfast** [comment]
What operating system do you use?

**Comment by chfast** [comment]
And what GPU?

**Comment by smurfy** [comment]
Also what version do you use? master or another one?

**Comment by vampyren** [comment]
Hi,
I'm on Windows 10 x64, CPU is a i5 4Ghz. 
I  just downloaded the latest version today.

**Comment by MariusVanDerWijden** [comment]
What Graphics Cards (GPU) do you use?

**Comment by mgedzius** [comment]
I'm getting a similar issue now. When I notice that I'm submitting an abnormal amount of stale shares I try killing ethminer. Instead of ethminer closing my cpu shoots too 100% and the process becomes defunct and not even a sigkill will stop it. I try shutdown -r and the system just hangs. I have to hard reset the system. I also ran nvidia-smi when this happened and it gave me an error something about not detecting the cards and a system reboot was needed. From what I could gather it seems it might be that my cards are overheating and shutting down. I'm trying to recreate the issue now. I will post back if I learn anything new.

Ubuntu 16.04.1
Nvidia GTX 1080 - 384.69

**Comment by mgedzius** [comment]
Just lost my first card
![issue](https://user-images.githubusercontent.com/3487807/33229054-df70129c-d18c-11e7-8854-d2824864da0e.png)

**Comment by vampyren** [comment]
GPU: nVidia 1070 
Driver: 388.31

**Comment by derubm** [comment]
set all of your cards to P0 mode before starting ethminer. this gives the cards a actual boost of 200 mhz, 
crashes and os hanging are produced by oc´d gfx ram on p2 state. if your card switches to P0 state it adds extra 200 mhz to actual speed, which causes crashes , os hanging, bad things. Note: you need t set gfx card ram to 200 mhz less then now, as the p0 state gives your card a 200 mhz push from start on.

**Comment by Jacxz** [comment]
@mgedzius the output in your screenshot looks a lot like what I see before ethminer crashes with a "broken pipe" which is reported in #171

**Comment by felixkohtz** [comment]
CPU also at 100% -- If more info is needed, please let me know:

./ethminer --version
> ethminer version 0.12.0
> Build: Linux/g++/Release


$ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 17.10
> Release:	17.10
> Codename:	artful

$ top

> Tasks: 206 gesamt,   1 laufend, 205 schlafend,   0 gestoppt,   0 Zombie
> %CPU(s): 22,1 be,  4,1 sy,  0,0 ni, 73,9 un,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
> KiB Spch :  8125492 gesamt,  6564420 frei,   817556 belegt,   743516 Puff/Cache
> KiB Swap:  8343548 gesamt,  8343548 frei,        0 belegt.  6996264 verfü Spch 
> 
>   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     ZEIT+ BEFEHL                                                                                                                                                                                                     
>  3893 rig1     20   0 15,134g 149464  99064 S 100,0  1,8 374:54.92 ethminer  

 


$ nvidia-smi

> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce GTX 1070    Off  | 00000000:01:00.0  On |                  N/A |
> | 44%   66C    P2   136W / 230W |   2457MiB /  8110MiB |    100%      Default |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0      1624      G   /usr/lib/xorg/Xorg                            21MiB |
> |    0      3893      C   ./ethminer                                  2379MiB |
> |    0      4025      G   /usr/lib/xorg/Xorg                            52MiB |
> +-----------------------------------------------------------------------------+
>

**Comment by bmatthewshea** [comment]
I had same problem - binary using 100% cpu - though it's mining fine
Ubuntu 16.04.3 LTS

I happen to notice my start file had -G because I had been running amd card with:
`ethminer -G -SC 1 -SP 1 -S 127.0.0.1:8008`

But i had swapped cards out and replaced with nvidia and forgot to change my start file.
was running opencl with nvidia card..
I switched to -U/cuda and that fixed the cpu load issue. (in my case..)

**Comment by ddobreff** [comment]
Its still unresolved regarding OpenCL.

**Comment by smurfy** [comment]
This happens on CUDA too sometimes. (Occurred on Win10) I noticed a problem of 30-100%  ethminer cpu load.
IT happens after a while sometimes.
It may be related to other cpu load. i noticed that if i do something cpu intensive the likely hood of  ethminer buggs and take higher cpu load is higher.

**Comment by bmatthewshea** [comment]
@smurfy Hmm never noticed it all under Windows, but as far as MS machines here, I'm still old school on Win7 lol. I will keep an eye out, though..

**Comment by fuelman31410** [comment]
I was able to resolve this by changing my page file size, I set min to 20480 max to 51200 . I am running 6 gtx 1070's and was getting terrible output before like 68mh now up to 158mh. This is my current batch file

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --farm-recheck 2000 --cuda -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -O mywalletaddress..minername --dag-load-mode sequential


Hope it helps

**Comment by chfast** [comment]
@fuelman31410 can you confirm this is what happened:
1. You had ethminer performing bad with 100% CPU usage.
2. You increased page file size (in Windows?) and now it works better?

**Comment by Quozzo** [comment]
I was having the same problem with ethminer.exe using two cores and keeping them constantly at 100%. Having a 7900X overclocked to 4.8GHz I didn't care all too much but was curious if that was normal.

Using what fuelman posted and changing the -G to --cuda and removing the last variable means it now uses less than 1% of my total CPU power. On top of that. My system power draw was reduced from 500W to less than 450W which is more than a 10% reduction. Unfortunately the hash rate has also been reduced on my 1080Ti from 37.5MH/s to around 35MH/s. 

Not sure what the difference is between -G and --cuda is but it is definitely doing something different. Just not sure if the ~7% drop in hash rate is worth it.

**Comment by chfast** [comment]
-G uses OpenCL, -U uses CUDA. @Quozzo do you use Windows?

**Comment by fuelman31410** [comment]
Yes, I am running my miners on Windows 10

**Comment by Quozzo** [comment]
@chfast Yes I use Windows 10

**Comment by chfast** [comment]
So this issue is only for Windows and Nvidia GPUs when using OpenCL? (@fuelman31410 did you mentioned having 100% usage also when running in CUDA mode?)

**Comment by chfast** [comment]
I've found this similar symptoms: https://github.com/pandegroup/openmm/issues/1541.

**Comment by Quozzo** [comment]
@chfast Yeah it looks similar. I should mention I have two 1080Ti's which is probably why I've got two cores pegged at 100% instead of a single core.

**Comment by uvoz** [comment]
Same here on Ubuntu 17.10. 100% CPU usage.  Replaced the -G flag with - -cuda. Processor is near idle now.

**Comment by fossum** [comment]
I'm running Ubuntu 17 and was using the `--opencl` option. I had 300% CPU even after a process restart. I switched to `--cuda` and all is better now.

**Comment by Quozzo** [comment]
@fossum Was that using version 0.13.0 because that was fixed for me (on windows).

**Comment by fossum** [comment]
Yes, I think it was with 13. I use the latest stable release.
