### ISSUE TITLE
ETHDBUS configuration option

### ISSUE THREAD

**Issue by chiwalfrm** [ethereum-mining/ethminer#402]
Can someone explain the ETHDBUS configuration option?  It is set to 'OFF' by default.

```
------------------------------------------------------------- components
-- ETHASHCL         Build OpenCL components                  ON
-- ETHASHCUDA       Build CUDA components                    ON
-- ETHSTRATUM       Build Stratum components                 ON
-- ETHDBUS          Build D-Bus components                   OFF
-- APICORE          Build API Server components              ON
------------------------------------------------------------------------

```

**Comment by dymonek** [comment]
**Maybe**
What is D-Bus?
D-Bus is a message bus system, a simple way for applications to talk to one another. In addition to interprocess communication, D-Bus helps coordinate process lifecycle; it makes it simple and reliable to code a "single instance" application or daemon, and to launch applications and daemons on demand when their services are needed.

source: https://www.freedesktop.org/wiki/Software/dbus/

**Comment by smurfy** [comment]
This is an alternative way of an API to access miner data. See #240
