### ISSUE TITLE
Mining not working with "ethminer.exe -G"

### ISSUE THREAD

**Issue by RanomPanda** [ethereum-mining/ethminer#408]
I want to mine alone and I wasn't having this problem earlier, I cant seem to get it to do something... I'm not sure and here are the logs of what I'm trying to do:

**C:\Users\Panda\Videos>cd C:\Users\Panda\Desktop\ethminer-0.12.0-Windows\bin

C:\Users\Panda\Desktop\ethminer-0.12.0-Windows\bin>setx GPU_FORCE_64BIT_PTR 0

SUCCESS: Specified value was saved.

C:\Users\Panda\Desktop\ethminer-0.12.0-Windows\bin>setx GPU_MAX_HEAP_SIZE 100

SUCCESS: Specified value was saved.

C:\Users\Panda\Desktop\ethminer-0.12.0-Windows\bin>setx GPU_USE_SYNC_OBJECTS 1

SUCCESS: Specified value was saved.

C:\Users\Panda\Desktop\ethminer-0.12.0-Windows\bin>setx GPU_MAX_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\Users\Panda\Desktop\ethminer-0.12.0-Windows\bin>setx GPU_SINGLE_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\Users\Panda\Desktop\ethminer-0.12.0-Windows\bin>ethminer -G
  i  21:09:17|main      Found suitable OpenCL device [ GeForce GTX 1080 ] with 8589934592  bytes of GPU memory
 cl  21:09:17|cl-0      No work. Pause for 3 s.
  m  21:09:17|main      Waiting for work package...
  X  21:09:18|main      Failed to submit hashrate.
  X  21:09:18|main      Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8545**

Can I have some help?

**Comment by smurfy** [comment]
First of all, since you have a nvidia card use cuda (-U)
Also you need to specify your pool and wallet.

Something like this, if ethermine is your pool of choice.
``ethminer.exe -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O <Your_Ethereum_Address>.<RigName>``

**Comment by RanomPanda** [comment]
But I want to mine alone :/

**Comment by smurfy** [comment]
Then install geth, wait till it syncs and then start ethminer with ``ethminer.exe -U``.

But you probably only waste money on power. But thats your choice. The chances getting **any** ethereum this way especially with a single gforce 1080 are rather slim.

**Comment by RanomPanda** [comment]
The thing is when i do Ethminer.exe -U it does the command line on my first comment...

**Comment by smurfy** [comment]
as i said before:

> Then install geth, wait till it sync

if you have geth running, ethminer can connect to it and do solomining

**Comment by jmgz4e9** [comment]
Seems to be a DNS issue. `nslookup` worked but not `telnet u1.ethermine.org 4444` (I got a temporary name failure). So I forced my DNS to use Google's public DNS. Ubuntu since 16.04 is using systemd, so you can't edit `/etc/resolv.conf`. Instead, change the `DNS` line in `/etc/systemd/resolved.conf`.

````diff
 [Resolve]
-DNS=
+DNS=8.8.4.4 2001:4860:4860::8844
 #FallbackDNS=
 #Domains=
```

Then restart with `systemctl restart systemd-resolved`.

If you are on Windows, it's pretty much point and click. You can refer to Google DNS instructions [here](https://developers.google.com/speed/public-dns/docs/using#windows). 

(If you found this useful, tips are most welcome! 0x44B7b4777Ec399Bc4a9b5621DcABC8Ea9612b5fd)
