### ISSUE TITLE
An error occurs with core dump when the server's port is blocked. (Ubuntu 16.04)

### ISSUE THREAD

**Issue by say2alice** [ethereum-mining/ethminer#412]
An error occurs with core dump when the server's port is blocked.

**System**
ubuntu 16.04 (4.4.0-101-generic #124-Ubuntu SMP)
cuda 8.0

**error message**
12:11:44|stratum   Stopping farm
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Aborted (core dumped)

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!
