### ISSUE TITLE
How could this be possible ? Is ethermine hacked ?

### ISSUE THREAD

**Issue by lev121212** [ethereum-mining/ethminer#417]
Toggle navigation

Miner: 362c89a6d8a1597ff41eb03e1E897d0d95827C54

Dashboard
Payouts / Rounds
Settings
Hashrates	2.0 GH/s / 260.5 GH/s / 260.6 GH/s
Unpaid Balance	1.023 ETH
Active Workers	12
Shares (Last 1h)	227568 (96%) / 10622 (4%) / 0 (0%)
Hashrate, Shares & Workers
Hashrate [MH/s]
0.00000
50.0000G
100.000G
150.000G
200.000G
250.000G
Current Effective Hashrate
Average Effective Hashrate
Reported Hashrate
Shares
0
20000
40000
60000
80000
100000
120000
140000
160000
180000
200000
220000
240000
Valid Shares
Stale Shares
Invalid Shares
Active Workers
0
2
4
6
8
10
12
Active Workers
Workers (12 active)

Search:
Worker	Reported Hashrate	Current Hashrate	Average Hashrate	Valid Shares (1h)	Stale Shares (1h)	Invalid Shares (1h)	Last Seen
biogas	165.0 MH/s	17.6 GH/s	17.7 GH/s	15261 (95%)	866 (5%)	0 (0%)	7 minutes ago
default	152.1 MH/s	128.8 MH/s	147.2 MH/s	112 (95%)	6 (5%)	0 (0%)	7 minutes ago
halle	175.2 MH/s	122.6 GH/s	121.6 GH/s	107785 (96%)	3933 (4%)	0 (0%)	7 minutes ago
melk1	168.5 MH/s	13.3 GH/s	13.7 GH/s	11518 (95%)	653 (5%)	0 (0%)	7 minutes ago
melk2	151.9 MH/s	9.9 GH/s	9.3 GH/s	8535 (94%)	570 (6%)	0 (0%)	7 minutes ago
melk3-108	167.2 MH/s	14.1 GH/s	14.1 GH/s	12260 (95%)	692 (5%)	0 (0%)	7 minutes ago
uno1/3	171.0 MH/s	15.3 GH/s	15.8 GH/s	13340 (95%)	687 (5%)	0 (0%)	7 minutes ago
uno1/4	176.4 MH/s	18.5 GH/s	18.8 GH/s	16040 (95%)	883 (5%)	0 (0%)	7 minutes ago
uno1/5	174.5 MH/s	17.2 GH/s	16.7 GH/s	14975 (95%)	825 (5%)	0 (0%)	7 minutes ago
uno1/6	174.1 MH/s	17.1 GH/s	17.3 GH/s	14889 (95%)	818 (5%)	0 (0%)	7 minutes ago
uno1/7	173.6 MH/s	13.6 GH/s	13.6 GH/s	11835 (95%)	650 (5%)	0 (0%)	7 minutes ago
usb	174.8 MH/s	1.2 GH/s	1.2 GH/s	1018 (96%)	39 (4%)	0 (0%)	7 minutes ago

© bitfly gmbh 2017 | The Ethereum Mining Pool | Imprint

**Comment by smurfy** [comment]
Not sure what you mean also not really related to ethminer.
