### ISSUE TITLE
No hashrate displayed using version 0.12.0rc3

### ISSUE THREAD

**Issue by inprosys** [ethereum-mining/ethminer#420]
I'm running ethminer version 0.12.0rc3 Build: Windows/msvc/Release (as displayed by -V option) on a Windows 7 system.  Everything continues to work great except that no hashrate displays locally and no hashrate is reported to the stratum server.  I've seen screen shots of what it is supposed to look like but it's not happening here.  Is there some new run-time option that needs to be set to allow the hashrate to be display and/or be reported?

By the way, when I downloaded the rc3 version from GitHub, the only file was "ethminer.exe" itself in a \bin\ directory when the zip was extracted.  Do some other libraries or dll files need to be updated?

**Comment by bmatthewshea** [comment]
You try the non-RC?

https://github.com/ethereum-mining/ethminer/releases/download/v0.12.0/ethminer-0.12.0-Windows.zip

**Comment by inprosys** [comment]
Thanks for the suggestion, bmatthershea.
Yes, I'm running v0.12.0 on four machines.  There is no hash rate being reported on any of them.  So, no hashrate displayed by v0.12.0 , and no hashrate displayed by v0.12.0rc3 under any conditions on any of my systems.

**Comment by bmatthewshea** [comment]
what is the full command you are using to start ethminer? What GPU card(s) are you running it on?

**Comment by smurfy** [comment]
@inprosys 
* What pool do you use
* Whats your commandline to start ethminer

**Comment by inprosys** [comment]
Thanks for the suggestion about "What is the full command you are using?"  

I log and write every run to a file to have a record of any errors.  And, that was the problem.  I was using the option "-v 1" and that level of verbosity was suppressing the hashrate display.  Any other level of verbosity such as "-v 2" and above will produce the display of the hashrate.

I will close this problem.
