### ISSUE TITLE
Invalid device symbol

### ISSUE THREAD

**Issue by lum4chi** [ethereum-mining/ethminer#422]
Hello, I've build this project in a machine (ubuntu 16.04, NVIDIA Quadro K4000) and successfully mined. Then tried same things on another machine (ubuntu 16.04, 4xNVIDIA Tesla M2075). Build is ok, but at runtime this error shows:
`Cuda error in func 'set_constants' at line 168 : invalid device symbol.`
Any advice?

**Comment by MariusVanDerWijden** [comment]
Do you use the Master?

**Comment by lum4chi** [comment]
Yes.

**Comment by MariusVanDerWijden** [comment]
NVIDIA Tesla M2075 GPU's only has Compute Capability 2.0, etherminer needs at least 3.0
http://www.gpuzoo.com/GPU-NVIDIA/Tesla_M2075.html

**Comment by lum4chi** [comment]
Oh I see! I was unaware or it... I'm sorry to have bothered you, thanks!
