### ISSUE TITLE
hackintosh issue with rx580 (natively supported) card STRIX

### ISSUE THREAD

**Issue by harrison-n** [ethereum-mining/ethminer#424]
Can't figure out what the problem is. Miner works for about an hour and then locks everything up. Can't find any logs or anything like that so this issue is mostly unhelpful. Just posting this here in case someone runs into the same issue eventually so we can weep together or maybe find a solution. Could honestly just be mac drivers too but I'm not sure right now.

**Comment by harrison-n** [comment]
found this in the logs only when I'm mining. 

void IOAccelFenceMachine::fence_timeout(IOTimerEventSource *): Radeon Pro 580 prodding blockFenceInterrupt

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!

**Comment by AndreaLanfranchi** [comment]
No feed back. Closing.
