### ISSUE TITLE
You broke -FS exit

### ISSUE THREAD

**Issue by tomose** [ethereum-mining/ethminer#425]
Linux

Works fine for ethminer_0.12.0.dev1

Does not work for ethminer_0.12.0

**Comment by cfelicio** [comment]
confirmed also broken on windows, this is very important for folks that are doing coin switching. Thanks :-)

**Comment by jromang** [comment]
Also on linux, -FS exit does not work

**Comment by tomose** [comment]
This is still broken in v13 rc2.

Even trying -SF exit fails to get the program to exit. 

  i  14:57:54|CUDA0     No work. Pause for 3 s.
  i  14:57:57|CUDA0     No work. Pause for 3 s.
  i  14:58:00|CUDA0     No work. Pause for 3 s.
  i  14:58:03|CUDA0     No work. Pause for 3 s.
  i  14:58:06|CUDA0     No work. Pause for 3 s.
  i  14:58:09|CUDA0     No work. Pause for 3 s.

That's all it does instead of exiting like it should. Going back to 12 til this is fixed.

**Comment by tomose** [comment]
ethminer_0.12.0.dev1 - Works fine
ethminer_0.12.0.rc1 - Works fine
ethminer_0.12.0.rc2 - Works fine (I thought it crashed during initial testing but further testing produced no crash on exit)
ethminer_0.12.0.rc3 - Exits but can generate a crash for ethminer on exit
ethminer_0.13.0rc1 and all versions since - No longer exits, no longer crashes

**Comment by tomose** [comment]
Is anybody even reading this? If a bug report is filed in the woods and no one is around to read it, does it make a sound?

**Comment by nCrazed** [comment]
Any update on this?

**Comment by jean-m-cyr** [comment]
Fix in PR#521. Included in r13

**Comment by jean-m-cyr** [comment]
> If a bug report is filed in the woods and no one is around to read it, does it make a sound?

No, it means some developer forgot to flag the solution against this ticket.

**Comment by nCrazed** [comment]
@jean-m-cyr I am on 0.13.0 and `-FS exit` still goes into a `No work. Pause for 3 s.` loop.

**Comment by jean-m-cyr** [comment]
@nCrazed I guess I wasn't paying attention, I thought this was about failover. What is this -FS option? Don't see it in the help. Do you mean -SF?

**Comment by nCrazed** [comment]
@jean-m-cyr it is my understanding that it was introduced in the [Genoil's fork](https://bitcointalk.org/index.php?topic=1368785.msg14505111#msg14505111) in order to support multi-algo switching use case (e.g. MPH).

The fact that it does not trigger `Invalid argument: -FS` and @tomose's comments above regarding the functionality in older versions suggests that it was at some point merged into this version as well without updating the `--help` output.

**Comment by tomose** [comment]
-FS exit has been depreciated. --exit only seems to be for GPU errors, not "no work" events.

The issue remains when using non-depreciated methods.

https://github.com/ethereum-mining/ethminer/issues/894
