### ISSUE TITLE
ethminer-0.12.0-Windows.zip infected with Application.BitCoinMiner.XO malware

### ISSUE THREAD

**Issue by demonfiddler** [ethereum-mining/ethminer#426]
According to Bullguard anti-virus, the file https://github.com/ethereum-mining/ethminer/releases/download/v0.12.0/ethminer-0.12.0-Windows.zip is infected with the virus:
----------
Infected object: ethminer.exe

Malware: Application.BitCoinMiner.XO
Path: D:\Users\Adrian\Ethereum\ethminer.exe
Infected process: [3256] C:\WINDOWS\Explorer.EXE

07/12/2017 20:33:58
----------

For heaven's sake, doesn't GitHub have anti-virus software to screen the downloadable files it hosts?!!!

**As a matter of urgency please take these binaries down pending investigation.**

**Comment by smurfy** [comment]
false positive

**Comment by MariusVanDerWijden** [comment]
Application.BitCoinMiner.XO... It detects it as mining software.

**Comment by demonfiddler** [comment]
In that case might I suggest that it would be a good idea to provide an explanation of this on the download page?
