### ISSUE TITLE
help

### ISSUE THREAD

**Issue by RUGame17** [ethereum-mining/ethminer#427]
dlls missing?
![vcr](https://user-images.githubusercontent.com/32495848/33739107-70f7196c-db61-11e7-8539-e7f6719ac0c7.png)
![msv](https://user-images.githubusercontent.com/32495848/33739108-721e9266-db61-11e7-8342-785b5282299e.png)

**Comment by MariusVanDerWijden** [comment]
Did you install CUDA toolkit

**Comment by smurfy** [comment]
Please install the [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-US/download/details.aspx?id=48145)
