### ISSUE TITLE
Unsupported gpu architecture 'compute_70'

### ISSUE THREAD

**Issue by Codefordl** [ethereum-mining/ethminer#429]
I received the error  on two different computers with cuda 8.0. One is GTX1060,the other is GTX TITAN X (old version).I have no ideal with this problem. Who can help me? 
> [ 63%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_70'
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.cmake:207 (message):
  Error generating
  /home/dl/ethminer/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:63: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o' failed
make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
CMakeFiles/Makefile2:319: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/all' failed
make[1]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2\

**Comment by fhlfibh** [comment]
AFAIK there's no 7.0 support in CUDA 8. You might try with cuda-toolkit 9.

**Comment by smurfy** [comment]
The master branch and all future versions of ethminer need cuda 9 toolkit to compile.
You **should** install it.

If you **want** you can remove the following line: ``https://github.com/ethereum-mining/ethminer/blob/master/libethash-cuda/CMakeLists.txt#L22`` and it compiles on cuda 8 too.
