### ISSUE TITLE
Mining through HTTP/HTTPS proxy

### ISSUE THREAD

**Issue by daiwei89** [ethereum-mining/ethminer#43]
Really appreciate the work done here. I have machines that can only access internet through an http/https proxy. It doesn't seem that this feature is available out of box, but I'm happy to implement this feature and make a pull request if someone can give me pointers on which file I should look at.

Thank you!

**Comment by chfast** [comment]
How do you used the proxy? Can't you just specify HTTP URL of your proxy instead of the mining pool address?

**Comment by daiwei89** [comment]
Thanks for the quick reply. The proxy server itself cannot run any command, so I have to rely on public pools through stratum. Thus I'm stuck on the following connection step:

```
10:40:02|ethminer  Connecting to stratum server eu1.ethermine.org:4444
```
