### ISSUE TITLE
Titan V Cuda error

### ISSUE THREAD

**Issue by rjhiles** [ethereum-mining/ethminer#435]
Miner connects but when trying to initialize it returns an error: 

cu  14:23:19|CUDA0     Using device: TITAN V  (Compute 7.0)
Cuda error in func 'set_constants' at line 151 : invalid device symbol.

**Comment by MariusVanDerWijden** [comment]
What cuda toolkit do you use?

**Comment by rjhiles** [comment]
The newest one

**Comment by xlvecle** [comment]
I get the same issue on Tesla V100

**Comment by dimitry12** [comment]
But works using OpenCL mode :D

**Comment by MariusVanDerWijden** [comment]
Do you use release 0.12?
The current master has Tesla/Titan support

**Comment by sleeepyjack** [comment]
Probably due to the new independent thread scheduling introduced with CUDA 9 on Volta. In a nutshell: They gave up the implicit warpsynchronous execution model. Adding __syncwarp() all over the place in your kernels may fix this problem.

**Comment by calclavia** [comment]
I get the same problem on Titan V

**Comment by DeadManWalkingTO** [comment]
Any news here?
