### ISSUE TITLE
,OpenCL Error: clEnqueueNDRangeKernel -4 CL_MEM_OBJECT_ALLOCATION_FAILURE

### ISSUE THREAD

**Issue by comarius** [ethereum-mining/ethminer#436]
Sources cloned on Dec 11 2017

ethminer -M -G pass but mining fails.

ethminer $1 -G -F http://eth-eu.dwarfpool.com:80/0x#################################
.....
 cl  15:16:38|cl-0      Build info: 
 cl  15:16:38|cl-0      Creating light cache buffer, size 37355072
 cl  15:16:38|cl-0      Creating DAG buffer, size 2390748544
 cl  15:16:38|cl-0      Loading kernels
 cl  15:16:38|cl-0      Writing light cache buffer
 cl  15:16:38|cl-0      Creating buffer for header.
 cl  15:16:38|cl-0      Creating mining buffer
 cl  15:16:38|cl-0      Generating DAG
  ✘  15:16:38|cl-0      Run: 0  ,OpenCL Error: clEnqueueNDRangeKernel -4

System info. Sources git at 

System:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

cmake.
-- CMake 3.5.1
-- Build Release / Linux
components
-- ETHASHCL         Build OpenCL components                  ON
-- ETHASHCUDA       Build CUDA components                    OFF
-- ETHSTRATUM       Build Stratum components                 ON
-- ETHDBUS          Build D-Bus components                   OFF
-- APICORE          Build API Server components              ON

clinfo

OpenCL 1.2 CUDA 9.0.194
GeForce GT 740M
Max work item sizes                             1024x1024x64
  Max work group size                             1024
  Preferred work group size multiple              32
  Warp size (NV)                                  32
Address bits                                    64, Little-Endian
  Global memory size                              2101542912 (1.957GiB)
  Error Correction support                        No
  Max memory allocation                           525385728 (501MiB)
NOTE:	your OpenCL library declares to support OpenCL 1.2,
		but it seems to support up to OpenCL 2.1 too.

 ethminer -M -G---------------------------------------------------
  ℹ  15:14:34|ethminer  Found suitable OpenCL device [ GeForce GT 740M ] with 2101542912  bytes of GPU memory
 cl  15:14:34|cl-0      No work. Pause for 3 s.
  m  15:14:34|ethminer  Waiting for work package...
  m  15:14:34|ethminer  Got work package: #164549fe
  m  15:14:34|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  15:14:35|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  15:14:35|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  15:14:36|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  15:14:36|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  15:14:37|cl-0      New work: header #164549fe… target 0000000040080100200400801002004008010020040080100200400801002004
 cl  15:14:37|cl-0      New seed #00000000…
cl  15:14:37|cl-0      Build info: 

 cl  15:14:37|cl-0      Creating light cache buffer, size 16776896
 cl  15:14:37|cl-0      Creating DAG buffer, size 1073739904
 cl  15:14:37|cl-0      Loading kernels
 cl  15:14:37|cl-0      Writing light cache buffer
 cl  15:14:37|cl-0      Creating buffer for header.
 cl  15:14:37|cl-0      Creating mining buffer
 cl  15:14:37|cl-0      Generating DAG
 cl  15:14:38|cl-0      DAG 0 %
  m  15:14:38|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  15:14:38|cl-0      DAG 6 %
 cl  15:14:38|cl-0      DAG 12 %
 cl  15:14:38|cl-0      DAG 18 %
  m  15:14:38|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  15:14:38|cl-0      DAG 25 %
 cl  15:14:38|cl-0      DAG 31 %
 cl  15:14:39|cl-0      DAG 37 %
  m  15:14:39|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  15:14:39|cl-0      DAG 43 %
 cl  15:14:39|cl-0      DAG 50 %
 cl  15:14:39|cl-0      DAG 56 %
  m  15:14:39|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  15:14:39|cl-0      DAG 62 %
 cl  15:14:39|cl-0      DAG 68 %
 cl  15:14:39|cl-0      DAG 75 %
  m  15:14:40|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  15:14:40|cl-0      DAG 81 %
 cl  15:14:40|cl-0      DAG 87 %
 cl  15:14:40|cl-0      DAG 93 %
 cl  15:14:40|cl-0      Switch time 6443 ms / 3444449 us
  m  15:14:40|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  15:14:41|ethminer  Speed   1.05 Mh/s    gpu/0  1.05  [A0+0:R0+0:F0] Time: 00:00

  m  15:14:37|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  15:14:37|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  15:14:37|cl-0      Platform: NVIDIA CUDA
 cl  15:14:37|cl-0      Device:   GeForce GT 740M  / OpenCL 1.2 CUDA

**Comment by MariusVanDerWijden** [comment]
Do you use the 4gb version of the GT 740m?

**Comment by comarius** [comment]
No is 2Gb, is up in the clinfo. 
I tweak the code and now I can run it for tutorial purposes.
Thank you.
