### ISSUE TITLE
CUDA error in func 'init' at line 245 : out of memory

### ISSUE THREAD

**Issue by vinid223** [ethereum-mining/ethminer#437]
I get the following error message 

cu  18:11:22|ethminer  Using grid size 8192 , block size 128
m  18:11:22|ethminer  Waiting for work package...
m  18:11:22|ethminer  Got work package: #a0b08556
ℹ  18:11:22|CUDA0     set work; seed: #c5f7a893, target:  #0000000225c1
ℹ  18:11:22|CUDA0     Initialising miner...
m  18:11:23|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
m  18:11:24|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
cu  18:11:24|CUDA0     Using device: GeForce GTX 780 Ti  (Compute 3.5)
m  18:11:24|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
CUDA error in func 'init' at line 245 : out of memory.
./start.sh: line 1: 10952 Segmentation fault      (core dumped) ./ethminer -U -F

For some reasons after I rebooted the computer I get this error. I tried to reinstall the NVIDIA Driver and rebooted again and I still get this error message. I am on Ubuntu 17.10 with the NVIDIA Driver 384.

It was running fine for more than 3 days in a row and even restarted some time and now I get this error and I don't really know how to fix that.

I also tried using OpenCL with the -G command instead to try it out and I get the error 
cl  18:08:18|cl-0      Loading kernels
cl  18:08:18|cl-0      Writing light cache buffer
cl  18:08:18|cl-0      Creating buffer for header.
cl  18:08:18|cl-0      Creating mining buffer
cl  18:08:18|cl-0      Generating DAG
✘  18:08:18|cl-0      clEnqueueNDRangeKernel ( -4 )
cl  18:08:18|cl-0      Switch time 4947 ms / 2242203 us
✘  18:08:18|cl-0      OpenCL Error: clEnqueueNDRangeKernel -4

I have a 780 TI 3Gb
Any Ideas?

**Comment by orkblutt** [comment]
Same here on 2 rigs:
I have to use --duda-devices x y z to see what's happening
i suspect dag size a bit bigger and cuda alloacting not only in gpu memory but in ram too...
I think my rigs needs more ram. can you confirm?

**Comment by orkblutt** [comment]
on 1070s x 6 rigs : i can't start the 6 card., only 5 at same time.

**Comment by orkblutt** [comment]
os: win10 64 with 4 Go of RAM

**Comment by vinid223** [comment]
I have 16 Go of ram so I don't think that is the problem

**Comment by michael-pesce** [comment]
If on Windows, make sure virtual memory is huge. I had to go to 24GB before I could get a 7 card rig to run. (I have 4GB of RAM)

**Comment by orkblutt** [comment]
Thank you Michael!! It's working back now by increasing virtual memory (swap)...
Have a good day!

**Comment by JamesTheAwesomeDude** [comment]
This precise error, same line number and everything is occurring on a GT 720M on Debian 9.2.1 with kernel 4.9.0-4 and the NVidia OpenCL drivers

[`clinfo`](http://ix.io/D3u)

**Comment by Algomorph** [comment]
I think I'm getting the same error.
The rig is on (currently) latest master 6fbf438, **Ubuntu** 16.04, 16GB RAM, GeForce 760 GTX, I get:
`CUDA error in func 'init' at line 247 : out of memory.`

**Comment by JamesTheAwesomeDude** [comment]
I've heard from a few places that you're just out of luck if you have a 2GB card due to DAG technicalities

**Comment by vinid223** [comment]
Like I said in the issue @JamesTheAwesomeDude I have a 3Gb GPU

**Comment by emclab** [comment]
I have same issue with 4GB GTX 1060 card. EthOS 1.2.9.

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!
