### ISSUE TITLE
Gtx 680 mh/s low hashrate

### ISSUE THREAD

**Issue by xB3RN5CHR0DRx** [ethereum-mining/ethminer#438]
Why in benchmark i have 15 mh/s but in real mining 6-7.

Win 7
GV-N680OC-4GD Gigabyte
Driver 388.59

**Comment by DeadManWalkingTO** [comment]
1. Try Update Drivers.
Download and install the latests.

2. Try use -U for CUDA devices.
That's my launch command:
`ethminer.exe -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

3. Try to change P2 State and Power managment mode.
You can use [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW).
For the best mining hashrate choose from sector "5 - Common":
    - CUDA - Force P2 State (Set to "Off")
    - Power managment mode (Set to "Prefer maximum performance")

4. Try Tweak Win10.
You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) (#695).

5. Try Optimize/Overclock GPUs. 
You can use [MSI Afterburner](https://www.msi.com/page/afterburner) for GPU OverClock/Optimize. 

6. Try use a WatchDog
You can use [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) (#735).

Please feedback.
Thank you!

**Comment by chfast** [comment]
Probably because you benchmark on epoch 0 (1 GB), but the current one has 2.5 GB DAG size.
