### ISSUE TITLE
segfault trying to mine with CUDA setting (-U)

### ISSUE THREAD

**Issue by OneOfMany07** [ethereum-mining/ethminer#440]
When I try to run I get an immediate segfault + coredump with very little info otherwise, even with -v 9.

I'm guessing I need to install a CUDA toolkit package to get -U (use CUDA not OpenCL) to work, but I haven't seen any mention of this requirement anywhere.  Including on the 2 older project versions.

Can we get a bit more info added to the README?  Or at least can someone tell me what more is needed beyond...

1. Install NVIDIA proprietary driver
2. Download, expand, then run ethminer app with appropriate flags (address of pool, my account, which API type, etc)

I mean I saw zero mention of pre-requisites to install, so I've been looking at random Google search results trying to guess.

Wouldn't surprise me if geth or another Ethereum client had to be working (and running?) in some manner too.  That is the next thing I'm doing now.  I'd already installed geth, and created an account...but hadn't let any sync happen yet.  Running ethminer while the sync is happening didn't work, but maybe it needs to finish?

**Comment by bmatthewshea** [comment]
I think this is because there isn't much to list?
You do not need geth or anything else running. Ethminer isn't just for Ethereum coin BTW.
AFAIK to run the release binary (not compile it) under Linux or Windows you should only need a current driver (which includes Cuda support/runtimes). I believe you may also need a vc++ redist for VS2015 if using windows, but this should be apparent by a given error if you don't already have it installed.

**Comment by OneOfMany07** [comment]
Thanks!

I've since redone my system with the CUDA 9.1 supported Ubuntu 16.04.3 LTS version instead.  I'd had the Ubuntu offered/supported 3rd party driver version of the NVIDIA proprietary driver installed, and seemed to be working (earlier had a bunch more heat from my system).

Even now I can't seem to get the driver included in the CUDA toolkit to install (when I reboot it still uses Nouveau, even after including the option use xconfig to change my settings step).  Earlier I didn't realize I'd need to boot into a non-GUI mode to allow the update/install.

This is my nvidia-smi output from this system, using what I believe was the same driver version and install method...

```
Sun Dec 17 11:36:10 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:09:00.0  On |                  N/A |
| 27%   33C    P8     7W / 151W |    593MiB /  8112MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1051      G   /usr/lib/xorg/Xorg                           293MiB |
|    0      1413      G   compiz                                       211MiB |
|    0      2287      G   ...-token=8D93557C58658C1672CE1705C966042C    86MiB |
+-----------------------------------------------------------------------------+
```
I didn't try the OpenCL method since I'd seen I'd need additional packages installed anyway, but will try that again later.

Sync'ing a client took longer than I'd hoped, and Parity never even finished after running for about 2 days.  Thankfully Geth did, and that is what I plan to do again today.  I'll try those other commands soon and report back.

**Comment by OneOfMany07** [comment]
Running fine this time.

```
  m  11:55:27|ethminer  Speed  25.37 Mh/s    gpu/0 25.37  [A3+0:R0+0:F0] Time: 00:01
  m  11:55:27|ethminer  Speed  25.37 Mh/s    gpu/0 25.37  [A3+0:R0+0:F0] Time: 00:01
  m  11:55:28|ethminer  Speed  25.37 Mh/s    gpu/0 25.37  [A3+0:R0+0:F0] Time: 00:01
  m  11:55:28|ethminer  Speed  25.37 Mh/s    gpu/0 25.37  [A3+0:R0+0:F0] Time: 00:01
  m  11:55:28|ethminer  Speed  25.28 Mh/s    gpu/0 25.28  [A3+0:R0+0:F0] Time: 00:01
  m  11:55:28|ethminer  Speed  25.28 Mh/s    gpu/0 25.28  [A3+0:R0+0:F0] Time: 00:01
```

My 2 biggest guesses for what fixed things are having the CUDA toolkit installed this time (earlier it died on the first step of installing a driver), and/or the "optional" libraries it had me install from these directions...

http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#optional-post

$ sudo apt-get install g++ freeglut3-dev build-essential libx11-dev \
    libxmu-dev libxi-dev libglu1-mesa libglu1-mesa-dev

**Comment by bmatthewshea** [comment]
@OneOfMany07 
Yeah, sorry, I think you need driver+toolkit. Been awhile since I installed it. You shouldn't need any -dev or build tools unless you are compiling it. (Which is what I did.)

tip - Don't use opencl with nvidia - there is a cpu-load bug (you may or may not notice). Cuda tends to work fine/better anyway w/ nv.

If you can document given steps on a clean ubuntu box, you may want to try for a pull on updating readme.. shouldn't be much, just install steps for driver and toolkit.
