### ISSUE TITLE
JSON_PARSE_ERROR when hitting --api-port

### ISSUE THREAD

**Issue by bradj** [ethereum-mining/ethminer#442]
I have tried several ways of getting data from the jsonrpc endpoint but every method returns the following error.

```
{"error":{"code":-32700,"message":"JSON_PARSE_ERROR: The JSON-Object is not JSON-Valid"},"id":null,"jsonrpc":"2.0"}
```

There aren't any docs or examples around accessing the rpc methods so I am not sure how to proceed.

Any help would be appreciated.

**Comment by smurfy** [comment]
See samples at #253
