### ISSUE TITLE
Cuda error in func 'set_constants' at line 151 : invalid device symbol.

### ISSUE THREAD

**Issue by vchrizz** [ethereum-mining/ethminer#445]
running Microsoft Windows [Version 10.0.16299.125]

```
D:\ethminer-0.12.0-Windows\bin>ethminer.exe -U -M
Using grid size 8192, block size 128

Benchmarking on platform: CUDA
Preparing DAG for block #0
Warming up...
  i  23:54:16|cudaminer0  set work; seed: #00000000, target: #000000000000
  i  23:54:16|cudaminer0  Initialising miner...
Using device: GeForce GT 635M (Compute 2.1)
Cuda error in func 'set_constants' at line 151 : invalid device symbol.

D:\ethminer-0.12.0-Windows\bin>
```
(same with v0.11.0)

```
D:\ethminer-0.12.0-Windows\bin>ethminer --list-devices

Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Intel(R) HD Graphics 4000
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 1468006400
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 367001600
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 512
[1] GeForce GT 635M
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 2147483648
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 536870912
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024


Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GT 635M
        Compute version: 2.1
        cudaDeviceProp::totalGlobalMem: 2147483648
```

**Comment by MariusVanDerWijden** [comment]
cudaDeviceProp::totalGlobalMem: 2147483648 you need at least 2.2 gb of Vram /Global mem to mine ethereum https://investoon.com/tools/dag_size

**Comment by vchrizz** [comment]
thanks, such a notification would be nice in output instead that error. :)
maybe a check on this on startup and warn user about this requirement..

**Comment by MariusVanDerWijden** [comment]
There used to be a warning, i don't know what happened to it

**Comment by LockeWatts** [comment]
This error is not associated with memory usage. 

`[0] [0] Tesla V100-SXM2-16GB
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 16936927232
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4234231808
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024`

`Using device: Tesla V100-SXM2-16GB  (Compute 7.0)
Cuda error in func 'set_constants' at line 151 : invalid device symbol.`

Something else is at work here.

**Comment by MariusVanDerWijden** [comment]
> I've seen this error on a card with over 16GB of ram. It should be able to fully process the DAG. I don't believe that's the whole issue.
Thats another problem. set_constants is the first cuda call in the code. If something in the code is wrong thats the first point to throw an error

**Comment by LockeWatts** [comment]
Is there a debug/logging mode somewhere in ethminer that I can use to look into this further? I'd like to be able to work on a solution, but coming into a new project cold is a slow process.

**Comment by MariusVanDerWijden** [comment]
I don't know if there's a debug mode, but you can use something like this https://developer.nvidia.com/nvidia-visual-profiler to debug

**Comment by MariusVanDerWijden** [comment]
I'm going to close this issue, @LockeWatts if your problem still exists, please open a new issue

**Comment by gnubyte** [comment]
https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exenetwork

Downloading the CUDA toolkit will run a system compatibility check when it first starts. It will also download any visual studio required dependencies when installed...


At the very least, you are checking to see if the "CUDA" library, which based on the error and the header of  ccminer's start, tells me you need the latest CUDA SDK.
