### ISSUE TITLE
.... Cuda error in func 'set_header' at line 178 : CUDA driver version is insufficient for CUDA runtime version. 

### ISSUE THREAD

**Issue by gexongexon** [ethereum-mining/ethminer#446]
Just started with a 2x RM 580 (opengl) and an Nvidia 1060 (CUDA)
 installed CUDA 9.1
installed OPENGL

I start with:
ethminer -X -S eu1.ethermine.org:4444 -O 716fb67367060bb5fdd173d80c4762acba533484.gio
But I get this: 

  ℹ  00:28:38|stratum   Received new job #fd48e272
Cuda error in func 'set_header' at line 178 : CUDA driver version is insufficient for CUDA runtime version.

My cuda was installed via sudo apt install cuda 9.1

any suggestion?

**Comment by MariusVanDerWijden** [comment]
Maybe you have to create a symlink to libcuda.so 
https://devtalk.nvidia.com/default/topic/617414/-solved-cuda-driver-version-is-insufficient-for-cuda-runtime-version-fedora-18-rpmfusion-driver/

**Comment by gexongexon** [comment]
Restarted from zero, reinstalled everything, it works
