### ISSUE TITLE
Issue with ethminer in debian 9 on esxi with radeon hd 7970

### ISSUE THREAD

**Issue by desultory** [ethereum-mining/ethminer#447]
I have a Debian 9 install on my esxi server and did a GPU passthrough and with some difficulty I managed to install the AMD drivers and opencl.  I can run ethminer with no errors but it just spams my terminal with messages saying it's mining at 0 MH/s.  I tried reinstalling the drivers and rebooting and I still get that error.  I know that mining in an esxi vm is possible because I've done it on windows but I want to do it in debian so I can manage it better and use fewer resources on my esxi server.  I ran it on the highest verbosity and get no errors, it just isn't hashing.

**Comment by MariusVanDerWijden** [comment]
What GPU/CUDA-Version/Kernel/KVM...?

**Comment by desultory** [comment]
It's a radeon hd 7970 so I don't think it uses cuda but I could be wrong and it's debian 9, 4.9.0-4-amd64, KVM isn't on the VM but my esxi server is running esxi 6.5 U1

**Comment by desultory** [comment]
this is the output of ethminer without my address
https://i.imgur.com/FUuqT4c.png
https://i.imgur.com/emBuWtr.png

It doesn't always throw those opencl errors but whenever it does, it continues running

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!

**Comment by AndreaLanfranchi** [comment]
Possibly related to #218
