### ISSUE TITLE
2xTitan Xp fluctuating/uneven Hashrates

### ISSUE THREAD

**Issue by tjr5269** [ethereum-mining/ethminer#448]
Hi, I'm testing a 2xTitan Xp setup on the 0.12.0 Windows release. 1 card is putting out 100Mh/s and the other is putting out 40Mh/s. Nothing else running on the computer.

What do you think the cause of this is? Also I'm extremely surprised that I'm even getting 40 Mh/s because from what I've seen on other sites is ~37... Sometimes Both cards output ~130Mh/s. I am using ethermine.org pool if that makes any difference. 

start params are: --farm-recheck 200 --cuda-block-size 256 --cuda-grid-size 32768 --cuda-parallel-hash 8 --cuda-streams 16 -U

**Comment by MariusVanDerWijden** [comment]
Is the slower card the one with the graphical output? There's a pretty significant performance penalty to running a visual interface on a card. Also maybe one card is thermal throttling/not getting enough power. Or its just an output error...

**Comment by tjr5269** [comment]
I don't think so the cards seem to switch back and forth on which one is faster or slower. What are the Typical Hashrates on a Titan Xp? Is a stable ~130Mh/s reasonable? Here is a screen shot of running for the first couple minutes. I didn't have time to grab a screenshot of the lower rates. I can do that later today. 
![titanxp](https://user-images.githubusercontent.com/7316142/34161414-9215cbc0-e49e-11e7-8b48-8ba38b43a7c5.png)

**Comment by tjr5269** [comment]
After running for a couple minutes here is whats going on:
![switching rates](https://user-images.githubusercontent.com/7316142/34215731-52921126-e574-11e7-9cf0-efd7d37496cf.png)

This then turns into:
![1 high 1 low](https://user-images.githubusercontent.com/7316142/34215740-58e00ee8-e574-11e7-9406-9a325deccbe6.png)

I'm not sure exactly why the rates are fluctuating. It could be that they are just reference Titan Xp's with no OC or thermal limit adjustments. 

This was tested on a compute workstation, I'm trying to determine if getting a Titan Xp is more viable than a 1080 Ti. I Believe the Xp is more efficient, more CUDA cores at same TDP than the 1080 Ti. The fluctuations are concerning if a card will drop to ~60 vs ~135, it's to inconsistent to predict ROI. Plus I think I could get close to 60 with 2 amd cards at less than half the price of a Xp.

**Comment by seymores** [comment]
@tjr5269 
Are you getting consistent 133 mhs if running on only one gpu?

**Comment by tjr5269** [comment]
So I have been running for 30 minutes, with a hashrate stable at 134.xx MH/s with --cuda-devices 0. It would seldomly hit 140-150. For reference this card has two displays hooked up to it.

**Comment by androidi** [comment]
You're probably calculating zeros some part of the time. I also got an insane "400 MH/s" out of a Vega 64 by increasing the OpenCL global work size multiplier to 262144. The only problem with this snake oil config was, that not all of those calculated bits were "real". ;(

According to Nvidia the Titan Xp's memory bandwidth is 547.7 GB/s, which means, your theoretical maximum hashrate is: 547.7 GB/s / 8 KB -> ~68.5 MH/s.

**Comment by RaviDevnani** [comment]
I don't mean to ask a simple question, but the numbers you are showing for the Titan Xp are great.  All of the other benchmarks out there don't seem to compare.  Is there something that I am missing? how can you get 140+ out of one Titan Xp... I am somewhat new to mining, but it seems everyone is missing a setting or two to achieve what you have.

**Comment by abelardojarab** [comment]
These guys RaviDevNani and the guy who opened this post truly dont know what they are talking about, but ignorance is daring right? Professional benchmarking shows 37.7~40 (overclock) mh/s but when someone like android quantitatively show them that they are wrong, still a guy like RaviDevnani comes and says 'seems everyone is missing a setting or two' plop

the daring empty-headed comments you have to hear these days :(

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!

**Comment by RaviDevnani** [comment]
I was trying to say in a nice way "I think you are wrong" to this thread that something is off... Along with getting whom ever the people that posted this, to back up what they had stated.  From everything that I read this is/was a very off statement and confusing from all of the benchmarks on numerous sites.  though I can go with "Plop" if that is the extent of your vocabulary  ;).  I was by no means reinforcing what they had posted.  Read in to it as you may, but i was also trying to bring clarity to a post that made no sense...  Oh, I didn't open this thread/post if you look at the message chain, I was questioning the validity, same as you (I guess).

**Comment by RaviDevnani** [comment]
My apologize if the prior post seems harsh, but I knew this was very off from all of the benchmarks and individuals testing these cards.  So I truly wanted to this thread debunked or a clear explanation of how they misread their information, so that people didn't get confused by this post.  So please don't think in any manner that I believed this post, started this post, with numerous sites, videos, etc... that displayed the actual hash rate of these cards.

**Comment by webprophet** [comment]
I run 3 Titan XPs on Win1709, ethminer, went to 14rc9 a day ago.  No over clocking is 37Mh/s each.  +107 core +764 mem 70% power runs 42.60ish.  runs all day long (except when gaming ;).  Hash rates haven't really changed in the last 3 months on various RC and Dev builds.  
--farm-recheck 2000 -RH --cuda -S (and I know I need to change -s to -p, just gotta take the time. :0)
