### ISSUE TITLE
Optimal Settings for GTX 1080 + i7 4790K Setup

### ISSUE THREAD

**Issue by firepro20** [ethereum-mining/ethminer#452]
I am new to mining. Before opening this ticket I did some research on ethminer and I got it up and running no problem.

I also saw the ticket for using -U instead of -G although I would like to understand whats the difference and what the parameters represent. 

My end goal for this ticket is for an explanation of the parameters accepted by ethminer so that I can maximize / optimise my mining rig.

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --farm-recheck 200 -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O (eth wallet).(miner)

where eth wallet is my Etherium receiving eWallet address and
          miner is my workstation Netbios name?

Thanks!

**Comment by smurfy** [comment]
``--help``  gives you more info.

-U is for CUDA, which is for Nvidia Cards
-G is for OpenCL, which is for AMD Cards. Nvidia supports OpenCL too, but is slower with it.

``(miner)``  can be ommitted, but its usefull if you have multiple miners running and want to differentiate between them in the pool info site.

**Comment by firepro20** [comment]
Great thanks for this information. I'm currently getting 21 mh/s on average, with default settings on both ethminer and no overclocking done on the GPU. 

Is it recommended to point the (eth wallet) to a Jaxx ethereum address? I have read that payouts mostly happen on a weekly basis, or maybe I am understanding it incorrectly. Please help!

**Comment by H05ted** [comment]
Hi, in script is my eth wallet.  And what about payouts? I didnt see
any troubles, I recive, transfer without problems. What help do you
need ? You want me to help you with set up and help you to manage your
rigs or smth else?

2017-12-21 13:29 GMT+02:00, firepro20 <notifications@github.com>:

**Comment by smurfy** [comment]
> Is it recommended to point the (eth wallet) to a Jaxx ethereum address? I have read that payouts mostly happen on a weekly basis, or maybe I am understanding it incorrectly. Please help!

Point it to YOUR etherueum address, it does not matter which wallet you use. (except it needs to be a real one, no fake wallet app). 

Regarding payouts that depends on your pool. But since you posted ethermine in your commandline, yes ethermine now has a force payout every week, regardless the limit you set.

With 21 mh/s (even if you overclock and are at 26)  it wont be much. but hey better than nothing :)

**Comment by firepro20** [comment]
Thanks a lot for your time and help! You can close the ticket.

**Comment by firepro20** [comment]
Good afternoon,

Kindly please provide an invoice which shows the total amount paid for the item such as a bank transaction

Thanks

Sheldon



From: Daniel Zammit [mailto:firepro20@gmail.com]
Sent: 15 February 2018 13:25
To: 1739599850-4ppt.ewsg.vzpv.ztwc@property.booking.com; 4P Customer Care <customercare@go.com.mt>; Aaron Galea <agalea80@gmail.com>; Abigail Galea <abigailg@unpsd.com>; academy@betssongroup.com; Adrian Agius <sales02@atoz.com.mt>; Adrian Agius <aagius@atoz.com.mt>; Adrian Gatt <adrian@ceek.com.mt>; Alfredo Agius <it@thepalacemalta.com>; alfredo.agius@axholdings.com.mt; Andre Azzopardi <andreazzopardi@hotmail.com>; andrea cassar <ancas94@gmail.com>; Andrea Sultana <andrea.sultana@6pmplc.com>; Andrew Grech (via Google Docs) <andrewgrech3@gmail.com>; android.support@ubisoft.com; Anthony Bugeja <info@gozo-choice.com>; Antionette Djinovic <djinovic.antionette@gmail.com>; Anton Vella <antoniusvella1@gmail.com>; ATOM I.T Technics <info@atomonline.com>; AtoZ Electronics - Adrian <sales02@compleet-is.com>; atoz@compleet-is.com; Attard-Frontdesk <attard-frontdesk@atoz.com.mt>; Book Depository <cancelorder@support.bookdepository.com>; bugant@vol.net.mt; bugejajoe@vol.net.mt; Bulky Invoice <bulkyinvoice@maltapost.com>; careers.malta@hilton.com; carmel galea <lucida@melita.com>; ccsales@melitaltd.com; Cellular Tech - Sales <sales@cellulartechmalta.com>; chr2che@yahoo.com; Christian Chetcuti <chr2che@gmail.com>; cinumerable@godaddy.com; clientsvy@vueling.com; Clint Francica - Scan <clint.francica@scanmalta.com>; Clint Galea <clintgalea@live.com>; cncfallout@gmail.com; Colin <attcol@gmail.com>; competitions2017@kitguru.net; contact@rovio.com; contactus@melitaltd.com; cs-reply@amazon.fr; cs-reply@amazon.fr; cs-reply@amazon.fr; cs-reply@amazon.fr; cs-reply@amazon.fr; customercare@squarespace.com; Damcar Properties <info@damcarproperties.com>; Daniel Galea St John <dan270194@gmail.com>; Daniel Mountford <info@medsailmalta.com>; Daniel Saliba <info@abprojects.com.mt>; Daniel Saliba <dsaliba95@gmail.com>; Daniel Zammit <dzamm20@gmail.com>; Daniel Zammit <firepro20@gmail.com>; daniel.zammit.12@um.edu.mt; daniel.zammit@axhotelsmalta.com; daniel20 <daniel20@searchmalta.com>; daniel20@searchmail.com; dannierxiao@hotmail.co.uk; David Borg Hedley <dbh@fexserv.com>; David Busuttil <david@qfi.re>; dejanz@maltanet.net; DEMCifilter SA <sales@demcifilter.com>; Doreen Zammit <Doreen.Zammit@hilton.com>; Doris Sultana <info@pergolafarmhousesgozo.com>; doris.baldacchino@mcast.edu.mt; drew ging <andrewbkr07@live.co.uk>; dtag-dev-sec/tpotce <reply@reply.github.com>; dtag-dev-sec/tpotce <reply@reply.github.com>; dtag-dev-sec/tpotce <reply@reply.github.com>; dtag-dev-sec/tpotce <reply@reply.github.com>; dzam0032@um.edu.mt; dzamm20@gmial.com; editorial@di-ve.com; Edmund Tabone <etabone@pbs.com.mt>; Edward Adam via Gumtree Mail <Buyer.1w88mtzt77z6x@reply.gumtree.com>; Elena Farrugia <elenaf194@gmail.com>; Emanuel Tabone <dove1@onvol.net>; english@amazon.fr; EPCMR Malta <epcmr.malta@gmail.com>; etc@gov.mt; ethereum-mining/ethminer <reply@reply.github.com>; eu-giveaway@msi.com; evarist bartolo <evaristbartolo@hotmail.com>; Evelyn Chetcuti <evelyn.chetcuti@um.edu.mt>; Executive Response (ECR) <ExecutiveResponse@t-mobile.com>; Fabianne Fenech <Fabianne.Fenech@melitaltd.com>; fabianne.ruggier@um.edu.mt; FeiTong - Amazon Marketplace <9k0cnj3q4tdf819@marketplace.amazon.de>; Fiorella - Scan <fiorella@scanmalta.com>; Football Tournaments <sportstournaments@mmsa.org.mt>; Gabriella Galea - Scan <gabriella@scanmalta.com>; gamescom@visitor.koelnmesse.de; Gary Sammut <gsammut@iescomputers.com>; george.mercieca@axhotelsmalta.com; Ghandixinghid <ghandixinghid@tvm.com.mt>; gianlaf@hotmail.com; Godwin Caruana <godwin.caruana@gmail.com>; gordon@factmalta.com; gozovillas@mail.com; Graziella Camilleri - Scan <gcamilleri@scanmalta.com>; Grech Luke <lgrech25@hotmail.com>; Grech Luke <lgrech1993@gmail.com>; GSM Arena <info@gsmarena.com>; gtagozo@onvol.net; Hackers Malta <info@hackersmalta.com>; Hannah Moore <appleltd_store087@hotmail.com>; hannah_zammit188@hotmail.com; hannah.h.zammit.15@um.edu.mt; hannah.h.zammit@um.edu.mt; help@e-shop.koelnmesse.de; help@eamobile.com; helpdesk@kinguin.net; hr.student@axhotelsmalta.com; hr.student@thepalacemalta.com; hr@aquarium.com.mt; hr@bingoroyale.com.mt; hr@corinthia.com; hr@seabankhotel.com; Humble Bundle <contact@humblebundle.com>; icc@mcast.edu.mt; ict@mcast.edu.mt; ict@um.edu.mt; iklinshowroom@scanmalta.com; ils.malta@ef.com; inbox@google.com; ind.emp.relations@gov.mt; Info - Gozo Village Holidays <info@gozovillageholidays.com>; info@audiomalta.com; info@comprod-computer-centre.com; info@ctscomputersmalta.com; info@destinationmalta.com; info@digiline.com.mt; info@domaingroup.com.mt; info@espritmalta.com; info@expansys.com.mt; info@forestals.com; info@giftvouchershop.com.mt; info@gozoescape.com; info@klikk.com.mt; info@lhcmalta.com; MaltaPost Info <info@maltapost.com>; info@matthewxuereb.com; info@melitaplc.com; info@mindfactory.de; info@mygov.mt; info@pavi.com.mt; info@printshop.com.mt; info@roccat.org; info@scotts.com.mt; info@soundmachine.com.mt; info@supergoldjewellers.com; info@targettechgroup.com; info@thenotebookcentre.com.mt; info@ultramalta.com; info@unpsd.com; infomalta@hsbc.com; Innovatech <info@innovatechmalta.com>; international@ksu.org.mt; italy.support@hihonor.com; ivan curmi <ivancurmi@hotmail.com>; Jackie Gauci <jackie.gauci@ixaris.com>; Janet Spiteri Staines <jsstaines@kitchenconcepts.com.mt>; Janice Zahra <jzahra@intercomp.com.mt>; Jason Galea <jasgalea@gmail.com>; jc-support.esims@um.edu.mt; jcutajar@iescomputers.com; Jean Gauci <gaucijean@gmail.com>; Jean Paul Formosa <jpformosa12@gmail.com>; Jean-Pierre Agius <jeanpierreagius@gmail.com>; Jeffrey Powell <jeffpowell91@gmail.com>; JL Export Oxford Street <export.oxford.street@johnlewis.co.uk>; jobs@ixaris.com; jobs@prixgroup.eu; jobs@scanmalta.com; joe bezzina <bezzina_j@yahoo.com>; Joe Mizzi <joemizzi.mlp@gmail.com>; John Abela <john.abela@um.edu.mt>; Jose Ashford <yestocredit12@yahoo.com>; Joseph Lanzon <info@bitsandbytesmalta.com>; josette@prestigecabsmalta.com; jp_farrugia@yahoo.com; jp_farrugiafb@yahoo.com; jubri abby <jubriabby@gmail.com>; Julian Mifsud <jmif0048@gmail.com>; justinator10@hotmail.com; Karolina Restaurant <info@karolinarestaurant.com>; Katriel Coppola - Scan <katriel@scanmalta.com>; keb@teknogods.com; Keith Mock <Kthmock@gmail.com>; Kill Ping <support+id58342@killping.zendesk.com>; Kinguin Socialmedia <socialmedia@kinguin.net>; KLIKK Sales Team <sales@klikk.com.mt>; Klikk Support Team <support@klikk.com.mt>; kristofer_1510@hotmail.com; Leanne Borg <leanne.borg1@gmail.com>; Lesnich Vassallo <lesnichvassallo@gmail.com>; Linas Mazonis <henkas@gmail.com>; lorry sant <eletronicbestdeals@gmail.com>; Luzzu Operations <luzzuoperations@axhotelsmalta.com>; marbor29@go.net.mt; Marcomp <sales@marcompmalta.com>; Maria Mifsud <mmifsud_36@hotmail.com>; maria pollacco <maria.pollacco@gmail.com>; Mariah Zammit <mariahbethany15@gmail.com>; Mario Debattista <mariodeb39@gmail.com>; Mario Dimech <mario.dimech@gmail.com>; Mario Mizzi <stylecomputerservices@gmail.com>; Marisa Portelli - ScanMalta <mportelli@scanmalta.com>; MARK ANTHONY CARUANA <mark.caruana@um.edu.mt>; Mark Mifsud <msmifsud@gmail.com>; Mark Sciberras <makkuxibi@gmail.com>; Mark Soundmachine <mark@soundmachine.com.mt>; marketing@smart.com.mt; Marlon Bugeja <mbugeja1977@gmail.com>; matlene.kind@mcast.edu.mt; Matt Blagden <matt@mattblagden.com>; Matthew Xuereb <matthew.xuereb@um.edu.mt>; Matthew Xuereb <bulbousbow@gmail.com>; Max F <mzmaxam@gmail.com>; Maxine Grima <mgrima@scanmalta.com>; Maxine Grima - SCAN Malta <corporate@scanmalta.com>; Med Books <medbooksmt@gmail.com>; media@roccat.org; Mifsud Grace at MITA <grace.mifsud@gov.mt>; mimmo@vol.net.mt; mxue0001 <mxue0001@gmail.com>; mxue0001@yahoo.com; nathaniel.massa@um.edu.mt; Nico Tanti <nico.tanti8@gmail.com>; Nigel Grech <secgen@ictsamalta.org>; Noeleen Camilleri <noeleen.camilleri@gmail.com>; nyemidnightexpress@gmail.com; offers@atoz.com.mt; operations@lhcmalta.com; osTicket/osTicket <reply@reply.github.com>; osTicket/osTicket <reply@reply.github.com>; osTicket/osTicket <reply@reply.github.com>; osTicket/osTicket <reply@reply.github.com>; palace.reservations@axhotelsmalta.com; PC-MALTA <info@pc-malta.com>; PCWise Malta <info@pcwisemalta.com>; Peter Sultana <bestmobileprices@yahoo.com>; Petra Domogalla <P.Domogalla@computeruniverse.net>; phly top <top5phly@gmail.com>; phoenixzammit <phoenixzammit@hotmail.co.uk>; PopArtUK - Amazon Marketplace <pm5jhcc0mttg7x8@marketplace.amazon.co.uk>; portal-feedback@hq.acm.org; Postfach Info <info@computeruniverse.net>; Prestigecabs Malta <info@prestigecabsmalta.com>; Priscilla Civelli <priscillacivelli@googlemail.com>; project@honeynet.org; Pueblo Ingles - Diverbo Coordinators <volunteers@diverbo.com>; Pulptech Customer Care <customercare@pulptechmalta.com>; queries@scan.co.uk; Ramon Mallia <rmallia@intercomp.com.mt>; razzett@gozoservices.com; Reachus@dell.com; reaver@teknogods.com; rentals@gozohomes.com; rentals@gozorentals.com; repairs@i-phonemalta.com; reservas@hotelesglobales.com; Reservations @ RamlaBayResort <reservations@ramlabayresort.com>; reservations.palace@axhotelsmalta.com; reservations@palazzinonina.com; Robert Bugeja <r.b.ufix@gmail.com>; Robert Delia <accountslessons@yahoo.com>; Robert Gonzi <robert@ascentsoftware.eu>; rose.m.azzopardi@um.edu.mt; ryan.leverington@ubercrate.intercom-mail.com; sales@atoz.com.mt; sales@iescomputers.com; sales@myshoppingcart.com.mt; sales@roccat.org; samdimech@hotmail.com; Samsung Customer Support <sei.contactus@samsung.com>; sbstore010 <sbstore010@gmail.com>; Scan Computers <sales@scanmalta.com>; Scan Computers <esales@scanmalta.com>; SCAN Servicing Support <support@scanmalta.com>; Sean Galea <galeasean@gmail.com>; sebastian rausi <sebrausi@hotmail.com>; sebastian rausi <sebrausi94@gmail.com>; Sebastian Rausi <srausi@rausi.com.mt>; service@visitor.koelnmesse.de; Sharon_Mary <us_sales@dell.com>; silvana zammit <docsil3@gmail.com>; Simark <info@simarksupplies.com>; srau0001@um.edu.mt; Stephanie Abood <stephanie.abood@um.edu.mt>; Steve Hyzler <steveh@kitchenconcepts.com.mt>; stipends <stipends@um.edu.mt>; strukturag/libde265 <reply@reply.github.com>; Support <info@homido.com>; support-uk@vmall.eu; support@hellogames.co.uk; support@ianker.com; support@iescomputers.com; support@pulptechmalta.com; support@twitch.tv; support@z2.com; talemt@brendacamilleri.com; talent@brendacamilleri.com; tanatu@waldonet.net.mt; tarcizju.zarb@ilearn.edu.mt; TheAP Gamer <theapgamer@gmail.com>; timothy@candcdiscovery.com; Tiziana Grech <Tiziana.Grech@melitaltd.com>; togi@ksu.org.mt; top5@warthunder.com; Torri Kercem <torrikercem@borvier.com>; Trevor@lhcmalta.com; Trion Worlds Customer Support <trionworld1@mailwc.custhelp.com>; Trustpilot Compliance <compliance@trustpilot.com>; Turtle Beach Support Team <support@turtlebeach.com>; ugoffice@rgu.ac.uk; uniquegozofarmhouses@gmail.com; unity-summer2012@googlegroups.com; vacancies@suncresthotel.com; vacancy vacancy <vacancy@klikk.com.mt>; vmall UK <vmall-uk+id54699@vmall.zendesk.com>; w.rizzo@met.com; w.rizzo@met.com.mt; Web Check-in Agent <webcheckin.helpdesk@airmalta.com>; web-team@acm.org; wekalist@list.waikato.ac.nz; World of Tanks <wot@mail-eu.wargaming.net>; YamGaming@hotmail.com; Zammit Joseph I at MDH-Health <joseph.i.zammit@gov.mt>; ZRGaming <zammitrausi@gmail.com>
Subject: Digital Games 5% Discount - Only at Kinguin!


I recently used Kinguin - they have some of the lowest prices for games! They also gave me a special offer to share with my friends. I'm treating you to an exclusive 5% discount on your first order. Enjoy!

Get a 5% discount at Kinguin<http://t.mention-me.email/lnk/AEMAScuf0IQAAU1sQ34AAF--V74AAO87QCkAAAAAAAEZ0gBahKTLXr22Iz34Qoqzc_I5lhFJ9QABD9s/1/bO4Z9OMZCQh0dygt_2lLzQ/aHR0cHM6Ly9raW5ndWluLm1lbnRpb24tbWUuY29tL20vZmUvbmwzY2MtZGFuaWVsLXphbW1pdD91dG1fY2FtcGFpZ249cmVmZXJyZXItZm9yd2FyZC1lbWFpbCZ1dG1fbWVkaXVtPWVtYWlsJnV0bV9zb3VyY2U9Y3VzdG9tZXJzJnV0bV9jb250ZW50PWN0YQ>


--
Thanks and Regards,

Daniel Zammit

**Comment by JonasHodges** [comment]
smurfy 

is it safe to overclock the memory to +1000,  i accidentally bought 6 GPU and made a rig to generate some profit. but later i figured its very low performance card. not like 1070Ti.  so dont know what to do. 

after tweaking your hint, i set TDP to 56 and Memory to 56. i get the ETH 26.3Mh/s but as afraid that if it will fry the cards? i read somewhere the fans and cooling system only concerns the GPU chip. and all sensors are watching the GPU temp. the memory is not being monitor. so perhaps we will burn the GPU. because 1000 is maximum for this. please guide me what to do. and also if there any other algorithms best for GTX1080 windforce cards. would you please refer me there? i am bit disappointed after this huge investment the profit is not as expected. 

thank you very much dear sir.

**Comment by JonasHodges** [comment]
is it safe to overclock the memory to +1000, i accidentally bought 6 GPU and made a rig to generate some profit. but later i figured its very low performance card. not like 1070Ti. so dont know what to do.

after reading some internet hint, i set TDP to 56 and Memory to +1000. i get the ETH 26.3Mh/s but as afraid that if it will fry the cards? i read somewhere the fans and cooling system only concerns the GPU chip. and all sensors are watching the GPU temp. the memory is not being monitor. so perhaps we will burn the GPU. because 1000 is maximum for this. please guide me what to do. and also if there any other algorithms best for GTX1080 windforce cards. would you please refer me there? i am bit disappointed after this huge investment the profit is not as expected.

thank you very much dear sir.
