### ISSUE TITLE
Mining stops after TDR

### ISSUE THREAD

**Issue by sxcurtin** [ethereum-mining/ethminer#453]
My machine appears to have hit TDR, (https://docs.microsoft.com/en-us/windows-hardware/drivers/display/timeout-detection-and-recovery) and the PC recovered, but ethminer continued to do work on the GPU but stopped mining correctly. When I killed the window it dropped 10*c, that's how I know it was still doing something.

**Comment by paucoma** [comment]
This may appear if you have problems with your graphics drivers, or perhaps even a problem with the GPU itself. Have you got your GPUs overclocked? If that is the case, perhaps its too much.

**Comment by sxcurtin** [comment]
Over clocked, but not by much. No artifacts, or other noticeable issues. I've pulled down the OC for now to see if it helps. i only encountered the issue once, but ethminer can surely be made to recover gracefully from it.

**Comment by paucoma** [comment]
you wouldn't happen to have captured the debug messages that etherminer gave? 
e.g. `error on line ...` 
Are you running the ...dbg version for windows ? if not, then do so as it will output more debug messages to help to see what is actually happening. 
Also there are a couple "work arounds" which monitor you mining and restart the mining incase of x,y,z you could try such as https://github.com/derubm/Ethminer_Watchdog or https://github.com/orkblutt/MinerLamp .
I personally have not tried any of these.

**Comment by sxcurtin** [comment]
CUDA error in func 'ethash_cuda_miner::search' at line 365 : unspecified launch failure.

Sure I can setup another component to monitor or restart the process, but I think ethminer could be improved by handling this error more gracefully. ie. restarting mining

**Comment by paucoma** [comment]
Yes, of course ethminer can be improved, and your feedback helps to improve ethminer. 
Untill then you can setup the proposed work-arounds to attempt to achieve your objectives or you could even help the project by having a look at the code and try to improve it yourself. 

Could you please specify the following:
Ethminer version / build ? e.g. ethminer-dbg-0.12.0-Windows
Operating System : Win 10 / 7 ? build number
GPU Cards installed ? 
Driver version for these GPUs ?

Thanks

**Comment by sxcurtin** [comment]
"Untill then you can setup the proposed work-arounds to attempt to achieve your objectives"
-- Already in place, non-issue

"you could even help the project by having a look at the code and try to improve it yourself"
-- Attempting to do this. But simply building the project is difficult as documentation is quite lacking, but I'll get there

EthMiner 0.11
Windows 10 LTSB
GTX 1070
driver v388.31
Shout away if you want anymore info.

**Comment by DeadManWalkingTO** [comment]
After #757 (added --exit parameter to exit whenever an error occurred) you can use a watchdog.

Here is my [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) Windows7/8/10 [32/64] & Linux (Any Dist/Any Ver/Any Arch) (#735).

Check and feedback please.
Thank you!
