### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_70'

### ISSUE THREAD

**Issue by phalexo** [ethereum-mining/ethminer#454]
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.Release.cmake:222 (message):
  Error generating
  /home/miner/ethminer/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o

Compute 70 is for newer architecture, and I don't have those. Makefile should not be generating stuff that is not compatible with my GPUs, i.e. older Titax X.

**Comment by MariusVanDerWijden** [comment]
just update cuda to cuda 9.0...
We have to support ever architecture, you can easily modify the makefile yourself.
It's here. libethash-cuda/CMakeLists.txt

**Comment by phalexo** [comment]
Nvidia does not offer that version for Ubuntu 14.04 LTS.

**Comment by smurfy** [comment]
as @MariusVanDerWijden mentioned,  just edit ``libethash-cuda/CMakeLists.txt`` and remove the ``compute_70`` line.

You also can use a prebuild version from here: https://github.com/ethereum-mining/ethminer/releases

**Comment by ilanbiala** [comment]
The file doesn't exist for me. Only these files exist:
```shell
$ ls libethash-cuda/
CMakeFiles          Makefile            cmake_install.cmake
```

**Comment by cosmicog** [comment]
>The file doesn't exist for me. Only these files exist:
>```
>$ ls libethash-cuda/
>CMakeFiles          Makefile            cmake_install.cmake
>```
Try this command:
```
$ git pull origin master
```
