### ISSUE TITLE
RPC endpoint always resets connection

### ISSUE THREAD

**Issue by skaldesh** [ethereum-mining/ethminer#459]
I wanted to query the RPC endpoint of my miner. 
I got it to work using golang and a tcp socket, however, after the first request -> response cycle, the api endpoint always resets the connection, forcing me to open the socket once again before requesting the next statistics

Here is my sample code for the socket:
```
conn, err := net.Dial("tcp", "192.168.2.102:4321")
if err != nil {
  panic(err)
}
defer conn.Close()
conn.Write([]byte(`{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}`))
conn.Write([]byte("\r\n"))

log.Printf("Send to socket...")
buff := make([]byte, 2048)
n, err := conn.Read(buff)
log.Printf("Receive: %s", buff[:n])

time.Sleep(time.Second)

conn.Write([]byte(`{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}`))
conn.Write([]byte("\r\n"))

log.Printf("Send to socket...")

n, err = conn.Read(buff)
if err != nil {
  // THIS ONE ALWAYS PANICS
  panic(err)
}
log.Printf("Receive: %d bytes; %s", n, buff[:n])
```

Error message I get is:
panic: read tcp 192.168.2.110:41719->192.168.2.102:4321: read: connection reset by peer

**Comment by smurfy** [comment]
yes, thats JSON-RPC, connection gets terminated after each method call. 
Thats not a bug, thats a feature :)
