### ISSUE TITLE
-S and -U flags not recognized

### ISSUE THREAD

**Issue by chronakazi** [ethereum-mining/ethminer#46]
I got ethminer built and working fine but couldn't get any shares accepted through pools. I decided to rebuild my dag file with geth. After going back and retrying ethminer with -S it says invalid argument and the URL of the pool. I definitely messed something up somehow. Why would the flags all of a sudden not work the same?

**Comment by chronakazi** [comment]
Restored Nvidia drivers, that fixed the -U flag but the stratum flag -S still throws an invalid argument. I rebuild from source and no luck. Any ideas on the -S? thanks

**Comment by chronakazi** [comment]
Ive tried wiping the directory and redownloading the .exe and i rebuilt ethimer from source and the -S flag still wont work no matter what i put after -S it says invalid argument. Are there any dependencies related to that -S flag that i could try to rebuild? im at a loss.

**Comment by chfast** [comment]
Can you send full argument list?

**Comment by chronakazi** [comment]
ethminer.exe --farm-recheck 200 -G -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -O <public address>.<worker>

**Comment by chronakazi** [comment]
left out address.workername after -O

**Comment by chronakazi** [comment]
aaaaand now its working, i seriously have no idea what was going on. Thanks so much for your help.
