### ISSUE TITLE
Compiling on macOs failed

### ISSUE THREAD

**Issue by s1rleblanc** [ethereum-mining/ethminer#460]
i try to compile to my environment of macOS but when y run "cmake --build ." at the 60% this crash with this message:

[ 63%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
nvcc fatal   : The version ('90000') of the host compiler ('Apple clang') is not supported
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.Release.cmake:219 (message):
  Error generating
  /Developer/ethminer/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o

gmake[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:65: libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:319: libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
gmake: *** [Makefile:152: all] Error 2

for what i see is version problems so.. can help me, please ?

**Comment by tomekmarchi** [comment]
Second this can't seem to get around it

**Comment by androidi** [comment]
https://github.com/pytorch/pytorch/issues/3047#issuecomment-335455420

**Comment by s1rleblanc** [comment]
i don't want to change!.. is to much work.. cus! the compile new lenguaje is on version 9

**Comment by DeadManWalkingTO** [comment]
Try to compile the latest version and feedback please.
Thank you!
