### ISSUE TITLE
ethminer throwing away perfectly valid results

### ISSUE THREAD

**Issue by androidi** [ethereum-mining/ethminer#461]
https://github.com/ethereum-mining/ethminer/blob/6f28ec56a8075b69406931bfea2a1262958ef019/libethash-cl/CLMiner.cpp#L199

Why does ethminer throw away perfectly good results? :DD

If one puts e.g. the following here:
cnote << "Number of results:" << results[0];
one can see, that sometimes the number of results is 2, 3 or even 4.

An easy way to test this is to set the aforementioned debug output, and increasing global work size e.g.: --cl-global-work 65536

Lo and behold! ethminer does only submit the first result.

I've tried to fix this a couple of days, but it's not that easy to fix, since something on upper level is blocking the submitting of several results one after another - that is, until receiving end responds (or something..). Farm-recheck time also has some seriously mysterious effect on this behaviour..

As a quick test:
- initialise several nonce-variables (CLMiner.cpp line 196)
- loop through to store all result nonces: "for (ires = 0; ires < results[0]; ..." and so on
- loop to submit all responses (CLMiner.cpp, line 215)
  -> set a chrono sleep 100 ms (or 200 ms) in result loop
- connect to Ropsten pool: pool.ropsten.ethereum.org with global work size 65536

I got ethminer to submit sometimes two results, but probably the only real way to handle this would be to construct a result-nonce buffer/stack/queue/what-ever, which is then checked and processed "somewhere".

This line:
https://github.com/ethereum-mining/ethminer/blob/master/libethash-cl/CLMiner.cpp#L215
leads here:
https://github.com/ethereum-mining/ethminer/blob/master/libethash-cl/CLMiner.cpp#L106

and somewhere beyond that, in the farm or JSON-client object/class, lies the problem...

If I understood correctly, the logic in workpackage loop (lines 138-227 in CLMiner.cpp) might also only allow to submit one result per round? Or one submit per farm-recheck?

Also an interesting one is...
a mutex in Stratum client v2:
https://github.com/ethereum-mining/ethminer/blob/8aa7abb59d0b867d12fef207b8af856748e68f10/libstratum/EthStratumClientV2.cpp#L459

Might that mutex block calls to submit(..) when one call is running?

I know Ropsten testpool does not use Stratum 2, so this whole bug might lie in several different places, depending on chosen client type...?

Btw. ethminer also calls EthashAux::eval like 3 times "just in case" when submitting the result. :D

**Comment by ddobreff** [comment]
Are you pointing a bug or a solution?

**Comment by androidi** [comment]
Mainly pointing a bug, since it is a bug. I just haven't found a solution to it yet, since the codebase is a bit messy with all it's boost threads, different connection methods and mining methods. But it is there "somewhere".

Here's an image of what happens with some debug extras:
![108940de-14b4-45b6-9481-0edd6acb1bee](https://user-images.githubusercontent.com/3873230/34426351-0df719dc-ec3e-11e7-9101-f23468c355d0.png)

The DAG was generated in single step since I used --cl-global-work 65536, if I recall correctly. Target is Ropsten test network, so this bug pops up there quite easily.

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!

**Comment by AndreaLanfranchi** [comment]
All issues removed in 0.14.rc and beyond.
