### ISSUE TITLE
Hashrate randomly increases after some time

### ISSUE THREAD

**Issue by heikomat** [ethereum-mining/ethminer#463]
Hello,

I noticed, that my Hashrate increases after 10 to 30 hours of uninterrupted mining. I start with 11.5 to 12 MH/s, and then after a while it suddenly jumps to 13 to 13.5 MH/s

When i stop and instantly restart the ethminer, it's back to the lower hashrate. Why is this?

My setup is as follows:
- GPU: GTX 780 from Gigabyte
   gpu + 270 MHz
   memory + 380 MHz
- OS: Ubuntu 17.10
- NVidia Driver: 384.90
- Ethminer:
  ```
  ./ethminer \
  --farm-recheck 2000 \
  --report-hashrate \
  --verbosity 1 \
  --opencl \
  --stratum eu1.ethermine.org:4444 \
  -FS us1.ethermine.org:4444 \
  --userpass 0x572292428767D8906Ec5C3c0fa237C1921f24e53.PCHome_ubuntu
  ```
 CUDA doesn't seem to be faster for me

**Comment by androidi** [comment]
Does the hashrate stay at 13-13.5 MH/s after the jump? If not, then it's just caused by timing vs. division artefact. Your machine however reports fairly stable 11.6 MH/s to the pool:
https://ethermine.org/miners/572292428767D8906Ec5C3c0fa237C1921f24e53

**Comment by heikomat** [comment]
@androidi i haven't had the miner running for long enough for the effect to happen in the last two days. I have seen this happen three or four times now. When the hashrate jumps up, it stays up until i restart ethminer.

I do have a screenshot from the first time this happenend:
<img width="426" alt="bildschirmfoto 2017-12-05 um 16 46 51" src="https://user-images.githubusercontent.com/20770029/34337241-32d23742-e95e-11e7-88b1-11a8f9bfae2b.png">

**Comment by androidi** [comment]
I've heard that Nvidia cards have these so called "perflevels". Maybe, at some point, your system decides to hop from level 2 to 3 or something like that? I were you, I'd monitor / print out GPU & mem freq when performance level boost happens next time to perhaps get some explanation for this.

**Comment by heikomat** [comment]
@androidi will do. For reference, these are the numbers pre-jump:

![bildschirmfoto vom 2017-12-25 12-29-29](https://user-images.githubusercontent.com/20770029/34339011-8e41ed1e-e96f-11e7-8e29-d15726f1460f.png)

**Comment by androidi** [comment]
Ok so on the left it says your GPU is currently at P0. Have you checked the output of that nvidia-smi right after you start mining? Is it perhaps at P2 then?

I've not had an nvidia card lately, but I'll probably receive my 1080 Ti in a couple of days. I'll be able to take better guesses once I've gotten the hang of how it operates.

**Comment by heikomat** [comment]
@androidi i checked while it was already mining for a couple of hours.

The jump just happened, but the performance-numbers look the same:
![bildschirmfoto vom 2017-12-26 12-34-02](https://user-images.githubusercontent.com/20770029/34355902-3cf6e80e-ea39-11e7-94ae-29d74db9d726.png)

**Comment by heikomat** [comment]
In also noticed, that we just started the next epoch. Could this be related? A wild guess would be that the performance increases when the dag changes. I have however no clue why that would be the case

**Comment by androidi** [comment]
I also noticed that by looking at your memory usage. From pics: 2790 MiB vs. 2849 MiB. But still, it really makes no sense. On a Vega 64 / Nanopool / Win10 / custom build from sources, the epoch change did not have any effect. Darn. :(
But hey! You should enjoy the risen hashrate :DD

I just can't help but wonder, why that nvidia-smi -q -d PREFORMANCE command displays the same P0 Performance State? Then again your PowerMizer is confident, the card is running at Performance Level 3 all the time?

However, when looking at the specs:
https://www.geforce.com/hardware/desktop-gpus/geforce-gtx-780/specifications

The memory bandwidth is 288.4 GB/s (non-OC'd), which roughly means a theoretical maximum of: 288.4 GB/s / 8 KB -> 36.05 MH/s

But those are just theoretical maximums.. my Vega 64 says 512 GB/s, theoretical max hashrate thus being: 512 GB/s / 8 KB -> 64 MH/s. Still, I can only get about 42 MH/s.

I also have an RX 480, which has memory throughput of 224 GB/s, and that crunched out about 25 MH/s, near ideal values.

People report all kinds of hashrates from 0.5 MH/s to 18 MH/s (e.g. in Reddit) for the GTX 780. So it can be a driver bug, a bug in ethminer, something related to power states, or.. dunno. Hopefully I observe something similar with the 1080 Ti so I can dig into this interesting issue.

**Comment by androidi** [comment]
GTX 1080 Ti grinding. Now we'll just have to wait 2+ days for the next epoch..

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
