### ISSUE TITLE
Help with AMD rx 570/580 getting lower hashrate than claymore.

### ISSUE THREAD

**Issue by TNguyen501** [ethereum-mining/ethminer#465]
New to this.  I am getting around 27-29mh/s on claymore, but on Ethminer, I only getting 24mh/s. I just download the ethminer.exe 0.12.0 for window. Bat file is:

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O <Your_Ethereum_Address>.<RigName>

Is there something I need to do to increase my hashrate.

**Comment by androidi** [comment]
Try adding params:
--cl-local-work 256 --cl-global-work 32768 --cl-parallel-hash 2

**Comment by TNguyen501** [comment]
Tried that didn't change anything. Also tried Master version and got this error
![screenshot 1](https://user-images.githubusercontent.com/34847064/34358744-11bfb8a8-ea18-11e7-9132-7b5c335f22ce.png)

**Comment by androidi** [comment]
You should put the cl-parameters on the same line as the ethminer-command, e.g. after MiningRig1.

ethminer tends to die sometimes. I don't know if it's related to network communication or something like that. At least when I change my wifi network, ethminer dies.

**Comment by TNguyen501** [comment]
Still getting error...

**Comment by Aciid** [comment]
@TNguyen501 As this is a no software error, please seek support from documentation the following communities.
Reddit: https://www.reddit.com/r/EtherMining/
Discord: https://discord.gg/EJpTavT

**Comment by tonyaik** [comment]
Are you sure you get 27MH in actual hashrate with claymores? In my experience ethminer displays the actual hashrate (the same as you see in the web GUI) and claymores displays aprox 10% higher compared to the web gui.

**Comment by TNguyen501** [comment]
Current hash rate vary....
https://ethermine.org/miners/2a4713a2D589Cbc8BD9Ac462798c09Ae98b40102/payouts

I have 6 GPUs running.

**Comment by TNguyen501** [comment]
https://ethermine.org/miners/2a4713a2D589Cbc8BD9Ac462798c09Ae98b40102

**Comment by TNguyen501** [comment]
It might just be the driver... I’m using and beta blockchain driver. When I get home I’ll remove that and install the current driver and set it to compute. 

My problem is claymore has a higher hash rate. I can run ethminer 0.12 version just fine just lower hashrate. But when I run the master version. It gives me that error. I was told that the master version is faster...

**Comment by androidi** [comment]
The master version may not be much faster, because the OpenCL kernel has not been touched, which accounts like 99,99% of the speed. (Also there's a bug, related to not submitting several valid results on one OpenCL kernel pass.)
I have a couple of comments as issues, but so far no-one has responded those...
If you have any kind of debugger, you could try and run the software in step-debug mode, to see, if you can catch the line that kills the software.

**Comment by cnetclub** [comment]
Hai.. im new in etherium mining

I have buy his rx 580 oc mining.. and i have install and make my own start bat. But my has rate only 17-18 mhs. And after looking information.. average 580 8gb is 24 up. Any one can help me?

**Comment by jim33** [comment]
From what i can tell 17-18 is about right for these cards now. For some reason these cards have been reducing hash rates when the DAG goes up.
I'm looking into NVidia cards now as they dont seem to be as badly affected.
![img_3281](https://user-images.githubusercontent.com/35636821/35186676-f9b0f50e-fe0f-11e7-99b7-dca516ffc7ca.PNG)

**Comment by DeadManWalkingTO** [comment]
1. Try Update Drivers.
Download and install the latests.

2. Try latest Ethminer version.
Check with this launch command:
`ethminer.exe -RH -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

3. Try to change P2 State and Power managment mode.
You can use [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW).
For the best mining hashrate choose from sector "5 - Common":
    - CUDA - Force P2 State (Set to "Off")
    - Power managment mode (Set to "Prefer maximum performance")

4. Try Tweak Win10.
You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) (#695).

5. Try Optimize/Overclock GPUs. 
You can use [MSI Afterburner](https://www.msi.com/page/afterburner) for GPU OverClock/Optimize. 

6. Try use a WatchDog
You can use [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) (#735).

Please feedback.
Thank you!

**Comment by Khayzer** [comment]
if you have done the over clocking and if you could mode your GPUs, it seems this kind of rigs may need to install an appropriate driver which is for blockchaine:
kindly note that you need to disable windows defender before installation.
http://how-to-mine.com/softwares/Drivers/AMD-Cards/AMD-Radeon_RX-Series/Radeon_Driver_Blockchain_Edition.zip

**Comment by ArtiomkaPL** [comment]
How do i put it to Simple Mining OS?
