### ISSUE TITLE
LOW hashrate upgrading configuration

### ISSUE THREAD

**Issue by gexongexon** [ethereum-mining/ethminer#469]
Strange... I had 2x rx580 and collect 23+23 Mh/s =46 mining with -G option . Then I've upgraded with a Nvidia 10603Gb and I got 13+13+11 = 37 !!!
Mining with -X
Should I have to tune something?

**Comment by ddobreff** [comment]
Its all about tuning, probably last one has different memory or other issue.

**Comment by DeadManWalkingTO** [comment]
Try launch different instances with latest version and feedback please.
Thank you!

**Comment by AndreaLanfranchi** [comment]
No feed back. Closing.
