### ISSUE TITLE
Hunter errors on Ubuntu 17.04

### ISSUE THREAD

**Issue by timcourtney** [ethereum-mining/ethminer#47]
I'm attempting to build ethminer on Ubuntu 17.04. New to Linux and command line. Reading up on as much as I can, but I'm struggling to find out what to do to resolve this error.

When I run `cmake ..` I receive this error: https://pastebin.com/embed_js/iXqCNmQE

Read the wiki page and looked at the log file but since I am inexperienced, I can't tell how to solve. Do I need to clean up anything from previous previous install attempts and if so, how would I do that?

Also found Found ruslo/hunter#539. Reply by xsacha says "Solution is to use a toolchain that sets fPIC." Found this: https://cmake.org/Wiki/CMake_Cross_Compiling. Do I need to make a toolchain file for cmake to prevent these errors? How do I learn how to do that?

Thanks for any assistance.

**Comment by timcourtney** [comment]
Installed OpenCL [with these instructions](https://wiki.tiker.net/OpenCLHowTo#Installing_the_AMD_ICD_loader_and_CPU_ICD_.28from_the_.22APP_SDK.22.29) and retried `cmake ..` to build ethminer. Same errors.

Note: I'm experiencing the errors on an Alienware Aurora R6 with NVIDIA GTX 1070 running Ubuntu 17.04. _I tried and successfully built ethminer on a separate MacOS machine with no issues._ So it is something to do with the configuration of my Ubuntu machine. Perhaps it needs additional software or libraries?

**Comment by jordan3250** [comment]
I am also having this problem. If you find a solution for this please contact me.

**Comment by timcourtney** [comment]
I solved this by (re)installing NVIDIA CUDA. First I read 

http://ethdocs.org/en/latest/mining.html

Then visited NVIDIA here:
https://developer.nvidia.com/cuda-downloads
http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#axzz4kGxlyrX7

After installing NVIDIA CUDA, I re-ran `cmake ..` and ethminer built successfully.

**Comment by JonasToth** [comment]
hi, i had the same issue.

i solved it, with configuring as root.
`sudo cmake ..`
`sudo make`

and then chowning it to my user
`sudo chown -R user:user build/`
