### ISSUE TITLE
ethminer-0.13.0rc1-Windows crash on Windows10

### ISSUE THREAD

**Issue by efrasyad** [ethereum-mining/ethminer#477]
ethminer for windows crash after this line:

`cl  13:10:22|cl-0      Platform: AMD Accelerated Parallel Processing`

Windows 10 FCU
RX570 and RX580 mixed cards
AMD Aug blockchain driver

ethminer-0.12.0-Windows running OK

**Comment by sullrich** [comment]
Had the same problem with 0.13.0rc1 on windows 10 and Ubuntu 16.  Installed ethminer-0.12 and it no longer crashes.

**Comment by chfast** [comment]
I need more information. Do you use hardware monitor (`-HWMON`)?

**Comment by jean-m-cyr** [comment]
Wish I had a Radeon to test with..

**Comment by efrasyad** [comment]
> I need more information. Do you use hardware monitor (-HWMON)?
with or without -HWMON both are crashing.

no issue with 0.12 release

**Comment by chfast** [comment]
Please test: https://github.com/ethereum-mining/ethminer/releases/tag/v0.13.0rc3.

**Comment by efrasyad** [comment]
> Please test: https://github.com/ethereum-mining/ethminer/releases/tag/v0.13.0rc3.

I can confirm this release working on my windows10 FCU running 3x rx570 and 2x rx580 Aug blockchain driver with and without -HWMON

The only drawback is my total hashrate reduced 1.5% from 0.13.dev1 release, but i can live with that, I need the HWMON.

Thank you for fixing this.

**Comment by chfast** [comment]
Is the hash rate lower with HWMON, or always?

**Comment by efrasyad** [comment]
Hasrate always 0.3-0.5MH/s lower with and without HWMON.

**Comment by efrasyad** [comment]
This release:

> https://github.com/ethereum-mining/ethminer/releases/tag/v0.13.0rc4

bring back my hashrate as in 0.12 release.
Thanks for all contributor hard work!

**Comment by chfast** [comment]
Thanks for testing it. in 0.13 RC4 we have 2 kernels to choose from. Looks like the old one works better for you.

**Comment by efrasyad** [comment]
From what i see, less stuttering on my PC while mining as well. so it is more convenience.
**Definitely ans improvement!**

By the way, what are the benefits from the new kernel compare to the old one?

**Comment by chfast** [comment]
The new one is quite different, should include some optimizations. But it looks like it may actually run slower on some hardware. So as for now, you have to benchmark both and select the better performing one.

**Comment by efrasyad** [comment]
I’ll keep my eye on any new build (dev, rc or release) and see how they goes. Is it all right if i used this thread to give some updates?

**Comment by chfast** [comment]
Better create a new issue every time you spot anything. You can also report your results (good or bad) to pull requests. This would be very valuable to us.

**Comment by efrasyad** [comment]
In case of new issue arise, yes i will create a new one.
But as long as the new build are not crashing on my rig or reduce the hashrate significantly, I’ll probably use this thread for update.

**Comment by efrasyad** [comment]
I just realized that with the latest build, i have more stalled share than before.
![image](https://user-images.githubusercontent.com/34883550/34725021-a2ce6da0-f547-11e7-9c02-18bbc27bda02.png)
