### ISSUE TITLE
Dual NVIDIA GTX 1070 TI - No GPU device with sufficient memory was found.

### ISSUE THREAD

**Issue by ornus** [ethereum-mining/ethminer#479]
Receiving insufficient memory errors when sufficient memory is available:

```
c:\Program Files\Ethminer\v0.13.0rc1>ethminer.exe -G -F http://eth-us.dwarfpool.com/0x<address>/1070ti/email@email.com --opencl-d
evices
No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument

c:\Program Files\Ethminer\v0.13.0rc1>ethminer.exe -G -F http://eth-us.dwarfpool.com/0x<address>/1070ti/email@email.com
No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument

c:\Program Files\Ethminer\v0.13.0rc1>ethminer.exe -F http://eth-us.dwarfpool.com/0x<address>/1070ti/email@email.com
No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument
```

```
Operating System: Microsoft Windows 7 Professional Version 6.1.7601 Service Pack 1 Build 7601
Video Cards: Two (2) x NVIDIA GeForce GTX 1070 Ti 8GB
Driver Version: 388.71
```

```
c:\Program Files\Ethminer\v0.13.0rc1>ethminer.exe --version
ethminer version 0.13.0rc1
Build: Windows/msvc/Release
```

```
c:\Program Files\Ethminer\v0.13.0rc1>ethminer.exe --list-devices
Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[1] [0] GeForce GTX 1070 Ti
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2147483648
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
[1] [1] GeForce GTX 1070 Ti
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2147483648
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1070 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 8589934592
[1] GeForce GTX 1070 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 8589934592
```

**Comment by ornus** [comment]
Was able to get it working by replacing -G with --opencl --opencl-platform 1. Nevertheless, I would still consider this to be a bug/problem given that there isn't an issue with a lack of memory. 

`c:\Program Files\Ethminer\v0.13.0rc1>ethminer.exe --opencl --opencl-platform 1 -F http://eth-us.dwarfpool.com/0x<address>/1070ti/email@email.com --opencl-devices`

**Comment by ZiDanRO** [comment]
Why do you whant to mine in OpenCL when you have nvidia cards? Try the -U instead of -G and it will work and it will have the best performance!

**Comment by ornus** [comment]
I was going through the various command line options recently and gave OpenCL mode a try to see much of a difference in hashrates I would see; it was ~2 Mh/s lower using OpenCL. 

Nevertheless, the fact that I'm getting an error is a good reason for filing a bug.

**Comment by chfast** [comment]
This is something with the OpenCL driver, because `CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2147483648`. So the GPU has 8 GB or memory, but driver will allow you to allocate only 2 GB at once. 

In AMD driver this can be controlled by env vars.

I have 1070 and I don't have this issue.

**Comment by DeadManWalkingTO** [comment]
1. Try Update Drivers.
Download and install the latests.

2. Try use -U for CUDA devices.
That's my launch command:
`ethminer.exe -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

3. Try to change P2 State and Power managment mode.
You can use [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW).
For the best mining hashrate choose from sector "5 - Common":
    - CUDA - Force P2 State (Set to "Off")
    - Power managment mode (Set to "Prefer maximum performance")

4. Try Tweak Win10.
You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) (#695).

5. Try Optimize/Overclock GPUs. 
You can use [MSI Afterburner](https://www.msi.com/page/afterburner) for GPU OverClock/Optimize. 

6. Try use a WatchDog
You can use [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) (#735).

Please feedback.
Thank you!
