### ISSUE TITLE
Stratum failover never exits failover

### ISSUE THREAD

**Issue by AstarothPoD** [ethereum-mining/ethminer#48]
Using both -S and -FS, on unavailability of the -S address, it switches to -FS. However, it never tries to switch back, even if -FS becomes unavailable.
Ideally, -S should be checked regularily and switched back to when it becomes available, as it can be considered the preferred node.
This is a bug of the original code, any chance of getting a fix?

**Comment by mnik247** [comment]
+1

**Comment by DeadManWalkingTO** [comment]
Maybe enhancement.

**Comment by smurfy** [comment]
This has been fixed. It now toggles between failover and main.
