### ISSUE TITLE
Ethminer 0.13.0rc1: Segfault after trial 5 - ethminer -U -M

### ISSUE THREAD

**Issue by omnihaand** [ethereum-mining/ethminer#480]
Ubuntu 17.04
2x GTX 1070 Ti

Output snippet, with -v 9 added, as follows:
**CUDA#0: 75%
CUDA#1: 94%
CUDA#0: 81%
CUDA#0: 88%
CUDA#0: 94%
Trial 1... 48783175
Trial 2... 53299640
Trial 3... 53404561
Trial 4... 53829629
Trial 5... 53713948
Segmentation fault (core dumped)**

Cmake/hunter build using:
cmake .. -DETHASHCUDA=ON -DETHASHCL=OFF

Prebuilt [ethminer 0.13.0rc1](https://github.com/ethereum-mining/ethminer/releases/download/v0.13.0rc1/ethminer-0.13.0rc1-Linux.tar.gz) gives the same segfault after trial 5.  But, the prebuilt [ethminer 0.12.0](https://github.com/ethereum-mining/ethminer/releases/download/v0.12.0/ethminer-0.12.0-Linux.tar.gz) works as expected. 

Would love to use the latest build, so any help is greatly appreciated.

**Comment by inprosys** [comment]
I'm getting a different error but similar crash failure after Trial 5 under Windows 7:  the V13 program crashes with exception error 0xC0000005 (according to the system log).  I've downloaded the V13 debug version and will try to test later for more detailed info.

**Comment by muraj** [comment]
I believe I was able to diagnose this.  Apparently after the miner vector
is cleared in Farm::stop(), the hooks are aborted, but the miners aren't
stopped so another round of the workloop happens with a deleted hook
(should work() is still true).  My solution to this was to call
stopWorking() in CUDAminer's destructor.  This leads to a deadlock between
Farm::stop and Farm::collectHashRate -- scoping the guard lock in stop() to
just the change to m_miners and moving the hashrateTimer changes to after
the thread joins fixes the deadlock and a possible condition.  Still
testing on my system, was going to make a pull request eventually.

**Comment by muraj** [comment]
Created pull request: https://github.com/ethereum-mining/ethminer/pull/487

**Comment by chfast** [comment]
Fix released in https://github.com/ethereum-mining/ethminer/releases/tag/v0.13.0rc2.
Can you test?

**Comment by popposs** [comment]
Still didn't work for me. 
```
Trial 1... 14477587
Trial 2... 15843003
Trial 3... 15843003
Trial 4... 15741232
Trial 5... 15739657
*** Error in `ethminer': free(): corrupted unsorted chunks: 0x0000000002b87600 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f067efa67e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f067efaf37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f067efb353c]
ethminer(_ZN3dev3eth9CUDAMinerD0Ev+0xe1)[0x4cb911]
ethminer(_ZN3dev3eth4Farm4stopEv+0x163)[0x46ab93]
ethminer(_ZN8MinerCLI11doBenchmarkEN3dev3eth9MinerTypeEjjj+0x68a)[0x46fdfa]
ethminer(_ZN8MinerCLI7executeEv+0x51a)[0x47798a]
ethminer(main+0x31a)[0x4585ea]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f067ef4f830]
ethminer[0x45ae3a]
```

**Comment by kang-chen** [comment]
Getting an error here on trial 5, although it was Segmentation fault 11
Geforce 1070GTX, through an eGPU, openCL build.

Is 0.14.0 ready to try?
