### ISSUE TITLE
r7 250 not working

### ISSUE THREAD

**Issue by c-bug** [ethereum-mining/ethminer#481]
Hi, got exactly this card [http://www.sapphiretech.com/productdetial.asp?pid=02195012-0938-48B1-B4E3-2866EB734787&lang=deu](http://www.sapphiretech.com/productdetial.asp?pid=02195012-0938-48B1-B4E3-2866EB734787&lang=deu)

ethminer shows
```1# ./ethminer --list-devices
Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[0] [0] Capeverde
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 2133504000
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1872683008
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
  ✘  00:30:19|ethminer  CUDA error: No CUDA driver found
```

but when I start mining using ./ethminer --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O XXX.XXX,
I get this after the fetch
```
 cl  00:25:59|cl-0      Platform: AMD Accelerated Parallel Processing
 cl  00:25:59|cl-0      Device:   Capeverde  / OpenCL 1.2 AMD-APP (2527.3)
  ✘  00:25:59|cl-0      clCreateCommandQueue ( -6 )
  ✘  00:25:59|cl-0      OpenCL Error: clEnqueueWriteBuffer -36
```

I tried AMD pro 17.40 and 17.50, no difference. I am running debian.
Help is very appreciated.

**Comment by MariusVanDerWijden** [comment]
https://investoon.com/tools/dag_size

**Comment by EoD** [comment]
``clCreateCommandQueue ( -6 )`` is ``CL_OUT_OF_HOST_MEMORY``

**Comment by chfast** [comment]
Your GPU does not have enough memory. You need 3+ GB.
