### ISSUE TITLE
Client connector error: libcurl error: 6

### ISSUE THREAD

**Issue by y0d4a** [ethereum-mining/ethminer#482]
Dear, i have issue with start this miner on linux x64:
$ ./ethminer -G -F http://eth-eu1.nanopool.org:9999/0xADDRESS.WORKER_NAME/email@email.com
  ℹ  14:04:05|ethminer  Found suitable OpenCL device [ GeForce GTX 1060 6GB ] with 6367346688  bytes of GPU memory
 cl  14:04:05|cl-0      No work. Pause for 3 s.
  m  14:04:05|ethminer  Waiting for work package...
 cl  14:04:08|cl-0      No work. Pause for 3 s.
 cl  14:04:11|cl-0      No work. Pause for 3 s.
 cl  14:04:14|cl-0      No work. Pause for 3 s.
  ✘  14:04:15|ethminer  Failed to submit hashrate.
  ✘  14:04:15|ethminer  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 6

can i get small help? :)

thank you!

**Comment by jasonwee** [comment]
you need a slash in between wallet address and worker name
http://eth-eu1.nanopool.org:8888/YOUR_WALLET_ADDRESS/YOUR_WORKER_NAME/YOUR_EMAIL

**Comment by smurfy** [comment]
I also would suggest using Stratum mode.

``./ethminer -RH -SP 1 -U -S eth-eu1.nanopool.org:9999 -O WALLET.WORKER``

**Comment by y0d4a** [comment]
thank you guys.
with this miner i get less hash, is that on miner or driver?

**Comment by smurfy** [comment]
``-G`` uses opencl instead of CUDA. Since your wrote you have a 1060 i guessed you have the nvidia drivers installed.

CUDA (``-U``) should give you a better hashrate, so you should install the correct drivers.

Also you should drop ``--farm-recheck`` its not needed for stratum mode.

**Comment by jean-m-cyr** [comment]
One reason you might use --farm-recheck in stratum mode is to slow down the hwmon status messages which are hooked up to the same timer. The default is 2 seconds which is too often to my liking.

**Comment by y0d4a** [comment]
yeap, after installing cuda driver, i got regular hash like on windows.
thank you guys for your help!

**Comment by stone212** [comment]
@smurfy I had the same problem and read your thread and I get 

`The following arguments were not expected: -S -SP -H`

I am using ethminer-0.16

**Comment by AndreaLanfranchi** [comment]
@stone212 
read help `ethminer --help`. Cli arguments -S -SP -H have been dropped since ages.
Here you can find docs about how to connect
https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md

**Comment by stone212** [comment]
@AndreaLanfranchi Thank you I am mining w stratum+tls now.
