### ISSUE TITLE
Getting error with ethminer 0.13.0rc1

### ISSUE THREAD

**Issue by dataclub** [ethereum-mining/ethminer#483]
m  18:04:27|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  gpu/2  0.00  gpu/3  0.00  gpu/4  0.00  gpu/5  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  18:04:28|cl-1      Platform: AMD Accelerated Parallel Processing
 cl  18:04:28|cl-2      Platform: AMD Accelerated Parallel Processing
 cl  18:04:28|cl-3      Platform: AMD Accelerated Parallel Processing
 cl  18:04:28|cl-4      Platform: AMD Accelerated Parallel Processing
 cl  18:04:28|cl-5      Platform: AMD Accelerated Parallel Processing
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 9 requests (9 known processed) with 0 events remaining.
*** Error in `./ethminer': double free or corruption (fasttop): 0x00007fbaac00c8b0 ***
 cl  18:04:28|cl-2      Device:   Pitcairn  / OpenCL 1.2 AMD-APP (1800.11)
^C

**Comment by EoD** [comment]
Probably a duplicate of  #234

**Comment by chfast** [comment]
Have you check the recent RC builds?
