### ISSUE TITLE
one gpu randomly errors at DAG

### ISSUE THREAD

**Issue by Decapitary** [ethereum-mining/ethminer#484]
I dont know what is happening. I have 4x 470 running everytime ethermine chooses a different one to error at dag. im getting 63MH/s with no overclock because always one of them is 0MH/S. What is happening?

EDIT:
guys I realy need help anything would be appreciated.
p.s im gonna stop using etherminer as soon as I reach the min withdrawal limit if I dont find a solution

**Comment by jasonwee** [comment]
if you add verbosity, will it show more information?

**Comment by Decapitary** [comment]
```
 cl  05:40:32|cl-0      New seed #54b9a934GǪ
  m  05:40:34|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
 cl  05:40:34|cl-0      Platform: AMD Accelerated Parallel Processing
 cl  05:40:34|cl-0      Device:   Ellesmere  / OpenCL 2.0 AMD-APP (2442.12)
 cl  05:40:35|cl-0      Build info:
 cl  05:40:35|cl-0      Creating light cache buffer, size 37879232
 cl  05:40:35|cl-0      Creating DAG buffer, size 2424307328
 cl  05:40:35|cl-0      Loading kernels
 cl  05:40:35|cl-0      Writing light cache buffer
 cl  05:40:35|cl-0      Creating buffer for header.
 cl  05:40:35|cl-0      Creating mining buffer
 cl  05:40:35|cl-0      Generating DAG
  X  05:40:35|cl-0      clEnqueueNDRangeKernel ( -4 )
 cl  05:40:35|cl-0      Switch time 4541 ms / 3037863 us
  X  05:40:35|cl-0      OpenCL Error: clEnqueueNDRangeKernel -4
  i  05:40:36|stratum   Received new job #2aa56ec8
  m  05:40:36|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  05:40:38|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  05:40:40|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
  m  05:40:42|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0]
```

**Comment by Decapitary** [comment]
I think its a CL_INVALID_GLOBAL_WORK_SIZE if global_work_size is NULL, or if any of the values specified in global_work_size[0], ...global_work_size [work_dim - 1] are 0 or exceed the range given by the sizeof(size_t) for the device on which the kernel execution will be enqueued. error. how can I fix this?

**Comment by EoD** [comment]
``clEnqueueNDRangeKernel ( -4 )`` is equivalent to ``CL_MEM_OBJECT_ALLOCATION_FAILURE``. Is the DAG too big for your card?

**Comment by Decapitary** [comment]
I have 4x MSI rx 470 armored 4G. everytime one gpu shows this error and others work perfeclty.
how is that each time I open ethermine one memory corrupted and if I restart ethermine it gets fixed but another one shows this error?

you mean one memory randomly gets corrupted and others get fixed each time I open ethermine?

**Comment by EoD** [comment]
@Decapitary Yes, but I am just guessing here. We don't have much information except the error ``CL_MEM_OBJECT_ALLOCATION_FAILURE``, so it's hard to see what is going wrong.

**Comment by Decapitary** [comment]
@EoD  thanks. now I have 6x still only uses 3.stock settings and overclock with afterburner has no effect what so ever.

**Comment by Decapitary** [comment]
MB: bt250 btc pro
Ram: 4G
OS: Win 10 64bit
6x MSI rx 470 armored 4G
Latest crimson driver.

**Comment by androidi** [comment]
> Ram: 4G
Increase virtual memory size. See: https://github.com/ethereum-mining/ethminer/issues/467#issuecomment-354125120

**Comment by Decapitary** [comment]
@androidi omg thank you it worked!
