### ISSUE TITLE
Console keeps scrolling

### ISSUE THREAD

**Issue by Sundheden** [ethereum-mining/ethminer#486]
Seems like the output is just adding new lines instead of replacing the old value, which I assume is the intended method: 

![image](https://user-images.githubusercontent.com/9757648/34465304-9c468f00-eea6-11e7-9a99-c2c31012fa7c.png)

**Comment by ZiDanRO** [comment]
This is the correct behavior in console. No problem with the console

**Comment by smurfy** [comment]
not a bug. if you are using stratum mode (``-S``)  use a lower ``--farm-recheck`` value like ``5000``  for a less spammy console.
