### ISSUE TITLE
12x AMD RX 570

### ISSUE THREAD

**Issue by bakamelonnn** [ethereum-mining/ethminer#488]
Hi! Can anyone give me an idea how to setup ethminer to use all my 12x RX 570 and not selecting the onboard Intel HD graphics?? Thank You!

**Comment by smurfy** [comment]
use ``--opencl-platform 1`` (or the number displayed in ``--list-devices``

**Comment by bakamelonnn** [comment]
Hi. After setting that i get the issue of ethminer.exe has stopped working.

**Comment by efrasyad** [comment]
I think AMD Windows driver can only support up to 8 GPUs.

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!

**Comment by AndreaLanfranchi** [comment]
No feed back.
