### ISSUE TITLE
GTX 970: Hashrate is dropping as DAG size is increasing

### ISSUE THREAD

**Issue by arainchik** [ethereum-mining/ethminer#489]
It looks like GTX 970 (Compute 5.2) can only get 8-9 Mh/s at current DAG (ethminer -M 4700000 -U), while it was getting 13-14 Mh/s at block 4,100,000 (ethminer -M 4100000 -U) , and 14-16 at block 0 (ethminer -M -U)

Why such a dramatic drop in performance? "nvidia-smi" shows that Memory utilization is 100% during low block number benchmarks with high rx/tx transfer rates and only 60% at block 4700000

Any suggestions on how to get hashrate increased?

**Comment by jasonwee** [comment]
use opencl instead of cuda? mine 960m can get around average 12Mh/s

**Comment by arainchik** [comment]
Switching to OpenCL (Linux) didn't make any difference, still getting 8-9 Mh/s

**Comment by seevik2580** [comment]
same problem here ... i tried older drivers, newer drivers, overclock, underclock, different miners, different OS, nothing helps .. still getting max 9,6Mh/s...

**Comment by orofbrown** [comment]
@jasonwee how did you get that high of a rate with the 960m? I can only manage to squeeze 4.5 Mh/s out of mine

**Comment by Ludicam** [comment]
i'm managing 10.67 atm with mine being overclocked (+200 core, +200 mem and +15mv and 100% plimit and changing the GPU to Compute performance P0 State. Looks like its time to upgrade the GPu lol unless anyone knows any hidden tricks especially if u guys are saying ubuntu isn't even helping

**Comment by Ludicam** [comment]
quick guide for u @orofbrown, Step 1 overclock gpu (watch a video), step 2 change from p2 state to p0 using nvsmi (type into google someone has a guide how to do it) you need to overclock before doing step 2 or don't overclock at all as you are changing your values meaning the p2-->p0 process will be ignored. then change your gpu to compute performance should up your hash rate to the same value as mine approx 10.7

**Comment by orofbrown** [comment]
Awesome thanks @ludicam I'll try it out. I did manage to get some better ethash performance by installing Ubuntu, but I'll see if I can overclock it like you said, bc I'm pretty sure I've got it on P0 already. Are there any concerns with over locking on a laptop? And yeah, I'm working on getting a better card myself lol

**Comment by phreakske** [comment]
No man, it works fine, yesterday, i did try myself with an MSI OC Gaming 4GB GTX 970, you've got to change Nvidia control panel and change "optimal performance" for computing power. Then Mh/s changes quickly to 26.411 MH/s at my place, which is very high for such an oldie. First it was 2.7MH/s. Simple solution :-)

**Comment by jasonwee** [comment]
try different `--cl-local-work --cl-global-work` that works for your card, @orofbrown

**Comment by RMRx** [comment]
phreakske, any chance you could share your system config & ethminer options?

**Comment by phreakske** [comment]
Well i've been running windows 10 and it seems every time i start up, it's something different.. windows 10 suxx.. i've ordered a new motherboard and i'm gonna test ubuntu/windows 7 next week. After the latest update "fall creators update" it's back to 9MH/s... so i guess after each windows-update everything is fucked up. I've ordered 2x GTX 1050ti and an extra GTX970 .. i'll keep u up to date as soon as i've got my new setup. Searched the whole internet and every opinion is the same... don't use windows 10 !

**Comment by niralacrypto** [comment]
Yes my GTX 970 4G is also not giving more than 8-9Mh/a

**Comment by ImSelectional** [comment]
@phreakske How did you even manage to get 26 mh were all stuck at around 8. Windows 10 isn't the problem if you set it up correctly.

**Comment by phreakske** [comment]
I still don't know how it did manage it... it was the first time i did ran claymore miner, after upgrade of windows i can't get more than 10.7MH/s. I didn't even had to do anything, stopped and started it was 26MH/s.
I'll try again friday, with windows 7, and 2 GPU's same brand, same card. GTX970 MSI gaming 4GB OC edition.
I use the latest drivers, using geforce experience, i've tried different onces, but then card wasn't dedected. I'll keep on trying to get the same result again... weird.

**Comment by ImSelectional** [comment]
@phreakske to have the cards detected use cuda6.5 but either way, it had no effect on performance. how did you change optimal performance for computing power? where is that setting?

**Comment by phreakske** [comment]
SET GPU0=-setBaseClockOffset:0,0,158 -setMemoryClockOffset:0,0,200 -setPowerTarget:0,75 -setTempTarget:0,0,67 -forcepstate:0,0
nvidiaInspector.exe %GPU0%

That's the line i'm experimenting with, i use ethminer (works better).. even on windows.
I use it in a batch before calling ethminer with his options... 
It's a small overclock but it helps and it gets the geforces in P0. Now it get's 10.5 maximum @ 114W

**Comment by phreakske** [comment]
In nvidia profile inspector you put "Force Cuda P2 state" to off... then you get an extra boost for free...

**Comment by quadaboum** [comment]
Hello, how do you manage this to achieve these rate i'm only at 2.5 using Claymore and it's the same with Ethminer

**Comment by ImSelectional** [comment]
@quadaboum Make sure you go to nvidia control panel and turn on "optimise for computer performance"

**Comment by tttonyyy** [comment]
Same issue here, got two Zotac GTX 970s, one in a Win10 box, one I've just put Ubuntu on, both get approx 9MH/s, same with claymore or WinEth.  The Win10 one is optimised for compute.

I did wonder if the DAG could be in the 0.5Gb slow area of the GTX 970 memory, but it's only 2513MiB at the time of writing and I assume claymore loads the fast area first.

**Comment by ricardobaehr** [comment]
Same problem here... 7.5 MH/s

Any suggestion?

**Comment by phreakske** [comment]
No succes..sold my cards...

Op ma 16 apr. 2018 22:31 schreef Ricardo Baehr <notifications@github.com>:

**Comment by ricardobaehr** [comment]
Which card do you recommend?

**Comment by phreakske** [comment]
Best cards are rx470 mining edition...29MH/s even microns 8GB will
do..sapphire...

Op ma 16 apr. 2018 23:04 schreef Ricardo Baehr <notifications@github.com>:
