### ISSUE TITLE
"Reported hashrate" not sent to ethpool and ethermine

### ISSUE THREAD

**Issue by AstarothPoD** [ethereum-mining/ethminer#49]
Ethpool and ethermine, and probably others, show the miner's reported hashrate. Ethminer does not send this value to the pools, so it's always 0 or blank.

**Comment by devcompl** [comment]
So looking at the code there is missing piece of code in [doStratum](https://github.com/ethereum-mining/ethminer/blob/60aea9246b163241a535bd7e4681386bd4e8d940/ethminer/MinerAux.h#L903)
```
try
{
    prpc->eth_submitHashrate(toJS(rate), "0x" + id.hex());
}
    catch (jsonrpc::JsonRpcException const& _e)
{
    cwarn << "Failed to submit hashrate.";
    cwarn << boost::diagnostic_information(_e);
}
```

Any reason for that?

**Comment by sfwhite** [comment]
I noticed this a couple days ago as well. I guess we can always build our own and include it, but I suspect this was an oversight on their part. Hopefully we get official word soon.

**Comment by jimmykl** [comment]
Has this been fixed? I can see that code above on https://github.com/ethereum-mining/ethminer/blob/60aea9246b163241a535bd7e4681386bd4e8d940/ethminer/MinerAux.h but I'm still not getting a reported hashrate on ethermine?

**Comment by wndsr** [comment]
Same case with nanopool. Reported hashrate remains at 0 since I switched to ethminer 0.11.0rc1

**Comment by jimmykl** [comment]
@sfwhite @devcompl I tried adding that to doStratum but I'm obviously doing something wrong because it fails to compile.
```
In file included from /Users/jimmy/Sites/ethminer/ethminer/main.cpp:34:
/Users/jimmy/Sites/ethminer/ethminer/MinerAux.h:974:7: error: use of undeclared identifier 'prpc'
                                                prpc->eth_submitHashrate(toJS(rate), "0x" + id.hex());
                                                ^
/Users/jimmy/Sites/ethminer/ethminer/MinerAux.h:974:51: error: use of undeclared identifier 'id'
                                                prpc->eth_submitHashrate(toJS(rate), "0x" + id.hex());
```
Unfortuately my C++ experience is zero so I don't know where to define/get 'prpc' or 'id'

Have either of you tried adding that code and compiling?

**Comment by DLS-bau** [comment]
You can't use eth_submitHashrate, that's for the old farm client, not for stratum. 
You have to write a new function to submit hashrate in the stratum client. I tried, but I can't find any clear documentation about how to format the JSON, and can't do it blindly. There is nothing about submitting hashrate in the stratum protocol draft, no idea how claymore is doing it.

**Comment by mnik247** [comment]
+1
remote reported hashrate = 0 ver 0.11.0rc1 (win7 x64, win10 x64) with ethermine and nanopool.
reported remote hashrate = 0 ver 0.11.0rc2  (win7 x64, win10 x64) with ethermine (nanopool not tested).

**Comment by murathai** [comment]
I hope it can be fixed soon.

**Comment by tex6246** [comment]
i am noticing that possibly the hashrate that the software is reporting to what ethermine reports is inaccurate by as much as 10h/s
both 0.11.0rc1 and rc2 are both affected with it also not reporting Reported hashrate on ethermine.
![hashrate](https://user-images.githubusercontent.com/29905340/27845621-1094ea2e-60ee-11e7-8f7d-0c7b076a6c1d.PNG)
as per the green line in pic.
i'll do more testing and try on other pools for more info

**Comment by ET-Bent** [comment]
@tex6246 you are probably using a WAY to low farm-recheck value. Use at least `3000-5000`. If you use `200` then the hashrate is completely off because the sample time is way too little.

**Comment by JHGitty** [comment]
@ET-Bent (or anybody else who knows it)

Is the "submitted hashrate" also affected by the "farm-recheck" value or how often is the hashrate submitted to the pool?

**Comment by sfwhite** [comment]
@jimmykl the problem is that there is no equivalent of FarmClient's
`bool eth_submitHashrate(...)` 
implemented in EthStratumClientV2.
The Stratum protocol doesn't support hashrate submission, to my knowledge.

My suspicion is that the miners that do successfully report to pools, despite being connected through stratum, are probably issuing a json rpc call in the same way FarmClient is doing it.

I'll dig into it this weekend, but don't let that stop anyone from trying as well. I'm rusty when it comes to c++.

**Comment by jimmykl** [comment]
Sounds like you're onto it @sfwhite I know it's only a reporting function but it'd be useful to have. 

Where is the stratum protocol documented?

**Comment by sfwhite** [comment]
@jimmykl I found it [here](https://en.bitcoin.it/wiki/Stratum_mining_protocol), but there apparently one on slushpool's site as well.

**Comment by pabloi** [comment]
I can confirm no hashrate reported on Nanopool either. Claymore does report, so it is supported somehow.

**Comment by sfwhite** [comment]
@pabloi its not supported in the Stratum servers. I suspect Claymore is reporting hashrates through the getwork endpoints (JSONRPC calls). 

Has anyone with Claymore run wireshark to see what packets are popping out the back?

**Comment by faithless1108** [comment]
+1 same Problem here.. would be verry nice!

**Comment by rom1nux** [comment]
I confirm the problem is still there in stratum mode (not in farm mode) but a lot of pool use only stratum now.

**Comment by Davesmacer** [comment]
Hello, 

I'm having this issue with latest master build. I used -SC 1. I tried -SC 2 but it says something about not being supported. My full run command is:

 ./ethminer.exe -HWMON --farm-recheck 450 -SC 1 -U -S us1.ethermine.org:4444 -FS eu1.ethermine.org:4444 -O "address"

**Comment by lexruee** [comment]
@Davesmacer 
you need to pass the extra option `--report-hashrate` to ethminer.

Example:
```
./ethminer.exe -HWMON --report-hashrate --farm-recheck 450 -SC 1 -U -S us1.ethermine.org:4444 -FS eu1.ethermine.org:4444 -O "address"
```

**Comment by Davesmacer** [comment]
Silly me! I checked on -h option and didn't see that one. Sorry

**Comment by akostadinov** [comment]
with this option still not workie `ethminer version 0.14.0.dev1`

**Comment by EoD** [comment]
@akostadinov can you show all options you are using? It is working fine for me on mentioned pools.

**Comment by akostadinov** [comment]
ethminer -HWMON --report-hashrate --farm-recheck 500 --opencl --cl-local-work 256 --api-port -3333 --stratum eth-eu2.nanopool.org:9999 --stratum-failover eth-eu1.nanopool.org:9999 -O 0x123456.symname/email

**Comment by tsauce** [comment]
on ethos and using these params. On nanopool Last Reported Hashrate not showing up. Works fine with claymore though.


/opt/miners/ethminer/ethminer -F http://127.0.0.1:8080/df20c6 -U --dag-load-mode sequential --cl-global-work 8192 --farm-recheck 2000 --stratum-protocol 1 --report-hashrate -HWMON --cuda-parallel-hash 4 --cuda-devices 0

**Comment by tsauce** [comment]
BTW, if you are using eth-proxy, I believe that prevents the hashrate from being submitted. 99.999% of the time you should be using stratum direct to pool.

Though on 0.14.dev1 my report-hashrate seems to be rather low, in fact, probably reporting only 1 of my workers.

**Comment by lindahl85** [comment]
Same issue here on 0.14.dev3 with this config:
ethminer.exe --farm-recheck 4000 -U -S eth-eu1.nanopool.org:9999 -FS eth-eu2.nanopool.org:9999 -O 0x89.RAPTOR/@gmail.com
--cuda-parallel-hash 4 -SP 1 -RH

**Comment by Angel996** [comment]
I'm not getting hashrate reporting on nanopool either:

`./ethminer --farm-recheck 6000 -S eth-eu2.nanopool.org:9999 -O 0x*******.RIGxx/user@domain.com -RH -G --cl-kernel 1 --cl-local-work 256 --cl-global-work 32768 --cl-parallel-hash 2`

**Comment by EoD** [comment]
It might be best to open a new issue. This issue here has been closed after basic reporting has been implemented (and confirmed working on ethermine): 4a2d841147aab0a635163cb034c3163b3851c822

The issue you are encountering is either a new bug or another missing feature.

**Comment by akostadinov** [comment]
All, please see #273 
For nanopool another stratum protocol needs to be specified: `--stratum-protocol 1`

Just tested with  0.15.0.dev0+git.26a51df and it is working. Perhaps this issue should be finally closed to avoid any more spam.

**Comment by lindahl85** [comment]
I used --stratum-protocol 1 but in the form -SP1 instead. It never reported any. My router with Asus AIprotection didn´t like ethminer so I had to use Claymore instead. Litte sad.

**Comment by Angel996** [comment]
-SP 1 works _sometimes_, but reporting stops suddenly, like one of the posters noted already.

**Comment by smurfy** [comment]
please test latest master. #897 should fix the problem

**Comment by Kecedar** [comment]
Hi,

please give me just short clarification.
In ethermineI have reported hashrate lower then current hashrate, which one is more important and whih is related with real mining in the pool?

Thanks a lot

**Comment by hbtpoprock** [comment]
Has it been fixed yet?

**Comment by akostadinov** [comment]
@hbtpoprock , yes, see #273

Somebody please close comments on the issue.
