### ISSUE TITLE
EthStratumClient can't be stopped

### ISSUE THREAD

**Issue by jgillich** [ethereum-mining/ethminer#490]
Correct me if I'm wrong, but there is no way to stop `EthStratumClient` because [`disconnect()`](https://github.com/ethereum-mining/ethminer/blob/master/libstratum/EthStratumClientV2.h#L41) is private. Can I submit a PR to change that, or did I miss something?

(Asking because I use ethminer as a library)

**Comment by smurfy** [comment]
what do you mean? and why do you want to "stop" it anyways?

**Comment by jgillich** [comment]
Now that you mention it..yes, I should just destroy the instance. Somehow I assumed I'd need to call disconnect to properly clean up the socket, but that is probably done by its destructor. Thanks!
