### ISSUE TITLE
ethminer only recognize one VEGA 64 card

### ISSUE THREAD

**Issue by carlosmaug** [ethereum-mining/ethminer#497]
Hi

I have 2 VEGA 64 cards  but ethminer -G --list-devices only recognize the one connected to the pcie x16

ethminer -G --list-devices

Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[0] [0] gfx900
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 8573157376
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 8573157376
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

lspci
01:00.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] Device 1470 (rev c1)
02:00.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] Device 1471
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 687f (rev c1)
03:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Device aaf8
08:00.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] Device 1470 (rev c1)
09:00.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] Device 1471
0a:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 687f (rev c1)
0a:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Device aaf8

/opt/rocm/bin/rocm-smi -a
====================    ROCm System Management Interface    ====================
================================================================================
GPU[1]     : GPU ID: 0x687f
GPU[2]     : GPU ID: 0x687f
GPU[0]     : GPU ID: 0x1902
================================================================================
================================================================================
GPU[1]     : Temperature: 79.0c
GPU[2]     : Temperature: 28.0c
GPU[0]     : Unable to display temperature
================================================================================
================================================================================
GPU[1]     : GPU Clock Level: 4 (1200Mhz)
GPU[1]     : GPU Memory Clock Level: 3 (945Mhz)
GPU[2]     : GPU Clock Level: 0 (852Mhz)
GPU[2]     : GPU Memory Clock Level: 1 (500Mhz)
GPU[0]     : PowerPlay not enabled - Cannot display clocks
================================================================================
================================================================================
GPU[1]     : Fan Level: 168 (65.88)%
GPU[2]     : Fan Level: 165 (64.71)%

**Comment by TarantulaENERGY** [comment]
Hello,

please make sure you disabled Crossfire in the AMD Radeon settings. Might happen right after a driver update it is enabled again. Please give a short reply, if this causes the problem.

**Comment by carlosmaug** [comment]
Hi

I'm using the Radeon Software Crimson ReLive Edition Beta for Blockchain, in this driver there is no option to deactivate  Crossfire. I've try also installing a windos 10 to check if there was an option to deactivate Crossfire but there is no option related to Crossfire.

For mining I'm using Ubuntu 16.04
uname -a
Linux mina 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Driver amdgpu-pro 17.40-483984

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!

**Comment by zah-henri** [comment]
Hi! I have this problem as well. I have a single Radeon rx vega 64 card. I had a nvidia 210 card installed for a while but it's no longer in the computer and I removed the nvidia driver software.

I don't have the crossfire settings visible, maybe because I only have one card.

C:\Users\henrialapeijari\Downloads\ethminer-0.14.0.dev2-Windows\bin>ethminer -G --list-devices

Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[0] [0] gfx900
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 8573157376
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

C:\Users\henrialapeijari\Downloads\ethminer-0.14.0.dev2-Windows\bin>
