### ISSUE TITLE
how can i miner with CPU ? can i found old version ?

### ISSUE THREAD

**Issue by luizfelipetx** [ethereum-mining/ethminer#50]
CPU mining is no longer supported in this miner. Use -G (opencl) or -U (cuda) flag to select GPU platform.

I on past mine cpu with this software , why i cant anymore ?

When can i found a old version of this software ?

**Comment by carmelo12341** [comment]
If you want to mine using cpu use geth, the go implementation of ethereum. It has a cpu miner built-in

**Comment by avatar-lavventura** [comment]
Can't I just use `parity` and mine using cpu? @carmelo12341

**Comment by bmatthewshea** [comment]
This is a discussion about current ethminer binary and not Parity or Geth or CPU mining.
CPU mining has been and is dead with most newer mining clients. Just not worth it. If you insist on using a CPU, it helps to have brand new one to be of ANY gain.

There are still miner binaries that can use CPU(s) as the engine device. Easiest to use for CPU IMO is 'nicehash' app - and there are others. You can also look to see what nicehash picks as miner(s) to see what they use as the best miner for a given CPU in the context of profitability. Or find an older ethminer client that accepts -C/CPU flag. Or... just buy a new GPU ;)

As mentioned, this isn't the place to find that - issue has been closed.

**Comment by avatar-lavventura** [comment]
Got it, I am sorry to write here. I shared my question on ethereum.stackexchange (https://ethereum.stackexchange.com/q/28062/4575). As I understand current ethminer binary won't do Ethash CPU mining. I have a private network, and I only have CPU machines so I need to do figure out how to do mining using `ethminer` on cpu machines, I am not looking for any profit out of it.

I will try to find older ethminer client that accepts -C/CPU flag.

Thank you for your valuable response. @bmatthewshea

**Comment by bmatthewshea** [comment]
Yeah, if you got a ton of machines to run it on and don't care too much about electrical costs - CPU mining would still be okay and bank you some coin.
Not the case here, though. My LAN nothing but old CPU and >my< electricity.. lol..
See what newest Nicehash app wants to run against your CPU(s) device. (Miner will probably be in 3rd party apps in parent nicehash folder). If you have trouble with main version try the 'legacy' version of same.

**Comment by 5chdn** [comment]
+1 for reopening this issue. I'm also looking for a CPU miner that is capable of Ethash.

Actually, I'm surprised this feature was actively removed from ethminer. I understand it's not feasible to mine Ethereum with CPU, but there are a lot of valid use-cases to use a stand-alone Ethash CPU-miner on any other Ethash PoW network, esp. testnets and private nets.

Please, consider re-enabling CPU mining for ethminer.

**Comment by avatar-lavventura** [comment]
@5chdn is point should be considered: 

> Please, consider re-enabling CPU mining for ethminer.

- Is there any update or progress on this issue?

**Comment by avatar-lavventura** [comment]
@carmelo12341 `geth ` cannot join into a mining pool.
