### ISSUE TITLE
Mining is not working with ethminer

### ISSUE THREAD

**Issue by 303benjamin** [ethereum-mining/ethminer#504]
Hello i tried to start mining but it is not working. This is what i see:

C:\Program Files\Etherminer\bin>setx GPU_FORCE_64BIT_PTR 0

ERFOLGREICH: Angegebener Wert wurde gespeichert.

C:\Program Files\Etherminer\bin>setx GPU_MAX_HEAP_SIZE 100

ERFOLGREICH: Angegebener Wert wurde gespeichert.

C:\Program Files\Etherminer\bin>setx GPU_USE_SYNC_OBJECTS 1

ERFOLGREICH: Angegebener Wert wurde gespeichert.

C:\Program Files\Etherminer\bin>setx GPU_MAX_ALLOC_PERCENT 100

ERFOLGREICH: Angegebener Wert wurde gespeichert.

C:\Program Files\Etherminer\bin>setx GPU_SINGLE_ALLOC_PERCENT 100

ERFOLGREICH: Angegebener Wert wurde gespeichert.

C:\Program Files\Etherminer\bin>ethminer.exe -G -S eu2.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x73e554cC02A5aD4bedb536Da752b3e7faEE2234D.B-Homebase
  i  22:01:01|main      Found suitable OpenCL device [ Bristol Ridge ] with 2146697216  bytes of GPU memory
  i  22:01:01|main      Connecting to stratum server eu2.ethermine.org:4444
  i  22:01:01|stratum   Connected to stratum server eu2.ethermine.org : 4444
  i  22:01:01|stratum   Starting farm
 cl  22:01:01|cl-0      No work. Pause for 3 s.
  i  22:01:01|stratum   Subscribed to stratum server
  i  22:01:01|stratum   Authorized worker 0x73e554cC02A5aD4bedb536Da752b3e7faEE2234D.B-Homebase
  i  22:01:01|stratum   Received new job #010c38ef  seed: #a92afa474bb50595e467a1722ed7a74f  target: #0000000112e0be826d694b2e
  m  22:01:03|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  i  22:01:03|stratum   Received new job #eddc5008  seed: #a92afa474bb50595e467a1722ed7a74f  target: #0000000112e0be826d694b2e
 cl  22:01:04|cl-0      New work: header #eddc5008ÔÇª target 0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba
 cl  22:01:04|cl-0      New seed #a92afa47ÔÇª
  m  22:01:05|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  22:01:06|cl-0      Platform: AMD Accelerated Parallel Processing
 cl  22:01:07|cl-0      Device:   Bristol Ridge  / OpenCL 2.0 AMD-APP (2527.7)
  m  22:01:07|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  22:01:08|cl-0      Build info:
 cl  22:01:08|cl-0      Creating light cache buffer, size 38009792
 cl  22:01:08|cl-0      Creating DAG buffer, size 2432695424
  X  22:01:08|cl-0      Creating DAG buffer failed: clCreateBuffer -61
  X  22:01:08|cl-0      OpenCL Error: clEnqueueWriteBuffer -38
  m  22:01:09|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  22:01:11|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  22:01:13|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  22:01:15|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  i  22:01:17|stratum   Received new job #094df8f0  seed: #a92afa474bb50595e467a1722ed7a74f  target: #0000000112e0be826d

This is what is in my .bat:

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe -G -S eu2.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x73e554cC02A5aD4bedb536Da752b3e7faEE2234D.B-Homebase

My Graphic Card is a AMD Radeon R7

Anybody has a clue? Thanks for help

**Comment by MariusVanDerWijden** [comment]
Your gpu has 2146697216 bytes of GPU memory (2GB)
At the current dag size you need at least 3GB (2432695424)
You can however mine different ethash-based coins with ethminer

**Comment by 303benjamin** [comment]
Thank you for you answer. I am a noob in these things but my system tells me that there should be gpu with 4291 MB (35151872 bytes). How comes the difference?
