### ISSUE TITLE
RPC API eth-proxy

### ISSUE THREAD

**Issue by mamashin** [ethereum-mining/ethminer#505]
Hello.
Run with cmd:
`ethminer --api-port 3333 --opencl --farm-recheck 400 -SP 1 -F http://eth-proxy:8080/rig-01`

and get stat:

` echo '{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}' | nc localhost 3333
{"id":0,"jsonrpc":"2.0","result":["0.13.0rc2","18","208176;65;0","25104;26328;26328;25191;26328;0;26328;26328;26241","0;0;0","off;off;off;off;off;off;off;off;off","45;60; 48;60; 47;60; 45;60; 48;60; 26;60; 46;60; 46;60; 48;60","","0;0;0;0"]}`

Missed info about proxy server host:port, just only "".

**Comment by jean-m-cyr** [comment]
@mamashin Should be fixed now...

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
