### ISSUE TITLE
libethash-cl: getting rid of bin2h.cmake

### ISSUE THREAD

**Issue by EoD** [ethereum-mining/ethminer#507]
The idea is from:
https://github.com/ethereum-mining/ethminer/blob/931d6ca03c0bf5091c858aaa4fe6ea9a86d7f077/libethash-cl/CLMiner.cpp#L462

If we were to use C++ string literals instead of this ugly ``bin2h.cmake``, we would have to add an ``R"abc(`` at the beginning of each OpenCL kernel (and ``)abc"`` at the end).

``CLMiner_kernel.cl`` would then look similar to:
```
R"xxx( 
#define OPENCL_PLATFORM_UNKNOWN 0
#define OPENCL_PLATFORM_NVIDIA  1
#define OPENCL_PLATFORM_AMD     2
#define OPENCL_PLATFORM_CLOVER  3

...
)xxx"
```

While it would save a lot of (very) complex build code and hence make it more robust, it might very likely break syntax highlighting on some editors.

* Can anyone confirm that it does break syntax highlighting? 
* Would we still go ahead and use it, even if it breaks syntax highlighting?

@jean-m-cyr @chfast @goobur you seem to be the only active contributors to libethash-cl at the moment.

**Comment by chfast** [comment]
How about adding `R"xxx( ` by cmake?

**Comment by EoD** [comment]
If we add this via cmake, we would reduce the complexity inside ``bin2h.cmake``, but we can not get rid of this and all the related stuff:
https://github.com/ethereum-mining/ethminer/blob/931d6ca03c0bf5091c858aaa4fe6ea9a86d7f077/libethash-cl/CMakeLists.txt#L4-L14

If we add the ``R"xxx(`` to the cl files, we can remove **all** the CMake related stuff and just put the following lines into the ``CLMiner.cpp``:
```c++
string kernel_code = 
#include CLMiner_kernel.cl
;
```

**Comment by chfast** [comment]
I understand, but making and reviewing any change in a file being a very long string literal will be very painful.
