### ISSUE TITLE
Access to the API from localhost only?

### ISSUE THREAD

**Issue by julianpoemp** [ethereum-mining/ethminer#508]
Could it be possible that the ethminer API is not accessible from another host? Can we access the API only from localhost?

I try to create a website to send requests to the ethminer api using a specific port. The website is hosted on another server. All firewall settings are done.

If I send requests to the API I get no response. It's just pending (net::ERR_CONNECTION_TIMED_OUT)

**Comment by smurfy** [comment]
It uses raw TCP not http (so you cant use your browser)
Also its open for all hosts

**Comment by julianpoemp** [comment]
@smurfy , thanks for your reply. Could you explain what the API is good for, please? Just for communication between apllications which uses raw Sockets?
Why do you use Raw TCP and not something like JSON RPC (as Geth)?

**Comment by smurfy** [comment]
Its actually JSON RPC, just like geth.

**Comment by julianpoemp** [comment]
Geth uses JSON RPC that is accessible via HTTP requests. Why are you using raw TCP sockets?

Do you know any workaround to make it possible to call the API via HTTP?

**Comment by smurfy** [comment]
for one http has quite an overhead, also it would need more dependencies, which currently not work. ``microhttpd``  (in our case)

**Comment by julianpoemp** [comment]
@smurfy, thank you.

**Comment by spartacusxxxxxx** [comment]
https://www.npmjs.com/package/ethminer-http-api
