### ISSUE TITLE
OSX Install

### ISSUE THREAD

**Issue by anteksiler** [ethereum-mining/ethminer#51]
Is there a quick tutorial on using ethminer on OSX?

**Comment by chfast** [comment]
Download the latest executable and run it. https://github.com/ethereum-mining/ethminer/releases/tag/v0.10.0.

**Comment by nerle** [comment]
Using the binary I use -G at iMac with AMD Radeon R9 M295X 4096 MB I get PoWhash with 1.8 MH/s until 2.7 MH/s but I though I could get values around 40 MH/s. Or do I something wrong?

**Comment by vapor99** [comment]
Same problem here.  I have a Gigabyte gtx 1080 and my hashrate is 2.2 MH/s (using opencv as cuda option will not compile on High Sierra) when it should be in the 40's.

**Comment by avatar-lavventura** [comment]
I face with the following warning: "CPU mining is no longer supported in this miner. Use -G (opencl) or -U (cuda) flag to select GPU platform".
