### ISSUE TITLE
0.13.0rc3 compile error Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1

### ISSUE THREAD

**Issue by goodman3654** [ethereum-mining/ethminer#511]
Hi

I've been facing a very strange issue at ethminer0.13.0rc3, vs2015 on win7 64.

error message:
Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1。 [C:\Users\Administrator\D ocuments\Visual Studio 2015\Projects\ethminer-0.13.0rc3\build\libethash-cuda\ethash-c uda.vcxproj

build comannds:
mkdir build
cd build
cmake -G "Visual Studio 14 2015 Win64" .. -DETHASHCUDA=ON
cmake --build . --config Release

build ethminer 0.12.0 with no error, but since 0.13.0rc1 this error occured.
need some help, thanks.

**Comment by janbernloehr** [comment]
Can you check whether there is an additional error further up in the chain? The exit code 1 is not very informative and just says that a previous error occured.

**Comment by goodman3654** [comment]
I checked all log in the chain. There is only one error message "MSB6006: "cmd.exe" exited with code 1" like above. I googled this error and tried every solution,  no one works.

**Comment by smurfy** [comment]
Do you have cuda 9.0+ ?  I only know a similiar error if i try compile it with vs 2017

**Comment by janbernloehr** [comment]
@goodman3654 I would advise you to upload the log to pastebin, then.

**Comment by jean-m-cyr** [comment]
9.0 is ok with vs2017.

9.1 is incompatible. But only with the latest community update. VS 2017 is ok with CUDA 9.1 if you stay at update 1. Do not upgrade to update 2!

**Comment by goodman3654** [comment]
Finally I upgrade cuda from 8.0 to 9.1.85. This error disappeared!

Thanks for helping.

**Comment by CongliWANG** [comment]
@jean-m-cyr I am suffering from this incompatibility. And it would be highly appreciated if you could kindly provide any reference to your claim. Thanks!

**Comment by jean-m-cyr** [comment]
@CongliWANG Google is your friend

cuda 9.1 incompatible with vs 2017 update 2

**Comment by CongliWANG** [comment]
@jean-m-cyr Thanks I now got it.
