### ISSUE TITLE
Strange hashrate and no-shares

### ISSUE THREAD

**Issue by destroyerisko** [ethereum-mining/ethminer#514]
Hi Guys,

I have GTX1050Ti Asus ROG strix 4gb and i was using claymore with stable 14,3Mh/s on nanopool ETH.. I spent some time today to setup ethminer and tried versions v11 / v12 and 13rc3. I tried different setups in .bat file but this setting made me confused

ethminer.exe -U --cuda-parallel-hash 4 --cuda-streams 24 -S eth-eu1.nanopool.org:9999 --report-hashrate -O wallet.miner/mail --farm-recheck 2000

im getting stable 25-27 mhs but not getting a single solution / share found 0shares in more than 2 hours with different settings of cuda streams and parallel hash (also i believe that this speed is unreal and cannot be true)

  m  20:44:24|main      Speed  25.17 Mh/s    gpu/0 25.17  [A0+0:R0+0:F0] Time: 00:00
  m  20:44:26|main      Speed  25.18 Mh/s    gpu/0 25.18  [A0+0:R0+0:F0] Time: 00:00
  m  20:44:28|main      Speed  25.18 Mh/s    gpu/0 25.18  [A0+0:R0+0:F0] Time: 00:00
Even when i lower the cuda streams parameter, non of shares are being found.

GPUTweak OC stats : 
GPU Core Clock 1613Mhz (1493+120Mhz)
Memory Clock 8278 Mhz (7008+1270Mhz)

I also tried this miner with my GTX1060 and set it up to 27-29 Mh/s but getting only 8-10 shares/hour - compare to claymore single mining, i got 20+ /hour

Without any modification of cuda stuff within the .bat file, im getting -1Mhs less than on Claymore, and not very sure regarding accepted shares.

Im wondering If there is a bug in this or my settings are wrong. 

As i read, ethminer should be better for single mining with nvidia GPUs compared to claymore which was the reason i wanted to get this work.

I would appreciate any help, meanwhile i switched back to claymore ..

**Comment by ddobreff** [comment]
can you try to remove --cuda-streams 24 and add --cuda-grid-size 4096

**Comment by chuyennm** [comment]
I have using 13rc3, 13rc4 run with config:

ethminer.exe --farm-recheck 4000 -G -S eu1-etc.ethermine.org:4444 -O mywall.worker

why reported hashrate from: https://etc.ethermine.org/miners/my_wallet is empty

![image](https://user-images.githubusercontent.com/767746/34657815-af4703da-f45c-11e7-8995-ebb0f963a4cf.png)

Another problem that hashrate report compare with claymore is down 2-3 MH per card , like from 30MH -> 27MH with the same driver, mod., OS .

**Comment by destroyerisko** [comment]
@ddobreff 
> can you try to remove --cuda-streams 24 and add --cuda-grid-size 4096

Hi ddobreff, Thank you very much ! I tried your tip and it is working with GTX1050Ti now, i have the same hashrate as on claymore (14,3) - not an increase but getting shares properly :)

Can you please also advise what should i put there in case of  MSI Armor GTX 1060 6GB ? Should i also remove "--cuda-streams xy" and put "--cuda-grid-size 6144" instead ?

@chuyennm 
Hi, in my case this helped with reported hashrate "--stratum-protocol 1 --report-hashrate" ..

**Comment by jean-m-cyr** [comment]
My 1060s work with the defaults (neither streams nor grid-size specified).

I'm surprised that your 1050 doesn't work that way as well. I don't think --cuda-streams=24 made much sense. How did you come up with that number?

**Comment by ZiDanRO** [comment]
From my experience the best way to run ethminer is like this:

`ethminer.exe --farm-recheck 4000 -G -S eu1-etc.ethermine.org:4444 -O mywall.worker --cuda-parallel-hash 4  --cuda-grid-size 4096`

if you what your HR reported to the pool (but is useless, no gain from this) you need to do this

`ethminer.exe --farm-recheck 4000 -G -S eu1-etc.ethermine.org:4444 -O mywall.worker -RH --cuda-parallel-hash 4  --cuda-grid-size 4096`

And for best berformance try 0.13rc1. Until now i see only HR lost with rc2 and rc3, now i test rc4, but i didn't see the same HR like rc1 maybe worst. In a few hours i will be convinced. I speak only on the CUDA mining, on OpenCL maybe the last versions are better, but not optimal for nVidia mining.
Test it and write your experience!

**Comment by destroyerisko** [comment]
@jean-m-cyr 
i had cuda-streams 24 setting from some forum talk i browsed, where people used even 16 / 32 etc and were happy with that.. with that i reported 25mhs but no shares so yes it actually really doesnt make sense for me, but with tip from ddobreff im all ok now.

regarding gtx1060, how much Mhs are you getting with the default setting ? i got 1-3mhs less than with adding the cuda stuff - im able to get 23 with it.


@ZiDanRO 
Thank you, once i get home i will try the 0.13rc1 and let you know

**Comment by chuyennm** [comment]
Thank @destroyerisko 
still one problem: 
**run ethminer 0.13rc3,4:** 
ethminer.exe --stratum-protocol 1 --report-hashrate --api-port 3333 -G -RH -S eu1-etc.ethermine.org:4444 -O mywallet --farm-recheck 5000  -FS us1-etc.ethermine.org:4444 --cl-local-work 256 --cl-global-work 16384 --cl-parallel-hash 2

m 03:09:56|main Speed 168.31 Mh/s gpu/0 28.08 gpu/1 28.08 gpu/2 28.16 gpu/3 28.08 gpu/4 27.92 gpu/5 28.00 [A30+0:R0+0:F0] Time: 00:13

**run claymore:**
ETH - Total Speed: 181.409 Mh/s, Total Shares: 40, Rejected: 0, Time: 00:20
ETH: GPU0 30.229 Mh/s, GPU1 30.237 Mh/s, GPU2 30.238 Mh/s, GPU3 30.226 Mh/s, GPU4 30.240 Mh/s, GPU5 30.239 Mh/s

Any config on ethminer for better hashrate? same card, same mod , same OS . thankyou.

**Comment by smurfy** [comment]
you could try ``--cl-kernel 1`` as far as i know the "unstable" kernel runs good/faster on Ellesmere cards

**Comment by jean-m-cyr** [comment]
> And for best berformance try 0.13rc1. Until now i see only HR lost with rc2 and rc3, now i test rc4, but i didn't see the same HR like rc1 maybe worst. In a few hours i will be convinced. I speak only on the CUDA mining,

@ZiDanRO Rc2 had a bug that failed to count the hashes for any found share. Reported low hash rate. RC3 had a memory leak that would over time lead to an out-of-memory failure.

Looking forward to your RC4 results.

**Comment by ZiDanRO** [comment]
@jean-m-cyr 3 rigs with 222mh/s reported on rc1 i get average HR between 220 and 230mh/s on ethermine.org. The rig 4 had 230mh reported on the pool on rc1, after i switched to rc4 the average droped to 215MH/s in 6 hours and it seems is going below that, but now i stopped it. While the rest of the rigs are still higher than 220MH/s

**Comment by bmatthewshea** [comment]
@jean-m-cyr 

"--stratum-protocol=1 is the default, you don't need to specify it."

Actually according to `--help` the default is '0'.
And to report hashrate, at least at nanopool, the help also states you must use:
`-SP 1` to use `-RH` (or -`-stratum-protocol 1 --report-hashrate` )
And indeed you do. I do not get it reported otherwise.

**Comment by jean-m-cyr** [comment]
My apologies. I jumped to the conclusion that --stratum-protocol 1 meant use stratum version 1, which is in fact the default. You are correct .

**Comment by bmatthewshea** [comment]
@jean-m-cyr
No problem! - I kind of figured you meant the --stratum-client (1 is default).
I just didn't want anyone getting a quick headache due to that previous post. lol

**Comment by bmatthewshea** [comment]
@mihaipopescu3 
 `ethminer -SP 1 -RH `.......

**Comment by jean-m-cyr** [comment]
The only valid values for cuda-streams are 1,2,4, or 8

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
