### ISSUE TITLE
warning: deleting ‘volatile void*’ is undefined [-Wdelete-incomplete]

### ISSUE THREAD

**Issue by cyfex** [ethereum-mining/ethminer#52]
When compiling, such warning came out.

> [ 89%] Building CXX object libethcore/CMakeFiles/ethcore.dir/EthashCUDAMiner.cpp.o
> /home/xxxxxxx/ethminer/ethminer/libethcore/EthashCUDAMiner.cpp: In member function ‘virtual void dev::eth::EthashCUDAMiner::workLoop()’:
> /home/xxxxxxx/ethminer/ethminer/libethcore/EthashCUDAMiner.cpp:190:15: warning: deleting ‘volatile > void*’ is undefined [-Wdelete-incomplete]
>       delete[] s_dagInHostMemory;
               ^
> [ 92%] Linking CXX static library libethcore.a

I'm concerned if it will cause memory leakage. Thanks

**Comment by EoD** [comment]
@cyfex 
What compile flags did you use? 
Can you reproduce this with a current version of ethminer? 

There have been quite some changes in the last couple of weeks: https://github.com/ethereum-mining/ethminer/commits/master/libethcore/EthashCUDAMiner.cpp
