### ISSUE TITLE
Hashrate low most of the time

### ISSUE THREAD

**Issue by dglobenko** [ethereum-mining/ethminer#520]
MSI Radeon rx480 4gb & 3 rx470 nitro before gives me ~24 MH in stock bios but after the issue with nicehash happend my hashrate start jumping and now in gives 19MH and then in changes back to 24. 24MHs works only 10% of time and 90% in 19MH.

It happens after miner setting DAG epoch #6 and shows 24 than it change to DAG epoch #162 and shows 19

How I can solve it and make hashrate stable in 24MH?
Thanks

**Comment by ddobreff** [comment]
if you are on linux read carefully on AMD site how to set fragment_size, or if you are using windows install blockchain compute drivers.

**Comment by dglobenko** [comment]
Thanks, but will it works with mod bios?
