### ISSUE TITLE
CUDA error in func 'init' at line 245 : out of memory.

### ISSUE THREAD

**Issue by EnricoSx** [ethereum-mining/ethminer#524]
`**./ethminer --dag-load-mode single 0 --farm-recheck 200 -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O xxxx.RigEnrico** 
 cu  13:46:33|ethminer  Using grid size 8192 , block size 128
  ℹ  13:46:33|ethminer  Connecting to stratum server eu1.ethermine.org:4444
  ℹ  13:46:33|stratum   Connected to stratum server eu1.ethermine.org : 4444
  ℹ  13:46:33|stratum   Starting farm
  ℹ  13:46:33|stratum   Subscribed to stratum server
  ℹ  13:46:33|stratum   Authorized worker xxxxxxxx.RigEnrico
  ℹ  13:46:33|stratum   Received new job #40f2b298
  ℹ  13:46:33|CUDA0     set work; seed: #a92afa47, target:  #0000000112e0
  ℹ  13:46:33|CUDA0     Initialising miner...
  m  13:46:33|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  13:46:33|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  13:46:33|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  13:46:33|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  13:46:34|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  13:46:34|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  13:46:34|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  13:46:34|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  13:46:34|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  13:46:35|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  13:46:35|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  13:46:35|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  13:46:35|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cu  13:46:35|CUDA0     Using device: GeForce GT 710  (Compute 3.5)
CUDA error in func 'init' at line 245 : out of memory.
Errore di segmentazione (core dump creato)
`

`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.34                 **Driver Version: 387.34**                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  **GeForce GT 710**      Off  | 00000000:01:00.0 N/A |                  N/A |
| 40%   28C    P0    N/A /  N/A |    303MiB /   978MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
`

**- i just set swap file to 20GB
- Kubuntu 17 64bit
- Linux pc-enrico 4.13.0-21-generic 64 GNU/Linux**

**Comment by jasonwee** [comment]
gpu memory is insufficient, not the system memory

https://www.geforce.com/hardware/desktop-gpus/geforce-gt-710/specifications

**Comment by MariusVanDerWijden** [comment]
You need at least 3GB V-ram to mine ethereum 
https://investoon.com/tools/dag_size
