### ISSUE TITLE
CUDA error: No CUDA driver found with 0.13.0RC4

### ISSUE THREAD

**Issue by JasonGu1988** [ethereum-mining/ethminer#526]
Hi,

I have 6 GTX 1060 running fine with 0.12.0, but when I try 0.13.0RC4 it doesn't start. and -U --list-devices gives me 
CUDA error: No CUDA driver found

driver version: 372.70 Win7

Thanks,

**Comment by nnaricom** [comment]
Have you tried other drivers?

**Comment by JasonGu1988** [comment]
Tried with the latest version, Windows 7 entering repairing mode somehow...

Is there a recommended driver version to use? I’m aware i’m very behind in driver version, but it’s stable at this moment.

**Comment by chfast** [comment]
It is built with CUDA 9. I'm not sure what driver is needed. Ask Nvidia.

**Comment by JasonGu1988** [comment]
Thanks.

**Comment by pmgriphone** [comment]
I have the same problem on Windows 10. Any resolution on what driver needs to be installed?
