### ISSUE TITLE
--cl-parallel-hash clarification

### ISSUE THREAD

**Issue by sgerbino** [ethereum-mining/ethminer#527]
Hello,

I've been using ethminer tracking master branch. A recent update introduced this commit:

f8d20e564a5634e1010d633c4ab7ab74c764f91c

Without the ability to set cl-parallel-hash I lose around 3-5 MH/s.

Can someone shed some light on the issue this is meant to resolve?

**Comment by sgerbino** [comment]
Update:

The commit:
4b18e91d592b2083d160fe0e115249b78ba6e32a
Explains a bit further, that a command line parameter was added.
So it seems the "unstable" kernel derived from sgminer is giving me better performance personally.
If you are also experiencing this issue after updating your repository, you want to add --cl-kernel 1 to your call to ethminer.

I'd still like to learn more about this if anyone can provide more information. What exactly makes this kernel "unstable"? Using this kernel I get about 20 MH/s more over 6 GPUs.

**Comment by alptolga** [comment]
@sgerbino 
Can you share your full parameters to start ethminer?

**Comment by sgerbino** [comment]
ethminer --farm-recheck 200 --report-hashrate --api-port -3333 --cl-kernel 1 --cl-local-work 256 --cl-global-work 32768 --cl-parallel-hash 2 -G -S us1.ethermine.org:4444 -FS eu1.ethermine.org:4444 -O <eth_address>.<miner>

**Comment by alptolga** [comment]
@sgerbino 
Thank you
