### ISSUE TITLE
windows nvidia driver 390.65

### ISSUE THREAD

**Issue by satori-q3a** [ethereum-mining/ethminer#529]
just a heads up on nvidia driver 390.65, when running ethminer while using one of it's cards as the desktop renderer, the desktop glitches on apps and causes ethminer to hang without you realizing it.

driver 388.71 is stable and does not have these problems.

another machine dedicated to mining, uses the intel HD graphics for the desktop and ethminer is stable on it with 390.65.

**Comment by jasonwee** [comment]
hmm.. intel hd graphics can do mining too? share more detail please.

**Comment by satori-q3a** [comment]
No, Intel does not have direct cuda support for their devices.  I use the intel graphics strictly as a dedicated windows desktop renderer.  This allows the nividia cards to run cuda applications without any windows overhead affecting them.

Tho, the intel graphics are pretty competent in terms of 4K display handling and video playback.

**Comment by DeadManWalkingTO** [comment]
The 1st GPU used by Windows GUI so drop hashrate. If you have an additional GPU on your system as primary GPU the GUI use that GPU and everything works fine.
