### ISSUE TITLE
CUDA0     No work. Pause for 3 s.

### ISSUE THREAD

**Issue by ThomsonW** [ethereum-mining/ethminer#536]
hi guys,i install the ethminer and run

> $ ethminer -M
  i  12:18:16|ethminer  Found suitable OpenCL device [ GeForce GTX 1080 Ti ] with 11715084288  bytes of GPU memory
Benchmarking on platform: CUDA
Preparing DAG for block #0
Warming up...
Trial 1... 0
Trial 2... 0
Trial 3... 0
Trial 4... 0
Trial 5... 0
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Aborted (core dumped)

and 

> $ ethminer -G -M
  i 12:17:00|ethminer  Found suitable OpenCL device [ GeForce GTX 1080 Ti ] with 11715084288  bytes of GPU memory
Benchmarking on platform: CL
Preparing DAG for block #0
 cl  12:17:00|cl-0      No work. Pause for 3 s.
 cl  12:17:00|cl-1      No work. Pause for 3 s.
 cl  12:17:00|cl-2      No work. Pause for 3 s.
 cl  12:17:00|cl-3      No work. Pause for 3 s.
Warming up...
 cl  12:17:03|cl-0      New work: header #50c856ae… target 0000000000000002000000000000000000000000000000000000000000000000
 cl  12:17:03|cl-0      New seed #00000000…
 cl  12:17:03|cl-2      New work: header #50c856ae… target 0000000000000002000000000000000000000000000000000000000000000000
 cl  12:17:03|cl-2      New seed #00000000…
 cl  12:17:03|cl-1      New work: header #50c856ae… target 0000000000000002000000000000000000000000000000000000000000000000
 cl  12:17:03|cl-1      New seed #00000000…
 cl  12:17:03|cl-3      New work: header #50c856ae… target 0000000000000002000000000000000000000000000000000000000000000000
 cl  12:17:03|cl-3      New seed #00000000…
 cl  12:17:04|cl-0      Platform: NVIDIA CUDA
 cl  12:17:04|cl-2      Platform: NVIDIA CUDA
 cl  12:17:04|cl-3      Platform: NVIDIA CUDA
 cl  12:17:04|cl-1      Platform: NVIDIA CUDA
 cl  12:17:04|cl-2      Device:   GeForce GTX 1080 Ti  / OpenCL 1.2 CUDA
 cl  12:17:04|cl-0      Device:   GeForce GTX 1080 Ti  / OpenCL 1.2 CUDA
 cl  12:17:04|cl-3      Device:   GeForce GTX 1080 Ti  / OpenCL 1.2 CUDA
 cl  12:17:04|cl-1      Device:   GeForce GTX 1080 Ti  / OpenCL 1.2 CUDA
 cl  12:17:05|cl-3      OpenCL kernel: Stable kernel
 cl  12:17:05|cl-3      Build info: 
 cl  12:17:05|cl-3      Creating light cache buffer, size 16776896
 cl  12:17:05|cl-3      Creating DAG buffer, size 1073739904
 cl  12:17:05|cl-3      Loading kernels
 cl  12:17:05|cl-3      Writing light cache buffer
 cl  12:17:05|cl-3      Creating buffer for header.
 cl  12:17:05|cl-3      Creating mining buffer
 cl  12:17:05|cl-3      Generating DAG
 cl  12:17:05|cl-0      OpenCL kernel: Stable kernel
 cl  12:17:05|cl-0      Build info: 
 cl  12:17:05|cl-0      Creating light cache buffer, size 16776896
 cl  12:17:05|cl-0      Creating DAG buffer, size 1073739904
 cl  12:17:05|cl-0      Loading kernels
 cl  12:17:05|cl-0      Writing light cache buffer
 cl  12:17:05|cl-0      Creating buffer for header.
 cl  12:17:05|cl-0      Creating mining buffer
 cl  12:17:05|cl-0      Generating DAG
 cl  12:17:05|cl-2      OpenCL kernel: Stable kernel
 cl  12:17:05|cl-2      Build info: 
 cl  12:17:05|cl-2      Creating light cache buffer, size 16776896
 cl  12:17:05|cl-2      Creating DAG buffer, size 1073739904
 cl  12:17:05|cl-2      Loading kernels
 cl  12:17:05|cl-2      Writing light cache buffer
 cl  12:17:05|cl-1      OpenCL kernel: Stable kernel
 cl  12:17:05|cl-2      Creating buffer for header.
 cl  12:17:05|cl-2      Creating mining buffer
 cl  12:17:05|cl-2      Generating DAG
 cl  12:17:05|cl-1      Build info: 
 cl  12:17:05|cl-1      Creating light cache buffer, size 16776896
 cl  12:17:05|cl-1      Creating DAG buffer, size 1073739904
 cl  12:17:05|cl-1      Loading kernels
 cl  12:17:05|cl-1      Writing light cache buffer
 cl  12:17:05|cl-1      Creating buffer for header.
 cl  12:17:05|cl-1      Creating mining buffer
 cl  12:17:05|cl-1      Generating DAG
 cl  12:17:06|cl-3      DAG 0 %
 cl  12:17:06|cl-0      DAG 0 %
 cl  12:17:06|cl-2      DAG 0 %
 cl  12:17:06|cl-1      DAG 0 %
 cl  12:17:06|cl-3      DAG 6 %
 cl  12:17:06|cl-0      DAG 6 %
 cl  12:17:06|cl-2      DAG 6 %
 cl  12:17:06|cl-1      DAG 6 %
 cl  12:17:06|cl-3      DAG 12 %
 cl  12:17:06|cl-0      DAG 12 %
 cl  12:17:06|cl-2      DAG 12 %
 cl  12:17:06|cl-1      DAG 12 %
 cl  12:17:06|cl-3      DAG 18 %
 cl  12:17:06|cl-0      DAG 18 %
 cl  12:17:06|cl-2      DAG 18 %
 cl  12:17:06|cl-1      DAG 18 %
 cl  12:17:07|cl-3      DAG 25 %
 cl  12:17:07|cl-0      DAG 25 %
 cl  12:17:07|cl-2      DAG 25 %
 cl  12:17:07|cl-1      DAG 25 %
 cl  12:17:07|cl-3      DAG 31 %
 cl  12:17:07|cl-0      DAG 31 %
 cl  12:17:07|cl-2      DAG 31 %
 cl  12:17:07|cl-1      DAG 31 %
 cl  12:17:07|cl-3      DAG 37 %
 cl  12:17:07|cl-0      DAG 37 %
 cl  12:17:07|cl-2      DAG 37 %
 cl  12:17:07|cl-1      DAG 37 %
 cl  12:17:07|cl-3      DAG 43 %
 cl  12:17:07|cl-0      DAG 43 %
 cl  12:17:07|cl-2      DAG 43 %
 cl  12:17:07|cl-1      DAG 43 %
 cl  12:17:08|cl-3      DAG 50 %
 cl  12:17:08|cl-0      DAG 50 %
 cl  12:17:08|cl-2      DAG 50 %
 cl  12:17:08|cl-1      DAG 50 %
 cl  12:17:08|cl-3      DAG 56 %
 cl  12:17:08|cl-0      DAG 56 %
 cl  12:17:08|cl-2      DAG 56 %
 cl  12:17:08|cl-1      DAG 56 %
 cl  12:17:08|cl-3      DAG 62 %
 cl  12:17:08|cl-0      DAG 62 %
 cl  12:17:08|cl-2      DAG 62 %
 cl  12:17:08|cl-1      DAG 62 %
 cl  12:17:08|cl-3      DAG 68 %
 cl  12:17:09|cl-0      DAG 68 %
 cl  12:17:09|cl-2      DAG 68 %
 cl  12:17:09|cl-1      DAG 68 %
 cl  12:17:09|cl-3      DAG 75 %
 cl  12:17:09|cl-0      DAG 75 %
 cl  12:17:09|cl-2      DAG 75 %
 cl  12:17:09|cl-1      DAG 75 %
 cl  12:17:09|cl-3      DAG 81 %
 cl  12:17:09|cl-0      DAG 81 %
 cl  12:17:09|cl-2      DAG 81 %
 cl  12:17:09|cl-1      DAG 81 %
 cl  12:17:09|cl-3      DAG 87 %
 cl  12:17:09|cl-0      DAG 87 %
 cl  12:17:09|cl-2      DAG 87 %
 cl  12:17:09|cl-1      DAG 87 %
 cl  12:17:10|cl-3      DAG 93 %
 cl  12:17:10|cl-3      Switch time 9895 ms / 6896011 us
 cl  12:17:10|cl-0      DAG 93 %
 cl  12:17:10|cl-0      Switch time 9937 ms / 6938676 us
 cl  12:17:10|cl-2      DAG 93 %
 cl  12:17:10|cl-2      Switch time 9946 ms / 6946676 us
 cl  12:17:10|cl-1      DAG 93 %
 cl  12:17:10|cl-1      Switch time 9959 ms / 6960233 us
Trial 1... 115187134
Trial 2... 128448461
Trial 3... 128448461
Trial 4... 128448461
Trial 5... 128448461
  ✘  12:17:30|cl-0      OpenCL Error: clEnqueueNDRangeKernel: CL_INVALID_KERNEL_ARGS (-52)
  ✘  12:17:42|cl-1      OpenCL Error: clEnqueueNDRangeKernel: CL_INVALID_KERNEL_ARGS (-52)
Segmentation fault (core dumped)

and when i run 

>$ ethminer --farm-recheck 2000 -U -S eth.f2pool.com:8008 -FS eth.f2pool.com:8080 -O 0x0A3d383899C14049A986d01305C65194BaB9819d
 cu  12:21:45|ethminer  Using grid size 8192 , block size 128
  i  12:21:45|ethminer  Connecting to stratum server eth.f2pool.com:8008
Could not resolve host eth.f2pool.com:8008, Operation canceled  i  12:21:45|ethminer  Reconnecting in 3 seconds...
  i  12:21:48|ethminer  Connecting to stratum server eth.f2pool.com:8008
  i  12:21:48|stratum   Connected to stratum server eth.f2pool.com : 8008
  i  12:21:48|stratum   Starting farm
  i  12:21:48|CUDA0     No work. Pause for 3 s.
  i  12:21:48|CUDA1     No work. Pause for 3 s.
  i  12:21:48|CUDA2     No work. Pause for 3 s.
  i  12:21:48|CUDA3     No work. Pause for 3 s.

the version of my OS is ubuntu 16.04, and i have already installed cuda. there are 4 GTX 1080 Ti cards,and my GCC version is  5.4.0.
that is my cuda configuration:

> ./deviceQuery
 Starting...
 CUDA Device Query (Runtime API) version (CUDART static linking)
Detected 4 CUDA Capable device(s)
Device 0: "GeForce GTX 1080 Ti"
  CUDA Driver Version / Runtime Version          9.0 / 8.0
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 11172 MBytes (11715084288 bytes)
  (28) Multiprocessors, (128) CUDA Cores/MP:     3584 CUDA Cores
  GPU Max Clock rate:                            1582 MHz (1.58 GHz)
  Memory Clock rate:                             5505 Mhz
  Memory Bus Width:                              352-bit
  L2 Cache Size:                                 2883584 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 2 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
Device 1: "GeForce GTX 1080 Ti"
  CUDA Driver Version / Runtime Version          9.0 / 8.0
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 11172 MBytes (11715084288 bytes)
  (28) Multiprocessors, (128) CUDA Cores/MP:     3584 CUDA Cores
  GPU Max Clock rate:                            1582 MHz (1.58 GHz)
  Memory Clock rate:                             5505 Mhz
  Memory Bus Width:                              352-bit
  L2 Cache Size:                                 2883584 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 3 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
Device 2: "GeForce GTX 1080 Ti"
  CUDA Driver Version / Runtime Version          9.0 / 8.0
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 11172 MBytes (11715084288 bytes)
  (28) Multiprocessors, (128) CUDA Cores/MP:     3584 CUDA Cores
  GPU Max Clock rate:                            1582 MHz (1.58 GHz)
  Memory Clock rate:                             5505 Mhz
  Memory Bus Width:                              352-bit
  L2 Cache Size:                                 2883584 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 130 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
Device 3: "GeForce GTX 1080 Ti"
  CUDA Driver Version / Runtime Version          9.0 / 8.0
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 11172 MBytes (11715084288 bytes)
  (28) Multiprocessors, (128) CUDA Cores/MP:     3584 CUDA Cores
  GPU Max Clock rate:                            1582 MHz (1.58 GHz)
  Memory Clock rate:                             5505 Mhz
  Memory Bus Width:                              352-bit
  L2 Cache Size:                                 2883584 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 131 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
> Peer access from GeForce GTX 1080 Ti (GPU0) -> GeForce GTX 1080 Ti (GPU1) : Yes
> Peer access from GeForce GTX 1080 Ti (GPU0) -> GeForce GTX 1080 Ti (GPU2) : No
> Peer access from GeForce GTX 1080 Ti (GPU0) -> GeForce GTX 1080 Ti (GPU3) : No
> Peer access from GeForce GTX 1080 Ti (GPU1) -> GeForce GTX 1080 Ti (GPU0) : Yes
> Peer access from GeForce GTX 1080 Ti (GPU1) -> GeForce GTX 1080 Ti (GPU2) : No
> Peer access from GeForce GTX 1080 Ti (GPU1) -> GeForce GTX 1080 Ti (GPU3) : No
> Peer access from GeForce GTX 1080 Ti (GPU2) -> GeForce GTX 1080 Ti (GPU0) : No
> Peer access from GeForce GTX 1080 Ti (GPU2) -> GeForce GTX 1080 Ti (GPU1) : No
> Peer access from GeForce GTX 1080 Ti (GPU2) -> GeForce GTX 1080 Ti (GPU3) : Yes
> Peer access from GeForce GTX 1080 Ti (GPU3) -> GeForce GTX 1080 Ti (GPU0) : No
> Peer access from GeForce GTX 1080 Ti (GPU3) -> GeForce GTX 1080 Ti (GPU1) : No
> Peer access from GeForce GTX 1080 Ti (GPU3) -> GeForce GTX 1080 Ti (GPU2) : Yes

what is the problems about?

**Comment by chfast** [comment]
You just have an issue with the connection to a pool. Have you tried other pools?

**Comment by Alan-ZhangDaixi** [comment]
try -SP 1

**Comment by xushijie** [comment]
@ThomsonW  Have you succeeded to use ethminer with f2pool?

**Comment by tkalfaoglu** [comment]
I got mine to work after fixing my ethereum address :)
ethminer -U -S eu1.xxxx.org:4444 -RH  -HWMON  \
  -O ab187167212....etc.. asdasd.MyPCGPU:x  \
  --farm-recheck 2000  --cuda-noeval

**Comment by DeadManWalkingTO** [comment]
That's my launch command:
`ethminer.exe -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`
Try it with the latest miner version and feedback please.
Thank you!

**Comment by AndreaLanfranchi** [comment]
Fixed.
