### ISSUE TITLE
Older System - No OpenCL devices error for Ethminer

### ISSUE THREAD

**Issue by Finger8** [ethereum-mining/ethminer#539]
Ethminer doesnt see either my GPU or CPU and throws a No openCL devices.

Nothing I can google seems to say what the issue is. Anyone know?

I have ATI Radeon 5800 with 3829mb memory
On Win 7 64bit, with AMD Phenom II x4 processors.

**Comment by DeadManWalkingTO** [comment]
Please give the exactly launch command.

**Comment by AndreaLanfranchi** [comment]
No feedback.
