### ISSUE TITLE
RPC API drop fan and temp to 0 when DAG epoch inc

### ISSUE THREAD

**Issue by mamashin** [ethereum-mining/ethminer#540]
I'm not sure about DAG, but today all my ethminer drop to zero FAN and TEMP stats via API after 09:30 UTC 

![fan-stat](https://user-images.githubusercontent.com/2655888/34827070-01c03f48-f6ea-11e7-800c-3f589f3a3151.png)

ps some rigs woks on claymore
pps graf time UTC+3

`¯\_(ツ)_/¯`

**Comment by mamashin** [comment]
```
Jan-16-2018 09:07:31 PM +UTC
block 4919999 -> 4920000
DAG 163 -> 164
```
And problem with API stat repeated.

**Comment by smurfy** [comment]
never had the problem, but please test latest master, if problem is gone now

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!
