### ISSUE TITLE
Crush on AMD miner due to hwmonitor calls

### ISSUE THREAD

**Issue by anizotropic** [ethereum-mining/ethminer#541]
In file CLMonitor the hwmonitor initialized through creating a new handle every-time new work is initiated in "init" method through for example:
 adlh = wrap_adl_create();

**System tested on:**
6xRX580 Saphire
Asus Mining Expert
AMD Blockchain drivers
Windows 10

**Issue 1:**
Handle never gets de-allocated and contributes to memory leaks and stability over time
**Issue 2:**
The driver DLL seems to have problems with concurrent calls to initiation methods and crushes because the hw monitor is initiated in every miner worker thread

**Proposed solution:**
Move hwmonitor handles to Farm object.
Create hwmonitor handles at once farm creation and remove them at farm destruction
Pass the handles to miner workers as parameters and keep the same temperature/fan querying from miner workers.

**Comment by smurfy** [comment]
Thank you for your report, we already know about this problem and the plan is to do exactly what you proposed.

**Comment by smurfy** [comment]
please test latest master

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!
