### ISSUE TITLE
Mining with Ubuntu 16.04.4 with Radeon R9 380x slow hashrate

### ISSUE THREAD

**Issue by laurentgrangeau** [ethereum-mining/ethminer#542]
Hi,

I recently installed Ubuntu 16.04 with the latest updates (16.04.4), amdgpu-pro driver from AMD, ethminer v0.13.0rc4 and I've got very very slow hashrate.
I have now around 2Mh/s. With Ubuntu 15.10, proprietary driver, I had around 20Mh/s...

Why the mining is so slow ? Can you please help me ?

**Comment by cloudnull** [comment]
++ Seeing the same in 16.04.3 w/ kernel 4.11 running AMDGPU pro 17.50.

**Comment by MariusVanDerWijden** [comment]
Probably not related to our miner... I'm going to close it
