### ISSUE TITLE
After updating linux kernel (ubuntu 16.04.3LTS) Hashrate drop

### ISSUE THREAD

**Issue by tribalpixel** [ethereum-mining/ethminer#543]
after doing update on my linux rig 6x rx 570
i have a hashrate drop on every cards... aproximatively 5 Mh/s per cards

someone with the same problem ?

**Comment by AndreaLanfranchi** [comment]
+1 on this one.

Must also say that I am experiencing a huge increase in FAILURES Invalid result from GPUs once I have compiled the lastest commits. Do not know what is happening but I had to switch back to Claymores' which, despite the dev fee, gives me better results.

My Rig is a 6x Gtx 1070. On ethminer I cannot get more than 170 Mhs as reported by ethermine.org. Using Claymore's i get a pretty decent 189 Mhs reported.
On my console I see claymore's stable at 192.8 Mhs (ie. 32.1 per GPU) while on ethminer i cannot push cards beyond 31.1 without risking a gpu crash every 4 to 6 hours: but still I get roughly 10% of shares marked as invalid.

**Comment by rafko-sc** [comment]
I also confirm the same problem

**Comment by MariusVanDerWijden** [comment]
Thats propably because of the Meltdown-Spectre fix in the new kernel 
https://en.wikipedia.org/wiki/Meltdown_(security_vulnerability)
The fix is supposed to result in 5 - 30 % slowdown on some loads

**Comment by tribalpixel** [comment]
@MariusVanDerWijden 
for what i have understood, Meltdown-Spectre is affecting CPU not GPU...

**Comment by jean-m-cyr** [comment]
It is relatively simple to go back to an older Linux kernel on Ubuntu.

If your miners are behind a reasonably secure firewall, and you only open the API port for incoming connections (if you use the API), your miners won't have any external attack vectors other than the API port itself.

That's what I did, just in case. The spector/meltdown attacks require the initial infection of a specialized virus (which has not been seen in the wild) through some side band channel like fishing or web access.

I won't be doing much email or web browsing in my miner!

Unrelated, I get better hash rates on older kernels than I do with the 4.4 series.

**Comment by jean-m-cyr** [comment]
> for what i have understood, Meltdown-Spectre is affecting CPU not GPU...

Yes both vulnerabilities were introduced to many processor architectures (ARM, AMD, Intel, etc) about a decade ago with the introduction of speculative pre-fetch. Unfortunately, redesigning, recalling, and replacing 10 years worth of processor chips is a non-starter. So the mitigation has to be in software.

The security exposure occurs every time kernel mode, ring 0 mode, supervisor mode, or whatever it's called in any given architecture. This mode switch occurs very frequently, with every driver call and interrupt. Responsibility has fallen on all kernel providers to try to reduce or prevent the exposure each time an and everywhere they get control in privileged mode.

It is unclear at this time how well these software updates have patched the security hole created by hardware, but all have admitted with carefully worded announcements that under certain unspecified workloads there may be significant performance loss (all intentionally vague).

**Comment by jean-m-cyr** [comment]
@tribalpixel Your older kernel should still be around. You use the 'advanced' GRUB boot time selection and choose to boot any older kernel it lists.

**Comment by tribalpixel** [comment]
hello people, for all that have the same problem, i can confirm(i think) that is the linux kernel problem

resolved with:

`sudo apt-get remove linux-image-4.13.0-26-generic && sudo apt autoremove -y`
`sudo update-grub`
`sudo reboot`

i get my hasrate back ;)

**Comment by rafko-sc** [comment]
Branch **cuda-parallel-hash** working normally on kernel **4.13.0-26-generic**

**Comment by jean-m-cyr** [comment]
> Branch cuda-parallel-hash working normally on kernel 4.13.0-26-generic

4.13.0-26 is the 1st kernel with the specter/meltdown patch.

We have conflicting testimony. Some see no HR reduction, others do. I wonder what other factors are contributing?

**Comment by jasonwee** [comment]
a shot into the wild, difficulty? https://etherscan.io/chart/difficulty

**Comment by rafko-sc** [comment]
No, on ETC exists the same problem

**Comment by AndreaLanfranchi** [comment]
My 2 cents.
Same machine. Ubuntu 16 kernel 4.13.0-26.
2 rounds of 24 hours against pool ethermine.org same overclock settings on each round

1 st round with ethminer 0.13.0.dev0 : average "invalid shares" 10%. On ethermine i get effective hashrate which is 4.5 to 5.2% lower than reported hashrate. 

2 nd round with claymore's ethdcrminer64 10.0 (solo eth mode mining) : invalid shares "none". On ethermine i get effective hashrate which is 3.1 to 3.2% lower than reported hashrate (consider that 2% is dev fee)

On both rounds I get roughly the same percentage of stale shares.
Please note round 2 has come 24 hours after with slightly higher diff.

Also ... monitoring the logs i see quite often in claymores the same job finds (and submits) two very near solutions on same job. While on ethminer maybe this not happens due to this https://github.com/ethereum-mining/ethminer/issues/461

**Comment by jean-m-cyr** [comment]
> with ethminer 0.13.0.dev0

I don't see dev0 in the releases list. Is that equivalent to rc6?

**Comment by AndreaLanfranchi** [comment]
It depicts 0.13.0.dev0 the release built from sources cloned from the repository

**Comment by rafko-sc** [comment]
RC6 - I have problem:
_✘  22:16:43|CUDA1     FAILURE: GPU gave incorrect result!_
What this?

**Comment by chfast** [comment]
.dev0 is something from master branch before RC1.

**Comment by nerdralph** [comment]
The the HSA/ROCm compiler does not optimize as well as the legacy compiler.  Try -legacy.
https://github.com/ethereum-mining/ethminer/issues/565
