### ISSUE TITLE
gtx 780 3gb

### ISSUE THREAD

**Issue by mystro1213** [ethereum-mining/ethminer#544]
i used to mine on it at 21mhs now its 7 mhs
used all drivers old and new i need help
cpu i7 4770k
8gb ram
gtx 780 3gb

**Comment by ZiDanRO** [comment]
What had changed between 21 and 7mhs? You installed something, another ethermine version etc?

**Comment by jean-m-cyr** [comment]
I don't get much more than 10 with an old gtx 980 ti, so I can't see a 780 doing 21.

**Comment by arainchik** [comment]
Why is that? According to https://www.videocardbenchmark.net/high_end_gpus.html 980 and 970 should be on par with RX580, or even faster. 

Why do we see such drop in performance on 970 and 970 cards as DAG size is increasing?

**Comment by jean-m-cyr** [comment]
passmark g3d is a directx video graphic test that focuses on the card's rendering ability, more specifically vertex and pixel shading. Not a very good indicator of mining performance. I'm sure there are sites out there with more relevant info. I have an old 980 ti which I don't don't mine with since the new 10 series are nearly twice as power efficient. That card, not overclocked, would get about 10 Mh/s.

**Comment by chfast** [comment]
Can you run a simulation mode `ethminer -G -Z`? My 280X was mining with 28 Mh/s, now is doing 5 Mh/s. The DAG size affects the performance a lot.

**Comment by jean-m-cyr** [comment]
Interesting! With 'ethminer -U -Z' on the 980 I get 19Mh/S, but the same cards only reports about 9.5 Mh/S when really mining?

**Comment by chfast** [comment]
Try `ethminer -U -Z 5000000`.

**Comment by mystro1213** [comment]
chfast thanks man its works getting 21mhs/s

**Comment by chfast** [comment]
@mystro1213 what works? If you get 21 mh/s with `ethminer -U -Z 5000000` that's actually something is wrong.

**Comment by jean-m-cyr** [comment]
> Try ethminer -U -Z 5000000.
Ah ok. Adjusted DAG size.
Confirmed. With this the 980 says 9.5Mh/S... same as live.

**Comment by arainchik** [comment]
There is a dramatic difference between -U -Z 4000000 (17MHs/) and -U -Z 4500000 (11MHs/) on my 970.

I think it's somewhere betweeb 4200000 and 4300000 blocks.

When I'm looking at GPU utilization stats with "nvidia-smi pmon" you can see that with 4000000 block I get 100%  sm and men utilization, but when I do 4500000 sm stays at 100% but mem drops to 65%

Try it, run "nvidia-smi pmon" in a separate window when running different block sizes.

**Comment by ddobreff** [comment]
On older maxwell/kepler GPUs page_size or as AMD put it fragment_size is default 64kb thats why your hashrate is dropping, if you mine ethash forks with <2GB DAG you'll be fine.

**Comment by arainchik** [comment]
Block number 4,000,000 has 2.04Gb size, so it's > 2Gb, but still get's decent hash rate.

I don't understand how 64Kb page size can have any impact on that...

I'm still wondering if an updated CUDA kernel can bring back 19MH/s on 970/980s :)

**Comment by Qwertzi01** [comment]
I have the same issue with my GTX 970 4GB without OC -> benchmark AND local mining are both around 22 MH/s. But when I start mining in pools like ethermine then the performance drops to 6.5 MH/s around. I don't understand this problem!?

**Comment by arainchik** [comment]
Qwertzi01 - benchmark on current block/DAG: ethminer -U -M 4700000 or ethminer -U -Z 4700000 - you'll get the same speed you are getting in pool mining. You are benchmarking on DAG size from years ago :)

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
