### ISSUE TITLE
Apple AMD Radeon Issue

### ISSUE THREAD

**Issue by imathome** [ethereum-mining/ethminer#545]
Appears to have allocation issues regarding the memory for the DAG. Any advice?

  ℹ  23:50:50|          Found suitable OpenCL device [ Intel(R) HD Graphics 530 ] with 1610612736  bytes of GPU memory
  ℹ  23:50:50|          Connecting to stratum server eth.pool.minergate.com:45791
Could not resolve host eth.pool.minergate.com:45791, Operation canceled  ℹ  23:50:50|          Reconnecting in 3 seconds...
  ℹ  23:50:53|          Connecting to stratum server eth.pool.minergate.com:45791
  ℹ  23:50:53|stratum   Connected to stratum server eth.pool.minergate.com : 45791
  ℹ  23:50:53|stratum   Starting farm
 cl  23:50:53|cl-0      No work. Pause for 3 s.
 cl  23:50:53|cl-1      No work. Pause for 3 s.
  ℹ  23:50:53|stratum   Subscribed to stratum server
  ℹ  23:50:53|stratum   Authorized worker xxxx@xxxx.com
  ℹ  23:50:53|stratum   Received new job #fe719398
  m  23:50:54|          Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  23:50:56|          Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  23:50:56|cl-0      New work: header #fe719398… target 000010c6f7a0b5ed8d36b4c7f34938583621fafc8b0079a2834d26fa3fcc9ea9
 cl  23:50:56|cl-1      New work: header #fe719398… target 000010c6f7a0b5ed8d36b4c7f34938583621fafc8b0079a2834d26fa3fcc9ea9
 cl  23:50:56|cl-0      New seed #ec6e8e0d…
 cl  23:50:56|cl-1      New seed #ec6e8e0d…
 cl  23:50:58|cl-0      Platform: Apple
 cl  23:50:58|cl-1      Platform: Apple
 cl  23:50:58|cl-0      Device:   Intel(R) HD Graphics 530  / OpenCL 1.2 
 cl  23:50:58|cl-1      Device:   AMD Radeon Pro 455 Compute Engine  / OpenCL 1.2 
 cl  23:50:58|cl-0      Build info: <program source>:327:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~
<program source>:362:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~

 cl  23:50:58|cl-0      Creating light cache buffer, size 38141888
 cl  23:50:58|cl-0      Creating DAG buffer, size 2441084288
  ✘  23:50:58|cl-0      Creating DAG buffer failed: clCreateBuffer -61
  ✘  23:50:58|cl-0      OpenCL Error: clEnqueueWriteBuffer -38
  m  23:50:58|          Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  23:50:58|cl-1      Build info: <program source>:329:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~
<program source>:364:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~

 cl  23:50:58|cl-1      Creating light cache buffer, size 38141888
 cl  23:50:58|cl-1      Creating DAG buffer, size 2441084288
  ✘  23:50:58|cl-1      Creating DAG buffer failed: clCreateBuffer -61
  ✘  23:50:58|cl-1      OpenCL Error: clEnqueueWriteBuffer -38
  m  23:51:00|          Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00

**Comment by MariusVanDerWijden** [comment]
1610612736 Byte vram... you need at least 3GB V-Ram to mine ethereum
If your AMD Radeon Pro 455 has enough V-ram you can try and only use this, by using 

`--opencl-device 1`
