### ISSUE TITLE
How to Set Up Ethminer

### ISSUE THREAD

**Issue by dcgithubnewbie** [ethereum-mining/ethminer#546]
I have downloaded ethminer-0.13.0rc5-Windows.zip and extract the zip file.
Then i create a start.bat file to run.
Here is the content of the bat file
`setx GPU_FORCE_64BIT_PTR 0 
setx GPU_MAX_HEAP_SIZE 100 
setx GPU_USE_SYNC_OBJECTS 1 
setx GPU_MAX_ALLOC_PERCENT 100 
setx GPU_SINGLE_ALLOC_PERCENT 100 

ethminer.exe --farm-recheck 200 -G -U -S asia1.ethermine.org:4444 -FS asia1.ethermine.org:14444 -O <0x91E22937d66c14f7372553b1ba59833c6ba8981a76a>.<workk>
Pause`

When I click on the bat file it immediately closes.
Any help on this would be appreciated.

**Comment by sgerbino** [comment]
I think you should change "<0x91E22937d66c14f7372553b1ba59833c6ba8981a76a>." to "0x91E22937d66c14f7372553b1ba59833c6ba8981a76a.miner0"

I'm not sure if asia1.ethermine.org:14444 is valid... so maybe re-check that. It's supposed to be a failover (so not the same as -S)

**Comment by dcgithubnewbie** [comment]
Thanks got it to work now!  @sgerbino 
However it tries to connect to stratum but cant connect.. Then it retries again but fail. What is the problem could be here ?
