### ISSUE TITLE
CMake gets stuck in building "Boost-system"

### ISSUE THREAD

**Issue by charlielam0615** [ethereum-mining/ethminer#548]
OS: Fedora 25_64
Tried to execute this command,
`cmake ..`
However, it got stuck in this line:

[ 75%] Performing build step for 'Boost-system'

I waited for about 16 hrs, no sign of any further progress. I checked top, and there was a b2 process, running with 100% CPU, however, 0.0 memory.

Any help?

P.S. Don't know if it's related, but the computer building the ETHminer has a slow Internet connection.

**Comment by dotKokott** [comment]
Have the same problem! Any solutions?

**Comment by glennoid** [comment]
I had this same issue, but I only waited about 20 minutes when it was stuck.. then Ctrl-C.  Running CMake again worked fine after that.  You're welcome for this extremely technical suggestion. ;)

**Comment by roqerxz** [comment]
any solutions? same problem on Ubuntu 14.04.

**Comment by charlielam0615** [comment]
Not a clue. And no idea why this issue was closed.

**Comment by roqerxz** [comment]
ok. Upgrading to cmake-3.10.2 fixed the issue for me.

**Comment by charlielam0615** [comment]
Glad to know. I shall try later.

**Comment by charlielam0615** [comment]
I found this is a problem with boost system. I manually installed boost with

./b2 -j N
with N being the number of cpus in my workstation, in my case it’s 20. 

Then exported some env variables as the boost post-installation suggested. 

Finally everything moved on normally.
