### ISSUE TITLE
Tesla v100-SXM2-16GB Error "Windows Server 2012 r2 , Windows Server 2010"

### ISSUE THREAD

**Issue by sfenky** [ethereum-mining/ethminer#550]
working opencl but i want cuda worked
please !
![error](https://user-images.githubusercontent.com/35326053/34890936-6f1dde40-f7dc-11e7-9ae2-62b0294d6f35.png)

**Comment by MariusVanDerWijden** [comment]
What cuda version do you use?
nvcc -V

**Comment by sfenky** [comment]
9.0 I solved the problem
ethminer-0.13.0rc5-Windows_3
tesla working perfectly ;)

**Comment by ZiDanRO** [comment]
What HR do you have with Tesla?

**Comment by sfenky** [comment]
90mh/s ethereum

**Comment by jean-m-cyr** [comment]
And how much power?
