### ISSUE TITLE
OpenCL Error: clEnqueueReadBuffer: CL_INVALID_CONTEXT (-34) - WX-9100

### ISSUE THREAD

**Issue by HommeCurieux** [ethereum-mining/ethminer#551]
Appears to have allocation issues regarding the memory for the DAG. Any advice?

ethminer.exe --opencl --cl-kernel 0 --cl-local-work 256  --cl-global-work 16384 --benchmark
rem                              --cl-kernel 1

  i  21:45:37|main      Found suitable OpenCL device [ gfx900 ] with 17163091968  bytes of GPU memory
Benchmarking on platform: CL
Preparing DAG for block #0
 cl  21:45:37|cl-0      No work. Pause for 3 s.
Warming up...
 cl  21:45:40|cl-0      New work: header #50c856aeΓÇª target 0000000000000002000000000000000000000000000000000000000000000000
 cl  21:45:40|cl-0      New seed #00000000ΓÇª
 cl  21:45:41|cl-0      Platform: AMD Accelerated Parallel Processing
 cl  21:45:41|cl-0      Device:   gfx900  / OpenCL 2.0 AMD-APP (2527.7)
 cl  21:45:41|cl-0      OpenCL kernel: Unstable kernel
 cl  21:45:42|cl-0      Build info:
 cl  21:45:42|cl-0      Creating light cache buffer, size 16776896
 cl  21:45:42|cl-0      Creating DAG buffer, size 1073739904
 cl  21:45:42|cl-0      Loading kernels
 cl  21:45:42|cl-0      Writing light cache buffer
 cl  21:45:42|cl-0      Creating buffer for header.
 cl  21:45:42|cl-0      Creating mining buffer
 cl  21:45:42|cl-0      Generating DAG
 cl  21:45:46|cl-0      DAG 0 %
 cl  21:45:51|cl-0      DAG 25 %
Trial 1... 0
Trial 2...  cl  21:45:56|cl-0      DAG 50 %
0
Trial 3... 0
Trial 4...  cl  21:46:01|cl-0      DAG 75 %
 cl  21:46:01|cl-0      Switch time 24290 ms / 21288282 us
4217500
Trial 5... 4205870
  X  21:46:08|cl-0      OpenCL Error: clEnqueueReadBuffer: CL_INVALID_CONTEXT (-34)

**Comment by MariusVanDerWijden** [comment]
You use --cl-kernel 0 and -cl-kernel 1 in the same command, maybe this causes some issues

**Comment by HommeCurieux** [comment]
**rem** --cl-kernel 1

**Comment by chfast** [comment]
> CL_INVALID_CONTEXT if the context associated with command_queue and buffer are not the same or if the context associated with command_queue and events in	event_wait_list are not the same.

**Comment by MariusVanDerWijden** [comment]
fixed in https://github.com/ethereum-mining/ethminer/pull/694
