### ISSUE TITLE
Crash after network problem.

### ISSUE THREAD

**Issue by marcriemer** [ethereum-mining/ethminer#552]
After some hours of mining without problems an network error occurred and the process crashed.

  ℹ  23:22:13|cl-0      Solution found; Submitted to eu1.ethermine.org
  ℹ  23:22:13|cl-0      Nonce: 0xf623b0f69da31041
  ℹ  23:22:13|cl-2      Solution found; Submitted to eu1.ethermine.org
  ℹ  23:22:13|cl-2      Nonce: 0xf623b0f69da31041
  ℹ  23:22:13|stratum    Accepted. 
  ✘  23:22:13|stratum   Read response failed: End of file
  ℹ  23:22:13|stratum   Reconnecting in 3 seconds...
  ℹ  23:22:16|stratum   Connecting to stratum server eu1.ethermine.org:4444
  ℹ  23:22:16|stratum   Connected to stratum server eu1.ethermine.org : 4444
Speicherzugriffsfehler (Speicherabzug geschrieben)

Dmesg shows this:

[29353.660858] traps: cl-6[1070] general protection ip:7fe700be527e sp:7fe6f702a550 error:0 in libamdocl64.so[7fe6ffff5000+3b33000]

**Comment by AndreaLanfranchi** [comment]
Please test 0.13.0rc9 and close the issue if problem solved.

Thank you.

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
