### ISSUE TITLE
ethminer fail to detect multiple CUDA devices with -X for AMD & Nvidia mixed cards

### ISSUE THREAD

**Issue by rushstrike** [ethereum-mining/ethminer#553]
.\ethminer.exe --list-devices

Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[1] [0] GeForce GTX 1070 Ti
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2147483648
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
[1] [1] GeForce GTX 1060 6GB
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 6442450944
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1610612736
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
[1] [2] GeForce GTX 1060 6GB
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 6442450944
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1610612736
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
[2] [0] gfx900
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 8573157376
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1070 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 8589934592
[1] GeForce GTX 1060 6GB
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 6442450944
[2] GeForce GTX 1060 6GB
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 6442450944

ethminer.exe --opencl-platform 2 --farm-recheck 2000 -X -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -O 0xxxxxxxxxxx

It only detect 1 openCL and 1 CUDA device what gives?

cl  20:16:14|cl-1      Switch time 30 ms / 4815 us
  m  20:16:15|main      Speed  69.36 Mh/s    gpu/0 31.79  gpu/1 37.57  [A0+0:R0+0:F0] Time: 00:00
  m  20:16:17|main      Speed  69.63 Mh/s    gpu/0 32.15  gpu/1 37.49  [A0+0:R0+0:F0] Time: 00:00
  m  20:16:19|main      Speed  69.53 Mh/s    gpu/0 32.14  gpu/1 37.39  [A0+0:R0+0:F0] Time: 00:00

**Comment by ZiDanRO** [comment]
use this command line and tell me if it is better:

`ethminer.exe --farm-recheck 4000 -U -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -O 0xYour_Wallet.RigName --cuda-parallel-hash 4  --cuda-grid-size 4096`

**Comment by rushstrike** [comment]
It found my 3 CUDA miner but missing my openCL miner:

i  23:14:01|stratum   Received new job #edc70ccd  seed: #ec6e8e0d8056cf9eb61046eaeb754b8e  target: #0000000112e0be826d694b2e
  i  23:14:04|CUDA0     Initialising miner...
  i  23:14:04|CUDA1     Initialising miner...
  i  23:14:04|CUDA2     Initialising miner...
 cu  23:14:06|CUDA0     Using device: GeForce GTX 1070 Ti  (Compute 6.1)
 cu  23:14:06|CUDA0     Set Device to current
 cu  23:14:06|CUDA2     Using device: GeForce GTX 1060 6GB  (Compute 6.1)
 cu  23:14:06|CUDA0     Resetting device
 cu  23:14:06|CUDA2     Set Device to current
 cu  23:14:06|CUDA2     Resetting device
 cu  23:14:06|CUDA1     Using device: GeForce GTX 1060 6GB  (Compute 6.1)
 cu  23:14:06|CUDA1     Set Device to current
 cu  23:14:06|CUDA1     Resetting device
 cu  23:14:06|CUDA0     Allocating light with size: 38141888
.....
m  23:14:33|main      Speed  79.83 Mh/s    gpu/0 32.12  gpu/1 23.91  gpu/2 23.80  [A0+0:R0+0:F0] Time: 00:00
