### ISSUE TITLE
CUDA error: Insufficient CUDA driver: 8000

### ISSUE THREAD

**Issue by skynet** [ethereum-mining/ethminer#557]
What is this:

`ethminer.exe --list-devices

Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[0] [0] Ellesmere
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 4294967296
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4026531840
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
  X  12:55:12|main      CUDA error: Insufficient CUDA driver: 8000`

**Comment by jasonwee** [comment]
think u need cuda version 9.0 onward

**Comment by skynet** [comment]
OpenCL™ Version
22.19.162.4

**Comment by chfast** [comment]
You probably need to upgrade Nvidia driver.

**Comment by bartocc** [comment]
Had the same problem with 381.22.
Upgraded to 387.34 and now it works with ethminer 0.13
