### ISSUE TITLE
0.13rc6 - CUDA mining: an illegal instruction was encountered

### ISSUE THREAD

**Issue by DLS-bau** [ethereum-mining/ethminer#559]
Went from everything stable for days with 0.12 to crashing all the time with 0.13 with: 

```
CUDA error in func 'ethash_cuda_miner::search' at line 300 : an illegal instruction was encountered.
  X  02:50:52|CUDA2     Error CUDA mining: an illegal instruction was encountered
CUDA error in func 'ethash_cuda_miner::search' at line 300 : an illegal instruction was encountered.
  X  02:50:52|CUDA1     Error CUDA mining: an illegal instruction was encountered
CUDA error in func 'ethash_cuda_miner::search' at line 300 : an illegal instruction was encountered.
  X  02:50:52|CUDA0     Error CUDA mining: an illegal instruction was encountered
```

The weird thing is this does not happen on a rig with combined GTX 1070 and 1060 cards but it does on another rig with only GTX 1060. Basically, that rig can't even find 80-90 shares in a row without crashing, no matter the frequencies on VRAM or core or power limit. 

I'm not completely sure but I suspect the issue was introduced  here https://github.com/ethereum-mining/ethminer/pull/361

**Comment by MariusVanDerWijden** [comment]
Do you have an Overclock applied? 
Which version of cuda do you use?

**Comment by DLS-bau** [comment]
Yes, there is VRAM overclocking. I'm getting crashes with Samsung GDDR5 overclocked to just 8600 Gbps (didn't try less, and I have no intention to; it would probably happen at stock 8000 too anyway).
0.12 is stable at over 9000-9200 Gbps. 
I used CUDA 9.0 and 9.1, compiled with VS2015. Same thing with both. No difference with Appveyor build either.  
Tested with drivers 388.71 and 390.65, no difference.

**Comment by jean-m-cyr** [comment]
@DLS-bau

>  I'm getting crashes with Samsung GDDR5 overclocked to just 8600 Gbps

It only takes one card to be running too hot to take down the entire farm this way. Are all you cards running this light overclock? Not being critical... just wondering?

**Comment by DLS-bau** [comment]
The cards in the GTX 1060 rig where 0.13 is unstable are running practically cold. I keep them between 56 and 62C. 
On the combined GTX 1070+1060 rig, where 0.13 runs just fine, the cards run much hotter. Between 66 and 75 C. 

I don't think heat is the issue here. There's about the same amount of heat with 0.12 and 0.13 and 0.12 is completely stable at much higher clocks than the minimum I tested on 0.13.

**Comment by MariusVanDerWijden** [comment]
Can you post, which parameter you use to launch the miner?

**Comment by DLS-bau** [comment]
Sure. 

--farm-recheck 5000 -U --cuda-devices 0 1 2 -S eu2.ethermine.org:4444 -FS us2.ethermine.org:4444 -RH -O wallet.workerID

**Comment by DeadManWalkingTO** [comment]
That's my run command:
`ethminer.exe -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`
Try with latest version and feedback please.
Thank you!

**Comment by AndreaLanfranchi** [comment]
Issue is related to an out-dated version.
Closing.

Feel free to open a new issue with updated version of ethminer.
