### ISSUE TITLE
OpenCl 1.0 support

### ISSUE THREAD

**Issue by milefork** [ethereum-mining/ethminer#56]
Hi,

I would Like to test my Nvidia Quadro Plex 2200 S4
It has internal 4xFX5800 with Compute 1.3 and OpenCl 1.0 support on linux.

What I've to do to get the Code running for OpenCl 1.0? 
I did this:
https://pastebin.com/aGSAqVg2

Is it enough? Or are there more things I've to adapt?

With a singe FX5800 and the patch up there I get:

` m  19:03:24|ethminer  Mining on PoWhash #0aab6bd8 : 2.75MH/s [A0+0:R0+0:F0]`

Seems slow or isn't it?

**Comment by chfast** [comment]
This not worth the effort. Supporting old hardware is bad idea. OpenCL 1.2 should be minimum. etheminer theoretically should also work on OpenCL 1.1, but I think it is broken now, because nobody was using it for a long time.
