### ISSUE TITLE
Low hash rates with rx 480

### ISSUE THREAD

**Issue by christophcarstensen** [ethereum-mining/ethminer#562]
I am only getting 18Mh/s but I should get 25+ 
Can someone confirm?

sapphire rx480 nitro
Beta blockchain drivers 

ethminer -G -F http://127.0.0.1:8080 --cl-local-work 256 --opencl-device 1 --opencl-platform 1

  m  03:22:09|main      Speed  18.01 Mh/s    gpu/0 18.01  [A2+0:R0+0:F0] Time: 00:03
  m  03:22:10|main      Speed  18.01 Mh/s    gpu/0 18.01  [A2+0:R0+0:F0] Time: 00:03
  m  03:22:10|main      Speed  18.01 Mh/s    gpu/0 18.01  [A2+0:R0+0:F0] Time: 00:03

**Comment by christophcarstensen** [comment]
0.12 and 0.13 tested. same result

**Comment by smurfy** [comment]
* Do you bios mod?
* Do you overclock your memory?

**Comment by christophcarstensen** [comment]
No to both.
All stock.

**Comment by Tokolosh** [comment]
that seems to be the correct average speed for stock rx card. to get more you would have to bios mod them.
For example i am currently running 2 rx580's which do about 22mhs stock and after bios mod they are up to 28-29

**Comment by christophcarstensen** [comment]
From what I have been reading the stock rate is well above 20Mh/s, but I'll see if I flash the bios next.

**Comment by hubbertj** [comment]
All my MSI 580 4gb are all about 18 MH/s bios modding (just changing the timers) does nothing to the card. I am running unbuntu 16.04 LTS and ethminer. So I am in the same boat.

**Comment by christophcarstensen** [comment]
My issue was solved by a simple change in the settings. 
https://www.reddit.com/r/EtherMining/comments/7qdkh3/radeon_rx480_only_18mhs/?utm_source=reddit-android

**Comment by cryptomine** [comment]
@hubbertj I was having the same issue and then fixed by downloading the beta drivers:
https://github.com/ethereum-mining/ethminer/issues/562

**AND**

"Enabling Large Page Support" 

I found the instructions to do so in the above link, at first I didn't see the large page support portion and had only installed the drivers to find they did nothing. Once I enabled large page support my cards went from ~18Mh/s to ~24Mh/s

**Comment by hubbertj** [comment]
@cryptomine  that did it for me I get 24 + a card now it was the driver and "Enabling Large Page Support"
-thanks

**Comment by jramos** [comment]
Large page support is enabled by default in the latest version (17.50).
