### ISSUE TITLE
Drop or stabilization ?

### ISSUE THREAD

**Issue by Rodriguevb** [ethereum-mining/ethminer#564]
![hashrate](https://user-images.githubusercontent.com/4284147/34941514-55972a52-f9f4-11e7-865a-ce58279a0a72.png)
(see picture)

Hello

I don't know if it's a drop or a stabilization.
When new work pops, the hashrate is directly at 31Mh/s or should it stabilize itself ? (farm-recheck 1 sec)

btw, there is a tuto somewhere to optimize CUDA parameters for mining ?
i use : 

- cuda-parallel-hash 8
- cuda-streams 10
- cuda-grid-size 8192
- cuda-block-size 256

But I have no idea if it's suitable for my GPUs 1070

Thanks for clarifications :)

**Comment by AndreaLanfranchi** [comment]
This was due to a very high time switching between jobs : the problem has been addressed and consistently mitigated with the recent 0.13.0rc9.
See [PR 599](https://github.com/ethereum-mining/ethminer/pull/599)
Please retest with latest release and report when possible.
