### ISSUE TITLE
use legacy with AMDGPU-Pro 17

### ISSUE THREAD

**Issue by nerdralph** [ethereum-mining/ethminer#565]
The new HSA/ROCm compiler in the AMDGPU-Pro drivers does a poor job of optimizing, making mining performance about 10% slower than AMDGPU-Pro 16.
Setting AMD_OCL_BUILD_OPTIONS_APPEND=-legacy will use the old compiler, restoring good performance.
I now get 28.6-29Mh with a Rx 470 clocked at 1126/2000 vs 28.5 for ethminer-nr (which uses -legacy by default).

**Comment by deanmarano** [comment]
Where is this to be set? I tried to set during the cmake configure (`cmake AMD_OCL_BUILD_OPTIONS_APPEND=-legacy ..`) but that doesn't seem like the right place.

**Comment by nerdralph** [comment]
It's a runtime variable you set before starting ethminer.
export AMD_OCL_BUILD_OPTIONS_APPEND=-legacy

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
