### ISSUE TITLE
lost work & incorrect speed reporting

### ISSUE THREAD

**Issue by nerdralph** [ethereum-mining/ethminer#567]
The original clminer code used double-buffering while the new CLminer code does not.  This means when new work is received, the results from the currently running kernel is discarded, and so stale solutions are lost.  This also means the speed reporting is slightly higher as the discarded work is counted in the total speed.

**Comment by chfast** [comment]
Not true, CLMiner will report the solution even though the work package have been updated. The mining thread has a copy of it.

**Comment by nerdralph** [comment]
Yes, it reports it here, as a solution to the CURRENT work:
https://github.com/ethereum-mining/ethminer/blob/master/libethash-cl/CLMiner.cpp#L385
It will then fail to validate, and get discarded.

JW and I kept track of the last work and current work in the stratum client in order to handle stale solutions, but you seem to have removed most of that code after merging from JW's fork.

**Comment by jean-m-cyr** [comment]
> JW and I kept track of the last work and current work in the stratum client in order to handle stale solutions, but you seem to have removed most of that code after merging from JW's fork.

Those 2 eval() calls in the submit function were a very expensive way to address that problem!

**Comment by jean-m-cyr** [comment]
@chfast 

In cuda we handle stale detection here, and pass it up the stack (so that stratum can count properly).

https://github.com/ethereum-mining/ethminer/blob/822358d5ef4d735e434dd30a7fc882a5fb45e82e/libethash-cuda/CUDAMiner.cpp#L114

where isStale() returns a flag that is toggled by setWork(). Once setWork has been called, we pretty much know than any result from in-flight hashes will be stale till the GPU is given the new problem.

in cl, we have:

https://github.com/ethereum-mining/ethminer/blob/822358d5ef4d735e434dd30a7fc882a5fb45e82e/libethash-cl/CLMiner.cpp#L274

which always passes up false, stale or not. I've not travelled the cl code much... not sure if the same solution couldn't be appiled.

**Comment by jean-m-cyr** [comment]
> The other ~1% of the time that a stale result is found, the 2nd eval gets called. Even on a low-end CPU, the CPU load is minimal. With the average pool mining difficulty of ~4B, a multi-GPU rig only finds a couple solutions per minute.

What matters is what the pool sees as stale, not what the miner thinks is stale. The motivation for removing the eval calls is that they are expensive computationally and unnecessarily (at least for cuda) delay the sending of a result to the pool. The same applied to the print formatting stuff. It was moved to after the send. Yes, it may only amount to a few 100us, but why throw them away if you can get them for free and slightly improve you chances of getting there on time.

**Comment by nerdralph** [comment]
@jean-m-cyr Actually, what maters is that the solution submitted matches the header and jobid.   When you send a solution for the last nonce to the pool with the current header and jobid, most pools silently discard it without a reject.  I've discussed this with Eun who runs MPH, and it makes sense that the pool operator doesn't want to do the extra eval() to see if the nonce is a solution to the current or past work.
Also note that stales can actually become part of the main chain instead of an uncle if the difficulty is high enough, as it is the heaviest chain that prevails and not necessarily the chain with the first solution to meet the minimum difficulty.

**Comment by jean-m-cyr** [comment]
> Actually, what maters is that the solution submitted matches the header and jobid.

Fully agree, and that is always the case now for stratum. In addition we detect and properly count stales we know about without burdening stratum with the task. Look at it more closely. The way the reporting function gets its job id, etc. has been completely redone. There is no longer any need for stratum to maintain a copy of old work, the submit function does only what is intended without unnecessary overhead.

**Comment by jean-m-cyr** [comment]
BTW. In in cl, the current code will NOT send shares with mismatched job_ids, it never had that problem! The root cause, where, why, and exactly how that was happening in cuda has only been identified an corrected just recently AFAIK. The only outstanding issue you've pointed out is the mis-count of knowingly sent stales by the cl miner.

**Comment by chfast** [comment]
I realized this problem some time ago (I'm still learning what's going on here).
I think the fix should be easy - compare the work send from a miner along with the nonce with the current one. If different, it's stale solution.

**Comment by nerdralph** [comment]
@chfast That should work better than the way I was doing it.  It would only involve a string compare instead of a full eval.

**Comment by jean-m-cyr** [comment]
@chfast 

> I realized this problem some time ago (I'm still learning what's going on here).
I think the fix should be easy - compare the work send from a miner along with the nonce with the current one. If different, it's stale solution.

Should work. I'd avoid the additional copy incurred with the extra invocation of work(). Maybe create a second version of work() that returns by reference?

**Comment by chfast** [comment]
No, that will be a data race. Unless you move it to stratum thread.
It's not worth in my opinion. Keep the code small and simple.

**Comment by jean-m-cyr** [comment]
I don't think it would create a race window. You have the job_id in a copy of the work packet taken at the time the work was submitted. Compare that with a reference to the current value. It doesn't matter if your compare catches the other thread in the middle of a copy. It'll either match, or it won't. If it doesn't then it's stale.

By calling work to get a copy, you'll be adding another opportunity to block stratum, with the ensuing scheduling overhead.

**Comment by chfast** [comment]
I agree this is not a big deal in practice, but doing that means we cannot use any of the tools like ThreadSanitizer. 
Anyway, if we have the mining thread running, some additional locks in other threads does no matter.

**Comment by nerdralph** [comment]
> Even in cl, the current code will NOT send shares with mismatched job_ids, it never had that problem!

I've re-read the code a few more times, and I think you're mistaken.  At line 354 the new work is assigned to current.
https://github.com/ethereum-mining/ethminer/blob/master/libethash-cl/CLMiner.cpp#L354

Therefore the report() call at line 385 is using the new WorkPackage with the old nonce.  I'm going to try moving the "current = w" assignment to after the report().

**Comment by chfast** [comment]
I think you are wrong.
The kernel runs on data from "current" and reports "current". There is no place to change the "current" in this lines: https://github.com/ethereum-mining/ethminer/blob/master/libethash-cl/CLMiner.cpp#L380-L385.

The "w" is a new package, and in case it's different than "current" we must update some additional data (including generating a new DAG if needed). Usually this is not the case so we just need to increment the start nonce.

**Comment by jean-m-cyr** [comment]
Ah, ok. I'll stay out of this. Don't know enough about how cl works.

**Comment by chfast** [comment]
I don't know much either. But this kernel call is synchronous, so the CPU thread waits there until it's finished. Then it reports, then it checks a new work, then it run the kernel again and waits.

The optimization would be to report and check for a new work package **while** the kernel is running. We need a bit different CL functions for that. And a bit reversed logic in the main loop.

Personally, I think that cleaning up the CUDA miner and extracting common code is much more important (we can even have a common main loop probably).

**Comment by jean-m-cyr** [comment]
That's the plan...

Just need to squash these last few self-inflicted bugs and warts to move on. :-)

**Comment by nerdralph** [comment]
enqueueNDRangeKernel is async, and only the enqueueReadBuffer is blocking.  I'd say that's why whoever wrote the current CLMiner code put the report() call after enqueueNDRangeKernel.

**Comment by chfast** [comment]
Hm... It seams I'm wrong here then. Thanks for checking it out.

**Comment by nerdralph** [comment]
I just finished benchmarking eval(), and on a Celeron G1840, it takes ~6ms.

**Comment by jean-m-cyr** [comment]
@nerdralph 6ms. Thought so... expensive. :-)

**Comment by nerdralph** [comment]
@jean-m-cyr I remembered in ethminer-nr I never sent the mixhash, just a 2nd copy of the header hash as pools have to do a full verify of the nonce against the header.  Otherwise the miner could cheat and only search for a mixhash which would avoid the DAG search/mix.  So I'm currently testing a version of CLMiner::report that submits the solution, then does the verify to ex-post facto determine if there was a failed result or not.

**Comment by jean-m-cyr** [comment]
@nerdralph Interesting approach. You know, why are we killing ourselves trying to detect stales? As long as we don't send invalids, who cares? Our counts, never match the pool's anyway! If it were up to me I'd drop the whole stale share counting thing. Do any other miners bother trying to do this?

**Comment by nerdralph** [comment]
@jean-m-cyr nanopool seems to reject solutions with out a valid mixHash, so I had to go back to validating before submitting.  If I was only using MPH, I can get away without submitting a mixHash.
The reason why some pools wouldn't care about the mixHash is because they do a full verify.
As to the importance of stale reporting, some pools do not show stales.  MPH was showing them about a year ago, but for a number of months now there share reporting has not been working right.  Nanopool doesn't seem to show rejects, and I'm not sure if they show stales.
Network latency and miner/kernel latency are the two primary factors in stale share generation.  With ethminer-nr I show the share submit response time from the pool, so a miner can tell if their pool is overloaded or has a poor network route.  When using larger work sizes, hashrate improves but kernel latency goes up, reaching a tradeoff where more stales offsets the faster speed.  Tracking stales helps figure out where that tradeoff is.
The ideal solution is where the miner picks the optimal local and global work along with the optimal kernel.  That's not practical for ethminer which needs to run on a plethora of different GPUs, but is not so hard for the most popular GPUs.  In that vein, I've started writing a new miner from scratch which will be optimized for only AMD GCN3 devices (Tonga & Polaris).

**Comment by jean-m-cyr** [comment]
@nerdralph I get it that we're interested in stale ratios as perceived by the pool. What I'm talking about are shares known to be stale before they are even't sent. Turns out to be very small, and hard to do in CL.

**Comment by nerdralph** [comment]
If the miner's average latency to submit a share is 100ms, and the network latency between the miner and the pool is 50ms, then stales will be ~1%.
A quick and easy way to detect stales is to add the following check in report():
 bool stale = (_w.header != work().header);

I'm testing that out now.

**Comment by jean-m-cyr** [comment]
Already got that covered in CUDA

**Comment by nerdralph** [comment]
@jean-m-cyr  Yes, I read about your CUDA code and stale hook.  I'm trying it this way so I don't have to read through the CUDA code.  If I decide to go further and submit a pull request, I'll look at refactoring to avoid duplication.

**Comment by jean-m-cyr** [comment]
The CUDA code is much more readable now... no more hooks.

**Comment by jean-m-cyr** [comment]
Anyway, if ever we converge on a common method we can move all of it to the common inherited Miner class.

**Comment by jean-m-cyr** [comment]
@chfast I realize this is old, but in re-reading I saw this:

> I agree this is not a big deal in practice, but doing that means we cannot use any of the tools like ThreadSanitizer.

What does the thread sanitizer think of the shared use of the m_abort variable in CUDA? It is not protected by a lock but can be considered atomic since it is never used in a 'read-conditional modify-write' way. It is either read, or written, but never both in the same pass. Wonder if the sanitizer figures that out?

**Comment by chfast** [comment]
The ThreadSanitizer reports a lot of issues already. In this case it should be `atomic<bool>` not regular `bool`.

**Comment by jean-m-cyr** [comment]
I was afraid of that. It's running smoothly right now because CUDA relies on the work() lock right now to sync stratum and the miner(s). Because we know the threads now operate in lock-step, we get away with it.

Would making it atomic cause the build to automatically wrap it with a software lock? I'd hate to throw another lock in there.

**Comment by chfast** [comment]
1. Do you use Linux or macOS? I can show you how to use sanitizers. I don't have a lot of time myself at the moment.
2. Atomic primitive types are implemented without locks, it's much faster than mutex. Atomic load on x86 is actually free.
3. Even without atomics this will work in practice (at least on x86). But I prefer to play accordingly to the C++ spec, just to learn this.
4. If we have timers to measure the switch time, we can benchmark the changes.
5. Another known thread-sync bug is around hashrate accumulation. We can miss some hashrates there...
6. I'm not sure how to handle the "work" in atomic way. We can do `atomic<Work>` but that will be implemented with a lock anyway, because Work is bigger than 8 bytes. In such case you may want to use pointers. `atomic_share_ptr` might be good, but it is not a standard one. Of to figure out how to use lock-free queue in this case.

**Comment by jean-m-cyr** [comment]
@chfast I'll definitely go with atomic then if it it is truly a hardware atomic. I have no issue with those. They don't thrash the OS scheduler.
