### ISSUE TITLE
v0.13-rc7, no accepts on nanopool

### ISSUE THREAD

**Issue by satori-q3a** [ethereum-mining/ethminer#568]
I just tried 0.13-rc7 on nanopool and stopped it after 10 mins when seeing that there no accepts had occurred during that time frame.  Usually there should be a few but I felt that something was wrong.

Reverted back to rc6 and within a min, I was getting accepts.

Maybe it's just me and what I've come to expect from running ethminer, but I'll wait a bit and am happy with rc6.

I should clarify that there were no submits being generated.  Running Win 10, cuda 9.1 on (2) nvidia 1070 and (1) 1060 cards.

**Comment by l4Dream** [comment]
Same problem - All shares Rejected on dwarfpool and minerpool.

**Comment by ddobreff** [comment]
did you try with -SP 1?

**Comment by l4Dream** [comment]
I use eth-proxy on dwarfpool, and -S [addr] -SP1 on minerpool, both reject shares, btw, i switch to rc6 and everything work fine for now.

**Comment by jean-m-cyr** [comment]
What do the command lines look like for thos two pools? I'll give it a look.

**Comment by l4Dream** [comment]
Dwarfpool+eth-proxy:
ethminer --farm-recheck 200 -U -F http://127.0.0.1:8080/name --cuda-block-size 256 --cuda-streams 8 --cuda-schedule auto
Minerpool:
ethminer.exe --farm-recheck 200 -U -S exp.minerpool.net:8004 -SP 1 -O [address].[name] --cuda-block-size 256 --cuda-streams 8 --cuda-schedule auto

**Comment by satori-q3a** [comment]
and mine for nanopool ...

c:\apps\ethminer-0.13\ethminer --farm-recheck 1000 -U --cuda-grid-size 16384 --cuda-block-size 128 --cuda-parallel-hash 4 -S eth-us-west1.nanopool.org:9999 -O eth-wallet-address.worker/mail-address

**Comment by jean-m-cyr** [comment]
Hmm... Seems to work here on nanopool.


  m  11:49:31|ethminer  Speed  81.63 Mh/s    gpu/0 21.19  gpu/1 21.40  gpu/2 17.63  gpu/3 21.40  [A1+0:R0+0:F0] Time: 00:05
  ℹ  11:49:31|CUDA0     Solution for job 70622cd2  found. Submitted to eth-us-west1.nanopool.org
  ℹ  11:49:31|CUDA0     Nonce: 0x17d60d716c5642d7
  ℹ  11:49:31|stratum    **Accepted**. 
  m  11:49:32|ethminer  Speed  81.62 Mh/s    gpu/0 21.19  gpu/1 21.40  gpu/2 17.83  gpu/3 21.19  [A2+0:R0+0:F0] Time: 00:05

**Comment by chfast** [comment]
I also tested nanopool, `ethminer --farm-recheck 1000 -U -RH -S eth-eu1.nanopool.org:9999`.

```
  ℹ  23:00:04|stratum   Received new job #dede7b63  seed: #d5d85ca51867514082660716ef2bedbb  target: #000000006df37f675ef6eadf
  m  23:00:05|ethminer  Speed  25.24 Mh/s    gpu/0 25.24  [A0+0:R0+0:F0] Time: 00:09
  m  23:00:06|ethminer  Speed  24.82 Mh/s    gpu/0 24.82  [A0+0:R0+0:F0] Time: 00:09
  ℹ  23:00:07|cuda-0    Solution found; Submitted to eth-eu1.nanopool.org
  ℹ  23:00:07|cuda-0    Nonce: 0xfcba42b9d9a57f71
  ℹ  23:00:07|stratum    Accepted. 

```
