### ISSUE TITLE
build issue CUDA 8.0 Ubuntu

### ISSUE THREAD

**Issue by filmo** [ethereum-mining/ethminer#572]
------------------------------------------------------------------------
-- CMake 3.5.1
-- Build Release / Linux
------------------------------------------------------------- components
-- ETHASHCL         Build OpenCL components                  OFF
-- ETHASHCUDA       Build CUDA components                    ON
-- ETHSTRATUM       Build Stratum components                 ON
-- ETHDBUS          Build D-Bus components                   OFF
-- APICORE          Build API Server components              ON
------------------------------------------------------------------------

-- Found CUDA: /usr/local/cuda (found version "8.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/philglau/ethminer/build

`cmake --build .
`
[ 83%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_70'

Is there a compatibility issue with CUDA 8? or just something on my end?

Is it possible to pass command arguments somewhere during the cmake process to ignore building for compute_70 which seems to be for Tesla V100 products ??

**Comment by filmo** [comment]
Sorry, found answer after I opened issue. Please ignore.

**Comment by jean-m-cyr** [comment]
Too late... ;-)
