### ISSUE TITLE
Issue trying to lower the GPU usage (aka the amount of work sent to GPU from the miner)

### ISSUE THREAD

**Issue by enshadowed** [ethereum-mining/ethminer#576]
Greetings, first of all thanks for keeping the miner alive and thank you for the development. 

I have been seeing a lot of comments regarding lowering the GPU usage of the etherminer. a TLDR version of many many forum posts are; 
`export GPU_MAX_ALLOC_PERCENT=25`
`-ethi 1`
`-li 1`

Which none of them works. Another suggested editing and rebuilding the miner; with the GPU_MAX_ALLOC changed from there but that still does not work. 

Officially are there any plans of providing means to lower how much work is sent to the GPU? Apologies if there is already a way that i am not aware of OR if this has been posted and got 'necroed'.

**Comment by ZeddBread** [comment]
Hear, hear!

**Comment by enshadowed** [comment]
Thanks for your prompt reply. Again, thanks! Hoping this is implemented soon! Cheers

**Comment by chfast** [comment]
We don't plan to do any of these, but patches welcome.

**Comment by Joshfindit** [comment]
Came here looking for the same thing.
Tbh, I only want it temporarily to track down an issue where my system is going unresposive overnight (then a small chance I want it at 95% all the time if the card can't handle 100)

**Comment by enshadowed** [comment]
Yes, we are using this miner to mine on a big community on twitch. Gamers have very powerful gear and they would like to be able to browse, play a lightweight game like Hearthstone for example that does not depend on GPU as much. I guess the best deal is to seek out alternative miners and hope they implement something like that. BUT, nothing like this miner. I hope they revise this and implement it.

**Comment by nmz787** [comment]
I also want a solution for this. I know youtube can't be using all my GPU.

**Comment by chfast** [comment]
Sorry @enshadowed, but nobody cares. There is precisely $0 direct gain for every new miner using this software.

**Comment by Joshfindit** [comment]
I would disagree if the new miners are having consistent crashes due to power or heat issues. Crashes are lost revenue.

**Comment by nmz787** [comment]
@chfast there's also $0 gain when I CTRL-C `ethminer` so why not just allow dynamic throttling so I can be a bit lazier?

**Comment by NukeManDan** [comment]
Cross posting: #2222 may help those looking to solve this. Thanks @TroyNeubauer 🙇🏼 !
