### ISSUE TITLE
ASUS DUAL RX480 8GB - Eventually stops mining

### ISSUE THREAD

**Issue by thxois** [ethereum-mining/ethminer#577]
Hello, as you can see from the title my ASUS RX480 8GB stops mining eventually and i need to restart the whole system to make it again work. However, when i tried to underclock the gpu there is no problem at all. I am using CentOS with no risers or something. The PSU is 1500watt so the power is not considered as a problem. The card is on a x8 PCI-e directly on the motherboard. What could cause such an issue?

**Comment by Tokolosh** [comment]
Have you set your pci-e slots to gen1 in your motherboard bios? Some Motherboards have a "Mining Mode" which does this automatically on others this needs to be set manually.

**Comment by thxois** [comment]
I think that i haven't checked that, but i think that gen2 and gen3 are backwards compatible with gen1.. So you think that this might cause the problem?

**Comment by Tokolosh** [comment]
i dont know, all i do know is that i had problems with 2 rigs until setting the pci-e to gen1. Also i tried out a couple of ethminer versions on both rigs with windows and linux (for testing) - just try out a couple of them (from 0.12 to 0.13rc7 or even one of the bleeding edge ones --> https://ci.appveyor.com/project/ethereum-mining/ethminer

but on amd cards a good bios mod is key to finally get the hashes you deserve ;) anorak.tech/c/downloads is a good place to search for your exact card/vram combo

**Comment by thxois** [comment]
Ok! Thank you very much, i will try it out tomorrow. I just thought its really weird that works if i underclock. By the way i have never overclocked the GPU, everything is as it is from Asus.

**Comment by Tokolosh** [comment]
well that is also part of the bios mod. Before i modded i was doing 22-23MHs and had a power draw of 145-150W per card, now i am doing 28,5MHs with a power draw of 105-110W per card ;)

**Comment by thxois** [comment]
But by using mods you might destroy the GPU completely. Am i right? Isn’t the same as flashing bios?

**Comment by jhallbox** [comment]
thxois yes don't try BIOS flashing if you don't have a dual bios card or can't afford to repurpose your GPU as a doorstop.

The dual bios allows you to boot into one bios, then switch to a different one to flash. Just keep track.

In my opinion, flashing your BIOS only shortens the lifetime of the card and in the end you may not see enough benefit to be worth it.

**Comment by thxois** [comment]
Actually I don’t think that i want to flash my GPU bios or even overclock it. I just don’t understand why stock settings can’t afford mining and the card stops and when i underclock stock settings everything is fine..

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
