### ISSUE TITLE
X server found. dri2 connection failed! [Fedora 27 i3wm]

### ISSUE THREAD

**Issue by drhacko** [ethereum-mining/ethminer#579]
(edit: sorry for the no-explanation, I quickly posted this before an event)
When trying to run ethminer on Fedora it kept failing even when configuring the files.
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument

screenfetch:
Fedora 27, i3wm
Kernel: x86_64 Linux 4.14.13-300.fc27.x86_64
GPU: GeForce GTX 970/PCIe/SSE2
CPU: Intel Core i5-4690K @ 4x 3.9GH

**Comment by AndreaLanfranchi** [comment]
When running on NVIDIA use CUDA instead of OpenCL.

`ethminer -U [...]`

instead of 

`ethminer -G [...]`

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.

**Comment by piotr-dobrogost** [comment]
> When running on NVIDIA use CUDA instead of OpenCL.

Theoretically it should be perfectly possible to mine on NVidia via OpenCL (not recommended of course but still), no?
I found this thread as I got the exact same error (`X server found. dri2 connection failed!`) while trying to run John The Ripper on NVidia cards via OpenCL (JtR removed support for CUDA some time ago and only supports OpenCL).

Anyone knows possible reason for error `X server found. dri2 connection failed!` when using OpenCL with NVidia cards?

**Comment by gaxhaje** [comment]
I am getting the same error on an AMD card. I also build from source but I get the same error. I have 

packages installed:
clinfo mesa-opencl beignet ocl-icd opencl-filesystem opencl-headers opencl-utils clpeak mesa-libGL mesa-libGL-devel xorg-x11-server-Xorg xor-x11-server-common

$ ethminer -G
  m  16:14:11|ethminer|  ethminer version 0.14.0.dev2
  m  16:14:11|ethminer|  Build: Linux/g++ / Release
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: No such file or directory
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [13]
param: 4, val: 0
No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument

System:
OS: Fedora 27
Kernel: 4.15.4-300.fc27.x86_64
GPU: AMD HAWAII (DRM 2.50.0 / 4.15.4-300.fc27.x86_64, LLVM 5.0.1)
