### ISSUE TITLE
Crash on benchmark

### ISSUE THREAD

**Issue by whitebarry** [ethereum-mining/ethminer#581]
Fresh download of ethminer, happens both on 0.12.0 and 0.13.0rc7. I am running `ethminer -G -M`. Here is the console output: 

> C:\Program Files\ethminer\bin>ethminer -G -M
  i  22:54:26|main      Found suitable OpenCL device [ Hawaii ] with 8589934592  bytes of GPU memory
Benchmarking on platform: CL
Preparing DAG for block #0
 cl  22:5W4a:r2m6i|ncgl -u0p . . .
  No work. Pause for 3 s.
 cl  22:54:29|cl-0      New work: header #50c856aeΓÇª target 0000000000000002000000000000000000000000000000000000000000000000
 cl  22:54:29|cl-0      New seed #00000000ΓÇª
 cl  22:54:30|cl-0      Platform: AMD Accelerated Parallel Processing
 cl  22:54:30|cl-0      Device:   Hawaii  / OpenCL 2.0 AMD-APP (2527.7)
 cl  22:54:31|cl-0      Build info:
 cl  22:54:31|cl-0      Creating light cache buffer, size 16776896
 cl  22:54:31|cl-0      Creating DAG buffer, size 1073739904
 cl  22:54:31|cl-0      Loading kernels
 cl  22:54:31|cl-0      Writing light cache buffer
 cl  22:54:31|cl-0      Creating buffer for header.
 cl  22:54:31|cl-0      Creating mining buffer
 cl  22:54:31|cl-0      Generating DAG
 cl  22:54:31|cl-0      DAG 0 %
 cl  22:54:31|cl-0      DAG 6 %
 cl  22:54:31|cl-0      DAG 12 %
 cl  22:54:31|cl-0      DAG 18 %
 cl  22:54:32|cl-0      DAG 25 %
 cl  22:54:32|cl-0      DAG 31 %
 cl  22:54:32|cl-0      DAG 37 %
 cl  22:54:32|cl-0      DAG 43 %
 cl  22:54:32|cl-0      DAG 50 %
 cl  22:54:32|cl-0      DAG 56 %
 cl  22:54:32|cl-0      DAG 62 %
 cl  22:54:32|cl-0      DAG 68 %
 cl  22:54:33|cl-0      DAG 75 %
 cl  22:54:33|cl-0      DAG 81 %
 cl  22:54:33|cl-0      DAG 87 %
 cl  22:54:33|cl-0      DAG 93 %
 cl  22:54:33|cl-0      Switch time 7276 ms / 4274279 us
Trial 1... 27892121
Trial 2... 27787264
Trial 3... 27795602
Trial 4... 27792822
Trial 5... 27897701

At this point I receive a crash:
![image](https://user-images.githubusercontent.com/25397325/35025093-58e791c4-fb11-11e7-9299-53c1b20a36ed.png)

Card is an R9 390x 8GB running on Win7 Ultimate x64. Am I missing something obvious here?

**Comment by chfast** [comment]
No. It's just broken for some time. We know about it.
