### ISSUE TITLE
v13-rc7 Problem with creating buffer for DAG on RX Vega 

### ISSUE THREAD

**Issue by lordxyra** [ethereum-mining/ethminer#584]
Problem creating Buffer on RX Vega with 13.RC7
 cl  12:42:24|cl-0      Build info:
 cl  12:42:24|cl-0      Creating light cache buffer, size 38272448
 cl  12:42:24|cl-0      Creating DAG buffer, size 2449472384
  X  12:42:24|cl-0      Creating DAG buffer failed: clCreateBuffer: CL_INVALID_BUFFER_SIZE (-61)
  X  12:42:24|cl-0      OpenCL Error: clEnqueueWriteBuffer: CL_INVALID_MEM_OBJECT (-38)
  m  12:42:24|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00

Works with RC6

**Comment by rushstrike** [comment]
I am using rc7 and have no problem with Vega. It would be wise to put your params so the person who may try to help you can try to recreate the same error.

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!

**Comment by lordxyra** [comment]
works with 14 dev2.
Also teste 13 release and it works there too.

closing ticket
