### ISSUE TITLE
0.13.0rc7 - Stale solution block the miner and lose connection

### ISSUE THREAD

**Issue by Rodriguevb** [ethereum-mining/ethminer#585]
Hello,

i have this error sometime on Xubuntu 17 and the last stable version of ethminer 0.12.0. 
Too much overclocking or my parameters are wrong ? ( cuda-parallel-hash 8 cuda-streams 10 cuda-grid-size 8192 cuda-block-size 512 )

![img_20180117_020946](https://user-images.githubusercontent.com/4284147/35041971-07af09c4-fb87-11e7-9c2d-79d9d4ebd6d5.jpg)

And i have so much Submitting Stale Solution too..
![submittingstalesolution](https://user-images.githubusercontent.com/4284147/35042017-2fab41fe-fb87-11e7-8c4d-dbb2d871bef4.png)

**Comment by Kveri** [comment]
try using latest 0.13rc7, but usually this means a lot of overclocking. Try going to stock clocks and then increasing to see when you start seeing these errors.

**Comment by Rodriguevb** [comment]
With 0.13.0rc7, the stale solution block the system

![stalesolutionfound](https://user-images.githubusercontent.com/4284147/35044847-213b888a-fb92-11e7-969b-645d79aaa861.png)

btw this error is strange : **Parse response faild: * Line 1, column 29 Missing ':' after object member name**

**Comment by fastaprilia** [comment]
Check your GPU temps and limits.  I have 1 GTX 1070 that would become very unstable above 61C.  Assuming you are air-cooling, set your max temps to something around 60C so that the thermal limits will kick-in and slow your card down if it starts to get too hot.

**Comment by DDDanny** [comment]
@Rodriguevb 
just checked your settings "cuda-parallel-hash 8 cuda-streams 10 cuda-grid-size 8192 cuda-block-size 512"
so for me (4 GTX 1070 and 1 GTX 1060) default settings of ethminer outputs much better hashrate (more stable)
so defaults are cuda-parallel-hash 4 cuda-grid-size 8192 cuda-block-size 128

**Comment by Rodriguevb** [comment]
My GPUs works at 50C +-, so it's 'cold' :)

And defaults parameters `cuda-parallel-hash 4` give a bad hashrate for me ( 28 (4) / 31 (8) ).

What is the main difference between `cuda-parallel-hash` and `cuda-streams`?

**Comment by jean-m-cyr** [comment]
@Rodriguevb Shouldn't happen with the final release 13. Please retest.

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
