### ISSUE TITLE
New work header garbled which stopps the program

### ISSUE THREAD

**Issue by funan1979** [ethereum-mining/ethminer#586]
I got following info when running ethminer (latest version):

D:\BlockChain\etherum\ethminer>ethminer.exe --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS eu2.ethermine.org:4444 -O 0x77dE43d11790c4ba5e2654f0bCBb5b8FB9f4e942.foxwell1
  i  00:07:40|main      Found suitable OpenCL device [ Ellesmere ] with 4294967296  bytes of GPU memory
  i  00:07:40|main      Connecting to stratum server eu1.ethermine.org:4444
  i  00:07:40|stratum   Connected to stratum server eu1.ethermine.org : 4444
  i  00:07:40|stratum   Starting farm
 cl  00:07:40|cl-0      No work. Pause for 3 s.
 cl  00:07:40|cl-1      No work. Pause for 3 s.
  i  00:07:40|stratum   Subscribed to stratum server
  i  00:07:40|stratum   Authorized worker 0x77dE43d11790c4ba5e2654f0bCBb5b8FB9f4e942.foxwell1
  i  00:07:40|stratum   Received new job #f5942822  seed: #d5d85ca51867514082660716ef2bedbb  target: #0000000112e0be826d694b2e
  m  00:07:40|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  00:07:40|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  00:07:41|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  00:07:41|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  00:07:41|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  00:07:41|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  00:07:41|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  00:07:42|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  00:07:42|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  00:07:42|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  00:07:42|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  00:07:42|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  00:07:43|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  00:07:43|main      Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  00:07:43|cl-0      **New work: header #f5942822鈥?**

Where does this Garbled come from and how to fix it? Many many thanks!

**Comment by efrasyad** [comment]
maybe this link https://superuser.com/questions/487819/how-do-i-view-unicode-characters-on-command-prompt will help

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.

**Comment by smurfy** [comment]
I actually see the same strange char on windows using opencl. I will look into it.

**Comment by DeadManWalkingTO** [comment]
CUDA run fine.
Maybe OpenCL only error.
@smurfy may fix that.

**Comment by AndreaLanfranchi** [comment]
@smurfy by the implementation of PoolManager both CUDA and OpenCL labels should be identical.
