### ISSUE TITLE
CI is broken again

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ethereum-mining/ethminer#589]
Circle CI:
`
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/zesty-security/universe/source/Sources  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/zesty/universe/source/Sources  404  Not Found [IP: 91.189.88.149 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/zesty-updates/universe/source/Sources  404  Not Found [IP: 91.189.88.149 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/zesty-backports/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.`

Travis CI:
`hunter] BOOST_ROOT: /Users/travis/.hunter/_Base/59b2b88/c3f1e39/962db2c/Install (ver.: 1.66.0)
-- [hunter] Cache HIT: Boost
-- [hunter] Cache info: /Users/travis/.hunter/_Base/Cache/meta/c3f1e39/Boost/1.66.0/075d0b4/da39a3e/d41f56c/d435a6c/da39a3e/cache.sha1
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
`

**Comment by DanielRamosAcosta** [comment]
I'm having this issue true, but not with CI. I'm in my local computer with Ubuntu Zesty Zapus 17.04 and I can't access Ubuntu's archives.

It's seems that they have gone down, as those IPs gives the Apache default page. Maybe some is attacking Ubuntu repos?
