### ISSUE TITLE
My his rx 580 8gb oc has low hassrate?

### ISSUE THREAD

**Issue by cnetclub** [ethereum-mining/ethminer#593]
Hi.. 
Im new in mining. I have buy his rx 580 8gb oc. But after i download claymore and i try to singgle mining eth. Hassrate only get 17-18mhs. Any one to help me please....

**Comment by AndreaLanfranchi** [comment]
This is not Claymore's software support area.
Have you tried with ethermine ?

**Comment by lightbored** [comment]
I'll take you on my adventure of my ASUS ROG-STRIX-RX580-T8G-GAMING card experience with ethminer.

I got this card at the beginning of December to compliment my GTX 1070 card that I've had for a long time in my gaming system. I was thinking, let me see how the other side (AMD) goes. Stock on supplied drivers it got 17 Mh/s. I found the ATI mining drivers and that pushed me up to 19 Mh/s. Then I started tinkering with the BIOS and a little overclocking and pushed it up to it's current average of 25.5Mh/s.

After going through all of that, I am going to happily stick to the easier nVidia (more expensive) cards :)

**Comment by cnetclub** [comment]
Wow nice.. can you help me to the overclock?

**Comment by jean-m-cyr** [comment]
> After going through all of that, I am going to happily stick to the easier nVidia (more expensive) cards :)

Why do you say more expensive? I can get a 3GB 1060 for about $250 (less before Christmas). I see the rx580 at about $550. The 1060 will easily get you 20mh/s at half the power.

**Comment by efrasyad** [comment]
> Why do you say more expensive? I can get a 3GB 1060 for about $250 (less before Christmas). I see the rx580 at about $550. The 1060 will easily get you 20mh/s at half the power.

He probably referred to GTX 1070 which is obviously more expensive than RX580 MSRP.

**Comment by tribalpixel** [comment]
for all people searching good bios for mining:
[try anoral.tech](https://anorak.tech/)
;)

**Comment by hubbertj** [comment]
@tribalpixel 

Thanks, I will give their bios a run. all my 570 and 580 are running at 17 -19 MH/s. Pretty disappointing but its still very profitable.

**Comment by lightbored** [comment]
Sorry, I ran away for a bit... I was comparing the RX580 with my GTX 1070 because they have the same amount of RAM and are considered 2nd from the top (GTX 1080ti vs AMD Vega being top). I got my RX580 before xmas for $318 vs my GTX 1070 FTW2 for $509.

After tweaking my 1070 now, it now runs at ~31.8 and RX580 is at 26.6.

**Comment by jramos** [comment]
@cnetclub @hubbertj - I have 4GB 470s getting ~21 MHs without any mods. If you're using Linux, be sure you have large page support enabled for AMDGPU -- `amdgpu.vm_fragment_size=9`. Hashrate should increase by ~10-15%.

Ref: https://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Driver-for-Linux-Release-Notes.aspx

**Comment by guzzijones** [comment]
@lightbored care to elaborate on the bios settings, and the driver you downloaded?  I am also only at about 15 Mh/s.  I am on windows.  RX580 8 gig.

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
