### ISSUE TITLE
Restart mining on card/driver failure

### ISSUE THREAD

**Issue by vlascik** [ethereum-mining/ethminer#60]
Whenever a driver fails (unstable overclock, some driver issue), the mining stops, which could lead to significant losses.
This is pretty much the only reason I'd use Claymore, which handles this situation pretty well.

**Comment by JHGitty** [comment]
Isn't it a better way to fix the instability issue? ;-)

Overall I agree that an auto-restart feature would be awesome!

**Comment by vlascik** [comment]
That's not always immediately possible, these issues like to happen when you're asleep/away from the computer. Sometimes you don't notice even if you are on the computer. This lost me quite a few hours already.
Claymore restarts mining gratefully, newest version can even restart whole system if the speed is below a threshold (perfect when one of the cards died but will recover after a restart). Maybe it could also restart driver the way NvidiaInspector does? I'm sure there is some call for that.

**Comment by rainbowhat** [comment]
+1

**Comment by dawjdh** [comment]
Workaround : [https://github.com/ethereum-mining/ethminer/issues/199#issuecomment-345067435](https://github.com/ethereum-mining/ethminer/issues/199#issuecomment-345067435)

**Comment by DeadManWalkingTO** [comment]
I believe now the issue have been solved #757 (added --exit parameter to exit whenever an error occurred).

**Comment by DeadManWalkingTO** [comment]
After #757 (added --exit parameter to exit whenever an error occurred) you can use a watchdog.

Try [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) Windows7/8/10 [32/64] & Linux (Any Dist/Any Ver/Any Arch) (#735).

Check and feedback please.
Thank you!
