### ISSUE TITLE
Crash in benchmarking OpenCL: CL_INVALID_KERNEL -48 

### ISSUE THREAD

**Issue by chfast** [ethereum-mining/ethminer#600]
Just run `ethminer -G -M` to reproduce.

**Comment by MariusVanDerWijden** [comment]
Works with CUDA
./ethminer -U -M

`cu  18:56:43|ethminer  Using grid size 8192 , block size 128
Benchmarking on platform: CUDA
Preparing DAG for block #0
  ℹ  18:56:43|CUDA0     No work. Pause for 3 s.
Warming up...
  ℹ  18:56:46|CUDA0     Initialising miner...
 cu  18:56:47|CUDA0     Using device: GeForce GTX 1080  (Compute 6.1)
 cu  18:56:47|CUDA0     Set Device to current
 cu  18:56:47|CUDA0     Resetting device
 cu  18:56:47|CUDA0     Allocating light with size: 16776896
 cu  18:56:47|CUDA0     Generating mining buffers
 cu  18:56:47|CUDA0     Generating DAG for GPU # 0  with dagSize: 1073739904  gridSize: 8192  &m_streams[0]: 0x7f5e280026a0
Trial 1... 9442849
Trial 2... 9574239
Trial 3... 9861545
Trial 4... 9862531
Trial 5... 9861545
min/mean/max: 9442849/9720541/9862531 H/s
inner mean: 9766105 H/s
`

**Comment by MariusVanDerWijden** [comment]
confirmed with opencl
