### ISSUE TITLE
stratum Parse response failed: * Line 1, Column 22 Missing ',' or '}' in object declaration

### ISSUE THREAD

**Issue by cypheron** [ethereum-mining/ethminer#608]
Case related to #142 (which was closed wns), but not exactly the same issue. Parsing error in server json response and subsequent hang up.

I'm running ethminer 0.13.0rc7 on Ubuntu 16.04.3. installed on an USB stick. I was suspecting maybe it is disk issue when json file is not written fast enough. However, I do not know how to get any debug information out of ethminer...

Here is my log:

```
ℹ 11:14:16|stratum Received new job #2d73c83a seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf [1642/45351]
ℹ 11:18:02|CUDA0 Solution found; Submitted to eth-eu1.nanopool.org
ℹ 11:25:18|CUDA1 Solution found; Submitted to eth-eu1.nanopool.org
ℹ 11:28:52|CUDA0 Nonce: 0xafa40dd6d96ed38f
ℹ 11:28:52|CUDA1 Nonce: 0x8bf304f3599555d6
ℹ 11:28:52|stratum Received new job #064b98bc seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
ℹ 11:28:52|stratum No new work received in 180 seconds.
ℹ 11:28:52|stratum Reconnecting in 3 seconds...
ℹ 11:28:55|stratum Connecting to stratum server eth-eu1.nanopool.org:9999
ℹ 11:28:55|stratum Received new job #b5ddbc7e seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
ℹ 11:28:55|stratum Connected to stratum server eth-eu1.nanopool.org : 9999
ℹ 11:28:55|stratum Received new job #f9868742 seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
✘ 11:28:55|stratum Parse response failed: * Line 1, Column 22
Missing ',' or '}' in object declaration

ℹ 11:28:58|stratum Received new job #407f08a1 seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
ℹ 11:29:06|stratum Received new job #80b980f9 seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
ℹ 11:29:30|stratum Received new job #aba61a0d seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
✘ 11:29:40|CUDA0 Can't submit solution: Not connected
ℹ 11:29:46|stratum Received new job #b73e27a9 seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
ℹ 11:29:49|stratum Received new job #ffea08fc seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
✘ 11:29:56|CUDA1 Can't submit solution: Not connected
ℹ 11:30:01|stratum Received new job #9c71072c seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
ℹ 11:30:10|stratum Received new job #ca1bb2d5 seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
ℹ 11:30:13|stratum Received new job #2120b49d seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
✘ 11:30:19|CUDA0 Can't submit solution: Not connected
ℹ 11:30:24|stratum Received new job #4a483e9e seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
ℹ 11:30:41|stratum Received new job #13963fe9 seed: #51e74ac038c9e3e66658ef25c1591022 target: #000000006df37f675ef6eadf
```

**Comment by satori-q3a** [comment]
just a debugger's 2 cents worth... but how's your internet connection?  Seems the first error is 'No new work received in 180 seconds.' and it goes down hill from there.

**Comment by cypheron** [comment]
@satori-q3a i have two rigs running, both on the same inter connection. only one fails.
I am now running through eth-proxy, this gives me some intel on the messages passed between client/server and should hopefully reveal at which point communication goes down hill.

**Comment by jasonwee** [comment]
think this happened, two days ago on dwarfpool? (23 january 2018), is this still happening?

**Comment by Mukundan314** [comment]
this happened also on ethermine

**Comment by georgedpeterson** [comment]
Happens to me on nanopool. Also running from a usb stick.

**Comment by cypheron** [comment]
Using stratum proxy I have been able to run for a week or so straight without having had the described issue on the very same rig. So I suspect that this really has to do with work fetching/delegation and simultaneous processing in the ethminer software. ethminer seems not able to recover from a parsing fault (which could happen in this case because of a slow storage drive).

**Comment by SnowLeopard71** [comment]
I've also encountered the _Parse error_ a few times (using nanopool), but running on SSD.
Is it possible the proxy "fixes" malformed responses?

**Comment by DeadManWalkingTO** [comment]
Try without proxy and feedback please.
Thank you!

**Comment by AndreaLanfranchi** [comment]
No feed back.
Closed
