### ISSUE TITLE
HELP: Ethminer stops accepting shares

### ISSUE THREAD

**Issue by Xeowolf** [ethereum-mining/ethminer#615]
So I finally got ethminer running last night and apparently minutes after I went to bed it had stopped accepting shares even though it ran all night doing jobs, I earned nothing. So I thought maybe it didn't like me using -RH and took that line out. For awhile today it was running fine, but just recently I noticed my hash falling so I took a look and sure enough no accepted share message again.

Can someone please assist and explain what might be causing this?
Windows 10 with 4 1060s
Bat file looks like this:
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

ethminer.exe --farm-recheck 2000 -U -S us1.ethermine.org:14444 -FS us2.ethermine.org:4444 -0 walletAddress.HomeCUDA

Scrolling up in the CMD window I see this error being output during one of the times this happened:
CUDA error in func 'dev::eth::cudaminer::search' at line 489 : unspecified launch failure

**Comment by satori-q3a** [comment]
How does it behave with "-U" instead of "-G" ?

**Comment by Xeowolf** [comment]
My apologies, it does have -U not -G.

**Comment by Xeowolf** [comment]
As a follow up for this, while using Claymore with the exact same rig / OS I did not run into this issue at all. Though Claymore was causing my OS to hang frequently.

**Comment by Xeowolf** [comment]
Why did this get closed? my issue isn't solved.

**Comment by piotr-dobrogost** [comment]
Recently, I've seen ethminer stopped reporting hashrate too. Can't give exact version but it was compiled from master about a week ago.

**Comment by emocanu** [comment]
This happen often if you overclock the GPU memory too much.
Is this the case?

**Comment by Xeowolf** [comment]
So here is the update and my findings.
I tried numerous different settings for the bat file, for windows, driver updates, bios changes, etc to get it more stable and nothing has worked. This was with all 4 GPU's at standard clock speeds, so no overclocking.
I then pulled all the cards out and disconnected the risers. I reconnected two of the video cards, and let it run for 2 nights. It was fine, no issues. I then swapped the video cards and same thing, they are working fine too.

So it's not the video cards. At this point it is either the risers (1 or more of them) or having 4 GPU's on the motherboard is breaking something in the software.

**Comment by Xeowolf** [comment]
For anyone who comes across this issue the solution:
One of your risers may be bad. I had to test each riser one by one to figure out which one but problem has since been solved. Running stable without issues.

**Comment by Easwood** [comment]
What was your method of checking each riser?

**Comment by Xeowolf** [comment]
I had 4 video cards. I reduced the rig down to two cards and let them run at base line levels no over clocking at least very very slight over clocking if any. And then I let those run for 24-48 hours. It would depend on how quickly you were getting issues. If it already can run 24 hours frequently then you need to let those two go longer. - If you run into an issue with those 2 cards drop it down to 1 card and test it again for the full duration.- If it is one of those cards, then you need to replace the riser on the trouble card and then run the test with that card again and no more than 2 cards total. To make sure everything is stable and eliminate the possibility that it's not the card.- Once you are stable with 2 cards for 24-48 hours add 1 more card at a time and run for that duration again. This will help you identify additional issues with any other risers as you go.    On Friday, April 27, 2018, 10:38:23 AM CDT, Easwood <notifications@github.com> wrote:  
 
 
What was your method of checking each riser?

**Comment by Easwood** [comment]
Thanks for the write up, I had them running again to check for the specific error and it's the same as yours. I'm going to run default clock speeds then try the method you recommended for checking the risers.

Do you remember if you received one instance of the error or was it similar to mine (all 4, see below notice cuda-1, cuda-2, ...)? Also, are you using USB risers?

CUDA error in func 'dev::eth::CUDAMiner::search' at line 489 : unspecified launch failure.

  X  20:24:52|cuda-1    Error CUDA mining: unspecified launch failure

CUDA error in func 'dev::eth::CUDAMiner::search' at line 489 : unspecified launch failure.

  X  20:24:52|cuda-2    Error CUDA mining: unspecified launch failure

CUDA error in func 'dev::eth::CUDAMiner::search' at line 489 : unspecified launch failure.

  X  20:24:52|cuda-3    Error CUDA mining: unspecified launch failure

CUDA error in func 'dev::eth::CUDAMiner::search' at line 489 : unspecified launch failure.

  X  20:24:52|cuda-0    Error CUDA mining: unspecified launch failure
