### ISSUE TITLE
Low hash rates with GTX 980m

### ISSUE THREAD

**Issue by digdug82** [ethereum-mining/ethminer#617]
Trying to mine using My Alienware 15 with GTX 980m, When I use widnows 8.1 I get 5.xMH/s and when I use UBUNTU amd I'm getting 7.67MH/s, I tried everything I could found using google with no luck.
Any help would be appreciated.

**Comment by chfast** [comment]
Use Ubuntu then.

**Comment by DeadManWalkingTO** [comment]
Windows use GPU for Desktop.
Maybe that's the problem.
Same here with my 1st GPU on rig.

**Comment by Angel996** [comment]
You can't really use GTX 980 or any other Maxwell based GPU for Ethereum mining because of large DAG file size. Hashrates will be very low.
