### ISSUE TITLE
Enhancement idea: make the "Solution found" message yellow in color

### ISSUE THREAD

**Issue by smcgeeak** [ethereum-mining/ethminer#619]
I think it would be great if this message...

Solution found; Submitted to <insert name of mining pool here>
Nonce: 0xc49bf6fe2b86e701
Accepted.

...could be displayed as yellow text on the black background of the command window. It would make it easy to see your found solutions at a glance. See the screenshot mock-up below for an example of what I have in mind.

Is this something that could be added to a future release of ethminer? It seems like it would be a fairly simple thing to implement.

![example-yellow-solution](https://user-images.githubusercontent.com/35796380/35379096-6fdb859c-0161-11e8-82bd-c743f1b73148.jpg)

**Comment by MariusVanDerWijden** [comment]
https://github.com/ethereum-mining/ethminer/pull/604 Already in Master, comes with next release

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
