### ISSUE TITLE
Help Ethminer stops reporting share accepted

### ISSUE THREAD

**Issue by Xeowolf** [ethereum-mining/ethminer#620]
Making a new ticket as my last one got closed without any assistance. :(

Ethminer will run anywhere between a few minutes to hours and report has such that etherminer.org will show an updated status. Somewhere along the way it stops giving share accepted but keeps running jobs. Scrolling up in the CMD window I see this error being output during one of the times this happened:
CUDA error in func 'dev::eth::cudaminer::search' at line 489 : unspecified launch failure

I tried vs .13 and 13rc9 both have this issue.

Can someone please assist and explain what might be causing this?

Windows 10 with 4 1060s
Bat file looks like this:
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

ethminer.exe --farm-recheck 2000 -U -S us1.ethermine.org:14444 -FS us2.ethermine.org:4444 -0 walletAddress.HomeCUDA

Scrolling up in the CMD window I see this error being output during one of the times this happened:
CUDA error in func 'dev::eth::cudaminer::search' at line 489 : unspecified launch failure

**Comment by piotr-dobrogost** [comment]
Duplicate of issue #615 which should be reopened.

**Comment by Xeowolf** [comment]
For anyone who comes across this issue the solution:
One of your risers may be bad. I had to test each riser one by one to figure out which one but problem has since been solved. Running stable without issues.
