### ISSUE TITLE
Mining is not starting/working

### ISSUE THREAD

**Issue by 303benjamin** [ethereum-mining/ethminer#621]
This ist what i see now:

C:\Program Files\Etherminer\bin>setx GPU_FORCE_64BIT_PTR 0

ERFOLGREICH: Angegebener Wert wurde gespeichert.

C:\Program Files\Etherminer\bin>setx GPU_MAX_HEAP_SIZE 100

ERFOLGREICH: Angegebener Wert wurde gespeichert.

C:\Program Files\Etherminer\bin>setx GPU_USE_SYNC_OBJECTS 1

ERFOLGREICH: Angegebener Wert wurde gespeichert.

C:\Program Files\Etherminer\bin>setx GPU_MAX_ALLOC_PERCENT 100

ERFOLGREICH: Angegebener Wert wurde gespeichert.

C:\Program Files\Etherminer\bin>setx GPU_SINGLE_ALLOC_PERCENT 100

ERFOLGREICH: Angegebener Wert wurde gespeichert.

C:\Program Files\Etherminer\bin>ethminer.exe -G -S eu2.ethermine.org:4444 -FS us1.ethermine.org:4444 -O MYWALLET.hiddenpath
  i  20:09:11|main      Found suitable OpenCL device [ Oland ] with 3221225472  bytes of GPU memory
  i  20:09:11|main      Connecting to stratum server eu2.ethermine.org:4444
  i  20:09:11|stratum   Connected to stratum server eu2.ethermine.org : 4444
  i  20:09:11|stratum   Starting farm
 cl  20:09:11|cl-0      No work. Pause for 3 s.
  i  20:09:11|stratum   Subscribed to stratum server
  i  20:09:11|stratum   Authorized worker MYWALLET.hiddenpath
  i  20:09:11|stratum   Received new job #c9bcffc5  seed: #51e74ac038c9e3e66658ef25c1591022  target: #0000000112e0be826d694b2e
  i  20:09:12|stratum   Received new job #41a67e84  seed: #51e74ac038c9e3e66658ef25c1591022  target: #0000000112e0be826d694b2e
  m  20:09:13|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  20:09:14|cl-0      New work: header #41a67e84ÔÇª target 0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba
 cl  20:09:14|cl-0      New seed #51e74ac0ÔÇª
  m  20:09:15|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  20:09:16|cl-0      Platform: AMD Accelerated Parallel Processing
 cl  20:09:16|cl-0      Device:   Oland  / OpenCL 1.2 AMD-APP (1800.5)
  m  20:09:17|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  i  20:09:18|stratum   Received new job #d623f34c  seed: #51e74ac038c9e3e66658ef25c1591022  target: #0000000112e0be826d694b2e
 cl  20:09:18|cl-0      Build info:
 cl  20:09:18|cl-0      Creating light cache buffer, size 38403392
 cl  20:09:18|cl-0      Creating DAG buffer, size 2457861248
 cl  20:09:18|cl-0      Loading kernels
 cl  20:09:18|cl-0      Writing light cache buffer
 cl  20:09:18|cl-0      Creating buffer for header.
 cl  20:09:18|cl-0      Creating mining buffer
 cl  20:09:18|cl-0      Generating DAG
  m  20:09:19|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  20:09:20|cl-0      DAG 0 %

My .bat

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe -G -S eu2.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x8b662C84d59Ff3CA0192F77baEDD019d437B89B2.hiddenpath

My Graphic Card is an ASUS R7 240 4GB DDR3

Where is the mistake? Can somebody help me? Thank you in advance!

P.s. @MariusVanDerWijden: Thank you for your answer in my last Issue.

**Comment by MariusVanDerWijden** [comment]
Did you solve it?

**Comment by 303benjamin** [comment]
I am not sure. Last time you said that my GPU were to slow. I bought an ASUS R7 240 4GB DDR3. I´d like to get a feeling for it before taking up with an RX 580 or something else

This is what i am seeing now:

  i  22:03:48|main      Found suitable OpenCL device [ Oland ] with 3221225472  bytes of GPU memory
  i  22:03:48|main      Connecting to stratum server eu2.ethermine.org:4444
  i  22:03:48|stratum   Connected to stratum server eu2.ethermine.org : 4444
  i  22:03:48|stratum   Starting farm
 cl  22:03:48|cl-0      No work. Pause for 3 s.
  i  22:03:48|stratum   Subscribed to stratum server
  i  22:03:48|stratum   Authorized worker MYWALLET.B-Homebase
  i  22:03:48|stratum   Received new job #f3e60fa0  seed: #51e74ac038c9e3e66658ef25c1591022  target: #0000000112e0be826d694b2e
  m  22:03:50|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  22:03:51|cl-0      New work: header #f3e60fa0ÔÇª target 0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba
 cl  22:03:51|cl-0      New seed #51e74ac0ÔÇª
  m  22:03:52|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  22:03:53|cl-0      Platform: AMD Accelerated Parallel Processing
 cl  22:03:53|cl-0      Device:   Oland  / OpenCL 1.2 AMD-APP (1800.5)
  m  22:03:54|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  22:03:55|cl-0      Build info:
 cl  22:03:55|cl-0      Creating light cache buffer, size 38403392
 cl  22:03:55|cl-0      Creating DAG buffer, size 2457861248
 cl  22:03:55|cl-0      Loading kernels
 cl  22:03:55|cl-0      Writing light cache buffer
 cl  22:03:55|cl-0      Creating buffer for header.
 cl  22:03:55|cl-0      Creating mining buffer
 cl  22:03:55|cl-0      Generating DAG
  i  22:03:56|stratum   Received new job #686f5894  seed: #51e74ac038c9e3e66658ef25c1591022  target: #0000000112e0be826d694b2e
  m  22:03:56|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  22:03:56|cl-0      DAG 0 %
 cl  22:03:58|cl-0      DAG 2 %
  m  22:03:58|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  22:03:59|cl-0      DAG 5 %
  m  22:04:00|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  22:04:00|cl-0      DAG 8 %
 cl  22:04:01|cl-0      DAG 10 %
  m  22:04:02|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  22:04:02|cl-0      DAG 13 %
 cl  22:04:03|cl-0      DAG 16 %
  m  22:04:04|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  22:04:04|cl-0      DAG 18 %
.
.
.
 m  22:05:12|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  22:05:12|cl-0      DAG 94 %
 cl  22:05:13|cl-0      DAG 97 %
 cl  22:05:13|cl-0      Switch time 13258 ms / 46080005 us
 cl  22:05:13|cl-0      New work: header #4b5c9cd8ÔÇª target 0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba
 cl  22:05:13|cl-0      Switch time 13278 ms / 10962 us
  m  22:05:14|main      Speed   2.10 Mh/s    gpu/0  2.10  [A0+0:R0+0:F0] Time: 00:00
  m  22:05:16|main      Speed   1.75 Mh/s    gpu/0  1.75  [A0+0:R0+0:F0] Time: 00:00
  i  22:05:17|stratum   Received new job #279e3ac2  seed: #51e74ac038c9e3e66658ef25c1591022  target: #0000000112e0be826d694b2e
 cl  22:05:17|cl-0      New work: header #279e3ac2ÔÇª target 0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba
 cl  22:05:17|cl-0      Switch time 446 ms / 10349 us
  m  22:05:18|main      Speed   1.49 Mh/s    gpu/0  1.49  [A0+0:R0+0:F0] Time: 00:00
  i  22:05:18|stratum   Received new job #d07cf57b  seed: #51e74ac038c9e3e66658ef25c1591022  target: #0000000112e0be826d694b2e
 cl  22:05:19|cl-0      New work: header #d07cf57bÔÇª target 0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba
 cl  22:05:19|cl-0      Switch time 150 ms / 8121 us
  m  22:05:20|main      Speed   1.52 Mh/s    gpu/0  1.52  [A0+0:R0+0:F0] Time: 00:00
  m  22:05:22|main      Speed   1.53 Mh/s    gpu/0  1.53  [A0+0:R0+0:F0] Time: 00:00
  i  22:05:24|stratum   Received new job #0641c747  seed: #51e74ac038c9e3e66658ef25c1591022  target: #0000000112e0be826d694b2e
 cl  22:05:24|cl-0      New work: header #0641c747ÔÇª target 0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba
 cl  22:05:24|cl-0      Switch time 148 ms / 10982 us
  m  22:05:24|main      Speed   1.48 Mh/s    gpu/0  1.48  [A0+0:R0+0:F0] Time: 00:01
  m  22:05:26|main      Speed   1.38 Mh/s    gpu/0  1.38  [A0+0:R0+0:F0] Time: 00:01
  m  22:05:28|main      Speed   1.47 Mh/s    gpu/0  1.47  [A0+0:R0+0:F0] Time: 00:01
  i  22:05:30|stratum   Received new job #774faa74  seed: #51e74ac038c9e3e66658ef25c1591022  target: #0000000112e0be826d694b2e
  m  22:05:30|main      Speed   1.47 Mh/s    gpu/0  1.47  [A0+0:R0+0:F0] Time: 00:01
 cl  22:05:30|cl-0      New work: header #774faa74ÔÇª target 0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba
 cl  22:05:30|cl-0      Switch time 365 ms / 9228 us
  m  22:05:32|main      Speed   1.47 Mh/s    gpu/0  1.47  [A0+0:R0+0:F0] Time: 00:01
  m  22:05:34|main      Speed   1.54 Mh/s    gpu/0  1.54  [A0+0:R0+0:F0] Time: 00:01
  m  22:05:36|main      Speed   1.43 Mh/s    gpu/0  1.43  [A0+0:R0+0:F0] Time: 00:01
  m  22:05:38|main      Speed   1.43 Mh/s    gpu/0  1.43  [A0+0:R0+0:F0] Time: 00:01
  i  22:05:39|stratum   Received new job #0c418182  seed: #51e74ac038c9e3e66658ef25c1591022  target: #0000000112e0be826d694b2e
 cl  22:05:40|cl-0      New work: header #0c418182ÔÇª target 0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba
 cl  22:05:40|cl-0      Switch time 141 ms / 7643 us
  m  22:05:40|main      Speed   1.56 Mh/s    gpu/0  1.56  [A0+0:R0+0:F0] Time: 00:01
  m  22:05:42|main      Speed   1.55 Mh/s    gpu/0  1.55  [A0+0:R0+0:F0] Time: 00:01
  m  22:05:44|main      Speed   1.55 Mh/s    gpu/0  1.55  [A0+0:R0+0:F0] Time: 00:01


Is this the actual mining? I never saw the mining process - so i am not sure what i see....
@MariusVanDerWijden

**Comment by 303benjamin** [comment]
I forgot to mention that my gpu is a asus r7 4gb ddr3 dies this help?

**Comment by MariusVanDerWijden** [comment]
Are you using the newest release? https://github.com/ethereum-mining/ethminer/releases/tag/v0.13.0

**Comment by 303benjamin** [comment]
I checked the release - i use v.013... I don´t know what to do...
Btw. What is the difference between etherminer and etherminer dbg for windows? I tried both - does not work.
