### ISSUE TITLE
use steady clock for timing

### ISSUE THREAD

**Issue by nerdralph** [ethereum-mining/ethminer#626]
steady clock is guaranteed not to change for things like leap seconds and dst.
Some of the code in CLMiner.cpp is using std::chrono::high_resolution_clock.
Here's an description of the 3 stl clocks:
http://www.modernescpp.com/index.php/the-three-clocks

**Comment by nerdralph** [comment]
I've got changes to CLMiner.cpp I'm currently working on, and don't want to juggle branches around.  Even though it's a simple change, I won't be getting to it soon.

**Comment by DeadManWalkingTO** [comment]
Any news here?

**Comment by nerdralph** [comment]
I've started work on writing a new ethereum miner in go (called miNR) , so
I won't be making time to contribute to ethminer until I'm finished.
