### ISSUE TITLE
Windows 10 Build Issue

### ISSUE THREAD

**Issue by Sineos** [ethereum-mining/ethminer#63]
Trying to build commit 4332082530235cfd8fb6a7ce1f1670fecc448b20 on a Win 10 machine:

- Visual Studio Version 12.0.31101.0
- cmake version 3.9.0-rc4

`cmake ..` runs fine but on `cmake --build .` I get follwoing errors: https://pastebin.com/akD4MSxa

Any pointer to what I'm doing wrong would be appreciated

**Comment by Sineos** [comment]
Ok, I'm one step further. I updated to VS 14 2015 as per #24 and the build passes the position where it initially errored out.
Now upon linking I get following errors: https://pastebin.com/YmyiPA3C

**Comment by flagstone78** [comment]
I had the same issue. I then tried doing cmake .. -G "Visual Studio 14 2015 Win64" as it says at the bottom of the build section. I opened the generated .sln file in visual studio 2015 and compiled it (as release). It gave me a access denied error at the end of compiling, but i found and ran ethminer.exe under build/ethminer/Release. I am still in the process of seeing if it actually compiled correctly, but that is my progress on the matter.

**Comment by J0-nas** [comment]
You're both further than I am. Maybe you can help me. Do I need to install something else besides cmake and some c/c++ compiler (clang/clang++ is included in my PATH)? The wired thing is that If I use the linux subsystem I get further - fail at building the boost dependency...

If I don't specifiy a generator on windows I get this error:
```
PS C:\ethminer\build>  cmake ..
-- Building for: NMake Makefiles
-- [hunter] Initializing Hunter workspace (435b09a4eec7fd58486bfb61efb1044ddb85c0f0)
-- [hunter]   https://github.com/ruslo/hunter/archive/v0.18.57.tar.gz
-- [hunter]   -> C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a
The system cannot find the file specified
CMake Error: Generator: execution of make failed. Make command was: "nmake" "/NOLOGO"

[hunter ** INTERNAL **] Build project failed
[hunter ** INTERNAL **] [Directory:C:/ethminer]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at cmake/HunterGate.cmake:82 (message):
Call Stack (most recent call first):
  cmake/HunterGate.cmake:92 (hunter_gate_wiki)
  cmake/HunterGate.cmake:345 (hunter_gate_internal_error)
  cmake/HunterGate.cmake:498 (hunter_gate_download)
  CMakeLists.txt:10 (HunterGate)


-- Configuring incomplete, errors occurred!
```

If i specify the Visual Studio 15 2017 Win64 generator I get a different error (the MSBuild.exe might yet not be correctly linked).

```
PS C:\ethminer\build>  cmake .. -G "Visual Studio 15 2017 Win64"
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:






[hunter ** INTERNAL **] Configure project failed
```

**Comment by chfast** [comment]
@Sineos you have to build configuration other than "Debug". Try "Release" or "RelWithDebInfo".

**Comment by Sineos** [comment]
@chfast 
Many thanks for your help, but I cannot get it to build release. I started from scratch and tried to build it out of source with:
`cmake -DCMAKE_BUILD_TYPE=Release ../ethminer`

I even added `set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}")` to CMakeLists.txt but I always end up on Debug with the Linker errors --> https://pastebin.com/ngucCWz0

**Comment by chfast** [comment]
Because `CMAKE_BUILD_TYPE` is not for toolsets like Visual Studio. You have to open Visual Studio and change it within a combo box, or build with `cmake --build . --config Release`.

**Comment by Sineos** [comment]
Cool, it worked. Again something learned ;-)
Many thanks!

**Comment by YanBellavance** [comment]
to fix this:
``d:\21_git\ethminer\libdevcore\Exceptions.h(38): error C3646: 'noexcept' : unknown override specifier (D:\21_Git\ethminer\libdevcore\RLP.cpp)``
replace with:
``throw()`` or define it yourself:
``#define noexcept``

**Comment by YanBellavance** [comment]
to fix this:
``d:\21_git\ethminer\libdevcore\Worker.h(104): error C2039: 'unique_ptr' : is not a member of 'std' (D:\21_Git\ethminer\libdevcore\Worker.cpp)``
include:
``#include <memory>``

**Comment by chfast** [comment]
@YanBellavance What version of Visual Studio do you have?

**Comment by jimmykl** [comment]
@Sineos If you are after a particular release the Appveyor system automatically builds exe's for every commit. You can browse them all at https://ci.appveyor.com/project/ethereum-mining/ethminer/history

In this case commit 4332082 is https://ci.appveyor.com/project/ethereum-mining/ethminer/build/94

Then under 'Job name' select 'Configuration: release' and select 'Artifacts' then you can download the zipped exe.

If you want to build on Windows 10 to do some development what worked for me was:

- Install the latest CUDA SDK and patch https://developer.nvidia.com/cuda-downloads
- Install cmake https://cmake.org/download/ (I used 3.8.2)
- Install Visual Studio 2015 https://www.visualstudio.com/vs/older-downloads/
- Download this repo and go to the directory
```
mkdir build; cd build
cmake .. -DETHASHCL=OFF -DETHASHCUDA=ON
cmake --build . --config Release
```

The first time you compile it will take a while, especially setting up Boost, but it won't take so long the next time because Hunter caches the built libraries.

Hopefully one of these suggestions helps you out. If it does please close the issue :-)

**Comment by chfast** [comment]
@jimmykl, can you add this description about AppVeyor to README?

**Comment by jimmykl** [comment]
Sure thing @chfast see https://github.com/ethereum-mining/ethminer/pull/120

**Comment by Sineos** [comment]
@jimmykl 
Many thanks for the points, I successfully managed to build it, once @chfast pointed me to the release build. I know about AppVeyor, it was just out of curiosity because I enjoy playing with such stuff ;-)

From my PoV it can be closed but there are additional questions, e.g. from @YanBellavance. I leave it to your descretion to close it.

**Comment by jimmykl** [comment]
Glad you got it working @Sineos 

@YanBellavance are you ok with this being closed? If you still have further questions you can start a new issue.

**Comment by DeadManWalkingTO** [comment]
I think it's time to close this Issue.

**Comment by YanBellavance** [comment]
It`s been a long time I haven't touched mining so I can't say off the top of my ead. But basically all of them. I have it running on all Visual Studios starting with 2012.

**Comment by DeadManWalkingTO** [comment]
Any PR is welcome!!
