### ISSUE TITLE
Ethminer doesn't work

### ISSUE THREAD

**Issue by jasonhuang0081** [ethereum-mining/ethminer#634]
Hello, I'm new to the mining. This is what I get when I run my bat file

 i  18:36:29|main      Found suitable OpenCL device [ Intel(R) HD Graphics 515 ] with 3384087348  bytes of GPU memory
  i  18:36:29|main      Connecting to stratum server eu1.ethermine.org:4444
  i  18:36:29|stratum   Connected to stratum server eu1.ethermine.org : 4444
  i  18:36:29|stratum   Starting farm
 cl  18:36:30|cl-0      No work. Pause for 3 s.
  i  18:36:30|stratum   Subscribed to stratum server
  i  18:36:30|stratum   Authorized worker 0xe9bB06F3d4cd3663b0e9EA334803bC5A6180C102
  i  18:36:30|stratum   Received new job #9b0e89bd  seed: #51e74ac038c9e3e66658ef25c1591022  target: #0000000112e0be826d694b2e
  m  18:36:30|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  18:36:30|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  18:36:30|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  18:36:31|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  18:36:31|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  18:36:31|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  18:36:31|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  18:36:32|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  18:36:32|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  18:36:32|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  18:36:32|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  18:36:32|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  18:36:33|cl-0      New work: header #9b0e89bd?

Then, it stop doing anything, so I close it down.
How should I fix it? Thanks!

**Comment by jasonwee** [comment]
rate is 0? i think you need a better gpu (nvidia/amd). don't think intel gpu able to do mining.

**Comment by jramos** [comment]
You're trying to mine with an iGPU on a really low-powered processor. You should buy an actual video card.

**Comment by kronem** [comment]
Make sure you select the opencl-platform your GPU's are on.

**Comment by AndreaLanfranchi** [comment]
Not an issue here.
Please close.

**Comment by doug65536** [comment]
I have zero rate on my GTX 2060 Super 8GB on 3950X. Should I get a faster GPU too?
