### ISSUE TITLE
binary from 0.13.0 source crashes at startup

### ISSUE THREAD

**Issue by Jacky-Cai** [ethereum-mining/ethminer#636]
My own built binary of 0.13.0 crashes consistently at startup. 

Exception thrown at 0x0F608E35 (amdocl.dll) in ethminer.exe: 0xC0000005: Access violation reading location 0x00000024. occurred 

![image](https://user-images.githubusercontent.com/6076972/35468432-7a20ef4e-0358-11e8-8ea4-3262b4948794.png)

the start cmd was ethminer.exe --farm-recheck 200 -G -S guangdong-pool.ethfans.org:13333 -O 0x5d89ddc98de0ea62974c1e321756d1b2d5d3f97c -SP 1 -v 9   
it's sapphire 570 4G with 17.10.3 driver installed. 

the strange things are: 
1. the pre-built binary of 0.13.0 works well. I am using vs 2017 community, and followed the windows build instructions (1. cmake .. ; 2. cmake --build . --config release)
2. the pre-built binary is 5.3MB, and my binary is only 785KB; 

I just like to know if there is any special build steps in the official release build.  
thanks very much

**Comment by chfast** [comment]
You built it without CUDA, that's why it's small.

**Comment by Jacky-Cai** [comment]
thanks. 
two quick questions: 
1. Which cuda version was used, cuda8 or cuda9? 
2. which build windows build env, vs 2015 or vs 2017?

**Comment by DeadManWalkingTO** [comment]
Try CUDA 9.x & VS2015.
I believe CUDA install problem.
Check and feedback please.
Thank you!
