### ISSUE TITLE
Floating average speed

### ISSUE THREAD

**Issue by ikebastuz** [ethereum-mining/ethminer#637]
Hello, gentlemen! At first - sry for poor english.
Before making a rig, i bought 1 gpu to set up and make tests.
It is Palit GTX 1060 6gb JetStream (Micron memory)
I set up default ethminer, mining only ETH with this settings
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --farm-recheck 200 -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O <Your_Ethereum_Address>.<RigName>

Overclocked a bit my card, made 60% power limit, +120 clock, +800 memory.
Miner shows me 22.5-22.7 pretty stable hashrate. 

Internet is by LAN->optic, so its stable as hell.

And this is what i see
![qqq](https://user-images.githubusercontent.com/24222413/35468515-8f86480c-0330-11e8-9c01-f813fd021748.png)

Valid shares are up-n-down, up-n-down, never straight, so the average speed is also waves-styles.
And i've read that difference between real rate and the one pool detects can be 2-5%. I have diff about 12-13%.
Why it behaves like that? Is there anything i can do?
Thanks in advance.

**Comment by AndreaLanfranchi** [comment]
This is perfectly normal.
The pool calculates the blue line (average hash speed in 1 hour) upon the number of submitted shares.
But shares are subjected to a "luck" factor when being found. A steady hash-rate (as reported by the miner) does not imply a steady and constant number of shares found.

You can easily check the same situation on other miners of the pool.
A few samples 
https://ethermine.org/miners/c52a28f294CE0F41742Ea2315F097869B999d9Da
https://ethermine.org/miners/13455330e894730F84915236503F6a5aa0136D10

**Comment by ikebastuz** [comment]
Thank you, sir. Just thought there is some kind of pattern for this "luck". Anyways, seems fine, looks like i can add some more GPU's.
