### ISSUE TITLE
100% cpu utilization when using more than 2 videocards

### ISSUE THREAD

**Issue by cfelicio** [ethereum-mining/ethminer#64]
I have a MSI Z270 SLI Plus with G4400, when I only had 2 GTX 1070, it would mine fine, now that I added another 4, ethminer starts very slow, and I can see 100% cpu utilization being the issue. Eventually it mines, but the console is extremely laggy.

I tried multiple versions (all the way back to genoils), and they all have the problem. I also found some threads from people complaining about the same problem, but no solution.

When using claymore, the cpu usage stays around 1%, and it mines fine, but I want to give the latest ethminer a try, as it should provide some nice optimization gains :)

any ideas?

**Comment by cfelicio** [comment]
umm, if I break down into 3 separate cmds, it work fine:

ethminer.exe --farm-recheck 200 -U --cuda-devices 4 5
ethminer.exe --farm-recheck 200 -U --cuda-devices 4 5
ethminer.exe --farm-recheck 200 -U --cuda-devices 4 5

**Comment by JHGitty** [comment]
I have the same issue. Please provide a fix for this.

**Comment by JHGitty** [comment]
Hi @cfelicio , please close this ticket because it has been / will be fixed inside #74.

**Comment by cfelicio** [comment]
done :)

**Comment by chfast** [comment]
Can you try this PR <https://github.com/ethereum-mining/ethminer/pull/110>?
