### ISSUE TITLE
0.14.0.dev0 : Lost work from GPU without warnings

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ethereum-mining/ethminer#643]
Latest build from source after merge of PR 642

Experiencing (on three different rigs) disconnection of work from one GPU (not always the same) without output of CUDA errors and without any NVRM error from DMESG.

Restarting ethminer only (no reboot) brings the _apparently_ failed GPU back on.

**Comment by MariusVanDerWijden** [comment]
Are your cards overclocked? This can be expected with the PR and overclocked cards

**Comment by AndreaLanfranchi** [comment]
Yes i am. But with same settings i had on 13 rc9

Sent from mobile. Apologies for brevity and typos.



In data 27 gennaio 2018 22:10:50 Marius van der Wijden 
<notifications@github.com> ha scritto:

**Comment by DekInc** [comment]
Strange, i had the same issue but was a problem with raisers, i have different versions and it looks like the pci-e connector to the motherbord only accepts that version and not other version, very strange, check out that if you have change pci-e risers from place

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!
