### ISSUE TITLE
Invalid argument: -HWMON

### ISSUE THREAD

**Issue by editorfatih** [ethereum-mining/ethminer#645]
Hi, when I add -HWMON parameter, I get this error, is it normal?

ethminer --simulation -HWMON

> Invalid argument: -HWMON

version v0.13.0

**Comment by jramos** [comment]
Swap the order. I.e.

```
ethminer -HWMON --simulation
```

**Comment by jramos** [comment]
There is an optional argument for `--simulation`, and with your ordering, `-HWMON` is being passed as that value.

```bash
--simulation [<n>] Mining test mode... Optionally specify block number.
```
