### ISSUE TITLE
Target always #00000000ffffffffffffffff and  can't find worker in the pool...

### ISSUE THREAD

**Issue by Alan-ZhangDaixi** [ethereum-mining/ethminer#650]
This is my .bat 

ethminer.exe --farm-recheck 4000 -U -S eth.f2pool.com:8008 -SF eth.f2pool.com:8080 -O wallet.miner0 -SP 1 -RH --cuda-parallel-hash 4 --cuda-grid-size 4096

I can see the right hashrate at local console but never find worker in the pool. it is strange that Target always #00000000ffffffffffffffff and no share. I really need someone to help me!!!Thank you!!!

**Comment by jean-m-cyr** [comment]
Works perfectly here!

  ℹ  01:05:58|cuda-1    Solution submitted to eth.f2pool.com
  ℹ  01:05:58|cuda-1    Nonce: 0xec88befa74991d72
  ℹ  01:05:59|stratum   **Accepted.

**Comment by Alan-ZhangDaixi** [comment]
![bug](https://user-images.githubusercontent.com/10813576/35510555-7d6ca1ca-0533-11e8-9ff1-4fab269c545e.png)

thank you for response @jean-m-cyr 
but my target always like this, i have no idea...

**Comment by DeadManWalkingTO** [comment]
Try latest version and feedback please.
Thank you!
