### ISSUE TITLE
Fails to exit since version 0.11 ++ (linux)

### ISSUE THREAD

**Issue by Yorper** [ethereum-mining/ethminer#652]
Version 0.11 was the last version to exit once pools were dropped. Versions 0.12 and 0.13 do not exit, they just sit in a never ending loop of 3 second retries to the pool.

This is the command string that works fine in 0.11 but no longer works in newer versions.

ethminer --cuda --cuda-streams 2 --farm-retries 0 -G -S pool.address:port -O username:x -FS exit

If something has changed or i'm doing something wrong please let me know and disregard, otherwise i'm stuck using 0.11 until this feature is fixed/returned.

Please note this is for the Linux edition, i have no idea if this is so for the Windows edition.

Thanks.

**Comment by jasonwee** [comment]
that is a failover stratum, have you try it?

**Comment by Yorper** [comment]
Yes in 0.11 it will exit. In 0.12 and newer (0.13) it does not exit. It just sits in retry connection loop.

**Comment by jasonwee** [comment]
it is -SF not -FS...

```
	-SF, --stratum-failover <host:port>  Failover stratum server at host:port
```

**Comment by Yorper** [comment]
It doesn't matter. with 0.11 -FS exit would exit. Now it does not. Netiher does -SF exit. All it does since versions newer than 0.11 is this...

 cl  15:34:36|cl-0      No work. Pause for 3 s.
 cl  15:34:39|cl-0      No work. Pause for 3 s.
 cl  15:34:42|cl-0      No work. Pause for 3 s.
 cl  15:34:45|cl-0      No work. Pause for 3 s.
 cl  15:34:48|cl-0      No work. Pause for 3 s.
 cl  15:34:51|cl-0      No work. Pause for 3 s.
 cl  15:34:54|cl-0      No work. Pause for 3 s.
 cl  15:34:57|cl-0      No work. Pause for 3 s.
 cl  15:35:00|cl-0      No work. Pause for 3 s.
 cl  15:35:03|cl-0      No work. Pause for 3 s.
 cl  15:35:06|cl-0      No work. Pause for 3 s.
 cl  15:35:09|cl-0      No work. Pause for 3 s.


It will do that forever and NEVER exit.

**Comment by AndreaLanfranchi** [comment]
I do not understand.

It seems like you do expect  a behavior like this:

```
   IF 
       primary stratum server does not respond
   THEN
       exit ethminer
   END 
```
If this is what you mean then ethminer was never meant to act like this.

Probably in older version you got this behavior due to an error of ethminer trying to resolve host "exit"

**Comment by Yorper** [comment]
Aah that is exactly what I want! :-) For ethminer to exit, and that is what was happening either 0.11.

Maybe this could be a feature request for newer versions as I need this behaviour for my miningpoolhub script.

To add an option to exit ethminer for no connection or for x amount of fails.

**Comment by MariusVanDerWijden** [comment]
> an option to exit ethminer for no connection or for x amount of fails.
