### ISSUE TITLE
IMPORTANT: Strawpoll Nvidia support

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ethereum-mining/ethminer#655]
Hey guys, we're planning on stopping support for Nvidia GPU's with compute capabilites 3.0 and 3.5, can you please answer this strawpoll? Thanks http://www.strawpoll.me/14955296

**Comment by MariusVanDerWijden** [comment]
poll will end 30.01. 21:00 GMT

**Comment by jasonwee** [comment]
okay, voted!

**Comment by DiazLv** [comment]
I am using 10 series which 6.1. does not effect me.
vote okey too

**Comment by satori-q3a** [comment]
Does NVidia even use them in any of their legacy drivers?

**Comment by jean-m-cyr** [comment]
@satori-q3a Yes, I believe they still support K40/K80.

**Comment by MariusVanDerWijden** [comment]
Official turnout: 
  35 for dropping sm_30, sm_35 
  2 against it
Sorry for everyone who still uses old cards, you may have to use another mining tool
