### ISSUE TITLE
Crash when i using intel platform.

### ISSUE THREAD

**Issue by SKlayer** [ethereum-mining/ethminer#656]
version;0.13.0
OS;Windows 10
OpenGL;Intel opengl 1.2(build 8)
![image](https://user-images.githubusercontent.com/20183734/35510598-ae4b7be0-0533-11e8-9df8-4d41a8f49752.png)

i  20:33:11|main      Found suitable OpenCL device [ Intel(R) Many Integrated Core Acceleration Card ] with 6055391232  bytes of GPU memory
  i  20:33:11|main      Connecting to stratum server stratum-eth.antpool.com:8008
  i  20:33:11|stratum   Connected to stratum server stratum-eth.antpool.com : 8008
  i  20:33:11|stratum   Starting farm
 cl  20:33:11|cl-0      No work. Pause for 3 s.
  i  20:33:11|stratum   Received new job #0x10747a  seed: #3aa8f28cac16bdd858f2a726a06d1217  target: #00000001ffffffffffffffff
  m  20:33:13|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  20:33:14|cl-0      New work: header #10747afa鈥?

**Comment by jasonwee** [comment]
买一个真正的GPU, 英特尔GPU不能挖掘

**Comment by AndreaLanfranchi** [comment]
Sorry. Only english here.
