### ISSUE TITLE
Latest MASTER does not compile anymore

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ethereum-mining/ethminer#657]
Trying to compile from latest pull.
Got these errors : 

```
-- Configuring done
-- Generating done
-- Build files have been written to: /home/prospector/ethereum-mining/ethminer/build
prospector@miner01:~/ethereum-mining/ethminer/build $ sudo cmake --build .
[  0%] Built target BuildInfo.h
[ 26%] Built target devcore
[ 38%] Built target ethash
[ 53%] Built target hwmon
[ 57%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
/home/prospector/ethereum-mining/ethminer/libethash-cuda/ethash_cuda_miner_kernel.cu(84): error: identifier "__shfl_sync" is undefined

/home/prospector/ethereum-mining/ethminer/libethash-cuda/ethash_cuda_miner_kernel.cu(100): error: identifier "__shfl_sync" is undefined

/home/prospector/ethereum-mining/ethminer/libethash-cuda/dagger_shuffled.cuh(35): error: identifier "__shfl_sync" is undefined
          detected during instantiation of "void ethash_search<_PARALLEL_HASH>(volatile search_results *, uint64_t) [with _PARALLEL_HASH=1U]"
/home/prospector/ethereum-mining/ethminer/libethash-cuda/ethash_cuda_miner_kernel.cu(54): here

/home/prospector/ethereum-mining/ethminer/libethash-cuda/dagger_shuffled.cuh(45): error: identifier "__shfl_sync" is undefined
          detected during instantiation of "void ethash_search<_PARALLEL_HASH>(volatile search_results *, uint64_t) [with _PARALLEL_HASH=1U]"
/home/prospector/ethereum-mining/ethminer/libethash-cuda/ethash_cuda_miner_kernel.cu(54): here

/home/prospector/ethereum-mining/ethminer/libethash-cuda/dagger_shuffled.cuh(77): error: identifier "__shfl_sync" is undefined
          detected during instantiation of "void ethash_search<_PARALLEL_HASH>(volatile search_results *, uint64_t) [with _PARALLEL_HASH=1U]"
/home/prospector/ethereum-mining/ethminer/libethash-cuda/ethash_cuda_miner_kernel.cu(54): here

/home/prospector/ethereum-mining/ethminer/libethash-cuda/dagger_shuffled.cuh(57): error: identifier "__shfl_sync" is undefined
          detected during:
            instantiation of "__nv_bool compute_hash<_PARALLEL_HASH>(uint64_t, uint64_t, uint2 *) [with _PARALLEL_HASH=1U]"
/home/prospector/ethereum-mining/ethminer/libethash-cuda/ethash_cuda_miner_kernel.cu(27): here
            instantiation of "void ethash_search<_PARALLEL_HASH>(volatile search_results *, uint64_t) [with _PARALLEL_HASH=1U]"
/home/prospector/ethereum-mining/ethminer/libethash-cuda/ethash_cuda_miner_kernel.cu(54): here

/home/prospector/ethereum-mining/ethminer/libethash-cuda/dagger_shuffled.cuh(57): error: identifier "__shfl_sync" is undefined
          detected during:
            instantiation of "__nv_bool compute_hash<_PARALLEL_HASH>(uint64_t, uint64_t, uint2 *) [with _PARALLEL_HASH=2U]"
/home/prospector/ethereum-mining/ethminer/libethash-cuda/ethash_cuda_miner_kernel.cu(27): here
            instantiation of "void ethash_search<_PARALLEL_HASH>(volatile search_results *, uint64_t) [with _PARALLEL_HASH=2U]"
/home/prospector/ethereum-mining/ethminer/libethash-cuda/ethash_cuda_miner_kernel.cu(55): here

/home/prospector/ethereum-mining/ethminer/libethash-cuda/dagger_shuffled.cuh(57): error: identifier "__shfl_sync" is undefined
          detected during:
            instantiation of "__nv_bool compute_hash<_PARALLEL_HASH>(uint64_t, uint64_t, uint2 *) [with _PARALLEL_HASH=4U]"
/home/prospector/ethereum-mining/ethminer/libethash-cuda/ethash_cuda_miner_kernel.cu(27): here
            instantiation of "void ethash_search<_PARALLEL_HASH>(volatile search_results *, uint64_t) [with _PARALLEL_HASH=4U]"
/home/prospector/ethereum-mining/ethminer/libethash-cuda/ethash_cuda_miner_kernel.cu(56): here

/home/prospector/ethereum-mining/ethminer/libethash-cuda/dagger_shuffled.cuh(57): error: identifier "__shfl_sync" is undefined
          detected during:
            instantiation of "__nv_bool compute_hash<_PARALLEL_HASH>(uint64_t, uint64_t, uint2 *) [with _PARALLEL_HASH=8U]"
/home/prospector/ethereum-mining/ethminer/libethash-cuda/ethash_cuda_miner_kernel.cu(27): here
            instantiation of "void ethash_search<_PARALLEL_HASH>(volatile search_results *, uint64_t) [with _PARALLEL_HASH=8U]"
/home/prospector/ethereum-mining/ethminer/libethash-cuda/ethash_cuda_miner_kernel.cu(57): here

9 errors detected in the compilation of "/tmp/tmpxft_00005d24_00000000-7_ethash_cuda_miner_kernel.cpp1.ii".
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.cmake:266 (message):
  Error generating file
  /home/prospector/ethereum-mining/ethminer/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o


libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:195: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o' failed
make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
CMakeFiles/Makefile2:431: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/all' failed
make[1]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by AndreaLanfranchi** [comment]
Please note I am on cuda 8
Do I have to switch to CUDA 9 ?

**Comment by jean-m-cyr** [comment]
Yes

**Comment by AndreaLanfranchi** [comment]
Yes what ? Need to switch to cuda 9 ?

**Comment by jean-m-cyr** [comment]
Yes, Cuda 9

**Comment by AndreaLanfranchi** [comment]
Disaster !
All OSs on USB sticks. With no sufficent space to upgrade.

**Comment by jean-m-cyr** [comment]
Hmm... I could restore support for 8. Not too hard

**Comment by jean-m-cyr** [comment]
But how long you gonna stay on 8? Need to upgrade eventually.

Disaster? A little strong... these are dev builds remember.

**Comment by AndreaLanfranchi** [comment]
Sorry if I appeared rude. Was not meant to be.

Problem is I handle about 40 rigs with 8Gb SUB sticks as storage.
And I was left with a pretty decent 900 Mb free.
Cuda 9 cannot upgrade on such sticks and have to rebuild images for all on new sticks.
A very boring and time consuming task.

**Comment by piotr-dobrogost** [comment]
@AndreaLanfranchi 
Sorry for offtopic, what OS do you use on these sticks?

**Comment by AndreaLanfranchi** [comment]
I use Ubuntu 16.04

**Comment by jean-m-cyr** [comment]
@AndreaLanfranchi Just pushed branch cuda8. Should restore cuda 8 compiles. I don't have 8, so please test and let me know. If there is consensus, I'll convert to PR.

**Comment by jean-m-cyr** [comment]
@AndreaLanfranchi @MariusVanDerWijden You are aware that code compiled under cuda 8 this way, will fail miserably on Volta. Right?

**Comment by MariusVanDerWijden** [comment]
thats why we shouldn't push it into the master, rather have the branch open for everyone who still needs cuda8

**Comment by MariusVanDerWijden** [comment]
I don't find a way to close the pr from @mosamlife without closing the branch

**Comment by jean-m-cyr** [comment]
Not sure if @AndreaLanfranchi wants to try. I have no issue with deleting this branch.

**Comment by AndreaLanfranchi** [comment]
Sorry guys had to leave for a couple of hours.

Do not want to sum my personal burdens to your great job.
I have planned to upgrade to cuda 9. So you can remove (at least for me) support for cuda 8.

**Comment by jean-m-cyr** [comment]
Or leave it. I just don't want to maintain it long-term.

**Comment by AndreaLanfranchi** [comment]
Just wanted to inform I completed upgrade of CUDA 9 and properly compiled ethminer latest master.
Running a test rig with 6 x GTX 1050 Ti

Bad news first:
Due to this I had to install latest Nvidia drivers 390.12 (instead of my previous 381.22) which has power draw measurement broken. Thus I have to rely on **power limit** set to determine the exact amount of power drawn by the rigs (even if a more precise measurement was appreciated).

Good news now:
Do not know if due to new CUDA release OR new driver version OR latest commits on master but rig seems to be more stable. At same overclock levels as previous setup I got (as reported by ethminer) a consistent 14.60 Mhs per GPU instead of previous 14.34. 

Will keep running for 12 hours at least to see if stability and effectiveness in general has improved.

This specific issue (at least for me) can be closed.

**Comment by jean-m-cyr** [comment]
@AndreaLanfranchi Good to hear.

nvidia-smi gives me power draw/max readings with 390.12 drivers

**Comment by AndreaLanfranchi** [comment]
> nvidia-smi gives me power draw/max readings with 390.12 drivers

R u on Windows ?
Cause I understand in Linux many have this problem. And yes ... I am on linux.

**Comment by AndreaLanfranchi** [comment]
This is my reading from nvidia-smi (driver 390.12) Linux Ubuntu 16.04

If not a problem could you post me a snapshot of your xorg.conf ? Maybe I forgot some coolbits.

```
    Power Readings
        Power Management            : Supported
        Power Draw                  : N/A
        Power Limit                 : 65.00 W
        Default Power Limit         : 75.00 W
        Enforced Power Limit        : 65.00 W
        Min Power Limit             : 52.50 W
        Max Power Limit             : 75.00 W
        Power Management Object     : N/A
        SW Power Cap                : Not Active
            HW Power Brake Slowdown : Not Active

```

**Comment by jean-m-cyr** [comment]
No same as you, Ubuntu 16.04

I regenerate my xorg.conf with:

sudo nvidia-xconfig -a --cool-bits=29 --allow-empty-initial-configuration --force-generate

from nvidia-smi

`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.12                 Driver Version: 390.12                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:04:00.0  On |                  N/A |
| 66%   82C    P2   **107W / 120W** |   2742MiB /  6069MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 106...  Off  | 00000000:05:00.0 Off |                  N/A |
`

**Comment by AndreaLanfranchi** [comment]
Nothing to do for me.
Maybe it's a problem for the 1050 Ti

**Comment by jean-m-cyr** [comment]
If you prefer different format for 1060:

    Power Readings
        Power Management            : Supported
        Power Draw                  : 110.22 W
        Power Limit                 : 120.00 W
        Default Power Limit         : 120.00 W
        Enforced Power Limit        : 120.00 W
        Min Power Limit             : 60.00 W
        Max Power Limit             : 140.00 W

**Comment by AndreaLanfranchi** [comment]
Maybe this applies.

https://devtalk.nvidia.com/default/topic/1024744/nvidia-387-12-breaks-power-reading-in-nvidia-smi-/

**Comment by AndreaLanfranchi** [comment]
In addition have to say that 1050 Ti is the only which reports P0 state while 1060 and 1070 report P2 state.

**Comment by AndreaLanfranchi** [comment]
A quick follow up.

12 hours round without a single glitch or hiccup.

`Speed  87.48 Mh/s    gpu/0 14.51  gpu/1 14.59  gpu/2 14.59  gpu/3 14.59  gpu/4 14.59  gpu/5 14.59  [A1087+7:R0+0:F0] Time: 13:30`

Very low stale hashes ratio.
Got same speed as with Cuda 8 and driver 381.22 lowering OC settings by roughly 3%

Red line depicts the switch from Cuda 8 to Cuda 9.

![immagine](https://user-images.githubusercontent.com/15280851/35560335-6cc615c0-05ad-11e8-9f2f-055c3f07a91e.jpg)


Thank you.

**Comment by jean-m-cyr** [comment]
I like it when orange an green overlap
