### ISSUE TITLE
windows.h not found on OpenBSD

### ISSUE THREAD

**Issue by janstary** [ethereum-mining/ethminer#659]
Current git does not compile on OpenBSD 6.2-current, failing with, ridiculously,

```
Scanning dependencies of target OpenCL
[ 25%] Building C object CMakeFiles/OpenCL.dir/icd_windows.c.o
/home/hans/.hunter/_Base/59b2b88/942d57b/962db2c/Build/OpenCL/Source/icd_windows
.c:40:10: fatal error: 'windows.h' file not found
#include <windows.h>
         ^~~~~~~~~~~
```

Am I missing something obvious?

**Comment by DeadManWalkingTO** [comment]
This is probably either an older unsupported compiler (gcc 4.5 or older) 
try
```
egcc --version
eg++ --version
```
OR 
boost configuration is not working on this OpenBSD compiler. 

Try
```
#include <boost/config.hpp>
#include <iostream>
int main () {
    std::cout << BOOST_GCC_VERSION << std::endl;
    return 0;
}
```
See what that outputs or if it fails to compile.

**Comment by janstary** [comment]
My `egcc` and `eg++` is GCC 4.9.4
The program compiles fine with `eg++` and outputs `40904`.
It does not compile with stock `c++` (which is clang 5.0.1) or `g++` (which is GCC 4.2.1)

During `env CC=egcc CXX=eg++ cmake ..` it fails with the above message.
I don't think the compiler has anything to do with it, it's a missing include file.

Is it supposed to find one of these?
```
$ find /home/hans/.hunter/ -name windows.h                       
/home/hans/.hunter/_Base/59b2b88/2ec6554/962db2c/Install/include/boost/predef/os/windows.h
/home/hans/.hunter/_Base/Cellar/a72d0c308c222d655e4b421cc8df9074fd1f06ad/a72d0c3/raw/include/boost/predef/os/windows.h
```

**Comment by XhmikosR** [comment]
Is this still an issue with the latest master?
