### ISSUE TITLE
CUDA error in func 'dev::eth::CUDAMiner::search'

### ISSUE THREAD

**Issue by maxcom99** [ethereum-mining/ethminer#662]
Running 3 x GTX 1070 after ~15min I get this error and then the hash rate "freezes" with no solutions found. Using latest 14.0.dev1 on windows 10.

  m  18:52:05|main      Speed  96.83 Mh/s    gpu/0 32.28 72C 89%  gpu/1 32.28 79C 94%  gpu/2 32.28 64C 84%  [A5+0:R0+0:F0]
  m  18:52:09|main      Speed  96.46 Mh/s    gpu/0 32.15 72C 89%  gpu/1 32.15 79C 94%  gpu/2 32.15 65C 84%  [A5+0:R0+0:F0]
  i  18:52:10|cuda-2    Solution found; Submitted to us1.ethermine.org
  i  18:52:10|cuda-2    Nonce: 0xd5a98aba332152d1
  i  18:52:10|stratum   Accepted.
  m  18:52:13|main      Speed  96.32 Mh/s    gpu/0 32.11 72C 89%  gpu/1 32.11 79C 94%  gpu/2 32.11 64C 84%  [A6+0:R0+0:F0]
  m  18:52:17|main      Speed  96.90 Mh/s    gpu/0 32.30 72C 89%  gpu/1 32.30 79C 94%  gpu/2 32.30 65C 84%  [A6+0:R0+0:F0]
  m  18:52:21|main      Speed  91.76 Mh/s    gpu/0 27.58 69C 89%  gpu/1 32.09 79C 94%  gpu/2 32.09 65C 84%  [A6+0:R0+0:F0]
  m  18:52:25|main      Speed  82.01 Mh/s    gpu/0 17.76 68C 87%  gpu/1 32.12 79C 94%  gpu/2 32.12 65C 84%  [A6+0:R0+0:F0]
  m  18:52:29|main      Speed  72.41 Mh/s    gpu/0  7.90 67C 86%  gpu/1 32.25 79C 95%  gpu/2 32.25 65C 84%  [A6+0:R0+0:F0]
CUDA error in func 'dev::eth::CUDAMiner::search' at line 491 : unspecified launch failure.
  X  18:52:31|cuda-0    Error CUDA mining: unspecified launch failure
CUDA error in func 'dev::eth::CUDAMiner::search' at line 491 : unspecified launch failure.
CUDA error in func 'dev::eth::CUDAMiner::search' at line 491 : unspecified launch failure.
  X  18:52:31|cuda-2    Error CUDA mining: unspecified launch failure
  X  18:52:31|cuda-1    Error CUDA mining: unspecified launch failure
  m  18:52:33|main      Speed  59.43 Mh/s    gpu/0  0.00 67C 86%  gpu/1 29.72 77C 93%  gpu/2 29.72 61C 81%  [A6+0:R0+0:F0]
  m  18:52:37|main      Speed  57.99 Mh/s    gpu/0  0.00 66C 85%  gpu/1 28.88 76C 92%  gpu/2 29.11 60C 81%  [A6+0:R0+0:F0]
  m  18:52:41|main      Speed  57.99 Mh/s    gpu/0  0.00 64C 85%  gpu/1 28.88 75C 92%  gpu/2 29.11 59C 81%  [A6+0:R0+0:F0]

**Comment by maxcom99** [comment]
i  19:14:57|stratum   Received new job #3767f5c0  seed: #3aa8f28cac16bdd858f2a726a06d1217  target: #0000000112e0be826d694b2e
  m  19:15:00|main      Speed  95.07 Mh/s    gpu/0 31.69 76C 92%  gpu/1 31.69 81C 96%  gpu/2 31.69 67C 86%  [A9+1:R0+0:F0]
  m  19:15:04|main      Speed  94.96 Mh/s    gpu/0 31.65 75C 91%  gpu/1 31.65 81C 96%  gpu/2 31.65 67C 86%  [A9+1:R0+0:F0]
  m  19:15:08|main      Speed  94.96 Mh/s    gpu/0 31.65 76C 91%  gpu/1 31.65 81C 96%  gpu/2 31.65 67C 86%  [A9+1:R0+0:F0]
  m  19:15:12|main      Speed  95.34 Mh/s    gpu/0 31.78 75C 92%  gpu/1 31.78 81C 96%  gpu/2 31.78 67C 86%  [A9+1:R0+0:F0]
  i  19:15:13|cuda-1    Solution found; Submitted to us1.ethermine.org
  i  19:15:13|cuda-1    Nonce: 0x2037542cb02712d2
CUDA error in func 'dev::eth::CUDAMiner::search' at line 487 : unspecified launch failure.
  X  19:15:13|cuda-0    Error CUDA mining: unspecified launch failure
CUDA error in func 'dev::eth::CUDAMiner::search' at line 487 : unspecified launch failure.
  X  19:15:13|cuda-2    Error CUDA mining: unspecified launch failure
CUDA error in func 'dev::eth::CUDAMiner::search' at line 487 : unspecified launch failure.
  X  19:15:13|cuda-1    Error CUDA mining: unspecified launch failure
  i  19:15:13|stratum   Accepted.
  i  19:15:14|stratum   Received new job #a29d078d  seed: #3aa8f28cac16bdd858f2a726a06d1217  target: #0000000112e0be826d694b2e
  m  19:15:16|main      Speed  87.45 Mh/s    gpu/0 29.15 72C 92%  gpu/1 29.15 79C 96%  gpu/2 29.15 62C 86%  [A10+1:R0+0:F0]
  m  19:15:20|main      Speed  87.45 Mh/s    gpu/0 29.15 71C 89%  gpu/1 29.15 78C 94%  gpu/2 29.15 62C 82%  [A10+1:R0+0:F0]
  m  19:15:24|main      Speed  87.45 Mh/s    gpu/0 29.15 70C 88%  gpu/1 29.15 78C 93%  gpu/2 29.15 61C 81%  [A10+1:R0+0:F0]
  m  19:15:28|main      Speed  87.45 Mh/s    gpu/0 29.15 70C 88%  gpu/1 29.15 77C 93%  gpu/2 29.15 60C 81%  [A10+1:R0+0:F0]
  m  19:15:32|main      Speed  87.45 Mh/s    gpu/0 29.15 69C 87%  gpu/1 29.15 76C 92%  gpu/2 29.15 59C 80%  [A10+1:R0+0:F0]
  m  19:15:36|main      Speed  87.45 Mh/s    gpu/0 29.15 68C 87%  gpu/1 29.15 75C 92%  gpu/2 29.15 58C 80%  [A10+1:R0+0:F0]
  m  19:15:40|main      Speed  87.45 Mh/s    gpu/0 29.15 68C 86%  gpu/1 29.15 75C 91%  gpu/2 29.15 57C 79%  [A10+1:R0+0:F0]
  i  19:15:42|stratum   Received new job #c3db711b  seed: #3aa8f28cac16bdd858f2a726a06d1217  target: #0000000112e0be826d694b2e
  m  19:15:44|main      Speed  87.45 Mh/s    gpu/0 29.15 67C 86%  gpu/1 29.15 74C 91%  gpu/2 29.15 57C 79%  [A10+1:R0+0:F0]
  i  19:15:46|stratum   Received new job #ab038049  seed: #3aa8f28cac16bdd858f2a726a06d1217  target: #0000000112e0be826d694b2e
  m  19:15:48|main      Speed  87.45 Mh/s    gpu/0 29.15 67C 86%  gpu/1 29.15 73C 91%  gpu/2 29.15 56C 78%  [A10+1:R0+0:F0]
  m  19:15:52|main      Speed  87.45 Mh/s    gpu/0 29.15 66C 85%  gpu/1 29.15 73C 90%  gpu/2 29.15 56C 78%  [A10+1:R0+0:F0]
  i  19:15:55|stratum   Received new job #b625210d  seed: #3aa8f28cac16bdd858f2a726a06d1217  target: #0000000112e0be826d694b2e
  m  19:15:56|main      Speed  87.45 Mh/s    gpu/0 29.15 66C 85%  gpu/1 29.15 72C 90%  gpu/2 29.15 55C 78%  [A10+1:R0+0:F0]
  i  19:15:58|stratum   Received new job #72dfeff3  seed: #3aa8f28cac16bdd858f2a726a06d1217  target: #0000000112e0be826d694b2e
  m  19:16:00|main      Speed  87.45 Mh/s    gpu/0 29.15 65C 85%  gpu/1 29.15 72C 89%  gpu/2 29.15 55C 77%  [A10+1:R0+0:F0]

**Comment by MariusVanDerWijden** [comment]
Do you have an extreme overclock applied?

**Comment by maxcom99** [comment]
I wouldn't say extreme no but scaling down +100/+720 to +0/+600 isn't helping with stability. A single card runs perfectly well at +120/+720. Something strange when multiple cards are used.

**Comment by MariusVanDerWijden** [comment]
Maybe thermals?

**Comment by maxcom99** [comment]
So there is nothing important happening at dev::eth::CUDAMiner::search and this is a driver crash and not really "an ethminer issue" ?

**Comment by evlo** [comment]
I have same problem on multiple rigs, It started after about 59:44 h:m of use on one, on the other one I don't remember, but also multiple days.

On one downgrading back to 0.12 did not help so that is weird, but it worked for more then month before upgrading.

**Comment by MariusVanDerWijden** [comment]
This line synchronizes the stream (a pipeline in which the Kernel is queued to run on the gpu), If a kernel throws an error, this call will fail. The kernel should only fail if there is a problem with the GPU (thermals/overclocking/...) so it's probably an issue with the HW/Driver

**Comment by maxcom99** [comment]
Should I close this out? Per your description this seems like an enhancement to have ethminer gracefully recover.

**Comment by MariusVanDerWijden** [comment]
We're working on this :) But it's not easy to differentiate between critical and non-critical failures

**Comment by maxcom99** [comment]
Do you want to tag this as an enhancement so it's not lost for others?

**Comment by aleqx** [comment]
Please refer to this if you're using Nvidia: https://github.com/ethereum-mining/ethminer/issues/596#issuecomment-360548462

There is almost always a driver error reported in the kernel log.
