### ISSUE TITLE
GTX 1080ti and RX 580 in same win10 box, how can I mine with both? 

### ISSUE THREAD

**Issue by s7webworks** [ethereum-mining/ethminer#663]
I have tried several different options, but everything seems to just use the 1080ti.  The RX 580 is apparently up and working in device manager.   I don't mind if they are mining diff types of coins or same, just as long as they are both working.  Any help would be greatly appreciated!

**Comment by smurfy** [comment]
either start two version of ethminer, one with ``-U``and one with ``-G`` or use ``-X``to mine with one version of ethminer.

**Comment by maxcom99** [comment]
I've found that when mixing it is best to run an instance per platform. the -X option produced sub-par results. FWIW

**Comment by s7webworks** [comment]
Thanks for the comments, I decided to return the RX 580 and purchase an additional 1080 (this one is not a ti) in place of the AMD card.  I Like the Cuda's too much. :-)     Thanks again!
