### ISSUE TITLE
Hashrate drops after running for 2-12 hours

### ISSUE THREAD

**Issue by SuCitta** [ethereum-mining/ethminer#667]
Hey there. I got this problem, that my hashrate seems to be dropping without any reason. I got a R9 390, with about 26Mh/s (stock, not OC) and a R9 280x with about 12Mh/s ... Sometimes the system runs stable about up to 12hours with 37-38Mh/s, sometimes it breaks down at 2huors already. It goes down to 11-20Mh/s (both Crads)..., though the system keeps the same temperatur (390 around 88, whilst 280x @76 ... I have not yet figured out, what causes this issue but updated this morning to 0.14.0dev1... same results after about 3hrs... After the H/s drops, restarting the miner does not solve the Problem, but only restarting Win (7, 64Bit)... Any clues?
Many many thanks !!!! Keep on the good work!!
PS: I know, i need to opimize my sys... but 390 are gone balisic in prices... they are nearls 50% more expensive compared to when i bougt my first one (back then 200€, now around 300€)

**Comment by AndreaLanfranchi** [comment]
Your temperatures are way too high imho.
88 C is eccessive and even 76 is too high.
Maybe your cards are self-protecting

**Comment by SuCitta** [comment]
Thanks for fast reply!
Hmm, they seemed very high for me too... But with monero i was able to mine for 24/7 (one Week only) with this temp... Also, i dont know how to cool them down? (without further investment, new cooler)

**Comment by AndreaLanfranchi** [comment]
Monero is a completely different algorythm (Cryptonight) which is way less aggressive on GPU's ram and needs a completely different overclocking setting (if any).
In my experience your cards run reliably with temps ranging from 58 to 65 max.

**Comment by SuCitta** [comment]
Ooops... So, you would advice me to?

**Comment by AndreaLanfranchi** [comment]
Mount on an open-air rig frame.

**Comment by dimkasta** [comment]
And put fan control at 100% if you do not already have it at that level

**Comment by SuCitta** [comment]
Sorry for late reply... 
@dimkasta is it already
@AndreaLanfranchi ... thinking about that... but, i do have, imho, a "not that bad" case with good airflow...
anyhow, i figured when downclocking my 390 it works fine now... Still as you mentioned, temperatures are way tooooo high

**Comment by DeadManWalkingTO** [comment]
Seems to be a temperature problem here!
Check [ExtremeTech’s guide to air cooling your PC](https://www.extremetech.com/computing/128313-extremetechs-guide-to-air-cooling-your-pc/2).
Maybe open air case solution.
