### ISSUE TITLE
GPL V3!!! Wish I had known

### ISSUE THREAD

**Issue by jean-m-cyr** [ethereum-mining/ethminer#668]
I object, V2 was fine. I don't contribute to GPL V3 projects. With Linus on that one

**Comment by jean-m-cyr** [comment]
There was no V3 stuff in here before! Why slap on these additional restrictions?

**Comment by lexruee** [comment]
The code base was always licensed under the GPLv3. However, there were previous attempts to change to MIT. Here is a short history overview in case someone is interested:

1. intial commit with GPLv3: 4108b53a82f2c5434b32fca48f179566b58ec99c
2. switch to MIT licence: e10bf35879318384814e0f82c29bf08665f394c7
3. switch to GPLv3: 2f524f645b536782085cc2f0be79289479f73d44
4. switch to MIT licence:  1de4b2cd8f31de6ea417c49aeadc83a0ef935baa, e9840bdfaf788f1dcb497817a081433a9cdd130e
5. switch to GPLv3: 179d6f6844a89ceb90013ca796ae2a6912bfcbf4

**Comment by jean-m-cyr** [comment]
Ah, missed that! Like I said... wish I had known...

Closing

**Comment by chfast** [comment]
Sorry for the confusion. I was asked to clarify this.

**Comment by jean-m-cyr** [comment]
Don't want to start a religious war here... Wrote the above before I had my first coffee!

Why not stick with MIT?

**Comment by chfast** [comment]
There is not option for MIT at the moment. Some original authors insisted on licensing this as GPLv3 and this was never changed.
I believe there is not way without having their permission to change it. Also, statically linking GPL libraries enforces GPL here, right?

cc @bobsummerwill.

**Comment by jean-m-cyr** [comment]
@chfast No argument. You are correct. You can't change an initial designation like that.
