### ISSUE TITLE
Titan x hashrate just 2m in windows 10

### ISSUE THREAD

**Issue by Alan-ZhangDaixi** [ethereum-mining/ethminer#669]
This is a question that ha
![35510555-7d6ca1ca-0533-11e8-9ff1-4fab269c545e](https://user-images.githubusercontent.com/10813576/35608338-ad4ad84c-0693-11e8-9c69-5a30f7441bf5.png)
s puzzled me for a long time.

**Comment by satori-q3a** [comment]
'Compute 5.2' ???

**Comment by Alan-ZhangDaixi** [comment]
@satori-q3a   it means cuda version or? could you tell me the meaning,thanks

**Comment by Alan-ZhangDaixi** [comment]
oh, i see, cuda architecture https://developer.nvidia.com/cuda-gpus

**Comment by satori-q3a** [comment]
Isn't 5.2 years old, current is 6.1, what driver are you using?

**Comment by MariusVanDerWijden** [comment]
He's using the the old Titan X which has compute capability 5.2 that can't be changed, however he can use CUDA 9.0 /9.1

**Comment by satori-q3a** [comment]
I run the current 390.77 on the 1070s,  which is compute 6.1 and cuda 9.1

**Comment by Alan-ZhangDaixi** [comment]
i will check it!!

**Comment by DeadManWalkingTO** [comment]
1. Try Update Drivers.
Download and install the latests.

2. Try use -U for CUDA devices.
That's my run command:
`ethminer.exe -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

3. Try to change P2 State and Power managment mode.
You can use [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW).
For the best mining hashrate choose from sector "5 - Common":
    - CUDA - Force P2 State (Set to "Off")
    - Power managment mode (Set to "Prefer maximum performance")

4. Try Tweak Win10.
You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) (#695).

5. Try Optimize/Overclock GPUs. 
You can use [MSI Afterburner](https://www.msi.com/page/afterburner) for GPU OverClock/Optimize. 

6. Try use a WatchDog
You can use [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) (#735).

Please feedback.
Thank you!

**Comment by wzm2256** [comment]
I also have this problem. 
It is sad to see exactly the same problem has remained unsolved for more than three years.
