### ISSUE TITLE
gracefully restart the miner

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ethereum-mining/ethminer#671]
As explained here https://github.com/ethereum-mining/ethminer/issues/662
Restart the miner whenever a cuda error occured in search

**Comment by andrewpsp** [comment]
Restart the miner after **x** amount of rejects of solutions

**Comment by DeadManWalkingTO** [comment]
Useful, very useful.

**Comment by AndreaLanfranchi** [comment]
Command line argument --exit instructs ethminer to terminate on each CUDA error.
Wrapping ethminer's launch in a script can help restart it or take action accordingly.
