### ISSUE TITLE
0.14dev1 - miner keeps resetting device and reloading DAG, restarting all the time

### ISSUE THREAD

**Issue by aleqx** [ethereum-mining/ethminer#675]
Haven't seen this before, it doesn't happen on all my cards, but I only noticed it on 0.14dev1 -- but I didn't pay close attention to 0.14 or 0.13. Was definitely not there in 0.12. Any clues?

Check this out:

```
 cu  12:39:32|cuda-0    Using device: GeForce GTX 1070  (Compute 6.1)
 cu  12:39:32|cuda-0    Set Device to current
 cu  12:39:32|cuda-0    Resetting device
 cu  12:39:33|cuda-0    Allocating light with size: 38660672
 cu  12:39:34|cuda-0    Generating mining buffers
 cu  12:39:34|cuda-0    Generating DAG for GPU # 12  with dagSize: 2474637184  gridSize: 8192  &m_streams[0]: 0x7f8aec147eb0
  ℹ  12:39:36|stratum   Received new job #f6fa13fe
  m  12:39:36|miner.12  Speed  30.53 Mh/s    gpu/0 30.53  [A1266+1:R1+0:F0] Time: 45:25
  ℹ  12:39:41|cuda-0    Initialising miner 0
 cu  12:39:41|cuda-0    Using device: GeForce GTX 1070  (Compute 6.1)
 cu  12:39:41|cuda-0    Set Device to current
 cu  12:39:41|cuda-0    Resetting device
 cu  12:39:42|cuda-0    Allocating light with size: 38535104
 cu  12:39:42|cuda-0    Generating mining buffers
 cu  12:39:42|cuda-0    Generating DAG for GPU # 12  with dagSize: 2466247808  gridSize: 8192  &m_streams[0]: 0x7f8aec148040
  m  12:39:46|miner.12  Speed  27.49 Mh/s    gpu/0 27.49  [A1266+1:R1+0:F0] Time: 45:25
  m  12:39:56|miner.12  Speed  26.23 Mh/s    gpu/0 26.23  [A1266+1:R1+0:F0] Time: 45:26
  ℹ  12:40:00|stratum   Received new job #7f74aaaf
  ℹ  12:40:00|stratum   Received new job #5e4d693e
  ℹ  12:40:00|cuda-0    Initialising miner 0
 cu  12:40:00|cuda-0    Using device: GeForce GTX 1070  (Compute 6.1)
 cu  12:40:00|cuda-0    Set Device to current
 cu  12:40:00|cuda-0    Resetting device
 cu  12:40:01|cuda-0    Allocating light with size: 38660672
 cu  12:40:02|cuda-0    Generating mining buffers
 cu  12:40:02|cuda-0    Generating DAG for GPU # 12  with dagSize: 2474637184  gridSize: 8192  &m_streams[0]: 0x7f8aec6b50d0
  ℹ  12:40:04|stratum   Received new job #7f74aaaf
  m  12:40:06|miner.12  Speed  31.06 Mh/s    gpu/0 31.06  [A1266+1:R1+0:F0] Time: 45:26
  ℹ  12:40:09|cuda-0    Initialising miner 0
 cu  12:40:09|cuda-0    Using device: GeForce GTX 1070  (Compute 6.1)
 cu  12:40:09|cuda-0    Set Device to current
 cu  12:40:09|cuda-0    Resetting device
 cu  12:40:10|cuda-0    Allocating light with size: 38535104
 cu  12:40:10|cuda-0    Generating mining buffers
 cu  12:40:10|cuda-0    Generating DAG for GPU # 12  with dagSize: 2466247808  gridSize: 8192  &m_streams[0]: 0x7f8aec1ff660
  m  12:40:16|miner.12  Speed  27.80 Mh/s    gpu/0 27.80  [A1266+1:R1+0:F0] Time: 45:26
  m  12:40:26|miner.12  Speed  27.01 Mh/s    gpu/0 27.01  [A1266+1:R1+0:F0] Time: 45:26
  ℹ  12:40:26|stratum   Received new job #cb7fdbb7
  m  12:40:36|miner.12  Speed  32.95 Mh/s    gpu/0 32.95  [A1266+1:R1+0:F0] Time: 45:26
  m  12:40:46|miner.12  Speed  33.00 Mh/s    gpu/0 33.00  [A1266+1:R1+0:F0] Time: 45:26
  ℹ  12:40:49|cuda-0    Solution submitted to eu1.ethermine.org
  ℹ  12:40:49|cuda-0    Nonce: 0x38d23e6569edbcd6
  ℹ  12:40:49|stratum   **Accepted.
  ℹ  12:40:51|stratum   Received new job #91d9cb5d
  ℹ  12:40:51|cuda-0    Initialising miner 0
 cu  12:40:52|cuda-0    Using device: GeForce GTX 1070  (Compute 6.1)
 cu  12:40:52|cuda-0    Set Device to current
 cu  12:40:52|cuda-0    Resetting device
 cu  12:40:53|cuda-0    Allocating light with size: 38660672
 cu  12:40:53|cuda-0    Generating mining buffers
 cu  12:40:53|cuda-0    Generating DAG for GPU # 12  with dagSize: 2474637184  gridSize: 8192  &m_streams[0]: 0x7f8aec6cd080
  ℹ  12:40:55|stratum   Received new job #096ae959
  m  12:40:56|miner.12  Speed  32.53 Mh/s    gpu/0 32.53  [A1267+1:R1+0:F0] Time: 45:27
  ℹ  12:41:00|cuda-0    Initialising miner 0
 cu  12:41:00|cuda-0    Using device: GeForce GTX 1070  (Compute 6.1)
 cu  12:41:00|cuda-0    Set Device to current
 cu  12:41:00|cuda-0    Resetting device
 cu  12:41:01|cuda-0    Allocating light with size: 38535104
 cu  12:41:01|cuda-0    Generating mining buffers
 cu  12:41:01|cuda-0    Generating DAG for GPU # 12  with dagSize: 2466247808  gridSize: 8192  &m_streams[0]: 0x7f8aec2ca730
  m  12:41:06|miner.12  Speed  29.28 Mh/s    gpu/0 29.28  [A1267+1:R1+0:F0] Time: 45:27
```

**Comment by AndreaLanfranchi** [comment]
Apparently this log does not come out from this ethminer.
Are you using some fork from someone else ?

We do not have logs labelled "miner.xx"

**Comment by aleqx** [comment]
Yes it is. `miner.xx` is the name of the executable, which I renamed (try it).

p.s. you may want to fix the `cuda-0` id though which is a bug. ethminer says it's always cuda-0 when running on a single device, regardless of which device id you choose.

**Comment by AndreaLanfranchi** [comment]
Sorry ... relabeled bug.

>p.s. you may want to fix the cuda-0 id though which is a bug

This is not a bug but the ordinal number of the cuda instances launched (the first). You can couple it with the device id **only** if you run **all** your cards within a single instance.

As I see you're running ethminer on the 12th card may I know If other cards are running something else ? Did the problem occurr if you run **only** ethminer ?

**Comment by aleqx** [comment]
> This is not a bug but the ordinal number of the cuda instances launched (the first). You can couple it with the device id only if you run all your cards within a single instance.

It should really say cuda-12, otherwise when running one process per card, they all say cuda-0 and you have no idea which log is from which card.

> As I see you're running ethminer on the 12th card may I know If other cards are running something else ? Did the problem occurr if you run only ethminer ?

As you can see from the date of the post, this was a very long time ago. I think I tried both a single process and multiple ethminer processes. No other gpu apps were running, that I know.

**Comment by AndreaLanfranchi** [comment]
> It should really say cuda-12, otherwise when running one process per card, they all say cuda-0 and you have no idea which log is from which card.

There is no quick workaround for this unfortunately.

> As you can see from the date of the post, this was a very long time ago

So the problem is still present or you did not make any further test ?

**Comment by aleqx** [comment]
I did test 0.14 and 0.15 briefly, mainly for speed, and after concluding that they are both slower than 0.12 even in offline benchmark mode (*) I never bothered with 0.14 and 0.15 again. I've been on and off of Eth mining since then also.

(*) Ubuntu 16.04, GTX1070, 13 cards per mobo.

**Comment by ddobreff** [comment]
I don't see how miner can fix your kworker business...you are free to test with less GPUs and report back.

**Comment by AndreaLanfranchi** [comment]
As I understand this issue is not a real issue.
Probably user is using ethOS which is known to launch one instance of ethminer for every single GPU. So, in reality, ethminer **is not** keeping resetting and re-loading DAG. This is simply multiple instances of ethminer outputting to a single log file.

**Comment by aleqx** [comment]
> Probably user is using ethOS which is known to launch one instance of ethminer for every single GPU. So, in reality, ethminer is not keeping resetting and re-loading DAG. This is simply multiple instances of ethminer outputting to a single log file.

That's wrong. First, I wasn't using ethOS. Second, the log is from a single process running on GPU 12. You can clearly see it says "Generating DAG for GPU # 12  with dagSize:" multiple times. You can also see the reported DAG size goes back and forth between 2466247808 and 2474637184, which might be linked to the problem.

I've been using 0.12 since then, which has always been problem free. I reported this as it was the first time I've seen it.

> As I understand this issue is not a real issue.

Whatever you say ...

**Comment by AndreaLanfranchi** [comment]
> DAG size goes back and forth between 2466247808 and 2474637184

Probably then is the pool sending new (or different) epoch every time: this might be the only reason for ethminer to do so. R u using nicehash ?

**Comment by aleqx** [comment]
No (I despise Nicehash) - it was on Ethermine which had been stable since November. The miner remained connected to the pool, and yet it kept updating the dag and restarting the gpu. Even if an epoch switch happened at that time, there shouldn't have been going back and forth ... I can't explain it.

I guess that if you don't get any other reports about it then it's not worth putting resources into debugging it.
