### ISSUE TITLE
Beginner on ethminer setup: payout threshold and Rigname?

### ISSUE THREAD

**Issue by arianaa30** [ethereum-mining/ethminer#676]
Hi,
Sorry I'm new to ethminer. Probably a frequent question:
I've seen to start ethminer, we have to create a bat with the following contents:

```
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O <Your_Ethereum_Address>.<RigName>
```
1- How to set the payout threshold?
2- What is that Rigname? I just have a ETH address.

**Comment by AndreaLanfranchi** [comment]
> 1- How to set the payout threshold?

You set it on ethermine.org (the pool's site) not on the software

> 2- What is that Rigname? I just have a ETH address.

Basically is the name of your computer. You set it when you have more than one miner and want to have detailed stats on the pool.

However this is not an issue of the software. Please close it.

**Comment by arianaa30** [comment]
OK. Thanks.
