### ISSUE TITLE
ethminer execution

### ISSUE THREAD

**Issue by arianaa30** [ethereum-mining/ethminer#678]
I'm new to ethminer. When I run a bat with the following contents, I see the process running, but all fields are set to 0 (`Mh/s`, etc.). Is anything missing?

```
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O <My Binance ETH address>.MyRig1
```

![eth](https://user-images.githubusercontent.com/5509837/35695010-cf3c8eae-0748-11e8-8e15-65848947e967.png)

**Comment by DeadManWalkingTO** [comment]
GPU?

**Comment by arianaa30** [comment]
Nvidia Geforce 950M with latest driver 390. No problem on execution.

**Comment by DeadManWalkingTO** [comment]
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

ethminer.exe -RH --farm-recheck 200 -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O wallet.rig


*GTX1060 & GTX1070

**Comment by arianaa30** [comment]
I changed the setting as per your parameters. It says exception occurred while executing the ethminer.exe

**Comment by satori-q3a** [comment]
I'm thinking you're using a laptop, it'll fry out in days running 24/7.

**Comment by arianaa30** [comment]
Yes laptop. Yes, but at this moment I'm wondering why it doesn't even doesn't execute.
I'm running on another good machine, with around 73MH/s. Is it a good rate?

**Comment by DeadManWalkingTO** [comment]
GTX1060 & GTX1070 
* 24/7 
* Open Case
* No OC (Stock Only)
* Power Limit 65%

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
