### ISSUE TITLE
0.14dev1 invalid shares

### ISSUE THREAD

**Issue by aleqx** [ethereum-mining/ethminer#679]
I never used to get them. Always had 0 invalid shares reported by Ethermine. Now they are always there. I have a hunch that this is related to the other bug I just reported in https://github.com/ethereum-mining/ethminer/issues/675

The stale shares also increased a little.

Here is 0.14dev1 on the left side, and switched to 0.12 on the right -- see screenshot annotation. You can also see stale shares dropping from 4-5% to 2-3% ... the stale share increase was introduced in 0.13. With 0.12 I used to have 2% (sometimes 3%). With 0.13 and 0.14dev I always get 4-5%, sometimes even 6%.

![](https://i.gyazo.com/30e4a40e18f4a8b97091fc8361910c7e.png)

![](https://i.gyazo.com/1421a34d61fa312c934a6e1b6e7984b3.png)

![](https://i.gyazo.com/e879855847848f33c3c5712a8276917c.png)

The hashrate around the switching time between 0.14dev1 and 0.12 is erratic because many cards were stopped (the all started working again only at the end of the screenshot)

**Note** in the last graph, that although the hashrate curve (top) has obviously dropped, the number of valid shares (bottom blue bars) has not really. By the looks of it, when 0.12 stabilizes (in a few hours) and the hashrate curve gets back to 6600+ then I expect the number of valid shares to actually be slightly higher than 0.13 and 0.14dev1, ar at least equal. Given I have had a **TON** more crashes under 0.13 and 0.14dev1 (you guys mentioned you tightened timings and it stresses the cards more) then I have all the reason to be running 0.12 instead of 0.13 or 0.14

I feel (haven't done much testing) that 0.13 and 0.14 have been a slight regression in my case :( ... It would be good if you could port some of the new features you are adding back into 0.12, e.g. watchdog etc.

**Comment by AndreaLanfranchi** [comment]
I am on 0.14.dev1 too and never got a single invalid share.
Also mining on ethermine.org (europe)

Could you please share cards type and OC settings ?
Also avg temp could be useful.

**Comment by aleqx** [comment]
So I was right :( ... 0.12 is indeed working in my case: more accepted shares at low stale share rate, and no more invalid shares. Also fewer crashes on my 200+ overclocked gtx1070's, which have the memory pushed to +1200..+1600, +135 on gpu, and tdp at 108w (I normally used to run 112w with no gpu overclock though).

Screenshots of the same kind as above as 0.12 is stabilizing. Note that it's now getting more than 6000 accepted shares per 10 minutes, which never happened with 0.13 or 0.14dev1.

No more invalid shares.
![](https://i.gyazo.com/b337376f70280882d812b5268b1288fd.png)

Lower stale share rate (2-3%), considering that accepted shares has increased.
![](https://i.gyazo.com/a3a81c99b023334fe1bfd2fa68640d00.png)

![](https://i.gyazo.com/c975521e475e45cfe39428ca4f6c132a.png)

**Comment by jean-m-cyr** [comment]
@aleqx There was a 14dev1 build that shortened submit time by bypassing the software re-evaluation of the GPUs solution. I am now hearing timing results as high as 15 extra ms. to do that recalculation. This allowed bad solutions from an overclocked CPU to be forwarded to the pool.

Nevertheless, since the majority seems intent on pushing their GPUs to the point of error, that feature has been made optional, turned off by default. The current master will NOT send invalids, but you will incur the re-evaluation delay for each solution found. Those who run their GPUs within safe bounds can benefit from enabling.

BTW. Version 12 ran that same re-evaluation at least twice per solution... sometimes even three times!!! Not sure how that could ever produce a better average stale rate.

**Comment by aleqx** [comment]
Well, you have evidence above that 0.12 is indeed better, at least in my case.

Also, I'm not sure why 0 or 1 re-evaluations would make any difference to the the number of accepted shares: (a) if re-evaluation is disabled, a bad share is submitted to the pool and the pool marks it as invalid; (b) if it's enabled, a bad share is discarded and not submitted to the pool. The number of accepted shares remains unaffected in both (a) and (b) ... what am I missing?

// i take the point of 2+ re-evaluations. It's the 0 vs 1 case that escapes me.

**Comment by jean-m-cyr** [comment]
It doesn't work that way. The pool returns accepted for ALL shares it receives that evaluate valid. It is only later in post processing that a share may be deemed stale. The pool never returns a result that says: We accepted your share but it was stale.

Stale share determination is based on receiving a solution for work that is no longer current (in other words, already solved). There are a number of reasons that can happen, but it stands to reason that the sooner you ship your results, the better chance it has to get there 1st.

**Comment by jean-m-cyr** [comment]
@aleqx The reason we can get away with 0 evals instead of 1 is that the GPU has already done all the necessary calculations. With a reliable GPU there is no need to redo them in host software.

**Comment by jean-m-cyr** [comment]
@aleqx BTW. It's really great that you're attempting better controlled A/B tests at higher hash rates than I can achieve. I never know how this stuff will scale.
Unfortunately, if you got the 13 results using the build that spits out invalids, it won't look like the current master which has the host eval enabled by default.

**Comment by aleqx** [comment]
First, would you mind pointing me to where in the 0.12 code it does 2+ re-evaluations? I'd like to build a custom 0.12 that does a single re-evaluation, in order to compare with the released 0.12.

I'm happy to help out with testing, seeing you being active and accommodating (many thanks for that). I'll try the current master at some point -- I'm a little confused that 0.12 seems to give better results than all versions after it though, plus it gives fewer crashes. Would you mind posting here if you make any more changes, just so I can re-pull and compile.

Hmm, a pool should know whether a submitted share is stale the moment it receives it, since it arrives at the pool after the pool sent out the next job (isn't that the definition of a stale share?), i.e. the rig submitted it too late. There are a plethora of reasons for that: rig happened to find it a little too late (just bad luck, can't improve this), slow ping or extra processing on rig's side (these can be improves) or others.

But please help me understand why would the miner want to re-evaluate before submitting. Assume you don't trust the GPU 100%, that it can give a bad share due to too much OC or noise in the power stage etc. Is re-evaluating it in software playing the same role as ECC in RAM, i.e. correcting errors and are consecutive shares part of the same job dependent on each other? In other words, would all shares computed after a bad uncorrected one become invalid too? If yes, then I see a very good case for software re-evaluation. 

You seemed surprised by folks who push their cards too much. Folks like me with access to quite a few GPUs benefit from tuning the o/c to max values, to the brink of crashes, because the rate of bad shares and crashes would still give a higher rate of accepted shares than it would give if I was to set "safe" o/c values. I have all incentive to push the cards to the point of crapping out (provided crash recovery can be automated -- hint hint watchdog hint hint), and I would very much want to use a miner that has this scenario in mind, or that allows me to configure it for such a scenario.

**Comment by jean-m-cyr** [comment]
Yeah... I get the watchdog thing! It's just hard to do the way ethminer is built!

> First, would you mind pointing me to where in the 0.12 code it does 2+ re-evaluations? I'd like to build a custom 0.12 that does a single re-evaluation, in order to compare with the released 0.12.

In 12, it is done the 2nd time, and sometimes a third in the EthStratumClient submit method. It is used there purely for accounting reasons to determine if a share is known to be stale (yes, we do knowingly generate  stales, but it's rare). If it fails the 2nd test, then it is test again against the previous work pack to make sure it's valid. That test was redundant, since invalids had already been filtered out by an earlier 1st eval call elsewhere!

Interesting experiment though! Remove the 2 eval calls from submit and send the solution as provided. Forget about counting knowingly sent stale shares... they never match pool counters anyway! Then 12H run with that vs. vanilla 12 average stale rate.

**Comment by aleqx** [comment]
> Interesting experiment though! Remove the 2 eval calls from submit and send the solution as provided. Forget about counting knowingly sent stale shares... they never match pool counters anyway! Then 12H run with that vs. vanilla 12 average stale rate.

Yeah, that's what I'd like to do. I see EthStratumClient.cpp and EthStratumClientV2.cpp ... both with same methods, but cmake file seems to be using both?!? https://github.com/ethereum-mining/ethminer/blob/v0.12.0/libstratum/CMakeLists.txt (my cmake is so rusty)

**Comment by jean-m-cyr** [comment]
Not sure why? V2 is not used. You can ignore it.

**Comment by jean-m-cyr** [comment]
@aleqx 

> But please help me understand why would the miner want to re-evaluate before submitting. Assume you don't trust the GPU 100%, that it can give a bad share due to too much OC or noise in the power stage etc. Is re-evaluating it in software playing the same role as ECC in RAM, i.e. can it correct a bad share, and are consecutive shares part of the same job dependent on each other? In other words, would all shares computed after a bad uncorrected one become invalid too? If so, then I see a very good case for software re-evaluation as it increases the rate of accepted shares.

Lots of questions there :-)

There are a couple of reasons why the software might want to run the eval function.
- the mix hash which must be submitted with the solution nonce was not passed back by the GPU. The eval call was a convenient way of recalculating it. The CUDA code has been updated to pass back the mix hash along with the nonce, so the eval call is no longer needed in CUDA for that reason.
- The eval call also recalculates the hash that is used to evaluate whether a solution passes or fails. In a sense it does also act similarly to ECC in that it can detect GPU calculation errors, but not correct them.

No, solutions found for the same job are not dependent on each other. They just happen to all fall within the ranges we've chosen for the GPUs to search.

**Comment by aleqx** [comment]
Does v0.12 have that updated CUDA code? If yes, then that eval is useless conceptually. Practically, it should result in a higher performance only if the time it takes to do the eval is indeed high enough to cause an increase in stale shares ... my test above doesn't support this hypothesis. I'm now running the modded 0.12 where I removed both eval's ... i'm already seeing invalid shares at ethermine. I'll monitor it  to see if the accepted share rate improves.

**Comment by xristianos** [comment]
34 hour up180mh/s rig in ethermine  168.6 MH/s AVERAGE EFFECTIVE. This is just insane if not something elses is happening. share accepted between 78-150ms. ridiculous?

**Comment by jean-m-cyr** [comment]
@aleqx No the updated CUDA code is not present in r12. It requires corresponding host software updates.

**Comment by jean-m-cyr** [comment]
@aleqx I'm looking forward to those results. I've gone over all of the r13 commits and can't see anything that could be used to explain the changes you're measuring? Doesn't mean they aren't there.

**Comment by jean-m-cyr** [comment]
@aleqx 

> i'm already seeing invalid shares at ethermine. I'll monitor it to see if the accepted share rate improves.

Don't bother. Something is wrong with your mod if you're seeing invalids reported back. I mean invalids, not stales.

**Comment by aleqx** [comment]
Why would it be wrong?

```C++
bool EthStratumClient::submit(Solution solution) {
        x_current.lock();
        WorkPackage tempWork(m_current);
        string temp_job = m_job;
        WorkPackage tempPreviousWork(m_previous);
        string temp_previous_job = m_previousJob;
        x_current.unlock();

        cnote << "Solution found; Submitting to" << p_active->host << "...";

        string minernonce;
        string nonceHex = toHex(solution.nonce);
        if (m_protocol != STRATUM_PROTOCOL_ETHEREUMSTRATUM)
                cnote << "  Nonce:" << "0x" + nonceHex;
        else
                minernonce = nonceHex.substr(m_extraNonceHexSize, 16 - m_extraNonceHexSize);


        //if (EthashAux::eval(tempWork.seed, tempWork.header, solution.nonce).value < tempWork.boundary)
        //{
                string json;

                switch (m_protocol) {
                        case STRATUM_PROTOCOL_STRATUM:
                                json = "{\"id\": 4, \"method\": \"mining.submit\", \"params\": [\"" + p_active->user + "\",\"" + temp_job + "\",\"0x" + nonceHex + "\",\"0x" + tempWork.header.hex() + "\",\"0x" + solution.mixHash.hex() + "\"]}\n";
                                break;
                        case STRATUM_PROTOCOL_ETHPROXY:
                                json = "{\"id\": 4, \"worker\":\"" + m_worker + "\", \"method\": \"eth_submitWork\", \"params\": [\"0x" + nonceHex + "\",\"0x" + tempWork.header.hex() + "\",\"0x" + solution.mixHash.hex() + "\"]}\n";
                                break;
                        case STRATUM_PROTOCOL_ETHEREUMSTRATUM:
                                json = "{\"id\": 4, \"method\": \"mining.submit\", \"params\": [\"" + p_active->user + "\",\"" + temp_job + "\",\"" + minernonce + "\"]}\n";
                                break;
                }

                std::ostream os(&m_requestBuffer);
                os << json;
                m_stale = false;
                async_write(m_socket, m_requestBuffer,
                        boost::bind(&EthStratumClient::handleResponse, this,
                        boost::asio::placeholders::error));
                return true;
        //}
        /*
        else if (EthashAux::eval(tempPreviousWork.seed, tempPreviousWork.header, solution.nonce).value < tempPreviousWork.boundary)
        {
                string json;

                switch (m_protocol) {
                case STRATUM_PROTOCOL_STRATUM:
                        json = "{\"id\": 4, \"method\": \"mining.submit\", \"params\": [\"" + p_active->user + "\",\"" + temp_previous_job + "\",\"0x" + nonceHex + "\",\"0x" + tempPreviousWork.header.hex() + "\",\"0x" + solution.mixHash.hex() + "\"]}\n";
                        break;
                case STRATUM_PROTOCOL_ETHPROXY:
                        json = "{\"id\": 4, \"worker\":\"" + m_worker + "\", \"method\": \"eth_submitWork\", \"params\": [\"0x" + nonceHex + "\",\"0x" + tempPreviousWork.header.hex() + "\",\"0x" + solution.mixHash.hex() + "\"]}\n";
                        break;
                case STRATUM_PROTOCOL_ETHEREUMSTRATUM:
                        json = "{\"id\": 4, \"method\": \"mining.submit\", \"params\": [\"" + p_active->user + "\",\"" + temp_previous_job + "\",\"" + minernonce + "\"]}\n";
                        break;
                }

                std::ostream os(&m_requestBuffer);
                os << json;
                m_stale = true;
                cwarn << "Submitting stale solution.";
                async_write(m_socket, m_requestBuffer,
                        boost::bind(&EthStratumClient::handleResponse, this,
                        boost::asio::placeholders::error));
                return true;
        }
        else {
                m_stale = false;
                cwarn << "FAILURE: GPU gave incorrect result!";
                p_farm->failedSolution();
        }

        return false;
        */
}
```

**Comment by aleqx** [comment]
And yes, I mean invalids. Here, below. Invalids start right when I started the first 10-20 cards with the modded 0.12. The hashrate varied wildly beforehand because I was doing lots of testing (cards going up and down).

![](https://i.gyazo.com/793f3a52506b49557fa700aa64f6c3b8.png)

**Comment by jean-m-cyr** [comment]
@aleqx It's all coming back now! I had this same issue once upon a time, and you'll now understand why this was such a mess.

The invalids you are seeing are basically stales, they are being sent out with the id of current job, which doesn't match the hash, so fail. That's the reason they put the extra eval in there. If it fails they assume it's stale and try to match it up with the previous job's id.

In R13 we've got a better way of detecting stales and pass the jobid along with the solution, so there's no need for all of these expensive shenanigans.

I can now see that to achieve what you want, you' pretty much have to do what we did in r13, and that wasn't the point of the exercise.

**Comment by aleqx** [comment]
Argh, now that finally makes sense ... do a software re-eval because at that time ethminer would know if it had received a new job, and would then "patch" the share submission to submit it for the previous job, so that the pool declares it as "stale" instead of "invalid". But why 2 evals though? My mod removes both evals.

Here's after 12 more hours. Not seeing improvement. I hate this aspect of mining - virtually impossible to do an accurate test without wasting money. Difficulty varies, shares vary, connection varies, pool has variations ... The only way would be a private blockchain, but I'm not going to pay for a lot of electricity with 0 returns.

By the time we figure it out I might have moved on from ethereum mining - I'm thinking of re-purposing the farm on other coins. I still love how low I can go with TDP with zero effects on profits on ethereum though.

Anyway, I don't see 6000+ shares per 10 minutes with this mod (but i'm 99% sure that's blockchain and pool variability) but I had almost no driver errors in the last 12h, which is darn good for this many cards pushed to the max. I think I'll give your latest commit a go later tonight ... please stop crashing my cards with your updates! :)

![](https://i.gyazo.com/72ccc0dc46fe768a096ae80dfdfed1d9.png)
![](https://gyazo.com/4965bcd4ece2ff97deed81307e25449e)
![](https://gyazo.com/f6bca7ba2ee3b9660bb7abaa4c68385a)

**Comment by jean-m-cyr** [comment]
> I'm not really seeing a visible reduction in stale shares either compared to official 0.12, damnit!

It may very well be that removing the delay is inconsequential with respect to stales as measured by the pool. So many factors involved. Job rate, network latency, pool software latency, etc...

My thoughts on that: it doesn't matter how small an advantage you get if you can get it for free!

**Comment by jean-m-cyr** [comment]
> I hate this aspect of mining - virtually impossible to do an accurate test without wasting money.

Same, for research and development... lots of miner down time

**Comment by aleqx** [comment]
> My thoughts on that: it doesn't matter how small an advantage you get if you can get it for free!

I fully agree, and sometimes it tricks me into wasting a lot of time for 0.1% improvement (I totally lose track for the 80-20 rule because of the excitement and fun, grrr)

However, in my case at least, the improvements you guys made in 0.13 and 0.14 are causing more crashes :( ... I have yet to get an accurate figure of _true_ average accepted share rate in 0.12 vs 0.13/0.14. I don't mind crashes as long as payment increases (and card lifetime is preserved).

**Comment by jean-m-cyr** [comment]
@aleqx It just added my high level take to the [release 13 notes](https://github.com/ethereum-mining/ethminer/releases). There's still some stuff that needs to be added but it's a start

**Comment by aleqx** [comment]
I was more interested in a pointer to actual code files & functions that suffered changes which add more stress on the GPU -- i'd like to better understand what's causing more driver crashes in my case and whether more tdp, sm clock or mem cloxk is needed. It just may be that 0.12 gives better profits if 0.13+ gives too many crashes (downtime) or too much power consumption for stable operation.

I don't understand something though: how come I get visibly fewer invalid shares rate with my modded 0.12 where I removed both software evals (see my [mod code above](https://github.com/ethereum-mining/ethminer/issues/679#issuecomment-362877532)) than I was getting with 0.14dev1? You can compare the first post with screenshots with the one above.

**Comment by jean-m-cyr** [comment]
@aleqx Your dev 1 test was done with a version that did not include any eval checks at all by default. I can only speculate that your GPUs are running close to the edge and actually generating the occasional invalids. With no eval call there to catch these they get forwarded to the pool. That change was not prudent and has been reverted in the dev builds. We will now only bypass the software eval if the --cuda-noeval cmd. line option is specified.

**Comment by aleqx** [comment]
I'm now compiling master as I'm itching to see if there is any difference. Just to confirm with you: if the pool does not pay stales, then there is no point in doing any eval at all, be it in cuda or in cpu, as that would just add unnecessary delays, correct?

**Comment by jean-m-cyr** [comment]
@aleqx The eval calculation is necessary in the GPU since the calculated mix hash as well as the nonce are part of the solution. It is also necessary in the host software for opencl since the opencl kernel does not return the mix hash with the nonce.

**Comment by aleqx** [comment]
If it's necessary then why is there a --cuda-noeval option? I think I'm missing something again (sorry)

**Comment by jean-m-cyr** [comment]
The eval is necessary for those Nvidia GPUs that have high error rates (overclocked.) Not enough to fail but enough to generate invalid solutions occasionally that would be sent to the pool. I've sent plenty of invalid solutions to Ethermine in testing and they were all rejected without further fuss, but there is this idea floating that you may get banned if you send too many? Haven't been at it long enough to witness this.

Personally I do +600 mem on my 1060s so they don't generate errors. I run with the --cuda-noeval options... for what it's worth.

**Comment by aleqx** [comment]
I just edited my post above when you replied ... id' be grateful if you read it again and replied to those questions (still confused, not a good day for me)

**Comment by jean-m-cyr** [comment]
0.14dev1 included more than a single commit. There was a period of about 1-2 days when we dropped eval completely for CUDA. That put overclockers at risk! Still in dev1 but now reverted to legacy (r13 legacy anyway) mode of running a single eval on every solution found by the GPU.

I've requested that each image built include a 'last commit' tag so that we can better identify dev images, which can be quite fluid. I don't mean a git tag, I mean a build process generated contant that could be included in the logs and error messages.

**Comment by aleqx** [comment]
> There was a period of about 1-2 days when we dropped eval completely for CUDA. That put overclockers at risk!
That's the bit I still fail to understand. If the pool doesn't pay stales and if this eval does not correct bad shares/errors, what's the point in doing the eval at all?

**Comment by jean-m-cyr** [comment]
Ah ok, when the eval fails, we know that the GPU generated an error, in that case we issue a GPU FAILURE message and discard the solution.

**Comment by jean-m-cyr** [comment]
If I recall, that's what the 2nd eval test in the r12 submit function did.

**Comment by aleqx** [comment]
So it makes absolutely no difference to payment, and everyone is better of not doing any eval since it eats processing power (either on gpu or on cpu). I completely fail to see the point of it ... just let the pool tell you it's invalid. Certainly you aren't blocking waiting for pool to reply, right?

**Comment by jean-m-cyr** [comment]
I'm not sure you're quite there yet... You're right about payment, but you don't want to send too many invalids to the pool and risk being banned. That would affect payment pretty drastically!

An overclocked GPU sometimes will actually generate a solution it thinks is valid, but because of a digital error is not. If we send this to the pool it will be rejected as invalid. By redoing and verifying the GPU's calculation with the eval call we catch those and discard them.

**Comment by jean-m-cyr** [comment]
And no, we don't block on sends. That's another aspect that's getting much better. Excessive, sometimes incorrect use of mutex locks, is being taken care of.

**Comment by aleqx** [comment]
But if you look at my first post here, the most I had was 10 invalids and ~6000 accepted within 10 minutes (i.e. invalid rate of a mere 0.16% ... and that was without any evals being done, correct? Certainly that can't be any risk of being banned ... if it was, ethermine wouldn't have a separate curve for invalids and would just outright ban you.

I continue to fail to see the point of those evals, at least in my case.

Even in general, after dealing with many gpus in all sort of scenarios, I have as trong feeling that you'd never get to submit so many invalids that a pool bans you, because you'd be inundated with CUDA/drivers errors that halts your miner. 

If I'm missing anything then do please correct me.

**Comment by jean-m-cyr** [comment]
:-)
There is so much urban legend around mining in general. Who really know the details of any pool's policies?

**Comment by aleqx** [comment]
Well, we're about to find out, hopefully (as I said, I'll ask ethermine and cc you)

**Comment by jean-m-cyr** [comment]
> But if you look at my first post here, the most I had was 15 invalids and ~6000 accepted within 10 minutes (i.e. invalid rate of a mere 0.25% ...

That sounds about right. It's a low probability event. For it to happen a stratum notification has to arrive in the middle of a GPU hash round where the round has found one or more solutions. On a 1060 each round runs about 60 us. and not many of them find solutions.

**Comment by jean-m-cyr** [comment]
Make that 60 us. times 32

**Comment by aleqx** [comment]
That's still less than 2ms ... but yes, becomes closer to the ping time, one order of magnitude difference, so invalids do happen. Poisson distribution here for a 10 minutes window and job arrival rate of 1 every 15 seconds (that's what I've been noticing on ethermine) should give the above 10-15 invalids on average ... if one was to actually compute it :)

**Comment by jean-m-cyr** [comment]
That 60ns. figure was based on a back of the envelope calculation using hash rate and 32 threads per grid.
Not actually timed.

**Comment by aleqx** [comment]
It's hard to time nanoseconds accurately anyway ...

p.s. it's number of events during a set window that is poisson distributed, the arrival times are exponentially distributed

**Comment by jean-m-cyr** [comment]
Meant micro not nano, think I got it right the 1st time.

You are correct on the arrival time distribution, had to check... college was a long time ago :-)

**Comment by aleqx** [comment]
Ok, i just pulled master, compiled against cuda 9.1 and just launched it using --cuda-noeval. Below is a snapshot of the last 24h on the modded 0.12. Tomorrow I'll post the same snapshot on the 0.14 master.

0.12 modded:
![](https://i.gyazo.com/0df37f967de8004372e9640ef8638dfd.png)
![](https://i.gyazo.com/b50f835916fe86f062a253665b46bf86.png)
![](https://i.gyazo.com/d38bae24a0a5b760ab73fbac569afc58.png)

**Comment by jean-m-cyr** [comment]
@aleqx Whether we like to admit it or not, those pcie 1x bus extenders over USB 3.0 cable aren't exactly PCIE3.0 spec. compliant. If you need to power cycle, the pcie bus is locked up, and there's not other way to reset.

**Comment by jean-m-cyr** [comment]
@aleqx Another thing to consider with the --cuda-noeval option is that since the GPU has to transfer the mix hash as well as the nonce, each GPU needs to push 5 times more data across the pcie interface. Perhaps it isn't the GPU compute units that are getting over stressed but rather pcie interface?

**Comment by aleqx** [comment]
> Whether we like to admit it or not, those pcie 1x bus extenders over USB 3.0 cable aren't exactly PCIE3.0 spec. compliant. If you need to power cycle, the pcie bus is locked up, and there's not other way to reset.

Who said they are PCI 3.0 compliant? :) In fact, most folks are well aware they are PCI 2.0 compliant, which is why newer mobos for mining default all pcie slots to pcie 2.0 spec.

5x more data only if --cuda-noeval is disabled, otherwise it's less. Also, even with --cuda-noeval, the transfers aren't frequent, are they, despite being 5x larger ... shouldn't affect the pcie bus.

You can query the utlization of the pcie bus using `nvidia-smi dmon -s pcet -d 10 -o DT` (see `nvidia-smi dmon --help` for all options). Here's an example output of 8 cards, out of which there are 2 bad usb risers (ntoe the `pci errs` column). This one is mining Zec.

Note the petty pcie transfer speed ...

```
# nvidia-smi dmon -s pcet -d 10 -o DT
#Date       Time        gpu   pwr  temp  mclk  pclk sbecc dbecc   pci rxpci txpci
#YYYYMMDD   HH:MM:SS    Idx     W     C   MHz   MHz  errs  errs  errs  MB/s  MB/s
 20180205   03:24:32      0   240    64  5433  1898     -     -     0    25    15
 20180205   03:24:32      1   146    42  4404  2075     -     -     0    28     7
 20180205   03:24:32      2   230    44  5490  1949     -     -    27    18    13
 20180205   03:24:32      3   231    55  5400  1923     -     -     0    21    11
 20180205   03:24:32      4   238    45  5514  1961     -     -     0    16     5
 20180205   03:24:32      5   238    49  5514  1923     -     -     0    18    13
 20180205   03:24:32      6   139    41  4404  1974     -     -     0    16     6
 20180205   03:24:32      7   225    54  5400  1873     -     -     0    19     6
```

Here's one mining ethereum using the 0.14 master with --cuda-noeval:

```
# nvidia-smi dmon -c 1 -s pcet -d 10 -o DT
#Date       Time        gpu   pwr  temp  mclk  pclk sbecc dbecc   pci rxpci txpci
#YYYYMMDD   HH:MM:SS    Idx     W     C   MHz   MHz  errs  errs  errs  MB/s  MB/s
 20180205   05:25:48      0   107    42  4608  1531     -     -     0    30    19
 20180205   05:25:48      1   109    38  4608  1518     -     -     0    23    10
 20180205   05:25:48      2   107    33  4608  1544     -     -     0    28    10
 20180205   05:25:48      3   108    47  4608  1556     -     -     0    31     8
 20180205   05:25:48      4   108    46  4608  1518     -     -     0    23     8
 20180205   05:25:48      5   107    43  4608  1531     -     -     0    23    11
 20180205   05:25:48      6   110    33  4608  1645     -     -     0    31     6
 20180205   05:25:48      7   107    46  4608  1544     -     -     0    17     6
 20180205   05:25:48      8   109    43  4551  1657     -     -     0    17     9
 20180205   05:25:48      9   107    36  4608  1556     -     -     0    18     4
 20180205   05:25:48     10   108    36  4608  1544     -     -     0    17     9
 20180205   05:25:48     11   109    35  4608  1594     -     -     0    17     6
 20180205   05:25:48     12    81    47  4608  1518     -     -     0    17     6
```

Hardly any stress on the pcie bus ...

**Comment by jean-m-cyr** [comment]
Ooh. that's nice. Didn't know nvidia-smi could do that

**Comment by aleqx** [comment]
Be careful with running `nvidia-smi` while rigs are mining and it's overclocked. nvidia-smi is essentially a gpu app, so whenever you execute it, it adds a little stress on the gpu, which tries to compensatre by boosting; if the gpu overclock is too high, you have a high chance of locking it up or causing some Xid and then you need to restart the driver or reboot.

You can see whether you are too close to that point by looking at whether you have any non-zero power or voltage violations

See `nvidia-smi stats --help` and `nvidia-smi dmon --help`

**Comment by aleqx** [comment]
Ok, so 12h later ... not seeing improvements. Stales went up very slightly. Invalids quieted down (interesting). Accepted shares which is all that matters didn't increase. In fact, I'm seeing slightly fewer on average - the don't often hit close to 6000 shares per 10 minutes as it did with 0.12. Crashes were as few as with 0.12, so that's good.

I think I might allow another 12h. It may be pool/blockchain variability ...

![](https://i.gyazo.com/33519b08636f2a2c40ea456666fa64e9.png)
![](https://i.gyazo.com/4ea4f12f7ce0bb2f0fd241983487a861.png)
![](https://i.gyazo.com/e0d9d57f67706fa8aae7a4ae6d490375.png)

**Comment by aleqx** [comment]
24h+ later and it's not really any better than 0.12 ...

![](https://i.gyazo.com/3ca2bf402512967c9af950aee1d7defb.png)
![](https://i.gyazo.com/e664af0f1c7fa6a685c97449040f5418.png)
![](https://i.gyazo.com/9aba2c43daaa376834047524d59072a2.png)

**Comment by itmanvn** [comment]
Same here with .014dev1, just back to .013 and waiting for results. :(

<img width="854" alt="screen shot 2018-02-07 at 3 36 59 pm" src="https://user-images.githubusercontent.com/103136/35906413-f9f21a78-0c1c-11e8-861b-b1b40a4f2bc5.png">

**Comment by AndreaLanfranchi** [comment]
All discussion about outdated releases.
Closing

(feel free to reopen with tests on latest)
