### ISSUE TITLE
0.14.0.dev1 sometimes 1 gpu stops alone and (it restart or crashes ethminer)

### ISSUE THREAD

**Issue by Rodriguevb** [ethereum-mining/ethminer#680]
Something 1 GPU stops to mine. It's not all the time the last (something 2th or 6th)
What am I doing wrong?

Sometimes it crashs ethminer (0.13.0)

	m  20:51:15|ethminer  Speed 409.21 Mh/s    gpu/0 31.57  gpu/1 31.19  gpu/2 31.29  gpu/3 31.57  gpu/4 31.57  gpu/5 31.57  gpu/6 31.57  gpu/7 31.57  gpu/8 31.57  gpu/9 31.48  gpu/10 31.19  gpu/11 31.48  gpu/12 31.57 [A6+0:R0+0:F0] Time: 00:03
	m  20:51:16|ethminer  Speed 408.98 Mh/s    gpu/0 31.47  gpu/1 31.19  gpu/2 31.28  gpu/3 31.57  gpu/4 31.57  gpu/5 31.47  gpu/6 31.47  gpu/7 31.57  gpu/8 31.57  gpu/9 31.57  gpu/10 31.19  gpu/11 31.47  gpu/12 31.57  [A6+0:R0+0:F0] Time: 00:03
	ℹ  20:51:16|cuda-4    Solution found; Submitted to eth-eu2.nanopool.org
	ℹ  20:51:16|cuda-4    Nonce: 0x8a936ae5118847e6
	ℹ  20:51:17|stratum    Accepted.
	m  20:51:17|ethminer  Speed 407.16 Mh/s    gpu/0 31.47  gpu/1 31.19  gpu/2 31.28  gpu/3 31.47  gpu/4 31.57  gpu/5 31.57  gpu/6 31.47  gpu/7 31.57  gpu/8 31.57  gpu/9 31.57  gpu/10 31.28  gpu/11 31.57  gpu/12 29.57  [A7+0:R0+0:F0] Time: 00:03
	m  20:51:18|ethminer  Speed 404.24 Mh/s    gpu/0 31.57  gpu/1 31.19  gpu/2 31.19  gpu/3 31.48  gpu/4 31.57  gpu/5 31.57  gpu/6 31.57  gpu/7 31.48  gpu/8 31.48  gpu/9 31.57  gpu/10 31.29  gpu/11 31.57  gpu/12 26.71  [A7+0:R0+0:F0] Time: 00:03
	m  20:51:19|ethminer  Speed 401.57 Mh/s    gpu/0 31.57  gpu/1 31.29  gpu/2 31.19  gpu/3 31.57  gpu/4 31.48  gpu/5 31.57  gpu/6 31.57  gpu/7 31.57  gpu/8 31.57  gpu/9 31.57  gpu/10 31.19  gpu/11 31.57  gpu/12 23.85  [A7+0:R0+0:F0] Time: 00:03
	m  20:51:20|ethminer  Speed 398.52 Mh/s    gpu/0 31.57  gpu/1 31.29  gpu/2 31.19  gpu/3 31.57  gpu/4 31.48  gpu/5 31.57  gpu/6 31.57  gpu/7 31.57  gpu/8 31.57  gpu/9 31.48  gpu/10 31.19  gpu/11 31.57  gpu/12 20.89  [A7+0:R0+0:F0] Time: 00:03
	m  20:51:21|ethminer  Speed 395.72 Mh/s    gpu/0 31.57  gpu/1 31.28  gpu/2 31.19  gpu/3 31.57  gpu/4 31.57  gpu/5 31.57  gpu/6 31.57  gpu/7 31.57  gpu/8 31.57  gpu/9 31.47  gpu/10 31.19  gpu/11 31.57  gpu/12 18.03  [A7+0:R0+0:F0] Time: 00:04
	m  20:51:22|ethminer  Speed 392.86 Mh/s    gpu/0 31.57  gpu/1 31.19  gpu/2 31.28  gpu/3 31.57  gpu/4 31.57  gpu/5 31.47  gpu/6 31.57  gpu/7 31.57  gpu/8 31.57  gpu/9 31.57  gpu/10 31.19  gpu/11 31.57  gpu/12 15.16  [A7+0:R0+0:F0] Time: 00:04
	ℹ  20:51:23|cuda-1    Solution found; Submitted to eth-eu2.nanopool.org
	ℹ  20:51:23|cuda-1    Nonce: 0x4e929338b89bd26c
	m  20:51:23|ethminer  Speed 391.09 Mh/s    gpu/0 31.53  gpu/1 31.17  gpu/2 31.26  gpu/3 31.53  gpu/4 31.53  gpu/5 31.53  gpu/6 31.53  gpu/7 31.53  gpu/8 31.53  gpu/9 31.53  gpu/10 31.26  gpu/11 31.62  gpu/12 13.54  [A7+0:R0+0:F0] Time: 00:04
	ℹ  20:51:23|stratum    Accepted.
	m  20:51:24|ethminer  Speed 390.27 Mh/s    gpu/0 31.65  gpu/1 31.30  gpu/2 31.39  gpu/3 31.65  gpu/4 31.65  gpu/5 31.65  gpu/6 31.65  gpu/7 31.65  gpu/8 31.65  gpu/9 31.65  gpu/10 31.39  gpu/11 31.65  gpu/12 11.37  [A8+0:R0+0:F0] Time: 00:04
	m  20:51:25|ethminer  Speed 387.41 Mh/s    gpu/0 31.65  gpu/1 31.30  gpu/2 31.30  gpu/3 31.65  gpu/4 31.65  gpu/5 31.65  gpu/6 31.65  gpu/7 31.56  gpu/8 31.56  gpu/9 31.65  gpu/10 31.39  gpu/11 31.65  gpu/12  8.74  [A8+0:R0+0:F0] Time: 00:04
	m  20:51:26|ethminer  Speed 384.85 Mh/s    gpu/0 31.65  gpu/1 31.30  gpu/2 31.30  gpu/3 31.65  gpu/4 31.65  gpu/5 31.65  gpu/6 31.65  gpu/7 31.65  gpu/8 31.65  gpu/9 31.65  gpu/10 31.30  gpu/11 31.65  gpu/12  6.12  [A8+0:R0+0:F0] Time: 00:04
	m  20:51:27|ethminer  Speed 382.22 Mh/s    gpu/0 31.65  gpu/1 31.39  gpu/2 31.30  gpu/3 31.65  gpu/4 31.65  gpu/5 31.65  gpu/6 31.65  gpu/7 31.65  gpu/8 31.65  gpu/9 31.65  gpu/10 31.30  gpu/11 31.65  gpu/12  3.41  [A8+0:R0+0:F0] Time: 00:04
	m  20:51:28|ethminer  Speed 379.51 Mh/s    gpu/0 31.65  gpu/1 31.39  gpu/2 31.30  gpu/3 31.65  gpu/4 31.65  gpu/5 31.65  gpu/6 31.65  gpu/7 31.65  gpu/8 31.65  gpu/9 31.56  gpu/10 31.30  gpu/11 31.65  gpu/12  0.79  [A8+0:R0+0:F0] Time: 00:04
	m  20:51:29|ethminer  Speed 378.58 Mh/s    gpu/0 31.65  gpu/1 31.30  gpu/2 31.30  gpu/3 31.65  gpu/4 31.65  gpu/5 31.56  gpu/6 31.65  gpu/7 31.65  gpu/8 31.65  gpu/9 31.65  gpu/10 31.30  gpu/11 31.56  gpu/12  0.00  [A8+0:R0+0:F0] Time: 00:04
	m  20:51:30|ethminer  Speed 378.64 Mh/s    gpu/0 31.56  gpu/1 31.30  gpu/2 31.39  gpu/3 31.65  gpu/4 31.65  gpu/5 31.65  gpu/6 31.56  gpu/7 31.65  gpu/8 31.65  gpu/9 31.65  gpu/10 31.30  gpu/11 31.65  gpu/12  0.00

**Comment by SnowLeopard71** [comment]
Does you kernel log any messages from the Nvidia driver?  (something like this: "NVRM: Xid (PCI:0000:01:00): 62, 1d5e(356c) 00000000 00000000")
Does restarting ethminer solve the problem or does the machine need to be rebooted?

**Comment by Rodriguevb** [comment]
How i get the kernel log from Nvidia driver ? :s 

Only restarting ethminer is enough. Sometimes the gpu re-works alone, sometimes it crashes all ethminer with 

	CUDA error in func 'search' at line 487 : an illegal memory access was encountered.
	  ✘  00:47:53|cuda-7    Error CUDA mining: an illegal memory access was encountered
	CUDA error in func 'search' at line 487 : an illegal memory access was encountered.
	  ✘  00:47:53|cuda-11   Error CUDA mining: an illegal memory access was encountered
	CUDA error in func 'search' at line 487 : an illegal memory access was encountered.
	  ✘  00:47:53|cuda-0    Error CUDA mining: an illegal memory access was encountered
	CUDA error in func 'search' at line 487 : an illegal memory access was encountered.
	  ✘  00:47:53|cuda-4    Error CUDA mining: an illegal memory access was encountered
	CUDA error in func 'search' at line 487 : an illegal memory access was encountered.
	  ✘  00:47:53|cuda-5    Error CUDA mining: an illegal memory access was encountered
	CUDA error in func 'search' at line 487 : an illegal memory access was encountered.
	  ✘  00:47:53|cuda-6    Error CUDA mining: an illegal memory access was encountered
	CUDA error in func 'search' at line 487 : an illegal memory access was encountered.
	  ✘  00:47:53|cuda-12   Error CUDA mining: an illegal memory access was encountered
	CUDA error in func 'search' at line 487 : an illegal memory access was encountered.
	  ✘  00:47:53|cuda-8    Error CUDA mining: an illegal memory access was encountered
	CUDA error in func 'search' at line 487 : an illegal memory access was encountered.
	  ✘  00:47:53|cuda-9    Error CUDA mining: an illegal memory access was encountered
	CUDA error in func 'search' at line 487 : an illegal memory access was encountered.
	  ✘  00:47:53|cuda-10   Error CUDA mining: an illegal memory access was encountered
	CUDA error in func 'search' at line 487 : an illegal memory access was encountered.
	  ✘  00:47:53|cuda-1    Error CUDA mining: an illegal memory access was encountered
	CUDA error in func 'search' at line 487 : an illegal memory access was encountered.
	  ✘  00:47:53|cuda-3    Error CUDA mining: an illegal memory access was encountered
	CUDA error in func 'search' at line 487 : an illegal memory access was encountered.
	  ✘  00:47:53|cuda-2    Error CUDA mining: an illegal memory access was encountered

**Comment by Rodriguevb** [comment]
It happens in 0.13.0 version and 0.14.0.dev1 too

**Comment by wetblanket0** [comment]
@Rodriguevb Since you closed this issue, I assume you figured out what was causing it? I'm seeing the same issue with one card in a 6x GTX 1070 headless rig. It was previously mining equihash without issue (higher power draw, more heat, etc than eth mining).

**Comment by Rodriguevb** [comment]
@wetblanket0 I didn't find the cause. It seems that this has happened since the arrival of the real threading.. I closed because I'm not the only one to open an issue
