### ISSUE TITLE
ethminer not starting. Only 1x GTX 1060 on HP Z400 machine

### ISSUE THREAD

**Issue by 9A6DQB** [ethereum-mining/ethminer#685]
Hello all.
I have problem starting miner form USB stick.
I followed this instructions:
ethereum_nvidia_miner

I prepared new stick, and manage to boot from it. I finished setup, putting all data that I need.
Now after reboot, and starting Ubuntu I do not have any output on my monitor. I can not start mining, nether do anything to start to work.
I tried to put fake monitor, but still not working.
Any advice?
Thanks

**Comment by DeadManWalkingTO** [comment]
Hi.
You boot from usb stick.
Before start miner Ubuntu have any output to monitor? or miner causes the problem?

**Comment by 9A6DQB** [comment]
There is no problem on start.
I install it on USB, and after first boot, and setup procedure, never again rebooted. I do not know if it is working or not.

 

 

 

S poštovanjem, 

 

Antun Paulin

direktor

 <http://www.tim-studio.net/> 

WEBMASTER j.d.o.o.

K.S.Tomaševića 1, 10410 Velika Gorica

OIB: 44170762314
IBAN: HR5924020061100760398

SWIFT: ESBCHR22  Erste Bank

 

Kontakt telefon: +385 98 339 178

Email:  <mailto:info@tim-studio.net> info@tim-studio.net 

 <http://www.tim-studio.net/> www.tim-studio.net

**Comment by AndreaLanfranchi** [comment]
No feedback.
Closed
