### ISSUE TITLE
Improve crash diagnostics

### ISSUE THREAD

**Issue by jean-m-cyr** [ethereum-mining/ethminer#686]
Create a build generated global string constant indicating build's latest commit. To be included in dev build diagnostic error messages, ie.

const char *lastComit = "xxxxxxxxxxxxxxxxxxxxxx";

Would help a lot correlating issue report error logs with actual dev build versions.

**Comment by jean-m-cyr** [comment]
Except that you would spell commit correctly :-)

**Comment by jean-m-cyr** [comment]
@chfast Based on my experiments, this will require a unique solution per CI service.

**Comment by chfast** [comment]
Not really. CMake can provide this. cpp-ethereum and solidity have this. We had it here too, maybe I removed it. Look for "buildinfo".

**Comment by jean-m-cyr** [comment]
Implemented.
