### ISSUE TITLE
ethminer's hashrate is lower than claremore

### ISSUE THREAD

**Issue by felixdfdf** [ethereum-mining/ethminer#689]
on the same hardwar machine. claremore is about 228, but ethminer is 208, why?

**Comment by MariusVanDerWijden** [comment]
Because it's different software...

**Comment by felixdfdf** [comment]
so even with devfee, it looks like claremore's profit is better than ethminer's?

**Comment by Rodriguevb** [comment]
Claymore hashrate is fake, reported hashrate higher than calculed hashrate. And  inverse with ethminer for me.

Furthermore, claymore has fee.
