### ISSUE TITLE
Solution for 100% CPU usage (Win10 - CUDA - OpenCL)

### ISSUE THREAD

**Issue by DeadManWalkingTO** [ethereum-mining/ethminer#695]
OS: Windows 10
CPU: INTEL PENTIUM DUAL CORE G4400 3.30GHZ
GPU: 5 x GTX1070 & 1 x GTX1060

CPU Usage: 100%

Ethminer execution:

> ethminer.exe -RH --farm-recheck 200 -U -S eu1.ethermine.org:4444 -O wallet.rig

I found some tweaks for windows 10 and achieve more than 50% less CPU usage.

New CPU Usage: 45% 

[Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW)
Just let me know about your results.

Have a nice mining!

**Comment by satori-q3a** [comment]
With 7 cards and an i3 6100, I'm getting 1% on Win 10.

**Comment by DeadManWalkingTO** [comment]
In some cases (unfortunately many), the processors in Windows 10 show 100% usage. 
From what I understand the problem grows according to the number of GPUs. 
Windows 10 overloads processors that have few flames when GPUs are more than the threads.
[#339](https://github.com/ethereum-mining/ethminer/issues/399) [#64](https://github.com/ethereum-mining/ethminer/issues/64) [#74](https://github.com/ethereum-mining/ethminer/issues/74) etc.

I had this problem with INTEL PENTIUM DUAL CORE G4400 3.30GHZ (2 cores - 2 threads - 8 CUDA GPUs). At i7 I had no problem.
After a lot of searching, I found a solution to my problem that I think will help those who face something similar. 
With the same system there is no problem doing mining Zcash (ZEC).

I have uploaded it to GitHub [Windows-10-Mining-Tweaks](https://github.com/DeadManWalkingTO/Windows-10-Mining-Tweaks) so that everyone can see the changes one by one and the more experts can find a better solution.
Developers can also detect the process that causes the processor to overload and make the appropriate modifications.
Please those who use it to let me know about the results and any additions or corrections.
Thanks!

**Comment by DeadManWalkingTO** [comment]
After many tests on different systems, I'm happy to let you know that the increased workload of the processor is due solely to the operating system (Windows 10).

**Comment by satori-q3a** [comment]
Is your CPU usage on etherminer only, or is it the whole system + ethminer + task monitor + display handler?

**Comment by DeadManWalkingTO** [comment]
Only ethminer (plus TeamViewer).

**Comment by DeadManWalkingTO** [comment]
Possible Fix  #339 #64 #74 #315

**Comment by AndreaLanfranchi** [comment]
Just for curiosity ... are you power-limiting your GPUs ?
I've seen on linux that power-limiting affects CPU usage : it's like CPU is working hard to prevent GPU from sucking power freely.

**Comment by DeadManWalkingTO** [comment]
Power Limit 65%-75% (MSI AB)

**Comment by DeadManWalkingTO** [comment]
I see that many still have a problem with the "High CPU Usage".

Solution:

-Windows 10 OS
If your cards are NVidia using -U you may see improvement in CPU usage.
If your GPU are ATI then you should consider the parameters better.

In all cases, you will see the big difference by tweaking Windows for mining.
It's easy using Windows10MiningTweaksDmW or manual if you prefer.

-Linux OS
If your GPU are NVidia using -U you will see great improvement in CPU usage.
If your GPU are ATI then you should consider the parameters better.

It is possible to correct the following issues:
#339 #64 #74 #315
