### ISSUE TITLE
ethminer output the infor too quickly

### ISSUE THREAD

**Issue by felixdfdf** [ethereum-mining/ethminer#696]
the infor moves too quickly in CMD, I can not check the hashrate, cpu temp and fan speec or the share status, Is there some way to slowdown the infor outputing?

**Comment by moonter45** [comment]
change --farm-recheck to 1500 :)

**Comment by XhmikosR** [comment]
I wonder, doesn't `farm-recheck` reflect the time the miner polls the pool for changes? If so, doesn't it affect stale shares too?

**Comment by AndreaLanfranchi** [comment]
@XhmikosR 
in stratum mode farm-recheck does absolutely nothing aside displaying the hashrate: in stratum mode it's the pool which pushes new jobs on the socket, not the miner pulling it.

**Comment by XhmikosR** [comment]
Thanks for the info, @AndreaLanfranchi. I was under the impression it affected the polling interval too.
