### ISSUE TITLE
what is the good options for RX470 with 8G ram

### ISSUE THREAD

**Issue by felixdfdf** [ethereum-mining/ethminer#697]
how to adjust the --cl-local-work and --cl-global-work parameters? I have 8 RX470 with 8G RAM. I increase the two options casually so that the total hashrate could be >370, waht a amazing.  Even though the card temp is <70 and Fan speed is about 40%, I changed these paramters to default value in case the cards been damaged.
 Could anybody tell me how to adjust these two paramtes for my RX470 with 8G RAM, thanks very much.

**Comment by jramos** [comment]
I use this for 4GB RX 480:

```
--cl-local-work 256 --cl-global-work 18432
```

Keep local-work at `256` and experiment with global work sizes in +/-2048 increments. Don't look only at hashrate. Let it run for a while and check your pool to confirm your speed and that you see no increase in stales.

**Comment by ddobreff** [comment]
--cl-local-work 256 --cl-global-work 16384 --cl-parallel-hash 2 --cl-kernel 1
Global worksize is calculated like this ( local-worksize * threads-per-hash * compute units )

**Comment by jramos** [comment]
I experience slower performance with anything but `--cl-parallel-hash 8`. How would reducing the number of threads per hash increase hashrate?

**Comment by czechspekk** [comment]
--cl-parallel-hash 2 seems to work best for my setup too

**Comment by jramos** [comment]
Nevermind. I just modded my BIOS, and `--cl-local-work 256 --cl-global-work 18432 --cl-parallel-hash 2 --cl-kernel 1` is the sweet spot for my RX 480s.

**Comment by simbadMarino** [comment]
Hello there, I'm having some problems with my hashrate in a RX 580, it's supposed to be ~24Mh/s without modding the BIOS but currently getting only 15.8Mh/s :(. I'm using the binary file in Ubuntu with following options:
./ethminer --farm-recheck 200 -G -S us2.ethermine.org:4444 -FS us1.ethermine.org:4444 -1 <ADDRESS>
Any help is much appreciated. I've googled a lot without any clue....
Thank you!

**Comment by jramos** [comment]
Which amdgpu driver version are you using?

**Comment by simbadMarino** [comment]
Hi jramos, its amdgpu-pro     17.40-492261 amd64 thanks for helping!

**Comment by jramos** [comment]
Either upgrade to 17.50, or enable large page support in 17.40.

17.50: https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-for-Linux-Release-Notes.aspx

17.40:
```
Ubuntu 16.04 LTS
Edit /etc/default/grub as root and modify GRUB_CMDLINE_LINUX_DEFAULT in order to add "amdgpu.vm_fragment_size=9" (without the quotes). The line may look something like this after the change:

GRUB_CMDLINE_LINUX_DEFAULT="quiet splash amdgpu.vm_fragment_size=9"

Update grub and reboot as root:

update-grub; reboot
```

**Comment by simbadMarino** [comment]
Thanks a lot @jramos ! Let me try and will come back with results.

**Comment by jramos** [comment]
IIRC, large page support gave me a ~15% increase. I would definitely consider doing a BIOS mod, as well... that gave me another ~20%. I just used the one click timing feature in Polaris BIOS Editor. Still need to experiment with clock rate adjustments.

**Comment by simbadMarino** [comment]
Hello again @jramos no luck with adding the GRUB_CMDLINE_LINUX_DEFAULT="quiet splash amdgpu.vm_fragment_size=9" line... :/

Do you think that it should be enough? Or should I try upgrading the driver to 17.50?

I will try also the BIOS mod after getting the normal stock Hash rate that should be 23Mh/s as per reviews

**Comment by jramos** [comment]
Did you run `update-grub`?

**Comment by simbadMarino** [comment]
Yes, then I rebooted but stil not having the correct Mh/s... Any sugestions?
--
Enviado desde la aplicación myMail para Android viernes, 16 febrero 2018, 11:57a.m. -06:00 de Justin Ramos  notifications@github.com :
