### ISSUE TITLE
Gigabyte GTX 1080 G1 gives low 2.668 Mh/s Rate

### ISSUE THREAD

**Issue by cryptoalexx** [ethereum-mining/ethminer#699]
I'm getting very low hash rates with two Gigabyte GTX 1080 G1 cards, around 2.7 MH/s. Please advise if there a setting to deal with the issue. I've removed all overclocking on the cards.

GPU0 t=50C fan=21%, GPU1 t=50C fan=10%
 DCR: 02/04/18-17:53:20 - New job from dcr.suprnova.cc:3252
ETH: 02/04/18-17:53:24 - New job from us1.ethpool.org:3333
ETH - Total Speed: 5.410 Mh/s, Total Shares: 1, Rejected: 0, Time: 00:09
ETH: GPU0 2.669 Mh/s, GPU1 2.742 Mh/s
 DCR - Total Speed: 54.103 Mh/s, Total Shares: 0, Rejected: 0
 DCR: GPU0 26.687 Mh/s, GPU1 27.416 Mh/s

**Comment by cryptoalexx** [comment]
Additional info regarding the setup:
Virtual memory: Initial size (MB): 20000 Maximum size (MB): 40000 (I've also tried 16000 and 16000 before) 
Nvidia drivers: 390.77 (latest) Number of GPU's: 2 Motherboard: BIOSTAR TB250-BTC+ Power supply: EVGA 1000 GQ - I've got a separate cable from the PSU for both the riser and card's 8 PIN connection.
I've updated BIOS for both the GTX 1080 from the Gigabite website
System memory: 4 GB
GPUs: 2 GTX 1080 Gigabyte G1

ETH - Total Speed: 5.413 Mh/s, Total Shares: 0, Rejected: 0, Time: 00:02 ETH: GPU0 2.671 Mh/s, GPU1 2.742 Mh/s DCR - Total Speed: 54.131 Mh/s, Total Shares: 0, Rejected: 0 DCR: GPU0 26.712 Mh/s, GPU1 27.419 Mh/s DCR: 02/04/18-19:02:41 - New job from decred.eu.nicehash.com:3354 DCR: 02/04/18-19:02:42 - New job from decred.eu.nicehash.com:3354

**Comment by tonyaik** [comment]
Look like you're running claymores. Wrong miner.
