### ISSUE TITLE
Question - export before ethminer

### ISSUE THREAD

**Issue by Rodriguevb** [ethereum-mining/ethminer#705]
Hello,

Is it still necessary to type these `export` commands before  ?

	export GPU_FORCE_64BIT_PTR=0
	export GPU_MAX_HEAP_SIZE=100
	export GPU_USE_SYNC_OBJECTS=1
	export GPU_MAX_ALLOC_PERCENT=100
	export GPU_SINGLE_ALLOC_PERCENT=100

	sudo ethminer ...

**Comment by MariusVanDerWijden** [comment]
No, I tried to contact ethermine, they said, they'll change it

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
