### ISSUE TITLE
Lots of "Unknown error" upon launch all of a sudden with 0.14 master

### ISSUE THREAD

**Issue by aleqx** [ethereum-mining/ethminer#706]
I can't explain it. I run one ethminer process per card (easier to recover from crashes) and suddenly about 8 of my cards started to get

```
  m  15:32:40|miner.4   ethminer version 0.14.0.dev1
  m  15:32:40|miner.4   Build: Linux/g++ / Release
Error: unknown error
```

Upon launching, after more than 36h of working uninterrupted and without a hitch. I have nothing else to go by ... any clues?

**Comment by aleqx** [comment]
I think I know what happened. Remember [my post here](https://github.com/ethereum-mining/ethminer/issues/596#issuecomment-360548462) about driver errors that should be properly caught and dealth with by ethminer inside a watchdog?

Today it was for the first time that I got a Xid 32 (which normally you can recover from by a simple miner relaunch) with the channel ID `00000003` (usually its `b` or `9`) ... this toppled most other cards in the rig. Ethminer on 10 gpus crashed with 

`Fatal GPU error: CUDA error in func set_header at line 147 all CUDA-capable devices are busy or unavailable`

and then it refused to start again with `unknown error`.

Watchdog, watchdog, watchdog, watchdog, watchdog, watchdog, watchdog, watchdog, watchdog, watchdog, watchdog, watchdog, watchdog, watchdog, watchdog, watchdog, watchdog, watchdog, watchdog, watchdog, watchdog :)

**Comment by skaldesh** [comment]
had the same error today!

**Comment by DeadManWalkingTO** [comment]
After #757 (added --exit parameter to exit whenever an error occurred) you can use a watchdog.

Here is my [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) Windows7/8/10 [32/64] & Linux (Any Dist/Any Ver/Any Arch) (#735).

Check and feedback please.
Thank you!
