### ISSUE TITLE
0.14dev1 ethminer hangs with read_until:End of File

### ISSUE THREAD

**Issue by Bat-Attack** [ethereum-mining/ethminer#708]
Hi all,
I got hangs of ethminer twice when using Options -SP 1 -RH -SC 2
It seems to happen at 24h Provider DSL-Reconnection
this ended in following output for hours:

read_until: End of file
  ℹ  16:36:04|stratum   Reconnecting in 3 seconds...
  ℹ  16:36:07|stratum   Connecting to stratum server eu1.ethermine.org:4444
  ℹ  16:36:07|stratum   Connected!
read_until: End of file
  ℹ  16:36:08|stratum   Reconnecting in 3 seconds...
  ℹ  16:36:11|stratum   Connecting to stratum server eu2.ethermine.org:14444
  ℹ  16:36:11|stratum   Connected!

after restarting ethminer everything is ok

startet with:
ethminer /root/bin/ethminer -SP 1 -RH -SC 2 -U -S eu1.ethermine.org:4444 -FS eu2.ethermine.org:14444 -O 0xxxxxxxxx --farm-recheck 1000
Using Ubuntu 17.10

**Comment by DeadManWalkingTO** [comment]
1. No need -SP.
2. eu2.ethermine.org not exist.

Try my script 
`ethminer.exe -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`
and feedback please
Thank you!

**Comment by Bat-Attack** [comment]
Thankyou smurfy. eu2 ethermine.org does exist.
Sorry for the delay - I switched to dev3 today and will test without options first and give feedback in a few days.
