### ISSUE TITLE
GTX 1060 3GB, ETC Mining Out of Memory Error 

### ISSUE THREAD

**Issue by lachymx** [ethereum-mining/ethminer#711]
Last Night all my ETC rigs suffered Out of Memory Errors at the same time, 

All Gtx 1060's 3GB 

Switched to ETH mining and they work fine? 

cu  15:12:23|main      Using grid size 8192 , block size 128
  i  15:12:23|main      Connecting to stratum server etc-au1.nanopool.org:19999
  i  15:12:23|stratum   Connected to stratum server etc-au1.nanopool.org : 19999
  i  15:12:23|stratum   Starting farm
  i  15:12:23|cuda-0    No work. Pause for 3 s.
  i  15:12:25|stratum   Received new job #0xe92727  seed: #40910b6ac043b9a4c8a3a5100b00efcc  target: #000000006df37f675ef6eadf
  i  15:12:26|cuda-0    Initialising miner...
 i  15:12:27|stratum   Received new job #0xc26cbd  seed: #40910b6ac043b9a4c8a3a5100b00efcc  target: #000000006df37f675ef6eadf
  m  15:12:28|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cu  15:12:28|cuda-0    Using device: GeForce GTX 1060 3GB  (Compute 6.1)
  i  15:12:35|stratum   Received new job #0xd4ac3f  seed: #40910b6ac043b9a4c8a3a5100b00efcc  target: #000000006df37f675ef6eadf
 cu  15:12:35|cuda-0    Set Device to current
  i  15:12:35|stratum   Received new job #0xa29b47  seed: #40910b6ac043b9a4c8a3a5100b00efcc  target: #000000006df37f675ef6eadf
 cu  15:12:35|cuda-0    Resetting device
 cu  15:12:35|cuda-0    Allocating light with size: 40107968
CUDA error in func 'dev::eth::CUDAMiner::cuda_init' at line 366 : out of memory.

**Comment by ddobreff** [comment]
ETC is few epochs ahead

**Comment by MariusVanDerWijden** [comment]
https://investoon.com/tools/dag_size 
ETC is at 2.39 GB for the DAG, but you need to factor in the size of the other structures that need to be allocated on the GPU's, 3GB cards are going to be obsolete in some epochs even for ETH

**Comment by lachymx** [comment]
Thanks for the information , That's a shame thought we'd get a bit longer till the 3GB cards stopped working for ETC & ETH

**Comment by RUminingTwo** [comment]
Mine has stopped on a 1060 3 gig Win 10 Pro, but the same GPU (1060 3 gig IS still working) on a windows 10 server. Its seems to have stopped on my Win 10 system around the same time as the latest Windows Updates for Win 10 were applied...and I see a patch ( or install for Skype) that I didn't have installed to begin with. Console miner also stopped working for ETC on this same Win 10 system. But fine on others with 3 gig. Windows Server

**Comment by lachymx** [comment]
Yeah I'm on windows 10 Pro as well, Looks like quite a bit of Video Ram is used by the OS, Might try it on Linux and see if I can get a but longer, By my rough calculations there's about 50 days until this issue starts to effect ETH mining aswell

**Comment by RUminingTwo** [comment]
Odd thing is that I have no problem with the same card installed on a Windows server 2012, still mining ETC.

After the windows updates being installed it started happening, and I am thinking the updates for Win 10 pushes GPU memory usage higher, not allowing ETC to now be mined by 3 Gig GPU.

 

May end up taking the card out and installing it as a second card in the ETC working server.

**Comment by kalltkaffe** [comment]
Just for the record. I just installed Ubuntu Linux on a rig with only 3Gb cards just to see if this will be an option when ETH reach the DAG-size that ETC has now. Mining ETC on 3Gb-cards using Linux and ethminer works fine.

**Comment by RUminingTwo** [comment]
Excellent !

For me, I realize he issue is Windows 10 Overhead of the graphics usage with the operating system, not leaving enough available GPU memory to run ETC mining now, ( worked for a while up until the latest windows updates) compared to my Windows Server 2012, which does not have the graphics usage overhead of the operating system and is still running fine mining ETC with a 3 Gig GPU.
