### ISSUE TITLE
Why my mh/s is dropping until I restart ethminer ? 

### ISSUE THREAD

**Issue by MehdyAmazigh** [ethereum-mining/ethminer#712]
Let's say I'm mining since 1 hour.
My MH/s drop to 25
When I close and start again ethminer
My MH/s get back to 28
What's going on ?

**Comment by Tokolosh** [comment]
i had one card that was acting similar, just that after about 40min it went down to 0 while the other cards were fine. In my case it was a thermal issue - after adding some more fans it went away and is now stable

**Comment by antonismandilas** [comment]
I had the same issue and it was also a thermal issue. After I increased the speed of the fan of the card, it works more smoothly,

**Comment by DeadManWalkingTO** [comment]
I believe it's thermal issue as described above. (@antonismandilas)

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.

**Comment by MehdyAmazigh** [comment]
Just to confirm, it was a thermal issue
