### ISSUE TITLE
Console verbosity (reduce hash rate output)

### ISSUE THREAD

**Issue by minerbird** [ethereum-mining/ethminer#717]
Currently, the hash rate is displayed every two seconds in the console which is overkill to me.
Is there any way to limit that to every 60 seconds or disable it (and press a key on the keyboard to display the current rate)? I mined xmr using xmr-stak and its console output is more intuitive and easier to read (see https://kameratrollet.se/wp-content/uploads/2017/11/xmr-stak-cpu-cmd.png).

**Comment by AndreaLanfranchi** [comment]
Ethminer does not provide (at the moment) any interactive key to display stats.

If you're mining using stratum protocol you can easily set

`--farm-recheck 10000`

to have the display record printed out every 10 seconds (or more if you want).

**Comment by minerbird** [comment]
Appreciate the help. That worked. Thanks @AndreaLanfranchi .
