### ISSUE TITLE
Need help about using cuda configuration parameters for gtx 1070

### ISSUE THREAD

**Issue by alptolga** [ethereum-mining/ethminer#719]
I need help for configuring cuda configuration parameters of gtx 1070
What is the best parameters? I need advice.
CUDA configuration:
    --cuda-block-size Set the CUDA block work size. Default is 128
    --cuda-grid-size Set the CUDA grid size. Default is 8192
    --cuda-streams Set the number of CUDA streams. Default is 2

**Comment by alptolga** [comment]
Benchmark just show the cuda grid size. There is still no info about stream and block size.

**Comment by DeadManWalkingTO** [comment]
The best are the defaults.
I try almost all combinations.

My script:
ethminer.exe -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O wallet.rig

**Comment by alptolga** [comment]
@DeadManWalkingTO 
I use msi afterburner to overclock my cards and use nvidia-smi for setting the power consumptions of the card. I do these process after miner starts to mine so I don't live any problem when generating and loading dag to the cards. After overclocking the cards there is no way to set the cards to p0 state. Anyway with overclocking procedure you use the card in its uppest limit. P0 is useful just for when you use it in stock frequency.

**Comment by DeadManWalkingTO** [comment]
What overclocking settings you use? (-50/+500 & 65% TDP -- Temp=52C)

**Comment by alptolga** [comment]
+800 memory and 10 watt over the minimum tdp of the cards.

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.

**Comment by alptolga** [comment]
@DeadManWalkingTO 
This is not an issue as written on the topic title. This is mostly collecting user experiences and advices for mining with cuda gpus. Even so if you feel your self uncomfortable, as long as it remains open. It is easy to close the topic.

**Comment by DeadManWalkingTO** [comment]
Sorry about false cleanup!
I use MSI Afterburner (-50/+500 & 65% TDP -- Temp=52C) not NVidia-smi.
`ethminer.exe -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O wallet.rig`
I believe the default values of miner are the best for GTX1070.
