### ISSUE TITLE
Hardware monitor values switched

### ISSUE THREAD

**Issue by merdecas** [ethereum-mining/ethminer#724]
Hi, the miner shows the hardware monitor (temp and fan speed) values switched.
There are 2 GPU in this example and the hwmon values of the gpu0 are being displayed  in gpu1.

![hardware monitor switched](https://user-images.githubusercontent.com/36327949/36061227-51e79f44-0e4f-11e8-8ce9-209e914f7f29.png)

Thanks

**Comment by smurfy** [comment]
What gpus are you using?

**Comment by merdecas** [comment]
2x RX480

**Comment by AndreaLanfranchi** [comment]
Try setting this env var before launching ethminer

`export CUDA_DEVICE_ORDER=PCI_BUS_ID`

**Comment by smurfy** [comment]
@AndreaLanfranchi well, with AMD cards this will fix nothing :(.. i currently work on a PR trying to fix some common issues with HWMON, hopefully this fixes that too.

**Comment by smurfy** [comment]
please test latest master

**Comment by Davesmacer** [comment]
Issue is still there... It is specific to AMD cards, NVIDIA cards seem to have good order. I need to test this with more than 2 AMD cards to see if the ADL order is flipped, or maybe it is switched. In both cases the fix should be easy
