### ISSUE TITLE
Colors in Windows should be optional

### ISSUE THREAD

**Issue by Alex-ASF** [ethereum-mining/ethminer#728]
I think ANSI colors in Windows should be optional. 
Because it works in Windows 10 only and does not work in earlier versions.

**Comment by Olegatorius** [comment]
How you can see colors in win 10? For me its all blackNwhite. Is there any way to enable them?

**Comment by smurfy** [comment]
@Olegatorius Lastest master does support colors on Win10

**Comment by jean-m-cyr** [comment]
@Alex-ASF PR #729 add support for optional B/W.

**Comment by Alex-ASF** [comment]
In your solution you got control by NO_COLOR only for Win10. For all other versions colors will simply never be, even if there is ANSI support. And it is so, checked.

**Comment by Alex-ASF** [comment]
I would suggest not to complicate it, just make a command line key. Moreover, by default there is no color, but we can turn it on.

**Comment by jean-m-cyr** [comment]
@Alex-ASF I don't see why we should cater to the minority?

**Comment by Alex-ASF** [comment]
Should not. Simply your decision is suitable only for Win10. In earlier versions of Win it does not work (which I reported). If their support is not needed, OK.

**Comment by Alex-ASF** [comment]
Should not. Simply your solution is suitable only for Win10. In earlier versions of Win it does not work (which I reported). If their support is not needed, OK.

**Comment by jean-m-cyr** [comment]
It should work under all versions of Windows and Linux. If you do not want color just set the NO_COLOR environment variable to something, prior to invoking ethminer.
