### ISSUE TITLE
CUDA builds for macOS

### ISSUE THREAD

**Issue by ssbb** [ethereum-mining/ethminer#73]
Looks like macOS builds have no CUDA support? When I am trying to use it with `-U` flag I get error:

`Selected CUDA mining without having compiled with -DETHASHCUDA=1 or -DBUNDLE=cudaminer
`

**Comment by zackoch** [comment]
when you built did you use those flags?

you should have something like cmake -DETHASHCUDA=YES

**Comment by ssbb** [comment]
I mean for releases. Or I should build it manually then?

Just it's a CUDA miner and have macOS release. Thought it should support CUDA on macOS out of the box then :)

**Comment by zackoch** [comment]
Unfortunately I am new to this software - I just built it manually but I also have a processor which is not "standard." (power 8)

AFAIK the U flag should dictate CUDA, so unless there are different pre-compiled packages for openCL and CUDA my next step would just be to build it. Should be easy on your mainstream os and architecture.

**Comment by jimmykl** [comment]
I think the automatic builds use the default which is -DETHASHCUDA=OFF No idea why that is the case but not much you can do apart from compiling it yourself. This is what I did on Macos Sierra:

Install CUDA drivers and toolkit https://developer.nvidia.com/cuda-downloads

If you don't have xcode installed:
Download & install Xcode CLT (Command Line Tools) *8.2* (this is an older version and required otherwise the compile will fail)
Run ```sudo xcode-select --switch /Library/Developer/CommandLineTools
git clone https://github.com/ethereum-mining/ethminer.git
cd ethminer
mkdir build; cd build
cmake -DETHASHCUDA=ON -DETHASHCL=OFF ..
cmake --build .
```

Then you can find the binary in /build/ethminer

**Comment by chfast** [comment]
The only reason the builds do not have CUDA on macOS is I didn't have time to include CUDA SDK installation step in Travi CI config for macOS. Should be similar complexity as Linux.

**Comment by WWWFWWW** [comment]
Hello, I followed the instructions above, and I am getting these errors:

```
sh: cicc: command not found
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.Release.cmake:282 (message):
  Error generating file
  /Volumes/[volume]/ethminer/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o


make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
make[1]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by stevemulligan** [comment]
I can build ok but when I run I get this with latest CUDA 9 driver:

```
./ethminer --list-devices
  ✘  11:53:35|          CUDA error: No CUDA driver found
```

And with CUDA 8 driver:

```
./ethminer --list-devices
  ✘  11:57:00|          CUDA error: Insufficient CUDA driver: 8000
```
