### ISSUE TITLE
CUDA 9.0 unsupported gcc versions later than 6

### ISSUE THREAD

**Issue by Rodriguevb** [ethereum-mining/ethminer#731]
Following these steps : 

- Use virtualbox and install Ubuntu Server
- git clone this repo
- `sudo ./scripts/install_cmake.sh`
- `sudo ./scripts/install-cuda-ubuntu1604.sh` (<<< install gcc-7)
- `/home/username/.local/bin/cmake -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-9.0 .. -DETHASHCUDA=ON -DETHASHCL=OFF`
- `/home/username/.local/bin/cmake --build .`

And gets `CMake Error unsupported GNU version! gcc versions later than 6 are not supported!`
But the script `install-cuda-ubuntu1604.sh` install `gcc-7`.. What i need to do ?

**Comment by jean-m-cyr** [comment]
@Rodriguevb I don't think the miner will work very well, if at all, in a virtualized environment.

**Comment by Rodriguevb** [comment]
@jean-m-cyr No doesn't work, but i just want to compile ethminer with specific requirements like gcc version 6 max and then I transfer to my miner :)

**Comment by piotr-dobrogost** [comment]
For what it's worth I managed to compile ethminer with CUDA 9.1 ang gcc 7.2 on Fedora 27 making change described at https://davidwpearson.wordpress.com/2017/12/21/installing-nvidias-cuda-9-1-on-fedora-27/

**Comment by MariusVanDerWijden** [comment]
You can use -DCMAKE_C_COMPILER=/usr/bin/gcc-6 to specify the path of the compiler

**Comment by alkmim** [comment]
You can also use this Dockerfile: https://github.com/alkmim/ethminer-docker

**Comment by StoneCypher** [comment]
it doesn't seem like this should be closed

i just set up a new ubuntu box and this appears to be a roadblock

**Comment by MariusVanDerWijden** [comment]
You need to download gcc-6 and use -DCMAKE_C_COMPILER=/usr/bin/gcc-6 to specify the path of the compiler. CUDA doesn't work with later gcc versions

**Comment by RustyRaptor** [comment]
guys just use 
```
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 10
```
and 
```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 10
```
I hope this helped.

**Comment by travis-cramer** [comment]
@RustyRaptor  Great solution. Worked for me.

**Comment by askerlee** [comment]
@RustyRaptor thanks it works. Do I need to revert it to gcc7 after installation?

**Comment by RustyRaptor** [comment]
@askerlee  you don't have to revert it unless you are going to compile a project that requires GCC7.

**Comment by Diyago** [comment]
`update-alternatives: error: alternative path /usr/bin/gcc-6 doesn't exist
` 
how can I fix that

**Comment by MariusVanDerWijden** [comment]
You have to install gcc-6 
e.g. sudo apt-get install gcc-6

**Comment by Diyago** [comment]
`E: Unable to locate package gcc-6 `
 (

**Comment by MariusVanDerWijden** [comment]
For Ubuntu xenial (16.04)
`
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-6 g++-6
`

**Comment by RustyRaptor** [comment]
Yeah. I think everyone should just upgrade to 18.04 at this point. My coworker was having trouble with it too. It's a 2-year-old release now lol.

**Comment by pranavnijampurkar33** [comment]
All those who are still struggling even if applying above solutions. I followed above and still failed to remove issue. I tried script located in following ling . Hope it helps you....!!!!
https://gist.github.com/zuyu/7d5682a5c75282c596449758d21db5ed

**Comment by Zumbalamambo** [comment]
Give this man @RustyRaptor a Noble Prize!!!!!!!!!!!!!

**Comment by lan786** [comment]
For those who are still facing this issue. 
I was unable to solve my problem using above mentioned methods. 
My system specification is

- Python 3.7

- CUDA 9, CuDNN 7.5 using RTX-2060 

- Ubuntu 18 having GCC/G++ 7.5


I solved my issue by using following method,

`sudo apt remove gcc gcc-7 g++ g++-7 `
`sudo apt install gcc-6 g++-6 `

and then using above mentioned commands 

`sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 10`
`sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 10`
