### ISSUE TITLE
Hashrate low

### ISSUE THREAD

**Issue by Matt8110** [ethereum-mining/ethminer#733]
I have a GTX 760 4GB (yes I know it draws A LOT of power). I decided to try mining since I don't really know a lot about it or cryptocurrency in general. 

So I have NiceHash Legacy, my GPU is running DaggerHashimoto, it benchmarks around 12MH/s, but rarely actually performs that well. It seems every now and then when I restart it, it'll hit 12-14 MH/s for a bit and then drop to around 4. 

I've tried changing drivers, changing versions of NiceHash, I've changed settings in the nvidia control panel, and I've dual booted windows 7 and done the same. It isn't thermal throttling and overclocking makes absolutely no difference.

**Comment by EoD** [comment]
@Matt8110 are you using CUDA (``-U``)? If yes, you can try playing with the ``--cuda-parallel-hash`` option and see if it makes a difference.


If you are using OpenCL (``-G``), try to play with the ``--cl-kernel`` option:
```
 OpenCL configuration:
    --cl-kernel <n>  Use a different OpenCL kernel (default: use stable kernel)
        0: stable kernel
        1: experimental kernel
```
If you are using the experimental OpenCL kernel, you can additionally play with the ``--cl-parallel-hash`` option.

**Comment by ddobreff** [comment]
That's not the issue. Older gpus don't have 2MB fragment size, so basically he sees 12MH on some eth fork and when nicehash switches dag to eth/etc/etz his hashrate drops because of bigger DAG size. It can't be fixed on that old HW.

**Comment by EoD** [comment]
Is it possible to detect this (via some OpenCL option maybe)? We could issue a warning on ethminer if that kind of hardware is used.

Otherwise we could document it somewhere (and be lucky if someone reads it).

**Comment by DeadManWalkingTO** [comment]
1. Try Update Drivers.
Download and install the latests.

2. Try use -U for CUDA devices.
That's my run command:
`ethminer.exe -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

3. Try to change P2 State and Power managment mode.
You can use [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW).
For the best mining hashrate choose from sector "5 - Common":
    - CUDA - Force P2 State (Set to "Off")
    - Power managment mode (Set to "Prefer maximum performance")

4. Try Tweak Win10.
You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) (#695).

5. Try Optimize/Overclock GPUs. 
You can use [MSI Afterburner](https://www.msi.com/page/afterburner) for GPU OverClock/Optimize. 

6. Try use a WatchDog
You can use [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) (#735).

Please feedback.
Thank you!

**Comment by EoD** [comment]
@DeadManWalkingTO did you follow the thread? This is an issue with ethminer and probably should be fixed by issuing some kind of warning.
