### ISSUE TITLE
Simple Script WatchDog

### ISSUE THREAD

**Issue by DeadManWalkingTO** [ethereum-mining/ethminer#735]
I would like to inform you that I have uploaded a simple  script (Windows/Linux) WatchDog for ETHminer.

[ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW)

At the moment (v1.0.0) script just restart the miner. In the future, it will consider more parameters and tools (nvidia-smi etc) for better operation.

Αny help/idea for improvement is welcome.

**Comment by piotr-dobrogost** [comment]
Have you seen https://github.com/derubm/Ethminer_Watchdog and https://github.com/xstead/ethereum-miner-monitor ?

**Comment by DeadManWalkingTO** [comment]
I was looking for something (apparently not so good), but I had not seen the two of them.
It's an opportunity to see their own approaches.
Thank you very much.

I hope we have the optimal solution with some combination of approaches.
Better Mining = Better Profit!

**Comment by DeadManWalkingTO** [comment]
Με την ευκαιρία να ευχαριστήσω όλους τους συνεισφέροντες για αυτό το πολύ καλό έργο.

**Comment by DeadManWalkingTO** [comment]
Thank you [MariusVanDerWijden](https://github.com/MariusVanDerWijden) for that amazing parameter #757 (added --exit parameter to exit whenever an error occurred).

Now with such a simple script like [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) we would have better results.

(#97) (#274) (#327)

**Comment by DeadManWalkingTO** [comment]
New bug free version (v1.8.0) 100% working both Win & Unix.
1. Run ethminer.
2. Restart ethminer up to 10 times.
3. Reboot the system.
