### ISSUE TITLE
Non overlapping nonce ranges over multiple rigs

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ethereum-mining/ethminer#736]
As per PR #618 we have now single instance of ethminer wich assign every attached gpu a non-overlapping range of nonces to search for.

Could it be possible to arrange non overlapping ranges over multiple rigs ?
(CLI argument ? JSON mining.notify message tampering ? ... )

My goal is to achieve a real hash clustering over multiple machines.

**Comment by jean-m-cyr** [comment]
Read and understand [this](http://www.mathpages.com/home/kmath580/kmath580.htm) then apply the formula at the end, using the 64bit nonce range as unity range and your fastest GPU hash rate as the segment size.

I think you will find that the probability of overlap approaches 0.

**Comment by jean-m-cyr** [comment]
Looking at it a different way. In one second a 50MH/S GPU will search less than a trillionth of the nonce space. Even with 10,000 randomly distributed GPUs, the chance of overlap is near nil.
