### ISSUE TITLE
Two errors during 'cmake .. -DETHASHCUDA=ON -DETHASHCL=OFF' when building from source

### ISSUE THREAD

**Issue by chucknb28409** [ethereum-mining/ethminer#738]
Hi,

I am receiving an error "CMakeFiles/cmTC_99d24.dir/build.make:97 recipe for target 'cmTC_99d24' failed" and the error " Makefile:126: recipe for target 'cmTC_99d24/fast' failed" during the cmake process.

Environment:
Ubuntu 16.04 with Utilities and OpenSSH server installed. 
Latest Ubuntu updates installed
Installed Nvidia drivers 3.90.25 from Nvidia
Fixed nouveau issue as described by Nvidia Developers Docs (ethernet crashing during boot), but still have to run 'dhclient' to get ethernet started after boot completes.
Gigabyte motherboard H110-D3A with latest BIOS
Gigabyte  Geforce GTX 1060 G1 Gaming 3GB (QTY 4 - Part Num GVN1060G1 GAMING-3GD)
4GB DDR4 2400MHZ RAM
M.2 128GB SATA SSD
Intel Celeron Processor G3930 - LGA1151 7th Gen Processor
Two Power Supplies - EVGA 1000 G2 and EVGA 1300 G2

Thanks

**Comment by DeadManWalkingTO** [comment]
Ηave you installed the Hunder correctly?

**Comment by DeadManWalkingTO** [comment]
By the way, Windows build has no problem. (21 warning(s))

**Comment by chucknb28409** [comment]
Not sure what you mean by Hunder... I know that that appears to be a package installed during the install process after the make and build is complete. I am building from source to make sure I have access to the latest CUDA version for optimizing the GPU. I think Windows vs Linux is a personal preference, but for me I can lock a Linux box down pretty tight (such as two-factor authentication, full firewall and access restrictions by IP or MAC address)

**Comment by chucknb28409** [comment]
I think I found the issue, sort of... I had not installed the nvidia-cuda-toolkit (because it installs CUDA 7.5.18), if I install this and run the cmake again it work but now the Build fails with Unsupported gpu architecture 'compute 60' which I though was due to the older CUDA version. I am going to try and see if the executable will work next...

**Comment by chucknb28409** [comment]
Sorry for being such a dolt. I should know better, I read the F...ing manual and figured it out. Its all working now...

**Comment by jean-m-cyr** [comment]
Great!
