### ISSUE TITLE
Limiting GPU Usage

### ISSUE THREAD

**Issue by oguzhankrcby** [ethereum-mining/ethminer#739]
Hi, i build the source newly and i am looking for limiting gpu usage but i couldn't reach any solution for that, i really need that gpu limitation, i am open for any ideas...

**Comment by AndreaLanfranchi** [comment]
Duplicate of #576

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.

**Comment by smurfy** [comment]
As mentioned before, this is a duplicate and there is no plan adding support for this at this time.
Patches welcome.

**Comment by NukeManDan** [comment]
Cross posting: #2222 may help those looking to solve this. Thanks @TroyNeubauer 🙇🏼 !
