### ISSUE TITLE
Ethminer successfully installed on Ubuntu 16.04, benchmarks, but cannot connect: Failed getting work

### ISSUE THREAD

**Issue by dalhoomist** [ethereum-mining/ethminer#741]
Hi Guys,

I am trying to mine using ethminer 0.14.0-dev for linux (Same issue with previous version). I am running Ubuntu 16.04. Installed AMDGPU driver 17.50 with no real issues. Also have OpenCl running using command:

`$ sudo apt-get install libclc-amdgcn mesa-opencl-icd.`

I run ethminer to bench mark and it works fine. But when I try to mine, it cannot connect. Here is a snapshot of the error
![screenshot from 2018-02-13 23-50-06](https://user-images.githubusercontent.com/34778387/36188221-af2f6134-1118-11e8-85cd-05329323e6e1.png)
![screenshot from 2018-02-13 23-49-07](https://user-images.githubusercontent.com/34778387/36188224-b39d9218-1118-11e8-845d-fb89b5e5e38b.png)

I tried using 3 different pool addresses, and turning off the firewall on my network. Still not working.

Any help is much appreciated

**Comment by Davesmacer** [comment]
Try with:  
ethminer --farm-recheck 200 -G -S us1.ethermine.org:4444 -FS eu1.ethermine.org:4444 -O <address>.<rig>

**Comment by smurfy** [comment]
As @Davesmacer mentioned use ``-S`` instead of ``-F`` otherwise your commandline looks good

**Comment by dalhoomist** [comment]
Oh thanks! this works! I really appreciate your help @smurfy @Davesmacer !!
Do you recommend any articles on how to optimize GPU hashing performance? Mine is an rx 580 8GB micron memory with modded BIOS. 
Thanks again
