### ISSUE TITLE
Error: Insufficient CUDA driver: 9000

### ISSUE THREAD

**Issue by Davesmacer** [ethereum-mining/ethminer#742]
Hello,

I just managed to correctly build the miner from the latest source to test it with 18 CUDA cards, but I got the error when trying to test it. Can't figure out what I did wrong. I have CUDA 9.1.85. My build commands were:

cmake .. -G "Visual Studio 15 2017 Win64" -Tv140 -DETHASHCUDA=ON (I had problems compiling CUDA 9.1 with VS 2017 compilers, used 2015 compilers to solve them)
cmake --build . --config Release

The error I got while running is:
![image](https://user-images.githubusercontent.com/7698291/36189750-e1d1fb6e-1119-11e8-9304-936d2550ff22.png)

Screenshot from Windows Programs:
![image](https://user-images.githubusercontent.com/7698291/36189781-07ebc87a-111a-11e8-975d-2fc9eee13539.png)

cmake compiled with some warnings, but I kind of ignore them... Let me know if you need to see those warnings or anything... 

The latest release works fine on this computer, the issue is with my build so I know I have proper drivers for CUDA.

Thank you in advance for any help!

**Comment by tuyendd25** [comment]
Hi Davesmacer

The same issue with 1060GTX so how can i resolve the problem. Thank you

m 20:02:46 ethminer ethminer 0.17.0.dev0-4+commit.8ccecb7d
 m 20:02:46 ethminer Build: linux/release
 X 20:02:46 ethminer CUDA error: Insufficient CUDA driver: 9000

**Comment by Davesmacer** [comment]
Oh buddy,I can't quite remember, but I believe it was something related to CUDA compatibility. Try using CUDA 9.0
