### ISSUE TITLE
stops working without any error on ethereumpool.co

### ISSUE THREAD

**Issue by okias** [ethereum-mining/ethminer#743]
Lastest git, I getting issue. Previously, it was fine with git old about 14 days and 2 cards.
After running 4 cards with latest git (sic, two variables) it sometimes after while stops mining. Only problem is, I don't see anything useful in logs (it seems happends before there errors).

Graph stops around 03:00 on mining site

  04:04:55|getwork |  Failed getting work!
  04:04:55|getwork |  Disconnected from http://ethereumpool.co/?miner=XXX
  04:04:55|getwork |  Shutting down miners...
  04:04:55|getwork |  Retrying in 3 ...
  04:04:56|getwork |  Retrying in 2 ...
  04:04:56|main    |  Exception thrown in Worker thread: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
  04:04:57|getwork |  Retrying in 1 ...
úno 14 04:04:58 worker-2 systemd-resolved[246]: Using degraded feature set (UDP) for DNS server 10.0.0.1.
  04:04:58|getwork |  Connected to http://ethereumpool.co/?miner=XXX
  04:04:58|getwork |  Spinning up miners...
  04:04:58|cuda-0  |  No work. Pause for 3 s.
  04:04:58|cuda-1  |  No work. Pause for 3 s.
  04:04:58|cuda-2  |  No work. Pause for 3 s.
  04:04:58|cuda-3  |  No work. Pause for 3 s.
  04:04:58|getwork |  Received new job #190de3d5 from http://ethereumpool.co/?miner=XXX
  04:05:01|getwork |  Received new job #54ebb80f from http://ethereumpool.co/?miner=XXX
  04:05:01|cuda-0  |  Initialising miner 0
  04:05:01|cuda-1  |  Initialising miner 1
  04:05:01|cuda-2  |  Initialising miner 2
  04:05:01|cuda-3  |  Initialising miner 3
  04:05:05|getwork |  Received new job #7e81cb58 from http://ethereumpool.co/?miner=XXX

**Comment by smurfy** [comment]
Please try latest git master (some minutes ago). The code you are using, shutdowns the miners on disconnect and starts them up again on reconnect.

Problem is shutdown of miners is currently bugged. 

A PR got merged today, which does not shutdown miners on disconnect. So hopefully this should fix your problem, not mining after a disconnect/"failed getting work!".

**Comment by DeadManWalkingTO** [comment]
Try Ethminer 's last version (master) and feedback please.
Thank you!
