### ISSUE TITLE
Feature request : exclude submission of known stale shares

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ethereum-mining/ethminer#746]
I think a command line argument to exclude **known** stale shares from submission could be appreciated.
It would help determining how many shares _"become stale"_ on the trip to pool.

**Comment by chfast** [comment]
If you only what to know how many become stales on the way, it should be enough to have separate counter for stales on the ethminer side (I think we have it, maybe does not work correctly).

**Comment by jean-m-cyr** [comment]
We display known stale count in the log

[A250+**_1_**:R0+0:F0]

**Comment by jean-m-cyr** [comment]
We've had this conversation before! Nobody can say with certainty whether or not pools pay for stales... I suspect they don't, but I have no direct knowledge of pool algorithms.

There is no cost in sending them, and they are very rare, so I think a command line options would be superfluous.

**Comment by smurfy** [comment]
Just looked at the code and i found the following:

* Stale count only works on CLMiner. Cuda returns the state of m_abort which seems wrong to me
* Cuda support no eval, CL does not. IF no eval, it should always mark the solution as not stale.

Reference:
https://github.com/ethereum-mining/ethminer/blob/master/libethash-cuda/CUDAMiner.cpp#L535
https://github.com/ethereum-mining/ethminer/blob/master/libethash-cl/CLMiner.cpp#L366

**Comment by chfast** [comment]
So you should be able to compare stale count on the ethminer side with the stale count on the pool side. 

Some pools are paying for stales (at least they claim to) because they can be converted to uncle blocks.

**Comment by jean-m-cyr** [comment]
@smurfy It think you meant to say, 'only works with CUDA'. That may be the case but code was recently added to opencl to detect stale shares, but it has yet to detect a known stale on my single AMD card.

The noeval option no longer disable stale counting since we no longer rely on eval to detect stales.

**Comment by smurfy** [comment]
@jean-m-cyr ok, maybe i did read the code wrong. (see linked lines)

**Comment by jean-m-cyr** [comment]
@smurfy The m_abort flag is a misnomer. It is really an indicator that the farm has sent new work.

Both in CUDA and CL, a stale share is generated every time a stratum notify arrives in the middle of a GPU hashing round where the round has found one or more solutions. This doesn't happen very often, but when it does we know that the pool has moved on and that our solution is stale.

The m_abort flag in CUDA is reset with the completion of each GPU hashing round, so it will only be true at the end of a round if new work has arrived. A similar test was recently added to opencl, but I'm not sure it works.

**Comment by AndreaLanfranchi** [comment]
Sorry if I have created some confusion.
Title of this issue is related to **known** stale shares where _known_ is referred to the logic of how ethminer (not the pool) detects them.
So i guess jean explanation fits:

> Both in CUDA and CL, a stale share is generated every time a stratum notify arrives in the middle of a GPU hashing round where the round has found one or more solutions. This doesn't happen very often, but when it does we know that the pool has moved on and that our solution is stale.

Due to this I thought that a command line argument could prevent the stale solution from being submitted thus freeing the transport stream for those ms needed to get a response.
https://github.com/ethereum-mining/ethminer/blob/c85463fadd6f26f0c7284156a78dba75d818b7af/libpoolprotocols/PoolManager.cpp#L59

**Comment by jean-m-cyr** [comment]
@AndreaLanfranchi Not sure why you'd want to do this? Ethermine pays 65% of a valid share for a valid stale.

**Comment by AndreaLanfranchi** [comment]
@jean-m-cyr 
I was not sure about other pool's payments over stale shares. 
Nevertheless I think this could be an "option" usable during tuning phase to help understand where it's up to the miner to produce stale shares or they get stale on the way to the pool.

BTW ... happy to hear you

**Comment by AndreaLanfranchi** [comment]
Not an issue.
