### ISSUE TITLE
JSON-RPC problem.

### ISSUE THREAD

**Issue by 3everah** [ethereum-mining/ethminer#747]
Hi there, I'm very new to programming and I was a bit bored and decided to try out Ethermine with my 
RX-480. So I followed the tutorials and spent a couple days waiting for my computer to essentially count to 5,000,000 and am now quite disappointed to be greeted with this after using '-G' :
*C:\Users\hector\Downloads\ethminer-0.11.0-windows\ethminer 0.11.0 windows>ethminer -G
Found suitable OpenCL device [Ellesmere] with 8589934592 bytes of GPU memory
  m  13:48:57|main  Getting work package...
  X  13:48:58|main  Failed to submit hashrate.
  X  13:48:58|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8545

JSON-RPC problem. Probably couldn't connect. Retrying in 1...*

Furthermore I have tried to fix this after researching online; however, after keying in various lines, I kept on getting a window that popped up and said ethminer.exe has stopped working. After trying to fix this with other commands, they failed to carry themselves through because of the JSON-RPC problem. So I'm sort of trapped and in need of some spoon fed help if anyone would be so kind. 
Thank you,
Hector Everard.

**Comment by smurfy** [comment]
Hi,

please use the latest version: https://github.com/ethereum-mining/ethminer/releases/latest

Also i you probably want use stratum and a pool. For example ethermine.org

Then create a batch file with the content:

```
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O <Your_Ethereum_Address>.<RigName>
```
