### ISSUE TITLE
HWMON doesn't report the card its operating on, only card 0.

### ISSUE THREAD

**Issue by dnfm** [ethereum-mining/ethminer#748]
If you run one instance of ethminer per GPU, the -HWMON parameter appears to return the fan speed/temp of card 0 all of the time, irrespective of which GPU it's mining on:

> $ nvidia-smi

> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 390.25                 Driver Version: 390.25                    |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce GTX 106...  Off  | 00000000:08:00.0  On |                  N/A |
> | 52%   84C    P2    86W / 120W |   2843MiB /  3019MiB |    100%      Default |
> +-------------------------------+----------------------+----------------------+
> |   1  GeForce GTX 106...  Off  | 00000000:09:00.0 Off |                  N/A |
> | 50%   79C    P2    92W / 120W |   2518MiB /  3019MiB |    100%      Default |
> +-------------------------------+----------------------+----------------------+

But both instances of ethminer with -hwmon are saying 52%/84C.

**Comment by smurfy** [comment]
I guess you specify ``--cuda-devices`` ?

**Comment by dnfm** [comment]
Yes.

**Comment by smurfy** [comment]
please test latest master

**Comment by zorohakobyan** [comment]
Hi! I think I have the same problem 
Here is bat file and  result in miner

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe -RH --cuda-devices --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0xeAB43401197Ace40975ADAcF9FF46b933Ed0940f.ELF2


C:\Users\elf3\Downloads\ethminer-0.12.0-Windows\bin>setx GPU_FORCE_64BIT_PTR 0

SUCCESS: Specified value was saved.

C:\Users\elf3\Downloads\ethminer-0.12.0-Windows\bin>setx GPU_MAX_HEAP_SIZE 100

SUCCESS: Specified value was saved.

C:\Users\elf3\Downloads\ethminer-0.12.0-Windows\bin>setx GPU_USE_SYNC_OBJECTS 1

SUCCESS: Specified value was saved.

C:\Users\elf3\Downloads\ethminer-0.12.0-Windows\bin>setx GPU_MAX_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\Users\elf3\Downloads\ethminer-0.12.0-Windows\bin>setx GPU_SINGLE_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\Users\elf3\Downloads\ethminer-0.12.0-Windows\bin>ethminer.exe -RH --cuda-devices --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0xeAB43401197Ace40975ADAcF9FF46b933Ed0940f.ELF2
  i  12:11:48|main      Found suitable OpenCL device [ Intel(R) HD Graphics 630 ] with 3369867674  bytes of GPU memory
  i  12:11:48|main      Connecting to stratum server eu1.ethermine.org:4444
  i  12:11:48|stratum   Connected to stratum server eu1.ethermine.org : 4444
  i  12:11:48|stratum   Starting farm
 cl  12:11:48|cl-0      No work. Pause for 3 s.
  i  12:11:48|stratum   Subscribed to stratum server
  i  12:11:48|stratum   Authorized worker 0xeAB43401197Ace40975ADAcF9FF46b933Ed0940f.ELF2
  i  12:11:48|stratum   Received new job #7fc94bca
  m  12:11:48|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:48|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:48|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:49|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:49|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:49|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:49|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:49|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:50|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:50|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:50|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:50|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:51|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:51|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  12:11:51|cl-0      New work: header #7fc94bcaΓÇª target 0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba
 cl  12:11:51|cl-0      New seed #4e99a30eΓÇª
  m  12:11:51|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:51|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:51|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:52|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:52|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:52|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:52|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:52|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:53|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:53|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  12:11:53|cl-0      Platform: Intel(R) OpenCL
 cl  12:11:53|cl-0      Device:   Intel(R) HD Graphics 630  / OpenCL 2.1
  m  12:11:53|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:53|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:53|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  12:11:54|cl-0      Build info: fcl build 1 succeeded.
bcl build succeeded.

 cl  12:11:54|cl-0      Creating light cache buffer, size 39059264
 cl  12:11:54|cl-0      Creating DAG buffer, size 2499803776
  X  12:11:54|cl-0      Creating DAG buffer failed: clCreateBuffer -61
  X  12:11:54|cl-0      OpenCL Error: clEnqueueWriteBuffer -38
  m  12:11:54|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:54|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:11:54|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
