### ISSUE TITLE
Question: Is EthStratumClientV2.cpp used?  What is behaviour when resolver returns multiple IPs?

### ISSUE THREAD

**Issue by SnowLeopard71** [ethereum-mining/ethminer#750]
I'm trying to read the source to see how hostnames that resolve to multiple IPs are treated (like the nanopool servers), and I think I've found that in EthStratumClientV2.cpp, but I cannot find where/how it gets called/used.
It appears the current behaviour when a hostname resolves to multiple IPs is to only use 1 of them and if it stops responding, to try the fail-over server.
If I've read the EthStratumClientV2.cpp code correctly, it would iterate through all IPs returned before moving on the the fail-over server, but this would be new code that is yet to be fully implemented (?)

Have I understood the code correctly?    
Thanks.

**Comment by SnowLeopard71** [comment]
Would it be possible to make it go through all IPs returned before switching to the failover host?
Also, when a connect failure occurs, can the IP that was tried be shown along with the hostname?
Thanks.

**Comment by jean-m-cyr** [comment]
Anything is possible. Feel free to submit a pull request.

**Comment by SnowLeopard71** [comment]
Showing the IP might be within my abilities, but probably not iterating through multiple IPs properly.

**Comment by jean-m-cyr** [comment]
You hinted at the existence of such capability in the V2 code. Maybe use it as a model.

**Comment by SnowLeopard71** [comment]
The V2 code uses different boost functions, but as you saw, I did submit a change based on boost examples for async_connect().
