### ISSUE TITLE
AMD support for power consumption

### ISSUE THREAD

**Issue by Davesmacer** [ethereum-mining/ethminer#756]
Hello,

I like to have the power consumption approximate per card in my miner as a reference. I managed to change some code and do exactly that with Nvidia cards. This was easy task as wrapnvml library already had a wrap_nvml_get_power_usage method defined and working: 

![image](https://user-images.githubusercontent.com/7698291/36291999-64eb0038-1294-11e8-8213-7ae2977765e0.png)

But when it comes to ATI/ADL wrapper wrapadl, the method is not there. I did some research and found out that the method ADL2_Overdrive6_CurrentPower_Get  of ATI/ADL API does exactly that for me.

I started doing the wrap method, but first, I'd like to ask developers if someone is already doing that, or there's a reason why is not done already, so maybe I can make a branch to work there on this feature and parameterize power consumption while I do this. 

Greetings

**Comment by smurfy** [comment]
Hi, its not added, because it's just to much info/output

**Comment by Davesmacer** [comment]
I get that! But it could be possible to add a parameter to show/hide power for people like me that like extra info/output on the same terminal...

**Comment by smurfy** [comment]
sure, create a separate branch + PR for ADL,  i have code for amd sysfs laying around, once you get there.

**Comment by Davesmacer** [comment]
Perfect! I just wanted your blessing haha. Yeah I saw that... I'll try to make it work with power too, for the sake of completeness. I just need a linux machine with video cards (I'm using Windows only because I couldn't get drivers that can work with overclock on linux for my P106-090 cards)

**Comment by nachitox** [comment]
Knowing how much power the cards are usign would be great

**Comment by SnowLeopard71** [comment]
I like the idea of ethminer having the ability to report power consumption.
Ideally, it would also be part of the API for easy queries (instead of parsing log output).

**Comment by Davesmacer** [comment]
I'll start by showing it with a parameter, later on I'll move to try to put it in the API. I'm just wondering if that would mess up claymore's compatibility. I don't use claymore as I hate fees lol

**Comment by smurfy** [comment]
@Davesmacer as i said, i have the amd sysfs code, you just need to worry about ADL.
Regarding api, it can be just a separate rpc method, which also returns power, to not break compatibility.

**Comment by Davesmacer** [comment]
@smurfy Oh got it! I understood wrong... I already made NVIDIA power work with parameter -HWMON 1 to show and -HWMON or -HWMON 0 to not show power. I uploaded the branch "show-power" on my repo...

**Comment by nachitox** [comment]
@Davesmacer I can test the use of ADL2_Overdrive6_CurrentPower_Get on Linux. I'm really interested in this feature.

**Comment by smurfy** [comment]
@nachitox davesmacer's branch currently only support nvidia, 
Do you really still use ADL on linux?

@Davesmacer create a PR here, then i should be able to write to your branch.

**Comment by Davesmacer** [comment]
@smurfy I already created the pull request to master, but I sort of wanted to merge there when I have the ADL wrapper. I think I can get it working at night, so I'll be letting you know through PR.

@nachitox  I'm not sure if linux would work with ADL calls. Once I commit ADL wrapper I let you know

**Comment by nachitox** [comment]
@smurfy Actually no. I tried to get the voltages using this tool https://github.com/matszpk/amdcovc but couldn't make ADL to work
I just want to know how much power the amd cards are using on Linux but I can't find a tool to do it :(

**Comment by SnowLeopard71** [comment]
The only place I've found (so far) to read the power usage for AMD cards on linux is /sys/kernel/debug/dri/0/amdgpu_pm_info (change the 0 as needed).   I'm not sure exactly how the 'max GPU', VDDC, and VDDCI, relate to each other though.

`# cat /sys/kernel/debug/dri/0/amdgpu_pm_info
Clock Gating Flags Mask: 0x37bcf
        Graphics Medium Grain Clock Gating: On
        Graphics Medium Grain memory Light Sleep: On
        Graphics Coarse Grain Clock Gating: On
        Graphics Coarse Grain memory Light Sleep: On
        Graphics Coarse Grain Tree Shader Clock Gating: Off
        Graphics Coarse Grain Tree Shader Light Sleep: Off
        Graphics Command Processor Light Sleep: On
        Graphics Run List Controller Light Sleep: On
        Graphics 3D Coarse Grain Clock Gating: Off
        Graphics 3D Coarse Grain memory Light Sleep: Off
        Memory Controller Light Sleep: On
        Memory Controller Medium Grain Clock Gating: On
        System Direct Memory Access Light Sleep: Off
        System Direct Memory Access Medium Grain Clock Gating: On
        Bus Interface Medium Grain Clock Gating: Off
        Bus Interface Light Sleep: On
        Unified Video Decoder Medium Grain Clock Gating: On
        Video Compression Engine Medium Grain Clock Gating: On
        Host Data Path Light Sleep: Off
        Host Data Path Medium Grain Clock Gating: On
        Digital Right Management Medium Grain Clock Gating: Off
        Digital Right Management Light Sleep: Off
        Rom Medium Grain Clock Gating: On
        Data Fabric Medium Grain Clock Gating: Off

GFX Clocks and Power:
        2000 MHz (MCLK)
        1075 MHz (SCLK)
        50.255 W (VDDC)
        16.0 W (VDDCI)
        78.86 W (max GPU)
        79.101 W (average GPU)

GPU Temperature: 69 C
GPU Load: 100 %

UVD: Disabled

VCE: Disabled
`

**Comment by smurfy** [comment]
@SnowLeopard71   yea, thats how i also read the watt on amdsysfs.

**Comment by nachitox** [comment]
@SnowLeopard71 great info!
So, in your example, the card is using 78.86 W (50.255 W from "the PSU" and 16.0 W from the PCI-E slot) and on average 79.101 W, right?

**Comment by SnowLeopard71** [comment]
@nachitox I don't know exactly how to add up the numbers to get something useful.
The VDDCI is always 16W for all 6 AMD cards I have, but the sum of VDDC+VDDCI is about 12W short of the GPU values.  Also confusing is that "max GPU" is less than "average GPU", if only by a fraction of a W.

**Comment by Davesmacer** [comment]
@nachitox Latest master shows power usage per card with option -HWMON 1

**Comment by SnowLeopard71** [comment]
Behaviour of new -HWMON not quite as described above -- it does require either 0 or 1 else it fails with an error. Expected the 0/1 to be optional, like the block-number for -M or -Z option.
