### ISSUE TITLE
-HWMON Parameter does not work if it is the last command line argument

### ISSUE THREAD

**Issue by techsy730** [ethereum-mining/ethminer#759]
It seems that -HWMON only works if it is not the last command line argument. Otherwise it reports it is an "Invalid Argument"

**Comment by techsy730** [comment]
The culprit seems to be `else if ((arg == "-HWMON") && i + 1 < argc)` in MinerAux.h.

Notice that it has the check for "is there a value after this" `i + 1 < argc` check that arguments that expect a value have (like "--farm-retries" and "--cuda-grid-size"), even though -HWMON doesn't actually read the next argument and thus the check isn't needed.

**Comment by Davesmacer** [comment]
Hello, 

Latest master uses that parameter to indicate if you want to show power usage per card.

-HWMON 1 shows power and -HWMON 0 hides it

Greetings

**Comment by jramos** [comment]
^^^

```
$ ./ethminer --help
...
    -HWMON Displays gpu temp, fan percent and power usage. Note: In linux, the program uses sysfs, which may require running with root priviledges.
        0: Displays only temp and fan percent
        1: Also displays power usage
```

**Comment by jean-m-cyr** [comment]
I believe this is fixed in master. closing

**Comment by SnowLeopard71** [comment]
Behaviour of new -HWMON not quite as described above -- it does require either 0 or 1 else it fails with an error.  Expected the 0/1 to be optional, like the block-number for -M or -Z option.

**Comment by jean-m-cyr** [comment]
We really should have supported backwards compatibility on this one!

**Comment by Davesmacer** [comment]
I thought it had!! Give me some hours to check it later

**Comment by SnowLeopard71** [comment]
@Davesmacer it's why we have "dev" brances, right? ;)
Also, could you change the help output to be like -M and -Z to show the parameter is optional:
```
    -HWMON [<n>] Displays gpu temp, fan percent and power usage. Note: In linux, the program uses sysfs, which may require running with root privileges.
        0: Displays only temp and fan percent (default behaviour)
        1: Also displays power usage
```

**Comment by Davesmacer** [comment]
Done. I'll include the changes on the PR related to power consumption API method #761

**Comment by jean-m-cyr** [comment]
@Davesmacer Already have queued PR for that
