### ISSUE TITLE
GPU fault detected: 146

### ISSUE THREAD

**Issue by mrproper** [ethereum-mining/ethminer#76]
I used to use genoils ethminer which had this problem (about every minute i get a dump of these in dmesg):
`[ 4700.645531] amdgpu 0000:02:00.0: GPU fault detected: 147 0x03c4c408
[ 4700.647095] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0010FE1E
[ 4700.648680] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x041C4008
[ 4700.649497] amdgpu 0000:02:00.0: VM fault (0x08, vmid 2) at page 1113630, read from 'TC7' (0x54433700) (452)
[ 4700.649497] amdgpu 0000:02:00.0: GPU fault detected: 147 0x02640808
[ 4700.649497] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0010FE1A
[ 4700.649497] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x04144008
[ 4700.649497] amdgpu 0000:02:00.0: VM fault (0x08, vmid 2) at page 1113626, read from 'TC1' (0x54433100) (324)
[ 4700.649497] amdgpu 0000:02:00.0: GPU fault detected: 147 0x03044808
[ 4700.649497] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0010FE10
[ 4700.649497] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x041C8008
[ 4700.649497] amdgpu 0000:02:00.0: VM fault (0x08, vmid 2) at page 1113616, read from 'TC6' (0x54433600) (456)
[ 4700.649497] amdgpu 0000:02:00.0: GPU fault detected: 147 0x03840808
[ 4700.649497] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0010FE15
[ 4700.649497] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x04188008
[ 4700.649497] amdgpu 0000:02:00.0: VM fault (0x08, vmid 2) at page 1113621, read from 'TC4' (0x54433400) (392)
[ 4700.649497] amdgpu 0000:02:00.0: GPU fault detected: 147 0x03444408
[ 4700.649497] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0010FE1E
[ 4700.649497] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x04088008
[ 4700.649497] amdgpu 0000:02:00.0: VM fault (0x08, vmid 2) at page 1113630, read from 'TC4' (0x54433400) (136)
[ 4700.649497] amdgpu 0000:02:00.0: GPU fault detected: 147 0x03840808
[ 4700.649497] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0010FE13
[ 4700.649497] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x04044008
[ 4700.649497] amdgpu 0000:02:00.0: VM fault (0x08, vmid 2) at page 1113619, read from 'TC1' (0x54433100) (68)
[ 4700.649497] amdgpu 0000:02:00.0: GPU fault detected: 147 0x03e4c808
[ 4700.649497] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0010FE1C
[ 4700.649497] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x04088008
[ 4700.649497] amdgpu 0000:02:00.0: VM fault (0x08, vmid 2) at page 1113628, read from 'TC4' (0x54433400) (136)
[ 4700.696148] amdgpu 0000:02:00.0: GPU fault detected: 147 0x02a40808
[ 4700.697552] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0010FE15
[ 4700.698968] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x04108008
[ 4700.700134] amdgpu 0000:02:00.0: VM fault (0x08, vmid 2) at page 1113621, read from 'TC2' (0x54433200) (264)
[ 4700.700134] amdgpu 0000:02:00.0: GPU fault detected: 147 0x0204c808
[ 4700.700134] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0010FE1F
[ 4700.700134] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x04088008
[ 4700.700134] amdgpu 0000:02:00.0: VM fault (0x08, vmid 2) at page 1113631, read from 'TC4' (0x54433400) (136)
[ 4700.700134] amdgpu 0000:02:00.0: GPU fault detected: 147 0x03e48808
[ 4700.700134] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0010FE11
[ 4700.700134] amdgpu 0000:02:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x04104008
[ 4700.700134] amdgpu 0000:02:00.0: VM fault (0x08, vmid 2) at page 1113617, read from 'TC3' (0x54433300) (260)
`
out of all the card combinations i have it only occurs on the MSI R9 380 card, when i had this problem it I had to update to genoil branch 110 which solved the problem, since i've switched to this build its back =)

btw thanks for the work you've done on this project, appreciated

**Comment by JHGitty** [comment]
Sounds to me as a hardware failure. Do you have any other R9 380 card to compare with?

**Comment by mrproper** [comment]
seems it may have been a dodgy riser batch i had, just replaced them all with a new batch and the problem has gone away...still strange that i wasnt getting it on the genoil branch i mentioned

**Comment by jimmykl** [comment]
Mining troubleshooting: one part turning it off and on again and another part voodoo!

Good it's working now for you. Please close the issue :)

**Comment by mrproper** [comment]
thanks for that and apologies for the muck around
