### ISSUE TITLE
Issues that can be closed (cleanup)

### ISSUE THREAD

**Issue by DeadManWalkingTO** [ethereum-mining/ethminer#764]
I think those issues can be closed.

#749 - #739 - #719 - #713 - #712 
#705 - #692 - #678 - #631 - #619
#593 - #586 - #585 - #579 - #577
#565 - #561 - #552 - #544 - #514
#512 - #505 - #441 - #385 - #378
#358 - #349 - #336 - #334 - #324
#318 - #297 - #289 - #281 - #280
#276 - #251 - #231

And this!

**Comment by smurfy** [comment]
Since other and i went thru all tickets, I closed most of them and added comments if needed.
Some of them where usage advice, so maybe we should continue/improve upon what i started here:

https://smurfy.github.io/ethminer/
https://github.com/smurfy/ethminer/tree/gh-pages

**Comment by SnowLeopard71** [comment]
@smurfy Maybe the wiki feature should be turned on and that kind of info there?

**Comment by DeadManWalkingTO** [comment]
I believe wiki is the best answer!

**Comment by DeadManWalkingTO** [comment]
BTW @smurfy  Very good job!

**Comment by smurfy** [comment]
i'm no fan of wikis. they tend to be outdated very quickly

**Comment by Davesmacer** [comment]
It will be great to have an info page as that one! Actually, I was checking old issues and most of them can be closed as they're not really issues or no one is giving any update if master solved it or just got solved and remained there...

**Comment by smurfy** [comment]
i will update the pages and correct some spelling errors. Then push them to the main repo.
After that everyone can contribute and submit PRs for the documentation.

**Comment by DeadManWalkingTO** [comment]
@smurfy  I think those issues can be closed.

#227 - #215 - #213 - #206 - #202
#201 - #199 - #195 - #194 - #190
#185 - #171 - #156 - #143 - #97
#93 - #92 - #81 - #79 - #60

**Comment by DeadManWalkingTO** [comment]
#814

**Comment by DeadManWalkingTO** [comment]
#813

**Comment by DeadManWalkingTO** [comment]
#769

**Comment by DeadManWalkingTO** [comment]
#734

**Comment by DeadManWalkingTO** [comment]
#529

**Comment by DeadManWalkingTO** [comment]
#463

**Comment by DeadManWalkingTO** [comment]
#341

**Comment by DeadManWalkingTO** [comment]
#299  2GB GPU

**Comment by DeadManWalkingTO** [comment]
#764 Dual Mining

**Comment by DeadManWalkingTO** [comment]
#215 Dual Mining

**Comment by DeadManWalkingTO** [comment]
#206 Wrong server name!!!

**Comment by DeadManWalkingTO** [comment]
#202 GTX 1070 Douplicate

**Comment by DeadManWalkingTO** [comment]
#190 Nvidia Optimization Duplicate

**Comment by DeadManWalkingTO** [comment]
#185 The Debug option -v [n]  and screen colors

**Comment by DeadManWalkingTO** [comment]
#156 GTX 1070 Duplicate

**Comment by DeadManWalkingTO** [comment]
#43 
Hashrate per card was added with PR #225
Temperature and Fan will come with PR #319

**Comment by DeadManWalkingTO** [comment]
#119 GTX 1060 Duplicate

**Comment by DeadManWalkingTO** [comment]
#79 colors

**Comment by DeadManWalkingTO** [comment]
350 issues are closed at the moment.
Please check those above!

**Comment by MariusVanDerWijden** [comment]
@DeadManWalkingTO Thank you very much :+1:
