### ISSUE TITLE
No "reported Hashrate" after Internet Disconnect and wierd behaviour (AMD)

### ISSUE THREAD

**Issue by JokerGermany** [ethereum-mining/ethminer#765]
Since ethminer 13.0 and after my Internet reconnects i get a wierd behaviour.
The good thing is, that it seems not to affect mining.
![ethwierd1](https://user-images.githubusercontent.com/30293477/36371183-9e3e8c36-1561-11e8-92f3-15132e02cdf5.PNG)
![ethwierd2](https://user-images.githubusercontent.com/30293477/36371184-9e5c9384-1561-11e8-82e9-6dd8dc23ea83.PNG)
(My Router reconnected at 4:39)

**Comment by smurfy** [comment]
can you try master?

**Comment by JokerGermany** [comment]
What do you mean?

**Comment by smurfy** [comment]
Current master (latest dev version)
https://ci.appveyor.com/project/ethereum-mining/ethminer/build/841/job/ulifvgfw7pedgbk7/artifacts

**Comment by JokerGermany** [comment]
I will use this, this night

**Comment by JokerGermany** [comment]
Yeah, the error seems to be fixed in dev1
![ethwierd1-dev1](https://user-images.githubusercontent.com/30293477/36418312-c5d5ee60-162e-11e8-9552-aa53907e78fe.PNG)
![ethwierd2-dev1](https://user-images.githubusercontent.com/30293477/36418313-c5f7d9b2-162e-11e8-9348-e2ef880e4e13.PNG)
