### ISSUE TITLE
cant build with cmake -- help!

### ISSUE THREAD

**Issue by d0n-miner1** [ethereum-mining/ethminer#769]
-- [hunter] LIBJSON-RPC-CPP_ROOT: /home/don/.hunter/_Base/59b2b88/0452b62/c20b399/Install (ver.: 0.7.0-p3)
------------------------------------------------------------------------
-- CMake 3.5.1
-- Build Release / Linux
------------------------------------------------------------- components
-- ETHASHCL         Build OpenCL components                  ON
-- ETHASHCUDA       Build CUDA components                    ON
-- ETHDBUS          Build D-Bus components                   OFF
-- APICORE          Build API Server components              ON
------------------------------------------------------------------------

CMake Error at /usr/share/cmake-3.5/Modules/FindCUDA.cmake:617 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  libhwmon/CMakeLists.txt:19 (find_package)

-- Configuring incomplete, errors occurred!
See also "/usr/local/ethminer/build/CMakeFiles/CMakeOutput.log".
See also "/usr/local/ethminer/build/CMakeFiles/CMakeError.log".
don@cryptolynx-my:/usr/local/ethminer/build$

**Comment by jean-m-cyr** [comment]
Either you don't have the CUDA toolkit installed, or /usr/local/cuda is not soft linked to your actual version's directory.

**Comment by d0n-miner1** [comment]
I gotta reinstall ubuntu

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
