### ISSUE TITLE
Ubuntu 16.04 and ATM RX470, crashed on OPENCL#0: 99%

### ISSUE THREAD

**Issue by honlen** [ethereum-mining/ethminer#77]
My PC is Ubuntu 16.04 and AMD RX470.
It is always crashed as following while ethminer is running.
[OPENCL]:Generating DAG data
OPENCL#0: 0%
...
OPENCL#0: 99%
Would you please give me some help to solve it?
Thanks a lot.

**Comment by nikolehto** [comment]
I got it working on ubuntu by downgrading the OpenCL ICD to version 16.40

Download the 16.40 driver http://support.amd.com/en-us/kb-articles/Pages/AMD-Radeon-GPU-PRO-Linux-Beta-Driver–Release-Notes.aspx
Extract the driver archive with 
```
tar xvJf amdgpu-pro-16.40-348864.tar.xz
cd amdgpu-pro-16.40-348864
dpkg -i opencl-amdgpu-pro-icd_16.40-348864_*.deb
```


instructions are from here
https://github.com/genesismining/sgminer-gm/wiki/Compile-sgminer-5.5.5-in-Ubuntu-16.04.1-LTS


I think instructions could be added on readme?

**Comment by honlen** [comment]
It works. 
amdgpu-pro-16.40-348864 is the key.

**Comment by honlen** [comment]
Thank you, nikolehto.
