### ISSUE TITLE
Problems with API requests on Python

### ISSUE THREAD

**Issue by vottghern** [ethereum-mining/ethminer#771]
I was started miner with `--api-port -3333` options on Ubuntu 16.04. Trying API request from command line of Bash shell:
`echo '{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}' | netcat localhost 3333`
output is:
`{"id":0,"jsonrpc":"2.0","result":["0.13.0rc7","121","172958;305;0","24619;24697;24697;24697;24775;24775;24697","0;0;0","off;off;off;off;off;off;off","54;70; 55;70; 52;65; 50;65; 52;65; 51;65; 56;70","pirl.minerpool.net:8004","0;0;0;0"]}`
All work fine! 
Then I tried writing a script in Python
First version:
```python
import socket
import json

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('127.0.0.1', 3333))
s.sendall('{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}'.encode('utf-8'))
s.shutdown(socket.SHUT_WR)
resp = ''
while 1:
     data = s.recv(1024)
     resp += data.decode('utf-8')
     if not data or (len(data) < 1024 and data[-2:] == ']}'):
          break
s.close()
print (resp)
```
The script hangs and I can exit only by pressing Ctrl+C. Hangs on line **data = s.recv(1024)**.

Second version of script:
```python
import socket
import json
import select

data = ''
timeout = 2

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('127.0.0.1', 3333))
s.sendall('{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}'.encode('utf-8'))
s.shutdown(socket.SHUT_WR)
s.setblocking(0)
fulltext = ''
while 1:
     ready = select.select([s], [], [], timeout)
     if ready[0]:
        data = s.recv(4096)
     if not data:
        break
     fulltext += data.decode('utf-8')
s.close()
print (fulltext)
```
The script hangs as much time as specified in the timeout variable and then terminates with the output of the empty string.
What am I doing wrong?

**Comment by AndreaLanfranchi** [comment]
The problem is you "shutdown" the socket immediately after the first send: thus s.recv has nothing to receive.
See [here](https://stackoverflow.com/questions/409783/socket-shutdown-vs-socket-close)

**Comment by vottghern** [comment]
Has removed. Nothing has changed, both versions give the same result

**Comment by AndreaLanfranchi** [comment]
JsonRpc specifications dictate messages should be sent terminated by a line-feed.
If you read ethminer code you will see it waits (on socket connections for a whole line).
Try to amend your s.sendall as per below sample

`s.sendall('{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}\n'.encode('utf-8'))`

**Comment by vottghern** [comment]
YES!!! Thanks!
```python
import socket
import json

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('localhost', 3333))
s.sendall('{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}\n'.encode('utf-8'))
resp = ''
while 1:
     data = s.recv(4096)
     resp += data.decode('utf-8')
     if not data or (len(data) < 4096 and data[-3:] == b']}\n'):
          break
s.close()
print (resp)
```
Also in the output at the end have \n ! Oh my God! 
Why not want to make a normal REST API?
