### ISSUE TITLE
Please Help: Miner see only onboard GPU

### ISSUE THREAD

**Issue by zorohakobyan** [ethereum-mining/ethminer#772]
Hi! I have 6x asus gtx 1050ti oc but after starting miner I see only onboard GPU and 0 mh/s
I've tried to use different versions but the problem is the same
here is bat file and screenshot
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe -RH  --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0xeAB43401197Ace40975ADAcF9FF46b933Ed0940f.ELF2
![capture](https://user-images.githubusercontent.com/36232590/36413630-b3185768-1638-11e8-99f9-d59b1ee1e681.PNG)

**Comment by AndreaLanfranchi** [comment]
With NVIDIA cards you have two options :

1. Use CUDA (preferred) thus replace -G with -U
2. Use OpenCl (not optimal) thus keep -G but add also add --opencl-platform 1

**Comment by zorohakobyan** [comment]
AndreaLanfranchi thank You!
Now it's working!!!
![capture](https://user-images.githubusercontent.com/36232590/36414677-8b487386-163c-11e8-93fd-3aba91b9c8a7.PNG)
And one more question: I'm using this overclocking parameters 
Power limit=100%
Core clock=+0
Memory clock=+600
Is it ok or You can recommend something else (using asus strix 1050ti oc)
Thank You in advance!

**Comment by AndreaLanfranchi** [comment]
I have a test rig with same cards on Linux.
My personal settings are :

Power Limit : 52.50 Watts
Core Clock : -190
Mem Clock:  800

I get roughly the same hashrate as you but with lot less power consumption.

If it's all ok please close this issue.

**Comment by zorohakobyan** [comment]
I'll try! Thanks again!
