### ISSUE TITLE
why in the dos mode (win10) ethminer.exe > 1234.txt is not working??

### ISSUE THREAD

**Issue by andy4525288** [ethereum-mining/ethminer#773]
Dear every one 

how to output the ethminer screen display to a file in DOS  mode
because , I am not sure why my ETHminer.exe will down after 1 or 2 days because of the CUDA error "line 489"
I want to export all the ethminer output   to a file and use DOS CMD function to find the error code "line 489"
so I can reboot my computer automatically without I am there

but I found a strange things 
i can do the following 
ping 8.8.8.8 > 1234.txt

but if I do the ethminer.exe >2345.txt 

this is not working  and  2345.txt is empty 
anyway  I can export the CRT to a file in windows 10 dos mode 64 bit??

please help

Andy

**Comment by XhmikosR** [comment]
@andy4525288: because it seems ethminer is using the error stream to output.

So to solve your issue as it is now, you need to do `ethminer.exe 2>1234.txt`

@jean-m-cyr @chfast: But I wonder, why this decision? The error stream should only have errors...

**Comment by jean-m-cyr** [comment]
Not sure, this choice was made long ago. The use of stderr for log output, as opposed to console output, is not uncommon practice in *nix apps.
