### ISSUE TITLE
HWMON fan speed reporting bug

### ISSUE THREAD

**Issue by Mneroen** [ethereum-mining/ethminer#774]
I have a 6 gpu rig, 5x RX570 and 1x R9 380
The gpu 3 is my R9 380 gpu.
Ethminer shows the gpu 3 fan speed at the gpu 5, and the gpu 5 fan speed at the gpu 3 with -HWMON 0 parameter.

![ethminer_fan_speed_error](https://user-images.githubusercontent.com/9325475/36427750-4fe88f80-164e-11e8-8ea7-2e03ed57e1b0.jpg)

**Comment by Davesmacer** [comment]
Hello,

This is a known issue using AMD and Windows ADL library!! See #724. Try to check old issues before opening a new one. @smurfy and I are working on it. Anyway, your output does helped me out to understand the issue. Are your sure those are the only monitors that are switched?

**Comment by smurfy** [comment]
Well best way would be mapping with pci id, i have methods for it for nvml + amdsysfs.

Based on this: https://anteru.net/blog/2014/08/01/2483/index.html 
Its possible to get pci id via opencl for amd + nvidia

Cuda should not be a problem, mapping between cuda id and nvml id is already there.

**Comment by Mneroen** [comment]
I don't know.

I've changed the fan speeds and this is a total mess, because in MSI Afterburner and in HWINFO the
1. gpu is RX 570 with 60% fan speed. In ethminer i see this number at the gpu/2
2. gpu is RX 570 with 61% fan speed. In ethminer i see this number at the gpu/1
3. gpu is R9 380 with 50% fan speed. In ethminer i see this number at the gpu/5, but i know that the R9 380 is the gpu/3 gpu because of the hashrate.
4. gpu is RX 570 with 62% fan speed. In ethminer i see this number at the gpu/4
5. gpu is RX 570 with 63% fan speed. In ethminer i see this number at the gpu/3
6. gpu is RX 570 with 64% fan speed. In ethminer i see this number at the gpu/0

**Comment by Davesmacer** [comment]
As you said, total mess!! ADL gives completely different order. I'm going to map pci id to match ADL and cards numbers as pointed by @smurfy. Thank you for your help
