### ISSUE TITLE
100% CPU use with CUDA

### ISSUE THREAD

**Issue by maxcom99** [ethereum-mining/ethminer#783]
![2018-02-21_9-06-28](https://user-images.githubusercontent.com/12089125/36490881-96b91f22-16e6-11e8-826a-1fce65bcf698.png)

This is only happening on my CUDA miner box. I initially thought it was the --cuda-schedule or --cuda-noeval but these changes had no effect. Any ideas? Running latest 14.dev2

**Comment by AndreaLanfranchi** [comment]
It appears you run a separate instance of ethminer for each gpu ?
Why would you want to do that ?

**Comment by maxcom99** [comment]
I'm playing around with ethOS so those are not questions I could answer - regardless of the setup, the CPU usage shouldn't be this high since with the OpenCL rig it is more like 4% using exact same everything else including the wasteful configuration.

**Comment by AndreaLanfranchi** [comment]
Are you power-limiting GPUs ?

**Comment by maxcom99** [comment]
Yes

**Comment by DeadManWalkingTO** [comment]
Check #695 !

**Comment by SnowLeopard71** [comment]
I was running with **--cuda-schedule auto** and it was causing "1" load per GPU (ie, 2 GPUs brought system load to about 2.00, 5 GPUs to about 5.00).  Without --cuda-schedule option load is normal (well below 1.00).  (System was not sluggish even with load at 5 though.)

Other reports mention mistakenly using OpenCL on CUDA devices... I did that once but didn't notice what the CPU usage was as the hashrate was down by a significant amount which made it obvious there was a problem.

**Comment by maxcom99** [comment]
After further testing it is  --cuda-schedule auto that is causing the CPU load thank you @SnowLeopard71  -- any ideas why?

**Comment by SnowLeopard71** [comment]
No, no clue why.  Even stranger is this box also has 6 AMD Gpus running under a different instance (while waiting for -X fixes) and it losses 4-6 Mh/s if the Nvidia instance is not running with --cuda-schedule auto, so I've kept it on for now.

**Comment by DeadManWalkingTO** [comment]
On Win10 `--cuda-schedule` not needed. (I have only CUDA GPU's).
After disabling services i have CPU load 100% for few sec at miner's start. After that load is about 40-50%.

**Comment by charleshap** [comment]
On wind10 --cuda-schedule auto not needed. REMOVE THIS!
