### ISSUE TITLE
Question about NO_COLOR

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ethereum-mining/ethminer#785]
Why to set an env var instead of passing a --no-color cli argument ?

**Comment by smurfy** [comment]
export NO_COLOR=1

or

set NO_COLOR=1

**Comment by AndreaLanfranchi** [comment]
Yes it is exactly what I said.
Why 

```
export NO_COLOR=1
./ethminer ....
```

instead of

`./ethminer --no-color ....`

**Comment by smurfy** [comment]
Oops sorry, misread your question.

The correct answer would be: http://no-color.org

**Comment by alptolga** [comment]
Is it possible to get colored text for win 8.1? My win10 rigs have colored text but win 8.1 rigs haven't

**Comment by smurfy** [comment]
@alptolga sorry, only win10+ support colors in command prompt.
You could try https://conemu.github.io/  on Win 8.1 not sure if colors work there. But i think we disable colors if the commands necessary for colors on win10 fail.

**Comment by AndreaLanfranchi** [comment]
Anyway the option to remove colors from the output works.
Method for setting this option is purely cosmetic.
Thus I close the issue.

**Comment by bmatthewshea** [comment]
Sorry to comment on this closed one, but why is color disabled on everything besides WIN10? I use Win7 for one of the miners and have been wondering why it's not supported?

AFAIK Windows7 CMD will still print color/escape codes..  = https://i.imgur.com/qmhHk2d.png

thanks much.

**Comment by bmatthewshea** [comment]
nevermind i see you used ENABLE_VIRTUAL_TERMINAL_PROCESSING 0x0004 
:(
