### ISSUE TITLE
Message logging

### ISSUE THREAD

**Issue by eLvErDe** [ethereum-mining/ethminer#79]
Hi,

I just started ethminer in a Mesos cluster and the output is kinda inappropriate for this.
I see two issues here:
* Most of the logs goes to stderr instead of stdout
* It uses colorized output that Mesos cannot handle (may I ask for a command line switch disabling this ? ;)

Regards, Adam.

**Comment by chfast** [comment]
The ethminer does not check at runtime if there is a terminal color support. See https://github.com/ethereum-mining/ethminer/blob/master/libdevcore/Terminal.h.

**Comment by JHGitty** [comment]
wait, what? The miner has color support? Then somehow the default windows terminal is not supported yet, right?

**Comment by chfast** [comment]
No colors on Windows, right. Blame Windows.

**Comment by jimmykl** [comment]
Yep @chfast it's Windows fault. I did some research and it's a known issue after the anniversary update. There is way to enable 'legacy' console support during compile I just need to get my head around configuring it.

**Comment by chfast** [comment]
If would forget about legacy cmd. I think PowerShell supports colors, so someone can add support for it.

**Comment by JHGitty** [comment]
I don't think it would be false to support the 'legacy' terminal/console on Windows because 99% of the users out there will use it. But that's a discussion for itself...

**Comment by ksimic** [comment]
Issue still persists..

ethminer.exe -F http://dbix2.pool.sexy:7777/XXX -G
Found suitable OpenCL device [GeForce GTX 1080 Ti] with 11811160064 bytes of GPU memory
  m  12:13:08|main  Getting work package...
  m  12:13:08|main  Got work package: #3be17e8d
  i  12:13:08|openclminer0  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer1  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer0  Initialising miner...
  i  12:13:08|openclminer1  Initialising miner...
  i  12:13:08|openclminer2  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer2  Initialising miner...
  i  12:13:08|openclminer3  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer3  Initialising miner...
  i  12:13:08|openclminer4  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer4  Initialising miner...
  i  12:13:08|openclminer5  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer5  Initialising miner...

**Any line from here on does char by char output and 100% CPU usage, rendering ethminer unusable**

  m  12:13:09|main  Mining on PoWhash #3be17e8d : 0.00MH/s [A0+0:R0+0:F0]
Using platform: NVIDIA CUDA  m  12:13:10|main  M

the m lines are killing the system @chfast

**Comment by ksimic** [comment]
Issue still persists..

ethminer.exe -F http://dbix2.pool.sexy:7777/XXX -G
Found suitable OpenCL device [GeForce GTX 1080 Ti] with 11811160064 bytes of GPU memory
  m  12:13:08|main  Getting work package...
  m  12:13:08|main  Got work package: #3be17e8d
  i  12:13:08|openclminer0  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer1  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer0  Initialising miner...
  i  12:13:08|openclminer1  Initialising miner...
  i  12:13:08|openclminer2  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer2  Initialising miner...
  i  12:13:08|openclminer3  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer3  Initialising miner...
  i  12:13:08|openclminer4  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer4  Initialising miner...
  i  12:13:08|openclminer5  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer5  Initialising miner...

**Any line from here on does char by char output and 100% CPU usage, rendering ethminer unusable**

  m  12:13:09|main  Mining on PoWhash #3be17e8d : 0.00MH/s [A0+0:R0+0:F0]
Using platform: NVIDIA CUDA  m  12:13:10|main  M

the m lines are killing the system @chfast 

The ETHCL_LOG macro still uses the spin lock based logging approach. Could you add a flag to use the simple logging everywhere like in your #110 fix?
