### ISSUE TITLE
How to set up an automatic restart of the miner every hour ?

### ISSUE THREAD

**Issue by miner56** [ethereum-mining/ethminer#790]
Hi.
How to set up an automatic restart of the miner **every hour** ?
In Claymore, this is done using the **_-R 60_** command

**Comment by MariusVanDerWijden** [comment]
Why would you want that?

**Comment by miner56** [comment]
To avoid mistakes in the work ethminer 0.14.0.dev2 - I want to specify the interval in minutes to restart-60 minutes, 180 minutes, 720 minutes...
in order to avoid financial losses from not stable work ethminer 0.14.0.dev2

**Comment by miner56** [comment]
I'm sorry for my English - I use google translator
я из россии... Путин, водка, балалайка ))

**Comment by mrbrendanhamm** [comment]
For Linux based systems:

I really like the [start-stop daemon](https://gist.github.com/bmatthewshea/9a062c092fd673318f8d208ce44f4f51).

Then you can setup a [monitor](https://gist.github.com/bmatthewshea/6bad5242dbf270ef881c033918b947c0), which you may want to change depending on how you want to handle issues. I have seen people use nvidia-smi to determine if cpu temp has dropped too low in the monitor. Add this to your Linux grub, and good to go.If you really wanted every 60 minutes, then you can just have a grub file which restarts ethminer every 60 minutes.

For windows based systems, just create a batch file which loops and restarts every hour. Some quick google searches will get you there.

**Comment by DeadManWalkingTO** [comment]
Hi@all
After #757 (added --exit parameter to exit whenever an error occurred) you can use a watchdog.

Here is my [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) Windows7/8/10 [32/64] & Linux (Any Dist/Any Ver/Any Arch).

Check and feedback pls.
Thank you!

**Comment by kokleong98** [comment]
I have create something similar even though still under development. You may have a try. EthminerMan.exe
https://github.com/kokleong98/raygust/releases

**Comment by miner56** [comment]
Заебись конечно! Хотелось бы реализовать перезагрузку штатно, внутри программы.

**Comment by AndreaLanfranchi** [comment]
Use a cronjob.
Kill ethminer process with signal 2 sleep a reasonable amount of time (say 30 seconds) and restart it.

**Comment by AndreaLanfranchi** [comment]
Not an issue.
