### ISSUE TITLE
ethminer 0.14.0.dev2 incorrect hashrates

### ISSUE THREAD

**Issue by lordrive** [ethereum-mining/ethminer#791]
I have 6 GTX 1060 in one of my mining rigs and for some reason after a while they are starting to display and report completely invalid hash rates.

My average reported hashrate is 224Mh/s and somehow the new build is reporting 250-260 Mh/s after half- one hour.

Not only it is reporting an ivalid hashrate but in the miner itself, the individual gpus are displaying unusually high hashrates.

While in another mining rig where there are RX 570s this error is not present.

![kep](https://user-images.githubusercontent.com/19550433/36552326-e03cf092-17f9-11e8-9f85-042cbb793134.png)

![kep](https://user-images.githubusercontent.com/19550433/36552374-000b8046-17fa-11e8-9f22-b9050110b4c6.png)

**Comment by DeadManWalkingTO** [comment]
I believe that have been fixed.
Use the last version of Ethminer and feedback please.
Thank you!

**Comment by lordrive** [comment]
It seems to be working now properly, although when i started the miner it still did produce some interesting hashing values, but then it normalized.

**Comment by lordrive** [comment]
Nope, it's still there, after 16 hours it appeared again.
![kep](https://user-images.githubusercontent.com/19550433/36779667-05480856-1c71-11e8-93b5-bfda79f61a2b.png)

**Comment by chfast** [comment]
What version have you used for the last test?

**Comment by chfast** [comment]
Can you test https://github.com/ethereum-mining/ethminer/releases/tag/v0.15.0rc1 ?
