### ISSUE TITLE
Very low hash rate with R9-280x on macOS (OSX)? Just under 4 Mh/s.

### ISSUE THREAD

**Issue by thoomp** [ethereum-mining/ethminer#792]
Hi there - Although I'm a mining newbie, I'd test ethminer on the MSI 3GB R9-280x I have in my Mac Pro (MacOS 10.13.3) before installing a RX 580 card. I set things up with eth.pool.minergate.com and things seem okay ("Nonce XXXXXXXXXX submitted to eth.pool.minergate.com | ** Accepted in (about 125) ms.)

The issue is that the speed only tops out at about 3.80 Mh/s - which doesn't seem right for this card. 

Per the forums, I compiled a working version to see if that might help, and there was no change in the speed.

Any thoughts? Many thanks in advance!

**Comment by DeadManWalkingTO** [comment]
Don't have a clue about MacOS but check for driver updates, CPU usage, available RAM and feedback please.
Thank you!

**Comment by bmacn** [comment]
I've been trying to resolve a similar problem; MacOS AMD RX 580 stays under 4 Mh/s.  I'll provide what output I can, this is my first attempt at mining so I'm ignorant in many ways.  I do consistently get an error when using the RX 580;
Build info: <program source>:336:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~
<program source>:371:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~


Tested on 2 machines, both macOS 10.13.3.  One is a 2016 Macbook Pro 2.5GHz i7 16G ram.  The other is Hackintosh macOS 3.7GHz (5GHz oc) i7 64G ram.  These machines have a GTX 1080 ti as well as the AMD RX 580.

Tested with ethminer 0.13.0 and ethminer 0.14.0.dev3.

Behavior seems to be the same on both platforms/versions.

This is output from the GTX 1080 ti to show that the setup is working;
  m  13:53:58|        |  ethminer version 0.14.0.dev3
  m  13:53:58|        |  Build: darwin / release +git. 83693003
 cu  13:53:59|        |  Using grid size 8192 , block size 128
 cu  13:54:03|cuda-0  |  Using device: GeForce GTX 1080 Ti  (Compute 6.1)
 cu  13:54:03|cuda-0  |  Set Device to current
 cu  13:54:03|cuda-0  |  Resetting device
 cu  13:54:03|cuda-0  |  Allocating light with size: 39320768
 cu  13:54:03|cuda-0  |  Generating mining buffers
 cu  13:54:03|cuda-0  |  Generating DAG for GPU # 0  with dagSize: 2516582272  gridSize: 8192
m  13:54:24|        |  Speed  32.51 Mh/s    gpu/0 32.51  [A430+0:R0+0:F0] Time: 00:00
^ this case runs well

This is output from the RX 580 which runs slow and produces an error regarding int/uint comparison;
  m  13:59:47|        |  ethminer version 0.14.0.dev3
  m  13:59:47|        |  Build: darwin / release +git. 83693003
  i  13:59:47|        |  Found suitable OpenCL device [ AMD Radeon RX 580 Compute Engine ] with 8589934592  bytes of GPU memory
 cl  13:59:51|cl-0    |  Platform: Apple
 cl  13:59:51|cl-0    |  Device:   AMD Radeon RX 580 Compute Engine  / OpenCL 1.2 
 cl  13:59:51|cl-0    |  OpenCL kernel: Stable kernel
 cl  13:59:51|cl-0    |  Build info: <program source>:336:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~
<program source>:371:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~

 cl  13:59:51|cl-0    |  Creating light cache buffer, size 39320768
 cl  13:59:51|cl-0    |  Creating DAG buffer, size 2516582272
 cl  13:59:51|cl-0    |  Loading kernels
 cl  13:59:51|cl-0    |  Writing light cache buffer
 cl  13:59:51|cl-0    |  Creating buffer for header.
 cl  13:59:51|cl-0    |  Creating mining buffer
  i  13:59:59|cl-0    |  2.34375  GB of DAG data generated in 7594 ms.
m  14:00:07|        |  Speed   3.54 Mh/s    gpu/0  3.54  [A17+0:R0+0:F0] Time: 00:00
^ as we can see here... consistent speeds under 4Mh/s.

I've not looked at the source, but perhaps the error here is actually related.  Let me know if there is any info I can provide.

**Comment by bmacn** [comment]
I did a quick patch/recompile to see if resolving this error fixes the slowness, unfortunately it does not.  It's still a bug that needs fixed though, heres the hasty patch I used;

diff --git a/libethash-cl/CLMiner_kernel_stable.cl b/libethash-cl/CLMiner_kernel_stable.cl
index a6a301e27..6ea4c7c31 100644
--- a/libethash-cl/CLMiner_kernel_stable.cl
+++ b/libethash-cl/CLMiner_kernel_stable.cl
@@ -318,12 +318,13 @@ __kernel void ethash_search(
        
        // Threads work together in this phase in groups of 8.
        uint const thread_id = gid & 7;
+       int thread_id_int = gid & 7;
        uint const hash_id = (gid % GROUP_SIZE) >> 3;
 
        for (int i = 0; i < THREADS_PER_HASH; i++)
        {
                // share init with other threads
-               if (i == thread_id)
+               if (i == thread_id_int)
                        copy(share[hash_id].ulongs, state, 8);
 
                barrier(CLK_LOCAL_MEM_FENCE);
@@ -358,7 +359,7 @@ __kernel void ethash_search(
                share[hash_id].uints[thread_id] = fnv_reduce(mix);
                barrier(CLK_LOCAL_MEM_FENCE);
 
-               if (i == thread_id)
+               if (i == thread_id_int)
                        copy(state + 8, share[hash_id].ulongs, 4);
 
                barrier(CLK_LOCAL_MEM_FENCE);

**Comment by smurfy** [comment]
``if (i == (int)thread_id)``  should work too.  

Regarding speed. try playing with the ``--cl-*`` params,

````
   --cl-local-work Set the OpenCL local work size. Default is 128
    --cl-global-work Set the OpenCL global work size as a multiple of the local work size. Default is 8192 * 128
    --cl-parallel-hash <1 2 ..8> Define how many threads to associate per hash. Default=8
````

**Comment by bmacn** [comment]
That does it, thanks smurfy!!!

Note that --cl-parallel-hash enforces 8 threads in the generic kernel so that cannot be adjusted.

This appears to have my RX 580 eGPU (thunderbolt) running appropriately.
--cl-local-work 256 --cl-global-work 98304
Speed  25.22 Mh/s    gpu/0 25.22  [A0+0:R0+0:F0] Time: 00:00

**Comment by DanMossa** [comment]
```
I've tried adding these to the end

--cl-local-work 256 --cl-global-work 98304

--cl-local-work 128 --cl-global-work 196608
```

I was originally getting around 4.00MH/s and now I'm getting 0.00MH/s

**Comment by AndreaLanfranchi** [comment]
@DanMossa please, if applicable, reopen new issue with complete description of your problem including environment, version of ethminer used, operating system and GPU.
