### ISSUE TITLE
Fatal GPU error: CUDA error in func dev::eth::CUDAMiner::search at line 484 unspecified launch failure

### ISSUE THREAD

**Issue by OriginalYshl** [ethereum-mining/ethminer#793]
Troubleshooting a crash with ethminer.exe on a GeForce 940MX 4GB

https://drive.google.com/file/d/1p4Uj3I2w7oS1Hs6eshjsrBng8k5u3x0p/view

It starts to run then errors out with:
Fatal GPU error: CUDA error in func dev::eth::CUDAMiner::search at line 484 unspecified launch failure

Using ethminer 0.14 dev2, dev1, or 0.13, same error.
Did install the most recent drivers, clean install.
OS: Windows 10 64-bit

etherminer.exe -U --list-devices gives:
Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce 940MX
   Compute version: 5.0
   cudaDeviceProp::totalGlobalMem: 4294967296
  Pci: 0000:01:00

Thanks in advance for any tips or advice!

**Comment by GlosVaper** [comment]
How much dedicated vRAM does the card have?
If it's less than 3Gb you're not going to be able to use it to mine, the DAG is too large.

**Comment by OriginalYshl** [comment]
The card has 4GB dedicated RAM.

**Comment by mrbrendanhamm** [comment]
I have heard the latest Windows 10 uses quite a bit of extra memory in Graphics cards after the latest updates. This causes 4Gb cards to not have enough for DAG file. I do not use WIndows on any of my miners, so this is all hearsay.

**Comment by OriginalYshl** [comment]
I've successfully used other cards (4 GB) in Windows, but this one is having the issue and I'm having trouble teasing out why. The screenshot shows that it even starts to mine, then seems to crash at the specific moment it receives a new job (and only one it's having some success working on a job).

**Comment by johnmorio** [comment]
Hi OriginalYshl ,

I found this thread while searching for a resolution to the same issue as yours. I was getting unspecified launch failure as well. I found another post here that offered a resolution to a different issue. However, in my case it was the resolution to my issue as well.

If you are overclocking try reducing your memory overclock. Reducing the memory overclock worked for my.

I ran an alternative popular miner using these same settings without issue. With ethminer they caused an issue until I dropped the memory by 50Mhz. I will say that ethminer is giving me a higher total hashrate across my cards and a more stable average hashrate. I am happy to drop the memory overclock by 50Mhz and still produce more than with the previous miner.

**Comment by DeadManWalkingTO** [comment]
Hi@all
Win10 use the card for desktop. Possibly eat your available memory. Check GPU status "Free memory" and feedback .
Thank you!

**Comment by OriginalYshl** [comment]
Hi there!

No overclocking going on. This is basically an out-of-the-box setup with the drivers updated to current, nothing more.

I'm getting a screenshot of the GPU-z stats on the card and will post them. I believe it's got plenty of free memory (it does start to run, see the screenshot in the initial post), but will verify and post.
