### ISSUE TITLE
Coinmine.pl fix

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ethereum-mining/ethminer#794]
https://github.com/ethereum-mining/ethminer/blob/47535a01ad4f1025bc667efa141233ad12207989/libpoolprotocols/stratum/EthStratumClient.cpp#L376

Maybe this small fix should be moved after line 382 ? Otherwise sShareTarget could never be ""

https://github.com/ethereum-mining/ethminer/blob/47535a01ad4f1025bc667efa141233ad12207989/libpoolprotocols/stratum/EthStratumClient.cpp#L382

**Comment by smurfy** [comment]
well the fix is more than 2 years old:

https://github.com/ethereum-mining/ethminer/commit/210af16294e5de39e19032f0fa84ebe0dd76e256

question is if its still needed

**Comment by AndreaLanfranchi** [comment]
Well ... some sort of sanity checks might be useful.
For instance I noticed that all four values of the params array should be 64 bytes.
This is an example from ethermine

```
{"id":6,"jsonrpc":"2.0","method":"mining.notify","params":[
	"3f454791fd08316428cf921b526de0ac426251fda6b6b5dc4c0e224a3299aa26",
	"3f454791fd08316428cf921b526de0ac426251fda6b6b5dc4c0e224a3299aa26",
	"a9b0e0c9aca72c07ba06b5bbdae8b8f69e61878301508473379bb4f71807d707",
	"0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba",
	false
	]
}
```
Do not know if possible tampering of this data may impact functionality of ethminer.
