### ISSUE TITLE
Possible convert to DLL?

### ISSUE THREAD

**Issue by Troodi** [ethereum-mining/ethminer#795]
Possible convert this code to DLL?

**Comment by DeadManWalkingTO** [comment]
Why?
Background mining?

**Comment by Troodi** [comment]
DeadManWalkingTO, no i want create windows app with zcash and eth miner.

**Comment by DeadManWalkingTO** [comment]
lol
I think it's easier to add a --background parameter.

**Comment by Troodi** [comment]
@DeadManWalkingTO, no, how then to use functions in fisrt program?

**Comment by bmatthewshea** [comment]
You can use a console exe (ethminer or whatever) as a non-shell background process (see "process()" ) under Visual Studio form. Meaning it can stay hidden/never appears for user. ref: https://msdn.microsoft.com/en-us/library/system.diagnostics.process(v=vs.110).aspx
