### ISSUE TITLE
cmake hangs on hunter boost build: upstream hunter bug

### ISSUE THREAD

**Issue by aphor** [ethereum-mining/ethminer#797]
I have a 12 core build machine, and hunter tries to build boost with a ridiculous `./b2 .. -j288 ..` which hangs in the "stage" step because b2 can't handle the parallelism.

https://github.com/ruslo/hunter/issues/668

**Comment by aphor** [comment]
hacking the broken ~/.hunter/.../cmake/modules/hunter_jobs_number.cmake file line 

https://github.com/ruslo/hunter/pull/658/files#diff-7b71f2b46fd59567a5caeae876dd34caR41

to 

    math(EXPR jobs_number "${l_cores}")

will make it work if you have a lot of cores and this bug breaks b2.

**Comment by chfast** [comment]
Thanks for referencing the Hunter bug.

**Comment by XhmikosR** [comment]
Is this still an issue with the latest master?

**Comment by XhmikosR** [comment]
@aphor : please make an upstream report on Hunter.

**Comment by aphor** [comment]
@XhmikosR it's an existing bug, referenced in the first comment. When you go to that bug, you can see a link to this issue, so they know there's downstream impact.

**Comment by XhmikosR** [comment]
Duh, you are right. I was looking at the link to the faulty PR.

How about you just use `HUNTER_JOBS_NUMBER` until then?

Also follow https://github.com/ruslo/hunter/issues/1352 too

**Comment by chfast** [comment]
This should be a workaround: https://github.com/ethereum-mining/ethminer/pull/989.

**Comment by aphor** [comment]
I have 12 cores, 24 virtual, so if I want either of those, I'm stuck hacking every time I build, so I'll wait for the upstream fix.

**Comment by chfast** [comment]
I believe it was fixed in Hunter
