### ISSUE TITLE
OpenCL error

### ISSUE THREAD

**Issue by d0n-miner1** [ethereum-mining/ethminer#800]
error loading dag.
for amd cards

  m  09:22:08|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  09:22:09|cl-0      Build info: fcl build 1 succeeded.
bcl build succeeded.

 cl  09:22:09|cl-0      Creating light cache buffer, size 39190336
 cl  09:22:09|cl-0      Creating DAG buffer, size 2508191872
  X  09:22:09|cl-0      Creating DAG buffer failed: clCreateBuffer: CL_INVALID_BUFFER_SIZE (-61)
  X  09:22:09|cl-0      OpenCL Error: clEnqueueWriteBuffer: CL_INVALID_MEM_OBJECT (-38)
  m  09:22:09|main      Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00

**Comment by RyanF109** [comment]
I fixed this issue by reinstalling AMD drivers with --opencl=legacy

**Comment by d0n-miner1** [comment]
thank you 
let me give it another go

**Comment by d0n-miner1** [comment]
did you install in linux?

or window cmd prompt with that "--opencl=legacy"

**Comment by RyanF109** [comment]
Linux.

**Comment by DeadManWalkingTO** [comment]
Reinstall AMD drivers with `--opencl=legacy` as @RyanF109 say.
Please feedback.
Thank you!

**Comment by melvyn2** [comment]
I have the same problem on Mac.
