### ISSUE TITLE
GPU order

### ISSUE THREAD

**Issue by mrbrendanhamm** [ethereum-mining/ethminer#801]
This is a strange phenomenon on build 0.13.0 in Linux whereby ethminer is not reporting the GPUs in the same order as nvidia-smi. This is a frankenstein build with a 1070, several 1060s and several 1050Tis and they get reported in descending order of card number (10x0). This doesn't pose any major problems, but makes it difficult to spot if any 1 card is not performing properly. Basically required me to overclock one at a time and look for hashrate change to identify.

Same build/operating system reports correctly with only the 1070s and 1060s in a different machine. The only difference I can consider is the former uses a pci-noaer (or nommsi) in the grub. Could these be due to lane sharing?

**Comment by StefanOberhumer** [comment]
Have you tried setting environment var
CUDA_DEVICE_ORDER=PCI_BUS_ID

This works for me (running under linux) and it seems to be working under also windows!
Refer to: #516

**Comment by DeadManWalkingTO** [comment]
Try
`CUDA_DEVICE_ORDER=PCI_BUS_ID`
as @StefanOberhumer  say.
Please feedback.
Thank you!

**Comment by momowchang** [comment]
Newbie question. How can I use CUDA_DEVICE_ORDER=PCI_BUS_ID on windows 10?

**Comment by StefanOberhumer** [comment]
Just googled "setting environment windows"  ( :-o ) and found https://www.computerhope.com/issues/ch000549.htm
Use the "System variables" so any process should have the setting

**Comment by momowchang** [comment]
@StefanOberhumer Thanks sir! The result was satisfying. :)
