### ISSUE TITLE
X server found. dri2 connection failed! [Fedora 27 AMD GPU]

### ISSUE THREAD

**Issue by gaxhaje** [ethereum-mining/ethminer#802]
I am getting the same error on an AMD card. I tried both pre-build package and I also build from source but I get the same error.

This issue is similar to: https://github.com/ethereum-mining/ethminer/issues/579

packages installed:
clinfo mesa-opencl beignet ocl-icd opencl-filesystem opencl-headers opencl-utils clpeak mesa-libGL mesa-libGL-devel xorg-x11-server-Xorg xor-x11-server-common

$ ethminer -G
m 16:14:11|ethminer| ethminer version 0.14.0.dev2
m 16:14:11|ethminer| Build: Linux/g++ / Release
X server found. dri2 connection failed!
DRM_IOCTL_I915_GEM_APERTURE failed: No such file or directory
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [13]
param: 4, val: 0
No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument

System:
OS: Fedora 27
Kernel: 4.15.4-300.fc27.x86_64
GPU: AMD HAWAII (DRM 2.50.0 / 4.15.4-300.fc27.x86_64, LLVM 5.0.1)

**Comment by SnowLeopard71** [comment]
i915 usually refers to onboard intel graphics.  
What does "lspci |grep VGA" output?  "ethminer --list-devices"?
Maybe you xorg.conf is incorrect/incomplete?

**Comment by gaxhaje** [comment]
Correct, I do have an Intel Built in graphics as well. 

$ lspci | grep VGA
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii XT / Grenada XT [Radeon R9 290X/390X] (rev 80)


$ ethminer --list-devices
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: No such file or directory
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [13]
param: 4, val: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: No such file or directory
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [13]
param: 4, val: 0
cl_get_gt_device(): error, unknown device: 0

Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[1] [0] AMD HAWAII (DRM 2.50.0 / 4.15.4-300.fc27.x86_64, LLVM 5.0.1)
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 6012954214
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

**Comment by SnowLeopard71** [comment]
Strange that the built-in gfx does not show up in lspci.
Try adding "--opencl-platform 1" to the ethminer command line.

**Comment by gaxhaje** [comment]
This is what I get when adding "--opencl-platform 1" flag

ethermine.sh

export GPU_FORCE_64BIT_PTR=0
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
ethminer --farm-recheck 200 -G --opencl-platform 1 -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -O <excluding address>.RigName


$ ./ethermine.sh 
  m  19:32:47|ethminer|  ethminer version 0.14.0.dev2
  m  19:32:47|ethminer|  Build: Linux/g++ / Release
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: No such file or directory
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [13]
param: 4, val: 0
  ℹ  19:32:47|ethminer|  Found suitable OpenCL device [ AMD HAWAII (DRM 2.50.0 / 4.15.4-300.fc27.x86_64, LLVM 5.0.1) ] with 8589934592  bytes of GPU memory
  m  19:32:47|ethminer|  not-connected
  ℹ  19:32:47|stratum |  Connected to us1.ethermine.org
  ℹ  19:32:47|stratum |  Spinning up miners...
 cl  19:32:47|cl-0    |  No work. Pause for 3 s.
  ℹ  19:32:47|stratum |  Subscribed to stratum server
  ℹ  19:32:47|stratum |  Authorized worker 0x9105719a80A357876152d758c62FC8372f1b7b70.mainrig_1
  ℹ  19:32:47|stratum |  Received new job #ddf9bcb8 from us1.ethermine.org
  ℹ  19:32:49|stratum |  Received new job #b1b3f87c from us1.ethermine.org
 cl  19:32:50|cl-0    |  New seed #a9b0e0c9…
 cl  19:32:52|cl-0    |  Platform: Clover
 cl  19:32:52|cl-0    |  Device:   AMD HAWAII (DRM 2.50.0 / 4.15.4-300.fc27.x86_64, LLVM 5.0.1)  / OpenCL 1.1 Mesa 17.3.5
 cl  19:32:52|cl-0    |  OpenCL 1.1  not supported, but platform Clover might work nevertheless. USE AT OWN RISK!
 cl  19:32:52|cl-0    |  OpenCL kernel: Stable kernel
 cl  19:32:52|cl-0    |  Build info: 
 cl  19:32:52|cl-0    |  Creating light cache buffer, size 39190336
 cl  19:32:52|cl-0    |  Creating DAG buffer, size 2508191872
 cl  19:32:52|cl-0    |  Loading kernels
 cl  19:32:52|cl-0    |  Writing light cache buffer
 cl  19:32:52|cl-0    |  Creating buffer for header.
 cl  19:32:52|cl-0    |  Creating mining buffer
radeon: Failed to allocate a buffer:
radeon:    size      : 2508193792 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 4
radeon:    flags     : 4
radeon: Failed to allocate a buffer:
radeon:    size      : 2508193792 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 4
radeon:    flags     : 4
  ✘  19:32:52|cl-0    |  OpenCL init failed: clEnqueueNDRangeKernel: CL_OUT_OF_RESOURCES (-5)
  m  19:32:52|ethminer|  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  19:32:57|ethminer|  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  19:33:02|ethminer|  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  19:33:07|ethminer|  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
^C  ℹ  19:33:12|ethminer|  Disconnected from us1.ethermine.org
  ℹ  19:33:12|ethminer|  Shutting down miners...

**Comment by SnowLeopard71** [comment]
That's an improvement anyway...  
Maybe someone else knows about the "OpenCL 1.1 not supported, but platform Clover might work nevertheless." error?

**Comment by gaxhaje** [comment]
Yes it is. There's also this error towards the bottom.

✘ 19:32:52|cl-0 | OpenCL init failed: clEnqueueNDRangeKernel: CL_OUT_OF_RESOURCES (-5)

**Comment by DeadManWalkingTO** [comment]
Try
`sudo apt-get install ocl-icd-opencl-dev`
then reboot and run Ethminer again.

If the problem din't solve try reinstall the packages.
Please feedback.
Thank you!

**Comment by gaxhaje** [comment]
I'm on Fedora 27. 
I installed `ocl-icd-devel` restarted and reinstalled without success. The output is the same as above.

List of all installed packages:

$ sudo dnf list clinfo mesa* beignet ocl* opencl* xorg-x11-server*
Last metadata expiration check: 0:05:33 ago on Tue 27 Feb 2018 11:32:08 AM CST.
Installed Packages
beignet.x86_64                                                                                           1.3.2-2.fc27                                                                                 @updates     
clinfo.x86_64                                                                                            2.2.17.10.25-1.fc27                                                                          @updates     
mesa-dri-drivers.i686                                                                                    17.3.5-1.fc27                                                                                @@commandline
mesa-dri-drivers.x86_64                                                                                  17.3.5-1.fc27                                                                                @@commandline
mesa-filesystem.i686                                                                                     17.3.5-1.fc27                                                                                @@commandline
mesa-filesystem.x86_64                                                                                   17.3.5-1.fc27                                                                                @@commandline
mesa-libEGL.i686                                                                                         17.3.5-1.fc27                                                                                @@commandline
mesa-libEGL.x86_64                                                                                       17.3.5-1.fc27                                                                                @@commandline
mesa-libGL.i686                                                                                          17.3.5-1.fc27                                                                                @updates     
mesa-libGL.x86_64                                                                                        17.3.5-1.fc27                                                                                @updates     
mesa-libGL-devel.x86_64                                                                                  17.3.5-1.fc27                                                                                @updates     
mesa-libGLU.x86_64                                                                                       9.0.0-13.fc27                                                                                @@commandline
mesa-libOSMesa.x86_64                                                                                    17.3.5-1.fc27                                                                                @@commandline
mesa-libOpenCL.x86_64                                                                                    17.3.5-1.fc27                                                                                @@commandline
mesa-libOpenCL-devel.x86_64                                                                              17.3.5-1.fc27                                                                                @@commandline
mesa-libd3d.x86_64                                                                                       17.3.5-1.fc27                                                                                @@commandline
mesa-libgbm.i686                                                                                         17.3.5-1.fc27                                                                                @@commandline
mesa-libgbm.x86_64                                                                                       17.3.5-1.fc27                                                                                @@commandline
mesa-libglapi.i686                                                                                       17.3.5-1.fc27                                                                                @@commandline
mesa-libglapi.x86_64                                                                                     17.3.5-1.fc27                                                                                @@commandline
mesa-libwayland-egl.x86_64                                                                               17.3.5-1.fc27                                                                                @@commandline
mesa-libxatracker.x86_64                                                                                 17.3.5-1.fc27                                                                                @@commandline
mesa-libxatracker-devel.x86_64                                                                           17.3.5-1.fc27                                                                                @@commandline
mesa-vdpau-drivers.x86_64                                                                                17.3.5-1.fc27                                                                                @@commandline
mesa-vulkan-drivers.x86_64                                                                               17.3.5-1.fc27                                                                                @updates     
ocl-icd.x86_64                                                                                           2.2.11-4.fc27                                                                                @fedora      
ocl-icd-devel.x86_64                                                                                     2.2.11-4.fc27                                                                                @fedora      
opencl-filesystem.noarch                                                                                 1.0-6.fc27                                                                                   @fedora      
opencl-headers.noarch                                                                                    2.1-3.fc27                                                                                   @fedora      
opencl-utils.x86_64                                                                                      1-5.svn16.fc27                                                                               @fedora      
opencl-utils-devel.x86_64                                                                                1-5.svn16.fc27                                                                               @fedora      
xorg-x11-server-Xorg.x86_64                                                                              1.19.6-5.fc27                                                                                @updates     
xorg-x11-server-Xwayland.x86_64                                                                          1.19.6-5.fc27                                                                                @@commandline
xorg-x11-server-common.x86_64                                                                            1.19.6-5.fc27                                                                                @@commandline
xorg-x11-server-utils.x86_64                                                                             7.7-23.fc27                                                                                  @@commandline

**Comment by gaxhaje** [comment]
so I managed to get rid of the error about `radeon` module. I passed a flag to `grub` `radeon.cik_support=0 amdgpu.cik_suppor=1` from this post https://ask.fedoraproject.org/en/question/116644/amdgpu-or-radeon-on-fedora-27/

I also install `xorg-x11-drv-amdgpu.x86_64` although i'm not sure if this is required `mesa` drivers are installed.

I am still seeing `OpenCL 1.1  not supported, but platform Clover might work nevertheless. USE AT OWN RISK!`. I don't know if this will prevent the miner from working.

I am getting the following output now. Shouldn't I see speeds higher then `0.00 Mh/s`?. 

So my card freezes at 100% allocation so I dropped to test but even at 100% I still see speods of `0.00Mh/s`. 

ethminer.sh:
```
# Not sure if all these flags are required since I have an AMD R9 390 with 8G Memory. 

export GPU_FORCE_64BIT_PTR=0
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=10
export GPU_SINGLE_ALLOC_PERCENT=10
ethminer --farm-recheck 200 -G --opencl-platform 1 -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -O <address omitted> 
```

$ ./ethermine.sh 
  m  13:24:40|ethminer|  ethminer version 0.14.0.dev2
  m  13:24:40|ethminer|  Build: Linux/g++ / Release
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
  ℹ  13:24:40|ethminer|  Found suitable OpenCL device [ AMD Radeon (TM) R9 390 Series (HAWAII / DRM 3.23.0 / 4.15.4-300.fc27.x86_64, LLVM 5.0.1) ] with 8588652544  bytes of GPU memory
  m  13:24:40|ethminer|  not-connected
  ℹ  13:24:40|stratum |  Connected to us1.ethermine.org
  ℹ  13:24:40|stratum |  Spinning up miners...
 cl  13:24:40|cl-0    |  No work. Pause for 3 s.
  ℹ  13:24:40|stratum |  Subscribed to stratum server
  ℹ  13:24:40|stratum |  Authorized worker 0x9105719a80A357876152d758c62FC8372f1b7b70.mainrig_1
  ℹ  13:24:40|stratum |  Received new job #a2ebc1bd from us1.ethermine.org
 cl  13:24:43|cl-0    |  New seed #1261dfe1…
 cl  13:24:45|cl-0    |  Platform: Clover
 cl  13:24:45|cl-0    |  Device:   AMD Radeon (TM) R9 390 Series (HAWAII / DRM 3.23.0 / 4.15.4-300.fc27.x86_64, LLVM 5.0.1)  / OpenCL 1.1 Mesa 17.3.5
 cl  13:24:45|cl-0    |  OpenCL 1.1  not supported, but platform Clover might work nevertheless. USE AT OWN RISK!
 cl  13:24:45|cl-0    |  OpenCL kernel: Stable kernel
 `m  13:24:45|ethminer|  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00`
 cl  13:24:45|cl-0    |  Build info: 
 cl  13:24:45|cl-0    |  Creating light cache buffer, size 39320768
 cl  13:24:45|cl-0    |  Creating DAG buffer, size 2516582272
 cl  13:24:45|cl-0    |  Loading kernels
 cl  13:24:45|cl-0    |  Writing light cache buffer
 cl  13:24:45|cl-0    |  Creating buffer for header.
 cl  13:24:45|cl-0    |  Creating mining buffer
  `m  13:24:50|ethminer|  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00`

**Comment by SnowLeopard71** [comment]
I think you need to install the amdgpu and amdgpu-pro drivers in order to get OpenCL 1.2 working with your R390.

**Comment by gaxhaje** [comment]
There are no amdgpu-pro packages for F27 so I tried the REHL7 drivers from https://support.amd.com/en-us/kb-articles/Pages/Installation-Instructions-for-amdgpu-Graphics-Stacks.aspx but it completly breaks the system. I cannot boot into the GUI and even the miner breaks. I'm not sure if it conflicts with prior packages but I did not see any installation errors.

Anyway, I'm giving up on this once more. It seams pointless. I build this system last year and have been trying to get ethminer working ever since with no luck. I guess I'll invest in another card down the road but I wanted to try with the 390 first.

**Comment by SnowLeopard71** [comment]
The problem is not the video card, it's getting `amdgpu` driver working on Fedora.
Why not try Ubuntu or another distro that is not Fedora?

**Comment by gaxhaje** [comment]
I enjoy using Fedora over Ubuntu. Also, I use this desktop for other work
as well. I was only trying to get etheminer going for fun.
I plan on building a dedicated mining rig (Ubuntu) soon but I wanted to see
how it would work with my 390 first.

**Comment by gaxhaje** [comment]
So I tried Ubuntu 16.04 and I now have the exact error as in https://github.com/ethereum-mining/ethminer/issues/590
