### ISSUE TITLE
cmake .. fails:  Cannot find GL/gl.h

### ISSUE THREAD

**Issue by tkalfaoglu** [ethereum-mining/ethminer#806]
[ 25%] Building C object CMakeFiles/OpenCL.dir/icd_linux.c.o
[ 75%] Building C object CMakeFiles/OpenCL.dir/icd_dispatch.c.o
[ 75%] Building C object CMakeFiles/OpenCL.dir/icd.c.o
In file included from /home/turgut/.hunter/_Base/59b2b88/95f6d02/c20b399/Build/OpenCL/Source/icd_dispatch.c:38:0:
/home/turgut/.hunter/_Base/59b2b88/95f6d02/c20b399/Build/OpenCL/Source/icd_dispatch.h:66:10: fatal error: GL/gl.h: No such file or directory
 #include <GL/gl.h>
          ^~~~~~~~~
compilation terminated.
gmake[5]: *** [CMakeFiles/OpenCL.dir/build.make:87: CMakeFiles/OpenCL.dir/icd_dispatch.c.o] Error 1
gmake[5]: *** Waiting for unfinished jobs....
In file included from /home/turgut/.hunter/_Base/59b2b88/95f6d02/c20b399/Build/OpenCL/Source/icd.c:39:0:
/home/turgut/.hunter/_Base/59b2b88/95f6d02/c20b399/Build/OpenCL/Source/icd_dispatch.h:66:10: fatal error: GL/gl.h: No such file or directory
 #include <GL/gl.h>
          ^~~~~~~~~
compilation terminated.
gmake[5]: *** [CMakeFiles/OpenCL.dir/build.make:63: CMakeFiles/OpenCL.dir/icd.c.o] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:68: CMakeFiles/OpenCL.dir/all] Error 2
gmake[3]: *** [Makefile:130: all] Error 2
gmake[2]: *** [CMakeFiles/OpenCL-Release.dir/build.make:115: OpenCL-Release-prefix/src/OpenCL-Release-stamp/OpenCL-Release-build] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/OpenCL-Release.dir/all] Error 2
gmake: *** [Makefile:84: all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: /home/turgut/.hunter/_Base/59b2b88/95f6d02/c20b399/Build/OpenCL
[hunter ** FATAL ERROR **] [Directory:/home/turgut/.hunter/_Base/Download/Hunter/0.19.213/59b2b88/Unpacked/cmake/projects/OpenCL]

**Comment by tkalfaoglu** [comment]
Which one is it failing to find? And maybe it should fail more gracefully? 

$ locate gl.h
/home/turgut/.hunter/_Base/59b2b88/8f26bb3/c20b399/Install/include/CL/cl_egl.h
/home/turgut/.hunter/_Base/59b2b88/8f26bb3/c20b399/Install/include/CL/cl_gl.h
/home/turgut/.hunter/_Base/59b2b88/8f26bb3/c20b399/Install/include/boost/compute/interop/opengl.hpp
/home/turgut/.hunter/_Base/59b2b88/8f26bb3/c20b399/Install/include/boost/compute/interop/opengl/cl_gl.hpp
/home/turgut/.hunter/_Base/59b2b88/8f26bb3/c20b399/Install/include/boost/compute/interop/opengl/gl.hpp
/home/turgut/.hunter/_Base/59b2b88/95f6d02/c20b399/Build/OpenCL/Source/include/CL/cl_egl.h
/home/turgut/.hunter/_Base/59b2b88/95f6d02/c20b399/Build/OpenCL/Source/include/CL/cl_gl.h
/home/turgut/.hunter/_Base/59b2b88/95f6d02/c20b399/Install/include/boost/compute/interop/opengl.hpp
/home/turgut/.hunter/_Base/59b2b88/95f6d02/c20b399/Install/include/boost/compute/interop/opengl/cl_gl.hpp
/home/turgut/.hunter/_Base/59b2b88/95f6d02/c20b399/Install/include/boost/compute/interop/opengl/gl.hpp
/home/turgut/.hunter/_Base/Cellar/01f8dbc72ce089500574454d913e08424edc1286/01f8dbc/raw/include/CL/cl_egl.h
/home/turgut/.hunter/_Base/Cellar/01f8dbc72ce089500574454d913e08424edc1286/01f8dbc/raw/include/CL/cl_gl.h
/home/turgut/.hunter/_Base/Cellar/092e90e022b75b9f85bf6c411f52504856104c94/092e90e/raw/include/boost/compute/interop/opengl.hpp
/home/turgut/.hunter/_Base/Cellar/092e90e022b75b9f85bf6c411f52504856104c94/092e90e/raw/include/boost/compute/interop/opengl/cl_gl.hpp
/home/turgut/.hunter/_Base/Cellar/092e90e022b75b9f85bf6c411f52504856104c94/092e90e/raw/include/boost/compute/interop/opengl/gl.hpp
/home/turgut/.hunter/_Base/Cellar/bb02cfd7aca1be193f857a09f9a07eb97de61c6c/bb02cfd/raw/include/boost/compute/interop/opengl.hpp
/home/turgut/.hunter/_Base/Cellar/bb02cfd7aca1be193f857a09f9a07eb97de61c6c/bb02cfd/raw/include/boost/compute/interop/opengl/cl_gl.hpp
/home/turgut/.hunter/_Base/Cellar/bb02cfd7aca1be193f857a09f9a07eb97de61c6c/bb02cfd/raw/include/boost/compute/interop/opengl/gl.hpp
/opt/cuda/extras/CUPTI/include/GL/gl.h
/opt/cuda/include/CL/cl_egl.h
/opt/cuda/include/CL/cl_gl.h
/opt/cuda/samples/common/inc/helper_cuda_gl.h
/opt/cuda/samples/common/inc/helper_gl.h
/opt/cuda/samples/common/inc/paramgl.h
/opt/cuda/samples/common/inc/rendercheck_gl.h
/opt/cuda/samples/common/inc/dynlink/cuda_drvapi_dynlink_gl.h
/usr/include/wayland-egl.h
/usr/include/boost/compute/interop/opengl.hpp
/usr/include/boost/compute/interop/opengl/cl_gl.hpp
/usr/include/boost/compute/interop/opengl/gl.hpp
/usr/include/epoxy/egl.h
/usr/include/epoxy/gl.h

**Comment by nachitox** [comment]
https://www.google.com.ar/search?q=GL%2Fgl.h%3A+No+such+file+or+directory&client=ms-unknown&sourceid=chrome-mobile&ie=UTF-8

**Comment by DeadManWalkingTO** [comment]
Try
```
sudo apt install mesa-common-dev
sudo apt install libglu1-mesa-dev freeglut3-dev
```
and the problem solved!

If all run ok close the issue.
Thank you!

**Comment by chfast** [comment]
You have to install `mesa-common-dev`: https://docs.hunter.sh/en/latest/packages/pkg/OpenCL.html#pitfalls.
