### ISSUE TITLE
NVIDIA 970 Performance under Windows

### ISSUE THREAD

**Issue by amir-hadi** [ethereum-mining/ethminer#810]
Hi guys,

I want to run ethminer under Windows 7. I tried NVIDIA driver versions 350.12 and 390.xx. With the newest drivers my GPU doesn't produce more then 5,5 MH/s.

Any ideas why this is so?

**Comment by DeadManWalkingTO** [comment]
Have you try Linux?

**Comment by amir-hadi** [comment]
No I didn’t. I personally use Linux for mining, but these machines are not completely under my control, they are on a customers premises, so it must run using Windows.

**Comment by GlosVaper** [comment]
Does the customer know?

**Comment by amir-hadi** [comment]
Of course the customer does know.

**Comment by AndreaLanfranchi** [comment]
Is this the only GPU on system ?

**Comment by amir-hadi** [comment]
Yes, it’s a gaming machine.

**Comment by AndreaLanfranchi** [comment]
And eventually the customer plays game while trying to mine ?

**Comment by amir-hadi** [comment]
No of course not, it’s a clean windows setup with visual c++
redistributable and NVIDIA drivers installed. In the net I read about doing
18 MH/s, but all machines I tried with a 9xx series card never made more
than 5 MH/s.
Andrea Lanfranchi <notifications@github.com> schrieb am Di. 27. Feb. 2018
um 17:56:

**Comment by AndreaLanfranchi** [comment]
Try this 
https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW

**Comment by amir-hadi** [comment]
Thanks for sharing. I will give that a shot. The customer even installed Windows 7, because the docs say that with WDDM 2.1 there is an issue with 9xx series GPUs and Windows 10. The docs also said that This miner should run fine with NVIDIA 970 + Windows 7.

Anyone has a 970 and Windows 7 with high hashrates?

**Comment by GlosVaper** [comment]
Have you turned off the P2 state?

**Comment by DeadManWalkingTO** [comment]
1. Try Update Drivers.
Download and install the latests.

2. Try Update Ethminer.
Download (or beter build) the latest.

3. Try use -U for CUDA devices.
CUDA Hardware Test Launch Command:
```
ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.issue810
```

4. Try to change P2 State and Power managment mode.
You can use [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW).
For the best mining hashrate choose from sector "5 - Common":
    - CUDA - Force P2 State (Set to "Off")
    - Power managment mode (Set to "Prefer maximum performance")

5. Try Tweak Win10.
You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) (#695).

6. Try Optimize/Overclock GPUs. 
You can use [MSI Afterburner](https://www.msi.com/page/afterburner) for GPU OverClock/Optimize. 

7. Try use a WatchDog
You can use [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) (#735).

Please feedback.
Thank you!

**Comment by amir-hadi** [comment]
@DeadManWalkingTO @GlosVaper I will try these ASAP and give you feedback soon. Thanks for trying to help!

**Comment by amir-hadi** [comment]
@DeadManWalkingTO Still no luck.

Here are the detailed configurations:
* NVIDIA Driver version 390.77
* Windows 7, 64 bit
* Force P2 State == off
* Power management mode == Prefer maximum performance
* Ethminer newest version

but still 5,44 MH/s.

**Comment by GlosVaper** [comment]
Try these switches and see what you get back

-U --cuda-parallel-hash 4 --cuda-grid-size 8192 --cuda-block-size 256 --cuda-schedule auto -S

**Comment by GlosVaper** [comment]
If they're staying that low then there may be a hardware/cooling issue

**Comment by StealthReign** [comment]
Did you remember to change the "optimize performance for compute" setting in your nvidia control panel?

**Comment by bmatthewshea** [comment]
Don't have a 970, but on my GTX 760 under linux/windows I mine other alt-coins besides ETH/ETC.
I get around 16-17MH on most other ethash coins. On ETH/ETC I get about 6MH.
May want to see if you get a different rate depending on coin and mine it?

**Comment by gordan-bobic** [comment]
9xx series cards aren't subject to running compute jobs in P2 state, so P state is not the problem.

5-6MH/s on a 970 on Windows sounds about right. A fully tuned up 980Ti gets about 10-11MH/s. With some OC-ing on Linux you might be able to get 7-8 our of it.

You have no hope of seeing 18MH/s on a 9xx series card with the real DAG (even if you do see it on a benchmark with an empty DAG).

**Comment by kozmic83** [comment]
Here is how I make my 970's run at ~20Mh on other ethash coins (haven't run them on ETH, so ymmv...) in Windows 10.

NVIDIA driver ver: 391.01

In the NVIDIA Control Panel set the following:
- Under "Adjust image settings with preview", select "use my preference emphasizing:", then move the slider to left over to "performance"
- Under "Manage 3D Settings", set these params:
1) "CUDA - GPUs" to "All"
2) "DSR - Factors" to "2.00x"
3) "DSR - Smoothness" to "33%"
4) "Optimise for Computer Performance" to "On"
5) "Power management mode" to "Prefer maximum performance"
- Under "Configure Surround, PhysX",I also set the PhysX locked to the CPU, but not sure this makes any difference

Then I use NVIDIA nvsmi to set the max clocks on the 970's (need to do this for 9xx cards). You may need to find the max supported clocks for your cards, but I believe most 970's should close. I search for the 970's installed (because I have other 10-series running in this same rig) and apply nvsmi settings only to the 970s.

Here's my start batch file:
****************************************************
@echo off

for /f "tokens=2,5 delims=: " %%f in ('"\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe" -L') do @if %%g==970 "\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe" -i %%f -ac 3505,1506
pause

ethminer -F http://us.ubiqpool.io:8888/0x501177a69013d7777DCc2FDAe740814360478ECB/miner1 -U --farm-recheck 200
****************************************************

Obviously you'll need to sub your own pool/account/rigname :)


Hope this helps!

**Comment by kozmic83** [comment]
Just a quick update - I pointed a rig that is running a few 970's at ethermine.org and with the above settings. While I get stable 20~21Mh on music/ubiq/etc (both pool and solo), I am only seeing 9.5~10.5Mh on eth running against ethermine.org. The gtx10-series cards are showing consistent numbers between eth and the others, but the 970's are def slower on eth that the other coins.

**Comment by AndreaLanfranchi** [comment]
Do you refer to values you read on your miner or avg hashrate reported by ethermine.org ?

**Comment by kozmic83** [comment]
The eth numbers are just what is being reported by ethminer...not gonna run this rig against ethermine.org for long enough to see what the ave report by the pool would be... I just wanted to post as a point of reference / followup to my previous reply.

(but yes, for the 970's, I see ~20Mh ave reported by music/ubiq pools - and by gmc/gubiq forks while mining solo)

**Comment by AndreaLanfranchi** [comment]
@kozmic83 
This is strange.
There are a lot of references about users complaining about 970s which progressively gets slower and slower as the DAG size increases.

On your situation values make sense if compared music and ubiq (which are respectively at epoch 70 and 13) which have smaller DAG sizes.

But you say you get stable 20-21 on ETC also : this makes no sense as ETC is 10 epochs ahead of ETH so it has a larger dag.

**Comment by kozmic83** [comment]
lol... I had to go back and re-read my post... sincere apologies!

When I "20-21Mh on music/ubiq/etc", the "etc" was meant as "etcetera". I need to be more careful. :)

**Comment by bmatthewshea** [comment]
Yes every ethash coin I know of (besides ETC/ETH obviously) should be significantly faster. I don't see any of them much past 1m block height. 
So: EXP, MUSIC, PIRL, ELLA, UBQ, ETP -  If you know of any others tell me. LOL..
Lately, I've been mining MUSIC with 'older' cards and selling it.
