### ISSUE TITLE
ethminer  show speed is 0Mh/s, and  -U -M parameter work well. who can help to analysis，thanks

### ISSUE THREAD

**Issue by hmcmmmmm** [ethereum-mining/ethminer#814]
1. With ./ethminer -U -M show:

 cu  16:33:01|cuda-0  |  Generating DAG for GPU # 0  with dagSize: 1073739904  gridSize: 8192
 cu  16:33:01|cuda-1  |  Generating DAG for GPU # 1  with dagSize: 1073739904  gridSize: 8192
Trial 1... 
191317657
Trial 2... 
191126997
Trial 3... 
190917198
Trial 4... 
191041210
Trial 5... 
191060325
min/mean/max: 190917198/191092677/191317657 H/s
inner mean: 191076177 H/s

2 My command under ubuntu16,04:
/ethminer -RH -G -S asia1.ethpool.org:3333 -FS us1.ethpool.org:3333 -O 859bd61abe5acfb5db638d34a35db1ac1c88cda2.myrigoo  --farm-recheck 200
m  16:36:03|ethminer|  ethminer version 0.14.0.dev2
  m  16:36:03|ethminer|  Build: Linux/g++ / Release
 cu  16:36:05|ethminer|  Using grid size 8192 , block size 128
  m  16:36:05|ethminer|  not-connected
  \u2139  16:36:07|stratum |  Connected to asia1.ethpool.org
  \u2139  16:36:07|stratum |  Spinning up miners...
  \u2139  16:36:07|cuda-0  |  No work. Pause for 3 s.
  \u2139  16:36:07|cuda-1  |  No work. Pause for 3 s.
  \u2139  16:36:07|stratum |  Subscribed to stratum server
  \u2139  16:36:10|cuda-0  |  No work. Pause for 3 s.
  \u2139  16:36:10|cuda-1  |  No work. Pause for 3 s.
  m  16:36:10|ethminer|  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  \u2139  16:36:13|cuda-0  |  No work. Pause for 3 s.
  \u2139  16:36:13|cuda-1  |  No work. Pause for 3 s.
  m  16:36:15|ethminer|  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  \u2139  16:36:16|cuda-0  |  No work. Pause for 3 s.
  \u2139  16:36:16|cuda-1  |  No work. Pause for 3 s.
  \u2139  16:36:19|cuda-0  |  No work. Pause for 3 s.
  \u2139  16:36:19|cuda-1  |  No work. Pause for 3 s.

If my command have some problem or other ?

**Comment by hmcmmmmm** [comment]
if i use another pool with command, it can successful. Below ethminer tool was build from cpp-ethereum. The version is 1.2.9.

### ethminer -G -t 4 -F http://ethereumpool.co/?miner=176@0x859bd61abe5acfb5db638d34a35db1ac1c88cda2

**Comment by hmcmmmmm** [comment]
Seemly , i got the ethminer that not generate DAG file auto, but i don't how to generate it.

**Comment by hmcmmmmm** [comment]
I use package:  ethminer-0.14.0.dev2-Linux.tar.gz

**Comment by AndreaLanfranchi** [comment]
DAG generation is triggered automatically on first job received but it seems like your instance does not receive any job.

I suspect you have missed an "0x" in front of your address.
Correct as follows and retry. (also remove farm-recheck as in stratum mode has no meaning)

`/ethminer -RH -G -S asia1.ethpool.org:3333 -FS us1.ethpool.org:3333 -O 0x859bd61abe5acfb5db638d34a35db1ac1c88cda2.myrigoo`

**Comment by DeadManWalkingTO** [comment]
Follow @AndreaLanfranchi 's instructions.

I think this issue can be closed.

**Comment by hmcmmmmm** [comment]
Thanks @AndreaLanfranchi
i try the instruction,but also got same error result. Could help other issue caused?

root@fw/bin# ./ethminer -RH -G -S asia1.ethpool.org:3333 -FS us1.ethpool.org:3333 -O 0x859bd61abe5acfb5db638d34a35db1ac1c88cda2.myrigoo
  m  09:47:53|ethminer|  ethminer version 0.14.0.dev2
  m  09:47:53|ethminer|  Build: Linux/g++ / Release
  \u2139  09:47:53|ethminer|  Found suitable OpenCL device [ Tesla V100-PCIE-16GB ] with 16936927232  bytes of GPU memory
  m  09:47:53|ethminer|  not-connected
  \u2139  09:47:54|stratum |  Connected to asia1.ethpool.org
  \u2139  09:47:54|stratum |  Spinning up miners...
 cl  09:47:54|cl-0    |  No work. Pause for 3 s.
 cl  09:47:54|cl-1    |  No work. Pause for 3 s.
  \u2139  09:47:54|stratum |  Subscribed to stratum server
 cl  09:47:57|cl-1    |  No work. Pause for 3 s.
 cl  09:47:57|cl-0    |  No work. Pause for 3 s.
  m  09:47:58|ethminer|  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  09:48:00|cl-1

**Comment by DeadManWalkingTO** [comment]
CUDA Hardware Test Launch Command:

```
ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.issue814
```

Try with latest Ethminer version and feedback please.
Thank you!

**Comment by hmcmmmmm** [comment]
change to this instruction:  ./ethminer -RH -G -S asia1.ethermine.org:14444 -FS us1.ethermine.org:14444 -O 0x859bd61abe5acfb5db638d34a35db1ac1c88cda2.test
Maybe the port caused the problem. Thanks

**Comment by DeadManWalkingTO** [comment]
I think the solution has been found.
