### ISSUE TITLE
Can't make the latest pull

### ISSUE THREAD

**Issue by unknown2this** [ethereum-mining/ethminer#816]
error message when I try to make

 CMake Error at CMakeLists.txt:3 (include):
  include could not find load file:

    cmake/cable/bootstrap.cmake

CMake Error at CMakeLists.txt:5 (include):
  include could not find load file:

    CableBuildInfo

CMake Error at CMakeLists.txt:6 (include):
  include could not find load file:

    CableBuildType

CMake Error at CMakeLists.txt:7 (include):
  include could not find load file:

    CableToolchains

CMake Error at CMakeLists.txt:9 (cable_configure_toolchain):
  Unknown CMake command "cable_configure_toolchain".

**Comment by unknown2this** [comment]
Cable folder is empty

**Comment by smurfy** [comment]
its a git submodule.  do a submodule update and it works again

**Comment by unknown2this** [comment]
Thank you. I was able to build it after the submodule update

**Comment by piotr-dobrogost** [comment]
From https://stackoverflow.com/a/1032653/95735:
> Note: If that's the first time you checkout a repo you need to use --init first:
`git submodule update --init --recursive`
