### ISSUE TITLE
Difference between this and genoil?

### ISSUE THREAD

**Issue by BIG1** [ethereum-mining/ethminer#819]
Whats the difference between this and genoil https://github.com/Genoil/cpp-ethereum ?

Can we OC and undervolt with this miner?

**Comment by smurfy** [comment]
genoil is no longer maintained and rarely gets any updates

**Comment by AndreaLanfranchi** [comment]
> Can we OC and undervolt with this miner?

Overclocking and undervolting or power-limiting is out-of-scope for the miner which works with wichever setting you have imposed by driver or GPUs manufacturer utilities.
