### ISSUE TITLE
Target # always all zeros.

### ISSUE THREAD

**Issue by 353kilo** [ethereum-mining/ethminer#82]
Was having same issue with ethminer 10.0.

 upgrading to version 11 to see if any changes happen

Same issue, everything works perfectly fine, I just want to clarify if something is actually wrong with the target # always being all 0's

In other user's logs I have yet to see someone with target #000000000000 on all work packages.

Thanks in advance for any help.

I have build logs if necessary as well.

Also Geth seems to be functioning properly.
starting geth using : 
geth --rpc --rpcaddr "localhost" --rpcport8545 --cache 1024

>ethminer.exe -G
Found suitable OpenCL device [Tahiti] with 3221225472 bytes of GPU memory
  m  10:16:13|main  Getting work package...
  m  10:16:13|main  Got work package: #9adae852
  i  10:16:13|openclminer0  set work; seed: #2228076c, target: #000000000000
  i  10:16:13|openclminer0  Initialising miner...
  m  10:16:14|main  Mining on PoWhash #9adae852 : 0.00MH/s [A0+0:R0+0:F0]
  m  10:16:14|main  Mining on PoWhash #9adae852 : 0.00MH/s [A0+0:R0+0:F0]
  m  10:16:15|main  Mining on PoWhash #9adae852 : 0.00MH/s [A0+0:R0+0:F0]
  m  10:16:15|main  Got work package: #a954a3e4
Using platform: AMD Accelerated Parallel Processing
Using device: Tahiti(OpenCL 1.2 AMD-APP (2348.3))
Printing program log

Creating cache buffer
Creating DAG buffer
Loading kernels
Writing cache buffer
Creating buffer for header.
Creating mining buffer 0
Creating mining buffer 1
Generating DAG data
OPENCL#0: 0%
OPENCL#0: 1%
OPENCL#0: 2%
OPENCL#0: 2%
OPENCL#0: 3%
OPENCL#0: 4%
OPENCL#0: 5%
OPENCL#0: 5%
OPENCL#0: 6%
OPENCL#0: 7%
OPENCL#0: 8%
OPENCL#0: 8%
OPENCL#0: 9%
OPENCL#0: 10%
OPENCL#0: 11%
OPENCL#0: 12%
OPENCL#0: 12%
OPENCL#0: 13%
OPENCL#0: 14%
OPENCL#0: 15%
OPENCL#0: 15%
OPENCL#0: 16%
OPENCL#0: 17%
OPENCL#0: 18%
OPENCL#0: 18%
OPENCL#0: 19%
OPENCL#0: 20%
OPENCL#0: 21%
OPENCL#0: 22%
OPENCL#0: 22%
OPENCL#0: 23%
OPENCL#0: 24%
OPENCL#0: 25%
OPENCL#0: 25%
OPENCL#0: 26%
OPENCL#0: 27%
OPENCL#0: 28%
OPENCL#0: 28%
OPENCL#0: 29%
OPENCL#0: 30%
OPENCL#0: 31%
OPENCL#0: 32%
OPENCL#0: 32%
OPENCL#0: 33%
OPENCL#0: 34%
OPENCL#0: 35%
OPENCL#0: 35%
OPENCL#0: 36%
OPENCL#0: 37%
OPENCL#0: 38%
OPENCL#0: 38%
OPENCL#0: 39%
OPENCL#0: 40%
OPENCL#0: 41%
OPENCL#0: 42%
OPENCL#0: 42%
OPENCL#0: 43%
OPENCL#0: 44%
OPENCL#0: 45%
OPENCL#0: 45%
OPENCL#0: 46%
OPENCL#0: 47%
OPENCL#0: 48%
OPENCL#0: 48%
OPENCL#0: 49%
OPENCL#0: 50%
OPENCL#0: 51%
OPENCL#0: 52%
OPENCL#0: 52%
OPENCL#0: 53%
OPENCL#0: 54%
OPENCL#0: 55%
OPENCL#0: 55%
OPENCL#0: 56%
OPENCL#0: 57%
OPENCL#0: 58%
OPENCL#0: 58%
OPENCL#0: 59%
OPENCL#0: 60%
OPENCL#0: 61%
OPENCL#0: 62%
OPENCL#0: 62%
OPENCL#0: 63%
OPENCL#0: 64%
OPENCL#0: 65%
OPENCL#0: 65%
OPENCL#0: 66%
OPENCL#0: 67%
OPENCL#0: 68%
OPENCL#0: 68%
OPENCL#0: 69%
OPENCL#0: 70%
OPENCL#0: 71%
OPENCL#0: 72%
OPENCL#0: 72%
OPENCL#0: 73%
OPENCL#0: 74%
OPENCL#0: 75%
OPENCL#0: 75%
OPENCL#0: 76%
OPENCL#0: 77%
OPENCL#0: 78%
OPENCL#0: 78%
OPENCL#0: 79%
OPENCL#0: 80%
OPENCL#0: 81%
OPENCL#0: 82%
OPENCL#0: 82%
OPENCL#0: 83%
OPENCL#0: 84%
OPENCL#0: 85%
OPENCL#0: 85%
OPENCL#0: 86%
OPENCL#0: 87%
OPENCL#0: 88%
OPENCL#0: 88%
OPENCL#0: 89%
OPENCL#0: 90%
OPENCL#0: 91%
OPENCL#0: 92%
OPENCL#0: 92%
OPENCL#0: 93%
OPENCL#0: 94%
OPENCL#0: 95%
OPENCL#0: 95%
OPENCL#0: 96%
OPENCL#0: 97%
OPENCL#0: 98%
OPENCL#0: 98%
OPENCL#0: 99%
  i  10:16:26|openclminer0  set work; seed: #2228076c, **target: #000000000000**
  m  10:16:26|main  Mining on PoWhash #a954a3e4 : 12.06MH/s [A0+0:R0+0:F0]
  m  10:16:26|main  Got work package: #66a595d3
  i  10:16:26|openclminer0  set work; seed: #2228076c, **target: #000000000000**
  m  10:16:27|main  Mining on PoWhash #66a595d3 : 12.06MH/s [A0+0:R0+0:F0]
  m  10:16:27|main  Mining on PoWhash #66a595d3 : 12.46MH/s [A0+0:R0+0:F0]
  m  10:16:28|main  Mining on PoWhash #66a595d3 : 12.98MH/s [A0+0:R0+0:F0]
  m  10:16:28|main  Mining on PoWhash #66a595d3 : 12.95MH/s [A0+0:R0+0:F0]

GETH:
INFO [06-28|10:16:14] Imported new chain segment               blocks=1 txs=40  mgas=4.512 elapsed=130.007ms mgasps=34.707  number=3943672 hash=14972b…b5c9ed
INFO [06-28|10:16:14] Commit new mining work                   number=3943673 txs=60  uncles=0 elapsed=368.020ms
INFO [06-28|10:16:24] Imported new chain segment               blocks=1 txs=58  mgas=4.666 elapsed=98.005ms  mgasps=47.610  number=3943673 hash=69d105…900b62
INFO [06-28|10:16:24] Commit new mining work                   number=3943674 txs=106 uncles=0 elapsed=433.024ms
INFO [06-28|10:17:11] Imported new chain segment               blocks=1 txs=63  mgas=4.666 elapsed=152.009ms mgasps=30.697  number=3943674 hash=2a9eca…3fd4c5

**Comment by 353kilo** [comment]
Do I need to run benchmark or something in order for miner to generate a target#?

**Comment by AstarothPoD** [comment]
My best guess is that local geth/parity/etc mining always starts on target 0.
You may want to join a pool with your hash rate, your average block time will be something like 800 days.

**Comment by 353kilo** [comment]
Thanks for the reply I will look into that.
