### ISSUE TITLE
Empiric data observation over stale shares

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ethereum-mining/ethminer#820]
I'm on latest master.
I have experienced two different rounds of 12 hours each on same machines connected to pool eu1.ethermine.org.

First round **without** -RH (report hash rates) : avg 2.3% of stale shares and avghashrate (orange line) less than 3% below my known hashrate.

Second round **with** -RH (report hash rates) : avg 5% of stale shares and avghashrate (orange line) almost 5% below my reported hashrate.

Obviosly avghashrate is calculated over valid shares (not stale ones) so this values make sense.

Do not know if ethminer's 5 second report time is too quick, or if it locks something or, again, if pool is clogged by too many requests.

Just thinking out loud.

**Comment by skaterdude** [comment]
Are you mining to ethermine.org?  (Sorry if that's a dumb question.).  Looking back at my history, there appears to be a cyclic change in number of stale shares.  I suggest running 24-hour tests just in case there is something going on with Internet connection / server load / etc.
