### ISSUE TITLE
No work. Pause for 3 s. constant loop

### ISSUE THREAD

**Issue by nightshift23** [ethereum-mining/ethminer#822]
the tile says most of it. my batch: 

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --farm-recheck 200 -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 1ExARWhBZmWZ1tvukbMUzrqDPeJU7TMaP3.edward1

and this is what I get : 

C:\Users\untai\Desktop\$$$$\bin>setx GPU_FORCE_64BIT_PTR 0

SUCCESS: Specified value was saved.

C:\Users\untai\Desktop\$$$$\bin>setx GPU_MAX_HEAP_SIZE 100

SUCCESS: Specified value was saved.

C:\Users\untai\Desktop\$$$$\bin>setx GPU_USE_SYNC_OBJECTS 1

SUCCESS: Specified value was saved.

C:\Users\untai\Desktop\$$$$\bin>setx GPU_MAX_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\Users\untai\Desktop\$$$$\bin>setx GPU_SINGLE_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\Users\untai\Desktop\$$$$\bin>ethminer.exe --farm-recheck 200 -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 1ExARWhBZmWZ1tvukbMUzrqDPeJU7TMaP3.edward1
  m  07:40:11|main    |  ethminer version 0.14.0.dev2
  m  07:40:11|main    |  Build: Windows/msvc / Release
 cu  07:40:11|main    |  Using grid size 8192 , block size 128
  m  07:40:11|main    |  not-connected
  i  07:40:12|stratum |  Connected to eu1.ethermine.org
  i  07:40:12|stratum |  Spinning up miners...
  i  07:40:12|cuda-0  |  No work. Pause for 3 s.
  i  07:40:12|stratum |  Subscribed to stratum server
  i  07:40:15|cuda-0  |  No work. Pause for 3 s.
  m  07:40:16|main    |  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  i  07:40:18|cuda-0  |  No work. Pause for 3 s.
  i  07:40:21|cuda-0  |  No work. Pause for 3 s.
  m  07:40:21|main    |  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  i  07:40:24|cuda-0  |  No work. Pause for 3 s.
  m  07:40:26|main    |  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  i  07:40:27|cuda-0  |  No work. Pause for 3 s.
  i  07:40:30|cuda-0  |  No work. Pause for 3 s.
  m  07:40:32|main    |  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  i  07:40:33|cuda-0  |  No work. Pause for 3 s.
  i  07:40:36|cuda-0  |  No work. Pause for 3 s.
  m  07:40:37|main    |  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  i  07:40:39|cuda-0  |  No work. Pause for 3 s.
  m  07:40:42|main    |  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  i  07:40:42|cuda-0  |  No work. Pause for 3 s.
  i  07:40:45|cuda-0  |  No work. Pause for 3 s.
  m  07:40:47|main    |  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  i  07:40:48|cuda-0  |  No work. Pause for 3 s.

any help greatly appreciated.

**Comment by DeadManWalkingTO** [comment]
CUDA Hardware Test Launch Command:

```
ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.CUDAhardwareTest
```

OpenCL Hardware Test Launch Command:

```
ethminer -RH -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.OpenCLhardwareTest
```

MIXed Hardware Test Launch Command:

```
ethminer -RH -X -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.MIXedhardwareTest
```


Try with latest Ethminer version to ensure that's not hardware problem and feedback please.
Thank you!

**Comment by smurfy** [comment]
``1ExARWhBZmWZ1tvukbMUzrqDPeJU7TMaP3`` is not a valid ethereum address.
Thats why ethermine.org pool never sends you work.

**Comment by nightshift23** [comment]
I even just ran a test that said its a valid address, what makes you say its invalid?

**Comment by nightshift23** [comment]
nope got it, makes sense now, my wallet has more than one address, and thats the bitcoin address, duh.
