### ISSUE TITLE
Ethminer reported share rate of zero.

### ISSUE THREAD

**Issue by jean-m-cyr** [ethereum-mining/ethminer#824]
Spontaneously ethminer starts reporting 0 hashrate!!! Continues finding shares and reporting hashrate, but with a rate of 0? This may be and artifact of the new ethermine pages, but previously the green line would disappear, not report 0.

![snap1](https://user-images.githubusercontent.com/3529253/36852591-0890ba7a-1d3a-11e8-9586-d1c27d3ad912.png)

**Comment by DeadManWalkingTO** [comment]
Have you managed to reproduce the conditions that caused it?
I have not seen anything like that before.

**Comment by jean-m-cyr** [comment]
Nope. Closing

**Comment by smurfy** [comment]
as far as i know, this is also fixed with #828
I noticed that it was possible after a farm.stop, that the hash collector is no longer running.
So last value will be reported to pool and console.

**Comment by sbervinov** [comment]
ethminer-0.14.0rc1 does not report hashrate to nanopool when -RH option is added. It was checked tomorow

**Comment by AndreaLanfranchi** [comment]
Hash collector relies on a boost's deadline timer which, again, relies on boost's io_service.
PR #1135 has made io_service persistent for all work session thus it should be solved.
Feel free to reopen if problem occurs again.
