### ISSUE TITLE
Error meesages on startup

### ISSUE THREAD

**Issue by jean-m-cyr** [ethereum-mining/ethminer#825]
Logged every time at startup, doesn't seem to affect anything!!! Mines normally.

All Nvidia.

DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0

**Comment by SnowLeopard71** [comment]
The "i915" is referring to INTEL graphics chip.
Not sure why others get this and I don't -- I have onboard intel configured as primary display.

**Comment by jean-m-cyr** [comment]
This particular BIOS does not support disabling the on-chip Intel video controller.

**Comment by SnowLeopard71** [comment]
It seems related to OpenCL, so maybe you have unnecessary OpenCL drivers/utils installed that you do not need since it's a nvidia-only box?

**Comment by jean-m-cyr** [comment]
Thing is, it just started happening lately. Nvidia includes opencl support by default.

**Comment by jean-m-cyr** [comment]
Ah, requires root. Closing.
