### ISSUE TITLE
Ethermine Stratum Security Upgrade

### ISSUE THREAD

**Issue by maxcom99** [ethereum-mining/ethminer#826]
https://medium.com/@bitfly/ethermine-stratum-security-upgrade-d2245076e1b5

Can you guys shed some light on how this will be handled? Is ethermine giving us a public key? Is this optional or is the plan to roll this out as a mandate?

I am assuming this is all because of claymore really because he wants to stop people from killing his dev fee.

**Comment by MasonLyons** [comment]
Partially to do with that but also to prevent people from changing other peoples without their knowledge.

**Comment by smurfy** [comment]
Well i don't go into how ssl/tls works but with the latest dev release ethminer supports the new encrypted stratum pool addresses.

Use the extra argument ``--stratum-ssl``  and the ``5555`` port for the address.
For eu1 this would be: ``eu1.ethermine.org:5555``. 

We plan to switch to the ``ssl://eu1.ethermine.org:5555`` syntax but this is not finished yet.

**Comment by GlosVaper** [comment]
And I can verify it's working :-)

**Comment by maxcom99** [comment]
@smurfy can you tag the merge? I'd like to see how this was accomplished.

**Comment by smurfy** [comment]
@maxcom99 see #799
