### ISSUE TITLE
cuda "general protection" kernel error

### ISSUE THREAD

**Issue by SnowLeopard71** [ethereum-mining/ethminer#827]
-dev2 master build including mixed-mode fix generated 3 kernel errors:

> Mar  1 02:54:18 tb250 kernel: [120969.050922] traps: cuda-0[19633] general protection ip:7fe574ff4f4d sp:7fe554eba600 error:0 in libc-2.23.so[7fe574fbb000+1c0000]
Mar  1 10:12:29 tb250 kernel: [147260.434772] traps: cuda-0[23044] general protection ip:7fad9764cf4d sp:7fad773ec600 error:0 in libc-2.23.so[7fad97613000+1c0000]
Mar  1 10:13:36 tb250 kernel: [147326.998898] traps: cuda-0[23095] general protection ip:7fe708b75f4d sp:7fe6e8909600 error:0 in libc-2.23.so[7fe708b3c000+1c0000]

Any ideas?

**Comment by kedwin** [comment]
same error but i realized claymore was running in background which i forgot to exit
maybe something using your gpu perhaps ? just a suggestion no clue tho
