### ISSUE TITLE
Output stops after scrolling cmd window in Win 10

### ISSUE THREAD

**Issue by skaterdude** [ethereum-mining/ethminer#829]
If I scroll back in the cmd batch window in Win 10, the output stops (when I scroll back down it just sits there: the cursor is blinking on the last line it wrote).  The app appears to continue running.  It's still showing hash rate in ethermine.org after 10 mins.

**Comment by XhmikosR** [comment]
For me it stops if I select all CMD output but the process is still running.

**Comment by bmatthewshea** [comment]
**just hit enter.** 'unfreezes' it. This isn't ethminer. This is how the cmd window functions - not a bug.
