### ISSUE TITLE
Miner Shutsdown after 10 Minutes of Operation

### ISSUE THREAD

**Issue by DrRobotto** [ethereum-mining/ethminer#83]
I tried the new release on my rig with no monitor  (8 x 1060 3GB, 8GB RAM and Celeron CPU) and after ca. 10 minutes it shuts down the whole miner and teamviewer disconnects ... I have no idea whats going on ...

**Comment by JHGitty** [comment]
This sounds to me as an instability of your system. Please check if your PSU gives enough power and please disable any overclocking. Afterwards test again with latest release.

**Comment by DrRobotto** [comment]
The miner takes about 650 Watt from the wall and I use a 1200 PSU. The miner does not shutdown when I use the previous release or nicehash miner.

**Comment by DrRobotto** [comment]
So I tested the miner on a working computer with an Core i5 6600K and a GTX 1050 TI. It seems it has something to do with the command line. Sometimes it gets stuck and then the CPU usage goes up to 100%.
![usage100](https://user-images.githubusercontent.com/20887855/27676386-fc73c2f2-5cad-11e7-8d38-d3f6f7026989.png)

 If you hit the enter button in the command line the miner resumes and the CPU usage goes back to normal.
![normal](https://user-images.githubusercontent.com/20887855/27676402-0cf55528-5cae-11e7-814a-5bfeac016987.png)

Any solution for this problem? Or am I starting the miner in a wrong way?

**Comment by forsakenredog** [comment]
While the crashing is probably something else entirely, your command window locking up might be related to the quick edit mode in the command window. 

When you left click in a window too many times it starts the quickedit mode which pauses the program running so you can copy output.

Try disabling it in the properties and see if the behavior persists:
![cmd_properties](https://user-images.githubusercontent.com/5727620/27696273-38b6fade-5cbf-11e7-844f-f34ea3aba0ab.png)

**Comment by DrRobotto** [comment]
So I disabled the quick edit mode and the hibernation of the system in any case and it did not happen again. Thank you very much
