### ISSUE TITLE
Some questions about cli arguments

### ISSUE THREAD

**Issue by zypoi** [ethereum-mining/ethminer#830]
Hi, I am using ethminer v0.13.0 on my rigs, and there are some problems on the command line arguments(or maybe I misunderstood them). So, could anyone give me some advice about the following questions:
- --farm-recheck can be used to set the interval between checks, but in stratum mode, work is pushed directly from the pool server. So, should I set the farm recheck in stratum mode.
- -v can control the  verbosity of the logs but it seemed no use.
- My rigs has six RX580 8GB GPU, the BIOS has been modded, how to set the --cl-local-work, --cl-global-work and --cl-parallel-hash to get the best hashrate. I am using the experimental kernel, and currently using the --cl-local-work 256, --cl-global-work 32768, --cl-parallel-hash 2, the log says the hashrate is about 185, but actually about 175 on the pool.

**Comment by smurfy** [comment]
> --farm-recheck

not used in stratum mode, so you can remove it

> -v

0.14 will change that to some degree, but not much. you get most messages all the time. I think only work switch time will be displayed in higher verbose level with 0.14.

> --cl-local-work, --cl-global-work and --cl-parallel-hash

play with them :)

**Comment by zypoi** [comment]
Well, I've tried to remove the --cl-global-work, the hashrate seemed more stable, and the hashrate from the pool is also a little bit higher ( 180 mh/s). So, what exactly the default value of --cl-global-work is? 8192*128=1048576?
