### ISSUE TITLE
Low Hashrate in First Start of Claymore Dual

### ISSUE THREAD

**Issue by gbishtnw** [ethereum-mining/ethminer#832]
Hi,

I am using 10.3 and 10.5 Claymore dual miner with windows 10 (6 x RX580 and 6 x GTX1060)
GTX1060 overclocked by MSI Afterburner
RX580 are overclocked by claymore miner ( -mclock 2180 -cclock 1150)

I am starting miner with windows startup and its starting miner successfully but problem is in this default run miner is reporting low hashrate of my RX580 (8GB) (Overclocked setting not applied which are mentioned in claymore miner script)

then I am closing miner and restarting it, and after that its working perfectly.

Can anyone suggest me what should I do ?

**Comment by tonyaik** [comment]
Yes, ask for help in the claymore forum. This is for ethminer.

**Comment by smurfy** [comment]
https://bitcointalk.org/index.php?topic=1433925.0
