### ISSUE TITLE
New --exit parameter doesn't appear to work at all

### ISSUE THREAD

**Issue by adawalli** [ethereum-mining/ethminer#835]
#757 was supposed to exit whenever an error was encountered, but in my experience, this is not working at all. ethminer continues to retry incessantly.

./miners/ethminer -U -S us-east.ethash-hub.miningpoolhub.com:12020 -O username.pw --exit
  m  09:16:49|ethminer|  ethminer version 0.14.0.dev3
  m  09:16:49|ethminer|  Build: linux / release +git. 83693003
 cu  09:16:49|ethminer|  Using grid size 8192 , block size 128
  m  09:16:49|ethminer|  not-connected
  ℹ  09:16:49|stratum |  Connected to us-east.ethash-hub.miningpoolhub.com
  ℹ  09:16:49|stratum |  Spinning up miners...
  ℹ  09:16:49|cuda-0  |  No work. Pause for 3 s.
  ℹ  09:16:49|cuda-1  |  No work. Pause for 3 s.
  ℹ  09:16:49|cuda-2  |  No work. Pause for 3 s.
  ℹ  09:16:49|cuda-3  |  No work. Pause for 3 s.
  ℹ  09:16:49|stratum |  Subscribed to stratum server
  ℹ  09:16:49|stratum |  Worker not authorized:adawalli.hub
  ℹ  09:16:49|stratum |  Disconnected from us-east.ethash-hub.miningpoolhub.com
  ✘  09:16:49|stratum |  Retrying in 3 ... 
  ✘  09:16:50|stratum |  Retrying in 2 ... 
  ✘  09:16:51|stratum |  Retrying in 1 ... 
  ℹ  09:16:52|cuda-0  |  No work. Pause for 3 s.
  ℹ  09:16:52|cuda-1  |  No work. Pause for 3 s.
  ℹ  09:16:52|cuda-2  |  No work. Pause for 3 s.
  ℹ  09:16:52|cuda-3  |  No work. Pause for 3 s.
  ℹ  09:16:52|stratum |  Connected to us-east.ethash-hub.miningpoolhub.com

In fact, I can't even ctrl-c at this point...I have to do a `killall -9 ethminer` to get out of this loop. Let me know if you need more data @MariusVanDerWijden ?

**Comment by adawalli** [comment]
Sounds like this might already be resolved in #821 - I will close as soon as I can test a dev release with this patch.

**Comment by smurfy** [comment]
``--exit`` is for gpu errors, not no work.

#828  will be merged soon. you can use ``-FS exit`` with it. So it will try 3 times to connect and get work of the current pool and then exits.

**Comment by adawalli** [comment]
Thanks for the update - I will close this issue then.
