### ISSUE TITLE
vega hashrate

### ISSUE THREAD

**Issue by br1egel** [ethereum-mining/ethminer#837]
hi,
I wonder, if anybody has some proper settings for vega64 or vega56, which get more than 42 Mh/s

I tried `--cl-local-work 128 --cl-global-work 32768 --cl-parallel-hash 4`
and `--cl-local-work 256 --cl-global-work 81920 --cl-parallel-hash 4`
but specially the last one I doubt that this big global worksize is right. Anyone ?

P.S.: I am using unstable kernel

**Comment by rawdez** [comment]
>vega64 or vega56

probably better choice is just to mine something else with them
eg Nicehash-CryptoNight
check whattomine.com

**Comment by rhlug** [comment]
I read somewhere cl-parallel-hash * cl-local-work * [compute units] = global-work.  So if Vega 56 has 56 compute units, and max work size on vega is 256, you have...

Vega 56
8 * 256 * 56 = 114688

Vega 6 4
8 * 256 * 64 = 131072

I've actually been running my vega 56s with 57344.

 params="--cl-local-work 256 --cl-global-work 57344 --cl-parallel-hash 8 --cl-kernel 0"

I have no scientific evidence to prove it, but stale shares looked higher on 114688. 

I tested various settings on my 6 gpus, running each with a different settings, and then checking pool stats after 24hrs, and thats what I decided on.  Whether its right or wrong, no idea.    I'm getting 229 Mh/s on 6 gpu (1107mhz core, 1023mhz mem, 875mv core), pulling 1170w TDP.    5.1w per MH, which is slightly better than my RX570s which take 5.25w per MH (171Mh/s on 900w).

For the heat and noise that Vega proceeds,  I'm disappointed in the hash rates.  I can up the mem clocks and push them 40-41mh/s, but even hotter and louder.  My rx470s, 570s, 580s, just hum along nice and cool and quiet, churning out 28-31mh/s.

**Comment by GordonHarley** [comment]
Definitely a local calculation bug.   Setting the value to something ridiculous ~75M, produces this output: 

 m  08:47:24|main    |  Speed 2147.48 Mh/s    gpu/0 2147.48 62C 40% 265W  [A0+0:R0+0:F0] Time: 00:00
  m  08:47:29|main    |  Speed 2147.48 Mh/s    gpu/0 2147.48 63C 47% 264W  [A0+0:R0+0:F0] Time: 00:00
  m  08:47:34|main    |  Speed 2147.48 Mh/s    gpu/0 2147.48 61C 46% 263W  [A0+0:R0+0:F0] Time: 00:00

The card is still processing things and clocked all the way up, but they're done in quick spikes 5 seconds apart.  I'm guessing data transfer from global->card memory factors in aside from there just not being that many compute units.  Oh well.  At the original number I posted I was still averaging a nonce every two minutes, which is well above what I can usually get, so I'll try to find some in-between.

**Comment by GordonHarley** [comment]
Of course I failed to notice that the command line option specifies an equivalent value for default global...  

>--cl-global-work Set the OpenCL global work size as a multiple of the local work size. Default is 8192 * 
128 

If I use the values listed as defaults I get nothing like the normal results.  Default settings nearly max out the usage graph, but not quite.   local 32, global 131072 and 8 threads comes the closest, and local 32, global 65536, and 2 threads is close.   

Via some playing around and checking vs. the etherminer.org history page (my average is screwed up from all the playing with settings).  I was getting the best current results with  a very spiked graph like --cl-local-work 128 --cl-global-work 524288.  Attached are some compute usage graphs from various settings along with what ethminer displays for further information on the issues: 


![various_settings](https://user-images.githubusercontent.com/31956356/38592173-2900a884-3d00-11e8-8aab-837a9c28bf2f.jpg)
![various_settings2](https://user-images.githubusercontent.com/31956356/38592174-296dbce4-3d00-11e8-87c7-2bb748b60b76.jpg)
