### ISSUE TITLE
Envionment NO_COLOR regex_error

### ISSUE THREAD

**Issue by peterwillcn** [ethereum-mining/ethminer#839]
Use systemd service syslog
> #export NO_COLOR=true 
> #/usr/local/bin/ethminer --farm-recheck 200 xxx
terminate called after throwing an instance of 'std::regex_error' 
ethminer: what():  regex_error
```
tail -f /var/log/messages
syslog output:
```
ethminer: #033[32m  m  #033[35m06:25:49#033[0m#033[30m|#033[34methminer#033[0m#033[30m|#033[36m#033[0m  Speed #033[1;36m240.11#033[0m Mh/s    gpu/0 #033[36m30.01#033[0m  gpu/1 #033[36m30.01#033[0m  gpu/2 #033[36m30.01#033[0m  gpu/3 #033[36m30.01#033[0m  gpu/4 #033[36m30.01#033[0m  gpu/5 #033[36m30.01#033[0m  gpu/6 #033[36m30.01#033[0m  gpu/7 #033[36m30.01#033[0m  [A11+0:R0+0:F0] Time: 00:02#033[0m
```

**Comment by peterwillcn** [comment]
ref: #831

**Comment by jean-m-cyr** [comment]
Can you provide the 1st few log lines of the log when you start ethminer (version and last commit). It would help me better understand which dev version you're seeing this issue with.

**Comment by smurfy** [comment]
#850

**Comment by jean-m-cyr** [comment]
PR #854 should fix this
