### ISSUE TITLE
Build issue, win 10

### ISSUE THREAD

**Issue by lifeisdream** [ethereum-mining/ethminer#84]
C:\Users\owl\Downloads\ethminer-master\build>cmake -DETHASHCUDA=ON -DETHASHCL=ON --build .
-- [hunter] Calculating Config-SHA1
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] HUNTER_ROOT: C:/.hunter
-- [hunter] [ Hunter-ID: 435b09a | Config-ID: 61c532d | Toolchain-ID: cb59435 ]
-- [hunter] BOOST_ROOT: C:/.hunter/_Base/435b09a/61c532d/cb59435/Install (ver.: 1.64.0)
-- [hunter] BOOST_ROOT: C:/.hunter/_Base/435b09a/61c532d/cb59435/Install (ver.: 1.64.0)
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   system
-- [hunter] JSONCPP_ROOT: C:/.hunter/_Base/435b09a/61c532d/cb59435/Install (ver.: 1.8.0)
-- [hunter] LIBJSON-RPC-CPP_ROOT: C:/.hunter/_Base/435b09a/61c532d/cb59435/Install (ver.: 0.7.0-p0)
------------------------------------------------------------------------
-- CMake 3.4.3
-- Build Release / Windows
------------------------------------------------------------- components
-- ETHASHCL         Build OpenCL components                  ON
-- ETHASHCUDA       Build CUDA components                    ON
-- ETHSTRATUM       Build Stratum components                 ON
------------------------------------------------------------------------

-- [hunter] OPENCL_ROOT: C:/.hunter/_Base/435b09a/61c532d/cb59435/Install (ver.: 2.1-p3)
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/FindCUDA.cmake:617 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  libethash-cuda/CMakeLists.txt:1 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Users/owl/Downloads/ethminer-master/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/owl/Downloads/ethminer-master/build/CMakeFiles/CMakeError.log".

**Comment by jimmykl** [comment]
Have you installed the full CUDA toolkit?

**Comment by lifeisdream** [comment]
Ok, my fault, I should've been restart console to let Path env to apply. Now it fails to compile at Debug but compiles at Release.
