### ISSUE TITLE
Ethermine always at "not conntected"

### ISSUE THREAD

**Issue by lukecywon** [ethereum-mining/ethminer#840]
ethminer.exe --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0xd20f8717ee1D0F9dBa09d22D1a72614B7fA0b66C.LaptopRig     
  m  01:01:46|main    |  ethminer version 0.14.0.dev3      
  m  01:01:46|main    |  Build: windows / release +git. 83693003      
  i  01:01:46|main    |  Found suitable OpenCL device [ Intel(R) HD Graphics 620 ] with 3377887642  bytes  of GPU memory    
  m  01:01:46|main    |  not-connected

How to fix this?

**Comment by smurfy** [comment]
you cant mine with your intel iGPU

What graphics card has your computer?
