### ISSUE TITLE
Impossible hashrate, no mining

### ISSUE THREAD

**Issue by melvyn2** [ethereum-mining/ethminer#841]
I am mining with an MSi Gaming X RX 480 8 GB, with 
```
ethminer version 0.14.0.dev3+git.be90cbf
Build: darwin/release/appleclang
```
I am getting extremely high hashrates, with no mining showing on nicehash (active worker but no profitability). Here is an example log : [https://pastebin.com/HTmu3WWy](https://pastebin.com/HTmu3WWy)

The commannd I am using is: `ethminer -G --opencl-device 0 --opencl-platform 0 --cl-local-work 256 --cl-global-work 98304 --cl-kernel 1 -SP 2 -S daggerhashimoto.usa.nicehash.com:3353 -O (MY_BCT_ADDRESS_HERE):x`

**Comment by bmatthewshea** [comment]
What's it do when you use the bare minimum command:
 `ethminer -G -SP 2 -S daggerhashimoto.usa.nicehash.com:3353 -O` (wallet)
?

**Comment by melvyn2** [comment]
With the barebones command, [this happens.](https://pastebin.com/qwc90XbD)

**Comment by melvyn2** [comment]
Or it did for a bit. Stopping and restarting the command makes it go back to what it was like before.

**Comment by melvyn2** [comment]
Weird. It seems to work randomly once in a while now...

**Comment by melvyn2** [comment]
Even when it reports 25-27 MH/s, nicehash says it is active but not profiting.

**Comment by bmatthewshea** [comment]
I don't have a mac anymore so can't tell you much about darwin builds.. with that said I have never seen that hashrate issue before. maybe someone with mac can help u..?
If it reporting a 'normal' hashrate now, do you ever see "solution found", occasionally?
If so, you should be reporting solutions back to NH and should be making revenue at NH.
It's probably not ethminer at any rate ^ -if- this is the case..

**Comment by melvyn2** [comment]
I haven't managed to reproduce a 'normal' hasrate anymore... However, I will post log output once I get home.

**Comment by bmatthewshea** [comment]
k.
RE: out of memory - but if that's the case, you will needed to specify the card you want to use - even on a 'bare bones' command you tried above - sorry - I didn't notice that.
Since you were specifying `--opencl-device 0 --opencl-platform 0` I assumed it would default to that anyway. (0 is first usable device/default, obviously - or should be). You may want to try these flags with a release build? if you haven't..

**Comment by melvyn2** [comment]
Sorry for the late reply, I was testing if using the claymore kernel (ethminer-cm) on mac or with claymore on ubuntu would fix it (claymore did, as this is a software problem, but ethminer-cm on mac didn't). I think I'll be using claymore from now on, or until this works. As far as the test, I'll try it soon.

**Comment by bmatthewshea** [comment]
I have no problems at all with ethminer under Linux (you mentioned Ubuntu).

Yeah, I cannot reproduce your issue because I don't have a Mac. Maybe someone else will have same issue and post here. As far as Claymore - It's not open source - why I've never used it.

**Comment by smurfy** [comment]
please try to use default params instead of setting ``--cl-local-work 256 --cl-global-work 98304``
Wrong or strange values there can lead to the display of wrong hashrates and no work done.

**Comment by bmatthewshea** [comment]
@smurfy I think he did - see the post under [this ^ above](https://github.com/ethereum-mining/ethminer/issues/841#issuecomment-370242633).

**Comment by piotr-dobrogost** [comment]
Using the same version on Linux with 8 1070s. Normally the hashrate of each card is 31-32Mh/s and this has been reported till recently (in earlier versions). Now I see the reported (in the log) hashrate dropping sometimes to 0.00Mh/s and sometimes going up to insane values like 80Mh/s or 112Mh/s but also going down to 18Mh/s. The cards are OC but it's "safe" level of OC which is pretty stable and didn't result in such wired hashrates before.

**Comment by bmatthewshea** [comment]
@piotr-dobrogost If you mean "ethminer version 0.14.0.dev3" as per OP? You may know already, but that is a development version. It may or may not be as 'stable' as a release. Maybe try current 'release'.. 0.13.0 or even 12 ? Also make sure you're not over heating.. since you seem to have OC in check.

**Comment by jakehaas** [comment]
Still not working....

>  m 12:35:44          ethminer 0.15.0
 m 12:35:44          Build: darwin/release
 i 12:35:44          Found suitable OpenCL device [AMD Radeon Pro 570 Compute Engine] with 4294967296 bytes of GPU memory
 i 12:35:44 main     Selected pool eth-us.dwarfpool.com:8008
 i 12:35:44 stratum  Trying 144.217.139.192:8008 ...
 i 12:35:44 stratum  Connected to eth-us.dwarfpool.com [144.217.139.192:8008]
 i 12:35:44 stratum  Spinning up miners...
cl 12:35:44 cl-0     No work. Pause for 3 s.
 i 12:35:44 stratum  Logged in to eth-proxy server
 i 12:35:44 stratum  Job: #f98c9b9f… eth-us.dwarfpool.com [144.217.139.192:8008]
 i 12:35:44 stratum  Pool difficulty: 2.00K megahash
 i 12:35:44 stratum  New epoch 203
cl 12:35:47 cl-0     Platform: Apple
cl 12:35:47 cl-0     Device:   AMD Radeon Pro 570 Compute Engine / OpenCL 1.2 
 i 12:35:48 stratum  Job: #8b4bd14b… eth-us.dwarfpool.com [144.217.139.192:8008]
cl 12:35:49 cl-0     OpenCL kernel: Stable kernel
cl 12:35:49 cl-0     Build info: 
cl 12:35:49 cl-0     Creating light cache buffer, size: 43382848
cl 12:35:49 cl-0     Creating DAG buffer, size: 2776625536
cl 12:35:49 cl-0     Loading kernels
cl 12:35:49 cl-0     Writing light cache buffer
cl 12:35:49 cl-0     Creating buffer for header.
cl 12:35:49 cl-0     Creating mining buffer
 i 12:35:49 cl-0     2.58593 GB of DAG data generated in 4 ms.
 m 12:35:49          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 i 12:35:50 stratum  Job: #2f66d7fd… eth-us.dwarfpool.com [144.217.139.192:8008]
 m 12:35:54          Speed 7975.42 Mh/s    gpu/0 7975.42  [A0+0:R0+0:F0] Time: 00:00
 i 12:35:55 stratum  Job: #eac32391… eth-us.dwarfpool.com [144.217.139.192:8008]
 i 12:35:58 stratum  Job: #a1d6e051… eth-us.dwarfpool.com [144.217.139.192:8008]
 m 12:35:59          Speed 8446.28 Mh/s    gpu/0 8446.28  [A0+0:R0+0:F0] Time: 00:00
 m 12:36:04          Speed 8918.33 Mh/s    gpu/0 8918.33  [A0+0:R0+0:F0] Time: 00:00
 i 12:36:04 stratum  Job: #c72b7c51… eth-us.dwarfpool.com [144.217.139.192:8008]
 i 12:36:06 stratum  Job: #07ee9eeb… eth-us.dwarfpool.com [144.217.139.192:8008]
 m 12:36:09          Speed 8906.09 Mh/s    gpu/0 8906.09  [A0+0:R0+0:F0] Time: 00:00
^C m 12:36:14          Speed 8833.53 Mh/s    gpu/0 8833.53  [A0+0:R0+0:F0] Time: 00:00
 i 12:36:14          Shutting down...
 i 12:36:14 main     Disconnected from eth-us.dwarfpool.com [144.217.139.192:8008]
 i 12:36:14 main     Shutting down miners...
 i 12:36:14 main     Terminated !

**Comment by AndreaLanfranchi** [comment]
We have no developers for Mac and soon the support for MacOS will be dropped due to inability of Apple to support new OpenCL specs.

Sorry.
