### ISSUE TITLE
low hashrate with GTX1070

### ISSUE THREAD

**Issue by lsongseven** [ethereum-mining/ethminer#842]
Use it to mine eth.

The hashrate is only about 26Mh/s, the effective hashrate is only 2.9Mh/s! 

![oykeym65ru8 933xz4 2f](https://user-images.githubusercontent.com/26639581/36948047-9fe66776-200f-11e8-8281-8e25ee3d3cf2.png)

And while it running, the GPU occupation rate is quite low.

![6l_q04dab380fh 5ipd02a](https://user-images.githubusercontent.com/26639581/36947999-ec7b0548-200e-11e8-8ea9-29bc7de7dd75.png)

![image](https://user-images.githubusercontent.com/26639581/36948012-1adc5252-200f-11e8-88c2-8634481bded3.png)

I am totally a freshman, could anyone tell me if it is normal and how to improve the effective hashrate?

**Comment by lsongseven** [comment]
@DeadManWalkingTO Thanks！

I tried your suggestions and find that the 4th tip helps improve hashrate by 2Mh/s. Now it is about 28Mh/s but still not good enough.

**Comment by GlosVaper** [comment]
Out of interest, what hashrate were you expecting?

There's a number of factors that can affect the hashrate returned, from the memory brand on your GPU to what other processes you have running on your machine through cooling.

The parameters you set in ethminer also have an effect, try this line and see what you get;

ethminer -RH -U --cuda-parallel-hash 6 --cuda-grid-size 8192 --cuda-block-size 256 --cuda-schedule auto -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O ccccccccccccccccccccccccccccccccccccccc.ddddddddd

**Comment by jmsjr** [comment]
The pool calculates your "Effective Hashrate" based on the number of shares you have submitted. Your console output shows you have only been mining for 13 minutes. It takes time for the "Effective Hashrate" to be near or close to your "Reported Hashrate". By the looks of it, you are submitting 1 share per minute. 

Go back to your miner's stats at nanopool after about 12 or 24 hours. Your "Effective Hashrate" should be closer to your "Reported Hashrate".

**Comment by gordan-bobic** [comment]
Try with the following parameters:
```
--stratum-protocol 1 --report-hashrate
```

That will send the actual hash rate to the pool, which you will then be able to see on the pool's graphs.
10xx series cards always run compute jobs in P2 state, which has memory clocked lower than gaming mode (P0). The hash rate you were seeing seems about right for a non-overclocked card on P2 power state.
