### ISSUE TITLE
ethminer version 0.14.0.dev3+git.be90cbf throws core dumped when launching

### ISSUE THREAD

**Issue by emclab** [ethereum-mining/ethminer#843]
I setup `ubuntu 16.04` for my mining rig with one AMD RX 560 & 570, with driver `17.50`. `ethminer version 0.14.0.dev3+git.be90cbf`. The benchmark output is fine with `ethminer -G -M`:

    ......
     cl  10:54:26|cl-1    |  Creating light cache buffer, size 16776896
     cl  10:54:26|cl-1    |  Creating DAG buffer, size 1073739904
     cl  10:54:26|cl-1    |  Loading kernels
     cl  10:54:26|cl-1    |  Writing light cache buffer
     cl  10:54:26|cl-1    |  Creating buffer for header.
     cl  10:54:26|cl-1    |  Creating mining buffer
      â
       ¹  10:54:28|cl-0    |  0.999998  GB of DAG data generated in 2360 ms.
      â
       ¹  10:54:31|cl-1    |  0.999998  GB of DAG data generated in 5157 ms.
    Trial 1...
    31784566
    Trial 2...
    33567859
    Trial 3...
    33567859
    Trial 4...
    33571217
    Trial 5...
    33462959
    min/mean/max: 31784566/33190892/33571217 H/s
    inner mean: 33534011 H/s

Then launching with `ethminer -G -F http://eth-us.dwarfpool.com:8008/my_wallet_add/my_worker` throws out error:

      m  12:28:25|ethminer|  ethminer version 0.14.0.dev3
      m  12:28:25|ethminer|  Build: linux / release +git. be90cbf
      â
       ¹  12:28:25|ethminer|  Found suitable OpenCL device [ Ellesmere ] with 8023568384  bytes of GPU memory
      m  12:28:25|ethminer|  not-connected
      m  12:28:30|ethminer|  not-connected
      m  12:28:35|ethminer|  not-connected
    *** longjmp causes uninitialized stack frame ***: ethminer terminated
    ======= Backtrace: =========
    /lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f946cc8f7e5]
    /lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x5c)[0x7f946cd3115c]
    /lib/x86_64-linux-gnu/libc.so.6(+0x11905d)[0x7f946cd3105d]
    /lib/x86_64-linux-gnu/libc.so.6(__longjmp_chk+0x29)[0x7f946cd30fb9]
    ethminer[0x5464d3]
    /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f946d894390]
    /lib/x86_64-linux-gnu/libpthread.so.0(__nanosleep+0x2d)[0x7f946d893c1d]
    ethminer(_ZN8MinerCLI7doMinerEv+0x1277)[0x4b4b17]
    ethminer(_ZN8MinerCLI7executeEv+0x38f)[0x4ba79f]
    ethminer(main+0x495)[0x4a2655]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f946cc38830]
    ethminer(_start+0x29)[0x4a5b49]
    ======= Memory map: ========
    00400000-00816000 r-xp 00000000 08:05 261987                             /usr/local/bin/ethminer
    00a16000-00a36000 r--p 00416000 08:05 261987                             /usr/local/bin/ethminer
    00a36000-00a45000 rw-p 00436000 08:05 261987                             /usr/local/bin/ethminer
    00a45000-00a4c000 rw-p 00000000 00:00 0
    01d8c000-02034000 rw-p 00000000 00:00 0                                  [heap]
    600200000-800000000 ---p 00000000 00:00 0
    7f945f9db000-7f945f9f2000 r-xp 00000000 08:05 806768                     /lib/x86_64-linux-gnu/libresolv-2.23.so
    7f945f9f2000-7f945fbf2000 ---p 00017000 08:05 806768                     /lib/x86_64-linux-gnu/libresolv-2.23.so
    7f945fbf2000-7f945fbf3000 r--p 00017000 08:05 806768                     /lib/x86_64-linux-gnu/libresolv-2.23.so
    7f945fbf3000-7f945fbf4000 rw-p 00018000 08:05 806768                     /lib/x86_64-linux-gnu/libresolv-2.23.so
    7f945fbf4000-7f945fbf6000 rw-p 00000000 00:00 0
    7f945fbf6000-7f945fbfb000 r-xp 00000000 08:05 806867                     /lib/x86_64-linux-gnu/libnss_dns-2.23.so
    7f945fbfb000-7f945fdfb000 ---p 00005000 08:05 806867                     /lib/x86_64-linux-gnu/libnss_dns-2.23.so
    7f945fdfb000-7f945fdfc000 r--p 00005000 08:05 806867                     /lib/x86_64-linux-gnu/libnss_dns-2.23.so
    7f945fdfc000-7f945fdfd000 rw-p 00006000 08:05 806867                     /lib/x86_64-linux-gnu/libnss_dns-2.23.so
    7f945fdfd000-7f945fdff000 r-xp 00000000 08:05 787774                     /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
    7f945fdff000-7f945fffe000 ---p 00002000 08:05 787774                     /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
    7f945fffe000-7f945ffff000 r--p 00001000 08:05 787774                     /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
    7f945ffff000-7f9460000000 rw-p 00002000 08:05 787774                     /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
    7f9460000000-7f9460021000 rw-p 00000000 00:00 0
    7f9460021000-7f9464000000 ---p 00000000 00:00 0
    7f946415c000-7f9464167000 r-xp 00000000 08:05 810065                     /lib/x86_64-linux-gnu/libnss_files-2.23.so
    7f9464167000-7f9464366000 ---p 0000b000 08:05 810065                     /lib/x86_64-linux-gnu/libnss_files-2.23.so
    7f9464366000-7f9464367000 r--p 0000a000 08:05 810065                     /lib/x86_64-linux-gnu/libnss_files-2.23.so
    7f9464367000-7f9464368000 rw-p 0000b000 08:05 810065                     /lib/x86_64-linux-gnu/libnss_files-2.23.so
    7f9464368000-7f946436e000 rw-p 00000000 00:00 0
    7f9464387000-7f9464388000 ---p 00000000 00:00 0
    7f9464388000-7f9464b88000 rw-p 00000000 00:00 0
    7f9464b88000-7f9464b89000 ---p 00000000 00:00 0
    7f9464b89000-7f9465389000 rw-p 00000000 00:00 0
    7f9465389000-7f9465399000 rw-s 10766c000 00:06 336                       /dev/dri/renderD129
    7f9465399000-7f94653a1000 rw-s 107664000 00:06 336                       /dev/dri/renderD129
    7f94653a1000-7f94653a3000 rw-s 107662000 00:06 336                       /dev/dri/renderD129
    7f94653a3000-7f94653a5000 rw-s 107660000 00:06 336                       /dev/dri/renderD129
    7f94653a5000-7f94654a5000 rw-s 107560000 00:06 336                       /dev/dri/renderD129
    7f94654a5000-7f94655a5000 rw-s 107460000 00:06 336                       /dev/dri/renderD129
    7f94655a5000-7f94655ab000 rw-s 10745a000 00:06 336                       /dev/dri/renderD129
    7f94655ab000-7f94655b1000 rw-s 107454000 00:06 336                       /dev/dri/renderD129
    7f94655b1000-7f94655b9000 rw-s 10744c000 00:06 336                       /dev/dri/renderD129
    7f94655b9000-7f94655c1000 rw-s 107444000 00:06 336                       /dev/dri/renderD129
    7f94655c1000-7f9465641000 rw-s 1073c4000 00:06 336                       /dev/dri/renderD129
    7f9465641000-7f94656c1000 rw-s 107344000 00:06 336                       /dev/dri/renderD129
    7f94656c1000-7f9465701000 rw-s 107304000 00:06 336                       /dev/dri/renderD129
    7f9465701000-7f9465741000 rw-s 1072c4000 00:06 336                       /dev/dri/renderD129
    7f9465741000-7f94657f7000 rw-p 00000000 00:00 0
    7f94657f7000-7f9467636000 r-xp 00000000 08:05 822274                     /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl12cl64.so
    7f9467636000-7f9467836000 ---p 01e3f000 08:05 822274                     /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl12cl64.so
    7f9467836000-7f9467b33000 rw-p 01e3f000 08:05 822274                     /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl12cl64.so
    7f9467b33000-7f9467be7000 rw-p 00000000 00:00 0
    7f9467be8000-7f9467bf0000 rw-s 106cbc000 00:06 336                       /dev/dri/renderD129
    7f9467bf0000-7f9467c00000 rw-s 106cac000 00:06 336                       /dev/dri/renderD129
    7f9467c00000-7f9467c10000 rw-s 10d49d000 00:06 201                       /dev/dri/renderD128
    7f9467c10000-7f9467d10000 rw-s 125c45000 00:06 201                       /dev/dri/renderD128
    7f9467d10000-7f9467e10000 rw-s 125b45000 00:06 201                       /dev/dri/renderD128
    7f9467e10000-7f9467e90000 rw-s 128245000 00:06 201                       /dev/dri/renderD128
    7f9467e90000-7f9467e9d000 r-xp 00000000 08:05 821329                     /opt/amdgpu/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0
    7f9467e9d000-7f946809c000 ---p 0000d000 08:05 821329                     /opt/amdgpu/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0
    7f946809c000-7f946809d000 r--p 0000c000 08:05 821329                     /opt/amdgpu/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0
    7f946809d000-7f946809e000 rw-p 0000d000 08:05 821329                     /opt/amdgpu/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0
    7f946809e000-7f94680b1000 r-xp 00000000 08:05 821311                     /opt/amdgpu/lib/x86_64-linux-gnu/libdrm.so.2.4.0
    7f94680b1000-7f94682b0000 ---p 00013000 08:05 821311                     /opt/amdgpu/lib/x86_64-linux-gnu/libdrm.so.2.4.0
    7f94682b0000-7f94682b1000 r--p 00012000 08:05 821311                     /opt/amdgpu/lib/x86_64-linux-gnu/libdrm.so.2.4.0
    7f94682b1000-7f94682b2000 rw-p 00013000 08:05 821311                     /opt/amdgpu/lib/x86_64-linux-gnu/libdrm.so.2.4.0
    7f94682b2000-7f94682b9000 r-xp 00000000 08:05 810074                     /lib/x86_64-linux-gnu/librt-2.23.so
    7f94682b9000-7f94684b8000 ---p 00007000 08:05 810074                     /lib/x86_64-linux-gnu/librt-2.23.so
    7f94684b8000-7f94684b9000 r--p 00006000 08:05 810074                     /lib/x86_64-linux-gnu/librt-2.23.so
    7f94684b9000-7f94684ba000 rw-p 00007000 08:05 810074                     /lib/x86_64-linux-gnu/librt-2.23.so
    7f94684ba000-7f946bfed000 r-xp 00000000 08:05 822273                     /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
    7f946bfed000-7f946c1ec000 ---p 03b33000 08:05 822273                     /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
    7f946c1ec000-7f946c787000 rw-p 03b32000 08:05 822273                     /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
    7f946c787000-7f946cc18000 rw-p 00000000 00:00 0
    7f946cc18000-7f946cdd8000 r-xp 00000000 08:05 788982                     /lib/x86_64-linux-gnu/libc-2.23.so
    7f946cdd8000-7f946cfd8000 ---p 001c0000 08:05 788982                     /lib/x86_64-linux-gnu/libc-2.23.so
    7f946cfd8000-7f946cfdc000 r--p 001c0000 08:05 788982                     /lib/x86_64-linux-gnu/libc-2.23.so
    7f946cfdc000-7f946cfde000 rw-p 001c4000 08:05 788982                     /lib/x86_64-linux-gnu/libc-2.23.so
    7f946cfde000-7f946cfe2000 rw-p 00000000 00:00 0
    7f946cfe2000-7f946cff8000 r-xp 00000000 08:05 787707                     /lib/x86_64-linux-gnu/libgcc_s.so.1
    7f946cff8000-7f946d1f7000 ---p 00016000 08:05 787707                     /lib/x86_64-linux-gnu/libgcc_s.so.1
    7f946d1f7000-7f946d1f8000 rw-p 00015000 08:05 787707                     /lib/x86_64-linux-gnu/libgcc_s.so.1
    7f946d1f8000-7f946d300000 r-xp 00000000 08:05 788978                     /lib/x86_64-linux-gnu/libm-2.23.so
    7f946d300000-7f946d4ff000 ---p 00108000 08:05 788978                     /lib/x86_64-linux-gnu/libm-2.23.so
    7f946d4ff000-7f946d500000 r--p 00107000 08:05 788978                     /lib/x86_64-linux-gnu/libm-2.23.so
    7f946d500000-7f946d501000 rw-p 00108000 08:05 788978                     /lib/x86_64-linux-gnu/libm-2.23.so
    7f946d501000-7f946d673000 r-xp 00000000 08:05 261995                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
    7f946d673000-7f946d873000 ---p 00172000 08:05 261995                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
    7f946d873000-7f946d87d000 r--p 00172000 08:05 261995                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
    7f946d87d000-7f946d87f000 rw-p 0017c000 08:05 261995                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
    7f946d87f000-7f946d883000 rw-p 00000000 00:00 0
    7f946d883000-7f946d89b000 r-xp 00000000 08:05 788981                     /lib/x86_64-linux-gnu/libpthread-2.23.so
    7f946d89b000-7f946da9a000 ---p 00018000 08:05 788981                     /lib/x86_64-linux-gnu/libpthread-2.23.so
    7f946da9a000-7f946da9b000 r--p 00017000 08:05 788981                     /lib/x86_64-linux-gnu/libpthread-2.23.so
    7f946da9b000-7f946da9c000 rw-p 00018000 08:05 788981                     /lib/x86_64-linux-gnu/libpthread-2.23.so
    7f946da9c000-7f946daa0000 rw-p 00000000 00:00 0
    7f946daa0000-7f946daa3000 r-xp 00000000 08:05 788984                     /lib/x86_64-linux-gnu/libdl-2.23.so
    7f946daa3000-7f946dca2000 ---p 00003000 08:05 788984                     /lib/x86_64-linux-gnu/libdl-2.23.so
    7f946dca2000-7f946dca3000 r--p 00002000 08:05 788984                     /lib/x86_64-linux-gnu/libdl-2.23.so
    7f946dca3000-7f946dca4000 rw-p 00003000 08:05 788984                     /lib/x86_64-linux-gnu/libdl-2.23.so
    7f946dca4000-7f946dcca000 r-xp 00000000 08:05 788980                     /lib/x86_64-linux-gnu/ld-2.23.so
    7f946dccb000-7f946dcd3000 rw-s 10d475000 00:06 201                       /dev/dri/renderD128
    7f946dcd3000-7f946dcd5000 rw-s 10d473000 00:06 201                       /dev/dri/renderD128
    7f946dcd5000-7f946dcd7000 rw-s 10d471000 00:06 201                       /dev/dri/renderD128
    7f946dcd7000-7f946dcdd000 rw-s 10d46b000 00:06 201                       /dev/dri/renderD128
    7f946dcdd000-7f946dce3000 rw-s 10d465000 00:06 201                       /dev/dri/renderD128
    7f946dce3000-7f946dceb000 rw-s 10d45d000 00:06 201                       /dev/dri/renderD128
    7f946dceb000-7f946dcf3000 rw-s 10d435000 00:06 201                       /dev/dri/renderD128
    7f946dcf3000-7f946dd73000 rw-s 1281c5000 00:06 201                       /dev/dri/renderD128
    7f946dd73000-7f946ddb3000 rw-s 128185000 00:06 201                       /dev/dri/renderD128
    7f946ddb3000-7f946ddf3000 rw-s 128145000 00:06 201                       /dev/dri/renderD128
    7f946ddf3000-7f946deb1000 rw-p 00000000 00:00 0
    7f946deb1000-7f946deb9000 rw-s 10d42d000 00:06 201                       /dev/dri/renderD128
    7f946deb9000-7f946dec9000 rw-s 10d41d000 00:06 201                       /dev/dri/renderD128
    7f946dec9000-7f946deca000 r--p 00025000 08:05 788980                     /lib/x86_64-linux-gnu/ld-2.23.so
    7f946deca000-7f946decb000 rw-p 00026000 08:05 788980                     /lib/x86_64-linux-gnu/ld-2.23.so
    7f946decb000-7f946decc000 rw-p 00000000 00:00 0
    7ffe60cd0000-7ffe60cf1000 rw-p 00000000 00:00 0                          [stack]
    7ffe60cf1000-7ffe60cf4000 r--p 00000000 00:00 0                          [vvar]
    7ffe60cf4000-7ffe60cf6000 r-xp 00000000 00:00 0                          [vdso]
    ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
    ./start_miner.sh: line 11:  1904 Aborted                 (core dumped) ethminer -G -F http://eth-us.dwarfpool.com:8008/my_wallet_add/my_worker

What caused the ethminer not connecting?

**Comment by peterwillcn** [comment]
upgrade amd latest driver

**Comment by jean-m-cyr** [comment]
I believe PR #828 fixes this. Please re-test and close.

**Comment by AndreaLanfranchi** [comment]
No feed back.
