### ISSUE TITLE
Job invalid chars (Master - Win10)

### ISSUE THREAD

**Issue by DeadManWalkingTO** [ethereum-mining/ethminer#844]
Invalid chars at end of job name.
Version : Last Master
OS : Windows 10

![001](https://user-images.githubusercontent.com/34924727/36950925-abb4dbfa-2005-11e8-9e1f-9ec6a4c7e251.jpg)

**Comment by jmsjr** [comment]
From my Linux console ( which supports UTF-8 ), that's supposed to be the ellipsis Unicode character.
https://www.fileformat.info/info/unicode/char/2026/index.htm

Not sure how you would check that in Windows, or even how ethminer is run in Windows.

IIRC, when you open a Command Prompt in Windows, you can "change the font" ??? Can you try using a Unicode font ?

**Comment by DeadManWalkingTO** [comment]
I try to change code page to unicode, but ethminer cant connect to the pool!!!

**Comment by jmsjr** [comment]
I am sure you can try right-click on the Command Prompt in Windows and change the font to say "Lucinda Console Unicode" ??? ( sorry, I don't have Windows handy unless I am at work )... without changing your code page.

**Comment by DeadManWalkingTO** [comment]
@jmsjr I tried it but I did not have any results.

**Comment by jean-m-cyr** [comment]
PR #856 Should solve this

**Comment by jean-m-cyr** [comment]
PR #856 Merged. Please re-rest and close.

**Comment by DeadManWalkingTO** [comment]
Problem solved!
