### ISSUE TITLE
disk full issue due to .ldb files

### ISSUE THREAD

**Issue by ajayaks** [ethereum-mining/ethminer#845]
Hi, 
I have 256GB SSD for my rig but its full in 1 week.
Actually "chaindata" folder i having .ldb files each is 2MB and having 60k + files.

Why these files are not getting deleted ? Does geth/ethnminer use these files ?

What should i do ? Is there a way to avoid disk full issue? 
Should i delete these files?

Please suggest.

Regards
Ajay

**Comment by GlosVaper** [comment]
It's Geth, that's the sync'd copy of the chain. Try switching to light mode
   $ geth removedb
   $ geth --fast --cache=2048

**Comment by ajayaks** [comment]
should i remove the complete chain first and then try above suggestion?

**Comment by smurfy** [comment]
why do you have geth running on your mining rig? Are you solo-mining?
If so it, why? Are you feeling lucky or do you have like a 1000+ GPU farm or something?
If you have only a couple of cards and still solo-mine, don't do it. You are just wasting energy.
Use a pool like ethermine.org 

Also geth problems are not really an ethminer issue.
