### ISSUE TITLE
errror 

### ISSUE THREAD

**Issue by tiknadaddy** [ethereum-mining/ethminer#846]
ETH: 5 pools are specified
Main Ethereum pool is eth-asia1.nanopool.org:9999
SC: 5 pools are specified
Main Siacoin pool is sia-asia1.nanopool.org:7777
AMD OpenCL platform not found
Be careful with overclocking, use default clocks for first tests
Press "s" for current statistics, "0".."9" to turn on/off cards, "r" to reload pools, "e" or "d" to select current pool
CUDA initializing...

NVIDIA Cards available: 1
CUDA Driver Version/Runtime Version: 9.1/8.0
GPU #0: GeForce 940MX, 4096 MB available, 3 compute units, capability: 5.0

Total cards: 1
NVIDIA NVML library not found, temperature monitoring for NVIDIA GPUs disabled.
DUAL MINING MODE ENABLED: ETHEREUM+SIACOIN
ETH: eth-proxy stratum mode
Watchdog enabled
Remote management (READ-ONLY MODE) is enabled on port 3333

ETH: Stratum - connecting to 'eth-asia1.nanopool.org' <172.104.165.191> port 9999
 SC: Stratum - connecting to 'sia-asia1.nanopool.org' <139.99.101.198> port 7777
ETH: Stratum - Connected (eth-asia1.nanopool.org:9999)
 SC: Stratum - Connected (sia-asia1.nanopool.org:7777)
ETH: Authorized
Setting DAG epoch #173...
 SC: Authorized
 SC: 03/05/18-11:34:19 - New job from sia-asia1.nanopool.org:7777
Setting DAG epoch #173 for GPU0
Create GPU buffer for GPU0
GPU 0, GpuMiner cu_kd failed 6 (1), the launch timed out and was terminated
GPU 0, Calc DAG failed!
GPU 0 failed
Setting DAG epoch #173 for GPU0
GPU 0, CUDA error 6 - cannot write buffer for DAG
GPU 0 failed
ETH: 03/05/18-11:34:34 - New job from eth-asia1.nanopool.org:9999
WATCHDOG: GPU error, you need to restart miner :(
ETH - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0, Time: 00:00
ETH: GPU0 0.000 Mh/s
 SC - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0
 SC: GPU0 0.000 Mh/s
Restarting OK, exit...

somebody pleAse help me

**Comment by lordrive** [comment]
The hell. Thats not even from this miner...

**Comment by jmsjr** [comment]
@tiknadaddy 

That output that you showed is from Claymore's dual miner, not ethminer.
