### ISSUE TITLE
0.14.0.dev3, mixed Nvidia & AMD, latest drivers, Ubuntu 16.04 B250, AMD not mining

### ISSUE THREAD

**Issue by Ben-and-Ellen** [ethereum-mining/ethminer#849]
Been using the ethminer version 0.14.0.dev3, however we're not seeing the difference between using the -G -U -X options. In our system with mixed cards, NV1070s and AMD580s we're only getting the 1070s to mine.

Using Ubuntu 16.04.3 LTS ethminer version 0.14.0.dev3+git.83693003 build

The system has two 1070ti cards and one RX580 card. ethminer does mine, however only with the 1070ti cards. The system can see the 1070tis and the 580 but it only mines with the 1070tis...

=ETHMINER VERSION=

$ ethminer -V
ethminer version 0.14.0.dev3+git.83693003
Build: linux/release/gnu

=ETHMINER - What cards installed?=

$ ethminer --list-devices

Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[0] [0] GeForce GTX 1070 Ti
CL_DEVICE_TYPE: GPU
CL_DEVICE_GLOBAL_MEM_SIZE: 8513978368
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2128494592
CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
[0] [1] GeForce GTX 1070 Ti
CL_DEVICE_TYPE: GPU
CL_DEVICE_GLOBAL_MEM_SIZE: 8513978368
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2128494592
CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
[1] [0] Ellesmere
CL_DEVICE_TYPE: GPU
CL_DEVICE_GLOBAL_MEM_SIZE: 8571142144
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1070 Ti
Compute version: 6.1
cudaDeviceProp::totalGlobalMem: 8513978368
Pci: 0000:0c:00
[1] GeForce GTX 1070 Ti
Compute version: 6.1
cudaDeviceProp::totalGlobalMem: 8513978368
Pci: 0000:0e:00

=TRYING TO MINE=

Using ethminer with -X option set:
only mines with the 1070s

Using ethminer with -G option set:
set --opencl-platform to 0 ethminer uses platform 0 - the two Nvidia cards
set --opencl-platform to 1 but ethminer used platform 0 - the two Nvidia cards
set --opencl-platform to 2 but ethminer used platform 0 - the two Nvidia cards

=ETHMINER with -X=

=OUTPUT=

$ ethminer -X --cuda-devices 0 1 --opencl-platform 1 --opencl-device 0 -SP 2 -U -S daggerhashimoto.eu.nicehash.com:3353 -O XXXXXXXXXXXXXXXXXXXX
m 18:06:44|ethminer| ethminer version 0.14.0.dev3
m 18:06:44|ethminer| Build: linux / release +git. 8369300
cu 18:06:45|ethminer| Using grid size 8192 , block size 128
cu 18:06:45|ethminer| Found suitable CUDA device [ GeForce GTX 1070 Ti ] with 8513978368 bytes of GPU memory
cu 18:06:45|ethminer| Found suitable CUDA device [ GeForce GTX 1070 Ti ] with 8513978368 bytes of GPU memory
m 18:06:45|ethminer| not-connected
ℹ 18:06:45|stratum | Connected to daggerhashimoto.eu.nicehash.com
ℹ 18:06:45|stratum | Spinning up miners...
ℹ 18:06:45|cuda-0 | No work. Pause for 3 s.
ℹ 18:06:45|cuda-1 | No work. Pause for 3 s.
ℹ 18:06:45|stratum | Extranonce set to 39c6ab
ℹ 18:06:45|stratum | Subscribed to stratum server
ℹ 18:06:45|stratum | Authorized worker XXXXXXXXXXXXXXXXXXXX
ℹ 18:06:45|stratum | Difficulty set to 0.5
ℹ 18:06:45|stratum | New pool difficulty: 2.1475 gigahashes
ℹ 18:06:45|stratum | Received new job #e8deb245… from daggerhashimoto.eu.nicehash.com
ℹ 18:06:48|cuda-0 | Initialising miner 0
ℹ 18:06:48|cuda-1 | Initialising miner 1
cu 18:06:50|cuda-0 | Using device: GeForce GTX 1070 Ti (Compute 6.1)
cu 18:06:50|cuda-0 | Set Device to current
cu 18:06:50|cuda-0 | Resetting device
cu 18:06:50|cuda-1 | Using device: GeForce GTX 1070 Ti (Compute 6.1)
cu 18:06:50|cuda-1 | Set Device to current
cu 18:06:50|cuda-1 | Resetting device
m 18:06:50|ethminer| Speed 0.00 Mh/s gpu/0 0.00 gpu/1 0.00 [A0+0:R0+0:F0] Time: 00:00
cu 18:06:50|cuda-0 | Allocating light with size: 39320768
cu 18:06:50|cuda-0 | Generating mining buffers
cu 18:06:50|cuda-1 | Allocating light with size: 39320768
cu 18:06:51|cuda-0 | Generating DAG for GPU # 0 with dagSize: 2516582272 gridSize: 8192
cu 18:06:51|cuda-1 | Generating mining buffers
cu 18:06:51|cuda-1 | Generating DAG for GPU # 1 with dagSize: 2516582272 gridSize: 8192
ℹ 18:06:55|stratum | Received new job #aae63a98… from daggerhashimoto.eu.nicehash.com
m 18:06:55|ethminer| Speed 0.00 Mh/s gpu/0 0.00 gpu/1 0.00 [A0+0:R0+0:F0] Time: 00:00
m 18:07:05|ethminer| Speed 50.95 Mh/s gpu/0 25.48 gpu/1 25.48 [A0+0:R0+0:F0] Time: 00:00

=ETHMINER with -G=

$ ethminer -G --opencl-platform 1 -SP 2 -U -S daggerhashimoto.eu.nicehash.com:3353 -O XXXXXXXXXXXXXXXXXXXX

=OUTPUT=
m 17:45:19|ethminer| ethminer version 0.14.0.dev3
m 17:45:19|ethminer| Build: linux / release +git. 8369300
cu 17:45:21|ethminer| Using grid size 8192 , block size 128
m 17:45:21|ethminer| not-connected
ℹ 17:45:21|stratum | Connected to daggerhashimoto.eu.nicehash.com
ℹ 17:45:21|stratum | Spinning up miners...
ℹ 17:45:21|cuda-0 | No work. Pause for 3 s.
ℹ 17:45:21|cuda-1 | No work. Pause for 3 s.
ℹ 17:45:21|stratum | Extranonce set to 2554
ℹ 17:45:21|stratum | Subscribed to stratum server
ℹ 17:45:21|stratum | Authorized worker XXXXXXXXXXXXXXXXXXXX
ℹ 17:45:21|stratum | Difficulty set to 0.5
ℹ 17:45:21|stratum | New pool difficulty: 2.1475 gigahashes
ℹ 17:45:21|stratum | Received new job #561e7a5f… from daggerhashimoto.eu.nicehash.com
ℹ 17:45:24|cuda-0 | Initialising miner 0
ℹ 17:45:24|cuda-1 | Initialising miner 1
cu 17:45:25|cuda-0 | Using device: GeForce GTX 1070 Ti (Compute 6.1)
cu 17:45:25|cuda-0 | Set Device to current
cu 17:45:25|cuda-1 | Using device: GeForce GTX 1070 Ti (Compute 6.1)
cu 17:45:25|cuda-0 | Resetting device
cu 17:45:25|cuda-1 | Set Device to current
cu 17:45:25|cuda-1 | Resetting device
cu 17:45:25|cuda-1 | Allocating light with size: 21364544
cu 17:45:25|cuda-1 | Generating mining buffers
cu 17:45:25|cuda-0 | Allocating light with size: 21364544
cu 17:45:25|cuda-1 | Generating DAG for GPU # 1 with dagSize: 1367339392 gridSize: 8192
cu 17:45:25|cuda-0 | Generating mining buffers
cu 17:45:25|cuda-0 | Generating DAG for GPU # 0 with dagSize: 1367339392 gridSize: 8192
m 17:45:36|ethminer| Speed 47.21 Mh/s gpu/0 23.29 gpu/1 23.92 [A0+0:R0+0:F0] Time: 00:00

FYI, for comparison and to make sure that it's not a hardware issue, started claymore miner. It's mining with all three cards with zero changes to drivers / system.

**Comment by jmsjr** [comment]
I have that problem too .. even with 0.14.0.dev1 and 0.14.0.dev2.

What I ended up doing is run two separate ethminer processes ... one just for OpenCL .. and another just for CUDA ( using the relevant options for only run for OpenCL / CUDA ).

**Comment by rawdez** [comment]
try to specify ONLY
--opencl-platform 1 
without
--cuda-devices 0 1 --opencl-device 0

**Comment by Ben-and-Ellen** [comment]
>try to specify ONLY
ok

Using -G or -X doesn't seem to engage the opencl mining. I notice that each line refers to cuda-0 or cuda-1. Here's the initial output. It is mining, it's just that it's using cuda only. The output continues in the same vein...

ethminer -G --opencl-platform 1 -SP 2 -U -S daggerhashimoto.eu.nicehash.com:3353 -O XXXXXXXXXXXXXXXXXXXX

  m  12:02:02|ethminer|  ethminer version 0.14.0.dev3
  m  12:02:02|ethminer|  Build: linux / release +git. 83693003
 cu  12:02:04|ethminer|  Using grid size 8192 , block size 128
  m  12:02:04|ethminer|  not-connected
  ℹ  12:02:04|stratum |  Connected to daggerhashimoto.eu.nicehash.com
  ℹ  12:02:04|stratum |  Spinning up miners...
  ℹ  12:02:04|cuda-0  |  No work. Pause for 3 s.
  ℹ  12:02:04|cuda-1  |  No work. Pause for 3 s.
  ℹ  12:02:04|stratum |  Extranonce set to 403081
  ℹ  12:02:04|stratum |  Subscribed to stratum server
  ℹ  12:02:04|stratum |  Authorized worker XXXXXXXXXXXXXXXXXXXX
  ℹ  12:02:04|stratum |  Difficulty set to 0.5
  ℹ  12:02:04|stratum |  New pool difficulty:  2.1475 gigahashes
  ℹ  12:02:04|stratum |  Received new job #cc90f643… from daggerhashimoto.eu.nicehash.com
  ℹ  12:02:07|cuda-0  |  Initialising miner 0
  ℹ  12:02:07|cuda-1  |  Initialising miner 1
 cu  12:02:08|cuda-0  |  Using device: GeForce GTX 1070 Ti  (Compute 6.1)
 cu  12:02:08|cuda-0  |  Set Device to current
 cu  12:02:08|cuda-0  |  Resetting device
 cu  12:02:08|cuda-1  |  Using device: GeForce GTX 1070 Ti  (Compute 6.1)
 cu  12:02:08|cuda-1  |  Set Device to current
 cu  12:02:08|cuda-1  |  Resetting device
 cu  12:02:08|cuda-0  |  Allocating light with size: 17824192
 cu  12:02:08|cuda-0  |  Generating mining buffers
 cu  12:02:08|cuda-1  |  Allocating light with size: 17824192
 cu  12:02:08|cuda-0  |  Generating DAG for GPU # 0  with dagSize: 1140849536  gridSize: 8192
 cu  12:02:08|cuda-1  |  Generating mining buffers
 cu  12:02:08|cuda-1  |  Generating DAG for GPU # 1  with dagSize: 1140849536  gridSize: 8192
  m  12:02:09|ethminer|  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  12:02:14|ethminer|  Speed  30.44 Mh/s    gpu/0 16.79  gpu/1 13.65  [A0+0:R0+0:F0] Time: 00:00
  m  12:02:19|ethminer|  Speed  50.01 Mh/s    gpu/0 25.18  gpu/1 24.83  [A0+0:R0+0:F0] Time: 00:00
  m  12:02:24|ethminer|  Speed  53.82 Mh/s    gpu/0 26.86  gpu/1 26.96  [A0+0:R0+0:F0] Time: 00:00

ethminer -X --opencl-platform 1 -SP 2 -U -S daggerhashimoto.eu.nicehash.com:3353 -O XXXXXXXXXXXXXXXXXXXX

  m  11:58:48|ethminer|  ethminer version 0.14.0.dev3
  m  11:58:48|ethminer|  Build: linux / release +git. 83693003
 cu  11:58:49|ethminer|  Using grid size 8192 , block size 128
  m  11:58:50|ethminer|  not-connected
  ℹ  11:58:50|stratum |  Connected to daggerhashimoto.eu.nicehash.com
  ℹ  11:58:50|stratum |  Spinning up miners...
  ℹ  11:58:50|cuda-0  |  No work. Pause for 3 s.
  ℹ  11:58:50|cuda-1  |  No work. Pause for 3 s.
  ℹ  11:58:50|stratum |  Extranonce set to 3e161e
  ℹ  11:58:50|stratum |  Subscribed to stratum server
  ℹ  11:58:50|stratum |  Authorized worker XXXXXXXXXXXXXXXXXXXX
  ℹ  11:58:50|stratum |  Difficulty set to 0.5
  ℹ  11:58:50|stratum |  New pool difficulty:  2.1475 gigahashes
  ℹ  11:58:50|stratum |  Received new job #89aa6f97… from daggerhashimoto.eu.nicehash.com
  ℹ  11:58:53|cuda-0  |  Initialising miner 0
  ℹ  11:58:53|cuda-1  |  Initialising miner 1
 cu  11:58:55|cuda-0  |  Using device: GeForce GTX 1070 Ti  (Compute 6.1)
 cu  11:58:55|cuda-1  |  Using device: GeForce GTX 1070 Ti  (Compute 6.1)
 cu  11:58:55|cuda-0  |  Set Device to current
 cu  11:58:55|cuda-0  |  Resetting device
 cu  11:58:55|cuda-1  |  Set Device to current
 cu  11:58:55|cuda-1  |  Resetting device
  m  11:58:55|ethminer|  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cu  11:58:55|cuda-1  |  Allocating light with size: 39452096
 cu  11:58:55|cuda-0  |  Allocating light with size: 39452096
 cu  11:58:55|cuda-0  |  Generating mining buffers
 cu  11:58:55|cuda-1  |  Generating mining buffers
 cu  11:58:55|cuda-1  |  Generating DAG for GPU # 1  with dagSize: 2524970368  gridSize: 8192
 cu  11:58:55|cuda-0  |  Generating DAG for GPU # 0  with dagSize: 2524970368  gridSize: 8192
  m  11:59:00|ethminer|  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  11:59:05|ethminer|  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  ℹ  11:59:08|stratum |  Received new job #c943d492… from daggerhashimoto.eu.nicehash.com
  m  11:59:10|ethminer|  Speed  52.21 Mh/s    gpu/0 26.23  gpu/1 25.97  [A0+0:R0+0:F0] Time: 00:00
  m  11:59:15|ethminer|  Speed  53.16 Mh/s    gpu/0 26.58  gpu/1 26.58  [A0+0:R0+0:F0] Time: 00:00
  ℹ  11:59:16|stratum |  Received new job #c6ed0d3b… from daggerhashimoto.eu.nicehash.com
  m  11:59:20|ethminer|  Speed  53.60 Mh/s    gpu/0 26.80  gpu/1 26.80  [A0+0:R0+0:F0] Time: 00:00

**Comment by SnowLeopard71** [comment]
Unless you can get `ethminer --list-devices` to show the AMD card, anything else you try is a waste of time.
You are probably missing at least one of the AMD packages...  `rocm-amdgpu-pro`

**Comment by Ben-and-Ellen** [comment]
>Unless you can get ethminer --list-devices to show the AMD card, anything else you try is a waste of time.

I agree. Please note that when I tried ethminer --list-devices it does show the AMD card. See first post and below:

$ uname -r
4.13.0-36-generic

$ dpkg -l amdgpu-pro
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  amdgpu-pro     17.40-492261 amd64        Meta package to install amdgpu Pr

$ ethminer --list-devices
Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[0] [0] GeForce GTX 1070 Ti
CL_DEVICE_TYPE: GPU
CL_DEVICE_GLOBAL_MEM_SIZE: 8513978368
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2128494592
CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
[0] [1] GeForce GTX 1070 Ti
CL_DEVICE_TYPE: GPU
CL_DEVICE_GLOBAL_MEM_SIZE: 8513978368
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2128494592
CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
[1] [0] Ellesmere
CL_DEVICE_TYPE: GPU
CL_DEVICE_GLOBAL_MEM_SIZE: 8571142144
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1070 Ti
Compute version: 6.1
cudaDeviceProp::totalGlobalMem: 8513978368
Pci: 0000:0c:00
[1] GeForce GTX 1070 Ti
Compute version: 6.1
cudaDeviceProp::totalGlobalMem: 8513978368
Pci: 0000:0e:00

**Comment by smurfy** [comment]
Really strange problem. ``ethminer -X --opencl-platform 1 -SP 2 -S xxxx -O xxxx``
Should work and mine with 2x cuda and 1x opencl (amd card)
Also
``ethminer -G --opencl-platform 1 -SP 2 -S xxxx -O xxxx`` 
Should work too, but only mine with amd card.

Since you wrote you tested both variants before, i would suggest removing both nvidia cards and try if you can get it mining with just the amd card, with only the ``-G`` param set.

If this does not work, i think its some kind of driver issue.

**Comment by SnowLeopard71** [comment]
Is `rocm-amdgpu-pro` installed?

**Comment by editorfatih** [comment]
@smurfy
Today i've had this problem.
Strange, but when I wrote these parameters in the first place, I started to work

ethminer -X --opencl-platform 0 --farm-recheck 2000 -P stratum1+tcp://0x3b335bf71378fe3674bf8417ac8951fc3df6b7c5.pool01@eth-eu1.nanopool.org:9999

is this a bug?

**Comment by AndreaLanfranchi** [comment]
See #1128 #1049

**Comment by AndreaLanfranchi** [comment]
No feed back and related to an outdated release.
Closing.
