### ISSUE TITLE
Release build crash on AMD. 

### ISSUE THREAD

**Issue by lifeisdream** [ethereum-mining/ethminer#85]
genoil miner works with the same settings.

![image](https://user-images.githubusercontent.com/1473995/27664585-09ebaf86-5c71-11e7-8f91-c40003d7bf87.png)

Found suitable OpenCL device [Tonga] with 3221225472 bytes of GPU memory
  i  02:16:39|main  Connecting to stratum server eu1.ethermine.org:4444
  i  02:16:39|stratum  Connected to stratum server eu1.ethermine.org : 4444
  i  02:16:39|stratum  Starting farm
  i  02:16:39|stratum  Subscribed to stratum server
  i  02:16:39|stratum  Authorized worker 0xeFD56742Cb1cB724d2BB0e2B9D1Fe03F6389Df2f.owl2
  i  02:16:39|stratum  Received new job #82df85e1
  i  02:16:39|openclminer0  set work; seed: #2228076c, target: #0000000112e0
  i  02:16:39|openclminer0  Initialising miner...
  m  02:16:41|main  Mining on PoWhash #82df85e1 : 0.00MH/s [A0+0:R0+0:F0]
  m  02:16:43|main  Mining on PoWhash #82df85e1 : 0.00MH/s [A0+0:R0+0:F0]
Using platform: AMD Accelerated Parallel Processing
Using device: Tonga(OpenCL 1.2 AMD-APP (2348.3))

**Comment by lifeisdream** [comment]
crash appears to be here : program.build({ device }, options);
and somehow it don't catch exception there =(

**Comment by lifeisdream** [comment]
same for -U mode

**Comment by maxcr** [comment]
Running fine in Linux for me.

**Comment by maxcr** [comment]
I'm using GCN1.2 Sea Islands tho

**Comment by chfast** [comment]
Can you try "Windows-dbg" build to maybe get more information about the crash?

**Comment by EoD** [comment]
@lifeisdream Your Tonga advertises OpenCL 1.2, are your drivers up to date? Could you also test it with a more recent build of ethminer?

I cannot reproduce your crash on similar hardware.

**Comment by rkjames** [comment]
I can reproduce this exact failure (program.build derefs null in amd cl dll) if I build 32-bit, no repro if I build 64-bit.
