### ISSUE TITLE
NO_COLOR environment variable results in crash

### ISSUE THREAD

**Issue by pengc99** [ethereum-mining/ethminer#850]
Running ethminer with NO_COLOR environment variable results in a crash:

```
$ NO_COLOR=1 /usr/local/src/ethminer.bin/ethminer -U -S us1.ethermine.org:5555 -O ethereum_address.worker_name --stratum-ssl 0
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted
```

**Comment by pengc99** [comment]
This is with the latest pre-release ethminer 0.14.0.dev3

**Comment by smurfy** [comment]
https://github.com/ethereum-mining/ethminer/blob/74417c7a9bb51ed2413375cee1685b399ce64e7d/libdevcore/Log.cpp#L127

i use ``std::regex e("\e\[[0-9;]+m");`` somewhere else to clean colors. only tested on linux.

**Comment by jean-m-cyr** [comment]
I think some versions of regex don't like the un-nested brackets.
