### ISSUE TITLE
stopped after recieve new work (after 14 dev2)

### ISSUE THREAD

**Issue by darotchou** [ethereum-mining/ethminer#852]
in my rig, there's no problem before 14 dev1(13 is also ok). after change to dev2 or dev3 it will halt after receive new work.
Any suggestion?

Windows 10
2 gtx 1070 with driver 390.77
batch file:
ethminer -SP 2 -U -S daggerhashimoto.eu.nicehash.com:3353 -O wallet:x --cuda-parallel-hash 4 --cuda-grid-size 8192 --cuda-block-size 128

**Comment by smurfy** [comment]
any error message?

**Comment by DeadManWalkingTO** [comment]
GTX1060 +150/+500/65%TDP @ 23-24 MH/s
GTX1070 +150/+500/65%TDP @ 32-33 MH/s

Windows
-------

1. Try Update Drivers.
Download and install the latests.

2. Try Update Ethminer.
Download (or beter build) the latest.

3. Try use -U for CUDA devices.
CUDA Hardware Test Launch Command:
```
ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.hardwaretest
```

4. Try to change P2 State and Power managment mode.
You can use [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW).
For the best mining hashrate choose from sector "5 - Common":
    - CUDA - Force P2 State (Set to "Off")
    - Power managment mode (Set to "Prefer maximum performance")

5. Try Tweak Win10.
You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) (#695).

6. Try Optimize/Overclock GPUs. 
You can use [MSI Afterburner](https://www.msi.com/page/afterburner) for GPU OverClock/Optimize. 

7. Try use a WatchDog
You can use [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) (#735).

Please feedback.
Thank you!

**Comment by jean-m-cyr** [comment]
I believe nicehash requires a BTC address for userid, not a ETH address. When a BTC address is specified as userid we get:

  ℹ  12:44:39|stratum |  Authorized worker 1E8Mp..............uYkU7K59t
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<dev::BadHexCharacter>'
  what():  BadHexCharacter

**Comment by jean-m-cyr** [comment]
Works correctly for me!

ethminer -SP 2 -U -G -S daggerhashimoto.eu.nicehash.com:3353 -O xxxxxxxxxxxxxxxxU5aiQuYkU7K59t:x --cuda-parallel-hash 4 --cuda-grid-size 8192 --cuda-block-size 128

  ℹ  12:57:12|cl-0    |  Nonce 0x776785001c4a50c9 submitted to daggerhashimoto.eu.nicehash.com
  ℹ  12:57:12|stratum |  **Accepted  in 128 ms.

**Comment by smurfy** [comment]
Closing this, @darotchou feel free to add error message and we can reopen/fix your issue

**Comment by darotchou** [comment]
Sorry for late to reply. the status is as the image. By the way. When I change the console to old version, it works but the display is not color and the display is very slow.(the function to change the version of console is provided by windows 10. I can change the default setting to older version console)

![default](https://user-images.githubusercontent.com/10337638/37241466-8ec09f78-2494-11e8-8070-d2c2064f9a31.png)

**Comment by smurfy** [comment]
hm, i d

**Comment by darotchou** [comment]
The version you provided works....thanks a lot.
And to switch console version means
1.open the command line console
2.move the mouse to the top of the console, and click right key of the mouse
3.select "default value"(mine is traditional Chinese version)
4.choose the first tab(maybe called "option")
5.there is a checkbox in the bottom. its "to use old version console"(need restart)

![1](https://user-images.githubusercontent.com/10337638/37242179-e4ca03fe-249f-11e8-8382-870a65b55b89.png)

**Comment by darotchou** [comment]
After test for 12hrs. It can run but the stability is still not as good as ver 13.
But I'm still curious about the root cause of 14.0.dev2 stop problem.

I check the comment of the updated version of dev3 you provided to me is 
"Make sure all stratum IO is handled asynchronously from a single thread"

Does it mean maybe I can also solve the "stop problem" by using multi thread?? if yes, how can I do?

**Comment by AndreaLanfranchi** [comment]
To address this problem please use 0.14.0rc9 or 0.15.0dev7 and report back.
