### ISSUE TITLE
Below average hashrate on GPU/0 of 6 GPUs

### ISSUE THREAD

**Issue by 58851** [ethereum-mining/ethminer#855]
Hello,

With overclocking, GPUs 1 - 5 average 31.6 MHs. However, GPU/0 hashes at 25 Mhs. Sometimes, it'll hash just at the same speed as its siblings. I was once able to resolve the issue by reverting to the 390.77 NVidia drivers (using this version still). But the issue has re-occurred. Is this a ethminer, NVidia driver issue, riser, or GPU problem? What's the solution? Thanks

I am mining with the following command: ethminer.exe --cuda --dag-load-mode sequential --farm-recheck 200 --stratum us1.ethermine.org:14444 --stratum-failover us2.ethermine.org:14444 --userpass [address_removed] --report-hashrate

EDIT: Using ethminer version 0.13.0

**Comment by DeadManWalkingTO** [comment]
It's a common Windows problem.
1 GPU used by desktop. 5-7 MHs down.

**Comment by 58851** [comment]
@DeadManWalkingTO 

But Windows is actually using the on-board/integrated motherboard GPU.

**Comment by 58851** [comment]
@DeadManWalkingTO 

You were right! I checked in the Task Manager, and even though the monitor is connected to the onboard/integrated motherboard GPU and the video signal is displayed on it, GPU/0 does the Windows GUI processing. The interesting part is that it is initially processed by the onboard GPU, and then switches over to GPU/0 if I connect via Remote Desktop. The issue is not duplicated if I connect via VNC.

Thank you for pointing me in the right direction. I was leaning towards a bad riser. It's actually a Windows thing.
