### ISSUE TITLE
0.14dev3 Windows - CUDA error in func set_header;

### ISSUE THREAD

**Issue by elcopdoo** [ethereum-mining/ethminer#857]
I still get that error on GTX 1060 6GB and also GTX960M 4GB, fresh win boot and about 1 minute after starting ethminer it terminates:
"Fatal GPU error: CUDA error in func dev::eth::CUDAMiner::search at line 147 the launch timed out and was terminated."
Sometime is at line 503.
I have last version of ethminer from appveyor (ethminer version 0.14.0.dev3
m 05:10:02|main | Build: windows / release +git. 5726f49)

**Comment by elcopdoo** [comment]
C:\ETH_MINER>Start_ETH.bat

C:\ETH_MINER>setx GPU_FORCE_64BIT_PTR 0

SUCCESS: Specified value was saved.

C:\ETH_MINER>setx GPU_MAX_HEAP_SIZE 100

SUCCESS: Specified value was saved.

C:\ETH_MINER>setx GPU_USE_SYNC_OBJECTS 1

SUCCESS: Specified value was saved.

C:\ETH_MINER>setx GPU_MAX_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\ETH_MINER>setx GPU_SINGLE_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\ETH_MINER>ethminer.exe -U -S eu1.ethermine.org:4444 -O xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxx
  m  05:38:20|main    |  ethminer version 0.14.0.dev3
  m  05:38:20|main    |  Build: windows / release +git. b501185
 cu  05:38:20|main    |  Using grid size 8192 , block size 128
  m  05:38:21|main    |  not-connected
  i  05:38:21|stratum |  Connected to eu1.ethermine.org
  i  05:38:21|stratum |  Spinning up miners...
  i  05:38:21|cuda-0  |  No work. Pause for 3 s.
  i  05:38:21|stratum |  Subscribed to stratum server
  i  05:38:21|stratum |  Authorized worker xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  i  05:38:21|stratum |  New pool difficulty:  4.0000 gigahashes
  i  05:38:21|stratum |  Received new job #302eb96f... from eu1.ethermine.org
  i  05:38:24|cuda-0  |  Initialising miner 0
  i  05:38:24|stratum |  Received new job #7d1e6790... from eu1.ethermine.org
  m  05:38:26|main    |  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cu  05:38:30|cuda-0  |  Using device: GeForce GTX 960M  (Compute 5.0)
 cu  05:38:30|cuda-0  |  Set Device to current
 cu  05:38:30|cuda-0  |  Resetting device
 cu  05:38:30|cuda-0  |  Allocating light with size: 39452096
 cu  05:38:30|cuda-0  |  Generating mining buffers
 cu  05:38:30|cuda-0  |  Generating DAG for GPU # 0  with dagSize: 2524970368  gridSize: 8192
  m  05:38:31|main    |  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  05:38:36|main    |  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  i  05:38:36|stratum |  Received new job #9c63875e... from eu1.ethermine.org
  m  05:38:41|main    |  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  05:38:46|main    |  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  i  05:38:47|stratum |  Received new job #6ecd7499... from eu1.ethermine.org
  m  05:38:51|main    |  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  i  05:38:55|stratum |  Received new job #849b5ed1... from eu1.ethermine.org
  m  05:38:56|main    |  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  05:39:01|main    |  Speed   1.05 Mh/s    gpu/0  1.05  [A0+0:R0+0:F0] Time: 00:00
  m  05:39:06|main    |  Speed   1.40 Mh/s    gpu/0  1.40  [A0+0:R0+0:F0] Time: 00:00
  m  05:39:11|main    |  Speed   1.75 Mh/s    gpu/0  1.75  [A0+0:R0+0:F0] Time: 00:00
  X  05:39:11|cuda-0  |  Fatal GPU error: CUDA error in func dev::eth::CUDAMiner::search at line 503 the launch timed out and was terminated
  X  05:39:11|cuda-0  |  Terminating.

**Comment by jean-m-cyr** [comment]
Does this happen when not overclocking?

**Comment by XhmikosR** [comment]
I hit this issue too with latest master. I haven't tried without overclocking but the same rig with the same config works fine with v0.13.

**Comment by AndreaLanfranchi** [comment]
Stale issue. Closing.
