### ISSUE TITLE
Use this with nicehash

### ISSUE THREAD

**Issue by BIG1** [ethereum-mining/ethminer#858]
Hi.
What settings to use to mine to my nicehash wallet? Using amd.

**Comment by kkkrackpot** [comment]
@BIG1 
`ethminer -G -S daggerhashimoto.eu.nicehash.com:3353 -O [your ETH wallet] --stratum-protocol 2`

**Comment by BIG1** [comment]
Should I download dbg ot the other version for windows?

**Comment by kkkrackpot** [comment]
@BIG1 "ordinary" binary for windows.
You don't need "dbg" versions unless you're going to do development.

**Comment by BIG1** [comment]
Thanks.

But according to nicehash website the correct line is:
ethminer -SP 2 -G -S daggerhashimoto.eu.nicehash.com:3353 -O BTCWALLET

**Comment by AndreaLanfranchi** [comment]
-SP 2 is the short version of --stratum-protocol 2

The rest is the same.

**Comment by BIG1** [comment]
It seeme like -SP and --stratum-protocol is deprecated.
How to use this command different with -P ?

**Comment by Hakkk2002** [comment]
-SP 2 without SSL is -P stratum2+tcp://.....................

**Comment by rgaufman** [comment]
I get the following when I try the command:
```
$ ./ethminer -G -S daggerhashimoto.eu.nicehash.com:3353 -O UNIQUE_BTC_ADDRESS_HERE --stratum-protocol 2

The following arguments were not expected: -S -O --stratum-protocol
```

I also tried the one in the last command but getting:

```
$ ./ethminer -G -P stratum2+tcp://daggerhashimoto.eu.nicehash.com:3353 -O UNIQUE_BTC_ADDRESS_HERE

The following argument was not expected: -O
```

Any ideas?

**Comment by rgaufman** [comment]
Thank you, that works :)

**Comment by samueldnj** [comment]
Hi all, I'm trying to set the m1 version of ethminer up to connect to nicehash, does anyone have any insights?

I'm following the above approach from mekkachi, Aug 13 2018

> use: ethminer -P stratum2+tcp://bitcoinadress.workername@daggerhashimoto.eu.nicehash.com:3353 -U (or -G foramd)

But I get the following output

> X 14:23:25          Got unknown method [mining.set_difficulty] from pool. Discarding...
> X 14:23:25          Stratum got invalid Json message : BadHexCharacter

Not sure where to go from here, this is my first day!

**Comment by StefanOberhumer** [comment]
Unsure and not tested:
It seems nicehash has change the ports

Try: option ```-P stratum2+ssl://bitcoinadress.workername@daggerhashimoto.auto.nicehash.com:443```

(refer to: https://www.nicehash.com/algorithm/daggerhashimoto )
