### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by manotroll** [ethereum-mining/ethminer#86]
Is the list of commands to use with VGA AMD?

**Comment by omento** [comment]
Run `ethminer --help` to get the full list of arguments. For using with an AMD GPU, you need to run with OpenCL. So run ethminer with the `-G` flag.

**Comment by manotroll** [comment]
I used the same commands as ethminer-0.9.41-genoil-1.1.9
Plus the income and the same

**Comment by omento** [comment]
Apologies, I don't quite understand. Were you expecting a hashrate increase? The latest improvements were only for CUDA cards, specifically the Pascal generation. Based on the Pull Requests, though, it does look like some OpenCL improvements are coming.

**Comment by manotroll** [comment]
Okay, I use amd cards.
