### ISSUE TITLE
List of devices empty (Centos 7)

### ISSUE THREAD

**Issue by jllados** [ethereum-mining/ethminer#862]
Hi,

I'm want to reuse an old computer to mine some ether. The problem is that the miner doesn't recognize the graphic card (HD6970).

**ethminer --list-devices -G**

    $ Listing OpenCL devices.
    $ FORMAT: [platformID] [deviceID] deviceName

I installed the 15.12-7 drivers from wolfy's testing repository (kmod-fglrx and fglrx-x11-drv).

    $ http://wdl.lug.ro/fglrx/testing/

I did the: **aticonfig --initial** and the **aticonfig --list-adapters** returned the correct graphic card.

    $ * 0. 03:00.0 AMD Radeon HD 6900 Series
    $ * - Default adapter

This is the output of **clinfo**

    $ Number of platforms:                             1
    $ Platform Profile:                              FULL_PROFILE
    $ Platform Version:                              OpenCL 2.0 AMD-APP (1912.5)
    $ Platform Name:                                 AMD Accelerated Parallel Processing
    $ Platform Vendor:                               Advanced Micro Devices, Inc.
    $ Platform Extensions:                           cl_khr_icd cl_amd_event_callback cl_amd_offline_devices
    $ Platform Name:                                 AMD Accelerated Parallel Processing
    $ ERROR: clGetDeviceIDs(-1)

Any idea? 

Thanks

**Comment by ryan-ronnander** [comment]
@jllados Does it work with sudo or under root? I've had lots of issues running the official amdgpu-pro stack on CentOS 7 as a non-root user trying to take advantage of OpenCL applications. FGLRX is also ancient and unmaintained at this point.

**Comment by AndreaLanfranchi** [comment]
No feed back in 2 months.
Closing.
