### ISSUE TITLE
0.14.0dev3 - strange chars appended to new work headers... ?

### ISSUE THREAD

**Issue by kozmic83** [ethereum-mining/ethminer#867]
- Ver: 0.14.0dev3
- OS: Windows 10
- GPUs: one GTX1070, three GTX1050ti, & three GTX970
- Solo mining to musicoin node on local network: GMC/v2.5.3-stable/linux-amd64/go1.9.2

Ethminer output throwing interesting characters appended to the end of every new work header string. Any thoughts on what might be causing this? I don't see this running 0.13 stable (I shut down 14dev3, re-launch with 13stable, new work headers look normal, then re-launch with 14dev3, and I see the same weird chars). I will post a pic.

Thanks!

![ethminer0140dev3](https://user-images.githubusercontent.com/37196772/37182390-b05e0d68-22f6-11e8-809b-4bd6a19f93ac.png)

**Comment by smurfy** [comment]
I think fixed with #856

**Comment by kozmic83** [comment]
Thanks quick for the reply - okay great... I don't believe it actually impacts mining... I pointed this same node to a testnet, and was immediately mining blocks from this rig running 14dev3 with no issue... I will let it run against a real network until we have a dev4 release and then test again.
