### ISSUE TITLE
master yields constant rejects when --cuda-noeval is used

### ISSUE THREAD

**Issue by aleqx** [ethereum-mining/ethminer#868]
Just compiled it, fresh git clone, on Linux. Anyone else? 0.12 has no issues.

I feel that ever since 0.13dev there have been a lot of buggy releases. What is the latest known working version (which also doesn't have disconnection/ctrl-c problems)?

Is there a 0.13/14 tag that is known to be stable?

**Comment by RB3rg** [comment]
It seems for me 013-dev0 is ok, 
I have 50% of the rigs with 013-dev0 and other 50% with 014-dev2
3 rigs with the latest for testing.

**Comment by jean-m-cyr** [comment]
Yes, the --cuda-noeval option seems to have been broken somewhere along the way.

**Comment by DeadManWalkingTO** [comment]
#861 same issue!

**Comment by aleqx** [comment]
As @jean-m-cyr confirmed, the --cuda-no-eval is now broken ... he is the one who introduced this optimization but I don't think he's the one who broke it.

@jean-m-cyr @smurfy ?

**Comment by AndreaLanfranchi** [comment]
Confirm same behavior

**Comment by XhmikosR** [comment]
This should have been fixed already in master.
