### ISSUE TITLE
What´s the best eth miner?

### ISSUE THREAD

**Issue by BIG1** [ethereum-mining/ethminer#869]
So... what´s fastest and cheapest of Claymore, Phoenix and Ethminer?

**Comment by AndreaLanfranchi** [comment]
What question is this ?
You're comparing apples with oranges.

Both Claymore and Phoenix are closed source programs ie. you do not really know if the dev is playing fair. In addition they have devfee.

Ethminer is open source and has no fees. (which is, at least for me, priceless).

So what's the point ?

**Comment by BIG1** [comment]
If claymore gives 4% better performance (as he claims) for 1% fee it may be the best miner?

**Comment by AndreaLanfranchi** [comment]
This is not an issue about ethminer.
Do your maths and tests. Run 24 hours on claymore, then 24 hours on Phoenix then 24 hour on ethminer.
This is the only result which may answer your question numerically.

For me there is no competition: open-source forever even if I might loose 1 or 2 percent points.

**Comment by smurfy** [comment]
then use claymore or phoenix which allegedly stole claymores kernels and has lower fee.
I would suggest run two miners in parallel on two rigs/cards  and compare the ACTUAL result on the pool. Over at least 24hours.

Then decide.

**Comment by BIG1** [comment]
Thanks. Will try that.

AndreasLan: Since ethminer doesnt have a forum we can only use github page.

Should I download dbg version or the other version for windows?

**Comment by Fox801** [comment]
I use the dbg one and it works just fine, although I'm not sure what it means or the differences between the two.

**Comment by Olegatorius** [comment]
The DBG version contains debug information for the developers to help debug the application I believe.

**Comment by ludvanieztha** [comment]
Hey all why u can said ethminer is not cointain fee? Where i can find forum or something about the devfee ethminer?

**Comment by rwaters71** [comment]
ethminer = open source, no dev fee, and ~same hashrate as Claymore/Phoenixminer.

**Comment by ikonspirasi** [comment]
hi, i just tried the ethminer-0.14.0.dev3-Windows version and it works fine, it is less 6 mh/s than claymore but i will try this until my next payout. so far love this ethminer new colorful lines

**Comment by GrannyCryptomaster** [comment]
Hashrates are the same in ethminer and Claymore. I tested both for 24h, with 6h pause between. I don't look at hashrates and accepted shares, I just look at the profits. It's the only thing that matters.
So, ethminer gave me 2,5% more ETH than Claymore's.
I must mention that I used Claymore's 11.3 that had some problems with stale shares (I saw that on ethermine), but now in version 11.5 it seems they resolved it. I used ethminer 14.0.dev3. It was very stable and reported corectly the hashrates. Now I started Claymore 11.5 and I will update this post after the 24h test.
If both miners have the same efficiency, the difference must be only 1% - Claymore's dev fee.
I like no dev fee and open source too.

**Comment by GrannyCryptomaster** [comment]
UPDATED!

**Comment by BIG1** [comment]
Wow. Thanks GrannyCryptomaster!
Claymore gives 0.8% more eth? But with 1% devfee it means that we loose -0.2% ? (0.8-1) ?

**Comment by GrannyCryptomaster** [comment]
Nope. Claymore makes 1,8% more ETH, 1% dev fee and 0,8% yours. Read again. "dev fee" means that it  mines 1% of the time to dev address.

**Comment by BIG1** [comment]
Ofcourse. My mistake.
Some people claims that he takes even more. If u add time it takes to reconnect and disconnect time used for devfee etc.

**Comment by rwaters71** [comment]
@GrannyCryptomaster the difference is within the margin of error - pools are luckier some days, and crypto prices/difficulty are moving targets as well. Considering all that, you'd have to mine the same pool at the same time with the same hardware/settings to get an accurate result.  Your testing is still appreciated and meaningful, I just had to add that, especially sincw we're discussing 0.8% difference :)

**Comment by GrannyCryptomaster** [comment]
I'm really not an expert, and I still didn't understood the exact mechanics of mining and pool rewarding system, and that's why I said that 0,8 % is negligible, because I thaught that maybe there are some factors of variance that I didn't know and I don't want people to take this test as a main factor of choosing a miner.
I don't take sides, I personnaly like free ware and open sources, but in this mining bussiness I must look for what is more profitable. If Claymore comes with a miner that it's obviously more profitable, than OK, I'll use it, and accept that 1% dev fee. If both miners give same profits, I go with open source, because of the obvious advantage of knowing what I run on my rig and there is no doubt of hidden agendas.

**Comment by Angel996** [comment]
For me, ethminer is a bit faster on Nvidia cards and about the same hashrate on AMD cards. All this is simply amazing. Provided ethminer is actually open source.
