### ISSUE TITLE
Try 2GB GPU solution

### ISSUE THREAD

**Issue by honlen** [ethereum-mining/ethminer#87]
I'm trying to build ethminer without GPU DAG file, i.e. calculate it for every search loop.
This may be helpful for 2GB GPU.
Would you please give me some help to do it?

**Comment by Genoil** [comment]
There is no point in doing this. I looked into it a few years ago. It will be dead slow.

**Comment by honlen** [comment]
It is good. 
I want to look into it, now. 
Can you share me your tried code about it?

**Comment by honlen** [comment]
I think a few days later, 3GB GPU will need it, then 4G GPU.

**Comment by Genoil** [comment]
It is basically all there already. Just replace the DAG access code with calls to calculate the node in real time, taken from the DAG generation kernel. To make it faster, just use regular DAG up to 2GB and only make the 2GB+ part dynamic.

**Comment by honlen** [comment]
Got it.
Thank you, Genoil.

**Comment by honlen** [comment]
Dear Genoil,
I tried, but it is not working.
Could you please send me your code that replace the DAG access code with calls to calculate the node in real time.
Thank you.


honlen@qq.com
 
From: Genoil
Date: 2017-06-29 15:24
To: ethereum-mining/ethminer
CC: honlen; Author
Subject: Re: [ethereum-mining/ethminer] Try 2GB GPU solution (#87)
It is basically all there already. Just replace the DAG access code with calls to calculate the node in real time, taken from the DAG generation kernel. To make it faster, just use regular DAG up to 2GB and only make the 2GB+ part dynamic.

**Comment by Genoil** [comment]
I'm sorry, this is the closest thing I have currently. Dig into CL for a bit and you should be able to tie the strings together. I don't gave time to do it myself.

**Comment by YanBellavance** [comment]
there is a _copyToHost parameter in : libethash-cuda\ethash_cuda_miner.cpp
perhaps it could be of help
