### ISSUE TITLE
Getting clGetPlatformIDs Error in some rigs (not all) with dev3

### ISSUE THREAD

**Issue by RB3rg** [ethereum-mining/ethminer#870]
Just compiled the lastest release 014-dev3-de05cc3 and about 10% of my rigs exit with clGetPlatformIDs Error.

`  m  07:40:24|ethminer|  ethminer version 0.14.0.dev3`
`  m  07:40:24|ethminer|  Build: linux / release +git. de05cc3`
` cu  07:40:25|ethminer|  Using grid size 8192 , block size 128`
`Error: clGetPlatformIDs`

All the rigs work with 0.14.0.dev2.
All the rigs are identical hardware and software (1060, same MB, same nvidia 390.25. Linux), not sure why it works in 90% and fail in 10% as the same ones work with dev2.

Any clue?

**Comment by AndreaLanfranchi** [comment]
Closing.

Feel free to post a new issue with latest releases of ethminer if problem persists
