### ISSUE TITLE
Ethminer crashes on new DAG file generation - v0.14.0.dev3

### ISSUE THREAD

**Issue by rwaters71** [ethereum-mining/ethminer#871]
Using 0.14.0.dev3, with the following command line under Windows 10 Pro:
ethminer -U -S .... -O ....  --cuda-schedule auto --dag-load-mode single 0 --display-interval 8 --exit --farm-recheck 5000

It runs great until, a few hours later it crashes when it has to change DAG files, the last lines I see are in the screenshot:
![ethminer_1](https://user-images.githubusercontent.com/8212123/37243280-e5f34ba6-2444-11e8-85fd-848c8de7f2e9.gif)

After that last line, the miner crashes with: "ethminer.exe has stopped working. A problem caused the program to stop working correctly" 

This then stops with a Windows dialog that prevents my my batch script from restarting it, etc. It only seems to happen at DAG generation/copying, after the miner disconnect/reconnects to the pool.

The interesting part is it doesn't happen the first time it is started...

**Comment by bmatthewshea** [comment]
`--cuda-schedule auto --dag-load-mode single 0 ` why?

**Comment by rwaters71** [comment]
I am removing "--dag-load-mode single 0" to test out, but it is hard to test to generate the crash, it takes hours. As to why I am using a dev build... rly? Just a personal choice.

I am not complaining, I am just reporting a possible issue to help debug.

**Comment by bmatthewshea** [comment]
Cool just had to state that - I see many who grab newest dev build and complain it's broken w/o ever trying a release or older build. May want to consider a 'watchdog' process to watch for crashes and restart it as needed. I just use a cron job under Linux - not sure on Windows.. I see you are renting it out, too.

**Comment by jean-m-cyr** [comment]
DAG recalculation occurs with epoch changes. Epochs changes do not occur every 'few hours'.

**Comment by rwaters71** [comment]
As previously mentioned, I use miningpoolrentals. When someone rents the rig (in a few hours), the miner reconnects to a new pool, and the DAG recalculation seems to occur, as per the above screenshot.

**Comment by jean-m-cyr** [comment]
Does it necessarily reconnect to the same dagger-hashimotto coin type?

**Comment by rwaters71** [comment]
@jean-m-cyr  ah yes, that is entirely possible. I am not sure whether that occurs though, or the client.reconnect algorithm somehow prompts the miner to do the DAG recalculation. Either way, it seems to crash around that DAG recalculation point in time only.

**Comment by jean-m-cyr** [comment]
Does it actually crash (as in terminate), or just hang (go silent on the console)?

**Comment by rwaters71** [comment]
Actual exe crash, with the Windows popup dialog: "ethminer.exe has stopped working. A problem caused the program to stop working correctly..."

**Comment by jean-m-cyr** [comment]
Ah Windows.... Sorry can't help much with that.

**Comment by rwaters71** [comment]
Yeah, could be Windows-specific.

**Comment by jean-m-cyr** [comment]
The reason I was asking is that some work on farm.stop, including stopping the farm around disconnects, and was wondering if it could be related?

**Comment by rwaters71** [comment]
There is a way to close the crash dialog automatically using the Windows Registry, I suppose this could be closed because it is easily mitigated by restarting the miner. Still, maybe it is worth to look at some additional error-handling, idk.

**Comment by bmatthewshea** [comment]
Was reading - yes you typically will have mining rentals jump to different D-H/ethash coins. That could also (partly) explain the exception.. just generate new dag each time (default) and I think you're problem is solved. I do not think copying it is a good idea if you are renting it out...?

**Comment by rwaters71** [comment]
I haven't noticed it last couple of days with the default DAG load. My thinking was just that such exception should possibly be caught/handled.
