### ISSUE TITLE
ConfigureEthminer to mine with only "X" card

### ISSUE THREAD

**Issue by charleshap** [ethereum-mining/ethminer#873]
So. This is my question. But, it's a gaming rig. I wouldto be able to run GPU0 on its own instance and GPU1 ~2 ~3 on another. This way I can turn off mining on the main GPU while I game. Instead of shutting down the entire process. What command would I need to add to the config file to achieve this? Thanks

**Comment by aleqx** [comment]
See --help and --cuda-devices

**Comment by charleshap** [comment]
Ty, i see --cuda-devices 0 1 , and works !

**Comment by pimovietc** [comment]
--cuda-devices 2 3 works fine for me in v0.14.0.dev3. It does name them GPU0 and GPU1 tho, but they are definitely the 3rd and 4th card in the system.

**Comment by smurfy** [comment]
@charleshap what cards do you have
@pimovietc well the cuda order can be different than the driver/nvml order. use ``--list-devices``  to identify. Are you on windows or linux?

**Comment by pimovietc** [comment]
@smurfy The cuda order CAN be different (I have never seen this tho) sure, however I can confirm you that the GPU0 and GPU1 is purely the names the ethminer gives them. They are in fact the 3rd and 4th card in the system. Hell, if I boot up two instances of ethminer, one running device 1 and the other device 3 it will name both of them GPU0 in each separate instance. (in other words, the GPU# naming is restricted to the running instance only and has nothing to do with the actual card)

**Comment by AndreaLanfranchi** [comment]
Resolved by #1704
