### ISSUE TITLE
Exit program when disconnect

### ISSUE THREAD

**Issue by ludvanieztha** [ethereum-mining/ethminer#874]
Hey all wanna asking where i can learn and read parameter list so i can configure why the miner to keep reconnecting while disconnect around 10 mins and back to connect but auto closed the program because i read in readme md there is nothing to do

**Comment by rwaters71** [comment]
you can use the -h command-line parameter to see a list of all available options:

'''
ethminer -h
'''

I don't think ethminer has a parameter to exit when disconnected from the pool? (The --exit parameter keeps retrying after 3 seconds delay when disconnected from the pool):

![ethminer_exit](https://user-images.githubusercontent.com/8212123/37347667-bcf56ea8-26a8-11e8-9915-f126ff2bbf6f.gif)


A parameter to exit on disconnect (or specify a finite number of retries) would be very useful. For example, the miningpoolhub auto-switch ports (12xxx) disconnect you from the pool and allow you to connect to a different port for your next miner/algo. This can't work if the miner keeps trying to reconnect without exiting. Many other miners have a parameter to exit on disconnect so restarting can be handled externally.

**Comment by papampi** [comment]
+1 on this.

**Comment by rwaters71** [comment]
Yeah, didn't work with dev3, what I saw was:

```
Could not resolve host exit:exit, The specified class was not found
Disconnected from exit
```

With dev4, and both parameters it exits after the third reconnect attempt with:

``` 
Exiting because reconnecting is not possible
Shutting down
```
Thanks for that. Still a bit awkward/counter-intuitive to me/undocumented but it works 👍 
imho would be easier with just: --farm-retries 0 or --farm-retries 1

**Comment by ludvanieztha** [comment]
ty for all support i think i just try --farm-retries 0 --exit
