### ISSUE TITLE
Crash with latest master on Ctrl+C

### ISSUE THREAD

**Issue by XhmikosR** [ethereum-mining/ethminer#877]
So, I'm using this in one of my rigs:

```
C:\Users\xmr\Desktop>ver

Microsoft Windows [Version 10.0.16299.251]

set CUDA_DEVICE_ORDER=PCI_BUS_ID
ethminer.exe --report-hashrate --exit --cuda --stratum eu1.ethermine.org:4444 --stratum-failover us1.ethermine.org:4444 --userpass 0xxxxx

C:\Users\xmr\Desktop>ethminer.exe --version
ethminer version 0.14.0.dev3+git.fa1f2bb
Build: windows/release/msvc
```

The issue: every time I hit Ctrl+C, ethminer is crashing. The crash does not happen with v0.13. Not sure what more info could help you guys.

Note that the crash happens after I see this in the output:

```
  X  15:21:37|stratum |  Read response failed: The network connection was aborted by the local system
  i  15:21:37|main    |  Disconnected from eu1.ethermine.org
  i  15:21:37|main    |  Shutting down miners...
```

**Comment by jean-m-cyr** [comment]
Been having issues with Ctl-C and disconnect for a while now. In my case it started around the pool manager restructure.

**Comment by XhmikosR** [comment]
I cannot reproduce now anymore...

I just feel like the latest master version is less forgiving when errors happen due to overclocking, or something like that. Because I was also hitting the #880 error too, but now that doesn't seem to happen either.

I'm gonna close the issue and comment if I find out something else.
