### ISSUE TITLE
Ubuntu 16.04.02 LTS  wont mine with RX 550

### ISSUE THREAD

**Issue by cryptomine** [ethereum-mining/ethminer#88]
I've been trying to get the RX550 4GB cards to run under Ubuntu 16.04.02 LTS but haven't had much luck. I've currently only tried the AMDGPU-PRO driver but I was going to test the radeon driver soon. The card mines under Windows So the issue is probably driver side in linux. 

The card being polaris 12 instead of 11 might be the source of some issues. I'd gladly donate some ETH to anyone who can help me get these cards mining under Linux

**Comment by nikolehto** [comment]
Does it freeze on OPENCL#0 99% - check #77

**Comment by cryptomine** [comment]
Nope, It doesn't even start

"[OPENCL]:No OpenCL platforms found
No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument
"

With any other Card I plug into the pcie slot, it works fine, it just doesn't work with the RX 550 4GB

**Comment by chfast** [comment]
Can you try `clinfo` or similar tool to check out your OpenCL platforms?

**Comment by calvintam236** [comment]
I tried to setup my RX470 on ubuntu 16.04.2 as well. No luck.
My setup: AMD RYZEN 1700X + RX470 GRAPHIC with AMDGPU-PRO driver

Tried with `-G`:
`--opencl-platform 1`
`--opencl-device 1`

`clinfo` does list both my CPU and GPU.

**Comment by tperalta82** [comment]
try running as root (sudo. ..... )

**Comment by calvintam236** [comment]
I am running all commands on `root` already.

**Comment by ljordan-pea** [comment]
Any luck with this

**Comment by dan-and** [comment]
It is a known driver issue at AMD. Let's wait for new amdpro gpu drivers

**Comment by derubm** [comment]
--opencl-device 2 , as deivce 1 is prob. your CPU.

**Comment by dan-and** [comment]
@derubm thats may be true for rx 560, 570 and 580, but the current amdgpu pro drivers are just broken, so you only see the CPU platform and no GPU-Platform. It will be fixed in the next amdpgu pro drivers. 

See: 
https://community.amd.com/thread/217469

**Comment by cryptomine** [comment]
If the new AMD Catalyst driver doesn't fix the RX550 issue then I'll gladly throw in 5eth to the pool to anyone who gets it working with the AMD Radeon drivers and Open source OPENCL if possible, AMD OPENCL otherwise.

https://signal.org/blog/bithub/
might be an interesting idea for the ethminer project as a whole.

**Comment by dan-and** [comment]
AMDGPU Pro 17.40 is released.

http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Driver-for-Linux-Release-Notes.aspx 

Good luck testing

**Comment by cryptomine** [comment]
Just updated to Ubuntu 16.04.03LTS and AMDGPU Pro 17.40 and that didn't fix it. I think this issue should be closed since the issue is with the driver and not ethminer.

**Comment by nova25edz** [comment]
Hi Smurfy, following the installation guide from AMD won't do on multiple GPU but instead install the AMDGPU 17.40 with these commands
#if you have previous installation of AMDGPU kindly uninstall and reinstall using the following commands
$ cd <amdgpu dir>
$ amdgpu-pro-uninstall
$ reboot
$ sudo apt-get update #(this depends on your distro on how you update)
$ cd <amdgpu dir>
$ ./amdgpu-pro-install -compute #(use -compute option instead of -y option)
$ sudo usermod -a -G video $LOGNAME
$ sudo apt install -y rocm-amdgpu-pro
$reboot

This work on my miner using Ubuntu 16.04.3 LTS and AMDGPU-PRO 17.40

**Comment by dan-and** [comment]
nova25edz:

Which cards do you use when you verified this?

Kind regards,

Daniel

**Comment by nova25edz** [comment]
@dan-and 

I am using RX580 8GB

**Comment by dan-and** [comment]
@nova25edz 

That's why it works for you. Only the RX550 (Polaris 12) doesn't have working drivers for Linux.

**Comment by smurfy** [comment]
what does ``ethminer --list-devices`` show, this should display all devices which ethminer could "see"

**Comment by Richard87** [comment]
Hi guys, I think I have the same problem on a RX580 8GB...

```
Downloads/ethminer-0.12.0-Linux/bin ➜ uname -a
Linux workstation.skilnet.no 4.13.16-302.fc27.x86_64 #1 SMP Thu Nov 30 15:33:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux


Downloads/ethminer-0.12.0-Linux/bin ➜ ./ethminer -V
ethminer version 0.12.0
Build: Linux/g++/Release

ethminer/build/ethminer on  master ➜ ./ethminer -V
ethminer version 0.13.0.dev0
Build: Linux/g++/Release


Downloads/ethminer-0.12.0-Linux/bin ➜ ./ethminer -M                     
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument


Downloads/ethminer-0.12.0-Linux/bin ➜ ./ethminer --list-devices         
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
cl_get_gt_device(): error, unknown device: 0

Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[2] [0] Radeon RX 580 Series (AMD POLARIS10 / DRM 3.18.0 / 4.13.16-302.fc27.x86_64, LLVM 4.0.1)
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8588075008
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 6011652505
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
  ✘  09:00:13|ethminer  CUDA error: No CUDA driver found
```

OpenCL Output: https://pastebin.com/t5zW3KDW

For the record, I'm running Fedora 27 w/Wayland, with the opensource driver.
(EthMiner tested on v 0.13.0.dev0 and 0.12.0)

**Comment by smurfy** [comment]
try adding ``--opencl-platform 2``

**Comment by ddobreff** [comment]
It will not work. 550s are known to have OpenCL issues with latest linux opencl package, its not driver related though.

**Comment by Richard87** [comment]
Thanks, `--opencl-platform 2` gave me some more data, but nothing worked ;)

```
ethminer/build/ethminer on  master ➜ ./ethminer -M -G --opencl-platform 2 --opencl-device 1
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
  ℹ  14:25:49|ethminer  Found suitable OpenCL device [ Radeon RX 580 Series (AMD POLARIS10 / DRM 3.18.0 / 4.13.16-302.fc27.x86_64, LLVM 4.0.1) ] with 8588075008  bytes of GPU memory
Benchmarking on platform: CL
Preparing DAG for block #0
 cl  14:25:49|cl-0      No work. Pause for 3 s.
Warming up...
 cl  14:25:52|cl-0      New work: header #50c856ae… target 0000000000000002000000000000000000000000000000000000000000000000
 cl  14:25:52|cl-0      New seed #00000000…
 cl  14:25:53|cl-0      Platform: Clover
 cl  14:25:53|cl-0      Device:   Radeon RX 580 Series (AMD POLARIS10 / DRM 3.18.0 / 4.13.16-302.fc27.x86_64, LLVM 4.0.1)  / OpenCL 1.1 Mesa 17.2.4
 cl  14:25:53|cl-0      OpenCL 1.1  not supported, but platform Clover might work nevertheless. USE AT OWN RISK!
  ✘  14:25:53|cl-0      Build info: input.cl:106:1: error: OpenCL version 1.1 does not support the 'static' storage class specifier

  ✘  14:25:53|cl-0      OpenCL Error: clEnqueueWriteBuffer -38
Trial 1... 0
Trial 2... 0
Trial 3... 0
Trial 4... 0
Trial 5... 0

^C
```

Thanks for answering, fast question, is there a version of OpenCL I can install that will work, or where can I pay attention to see when they release something that might work?

**Comment by ddobreff** [comment]
https://community.amd.com/thread/221002
Unfortunately linux support for Lexa core a.k.a Polaris 12 is not planned for both ROCm or propietary OpenCL, you should try windows instead.

**Comment by aphilippi** [comment]
same issue here, but this solved it:
http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-Pro-Beta-Driver-for-Linux-Release-Notes.aspx

**Comment by Richard87** [comment]
Cool @aphilippi ! Btw, do you use Wayland or Xorg?

**Comment by aphilippi** [comment]
no, we're building a cheap and low-power xmr miner using https://github.com/fireice-uk/xmr-stak

**Comment by dan-and** [comment]
finally! Thanks for the high @aphilippi

**Comment by bmatthewshea** [comment]
Friendly reminder -
Also, don't forget to add user to 'video' group. This is easily overlooked.
(The user running ethminer binary for any AMD cards needs to be a member of **'video' group** else you get errors. At least under Ubuntu.) -> `sudo usermod -a -G video ethminer-username-here`

**Comment by rcole1200** [comment]
I have had the same problem exactly as dan experienced and went through installing 17.40 and then also the 17.50 and ubuntu 16.4 running claymore 10.2 would not recognize the 550. All my other rigs run fine 480s, 580s linux 17.50 drivers. In the effort to get my 550 to work outside of windows at more hashrate I went through the process of the posts here and others. the main hang up I still have is rocm wont install. I then discovered that the board and processor I was using was gen2 PCIE and pentium which rocm does not support. So I was interested to know what board and processor you used when you finally got it to work from aphillipi recommendation and is their another way to use opencl to recognize pentium and gen2pcie setups. I run gen 2pcie setups unbuntu 16.4 and claymore 10.2 with great results with 480s and 580s. Anyone care to comment?

**Comment by cryptomine** [comment]
@aphilippi Confirmed that the beta 550 driver you linked to works, I'm seeing ~6Mh/s per GPU on Ubuntu Server 16.04.03 LTS. I used the -y instead of -compute flag so I'll test the -compute flag and report back here, probably next week unless someone else does so first.

@rcole1200 Sorry, I have no way to test pcie2 at this time, I'm also not using rocm and don't really know what benefits it provides...

**Comment by cryptomine** [comment]
Nevermind, I actually had some free time. The "--compute" flag did nothing for the RX 550 4GB but

"Enabling Large Page Support" 
(found at the bottom of:
http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-Pro-Beta-Driver-for-Linux-Release-Notes.aspx)

Increased the per GPU hash rate from ~6.3Mh/s to ~7.2Mh/s
