### ISSUE TITLE
similar Nvidia cards are grouped with same hashrate, although clock is different.

### ISSUE THREAD

**Issue by whotheff** [ethereum-mining/ethminer#881]
I have mixed bag of 1060 6GB with Samsung, Micron and Hynix.
I noticed that when having 2 or more different Hynix cards, they all spit the same hashrate, although they have different clocks. Micron cards do the same - they sincronize somehow.
Is Ethminer designed that way in mind? Does it improve it's work or it is a bug?

**Comment by Olegatorius** [comment]
Slightly offtopic Question - have you overclocked them by Riva Tuner / MSI Afterburner ?

**Comment by whotheff** [comment]
MSI AB, however the option to group similar cards is Off.
