### ISSUE TITLE
0.14.0.dev3: GPU gave incorrect result - only when running with multiple gpus

### ISSUE THREAD

**Issue by igy137** [ethereum-mining/ethminer#883]
Hi,

On a rig running Windows 10 with 6x GTX 1070, using release 0.14.0.dev3 I receive every 1-2 hours a "GPU gave incorrect result" error, always happening on the last gpu. Otherwise even this gpu is delivering similar effective hashrate as the others.

Yesterday out of curiosity I started a separate ethminer instance for each card, so in total 6.
After running for around 12 hours, it seems, that the "GPU gave incorrect results" errors are not happening this way.

I attached log files from last ~8 hours for both setup:
- output.log is when running 6 card with one ethminer instance
- output_a[0..5].log when running separate ethminer instances per gpu

As far as I remember, running 0.13.0 release I haven't seen such errors, using same rig, same clocks/temps.

igy

[logs_incorrect.zip](https://github.com/ethereum-mining/ethminer/files/1801977/logs_incorrect.zip)

**Comment by whotheff** [comment]
Have not tested them seperately, but "Cuda 4: GPU gave incorrect result!" message appears every now and then. 
It was probably happening previously with version 13, but it was not displaying it.

Please clarify what can be the causes for these errors and how to solve them.

**Comment by AndreaLanfranchi** [comment]
Not ethminer's problem.
Something related to that specific gpu and or raisers quality.
