### ISSUE TITLE
0.14.0.dev4 effective hashrate halved

### ISSUE THREAD

**Issue by sandrodz** [ethereum-mining/ethminer#886]
```
#export GPU_FORCE_64BIT_PTR=0
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100

./bin/ethminer -HWMON -RH -G --farm-recheck 200 -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x4383cb1808668f0d73c4ec46b7c7c291f5812d8b.fujin --exit
```

centos7, AMD rx580 (Sapphire, Armor)

**Comment by tribalpixel** [comment]
hello,

try add `"--cl-local-work 256 --cl-kernel 1 --cl-parallel-hash 2"`

since 0.12/0.13 i dont remember, there is option kernel and parallel-hash that change a lot in hashrate results (for what i have tested so far...)

and you say you have rx580, so you can use local-work 256 (128 is default)

**Comment by sandrodz** [comment]
Seems to have worked, thanks. Lets see if it is reflected in effective hash rate on the pool itself.

<img width="1207" alt="screen shot 2018-03-14 at 1 31 31 pm" src="https://user-images.githubusercontent.com/8479569/37396613-d2767b2e-2792-11e8-949f-7955169a5e4a.png">

**Comment by satori-q3a** [comment]
Apparently, using block-size of 256 on 0.14.4 results in 50% less accepts.  However a value of 128 performs as well as 0.14.3, altho maybe with 1% more stales.

0.14.3 performs slightly better using block size of 256, rather than 128 with same accept rates.

**Comment by vanfaux** [comment]
![06319827-d1ae-4373-b1c0-4491febcf3fd](https://user-images.githubusercontent.com/37390021/37549953-c8ccebc8-29c0-11e8-9136-3b8c7eb44ce0.jpeg)

2% stale shares for 1 day run on this version with block size @ 256 and scheduling set to auto. High CPU utilization still if scheduling is used, no matter which settings and driving core temperature above 92deg celcius and fans beyond 4K rpm. Switching off scheduling has low CPU usage but lesser accepts and valid shares. Stale rate is the same.
