### ISSUE TITLE
ethminer doesn't exit when hash rate drops to zero

### ISSUE THREAD

**Issue by sandrodz** [ethereum-mining/ethminer#891]
<img width="1207" alt="screen shot 2018-03-14 at 1 15 54 pm" src="https://user-images.githubusercontent.com/8479569/37393408-7039e61a-278a-11e8-9de2-73aaf7fa06a0.png">

**Comment by Rodriguevb** [comment]
Same #859

**Comment by sandrodz** [comment]
error is: `GPU hangs in OpenCL call`
