### ISSUE TITLE
multi-thread synchronization problems for EthStratumClient

### ISSUE THREAD

**Issue by zyf224** [ethereum-mining/ethminer#892]
https://github.com/ethereum-mining/ethminer/blob/81ad571ca2f9e9bee8210631c72c3e696d516748/libpoolprotocols/stratum/EthStratumClient.cpp#L660

version 0.14.0.dev3
When the link is down, it waits 3 seconds before reconnecting. If the thread of Farm comes in at that time, m_socket is used to summit. but it has been deleted previously, so crash.

It performs better for  0.14.0.dev4, because Farm is stopped during disconnection. But the problem of multi-thread synchronization still exists. Consider the sequence when disconnection happens: 

Miner's thread enters EthStratumClient::submitSolution ==> EthStratumClient's thread launches disconnection and delete m_socket ==>Miner's thread calls async_write in  EthStratumClient::submitSolution ==> crash

Adding status judgement like "if (!m_linkdown)" at the entrance of  EthStratumClient::submitSolution can reduce possibility of crash greatly, but it won't work when above sequence happens.

I suggest add a mutex member to protect all io_service handler functions of EthStratumClient and public methods like EthStratumClient::submitSolution. Another way is to let all things to be done in EthStratumClient's thread, just like what m_hashrate_event do, or just use io_service's post method instead.

**Comment by AndreaLanfranchi** [comment]
Addressed in #1027
