### ISSUE TITLE
No work, cannot exit

### ISSUE THREAD

**Issue by nachitox** [ethereum-mining/ethminer#894]
```
m  16:43:50|ethminer|  ethminer version 0.14.0.dev4
  m  16:43:50|ethminer|  Build: linux / release +git. 81ad571
  ℹ  16:43:51|ethminer|  Found suitable OpenCL device [ Ellesmere ] with 8576192512  bytes of GPU memory
 cu  16:43:51|ethminer|  Using grid size 8192 , block size 128
  m  16:43:51|ethminer|  not-connected
  ℹ  16:43:52|stratum |  Connected to us1.ethermine.org
  ℹ  16:43:52|stratum |  Spinning up miners...
  ℹ  16:43:52|cuda-0  |  No work. Pause for 3 s.
 cl  16:43:52|cl-1    |  No work. Pause for 3 s.
 cl  16:43:52|cl-2    |  No work. Pause for 3 s.
 cl  16:43:52|cl-3    |  No work. Pause for 3 s.
  ℹ  16:43:55|cuda-0  |  No work. Pause for 3 s.
 cl  16:43:55|cl-1    |  No work. Pause for 3 s.
 cl  16:43:55|cl-2    |  No work. Pause for 3 s.
 cl  16:43:55|cl-3    |  No work. Pause for 3 s.
  m  16:43:56|ethminer|  not-connected
---
 ℹ  16:46:55|cuda-0  |  No work. Pause for 3 s.
 cl  16:46:55|cl-3    |  No work. Pause for 3 s.
  ℹ  16:46:56|ethminer|  Shutting down...
  ℹ  16:46:56|ethminer|  Shutting down miners...
 cl  16:46:58|cl-2    |  No work. Pause for 3 s.
 cl  16:46:58|cl-1    |  No work. Pause for 3 s.
  ℹ  16:46:58|cuda-0  |  No work. Pause for 3 s.
 cl  16:46:58|cl-3    |  No work. Pause for 3 s.
 cl  16:47:01|cl-1    |  No work. Pause for 3 s.
 cl  16:47:01|cl-2    |  No work. Pause for 3 s.
```

I thought it was a dwarfpool issue. The same happens with ethermine.
What can it be?

Also, CTRL+C didn't stopped the process.

**Comment by jean-m-cyr** [comment]
This unresolved issue goes all the way back to the intro of the pool manager. That's when it started occurring on my setup.

**Comment by AnjinMeili** [comment]
Sometimes it works, sometimes it doesn't.

```
ethminer version 0.15.0.dev0+git.0c65908
Build: linux/release/gnu

NVIDIA 390.47 + CUDA 9.1
AMD GPUPRO 17.50
Linux 4.15 Current
```

`ethminer --api-port 4029 --opencl-platform 1 --farm-recheck 2000 -X -P stratum+tcp://${WALLET}.${RIG}@eu1.ethermine.org:4444`
<img width="760" alt="screen shot 2018-03-26 at 4 41 45 pm" src="https://user-images.githubusercontent.com/1175978/37938838-9f877bec-3114-11e8-93f4-3d8ea57be456.png">

Process hangs and will not respond to a `CTRL-C`.  If I hit `CTRL-Z` to suspend, I can use `kill -9 ${PID}`.

If I change the wallet address, it might work the first time, but will fail the next.  If I change the pool, again, might work the first time, but not the next.

**Comment by melt7777** [comment]
Hello, any updates? Many thanks.

**Comment by peterwillcn** [comment]
Any updates? #1106

**Comment by peterwillcn** [comment]
@AndreaLanfranchi Can't work, LoL........
ethminer -U -P stratum1+tcp://$eth_address.$workername@eth.f2pool.com:8008

**Comment by peterwillcn** [comment]
Hello, any updates?

**Comment by smurfy** [comment]
see https://github.com/ethereum-mining/ethminer/issues/1111#issuecomment-389775773
