### ISSUE TITLE
this happened 0.14.4

### ISSUE THREAD

**Issue by invidtiv** [ethereum-mining/ethminer#899]
ethminer/build/ethminer/ethminer': double free or corruption (top): 0x00007f1b085c1390 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f1b3f7887e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f1b3f79137a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f1b3f79553c]
/home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer(ssl3_release_write_buffer+0x3d)[0x5bef7d]
/home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer(ssl3_write_bytes+0x6af)[0x5bdd4f]
/home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer(SSL_write+0x40)[0x5c9730]
/home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer(_ZN5boost4asio3ssl6detail6engine7performEMS3_FiPvmES4_mRNS_6system10error_codeEPm+0x52)[0x4debd2]
/home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer(_ZN5boost4asio3ssl6detail5io_opINS0_19basic_stream_socketINS0_2ip3tcpEEENS2_8write_opINS0_15const_buffers_1EEENS0_6detail8write_opINS1_6streamIS7_EES9_PKNS0_12const_bufferENSB_14transfer_all_tENSB_15write_dynbuf_opISE_NS0_19basic_streambuf_refISaIcEEESI_NS_3_bi6bind_tIvNS_4_mfi3mf1Iv16EthStratumClientRKNS_6system10error_codeEEENSN_5list2INSN_5valueIPSR_EEPFNS_3argILi1EEEvEEEEEEEEEEclEST_mi+0x105)[0x4eb235]
/home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer(_ZN5boost4asio6detail8write_opINS0_3ssl6streamINS0_19basic_stream_socketINS0_2ip3tcpEEEEENS0_15const_buffers_1EPKNS0_12const_bufferENS1_14transfer_all_tENS1_15write_dynbuf_opIS9_NS0_19basic_streambuf_refISaIcEEESE_NS_3_bi6bind_tIvNS_4_mfi3mf1Iv16EthStratumClientRKNS_6system10error_codeEEENSJ_5list2INSJ_5valueIPSN_EEPFNS_3argILi1EEEvEEEEEEEEclESR_mi+0x127)[0x4eb787]
/home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer[0x4eb924]
/home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer(_ZN16EthStratumClient14submitSolutionEN3dev3eth8SolutionE+0x27b)[0x4ec97b]
/home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer[0x4cda0f]
/home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer[0x4cdbbd]
/home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer(_ZN3dev3eth9CUDAMiner6searchEPKhmbmRKNS0_11WorkPackageE+0x677)[0x50fab7]
/home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer(_ZN3dev3eth9CUDAMiner8workLoopEv+0x892)[0x517582]
/home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer[0x4f5186]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80)[0x7f1b400b2c80]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f1b403836ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f1b3f81841d]
======= Memory map: ========
00400000-00ca0000 r-xp 00000000 fc:00 12585                              /home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer
00e9f000-00ec1000 r--p 0089f000 fc:00 12585                              /home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer
00ec1000-00ed0000 rw-p 008c1000 fc:00 12585                              /home/prospector/ethereum-mining/ethminer/build/ethminer/ethminer
00ed0000-00ed8000 rw-p 00000000 00:00 0
01766000-018e3000 rw-p 00000000 00:00 0                                  [heap]
200000000-200200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
200200000-200400000 rw-s 00000000 00:06 451                              /dev/nvidiactl
200400000-200600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
200600000-200800000 rw-s 00000000 00:06 451                              /dev/nvidiactl
200800000-200a00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
200a00000-200c00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
200c00000-200e00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
200e00000-201000000 rw-s 00000000 00:06 451                              /dev/nvidiactl
201000000-201200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
201200000-201400000 rw-s 00000000 00:06 451                              /dev/nvidiactl
201400000-201600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
201600000-202c00000 ---p 00000000 00:00 0
202c00000-202c04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
202c04000-202e00000 ---p 00000000 00:00 0
202e00000-202e04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
202e04000-203000000 ---p 00000000 00:00 0
203000000-203004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
203004000-203200000 ---p 00000000 00:00 0
203200000-203600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
203600000-203a00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
203a00000-203a04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
203a04000-203c00000 ---p 00000000 00:00 0
203c00000-203c04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
203c04000-203e00000 ---p 00000000 00:00 0
203e00000-204200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
204200000-204204000 rw-s 00000000 00:06 451                              /dev/nvidiactl
204204000-204400000 ---p 00000000 00:00 0
204400000-204404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
204404000-204600000 ---p 00000000 00:00 0
204600000-204a00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
204a00000-204a04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
204a04000-204c00000 ---p 00000000 00:00 0
204c00000-205000000 rw-s 00000000 00:06 451                              /dev/nvidiactl
205000000-205004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
205004000-205200000 ---p 00000000 00:00 0
205200000-205204000 rw-s 00000000 00:06 451                              /dev/nvidiactl
205204000-205400000 ---p 00000000 00:00 0
205400000-205404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
205404000-205600000 ---p 00000000 00:00 0
205600000-205a00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
205a00000-205e00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
205e00000-206200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
206200000-206600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
206600000-207000000 ---p 00000000 00:00 0
207000000-207004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
207004000-207c00000 ---p 00000000 00:00 0
207c00000-207c04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
207c04000-207e00000 ---p 00000000 00:00 0
207e00000-208200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
208200000-208600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
208600000-208a00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
208a00000-209400000 ---p 00000000 00:00 0
209400000-209404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
209404000-20a000000 ---p 00000000 00:00 0
20a000000-20a004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
20a004000-20ac00000 ---p 00000000 00:00 0
20ac00000-20ac04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
20ac04000-20ae00000 ---p 00000000 00:00 0
20ae00000-20b200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
20b200000-20bc00000 ---p 00000000 00:00 0
20bc00000-20bc04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
20bc04000-20c800000 ---p 00000000 00:00 0
20c800000-20c804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
20c804000-20ca00000 ---p 00000000 00:00 0
20ca00000-20ce00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
20ce00000-20d800000 ---p 00000000 00:00 0
20d800000-20d804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
20d804000-20e400000 ---p 00000000 00:00 0
20e400000-20e404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
20e404000-20e600000 ---p 00000000 00:00 0
20e600000-20ea00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
20ea00000-20ee00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
20ee00000-20f200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
20f200000-20fc00000 ---p 00000000 00:00 0
20fc00000-20fc04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
20fc04000-20fe00000 ---p 00000000 00:00 0
20fe00000-210200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
210200000-210600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
210600000-211000000 ---p 00000000 00:00 0
211000000-211004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
211004000-211200000 ---p 00000000 00:00 0
211200000-211600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
211600000-212000000 ---p 00000000 00:00 0
212000000-212004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
212004000-212200000 ---p 00000000 00:00 0
212200000-212600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
212600000-213000000 ---p 00000000 00:00 0
213000000-213004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
213004000-213200000 ---p 00000000 00:00 0
213200000-213600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
213600000-214000000 ---p 00000000 00:00 0
214000000-214004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
214004000-214c00000 ---p 00000000 00:00 0
214c00000-214c04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
214c04000-215800000 ---p 00000000 00:00 0
215800000-215804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
215804000-215a00000 ---p 00000000 00:00 0
215a00000-215e00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
215e00000-216200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
216200000-216c00000 ---p 00000000 00:00 0
216c00000-216c04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
216c04000-217800000 ---p 00000000 00:00 0
217800000-217804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
217804000-217a00000 ---p 00000000 00:00 0
217a00000-217e00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
217e00000-218800000 ---p 00000000 00:00 0
218800000-218804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
218804000-218a00000 ---p 00000000 00:00 0
218a00000-218e00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
218e00000-219200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
219200000-219600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
219600000-219a00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
219a00000-219e00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
219e00000-21a800000 ---p 00000000 00:00 0
21a800000-21a804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
21a804000-21b400000 ---p 00000000 00:00 0
21b400000-21b404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
21b404000-21b600000 ---p 00000000 00:00 0
21b600000-21ba00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
21ba00000-21c400000 ---p 00000000 00:00 0
21c400000-21c404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
21c404000-21d000000 ---p 00000000 00:00 0
21d000000-21d004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
21d004000-21dc00000 ---p 00000000 00:00 0
21dc00000-21dc04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
21dc04000-21de00000 ---p 00000000 00:00 0
21de00000-21e200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
21e200000-21e600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
21e600000-21ea00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
21ea00000-21ee00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
21ee00000-21f800000 ---p 00000000 00:00 0
21f800000-21f804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
21f804000-220400000 ---p 00000000 00:00 0
220400000-220404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
220404000-221000000 ---p 00000000 00:00 0
221000000-221004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
221004000-221c00000 ---p 00000000 00:00 0
221c00000-221c04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
221c04000-221e00000 ---p 00000000 00:00 0
221e00000-222200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
222200000-222c00000 ---p 00000000 00:00 0
222c00000-222c04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
222c04000-223800000 ---p 00000000 00:00 0
223800000-223804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
223804000-223a00000 ---p 00000000 00:00 0
223a00000-223e00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
223e00000-224800000 ---p 00000000 00:00 0
224800000-224804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
224804000-225400000 ---p 00000000 00:00 0
225400000-225404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
225404000-225600000 ---p 00000000 00:00 0
225600000-225a00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
225a00000-225e00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
225e00000-226800000 ---p 00000000 00:00 0
226800000-226804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
226804000-226a00000 ---p 00000000 00:00 0
226a00000-226e00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
226e00000-227200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
227200000-227c00000 ---p 00000000 00:00 0
227c00000-227c04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
227c04000-227e00000 ---p 00000000 00:00 0
227e00000-228200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
228200000-228c00000 ---p 00000000 00:00 0
228c00000-228c04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
228c04000-228e00000 ---p 00000000 00:00 0
228e00000-229200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
229200000-229c00000 ---p 00000000 00:00 0
229c00000-229c04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
229c04000-229e00000 ---p 00000000 00:00 0
229e00000-22a200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
22a200000-22a600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
22a600000-22aa00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
22aa00000-22b400000 ---p 00000000 00:00 0
22b400000-22b404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
22b404000-22b600000 ---p 00000000 00:00 0
22b600000-22ba00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
22ba00000-22c400000 ---p 00000000 00:00 0
22c400000-22c404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
22c404000-22d000000 ---p 00000000 00:00 0
22d000000-22d004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
22d004000-22d200000 ---p 00000000 00:00 0
22d200000-22d600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
22d600000-22da00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
22da00000-22e400000 ---p 00000000 00:00 0
22e400000-22e404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
22e404000-22f000000 ---p 00000000 00:00 0
22f000000-22f004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
22f004000-22f200000 ---p 00000000 00:00 0
22f200000-22f600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
22f600000-230000000 ---p 00000000 00:00 0
230000000-230004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
230004000-230200000 ---p 00000000 00:00 0
230200000-230600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
230600000-230a00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
230a00000-231400000 ---p 00000000 00:00 0
231400000-231404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
231404000-231600000 ---p 00000000 00:00 0
231600000-231a00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
231a00000-232400000 ---p 00000000 00:00 0
232400000-232404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
232404000-232600000 ---p 00000000 00:00 0
232600000-232a00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
232a00000-233400000 ---p 00000000 00:00 0
233400000-233404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
233404000-234000000 ---p 00000000 00:00 0
234000000-234004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
234004000-234c00000 ---p 00000000 00:00 0
234c00000-234c04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
234c04000-234e00000 ---p 00000000 00:00 0
234e00000-235200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
235200000-235600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
235600000-235a00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
235a00000-236400000 ---p 00000000 00:00 0
236400000-236404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
236404000-237000000 ---p 00000000 00:00 0
237000000-237004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
237004000-237c00000 ---p 00000000 00:00 0
237c00000-237c04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
237c04000-238800000 ---p 00000000 00:00 0
238800000-238804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
238804000-238a00000 ---p 00000000 00:00 0
238a00000-238e00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
238e00000-239200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
239200000-239c00000 ---p 00000000 00:00 0
239c00000-239c04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
239c04000-239e00000 ---p 00000000 00:00 0
239e00000-23a200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
23a200000-23ac00000 ---p 00000000 00:00 0
23ac00000-23ac04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
23ac04000-23b800000 ---p 00000000 00:00 0
23b800000-23b804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
23b804000-23ba00000 ---p 00000000 00:00 0
23ba00000-23be00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
23be00000-23c200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
23c200000-23cc00000 ---p 00000000 00:00 0
23cc00000-23cc04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
23cc04000-23d800000 ---p 00000000 00:00 0
23d800000-23d804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
23d804000-23da00000 ---p 00000000 00:00 0
23da00000-23de00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
23de00000-23e200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
23e200000-23e600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
23e600000-23f000000 ---p 00000000 00:00 0
23f000000-23f004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
23f004000-23f200000 ---p 00000000 00:00 0
23f200000-23f600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
23f600000-23fa00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
23fa00000-240400000 ---p 00000000 00:00 0
240400000-240404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
240404000-241000000 ---p 00000000 00:00 0
241000000-241004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
241004000-241200000 ---p 00000000 00:00 0
241200000-241600000 rw-s 00000000 00:06 451                              /dev/nvidiactl
241600000-241a00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
241a00000-241e00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
241e00000-242800000 ---p 00000000 00:00 0
242800000-242804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
242804000-243400000 ---p 00000000 00:00 0
243400000-243404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
243404000-244000000 ---p 00000000 00:00 0
244000000-244004000 rw-s 00000000 00:06 451                              /dev/nvidiactl
244004000-244c00000 ---p 00000000 00:00 0
244c00000-244c04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
244c04000-245800000 ---p 00000000 00:00 0
245800000-245804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
245804000-245a00000 ---p 00000000 00:00 0
245a00000-245e00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
245e00000-246800000 ---p 00000000 00:00 0
246800000-246804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
246804000-246a00000 ---p 00000000 00:00 0
246a00000-246e00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
246e00000-247800000 ---p 00000000 00:00 0
247800000-247804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
247804000-247a00000 ---p 00000000 00:00 0
247a00000-247e00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
247e00000-248800000 ---p 00000000 00:00 0
248800000-248804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
248804000-248a00000 ---p 00000000 00:00 0
248a00000-248e00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
248e00000-249800000 ---p 00000000 00:00 0
249800000-249804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
249804000-249a00000 ---p 00000000 00:00 0
249a00000-249e00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
249e00000-24a800000 ---p 00000000 00:00 0
24a800000-24a804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
24a804000-24aa00000 ---p 00000000 00:00 0
24aa00000-24ae00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
24ae00000-24b200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
24b200000-24bc00000 ---p 00000000 00:00 0
24bc00000-24bc04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
24bc04000-24be00000 ---p 00000000 00:00 0
24be00000-24c200000 rw-s 00000000 00:06 451                              /dev/nvidiactl
24c200000-24cc00000 ---p 00000000 00:00 0
24cc00000-24cc04000 rw-s 00000000 00:06 451                              /dev/nvidiactl
24cc04000-24d800000 ---p 00000000 00:00 0
24d800000-24dc00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
24dc00000-24e600000 ---p 00000000 00:00 0
24e600000-24e604000 rw-s 00000000 00:06 451                              /dev/nvidiactl
24e604000-24f200000 ---p 00000000 00:00 0
24f200000-24f204000 rw-s 00000000 00:06 451                              /dev/nvidiactl
24f204000-24f400000 ---p 00000000 00:00 0
24f400000-24f800000 rw-s 00000000 00:06 451                              /dev/nvidiactl
24f800000-24f804000 rw-s 00000000 00:06 451                              /dev/nvidiactl
24f804000-250400000 ---p 00000000 00:00 0
250400000-250404000 rw-s 00000000 00:06 451                              /dev/nvidiactl
250404000-250600000 ---p 00000000 00:00 0
250600000-250a00000 rw-s 00000000 00:06 451                              /dev/nvidiactl
250a00000-251400000 ---p 00000000 00:00 0
251400000-251800000 rw-s 00000000 00:06 451

**Comment by jmsjr** [comment]
I see you are using SSL. I believe this is the same / related issue as https://github.com/ethereum-mining/ethminer/issues/890

That issue only happens on SSL / TLS connections and when re-connecting after being disconnected.

Workaround for now is to go back to 0.14.0.dev3 WITHOUT using SSL.

**Comment by efrasyad** [comment]
0.14.dev3 works well with stratum-ssl on my rig (4x rx 570 and 2 rx580).
0.14.dev4 and so on are crashing after an hour or two.
