### ISSUE TITLE
Mac Pro D700 8MH/S then drops to 0

### ISSUE THREAD

**Issue by dbvrac** [ethereum-mining/ethminer#90]
I have 3 identical machines, and this happens on two of them, which suggests a software difference. What could it possibly be? In any case, is 8MH/S realistic, or is something else going on? This is a lot slower than I expected. I'm getting ~35MH/S from a pair of GTX Titans.

**Comment by JHGitty** [comment]
Are you a technical guy? If yes please try out this code change: https://github.com/ethereum-mining/ethminer/pull/44

**Comment by dbvrac** [comment]
Trying it now. Not seeing any improvement - looking for further code/config tweaks.

min/mean/max: 6640981/6710885/6728362 H/s
inner mean: 2242787 H/s

I'm only a 'technical guy' to the extent that I may be an annoyance, not particularly dangerous.

**Comment by dbvrac** [comment]
Partial success!
min/mean/max: 22840614/22977385/23060985 H/s
inner mean: 22995108 H/s

I can compile and run on the same two machines, which then fall to 0Mh/s. The other machine will not compile (fails on boost), but when I copy the binary compiled on another machine it's nice and stable.

**Comment by mxjoe** [comment]
I am running macOS 10.12.6 on my dual D700 Mac Pro and also get about 8.5 MH/s. But [wtfuzz](https://github.com/wtfuzz/ethminer) made some adjustments which resulted in doubling of the hashrate. So now I get more than 17 MH/s. :-)
