### ISSUE TITLE
The version ('90000') compiler ('Apple clang') is not supported

### ISSUE THREAD

**Issue by LiweiDong** [ethereum-mining/ethminer#900]
[ 44%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
nvcc fatal   : The version ('90000') of the host compiler ('Apple clang') is not supported
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.Release.cmake:219 (message)

**Comment by LiweiDong** [comment]
`clang --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

**Comment by LiweiDong** [comment]
which version of clang can be supported ?

**Comment by chfast** [comment]
Ask Nvidia. You can try upgrading CUDA SDK and check what clang version is required there.
