### ISSUE TITLE
Hashrate submitting not working on Nanopool 

### ISSUE THREAD

**Issue by Angel996** [ethereum-mining/ethminer#901]
It's weird, but I can't get the worker to show up on pool. I'm using exactly the same pool/settings as with Claymore's. So, mining is working, I can see ethminer report hashrate etc etc, but no idea where the shares actually going. My connection string is:

`./ethminer --farm-recheck 6000 -S eth-eu2.nanopool.org:9999 -O 0x392220D88C929ffff8421f1D0Ac11DaCeBAE9777.RIG05/user@email.com -U`

Running on Ubuntu 16.04 LTS. Please?

p.s. If I use Claymore's, workers appears immediately.

**Comment by AndreaLanfranchi** [comment]
The worker appearance is subject to these conditions:

1. Either it finds a valid nonce and it submits it
2. Or the submitting of hashrate is triggered

In your example you're not endorsing the latter so you'd have to wait for the first condition.

P.s. with -S (stratum mode) is not necessary to set --farm-recheck as it has no meaning.

**Comment by Angel996** [comment]
Looks like hashrate submitting is not working on nanopool. Here is the command line (version 0.13.0):

./ethminer --farm-recheck 6000 -S eth-eu2.nanopool.org:9999 -O 0x*******.RIGxx/user@domain.com -RH -G --cl-kernel 1 --cl-local-work 256 --cl-global-work 32768 --cl-parallel-hash 2

p.s. _--farm-recheck_ does have a meaning, it affects how often hashrate gets updated in the miner window, if I remove this option, it's too frequent. I don't know if it's a bug, but that's how it is.

**Comment by jmsjr** [comment]
What version of ethminer ?
Is it working initially and stops working after some time ?
Related to https://github.com/ethereum-mining/ethminer/issues/888 ?

**Comment by smurfy** [comment]
@Angel996 

You need to use ``-RH`` **and** ``-SP 2`` for nanopool, to get hashrate reporting to work.

**Comment by Angel996** [comment]
I tried to add the -SP 2 swtich, I get the error msg:

_Exception thrown in Worker thread: apparent block number for 653b2f32d4aa5816cccea1ed449d2199a030de1b7e5ffae974f33ce50b7179c2 is too high; max is 61440000_

Then 0 mh/s is reported (DAG is not loaded) and mining does not start. Full command line:

`./ethminer --farm-recheck 6000 -S eth-eu2.nanopool.org:9999 -O 0x*******.RIGxx/user@domain.com -RH -U -SP 2`

Looks like -SP 2 stratum protocol is not right for Nanopool.
