### ISSUE TITLE
 Fatal GPU error: CUDA error in func dev::eth::CUDAMiner::search at line 503

### ISSUE THREAD

**Issue by kolumbus120** [ethereum-mining/ethminer#902]
ethminer-0.14.0.dev4-Windows
windows 10 pro, version 1709, OS build 16299.248
cuda 9.1
nvidia 390.65
rig with 6gpu (4 gtx 1070, 2 gtx 1060)
after 10-15hour on ubiqpool.maxhash.org on screeen is this error:
Fatal GPU error: CUDA error in func dev::eth::CUDAMiner::search at line 503

it does happend on ethminer-0.14.0.dev3-Windows too, but after 3-6 hours.
with ethminer-0.13.0-Windows everithing works just fine.

**Comment by digitalpara** [comment]
ethminer 0.14.0rc4-windows 10 pro, version 64
cuda 9.1 nvidia 390.65
rig with 5gpu (4 gtx 1060 - 1 gtx 1050 ti )
after 10 seconds - or 1 minute on ethermine.org on screeen is this error:
Fatal GPU error: CUDA error in func dev::eth::CUDAMiner::search at line 503 an illegal instruction was encountered and ethermine freeze and exit

it does happend on ethminer-Windows everithing works just fine. please help.

i am using this miner software Download: https://mirrorace.com/m/1qikt

**Comment by area511** [comment]
0.14.0rc4, only one time so far:

X 03:08:27|cuda-2 | Fatal GPU error: CUDA error in func dev::eth::CUDAMiner::search at line 503 an illegal memory access was encountered
X 03:08:27|cuda-0 | Terminating.

**Comment by colin-i** [comment]
It may be from overclocking.

A c# code to restart when first gpu is stopping:
```
using System;
using System.Diagnostics;
namespace ConsoleApp1
{
    class Program
    {
        static bool error;
        static Process proc;
        static int nr;
        static void Main(string[] args)
        {
            String exeFileName = ".\ethminer.exe";
            ProcessStartInfo info = new ProcessStartInfo(exeFileName);
            info.UseShellExecute = false;// Set UseShellExecute to false for redirection
            info.Arguments = "--help";//write arguments
            info.RedirectStandardOutput = true;
            info.RedirectStandardError = true;
            do
            {
                proc = new Process();
                proc.OutputDataReceived += new DataReceivedEventHandler(proc_OutputDataReceived);
                proc.ErrorDataReceived += new DataReceivedEventHandler(proc_ErrorDataReceived);
                proc.StartInfo = info;
                error = false;nr = 0;
                proc.Start();
                proc.BeginOutputReadLine();
                proc.BeginErrorReadLine();
                proc.WaitForExit();
            } while (error);
        }
        static void proc_ErrorDataReceived(object sender, DataReceivedEventArgs e) {
            if (e.Data != null)
            {
                Console.WriteLine(e.Data);
                if (e.Data.Contains("gpu0 0,00"))
                {
                    nr++;Console.WriteLine(nr);
                    if (nr > 9)
                    {
                        System.IO.File.WriteAllText(".\er.txt", e.Data); error = true;
                        proc.Kill();
                    }
                }
            }
        }
        static void proc_OutputDataReceived(object sender, DataReceivedEventArgs e) { Console.WriteLine("output stream"); }
    }
}
```

**Comment by AndreaLanfranchi** [comment]
Stale issue and related to outdated version.
Closing.
