### ISSUE TITLE
No cuda driver found with AMD

### ISSUE THREAD

**Issue by rawsh** [ethereum-mining/ethminer#903]
2 rx 480s. Here is the error:

```
  m  15:52:47|ethminer|  ethminer version 0.14.0.dev4
  m  15:52:47|ethminer|  Build: linux / release +git. 81ad571
  ℹ  15:52:47|ethminer|  Found suitable OpenCL device [ AMD Radeon (TM) RX 480 Graphics (AMD POLARIS10 / DRM 3.20.0 / 4.13.0-37-generic, LLVM 5.0.0) ] with 8587001856  bytes of GPU memory
Error: No CUDA driver found
```

and 

```
Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[0] [0] AMD Radeon (TM) RX 480 Graphics (AMD POLARIS10 / DRM 3.20.0 / 4.13.0-37-generic, LLVM 5.0.0)
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8587001856
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 6010901299
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[0] [1] AMD Radeon (TM) RX 480 Graphics (AMD POLARIS10 / DRM 3.20.0 / 4.13.0-37-generic, LLVM 5.0.0)
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8587001856
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 6010901299
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] [0] Ellesmere
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8463011840
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] [1] Ellesmere
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8463142912
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
```

**Comment by Elycin** [comment]
I'm hoping to help, but I'm not sure I understand the problem here.
CUDA is Nvidia's proprietary compute library for utilizing Nvidia's GPUs, AMD takes an open source approach with their graphics cards by using OpenCL.

Are you trying to use CUDA on an AMD card?

**Comment by rawsh** [comment]
I don't think so. Just running ./ethminer by default gives this message

**Comment by Elycin** [comment]
Gotcha.

If you have a shell or bash script, try adding the arguments: `--opencl-devices 0,1,2,3`.
You may need to alternate the numbers to the corresponding indices of the graphics cards.

**Comment by rawsh** [comment]
Thanks, got it to work with that

**Comment by RJBetancor** [comment]
How do I do it in Windows?
I have an AMD R7 360 and the same problem happens to me.

**Comment by CristianJG18** [comment]
> How do I do it in Windows?
> I have an AMD R7 360 and the same problem happens to me.

I'm having that problem with r270! :P Anyone can help me? Windows 10 64 bits

**Comment by wcabezas** [comment]
> > ¿Cómo lo hago en Windows? 
> > Tengo una AMD R7 360 y me pasa el mismo problema.
> 
> ¡Tengo ese problema con r270! : P ¿Alguien me puede ayudar? Windows 10 de 64 bits

Pudieron resolverlo? tengo el mismo problema

**Comment by xiaocode337317439** [comment]
ethminer 0.19.0-alpha.0
Build: darwin/release/appleclang

Unrecognized platform Apple
CUDA Error : No CUDA driver found
Error: No usable mining devices found

AMD  Radeon Pro 580X 8

**Comment by Alvaro245ap** [comment]
> > > ¿Cómo lo hago en Windows?
> > > Tengo una AMD R7 360 y me pasa el mismo problema.
> > 
> > 
> > ¡Tengo ese problema con r270! : P ¿Alguien me puede ayudar? Windows 10 de 64 bits
> 
> Pudieron resolverlo? tengo el mismo problema

Hola. pudiste resolverlo? Tengo el mismo problema
