### ISSUE TITLE
6 GPU right Ethminer has stopped working but works with 5?

### ISSUE THREAD

**Issue by beardedbob** [ethereum-mining/ethminer#905]
Hi All,

I'm currently running a 6 gpu mining rig but I can only get it to work with 5 enabled. The GPU's are mixed 1x1070, 1x 1060 and 4x 1050ti (one is a different made). I can mine with 5 as long as i disable one of the cards but if I tried to run it with all 6 ethminer stops. I'm running win 10, can you help?

**Comment by satori-q3a** [comment]
Are you saying it worked with 6 cards before but now only runs with 5?

Have you eliminated the usual suspects... GPT, Pagefile, Device Manager, failed card and what does ethminer start up look like?

**Comment by beardedbob** [comment]
Hi,

Thanks for coming back. It never worked with 6 GPU's i've only been able to get 5 working at once. I didn't think to check the virtual memory this was the issue i've not changed this and its working. below is the error I was getting for anyone who might come across it. @satori-q3a thanks for your help.

Ethminer error https://imgur.com/a/K3qzT

**Comment by ddobreff** [comment]
Its definately virtual memory, so you should increase it.
