### ISSUE TITLE
No new work received 0.14.0-dev4

### ISSUE THREAD

**Issue by abdullasharapov** [ethereum-mining/ethminer#908]
Hi!
I have some issue, here is log:

No new work received in ^[[97m180^[[0m seconds.
^[[94m ℹ ^[[35m09:34:11^[[0m^[[30m|^[[34mstratum ^[[0m^[[30m|^[[36m^[[0m Disconnected from exp-eu.dwarfpool.com^[[0m
^[[94m ℹ ^[[35m09:34:11^[[0m^[[30m|^[[34mstratum ^[[0m^[[30m|^[[36m^[[0m Shutting down miners...
^[[32m m ^[[35m09:34:12^[[0m^[[30m|^[[34methminer^[[0m^[[30m|^[[36m^[[0m not-connected
^[[94m ℹ ^[[35m09:34:14^[[0m^[[30m|^[[34mstratum ^[[0m^[[30m|^[[36m^[[0m Retrying in ^[[97m3^[[0m ... ^M
^[[94m ℹ ^[[35m09:34:15^[[0m^[[30m|^[[34mstratum ^[[0m^[[30m|^[[36m^[[0m Retrying in ^[[97m2^[[0m ... ^M
^[[94m ℹ ^[[35m09:34:16^[[0m^[[30m|^[[34mstratum ^[[0m^[[30m|^[[36m^[[0m Retrying in ^[[97m1^[[0m ... ^M
^[[94m ℹ ^[[35m09:34:17^[[0m^[[30m|^[[34mstratum ^[[0m^[[30m|^[[36m^[[0m Connected to exp-eu.dwarfpool.com^[[0m
^[[94m ℹ ^[[35m09:34:17^[[0m^[[30m|^[[34mstratum ^[[0m^[[30m|^[[36m^[[0m Spinning up miners...
^[[94m ℹ ^[[35m09:34:17^[[0m^[[30m|^[[34mcuda-0 ^[[0m^[[30m|^[[36m^[[0m No work. Pause for 3 s.
^[[94m ℹ ^[[35m09:34:17^[[0m^[[30m|^[[34mcuda-1 ^[[0m^[[30m|^[[36m^[[0m No work. Pause for 3 s.
^[[94m ℹ ^[[35m09:34:17^[[0m^[[30m|^[[34mcuda-2 ^[[0m^[[30m|^[[36m^[[0m No work. Pause for 3 s.
^[[94m ℹ ^[[35m09:34:17^[[0m^[[30m|^[[34mcuda-3 ^[[0m^[[30m|^[[36m^[[0m No work. Pause for 3 s.
^[[94m ℹ ^[[35m09:34:17^[[0m^[[30m|^[[34mstratum ^[[0m^[[30m|^[[36m^[[0m Received new job ^[[97m#a485fe48…^[[0m from exp-eu.dwarfpool.com^[[0m
^[[32m m ^[[35m09:34:17^[[0m^[[30m|^[[34methminer^[[0m^[[30m|^[[36m^[[0m Speed ^[[1;36m 0.00^[[0m Mh/s gpu/0 ^[[36m 0.00^[[0m ^[[36m0C 0% ^[[0m gpu/1 ^[[36m 0.00^[[0m ^[[36m0C 0% ^[[0m gpu/2 ^[[36m 0.00^[[0m ^[[36m0C 0% ^[[0m gpu/3 ^[[36m 0.00^[[0m ^[[36
^[[94m ℹ ^[[35m09:34:20^[[0m^[[30m|^[[34mcuda-0 ^[[0m^[[30m|^[[36m^[[0m Initialising miner ^[[97m0^[[0m
^[[94m ℹ ^[[35m09:34:20^[[0m^[[30m|^[[34mcuda-1 ^[[0m^[[30m|^[[36m^[[0m Initialising miner ^[[97m1^[[0m
^[[94m ℹ ^[[35m09:34:20^[[0m^[[30m|^[[34mcuda-2 ^[[0m^[[30m|^[[36m^[[0m Initialising miner ^[[97m2^[[0m
^[[94m ℹ ^[[35m09:34:20^[[0m^[[30m|^[[34mcuda-3 ^[[0m^[[30m|^[[36m^[[0m Initialising miner ^[[97m3^[[0m

Who has the same problem please help with the solution. Perhaps this problem is related to the pool i use, i don't know.

**Comment by AndreaLanfranchi** [comment]
Please post the whole command line you use to launch ethminer.
For instance you appear to use dwarfpool which requires parameter -SP 1

**Comment by abdullasharapov** [comment]
@AndreaLanfranchi
--farm-recheck 2000 --cuda -S exp-eu.dwarfpool.com:8018 -FS exp-us.dwarfpool.com:8018 -O wallet/worker_name:x -SP 1 --report-hashrate --api-port 3334 -HWMON 0

**Comment by AndreaLanfranchi** [comment]
There is apparently nothing strange here. It only seems you're not posting enough log lines after "Initializing miner ..."

**Comment by AndreaLanfranchi** [comment]
Please disable colors if you want to post logs.

Anyway is working properly.

**Comment by AndreaLanfranchi** [comment]
Please close the issue if not needed any more.

Thanks

**Comment by AndreaLanfranchi** [comment]
To disable colors set an environment variable named NO_COLOR to any value

--work-timeout sets the maximum "delay" of new jobs. If no job is received within that amount of time then ethminer disconnects and retries connection (it means that the pool has some problem).

**Comment by abdullasharapov** [comment]
--work-timeout this solve my problem
