### ISSUE TITLE
"stratum not accepted", why this happening?

### ISSUE THREAD

**Issue by karlyshka** [ethereum-mining/ethminer#91]
Hi)

ethminer 0.11.0rc1 + dwarfpool + 1060

why this happening?

![default](https://user-images.githubusercontent.com/29449399/27698911-622e2cc4-5d1a-11e7-8669-e1a34fab1462.PNG)

**Comment by Revasz** [comment]
I have the exact same problem when I try to mine on eth-eu.dwarfpool with latest EthMiner.
Tried every stratum configuration for connecting to the pool but the result is always the same.
The  first, found, solution goes through but the following solutions are always rejected.

Dwarfpool says the DAG-File is possibly corrupted but mining on ethermine is totally fine and shows never an error.

Specs:
GTX 1070 (tried with overclocking and without) (Micron Memory)
EthMiner  0.11.0rc1
Windows 10 x64

**Comment by MichaelHeimann** [comment]
Have this, too with a 1070 and a 1080. My workaround: use the eth-proxy from dwarfpool.

**Comment by chfast** [comment]
Don't use Dwarf pool.
