### ISSUE TITLE
dev4 is loosing report hashrate after few hours

### ISSUE THREAD

**Issue by Teressss** [ethereum-mining/ethminer#912]
I'm on Ubuntu and even miner is running great and continues mining, after few hours ethminer stops reporting hashrate to pool. My other rigs running the same version are reporting hashrate forever without loosing it. It just happens only on one rig

**Comment by piotr-dobrogost** [comment]
Please take a look at existing issues. This was already raised few times.

**Comment by vatanuki** [comment]
duplicate #888 
fixing attempts #897

**Comment by Teressss** [comment]
sorry

**Comment by jean-m-cyr** [comment]
Fixed by PR #897. Closing
