### ISSUE TITLE
HWMON not working for OSX on NVIDIA cards

### ISSUE THREAD

**Issue by vanfaux** [ethereum-mining/ethminer#913]
Anyone managed to make HWMON work on MacOSX? 

ethminer works really well, no RH issues, no SSL issues, just HWMON is not working or is it really not supported in OSX by nvidia webdriver?

I compiled with this issue:

/Users//ethminer/libhwmon/wrapnvml.cpp:56:2: warning: "Unrecognized
platform: need NVML DLL path for this platform..." [-W#warnings]
#warning "Unrecognized platform: need NVML DLL path for this platform..."
^
1 warning generated.

**Comment by smurfy** [comment]
do you find a ``libnvidia-ml.so`` on our file system?  or does ``nvidia-smi`` exists on osx?

**Comment by vanfaux** [comment]
Can't find any of those 2 files anywhere in OSX. I have cuda-smi and can only display memory usage.

**Comment by vanfaux** [comment]
Closing this issue as no native support for GPU monitoring for OSX.

Workaround, bash scripted cuda-smi and istats.
