### ISSUE TITLE
File logging.

### ISSUE THREAD

**Issue by Undertrey** [ethereum-mining/ethminer#914]
Hello! Please add support of --logfile function to write output into the .log file.
Thank you very much!

**Comment by MariusVanDerWijden** [comment]
you can pipe the output into a logfile 
`./ethminer > log.txt`

**Comment by Undertrey** [comment]
True. I'm Windows user. And I want to have file logging + output in CMD window.
Using ">>" redirection it can be only output into the file. CMD window will be black.
This functionality is very nice. Almost all miners have it. Thank you!

**Comment by AndreaLanfranchi** [comment]
I personally think that std output is the better option. So everyone can redirect to whatever they want without adding complexities to the code.

If you want your output to console and to logfile use native powershell from within your windows.

`powershell ".\ethminer.exe | tee yourlogfile.txt"`

**Comment by Undertrey** [comment]
I understand that there is an opportunity to put additional applications. I just ask to add the possibility of logging. I am interested in either the solution specifically on the standard cmd.exe or the implementation of such a function in the miner.

Most of the miners have this function. It is very useful to be able to record a log. In any case, I will write the log for myself using the ">" function. But I would also like to see the window of the miner with the information.

Not all users have the opportunity, the desire, the ability to make complex system settings to get a log and display information on the screen at the same time. So I ask developers to simplify life for everyone. Thank you!

**Comment by AndreaLanfranchi** [comment]
What complexity there is in this ?

`powershell ".\ethminer.exe <add your switcheshere> | tee yourlogfile.txt"`

it's a one line solution.

**Comment by Undertrey** [comment]
Because for me it does not work. I tried to run both through .bat and through .ps1 - the file is not created.
![image](https://user-images.githubusercontent.com/9869964/37771931-c8120356-2de1-11e8-8dec-91165a5b4cdc.png)

**Comment by AndreaLanfranchi** [comment]
Forgot to mention that output of ethminer is to stderr stream
Thus you have to change sligtly the command adding 2>&1 as a redirection

`powershell ".\ethminer.exe <add your switcheshere> 2>&1 | tee yourlogfile.txt"`

**Comment by Undertrey** [comment]
![image](https://user-images.githubusercontent.com/9869964/37779301-c7d8f7ec-2df4-11e8-9123-98d3d3d78479.png)

**Comment by AndreaLanfranchi** [comment]
The new option --stdout makes this request obsolete.
Simply redirect to log file.

```
./ethminer [...] --stdout > log.txt
```
or

```
./ethminer [...] --stdout | tee log.txt
```

**Comment by Gondagar** [comment]
Блядь, Так сложно логи было разрабам добавить?
