### ISSUE TITLE
0.15.dev0 --cuda-noeval still 100% invalid shares

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ethereum-mining/ethminer#915]
As subject says.

**Comment by alptolga** [comment]
--cuda-noeval  bypass host software re-evalution of GPU solutions.
Can you describe this parameter?

**Comment by AndreaLanfranchi** [comment]
The advantage is clearly stated in the description

"This will trim some milliseconds off the time it takes to send a result to the pool."

Say it trims off 1 ms for every found share.
Every 1000 shares you have "gained" 1 second of hashing

**Comment by alptolga** [comment]
''Use at your own risk! If GPU generates errored results they WILL be forwarded to the pool''
If they need to make such an explanation, it seems like loosing is more possible then earning share
Thanks for your explanation.

**Comment by AndreaLanfranchi** [comment]
That's not the point.
Point is the setting of this flag causes automagically every single share to be invalid (100%)
This is not the expected behavior.

It is plausible that in high overclocked environments you may get some invalid shares but this is not the case.

**Comment by AndreaLanfranchi** [comment]
This has already been addressed in #889 which has been merged but apparently with no effect.

**Comment by DeadManWalkingTO** [comment]
@AndreaLanfranchi i confirm the issue!
