### ISSUE TITLE
0.14.0rc0-Linux pre-built binary Segmentation fault

### ISSUE THREAD

**Issue by stralex7** [ethereum-mining/ethminer#916]
Segmentation fault      (core dumped) /opt/miner/bin/ethminer -RH -HWMON --api-port 8080 --farm-recheck 200 -U -P stratum+tcp://eu1.ethermine.org:4444 -P stratum+tcp://us1.ethermine.org:4444 -O xxxx

ldd bin/ethminer
        linux-vdso.so.1 =>  (0x00007ffc08f5c000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4861c71000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4861a6d000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f486184e000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f48614c8000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4861172000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4860f5b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4860b7b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4861e79000)

Operating System: Ubuntu 17.10
            Kernel: Linux 4.13.0-36-generic
nvidia-390/artful,now 390.25-0ubuntu0~gpu17.10.1 amd64 [installed]

**Comment by stralex7** [comment]
-O is depreciated but using a proper -P format causes Seg fault as well

**Comment by megapearl** [comment]
Same problem here, with same ethminer version and same ubuntu 17.10 as poster above.

**Comment by jean-m-cyr** [comment]
@megapearl @stralex7 Please post you command line.

**Comment by jean-m-cyr** [comment]
@stralex7 @megapearl Just ran:

ethminer -RH -HWMON --api-port 8080 --farm-recheck 200 -U -P stratum+tcp://$ETHWALLET.$HOSTNAME@us1.ethermine.org:4444

with no issue from master. Please post your exact command line.

**Comment by megapearl** [comment]
Old cmd line (v0.14.0dev4)

/usr/bin/ethminer --cuda --report-hashrate --stratum-protocol 1 --stratum eth-eu1.nanopool.org:9999 --stratum-failover eth-eu2.nanopool.org:9999 --userpass 0x0mywalletaddres.myworker-name/my@mailaddres.com

New cmd line (v0.14.0rc0) segfaulting:

/usr/bin/ethminer --cuda --report-hashrate -P stratum1+tcp://0x0mywalletaddres.myworker-name/my@mailaddres.com@eth-eu1.nanopool.org:9999
 
which gives on cli:
Segmentation fault (core dumped)

and dmesg:
[419785.234413] ethminer[25928]: segfault at fffffffffffffff8 ip 00007f75abb9ead3 sp 00007ffdfc836d08 error 5 in libstdc++.so.6.0.24[7f75abacc000+178000]

**Comment by jean-m-cyr** [comment]
Don't know what to say... without password of course. Still trying to figure out best way to handle nanopool email address style passwords... or any other style for that matter that would create illegal URIs

jcyr@miner0:~$ ethminer --cuda --report-hashrate -P stratum1+tcp://$ETHWALLET.$HOSTNAME@eth-eu1.nanopool.org:9999         
  m  09:52:32|ethminer|  ethminer version 0.15.0.dev0
  m  09:52:32|ethminer|  Build: linux / release +git. f327cf2
 cu  09:52:32|ethminer|  Using grid size 8192 , block size 128
  m  09:52:32|ethminer|  not-connected
  ℹ  09:52:32|stratum |  Connected to eth-eu1.nanopool.org:9999
  ℹ  09:52:32|stratum |  Spinning up miners...
  ℹ  09:52:32|cuda-0  |  No work. Pause for 3 s.
  ℹ  09:52:32|cuda-1  |  No work. Pause for 3 s.
  ℹ  09:52:32|cuda-2  |  No work. Pause for 3 s.
  ℹ  09:52:32|cuda-3  |  No work. Pause for 3 s.
  ℹ  09:52:32|stratum |  New pool difficulty:  10.0000 gigahashes 
  ℹ  09:52:32|stratum |  Received new job #20c5fd09… from eth-eu1.nanopool.org
  ℹ  09:52:35|cuda-0  |  Initialising miner 0
  ℹ  09:52:35|cuda-1  |  Initialising miner 1
  ℹ  09:52:35|cuda-2  |  Initialising miner 2
  ℹ  09:52:35|cuda-3  |  Initialising miner 3
 cu  09:52:37|cuda-0  |  Using device: GeForce GTX 1060 6GB  (Compute 6.1)
 cu  09:52:37|cuda-0  |  Set Device to current
 cu  09:52:37|cuda-0  |  Resetting device

**Comment by stralex7** [comment]
./ethminer -RH -HWMON --api-port 8081 --farm-recheck 200 -U -P stratum+tcp://0x111111111111111111111111111111.rig01@eu1.ethermine.org:4444
Segmentation fault (core dumped)

**Comment by jean-m-cyr** [comment]
Are you building from master HEAD code?

**Comment by jean-m-cyr** [comment]
jcyr@miner0:~$ ethminer -RH -HWMON --api-port 8081 --farm-recheck 200 -U -P stratum+tcp://${ETHWALLET}.${HOSTNAME}@eu1.ethermine.org:4444
  m  11:38:36|ethminer|  ethminer version 0.15.0.dev0
  m  11:38:36|ethminer|  Build: linux / release +git. b9dd182
 cu  11:38:37|ethminer|  Using grid size 8192 , block size 128
  m  11:38:37|ethminer|  not-connected
  ℹ  11:38:37|stratum |  Connected to eu1.ethermine.org:4444
  ℹ  11:38:37|stratum |  Spinning up miners...
  ℹ  11:38:37|cuda-0  |  No work. Pause for 3 s.
  ℹ  11:38:37|cuda-1  |  No work. Pause for 3 s.
  ℹ  11:38:37|cuda-2  |  No work. Pause for 3 s.
  ℹ  11:38:37|cuda-3  |  No work. Pause for 3 s.
  ℹ  11:38:37|stratum |  Subscribed to stratum server
  ℹ  11:38:37|stratum |  Authorized worker 0xf14B675F13fCD5E2fED55c8E3EEd2c1a954CC401.miner0
  ℹ  11:38:37|stratum |  New pool difficulty:  4.0000 gigahashes 
  ℹ  11:38:37|stratum |  Received new job #606d5434… from eu1.ethermine.org
  ℹ  11:38:40|cuda-0  |  Initialising miner 0
  ℹ  11:38:40|cuda-1  |  Initialising miner 1
  ℹ  11:38:40|cuda-2  |  Initialising miner 2
  ℹ  11:38:40|cuda-3  |  Initialising miner 3

**Comment by invidtiv** [comment]
Also found same bug with pre built, did a git pull and compiled, and it works ok.
