### ISSUE TITLE
0.14.0rc0 Windows not working on Nvidia

### ISSUE THREAD

**Issue by gituser-4** [ethereum-mining/ethminer#919]
I am trying to update to 0.14.0rc0 but it is not work!
Cmd window closed on start. On other rig amd work fine. What is this?

Windows 7 x64

Older virsions work very good...

ethminer.exe --exit -RH --farm-recheck 2000 -U -P stratum+tcp://User.Rig1:x@us-east.ethash-hub.miningpoolhub.com:17020 -P stratum+ssl://0x7sd5f252689cf893fdca9795b900bdf265606b09.FailRig1:x@eu1.ethermine.org:5555 

  m  11:13:38|main    |  ethminer version 0.14.0rc0
  m  11:13:38|main    |  Build: windows / release +git. 808ce96
  i  11:13:38|main    |  Found suitable OpenCL device [ GeForce GTX 1070 ] with 8589934592  bytes of GPU memory
 cu  11:13:39|main    |  Using grid size 8192 , block size 128

**Comment by l4Dream** [comment]
Same problem, Nvidia, Win10x64

**Comment by vatanuki** [comment]
its random bug, sometimes working, sometimes not, even using deprecated params like -O / -S

**Comment by jean-m-cyr** [comment]
This is weird!!! You invoked with -U (cuda), yet miner is saying it found suitable OpenCL device!

I believe @Hakkk2002 correctly referenced this issue in #920, and should be fixed in master.

**Comment by chfast** [comment]
Can you test RC3?

**Comment by gituser-4** [comment]
Yes, it is work.
