### ISSUE TITLE
Sporadic crashes since upgraded from 0.14.0.dev2 to 0.14.0.dev4

### ISSUE THREAD

**Issue by j1v** [ethereum-mining/ethminer#929]
Mar 21 08:23:02 rig01 kernel: [ 2345.850477] cl-12[1334]: segfault at 28 ip 00000000004dc6d3 sp 00007f26b2ffb8a0 error 4 in ethminer-0.14.0.dev4[400000+890000]

Mar 21 08:22:30 rig06 kernel: [925572.285154] cl-10[20144]: segfault at 28 ip 00000000004dc6d3 sp 00007f510f7fc8a0 error 4 in ethminer-0.14.0.dev4[400000+890000]

Mar 23 15:34:54 rig07 kernel: [1122728.343344] cl-8[9317]: segfault at 28 ip 00000000004dc6d3 sp 00007f9c037fc8a0 error 4 in ethminer-0.14.0.dev4[400000+890000]

Is there any other info I can capture, that could be usefull ?

**Comment by j1v** [comment]
It's happening on random rigs and cards, switching back to dev2 

[Sat Mar 24 20:37:12 2018] cl-6[1323]: segfault at 106000058 ip 00000000004dc36e sp 00007f4ed2ffb830 error 4 in ethminer-0.14.0.dev4[400000+890000]
[Sun Mar 25 00:29:49 2018] cl-11[5530]: segfault at 28 ip 00000000004dc6d3 sp 00007f6cb6ffb8a0 error 4 in ethminer-0.14.0.dev4[400000+890000]

**Comment by AndreaLanfranchi** [comment]
Should be fixed in 0.14rc and 0.15.
Eventually reopen new issue.
