### ISSUE TITLE
Windows 7 build failure

### ISSUE THREAD

**Issue by jonno85uk** [ethereum-mining/ethminer#93]
Using the prescribed commands 'cmake ..  ; cmake --build ." the compilation fails with 21 errors

[config.txt](https://github.com/ethereum-mining/ethminer/files/1113328/config.txt)
[error.txt](https://github.com/ethereum-mining/ethminer/files/1113317/error.txt)

It would appear jsonrpccpp-client.lib is a'Release' build yet ethminer is building in 'Debug'.

In visual-studio, building the 'Release' configuration works fine.

**Comment by jonno85uk** [comment]
Using 'cmake -DETH_BUILD_TYPE=Release' results in 

> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     ETH_BUILD_TYPE

**Comment by volpeandrew** [comment]
I had the same problem on Windows 10. Follow the advice in issue #63 
https://github.com/ethereum-mining/ethminer/issues/63

**Comment by jonno85uk** [comment]
I needed Debug because it's crashing due to memory access violations in the GPU. I edited a cmake file to get hunter to build dependencies in debug.

**Comment by chfast** [comment]
@jonno85uk can you send us your changes?

**Comment by DeadManWalkingTO** [comment]
My compile works fine [22 Warning(s) &  0 Error(s)]
````
cmake .. -G "Visual Studio 14 2015 Win64" -Tv140 -DETHASHCUDA=ON -DETHASHCL=OFF -DETHSTRATUM=ON -DAPICORE=OFF
````
````
cmake --build . --config Release
````
(cmake version 3.10.2)
