### ISSUE TITLE
Add documentation for multiple CUDA toolkit installations

### ISSUE THREAD

**Issue by nazerim** [ethereum-mining/ethminer#932]
CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-9.0 - set CUDA toolkit directory to /usr/local/cuda-9.0

**Comment by Spudz76** [comment]
That's basic how-to-use-CUDA stuff (in the CUDA docs about how to setup environment...) and does not belong documented in a CUDA-using client application unless there are special exceptions to the standard preparations.

There are several other envvars too that are necessary for compiling some other miner software (not this) but those are also documented in the CUDA docs...

**Comment by AndreaLanfranchi** [comment]
Please close issue.
