### ISSUE TITLE
Where to find help? Command -h immediately closes the miner...

### ISSUE THREAD

**Issue by miner56** [ethereum-mining/ethminer#938]
Where to find help? Command -h immediately closes the miner...
:-(

**Comment by dieuquocgia** [comment]
pause in .bat file

**Comment by AndreaLanfranchi** [comment]
Premise : a minimal knowledge about how a computer works (or better how your operating system works) is mandatory.

However ... .bat file is an "envelope" which encapsulates the command to start the miner with all the switches. If you want to learn and make some adjustments simply open a command window (cmd - the black one) and type ethminer.exe --help

**Comment by miner56** [comment]
Thank You! 
Спасибо !
