### ISSUE TITLE
connection error after an hour on 0.15.0dev0

### ISSUE THREAD

**Issue by invidtiv** [ethereum-mining/ethminer#940]
so i m getting, I think I saw an issue on here about the same error, can t find it now, so i m sorry about possible spaming.

```
  ℹ  13:29:48|cuda-9  |  Nonce 0x443c66e452725d84 submitted to eu1.ethermine.org
  ℹ  13:29:48|stratum |  **Accepted  in 35 ms.
  m  13:29:52|ethminer|  Speed 349.74 Mh/s    gpu/0 31.78 46C 100%   gpu/1 32.59 45C 100%   gpu/2 32.59 45C 100%   gpu/3 32.59 43C 100%   gpu/4 27.83 48C 100%   gpu/5 32.51 44C 100%   gpu/6 31.54 42C 100%   gpu/7 31.54 48C 100%   gpu/8 32.59 41C 100%   gpu/9 32.59 44C 100%   gpu/10 31.62 47C 100%   [A367+15:R0+0:F0] Time: 01:17
  ℹ  13:29:54|stratum |  Received new job #c14bfd8d… from eu1.ethermine.org
  m  13:29:57|ethminer|  Speed 349.20 Mh/s    gpu/0 31.72 46C 100%   gpu/1 32.60 45C 100%   gpu/2 32.51 45C 100%   gpu/3 32.51 43C 100%   gpu/4 27.79 48C 100%   gpu/5 32.60 44C 100%   gpu/6 31.46 42C 100%   gpu/7 31.46 48C 100%   gpu/8 32.51 41C 100%   gpu/9 32.51 44C 100%   gpu/10 31.55 47C 100%   [A367+15:R0+0:F0] Time: 01:17
  ℹ  13:29:59|cuda-3  |  Nonce 0x443c60e43d1db586 submitted to eu1.ethermine.org
  ✘  13:30:01|stratum |  No no response received in 2 seconds.
  ℹ  13:30:01|stratum |  Disconnected from eu1.ethermine.org
  ℹ  13:30:01|stratum |  Shutting down miners...
  m  13:30:02|ethminer|  not-connected
  m  13:30:07|ethminer|  not-connected
  m  13:30:12|ethminer|  not-connected
  ℹ  13:30:14|cuda-6  |  Nonce 0x443c63e4591a9476 submitted to eu1.ethermine.org
./miner.sh: line 41: 24508 Segmentation fault      (core dumped) ~/ethereum-mining/ethminer/build/ethminer/ethminer -RH -U -P stratum+tcp://"$MY_ADDRESS.$MY_RIG"@eu1.ethermine.org:4444 --api-port 3333 -HWMON
```

**Comment by invidtiv** [comment]
#936  so this is the same I think, altough I m not using ssl

**Comment by aleqx** [comment]
Does this exist on 0.14.rc2 as well?

**Comment by Olegatorius** [comment]
same issue - no ssl

**Comment by smurfy** [comment]
Will have a look, while i'm not a fan of the ``No no response received in 2 seconds.`` feature @jean-m-cyr introduced, i understand why its there.

The bug seems to be, that if the no response timeout is triggered, instead of trying to reconnect (which it strangely does in #936 ) it either crashes or causes an error in case of ssl because the socket connection is closed but the tls/ssl protocol is still active.

**Comment by jean-m-cyr** [comment]
You could make the time out longer, but the underlying issue remains the same.

**Comment by Tominator1st** [comment]
You might have gotten caught up in a scam, as I did. On Windows, key in control, alt, and delete keys at the same moment. You are looking for the "task manager" window. Once you find it, you might see as I did, that your computer is mining away. Congrats. We just got conned.

**Comment by AndreaLanfranchi** [comment]
Solved in 
* 0.14.rc7
* 0.15.dev6
