### ISSUE TITLE
Cannot use openCL device radeon 580

### ISSUE THREAD

**Issue by lendeezy** [ethereum-mining/ethminer#943]
http://i67.tinypic.com/2w2fwib.png

hi, i been having issues, the device manager is perfect, every card is powered, it sees the cards but wont mine them, i tried installing drivers, i installed opencl for amd support, i tried other drivers. any clue? much love and thanks for whoever fixs this issue. the board is B250 mining expert ASUS. the 3 cards that arent mining are section B cards and theyre hooked up and powered correctly. i have had 7 cards mining before, so when i added two more on, something just happen i dont really know either.

**Comment by AndreaLanfranchi** [comment]
You're posting image from Phoenix Miner which is NOT ethminer.
