### ISSUE TITLE
Question: Which version of ethminer has the best hashrate for CUDA GPUs?

### ISSUE THREAD

**Issue by DeadManWalkingTO** [ethereum-mining/ethminer#944]
Which version of ethminer has the best hashrate for CUDA GPUs?

I believe `ethminer 0.14.0.dev1` and `ethminer 0.13.0` has the best hashrate.

OS: Win10.
GPUs: GTX1060 and GTX1070.

I want ethminer's  version comparison, not OC settings comparison.

Thank you.

**Comment by abdullasharapov** [comment]
On Ubuntu most stable for me ethminer 0.13.0

**Comment by DeadManWalkingTO** [comment]
Stable 99.99% are both 'ethminer 0.14.0.dev1' and 'ethminer 0.13.0' (Win10).
I need the version of ethminer that has the best hashrate for CUDA GPUs. 
(It does not matter how old this version is.)

**Comment by vladgrand2** [comment]
I using 0.14.0 dev3 very stable and suitable for me right now for Cuda

**Comment by DeadManWalkingTO** [comment]
`0.14.0 dev3` not stable for me.

**Comment by aleqx** [comment]
After trying pretty much all versions (dev ad rc too, extensively, on a rather big farm), I keep going back to my 0.12.0 modded (*)

(*) my mod is the original 0.12.0 where I manually removed the software evaluations (little to no difference to hashrate) and patched the connection setup problem (no difference to hashrate). I was eager to try the 0.14 versions that use separate threads for connections, but they were all buggy and/or provably slower than 0.12.0
