### ISSUE TITLE
Question: How can I use parameter --exit?

### ISSUE THREAD

**Issue by abdullasharapov** [ethereum-mining/ethminer#946]
I read about this parameter, but not understand how can i use it for restarting miner or system. I use 14.rc1 and when miner fails --exit just only close miner. Is there any solution? Like in claymore for example.
PS I read about ETHminerWatchDog from @DeadManWalkingTO, but in the futures he write "* CUDA support removed because ethminer added `--exit` parameter to exit whenever an error occurred! "

**Comment by DeadManWalkingTO** [comment]
Example of --exit use:
```
ethminer -RH -U --exit -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.hardwaretest
```
After #757 (added --exit parameter to exit whenever an error occurred) you can use a watchdog.

Try [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) Windows7/8/10 [32/64] & Linux (Any Dist/Any Ver/Any Arch) (#735).

Check and feedback please.
Thank you!

**Comment by abed313** [comment]
Hello im having the same problem, however when used the example you mentioned i got (  invalid argument --exit )

**Comment by Hakkk2002** [comment]
--exit was added after #757 so if you are running an older version this argument is not valid.
