### ISSUE TITLE
segfault (miner continues but there are no accepted shares)

### ISSUE THREAD

**Issue by sandrodz** [ethereum-mining/ethminer#947]
Centos7/0.14.0rc1

dmesg shows:
```
cl-1[3657]: segfault at 239adc0 ip 000000000239adc0 sp 00007fcac77af788 error 15
stratum[3777]: segfault at 30c4dc0 ip 00000000030c4dc0 sp 00007fae85359b78 error 15
```

ethminer thinks all is good and continues mining with normal speed, but there are no shares on the pool, and pool thinks miner is offline.

```
./bin/ethminer -HWMON -RH -G \
               -P stratum+ssl://wallet.fujin@eu1.ethermine.org:5555 \
               --farm-recheck 200 \
               --cl-local-work 256 --cl-kernel 1 --cl-parallel-hash 2 \
               --exit
```

**Comment by Tominator1st** [comment]
You might have gotten caught up in a scam, as I did. On Windows, key in control, alt, and delete keys at the same moment. You are looking for the "task manager" window. Once you find it, you might see as I did, that your computer is mining away. Congrats. We just got conned.

**Comment by AndreaLanfranchi** [comment]
Please try latest 

Quite likely related to #936 (see last messages)

**Comment by AndreaLanfranchi** [comment]
No feed back.
Closing
