### ISSUE TITLE
Fix GCC pedantic warnings

### ISSUE THREAD

**Issue by XhmikosR** [ethereum-mining/ethminer#949]
I'm not on *nix, but I see these on Travis:

```
warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [-Wpedantic]
```

Would be nice if they were fixed so that it's easier to spot new warnings and errors.

**Comment by jean-m-cyr** [comment]
Which Travis? Regular or XCode?

**Comment by XhmikosR** [comment]
Regular one.

**Comment by unquietwiki** [comment]
#1045 related? [This discussion](https://stackoverflow.com/questions/2855121/what-is-the-purpose-of-using-pedantic-in-gcc-g-compiler) points to desired code-styling as triggering said warnings.

**Comment by XhmikosR** [comment]
I don't see the warnings anymore, so I'm gonna close this.
