### ISSUE TITLE
How would i remove this? QUESTION / HELP

### ISSUE THREAD

**Issue by trippyypanda** [ethereum-mining/ethminer#950]
Hi I am modifying this project for my own needs and i can not figure out where this is locate/ initialized.
I am trying to change the output of the miner to remove this part 

![screenshot 26](https://user-images.githubusercontent.com/30687357/38054976-13026354-329e-11e8-905a-0f97652a36ef.png)

It really bothering me and i can seem to find why/how its there.

**Comment by SnowLeopard71** [comment]
Look in `libdevcore/Log.cpp`.   The log lines are constructed using c_begin, c_sep1, c_sep2, and c_end.

**Comment by trippyypanda** [comment]
Thank  you!!!
