### ISSUE TITLE
-RH does not work

### ISSUE THREAD

**Issue by sbervinov** [ethereum-mining/ethminer#955]
ethminer-0.14.0rc1 and ethminer-0.13 do not report hashrate to nanopool when -RH option is added. It was checked tomorow.

I have used the following command line

ethminer.exe --farm-recheck 200 -U -RH -HWMON --api-port -3333 -S eth-eu1.nanopool.org:9999 -FS eth-eu2.nanopool.org:9999 -O 0x000067517a8eFD4104Ba30000F0B89692dAc0000/JAMES-MINER/user@gmail.com

**Comment by sbervinov** [comment]
Sorry, I' is not clear for me how farm recheck option works. This param is present in the help of nanopool how to use ethminer to mine with nanopool. So I should remove this option and check again? Now I'm using another miner and do not want to stop it to check. BTW. I also can see that ethminer has option to disable colors in console, which means that by default they are enabled, but for me colors are absent even without this option. I use Windows 7.

**Comment by megapearl** [comment]
I use nanopool too, you need to use -SP 1 to make -RH work, see ethminer --help
``
-SP, --stratum-protocol <n> (deprecated) Choose which stratum protocol to use:
        0: official stratum spec: ethpool, ethermine, coinotron, mph, nanopool (default)
        1: eth-proxy compatible: dwarfpool, f2pool, nanopool (required for hashrate reporting to work with nanopool)
        2: EthereumStratum/1.0.0: nicehash
``

**Comment by sbervinov** [comment]
Thank you

**Comment by megapearl** [comment]
I don't think you need it if you use stratum instead of getwork.
