### ISSUE TITLE
Keep getting disconnected from pool

### ISSUE THREAD

**Issue by luizfelipefb** [ethereum-mining/ethminer#956]
In the old version, 0.13.0, the command below worked just fine:

**ethminer.exe -U -SP 1 -S ubiq-us.maxhash.org:8008 -O 0xfF...6.pc**

but now in the new version 0.14.0rc2, none of the commands below worked with the new -P parameter, maybe it doesn't work anymore because I cant use the -SP parameter:

**ethminer.exe -U -P stratum+tcp://0xfF..6.pc@ubiq-us.maxhash.org:8008**
**ethminer.exe -U -P http://0xfF..6.pc@ubiq-us.maxhash.org:8008**

I keep getting disconnected from the pool, any ideas why?

![image](https://user-images.githubusercontent.com/3042811/38116090-fa7d9a82-3384-11e8-9372-c4da3cf3ab4f.png)

**Comment by Spudz76** [comment]
Copy your old SP param into the protocol header (it's in the new help/usage, but not this clearly explained...)

-SP 0 becomes stratum+tcp:
-SP 1 becomes stratum1+tcp:
-SP 2 becomes stratum2+tcp:

Most pools want something other than no password which may be a secondary problem (not familiar with maxhash)

So you probably want:
ethminer.exe -U -P stratum1+tcp://0xfF..6.pc:x@ubiq-us.maxhash.org:8008

I formerly used -SP 1 with dwarfpool and now use stratum1+tcp which works great.

**Comment by luizfelipefb** [comment]
stratum1+tcp did the job.

Thank you very much.

Maybe this should be somewhere in the help, or in a guide to help people to understand what is what. Or maybe it is and I just don't know.
