### ISSUE TITLE
Does --farm-recheck do anything?

### ISSUE THREAD

**Issue by thghdbs** [ethereum-mining/ethminer#96]
Does changing the --farm-recheck value do anything other than change the averaged hash rate reporting interval?

**Comment by derubm** [comment]
It should time the question to the (pool)server if there is a new work ready.

**Comment by thghdbs** [comment]
Does changing the setting really do that?

**Comment by derubm** [comment]
wireshark it ;)

**Comment by DLS-bau** [comment]
It doesn't do anything else when using a stratum connection to the pool. The stratum client can receive work independently, it won't be affected by the farm-recheck value.

**Comment by chfast** [comment]
Unfortunately, it does. Stratum implementation works as a proxy, but `--farm-recheck` decides how often the miner is checking for a new works in the proxy. Bad legacy design, but this is how it works currently.

**Comment by thghdbs** [comment]
So then, would it makes sense to lower this to "1" since the latency between the miner and proxy should be near zero?

**Comment by chfast** [comment]
Probably not. You will be killed by logs and maybe some other side effects. But you can try.
