### ISSUE TITLE
[0.14.0rc2] NiceHash mining... How to?

### ISSUE THREAD

**Issue by ZielarSRC** [ethereum-mining/ethminer#963]
What is the correct command syntax for running mining on nicehash?
As far as I know - NiceHash only supports stratum + tcp: //, but I am trying to connect with the following command:
`sudo ./ethminer -U -P stratum+tcp://MyWallet.MyWorker@daggerhashimoto.eu.nicehash.com:3353
`
it ends with a return: 
``
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<dev::BadHexCharacter>'
what():  BadHexCharacter
Aborted (core dumped)
``
For trying the other combinations I tried connecting via stratum2+tcp://  and to my surprise - the connection is going well and the mining process is seemingly correct, although most of the time in nicehash statistics you can not see the results of the worker (as if most of the time mining into space) in what I do not penetrate - preferring to avoid, however, not officially supported by NiceHash Protocol.

**Comment by AndreaLanfranchi** [comment]
Amend with this (note the 2 suffix for stratum)

`sudo ./ethminer -U -P stratum2+tcp://MyWallet.MyWorker@daggerhashimoto.eu.nicehash.com:3353`

**Comment by AndreaLanfranchi** [comment]
>(i see only Connecting to stratum... , and Connection failed, trying in 3.. 2.. 1.. and loop again)
This is related to #988

**Comment by AndreaLanfranchi** [comment]
To address this problem please use 0.14.0rc9 or 0.15.0dev7 and report.
Eventually open a new issue with detailed description of behavior.

**Comment by rgaufman** [comment]
With AMD this command works for me:

```
sudo ./ethminer -G -P stratum2+tcp://MyWallet.MyWorker@daggerhashimoto.eu.nicehash.com:3353
```
