### ISSUE TITLE
-P why?

### ISSUE THREAD

**Issue by R00dNet** [ethereum-mining/ethminer#964]
was there really a need to add this. or am i missing something?

it is not compatible with a lot of pools and I do not expect the pools to adjust anything for the sake of this miner.....

**Comment by ThetaProtocol** [comment]
its compatible with most just wait for proper syntax have mine working with ethermine ssl atm

**Comment by alexmannen** [comment]
for an idiot can you explain how to setup. previous was ethminer -g -s URL -o login
when i tried ethminer -g -p url -p login , it just crash on minergate

**Comment by ThetaProtocol** [comment]
-P stratum+ssl://address.Theta:x@us1.ethermine.org:5555 -U -RH is my current one. replace ssl with tcp for normal stratum

**Comment by Zohaib2018** [comment]
snd me link i want ethmine :(

**Comment by AndreaLanfranchi** [comment]
@alexmannen 

Syntax is (values in square brackets are optional).
Just replace with YOUR values

```
-P <scheme>://<youretheraddress>[.<workername>]@<poolhostname:poolconnectionport>

where <scheme> can be any of
stratum+ssl 
stratum+tcp 
stratum+tls 
stratum+tls12 
stratum1+ssl 
stratum1+tcp 
stratum1+tls 
stratum1+tls12 
stratum2+ssl 
stratum2+tcp 
stratum2+tls 
stratum2+tls12

```
Mostly you may want tu use stratum+tcp

**Comment by kkkrackpot** [comment]
New URL parameter is rather inconvenient when you have to deal with it in terminal over SSH...

**Comment by gituser-4** [comment]
And what is the analog of the command --stratum-ssl [<n>]  (deprecated) Use encryption to connect to stratum server.
        
       **2: Allow self-signed or invalid certs and any TLS version**

???

**Comment by gituser-4** [comment]
And what is the analog of the command --stratum-ssl [<n>]  (deprecated) 
        
       **2: Allow self-signed or invalid certs and any TLS version**

???

**Comment by Tominator1st** [comment]
You might have gotten caught up in a scam, as I did. On Windows, key in control, alt, and delete keys at the same moment. You are looking for the "task manager" window. Once you find it, you might see as I did, that your computer is mining away. Congrats. We just got conned.

**Comment by AndreaLanfranchi** [comment]
> And what is the analog of the command --stratum-ssl [] (deprecated)

What about -P stratum+ssl://....  ?
