### ISSUE TITLE
Fresh Install of Windows 10. Cant connect

### ISSUE THREAD

**Issue by MrPurns** [ethereum-mining/ethminer#965]
Hi all, i did a fresh install of Windows 10 and now i cant connect to ethminer.
Im running one 1080ti and one 970

Is there something wrong in my .bat file?

Ethminer is in "bin" on the desktop

cd /
cd bin
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --farm-recheck 200 --cuda -U -S eu1.ethermine.org:14444 -FS eu1.ethermine.org:4444 -O 0x396cf132980f1B79bFB1503589b45F4d38E64d27.GTX1080TIGTX970

And this is what Ethminer says:

  m  11:42:49|main    |  ethminer version 0.14.0.dev2
  m  11:42:49|main    |  Build: Windows/msvc / Release
  i  11:42:49|main    |  Found suitable OpenCL device [ GeForce GTX 1080 Ti ] with 11811160064  bytes of GPU memory
 cu  11:42:49|main    |  Using grid size 8192 , block size 128
  m  11:42:49|main    |  not-connected
  X  11:42:51|getwork |  Failed getting work!
  i  11:42:51|getwork |  Disconnected from http://127.0.0.1:8545
  X  11:42:51|getwork |  Retrying in 3 ...
  X  11:42:52|getwork |  Retrying in 2 ...
  X  11:42:53|getwork |  Retrying in 1 ...
  m  11:42:54|main    |  not-connected
  X  11:42:55|getwork |  Failed getting work!
  i  11:42:55|getwork |  Disconnected from http://127.0.0.1:8545
  X  11:42:55|getwork |  Retrying in 3 ...
  X  11:42:56|getwork |  Retrying in 2 ...
  X  11:42:57|getwork |  Retrying in 1 ...
  m  11:42:59|main    |  not-connected
  X  11:43:00|getwork |  Failed getting work!
  i  11:43:00|getwork |  Disconnected from http://127.0.0.1:8545
  X  11:43:00|getwork |  Retrying in 3 ...
  X  11:43:01|getwork |  Retrying in 2 ...
  X  11:43:02|getwork |  Retrying in 1 ...
  m  11:43:04|main    |  not-connected
  X  11:43:06|getwork |  Failed getting work!
  i  11:43:06|getwork |  Disconnected from http://127.0.0.1:8545
  X  11:43:06|getwork |  Retrying in 3 ...

**Comment by AndreaLanfranchi** [comment]
You apparently try to mine on ethermine pool but your log report you're mining in local mode.
For instance ... --cuda and -U mean the same. Try removing one or the other,

**Comment by AndreaLanfranchi** [comment]
Also ... you give your machine the name GTX1080TIGTX970 which make me assume you have two NVIDIA cards on board. However you'r not mining with CUDA but with OpenCL

**Comment by AndreaLanfranchi** [comment]
Addendum.
From what you say you have the bat file on your desktop and the miner itself in a desktop subfolder named "bin". But from what I see yur batch file invokes ethminer from a bin folder in the root drive

```
cd /                    <---- This changes to your C:\ root folder
cd bin                  <---- This enters in C:\bin (not C:\Users\<yourname>\Desktop\bin)

```

**Comment by AndreaLanfranchi** [comment]
Please report some logs.

**Comment by MrPurns** [comment]
What kind of logs do you want? @AndreaLanfranchi I really appreciate your help! 

@satori-q3a What do you mean by DNS-Fail? Do you have any suggestion on what kind of problem it might be? Thanks =)

**Comment by satori-q3a** [comment]
ping eu1.ethermine.org... to be sure you can access them and to be sure the ip address is translated correctly.
