### ISSUE TITLE
NO_COLOR how to use?

### ISSUE THREAD

**Issue by Rodriguevb** [ethereum-mining/ethminer#967]
export NO_COLOR=1
	./ethminer ...
or

	set NO_COLOR=1
	./ethminer ...
or
 
	NO_COLOR=1
	./ethminer ...

all run `ethminer` with color, so how to use`NO_COLOR` on linux ?

thanks!

**Comment by smurfy** [comment]
````
export NO_COLOR=1
./ethminer ...
````
