### ISSUE TITLE
Ethminer reports 166Mhs, pool reports 140 or less.

### ISSUE THREAD

**Issue by whotheff** [ethereum-mining/ethminer#971]
7 x 1060 GPU rig with identical cards with the same clocks. - 166mhs on ethminer, 140 or less on pool.
(sync similar cards is OFF!) Average hashrate for 4 days is 134Mhs

On the same pool i'm using another rig with 6 GPUs - different brands of 1060s with various clock settings
to match each card. Makes 125Mhs on Ethminer, pool shows 125-130.

Why is that?

**Comment by ddobreff** [comment]
Try lowering memory clock and wait 24h.

**Comment by whotheff** [comment]
in one hour the hashrate is even lower, also number of shares

**Comment by bmatthewshea** [comment]
Dunno, but make sure you're network connection is -up- 100%
It's all about shares you solve over a given amount of time. Most pools determine your hashrate like this. Not by a report from miner/etc. Are you seeing lots of stale shares on pool side?

**Comment by whotheff** [comment]
Both rigs use the same router.
Stale shares are 2-3 per day.

**Comment by whotheff** [comment]
replaced version 13 with 14RC3 displays incorrect calculations. This is how i understood card 4(5) is always submitting wrong shares regardless of the overclock. Any advices on what can cause this are welcome.

**Comment by SukharevPavel** [comment]
Did you change your --cl-local-work and --cl-global-work parameters?

**Comment by whotheff** [comment]
Initially -yes. I deleted them and left ETHminer stock. Absolutely no difference.

So far I tried moving the card on a seperate pc directly mounted on onboard PCI-E with Claymore.
Card works again with some messages about wrong shares but still submits correct ones from time to time.
Tried it with stock clock, underclock, overclock, undervolt, overvolt, tdp max, tdp min, custom curve,
replaced thermal grease, even updated to latest beta Vbios by Gigabyte.
Absolutely no difference!

Please suggest what can cause bad calculations!

**Comment by GordonHarley** [comment]
The local view shows how many hashes you're calculating, the pool shows a number based on your average over a certain time period.  Sometimes this is just pure luck of the draw on who submits a correct nonce first, and the rate shown on the pool is well below what the card is doing... other times the opposite happens.

**Comment by whotheff** [comment]
Hi Gordon, you are correct. But in this case it's one GPU which uses electricity without providing correct calculations. When I remove it from the system the 166mh/s go to 140 and then it is all normal. I suspect a defect GPU memory or memory controller :(  I hope it shows artifacts in games, otherwise It'll be hard to explain why it is not working for RMA.

**Comment by whotheff** [comment]
It was faulty card. It runs okay, but submits wrong shares 80% of the time. I guess it malfunctioned. So the hashrate submitted to pool is high, but the actual correct shares are lower than expected.
