### ISSUE TITLE
Make blue color a little lighter so that it looks good on Windows too

### ISSUE THREAD

**Issue by XhmikosR** [ethereum-mining/ethminer#973]
The color used for `[main]` doesn't look good on Windows. It's too dark. The blue color used for the `i` looks a little better.

**Comment by satori-q3a** [comment]
Maybe while we're at it, how about changing the gpus hash display line so that the particular gpu that generated an accept shows in another color... :)

**Comment by Hakkk2002** [comment]
Check this:
[https://blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors/](url)
The new color scheme is brighter but you may have to move to it manually.

**Comment by jean-m-cyr** [comment]
I get a 404 on that link!

**Comment by Hakkk2002** [comment]
Sorry, my fault... I didn't edit the url field.

**Comment by XhmikosR** [comment]
I'd either use the blue we use for the `i` letter or for the hashrate itself; both look better on Windows.

**Comment by JohnDeLaFlorida** [comment]
A workaround:
In Windows Command Prompt window, right click the top bar and choose Properties.
Select tab Colors and choose Black color (0,0,0) for Screen Text and Light Green (0,255,0) for Screen Background.  Click OK. Now you can read everything. Not very nice, but works.

**Comment by XhmikosR** [comment]
@AndreaLanfranchi : this is still a valid request.

**Comment by AndreaLanfranchi** [comment]
Sorry I thought the workaround from @JohnDeLaFlorida would help make the trick.

Are there still so many people really caring for colors ? :wow:

**Comment by XhmikosR** [comment]
It's just annoying that is all :)

Can't we just use the same blue color we use for the thread `i` icon?

**Comment by AndreaLanfranchi** [comment]
There are 2 flavours of blue actually used.

Blue (lighter) and Navy (darker).
Do you want to accomodate everything to blue ?

**Comment by XhmikosR** [comment]
![2018-08-26_19-07-59](https://user-images.githubusercontent.com/349621/44630273-6cfa4e80-a963-11e8-8037-8e3db6b3b369.jpg)

This one is more legible than the one `main`/`stratum` is using.

**Comment by AndreaLanfranchi** [comment]
@XhmikosR please check PR.

Was not that difficoult. ;)
