### ISSUE TITLE
Too low hashrate?

### ISSUE THREAD

**Issue by BIG1** [ethereum-mining/ethminer#977]
ethminer gives me about 360 mh/s.
claymore gives me about 405 mh/s
Using the same pool (daggerhashimoto)

Issue?

**Comment by tonyaik** [comment]
Tweaking your --cl-global-work and --cl-local-work will help you get you effective hashrate (at the pool) to the same levels with ethminer as with claymores.
What GPUs are you using?

**Comment by tonyaik** [comment]
I'm using these values on my Nitro+ 580 8GB
--cl-local-work 64 --cl-global-work 36864
It produces the most stable hashrate.

**Comment by BIG1** [comment]
Thanks. will try those settings.
Currently installed newest ethminer rc3.

It seems like the -SP is deprecated. How to use it different?

ethminer.exe -SP 2 -G -S daggerhashimoto.eu.nicehash.com:3353 -O WALLET

**Comment by BIG1** [comment]
--cl-local-work 64 --cl-global-work 36864 gave me 378 mh/s. Still 27 more to go :)

**Comment by tonyaik** [comment]
Maybe you need to tweak a bit more for your 570s.

Also. Please discard the hashrate in the client, compare 24hr runs on the pool instead. Claymores numbers are way inflated in the client.

**Comment by BIG1** [comment]
Ok. thanks. Will try.
What does local-work and global-work means? Highter number more stress on gpu?

**Comment by BIG1** [comment]
Will read it.
Ethminer suddenly stopped mining. No errors were shows in the command window. Closed the window and started mining again.
39 gpu gave me about 0.00498 - 0.00503 BTC every 24 hour with claymore on nicehash. I am curious how much ethminer produce.

**Comment by jean-m-cyr** [comment]
The thing that most don't understand is that for Ethminer the global work size parameter is a misnomer! It is actually a multiplier, which multiplied by the local work size (work group size) gives the actual global work size.

The global work size is the number of hashes you want the GPU to calculate in one pass. By increasing the multiplier you give the GPU's hardware dispatcher more work to choose from an a better chance at maximizing the use of internal resources. This results in better hash rate. But there's a down size!

The more hashes you ask for in 1 pass, the longer it takes to calculate. The longer it takes the longer the average job switch time will be, as well as the frequency at which the host can check for found shares. The end result is increased stale rate.

Below are a couple of graphs showing hash rate vs. share delay time on a AMD 480.

![snap1](https://user-images.githubusercontent.com/3529253/38367378-7b2362ea-38b0-11e8-8381-87a47149ec83.png)
![snap2](https://user-images.githubusercontent.com/3529253/38367382-7ebfb7e6-38b0-11e8-8922-bb259c3274a9.png)

**Comment by BIG1** [comment]
Thank u jean.
What settings would u recommend for 570 8gb?
Currently trying with local-work 128 and global-work 8192 (gives the same as local-work 64 and global 4096)

**Comment by jean-m-cyr** [comment]
I don't recommend anything. Only pointing out the trade-offs.

I would think that for current gen AMD GPU a local work size of 64 would be a natural fit.

**Comment by BIG1** [comment]
kernel 1 only gives 26.x mh/s. (default local-work and global work)

**Comment by jean-m-cyr** [comment]
For best results with kernel 1
local work 256,  global work 8192,  threads 2

**Comment by BIG1** [comment]
Will try.
256 and 8192 (if I remember etminer -help correct).
Will try with threads 2

**Comment by Xeroeth** [comment]
Also try ver 13, 14 is crashing on me way to often and have problems with getting back to work after network loss.

**Comment by tribalpixel** [comment]
for me, the best hashrate is with 
`--cl-local-work 256 --cl-global-work 65536 --cl-kernel 1 --cl-parallel-hash 2`

on RX570/580 4GB/8GB
