### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Zelwood3** [ethereum-mining/ethminer#979]
I am having issues mining with ethminer
I can not get past JSONRPC ADMIN SESSION KEY

**Comment by Zelwood3** [comment]
Is there another step I am missing to start DAG

**Comment by AndreaLanfranchi** [comment]
Post full command line with parameters **AND** sample of output log.

**Comment by Zelwood3** [comment]
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

eth.exe  -G -S http://140.82.40.165:8080/0x31ca6D77Eab998F7508EB0a18a0a8De8fd36B35e 
pause

**Comment by Zelwood3** [comment]
C:\Users\elwoo\OneDrive\Desktop\SL8Miner>setx GPU_FORCE_64BIT_PTR 0

SUCCESS: Specified value was saved.

C:\Users\elwoo\OneDrive\Desktop\SL8Miner>setx GPU_MAX_HEAP_SIZE 100

SUCCESS: Specified value was saved.

C:\Users\elwoo\OneDrive\Desktop\SL8Miner>setx GPU_USE_SYNC_OBJECTS 1

SUCCESS: Specified value was saved.

C:\Users\elwoo\OneDrive\Desktop\SL8Miner>setx GPU_MAX_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\Users\elwoo\OneDrive\Desktop\SL8Miner>setx GPU_SINGLE_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\Users\elwoo\OneDrive\Desktop\SL8Miner>eth.exe  -G -S http://140.82.40.165:8080/0x31cc6D77Eab998F7508EB0a18a7a8De8fd36B35e
cpp-ethereum, a C++ Ethereum client
Found suitable OpenCL device [Ellesmere] with 4294967296 bytes of GPU memory
cpp-ethereum 1.2.7
  By cpp-ethereum contributors, (c) 2013-2016.
  See the README for contributors and credits.
Transaction Signer: XE417DBK1579V1PQ8URDXLUMGWS9PKKMPPX (00000000-0000-0000-0000-000000000000 - 3f17f196)
Mining Beneficiary: XE41119MDZQTI4PY05XXTIZ8HW02PLQAUK (7bb3ac10-a967-8cd0-d674-d2c53b1cfc38 - 003f051d)
Foundation: XE55PXQKKK4B9BYPBGT1XCYW6R5ELFAT6EM (00000000-0000-0000-0000-000000000000 - de0b2956)
  i  15:54:41.905|p2p  UPnP device: http://192.168.1.12:41251/upnp/dev/a065ee5c-4585-acff-ffff-ffff83f93222/desc [st: upnp:rootdevice ]
Node ID: enode://149832f92ea9ac6310bdb0672356523a935c4683464101e84154610b87fa1bd0f696608bce222c5e24ea42274d69cfecc9ba2f1c9714e0d2213978003169a706@0.0.0.0:0
JSONRPC Admin Session Key:

**Comment by Zelwood3** [comment]
That's my bat file
And that's everything on cmd that shows up don't Kno how to view log I've only used claymore

**Comment by Zelwood3** [comment]
It's a test wallet so doesn't matter

**Comment by AndreaLanfranchi** [comment]
This **IS NOT** ethminer.
You're using cpp-ethereum which has nothing to do with this project.

Please close issue.
