### ISSUE TITLE
result == target is ignored in OpenCL miner

### ISSUE THREAD

**Issue by rufus210** [ethereum-mining/ethminer#980]
From the OpenCL miner:

    if (as_ulong(as_uchar8(state[0]).s76543210) < target)
    {
        uint slot = min(MAX_OUTPUTS, atomic_inc(&g_output[0]) + 1);
        g_output[slot] = gid;
    }

From the spec:

    while hashimoto_full(full_size, dataset, header, nonce) > target:
        nonce = (nonce + 1) % 2**64`

So a result that == is valid, but the OpenCL miner will ignore it.  The CUDA miner handles this properly.

**Comment by rhlug** [comment]
How big of a deal is this?  What % of results are potentially == target.
