### ISSUE TITLE
Failed getting work!

### ISSUE THREAD

**Issue by zheng-bin** [ethereum-mining/ethminer#981]
* I running the ethereum, it is ok.
```
  ℹ  11:17:18|getwork |  zheng p_client->eth_getWork +
  ℹ  11:17:18|getwork |  zheng eth_getWork p = null
  ℹ  11:17:18|getwork |  zheng eth_getWork result = [
	"0x9242a6ecaf0d5b2360d8fb89eda64db1f3842229c1322b29fd5e7eb0b2eb0692",
	"0x0000000000000000000000000000000000000000000000000000000000000000",
	"0x0000000040080100200400801002004008010020040080100200400801002004"
```
* The I running another program based on ethereum modification, it always failed getting work.
I think the problem is there:
```
Json::Value result = this->client->CallMethod("eth_getWork",p);
```
```
  ℹ  12:50:18|getwork |  zheng EthGetworkClient::workLoop 0 1
  ℹ  12:50:18|getwork |  zheng p_client->eth_getWork +
  ℹ  12:50:18|getwork |  zheng eth_getWork p = null
  ✘  12:50:18|getwork |  Failed getting work!
  ℹ  12:50:18|getwork |  Disconnected from 127.0.0.1
  ℹ  12:50:18|getwork |  Retrying in 3 ... 
  ℹ  12:50:19|getwork |  Retrying in 2 ... 
  ℹ  12:50:20|getwork |  Retrying in 1 ... 
  ℹ  12:50:22|getwork |  zheng EthGetworkClient::workLoop 0 1
  ℹ  12:50:22|getwork |  zheng p_client->eth_getWork +
  ℹ  12:50:22|getwork |  zheng eth_getWork p = null
  ✘  12:50:22|getwork |  Failed getting work!

```
Can you help me?

**Comment by zheng-bin** [comment]
'''
  ℹ  13:57:11|getwork |  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32001 : The response is invalid:  {
   "id" : 1,
   "jsonrpc" : "3.0",
   "result" : [
      "0xe0eaaed30b6d7a8546a03c01f9c45865717ece0a5aedd18ee0329324d5bb4989",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x00007db94cae1b0f944b317f187137455528ce5f82566a7b7ab3cda757e71770"
   ]
}
'''

**Comment by zheng-bin** [comment]
I modify the code:
```
+                try{
+                    v=p_client->eth_getWork();
+                }
+                catch (jsonrpc::JsonRpcException const& _e){
+                    cwarn << "Failed getting frist work!";
+                    p=boost::diagnostic_information(_e);
+                }
+                cnote<<p.asString();
```
pop error:
```
std::exception::what: Exception -32001 : The response is invalid:  {
   "id" : 1,
   "jsonrpc" : "3.0",
   "result" : [
      "0xe10f0007f6209c5081fb5a50305e22b6410296161f2bb434d0cb3d05ef576d03",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x00007ea3bdb64ab294e6860f55d3f9130ba007ea3bdb64ab294e6860f55d3f90"
   ]
}
```
So I think the  following has problem,is it right?
```
Json::Value result = this->client->CallMethod("eth_getWork",p) 
...
private:
	jsonrpc::Client* client;
```

 

`  ℹ  13:57:11|getwork |  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32001 : The response is invalid:  {
   "id" : 1,
   "jsonrpc" : "3.0",
   "result" : [
      "0xe0eaaed30b6d7a8546a03c01f9c45865717ece0a5aedd18ee0329324d5bb4989",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x00007db94cae1b0f944b317f187137455528ce5f82566a7b7ab3cda757e71770"
   ]
}`

**Comment by Tominator1st** [comment]
You might have gotten caught up in a scam, as I did. On Windows, key in control, alt, and delete keys at the same moment. You are looking for the "task manager" window. Once you find it, you might see as I did, that your computer is mining away. Congrats. We just got conned.

**Comment by AndreaLanfranchi** [comment]
The response is not valid as it reports "jsonrpc" : "3.0" (it should be "2.0")
