### ISSUE TITLE
Log formatting issue

### ISSUE THREAD

**Issue by Teressss** [ethereum-mining/ethminer#982]
Hi, can someone explain to me, why is ethminer log output looking so weird with lots of strange characters? I tried to use rsyslog and syslog-ng to send logs to my logserver, but on both the output is crippled:

m  [35m12:32:17[0m[30m|[34methminer[0m[30m|[36m[0m  Speed [1;36m152.65[0m Mh/s    gpu/0 [36m25.22[0m [36m51C 56% [0m  gpu/1 [36m25.66[0m [36m51C 57% [0m  gpu/2 [36m25.83[0m [36m49C 55% [0m  gpu/3 [36m25.31[0m [36m52C 57% [0m  gpu/4 [36m25.75[0m [36m51C 57% [0m  gpu/5 [36m24.87[0m [36m48C 53% [0m  [A552+3:R0+0:F0] Time: 10:45[0m
![screen shot 2018-04-06 at 12 34 01](https://user-images.githubusercontent.com/37613557/38416974-d95794e4-3996-11e8-8d2a-3c1c9383efb2.png)

**Comment by AndreaLanfranchi** [comment]
Those are the escape sequences of colors.
If you want to disable coloring output just

```
export NO_COLORS=1
./ethminer ...

```
or on Windows

```
set NO_COLORS=1
./ethminer.exe ...

```

**Comment by Teressss** [comment]
I want colors in viewing live miner, but don't want these garbage characters in log.

**Comment by AndreaLanfranchi** [comment]
You can't ... as ethminer does not have a log option I assume you're redirecting output to log file.
So in your log file you have the exact same output you get on screen.

**Comment by Teressss** [comment]
ok, so I wanted to set the env var but without success :( On ubuntu. Maybe someone can tell me exactly when and exactly when what to write.

**Comment by Teressss** [comment]
I have over latest 20 years set up dozens of webservers, logserver, file servers... but never realized I need to be master linux super guru to run ethminer withour colors :(

**Comment by AndreaLanfranchi** [comment]
Sorry for my typo. It's NO_COLOR not NO_COLORS

export NO_COLOR=1

Anyway it's well depicted in help (ethminer --help) without any need to be a guru.

**Comment by Teressss** [comment]
I can't agree. First I checked ethminer help, but all it says is this:
Envionment variables:
     NO_COLOR - set to any value to disable color output. Unset to re-enable color output.

**Comment by AndreaLanfranchi** [comment]
> I have over latest 20 years set up dozens of webservers, logserver, file servers...

With such an expertise you should know what an environment variable is and how to set it.
And, as you have read the help, you should have been able to spot the typo.

**Comment by Teressss** [comment]
So again, after applying export NO_COLOR=1 ethminer is still in color = nothing changed.

**Comment by AndreaLanfranchi** [comment]
Post your launch file.

**Comment by Teressss** [comment]
--report-hashrate --api-port 3334 -HWMON --cuda -O 0xxxxxx -S eth-eu2.nanopool.org:9999 --stratum-failover eth-eu1.nanopool.org:9999 --stratum-protocol 1

**Comment by AndreaLanfranchi** [comment]
You should have this in a bash file.
Example of file named start.sh

```
#!/usr/bin/env bash
export NO_COLOR=1
./ethminer --cuda -P stratum1+tcp://<youretheraddress>@eth-eu2.nanopool.org:9999 -P stratum1+tcp://<youretheraddress>@eth-eu1.nanopool.org:9999 --report-hashrate 
```

**Comment by Teressss** [comment]
I have it in bash file, but still it is not working.

#!/usr/bin/env bash

export NO_COLOR=1
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_ALLOC_PERCENT=100

[[ ! -e ./ethminer.conf ]] && echo "No ethminer.conf, exiting" && exit 1

conf=`cat ./ethminer.conf | grep -v "^$" | grep -v "^#"`

#echo $conf outputs all in one line
echo $conf
./ethminer `echo $conf` 2>&1 | tee /var/log/miner/ethminer/ethminer.log

**Comment by AndreaLanfranchi** [comment]
Here is the problem

`./ethminer echo $conf 2>&1 | tee /var/log/miner/ethminer/ethminer.log`

the piping to tee opens a subshell which does not inherit the local environment variables.

Would suggest to amend your script as follows

```
#!/usr/bin/env bash

export NO_COLOR=1
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_ALLOC_PERCENT=100

[[ ! -e ./ethminer.conf ]] && echo "No ethminer.conf, exiting" && exit 1

conf=cat ./ethminer.conf | grep -v "^$" | grep -v "^#"

#echo $conf outputs all in one line
echo $conf
./ethminer $conf >> /var/log/miner/ethminer/ethminer.log 2>&1 </dev/null & tail -f /var/log/miner/ethminer/ethminer.log
```

**Comment by Teressss** [comment]
So after 3 reboots it is working now. I don't get why it wasn't working before

**Comment by AndreaLanfranchi** [comment]
> So after 3 reboots it is working now. I don't get why it wasn't working before

You probably added NO_COLORS as a permanent SHELL variable thus subshell piping is amended.
