### ISSUE TITLE
Problems on building

### ISSUE THREAD

**Issue by zypoi** [ethereum-mining/ethminer#985]
Something happened when I am trying to build the code on my computer following the steps of readme.

```
>-- [hunter] JSONCPP_ROOT: /home/zypoi/.hunter/_Base/59b2b88/0452b62/c20b399/Install (ver.: 1.8.0)
>-- [hunter] Cache HIT: jsoncpp
>-- [hunter] Cache info: /home/zypoi/.hunter/_Base/Cache/meta/0452b62/jsoncpp/1.8.0/40f7f34/ad44e31/d41f56c/da39a3e/da39a3e/cache.sha1
>
>[hunter ** INTERNAL **] Unknown error
>  code: 60
>  message: "Peer certificate cannot be authenticated with given CA certificates"
>[hunter ** INTERNAL **] [Directory:/home/zypoi/.hunter/_Base/Download/Hunter/0.19.213/59b2b88/Unpacked/cmake/projects/jsoncpp]
>
>------------------------------ WIKI -------------------------------
>   https://github.com/ruslo/hunter/wiki/error.internal
>-------------------------------------------------------------------
>
>CMake Error at /home/zypoi/.hunter/_Base/Download/Hunter/0.19.213/59b2b88/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
```

I think there is some problem on the authentication of CA certificate.

Is there any workarounds? Like build a jsoncpp by myself instead of hunter, and how to? Could anyone give me an instruction.

THX.

**Comment by zypoi** [comment]
By the way, I am in China so maybe the problem is caused by my network.
I can build the version 0.14.0rc3 on my AWS instance successfully but there is a segment fault on my rig.

**Comment by XhmikosR** [comment]
I don't think there's something we can do. Check out https://github.com/ruslo/hunter/issues?utf8=%E2%9C%93&q=is%3Aissue+Peer+certificate+cannot+be+authenticated+with+given+CA+certificates
