### ISSUE TITLE
Build not working since Hunter upgrade 

### ISSUE THREAD

**Issue by fsalle** [ethereum-mining/ethminer#986]
The PR introduced +include(defaults/HunterCacheServers) in CMakeLists.txt.
If you don't create the folder 'defaults' then an empty HunterCacheServers file manually, the build (cmake) fails with Ubuntu (16.04)

Thank you.

**Comment by chfast** [comment]
`git submodule update -init`.

**Comment by fsalle** [comment]
It works :-)
Sorry for the noise.
