### ISSUE TITLE
error 6050

### ISSUE THREAD

**Issue by alexandrecs89** [ethereum-mining/ethminer#987]
Hello there!

I'm trying to use ethminer but when i run the .bat file i receive the error on the following screenshot
https://ibb.co/cVZOmc

I searched for it on google and i saw two solutions: installing cuda 9 and installing cuda 6.5... I've tryed to do so but on both cases cuda said he couldnt find suitable device.

My GPU is a NVIDIA GeForce 210

thank you for the help

**Comment by Tominator1st** [comment]
You might have gotten caught up in a scam, as I did. On Windows, key in control, alt, and delete keys at the same moment. You are looking for the "task manager" window. Once you find it, you might see as I did, that your computer is mining away. Congrats. We just got conned.
