### ISSUE TITLE
Guide?

### ISSUE THREAD

**Issue by vladimirkrstic** [ethereum-mining/ethminer#99]
Can someone write noob friendly guide? 

I create .bat file with `ethminer.exe -U -S pool wallet.worker` but it fails to load.

edit: would be nice to have README text file with commands instead of using command line for that.

**Comment by LinuxDonald** [comment]
For nanopool you could use this:

@echo off

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

ethminer.exe --farm-recheck 200 -G -S eth-eu1.nanopool.org:9999 -O YOUR_ADDRESS.YOUR_WORKER/YOUR_EMAIL

**Comment by vladimirkrstic** [comment]
I've used -U instead of -G. OpenCL is not playing well with my rig, utilizing 100% CPU. I've also got 1070 GPUs. It's mining now, got a tiny boost in MH/s but nanopool for some reason isn't reporting hash rate. Miner is online, accepted shares are shown, effective hash rate is shown but no reported hash rate.

**Comment by LinuxDonald** [comment]
Yeah for me only the claymore miner shows hash rate. But this miner is closed source.

**Comment by vladimirkrstic** [comment]
Off topic: Sadly in lot of cases open source alternatives are just not good enough. I would love to use Linux, Gimp, Inkscape... but macOS, Windows, Illustrator, Photoshop... are by far superior for my needs. Same thing is in the mining world. GPUs just perform a lot better under Windows. Claymore performs better than Ethminer on almost all cards. Ethminer makes whole system unstable, starts slowly, hash rate varies a lot. I moved 2 1060 rigs to Ethminer because of a lot higher hash rate but will still keep 480 and 1070 rigs on Claymore. 

Back to the topic: it would be really nice to have .txt file with commands shipped with builds. Also settings templates for most common rigs and pools would make it more accessible which can result in higher usage, higher visibility, more feedback, more bug reports  and hopefully more developers involved into the project.

**Comment by chfast** [comment]
The missing reported hash rate a know issue for stratum protocol. Maybe it was never implemented or it has to be fixed. Separated bug report about this would be good start.

**Comment by orkblutt** [comment]
@LinuxDonald can you wireshark Claymore and take a look if it using stratum.
For myself I use ethminer with  -F http://eth1.nanopool.org:8888/YOUR_ETH_ADDRESS/WORKER-NAME/EMAIL
It's working fine and shows reported hashrate correctly

**Comment by jimmykl** [comment]
@chfast There is a open issue for that bug, first raised a couple of weeks ago: https://github.com/ethereum-mining/ethminer/issues/49

@vladimirkrstic Please add your details on that issue so devs can see how many people it is effecting

**Comment by focuspro** [comment]
Hi! pls help me connect to ethermine pool

**Comment by jimmykl** [comment]
@focuspro 

ethminer.exe --farm-recheck 2000 -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O <Your_Ethereum_Address>.<RigName>

Put whichever etherminer servers are closest to you in the -S and -FS (which is the fallback if the first doesn't work)

**Comment by jimmykl** [comment]
Hi @vladimirkrstic did you manage to get your bat file working? If you did could you please close this issue? Thanks!

**Comment by vladimirkrstic** [comment]
@jimmykl Yup. Sure.

**Comment by ovived** [comment]
so the farm recheck command is required if you want to see 'reported hashrate' on nanopool?

Thanks

**Comment by jakemelon** [comment]
Does anyone know how to stop one GPU from mining in Ethminer while the rest keep on mining?

**Comment by Simon0Harms** [comment]
@jakemelon 
I don't think this is possible.
I start two ethminer processes.
Then i can shut down on of them for example  when i want to play a game.

**Comment by polymath64** [comment]
You can write a simple .bat file with the lines:

ethminer.exe --help
pause

Place that in the same folder as ethminer.exe and run it.

**Comment by nurizal1980** [comment]
why use new ethminer 0.13.0rc1 and the hashrate for 580 reduce 2 mh ? from 29mh to 27mh

**Comment by IRFANALI-0101** [comment]
No Reported hashrate in Mix Blockchain however Calculated Hashrate is available.

**Comment by AndreaLanfranchi** [comment]
@IRFANALI-0101 
Reported hashrate is affected by two factors : 

1. You explicitly have to instruct ethminer to report it : use `-R` command line argument
2. Pool must handle it: not all pools do. Some pools do not implement the json method to collect it, some pools simply disregard the data.

`ethminer --help` is your friend.
