### ISSUE TITLE
Eth-proxy rigname how to

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ethereum-mining/ethminer#990]
Using -P http://host:port/rigname does not recognize rigname

**Comment by smurfy** [comment]
try with #983

**Comment by AndreaLanfranchi** [comment]
Already tried. Nothing to do.
Eth-proxy does not get the rigname

**Comment by AndreaLanfranchi** [comment]
Sorry I thought it was already merged

**Comment by smurfy** [comment]
try it, if it works, i'm happy to press the "merge" button ^^

**Comment by AndreaLanfranchi** [comment]
It does work.
Perfect
