### ISSUE TITLE
AMD HASHRATE DROPPED

### ISSUE THREAD

**Issue by mhakulit** [ethereum-mining/ethminer#991]
my rig started 1 month ago with a fix hashrate of 180/mh . but now after a month hashrate dropped up to 50 percent and return to normal after a few minutes, any held regarding my issues ?

6 asus strix RX580 8gb (Hynix)

**Comment by SnowLeopard71** [comment]
Could it be happening when the DAG changes?   If not, are you getting kernel or driver errors?

**Comment by tribalpixel** [comment]
Hello,
Could you provide more informations?
what command do you use to run ethminer?
what OS do you use (linux/win) ?
what temperature are you cards when full working?

maybe you didn't monitor your temp, and you burned the termic paste on your cards... so they stop mining when overheating... cooldown... overheat... etc... that can be a theorical explanation for you hashrate drop ;)

but without more infos, we can not help you more...

**Comment by K3ppy** [comment]
Hi, I have similar performance on my rx 580, win10, ethminer v15 dev (tried a few vers before it as well)

On claymore I got 29-30 mh but on ethminer around 24 mh
No errors, OpenCL 2.0 AMD-APP (2527.10), OpenCL kernel: Stable kernel, amd adrenalin 18 driver with gpu compute mode on

Usage
ethminer.exe --farm-recheck 200 -G -S eth-us-east1.nanopool.org:9999 -FS eth-us-west1.nanopool.org:9999 -O 0x000000000000000000000000000000000000000.worker1/xxxx@xmail.com --cl-local-work 256 --cl-global-work 32768 --opencl-device 1

My RX580 is modded with faster memory timings  and temps are fine.
PS. I dont really use claymore as this was just to test ethminer on my gtx 1070 rig works as expected.

**Comment by K3ppy** [comment]
Hmm thanks tried it and increased a bit to 25 mh, but thats not the weird part.. Since I have two RX580's I only selected one to mine with using --opencl-device 1.. BUT only when removing that parameter and using both cards I'm getting the 29-30 mh...
