### ISSUE TITLE
Problem while building

### ISSUE THREAD

**Issue by Tockra** [ethereum-mining/ethminer#992]
hi guys,

I followed the build instructions and have problems at the build process. 
I'll get errors and don't know why:

https://pastebin.com/MkWVzfyc

OS: Linux ppcMiner 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 20:00:40 UTC 2018 ppc64le ppc64le ppc64le GNU/Linux

You help is welcome ;)

T

**Comment by AndreaLanfranchi** [comment]
Please report result of

`gcc -v`

**Comment by Tockra** [comment]
titant@ppcMiner:/home/ttannert$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/powerpc64le-linux-gnu/5/lto-wrapper
Target: powerpc64le-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/IBM 5.4.0-6ubuntu1~16.04.9' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-ppc64el/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-ppc64el --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-ppc64el --with-arch-directory=ppc64le --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-secureplt --with-cpu=power8 --enable-targets=powerpcle-linux --disable-multilib --enable-multiarch --disable-werror --with-long-double-128 --enable-checking=release --build=powerpc64le-linux-gnu --host=powerpc64le-linux-gnu --target=powerpc64le-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu/IBM 5.4.0-6ubuntu1~16.04.9)

**Comment by XhmikosR** [comment]
I doubt PowerPPC is supported.

/CC @chfast

**Comment by chfast** [comment]
Big-endian architectures are not supported because of the broken ethash library, but I'm working on this.
Other endianness changes might be needed in other places.

Still there might be other issues related to other driver specific pieces of code. You can try building without hardware monitor.

What GPU do you plan to use there?

**Comment by Tockra** [comment]
@chfast 
How can I build without hardware monitor?

I want to use some Tesla P100-SXM2 on our university server.

**Comment by chfast** [comment]
It looks you cannot at the moment, unless you will make a change to build hwmon library conditionally.
