### ISSUE TITLE
ETH Mining Problems with AMD R7 360 - Problems from the [Windows 7]

### ISSUE THREAD

**Issue by RJBetancor** [ethereum-mining/ethminer#993]
I have an AMD R7 **360** of **2GB** with which I want to mine **ETH** from Ethermine, but when I start the .bat it closes giving me this error.

PD: I have only one GPU.
¿Could it be that the problem arises because of the Memory Allocation DAG?
![123](https://user-images.githubusercontent.com/38199723/38511336-4000ebb4-3bfe-11e8-85af-9b1398e2d1e4.png)
> Config in **.ba**t is:
![1234](https://user-images.githubusercontent.com/38199723/38511435-91d94a3a-3bfe-11e8-9dc7-08bd30cc2a39.png)

**Comment by AndreaLanfranchi** [comment]
Change your .bat to

`ethminer.exe -P stratum+ssl://<youretheraddress>.IAM@us1.ethermine.org:5555 `

**Comment by RJBetancor** [comment]
Thank you very much but...
Why should the 2GB GPUs not be used to mine **ETH**?
I already fail, it's the only thing I have, here in Venezuela it is impossible now to buy a GPU. here in a job we earn $ 5 per month and a GPU of 4 GB are for $ 200, I talk about buying a GPU here it would be talking about 3.3 years of work! God!

**Comment by AndreaLanfranchi** [comment]
I am sorry but the eth algorithm requires at least 3+ Gb
-----------

Sent from mobile. Apologies for brevity and typos.

In data 9 aprile 2018 23:13:32 RJBetancor <notifications@github.com> ha 
scritto:
Thank you very much but...
Why should the 2GB GPUs not be used to mine ETH?
I already fail, it's the only thing I have, here in Venezuela it is 
impossible now to buy a GPU. here in a job we earn $ 5 per month and a GPU 
of 4 GB are for $ 200, I talk about buying a GPU here it would be talking 
about 3.3 years of work! God!—

**Comment by tribalpixel** [comment]
hello,
maybe you can try to mine other coins with it, like Ubiq, Musicoin, Expanse
dag file are still under 2GB, and you can use ethminer ;)

[dag size for eth algo](https://investoon.com/tools/dag_size)
