### ISSUE TITLE
cuda   insufficient GPU memory.

### ISSUE THREAD

**Issue by oneook** [ethereum-mining/ethminer#994]
hi, my nvdia is GTX 960 (2G)

and run:
ethminer -U -SP 2  -S pools -O wallet

then
show error:
 CUDA device GeForce GTX 960  has insufficient GPU memory. 2096168960  bytes of memory found < 2659188352  bytes of memory required
Segmentation fault

so , i see memory out ..
how can i modify parameters?

Thanks,

**Comment by oneook** [comment]
Warning: -SP is deprecated. Use the -P parameter instead.
Warning: -S is deprecated. Use the -P parameter instead.
Warning: -O is deprecated. Use the -P parameter instead.
  m  18:36:27|ethminer|  ethminer version 0.15.0.dev0
  m  18:36:27|ethminer|  Build: linux / release +git. 6f3e6a8
 cu  18:36:27|ethminer|  Using grid size 8192 , block size 128
  m  18:36:27|ethminer|  not-connected
  ℹ  18:36:27|stratum |  Connected to xxx
  ℹ  18:36:27|stratum |  Spinning up miners...
  ℹ  18:36:27|cuda-0  |  No work. Pause for 3 s.
  ℹ  18:36:27|stratum |  Extranonce set to 4c25
  ℹ  18:36:27|stratum |  Subscribed to stratum server
  ℹ  18:36:27|stratum |  Authorized worker xxx
  ℹ  18:36:27|stratum |  Difficulty set to 0.5
  ℹ  18:36:27|stratum |  New pool difficulty:  2.1475 gigahashes 
  ℹ  18:36:27|stratum |  Received new job #1b698fc9… from etc.coinfoundry.org
  ℹ  18:36:30|cuda-0  |  Initialising miner 0
 cu  18:36:32|cuda-0  |  Using device: GeForce GTX 960  (Compute 5.2)
 cu  18:36:32|cuda-0  |  Set Device to current
 cu  18:36:32|cuda-0  |  CUDA device GeForce GTX 960  has insufficient GPU memory. 2096168960  bytes of memory found < 2659188352  bytes of memory required
Segmentation fault

**Comment by AndreaLanfranchi** [comment]
You cannot. 
2Gb are not enough for Ethereum as the DAG file is over 2.5 Gb.
And in a few weeks 3Gb will be out of games too.

You MUST have a 4Gb+ ram GPU.

**Comment by AndreaLanfranchi** [comment]
Please close issue

**Comment by oneook** [comment]
thanks again
