### ISSUE TITLE
Ethminer connected to node but not hashing

### ISSUE THREAD

**Issue by FromBandai** [ethereum-mining/ethminer#995]
I am using AMD gpus (rx580s) and when I launch ethminer with "--opencl-platform 1" it connected to the node but is showing 0.00MH/s. How can I fix this?

**Comment by AndreaLanfranchi** [comment]
Please post the full launch command (including parameters) and the first 30 seconds of logs.

**Comment by FromBandai** [comment]
C:\Program Files\ethminer-master\ethminer\bin>ethminer.exe --opencl-platform 1
Found suitable OpenCL device [Ellesmere] with 8589934592 bytes of GPU memory
  m  06:45:03|main  Getting work package...
  m  06:45:03|main  Got work package: #2142d07b
  m  06:45:04|main  Mining on PoWhash #2142d07b : 0.00MH/s [A0+0:R0+0:F0]
  m  06:45:04|main  Mining on PoWhash #2142d07b : 0.00MH/s [A0+0:R0+0:F0]
  m  06:45:05|main  Mining on PoWhash #2142d07b : 0.00MH/s [A0+0:R0+0:F0]
  m  06:45:06|main  Mining on PoWhash #2142d07b : 0.00MH/s [A0+0:R0+0:F0]
  m  06:45:06|main  Mining on PoWhash #2142d07b : 0.00MH/s [A0+0:R0+0:F0]
  m  06:45:07|main  Mining on PoWhash #2142d07b : 0.00MH/s [A0+0:R0+0:F0]
  m  06:45:07|main  Mining on PoWhash #2142d07b : 0.00MH/s [A0+0:R0+0:F0]
  m  06:45:08|main  Mining on PoWhash #2142d07b : 0.00MH/s [A0+0:R0+0:F0]
  m  06:45:08|main  Mining on PoWhash #2142d07b : 0.00MH/s [A0+0:R0+0:F0]

It repeats this until it gets a new work package then the POWhash# changes. Thats it.

**Comment by AndreaLanfranchi** [comment]
> ethminer.exe --opencl-platform 1

This is not the full launch parameter sequence.
Could you also report the result of this command ?

`ethminer.exe -V`

**Comment by FromBandai** [comment]
Microsoft Windows [Version 10.0.16299.334]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Matt's Mine>cd C:\Program Files\ethminer-master\ethminer\bin

C:\Program Files\ethminer-master\ethminer\bin>ethminer.exe -V
ethminer version 0.11.0
Build: Windows/msvc/Release

C:\Program Files\ethminer-master\ethminer\bin>ethminer.exe --opencl-platform 1
Found suitable OpenCL device [Ellesmere] with 8589934592 bytes of GPU memory
  m  07:27:49|main  Getting work package...
JSON-RPC problem. Probably couldn't connect. Retrying in 1...
  m  07:27:51|main  Getting work package...
  m  07:27:51|main  Got work package: #6dc2657e
  m  07:27:52|main  Mining on PoWhash #6dc2657e : 0.00MH/s [A0+0:R0+0:F0]
  m  07:27:52|main  Mining on PoWhash #6dc2657e : 0.00MH/s [A0+0:R0+0:F0]
  m  07:27:53|main  Mining on PoWhash #6dc2657e : 0.00MH/s [A0+0:R0+0:F0]
  m  07:27:53|main  Mining on PoWhash #6dc2657e : 0.00MH/s [A0+0:R0+0:F0]
  m  07:27:54|main  Mining on PoWhash #6dc2657e : 0.00MH/s [A0+0:R0+0:F0]
  m  07:27:54|main  Mining on PoWhash #6dc2657e : 0.00MH/s [A0+0:R0+0:F0]
  m  07:27:55|main  Mining on PoWhash #6dc2657e : 0.00MH/s [A0+0:R0+0:F0]
  m  07:27:55|main  Mining on PoWhash #6dc2657e : 0.00MH/s [A0+0:R0+0:F0]
  m  07:27:56|main  Mining on PoWhash #6dc2657e : 0.00MH/s [A0+0:R0+0:F0]
  m  07:27:56|main  Mining on PoWhash #6dc2657e : 0.00MH/s [A0+0:R0+0:F0]
  m  07:27:57|main  Mining on PoWhash #6dc2657e : 0.00MH/s [A0+0:R0+0:F0]

**Comment by AndreaLanfranchi** [comment]
You're on a very old ethminer release.
Pick a newer one.

**Comment by FromBandai** [comment]
I updated ethminer but now I am getting a different error regarding CUDA drivers. these shouldnt be required if I am only running AMD correct?

Microsoft Windows [Version 10.0.16299.334]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Matt's Mine>cd C:\Program Files\ethminer-master\ethminer\bin

C:\Program Files\ethminer-master\ethminer\bin>ethminer.exe -V
ethminer version 0.14.0rc4+git.3eaf0ec
Build: windows/release/msvc

C:\Program Files\ethminer-master\ethminer\bin>ethminer.exe --opencl-platform 1
  m  08:00:50|main    |  ethminer version 0.14.0rc4
  m  08:00:50|main    |  Build: windows / release +git. 3eaf0ec
  i  08:00:50|main    |  Found suitable OpenCL device [ Ellesmere ] with 8589934592  bytes of GPU memory
Error: No CUDA driver found

**Comment by FromBandai** [comment]
When i list devices, this is what i get:

Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[1] [0] Ellesmere
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] [1] Ellesmere
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] [2] Ellesmere
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] [3] Ellesmere
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

Listing CUDA devices.
FORMAT: [deviceID] deviceName
  X  08:31:20|main    |  CUDA error: No CUDA driver found

**Comment by AndreaLanfranchi** [comment]
You're missing a lot of parameters.

1) You're not saying which mode you want to mine on : CUDA or OpenCL ? 
2) You're not saying where is the node to connect to

How is it supposed to mine ?

You should have **at least** something like

`ethminer.exe --opencl --opencl-platform 1 -P http://<ipaddresstoyourprivategethnode>:<port>`

**Comment by FromBandai** [comment]
That may have done it. I incorrectly assumed it would default to these settings.  I used this and the machine turned itself off. I assume I can set verbosity lower to see if it is more stable?

Thank you very much for your assistance.

**Comment by AndreaLanfranchi** [comment]
If solved please close the issue

**Comment by SnowLeopard71** [comment]
If the machine shutdown when you launched ethminer with complete command line, it is likely there is not enough power to drive all 4 of your cards under load, or you may have defective PCIe riser that cannot deliver enough power.

**Comment by FromBandai** [comment]
I starting using it with just one gpu for now as a test and its working fine. Except in Geth/Node the hashrate is fluctuating between 0 and 28,000,000. Is there a way to ensure its constantly mining. I am thinking there is a refresh period when receiving updated blocks before the miner starts hashing again. Ethminer is showing no changes.

**Comment by SnowLeopard71** [comment]
So, you are mining locally (`PoWhash`) -- default ethminer behaviour of farm mode to http://127.0.0.1:8545.   
That means it is checking for new work using the default 500ms (`--farm-recheck` option default).  

You should try using a pool like `ethermine` or `nanopool` rather than solo mining as you are now.

**Comment by FromBandai** [comment]
I am mining on a private chain, trying to get a working model for how to use ethminer with a node hosted on the machine. Everything seems to be working great except the hashrate in the node keeps dropping off to 0 - nothing showing in Ethminer. Any idea what could be causing that?

**Comment by AndreaLanfranchi** [comment]
> constant while the hashrate in the node (like Geth) drops to 0.

Please ... which command in geth you use to see hashrate ?

**Comment by SnowLeopard71** [comment]
Sounds like `ethminer` is working exactly as it should.  I've never run it the way you are, but the parameter that might have an impact is `--farm-recheck` 
Maybe the node has a bug with reporting hashrate?   Even public stratum pools report huge fluctuations in momentary hashrate, but when averaged over longer periods like 24 hours, the pool's reported value nearly matches `ethminer` values.

**Comment by AndreaLanfranchi** [comment]
@SnowLeopard71 ... he is in a completely different situation.
He is mining a private chain with likely no transactions to mine.

**Comment by FromBandai** [comment]
@AndreaLanfranchi I use miner.getHashrate() to view hashrate for the node.

**Comment by AndreaLanfranchi** [comment]
You better read this : 
https://github.com/ethereum/go-ethereum/wiki/mining

**Note hashrate info is not available in geth when GPU mining. Check your hashrate with ethminer, miner.hashrate will always report 0.**

**Comment by FromBandai** [comment]
Well that makes perfect sense then. Thank you so much for your help!

**Comment by AndreaLanfranchi** [comment]
Please close the issue.
